### ISSUE TITLE
How do I use superagent from react-native?

### ISSUE THREAD

**Issue by gaearon** [facebook/react-native#10]
[Superagent](https://github.com/visionmedia/superagent) fails trying to `require()` what I presume to be Node modules, such as `tty`.

Is React Native supposed to be browserish or nodeish environment from third-party package point of view? Should React Native expose Node modules like `events`?

**Comment by lazywei** [comment]
This is still a problem, isn't it? Would RN packager plan to fix this? Thanks :+1:

**Comment by philipshurpik** [comment]
Hi! 
You can try 'superagent/lib/client' but you need to modify require statements at the top of file:
var Emitter = require('component-emitter');
var reduce = require('reduce-component');
Because React Native doesn't correctly handle 'browser' section in package.json.

Also you can try my fork that is work with React Native:
https://github.com/philipshurpik/superagent
It has some other little fixes... Mainly default content type fix - set "application/json" as default, because react native xhr request doesn't correctly handle it.

**Comment by amasad** [comment]
The packager now looks at the `browser` field. superagent should be usable once they publish a new version following this PR https://github.com/visionmedia/superagent/pull/621 which just makes it not depend on a `location` object on the global object.
