### ISSUE TITLE
[iOS] Error using component Text from ART

### ISSUE THREAD

**Issue by flaviotobi** [facebook/react-native#10003]
Hi there, i'm currently using react native ART module, and everything is ok except the Text component, but the bug is only happening in iOS, in android everything seems to work as expected.

When i try to use the Text component in iOS react trows an this error:
![simulator screen shot 20 sep 2016 17 19 55](https://cloud.githubusercontent.com/assets/13239857/18679192/76fc1ec4-7f56-11e6-93ca-057dbcb04d51.png)

And in Xcode console output's this:

2016-09-20 17:17:17.663 [error][tid:main][RCTConvert.m:57] Error setting property 'frame' of ARTText with tag #7: JSON value '<null>' of type NSNull cannot be converted to NSDictionary

Since react native ART doesn't have documentation, it's very possible that i'm not doing something right, but i already read the source code and nothing is working that i try.

  

### Additional Information

* React Native version:0.33.0
* Platform: iOS
* Operating System: macOS
* Xcode: 8.0

RnPlay is down so i'm gonna post the code here:
https://jpst.it/NAac
As soon as the RNplay is up, i will update this post and put the code there.

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of React Native.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #react-native](http://stackoverflow.com/questions/tagged/react-native)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

**Comment by flaviotobi** [comment]
http://stackoverflow.com/questions/39611050/error-using-component-text-from-art

**Comment by flaviotobi** [comment]
@hramos Hi there, i'm sorry but i don't understand why this issue was closed.
This is bug, i understand  that i may doing something wrong, but the same code that i use is working in android but not in iOS.
