### ISSUE TITLE
how LazyReactPackage work?

### ISSUE THREAD

**Issue by xujinyang** [facebook/react-native#10011]
in LazyReactPackage.java

   for (ModuleSpec holder : getNativeModules(reactContext)) {
      try {
        modules.add(holder.getProvider().get());
      } finally {
        Systrace.endSection(TRACE_TAG_REACT_JAVA_BRIDGE);
      }
    }

all modules create now，why see lazy creation of native modules？

**Comment by ide** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-4** [comment]
Hey @xujinyang and thanks for posting this! @ide tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
