### ISSUE TITLE
Wrapping the view around the content.

### ISSUE THREAD

**Issue by birat-bade** [facebook/react-native#10059]
I have a ListView  which displays the text data from the server. The text can be of any size. What I want to do is if the text is short I want the height of the view to also be short and if the text is long I want the height of the view to be long so that it wraps the content perfectly.I want the view to be dynamic is this possible.

**Comment by Kureev** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-4** [comment]
Hey @birat-bade and thanks for posting this! @Kureev tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
