### ISSUE TITLE
El Capitain Error: EACCES: permission denied, open '/Users/milinka/.babel.json'..

### ISSUE THREAD

**Issue by milinka** [facebook/react-native#10093]
## Hey there and thank you for using React Native!

React Native, as you've probably heard, is getting really popular and truth is we're getting a bit overwhelmed by the activity surrounding it. Before opening a new issue, make sure to carefully read the following guidelines.
- Is this something you can **debug and fix**? 
  Send a pull request! Bug fixes and documentation fixes are welcome.
- Have a **usage** question?
  We use GitHub Issues for bugs. Ask your usage question on Stack Overflow: http://stackoverflow.com/questions/tagged/react-native
- Have an idea for a **feature**? 
  Post the feature request on Product Pains, which has a voting system to surface important issues: https://productpains.com/product/react-native/

GitHub issues should only be used for bugs. Make sure these boxes are checked before submitting your issue:
- [x] You're using the latest release of React Native: https://github.com/facebook/react-native/releases
- [x] You've searched through existing issues: https://github.com/facebook/react-native/issues 
    Chances are that your issue has been reported or resolved before.
- [x] You have filled out the template below, or provided an equivalent amount of detail.
    Issues without sufficient information will be labeled 'Needs more information' and will be closed until there is enough information.

Describe your issue in as much detail as possible. Provide **screenshots** where appropriate. Provide a **minimal code snippet** / [rnplay](https://rnplay.org/) example that reproduces the bug, or include a list of detailed list of steps that reproduce the issue.

--- delete everything above this line before submitting your issue --- 
### Issue Description

Cannot "sudo react-native run-ios" .. new windows open by xcode and text:
Error: EACCES: permission denied, open '/Users/milinka/.babel.json'
### Steps to Reproduce / Code Snippets

login mac as default user
sudo npm install -g react-native-cli
sudo react-native init AwesomeProject
cd AwesomeProject
sudo react-native run-ios
#### Expected Results

Error: EACCES: permission denied, open '/Users/milinka/.babel.json'
### Additional Information
- React Native version: react-native-cli: 1.0.0
- Platform(s) (iOS, Android, or both?): iOS
- Operating System (macOS, Linux, or Windows?): macOS

**Comment by travoux** [comment]
+1

**Comment by TopNiz** [comment]
I've came past this by changing the owner of .babel.json
`sudo chown milinka:staff /Users/milinka/.babel.json`

**Comment by christopherdro** [comment]
@facebook-github-bot answered

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by rawatrob** [comment]
:) Go the same error and fixed it with below command
sudo chmod 777  /Users/{{-username-}}/.babel.json
or open new terminal hit below commnd
ls -al
check that file 
if you got then hit
sudo chmod  777 .babel.json

**Comment by GustavoMSevero** [comment]
Thank you @rawatrob ! It works for me.
