### ISSUE TITLE
Is this a bug of iOS 10 simulator or react-native ?

### ISSUE THREAD

**Issue by Hkmu** [facebook/react-native#10109]
![simulator screen shot 2016 9 26 5 42 57](https://cloud.githubusercontent.com/assets/3169251/18829912/0f93978e-8411-11e6-9924-77a2055c7357.png)

```
<Modal>
     <View>...</View>
</Modal>
```

The iPhone battery bar is on the top of React Native Modal component.

**Comment by rmevans9** [comment]
Can you change the background color of the modal? My guess is the entire status bar is visible its just white so the time blends in with the modal. I would suspect this isn't a bug at all as the default behavior in iOS is to have the status bar overlay the app. If you want it gone then I would recommend hiding it using the StatusBar component. http://facebook.github.io/react-native/releases/0.34/docs/statusbar.html#statusbar

**Comment by ide** [comment]
This is intentional -- the React Native modal is implemented by adding a new UIViewController to the existing UIView/UIViewController hierarchy, which is in a UIWindow that sits under the status bar. I believe this behavior is the same in iOS 8 and 9 as well.

If you want to show a modal above the status bar, either you should do what @rmevans9 says and simulate the effect by hiding the status bar, or write your own native component that adds a UIWindow above the status bar's.
