### ISSUE TITLE
PushNotificationIOS can not be used，error。 Ask for help

### ISSUE THREAD

**Issue by durongzhang** [facebook/react-native#10122]
I can not use the message push function, is not because I am not a member of the Apple Developer

![wechatimg1](https://cloud.githubusercontent.com/assets/15725537/18859351/d7b713f0-84a5-11e6-8a62-c9c51ea74c76.jpeg)

* React Native version: 0.34
* Platform(s) (iOS, Android, or both?): ios10 xcode8
* Operating System (macOS, Linux, or Windows?): macos

**Comment by durongzhang** [comment]
Also ‘Cannot call requestPermissions twice before the first has returned.’

**Comment by rmevans9** [comment]
Hey @durongzhang the first error is actually because you haven't setup your app for Push Notifications or you haven't refreshed your provisioning profiles on your computer since setting up Push Notifications in the Apple Developer portal.

ref: http://stackoverflow.com/questions/27324020/no-valid-aps-environment-entitlement-string-found-for-application-on-app-store

For the second I would have to see your code but it might be resolved by resolving the first issue.

Closing this for now since this isn't a React Native issue but just some configuration on the iOS app side. If you run into more issues with this I would recommend asking on Stack Overflow.

**Comment by rmevans9** [comment]
@facebook-github-bot answered
