### ISSUE TITLE
Babel plugin transform-builtin-extend

### ISSUE THREAD

**Issue by Zyphrax** [facebook/react-native#10152]
Would you consider adding the babel-plugin transform-builtin-extend?
https://github.com/loganfsmyth/babel-plugin-transform-builtin-extend

The plugin makes it easier to define custom arrays and errors etc.

ES6 defines an Error type, but unfortunately it cannot be extended.
With this plugin and [extendable-error-class](https://github.com/brillout/extendable-error-class) it becomes easy to write your own errors.

**Comment by lacker** [comment]
Ah thanks for reporting this! It's a huge pain to change babel plugins. I think instead we are going to try to ship ES5 like most libraries do instead of transpiling everything with one standard preset, so that would let you use your own babel plugins. FYI @cpojer who is dealing with this. But I am going to close this issue because the plan is to solve this with that other work in progress.
