### ISSUE TITLE
Equivalent dangerouslySetInnerHTML?

### ISSUE THREAD

**Issue by nick** [facebook/react-native#1016]
I'm having trouble using UTF-8 entities in `<Text>` elements. For example, the following will work as expected:

    <Text>&#174;</Text>

But this will not:

    var txt = '&#174;';
    return <Text>{txt}</Text>

I'm assuming it's because variables get escaped at some point - is there an equivalent `dangerouslySetInnerHTML` for Text components?

**Comment by nicklockwood** [comment]
We don't use HTML for rich text on the native side at all. I suspect (although I'm not 100% sure) that the reason the first example works is that the JSX parser converts the entity into the equivalent unicode character.

So to make the second example work, you should probably use JavaScript-style unicode escaping instead of XML/HTML-style escaping - i.e.

    var txt = '\u00AE';
    return <Text>{txt}</Text>

**Comment by ide** [comment]
I don't think there's an equivalent right now but two suggestions:
- could you use Unicode escapes directly \u00AE?
- or could you use https://www.npmjs.com/package/html-entities ?

**Comment by nick** [comment]
JS style unicode did the trick - thanks.

**Comment by sleekvick** [comment]
@nick Can you please share your solution...

**Comment by ericyang89** [comment]
I meet the same problem，any one have solution？
