### ISSUE TITLE
Just running react-native init projectName and get warn EPEERINVALID react-native@0.34.1 requires a peer of react@~15.3.1 but none was installed

### ISSUE THREAD

**Issue by denirachmadi** [facebook/react-native#10166]
attach NPM debug log.
[npm-debug.txt](https://github.com/facebook/react-native/files/500069/npm-debug.txt)

**Comment by RichardLindhout** [comment]
After first attempt with react-native init do npm install react on your projectName folder and then do react-native init projectName --verbose on the original folder

**Comment by dvestal** [comment]
Is there anything else that can be done for this issue? I have had the same problem for quite some time. When I manually install react as suggested the init process does not stop because it's looking for react, but it still hangs near the end of the process. When I hit Ctrl-c I see the message "Setting up new React Native app in <project dir>" and then it exits.

``` shell:
npm verb linkMans react-native@0.34.1
npm info lifecycle react-native@0.34.1~install: react-native@0.34.1
npm info lifecycle react-native@0.34.1~postinstall: react-native@0.34.1
npm verb unlock done using /Users/david/.npm/_locks/staging-9d951c97b033a491.lock for /Users/david/source/tests/AwesomeProject/node_modules/.staging
npm verb saving [ { name: 'react-native', spec: '0.34.1', save: 'dependencies' } ]
AwesomeProject@0.0.1 /Users/david/source/tests/AwesomeProject
└── react-native@0.34.1 

npm verb exit [ 0, true ]
npm info ok 
^CSetting up new React Native app in /Users/david/source/tests/AwesomeProject

```

The node_modules directory and package.json are present in the created AwesomeProject directory, but the react-native specific things are not there.
