### ISSUE TITLE
TextInput is not displaying the value react native

### ISSUE THREAD

**Issue by vikiesakki** [facebook/react-native#10163]
Hi in my componentWillMount i set my states like this
componentWillMount(){
        this.timeSheetData().then((timeSheetResponse)=>{
            this.setState({comments:timeSheetResponse.comments});
            this.setState({spentHours:parseInt(timeSheetResponse.hours)});
            alert(this.state.spentHours);
        });
       });
In my view

I have the TextInput like this. I can't display the value on the TextInput but
 i can display the value on Text i don't know why it's happening
<TextInput onChangeText={(spentHours) =>this.setState({spentHours})}
  value={this.state.spentHours} />

**Comment by rmevans9** [comment]
Hey @vikiesakki 

This is unrelated to your question but generally you would not do two setStates right in a row like that... you can combine them

`this.setState({
    comments: timeSheetResponse.comments,
    spentHours: parseInt(timeSheetResponse.hours)
});`

To your actual question: this type of question is generally suited better on Stack Overflow. The issue tracker here is meant to track bugs within React Native which I am going to guess this particular issue is not a bug. I would recommend posting this over on Stack Overflow. When you do I would recommend giving more code in the example as that will help get you a solution. 

Closing this since this isn't a bug in React Native

**Comment by rmevans9** [comment]
@facebook-github-bot stack-overflow

**Comment by dsibiski** [comment]
@vikiesakki Please use Stack Overflow for questions like these as @rmevans9 mentioned earlier.
