### ISSUE TITLE
Image.getSize with fresco provokes local Image rendering issues

### ISSUE THREAD

**Issue by maraujop** [facebook/react-native#10170]
## Issue Description

I've found out, the hard and ugly way, after many hours of debugging, that when you trigger `Image.getSize` at the same time you render an `Image` component with the same source you've requested in `getSize`, sometimes the image might render blank and others correctly. 

I also reported an issue when Image.getSize is called "concurrently" https://github.com/facebook/react-native/issues/10002

The ironic thing is that this problem only happens with local images, remote online images seem to do fine. 

Therefore I decided to compile React Native myself and try to figure out what is wrong with `ImageLoaderModule.getSize` (<a href="https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/modules/image/ImageLoaderModule.java#L73">here</a>). 

I tried replacing `CallerThreadExecutor` with `DefaultExecutroSupplier(1).forBackgroundTasks()` based on the executors information provided here http://frescolib.org/docs/datasources-datasubscribers.html but it is still having issues, and I also tried `UiThreadImmediateExecutorService.getInstance()` with same results, make sense as the callback is quite lightweight.

After adding some loggers in Android code. I've found that after some calls to `Image.getSize` with a local image, you start getting errors in `onFailureImpl`.

```
09-29 13:20:06.975 16173 17490 I ReactNativeJS: { [Error: Pool hard cap violation? Hard cap = 75497472 Used size = 24449572 Free size = 0 Request size = 51916800] framesToPop: 1, code: 'E_GET_SIZE_FAILURE' }
09-29 13:20:10.898 16173 17490 I ReactNativeJS: { [Error: Pool hard cap violation? Hard cap = 75497472 Used size = 24756772 Free size = 0 Request size = 51916800] framesToPop: 1, code:
09-29 13:20:11.361 16173 17490 I ReactNativeJS: { [Error: Pool hard cap violation? Hard cap = 75497472 Used size = 31246372 Free size = 0 Request size = 51916800] framesToPop: 1, code: 'E_GET_SIZE_FAILURE' }
09-29 13:20:11.427 16173 17490 I ReactNativeJS: { [Error: Pool hard cap violation? Hard cap = 75497472 Used size = 28001572 Free size = 0 Request size = 51916800] framesToPop: 1, code: 'E_GET_SIZE_FAILURE' }
content://media/external/images/media/13090 getSize with results width 3120 and height 4160
```

All the information I've found about `pool hard cap violation` leads to think there is a memory leak somewhere. The thing is that when I retry you can see the used size decreases and finally It succeeds, so apparently retries frees resources somehow. Maybe Image ends up getting not rendered because Fresco runs out of memory.

I'm not loading hundreds of images, just 5 images in a Gallery.
### Steps to Reproduce / Code Snippets

It's hard to provide a snippet to reproduce this, because you need a local image. But a component that renders an `Image` and calls `Image.getSize` in `componentWillMount`, that gets reloaded and unloaded 5 or 6 times should do it (scene push and pop).
#### Expected Results

Image should render correctly, `Image.getSize` should be reliable with local images.
### Additional Information
- React Native version: 0.34.0
- Platform: Android 6.0
- Operating System: macOS

This issue doesn't happen in an emulator, only happens in real devices. My guess is that emulator loads local images faster than a device. There seems to be some concurrency involved, so this makes it harder to reproduce. My nexus 5x fails way less times than my Moto G3.

**Comment by kosiakMD** [comment]
Have the same!

**Comment by EgaSetya** [comment]
Have the same issue, I'm on 0.36. Do you Find any workaround for this issue?

**Comment by nehalahmad** [comment]
Have the same issue on Android device but not on the simulator. I take photo and then use that image, Image.getSize throwing warning and screen is blank, its working fine for local images instead.

Any help would be highly appreciated.

Thanks in advance.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
