### ISSUE TITLE
Crash when hot reload JS with safari JSContext console open

### ISSUE THREAD

**Issue by seph14** [facebook/react-native#10195]
### Issue Description

On both simulator or real iOS devices, when having the JSContext console opening from Safari, 
if use cmd+R to reload javascript, the app will crash.
From the stack trace, it looks like 2 javascript environment instances have been created. 
This wasn't happening on xcode7 with react-native 0.33. 
Tested on a fresh installed react-native project with react-native init command. 
There's a chance where first time when you reload it doesn't crash but on a second refresh, it will 100% crash. 
### Steps to Reproduce / Code Snippets

Start a project, open the console from Safari, then reload.
#### Expected Results

Shouldn't crash. 
### Additional Information
- React Native version:0.34.1/0.34.0
- Platform(s) (iOS, Android, or both?): iOS
- Operating System (macOS, Linux, or Windows?): macOS 10.11.6, Xcode 8.0(8A218a), safari 10.0 (11602.1.50.0.10)

**Comment by zzimbler** [comment]
@seph14 have you found a work around or a solution to this yet? I experience the same issue with the exact same specs

**Comment by seph14** [comment]
@zzimbler not really. just don't forget closing the console window before you reload...

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
