### ISSUE TITLE
ReactNativeJS: Requiring unknown module "react-native" on release build

### ISSUE THREAD

**Issue by jarradh** [facebook/react-native#10196]
### Issue Description

In development React Native app has performed well and works great, we have started packaging our app ready for release only to find that while we can build successfully, and generate a signed app-release.apk just fine. It has a runtime error that suggests react-native module is missing?

```
10-01 20:57:57.028 20184 20224 E ReactNativeJS: Requiring unknown module "react-native".
10-01 20:57:57.035 20184 20225 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
10-01 20:57:57.035 20184 20225 E AndroidRuntime: Process: com.statusim, PID: 20184
10-01 20:57:57.035 20184 20225 E AndroidRuntime: Theme: themes:{}
10-01 20:57:57.035 20184 20225 E AndroidRuntime: com.facebook.react.common.JavascriptException: Requiring unknown module "react-native".
```

Before this error there is preamble that, when googling, suggested that proguard is interfering however `def enableProguardInReleaseBuilds = false`. 
### Steps to Reproduce / Code Snippets
1. Run `cd android && ./gradlew clean && ./gradlew assembleRelease`
   Output as follows:
   https://gist.github.com/jarradh/e913af53d2ca0b09d35052c274d27874
2. Run `adb install app/build/outputs/apk/app-release.apk`
3. Tap on App Icon
   Output from `adb logcat` as follows :
   https://gist.github.com/jarradh/c8a6ed962d9d30c0e96cd15d830dd66e
#### Expected Results

We expected the app to run untethered from the react packager and a debugging environment, ready for release.
### Additional Information
- React Native version: 0.34.1
- Platform(s) (iOS, Android, or both?): Android, i presume iOS also
- Operating System (macOS, Linux, or Windows?): macOS

**Comment by lauborges** [comment]
I have the same issue

**Comment by etamity** [comment]
I have same problem too
![simulator screen shot 3 oct 2016 21 42 00](https://cloud.githubusercontent.com/assets/3015181/19053300/3c587bd0-89b2-11e6-8781-e0b67783bf19.png)

**Comment by jarradh** [comment]
is that on a release build? I don't get to a red screen it literally crashes before then

**Comment by alekhurst** [comment]
I have this problem too generating a release build on Android. RN version 0.34.0, getting `com.facebook.react.common.JavascriptException: Requiring unknown module "react-native-location"`

**Comment by raphkr** [comment]
Hey,

I too am facing the same problem. Has there been any fix to this.

**Comment by efkan** [comment]
Most likely your problem and solution are not the same with mine. 

I've got the error because of using `fbjs/lib/invariant` function in my code.

Figuring it out took my 1 day because of the long package building time.

Good luck!

**Comment by codebymikey** [comment]
@alekhurst and @raphkr, the reason it fails on android releases is because the libraries in question have their `package.json` files referencing the ios versions explicitly as their [main](https://docs.npmjs.com/files/package.json#main) entry point.

react-native-location's [package.json file](https://github.com/timfpark/react-native-location/blob/b8cf94c/package.json#L18)

react-native-passcode-auth's [package.json file](https://github.com/naoufal/react-native-passcode-auth/blob/b9046b9/package.json#L8)

I think this can be solved in two ways:

1. Remove the `.ios.js` suffix so the packager picks up the correct `index.js` version. 
2. Create a simple `main.js` file to act as your main entry point, and then that requires the platform specific versions for you.

I do find it weird that this only occurs on android releases, and not development versions.

**Comment by hramos** [comment]
This issue has been inactive for a while. It's possible that the bug has been fixed since this issue was originally submitted, or perhaps it is not affecting a great amount of people, or a workaround has been provided. Either way, we're going to close this in order to allow the community to focus on more pressing issues.

If you strongly believe this issue should remain open, please provide a justification below.
