### ISSUE TITLE
Keyboard is dismissed for programmatic scroll calls on Android

### ISSUE THREAD

**Issue by bleonard** [facebook/react-native#10192]
### Issue Description

When programmatically messing with the scroll position of a scroll view via something like `scrollView.getScrollResponder().scrollResponderScrollNativeHandleToKeyboard()`, the keyboard is dismissed on Android.

This happens when the `keyboardDismissMode='on-drag'` because that's what it says to do in `_handleScroll`:

``` javascript
    if (Platform.OS === 'android') {
      if (this.props.keyboardDismissMode === 'on-drag') {
        dismissKeyboard();
      }
    }
```
### Steps to Reproduce / Code Snippets

``` javascript
  scrollTargetIntoFocus: function(component) {
    var reactNode = ReactNative.findNodeHandle(component);
    var scrollView = this.refs.scrollView;
    var responder = scrollView.getScrollResponder();
    responder.scrollResponderScrollNativeHandleToKeyboard(
      reactNode, 0, true
    );
  },
```
#### Expected Results

My impression is that the `_handleScroll` code was there to provide a behavior for a user gesture (dismissing the keyboard when moving finger on screen). I do not believe that should take effect when the scroll happens programatically. This does not happen when the same thing is done on iOS.

@mkonicek I wanted to get your thoughts.
### Additional Information
- React Native version: 0.33
- Platform(s) (iOS, Android, or both?): Android
- Operating System (macOS, Linux, or Windows?): macOS

**Comment by Feng999** [comment]
anything happened?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by llamaluvr** [comment]
I've confirmed this is still an issue on Expo 22 / RN 49. I'll be able to check it soon on Expo 24/ RN 51. I agree, on-drag behavior should only trigger on actual drags by the user, not programatic scrolls.

In our use case, we have a chat UI (GiftedChat-based) that should automatically scroll to the most recent message when the keyboard appears. I do this with ScrollView.scrollTo() on keyboardDidAppear event. Of course, since this generates a "drag", the keyboard goes away right after it appears. I should be able to move the ScrollView to the top when they keyboard is displayed without dismissing the keyboard.
