### ISSUE TITLE
[Critical]all await operation was blocked by previous await operation(android), does all await operations all execute in single thread in Android?

### ISSUE THREAD

**Issue by sopaco** [facebook/react-native#10203]
All await operation was blocked by previous await operation(android), does all await operations all execute in single thread in Android?
(PS: in ios there are no such problem)

**Comment by ide** [comment]
What is an await operation?

**Comment by sopaco** [comment]
@ide 
such as `await fetch(...)`
in fact I has this problem when I use the code-push for react native, when the code-push downloading the upgrade file, all `await` oprations was block until upgrade completed.And this problem only occurs on Android, on ios it works fine.

**Comment by ide** [comment]
Await statements don't block a thread. They only logically block the function they are in. There is a single thread but it's not blocked. Await statements give you cooperative multitasking so other await statements in your program are allowed to keep running.

If this isn't clear you should use promises instead of await, and if promises aren't clear then use callback functions. Then go back to async/await when you understand how the other parts work.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/criticalall-await-operation-was-blocked-by-previous-await-operationandroid-does-
