### ISSUE TITLE
React Native Getting Started Tutorial Broken 

### ISSUE THREAD

**Issue by mailtoharshit** [facebook/react-native#10208]
I followed all steps 

`npm install -g react-native-cli`

and then 

```
react-native init AwesomeProject
cd AwesomeProject
react-native run-ios

```

<img width="838" alt="screen shot 2016-10-02 at 11 43 35 am" src="https://cloud.githubusercontent.com/assets/453090/19022819/8294e5a2-8895-11e6-8339-b8262b4baad8.png">

**Comment by reneweb** [comment]
Have you searched for the error already? When I look for `cfbundleidentifier does not exist`, there are a few stack overflow posts and an issue about that at the top of the results.

see #7308

**Comment by cristim** [comment]
I also got errors while running the Getting Started on my Nexus5 Android device and I had to perform a number of things that were not documented in the tutorial in order to get it work.

I eventually fixed it following some suggestions from error messages and later with some more information from Stack Overflow, but as a new user I expect the getting started tutorial to be complete enough to work out of the box, and the fact that it fails gives new users a bad impression about the project.

**Comment by lacker** [comment]
@hramos revamped this getting started guide recently, which I believe should make this a lot better. For what it's worth, a number of these problems seem to be Android-specific rather than React-Native-specific. You might also want to try Exponent. Thanks for reporting these!

**Comment by hramos** [comment]
Duplicate of #14423
