### ISSUE TITLE
TextInput textAlign:right space issue

### ISSUE THREAD

**Issue by vgalkin** [facebook/react-native#10218]
### Issue Description

If use TextInput component with textAlign:'right' property, when typing space, it is not shown until entering another character (not space)
### Steps to Reproduce / Code Snippets

`
const styles = {
        textInput:{
               textAlign:'right',
               color:'#3599E0',
               padding:0
        }
}
`
`
render(){
        return (
                <TextInput style={styles.textInput} value={this.state.value}/>
        )
}
`
#### Expected Results

Show space in TextInput
### Additional Information
- React Native version: 0.34
- Platform(s) (iOS, Android, or both?): iOS
- Operating System (macOS, Linux, or Windows?): macOS

**Comment by satya164** [comment]
What do you mean by showing space? How will you see the space on the left if it's right aligned?

**Comment by vgalkin** [comment]
I mean, when you type space, this symbol is not showing at the end of the string, which is right-aligned

**Comment by madjam002** [comment]
@satya164 When a TextInput is aligned right and the user enters "Hello [lots of spaces here]", it looks exactly the same as if they enter "Hello" which is confusing:

![Imgur](http://i.imgur.com/uBjvtiT.png)

**Comment by baldurpan** [comment]
This is still an issue in RN 0.43.2

**Comment by junshengpierre** [comment]
Does anyone have a workaround for this?

**Comment by chrumchrum** [comment]
@junshengpierre have you found a solution to this problem ?

**Comment by junshengpierre** [comment]
@chrumchrum nope, not yet

**Comment by shergin** [comment]
This is common problem (or even expected behaviour) on iOS.
https://stackoverflow.com/questions/19569688/right-aligned-uitextfield-spacebar-does-not-advance-cursor-in-ios-7
Unfortunately, I am not aware of good enough solution... yet. But I will try to find one.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by sei0o** [comment]
This worked for me:
```javascript
render() {
  return (
    <Input style={{ textAlign: 'right' }} value={this.state.text} onChangeText={(text) => this.setState({text: this._replaceSpace(text)})} />
  )
}

// ....

_replaceSpace(str) {
  return str.replace(/\u0020/, '\u00a0')
}
```

It replaces `\u0020` (Space) with `\u0040` (Non-breaking space; `&nbsp;`).
Thanks to @shergin (and the question in stackoverflow)
