### ISSUE TITLE
[Android] Debug Build Will Run, Release Build Will Not

### ISSUE THREAD

**Issue by joncursi** [facebook/react-native#10257]
RN 0.34.1

Debug version of the android application runs perfectly fine:

```
react-native run-android
```

Production build will build successfully, but will not run ("Unfortunately, appName has stopped" modal):

```
react-native run-android --variant=release
```

I have made sure that ProGuard is turned off. Here are the errors reported by logcat:

```
10-05 14:13:46.102  5163  5179 E ReactNativeJS: Invalid regular expression: unmatched parentheses
10-05 14:13:46.242  5163  5179 E ReactNativeJS: Module AppRegistry is not a registered callable module (calling runApplication)
10-05 14:13:46.774  5163  5179 E ReactNativeJS: Module AppRegistry is not a registered callable module (calling unmountApplicationComponentAtRootTag)
```

The odd thing, is that I have searched for regular expressions in my codebase and haven't found any. I do not get these errors in logcat when running the debug version of the app. So I'm not sure why or where the production build is getting tripped up.

**Comment by akramin55** [comment]
I get the same issue, debug build works normally after build but the release build closes on opening it with the same error message ("Unfortunately, <app_name> has stopped.")

**Comment by mrnahidtalukder** [comment]
I have the same issue as well

**Comment by ccokme** [comment]
me too:(

**Comment by kwelch** [comment]
I have similar issue where it does not work from Android Studio but it works from the command line.

**Comment by Ethan0007** [comment]
Hi , can you please try my fix below:

react-native bundle --platform android --dev false --entry-file index.android.js  --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/

Then: react-native run-android --variant=release

#Hope will help.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by rajeshzmoke** [comment]
hi i have the same issue where the release build stops working when the app is opened

**Comment by hu8373551** [comment]
same issue 
react native 0.52.1

**Comment by Veronica1026** [comment]
same issue here!
SOS!

**Comment by armanbabai** [comment]
I have the same issue as well
