### ISSUE TITLE
Slider with minimumValue > 0 doesn't move

### ISSUE THREAD

**Issue by iKettles** [facebook/react-native#10253]
### Issue Description

Using the React Native Slider works fine with a minimum value of 0. With a minimum value above 0, the slider doesn't respect the value set and places the thumb to the beginning of the slider. This prevents the thumb from being moved.
### Steps to Reproduce / Code Snippets

With a minimum value of 0, this works and allows the thumb to be moved. With a value higher than 0 the thumb will be locked to the start of the slider.

```
import React, { 
  Component
} from 'react'

import {
  Slider,
  View
} from 'react-native';

export default class RangeSlider extends React.Component {
  constructor (props) {
    super(props)
  }

  render () {
    return (
      <View>
        <Slider 
          maximumValue={10}
          minimumValue={1} 
          stepValue={0.1} 
          value={4}
          />
      </View>
    )
  }
}
```
#### Expected Results

The thumb should be able to move with a minimum value above 0
### Additional Information
- React Native version: 0.34.1
- Platform(s) (iOS, Android, or both?): Android
- Operating System (macOS, Linux, or Windows?): macOS

**Comment by reneweb** [comment]
The problem is in `ReactSlider.java` when calculating the step value: https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/slider/ReactSlider.java#L94

What happens is that before the `maxValue` property gets set, the `minValue` one will get set and causes the `updateAll` method to be called. If at the same time the `step` is zero and we therefore calculate it, the `minValue` will be greater zero and the `maxValue` will be zero resulting in a negative `step` value.

To work around this you need to provide the `step` value yourself, which you are trying to, but the name is just `step` not `stepValue`.
So, this should work:
```
import React, { 
  Component
} from 'react'

import {
  Slider,
  View
} from 'react-native';

export default class RangeSlider extends React.Component {
  constructor (props) {
    super(props)
  }

  render () {
    return (
      <View>
        <Slider 
          maximumValue={10}
          minimumValue={1} 
          step={0.1} 
          value={4}
          />
      </View>
    )
  }
}
```

I will also add a pr to fix the issue when the step is indeed 0.
