### ISSUE TITLE
react-native bundle command not recognized

### ISSUE THREAD

**Issue by davidpfahler** [facebook/react-native#1027]
On [Running On Device](https://facebook.github.io/react-native/docs/runningondevice.html), section [Using offline bundle](https://facebook.github.io/react-native/docs/runningondevice.html#using-offline-bundle), it says:

> Run the `react-native bundle` command in terminal from the root directory of your app

Unfortunately, when I tried to bundle my react-native app in this way, but all I got was this:

```
$ react-native bundle
Command `bundle` unrecognized
Usage: react-native <command>

Commands:
  start: starts the webserver
  install: installs npm react components
```

I'm running react-native-cli@0.1.3 and my react-native is based on 0.4.0.

Please clarify what the proper way is to bundle your app for distribution. Thank you :)

**Comment by brentvatne** [comment]
@davidpfahler - it looks like this made it into the docs because it was included into the release - [see comment here](https://github.com/facebook/react-native/pull/851#issuecomment-96295179) - it is merged into master but still not on npm. Until then you can use the former approach: `curl 'http://localhost:8081/index.ios.bundle?dev=false&minify=true' -o iOS/main.jsbundle`

**Comment by davidpfahler** [comment]
@brentvatne Thank you very much for your swift response. This indeed works and helped me. However, is there any way we can either ship `react-native bundle` or update the documentation, so that other people don't run into the same issue?

**Comment by brentvatne** [comment]
@davidpfahler - this is live now in 0.4.1, we're tracking the issue of documentation sync in #1022 :smile: - if you have any ideas for how we can solve this problem they would be very welcome, thanks!
