### ISSUE TITLE
Required dispatch_sync to load constants for Orientation. This may lead to deadlocks

### ISSUE THREAD

**Issue by shirleyYing** [facebook/react-native#10312]
when I update RN from 0.30 to 0.34.1 I get this waring  
```
Required dispatch_sync to load constants for Orientation. This may lead to deadlocks
```
it not appears in 0.30

is it serious？

**Comment by cbrevik** [comment]
Another developer has reported the same warning for my native module: https://github.com/idehub/react-native-google-analytics-bridge/issues/70

It seems to have showed up in 0.33 and be related to the Native Module exporting constants.

The framework [loads the constants from native modules in `RCTModuleData ` `gatherConstants`](https://github.com/facebook/react-native/blob/cfae3e376d96653e5ad48e0d0398674a954d3637/React/Base/RCTModuleData.mm#L287). That method is used in [RCTBatchedBridge](https://github.com/facebook/react-native/blob/9981b8928d20416d1a3f3995b9f4d32ccf273ebd/React/Base/RCTBatchedBridge.m#L419), which has the following comment:
>    // Modules that need to be set up on the main thread cannot be initialized
      // lazily when required without doing a dispatch_sync to the main thread,
      // which can result in deadlock. To avoid this, we initialize all of these
      // modules on the main thread in parallel with loading the JS code, so
      // they will already be available before they are ever required.

I've also gotted this warning intermittently for other things like `RCTUIManager` and [CodePush](https://github.com/Microsoft/react-native-code-push).

Tagging @javache since he introduced this warning.

**Comment by javache** [comment]
This is a known issue with the current bridge initialisation. In practice, this won't lead to any issues with RN apps since the main thread is free, but in more complex integration scenarios this may result in issues, which is why I added this warning to chase it down.

**Comment by cbrevik** [comment]
Hm, and there isn't any way for me to implement `constantsToExport` in order to not get this error?

All I am really doing is:
```objective-c
NSString *staticTrackerId;

- (instancetype)init
{
    if ((self = [super init])) {
        ...
        staticTrackerId = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"GAITrackingId"];
        ...
    }
    return self;
}

- (NSDictionary *)constantsToExport
{
    return @{ @"nativeTrackerId": staticTrackerId != nil ? staticTrackerId : [NSNull null] };
}
```

Or will I get it regardless if I export constants?

**Comment by amanthegreatone** [comment]
I am getting this error and chrome debugging is stuck!

**Comment by joonhocho** [comment]
@javache Is it safe to ignore all these warnings about possible deadlocks? kinda scary warning tho.
