### ISSUE TITLE
Can't find variable: require

### ISSUE THREAD

**Issue by sospedra** [facebook/react-native#10361]
### Issue Description

When runninng `react-native run-ios` and checking the ios simulator I get the following error:
`Unhandled JS Exception: ReferenceError: Can't find variable: require`.
I checked the `localhost:8081/index.ios.bundle` and notice that the function `_require` and the declaration `global.require=_require` is not present.
When I go to `localhost:8081/index.android.bundle` the `require` definition is there.

![image](https://cloud.githubusercontent.com/assets/3116899/19342754/6cbe9574-9133-11e6-81a4-2bac6ad45f95.png)

### Additional Information

* React Native version: 0.34.1
* Platform(s) (iOS, Android, or both?): iOS
* Operating System (macOS, Linux, or Windows?): macOS Sierra

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of React Native.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #react-native](http://stackoverflow.com/questions/tagged/react-native)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.
