### ISSUE TITLE
Trouble with refresh  NavigatorIOS, navigationBarHidden  with state

### ISSUE THREAD

**Issue by acoderleex** [facebook/react-native#10387]
I want to control NavigatorIOS navigationBarHidden with state as below code

![99f4bea9-355e-49af-93e3-570a94e786d0](https://cloud.githubusercontent.com/assets/6228441/19384097/1b6aa098-923a-11e6-938d-d8fd8addeaa6.png)

and the badge can be refresh with notifyCount from state ,
but navigationBarHidden failed

 Is there something I missed?

**Comment by acoderleex** [comment]
I intend to control NavigatorIOS navigationBar  hidden  or not by isShowHeader from the state,
But the result is not what I expect
So give me some advises , thanks a lot

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of React Native.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #react-native](http://stackoverflow.com/questions/tagged/react-native)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

**Comment by acoderleex** [comment]
Sure

**Comment by acoderleex** [comment]
Sure,Like this, http://stackoverflow.com/questions/40126338/trouble-with-refresh-navigatorios-navigationbarhidden-with-state
