### ISSUE TITLE
com.android.ddmlib.InstallException: Unable to upload some APKs

### ISSUE THREAD

**Issue by joyceHong** [facebook/react-native#10384]
I run android emulate is fine (android 5.0.1) but run in real android device (InFocus M680 Android 5.1 ) that show error message.

command :
> react-native run-android

ErrorMessage:
【:app:installDebug
Installing APK 'app-debug.apk' on 'AVD_for_5_1_WVGA(AVD) - 5.0.2'
Installing APK 'app-debug.apk' on 'InFocus M680 - 5.1'
Unable to install D:\joyce\reactNative\AwesomeProject\android\app\build\outputs\apk\app-debug.apk
com.android.ddmlib.InstallException: Unable to upload some APKs
at com.android.ddmlib.Device.installPackages(Device.java:920)
        ...
02:34:20 E/1602322387: Error while uploading app-debug.apk : Unknown failure
 :app:installDebug FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:installDebug'.
> com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: Unable to upload some APKs
】
* React Native version: 0.33.0
* React Native cli version: 1.0.0
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT] Android 5.1
* Operating System (macOS, Linux, or Windows?): Window 10

I find https://github.com/facebook/react-native/issues/2720 issue.
I had changed the (com.android.tools.build:gradle:1.3.1) to (com.android.tools.build:gradle:1.2.0)
but show another error message:【FAILURE: Build failed with an exception.】
does react native can support the android 5.1 ? 

Please give me some help. thank you.

**Comment by christopherdro** [comment]
@facebook-github-bot label Android

**Comment by lacker** [comment]
Can you run apps via the normal Android development process on this device? Like if you just run an app via Android Studio does that work? It's not clear that this is a React Native problem - it may be an Android development problem. I think it's going to be hard to assist from this issue, because we aren't going to be able to reproduce this problem. I recommend going through the various workarounds described in https://github.com/facebook/react-native/issues/2720 and then to try posting on stack overflow. I am going to close this issue in lieu of one of those channels.

**Comment by Alexintosh** [comment]
I have the same problem, I can run regular Android app through android studio, cordova, ionic cli and other tools.

**Comment by januslo** [comment]
+1
