### ISSUE TITLE
Battery drain test on Android 

### ISSUE THREAD

**Issue by aakashrai1** [facebook/react-native#10383]
Performed current drain test on sample (Welcome to React Native) app when the app was in background for an hour and the results are as follows 

- Sample application with RN version 34 : 31.54mA
- Sample application with RN version 22 : 24.60mA 

Where as the sample native android app only consumes about 10mA in the same scenario.

Tools Used : 
Power monitor (H/w)
Power tool (S/w)

1) Can anybody confirm the above test and explain the reason behind high current drain ?
2) Is it normal for react native apps to have higher current drain values as compared to the native android app?

* React Native version: RN 0.22 and RN 0.34
* Platform : Android

PS : Also attached method profiling graph of the sample RN 0.34 app running in background.

![screen shot 2016-10-13 at 5 37 34 pm](https://cloud.githubusercontent.com/assets/18569902/19377128/39472048-9201-11e6-993c-e08118308ed9.png)

**Comment by janmonschke** [comment]
Did you run the app in development mode with hot reloading on or did you run a packaged app?

**Comment by aakashrai1** [comment]
@janmonschke Battery drain test was performed on packaged(release) app but method profiling graph is of app in development mode with hot reloading turned off.

**Comment by christopherdro** [comment]
@facebook-github-bot label Android

**Comment by lacker** [comment]
Hey, thanks for sharing this information! I'm not entirely sure, but this doesn't seem quite right to me because by default in a production app there shouldn't be a noticeable amount of extra work happening. In general, I think you need a larger number of repeated runs and different devices to get power usage data - you need to figure out what is the deviation between runs that just happens by default. I think it is also only really going to make sense to do these tests on real apps rather than "hello world" type apps. Overall, though, I would love to have more specific testing data, but I don't.  Since issues are probably not the ideal sort of channel for this, I'm going to close this issue, but thanks again for bringing this up.
