### ISSUE TITLE
IOS emulator won't display the app

### ISSUE THREAD

**Issue by ansmonjol** [facebook/react-native#10394]
Hi,
I have a problem when running `react-native run-ios` on my project.

The IOS emulator launch well when then I have the application which start to launch and immediately after hide itself. 
I say hide because if I `Cmd-Shift-H(X2)` I saw the app in the background, and when I click on it, it return me to the home screen.

If I launch the Xcode project and run the app from the Xcode app, it work fine.

I've had some troubles with my app before, the IOS version was 'abandoned' and I've installed a lot of modules and changed the name of the project in the mean time and before trying to make it work on IOS. 
Then I've decided to create a new project with `react-native init myNewProject` (because I couldn't figured out how to fix the IOS, something with a workspace not configured)  and copy paste inside my index.ios/android.js and all my code base. 

So now Android is still working and IOS is only working if I launch the app from Xcode.

I've tried to reset the emulator but it don't change anything.
I don't have any logs about app crash or something, 

Any idea ?

### Logs
I've put the device logs after running `react-native run-ios` on a gist
https://gist.github.com/ansmonjol/f6fa1e71a20b944bf67429c57d081165

### Additional Information

* React Native version: 0.35
* Platform: IOS
* Operating System: macOS El capitan 
* Xcode: Version 8.0

**Comment by dunhuang** [comment]
I have the same issue, and I can't even run with Xcode...

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of React Native.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #react-native](http://stackoverflow.com/questions/tagged/react-native)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

**Comment by ansmonjol** [comment]
Thank you @hramos 

Here is the Stack Overflow: http://stackoverflow.com/questions/40116595/ios-emulator-app-stay-in-background

**Comment by thomas5903** [comment]
For me, I use NVM to set the latest node version. I had to set my default node version to a compatible version for react-native and afterwards everything worked fine.

**Comment by suryaadtmaja** [comment]
i have the same issue, when i started running (react-native run-ios) the emulator is opened but not showing my apps, and some apps that i get from github sometimes is showing up

**Comment by sillygoose4u** [comment]
same issue here the app closes upon start, though it works with android

**Comment by katiachumakova** [comment]
Anyone found out how to fix this? If so can you post your solution (I'm a noob so please please post instructions).

**Comment by sillygoose4u** [comment]
[https://github.com/facebook/react-native/issues/15762#issuecomment-326826411](url)

**Comment by sillygoose4u** [comment]
#326826411

**Comment by sillygoose4u** [comment]
#15762

**Comment by sillygoose4u** [comment]
#15762 https://github.com/facebook/react-native/issues/15762#issuecomment-326826411

**Comment by sillygoose4u** [comment]
Apparently, This is a known issue with versions above 47.x, I personally had to rebuild my project using an older version of react native.
https://github.com/facebook/react-native/issues/15762#issuecomment-326826411

**Comment by rseevan** [comment]
try

`react-native init --version="0.44.0" Albums`

while creating a new project.
Then 

`react-native run-ios`

It did not launch the simulator for the first time so I opened another iOS application in Xcode and ran it. There it was! Behind the recently launched simulator.

Then next time when I recreated the react native application using version 0.44.0, it launched automatically.

**Comment by suryaadtmaja** [comment]
i've same issue, fixed went i change the emulator device and build it in xcode.

**Comment by kevinNejad** [comment]
I've come across the same issue.you may have installed a new native library and link it to your project. Some native modules and library need you to add their framework into your project from xcode. I'm not sure if changing device would help fixing the issue. you may need to unlink the library. Its so annoying, but I am sure there should be a way to resolve it completely. 
It happened to me when I installed lottie library and had to add a framework manually to my ios project.

**Comment by pstanton** [comment]
I'm having the exact same problem, also having tried to bring a fully functional android tested app into iOS - given up and started a blank project. I've even deleted the app project and created a new blank one but can't get it to run.

I can't quite understand how this is not a react-native issue @hramos ? why is it closed? is there a solution?

As per the recommendations, I can't unlink components because the project that referenced anything has been deleted.

I don't think downgrading react-native is a very good solution - especially if it is not a react-native issue! but i've tried all the other suggestions including:

react-native start --reset-cache
watchman watch-del-all
npm cache verify

the only thing that worked for me was deleting the `[project]/ios/build` directory, running `npm start` and then `react-native run-ios`

i can now build my test-app with no extra dependencies.
