### ISSUE TITLE
Accessing _cachedSystemAnimationFence requires the main thread

### ISSUE THREAD

**Issue by maphongba008** [facebook/react-native#10418]
* React Native version :0.34.1
* Platform: iOS
* OS: Mac

I've got a register from with Submit button, which was call a method from native Objective C code:
```
@implementation Utils
RCT_EXPORT_MODULE()

RCT_EXPORT_METHOD(authenticate: (NSString *)code number:(NSString *)number) {
  Digits *digits = [Digits sharedInstance];
  DGTAuthenticationConfiguration *configuration = [[DGTAuthenticationConfiguration alloc] initWithAccountFields:DGTAccountFieldsDefaultOptionMask];
  configuration.phoneNumber = [NSString stringWithFormat:@"%@%@", code, number];
  [digits authenticateWithViewController:nil configuration:configuration completion:^(DGTSession *newSession, NSError *error){
  }];
  
}
@end
```
If I do nothing and click on Submit button, everything works well
But, if I enter some text to one or more text fields in the form, it cause the error Accessing _cachedSystemAnimationFence requires the main thread ... Anyone know why and how to fix it, thanks.
![simulator screen shot oct 17 2016 10 14 40 am](https://cloud.githubusercontent.com/assets/8359203/19424347/978c56ac-9452-11e6-999a-bbc28cf97285.png)

**Comment by ide** [comment]
Looks like a thread-affinity bug with your code.

@facebook-github-bot stack-overflow

**Comment by maphongba008** [comment]
Can you explain it? And do you know how to fix?

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of React Native.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #react-native](http://stackoverflow.com/questions/tagged/react-native)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

**Comment by raminious** [comment]
I fixed similar issue by removing ```autoFocus``` from my ```TextInput``` component
