### ISSUE TITLE
[Navigator] routeStack looping - how to do it and worth adding?

### ISSUE THREAD

**Issue by jmstout** [facebook/react-native#1041]
@ericvicenti

It would be nice to be able to loop the routes in the routeStack on the Navigator component.

The current use case is with the Navigator.SceneConfigs.HorizontalSwipeJump, but it should work for any navigation that uses the jumpForward / jumpBack methods.

Any guidance on how you think this would be best accomplished?

Would be happy to submit a PR if you think it's a feature worth adding to the component.

If so, any thoughts on the interface? A simple `<Navigator loop={true} />`?

Thanks so much!

**Comment by ericvicenti** [comment]
This is a cool idea, and I would like to make sure the Navigator supports this. Ideally, this would be done through some advanced scene configuration that can be made accessible with a special scene configuration or configuration utility.

In a general sense, I think we should add gesture actions for jumpToTop and jumpToLast, and configure the first and last scenes accordingly, so the gesture causes the routes to loop.

I am still making some big changes to the internals of the Navigator. (I hope to split the existing Navigator into two components). Once things settle down, I can add this feature or help walk you through the implementation.

Thanks for this idea! I will keep this use case in mind and make sure we can eventually support this.

**Comment by brentvatne** [comment]
Agreed, neat idea :smile:

**Comment by ccheever** [comment]
@ericvicenti - is this still part of your plan?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/navigator-routestack-looping-how-to-do-it-and-worth-adding

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
