### ISSUE TITLE
Previous scene will rerender when NavigationExperimental pop

### ISSUE THREAD

**Issue by musicode** [facebook/react-native#10422]
I think scenes will keep in stack, but when I pop the navigator, the previous scene is re-rendered.

why? the experience is so bad.

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of React Native.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #react-native](http://stackoverflow.com/questions/tagged/react-native)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.
