### ISSUE TITLE
NavigationExperimental anim

### ISSUE THREAD

**Issue by yanbober** [facebook/react-native#10425]
when using ToolBarAndroid, the NavigationExperimental default push and pop anim in android have a white space, how to fix?

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of React Native.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #react-native](http://stackoverflow.com/questions/tagged/react-native)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.
