### ISSUE TITLE
MoveToTask

### ISSUE THREAD

**Issue by mykelaballe** [facebook/react-native#10453]
How can i replicate Android's `moveToTask` functionality?

**Comment by lacker** [comment]
When I google for `[android movetotask]` I only get this issue. What are you trying to do in your app exactly?

**Comment by ericvicenti** [comment]
If you're asking about Android's [ActivityManager](https://developer.android.com/reference/android/app/ActivityManager.html) you might be interested in the react-native equivalent, [AppState](http://facebook.github.io/react-native/docs/appstate.html).

Feel free to re-open as a more specific issue that describes your expected behavior in comparison to whats actually happening.
