### ISSUE TITLE
Trying to use dynamic underlayColor with TouchableHighlight

### ISSUE THREAD

**Issue by JDeuce** [facebook/react-native#10455]
Messing around with my first react-native project here.

I have a component which starts a timer during the onPress event,
and the timer is cleared during the onPressOut event.
If a press is long enough, that the timer has not been cleared, it will fire and update the state of my component with a new underlayColor, that I pass through as a prop to the TouchableHighlight.

Since the user is already considered "inside" an active touch, the TouchableHighlight does not update the underlay.

I've done a little debugging, in [componentWillReceiveProps](
https://github.com/facebook/react-native/blob/9ee815f6b52e0c2417c04e5a05e1e31df26daed2/Libraries/Components/Touchable/TouchableHighlight.js#L136) I notice that my new underlayColor is accepted and flowed out to the state of the TouchableHighlight. But the TouchableHighlight component only seems to flow that state into the child underlay component's style during the [_showUnderlay function](https://github.com/facebook/react-native/blob/9ee815f6b52e0c2417c04e5a05e1e31df26daed2/Libraries/Components/Touchable/TouchableHighlight.js#L200-L201), which in turn is called from the [touchableHandleActivePressIn event](https://github.com/facebook/react-native/blob/9ee815f6b52e0c2417c04e5a05e1e31df26daed2/Libraries/Components/Touchable/TouchableHighlight.js#L152).

Seems to me like the componentWillReceiveProps could be modified to also flow the style down to the children via the same code as the existing [_showUnderlay](https://github.com/facebook/react-native/blob/9ee815f6b52e0c2417c04e5a05e1e31df26daed2/Libraries/Components/Touchable/TouchableHighlight.js#L200-L201) and [_hideUnderlay](https://github.com/facebook/react-native/blob/9ee815f6b52e0c2417c04e5a05e1e31df26daed2/Libraries/Components/Touchable/TouchableHighlight.js#L209-L213) function, depending on whether the underlay is currently being shown or not.

Getting the current state is another challenge, that I'm not quite sure the best way to solve.

If I were to modify this so the underlayColor can flow dynamically as described, would it likely be merged? Is there anything else to consider?

Thanks, 
J

**Comment by ericvicenti** [comment]
The `setNativeProps` method is used to bypass React's normal rendering process and imperatively mutate the UI. We use it in `_showUnderlay` and `_hideUnderlay` in order to optimize performance and avoid an extra cycle through `componentWillUpdate`, `render`, and `componentDidUpdate`.

`componentWillReceiveProps` will get called when the component is about to render anyways, (due to a change in the parent), so there is nothing to optimize and `setNativeProps` is not needed because React does that under the hood.

Although, it is possible I am misunderstanding your concern. Is there a code snippet that demonstrates the bad behavior you want to fix? Maybe you could post it on rnplay.org so that is easy for people to see. If there is still an issue, feel free to re-open this!

**Comment by JDeuce** [comment]
Here is a sample demonstrating the problem.

It contains a minimal sample reproduction, where onLongPress it tries to change the underlayColor to green, and after the press is released it changes it back to lightgrey.

The expectation is that after the longPress, when continuing to hold the touchable highlight now, the new color would be reflected. What happens instead is the old color continues to be rendered.


https://rnplay.org/apps/xfGkMw

Since you closed the issue I cannot reopen it.
