### ISSUE TITLE
Can`t catch error in AsyncStorage.mergeItem.

### ISSUE THREAD

**Issue by britishd** [facebook/react-native#10464]
I`m trying to catch error in mergeItem method of AsyncStorage. In your documentation you wrote what third params must be callback for catching error. But it is not working. 

`
export const setToken = (token) => {
	return AsyncStorage.mergeItem(constant.permissionSettings, null, () => {
		console.log("ERROR")
	});
};
`
For example in this situation I don`t see in console my message, but application is down with a normal message:
> ExceptionsManager.js:82 JSON value '<null>' of type NSNull cannot be converted to NSString

I tried catch it with `try catch` but result is the same.

**Comment by lacker** [comment]
The second arg of `mergeItem` is supposed to be a string, but you are passing null. I think you should just pass a string there. See the examples at https://facebook.github.io/react-native/docs/asyncstorage.html . 

In general, I think you should expect error callbacks to be for cases where there's some unpreventable underlying error, like there's a disk failure or some other sort of IO failure. Rather than passing the wrong datatype.
