### ISSUE TITLE
Picker Android: undefined is not an object (evaluating 'this.props.children[position].props') React Native

### ISSUE THREAD

**Issue by naveedmastan** [facebook/react-native#10535]
I am using Picker for Android,  I need it to work for dynamic array as coded below not in static way
I getting the error as shown in the image
I also referred to some issues regarding this but haven’t found right thing to fix the solution

Can You please help me to fix the problem
```
 <Picker  selectedValue={this.state.selected} onValueChange={(value) => this.setState({selected:  @value})}> 
					 		<Picker.Item label={prompt}  /> 
					 		{
						 		this.props.property.dataType.options.map(function(value){
						 			return (<Picker.Item label={value} value={value} />)
						 		})
					 		}
				      </Picker>
```
![screenshot_20161025-112040](https://cloud.githubusercontent.com/assets/18306911/19674345/188dc30a-9aa5-11e6-998b-3212fe293047.png)
@maartenschumacher @reactjs-bot

**Comment by lacker** [comment]
This isn't really a React Native problem. It looks like one of the things you're passing is undefined. Instead of writing your code with a massive one-liner, I suggest expanding things into functions where, if you're confused, you can stick print statements. This is basically the same as implementing a list in plain old React, so you might find it helpful to read about that too. You might also try stack overflow. It's not a bug though so I am going to close this issue. Good luck!
