### ISSUE TITLE
Debugging in chrome does not work

### ISSUE THREAD

**Issue by sunify** [facebook/react-native#10551]
After long pause i return to my app and try to update to latest version. I have some bugs, but i can´t debug it, because chrome debugger does not work now.

I enable remote debugging in devmenu, chrome tab is open with message like «Debugger session ... is active», but console is empty, debugger keyword not work and debugger not pause on exceptions.

How i update my app:
1. Install new version
2. Fix issues (use react instead of react-native, etc)
3. react-native upgrade

### Additional Information

* React Native version: update from 0.22 to 0.35 (also i try 0.34)
* Platform: iOS
* Operating System: macOS Sierra

**Comment by lacker** [comment]
I would try restarting everything in your dev environment. After that, the first question I would ask is whether it's this specific app or your React Native setup, and to figure that out I would see, can you reproduce this problem on a blank app that you create?

**Comment by sunify** [comment]
Yes, i have same error on blank app (react-native init).

**Comment by lacker** [comment]
That is strange. Either something is borked on your particular install of React Native or you are doing something unusual without realizing it, because in general the debugger does work on new apps. I would try this on a different machine to be sure you are doing the right steps. If that does not work then really you just have to restart things and reinstall them - I don't know a better way. Make sure you kill any lingering processes - restarting your computer, watchman, the packager, all of these are good things to restart. Sorry I don't have a more intelligent answer here.

**Comment by sunify** [comment]
Oh, i restart computer and now everything is ok.

Thank you very much, @lacker!

**Comment by lacker** [comment]
Turning it off and on again baby! The bugfixing technique of champions.
