### ISSUE TITLE
Can onLayout also provide the page position, like measure does?

### ISSUE THREAD

**Issue by josvos** [facebook/react-native#10556]
### Description

The `onLayout` callback now provides in its layout data the same information as the `measure` (NativeMethodsMixin) callback does, except for the missing absolute page position.  Is there a technical reason for this, or can these 2 values also be included in the `onLayout` data?

I'm now calling `measure` (i.e. triggering the callback) in the `onLayout` callback, in order to know when `measure(`) can provide (update) information, but this seems to be double work.

**Comment by lacker** [comment]
I don't think there's a technical reason for this, it's more that it's bad form to use the absolute page position all the time. It seems like you have a valid workaround so I am going to close this issue.

**Comment by scally** [comment]
So, there's a workaround for this, but it's really awkward -- you need to save a child view as a ref, and then use that ref in a callback in another callback in onLayout. 

There are legitimate use cases for absolute page positioning, one of which is drag/drop; if you want to know if one component has been dropped onto another when the two don't share a common immediate parent.

If there's no technical limitation preventing this from being surfaced as a param to onLayout (or on another event handler) then could we re-open this issue?

**Comment by scally** [comment]
the workaround looks like this, fwiw: 

```
render() {
    return (
      <View
        style={styles.container}
        ref={ref => this.view = ref}
        onLayout={() => this.saveLayout()}
        >
  )
}

// later....

saveLayout() {
  view.measureInWindow((x, y, width, height) => {
    // do a thing with the layout...
  }
}
```

And it's even uglier wrapped with redux/dispatch

**Comment by mattread90** [comment]
I'm also after the `pageX`/`pageY` for the purposes of drag and drop, so having to resort to `.measure()`.

On a slightly different but related note, my `.measure()` call is returning inconsistent values when my view is first mounted after navigating to the scene. The `pageX` value is being given as either 0 or 374.5, which I'm guessing is due to the fact that the scene is sliding in from the right and the `onLayout` callback is being fired at different times during this process.

**Comment by Ashoat** [comment]
A good reason that `pageX`/`pageY` are needed is that `PanResponder`'s relative positioning info is double broken (#12591, #15290). The first issue is fixed in upcoming release RN@0.49, but the second has unfortunately not be debugged yet.

Currently, any components that rely on panning behavior are forced to do absolute comparisons, and this issue makes that really hard by forcing people to use a `measure()` nested inside an `onLayout` to even get at the absolute data they need.

**Comment by HideyaSwider** [comment]
I am also in need of these properties. Has anyone gotten anywhere?

**Comment by necolas** [comment]
FWIW, I was also hoping `onLayout` would provide the equivalent data to either web's `getBoundingClientRect` or web's ResizeObserver.
