### ISSUE TITLE
Failed to start the React Native packager: Could not start the packager.

### ISSUE THREAD

**Issue by feilongOnMoudu** [facebook/react-native#10581]
Failed to start the React Native packager: Could not start the packager.
npm start        can not
react-native    can not

who can help me?

**Comment by ide** [comment]
@facebook-github-bot stack-overflow

**Comment by feilongOnMoudu** [comment]
But there is no way to solve it

**Comment by feilongOnMoudu** [comment]
@ide can you help me?

**Comment by ide** [comment]
Hey @feilongOnMoudu and thanks for posting this! This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by feilongOnMoudu** [comment]
thank you!
