### ISSUE TITLE
How to get Text component value onPress

### ISSUE THREAD

**Issue by pardeepbeniwal** [facebook/react-native#10591]
Hi All,
I am using react native react-native: 0.30.0. I want to get value of Text component onPress. Below is my code:
 <Text  onPress={() => {this.setHabit(this)}}>  {'Test1} </Text>
 <Text  onPress={() => {this.setHabit(this)}}>  {'Test2} </Text>
 <Text  onPress={() => {this.setHabit(this)}}>  {'Test3} </Text>
my funtion"
setHabit(value){
	alert(value);//here should be value show Test1,Test2 vice varsa
}
Please help

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of React Native.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #react-native](http://stackoverflow.com/questions/tagged/react-native)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

**Comment by pardeepbeniwal** [comment]
Hi
Thanks for help.
But I have not any textbox. There will be simple text like attached image.
I want to functionality like attached image eg. I will select select habit,clear habit
![41ef7f74-896e-11e6-8a19-29b55bea3598](https://cloud.githubusercontent.com/assets/12539456/19795537/01789030-9cfa-11e6-922c-90f95ddc93f9.png)

Thanks

**Comment by symmetriccurve** [comment]
@pardeepbeniwal. 

If I understood Correctly, user should able to tap select and tap deselect items. is that right ?
In that case, simply have the List of Items in a object with a flag 

selected: true 

```
habits :[
   { 
      habit: 'Go for a Walk',
      selected: false
   
   },
   { 
      habit: 'Wash your hair',
      selected: false
   
   },
   { 
      habit: 'Reply to a Text',
      selected: false
   
   },
   { 
      habit: 'Go for a run',
      selected: false
   
   }

]

```

As user Taps on one of the Items, invert the flag on the  user selected habit object's variable  **selected: !this.state.habit[index].selected** (which should be in state). and as State changes, render with UI logic with selected: true with different color.

**Comment by leizard** [comment]
+1. I have a result list from a search query. I want to get the value when people click on the Text component, which is inside a ListItem.
