### ISSUE TITLE
Layout animation collision on Alert call with KeyboardAvoidingView

### ISSUE THREAD

**Issue by kirillpisarev** [facebook/react-native#10606]
### Description

Calling Alert with focused TextInput (Keyboard is open) wrapped in KeyboardAvoidingView causes warning:

```
Warning: Overriding previous layout animation with new one before the first began:
{
    duration = 250;
    update =     {
        duration = 250;
        type = keyboard;
    };
} -> {
    duration = 404;
    update =     {
        duration = 404;
        type = keyboard;
    };
}.
```

And should input become focused after alert dismiss or not? Now i do it manually but in older versions seems it was automatically
### Reproduction

https://rnplay.org/apps/5lB8-A
### Additional Information
- React Native version: 0.36
- Platform: iOS 10
- Operating System: MacOS

**Comment by perrosnk** [comment]
+1

**Comment by edo1493** [comment]
+1

**Comment by neiker** [comment]
+1

**Comment by askarhu** [comment]
+1, hope this gets some attention.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by anonrig** [comment]
I'm having this issue atm.

**Comment by tbazko** [comment]
Similar issue here

**Comment by anand-neema** [comment]
Same issue

**Comment by suhabaobaid** [comment]
Anything new on this issue? I am facing the same thing and would like to get rid of the warning

**Comment by ankur-sardar** [comment]
+1

**Comment by khushboogupta1** [comment]
I am facing same issue on IOS

**Comment by neiker** [comment]
I kinda hate that bot.

**Comment by anonrig** [comment]
@neiker Me too brother. Me too...
