### ISSUE TITLE
[Navigator] NavigationBar assumes there will be a status bar that is 20 units tall on IOS

### ISSUE THREAD

**Issue by daniel-nagy** [facebook/react-native#10600]
### Description

On IOS the `Navigator.NavigationBar` component assumes that it needs to displace a status bar that is 20 units tall. For IOS 10 iMessages apps this is not the case and overriding the default styles is a bit cumbersome. For example, one would have to do

``` javascript
import NavigationBarStyles from 'NavigatorNavigationBarStylesIOS';

const navigationStyles = merge({}, NavigationBarStyles, {
  Stages: {
    Center: {
      Title: {
        top: 0,
        justifyContent: 'center'
      }
    }
    // repeat for left and right?
  },
  General: {
    TotalNavHeight: 44,
    StatusBarHeight: 0
  }
});

<Navigator.NavigationBar navigationStyles={navigationStyles} />
```

Maybe there needs to be a preset for IOS iMessages apps or an easier way to override the height of the status bar?
### Additional Information
- React Native version: `0.35.0`
- Platform: IOS
- Operating System: MacOS

**Comment by avioli** [comment]
What I'm doing is to copy `node_modules/react-native/Libraries/CustomComponents/Navigator/NavigatorNavigationBarStylesIOS.js` locally, then change `var STATUS_BAR_HEIGHT = 20;` to `0` and import that file to feed it to the NavigationBar's styles. In addition you have to change the `@providesModule` name, remove it or remove at least the `@`, otherwise you'll get a collision warning from the packager.

Then:

```
import * as navigationStyles from './LocalNavigationBarStylesIOS.js';
// or
// const navigationStyles = require('./LocalNavigationBarStylesIOS.js');
```

```
<Navigator.NavigationBar navigationStyles={navigationStyles} ... />
```

This way you ensure you are controlling the whole data, not just merging some changes.

**Comment by christopherdro** [comment]
@facebook-github-bot answered

**Comment by hramos** [comment]
Navigator has been deprecated in favor of the [`react-navigation`](https://reactnavigation.org) library.
