### ISSUE TITLE
Include the NativeAnimation module on iOS in the starter project

### ISSUE THREAD

**Issue by janicduplessis** [facebook/react-native#10638]
https://github.com/facebook/react-native/tree/master/Libraries/NativeAnimation should be included when creating a new project. We will want to use native animations in react-native core so having it included by default makes sense. It is also included by default on Android now.

**Comment by petrgazarov** [comment]
I'm new to the codebase and would like to take this on if that's alright. I looked around and couldn't find where this logic lives. Perhaps if you have a minute, can you point out where/how it is included on Android? Also, some steps to test expected behavior. Should there be an automated test? Thanks!!

**Comment by sreejithr** [comment]
@janicduplessis I've made a pull request [here](https://github.com/facebook/react-native/pull/10783). I added the `../node_modules/react-native/Libraries/NativeAnimation/RCTAnimation.xcodeproj` file and linked `libRCTAnimation.a` in `local-cli/generator-ios/templates/xcodeproj/project.pbxproj`.

Do let me know if everything is OK. I published my branch in Sinopia and tried having `useNativeDriver`. No errors. Animation works. Thank you.

**Comment by pvsousalima** [comment]
I am receiving a red screen here, even though I did everything as the PR.
![image](https://cloud.githubusercontent.com/assets/1810178/20610358/a1c84d2e-b27f-11e6-80bd-2a7026095109.png)
