### ISSUE TITLE
Slow animations seem to be stuck in "On" state when debugger is attached

### ISSUE THREAD

**Issue by jcollum** [facebook/react-native#10633]
### Description

I am using React Native with iOS simulator. I'm finding that Slow Animations seems to be stuck in an "On" state. 

### Reproduction

Steps: 

1. Kill any react native server that is running
1. Close any React Native Debugger windows in Chrome 
1. `node node_modules/react-native/local-cli/cli.js start`
1. wait for server to start 
1. `react-native run-ios`
1. Confirm that Slow Animations is not toggled on
1. Attach debugger: Cmd D; Debug JS Remotely

Expected: animations are running at normal speed 

Actual: animations are running at slow speed

### Additional Information

```
$ react-native --version
react-native-cli: 1.0.0
react-native: 0.34.1
$ versions
npm 3.10.3
node v6.7.0
OS Darwin por-collumj-m.ds.ad.adp.com 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64
```

Platform: iOS (simulator)

**Comment by brentvatne** [comment]
Animations will run very slowly with the debugger enabled because the JavaScript is running on your computer rather than on the device, so there is much more overhead for communicating over the bridge -- see https://github.com/facebook/react-native/issues/2367 and https://productpains.com/post/react-native/improve-performance-of-chrome-debugger/

I would recommend to only attach the debugger specifically when you are debugging something, and otherwise leave it turned off.
