### ISSUE TITLE
NavigatorIOS component. How to make background be transparent?

### ISSUE THREAD

**Issue by CharlesMoone** [facebook/react-native#10652]
i want to keep NavigatorIOS component exist but backgroundColor.NavigatorIOS initialRoute API has no param about this , it means that RN can't do this?

**Comment by brentvatne** [comment]
NavigatorIOS isn't used or supported by the React Native team, so you're unlikely to get help on this here. Additionally, the issues are intended for bug reports rather than questions and feature requests. You might be better off using one of the community resources: https://facebook.github.io/react-native/support.html :)
