### ISSUE TITLE
0.36.0 not respecting blacklistRE in rn-cli.config.js

### ISSUE THREAD

**Issue by robtaireeo** [facebook/react-native#10673]
### Description

0.36.0 not respecting blacklistRE in rn-cli.config.js

I have a git submodule at named server, and the node_modules folder under it is ignored correctly with 0.35.0 with the following, but when i upgrade to 0.36.0 the package manager is now finding duplicate modules.

```
var blacklist = require('react-native/packager/blacklist');

var config = {
    getBlacklistRE(platform) {
        return blacklist(platform, [
            /server\/.*/
        ]);
    }
};

module.exports = config;
```

### Additional Information

* React Native version: 0.36.0
* Platform: both
* Operating System: el capitan and win10

**Comment by ide** [comment]
The blacklist functions signature changed. Drop the platform argument.

**Comment by Venryx** [comment]
An error should really be thrown when someone calls `blacklist` using the old signature.

This has caused problems, as it silently causes the blacklist system to fail in projects -- which is seemingly the only way to solve issues such as this: https://github.com/facebook/react-native/issues/9136

Because I didn't know this, and because using the wrong signature just failed silently, the build error in the thread above (well, one similar) has plagued me for weeks, wasting me a lot of time as I had to keep doing a workaround of deleting the entire build folder each time I ran "react-native run-android".
