### ISSUE TITLE
Xcode: on deploy to device, Packager re-packages even when no changes

### ISSUE THREAD

**Issue by onpaws** [facebook/react-native#10686]
### Description
Sometimes I use Xcode to deploy my RN app to a physical device using the Xcode toolbar, e.g. 
![image](https://cloud.githubusercontent.com/assets/182515/19909733/5fc8a3d8-a05f-11e6-972e-7ddd6065b741.png)

As expected, during the 'Bundle React Native code and images' build phase...
![image](https://cloud.githubusercontent.com/assets/182515/19909850/e7aba7f0-a05f-11e6-88ec-a37028dcf4df.png)

...the RN Packager bundles the app. It's a substantially lengthy process, in my case ~6-8 minutes.

If I _don't change any code_ and simply deploy the app again using Xcode, the entire packager build restarts.

**Is there a way I can persist Packager builds across Xcode deploys?** 

Feels like the whole point of HMR/Live Reload is to avoid this -- how can I bring it to device deploys? Given how clever HMR is, this just seems so unnecessary.

### Reproduction
1. Open an RN project's `ios/app.xcodeproj`
2. Plug in physical iOS device
3. Deploy RN app to device
4. Don't change any code
5. Deploy again

### Additional Information
* React Native version: 0.33
* Xcode version: 8.1
* Platform: iOS
* Operating System: MacOS El Capitan 10.11.6

Did an Issues search for 'Xcode' & 'Xcode Packager' -- didn't find anything pertinent, apologies if this is a dupe.

**Comment by pvinis** [comment]
yea this should change. i propose we change the `react-native-xcode.sh` code, to skip building if its the scheme is `Debug`. currently it skips if the scheme is `Debug` AND its running on a simulator. Debugging should be quick and not build the bundle, even on a device.

**Comment by ephemer** [comment]
+1 on this issue and the proposed fix

**Comment by onpaws** [comment]
@frantic, @mkonicek thanks for your previous [work](https://github.com/facebook/react-native/commit/5f0ef12cb59f5bf619c3f5b38a7b400f5fbb9b8b#diff-e35d320a1bf991537277377d63b968e9) on this important part of RN. 

Because Apple requires a physical device for certain features, e.g. push notifications, I know I'm not alone in feeling the pain on this. I feel like a fix would be a _massive_ cumulative time savings for the RN community.

Do you know of any already existing efforts on this?

**Comment by pvinis** [comment]
i commented out the `if` in the file i mentioned before. and it works faster, but sometimes the `jsCodeLocation` is nil, and then i have to uncomment it, run, then comment it again and its file for a while again..

**Comment by wafisher** [comment]
+1 and can we get some input from the core team?

**Comment by frantic** [comment]
If you just want to re-deploy your app to device and haven't changed any native or JS code, use "Run Without Building" `^⌘R`

![image](https://cloud.githubusercontent.com/assets/192222/21297380/5cee5286-c533-11e6-9c7d-57aaced7acb8.png)

**Comment by ephemer** [comment]
@frantic I appreciate the tip. If I didn't need anything built I could also just tap the app on the device's springboard.

What about the case where you're developing a native plugin which requires constant rebuilding of native code but not of the JS bundle?

It's possible to work around this (to a degree) by creating a new RN project containing only the component under development, but this involves a fair bit of overhead, including maintenance of an additional project.

To me it'd make sense to have some intelligent way around this built into the tooling, without the overhead. For example, would it be reasonable to at least do the JS build in parallel to the native build instead of in series? I don't fully understand the bundler yet but from what I gather it shouldn't matter - in debug / development - whether the app starts before the bundling is complete

**Comment by pvinis** [comment]
exactly. we need that so we can develop native components quicker. every time i recompile the objc part of the app, its waiting to rebuild the js part too.

**Comment by onpaws** [comment]
**Assumptions**
1. Bundler takes longer than compiling native Xcode
1. It's true that it shouldn't matter whether the app starts before the bundling is complete
I noticed it's possible to rearrange build phases, including the bundler:

Caveat emptor.
