### ISSUE TITLE
How TouchableHighlight prevent parent view get gesture responder?

### ISSUE THREAD

**Issue by feyy** [facebook/react-native#10693]
There is a `TouchableHighLight` in a `View`, which specify `onStartShouldSetResponder` `onMoveShouldSetResponder` return `true`, `onResponderTerminationRequest` return `false`.
Then, only in iphone 7 plus, the TouchableHightLight's `onPress` can't be trigger when press it.

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of React Native.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #react-native](http://stackoverflow.com/questions/tagged/react-native)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.
