### ISSUE TITLE
Linking API documentation is out of date for v0.37, v0.36

### ISSUE THREAD

**Issue by liesislukas** [facebook/react-native#10717]
Newest version is 0.37 rc, so maybe you still on the way to update docs, but right now documentation still talks about how to manually add LinkingIOS to xcode project, while on release description it's said, that LinkingIOS is removed and now we have to use Linking api for both platforms.

http://facebook.github.io/react-native/releases/0.37/docs/linking.html
https://github.com/facebook/react-native/releases/tag/v0.37.0-rc.0

For v0.36 docs, there is also same issue. http://facebook.github.io/react-native/releases/0.36/docs/linking.html

I tried to follow step by step, seems like most of the stuff is already done by default.

**Comment by hramos** [comment]
If the change is introduced in 0.37-RC, then it should be fine to have the old way in the 0.36 docs for people using older versions.

We still have a chance to land any doc changes for 0.37-RC before it is released. Can you open a PR? cc @satya164 who authored the commit.

**Comment by satya164** [comment]
The iOS code is still called `LinkingIOS` and the documentation didn't need any change regarding this. If it's done by default in the generator template, probably the documentation says this because you'll still need to do this manually in a hybrid app.

cc @grabbou who will have more context on iOS code

**Comment by grabbou** [comment]
It's a bit unfortunate and I remember reviewing a PR in the past that was renaming LinkingIOS.xcodeproj to Linking.xcodeproj (since there's no need to have `IOS` suffix in the platform-specific modules). 

JS uses `Linking` module, but it calls into `LinkingIOS` module. It calls `LinkingManager` (https://github.com/facebook/react-native/blob/master/Libraries/Linking/Linking.js#L21) which is exposed inside `LinkingIOS.xcodeproj` -> https://github.com/facebook/react-native/blob/master/Libraries/LinkingIOS/RCTLinkingManager.m

To remove the confusion, we should rename LinkingIOS module to Linking (breaking change for all the projects since they will have to remove LinkingIOS and add Linking in xcode). Given experience of people with Xcode tool, we should aim for a super tested update script before we roll it out.

For now, I suggest to highlight that `LinkingIOS` is just the name of the module to add inside Xcode and has nothing to do with JS calls.

**Comment by brentvatne** [comment]
If anyone wants to update docs to make this 100% clear beyond any doubt then feel free ;) Closing, but PR welcome!
