### ISSUE TITLE
could not connect to development server 

### ISSUE THREAD

**Issue by omhybrid** [facebook/react-native#10732]
windows 7, android 

when i fire in cli  react-native run-android
![screenshot_2016-11-04-11-54-12](https://cloud.githubusercontent.com/assets/22111807/19996449/9fa72f10-a285-11e6-8ec4-5c525bdb89fd.jpeg)

**Comment by TuKun33** [comment]
'react-native start ' again

**Comment by omhybrid** [comment]
i already try this but not solve

**Comment by aiDove** [comment]
Should check whether the IP is in the same LAN.( mobile and computer )

**Comment by TuKun33** [comment]
are you sure the serve is running? open your browser and input localhost:8081

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of React Native.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #react-native](http://stackoverflow.com/questions/tagged/react-native)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.
