### ISSUE TITLE
ScrollView rendered incorrectly with RefreshControl if push back a bit before finish refreshing

### ISSUE THREAD

**Issue by nihgwu** [facebook/react-native#10747]
![rc](https://cloud.githubusercontent.com/assets/2595058/20011421/93479b4a-a2e6-11e6-82c6-09dd427460e6.gif)
to reproduce:
Open the `RefreshControl` example in `UIExplorer` for iOS, pull to refresh and then push back a bit(not hide the RefreshControl) before turning off `refreshing`, and you will see the issue every time with the latest code in master branch of React Native, the ScrollView bounces back with a space for RefreshControl witch is already disappeared instead of scroll to the top

**Comment by tsteele2013** [comment]
Having the same issue described by @nihgwu in my ListView. If I scroll down while the refresh is still processing, the space for the RefreshControl is still being rendered, which pushes down my stickyHeader and makes things look quite ugly.

The Today sectionHeader should be directly underneath the StatusBar.


![img_4426](https://cloud.githubusercontent.com/assets/13422144/21825748/fedd7726-d752-11e6-97a6-af4a91923363.PNG)

**Comment by kkamperschroer** [comment]
My team has been encountering the same issue:

<img width="375" alt="screen shot 2017-01-23 at 3 13 09 pm" src="https://cloud.githubusercontent.com/assets/382859/22222916/7fdcce14-e17e-11e6-8329-cdd0f73cb874.png">

Corresponding `render` code snippet looks like:
```
return (
  <ListView
    style={styles.listView}
    dataSource={dataSource}
    renderRow={renderRow}
    renderSeparator={renderSeparator}
    renderSectionHeader={renderSectionHeader}
    onEndReached={this.loadMoreAppointments}
    onEndReachedThreshold={800}
    initialListSize={appointments.length}
    refreshControl={refreshControl}
  />
);
```

With `RefreshControl` being a simple:
```
<RefreshControl
  refreshing={loadingAppointments}
  onRefresh={this.handleRefresh}
  tintColor={'#01A191'}
  title={'Loading...'}
  titleColor={'#01A191'}
  colors={['#01A191', '#41CFBD']}
  progressBackgroundColor={'#FFFFFF'}
/>
```

When this https://github.com/facebook/react-native/pull/11700 makes it into a release, we are debating just disabling section sticky headers (or just rendering them as normal rows now to disable them).

Finally, just to add some more context; it does appear there was an intentional commit a while back to resolve this issue: https://github.com/facebook/react-native/commit/34389c529dc5a1dff86164b6087228ca021fdde7.

**Comment by stief510** [comment]
+1

**Comment by VansonLeung** [comment]
+1

**Comment by MataHu** [comment]
+1

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/scrollview-rendered-incorrectly-with-refreshcontrol-if-push-back-a-bit-before-fi
