### ISSUE TITLE
On an Android platform, calling substr on a string that contains an emoji expression can cause a crash

### ISSUE THREAD

**Issue by yinxin630** [facebook/react-native#10803]
I encountered a bug, if a string contains emoji expression. Call substr. Because emoji occupy two bytes. If the substr end point just in the emoji characters in the Andrews platform will produce a crash, but the ios platform Not in.

Example:
`'aa😈😈😈'.substr(0, 6)` Will not cause a crash.
`'a😈😈😈'.substr(0, 6)` But this will crash because an Emoji expression is truncated.

**Comment by lacker** [comment]
That's pretty strange. I thought that `substr` stayed inside the JS environment rather than doing anything like using native code. Does this happen in a standard environment like just in a "hello world" app that does nothing else except call this? I wonder if it's actually something else going awry here.

**Comment by christopherdro** [comment]
@facebook-github-bot no-reply

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/on-an-android-platform-calling-substr-on-a-string-that-contains-an-emoji-express
