### ISSUE TITLE
onLongPress breaks next touch event, when component is umnounted in the onLongPress handler

### ISSUE THREAD

**Issue by SaboteurSpk** [facebook/react-native#10820]
### Description

I'm changing component state in onLongPress handler of Touchable component. Setting new state causes that the Touchable component is removed and new view introduces second Touchable component.
First touch on second Touchable component doesn't fire event (I didn't test all of them, but onPress doesn't work). The second touch works well again.

### Reproduction

https://rnplay.org/apps/boZDkw

Long press the first button, and then try to pres the newly appeared button.

### Additional Information

* React Native version: [0.35, 0.36, 0.37]
* Platform: [ iOS, Android ]

**Comment by cvillecsteele** [comment]
+1 Seeing this behavior also.

**Comment by dannycochran** [comment]
Seeing this on 0.41.0 as well.

**Comment by georgest** [comment]
+1 Seeing this on 0.42.3 as well.

**Comment by dannycochran** [comment]
No longer seeing this on 0.44. I think it's safe to close.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
