### ISSUE TITLE
Touchable* onPress not working on ScrollView composition

### ISSUE THREAD

**Issue by 7ynk3r** [facebook/react-native#10822]
### Description

I have one `ScrollView`(a) containing another `ScrollView`(b) and a `TouchableOpacity`(c) floating on top for (b). While scrolling on (b), `onPress` on (c) is not triggered. 
- This only happens when `scrollEventThrottle` is 50 or less
- Scroll on (a) is disabled.
- It doesn't matter the direction of (a) or (b). 

### Reproduction

Use the following code, scroll and press the yellow square button. The button will only work if you're not scrolling.

```
import React, { Component } from 'react';
import {
  AppRegistry,
  View,
  ScrollView,
  TouchableOpacity,
  Dimensions,
} from 'react-native';

const {width,height} = Dimensions.get('window');

export default class scrollplusbutton extends Component {
  render() {
    const color = ['green','red','blue'];
    return (
      <ScrollView scrollEnabled={false}>

        <View style={{width, height}}>

          <ScrollView scrollEventThrottle={50}>
            {[...Array(20)].map((_, i) =>
              <View key={i} style={{height:i*50, backgroundColor:color[i%color.length]}}/>
            )}
          </ScrollView>

          <TouchableOpacity
            style={{
              position:'absolute',
              left:0,
              top:0,
              width:100,
              height:100,
              backgroundColor:'yellow',
            }}
            onPress={()=>alert('hello!')}
          />

        </View>

      </ScrollView>
    );
  }
}

AppRegistry.registerComponent('scrollplusbutton', () => scrollplusbutton);
```

### Additional Information

* React Native version: "react": "15.3.2" and "react-native": "^0.37.0"
* Platform: iOS (works well on Android)
* Operating System: MacOS

**Comment by mdvacca** [comment]
same problem here

**Comment by michaelcpuckett** [comment]
+1

**Comment by sachinrekhi** [comment]
Running into the same problem with React Native 0.39.2.

I've tried both TouchableWithoutFeedback and TouchableOpacity and in neither case the onPress handler is triggered when rendered within ScrollViews.

This appears to be a regression as it was working fine for me in React Native 0.34.1 and only saw the issue occur immediately after upgrading to RN 0.39.2.

Strange thing is the onPress handler is properly triggered for me in the iOS Simulator, but is not triggered when I actually load the app on my iPhone.

**Comment by sachinrekhi** [comment]
It appears that the ScrollView is intercepting and cancelling the onPress event. The workaround I found was to set delayPressIn={0} and attach to the onPressIn event instead of onPress.

**Comment by aforty** [comment]
Same problem here and it's very frustrating. 

I use a `ScrollView` to allow for easy keyboard dismissing (when it is pressed) but Touchable* onPress events don't trigger. Interestingly, it works fine on my iPhone 6 (regular) and in the simulators (of all sizes) but not on any actual "Plus" sized devices (tested both 6 Plus and 7 Plus). This was a very frustrating bug to find as I don't own a "Plus" device and only found out about this bug when the app was in the wild and reports started surfacing of people not being able to interact with a very basic control. 

`delayPressIn` seems to be a workaround for now, although it prevents me from holding down on `PressIn`, so that's not gonna do it for me in the long run.

react@15.4.2
react-native@0.42.3

**Comment by Sam1301** [comment]
faced same issue, solved it by wrapping the contents of ` TouchableWithoutFeedback` within a `View` component.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
