### ISSUE TITLE
Run in new tab instead of new window in terminal.app

### ISSUE THREAD

**Issue by LiamInJapan** [facebook/react-native#10848]
### Description

invoke react-native run-android

the command runs the packager in a new window.

It would be great if there was a way of spawning this in a new tab instead of a new window, as this matches my workflows much more closely

### Additional Information

* React Native version: 
react-native-cli: 1.2.0
react-native: 0.37.0

* Platform: Android
* Operating System: MacOS's terminal.app

**Comment by mkonicek** [comment]
Hi, this makes sense and I'd like that better that a new window. However it is a feature request rather than a bug. Please report it here: https://productpains.com/product/react-native?tab=top, or even better - please send a pull request!

From https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md:

> If you have a feature request, post it on Product Pains: https://productpains.com/product/react-native/

**Comment by LiamInJapan** [comment]
thanks!
