### ISSUE TITLE
ios debug js remotely  white screen

### ISSUE THREAD

**Issue by tofrookie** [facebook/react-native#10853]
### Description
i debug on simulator everything is ok,
and run on the ios device is fine,when debug on the device
show the white screen,no error log

### Additional Information

* React Native version: 0.35.0
* Platform: [iOS 10.1]
* Operating System: [ MacOS]

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of React Native.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #react-native](http://stackoverflow.com/questions/tagged/react-native)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.
