### ISSUE TITLE
Contribute and develop

### ISSUE THREAD

**Issue by 7ynk3r** [facebook/react-native#1087]
So far it's been easy to create a new app and add content to it, just follow the instructions in https://facebook.github.io/react-native/docs/getting-started.html and eveything works great.

Now, I couple of questions:
1. How can update the sources for react? As far as I know when I use `react-native init [MY_PROJECT]` they are copied and never updated again.
2. I would also like to contribute. i.e. I've exposed a property in the webview to automatically adjust the zoom to fit the content.

I've tried to accomplish 1 and 2 by forking the repo in `./react-native` and under `./my_project` have my project. After that I tried to link the libraries to my project following https://facebook.github.io/react-native/docs/linking-libraries.html. I copied the same structure used by `react-native init [...]` (drag&drop libraries, link them and added the headers). But when I try to compile I get:
```
module.js:338
    throw err;
          ^
Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/jmrodriguez/dev/test/react-native/packager/getFlowTypeCheckMiddleware.js:11:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
Process terminated. Press <enter> to close the window

```

How can I solve this issue? Is this the correct configuration for contribute and develop? 

Thanks in advance!
JM

**Comment by ide** [comment]
1. To update React, update the version number of react-native in your your package.json file. To help with this you could run `npm install -g npm-check-updates` to install a helper script, and then run `npm-check-updates -u` inside of your project directory. Then run `npm install` to get the latest copy of React.

2. You might need to run `npm install` in your project directory since it looks like you're missing dependencies. For testing my development copy of React, here's what I recommend:

a) Fork this git repo and clone the fork to your computer
b) Create a new git branch and make your changes
c) In your iOS project, change the value of the "react-native" dependency from a version number to the path of your local git repo. For example `"react-native": "~/Code/react-native"`.
d) Run npm install in your iOS project
e) You should be able to run your project using your own copy of React
f) Push your branch when you're done and submit a PR

**Comment by brentvatne** [comment]
Pretty comprehensive answer there from @ide, nice one :smile:
