### ISSUE TITLE
Crash when rendering ReactSwitch on Android 4.4

### ISSUE THREAD

**Issue by iury** [facebook/react-native#10877]
### Description

Crashylitcs reporting the following error only on Android 4.x:
http://crashes.to/s/805a3d371b4

### Additional Information

* React Native version: 0.35
* Platform: Android 4.x

**Comment by ericvicenti** [comment]
Does this happen every time the switch gets rendered on 4.4? Do you have a reliable way to reproduce the crash?

**Comment by iury** [comment]
I've figured it out. The React Native has a dependence to AppCompat-v7 v23.0.1 but my app uses the Facebook SDK, which has AppCompat-v7 v25.0.0. I changed the React Native to 25 as well and no more crashes so far.

**Comment by KazooTang** [comment]
I have exactly the same issue in my project.

with:
React Native version: 0.37
Platform: Android 4.x (only)

It happens quite frequently.

**Comment by hey99xx** [comment]
Possibly this exact issue you guys are facing http://stackoverflow.com/questions/39091521/vector-drawables-flag-doesnt-work-on-support-library-24

**Comment by iury** [comment]
I think it is indeed about the support library version, but I'm unable to reproduce the error on 4.x emulators so dunno how to fix exactly. React Native uses the 23.x series but our project integrates with Facebook SDK which itself uses 24.x series, so probably there is a conflict somewhere.

**Comment by stinju** [comment]
Running into the same issue with RN0.39 on an Android 4.4.4 device.  It crashes intermittently but very frequently (>50% of the time).  Using `compileSdkVersion 23` and `buildToolsVersion "23.0.1"`.  Any tips/workarounds would be greatly appreciated.

**Comment by frostedcake** [comment]
@stinju I've upgraded to RN 0.40 and it still happens. Also using compileSdkVersion 23 and buildToolsVersion "23.0.1".

**Comment by rgngl** [comment]
See my comment here: https://github.com/facebook/react-native/issues/12359#issuecomment-292817057

Maybe switch component used in React Native can be changed with a `Switch` instead of `SwitchCompat` to make it compatible with regular activities.

**Comment by pietropizzi** [comment]
I am having the same crashes happen. Have a look at the Fabric crash reports: http://crashes.to/s/de05af661bd It only happens on 4.x devices and most of them are Samsung. I tried different combinations of support library versions but that did not help.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
