### ISSUE TITLE
simulator ios8.1 crashed with Unhandled JS Exception: Syntax Error

### ISSUE THREAD

**Issue by Yidada** [facebook/react-native#10891]
![image](https://cloud.githubusercontent.com/assets/12830571/20236711/6cc06340-a8f8-11e6-865a-67ed7f63eb93.png)
Find that when I open the Debug JS Remotely.My app running fine, but if I close the Debug JS Remotely the App crashed. 
My RN version is 0.37.0, Really confused about this error. cause I can't find any information from the exception console.

**Comment by Yidada** [comment]
![Uploading image.png…]()

Here is what I got from the ios simulator.

**Comment by Yidada** [comment]
![image](https://cloud.githubusercontent.com/assets/12830571/20236743/375470ce-a8f9-11e6-8a7c-3f1551bdb624.png)

**Comment by Jack-Wen** [comment]
I got the same error when the application first run.  It run on simulator 9.0+ version is ok.
simulator: ios 8.4
RN version: 0.35

**Comment by ericvicenti** [comment]
I think the packager logs should show the real error in this case. Does it show anything? Also please try restarting the packager.

Syntax errors are quite common during development, so it is likely that you can fix this by finding the syntax error in your code. If it changes on different simulators then maybe it is because you're using a new feature in later versions of JSC, such as `Symbol`.

Feel free to re-open if you manage to find the actual error. Also, next time you post an issue, please include a simple example snippet of the code which causes the error!

**Comment by chuks008** [comment]
I have the same problem whenever I create a new RN project. Same red screen, same error message in the xcode console.

**Comment by kumarryogeshh** [comment]
Facing exactly same issue. New project, react-native run-ios. Crash. 
Not a single line of code written. Runs fine when I open Debug console.
react-native-cli: 1.0.0
react-native: 0.39.1
Simulator: iOS 6 /iOS 9.3

**Comment by chuks008** [comment]
@kumarryogeshh Yes, the simulator runs fine when I enable Remote JS Debugging.
react-native-cli: 1.3.0
react-native: 0.39.1
Simulator: IOS 7 / IOS 9.0

**Comment by chuks008** [comment]
Downgrading to RN 0.38.0 got rid of the error for me. Thanks @sreejithr !!
