### ISSUE TITLE
[Android] Custom fonts are not taken in android app

### ISSUE THREAD

**Issue by shanuks** [facebook/react-native#10926]
I am using below fonts in App:
* SourceSansPro-Light.ttf
* SourceSansPro-Regular.ttf
* SourceSansPro-Semibold.ttf

These fonts are not applied reflected in Android App and working fine with iOS.
For Android, these fonts are copied to app/src/main/assets/fonts folder.
In the CSS file:

cellTitle: {
        flex: 1,
        fontFamily: 'SourceSansPro-Regular',
        fontSize: 14,
        letterSpacing: 1,
        color: '#646464',
    },

Any additional configuration needed in android to work with custom fonts?

### Additional Information

* React Native version: 0.35.0
* Platform: Android
* Operating System: MacOS

**Comment by ericvicenti** [comment]
It seems super fragile, but it looks like the problem may be due to capital letters in your font files.

To figure this out I googled for 'react native android custom fonts', and found this article: https://medium.com/@gattermeier/custom-fonts-in-react-native-for-android-b8a331a7d2a7#.p57gxqd2j

Because this capitalized font filename issue isn't a total deal breaker, I'm going to close this issue for now. If this feels super important, free to put it into product pains and the community can vote and help prioritize
