### ISSUE TITLE
panResponder inside ScrollView

### ISSUE THREAD

**Issue by ronzilca** [facebook/react-native#10972]
### Description

I've got horizontal ScrollView with some thumbnails. I defined panResponder to my thumbnails in order to drag them on the screen. The problem is that I can't drag them outside the ScrollView - the thumbnail is become hidden when my finger is exceeds the borders of the ScrollView.

There is a way to make this work?

### Additional Information

* React Native version: 0.35
* Platform: both
* Operating System: MacOS

**Comment by xtutu** [comment]
Maybe you can add a invisible thumbnails out of scrollview.
when you start to drag thumbnails in scorllview, you just need to set the outside thumbanail visible and move it!
hope it can do the effect as you want.

**Comment by christopherdro** [comment]
@ronzilca Any updates?

**Comment by ronzilca** [comment]
@christopherdro Unfortunately no, for my knowledge you can make it work on iOS but not on Android..

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
