### ISSUE TITLE
ToolbarAndroid for ios?

### ISSUE THREAD

**Issue by itagakixt** [facebook/react-native#11026]
Hello react-native,

I have some code in android as follows.
return (
      <View style={styles.container}>
  			<**ToolbarAndroid**
          style={styles.toolbar}
          title="acount" />
        <View style={styles.body}>
          {content}
        </View>
      </View>
    );
To work in ios, have to change this code. As name ToolbarAndroid shows
This function is for Android.

Is there any reference as such a conversion?

Thanks 
Shoji Itagaki

**Comment by mkonicek** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

Toolbar is an Android concept so it's not supported on iOS, and iOS apps usually don't have toolbars. They have headers that are rendered as part of navigation.
