### ISSUE TITLE
Plans to integrate animatedjs/animated?

### ISSUE THREAD

**Issue by tuckerconnelly** [facebook/react-native#11029]
https://github.com/animatedjs/animated

I just added support for arbitrary values with `rgba` (like boxShadow on web) in `animatedjs/animated`, and just submitted a PR for nested `AnimatedStyle`'s in `react-native`.

Would be nice to consolidate efforts into a single, platform-agnostic lib.

**Comment by mkonicek** [comment]
By integrate do you mean merging this into RN core?

The philosophy so far is to keep the RN repo as small as possible and make it super easy to author and use 3rd-party modules so when you're building an app it makes little difference if you're importing something from 'react-native' or a 3rd-party module.

The reason is if we followed the approach of integrating all great modules into RN core the repo would grow very large - 'npm install react-native' would take longer even if you don't use all the modules, triaging GitHub issues and pull requests would become more tricky as they'd all be in a single repo.

**Comment by mkonicek** [comment]
Thanks for submitting the pull request!

**Comment by mkonicek** [comment]
From the docs of https://github.com/animatedjs/animated:

> The goal of this repo is to provide an implementation of the Animated library that is currently provided by React Native that can also be used by React in a web context.

n00b question (I don't have full context on what the library does): What would be the reason for adding this library to React Native which is focused on Android and iOS development?

**Comment by tuckerconnelly** [comment]
Ah no, I mean like--check out how react-native-web uses it :) https://github.com/necolas/react-native-web/blob/master/src/apis/Animated/index.js

So, move Animated _out_ of React Native and into its own module.
