### ISSUE TITLE
[Perf] Remove layout only views to optimize view hierarchy

### ISSUE THREAD

**Issue by sahrens** [facebook/react-native#1102]
Right now we create a view for every <View>/shadow node, which shouldn't be necessary since many shadow nodes are used only to compute layout or attributed text.

**Comment by sahrens** [comment]
This almost works, but mutating children is problematic.  Tracked internally as #6851970

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/perf-remove-layout-only-views-to-optimize-view-hierarchy

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
