### ISSUE TITLE
When i focus input the keyboard move up all the text

### ISSUE THREAD

**Issue by kfir91** [facebook/react-native#11040]
Hello i have a problem,
i use this:
```
				<ScrollView contentContainerStyle={styles.regScrollView}>
					<View style={styles.twoFields}>
						<View style={[styles.field, styles.halfInput, styles.lastField]}>
							<Text style={styles.label}>שם פרטי:</Text>
							<TextInput underlineColorAndroid='rgba(0,0,0,0)' maxLength = {40} style={[styles.textInput]} />
						</View>
						<View style={[styles.field, styles.halfInput]}>
							<Text style={styles.label}>שם משפחה:</Text>
							<TextInput underlineColorAndroid='rgba(0,0,0,0)' maxLength = {40} style={[styles.textInput]} />
						</View>
					</View>
					<View style={[styles.field]}>
						<Text style={styles.label}>דואר אלקטרוני:</Text>
						<TextInput underlineColorAndroid='rgba(0,0,0,0)' style={styles.textInput} />
					</View>
				</ScrollView>
```

but when i click to write on textInput the keyboard that open move up all the text 
like this:

https://s11.postimg.org/iss4dw2eb/Whats_App_Image_2016_11_21_at_12_10_37.jpg

(sorry about the hebrew language)...
```

**Comment by ericvicenti** [comment]
I googled and found this article which explains how `android:configChanges` can be changed to re-configure this behavior: http://blog.arjun.io/react-native/mobile/cross-platform/2016/04/01/handling-the-keyboard-in-react-native.html

Please post issues like this in StackOverflow next time, because this is not a bug with react native itself
