### ISSUE TITLE
Create picker with search bar

### ISSUE THREAD

**Issue by kfir91** [facebook/react-native#11061]
Hello i looking for plugin the when i click button or some text
its open modal like this:
https://s15.postimg.org/s1de2a3ln/image.png

actually - modal that show my list and i can search in the list...
i need it to like select to form

tnx a lot

**Comment by cyprusglobe** [comment]
maybe try something like this?
you might need to fork and make changes for your project.

https://github.com/tylermcginnis/react-native-algolia-dropdown

**Comment by kfir91** [comment]
@cyprusglobe  tnx i check it

**Comment by mkonicek** [comment]
Closing as answered.

This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
