### ISSUE TITLE
[Enhancement]: Support for Custom Keyboard Buttons

### ISSUE THREAD

**Issue by joncursi** [facebook/react-native#11074]
I'm trying to a build a keyboard that will make it as easy as possible to enter a web address. The Google Chrome app for iOS uses a customized keyboard to provide a lot of the special characters that are required in a web address on a secondary row at the top of the keyboard so that the user doesn't need to dig through the keyboard layers for these required characters.

![img_3128](https://cloud.githubusercontent.com/assets/4974609/20540584/b4963556-b0c7-11e6-8455-daf7c6a7ae48.png)

Such customization would be amazing if it could be brought into React Native! Any ideas on how we can achieve this?

**Comment by mkonicek** [comment]
You could build a keyboard module and publish it to npm so others can use it.

This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
