### ISSUE TITLE
I am tired of shaking the device

### ISSUE THREAD

**Issue by mkjangid** [facebook/react-native#11081]
Where are soft controls or shortcuts or keys or whatever ? Or a great IDE similar to android studio?

**Comment by linmic** [comment]
You might try https://github.com/niftylettuce/frappe for android development. As for iOS, there's no good one that I know of.

**Comment by ptomasroos** [comment]
You should ask this on Stackoverflow. Bugs are suppose to be reported here.

**Comment by mdamien** [comment]
If you're under cyanogen or similar, you can add a "menu" button to the navigation bar:

![image](https://cloud.githubusercontent.com/assets/1469823/20565465/ec25ed3e-b191-11e6-8e9d-9783776097a3.png)

the solution suggested by @linmic can also be replaced by a simple script:

```term
# simulate ctrl-shift-r
adb shell input keyevent 82 input keyevent 19 input keyevent 23
```

(taken from https://github.com/niftylettuce/frappe/blob/master/src/main.js#L28 )

**Comment by mkjangid** [comment]
I was wondering if they could bundle something with the framework itself basis OS. Makes life easier. Wont close it until I get a satisfying response.

**Comment by mkonicek** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
