### ISSUE TITLE
ScrollView scroll to textbox not working when app loses focus

### ISSUE THREAD

**Issue by ethandav0** [facebook/react-native#11100]
We are using a `KeyboardAvoidingView` inside a  `ScrollView `to allow our TextInputs to scroll above the keyboard when it's open. When functioning correctly, the `ScrollView `is automatically scrolled to the correct correct position to allow for the size of the keyboard. 

```
<ScrollView>
    <KeyboardAvoidingView>
          {this.props.children}
    </KeyboardAvoidingView>
</ScrollView>
```

However, when the application loses focus and then re-gains focus, this auto-scroll functionality breaks. Instead, when you focus a `TextInput`, the keyboard opens and covers it and no auto-scroll happens, this happens for the remainder of the app session. A force close of the app fixes it.

React Native version: 0.37.0
Platform: Android (iOS untested)

**Comment by mkonicek** [comment]
Can you reproduce this on [rnplay.org](https://rnplay.org/)? Please provide a link.

I'm not sure but should it be the other way round? `ScrollView` inside a `KeyboardAvoidingView`?

**Comment by christopherdro** [comment]
@facebook-github-bot no-reply

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
