### ISSUE TITLE
Alert Disappearing for an outside touch

### ISSUE THREAD

**Issue by swaroopa94** [facebook/react-native#11112]
HI 
I am using alert component in my application.
Its working fine in ios but in android when alert appears  and when I click on outside the alert is diappearing.
Here is my code:

`Alert.alert('XXXx', 'Password must contain 8 characters', [{text: 'OK'}]);`

**Comment by haibinyu** [comment]
set cancelable = false
`
Alert.alert('XXXx', 'Password must contain 8 characters', [{text: 'OK'}], { cancelable: false});
`

**Comment by mkonicek** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of React Native.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #react-native](http://stackoverflow.com/questions/tagged/react-native)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

**Comment by mkonicek** [comment]
Closed as @haibinyu answered.

**Comment by swaroopa94** [comment]
@haibinyu  But it is not Working for me..

React native - "0.25.1"

**Comment by haibinyu** [comment]
@swaroopa94  This feature was added in v0.33.0

**Comment by swaroopa94** [comment]
@haibinyu okay but how to solve my issue now.

**Comment by swaroopa94** [comment]
Here is my link to stackoverflow question:[http://stackoverflow.com/questions/40815473/alert-disappearing-for-an-outside-touch](url)
