### ISSUE TITLE
How to use custom animationType in Modal

### ISSUE THREAD

**Issue by kfir91** [facebook/react-native#11111]
Hello this is my code:
```
				<Modal
				animationType={"slide"}
				transparent={true}
				visible={this.state.modalVisible}
				onRequestClose={() => {this.setModalVisible(false)}}
				>
```

how i can use custom animationType?
now its slide from bottom to top
i want slide from right to left

how?

and how i close it when i click out of modal?

**Comment by nihgwu** [comment]
You'd better ask on Stackoverflow, `Modal` only supports slides/fade/none, for other types you can use Animated for custom animation, see `react-native-modal`

**Comment by mkonicek** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of React Native.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #react-native](http://stackoverflow.com/questions/tagged/react-native)? Post a link to your Stack Overflow question here, so that we don't lose track of it.

Closing as @nihgwu answered.
