### ISSUE TITLE
js stall

### ISSUE THREAD

**Issue by pvinis** [facebook/react-native#11139]
in the native animated example, what is a js stall, and when does it happen normally?

**Comment by mkonicek** [comment]
Check out detailed explanation here: https://speakerdeck.com/mkonicek/under-the-hood-of-react-native?slide=36, slides 36 and 37, and the slides before for more context.

This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
