### ISSUE TITLE
base64 string got from ImageEditor.cropImage(uri) have linefeed after each 76 characters.

### ISSUE THREAD

**Issue by linus87** [facebook/react-native#11142]
### Description

I launched "react-native run-android" on MAC 10.11.6 (15G1004). I found when I use ImageEditor.cropImage(uri) to crop an image, the base64 text of image is not as my expected. Base64 text of image should be a whole string. But I found there is a linefeed after each 76 characters. When I put it as a JOSN object value, and stringify the JSON object. Then I try to parse this JSON object. I will meet a error: Unexpected Token. If I use base64Text.replace("\n", "").replace("\r",""), then It's ok;

for example:
ImageStore.getBase64ForTag(url, (base64Data) => {
        let sImageBase64Data = "data:image/jpg;base64," + base64Data.replace(/\n|\r/g, "");
}

### Solution

Replace all linefeed and carriage-return by base64Data.replace(/\n|\r/g, "").

### Additional Information

* React Native version: 0.29
* Platform: Android
* Operating System: MacOS

**Comment by mkonicek** [comment]
Good find, thanks for reporting it! Note that RN releases older than latest are not supported, can you try if the bug is still present in the latest release? Would you be up for fixing it here?
https://github.com/facebook/react-native/blob/9ee815f6b52e0c2417c04e5a05e1e31df26daed2/ReactAndroid/src/main/java/com/facebook/react/modules/camera/ImageStoreManager.java

Found this: http://stackoverflow.com/questions/19952621/is-it-ok-to-remove-newline-in-base64-encoding

**Comment by joshyhargreaves** [comment]
I don't mind taking a look.

**Comment by wellmonge** [comment]
@leeight seems the issue  has been  solved on #11155 !?

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
