### ISSUE TITLE
RCTDirectEventBlock vs RCTBubblingEventBlock

### ISSUE THREAD

**Issue by pvinis** [facebook/react-native#11148]
what's the difference of the two?

**Comment by mkonicek** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

**Comment by pvinis** [comment]
I know it but I thought adding it as an issue is better because docs could be updated.
