### ISSUE TITLE
no information about AppRegistry anywhere on the internet !

### ISSUE THREAD

**Issue by alzalabany** [facebook/react-native#11158]
### Description

AppRegistry is not documented anywhere on react-native website nor on world wide web !

i'm trying to figure out usage of AppRegistry.registerComponent multiple times, possibility to launch various rootApps based on logged in status of user. there seem to be couple functions that can be used to do this, yet no documentation on em anywhere.

### Example What i'm trying to do.
. register a <login/> component and run login app. if user logged in successful, i want to destroy login app and run <App user={user} /> App.

### Reproduction
1. > react-native init awsome app
2. edit index.ios.js and duplicate `AppRegistry.registerComponent('Appname', () => App);` to `AppRegistry.registerComponent('App2name', () => App2);`

````
const App = props => <View><Text>App1</Text></View>
const App2 = props => <View><Text>App2</Text></View>

AppRegistry.registerComponent('Appname', () => App);
AppRegistry.registerComponent('App2name', () => App2);`
```

3. > react-native run-ios

App2 name will run successful, yet if we moved the App2 registerComponent inside constructor of App for example, App1 will be the one on the screen, and App2 will never run;

How can we register more than one root component and alternate between them if needed ?



* React Native version: 0.38
* Platform: both
* Operating System:MacOS

**Comment by mkonicek** [comment]
See the docs here: https://github.com/facebook/react-native/blob/master/Libraries/ReactNative/AppRegistry.js

Here's how it's called: https://github.com/facebook/react-native/blob/master/local-cli/templates/HelloWorld/android/app/src/main/java/com/helloworld/MainActivity.java#L13

You'd have to do the switching in native.

If you want to do that in JS it's probably easier to just register one component and make it render different components based on state.

This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

**Comment by alzalabany** [comment]
thanks, i ended up using wix/react-naviagation solution 👍  it allowed me to relaunch app whenever i needed. thanks for explanation 💯
