### ISSUE TITLE
[Android] Removing a View from card stack shifts everything up

### ISSUE THREAD

**Issue by amitverma** [facebook/react-native#11183]
This is definitely an issue with react-native android. Works like a charm for iOS. 

I have a stack of cards (fullscreen) absolutely position and using zIndex. I swipe the card up to slide it up out of the viewport. To save up on memory, I unmount every [ACTIVE-2] card. So essentially at any given point, only 3 cards are rendered in the app. [ACTIVE-1], [ACTIVE], [ACTIVE+1].

This works flawlessly in iOS. But when I unmount the [ACTIVE-2] card in android (by returning null in render), the cards shift up one level. So I see [ACTIVE+1] on the screen instead of [ACTIVE]. 

I have had to render a fullscreened absolutely positioned ```<View>``` instead of null to counter this effect. Thought I should mention this here.

**Comment by lacker** [comment]
Can you provide a reproduction of this with a rnplay.org app?

**Comment by christopherdro** [comment]
@facebook-github-bot no-reply

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
