### ISSUE TITLE
MapView annotation press event

### ISSUE THREAD

**Issue by metacortex** [facebook/react-native#1120]
I couldn't find anything about MapView press event.

Should I create custom component?

**Comment by brentvatne** [comment]
It looks like this isn't possible yet, do you want to try to implement it? See: http://stackoverflow.com/a/15297919/659988

Something like this on `RCTMapManager.m` (the delegate):

```objc
- (void)mapView:(MKMapView *)mapView didSelectAnnotationView:(MKAnnotationView *)view
{
    // Dispatch event through React stack
}
```

**Comment by dvcrn** [comment]
@brentvatne I tried my luck and implemented didSelectAnnotationView. Before opening a pull request I'ld like to know if this has been implemented the correct way since it is my first time hacking on react-native - https://github.com/facebook/react-native/compare/master...dvcrn:on-annotation-press

Though the question comes into my head how useful this is. My implementation only gives the marker long, lat, title and subtitle. With this alone, you can't really identify which marker in particular has been pressed. 

Nevertheless, let me know how to proceed with this :)

**Comment by brentvatne** [comment]
@dvcrn - Nice one! Closing so we can track this in the PR
