### ISSUE TITLE
ListView Header-Row group

### ISSUE THREAD

**Issue by theobouwman** [facebook/react-native#11214]
Why is a Seaction Header separated from a Row instead of making it a Group.

When it is a group, you can render each Section side by side in a grid like layout.

**Comment by lacker** [comment]
Yeah, it might be nicer in some use cases to be a group, but I think in general ListView is just not going to be the perfect solution for all lists. There are some other listview like projects you can check out; don't feel obliged to use ListView for all listlike things. Anyway we are trying to use github issues for bugs rather than feature requests so for now I am going to close this issue.
