### ISSUE TITLE
Provide timestamp in microseconds value

### ISSUE THREAD

**Issue by julienfouilhe** [facebook/react-native#11221]
### Description

Can you provide a value such as Node's `process.hrtime`, very useful when playing with sound for instance.

### Additional Information

* React Native version: 0.34.0
* Platform: both
* Operating System: MacOS

**Comment by lacker** [comment]
Hmm, how would this be implemented? You couldn't use the typical native modules setup because it requires asynchronous bridging between js <-> native.

**Comment by julienfouilhe** [comment]
@lacker Exactly, and I don't know enough of the inner mechanisms of react native to make a pull request with my own solution, hence why I'm asking in case someone has a solution :)

Thanks

**Comment by mehcode** [comment]
This actually exists already in React Native since v0.24. I've been using it for awhile but its not documented anywhere.

```js
const currentTimeInSecondsToNanoPrecision = global.nativePerformanceNow();
```

It's used in the internal [PerformanceLogger](https://github.com/facebook/react-native/blob/master/Libraries/Utilities/PerformanceLogger.js) module.

**Comment by jniac** [comment]
why is there not more information about that ? 
I really need that kind of tool to monitor my own function / performance. 
When you're dealing with animations, with 16ms for a frame, milliseconds are not small enough.
Nobody cares for performance ?

PS: in a navigator performance.now() is given relative to a time origin which is generally the page creation. In React Native what is the time origin ? (simple curiosity)

**Comment by FruitieX** [comment]
@jniac: After digging around in the source code for a while, I found out that `global.nativePerformanceNow()` seems to call the native functions [`CACurrentMediaTime()`](https://developer.apple.com/documentation/quartzcore/1395996-cacurrentmediatime) on iOS, and [`clock_gettime()`](https://linux.die.net/man/3/clock_gettime) on Android.

Both of these native functions appear to have up to nanosecond resolution, and from some quick testing it seems like `global.nativePerformanceNow()` returns a floating point number representing the amount of milliseconds since device boot on both platforms.

Good question as to why it's not documented, it seems like it would be useful in a lot of cases. Maybe there's something that we're missing here from the whole picture.
