### ISSUE TITLE
the Proxy can not use on Android but iOS is ok

### ISSUE THREAD

**Issue by TuomaXu** [facebook/react-native#11232]
### Description

I write code include Proxy. the sample code like this:

```
var defaultCache = {
  isWorking:true,
};

var cache = new Proxy(defaultCache, {
  set: function(obj, prop, value) {
    obj[prop] = value;
    return true;
  }
});

cache.isWorking = false;
```

the code in index.ios.js and index.android.js. the iOS is ok but run Android is bad.

![](http://7u2rl9.com1.z0.glb.clouddn.com/E9F574B86CB0DA3251436E4478569600.jpg)

### Additional Information

* React Native version:  0.38
* Platform: iOS is ok ,Android is bad
* Operating System:iOS in MacOS 10.12.1 , Android  Windows 7

**Comment by ide** [comment]
Proxies are not supported on Android or iOS 8 or 9 because the versions of JSC on those platform don't implement Proxies.

**Comment by warpech** [comment]
@ide Where is the JavaScriptCore for Android maintained? I would like to report an issue about this, or track the progress of that because this is a serious limitation.

**Comment by alshakero** [comment]
@ide any update on this?

**Comment by ide** [comment]
No updates but if you'd like to help financially sponsor the work to get this done please reach out to me and I will try to coordinate with a contractor whom I believe is especially well-equipped to work on this.

**Comment by warpech** [comment]
Is JavaScriptCore for Android part of React Native project or is it a separate dependency?

**Comment by ide** [comment]
It is a separate dep/repo but maintained under RN Android.

**Comment by warpech** [comment]
Thanks for the clarification.

ES6 Proxy is a language meta-programming feature (see many examples at https://github.com/mikaelbr/proxy-fun). There are more and more JavaScript projects like ours ([Palindrom](https://github.com/palindrom/palindrom)), that use ES6 Proxy.

As the Palindrom guys we are not directly interested in sponsoring that feature because we are fine providing an old version of our lib that uses dirty-checking instead of ES6 Proxy. We just wanted to let the core team of React Native know that ES6 compliance would be welcome in the Android version of React Native and saw a "Won't Fix". Which is a little bit surprising for a library that supports building apps with JavaScript using NodeJs and JavaScriptCore. NodeJs and JavaScriptCore both support ES6 Proxy for many months now.

Now I understand that it is not a "Won't Fix" but rather a "Someone fix this if this becomes a problem for you".

**Comment by alshakero** [comment]
I checked again today and `typeof Proxy` is still `undefined` in Android.

**Comment by Draccan** [comment]
Is someone who knows how to deal Proxy with Android or if there is a workaround?

**Comment by alshakero** [comment]
@Draccan there is no syncronous way. You might use dirty checking but that will only achieve async results.

**Comment by clintonjrobinson** [comment]
@Draccan This worked for us https://github.com/SoftwareMansion/jsc-android-buildscripts
