### ISSUE TITLE
_clearer is not a function error

### ISSUE THREAD

**Issue by alexkendall** [facebook/react-native#11297]
RN 0.39
![simulator screen shot dec 4 2016 8 58 24 pm](https://cloud.githubusercontent.com/assets/8241866/20871487/6a6f6604-ba64-11e6-920a-87f5bd7cf87a.png)

**Comment by eljago** [comment]
Does this happen when you turn on the remote JS debugger? I'm also getting this error, as well as the following: 
![screen shot 2016-12-17 at 4 15 01 am](https://cloud.githubusercontent.com/assets/2080977/21285150/b1ca98b6-c40f-11e6-8333-c12725d32287.png)

It happens to me only when the remote JS debugger is turned off.

**Comment by arunshan** [comment]
@eljago @alexkendall Could you guys resolve this issue? I am new to firestack and am stuck with this issue. This is in regards to the `window` object that is not available in react native.

**Comment by sprmn** [comment]
This is not a react native issue, but a firestack issue, related to fullstackreact/react-native-firestack#191. The issue should probably be discussed over there and closed here. 

FYI, the fix is a bit hard to find, but applying [this](https://github.com/fullstackreact/react-native-firestack/commit/bfa9ed31c8d9145b508d5e093fd90c59211b4500) change manually will fix the for now. 

In other words, you'll have to open `node_modules/react-native-firestack/lib/utils/window-or-global.js` and replace `{}` on the fifth line with `this`.

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
