### ISSUE TITLE
[Packager 0.39] RN Packager doesn't see changes inside node_modules

### ISSUE THREAD

**Issue by xxsnakerxx** [facebook/react-native#11301]
### Description

If I changing a file in my app folder, livereload and HMR works! But LR and HMR doesn't work if I changing a file inside node_modules directory (if stop packager process and start it again, the changes are applying)

With RN 0.38 - 0.38.1 all works fine!

### Additional Information

* React Native version: 0.39
* Operating System: Mac OS Sierra
* Watchman: 4.7.0
* Node: 6.9.1

**Comment by asciiman** [comment]
I'm experiencing this too after upgrading to RN 0.39.
watchman 4.5.0

**Comment by Thomas101** [comment]
We see exactly the same. Things that don't work our end...

* Manually changing a file in node_modules *(I know, I know, very bad!!)*
* npm install
* npm install -f my_package_name
* Changing a file in the main repository (which does get its changes reloaded) doesn't trigger the changes in node_modules to be reloaded

This is on Mac OS Sierra. Watchman 4.7.0. Node 6.3.1. React Native 0.39

**Comment by Exilz** [comment]
I'm experiencing this too with RN 0.39

**Comment by Clawg** [comment]
Same issue for me.  Has anyone made any progress on this.

**Comment by farwayer** [comment]
@cpojer Can this regression be introduced by the packager refactoring?

**Comment by cpojer** [comment]
yes, that is most likely the issue.

**Comment by jhen0409** [comment]
Looks like the problem is related to `jest-haste-map`, the [whilelist using `providesModuleNodeModules`](https://github.com/facebook/jest/blob/c32e74b6a84494973d3f3f3fffe116dd3fdcf35c/packages/jest-haste-map/src/index.js#L224) (use for [_isNodeModulesDir](https://github.com/facebook/jest/blob/c32e74b6a84494973d3f3f3fffe116dd3fdcf35c/packages/jest-haste-map/src/index.js#L681-L692)), so it will only process `react-native`, `react-native-windows` file changes. (JestHasteMap in [node-haste](https://github.com/facebook/react-native/blob/efc12cd5bffcc5161f7002a63506be893b8794e1/packager/react-packager/src/node-haste/index.js#L164))

It's broken my module development, a temporarily workaround is add the module name to [providesModuleNodeModules](https://github.com/facebook/react-native/blob/72157cf99164d00c7a14b6b9ca51b406080b5265/packager/defaults.js#L36), or can we provide an option for [it](https://github.com/facebook/react-native/blob/master/packager/react-packager/src/Resolver/index.js#L68)?

**Comment by Exilz** [comment]
Any news ? This is a major issue :(

**Comment by Shenenkaka** [comment]
@jhen0409 temporary fix, thanks

**Comment by Exilz** [comment]
@cpojer when's jest latest version going to be out ? I guess once it's out, we will need to wait a newer release of react-native with the latest jest version as its dependency, right ?

**Comment by cpojer** [comment]
soon!

**Comment by fadookie** [comment]
@cpojer Thanks for getting this fixed? Any idea when react native will switch to jest 19?
