### ISSUE TITLE
how to animate 'opacity' from 1.0 to 0.2?

### ISSUE THREAD

**Issue by heimasi** [facebook/react-native#1132]
AnimationExperimental.startAnimation({
      node: this.refs.logos,
      duration: 500,
      easing: 'easeInOutQuad',
      property: 'opacity',
      toValue: 0.2,
});

this is my code. when the animation begin, its's opacity will be changed to 0.0 firstly, then it is changed from 0.0 to 0.2. How to animate the opacity from 1.0 to 0.2? thanks

**Comment by frantic** [comment]
Look at AnimationExperimental module, it has `fromValue` property you can use. Please reopen if it doesn't help. cc @a2

**Comment by heimasi** [comment]
In RCTAnimationExperimentalManager.m:
219: NSValue *fromValue = [view.layer.presentationLayer valueForKeyPath:keypath];
220: NSLog(@"fromvalue  %@",fromValue); //added by myself

console:  fromvalue 1

It should be ok, but during the animation running, the view's opacity is still changed to 0.0 firstly. If I miss something?

**Comment by muzix** [comment]
@heimasi @frantic 
I'm also had same problem. Opacity animating correctly from 0.0 to 1.0 but it's doesn't work when animating from 1.0 back to 0.0

So i looked into RCTAnimationExperimentalManager.m and i think it's because of "fromValue" not being typecast correctly as "toValue".

switch (typeName[0]) {
#define CASE(encoding, type) \
          case encoding: { \
            type value; \
            [toValue getValue:&value]; \
            toFields[0] = value; \
            break; \
          }

          CASE('i', int)
          CASE('I', unsigned int)
          CASE('s', short)
          CASE('S', unsigned short)
          CASE('l', long)
          CASE('L', unsigned long)
          CASE('q', long long)
          CASE('Q', unsigned long long)

#undef CASE

        default:
          [toValue getValue:toFields];
          break;
      }

moreover, I think float and double datatype is missing in above code 
          CASE('f', float)
          CASE('d', double)

So, i commented out line: [fromValue getValue:fromFields];
and replace it with below:
switch (fromTypeName[0]) {
#define CASE(encoding, type) \
          case encoding: { \
            type value; \
            [fromValue getValue:&value]; \
            fromFields[0] = value; \
            break; \
          }
                            
          CASE('i', int)
          CASE('I', unsigned int)
          CASE('s', short)
          CASE('S', unsigned short)
          CASE('l', long)
          CASE('L', unsigned long)
          CASE('q', long long)
          CASE('Q', unsigned long long)
          CASE('f', float)
          CASE('d', double)
                
#undef CASE
          default:
            [fromValue getValue:fromFields];
            break;
        }

Then, animation worked correctly.

**Comment by heimasi** [comment]
Thank you very much, @muzix , It works! Cool!
