### ISSUE TITLE
Cannot find module 'invariant' - react-native-cli

### ISSUE THREAD

**Issue by frnk94** [facebook/react-native#11327]
![image](https://cloud.githubusercontent.com/assets/11723501/20942361/14de700c-bbc9-11e6-8b7a-554ba1c894be.png)

### Description

When trying to create a new react-native project there an error while installing packages.

### Reproduction

react-native init <project-name>

### Additional Information

* React Native version: react-native-cli: 1.0.0
* Operating System: macOS Sierra 10.12.1

**Comment by frnk94** [comment]
#11324 Related ?

**Comment by Cfiddle** [comment]
Reproduced over here too. Trying to init a new project.

**Comment by herudi** [comment]
Same error with me.
Cannot find module 'invariant'

**Comment by haustraliaer** [comment]
We get it as well when "running" the react-native Examples (latest master) in Xcode.

react-native-cli: 1.3.0
macOS Sierra: 10.12.1

... but only on one of our machines (the other is fine with the same versions).

Fixed it here by running `npm i --save-dev invariant` on the `react-native` cloned repo, which is obviously a temporary solution, and I doubt that would work with the CLI.

**Comment by herudi** [comment]
work for me.
`npm cache clean`
`npm uninstall react-native-cli -g`
`npm install react-native-cli -g`
`react-native init myapp`

**Comment by nuthinking** [comment]
+1 :S

**Comment by skonves** [comment]
Same issue here.  I tried herudi's solution and still got the same error, but it worked after updating npm to the latest version (`npm install npm@latest -g`).

Old npm version: 2.15.8
New npm version: 4.0.3

**Comment by frnk94** [comment]
> npm cache clean
npm uninstall react-native-cli -g
npm install react-native-cli -g
react-native init myapp

It worked for me but it installed package dependencies through yarn v0.16.1

**Comment by rogueSnake** [comment]
Like skonves, I updated npm to 4.0.3 and tried herudi's solution. No luck for me, but I was able to get it working by just installing invariant globally. Kinda hacky, but it works for me.

> npm install -g invariant

**Comment by Cfiddle** [comment]
Like haustraliaer, `npm i --save-dev invariant` worked for me.

**Comment by devangpandya20** [comment]
`npm i --save-dev invariant` worked for me

**Comment by gnanaprakash** [comment]
skonves solution worked for me

**Comment by zerocoolys** [comment]
@skonves  `npm install npm@latest -g`   solution works for me.

**Comment by Tim77277** [comment]
npm i --save-dev invariant work for me.

**Comment by Nopzen** [comment]
@herudi  +1

@skonves +1 for figuring that older NPM versions have an issue here great job :)

**Comment by matiasgq** [comment]
This worked for me:
```- npm cache clean
- npm uninstall react-native-cli -g
- npm install npm@latest -g
- npm install react-native-cli -g
- react-native init myapp```

**Comment by demonhunterunderdarkness** [comment]
upgrade npm works for me ,thanks a lot~

**Comment by simonfl3tcher** [comment]
@skonves also worked for me, thanks!

**Comment by antonis80** [comment]
@skonves npm install npm@latest -g solution works for me.

**Comment by kythanh** [comment]
Upgraded npm then follow @herudi commands worked for me.
```
- npm install npm@latest -g
- npm cache clean
- npm uninstall react-native-cli -g
- npm install react-native-cli -g
- react-native init myapp
```

**Comment by NineCity** [comment]
@skonves It worked for me too,thanks

**Comment by sumitk** [comment]
`npm i --save-dev invariant `
works for me

**Comment by Noitidart** [comment]
Upgrading npm with `npm install npm@latest -g` fixed for me.

**Comment by brobey8** [comment]
A note for anyone getting this issue with `anymatch` not being found. Doing a `npm i --save-dev anymatch` fixes the problem. Seems like this may work for a few packages not being found.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
