### ISSUE TITLE
Local static images are disappearing when app is in use (Android only)

### ISSUE THREAD

**Issue by marxsk** [facebook/react-native#11343]
### Description

In my application there are dozens of images (~70MB in JPEG format) bundled with application, so it can work offline. 

On the real devices (multiple, various Android releases) images are mostly shown after application starts but after few scenes, they are not displayed. This happends quite randomly but with increased occasionality. Displaying images is not consistent even on one phone. When bundle.js is used there are no issues at all. 

Adding android:largeHeap="true" to manifest did not change anything.

I have also opened bounty on stackoverflow. But only response did not help, so it should not be trivial bug on my side.

http://stackoverflow.com/questions/40847641/static-images-are-not-displayed-every-time

### Reproduction
    Bundle images with application and use them via require. 

    const IMAGES = [
         require('../../images/animals/agamaKocincinska/01.jpg'),
         require('../../images/animals/agamaKocincinska/02.jpg'),
    ];

     <Image
            source={this.props.thumbnails[this.props.index]}
            resizeMode='cover'
            style={this.props.thumbnailStyle}
      />

### Solution

[FILL THIS OUT: What needs to be done to address this issue? Ideally, provide a pull request with a fix.]

### Additional Information

* React Native version: 0.33
* Platform: Android
* Operating System: MacOS

**Comment by qpowell** [comment]
+1. I'm having a similar issue trying to get some images rendering in my app. 

I've got a `ScrollView` that I'm using for onboarding like:

```javascript
<ScrollView ref={(ref) => this._scrollView = ref} horizontal scrollEnabled={false}>
  <OnboardingStep image="intro" />
  <OnboardingStep image="step1" />
  <OnboardingStep image="step2" />
  <OnboardingStep image="step3" />
</ScrollView>
```

Inside the `OnboardingStep` component, I have a function that returns the image source:

```javascript
function getStepImage(name) {
  switch (name) {
    case 'intro':
      return require('../../img/01-intro.png');
    case 'step1':
      return require('../../img/02-account_name.png');
    default:
      return require('../../img/01-intro.png');
  }
 // etc...
}
```

...and the source is included using `<Image source={getSourceImage(this.props.name)} resizeMode="contain"/>`.

I have *8* images that I use in this process. When I have the `resizeMode` set to contain, there are always 2 images that don't display. These 2 images aren't the same ones each time.

If I remove the `resizeMode` prop completely, all of the images load.
If I leave the `resizeMode` prop but remove some of the steps so that I have 5 instead of 8, all of the images consistently load.

This works 100% of the time for me on iOS. I haven't tried the heap size change to the manifest yet, but I'll give it a shot :)

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/local-static-images-are-disappearing-when-app-is-in-use-android-only
