### ISSUE TITLE
iOS [RCTShadowText buildTextStorageForWidth: widthMode:]  will cause app infinite-loop and memory-blast in a very small probability 

### ISSUE THREAD

**Issue by ywz2010** [facebook/react-native#11412]
We use react-native 0.33.0. And we find that in some situation, the memory will non-stop increase  and cause the app crashed. At the meaning time the react-native page is just empty. This often happen after we upgrade the app from appStore.

It happen by chance when I run app in Xcode , and I recored the thread and find that  `[RCTShadowText buildTextStorageForWidth:width widthMode:widthMode]  ` cause app infinite-loop and memory-blast. 
￼
I  find it like #7851, but I can't reproduce it.
![14814384939130](https://cloud.githubusercontent.com/assets/5178436/21087602/52280412-c062-11e6-8d86-df3d0e30f53a.jpg)
￼

**Comment by littlesome** [comment]
Hi I got the same error. I think it's caused by buildTextStorageForWidth width passed in is NaN. I just add a check and return, things works and not get this stuck again. This is a temp workaround, maybe someone can help to check why NaN is passed in.

**Comment by camellieeee** [comment]
+1

**Comment by ajwhite** [comment]
I noticed this got closed, but not seeing any commits, PRs, or other issues linking to this.

Did this get fixed, and if so, can the diff be linked?

We're seeing noticeable growth by this method as well. `8.5KiB` every so often in the app. 90 persists within a 50 minute window.

**Comment by ywz2010** [comment]
@ajwhite  I closed this issue because I used some protective code and this never happen again. But I still don't know why this happen and what the protective code will cause in this case, so I don't submit PR.

In my situation, `shadowQueue` is busy, so the RN page will not render any new View.
   
The protective code is  inspired by littlesome.


``` Objective-C
- (NSTextStorage *)buildTextStorageForWidth:(CGFloat)width widthMode:(YGMeasureMode)widthMode
{

... 

  textContainer.maximumNumberOfLines = _numberOfLines;
  textContainer.size = (CGSize){widthMode == YGMeasureModeUndefined ? CGFLOAT_MAX : width, CGFLOAT_MAX};

  // protective code ↓
  if (isnan(textContainer.size.width)) {
    textContainer.size = (CGSize){CGFLOAT_MAX, CGFLOAT_MAX};
  }
   // protective code ↑

  [layoutManager addTextContainer:textContainer];
  [layoutManager ensureLayoutForTextContainer:textContainer];

  _cachedTextStorageWidth = width;
  _cachedTextStorageWidthMode = widthMode;
  _cachedTextStorage = textStorage;

  return textStorage;
}
```

**Comment by ajwhite** [comment]
Interesting. I've observed a leak in this specific function and attempted to patch in something to mitigate.

I would observe that any time the font width changes (which brings us here), a `Malloc 8.5Kib` would be retained. It sounds related to what you experienced. 

I attempted to unlink the `NSLayoutManager` and `NSTextContainer` seeing somehow if there was any references being held after `_cachedTextStorage` becomes reassigned. No dice.

_Note: we're running the [0.27 version of this file](https://github.com/facebook/react-native/blob/0.27-stable/Libraries/Text/RCTShadowText.m#L156-L181), before Yoga. However, I don't see that as an offender._

 ```obj-c
// called before _cachedTextStorage reassignment and when invalidation occurrs
-(void)cleanupTextStorageReferences
{
  if (!_cachedTextStorage) {
    return;
  }
  
  NSArray<NSLayoutManager *> *layoutManagers = _cachedTextStorage.layoutManagers;
  
  for (int i = 0; i < layoutManagers.count; i++) {
    
    NSArray<NSTextContainer *> *textContainers = layoutManagers[i].textContainers;
    for (int j = 0; j < textContainers.count; j++) {
      [layoutManagers[i] removeTextContainerAtIndex:j];
    }

    [_cachedTextStorage removeLayoutManager:layoutManagers[i]];
  }
}
```

In my case I had a clock on the display, and as the numbers ticked every minute, `buildTextStorageForWidth:widthMode:` would leak due to the characters changing and causing slight width changes. Given that, I assume a reproducible example would just be a `Text` component with growing content.

----

I'm going to give your version a shot tomorrow. Thanks for sharing, as I didn't see a infinite loop on my end and may not have came to the same conclusion that you have.

I'd urge you to reopen this issue and update the description to include the protective code that solved your problem. Every user of the library is affected by this nasty one. `8.5KiB` is no joke!

**Comment by ywz2010** [comment]
@ajwhite  Thanks for you advise. But I don't want to reopen this issue now. It  was on v0.33.0, and now the latest version is v0.53.0-rc. I have changed job and not focus in React Native now, so I can't check if the buy still exist. If some one say this happen in the latest version, I will reopen it.
