### ISSUE TITLE
_CLSNSLog -- Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by peacechen** [facebook/react-native#11432]
### Description

Our project was upgraded to React Native 0.39.2 (previously 0.34) and is now getting this error when trying to run in the simulator using the command _react-native run-ios_:

> Undefined symbols for architecture x86_64:
> "_CLSNSLog", referenced from:
> -[SMXCrashlytics log:] in libSMXCrashlytics.a(SMXCrashlytics.o)
> "OBJC_CLASS$_Answers", referenced from:
> objc-class-ref in libSMXCrashlytics.a(SMXAnswers.o)
> "OBJC_CLASS$_CLSStackFrame", referenced from:
> objc-class-ref in libSMXCrashlytics.a(SMXCrashlytics.o)
> "OBJC_CLASS$_Crashlytics", referenced from:
> objc-class-ref in libSMXCrashlytics.a(SMXCrashlytics.o)
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 

Oddly, building from Xcode works. I've checked to make sure that _libSMXCrashlytics.a_ is included under the _Link Binary with Libraries section_. Also tried adding _SMXCrashlytics.m_ to _Compile Sources_.

### Reproduction

Use _react-native-fabric_ in the project.  Run _react-native run-ios_ from the command line.

### Solution

I've tried the suggestions in #85 to no avail.
The PR's in react-native-fabric doesn't resolve it.
https://github.com/corymsmith/react-native-fabric/pulls

### Additional Information

* React Native version: 0.39.2
* Platform: iOS
* Operating System: OSX 10.12 Sierra, XCode 8.1

**Comment by lacker** [comment]
Can you get `react-native-fabric` to work on a new app that you create from scratch? Figuring that out would let us determine whether it's a problem in the upgrade process, or a problem in react-native-fabric + 0.39 compatibility.

**Comment by christopherdro** [comment]
@facebook-github-bot no-reply

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
