### ISSUE TITLE
onEndReached is not called on Android

### ISSUE THREAD

**Issue by aterribili** [facebook/react-native#11489]
I'm trying to implement endless listview on **Android** using the `ListView` component, and both methods `onScroll` and `onEndReached` are not been fired.

### Code
```
        <ListView
          dataSource={ this.state.dataSource }
          onEndReached={() => {console.log('fetch more')}}
          onEndReachedThreshold={10}
          initialListSize={ 20 }
          onScroll={() => { console.log('onScroll') }}
          renderRow={(rowData) => <ProductRow {...rowData} /> }
        />
```

### Additional Information

* React Native version: `0.38.0` and `0.39.0`
* Platform: Android
* Operating System: MacOS

**Comment by Pilon** [comment]
+1

**Comment by viton** [comment]
+1

**Comment by tiagolimaelo7** [comment]
+1

**Comment by ptomasroos** [comment]
We have no problems with this on RN 0.38.0
Running in production without any problems.

**Comment by aterribili** [comment]
Can you tell me what I'm doing wrong @ptomasroos ?

**Comment by Pilon** [comment]
Hi @ptomasroos, I work with @aterribili. He forgot to mention that we place the react native view inside a `Fragment`.

**Comment by lacker** [comment]
Can you provide a sample app like on rnplay.org that reproduces this problem? Without the ability to repro it's going to be hard for anyone else to figure this out.

**Comment by aterribili** [comment]
When I use `ReactActivity` the `onEndReached` of `ListView` is triggered, but when I use `AppCompactActivity` and `Fragment` it's doesn't work.

**Comment by felagund18** [comment]
```onEndReached``` is not called even if i use ```ReactActivity``` on Android..., nor ```onScroll``` is called

**Comment by Chren** [comment]
+1, any solution?

**Comment by felagund18** [comment]
I am using NativeBase.io, i could not even get these ```onEndReached, onScroll``` function called... (Is NativeBase causing this?)

But on fresh new install of ReactNative, ```onScroll``` function gets called. (Not tested ```onEndReached```)

**Comment by aiyidu** [comment]
I am using React Native 0.39.2 on Android
onScroll works but onEndReached never called

**Comment by rocwangv** [comment]
+1

**Comment by Exilz** [comment]
Same problem with RN 0.41

**Comment by MrPluto** [comment]
+1 on 0.41.2 . onendreached just called one time

**Comment by MrPluto** [comment]
+1 on 0.41.2.  HEEEEEELP

**Comment by felagund18** [comment]
Any nested ScrollView?

```
<ScrollView>
    <ScrollView>
    </ScrollView>
</ScrollView>
```
In this case, onEndReached or onScroll function will not be called on 2nd level of ScrollViews...

**Comment by sexykodo** [comment]
0.43.1 and Flatlist,  onEndReached never called on Android

**Comment by stonecold123** [comment]
Please fix this. It never gets called on Android in 0.43.

**Comment by stonecold123** [comment]
@sexykodo 
I'm getting the same problem. The only way to get it work in my case is setting the height explicitly to the flatlist, like 
````
    <View style={{flex: 1}}>
          <FlatList
               onEndReached={this._onEnd.bind(this)}
               onEndReachedThreshold={2}
               keyExtractor={(item, index) => index}
               data={items}
               numColumns={2}
               style={{height:Dimensions.get("window").height - 100}}
               renderItem={this._renderItem.bind(this}/>
    </View>
````
 which is a very bad solution. Have you found any solutions?

**Comment by sexykodo** [comment]
I actually got this working quite well playing with onEndReachedThreshold prop.
On IOS I set it to 0 and on Android to 1.

const isIOS = Platform.OS === 'ios';
...
onEndReachedThreshold={isIOS ? 0 : 1}

**Comment by SoundBlaster** [comment]
@sexykodo you are my release saviour

**Comment by slorber** [comment]
Hi,

I was able to reproduce this behavior too.

It happens notably when I'm using the pageSize attribute:

pageSize={this.state.layout.columns * this.props.pageRows}

I do this because my ListView is actually a gallery of pictures and there are 3 pictures per row. When I remove the pageSize attribute it works fine

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
