### ISSUE TITLE
state data bind fails to trigger child prop with a large number of children / state objects

### ISSUE THREAD

**Issue by peacechen** [facebook/react-native#11501]
### Description

This is an odd duck that I haven't gotten any hits from a web search.  React Native's data bind appears to fail when there are a large number of state objects and/or children.  The children live in a ScrollView and have props bound to the parent's state.

### Reproduction

_this.state.inventory_ is updated when the component receives props.  _inventory_ is an array of _renderRow()_ components. This works as expected.

_get_times()_ updates _this.state.expanded_ which updates the appropriate Times component.  _expanded_ is an object containing fields named _[rowData.id + "\_timeslots"]_ for each item in the ScrollView.  I was concerned that a single large state object might be the culprit, but changing them to their own individual objects directly under _state_ didn't fix it.

When there are a large number of items in the ScrollView, updating _this.state.expanded_ doesn't trigger the \<Times\> component's _componentWillReceiveProps()_ callback.  It does work when there are about 8 or fewer items in the ScrollView.

```
renderRowHeader (rowData) {
  return (
	<View style={styles.rowHeader}>
		<ListItem
			key={rowData.id}
			title={rowData.organization.name}
			subtitle={rowData.name}
			avatar={ {uri: rowData.image_url } }
			onPress={this.show_details(rowData)}
		/>
		<CalendarStrip
			iconStyle={styles.hidden}
			useIsoWeekday={false}
			onDateSelected={(date) => { this.get_times(date, rowData); } }
		/>
	</View>
  )
}

renderRow (rowData) {
  return (
	<ExpandablePanel
		expanded={this.state.expanded[rowData.id]}
		header={this.renderRowHeader(rowData)} buttonColor="#0F0"
	>
		<Times timeslots={this.state.expanded[rowData.id + "_timeslots"]} inventory={rowData}/>
	</ExpandablePanel>
  )
}

render() {
  return (
	<View style={styles.container}>
		<Text>My Title</Text>
		<ScrollView>
			{this.state.inventory}
		</ScrollView>
	</View>
  );
}
```

### Solution

Props should be passed from state to children when there are more than 8 items in the ScrollView.

### Additional Information

* React Native version: 0.34, 0.39
* Platform: iOS simulator and real device
* Operating System: OSX

**Comment by lacker** [comment]
Your sample code is confusing to me. Can you provide the whole code for the component? From this existing code it's not clear to me why you would expect anything to update when you update `this.state.expanded`, since `render` doesn't refer to `this.state.expanded`.

In general, the way to think about relating a child's props to the parent's state is not "binding" because it doesn't work like an event listener. It's just that when you change the parent, it will normally render a new element containing different props for the child. To debug it's probably most useful to figure out what element tree is being rendered both before and after when you expected to see a change but didn't.

**Comment by peacechen** [comment]
You hit the nail on the head.  I flattened the state references and the data binding works as expected.  I do believe that nested state data binding exposes a corner case which should be addressed in one of 3 ways:
- always work even with larger quantity of state & components.
- never work regardless of the quantity of state & components.
- Log a warning/error to the console when this scenario occurs.

The current behavior of working sometimes, silently failing other times is amongst the hardest to debug. 

Here is how the bug is triggered.  The root render() is
```
	<View style={styles.container}>
		<Text>My Title</Text>
		<ScrollView>
			{this.state.inventory}
		</ScrollView>
	</View>
```

_state.inventory_ is an array of _renderRows()_ which looks like
```
	<ExpandablePanel
		expanded={this.state.expanded[rowData.id]}
		header={this.renderRowHeader(rowData)} buttonColor="#0F0"
	>
		<Times timeslots={this.state.expanded[rowData.id + "_timeslots"]} inventory={rowData}/>
	</ExpandablePanel>
```

The root render() doesn't reference _state.expanded_ directly, but its children do.  Curiously, the state data binding works when there are a relatively small number of children (approx <8).  It fails as the number of children increase.

**Comment by lacker** [comment]
I suspect the number of children is a red herring which is making you jump to the wrong conclusion. This seems like a generic React issue rather than a React Native issue - you expect a re-render to update, but something is short-circuiting it.

One issue that might or might not be related, shouldn't you set a `key` on the `ExpandablePanel` since you're rendering a list of them?

So you know that the `Times` component doesn't receive new props. Does the `ExpandablePanel` receive new props? Perhaps the `ExpandablePanel` is deciding not to update for some reason.

**Comment by peacechen** [comment]
You're correct again, RN warned about the missing key prop in `ExpandablePanel`.  Adding that didn't resolve the bug though. 

Neither the `ExpandablePanel` nor `Times` components fired their `componentWillReceiveProps()` callbacks.  It doesn't sound like `ExpandablePanel` is gating the binding, otherwise it would at least receive props.

**Comment by lacker** [comment]
OK so the key to understand this is that there is no "binding" in React. React doesn't bind views to models by listening to events, like many other UI frameworsk di. So it doesn't automatically know when things change at any point in the tree. Instead, React walks along the tree checking what components need to change, and if it thinks a particular node doesn't need to update, then it will just skip all the children.

So if the `ExpandablePanel` isn't rerendering then that's a real problem here. Checking `componentWillReceiveProps` doesn't seem like it's quite enough to verify what's happening though. I would log the return value of `render` in your root component and in `ExpandablePanel` and try to figure out where the second render is stopping.

**Comment by peacechen** [comment]
React advertises its one-way data binding as one of its advantages.  I agree that their implementation is significantly different than event-based data binding of other view libraries, particularly the template-based binding used by popular frameworks such as Angular.  Thanks for clarifying and reminding me of this distinction :)

What do you feel would be a better nomenclature than React's one-way data binding?

I've found experimentally that React's render is reliable for state bindings one level deep.  For instance
`render ( subRenderMethod() )`

Where subRenderMethod() directly references state.  However, if it goes deeper
`render ( subRenderMethod( subSubRenderMethod() ))`

Where subRenderMethod() doesn't reference state directly, but subSubRenderMethod() does, then the React's tree walking can break down.

**Comment by lacker** [comment]
I would just not think about it in terms of state bindings or sub-render-methods, I think both of those are confusing you. Just look at what components you have and what their `render` function returns. In this case I would log the return value of render in your root component and in ExpandablePanel and try to figure out where the second render is stopping.

At this point I think it is reasonably evident that there is not a React Native bug here, so I'm going to close the issue, but if you would still like help debugging then I can help - just comment with the results of logging render output.
