### ISSUE TITLE
A resolution for 'Print: Entry, ":CFBundleIdentifier", Does Not Exist'

### ISSUE THREAD

**Issue by zhoulinxiang** [facebook/react-native#11508]
### Description

react-native:0.39.2
xcode:7.0

react-native run-ios ,a error is 

<img width="1055" alt="2016-12-16 6 46 03" src="https://cloud.githubusercontent.com/assets/4335918/21260280/1d797046-c3c0-11e6-8e39-e8cecda6ec52.png">

then,i build in xcode7.0,find some error are

<img width="866" alt="2016-12-16 5 06 11" src="https://cloud.githubusercontent.com/assets/4335918/21257252/09971186-c3b2-11e6-8f7b-5e90275673a6.png">

Because in 
<img width="382" alt="2016-12-16 5 08 44" src="https://cloud.githubusercontent.com/assets/4335918/21257318/7328eb42-c3b2-11e6-9d92-f65b1570fa66.png">

<img width="643" alt="2016-12-16 5 08 47" src="https://cloud.githubusercontent.com/assets/4335918/21257321/755c0408-c3b2-11e6-9e20-343453a4ad78.png">

 ios 9 ,UIUserInterfaceIdiom don't support UIUserInterfaceIdiomTV and UIUserInterfaceIdiomCarPlay.

so,you can comment those lines in node_modules/react-native/React/Base/RCTPlatform.m,also,you can update your xcode,then,it works

**Comment by lacker** [comment]
Are you just getting this error when running a new app created directly from `react-native init`?

**Comment by zhoulinxiang** [comment]
@lacker yeah,just react-native init and run-ios

**Comment by xuanskyer** [comment]
same Q.

react-native-cli: 2.0.1
react-native: 0.40.0
Xcode :Version 7.1 (7B91b)

**Comment by 0captain** [comment]
`Found Xcode project AwesomeProject.xcodeproj
We couldn't boot your defined simulator due to an already booted simulator. We are limited to one simulator launched at a time.
Launching iPhone 6 (iOS 10.2)...
Building using "xcodebuild -project AwesomeProject.xcodeproj -configuration Debug -scheme AwesomeProject -destination id=DC854AE2-0ABD-4991-B967-F3B1D064D40F -derivedDataPath build"
warning: destination option not implemented
warning: custom derived data path not implemented

xcodebuild(14414,0x7fffddb8c3c0) malloc: *** error for object 0x7f99ab48f278: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug

Installing build/Build/Products/Debug-iphonesimulator/AwesomeProject.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/AwesomeProject.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist`


* react-native-cli@2.0.1
* node v7.1.0
* xcode 8.2.1

**Comment by franzejr** [comment]
@zhoulinxiang this solution worked for me!

**Comment by jasperkuperus** [comment]
I had the exact same error after just running:

```
react-native init MyProject
react-native run-ios
```

Turns out one of the projects I work on was using port 8081. Killing that project and making 8081 available again solved it for me.

Maybe the error could be clarified. The `CFBundleIdentifier, Does Not Exist` did not in any way point me in the right direction. Running it in Xcode gave me a better error:

```
Connection to localhost port 8081 [tcp/sunproxyadmin] succeeded!
Port 8081 already in use, packager is either not running or not running correctly
Command /bin/sh failed with exit code 2
```

**Comment by dotansimha** [comment]
This error is not your main error, it's just a side effect of a failed build. 
The `CFBundleIdentifier` is not found, because in most of the times the `Info.plist` does not exists at all, but the react-native packager still try to execute the app, causing this error to show.

Few tips to debug this issue:
* Update your XCode to the latest version.
* Look at the log - in most of the times you will see `BUILD FAILED` somewhere - try to take a look at the lines before this one, and find the actual error (Usually it related to CompileC or Analyze file).
* If you are using Pods, make sure that you are using the latest `pod` executable (`pod --version`), and run `cd ios && pod update` to make sure you have the latest versions.
* Try to execute the project from XCode and not from the packager.

**Comment by hramos** [comment]
If you're still running into this, add repro steps to #14447 which is a more recent issue.

**Comment by hramos** [comment]
Duplicate of #14423
