### ISSUE TITLE
When android textinput wrap, the new line is not wrap at a fixed position on the last line. 

### ISSUE THREAD

**Issue by MingYe-dz** [facebook/react-native#11507]
When android Textinput wrap, the new line is not wrap based a fixed position on the last line.  The whole text move upward. This problem maybe cause another issue:  When the Textinput height dynamic change, I Can not put a View under the TextInput,  due to the view is also move upward with the textinput text.

**Comment by lacker** [comment]
Is this a bug? It's not clear to me that this is not intended behavior. Also, would you mind providing a sample app that reproduces this problem from rnplay.org?

**Comment by christopherdro** [comment]
@facebook-github-bot no-reply

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
