### ISSUE TITLE
Avoid smart app banner from Universal Linking in IOS 

### ISSUE THREAD

**Issue by renganatha10** [facebook/react-native#11559]
I am trying to implement universal linking in IOS

I have created the `apple-app-site-association` and linked with my site
Followed this https://developer.apple.com/library/content/documentation/General/Conceptual/AppSearch/UniversalLinks.html

In appDelegate.m I added this 

```
- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity
 restorationHandler:(void (^)(NSArray * _Nullable))restorationHandler
{
 return [RCTLinkingManager application:application
                  continueUserActivity:userActivity
                    restorationHandler:restorationHandler];
}
```

Every thing works fine BUt the problem is when i click the universal Link it opens our webapp with `smart app banner` . and i click on `open` in `smart app banner`  to open the app. 

I want to bypass this `smart app banner`  and directly open the app

**Comment by johnryan** [comment]
@rengasahusoft there are more steps than just adding that file and the handler in your app delegate (changing app permissions and the provisioning profile). Check out https://www.raywenderlich.com/128948/universal-links-make-connection

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
