### ISSUE TITLE
[0.40] Warning: Swift Projects Fail

### ISSUE THREAD

**Issue by sjmueller** [facebook/react-native#11572]
With the new changes in e1577df and 59407f3, header references have been changed from quotes to angle brackets. While this may work in an Obj-C project, it causes several compilation errors for swift projects.

Previously to `0.40`, you could create a new swift project and perform the following steps to compile successfully:
* add the `-all_load` and `-lc++` linker flags
* add react native dir (recursively) to `Header Search Paths`
* setup your bridging header

Full steps for swift setup details can be seen [here](https://gist.github.com/boopathi/27d21956fefcb5b168fe).

Now according to the summary in update 59407f3:
 > $(BUILT_PRODUCTS_DIR)/include, which is added to the include path by Xcode by default

The above statement implies that customizing `Header Search Paths` is no longer necessary, but is this true for Swift? In fact it seems there's no longer *any* straightforward way for Swift projects to find these angle bracket headers when libraries are included directly in the project (not using cocoapods), similar to what has been detailed [on stack overflow](http://stackoverflow.com/questions/17465902/use-of-external-c-headers-in-objective-c). In addition to `Header Search Paths`, I've tried `User Header Search Paths` and setting `Always Search User Paths` to `Yes`. No combination thus far yields successful compilation, instead throwing these errors:

![image](https://cloud.githubusercontent.com/assets/29085/21370816/9ffba192-c6c2-11e6-8c73-24bdbbb99c56.png)

Why is this change being made? I've been using swift with RN successfully since the very beginning, and now there is risk of not being able to upgrade without jumping through hoops (i.e. npm post install scripts to rewrite headers). Please don't introduce such a breaking change unless there's a verified way of supporting swift!

**Comment by rh389** [comment]
As far as I can tell master is effectively broken at the moment, even for simple Obj-C projects created with `react-native init`. Certainly it seems to break compatibility with nearly all third-party native code.

```
react-native init foo --version=react-native@facebook/react-native#59407f36608f52d4402d742d916f78acd3ca7152
cd foo
yarn add react-native-vector-icons
[hack https://github.com/facebook/react-native/pull/11590]
react-native link
react-native run-ios
```
Fails due to redefinitions, because `react-native-vector-icons` (and pretty much any other native extension) uses the quote style to include RCT headers, so anything they include (eg `"RCTLog.h"`) get included twice -> redefinition errors.

 0.40.0-rc.2 (which has https://github.com/facebook/react-native/commit/e1577df1fd70049ce7f288f91f6e2b18d512ff4d but not https://github.com/facebook/react-native/commit/59407f36608f52d4402d742d916f78acd3ca7152) fails because headers can't be found - I think that's because third-party libraries pick up RCT headers as user headers, which in turn try to include more RCT headers as library headers, but then they're not found (because the third-party lib doesn't have the proper dependency on React? Not sure).

**Comment by rh389** [comment]
@sjmueller I'd be interested to know if https://github.com/facebook/react-native/pull/11614 helps you.

**Comment by rh389** [comment]
@sjmueller I've just given Swift a try, and I had success with the latest master if I use `#import <React/RCTRootView.h>` etc in all of my bridging header imports (rather than a quote style), and have `[js root]node_modules/react-native/React` recursive in my header search paths.

**Comment by sjmueller** [comment]
@rh389 I tried latest, but still getting errors. Can you outline how to reproduce your success? Keep in mind I'm trying to start from a fresh swift project, rather than using swift files inside the Obj-C project that's create with react-native-init.

**Comment by sjmueller** [comment]
Did you mean latest master **with** your #11614 PR applied?

**Comment by rh389** [comment]
Sure. And nope, I didn't mean with the PR applied, although if you do have the PR applied it's possible to continue to use a quote style in your bridging header's imports. Below works without my PR:

1. Create a new single page Swift app with the Xcode wizard.
2. In the project root: `yarn cache clean && yarn add react-native@facebook/react-native#master`
3. Add `node_modules/react-native/React/React.xcodeproj` to 'Linked frameworks and libraries'
4. Add `libReact.a` (iOS target, not TV) to 'Linked frameworks and libraries'
5. Add a dummy objective C file to get Xcode to prompt about a bridging header. Create the bridging header and delete the dummy file. (Or create a bridging header manually)
6. Add `#import <React/RCTRootView.h>` (and whatever other headers you need - but use that format) to your bridging header.
7. Add `-lc++` to `Other linker flags` in your project's build settings. It should build fine at this point.
8. Modify your `AppDelegate.swift` in the usual way. You should be able to use `RCTRootView()` without errors and without `#import`ing anything except in your bridging header.

I haven't gone through step 8 myself, but I've pushed the rest up here: https://github.com/rh389/react-native-swift-template.

I haven't needed to touch header search paths here because `node_modules` is underneath the Xcode project's root directory. If it's outside (e.g. you've got your Xcode project under an `ios` subdirectory) you'll need to add a recursive header search path to `node_modules/react-native/React`.

HTH🎄

**Comment by sjmueller** [comment]
@rh389 just came to say I had success starting from scratch and using the similar steps you outlined above. I'll also mention some extra info for anyone else trying to get get swift 3 running end to end:

6a. In addition, include `#import <React/RCTBundleURLProvider.h>` to get the minimum needed to get the app launched successfully. 

7a. Add `-all-load` in addition to `-lc++` to avoid runtime error `[error][tid:com.facebook.react.JavaScript] Native module cannot be null.` and `'NSInvalidArgumentException', reason: '-[RCTRootView reactTag]: unrecognized selector sent to instance`

8a. Example Swift 3 code as a drop-in to `AppDelegate.swift`:
```
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        let jsCodeLocation: URL
        
        jsCodeLocation = RCTBundleURLProvider.sharedSettings().jsBundleURL(forBundleRoot: "index.ios", fallbackResource:nil)
        let rootView = RCTRootView(bundleURL: jsCodeLocation, moduleName: "YOUR_PROJECT_NAME", initialProperties: nil, launchOptions: launchOptions)
        let rootViewController = UIViewController()
        rootViewController.view = rootView
        
        self.window = UIWindow(frame: UIScreen.main.bounds)
        self.window?.rootViewController = rootViewController
        self.window?.makeKeyAndVisible()
        
        return true
    }
```

9. Add the following to `Info.plist` to ensure RN can load your bundle from package server:
```
    <key>NSAppTransportSecurity</key>
    <dict>
        <key>NSAllowsArbitraryLoads</key>
        <true/>
    </dict>
```

**Comment by rh389** [comment]
Cheers for fleshing that out, glad you got it working.

I _think_ you'll still have problems with any third-party libs that import anything you've already imported, unfortunately, until either they're updated or something like https://github.com/facebook/react-native/pull/11614 is merged.

**Comment by sjmueller** [comment]
I just found out that we still have problems, in both 0.40 rc0 and latest master. While the steps above do get you a build that works, unfortunately once someone else clones from source control, the`file not found` problems resurface.

The only solution I know of is to remove all of the core react libs from *Linked Frameworks and Libraries* except for `libReact.a`. Then build the project successfully, and finally add back all the libraries you just removed:

![image](https://cloud.githubusercontent.com/assets/29085/22208286/38a1535e-e137-11e6-90cc-cb88d42a1ce9.png)

What a pain! It seems that xcode is getting confused because of not building the react project first, which results in all the other dependent projects failing left and right.

**Comment by rh389** [comment]
You'll probably want to make React the first target and disable build parallelisation to ensure that it's built first, See @SandroMachado's comment at https://github.com/facebook/react-native/issues/11721#issuecomment-270672904.

**Comment by Snorlock** [comment]
Have any RN core developer made any comments about that they want to focus on swift support? So this doesnt keep happening? Or if there is any updates in the near future that fixes this?

**Comment by rh389** [comment]
Speaking as an observer, Swift doesn't appear to have first-class support from the RN team because AFAIK they don't use it internally (and I think it's healthy, at least for now, to regard RN as part of facebook's stack they've chosen to share rather than as something they build primarily for the community's needs). 

There are plans to add some more tests to prevent big regressions though, and as you can see from this thread, it's very possible to use Swift currently. https://github.com/facebook/react-native/pull/12089 should make it smoother - using CocoaPods to build RN as a framework avoids the need for bridging headers.
