### ISSUE TITLE
Component styles sometimes do not display in the inspector

### ISSUE THREAD

**Issue by petermikitsh** [facebook/react-native#11584]
### Description

When using the inspector, occasionally a component's styles are not shown. Here's a screenshot of my simulator with the inspector open with no styles listed:

<img width="374" alt="screen shot 2016-12-21 at 10 54 47 am" src="https://cloud.githubusercontent.com/assets/1571918/21402129/f6700e56-c76b-11e6-9937-485b23c67049.png">

Using the debugger, we can inspect the component and confirm that styles are being applied (and can also be visually confirmed in the simulator screenshot above, noting the custom font face, color, font weight, etc):

<img width="416" alt="screen shot 2016-12-21 at 10 26 36 am" src="https://cloud.githubusercontent.com/assets/1571918/21401275/92af0d7a-c768-11e6-850c-96711ac2898c.png">

### Reproduction

Since this is in a pretty complex project, I'll attempt to reproduce this in an isolated format and update this issue with a link to that repo.

So far, I've tried manipulating various vectors for possible hints at what the underlying issue may be. Unfortunately, none of them worked:

- Attempted collapsing my array of style objects into a single object
- Attempted supplying less styles (e.g., just 1 key value pair instead of my regular use case of two objects each containing about 7 styles)

It could be due to the fact that the component tree is complex (as this Text component is 9 levels deep).

One thing worth nothing is that other components in the tree do show their styles correctly:

<img width="373" alt="screen shot 2016-12-21 at 10 47 50 am" src="https://cloud.githubusercontent.com/assets/1571918/21401950/20495cb0-c76b-11e6-9f58-61d0625885bc.png">

### Solution

The expected result is seeing styles listed inside the inspector for all components.

### Additional Information

* React Native version: [0.39.0]
* Platform: [iOS]
* Operating System: [MacOS]

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Comment by CapitanRedBeard** [comment]
I am also seeing the RN inspector having a lack of styles compared to the chrome inspector. Also you can only seem to see styles of leaf nodes. Can we open this up again and get clarity on why there is a gap in dev tools + how we can close that gap? Right now I just `StyleSheet.flatten(style)` all my styles to see if they're correct or not which is pretty lame.

**Comment by petermikitsh** [comment]
@hramos, I would appreciative your perspective on the inspector functionality and how it can be improved because this is still a problem. I would also request that we re-open this issue. Thanks!

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
