### ISSUE TITLE
【Android】why does bundleReleaseJsAndAssets task not run

### ISSUE THREAD

**Issue by helengray** [facebook/react-native#11665]
![qq 20161229152803](https://cloud.githubusercontent.com/assets/6320872/21538804/b1e6dcf8-cddb-11e6-9223-e7fe59b63f2a.png)

for pic

left:run assembleDevRelease task by cmd
right:run app by app

on the 'left',it run bundleReleaseJsAndAssets task and output the bundle file,but 'right' can't.

why?it's similar to run the task

**Comment by rmevans9** [comment]
Because assembleDevRelease builds without debug mode. The other is in some sort of debug build which skips building the bundle. The bundle built during the gradle build is only used to ship it with the APK. If you doing a debug build it assumes you will have the React Native packager running which the app will use to pull the bundle.

**Comment by helengray** [comment]
@rmevans9 Not,the two build type all is release,they difference just one run by cmd,the other run by IDE,the task all is assembleDevRelease

**Comment by Swordsman-Inaction** [comment]
![image](https://cloud.githubusercontent.com/assets/12252463/23290151/a8239262-fa89-11e6-9155-e7fdc5253731.png)


Try to uncheck `Configure on demand`.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/androidwhy-does-bundlereleasejsandassets-task-not-run
