### ISSUE TITLE
Update 0.39 and error "unknow named module:'fbjs/lib/invariant'"

### ISSUE THREAD

**Issue by ghost** [facebook/react-native#11686]
### Description
I update rn from 0.35 to 0.39
now the information of react native.
"react": "^15.4.1",
"react-native": "0.39.2",
But There is an error when I do a android app.

please look image
![snip20161231_1](https://cloud.githubusercontent.com/assets/7948820/21575125/3201d368-cf3d-11e6-93e1-dfbc39994c80.png)

**but I have install fbjs**
"fbjs": "^0.8.8",
"fbjs-scripts": "^0.7.1",

### Additional Information
* React Native version: 0.39.2
* Platform:Android
* Operating System:MacOs

**Comment by ericvicenti** [comment]
Can you try a few things:

- Wipe out your `node_modules` and re-install
- Run the RN packager with `react-native start --reset-cache`

**Comment by christopherdro** [comment]
@facebook-github-bot answered

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
