### ISSUE TITLE
[Device Rotation] View behind status bar when starting app in landscape mode and then rotating

### ISSUE THREAD

**Issue by johanneslumpe** [facebook/react-native#1170]
When you have a view with a navigator, start the app in landscape mode and then rotate it to portrait, the text of the navigation bar will be underneath the status bar and becomes illegible.

I assume it has to do with the fact that in landscape mode on iOS 8 there is no status bar and react does not take that into account. Didn't yet investigate any further. This is a follow-up to #1064

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by satya164** [comment]
Is this still an issue?

**Comment by christopherdro** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

If you'd like you can create an issue on [Product Pains](https://productpains.com/product/react-native).
ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. 

Also, if this issue is a bug, please consider sending a PR with a fix. Thanks!
