### ISSUE TITLE
Run application on android with custom flavour

### ISSUE THREAD

**Issue by jr-k** [facebook/react-native#11785]
Hello,

I'm trying to use productFlavours on my app. Here is my build.gradle

```gradle
 productFlavors {
        free {
            applicationId "com.myapp"
        }
        pro{
            applicationId "com.myapp.pro"
        }
    }
```

My application is working fine with the original applicationId/packageName which is com.myapp

When I run my app with variant "pro" I see my custom SplashScreenActivity then, when it comes to MainActivity it crashes: http://puu.sh/tgssh/4dce437439.png

FYI here is my SplashScreenActivity bootstraping my app just in case: http://puu.sh/tgsvm/ccedc60af6.png

Any idea ? Thanks for your help !

**Comment by dkpalmer** [comment]
I ran into the same "Could not get BatchedBridge" error with different build types instead of product flavors, but I suspect it's the same issue. In your build.gradle file, you can try added a `project.ext.react` section (see comment block at top of the file).

For me, I have three variants (`debug`, `beta`, `release`) with corresponding packages similar to `com.myapp.debug`, `com.myapp.beta`, and `com.myapp`. I had to add a `project.ext.react` block to allow connection to packager in `debug` and to bundle my app for `beta` and `release`:

```
project.ext.react = [
  bundleInDebug: false,
  bundleInBeta: true,
  bundleInRelease: true,
]
```

Also worth noting I had issues getting `project.ext.react` settings picked up the first time. See https://github.com/facebook/react-native/issues/12135.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/run-application-on-android-with-custom-flavour
