### ISSUE TITLE
KeyboardAvoidingView with padding behavior fails to animate text

### ISSUE THREAD

**Issue by thomaslindstrom** [facebook/react-native#11821]
### Description

I started a fresh `react-native` `0.40.0` project and added an index view with a `Text` label and an `TextInput` contained inside a `KeyboardAvoidingView` with `behavior` set to `padding`. Opening the keyboard made the `TextInput` animate smoothly to where it should be, but the `Text` just skipped there (didn't animate).

#### Here's a video of the issue: 
https://www.dropbox.com/s/cbqv9sve1k6fa3k/react_native-keyboard_avoiding_view-bug.mov?dl=0

#### This code reproduces the issue:

```javascript
import React from 'react';

import {
    StyleSheet,
    Text,
    TextInput,
    View,
    KeyboardAvoidingView
} from 'react-native';

const styles = StyleSheet.create({
    view: {
        padding: 20,
        flex: 1,
        justifyContent: 'center'
    },
    inputContainer: {
        flex: 1,
        justifyContent: 'center'
    },
    label: {
        fontFamily: 'helvetica neue',
        fontSize: 18
    },
    input: {
        backgroundColor: '#ddd',
        height: 30,
        fontSize: 18
    }
});

function IndexView() {
    return (
        <KeyboardAvoidingView style={styles.view} behavior="padding">
            <View style={styles.inputContainer}>
                <Text style={styles.label}>
                    Some label
                </Text>

                <TextInput style={styles.input} />
            </View>
        </KeyboardAvoidingView>
    );
}

export default IndexView;
```

### Solution

I expected everything to animate as smoothly as the `TextInput` did.

### Additional Information

* React Native version: 0.40.0
* Platform: iOS 10.2 (Simulator)
* Operating System: MacOS 10.12.2

**Comment by jameszonk** [comment]
Wrapping TextInput with View component fixed this issue for me

**Comment by grundmanise** [comment]
I am experiencing the same issue only with a `FlatList`, it's height is not animated (the same behavior as with your `Text` element):
```
         <KeyboardAvoidingView style={{flex: 1}} behavior={'padding'}>
                <FlatList {...props} />
                <TextInput style={{height: 50, alignSelf: 'stretch'}} />
          </KeyboardAvoidingView>
```

Wrapping `TextInput` with a `View` does not solve it.

**Comment by jackcutting** [comment]
@grundmanise I was experiencing exactly the same issue as @thomaslindstrom 

Wrapping the `Text` with a `View` solved this issue for me. Maybe try doing the same with your `FlatList`

```
<KeyboardAvoidingView style={{ flex: 1 }} behavior="padding">
  <View>
    <FlatList {...props} />
  </View>

  <TextInput style={{ height: 50, alignSelf: 'stretch' }} />
</KeyboardAvoidingView>
```

**Comment by grundmanise** [comment]
@jackcutting does not work with `FlatList`/`ScrollView`
https://github.com/facebook/react-native/issues/13076

**Comment by guidsen** [comment]
I'm experiencing this issue as well. Any updates on this yet?

**Comment by zmGitHub** [comment]
+1

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by conor909** [comment]
Im having the same issue with a FlatList wrapped in a KeyboardAvoidingView.  I have a flatlist of inputs, which works fine for the bottom input at the bottom of the screen, the keyboard pushes the bottom input up.  But it doesnt work for the item at the top of the list - the keyboard pushes the item out of view.
