### ISSUE TITLE
Style property 'backgroundColor' is not supported by native animated module

### ISSUE THREAD

**Issue by clochokeca** [facebook/react-native#11831]
### Description
Hello,  react native give me this error: 
**" Style property 'backgroundColor' is not supported by native animated module "**

it's happened then :
```
xOffset = Animated.value(0)
return (
 <Animated.View style={{backgroundColor:xOffset.interpolate({
                                inputRange: [0,1],
                                outputRange:  ['white', 'black' ],
                                extrapolate: 'clamp'})}/>
  <Animated.ScrollView
    onScroll={Animated.event([{ nativeEvent: { contentOffset: { x: xOffset } } }])}>
)
```
### Solution
I fix Error by change onScroll prop in Scrollview :
```
onScroll={ x => {
  let mover = Animated.event([ {nativeEvent: { contentOffset: { x: xOffset} } } ])
  return mover(x) 
}
```

**Comment by clochokeca** [comment]
### **it's happened then :**
Animated.ScrollView 
  onScroll={Animated.event([{ nativeEvent: { contentOffset: { x: xOffset } } }]}
        
### I fix Error by change : 
onScroll={ (x)=> {let mover = Animated.event([ {nativeEvent: { contentOffset: { x: xOffset} } } ])
            return mover(x) }

**Comment by zoharlevin** [comment]
@clochokeca can you explain the solution?
this used to work in RN 0.42.0 but now with RN 0.44.0 i'm also getting this error.
however, your solution doesn't work with `useNativeDriver: true`

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by jose920405** [comment]
https://github.com/skv-headless/react-native-scrollable-tab-view/issues/669#issuecomment-318459122
