### ISSUE TITLE
react-native is not calling componentWillMount for the root component everytime the app is restarted on device

### ISSUE THREAD

**Issue by chirag04** [facebook/react-native#1183]
@vjeux @spicyj  Thoughts?

**Comment by spicyj** [comment]
It should. Please post more info about the behavior you're seeing and a repro case.

**Comment by spicyj** [comment]
In general, please post as much detail as you can to help us understand what your problem is. No need to tag specific people in the post unless you know that your issue is related to them. (In this case, it is probably not.) Whoever's monitoring the issues will get to your issue and reply when they have a chance.
