### ISSUE TITLE
react-native panresponder onPanResponderMove possible bug or improvement needed + documentation needed

### ISSUE THREAD

**Issue by Kielan** [facebook/react-native#11832]
i wrote a stackoverflow but I believe this to be an unintended behavior/bug

http://stackoverflow.com/questions/41586276/react-native-onpanrespondermove-strange-behavior-no-documentation-animated-event

### Description

I want to have a pan responder I can drop and focus on child elements. When I use the syntax 
  onPanResponderMove: Animated.event([null, {dx: this._pan}]),
Animated.event does call this._pan however if I use 
 onPanResponderMove: (e, gestureState) => {
    Animated.event([null, {dx: this._pan}])
  },
such a syntax does not get called even though it is the recommended usage in the docs. Animated.event just doesn't call on drag.

### Reproduction

https://github.com/Kielan/rn_emoji_test

Not sure how to fix this I just want to start the discussion and get more documentation on panresponder.
### Additional Information

* React Native version: latest
* Platform:  iOS simulator
* Operating System: MacOS osx

**Comment by fcFn** [comment]
Hey, I answered you question on SO. 

As for documentation, all the examples seem to have no wrapping in them. A note on applying might be useful though.

**Comment by christopherdro** [comment]
@facebook-github-bot answered

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
