### ISSUE TITLE
PermissionAndroid API Level 22 (Samsung J5) Camera Permission is not granted

### ISSUE THREAD

**Issue by fasibio** [facebook/react-native#11842]
Bug
### Description

The following Code is not granted

 ```
PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.CAMERA).then((granted) =>{
// is not granted
//do some stuff
}
```

In [React Native Dokumentation](http://facebook.github.io/react-native/releases/0.40/docs/permissionsandroid.html#permissionsandroid) : 
On devices before SDK version 23, the permissions are automatically granted if they appear in the manifest, so checkPermission and requestPermission should always be true.

In the Manifest the permission is set: 
```
<uses-feature android:name="android.hardware.camera" />
<uses-permission android:name="android.permission.CAMERA" />
```

So I think this will be a Bug in the Module
### Additional Information

* React Native version: 0.40.0
* Platform:  Android

### Workaround
```
if (Platform.OS === 'android' && Platform.Version >= 23) {
PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.CAMERA).then((granted) =>{
doSomeStuff()
} else {
doSomeStuff()
}

```

**Comment by hey99xx** [comment]
If the permission is not granted, this does sound like a bug. Looking at the code, I don't see an obvious mistake. Is it a problem specifically with your Samsung J5 or all devices?

**Comment by ThaJay** [comment]
I have the same problem on Android 4.4.1
using react-native 0.41.2
It used to work on 40.0

This is bad because before I did not have a test phone on android 4 and a client of ours who is on Android 5 experienced this bug in production because I trusted this function to keep working after updating react-native.

Now I do have a phone with Android 4 on it and I will check api version like suggested above.
Has this been fixed upstream? if so in what version?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/permissionandroid-api-level-22-samsung-j5-camera-permission-is-not-granted
