### ISSUE TITLE
[iOS][Build] Unable to build in Release with RN v0.40.0

### ISSUE THREAD

**Issue by sergey-akhalkov** [facebook/react-native#11861]
Hello!

### Description

I've got following error while trying to build `react-native` initial project using `Release` configuration:

![image](https://cloud.githubusercontent.com/assets/4928157/21884627/235ec7bc-d8c5-11e6-81dd-99c23af213af.png)

The error occurs in: 

![image](https://cloud.githubusercontent.com/assets/4928157/21884708/79117dd0-d8c5-11e6-9cb3-899c07b20c6b.png)

### Reproduction

1. `react-native init rn`
2. `Xcode->Product->Scheme->Edit Scheme->Run->Build Configuration` property
Change its value from `Debug` to `Release`
3. Build Project

### Additional Information

* React Native version: v0.40.0
* Platform: iOS
* Operating System: MacOS

**Comment by grabbou** [comment]
cc: @javache

**Comment by rh389** [comment]
Looks like `-lc++` is missing from the `myprojectTests` target's `Other Linker Flags`. It's still broken in master - will put a PR in.

**Comment by nihgwu** [comment]
I add `-lc++` to projectTests manually every time I upgrade RN

**Comment by rh389** [comment]
Interesting, I don't remember having to do that. The `-lc++` and `-ObjC` flags are both present in pre-existing projects I had, but I guess they got dropped somewhere along the way (looking through `pbxproj` diffs is a bit painful!)

**Comment by itinance** [comment]
Run into the same issue. Just create a new project with "react-native init test", open it with xcode, change the scheme to release mode and try to compile will result in exactly the same issue

**Comment by itinance** [comment]
Adding -lc++ and -ObjC in "other linker flags" at the test-target solved this issue. Wondering how RN 0.40 could being published with this error, that is really simple to reproduce?

**Comment by rh389** [comment]
I've been meaning to raise the issue of adding some more build tests generally because RN seems particularly fragile in that area of late - you're right IMO this kind of thing shouldn't make it out of the door. I'd be happy to work on automated tests for the various supported build configs but would need to chat to someone about fitting it into CI and/or the release process without slowing the test run too much.

**Comment by grabbou** [comment]
> It's not obvious to me why this only affects the release config though?

Since linker flags can differ between Release and Debug, maybe by any chance you had set them only in `Debug` mode?

**Comment by rh389** [comment]
It's not that - 'Other linker flags' is set on each target and not on the particular confitg. Debug seems not to require lc++ on the projectTests target.

**Comment by kadzier** [comment]
Running into this exact same problem with the same solution too.  Building for debug works fine but release requires the -lc++ flag set on the test target.

**Comment by smkhalsa** [comment]
I'm still having this issue with my "Staging" build configuration. I've set `-lc++` flags on all three build configs (Debug, Release, and Staging).

@rh389 Did you figure out why this was affecting Release and not Debug? I'm hoping the answer to that question will help answer mine as well.

**Comment by rh389** [comment]
@smkhalsa No, I never worked that out. The call to `abi::__cxa_demangle` in `RCTLog.mm` is the only line that requires the C++ libs as far as I can see, and as that's precompiled away in release mode it seems counter-intuitive that release requires `-lc++` but debug doesn't. 

I have a suspicion that the compiler/linker is cleverly inferring a need for the C++ link in debug without requiring it to be explicit, but wrongly thinking it's unnecessary in release (maybe because the call is removed but the header is still included) - which may be why disabling 'dead code stripping' fixed the issue in some cases (https://github.com/facebook/react-native/issues/11285). I'm out of my depth when it comes to compiler internals though.

Is it the `...Tests` target that's failing for you as well? Same linker error? It's worth checking you have `C++ Standard Library = libc++` and `C++ Language Dialect = C++14` on your staging config but I don't know what else might cause this error.

**Comment by Naoto-Ida** [comment]
I don't get the exact error(actually no error at all), but can never get the app to build in Release mode. It just hangs after the `bundle: Done copying assets` message.
