### ISSUE TITLE
Multiple Class prefixes: RCT, RK

### ISSUE THREAD

**Issue by jaygarcia** [facebook/react-native#119]
Are all of these contractions of "React"?

**Comment by hahaGitHub** [comment]
@nicklockwood 
hi,i have a question.
pod react in my own project.i use the RCTRootView.by the url ,I can get the view.but i meet a problem.
it is a warning. could you tell me why? thank you very much.
[warn][tid:com.facebook.React.JavaScript] 'devtools socket errored', { [Error: The operation couldn’t be completed. Connection refused]
  line: 14510,
  column: 39,
  sourceURL: 'http://localhost/index.ios.bundle' }

**Comment by nicklockwood** [comment]
@hahaGitHub this doesn't seem related to the issue that you've commented on. It's better to create new issues rather than comment on an unrelated one.

In any case, it sounds like there's either a problem with the packager on your system, or you've got the wrong sourceURL for your bundle.

The packager runs in a window in the terminal, and creates a server running on localhost, normally on port 8081.

It looks like you're trying to access it via 'http://localhost/index.ios.bundle', which would be port 8080 by default. In your browser, try accessing http://localhost/index.ios.bundle to see if it exists, and if not, try http://localhost:8081/index.ios.bundle instead. If the latter works, you need to change your sourceURL.

If neither work, look in the packager window in the Terminal and see if there are any errors. If there is no packager window, it's not running, and that's the problem.

**Comment by hahaGitHub** [comment]
@nickbalestra thank you your answer!

**Comment by hahaGitHub** [comment]
@nickbalestra 
hi,i have commit a new issue.and i try your idea,then the url is normal.
