### ISSUE TITLE
Crash with  'InputEventReceiver: Exception dispatching input event' on android N(7.0)

### ISSUE THREAD

**Issue by LittoCats** [facebook/react-native#11927]
### Description

My app crash when  tap or move in from the left/right edge of screen, and I just recieve adb message as flows:
```
InputEventReceiver: Exception dispatching input event
```

crash with empty project too.

RN version: 0.40
Android version:  7.0
Device: HUWEI Mate 9

**Comment by sidbusy** [comment]
I met the same problem.

**Comment by sidbusy** [comment]
Maybe all HUAWEI devices (Android 7.0 only)  have the same problem.

**Comment by pinkelf** [comment]
Is this the same problem as  #11302 ?

**Comment by sidbusy** [comment]
@pinkelf Is **not** the same problem.

**Comment by sunxfancy** [comment]
Same problem on HUAWEI Mate 8 (Android 7.0)

**Comment by danielang** [comment]
Same problem on Huawei P9 (Android 7.0) with React-Native: 0.42.3

**Comment by MrPluto** [comment]
+1 at mate 8 & android 7
logcat `E InputEventReceiver: Exception dispatching input event.`

**Comment by MrPluto** [comment]
find a fix in 0.44.3. [Fix java.lang.RuntimeException: Tried to get non-existent cookie](https://github.com/facebook/react-native/commit/d2939eafbf56f99ea4da7374b9812ae6f54c1d3d)

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
