### ISSUE TITLE
'RCTImage/RCTImageUtils.h' header file not found in version 0.40.0, only exist when archive release package.

### ISSUE THREAD

**Issue by jaggerwang** [facebook/react-native#11954]
### Description

I'm using react-native-wechat to share something to WeChat. The code can be compiled when debugging on simulator or device, but when tried to archive, compile failed. I've already submitted a [issue](https://github.com/weflex/react-native-wechat/pull/160) to the lib I'm using.

It's weird that only 'RCTImageUtils.h' need to using prefix 'RCTImage', but 'RCTImageLoader.h', which is in the same directory, not need.

![image](https://cloud.githubusercontent.com/assets/1255011/22048717/c99b9bfc-dd69-11e6-83cb-1f2fc648a1be.png)

### Additional Information

* React Native version: 0.40.0
* Platform: iOS
* Operating System: MacOS
* Xcode: 8.2.1

**Comment by jaggerwang** [comment]
I found the 'RCTImage' directory not exist at the first. It shows at some time. So first you should copy file 'RCTImageUtils.h' from the source by yourself. And this is not make sure compile to be passed. I tried removing Xcode cache and restarting for several times, finally archive successfully. But I'm still not sure about the reason...

**Comment by sibelius** [comment]
I think it should be `<React/...>` instead of `<RCTImage/...>`

**Comment by eulo** [comment]
For anyone coming here looking for RCTImageUtils.h fix, this compiled for me

```Objective-C
#import <React/RCTUtils.h>
#import "RCTImageUtils.h"
```

**Comment by SRandazzo** [comment]
This took me a bit, but my solution was to modify RCTImage so that the RCTImageUtils.h is in the `public` headers instead of project, which reflects where it is in the latest master. I have been on RN since 0.29 so it's possible i did not upgrade correctly all this time

<img width="1442" alt="screen shot 2017-05-02 at 1 02 41 pm" src="https://cloud.githubusercontent.com/assets/307819/25629684/6335fd64-2f38-11e7-9165-1dd6918bb93c.png">

**Comment by rclai** [comment]
@SRandazzo how do you get to that public headers screen?

**Comment by rclai** [comment]
I found it.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
