### ISSUE TITLE
webview can't go back to original url

### ISSUE THREAD

**Issue by tigerohuang** [facebook/react-native#11952]
Webview now has two functions: goBack, goForward, but if I want to go back to the original url when entering webview, there is no functions.

**Comment by BogdanHossu** [comment]
There are some ways how to do this: 

1. You cold inject a script which is changing the url inside of the webview depending on the postMessage.
2. You could reload the webview or change the source link.

Probably there are more ways but this one are the ones I have first in my head. Hope helps.

**Comment by lyahdav** [comment]
This is trickier than it seems and I'm having issues with both of @BogdanHossu's suggestions:

1. The `injectedJavaScript` property is only read when the webview is initially loaded (at least according to the [docs](http://facebook.github.io/react-native/docs/webview.html#injectedjavascript)). It's also not clear to me how to do this with `postMessage`. Can you provide an example?
1. Reloading the webview works with the `reload` method, but that will keep me on the current page, not the original URL. I tried to change the source property with `this.webView.source = {uri: 'http://google.com'};` but it doesn't seem to do anything. Maybe the source property is only read on initial rendering of the webview?

**Comment by sergiulucaci** [comment]
hey guys,

I’ve just met the same problem. Didn’t found your responses until yet, but I’ve tried those two solutions before reaching here (they’re similar to yours):

1. update the already render source of the web view (nothing happens).
2. reload the web view (reloading the web view it will reload the current url where the user arrived if by navigating into that web view).

Have you finally found a solution for this?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by dirkpostma** [comment]
I added a comment in this commit:

https://github.com/facebook/react-native/commit/9923d3fa6f9d691557ce561327f0cc039179f0c2#diff-17ddfccc3e39071c0aa51f82677e6d68

> Image the following case:
>
> I create a WebVew with url X
> I surf a bit, the currentURL of webview changes to Y
> The source of WebView however, doesn't change while surfing, remains X
> I want to load the original url X in the WebView was initiated with
> Using setState({source: X}) won't work, because source is still X. No rerender is triggered
> Calling reload() won't work either, as it reloads Y
> Question: How can I load X again?
> 
> Currently, the only way is to unmount en remount the WebView.
> 
> Suggestion: Why not always call [_webView loadRequest:request], also if _webView.request.URL.absoluteString is not empty?

It addresses the issues mentioned here. I suggest to reopen this issue and adapt the reload function in RCTWebView.m

**Comment by hramos** [comment]
Comments in commits are not a great way to flag things, as many commits come from internal source control at Facebook and the comment won't be seen by the author. It's best to open a new issue.

**Comment by Adamfoust** [comment]
How do I unsubscribe 




On Friday, October 27, 2017, 2:15 PM, Héctor Ramos <notifications@github.com> wrote:


Comments in commits are not a great way to flag things, as many commits come from internal source control at Facebook and the comment won't be seen by the author. It's best to open a new issue.

**Comment by mb16** [comment]
I can confirm that the solution by Andrei works.  Thank you for posting this code.
