### ISSUE TITLE
Activity Indicator not showing in specific Android device

### ISSUE THREAD

**Issue by BogdanHossu** [facebook/react-native#11964]
I found this issue on a OnePlus 2 phone with Android version 6.0.1. When I am loading an activity indicator, nothing appears on the screen. If you turn on the layout settings, you will see that actually the activity indicator is there but not showing.

What can be a solution to fix this?

React-Native version: 0.39
Platform: Android
Operating System: MacOS
Phone tested on: OnePlus 2

![screenshot_20170118-125938](https://cloud.githubusercontent.com/assets/15978240/22067086/02b2e7da-dd90-11e6-969f-e512789597ba.png)

My code:

```
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  ActivityIndicator
} from 'react-native';

export default class test extends Component {
  render() {
    return (
      <View style={styles.container}>
        <ActivityIndicator
            animating
            size="large"
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('test', () => test);
```

**Comment by janicduplessis** [comment]
This will be pretty hard to debug as I don't have this device. Is there any prop you can change that makes it show up? The native code is in https://github.com/facebook/react-native/tree/master/ReactAndroid/src/main/java/com/facebook/react/views/progressbar, seems like it just uses android ProgressBar and doesn't do anything too crazy.

**Comment by rajatvijay** [comment]
Having the same problem, its not rendering even on the virtual device.

**Comment by BogdanHossu** [comment]
On which Virtual Device you are testing? I couldn't reproduce on mine.

**Comment by rajatvijay** [comment]
Oh sorry my mistake it was a typo in my code!

**Comment by Slooowpoke** [comment]
I have this issue on a specific device as well. LG G3. All other devices I've tried seem to work fine. All the devices I've tested it on have been physical devices.

**Comment by BogdanHossu** [comment]
My solution for the moment was to make my own "activity indicator" from a image which I am rotating it.

**Comment by razvan-tudosa** [comment]
I think I experience the same problem, I own a One Plus 3T but my client has a One Plus 3. I can see the activity indicators on my device and my simulators, however he cannot. Both of us are running Nougat on the devices with latest Oxygen updates.

I don't even know where to begin digging for this issue.

**Comment by natdm** [comment]
Here is a video of the bug:
https://www.youtube.com/watch?v=vubkS6Sikpg&feature=youtu.be

If you are hot reloading and you have the page reload at all, it will show the activity indicator.

**Comment by ViGi-P** [comment]
I'm facing the same problem on an LG K7. Has anyone figured out a solution other than what @BogdanHossu mentioned?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by efkan** [comment]
I am also having the same problem.
The indicator is shown on Galaxy J5 (6), is not shown on Xperia Z, is shown on the emulator.

**Comment by huntinghawk1415** [comment]
I'm having the problem as well. Using a Samsung Galaxy S7 Edge device (not an emulator) and nothing shows.

Also tried it on an Android emulator using BlueStacks, worked perfectly fine there.
