### ISSUE TITLE
Listview blanks when using navigator pop.

### ISSUE THREAD

**Issue by krishbhattacharyya** [facebook/react-native#11998]
Hi,

@hramos I am facing two problems & can not resolve this.  Can anyone explain why this is happening? Or can anyone give me the solution?

**Problem NO 1:** 
_There are two components 1) Home  2) Inner_
In the Home there are list of data & when I click any one of them it route to Inner. There are also a back button with using navigator pop. There is the issue sometime reproduce - When I click on back, it routes to Home but there is no data(listview element) but when I touch on the screen the data shows properly.
**Problem NO 2:** 
In the home component within the list data, there also some repeated data within the single row. 
I have used map function for this. Sometimes ( Most of the time it shows correctly ) it is also not shown in list view, the row is showing properly but the repeated data are missing.

**Comment by krishbhattacharyya** [comment]
`              <ListView 
                onEndReached={this.props.reloadArticles} 
                onEndReachedThreshold={10} 
                dataSource={this.props.dataSource} 
                renderRow={this.renderPost} 
                _angleDown={this.props._angleDown} 
                enableEmptySections={true}
                refreshControl={
                  <RefreshControl
                    refreshing={this.props.isRefreshing}
                    onRefresh={this.props._onRefresh}
                   
                  />
                }
                />`

**Comment by nihgwu** [comment]
#8607 #1831

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

**Comment by kliuj** [comment]
try  removeClippedSubviews ={ false}
