### ISSUE TITLE
react-native-git-upgrade cannot apply binary patch *** without full index line

### ISSUE THREAD

**Issue by alfonsodev** [facebook/react-native#11995]
### Description
I've tried to use  `react-native-git-upgrade` to update my project from `0.36.1` to `0.37.0` , then from `0.38` to `0.39` 
I always get the same errors `cannot apply binary patch /path/to/file.so` without the full index.
```
error: cannot apply binary patch to 'node_modules/react-native/ReactAndroid/src/main/jni/prebuilt/lib/armeabi-v7a/libreactnativejni.so' without full index line
error: cannot apply binary patch to 'node_modules/react-native/ReactAndroid/src/main/jni/prebuilt/lib/armeabi-v7a/libreactnativejni.so' without full index line
error: cannot apply binary patch to 'node_modules/react-native/ReactAndroid/src/main/jni/prebuilt/lib/armeabi-v7a/libreactnativejnifb.so' without full index line
error: cannot apply binary patch to 'node_modules/react-native/ReactAndroid/src/main/jni/prebuilt/lib/armeabi-v7a/libreactnativejnifb.so' without full index line
error: cannot apply binary patch to 'node_modules/react-native/ReactAndroid/src/main/jni/prebuilt/lib/x86/libreactnativejni.so' without full index line
error: cannot apply binary patch to 'node_modules/react-native/ReactAndroid/src/main/jni/prebuilt/lib/x86/libreactnativejni.so' without full index line
error: cannot apply binary patch to 'node_modules/react-native/ReactAndroid/src/main/jni/prebuilt/lib/x86/libreactnativejnifb.so' without full index line
error: cannot apply binary patch to 'node_modules/react-native/ReactAndroid/src/main/jni/prebuilt/lib/x86/libreactnativejnifb.so' without full index line
error: cannot apply binary patch to 'node_modules/react-native/android/com/facebook/react/react-native/0.38.0/react-native-0.38.0-javadoc.jar' without full index line
error: cannot apply binary patch to 'node_modules/react-native/android/com/facebook/react/react-native/0.38.0/react-native-0.38.0-sources.jar' without full index line
error: cannot apply binary patch to 'node_modules/react-native/android/com/facebook/react/react-native/0.38.0/react-native-0.38.0.aar' without full index line
error: cannot apply binary patch to 'node_modules/react-native/local-cli/generator-android/templates/bin/gradle/wrapper/gradle-wrapper.jar' without full index line
```
**Edit** I've removed the second case to focus only in one problem as the second issue only happens in 0.36 to 0.37
**Edit 2** I saw that my issue in part is similar to https://github.com/facebook/react-native/issues/11402  so fixed partially, by temporarily adding *.png to global gitignore,
and I've update the error output just to show the affected files currently.   

Also I've tried copying the files that are mention in the error, from a fresh app, to my app, and it didn't help. 
### Reproduction
With a clean project the upgrade command works perfectly so I guess my app is not in a clean state, I've been updating with `react-native upgrade` since `0.34`

### Additional Information
* react-native-git-upgrade: 0.2.4
* react-native-cli: 2.0.1
* react-native: 0.36.1
* Platform: both
* Operating System: MacOS

**Comment by fengjiankang** [comment]
I had met the similar problem.  I hope the upgrade tools can more friendly。

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
