### ISSUE TITLE
Not getting onPanResponderMove events after decreasing number of items in the ListView

### ISSUE THREAD

**Issue by lesniakania** [facebook/react-native#12014]
### Description

I have `Board` component which is a `ScrollView` and I have `PanResponder` attached to the `ScrollView`.
`Board` renders `Column` inside which is a `ListView`.
`ListView` row is a simple `TouchableWithoutFeedback` with `onPressIn`.
In `onPressIn` I have timeout after that I decrease number if items displayed in the `Column`.

**Expected behaviour:**

When I start touches and keep moving cursor, even after changing number of items, I should get events about the move from `PanResponder`.

**Actual behaviour:**

When I start touches and keep moving cursor, decreasing number of items, I don't get events from `PanResponder` about the move anymore.
Funny thing is it's not only about the change of datasource, cause when I increase number of items it works.

### Reproduction

I've created project demonstrating the issue: https://github.com/lesniakania/PanResponderExample
There are more details about how to reproduce it In the `README`. I also attached gifs with visualization of the issue there.

This bug causes [this](https://github.com/lesniakania/react-native-draggable-board/issues/2) issue in my project.

### Additional Information

* React Native version: `0.40.0 `
* Platform: both iOS and Android
* Operating System: MacOS, but I think it's not relevant

**Comment by lesniakania** [comment]
Hm, is `react-native` still developed? I see lot's of unresponded issues. I need to admit that it worries me a bit.

**Comment by lesniakania** [comment]
@AaaChiuuu @sahrens @mmmulani @janicduplessis @amonshiz I see you (and many others) committing to this repo, but why no one responds to any issues? It is kind of worrying and discouraging from using react-native at all.

**Comment by mmmulani** [comment]
hey, this project is pretty high traffic so we don't really have time to go through the issues, cc @lacker (he helps to triage)

you can also check out https://facebook.github.io/react-native/support.html for places to get support. Issues are kind of the last resort, stack-overflow usually works better

**Comment by lacker** [comment]
We do in fact go through the issues, you can see we have dealt with most of them at https://github.com/facebook/react-native/issues . But it's true that a single issue might not get a response for weeks. In most cases someone from the React Native community does chime in.

I think the tough thing here is that your sample project is massive. When you post your whole project and ask if someone can debug, it's pretty hard to look at it and figure out anything. My suggestion is to find a more minimal reproduction. For example can you get this bug to repro with just a single ListView?

**Comment by lesniakania** [comment]
Thanks for the response. I can't really go to stack overflow as I believe it's bug in React Native itself.
From My experience developing my library, `PanResponder` is very very very fragile - really weird things happen if you have complex component structure.

@lacker this is example project: https://github.com/lesniakania/PanResponderExample (not my library, the library is massive indeed). Do you still think it's massive? Everything is described in https://github.com/lesniakania/PanResponderExample/blob/master/README.md and there are actually only two components: https://github.com/lesniakania/PanResponderExample/tree/master/src/compontents.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
