### ISSUE TITLE
Customised Bridge initialisation fails for iOS

### ISSUE THREAD

**Issue by oargaruna** [facebook/react-native#12027]
### Description

Our project is a hybrid of React Native modules and native UI. We ideally want only the React Native developers to run the development server, while the rest pick up the bundle file. 

We have implemented the `RCTBridgeDelegate` protocol which is passed to the bridge during initialisation. Below is a snippet of the methods which return the source URL. In debug, the source URL should be the development server, with the bundle as fallback, if it's not running.

```
- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#ifdef DEBUG
    NSURL* sourceURL = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle?platform=ios&dev=true"];
#else
    NSURL* sourceURL = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
    
    return sourceURL;
}

- (NSURL *)fallbackSourceURLForBridge:(RCTBridge *)bridge
{
    return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
}
```

I must be doing something wrong because I still get the Red Screen if I try to load a React Native module. Any suggestions will be appreciated.

### Additional Information

* React Native version: 0.35
* Platform: iOS
* Operating System: MacOs

**Comment by ericvicenti** [comment]
Do you see the red screen while running in debug mode, running outside of debug mode, or both? What does the error say? Does your server properly respond with a bundle when hitting that URL?

**Comment by oargaruna** [comment]
<img width="225" alt="screen shot 2017-01-24 at 10 11 40 am" src="https://cloud.githubusercontent.com/assets/3697736/22234370/a66a6542-e21d-11e6-8aef-f8827f981474.png">

I get the standard error that the development server is not reachable. I have only tried in Debug. This will not fail in Release since we are picking up the bundle.

If the server is running, it responds with the bundle.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
