### ISSUE TITLE
Invalid UIActivityIndicatorViewStyle '100'. should be one of: (0, 1 )

### ISSUE THREAD

**Issue by laclance** [facebook/react-native#12030]
Please help, my app runs on android and used to run on ios but now react-native run-ios  gives me this error:

Invalid UIActivityIndicatorViewStyle '100'. should be one of: (
    0,
    1
)

* React Native version: 0.39 and 0.40
* Platform: iOs 9.0 and 10.2
* Operating System: macOs Sierra 10.12.2

**Comment by lavarajallu** [comment]
Under the hood a static function differs from an instance function only in how it takes its implicit parameters: instance functions take one implicit parameter for **self** while static functions take no implicit parameters for anything.

As far as the code for the function is concerned, there is no penalty for a function being static or non-static. Same goes for performance: static functions are simplest lightweight "packages" of executable code; calling them carries no additional costs.

Your particular implementation, however, may benefit from storing **activityIndicator** in a variable to avoid re-creating it in each static call. Moreover, this would make it easier for you to remove the activity indicator from superview once the activity has finished. If you would like to use a single activityIndicator, you could keep your function static, and add a class variable for **activityIndicator**. Otherwise, you should make multiple instances of **ActivityIndicator** class, each having its own **activityIndicator** instance variable. In this case, start**ActivityIndicator** should become an instance method as well.

**Comment by laclance** [comment]
Thank you but I am being silly. My apologies. In android, the ActivityIndicator can be any size (a number representing width and height, I presume) but in iOs it can only be 0 ('small') or 1 ('large').

**Comment by lavarajallu** [comment]
Okay laclance.

Can you favour me i have a samll issue

**Comment by laclance** [comment]
sure?

**Comment by lavarajallu** [comment]
yah Thank u

**Comment by lavarajallu** [comment]
http://stackoverflow.com/questions/41743667/react-nativehow-can-i-get-the-dot-or-image-when-i-click-on-the-particular-pos

Can you Refer This Link I was Post the Issue...Plz Refer this

**Comment by lavarajallu** [comment]
thanks in Advance

**Comment by lavarajallu** [comment]
did u get it my question?
