### ISSUE TITLE
Loading website content without waiting domLoad on website

### ISSUE THREAD

**Issue by reactipsum** [facebook/react-native#12031]
Hi,

I'm using Webview my iOS App that load one remote web page. But this web page dom loading takes a lot of time. So i want to show content without wait domLoad. When i use native browser app (like safari) website loads faster (content is showing first time - my app waits everything load) than my app webview.

My  WebView component is below

  <WebView
                    source={{uri: this.props.uri}}
                    style={styles.webview}
                    onError={(e)=>{}}
                    renderError={(e)=>{}}
                    onLoad={this.onLoadEnd}
                    javaScriptEnabled={true}
                    onLoadEnd={this.onLoadEnd}
                    automaticallyAdjustContentInsets={true}
                    domStorageEnabled={true}
                    startInLoadingState={true}
                /> 

Where am I doing wrong?

**Comment by ericvicenti** [comment]
Maybe Safari has a warmed-up cache that allows it to load much faster?

**Comment by alexandrebini** [comment]
Hi there,

I'm having the same issue here... the page seems to be rendered only when something like 'domLoad' is fired. It's not a progressive render, like any browser would do.

It's happening on iOS and on Android (rn 0.41.2).

**Comment by alexandrebini** [comment]
@reactipsum @ericvicenti Removing `startInLoadingState` fixed to me... but the loading don't render

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by minhphung210** [comment]
same issues

**Comment by ShaikhKabeer** [comment]
The issue is happening due to startInLoadingState={true} and it's not working in iOS if we are rendering html response like 
` <WebView
                  bounces={false}
                  source={{html:this.state.htmlResponse}}
                  startInLoadingState={true}
                />`
