### ISSUE TITLE
Android build release apk error - Could not find generated setter for class - RN 0.40

### ISSUE THREAD

**Issue by vdesdoigts** [facebook/react-native#12040]
Result of `adb logcat`

```
W/unknown:ViewManagerPropertyUpdater(10521): Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputShadowNode
W/unknown:ViewManagerPropertyUpdater(10521): Could not find generated setter for class com.facebook.react.views.text.ReactTextViewManager
W/unknown:ViewManagerPropertyUpdater(10521): Could not find generated setter for class com.facebook.react.views.toolbar.ReactToolbarManager
W/unknown:ViewManagerPropertyUpdater(10521): Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
```

**Comment by vdesdoigts** [comment]
Ref https://github.com/facebook/react-native/issues/12013

**Comment by buskerone** [comment]
+1

**Comment by a289459798** [comment]
+1

**Comment by devmaster72** [comment]
+1

**Comment by koansang** [comment]
+1
RN: 0.44.0
Device: Android Ver 6.0 and 7.0

**Comment by sgong-gzy** [comment]
+1

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
