### ISSUE TITLE
Overflow: 'hidden' requires zIndex on android

### ISSUE THREAD

**Issue by saberking** [facebook/react-native#12057]
### Description

`Overflow: 'hidden'` requires `zIndex` on android

### Reproduction
```
import React, { Component } from 'react';
import {
  AppRegistry,
  View
} from 'react-native';

export default class overflow extends Component {
  render() {
    return (
      <View style={{top: 200, overflow: 'hidden', left: 0, right: 0, height: 200}}>
        <View style={{top: -200, backgroundColor: 'red', height: 400, left: 0, right: 0}}/>
      </View>
    )
  }
}
AppRegistry.registerComponent('overflow', () => overflow);

```

### Solution

Add `zIndex` to the outer `View`

### Additional Information

Occurs on android emulator and real device (Nexus 5X), both android 7
not reproducible on rnplay.org

* React Native version: 0.40.0
* Platform: Android
* Operating System: Windows 7

**Comment by airman00** [comment]
Confirming your solution to be correct. I didn't believe it at first...

It only works if you add zIndex to the parent view

**Comment by samuelltk** [comment]
Thanks @saberking.  Your share is perfect.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
