### ISSUE TITLE
Bugs/Ommisions in Windows-Android 'Getting started'

### ISSUE THREAD

**Issue by peternann** [facebook/react-native#12068]
--- Please use this template, and delete everything above this line before submitting your issue --- 

### Description

Tried to follow the Getting Started guide at https://facebook.github.io/react-native/docs/getting-started.html on 25/Jan/2017 - in Windows-Android mode.
Expected if I followed each step to the letter it would work.
I followed each step to the letter. It didn't work.
I would like to help ensure it works for some noob in the near future.

### Reproduction

Get on a fresh Windows box.
Or un-install Android Studio, SDK, HAXM, and reset any environment variables to have no trace of these.
Then follow the Getting Started instructions to the letter (Windows-Android mode).
I am pretty sure you will have the same issues I did.

### Solution

The following ommissions cause a faithful walkthrough of Windows-Android Getting Started to fail, and should be corrected:

1) Section "3. Install the Android 6.0 (Marshmallow) SDK" clearly lists 4 items to newly install. It does not list "Android SDK Platform 23". I am pretty sure you need to install this, no?

2) There is no mention to put "%ANDROID_HOME%\tools" and "%ANDROID_HOME%\platform-tools" into PATH. You need to do that for the later stated "android AVD" command to work.
The Linux variants of Getting Started seem to cover equivalent PATH setting.
If Getting Started never mentioned using the "android" command, you may be excused from not setting PATH. But the "android" command line tool is mentioned, and doesn't work in the context of a fresh walkthrough.

The following might be considered Android Studio bugs/short-comings, but anyway:

3) Even though the SDK Manager says the "... (HAXM installer)" is "installed", the installer appears to have never been run. Not for me anyway. From StackOverflow pointers, I had to CD to %ANDROID_HOME%\extras\intel\Hardware_Accelerated_Execution_Manager and run "silent_install.bat" before any AVD would start.

4) Defining an AVD for the context here can be pretty daunting for a new starter. Yes, I had no working AVD after Android Studio installation, as warned in the Getting Started. It would be highly beneficial to noobs to mention the critical fields relevant here to create a relevant AVD - API Level and CPU/ABI matching the AVD images that were early targeted for installation, right?

5) And a Bonus: The last section basically says "Change code in your text editor, then type R twice to reload" - Ahhh, following that just types two new "R"s in my text editor... Using something like this would be clearer for a noob: "In the Android Emulator, tap the R key twice on your PC keyboard..." 

Please consider. Cheers.

### Additional Information

* React Native version: 0.40
* Platform: Android
* Operating System: Windows

**Comment by ericvicenti** [comment]
If you submit these changes as a Pull Request, we can improve the guide!

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
