### ISSUE TITLE
Bug in Modal component of Android.

### ISSUE THREAD

**Issue by ktusharprdxn** [facebook/react-native#12060]
I got strange issue with modal while working, here is a issue description:
1. I have one element with styling as position absolute.
2. When my modal gets open by some action, and on close of that modal, element mention above in 1 gets hidden/vanished permanently. 

I am using version 0.35 react-native. Please help.

**Comment by yachaka** [comment]
I got the same issue. I figured out that mounting/unmounting any `View` with `position: absolute` will make the view above it - I mean right above in the code - vanish.

A temporary solution is to put the `View` with `position: absolute` at start of the children :
Change this:
```js
<View>
    <View>...</View>
    <View style={{ position: 'absolute' }}>Hey !</View>
</View>
```
By this:
```js
<View>
    <View style={{ position: 'absolute' }}>Hey !</View>
    <View>...</View>
</View>
```

**Comment by saberking** [comment]
I found a workaround, just put the absolute positioned element twice, one on top of the other. Then you don't notice if one disappears

**Comment by saberking** [comment]
BTW this is not just a problem with Modal, I made my own JS Modal and the problem stays so I think it must be to do with stacking of absolute positioned views

**Comment by pedrohenriquerls** [comment]
The same behavior happens with too, but no one of those workarounds fixes this behavior to me. I using the `0.42.0-rc.3`

**Comment by ColCh** [comment]
Fix that helped me with disappearing components: setting `zIndex` to it
Another one, which removed disappearing screen problem using custom self-written Modal

```diff
```

**Comment by mienaikoe** [comment]
you're a lifesaver, @ColCh !

**Comment by hasLandon** [comment]
Adding zIndex helps me too, but sadly this is still happening on react native 0.44.0

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
