### ISSUE TITLE
Switch component doesn't work in Android

### ISSUE THREAD

**Issue by frostedcake** [facebook/react-native#12079]
### Description

I added a basic Switch to my app (pasted directly from tutorial). This gives an error in Android but not iOS.

Error:

![screenshot-2017-01-26_14 17 40 149](https://cloud.githubusercontent.com/assets/22812343/22334329/48c01372-e3d2-11e6-8c97-8f94778d0db6.png)

I've searched for this error, and it seems to have something to do with SDK/build-tools versioning.

https://stackoverflow.com/questions/39091521/vector-drawables-flag-doesnt-work-on-support-library-24

(I've updated everything as stated with no effect on this -- see build.gradle config below).

### Additional Information

From build.gradle (If anyone has a Switch working in Android, could you please let me know how your build.gradle file differs so we can figure out what exactly causes the error):

    compileSdkVersion 23
    buildToolsVersion "24.0.1"
    minSdkVersion 16
    targetSdkVersion 22
    compile "com.android.support:appcompat-v7:23.0.1"

Other info:

* react: 15.3.2
* react-native 0.39.0
* Platform: Android
* Operating System: Linux

**Comment by hey99xx** [comment]
Same as https://github.com/facebook/react-native/issues/10877

**Comment by duhecx** [comment]
I am having the same problem with the same gradle build configuration. Tried changing buildToolsVersion to latest, and sdk versions but to no success. Problem still persists on latest React native version (0.42.2).

The issue seems to be in calculating Switch's layout size, but tries to call length() on a null text.
If only we could supply mShowText or mTextOn/mTextOff internal variables of a SwitchCompat...

See stack trace:
https://github.com/android/platform_frameworks_support/blob/master/v7/appcompat/src/android/support/v7/widget/SwitchCompat.java line 783 and line 864
https://github.com/android/platform_frameworks_base/blob/master/core/java/android/text/StaticLayout.java line 422

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
