### ISSUE TITLE
There is some way to use react-native into a network proxy?

### ISSUE THREAD

**Issue by luizguilhermefr** [facebook/react-native#12097]
Hello.

There is some way to use **react-native** (the command-line interface and server) through a network proxy?

I'm into an authenticated proxy network and cannot run command like `react-native run-android` because it fails to fetch data. Also, I cannot communicate an installed app with the hosted `react-native start` server.

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
