### ISSUE TITLE
RTL Text gets repositioned if missing lineHeight styles

### ISSUE THREAD

**Issue by StefanWallin** [facebook/react-native#12096]
#### Expected behaviour
Text rows in arabic app should render Right To Left given that textDirection and 
I18nManager is set up correctly.

#### Actual behaviour
- With lineHeight the text component behaves as expected.
- Without lineHeight the text component seemingly ignores writingDirection or gets 
moved to another position.

### Reproduction
**RNPlay:** https://rnplay.org/apps/V3ZfZA
**Repo:** https://github.com/StefanWallin/rtl_test_app
**Diff:** https://github.com/StefanWallin/rtl_test_app/commit/7ddec1b2ef67c585cadbb8f0180262ed349e1d83

### Solution
Don't have the wildest idea 😢 

### Additional Information
* React Native version: 0.40.0
* Platform: iOS
* Operating System: MacOS

**Comment by fmmajd** [comment]
had the same problem. the only solution is using height. or you can put the text in a view, and give the view an appropriate amount of padding :)

**Comment by saracodes** [comment]
Same problem here.
RN v0.41.2

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
