### ISSUE TITLE
TextInput in react native is not behaving like the input type="text"

### ISSUE THREAD

**Issue by aniruddhashevle** [facebook/react-native#12091]
If I fill the values in **input type="text"** and If I click anywhere except the input type="text", default behaviour is, that input field shows the values(characters which are written) from the start. 

While in **TextInput of react native** with the same situation, that input field shows the values(characters which are written) those are at the end. **I want that TextInput to show the valuse(characters which are written) from the start.**

**Comment by ktusharprdxn** [comment]
@aniruddhashevle Please clarify your query clearly. What I understand from your query is that in react native text input field if value size is greater than width of that field then it gets render from right to left and start of the text gets cut. 

<TextInput style={ width: 300} value="This is demo, this is demo will get cut this is demo is cut" />

So as we can see when text gets overflow, it will get cut from start not from end(ideal expected behavior of HTML text input see this http://jsbin.com/mafurekole/edit?html,output)

Even I am not getting solution on this. @reactjs-bot Please help.

**Comment by ktusharprdxn** [comment]
@brentvatne This issue is not yet resolved, can you please provide some solution so that we can work on. I don't know why it marked as closed.
