### ISSUE TITLE
<Image> components with a base64 URI sometimes do not initially render. 

### ISSUE THREAD

**Issue by ChristianTucker** [facebook/react-native#12120]
--- Please use this template, and delete everything above this line before submitting your issue --- 

### Description

When using the React-Native `<Image />` component with a base64 encoded image, sometimes the image does not display, when rendering multiple Image components at the same time. The image is left blank, and will sometimes come up during a re-render. I've debugged and made sure that the uri was available during the render method, I see no reason for the image to not appear. It's not always the same images that do it. It's complete random. Sometimes they will all load. Sometimes random ones will stay blank. Sometimes they'll show up after scrolling around the page. Sometimes they won't. 

### Reproduction

Just create a page with several images loading different base64 sources. `{uri: 'base64string'}` 

### Solution

Unknown. I've tried several hacks to force re-renders and everything.

### Additional Information

* React Native version: 0.40
* Platform: iOS, haven't tested Android. 
* Operating System: MacOS

**Comment by ivpusic** [comment]
the same for me, but for normal images. Did you find something to solve this?

**Comment by ChristianTucker** [comment]
@ivpusic it seems like this problem may only exist on the Simulator. Can you confirm? We published our application through TestFlight (distribution mode) and the problem did not persist.

**Comment by Jammyvm** [comment]
I'm having the same problem in android, in the simulator and in a tablet with a release version. Anyone have a fix to this?

**Comment by raytorres280** [comment]
Currently dealing with same issue.

**Comment by qwerty94155** [comment]
This problem is more frequent in devices with low memory. Please provide some solution

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by RamKrish2079** [comment]
Please reopen the issue. I am also facing the same problem. `<Image src={{uri: base64}} />` does not render initially.

**Comment by RamKrish2079** [comment]
I faced the same problem with this image component where image not rendered initially.
`
const GridImage = props => {
  const { image } = props;
  return <Image style={styles.container} source={image} />;
};

export default GridImage;

styles = {
  container: {
    height: 50,
    width: 50,
    tintColor: "#f00"
  }
};
`
but the image rendered while hot-reloading
 and I later found that i missed to declare `styles` as constant

working code with `const styles`  : 

const GridImage = props => {
  const { image } = props;
  return <Image style={styles.container} source={image} />;
};

export default GridImage;

const styles = {
  container: {
    height: 50,
    width: 50,
    tintColor: "#f00"
  }
};
`

**Comment by rawrmaan** [comment]
Still seeing this as of `0.49.4`.

**Comment by quantumproducer** [comment]
Bump, my image loaded from base64 is blank.

**Comment by OzoTek** [comment]
Happening as well with `0.53.2`.

**Comment by lakhwinder99** [comment]
Same issue with me.. revisit to image gallery page returns blank images for images received from server response. Images received in log

**Comment by sadeghtkd** [comment]
I had the same problem, After I added height and width to the image the problem resolved.

**Comment by hpmax00** [comment]
+1, with device and simulator

**Comment by michaelaflores** [comment]
Have this issue as well.
