### ISSUE TITLE
packager @providesModule naming collision

### ISSUE THREAD

**Issue by thurt** [facebook/react-native#12131]
### Description

http://stackoverflow.com/questions/41813211/how-to-make-react-native-packager-ignore-certain-directories

### Reproduction

#12078 

### Solution

make packager option to completely ignore certain directories

### Additional Information

* React Native version: 0.40.0
* Platform: both (build issue -- not platform specific)
* Operating System: MacOS

### What I have tried
1. (does not work) tried creating `rn-cli.config.js` in root of project then run `react-native run-ios`
```javascript
const blacklist = require('react-native/packager/blacklist');

const config = {
  getBlacklistRE() {
    return blacklist([
      /dist\/.*/
    ]);
  }
};

module.exports = config;
```
1. (works, not ideal) rename `dist/` folder to `.dist/` (packager appears to automatically ignore . dirs).

**Comment by rh389** [comment]
I've answered you on SO - you need to explicitly name the config file with `--config` and make sure you `--resetCache` the first time.

**Comment by gritzko** [comment]
@rh389 Thank you for the workaround.
Still, it is better to prevent such mashups automatically. Like, to include build/ into the default blacklist.
It is even better to prevent such mashups at the design level. For example, change from a blacklist to a whitelist. Like, everything but `node_modules` is not included by default.

**Comment by rh389** [comment]
It's intentional that user projects can `@providesModule` too so I don't think restricting to `node_modules` would work. There are a [bunch of directories](https://github.com/facebook/react-native/blob/master/packager/blacklist.js#L15) excluded by default but `build` / `dist` aren't among them. Maybe they should be, maybe that's potentially surprising - not sure.

I agree that `rn-cli.config.js` feels like a hammer to crack a nut for a simple use case like this, but AFAIK at the moment it's the only way. It'd be nice to be able to specify include/exclude lists in `package.json`.

**Comment by gritzko** [comment]
Well, a whitelist is much less surprising, potentially. You need it to work - you make it work.
If a program tries to be smart in unexpected ways, that usually leads to frustrating results. Google says, people hit this issue often.

**Comment by thurt** [comment]
appreciate it @rh389 ! i added a comment over on SO

**Comment by th317erd** [comment]
What is NOT said here is that the matching is anchored to the end of input (the regular expressions in the array are built into one final regular expression that is terminated by $)... so make sure to put a .* at the end of the regular expression you would like to match against. Also, another helpful hint is that all '/' forward slashes are automatically replaced with the current OS path separator.
