### ISSUE TITLE
Starting android phone in aeroplane mode results in NetInfo.isConnected.fetch resolves to true when app is opened

### ISSUE THREAD

**Issue by brcarey** [facebook/react-native#12138]
### Description

When an android device is rebooted in aeroplane mode, when the app is opened NetInfo.isConnected erroneously returns true

### Reproduction

* Turn on aeroplane mode and reboot phone
* Open app
* Observe that NetInfo.isConnected returns true, when it should be false

### Solution

Changing this line:

https://github.com/facebook/react-native/blob/master/Libraries/Network/NetInfo.js#L72

to 

`return connectionType !== 'NONE' && connectionType !== 'UNKNOWN' && connectionType !== '';`

may mean adding EMPTY to the ConnectivityStateAndroid enum as well?

### Additional Information

* React Native version: 0.40
* Platform: Android (any version)
* Operating System: Ubuntu

**Comment by maraujop** [comment]
I was having issues with `NetInfo` in Samsung Android devices and your patch totally fixes them. However, my situation is a little different.

In these devices there is a battery saver Samsung app, that makes weird things when suspending the phone and then turning it back on and going back to the app. It makes the app think there is no connection and when you foreground the app, the event listener never sees a connection change, so it thinks there is no connection anymore, even though the user has data. 

It only starts working again when the user actively switches from wifi to data or viceversa.

Thank you Brendan for this, it was driving me nuts.

Cheers,
Miguel

**Comment by brcarey** [comment]
Glad it could help @maraujop, I have been meaning to get one of my colleagues macs so I can see why the build is failing and hopefully get it merged to master

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
