### ISSUE TITLE
Android react.gradle bundle settings ignored

### ISSUE THREAD

**Issue by chuckhacker** [facebook/react-native#12135]
### Description

When renaming the bundle and specifying `bundleIn{Debug,Release}` in `build.gradle` like so:

```
project.ext.react = [
        // the name of the generated asset file containing your JS bundle
        bundleAssetName: "index.bundle",

        // the entry file for bundle generation
        entryFile: "index.js",

        // whether to bundle JS and assets in debug mode
        bundleInDebug: true,

        // whether to bundle JS and assets in release mode
        bundleInRelease: true,
]

apply from: "../../node_modules/react-native/react.gradle"
```

These settings are ignored and the following error is always displayed, suggesting that RN is still looking for the old `index.android.js` and not the new `index.js`:
http://imgur.com/a/oqTMf

The problem persists even after restarting `react-native start`.

As you can see, it is still looking for `index.android.js` AND it is still not bundling the JS in debug mode.

### Reproduction

Easy to reproduce, just use `react-native init` and try to rename the bundle. For example (remove the "android") in `build.gradle` (Module: app) as follows:

```
project.ext.react = [
        // the name of the generated asset file containing your JS bundle
        bundleAssetName: "index.bundle",

        // the entry file for bundle generation
        entryFile: "index.js",

        // whether to bundle JS and assets in debug mode
        bundleInDebug: true,

        // whether to bundle JS and assets in release mode
        bundleInRelease: true,
]

apply from: "../../node_modules/react-native/react.gradle"
```

Then, run either using `react-native run-android` or by opening the Android Studio project and pressing the play button.

### Solution

React Native needs to abide by the `project.ext.react` gradle settings and look in the correct place for the bundle (and use the bundle in debug mode as well when specified).

### Additional Information

* React Native version: 0.40.0
* Platform: Android
* Operating System: macOS 10.12.2

**Comment by TheChuckster** [comment]
I'm shocked this hasn't been reported yet. Do people actually never try to use a shared Android/iOS codebase?  It's a cheap (and quite unacceptable IMO) workaround, but for now, I just copy `index.js` to `index.android.js`, and then of course, RN finds it just fine.

**Comment by TheChuckster** [comment]
Any updates?

Moreover, I've discovered that whenever I set `bundleInDebug` to `false` and resynchronize my Gradle, React Native does not even try to hit my node server in the debug build variant; it's still looking for a bundle.

It seems like the `project.ext.react` gradle settings are ignored all together.

**Comment by janicduplessis** [comment]
I think what most people do is have an common file that they import in both index.ios.js and index.android.js.

Looks like a real issue, not sure who owns that code @mkonicek maybe? :)

**Comment by dkpalmer** [comment]
I had issues with `project.ext.react` getting picked up as well. After going through a few other issues, I saw mention of setting `org.gradle.configureondemand=false` in gradle.properties. After setting this, removing the same setting in my global gradle properties, and killing all running gradle processes, my `project.ext.react` settings started working.

As a workaround, you could try specifying your options manually at the command line as described at https://github.com/facebook/react-native/issues/9612#issuecomment-249780917.

Also wanted to mention, we follow the paradigm described by @janicduplessis (importing a common file in both index files.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by frmrgr** [comment]
Gotta add `protected String getJSMainModuleName() {return "index";}` to `mReactNativeHost` in `MainApplication.java`. That is for packager, `entryFile` is about offline bundling.

**Comment by hugo-retro** [comment]
Here is a better answer: https://github.com/facebook/react-native/issues/16594#issuecomment-348188077

Make sure your `project.ext.react` is before `apply ... /react.gradle`
