### ISSUE TITLE
Changing system font on Android makes text disappear

### ISSUE THREAD

**Issue by mikaello** [facebook/react-native#12147]
### Description

If I switch system font on my phone to Serif (_Settings -> Screen -> Font_), start a clean project with `react-native init projectname`, and runs the app on an LG G3. The app starts fine, but random parts of the text disappears (and the app does not use the serif font, it uses the default sans serif font that ships with react-native), if I switch system font back to Roboto (which is the default on android system for LG G3) everything displays as it should.

### Reproduction

- Switch to Serif font as system font in android (the problem also appears with other fonts as well, e.g. Travel  or Purewhite, but then other parts of the text disappears)
- `react-native init projectname`
- `cd projectname`
- `react-native run-android`

Android system font Roboto:
![screenshot-2017-02-01-10-47-35](https://cloud.githubusercontent.com/assets/2505178/22502872/3780a51c-e86f-11e6-8d47-e5c69056566a.png)

Android system font Serif:
![screenshot-2017-02-01-10-47-56](https://cloud.githubusercontent.com/assets/2505178/22502874/39d217a6-e86f-11e6-99a9-270bc49b8f39.png)

Android system font Purewhite:
![screenshot-2017-02-01-11-22-44](https://cloud.githubusercontent.com/assets/2505178/22503223/1050bf5c-e871-11e6-90b5-8cd9493160db.png)

I have only seen this issue on LG G3 and LG G4, my Samsung S4 Active does not have the problem, and displays the app perfectly with correct system font.

### Solution

If you add a `fontFamily: 'fontname'` in the styling of the text-components it will work, and all the text appears with the font family chosen in the styling. If you provide a font-family that does not exists, e.g. "aoeuid", it will use the Android-system font and display all the text correctly. 

### Additional Information

* React Native version: 0.39 and 0.40 (not tested earlier versions)
* Platform: Android
* Operating System: MacOS and Linux (not tested Windows)

**Comment by jdmunro** [comment]
I've had this issue cropping up too. Will try your workaround soon - thanks!

**Comment by jdmunro** [comment]
I'd like to take a closer look at this issue. I can't get my hands on an LG phone though so I've so far been unable to reproduce the problem. Is there a way to reproduce the problem using a stock emulator?

**Comment by mikaello** [comment]
I haven't been able to reproduce it in the simulators that came with my version of Android Studio. My next step before I figured out the workaround was to test different types of phones on [Firebase test lab](https://firebase.google.com/docs/test-lab/) or [AWS Device Farm](https://aws.amazon.com/device-farm/), but I never tested that. AWS Device Farm has the first 250 minutes free, so that may be an option?

**Comment by jdmunro** [comment]
AWS device farm looks like a good shout, I'll see what I can find out. Thanks!

**Comment by jdmunro** [comment]
Interestingly I've been unable to reproduce this issue on any LG phones with Android 4.x. AWS Device Farm doesn't have any Android 5.x LG devices. Just wondering what version your G3 has?

**Comment by mikaello** [comment]
The G3 had a Android 6.x version, I don't have access to the phone anymore to check the minor version.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by WildyDS** [comment]
Still having this issue on LG devices. To reproduce just change font in settings for any other than Roboto. Font won't be changed but text's got cut off. Changing font works well on Samsung btw. Anyone has workaround other than changing style of every text component?

RN 0.48.4

**Comment by jdmunro** [comment]
Only solution I've found is to create a `Text` wrapper and use that consistently throughout the project.
