### ISSUE TITLE
Android deploys always the same release on device. Emulator ok

### ISSUE THREAD

**Issue by adriancuco** [facebook/react-native#12155]
Hi,
I am deploying an app on Android 4.2.2 and everything was ok.
Suddenly one day it started to deploy always the same version, even when code is changed and recompiled. Even removing the app from the device, redeploy the old app version.
I appears to compile ok, as follows:
Installing APK 'app-debug.apk' on 'SM-T110 - 4.2.2'
Installed on 1 device.

BUILD SUCCESSFUL

Total time: 23.589 secs

This build could be faster, please consider using the Gradle Daemon: http://gradle.org/docs/2.4/userguide/gradle_daemon.html
Starting the app on 3004e4a342269100 (/Users/adriancuco/Library/Android/sdk/platform-tools/adb -s 3004e4a342269100 shell am start -n com.test1/.MainActivity)...
Starting: Intent { cmp=com.test1/.MainActivity }

Just in case I created new test app from the scratch and the same issue.
I restarted the device and the mac and the same.

React Native version: 0.34
Platform(s) (iOS, Android, or both?): Android
Operating System (macOS, Linux, or Windows?): macOS El Capitan

I was advised to run the following but it did not work:

cd android && ./gradlew clean

Please advise. Now I am running 0.38 and the same issue.
Thanks

**Comment by mkoo21** [comment]
Do `watchman watch-del-all` and `npm cache clean` help?

**Comment by adriancuco** [comment]
Hi,
It did not work. 
Please advise.
Thx

**Comment by adriancuco** [comment]
Quick finding:
By signing the app and releasing it as follows it worked:
 react-native run-android --variant=release

Why the debug mode not?
Thx

**Comment by YouHan26** [comment]
I came the same problem. `react-native run-ios --variant=release` show error : `unknow option --variant`. Any advise?

**Comment by Swordsman-Inaction** [comment]
@YouHan26 try to replace `variant` with `configuration`

**Comment by YouHan26** [comment]
@Swordsman-Inaction Solved, Xcode has the command `Product` -> `Clean`, then everything will be ok. Thanks your advise anyway.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by nicodonof** [comment]
This still happens!

**Comment by hramos** [comment]
Please submit a new issue and make sure to fill out the template.

**Comment by Gennady77** [comment]
I have the same problem. Where is the continuous of this discusion?
