### ISSUE TITLE
TextInput ignores dynamic textAlign

### ISSUE THREAD

**Issue by alanhoff** [facebook/react-native#12160]
### Description

I have a text input that have a dynamic `textAlign` style. When I focus the input it should have `textAlign: left` and `textAlign: center` when blurred and empty text. This is the way that I found to place the placeholder in the middle without centering what the user types. Everything works fine until I blur the input. The textAlign will stay in the left and the placeholder isn't centered anymore. 

### Reproduction

```jsx
render () {
  const shouldCenter = !this.state.text && !this.state.focused

  return <TextInput
    multiline
    value={this.state.text}
    style={{ textAlign: shouldCenter ? 'center' : 'left' }}
    onFocus={() => this.setState({ focused: true })}
    onBlur={() => this.setState({ focused: false })}
    onChangeText={text => this.setState({ text })}
    placeholder={shouldCenter ? 'This should always be on center' : null} />
}
```

### Solution

As a short-term solution I added a `key={this.state.key}` to the input and changed the key each time the input is blurred and have no text. I think this forces the correct redraw of the input and the placeholder appears in the center correctly.

### Additional Information

* React Native version: 0.39.0
* React version: 15.4.1
* Platform: Darwin user.local 15.6.0 Darwin Kernel Version 15.6.0: Mon Jan  9 23:07:29 PST 2017; root:xnu-3248.60.11.2.1~1/RELEASE_X86_64 x86_64
* Operating System: Simulator Version 10.0 (SimulatorApp-726.7 ) running iPhone 6 - iOS 10.2 (14C89)
* Xcode: Version 8.2.1 (8C1002)

**Comment by holyxiaoxin** [comment]
Facing this as well. Flex property breaks when multiline is true for IOS TextInput. It's fine in Android.

**Comment by MilosR** [comment]
+1 Also ignores dynamic placeholder on Android 6.0.1 (RN 0.42.3)

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
