### ISSUE TITLE
react-addons-perf doesn't measure anything

### ISSUE THREAD

**Issue by 1st8** [facebook/react-native#12163]
### Description

When using react-addons-perf, the result of `Perf.getLastMeasurements()` always returns an empty array, although there were updates happening between the calls to `Perf.start()` and `Perf.stop()`.

### Reproduction

Create a fresh react-native project and apply the following changes: https://github.com/1st8/PerfNative2/commit/9916526d80150ceeda0a20eb9f48b1e38ce969e8
Now open the app and start debugging in chrome. In the console, select the "debuggerWorker.js" environment to get access to the global `Perf` object.
Then run `Perf.start()`, click the plus-button a few times and finalize with running `Perf.stop()`.
The following call to `Perf.getLastMeasurements()` is expected to return measurements of your actions, but returns none. 
I did a similar test with a fresh create-react-app project and got the expected result.

### Solution

Sadly no idea...

### Additional Information

* React Native version: 0.40.0
* Platform: both
* Operating System: MacOS

**Comment by 24ark** [comment]
@1st8 You can use [RCTRenderingPerf.js](https://github.com/facebook/react-native/blob/master/Libraries/Performance/RCTRenderingPerf.js) instead of `react-addons-perf`.
``` 
import PrefMonitor from 'react-native/Libraries/Performance/RCTRenderingPerf';

componentDidMount() {

  PrefMonitor.toggle();
  PrefMonitor.start();
  setTimeout(() => {
      PrefMonitor.stop();
  },5000);

}

```

**Comment by lslima91** [comment]
@24ark this gives me "Failed to execute 'measure' on 'WorkerPerformance': The mark '163::ctor' does not exist"

**Comment by seanadkinson** [comment]
Using `react-native@0.39` was able to get access to a working `Perf` using:

    var Perf = require('ReactPerf');

After measuring, it seems to be displaying useful information in the console using `Perf.printInclusive()`.

**Comment by teameh** [comment]
@24ark PrefMonitor works fine for me (0.44), thanks! I've made a small PR to at least have something that works in the docs. https://github.com/facebook/react-native/pull/13902

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
