### ISSUE TITLE
Keyboard.dismiss do not work with WebView

### ISSUE THREAD

**Issue by magicismight** [facebook/react-native#12189]
### Description

Keyboard.dismiss can not work properly with WebView.

### Reproduction

Show keyboard from WebView.
Then use `Keyboard.dismiss()` can not hide the keyboard.

### Additional Information

* Platform: both

**Comment by sachinrekhi** [comment]
I seem to be running into the same issue. Did you find any workarounds or fix?

**Comment by AkiraXue** [comment]
i get the same issue  when pop or switch the navigator from webview which the input is focused to another navigator which show the native component,  anybody know how to solve the issue

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by ashconnell** [comment]
@magicismight did you ever find a workaround to this? It's still happening

**Comment by chasecs** [comment]
running into the same issue. on React Native 0.50.3

**Comment by henrytndrly** [comment]
I still have the same issue on RN 50.4.
My workaround is to have a 'hidden' TextInput in the View that I focus on before calling Keyboard.dismiss

e.g.

    closekeyboardhack() {
        this.closekeyboardhackElement.focus();
        Keyboard.dismiss();
    }

    setCloseKeyboardHackElement = (ref) => {
        this.closekeyboardhackElement = ref;
    }

...

`<TextInput ref={this.setCloseKeyboardHackElement} underlineColorAndroid="transparent" style={{ height: 0, margin: 0, padding: 0 }} />`

`<TouchableOpacity onPress={() => { this.closekeyboardhack(); }} >`

`    [.... code with webview in here]`

`</TouchableOpacity>`

(Anyone know how to nicely write multi-line code snippets? this keeps 'hiding' my new-lines within the JSX code when in just one block.)

The downside is that it has a tendency to flicker 'keyboard aware' content when tapping within the TouchableOpacity.

It also doesn't appear to remove the flashing cursor from Android webviews, although it does hide the keyboard. (The non-removal of the cursor may be a facet of my code elsewhere, vs something 'wrong' with the principle... YMMV)

**Comment by ashconnell** [comment]
I'm not on a computer right now but I solved this by executing a blur event inside the WebView.

Let me know if you want the specific code.

**Comment by paolomaffei** [comment]
@ashconnell something like this, I'd assume? `document.getElementById("...").blur()`

**Comment by alexmbarton** [comment]
@ashconnell 👍 

I'm wrapping an old ember application in React Native and are bridging between the two.

I solved it by running `document.activeElement && document.activeElement.blur()` then `Keyboard.dismiss()`.
