### ISSUE TITLE
Maximum call stack size exceeded when running react-native link

### ISSUE THREAD

**Issue by aymericbouzy** [facebook/react-native#12188]
### Description

What I did : I ran `react-native link`
I expected the command to succeed, here was the output : 
```
rnpm-install ERR! It seems something went wrong while linking. Error: Maximum call stack size exceeded 
Please file an issue here: https://github.com/facebook/react-native/issues 

Maximum call stack size exceeded

```

### Reproduction

Haven't been able to reproduce yet (I can reproduce fine with my current repo, I just cannot create a broken project from a new project).

### Solution

I've no idea.

### Additional Information

* React Native version: 0.37 (would love to upgrade, I cannot because of #3406)
* Platform: not relevant
* Operating System: MacOS 10.12.2

**Comment by aymericbouzy** [comment]
When running `react-native link react-native-material-kit` I get : 
```
rnpm-install info Android module react-native-material-kit is already linked 
rnpm-install ERR! It seems something went wrong while linking. Error: Maximum call stack size exceeded 
Please file an issue here: https://github.com/facebook/react-native/issues 

Maximum call stack size exceeded

```
Same with any other package.
It makes me think the issue is with the iOS Platform.

**Comment by aymericbouzy** [comment]
The culprit is the 'xcode' package. It fails parsing my project at line 10 of file `local-cli/link/ios/isInstalled.js`.

Adding a better error message would be nice.

Here is the stacktrace : 
```
RangeError: Maximum call stack size exceeded
    at RegExp.test (native)
    at peg$parseIdentifier (/Users/aymericbouzy/Documents/Développement informatique/instant_job_app/node_modules/xcode/lib/parser/pbxproj.js:1216:19)
    at peg$parseCommentedIdentifier (/Users/aymericbouzy/Documents/Développement informatique/instant_job_app/node_modules/xcode/lib/parser/pbxproj.js:724:12)
    at peg$parseCommentedAssignment (/Users/aymericbouzy/Documents/Développement informatique/instant_job_app/node_modules/xcode/lib/parser/pbxproj.js:611:12)
    at peg$parseAssignment (/Users/aymericbouzy/Documents/Développement informatique/instant_job_app/node_modules/xcode/lib/parser/pbxproj.js:542:14)
    at peg$parseAssignmentList (/Users/aymericbouzy/Documents/Développement informatique/instant_job_app/node_modules/xcode/lib/parser/pbxproj.js:462:14)
    at peg$parseAssignmentList (/Users/aymericbouzy/Documents/Développement informatique/instant_job_app/node_modules/xcode/lib/parser/pbxproj.js:467:18)
    at peg$parseAssignmentList (/Users/aymericbouzy/Documents/Développement informatique/instant_job_app/node_modules/xcode/lib/parser/pbxproj.js:467:18)
    at peg$parseAssignmentList (/Users/aymericbouzy/Documents/Développement informatique/instant_job_app/node_modules/xcode/lib/parser/pbxproj.js:467:18)
    at peg$parseAssignmentList (/Users/aymericbouzy/Documents/Développement informatique/instant_job_app/node_modules/xcode/lib/parser/pbxproj.js:467:18) 
```

**Comment by dxiao** [comment]
Just ran into this issue as well. How did you figure out the callstack?

**Comment by juddey** [comment]
I've got this one as well.

**Comment by aymericbouzy** [comment]
I went in the file and logged the error's stack ;)

**Comment by dxiao** [comment]
In case anybody else runs into this kind of error, ended up being my own fault. Creative insertion of console.log()'s into `node_modules/react-native/local-cli/link/ios/isInstalled.js` and `node_modules/xcode/lib/parse/pbxproj.js` showed me the issue. It turns out I had recently upgraded react-native, and while fixing merge conflicts from react-native-git-upgrade had introduced a duplicated entry into my project.pbxproj file. Once it cleared that up, everything worked fine.

**Comment by aymericbouzy** [comment]
Thanks! Any tip on finding the duplicated entry? I'm considering going through my git history to find the breaking commit and then inspect it, but maybe you have a more efficient way of doing this?

**Comment by aymericbouzy** [comment]
I used `git bisect` to find the commit, running `react-native link` at each step.
I restored the `project.pbxproj` to the way it was on the latest "good" commit. Indeed, I had broken the file when I had tried upgrading.
From there, I restored the project to its current state (I had not done much change to the Xcode project luckily), and everything works fine ! thanks @dxiao.

It would be nice to have file parser that helps with upgrading the Xcode project when upgrading React Native, that would at least tell if the `project.pbxproj` "looks fine".

**Comment by juddey** [comment]
I had duplicates in my `.pbxproj` too. Once I removed those and re-ran, all was fine.

**Comment by sathyakumarseshachalam** [comment]
I have removed the duplicates in my `.pbxproj` via [xUnique](https://github.com/truebit/xUnique). Yet I keep getting the below error
```
rnpm-install info Android module react-native-fbsdk is already linked
rnpm-install ERR! It seems something went wrong while linking. Error: Maximum call stack size exceeded
Please file an issue here: https://github.com/facebook/react-native/issues
```
And almost sure .pbxproj is at fault here, for a couple commits back, this works without any problem, but just not able to pinpoint the problem. 

PS : I come from a non-ios/xcode background

**Comment by sathyakumarseshachalam** [comment]
My bad. Had duplicate image assets. Removing them and re-running helped.

**Comment by cdesch** [comment]
Letting Xcode Update the project settings fixed the issue for me.

**Comment by jamesone** [comment]
@cdesdh Can confirm that this fixed it for me! For anyone wanting to know where you can update to the recommended settings: open xcode => the left sidebar should give you the option to update the recommended settings (it should have a yellow warning symbol next to it).

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by atitpatel** [comment]
Facing the same issue for lottie-react-native while linking. I am doing it for android. Any help is appreciated.

**Comment by Build100** [comment]
Opened the old project for Android. I see the same error. Fixed in package.json 
    "react": "16.0.0",
    "react-native": "0.49.0",
App working.

**Comment by sakamaki** [comment]
I avoided the error with the following command.
5000 is appropriate.

```
node --stack-size=5000 `which react-native` link
```

**Comment by jaxatto** [comment]
Having the same issue for react-native link react-native-svg. @cdesch / @jamesone's solution didn't work for me for this issue, though it did for a different maximum stack issue?
```

rnpm-install info Linking react-native-svg android dependency 
rnpm-install info Android module react-native-svg has been successfully linked 
rnpm-install ERR! Something went wrong while linking. Error: Maximum call stack size exceeded 
Please file an issue here: https://github.com/facebook/react-native/issues 

Maximum call stack size exceeded
```

**Comment by solaomosola** [comment]
Same issue, was able to fix it by deleting libRNFetchBlob.a from Recovered References. Works fine now.
