### ISSUE TITLE
[Navigator] Navigator vs. NavigatorIOS please fix docs

### ISSUE THREAD

**Issue by soheil** [facebook/react-native#1219]
Someone should update this doc; how is one supposed to know the difference between Navigator and NavigatorIOS?
http://facebook.github.io/react-native/docs/navigator.html#content

It should be noted Navigator uses JS animations and that you cannot pass `props` in the same way as NavigatorIOS. I modified my entire app only to find out that Navigator is not what I want because the animations suck and don't feel native!

Also explain exactly why they are two different components, this should be in bold on top of both their doc pages. I'm yet to know the logic behind having two different ones.

**Comment by jtremback** [comment]
:+1:

**Comment by brentvatne** [comment]
> I modified my entire app only to find out that Navigator is not what I want because the animations suck and don't feel native!

Aw man, sorry to hear that. Which animations are you having trouble with? When you say they don't feel native, is it because they feel janky or just don't seem like they are the correct animations?

> Someone should update this doc; how is one supposed to know the difference between Navigator and NavigatorIOS?

> Also explain exactly why they are two different components, this should be in bold on top of both their doc pages. I'm yet to know the logic behind having two different ones.

I believe that by reading the docs for each it is not too difficult to determine the differences, but agree that it might be useful to have a sentence at the top explaining how they relate to each other.

Notice how with `NavigatorIOS` there is no way to add your own custom navigation bar? It uses the native implementation for it. `Navigator` allows you to write your own component to use as a navigation bar. Additionally, `NavigatorIOS` adds support for swipe-back, but `Navigator` has many more transitions available (eg: you can swipe a view down to dismiss it with `floatFromTop`), and they can be customized as well!

Would a description like the above help to have in the documentation? Or would there need to be more information?

As for passProps, this is all done with `renderScene` I believe - you get the data from the route object that you pushed and then pass it in as a prop to the component that you render here.

**Comment by jtremback** [comment]
I feel like there was some way to add custom stuff to a basic nav bar when I was doing a little true native dev- would this be at all worth adding or is the functionality too hobbled?

**Comment by brentvatne** [comment]
@jtremback - `NavigatorIOS` uses [UINavigationController](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UINavigationController_Class/), check it out to see what options are exposed

**Comment by jtremback** [comment]
I can set [leftBarButtonItem](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UINavigationItem_Class/index.html#//apple_ref/occ/instp/UINavigationItem/leftBarButtonItem) from JS?

**Comment by brentvatne** [comment]
@jtremback - you can set the `leftButtonIcon` and `leftButtonTitle`, see #1230 for issue to improve parsing of the docs for this

**Comment by iostalk** [comment]
Doc no good

**Comment by nigelmanson** [comment]
+1 the documentation needs to be clearer. PS good work guys so far..

**Comment by yelled3** [comment]
I was about to open a similar PR and found this, so :+1: @soheil 

@brentvatne 
> Would a description like the above help to have in the documentation? Or would there need to be more information?

I would even go further and suggest adding a new page in the docs that compares between `Navigator` and `NavigatorIOS`. 
It would also be helpful to include examples to use cases where it's best to use one and not the other.

**Comment by sharathprabhal** [comment]
> I would even go further and suggest adding a new page in the docs that compares between Navigator and NavigatorIOS.

^ +1

**Comment by brentvatne** [comment]
Thanks for the :+1:'s folks, helps me to prioritize this

**Comment by richardscarrott** [comment]
+1

**Comment by faithfe** [comment]
＋1

**Comment by mitchozer** [comment]
+1, thanks!

**Comment by AdamBrodzinski** [comment]
+1 and thanks for the info in this issue, makes it much more clear :+1:

**Comment by albertwchang** [comment]
+1
The problem I am having is with giving a bar button item access to objects and variables local within the target scene.  Example:  Scene 1 goes to Scene 2, but I setup the "onRightButtonPress()" function in Scene 1.

I am using the REACT-NATIVE-SIDE-MENU module in Scene 2, and do not know how to have the Bar Button Item access this component...

**Comment by ssssssssssss** [comment]
> @soheil - aw man, sorry to hear that. Which animations are you having trouble with? When you say they don't feel native, is it because they feel janky or just don't seem like they are the correct animations?

@brentvatne The animation of Navigator feels really janky and the animation is not identical to the NavigatorIOS. The interpolator of Navigator module should be "RightToLeft" if I remember correctly.

**Comment by soheil** [comment]
sorry I stopped using react native

**Comment by brentvatne** [comment]
I haven't had much time for this recently but should get around to fixing up a bunch of docs this week. Additionally, to better reflect Facebook's priorities the idea is to move NavigatorIOS [to an OSSLibraries folder](https://github.com/facebook/react-native/issues/1519) and outside of the internal sync process which will allow us (the OSS community) to iterate on it more quickly.

**Comment by paramaggarwal** [comment]
From what I understand, the two drawbacks `Navigator` has are swipe-to-go-back and JS driven animations - while there are a number of other benefits. Any view 'controller' that iOS provides can very well be in JS because it is just logic. The view continues to remain native, but the control is now driven from JS. This makes it more customisable.

Fortunately even the two drawbacks as mentioned can theoretically be fixed. Apple provides a EdgeSwipe UIGestureRecognizer that can be used/enabled on Navigator, to get fluid swipe to go back animation. Also JS driven animations will definitely get better as the RN team is working/exploring it very deeply.

**Comment by wootwoot1234** [comment]
+1

**Comment by brentvatne** [comment]
Done: [https://facebook.github.io/react-native/docs/navigator-comparison.html](Navigator Comparison)

(just pushed, should be up within a few minutes)

**Comment by wootwoot1234** [comment]
cool! links broken though.  ;)

**Comment by ide** [comment]
That's github being too clever. Try this: [https://facebook.github.io/react-native/docs/navigator-comparison.html](https://facebook.github.io/react-native/docs/navigator-comparison.html)

**Comment by paramaggarwal** [comment]
This is very nice, thanks @brentvatne!

**Comment by brentvatne** [comment]
@paramaggarwal - if we can come up with a name that communicates that these libraries are considered not part of the core and not actively maintained by the core team, that would be nice :smile:

let's get them moved into an `OSSLibraries` directory first, and we can revisit when that's done!

**Comment by yelled3** [comment]
@brentvatne amazing work - thanks!


> separate sidebar section called Third Party or Libraries

@paramaggarwal I agree - I think people should know which component is more supported.

**Comment by nwpuhmz** [comment]
+1 ,thanks
