### ISSUE TITLE
Build release failed

### ISSUE THREAD

**Issue by radvc** [facebook/react-native#12208]
Im going to build the app for production, when I change the scheme to release I got the following error:

<img width="254" alt="error" src="https://cloud.githubusercontent.com/assets/11433690/22618968/25f05230-eb25-11e6-9d4c-d801dee2a2c2.png">

but when I build it to debug I dont have any errors

**Comment by rh389** [comment]
You'll need to add `-lc++` to your `projectTests` target. See https://github.com/facebook/react-native/issues/11861

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
