### ISSUE TITLE
Image problem after updating react-native version and Xcode

### ISSUE THREAD

**Issue by rishiankush** [facebook/react-native#12213]
I updated my react-native version and installed xcode 8.1, everything is working fine but only images does not load.

I have done everything:
1. Clear watchman watches: `watchman watch-del-all`.
2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.}

and many times but nothing was resolved.

I am using react-native 0.41 and xcode 8.

Previously my images in project were working fine but after updation when I cloned my project from github, I am getting this error always:
![screen shot 2017-02-05 at 7 41 06 am](https://cloud.githubusercontent.com/assets/25289937/22623172/877c246a-eb76-11e6-9611-0009de99687d.png)

I restarted packager, xcode and simulator, done with everything but nothing worked.

**Comment by ignatif** [comment]
Experiencing the same problem here

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
