### ISSUE TITLE
Automatically vendor Yoga.podspec along with the Yoga source code

### ISSUE THREAD

**Issue by ide** [facebook/react-native#12221]
#12089 updates the React Native podspec to reference a separate Yoga podspec. The Yoga podspec is the same as the one in the Yoga repo (https://github.com/facebook/yoga/blob/master/Yoga.podspec). It was manually copied but might be better to automatically sync it the same way the Yoga source code is synced here: https://github.com/facebook/react-native/tree/master/ReactCommon/yoga/yoga

**Comment by alloy** [comment]
Agreed. Right now I’ve made some modifications, but I have ideas on how to apply those while keeping it simple to merge the podspec from upstream.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
