### ISSUE TITLE
string function error @android [RN 0.4,0.41]

### ISSUE THREAD

**Issue by olimish** [facebook/react-native#12224]
I just wrote those code

var x = '\ud83d\udc0e\ud83d\udc71\u2764'.codePointAt(0);

this works on ios[device and simulator]
but, it can Not run on android platform[device and simulator], it 's so weird, if I open debug remote page, it works, if I just run on android (close debug remote page), it crashed.

undefined is not a function (evaluating ''\uD83D\uDC0E\uD83D\uDC71\u2764'.codePointAt(0)')
render
    index.android.js:18
<unknown>
    ReactCompositeComponent.js:1045
measureLifeCyclePerf
    ReactCompositeComponent.js:85
_renderValidatedComponentWithoutOwnerOrContext
    ReactCompositeComponent.js:1044
_renderValidatedComponent
    ReactCompositeComponent.js:1075
performInitialMount
    ReactCompositeComponent.js:484
mountComponent
    ReactCompositeComponent.js:346
mountComponent
    ReactReconciler.js:61
mountChildren
    ReactMultiChild.js:263
initializeChildren
    ReactNativeBaseComponent.js:74
mountComponent
    ReactNativeBaseComponent.js:211
mountComponent
    ReactReconciler.js:61
performInitialMount
    ReactCompositeComponent.js:495
mountComponent
    ReactCompositeComponent.js:346
mountComponent
    ReactReconciler.js:61
mountChildren
    ReactMultiChild.js:263
initializeChildren
    ReactNativeBaseComponent.js:74
mountComponent
    ReactNativeBaseComponent.js:211
mountComponent
    ReactReconciler.js:61
performInitialMount
    ReactCompositeComponent.js:495
mountComponent
    ReactCompositeComponent.js:346
mountComponent
    ReactReconciler.js:61
performInitialMount
    ReactCompositeComponent.js:495
mountComponent
    ReactCompositeComponent.js:346
mountComponent
    ReactReconciler.js:61
performInitialMount
    ReactCompositeComponent.js:495
mountComponent
    ReactCompositeComponent.js:346
mountComponent
    ReactReconciler.js:61
mountComponentIntoNode
    ReactNativeMount.js:54
perform
    Transaction.js:149
batchedMountComponentIntoNode
    ReactNativeMount.js:77
perform
    Transaction.js:149
batchedUpdates
    ReactDefaultBatchingStrategy.js:65
batchedUpdates
    ReactUpdates.js:111
renderComponent
    ReactNativeMount.js:141
render
    ReactNative.js:31
renderApplication
    renderApplication.js:33
run
    AppRegistry.js:76
runApplication
    AppRegistry.js:105
__callFunction
    MessageQueue.js:236
<unknown>
    MessageQueue.js:108
guard
    MessageQueue.js:46
callFunctionReturnFlushedQueue
    MessageQueue.js:107

### Description

string function can Not use at android @ rn 0.40 & 0.41

### Additional Information

* React Native version: [0.40,0.41]
* Platform: [Android]
* Operating System: [MacOS]

**Comment by K-Leon** [comment]
It's just not supported on Android JS Engine (check  https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/String/codePointAt). If you run Debugging the JS Code is executed in Chrome - if not the JS Engine on Android is used  and fails.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
