### ISSUE TITLE
Border around a view leaves some area around the edges in the view color in iOS

### ISSUE THREAD

**Issue by varungupta85** [facebook/react-native#12278]
### Description

I am trying to create circular badges that I can then place over user avatars to show their availability. I have a `View` which has a `borderRadius` to make it circular. I have also defined a `borderWidth` to have a bit of white space around the badge. Below app on rnplay demonstrates what I am doing

https://rnplay.org/apps/eNIbjw

Please note that there is a bit of a green color around the white border in iOS which is not correct. On Android, it looks fine and there is no green color around the border. I have asked this question on [stackoverflow](http://stackoverflow.com/questions/40974343/border-around-a-view-leaves-some-area-around-the-edges-in-the-view-color-in-reac) but I have been told that this looks like a bug and should be filed as an issue.

### Reproduction

rnplay app link pasted above.

### Solution

I don't know how to solve this issue.

### Additional Information

* React Native version: 0.37.0
* Platform: iOS
* Operating System: MacOS

**Comment by shergin** [comment]
(t12462956)

**Comment by varungupta85** [comment]
hi @shergin I am not sure what `(t12462956)` is supposed to mean? Are you referring to some commit which fixes this problem? Thanks!

**Comment by shergin** [comment]
@varungupta85 I updated original comment. I am sorry for unclarity. :(

Have you tried to wrap the <Image> in <View> and apply bordering to the <View>?

If it will not work, you also can try another super hacky workaround: try specify slightly different border radius value to one of the angles of the <View> (or specify slightly different top border width), it should switch internal bordering mechanism from "CoreGraphics powered" to "manual rendering" which doest not have this problem.

**Comment by varungupta85** [comment]
hi @shergin , thanks for providing more info. I wouldn't call myself a power `react-native` user and I apologize for my lack of knowledge. Although I understand what you commented but I don't know how to implement it. If you think it wouldn't take too much of your time, could you please provide an example of how to achieve what you have suggested.

I will try to figure it out on the internet in the mean time and comment back if I find a way to do it.

Thanks!

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
