### ISSUE TITLE
PanResponder e.nativeEvent BUG ANDROID

### ISSUE THREAD

**Issue by freddie17** [facebook/react-native#12282]
### Description

Bug in onResponderMove : locationX never changes

### Reproduction
```
<View
        onTouchMove={(e) => {console.log( e.nativeEvent)}}
       />
```
console.log give me the same value then I moved cursor.

### Additional Information

* React Native version: [0.22, 0.28, 0.30, 0.38, 0.40, 0.41....]
* Platform: [Android]
* Operating System: [MacOS]

**Comment by capozzid** [comment]
Same problem here with RN 0.41

**Comment by linytsysu** [comment]
I have the same problem with RN 0.39. I found locationX never changes but pageX changes.

**Comment by JonesN7** [comment]
RN 0.42

LocationX/Y Changes only on tapping on not while dragging. PageX/Y always changes.

**Comment by JonesN7** [comment]
https://github.com/facebook/react-native/issues/7221

**Comment by JonesN7** [comment]
#7221

**Comment by JonesN7** [comment]
#7221

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
