### ISSUE TITLE
[iOS][Native].h file can not found?

### ISSUE THREAD

**Issue by AlanMoMo** [facebook/react-native#12297]
We use GitHub Issues for bugs.

If you have a non-bug question, ask on Stack Overflow: http://stackoverflow.com/questions/tagged/react-native

If you have a feature request, post it on Product Pains: https://productpains.com/product/react-native/

--- Please use this template, and delete everything above this line before submitting your issue --- 

### Description

I meet the issue that can't found '<React/RCTBridgeModule.h>' file. I set the Header Search Patch like this picture.

<img width="587" alt="2017-02-09 4 43 24" src="https://cloud.githubusercontent.com/assets/18734693/22775488/e8e55a46-eee6-11e6-80f0-388bde71ee74.png">
<img width="815" alt="2017-02-09 4 44 19" src="https://cloud.githubusercontent.com/assets/18734693/22775655/a44fc33e-eee7-11e6-9c21-adf4f137be7b.png">

this is my directory structure：
<img width="244" alt="2017-02-09 4 45 31" src="https://cloud.githubusercontent.com/assets/18734693/22775556/330581fa-eee7-11e6-861c-f04301b51e4a.png">

### Reproduction

sometimes if the issue come,but the project can build success.I feel very confused。

### Additional Information

* React Native version: [0.41.2]
* Platform: [ iOS ]
* Operating System: [MacOS]

**Comment by zpp-gp** [comment]
delete  Build Settings --> Header Search Paths
$(SRCROOT)/../node_modules/react-native/React
$(SRCROOT)/../node_modules/react-native/ReactCommon

try a try

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
