### ISSUE TITLE
TabBarIOS: badgeColor only changes when systemIcon is used not reglar icon 

### ISSUE THREAD

**Issue by alfrednerstu** [facebook/react-native#12330]
### Description

When using TabBarIOS the badgeColor parameter only works if you use a systemIcon. When you provide your own icon the badge color reverts back to standard red.

### Reproduction

https://rnplay.org/apps/VSu2mw

Not reproducible on rnplay as system icons don't seem to work, but copy the project and run locally to reproduce.

### Solution

I don't have any solution. But as it works with system icons it might just be an oversight to make it work with custom icons?

### Additional Information

* React Native version: 0.40.0
* Platform: iOS
* Operating System: MacOS 10.12.3

**Comment by alfrednerstu** [comment]
Did some more testing and if you define a number from start the badgeColor works, it's only if you add the first number after load that the badge becomes red.

**Comment by magneticz** [comment]
@alfrednerstu, did you solve this issue? If I set the number before load, then by default it will be 0, and I don't want to display badge if it is 0.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
