### ISSUE TITLE
Switch layout calculation fails on Android (SwitchCompat)

### ISSUE THREAD

**Issue by duhecx** [facebook/react-native#12359]
### Description

Using Switch in my jsx fails with an error shown on the image below on Android, but works fine on iOS.
Tried changing buildToolsVersion, compileSdkVersion, targetSdkVersion in gradle config, but to no success.
Problem still persists on latest React native version (0.42.2).

![screenshot_1486988203](https://cloud.githubusercontent.com/assets/9784392/22884068/40c00810-f1f3-11e6-8c59-4860704be742.png)

Switch component used to work a few weeks ago. We were developing our app, so I'm not completely sure what changed, but I do know, we updated RN version from 0.40.0 to 0.42.2.
When I run "gradle clean", delete node_modules folder and run "npm install" with react native version 0.40 (same as before), I still get the same error. I can't get it to work anymore.

Anyone having same problem?

### Reproduction

```
class Sample extends Component {
  render() {
    return (
      <View>
        <Switch />
      </View>
    );
  }
}
```

### Solution

The issue seems to be in calculating Switch's layout size, but tries to call length() on a null text CharSequence object.
If only we could supply mShowText or mTextOn/mTextOff internal variables of a SwitchCompat...

See stack trace:
https://github.com/android/platform_frameworks_support/blob/master/v7/appcompat/src/android/support/v7/widget/SwitchCompat.java line 783 and line 864
https://github.com/android/platform_frameworks_base/blob/master/core/java/android/text/StaticLayout.java line 422

### Additional Information

* React Native version: 0.42.2 (tried also 0.40.0)
* Platform: Android
* Operating System: Windows, Linux (did not try on Mac)

**Comment by hey99xx** [comment]
Same as https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/issues/14

There's a bug report about Android switch view almost every month now; it seems many libraries use different versions of support libraries, always having incompatibility issues.

> If only we could supply mShowText or mTextOn/mTextOff internal variables of a SwitchCompat...

I think this is possible but not super straight-forward. Notice that `mShowText` can be customized with https://developer.android.com/reference/android/support/v7/widget/SwitchCompat.html#attr_android.support.v7.appcompat:showText. The default is also false, so I don't know how it's set to true.

To edit that through XML, you will need to put custom styles and themes inside your app, explained in 
https://android-developers.googleblog.com/2014/10/appcompat-v21-material-design-for-pre.html
https://developer.android.com/guide/topics/ui/themes.html

Likely code you need to have in values/themes.xml (just assuming based on the tutorial, didn't try myself)

    <style name="CustomTheme" parent="Theme.AppCompat">
        <item name="switchStyle">@style/MySwitchStyle</item>
    </style>
    <style name="MySwitchStyle" parent="Widget.AppCompat.CompoundButton.Switch">
        <item name="showText">false</item>
    </style>

then in your AndroidManifest.xml

    <application android:theme="@style/CustomTheme">

**Comment by hey99xx** [comment]
All that said, I think RN should have a fix hopefully. In my app, none of the devs is using the React switch component because of all the other bugs it got reported about. So we decided it's not worth it, and rolled out our own switch implementation with touchables.

**Comment by rgngl** [comment]
The problem is caused by using `SwitchCompat` on an `Activity` that is not `AppCompatActivity`, so I am assuming your application is not using the `ReactActivity`(or you have a hybrid app).

As a workaround you can create your own `Switch` component by copying from RN sources and replace `	android.support.v7.widget.SwitchCompat` with an `android.widget.Swich`.

**Comment by hey99xx** [comment]
@rgngl Do you have a source that explains why `SwitchCompat` needs to be used only with `AppCompatActivity`? This is the first time I am hearing this requirement. 

But you are correct, I am not using `ReactActivity`. I am integrating React with an existing app which is already using a custom base class from `android.support.v4.app.FragmentActivity`. Then again I don't know what the other developers also suffer from the same issue.

**Comment by rgngl** [comment]
@hey99xx if you look at the source code of `SwitchCompat` you'll see in the constructor it's referring to some appcompat related resources. So your context should have a theme from from that package. If you try to set an AppCompat theme to a normal activity it throws out an exception while initializing saying that you can only use it with an `AppCompatActivity`.

https://github.com/android/platform_frameworks_support/blob/master/v7/appcompat/src/android/support/v7/widget/SwitchCompat.java#L236

**Comment by hey99xx** [comment]
@rgngl I don't think your explanation makes sense. `ReactActivity` itself does not extend from `AppCompatActivity` so by your explanation `Switch` should have never worked. FYI `ReactActivity` extends from regular `android.app.Activity` and `ReactFragmentActivity` extends from `android.support.v4.app.FragmentActivity` which I am also using in my app.

I do think that there is a problem with theme resources, but a different one. I also don't believe all the people who have commented on https://github.com/facebook/react-native/issues/10877 are intentionally deviating from `ReactActivity` the way I am. I will try to render a `Switch` within an  `AppCompatActivity` but I have low hopes.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
