### ISSUE TITLE
Confusion on which APIs should work (or must be mocked) in a jest testing environment

### ISSUE THREAD

**Issue by thurt** [facebook/react-native#12363]
### Description
when I was using react-community/react-navigation, I realized that I had to create stubs for the react-native Linking API in order to snapshot test my navigators without getting exceptions. 

Then, I went on to test another component which uses the Dimensions API, expecting that I should stub Dimensions, only to find out that Dimensions actually works inside the jest testing environment; when I call `Dimensions.get('window')` in a jest test i get back,
```
{
  height: 1334,
  width: 750,
  scale: 2,
  fontScale: 2
}
```

what you expected to happen: i expected that all react-native APIs would need to be manually mocked/stubbed by the end user. 

What actually happened: some APIs appear to have implementations while others don't

### Solution

i'm hoping for some more explanation/documentation/guidance about what APIs I need to manually stub vs. APIs which already work in jest.

### Additional Information

* React Native version: 0.41.2
* Platform: not platform specific
* Operating System: not OS specific

**Comment by ericvicenti** [comment]
@cpojer, maybe we should add a doc that discusses mocks for RN testing?

**Comment by cpojer** [comment]
The ideal solution is to provide great mocks for everything that needs to be mocked by default. Meanwhile, updating the docs on the RN or Jest website to include more detail about the RN environment sounds like a good idea.

**Comment by thurt** [comment]
Some updates:

Linking library mock is coming #13049 

and for anyone looking for info on what mocks are currently provided, you may look here https://github.com/facebook/react-native/blob/master/jest/setup.js

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
