### ISSUE TITLE
Packager doesn't launch automatically on Windows and Linux

### ISSUE THREAD

**Issue by jrodiger** [facebook/react-native#12367]
### Description

When running `react-native run-ios` or `react-native run-android` on Mac OS, the packager is launched automatically in a new terminal window while the project is built. On Windows and Linux `react-native start` needs to be run manually in a separate shell, while `react-native run-android` is run in a different shell.

### Reproduction

Run `react-native run-android` on Windows or Linux, and the project will not start the packager automatically.

### Solution

Packager should launch automatically on Windows and Linux, like it does on Mac OS.

### Additional Information

* React Native version: 0.41.2
* Platform: Android
* Operating System: Windows & Linux

**Comment by sinxwal** [comment]
As i see, linux packager launcher is broken after this commit
https://github.com/facebook/react-native/commit/c6a3052c73379eaffa08fd8a6a843c1ebebe2175
sh does not support pushd, source and popd commands.
Fast fix is to update runAndroid.js like this:
} else if (process.platform === 'linux') {
    procConfig.detached = true;
    if (yargV.open){
      return child_process.spawn(yargV.open,['-e', 'bash', launchPackagerScript], procConfig);
    }
    return child_process.spawn('bash', [launchPackagerScript], procConfig);
  }

I.E. change 'sh' to 'bash'.

**Comment by jrodiger** [comment]
@sinxwal Just tested on RN version 0.43.3 and confirmed the fix you suggested works. Are you planning on submitting a pull request?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
