### ISSUE TITLE
ScrollView Broken on iOS Devices (emulator fine)

### ISSUE THREAD

**Issue by yaalax-steve** [facebook/react-native#12366]
### Description

I found when developing a complex application that ScrollView would work fine everywhere, except iOS physical devices. The iOS simulator, Android devices, all work without a problem. The symptom is that the scrollview will snap back immediately to the top of the area (but if you keep scrolling, all child content is rendered and the heights in the hierarchy are correctly measured).

If I add logging to the onScroll event, I can see my manual scrolls, but as soon as I release, another scroll event is raised and everything moves back to the top. 

__UPDATE__: The issue _does not_ occur if the app on the device is running from the local bundle. If I switch the device to flight mode, close and re-open the app, when it uses the local bundle the app scrolls perfectly. I suspect it's something to do with development mode behaviours now - though I can still get to the shake-menu on the device even running solo.

### Reproduction

````
// NPM Imports
import React, { Component } from 'react';
import { ScrollView, Text } from 'react-native';

export default class MinimumExample extends Component {
  /**
   * Render the root application component.
   */
  render() {
    return (
         <ScrollView >
          <Text style={{fontSize:96}}>Scroll me plz</Text>
          <Text style={{fontSize:96}}>If you like</Text>
          <Text style={{fontSize:96}}>Scrolling down</Text>
          <Text style={{fontSize:96}}>What's the best</Text>
          <Text style={{fontSize:96}}>Framework around?</Text>
          <Text style={{fontSize:80}}>React Native</Text>
        </ScrollView>
    );
  }
}
````

On RNPlay at: https://rnplay.org/apps/3mtJPg

Notice that scrolling vertically works as expected on both emulators.

### Solution

ScrollView should work on physical devices.

### Additional Information

* React Native version: 0.41.2
* Platform: iOS
* Operating System: MacOS

**Comment by orhan** [comment]
I can confirm that this is happening, took me hours to find a fix until I gave up.
Running the app under the "Release" build configuration, it works fine!

## **Additional Information**

- React Native version: 0.42.0
- Platform: iOS
- OS: macOS

**Comment by d7laungani** [comment]
I also have this issue so it still exists

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
