### ISSUE TITLE
onPressIn doesn't work if key has been changed

### ISSUE THREAD

**Issue by ptol** [facebook/react-native#12364]
`onPressIn` doesn't work every other touch.
```
import React, { Component } from 'react';
import {AppRegistry, TouchableWithoutFeedback, Text, View} from 'react-native';

export default class test extends Component {
	constructor(props) {
		super(props);
		this.state = {index: 1};
		this.inc = this.inc.bind(this);
	}
	inc() {
		this.setState({index: (this.state.index + 1)});
	}
	render() {
		return (
		<TouchableWithoutFeedback onPressIn={this.inc} key={this.state.index}>
			<View>
				<Text>Index {this.state.index}</Text>
			</View>
		 </TouchableWithoutFeedback>
		)
	}
}

AppRegistry.registerComponent('test', () => test);
```
If you remove key from
```
<TouchableWithoutFeedback onPressIn={this.inc} key={this.state.index}>
```
or replace `onPressIn` with `onPress` it would work every touch.

* React Native version: 0.41
* Platform: Android
* Operating System: Windows

**Comment by hey99xx** [comment]
There might be a bug in RN, but this example looks like it's intentionally created to make things fail. In what real life scenario, does key have to change in the middle of a press?

**Comment by ptol** [comment]
@hey99xx For example, I want to use object id as a key and I want to show new objects `onPressIn`.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
