### ISSUE TITLE
ScrollView inside a View. Pass pan events from View to ScrollView

### ISSUE THREAD

**Issue by grundmanise** [facebook/react-native#12362]
I have a `ScrollView` inside a `View`. `ScrollView` is smaller than the `View`. I need to start a `pan event` on the `View` (outside of the `ScrollView` `bounds`) and pass it to the `ScrollView`, so that I can scroll the `ScrollView` while panning on the parent `View`. How can I pass a `pan events` from a `View` to the `ScrollView`?

Is it possible to set something like:

`[self.view addGestureRecognizer:mainScrollView.panGestureRecognizer];`

without touching the native code? With `PanResponder`?

**Comment by shergin** [comment]
It almost impossible on iOS.
`UIScrollView`'s panGestureRecognizer cannot start recognition without "capturing" `touchStart` event. You probably can workaround it overriding `hitTest:withEvent:` method of your view and return your `UIScrollView` instance as event target. It kinda makes your UIScrollView covers UIView from events perspective.
This question is unrelated to React Native though.

**Comment by grundmanise** [comment]
@shergin

I saw [this answer ](http://stackoverflow.com/questions/1220354/uiscrollview-horizontal-paging-like-mobile-safari-tabs/1220605#1220605). But I don't understand, in my custom RN component, how can I return `UIView` ( from the `- (UIView*)view` method ) that contains `UIScrollView` and pass all `RCT_EXPORT_VIEW_PROPERTY` to the `UIView`'s child - `UIScrollView`?
...is it something to do with delegation?

or maybe I should create a separate `UIView` component that only implements `hitTest:withEvenet` and somehow pass a `UIScrollView` reference to this component's `hitTest:withEvenet`?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
