### ISSUE TITLE
Task 'installDebug' not found in root project 'android'.

### ISSUE THREAD

**Issue by Poney1** [facebook/react-native#12376]
### Description
Integration With Existing Apps  and  execute "react-native run-android" 

![image](https://cloud.githubusercontent.com/assets/10766773/22923482/9ce272ce-f2dc-11e6-9854-1f8498656043.png)

### Additional Information

* React Native version: [the lastest version]
* Platform: [FILL THIS OUT:  Android, ]
* Operating System: [ Windows 7 x64 ]

**Comment by christopherdro** [comment]
https://github.com/facebook/react-native/issues/2720#issuecomment-140562534

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
