### ISSUE TITLE
[iOS] VoiceOver focus does not automatically move to first unrendered element in ListView

### ISSUE THREAD

**Issue by oargaruna** [facebook/react-native#12374]
### Description

Our project is a hybrid of React Native modules and native UI. We are adding accessibility to our App and are hitting a weird issue with VoiceOver in ListView:

VoiceOver does not automatically shift focus to elements rendered after the last visible element in a ListView.

### Reproduction

I have been able to reproduce the bug in a sample app: https://github.com/oargaruna/ListViewVoiceOver

1. Deploy the App on an iOS device
2. Enable VoiceOver (from Settings -> General -> Accessibility) and open the Sample App
3. Tap once on the last visible Image to give it VoiceOver focus
4. Flick right to move focus to the next element.

After VoiceOver focus, reaches the last element in the row, we expect the focus to automatically move to the first element in the next row.

### Additional Information

* React Native version: 0.41
* Platform: iOS

**Comment by shergin** [comment]
That's terrible. 😿 
I will try to fix it. `t16126090`

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
