### ISSUE TITLE
Platform specific libraries - automatic linking

### ISSUE THREAD

**Issue by Thibaut-Fatus** [facebook/react-native#12375]
### Description

When using react-native link every dependency is linked to both iOS and Android projects, and I found no way (neither in rnpm legacy code nor react-native cli) to choose to link a lib only to a specific platform (Firebase Cloud Messaging in my case)

### Reproduction

Add a lib you want to use only in iOS or respectively in Android, call react-native link, lib will be linked to both projects.

### Solution

We should have something like 'androidDependencies' and 'iosDependencies' in our package.json, which react-native link could understand and accordingly use to only link lib to desired platform.

### Additional Information

* React Native version: 0.41, cli 1.0.0
* Platform: iOS / Android
* Operating System: MacOS

**Comment by Thibaut-Fatus** [comment]
Feel free to give me guidelines on how you'd like to see this support added, I'll be glad to help.

For what I've seen it won't be over complicated to patch [react-native/local-cli/link/link.js](https://github.com/facebook/react-native/blob/1c249e4804030b5691adf508751c369bf0036f1c/local-cli/link/link.js) but I'm unsure how to declare this dependencies (adding react-native specific keys to npm package.json is simple, but probably incorrect)

**Comment by jjhesk** [comment]
this is the new `rnpm` introduced by the cli? can I have more materials to catch up how to building automatic linkings pls?

**Comment by Thibaut-Fatus** [comment]
rnpm has been merged 7 months ago to react-native cli as react-native link

**Comment by loug38** [comment]
I actually really like the idea of the dependancies being declared platform specific in the package.json but maybe have it be 'sharedDependencies', 'androidDependencies', and 'iosDependencies' since I feel 90% of libraries will be shared on both platforms writing everything twice seems unnecessary.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by calcazar** [comment]
Just wanted to quickly add my two cents on this issue and hopefully have it reopened. My team is currently facing an issue where running react-native link causes issues with the Android build when using a certain library. 

While I understand that this is an open issue with that specific library.. it's a good example of where specifying the platform can come in handy. Until that issue is fixed, my team is contemplating writing a script that prevents the android build of the library from kicking off.. would be nice if we could control which platform to link from instead.. I envision something like:

react-native link <LibraryName> <Platform>

Platform would be an optional parameter in this case and would default to both platforms unless explicitly specified.

it isn't as simple as this though.. I imagine that we want to hold some kind of record indicating which libraries were linked to which platforms in case someone runs the more global react-native link. For this I envision something similar to the lock files in yarn/npm. That way if someone where to run react-native link it would link the libraries to their respecting platforms.

**Comment by tommynordli** [comment]
I'm also having issues with `react-native-fcm` being linked in iOS when I'm running `react-native link`. It would be really nice to have platform specific dependencies
