### ISSUE TITLE
app::bundleReleaseJsAndAssets gets stuck never progress

### ISSUE THREAD

**Issue by khalidahmada** [facebook/react-native#12378]
I'm trying to generate release version of my app using React-native :

`./gradlew assembleRelease`
It's progress until **app::bundleReleaseJsAndAssets** gets stuck at 93% and never progress. I dont have any error on terminal.

About OS I'm on Mac OS.

**Comment by jaimecorrea** [comment]
Same issue here, Mac OS

**Comment by wilomgfx** [comment]
Did you fix it ? Im having the same issue on macOs 10.12.4

**Comment by jaimecorrea** [comment]
Hi, this worked for me:

To set a limit add the following environment variable:

export REACT_NATIVE_MAX_WORKERS=2

https://github.com/facebook/react-native/issues/11696

**Comment by wilomgfx** [comment]
@jaimecorrea  does not work for me. It hangs at 92%

**Comment by billpatterson** [comment]
Same here. This is not (only?) a workers-limit problem. Changing that setting has no effect at all on the issue for me.

**Comment by beansoftapp** [comment]
I've encounter issue too, found a temp solution:
edit android/app/build.gralde
 and comment out the react.gradle call.
//apply from: "../../node_modules/react-native/react.gradle"

then you can create your bundle with a call of:

react-native bundle --platform android --entry-file index.android.js --reset-cache --bundle-output android/app/src/main/assets/index.android.bundle --dev false --assets-dest android/app/src/main/res/

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by TGPSKI** [comment]
Hi, I ran into this problem getting our Android app published, and ended up writing a medium article that addresses this and related issues.

https://medium.com/@paterw00t_17915/android-react-native-fastlane-working-with-multiple-build-types-a9a6641c5704

**Comment by fendorio** [comment]
Anyone coming here as a new RN developer, when I build the production version of the app i'm currently working on (RN), it hangs at 93%:

> Building 93% > :app:bundleReleaseJsAndAssets

For around 22 minutes (mid 2012 macbook pro, 15, 4GB RAM), it does then indeed finishing building.
