### ISSUE TITLE
Bugs in Animated + useNativeDriver time values

### ISSUE THREAD

**Issue by mosesoak** [facebook/react-native#12388]
### Description

When `useNativeDriver` is used with a supported value like `opacity`, several bugs manifest around time values:

- `delay` appears to operate in seconds, not milliseconds. This makes it look like the animation doesn't run at all, when in fact it's just delaying for several minutes.
- When `delay` is set, `duration` doesn't appear to work – animations just jump to their end frame without tweening.

### Reproduction

https://rnplay.org/apps/MQ5xNg

### Solution

unknown

### Additional Information

* React Native version: 0.40.0
* Platform: iOS only (don't think useNativeDriver is implemented on Android yet)
* Operating System: MacOS

CC @kmagiera @janicduplessis

**Comment by janicduplessis** [comment]
Thanks for reporting this, I'll have a look, we don't have any tests with `delay` at the moment so it's very probable that it's broken.

**Comment by scarlac** [comment]
I think my issue is related to this. Let me know if you disagree, then I'll create a separate issue.
The issue is with `Animated.Text` and `opacity`:
```javascript
accountSelectorAnim = new Animated.Value(0)
// ...
Animated.parallel([
  Animated.timing(this.accountSelectorAnim, {
    toValue: 1,
    duration: 515,
    easing: Easing.easeOut,
    useNativeDriver: true,
  }),
  // ...  
]);
// ...
const textOpacity = animation.interpolate({
  inputRange: [0, 0.5, 1], outputRange: [0, 0.5, 1]
});
```
In render:
```jsx
<Animated.Text style={{opacity: textOpacity, color: 'white', marginBottom: 5}}>
Hello
</Animated.Text>
```
Only the first value in the interpolation will be applied (in this case 0, which means text will never appear). The rest of the values have no visible effect.
If I change the first value to something larger than 0, I can faintly see some kind of animation back and forth in opacity values before it quickly lands on the first outputRange value, but I'm not sure what it's doing.
If I set `useNativeDriver: false` then it works exactly as expected.

**Comment by janicduplessis** [comment]
@scarlac I think you can make a separate issue, I tested this and the issue is related to `delay` being broken on iOS.

@mosesoak Got a PR to fix this!

**Comment by mosesoak** [comment]
@janicduplessis awesome! 🎉

**Comment by bollogo** [comment]
I just stumbled upon this issue facing a similar problem with the native-driver support. Just a hacky workaround for people needing a delay until this is fixed. One can interpolate an animated value with an extra step and thus, faking a delay in the animation.

```javascript
Animated.interpolate(this.accountSelectorAnim, {
    inputRange: [0, 0.2, 1.0],
    outputRange: [0, 0, 1.0],
  });
```
