### ISSUE TITLE
Integration With Existing Apps ，Manifest merger failed with multiple errors, see logs

### ISSUE THREAD

**Issue by itxuye** [facebook/react-native#12412]
```groovy
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs
```

**Comment by itxuye** [comment]
Sorry,it's my problem.The minSdkVersion should be the same with the react native android minSdkVersion .

**Comment by hey99xx** [comment]
the app's minSdkVersion should be the same or higher than RN's minSdkVersion

**Comment by itxuye** [comment]
@hey99xx  Yes,Thanks .

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
