### ISSUE TITLE
[iOS] Problems with fetch/NetInfo while no internet connection

### ISSUE THREAD

**Issue by tomazahlin** [facebook/react-native#12436]
RN 0.41.0, using iOS 10.2 simulator.

In our project we are using fetch(), which is from react-native dependencies - whatwg-fetch.

On Android it works good, when there is no internet connection, we can catch the TypeError with message Network Request Failed immediately.

But on iOS, the promise doesn't get resolved or rejected when no internet connection, so we cannot catch the TypeError in simulator. On real device (iPhone 5s for example), it works okay.

Anyone else having the same issues, any solutions? Thanks!

**Comment by nhayfield** [comment]
i had good luck with this one: https://github.com/wkh237/react-native-fetch-blob

**Comment by MattyK14** [comment]
You could wrap it in a try & catch?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
