### ISSUE TITLE
React PropTypes warning with LayoutAnimation

### ISSUE THREAD

**Issue by janicduplessis** [facebook/react-native#12458]
We are calling PropTypes manually in LayoutAnimation which now triggers a warning since React 16. https://facebook.github.io/react/warnings/dont-call-proptypes.html explains the warning but there doesn't seem to be an ideal solution in our case, including a new dependency to do these validations seems a bit overkill and writing these validations manually a bit too complex.

Opening this issue to discuss what would be the best situation here. Some ideas...

- Write the validation manually
- Use a validation library that is pretty much the react prop types checker without the warning like https://github.com/developit/proptypes
- Use `console.ignoredYellowBox` to silence the warning.
- Include the React secret in RN and use it to silence the warning.

cc @gaearon @sebmarkbage

**Comment by janicduplessis** [comment]
I'm personally leaning towards point 3 or 4, those are more hacky but let's say that "we know what we are doing" :)

**Comment by sebmarkbage** [comment]
We have an open issue of this internally. We're exposing an external API to do the type checking explicitly. https://github.com/facebook/react/pull/9004

**Comment by MobiusHorizons** [comment]
is there a temporary work-arround? I had to update to 0.43-rc.2 to get `FlatList` because of unfixed android bugs in `ListView` but this bug makes development a pain. I guess it goes away in the production version of the app, but that's still a real pain in development. 

Also if there is specific work that you would like a PR for, I'd be glad to do it, as I know you guys have a lot of work on your plate.

**Comment by janicduplessis** [comment]
You can use console.ignoredYellowBox (http://facebook.github.io/react-native/docs/debugging.html#warnings)

**Comment by janicduplessis** [comment]
Also I have a PR already to fix this, should get merged soon and then we can include the fix in the next rc patch.

**Comment by fungilation** [comment]
I just upgraded to yesterday-released version of RN 0.43.0 and I'm seeing these yellow box warnings.

So please tell me. Is this ok to ignore in production as the PropTypes wouldn't be checked in production? Or there's a more proper fix coming before I release my app to production on RN 0.43?

Otherwise, in dev I'd just add these to yellowbox ignore. Thanks for a heads up on this as the last message here is 18 days ago.

**Comment by bvaughn** [comment]
Sorry for the temporary annoyance, folks! Andrew and I have been preparing the react 15.5.0 release for the last few days that will- among other things- provide a new "official" proptypes package to use for validation (as mentioned in facebook/react#9004).

Our plan is to publish an RC for all of the packages/add-ons (hopefully sometime this evening) so that people can do some test runs with react/react-dom. Presumably you could use this new standalone proptypes lib?

cc @acdlite in case I misspoke about timing WRT the proptypes lib

**Comment by gaearon** [comment]
The issue here is that 0.43 final was released yesterday but didn't include this fix: https://github.com/facebook/react-native/commit/d9910a5d610ca46e38349e49a99200bd6860cce6. So looks like everyone in open source will get this stray warning now. 😞 

cc @grabbou What can we do to get this fix out asap?

**Comment by bvaughn** [comment]
☹️  I didn't realize that 43 stable had gone out yet. I thought we were still on RC.

**Comment by gaearon** [comment]
For people encountering the warning: please feel free to [ignore it](http://facebook.github.io/react-native/docs/debugging.html#warnings) for now. Sorry this slipped through.

**Comment by grabbou** [comment]
I will cherry pick this ASAP as soon as I get to work, approx 2 hours.

**Comment by grabbou** [comment]
@bvaughn it goes stable at the end of the month, if there's anything that you are working that needs extra time, please let me know on Slack so we can better organise that 👍

**Comment by gaearon** [comment]
Thanks! Which Slack would that be?

**Comment by bvaughn** [comment]
Thanks @grabbou! I had been coordinating with @yungsters but I think he's on PTO at the moment. I don't know which Slack channel you're referring to either. Is it just the reactiflux channel? (I thought that moved to Discord?)

**Comment by grabbou** [comment]
It's reactnativecore.slack.com. We use it to coordinate things like
releases or work in projects. I believe you can get access by opening post
in Core Contributors group on FB.

**Comment by gaearon** [comment]
Left a comment there. I don't see a pinned post if that's what you mean 😅
