### ISSUE TITLE
run-android with custom package build variants launch wrong MainActivity

### ISSUE THREAD

**Issue by dkpalmer** [facebook/react-native#12480]
--- Please use this template, and delete everything above this line before submitting your issue --- 

### Description

I've setup three different build types: release, beta, and debug. beta and debug have different package names from release, e.g.:

release: com.myapp
beta: com.myapp.beta
debug: com.myapp.debug

When running `react-native run-android --variant=beta`, build and install work as expected (gradle commands use the proper variant). However, launching the app results in the Android CLI trying to launch `Starting: Intent { cmp=com.myapp/.MainActivity }` against the default app package. I was expecting the CLI to try and launch `cmp=com.myapp.beta/com.myapp.MainActivity`.

When I don't have any of these builds installed prior it just errors on launch ("MainActivity does not exist") and I can easily go in and manually launch the app. However, if I have my release build pre-installed, my release build ends up getting launched when trying to run both beta and debug variants, which can be confusing.

### Reproduction

CLI Issue

### Solution

The runAndroid.js script pulls the packageName from the src AndroidManifest.xml file. With different build types/variants/flavors, the app package may be different and should be pulled from `app/build/intermediates/manifests`. Then the command to launch should be similar to `adb shell am start -n com.myapp.beta/com.myapp.MainActivity`.

I have this working locally, but haven't tested it extensively with the different ways of running Android builds. I'm happy to put up a PR with what I have if anyone wants to collab on this.

### Additional Information

* React Native version: 0.42.0rc3
* Platform: Android
* Operating System: MacOS

**Comment by Snorlock** [comment]
This is known and a PR ongoing: https://github.com/facebook/react-native/pull/8950#issuecomment-281776167
Iv noticed that my app still works, even if the activity doesnt start. Just have to start i manually. I had problems with my app, and thought it was this, but it seemed that it was some selfmade bug.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
