### ISSUE TITLE
How can I bundle files inside android app?

### ISSUE THREAD

**Issue by sun2rise** [facebook/react-native#12490]
I am trying to bundle some file inside my react-native app.
I placed them inside android/app/src/main/assets/ folder but i don't know how to use them in debug and don't know how to load/read them. 

Moreover I would like to use those files inside a webview (html and js)..

What are my possibilities?
Thank you

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
