### ISSUE TITLE
in scrollView, onResponderRelease Event not fired on android

### ISSUE THREAD

**Issue by yoohoogun114** [facebook/react-native#12505]
### Description

in scrollView, onResponderRelease Event not fired on android

but it works nicely on ios.

### Reproduction

```javascript
<ScrollView ref={(ref) => this._scrollView = ref} scrollEnabled={true} showsVerticalScrollIndicator={false}
                          onScroll={(evt) => this.handleScroll(evt)} scrollEventThrottle={200}
                          onResponderRelease={(evt) => {console.log('release')}}
              >
blah blah blah
</ScrollView>
```

the above code works nice on ios. (logged on console correctly)

but it doesn't fire on android. 

### Solution

in scrollView, onResponderRelease event fire on android

### Additional Information

* react-native-cli: 2.0.1
* react-native: 0.40.0
* Platform: android(6.0.0)
* Operating System: mac os(10.12.3)

**Comment by brentvatne** [comment]
This isn't an exposed prop on ScrollView and so there is no contract with the component user that this should work. I'm not sure why exactly it's not called on Android but if you want to investigate you're welcome to!

**Comment by eggytronixx** [comment]
I tried to use a ScrollView and onResponderRelease still did not fire

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by jukben** [comment]
I'm having the same issue. React Native: 0.49.3

**Comment by bolan9999** [comment]
Me too

**Comment by tsaohucn** [comment]
Me Too
