### ISSUE TITLE
ReadableArray and ReadableMap do not support Long (int64)

### ISSUE THREAD

**Issue by MattFoley** [facebook/react-native#12506]
### Description

Attempting to consume an API that serves long values in some cases via JSON. When passing from JS to Native Java code on Android, there is no getLong functionality on ReadableArray and ReadableMap.

### Reproduction

Simply pass a value greater than MAX_INT to Java from JS via a ReadableArray or ReadableMap. 

Attempt to use getInt and see exception:

```
com.facebook.react.bridge.UnexpectedNativeTypeException: Value '4205344624' doesn't fit into a 32 bit signed int
   at com.facebook.react.bridge.ReadableNativeArray.getInt(Native Method)
```

Attempt to use getString and see exception:

```
com.facebook.react.bridge.UnexpectedNativeTypeException: TypeError: expected dynamic type `string', but had type `int64'
  at com.facebook.react.bridge.ReadableNativeArray.getString(Native Method)
```

### Solution

This feels magical and bad, but this works for the moment.

Current workaround:
```
long value = (long)array.getDouble(index);
```

Better solution would be to add getLong, or some other function able to fetch long values.

### Additional Information

* React Native version: 0.40
* Platform:  Android
* Operating System: OSX

**Comment by ide** [comment]
I'm not certain but believe this could be because JS doesn't have longs yet (64-bit types are coming) and it would be deceiving to provide `set/getLong` methods that don't work reliably. It's more correct to write `(long)array.getDouble(index)` and make the programmer think about the consequences of double -> long conversion.

**Comment by MattFoley** [comment]
Interesting. I still don't quite understand the additions of the ReadableMap and ReadableArray, since Objective C just uses built in types. Is this just due to JavaScriptCore functionality, no comparable functionality in native Java?

**Comment by ide** [comment]
I'm not really sure, I imagine the fact that the authors were different people at different times has something to do with the discrepancy. The unified C++ bridge is coming which should clear away these differences in C++ if you prefer to program at that level.

**Comment by hey99xx** [comment]
There was previously conversation in https://github.com/facebook/react-native/issues/9685

> It's more correct to write (long)array.getDouble(index) and make the programmer think about the consequences of double -> long conversion.

If a programmer knows it's sending a large integer value, there's no choice other than using this forced casting code, which in my opinion leads to confusion rather than thinking about consequences of double -> long. The timestamps in Android/Java for example are mostly represented as longs, using  `set/getLong` would be the most natural for these.

> it would be deceiving to provide `set/getLong` methods that don't work reliably

I think this is the real reason. Before exposing the method, we should make sure the types work correctly without potentially losing precision or overflowing while crossing Java/JS bridges.

> Objective C just uses built in types

That's interesting. I'm also curious what Java lacks then.

> The unified C++ bridge is coming

Unrelated to this issue, but is there any doc about this?

**Comment by ide** [comment]
> Unrelated to this issue, but is there any doc about this?

I think the source code is the best place to look, it's already in master.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
