### ISSUE TITLE
Antialiasing for transformMatrix seems to be broken in 0.4.2

### ISSUE THREAD

**Issue by pukhalski** [facebook/react-native#1251]
Hey team, 
I have just updated to React Native 0.4.2 and experiencing a lot of issues starting with position absolute updates and ending with a pretty much annoying issue with anti-aliasing for transformMatrix-applied elements.

It was working as a charm in 0.3.x.

Could anyone clarify what's going on with it? Will it be fixed soon or should I downgrade back to 0.3.x to make my app look as supposed to be?

![anti-aliasing-transformmatrix](https://cloud.githubusercontent.com/assets/1217692/7595002/a212206c-f8e4-11e4-8cd3-c32dbdaa3c70.png)

Thanks.

**Comment by brentvatne** [comment]
@pukhalski - closing this issue as it has been inactive for quite a while :smile: - if this isn't fixed in 0.5.0-rc can you please post a runnable example [as per our contributing guidelines](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#reporting-new-issues)? It helps us a lot narrow down the problem
