### ISSUE TITLE
[IOS] Improve DatePickerIOS style

### ISSUE THREAD

**Issue by KarlosQ** [facebook/react-native#12519]
DatePickerIOS doesn't have a editable style.

this pull resquest is 'merged' 
[https://github.com/facebook/react-native/pull/10356](url)
but it isn't in the master

It would be good to be able to control the fontFamily, fontSize.. etc 

In DatePickerIOS.ios.js maybe must have a stylePicker for a height control ...etc.
One solution would be to put a property like stylePicker:
`style={[styles.datePickerIOS, props.stylePicker]}`

Would any charitable, caring soul be able to implement this? Thanks! 👍

**Comment by ericvicenti** [comment]
That pull request was closed because it used private APIs that would cause rejection in the app store. Do you know if it can be done with public UIKit APIs?

**Comment by KarlosQ** [comment]
Ah, okey. I see that now. When I try to open a modal in a real device with the modified DatePicker.IOS the app crash. 

Maybe [](https://github.com/xgfe/react-native-datepicker) is the solution

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by SSTPIERRE2** [comment]
I vote to reopen this issue. My team now has to manually implement a date picker with different text color than the default using regular Picker components. We just need to be able to control simple styling aspects like text color, font size, font family, all that good stuff, thanks.

**Comment by pinguinjkeke** [comment]
Is there any ability to replace standard RCDatePickerManager.m with my edited version via DI or something else?
It's not ok to edit files inside ReactNative lib directory.
There is really small documentation about DI that contains no explanation and use cases.

**Comment by hugoh1995** [comment]
This really is a pain.

**Comment by KarlosQ** [comment]
@hugoh1995 

Make the changes manually
