### ISSUE TITLE
Incorrect behavior of ellipsizeMode when text contains special symbols like '+'

### ISSUE THREAD

**Issue by alekseykarpenko** [facebook/react-native#12513]
### Description

I'm trying to display user's email with ```ellipsizeMode='tail'```, but faced to RN bug with this property.

```ellipsizeMode``` property of ```<Text>``` component works incorrect when text contains some special chars (e.g. ```+``` but not ```_```)

### Reproduction

```javascript
<View>
  <Text style={{fontWeight: 'bold'}}>Actual Result:</Text>
  <Text>END:</Text>
  <Text numberOfLines={1}>
    someverylongemail+somecyphers12345678901234567890@test.com
  </Text>
  <Text>MIDDLE:</Text>
  <Text ellipsizeMode="middle" numberOfLines={1}>
    someverylongemail+somecyphers12345678901234567890@test.com
  </Text>
  <Text>HEAD:</Text>
  <Text ellipsizeMode="head" numberOfLines={1}>
    someverylongemail+somecyphers12345678901234567890@test.com
  </Text>
  <Text style={{fontWeight: 'bold'}}>Expected Result:</Text>
  <Text>END:</Text>
  <Text numberOfLines={1}>
    someverylongemail_somecyphers12345678901234567890@test.com
  </Text>
  <Text>MIDDLE:</Text>
  <Text ellipsizeMode="middle" numberOfLines={1}>
    someverylongemail_somecyphers12345678901234567890@test.com
  </Text>
  <Text>HEAD:</Text>
  <Text ellipsizeMode="head" numberOfLines={1}>
    someverylongemail_somecyphers12345678901234567890@test.com
  </Text>
</View>
```
![screenshot_2017-02-22-12-41-38](https://cloud.githubusercontent.com/assets/4648983/23209863/b5d69544-f903-11e6-9b20-1f2a54f8b856.png)

(!) Not reproduced in RN 0.33.0 at RNPlay:
https://rnplay.org/apps/N8Ls9A

### Solution

Imho bug is in java source, so i can only extend  ```<Text>``` component to change it's text manually.

### Additional Information

* React Native version: 0.41.0, 0.42.0-rc.3 (CNR 0.33.0)
* Platform: Android
* Operating System: MacOS

**Comment by alekseykarpenko** [comment]
**IMPORTANT UPDATE!**

Bug is reproducing on:
*Samsung J1* (**Android 5.1.1**) & *Samsung Galaxy S6 Edge+* (**Android 5.1.1**)
but not reproducing on:
*Samsung Galaxy S7* (**Android 6.0.1**), *LG Nexus 5x* (**Android 7.1.1**), *Moto G2* (**Android 6.0**), *AVD Nexus 5* (**Android 6.0 API Level 23**), *LG G3 Vigor* (**Android 4.4.2**), *AVD Nexus 5* (**Android 6.0**), 

Now I can conclude this bug is related only to **Android 5.1.1**.

When i tried to run my demo on *AVD Nexus 5* (**Android 5.1.1 API Level 22**) i've got my app crashed with next stack trace:
![screenshot_1488220769](https://cloud.githubusercontent.com/assets/4648983/23374583/9090b958-fd2d-11e6-90a1-2191539a3da2.png)

**Comment by alekseykarpenko** [comment]
May be related to internal Android issue: https://code.google.com/p/android/issues/detail?id=33868

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
