### ISSUE TITLE
TextInput unable to take Text node as placeholder

### ISSUE THREAD

**Issue by steveccable** [facebook/react-native#12525]
### Description

When attempting to use a Text node as a placeholder of TextInput, the app throws an error (see screenshot).  This is contrary to what is indicated by the docs, which states that placeholder is of type Node.

### Reproduction

Sample Code:
```
import React, { Component } from 'react'
import { TextInput, Text } from 'react-native'

class App extends Component {

  render() {
    const myText = (
      <Text style={{fontStyle:'italic', fontSize: 40}}>This is my placeholder</Text>
    );
    return (

        <TextInput
          placeholder={myText}
        />
    )
  }
}

export default (App)

```

For whatever reason, this problem presents itself when running via `react-native run-<ios|android>` but is not seen when editing in the [tutorial docs](https://facebook.github.io/react-native/docs/handling-text-input.html).

### Solution

To address this issue, TextInput should actually be able to support taking a placeholder of type Node and rendering it.

### Additional Information

* React Native version: Seen on both 0.37.0 and 0.41.2
* Platform: both
* Operating System: MacOS

### Screenshots
ios | android
--- | ---
![screen shot 2017-02-22 at 2 03 12 pm](https://cloud.githubusercontent.com/assets/17714428/23227940/b384cf22-f908-11e6-9379-f3b3e1e85760.png) | ![screen shot 2017-02-22 at 2 09 19 pm](https://cloud.githubusercontent.com/assets/17714428/23227953/b8334a80-f908-11e6-9f4c-4c1f92dda920.png)

**Comment by brentvatne** [comment]
My guess is that this is either a mistake or Facebook has a different native module for TextInput that supports nodes. Can you submit a PR to change it to `PropTypes.string`? https://github.com/facebook/react-native/blame/master/Libraries/Components/TextInput/TextInput.js#L398-L401

**Comment by steveccable** [comment]
@brentvatne I'm not sure I understand.  Are you saying the issue is that it SHOULD take a node and doing so doesn't work for some reason, or that it SHOULDN'T take a node but currently accepts a broader type than it should?
The link you put makes it seem more like the latter, but that would indicate to me that it once worked and was intentionally taken out without updating the propTypes in TextInput.  If that is the case, I should be just fine to make a PR to restrict the propTypes there, though we may want to let the folks at react-native-web know, since apparently passing a node still works fine for them (as demonstrated by the fact that doing this plays nicely in the tutorial linked in the issue description).
If it is the former, fixing that is far less trivial, and would require some investigation by either me or someone else to figure out why exactly it is broken anyway.

**Comment by brentvatne** [comment]
It should not take a node. I was saying that it is possible that Facebook internally has an implementation that supports nodes for placeholders, but the OSS version only supports text.

**Comment by steveccable** [comment]
PR created and linked just above this comment.

**Comment by hramos** [comment]
Current status: the example is fine, as it only shows the use of a string in the placeholder prop. The reference docs do state that a node can be used as well, but this does only works internally at FB. The reference docs need to remain as is, as they are generated from source.

**Comment by steveccable** [comment]
Is there really nothing that can be done regarding the docs?  It seems to me that we wouldn't want to make developers think they can do something that is in reality both unsupported and definitely going to cause their code to break.  That's basically false advertising capabilities in documentation.

I agree the example posted in the main docs page for TextInput is fine, as it only uses a string, though it is a bit concerning that interactive examples that can be found elsewhere in the docs (such as the one link) can take a node and still work, leading those who experiment with such examples to think it should work in their actual code.  That said, I admit that the example linked to is running react-native-web and is thus outside of your control.

**Comment by hramos** [comment]
You can add a note to the docs noting that this will only take a string if you are inclined. What we cannot change is the documented prop type, as the source of truth is the Flow type which is a node.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
