### ISSUE TITLE
Invalid imageTag: assets-library://asset/asset.JPG?id=B84E8479-475C-4727-A4A4-B77AA9980897&ext=JPG

### ISSUE THREAD

**Issue by zulkarnainshah** [facebook/react-native#12522]
`ImageStore.getBase64ForTag` throws error on passing image URI received from `ImagePickerIOS.openSelectDialog`

While using the function `ImagePickerIOS.openSelectDialog`, the callback gives a URI if the image picked from the CameraRoll of iOS. Then i use the function `ImageStore.getBase64ForTag` to get base64 encoded string so that i could upload to a server, but calling this function returns the following error-
 **Invalid imageTag: assets-library://asset/asset.JPG?id=B84E8479-475C-4727-A4A4-B77AA9980897&ext=JPG** 

* React Native version: 0.41.2
* Platform: iOS, Android
* Operating System: MacOS

**Comment by brentvatne** [comment]
I think you are confusing the purpose of the ImageStore -- it is meant to store base64 images so that you don't need to pass them over the bridge each time. It does not convert arbitrary image urls to base64. You can upload the image using fetch with a multi-part POST request, eg: https://github.com/exponent/image-upload-example/blob/master/frontend/main.js#L155-L187
