### ISSUE TITLE
Add documentation for FlatList and underlying VirtualizedList?

### ISSUE THREAD

**Issue by coodoo** [facebook/react-native#12531]
Now that `FlatList` and `VirtualizedList` is around the corner (available in `master`), is there any plan to update the documentation as well? From a quick skim there's seemed to be a bunch of new properties to the `VirtualizedList` which is much worth documenting.

**Comment by hramos** [comment]
I have yet to sync with @sahrens what the plans are for `FlatList`, but if it's on master then these should be going out with the next release candidate in March. In order to get the API docs displayed on the website we'll need to add these components to https://github.com/facebook/react-native/blob/master/website/server/docsList.js

If you want to go ahead and do that, you should be able to generate the site locally and confirm that the docs are visible for these components. Please let us know if any issues come up, especially related to `react-docgen`.

**Comment by sahrens** [comment]
Definitely planning on docs (and moving out of /Experimental, exporting as part of require('react-native'), etc.) there are just a couple changes I want to make to the API and would like to get a little more data from our internal tests which are just going out now.

**Comment by hramos** [comment]
That seems perfectly reasonable. @coodo hopefully this answers your question: this is still in an early access phase, but we'll make sure it is fully documented by the time it is moved out of Experimental.

**Comment by coodoo** [comment]
Sounds good, thanks for the prompt replies, btw, @sahrens good job building out the `VirtualizedList`, it's probably the most exciting thing after `Adobe Flex` 👍👍
