### ISSUE TITLE
React Native LTS on Roadmap?

### ISSUE THREAD

**Issue by ericnograles** [facebook/react-native#12546]
Hi RN team,

Sorry if this is the wrong avenue for this, but I figured it was worth a discussion.

As React Native matures, is there any thought of following an LTS cycle like Node.js, or is that simply not feasible in the immediate future due to manpower, technical reasons, etc?

Only reason I ask is because I am using React Native for client engagements (mainly larger enterprises), and while tools like Yarn and the Git patching are vast improvements to earlier versions and help ease version-to-version risks, folks still get a little skittish about the fast release cycle.  I also recognize that the fast release cycle is vital to keep pace with mobile platforms and to introduce amazing new features, so I'm not necessarily against it either.

Anyway, I thought I'd get yours and the community's thoughts on this, either here or on some other forum.

Love what you guys do, keep up the great work!

**Comment by ide** [comment]
There was some discussion of LTS awhile ago and the conclusion was that moving from two-week releases to monthly releases (to address some issues with the fast release cycle) was the best solution when considering the maintenance costs. There would need to be enough of the largest consumer-and-contributors of RN to be willing to maintain an LTS branch and one hasn't emerged. Since an unmaintained LTS branch is likely worse than setting expectations that there isn't an LTS release, we don't have an LTS branch today.

**Comment by ericnograles** [comment]
Makes sense, thanks for the clarification @ide.  I'm hoping with a bit of advocacy we can get to that point, and I'd definitely be willing to help move that forward.
