### ISSUE TITLE
WebView doesn't redirect successfully

### ISSUE THREAD

**Issue by manask88** [facebook/react-native#12556]
### Description

I used the WebView component in RN 0.41.2

### Reproduction

1. Load a page that contains a form with a submit button.
2. Click on the submit button.
3.Page should be redirected after this, but the Location response header that comes form the server is not being process correctly.

I did the same test in a desktop browser and a mobile browser. In both cases, the page was redirected successfully.

This is the headers I got as a response from the server:

General

Request URL:https://xxxxx.desk.com/customer/widget/emails
Request Method:POST
Status Code:302 Found
Remote Address:xx.xx.xx.xx:443

Response Headers

Cache-Control:no-cache
Connection:keep-alive
Content-Length:124
Content-Type:text/html; charset=utf-8
Date:Wed, 22 Feb 2017 01:01:46 GMT
Location:https://xxxxx.desk.com/customer/widget/emails/completed
Server:nginx/1.9.2
Set-Cookie:spam_detected=; path=/; expires=Thu, 01-Jan-1970 00:00:00 GMT
Status:302 Found
X-Frame-Options:SAMEORIGIN
X-Rack-Cache:invalidate, pass
X-Request-Id:xxxxxxxxxxxxxxxxxxxxxxxx
X-Runtime:0.356235
X-Ua-Compatible:IE=Edge,chrome=1

The webview stays in https://xxxxx.desk.com/customer/widget/emails. However, it should be redirected to https://xxxxx.desk.com/customer/widget/emails/completed

The https://github.com/facebook/react-native/issues/8693 issue is related, but it's different because that happens when custom headers are defined. In this case, i'm not defining any custom headers. I'm just trying to use the ones coming from the server.

### Solution

The headers from the 302 response should be processed correctly so that redirection can happen correctly

### Additional Information

* React Native version: 0.41.2
* Platform:  iOS
* Operating System: MacOS

**Comment by unicornRainbows** [comment]
I agree.. going to try the solution from 
http://blog.bigbinary.com/2016/07/26/passing-request-headers-on-each-webview-request-in-react-native.html

**Comment by unicornRainbows** [comment]
aaaaaand it didn't work..

**Comment by unicornRainbows** [comment]
HERE is a SOLUTION! I wasted HOURS on this..
https://github.com/facebook/react-native/issues/9201
<3 its a hack, but it works at least
:)

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by thecodecafe** [comment]
Anybody solved this? I've been stuck for a week on my project because of this. Need a solution for iOS, sadly I don't know how to write in swift would have written my own package that supports it. {{ sighs with deep sadness }}
