### ISSUE TITLE
iOS doco on 'Native Modules' is unclear on passing back JavaScript objects

### ISSUE THREAD

**Issue by peternann** [facebook/react-native#12579]
### Description

I'm developing an iOS Native Module integration, and found the documentation lacking/erroneous(?) in detail for creating objects for callbacks to javascript.

**Cutting to the chase: Shouldn't the iOS Native Module examples show the creation of a JavaScript object (for callbacks) as an NSDictionary?**

### Details:
Where a callback is shown in the examples here: https://facebook.github.io/react-native/docs/native-modules-ios.html
any 'event' data is exclusively shown as:
`NSArray *events = ...`
Right down to the ellipsis. And it's a bit hard to figure out the details.

The page also mentions the macro RCTMakeError in RCTUtils.h, which on inspection actually creates an NSDictionary, NOT an NSArray.

I've tried making my own NSDictionary like so:
```
NSDictionary *event = @{
    @"success" : @NO,
    @"errMsg"  : @"Something went wrong"
};
```

And it DOES seem to create a usable JavaScript object back in javascript-land.
(Plus it seems totally sensible to be a Dictionary, not an Array)

Admittedly, the documentation does state:
"This section is more experimental than others because we don't have a solid set of best practices around callbacks yet."
**But maybe it could be updated/clarified now?**

### Reproduction

Visit the page above. Try to find any explicit example shown that creates a canonical JavaScript object for a callback.

### Solution

Update the iOS Native Module doco to be clearer (No mystery ellipsis would be great), and relative to latest code release. Creating NSDictionaries seems to work!

### Additional Information

* React Native version: 0.41.2
* Platform: iOS
* Operating System: MacOS

**Comment by ericvicenti** [comment]
These docs aren't very great right now, but if you can send in a pull request for some improvements, you can cc me, and I'll take a look and cc the right experts to weigh in and make sure it looks good.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
