### ISSUE TITLE
[FlatList] numColumns glitch when rerendering

### ISSUE THREAD

**Issue by olofd** [facebook/react-native#12595]
### Description

When you set the property numColumns in the new FlatList and then rerender a column when eg. pressing that column, the entire row rerenders and you can see it rerendering, it blinks.

### Reproduction

Set numColumns on FlatList and then cause a rerender.

### Solution

Looking at the implementation it seems that each row is only one instance of CellRenderer in VirtualizedList. And the column-splitting is taken care of by the parent component FlatList.
My best guess is that this is somehow what's causing the problem. It seems that it might be fixed if each column in the row was a instance of CellRenderer.

### Additional Information

* React Native version: master
* Platform: iOS
* Operating System: macOS

**Comment by booboothefool** [comment]
+1 Also noticing some flickering/stuttering with FlatList numColumns={2} in various situations (like when I just add a `SeparatorComponent`.

**Comment by sahrens** [comment]
Hmm, what kind of re-rendering are you doing? I don't know why it would blink unless you're doing something like rendering a placeholder briefly or something like that? You can see in the `<FlatList> - MultiColumn` example in UIExplorer that pressing a row will re-render it without causing any sort of blinking as far as I can tell. Are you seeing something else?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by cristianosantos95** [comment]
I'm also experiencing this issue :/ @olofd did you manage to fix it?
