### ISSUE TITLE
StatusBar background color is not being set on Android 7 

### ISSUE THREAD

**Issue by sattaman** [facebook/react-native#12618]
### Description

StatusBar background color is not being set on Android 7 

### Reproduction

https://rnplay.org/apps/ELYWHg

### Solution

StatusBar color should be applied in Android 7

### Additional Information

* React Native version: 0.41
* Platform: Andriod 7.1
* Operating System: MacOS

**Comment by appsthatmatter** [comment]
is working for me in 0.42.0

**Comment by JonasWho** [comment]
+1 on this issue

**Comment by studiobrain** [comment]
+1 Nexus 6p on 7.1 is not rendering the backgroundColor (its grey)...

**Comment by sattaman** [comment]
I found it was set intermittently, sometimes working other times not. I set
it in the java source code and this has worked for me .

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by markentingh** [comment]
This is happening to me as well. I've tried everything I can to get this to work. Using Android 7.0 Emulator in Windows 10.  Also, there's something else going on. There's a strange white bar below the statusbar... I have no other content in my app besides the statusbar component.

![2017-07-29-day-2-statusbarcolorbug](https://user-images.githubusercontent.com/2896371/28751116-e860c756-74cc-11e7-9be8-04e0d0aef655.jpg)

**Comment by markentingh** [comment]
Unfortunately, I can reproduce this bug. Running React Native 0.46.4 on Windows 10.

In the first screenshot, you can clearly see a translucent StatusBar with no background color, even though I set the translucent property to false & backgroundColor to "blue".

In the second screenshot, I set hidden to true, and the StatusBar did infact hide, so the component is working (somewhat).

![2017-07-29-day-2-statusbarcolorbug2](https://user-images.githubusercontent.com/2896371/28755240-401bef96-7524-11e7-85b8-a68751705ab1.jpg)

![2017-07-29-day-2-statusbarcolorbug3](https://user-images.githubusercontent.com/2896371/28755243-4425411e-7524-11e7-8421-ddf70ae5ddd9.jpg)

**Comment by markentingh** [comment]
Hello? Will no one recognize that this is actually an existing bug?????? It even bugs out on my Motorola phone. Please fix this :)

**Comment by btrautmann** [comment]
I am also seeing this issue, tested on Android O (Pixel emulator) and Android 7.1.2 (Nexus 5X physical device). The actual desired color will be initially shown, but I can usually get it to change to grey by backgrounding app, waiting a while and re-launching the app.

```
        <StatusBar
          translucent={false}
          backgroundColor="rgb(122,77,246)"
          barStyle="light-content"
        />
```

**Comment by voidstarfire** [comment]
I also have the same issue, randomly the status bar will be grey AND there will be extra space under it.

Cannot release app if this bug continues.

**Comment by btrautmann** [comment]
@voidstarfire so to avoid the spacing, I made my toolbar the same height as used in the F8 app and make the app status bar not translucent, defining it in the HIGHEST component possible.

```
          <StatusBar
            translucent={false}
            animated={false}
            hidden={false}
            backgroundColor="rgb(122,77,246)"
            barStyle="light-content" />
```
This helped me avoid the spacing issue. Now, in order to avoid the grey status bar, I think this is caused by a bug on Android launchers actually (I experienced it earlier because I'm an Android developer). To reproduce it, install your app (sometimes it does it on first install). Then, background the app, drag the app icon to your launcher and click it. What this does is it actually launches the main launcher Intent OVER your already existing app. You can now click back and expose your actual app that still exists behind that new Intent. To solve this, go into your MainActivirty.java within the Android project, and implement onCreate like so:

```
    // Fixes a launcher bug that causes launcher Activity to be shown over
    // current screen when launching app after backgrounding it
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (!isTaskRoot()) { 
            Intent intent = getIntent(); 
            String action = intent.getAction(); 
            if (intent.hasCategory(Intent.CATEGORY_LAUNCHER) && action != null && action.equals(Intent.ACTION_MAIN)) { 
                finish(); 
                return; 
            } 
        }
    }
``` 

This will help to dismiss the incorrect Activity and show the appropriate one, with the correct status color. Let me know if it works!

**Comment by hramos** [comment]
Since this issue was closed due to lack of activity and the original post doesn't have as much information as we now require, I recommend opening a new issue and filling out the template in its entirety. Feel free to copy over any new information that has been posted here since it was closed.

**Comment by voidstarfire** [comment]
@btrautmann works perfect, thanks very much.

**Comment by btrautmann** [comment]
You got it @voidstarfire!!

**Comment by aishbetu** [comment]
It's not working because android & has transparent statusBar just like iOS. To check just change the backgroundColor of your view component and it'll change the color of the statusBar as well.
