### ISSUE TITLE
React Native BackAndroid

### ISSUE THREAD

**Issue by kazimmusani** [facebook/react-native#12614]
Hi Friends,
I need your help.

i am using BackAndroid EventListner on one of my screen but it automatically applies on all available screens on app. Can you please advise how to refactor the below code. I want to use below code only on one screen not all.

import { BackAndroid } from 'react-native';

componentWillMount() { 

BackAndroid.addEventListener('hardwareBackPress', () => {return true}); 

}

Thanks in advance for your kind co-operation.

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
