### ISSUE TITLE
Warning ALWAYS_SEARCH_USER_PATHS when upgrade RN version 0.40.0

### ISSUE THREAD

**Issue by tanmynguyen** [facebook/react-native#12610]
I have been issue blow:
<img width="869" alt="screen shot 2017-02-28 at 12 28 25" src="https://cloud.githubusercontent.com/assets/11315567/23394482/fc422bda-fdbb-11e6-8bb2-d494f2e0bd50.png">
Who can help me?

**Comment by bd-arc** [comment]
I can confirm having the same issue after upgrading from RN 0.39.2 to RN 0.41.2.

**Comment by tanmynguyen** [comment]
hi @bd-arc  :) . I upgrade from RN 0.39 to RN 0.40.0? I known't fix it where? I worry won't build product in IOS :(

**Comment by tanmynguyen** [comment]
I updated RN 0.42.0 and setting like blow?
<img width="689" alt="screen shot 2017-03-02 at 10 28 36" src="https://cloud.githubusercontent.com/assets/11315567/23491901/c5292a9e-ff33-11e6-8fca-fda6caa3609b.png">

**Comment by mbodge** [comment]
Same issue here.

**Comment by flybayer** [comment]
Same. Is it something to worry about?

**Comment by cooperka** [comment]
If you go to your project's Build Settings (in Xcode) and search for `ALWAYS_SEARCH_USER_PATHS`, you can see the setting for your own app there. Mine is set to `No`, but I'm still getting these warnings, so they're most likely coming from native dependencies you've linked.

You'll need to submit PRs to those dependencies to make the warnings go away. In the meantime, it's probably not anything to worry about!

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
