### ISSUE TITLE
RCTLog.h not found After setting up cocoapod

### ISSUE THREAD

**Issue by eduardomoroni** [facebook/react-native#12615]
I created a brand new project: `react-native init cocoa`
then `cd cocoa && npm install`
My xcode project looks like the picture:
![image](https://cloud.githubusercontent.com/assets/823150/23403202/cdf8f732-fd8d-11e6-9a94-411f72bf073f.png)
so I did `cd ios && pod init` and removed all references from library folder on Xcode project and set up my Podfile like this:

 ```
target 'cocoa' do
    source 'https://github.com/CocoaPods/Specs.git'
    pod 'React', :subspecs => [
      'RCTAnimation',
      'RCTActionSheet',
      'RCTGeolocation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTNetwork',
      'RCTSettings',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket'], :path => '../node_modules/react-native'
end
```
then `pod install`
After this I opened cocoa.xcworkspace tryied to Build and I'm getting `.../cocoa/ios/cocoaTests/cocoaTests.m:13:9: 'React/RCTLog.h' file not found`

I'm using:
xCode 8.2.1
react-native-cli: 2.0.1
react-native: 0.41.2

**Comment by vjeranc** [comment]
0.44 has the same issue

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by kayluhb** [comment]
For anyone that finds this in the future, I was able to fix this by ensuring there was a target for the test project in my podfile

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

def shared_pods
    pod 'React',
    path: '../node_modules/react-native',
    subspecs: [
      'Core',
      'ART',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTCameraRoll',
      'RCTGeolocation',
      'RCTImage',
      'RCTNetwork',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket',
      'DevSupport',
      'BatchedBridge',
      'RCTLinkingIOS',
      'RCTSettings'
    ]
    pod 'Yoga',
    path: '../node_modules/react-native/ReactCommon/yoga'
end

target 'MyProject' do
    shared_pods
end

target 'MyProjectTests' do
    shared_pods
end


post_install do |installer|
    installer.pods_project.main_group.tab_width = '2';
    installer.pods_project.main_group.indent_width = '2';
end
```

**Comment by StevenMasini** [comment]
@kayluhb Thanks! You saved my day! ^^
