### ISSUE TITLE
Image Prefetch Additional DOcumentation

### ISSUE THREAD

**Issue by joecaraccio** [facebook/react-native#12625]
### Additional Information

Not sure if I am alone in having issues with simply understanding how React-native Prefetch Image works. 

IS there any additional documentation or an example application that utilizes this?

**Comment by qpowell** [comment]
@joecaraccio I had the same issue and ultimately solved my problem with a little trial and error. Is there a specific scenario you had in mind? If so, maybe I can offer some insight.

In my particular case, I needed to render some cover images for a content libraries, and wanted to show a loading screen until all of them were completed. Before using `Image.prefetch`, the images would just trickle in as they were loaded...one by one. My implementation ended up looking something like this:

```javascript
// ... the loading indicator is rendered conditionally using the value of this.state.isLoading
handleLibraryImages(libs) {
  const libraryImages = libs.map(lib => Image.prefetch(lib.image_large_url));
  Promise.all(libraryImages)
    .then(() => {
      this._setIsLoading(false);
    })
    .catch(error => console.log('error...', error))
}
```

Not sure if that helps or not for your use case, though

**Comment by joecaraccio** [comment]
@qpowell  Thanks so much for your response.. that little code sample right there was pretty valuable alone! My ultimate scenario I am trying to accomplish is implement a tap slideshow, where when I press the image view it automatically transitions to the next image, without any loading or white flicker

I do have a few specific questions that I think quite a few people wonder..
Where did you call that function.. from the constructor?

Did you wrap the image view in something like an onLoad? When you used the image view, did you just specify the source url like you had it in the array. I didn't know if it somehow checked the source url in the catch or you had to pass in some like Image.Prefetch('imageone') object as the image source... if that makes sense.

Thanks so much!

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
