### ISSUE TITLE
[0.42.0] Undesirable changes in Info.plist

### ISSUE THREAD

**Issue by ncuillery** [facebook/react-native#12640]
When upgrading from 0.41.2 to 0.42.0 (using either `react-native upgrade` or `react-native-git-upgrade`), two lines are removed in the `Info.plist` file:

https://github.com/ncuillery/rn-diff/compare/rn-0.41.2...rn-0.42.0#diff-faf314fabd1fcf63d4c5d4dc90ac7f1c

I think that's because this commit https://github.com/facebook/react-native/commit/516d97397bbf32ca9c05c17b7af5ecd8bea1d885 is in the `0.41-stable` but has not been cherry-picked in the `0.42-stable`. This commit has changed the HelloWorld template used by the upgrade tools.

**Comment by fmatoss** [comment]
I was going to create an issue for this, the CLI command `eject` is not working anymore.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
