### ISSUE TITLE
Left, Right, Top and Bottom with percentages don't work when same element has flexDirection: 'row'

### ISSUE THREAD

**Issue by henrikra** [facebook/react-native#12660]
### Description

Here is example:
```javascript
import React from 'react';
import {AppRegistry, StyleSheet, View} from 'react-native';

const leftPercentBug = () => (
  <View style={styles.container}>
    <View style={styles.child}>
      <View style={styles.grandChild} />
      <View style={styles.grandChild} />
    </View>
  </View>
);

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'red',
    borderWidth: 2,
    borderColor: 'black',
  },
  child: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 255, 0.5)',
    left: '50%',
    flexDirection: 'row',
  },
  grandChild: {
    backgroundColor: 'green',
    borderWidth: 1,
    borderColor: 'pink',
    flex: 1,
  },
});

AppRegistry.registerComponent('leftPercentBug', () => leftPercentBug);
```

With this code the layout **should** look something like this:
![image](https://cloud.githubusercontent.com/assets/12229968/23516753/c72f7756-ff76-11e6-848e-2ef6727c28ee.png)

Instead it looks like this:
![image](https://cloud.githubusercontent.com/assets/12229968/23516776/d83f7794-ff76-11e6-9b66-ee82badeb1a5.png)

So the `left` is not calculated right when the same element has `flexDirection: 'row'`
This same happened also when using `left`, `right`, `bottom` and `top` properties.

### Reproduction

Run the code above by yourself. Also you can see how the same should look in the web: https://jsfiddle.net/L8ps52sp/3/

### Solution

I think @emilsjolander should check this out since he added percentages in latest version ;)

### Additional Information

* React Native version: [0.42]
* Platform: [iOS]
* Operating System: [MacOS]

**Comment by henrikra** [comment]
@emilsjolander I have posted this on facebook/yoga now :) https://github.com/facebook/yoga/issues/454

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
