### ISSUE TITLE
DatePickerIOS minuteInterval does not work when choose mode='time' on some phones

### ISSUE THREAD

**Issue by 13160102112** [facebook/react-native#12672]
this happens not on every phone ,however,when I change time to datetime ,it woks correctly on those phones which do not work correctly when using time

**Comment by 13160102112** [comment]
my version is 039.0

**Comment by duhseekoh** [comment]
Seeing the same results on the iPhone 6 simulator with RN 0.42.3

**Comment by kushanson** [comment]
I can confirm the issue still exists in react-native 0.43.2. The issue occurs when hours and minutes are simultaneously settling on their respective values. The onDateChange callback can get blocked from being called when the hours and minutes are simultaneously settling.

When this defect occurred, the breakpoint in onDateChange callback did not get hit, so there was no opportunity to update the state of the DatePickerIOS. This causes the DatePickerIOS UI to be out of sync with its state.

**Comment by Hunter-Dolan** [comment]
Can confirm it is an issue on React-Native 0.43.0. What is even more annoying now is the remedies offered in past issues no longer seem to work.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by marano** [comment]
I am seeing this issue on `0.50.3`

**Comment by hskyaw-2015** [comment]
been 3 years, still not working, lmao
