### ISSUE TITLE
WebSocket "onclose" event is missing code attribute

### ISSUE THREAD

**Issue by Cederman** [facebook/react-native#12678]
### Description
I have successfully opened a WSS connection on the iOS Simulator where I get data back from the socket. No issues. However, the same socket doesn't seem to get any data at all in the Android emulator. I've tried with another WSS endpoint just to rule out the SSL being the issue. _wss://echo.websocket.org_ works on both platforms without issues.

To debug this, I expected to get a `code` in the WebSocketEvent that is sent on the `onerror` listener I have registered, but it is undefined and missing from the event object. I expected a code in return to be able to know the reason why I can't connect to the socket in the Android emulator.

### Reproduction
The code I used is very simple and works on iOS:
```
const socket = new WebSocket("wss://endpoint")
        socket.onopen = () => {
            console.log("Connected!")
        }
        socket.onmessage = event => {
            console.log(event.data)  
        }
        socket.onclose = event => {
            console.log("Socket closed") // event.code is missing here
        }

        socket.onerror = error => {
            console.log("Error", error)
        }
```
### Solution

As the WebSocket implementation in Chrome retrieves both `code` and `reason` (although almost always empty), so should the RN implementation of WebSocket.

### Additional Information

* React Native version: 0.41.2
* Platform: iOS (works), Android (Nexus 5, API 25:5554doesn't work)
* Operating System: MacOS 10.12.2

![screen shot 2017-03-03 at 09 15 56](https://cloud.githubusercontent.com/assets/1753170/23543351/10198ecc-fff2-11e6-9747-8832353f8a04.png)

**Comment by miniFrank** [comment]
+1

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by Adjective-Object** [comment]
I have also encountered this issue while trying to connect to a socket server on my local network. Code is more or less identical.

**Comment by wprater** [comment]
Im seeing this same behavior when I close with a custom code, its not being set

**Comment by perrosnk** [comment]
I am facing the same issue. Has anyone found a solution or the root cause?

**Comment by timt** [comment]
Yes I have seen the same problem, also seems it does not call onerror either for android

**Comment by justincrow** [comment]
Same error: onClose and onError don't get called from Android (they do from iOS).

**Comment by tli4** [comment]
Same error here, I use a websocket server over wamp.
when I try to close the connection with a custom code, no matter what I passed, it always receive the code 1001 on react native side, but it works normal on a browser.
