### ISSUE TITLE
Child View have a 1pixel gap between them

### ISSUE THREAD

**Issue by gilbertKaradja** [facebook/react-native#12681]
![x2_edit](https://cloud.githubusercontent.com/assets/22845863/23545389/76b3dd00-fffb-11e6-8266-2969eb98489f.png)
### Description
I have a simple layout. 
1) View A: filling whole screen (flexDirection: column)

2) View B and View C = under View A. View B (flex: 25)  View C (flex 75)

3) View D and View E = under View C

Everything works fine in the emulator but when i build an apk and try it on a phone there is a white line between View D and View E. I have no idea what causes it.

Link to SO question with screenshots: http://stackoverflow.com/questions/42565184/react-native-unexplainable-space-between-two-views

### Additional Information

* React Native version: 0.41.2
* Platform: Android

**Comment by ericvicenti** [comment]
Have you tried an emulator with the same resolution and display settings as your phone? You may be able to reproduce it. Please also report the size of your phone screen and the version of Android.

**Comment by zenyr** [comment]
I had a similar issue without flexbox. My designer gave me sizes with decimal places, resulting `height:132*0.302`. It works okay for most cases, but when I tried to stack multiple instances of them (simple `map(data, <Item style={ { height:132*0.302} } />)` with or without `StyleSheet.create` ) they started pushing each other randomly as if I had put `{marginTop: Math.random()* StyleSheet.hairlineWidth }`

It seemed like a rounding error for me, so I put `Math.round(132*0.302)` and the issue was fixed.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
