### ISSUE TITLE
react-native run-android no longer supports --configuration=release

### ISSUE THREAD

**Issue by sungwoncho** [facebook/react-native#12698]
### Description

Documentation for [Testing the release build of your app](https://facebook.github.io/react-native/docs/signed-apk-android.html#testing-the-release-build-of-your-app) for Android seems to be outdated.

Concretely, the flag `--configuration` does not exist anymore.

### Reproduction

Running `react-native run-android --configuration=release` gives me:

      error: unknown option `--configuration'

### Solution

Replacing `configuration` flag with `variant` flag works.

    react-native run-android --variant=release

### Additional Information

* React Native version: 0.42.0
* Platform: Android
* Operating System: MacOS 10.12.3

**Comment by laalaguer** [comment]
Shall we update the official tutorial as well? it still contains outdated info here:
https://facebook.github.io/react-native/docs/signed-apk-android.html

**Comment by sungwoncho** [comment]
@laalaguer I fixed this in https://github.com/facebook/react-native/pull/12699 but it seems that the doc has not been released yet. Let's close this when the updated version is released.

**Comment by wedelgaard** [comment]
@sungwoncho not updated in 0.43 :/

**Comment by fauna5** [comment]
Just tripped over this too. Would be great to update it

**Comment by sungwoncho** [comment]
@janicduplessis https://github.com/facebook/react-native/pull/12699 was merged but doc has not been updated. Any action required to update the docs?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
