### ISSUE TITLE
Can't debug TypeScript code because of the new source map generator in 0.42

### ISSUE THREAD

**Issue by balesz** [facebook/react-native#12705]
### Description

I use TypeScript and VSCode for development my app. Before 0.42 the RN packager is able to handle the compiled .js files with source map informations from TypeScript compiler. In 0.42 The new source map generator logic ignore these map informations and don't put them to the output boundle.map file. Because of this behaviour I can't debug my TypeScript code just the compiled JavaScript code.

### Reproduction

Check out this Gist: https://gist.github.com/balesz/164293cad6ada4ab7439859bf34896b0

* Create a simple react native project: `react-native init sourceMapIssue`
* Add tsconfig.json file to the project root
* Create src directory into the project root
* Add sourceMapIssue.tsx file to the src directory
* Overwrite the index.ios.js or index.android.js file with the index.ios.js
* `yarn add typescript -D`

You can debug .tsx source file:

* Kill running RN packager
* Set react-native version to 0.41.2 in package.json
* `yarn install`
* `rm -rf build`
* `rm -rf ios/build`
* `node_modules/.bin/tsc`
* `react-natvie run-ios`
* You can debug src/sourceMapIssue.tsx file in Chrome debugger

You can't debug .tsx source file:

* Kill running RN packager
* Set react-native version to 0.42.0 in package.json
* `yarn install`
* `rm -rf build`
* `rm -rf ios/build`
* `node_modules/.bin/tsc`
* `react-natvie run-ios`
* You can't debug src/sourceMapIssue.tsx file but You can debug build/sourceMapIssue.js file in Chrome debugger

### Additional Information

- React Native version: 0.42
- Platform: both
- Operating System: MacOS

**Comment by vladimir-kotikov** [comment]
This was 'broken' in https://github.com/facebook/react-native/commit/0849f84df26e4c56f5763375363bae90d94015fe. Since that commit transformer module doesn't use default babel's 'transform' method (which was taking care of merging original and generated source maps - see https://github.com/babel/babel/blob/7d37017a5f85260c0c95580731585916e791265c/packages/babel-core/src/transformation/file/index.js#L535) to generate code but uses babel-generator's generate instead.

@davidaurelio, is that possible to add logic to handle pre-existing maps in original files (maybe similar to what was suggested in https://github.com/facebook/react-native/issues/7083#issuecomment-284147710)?

**Comment by davidaurelio** [comment]
It is possible, pull requests welcome. It should be a matter of detecting these source maps and feeding them into babel, right?

Apologies, but I don’t have capacities to look into this, and the new method of creating source maps has solved many issues around speed and correctness of source map generation.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by lukecwilliams** [comment]
FYI: workaround for TypeScript debugging will deploy soon in vscode-react-native.

See https://github.com/Microsoft/vscode-react-native/issues/441.
