### ISSUE TITLE
autocrlf git config - with windows EOL in source

### ISSUE THREAD

**Issue by GantMan** [facebook/react-native#12724]
If you have autocrlf set to true, then the gradle.bat side of things has issues.   I've noticed this fixed in RN in the past, but it seems to be back.

There are 3 possible fixes, and I'm willing to do any:

### First Fix
Document that line endings cannot be enforced at a git level.  Adding this to the docs and suggesting the fix as policy:
```
$ git config --global core.autocrlf false
$ git config --global core.safecrlf false
```

### Second Fix
I could clean up the offending files, and add a CI test to verify that any incoming PRs would not trigger this issue for others.

### Third Fix
We implement a `.gitattributes` file, which identifies the file types that can break the rules.  https://help.github.com/articles/dealing-with-line-endings/

---
This currently causing issues in our tooling - RE: https://github.com/infinitered/ignite/issues/864
Related stack overflow info: http://stackoverflow.com/questions/170961/whats-the-best-crlf-carriage-return-line-feed-handling-strategy-with-git

**Comment by ericvicenti** [comment]
I'm in support of the manual fix and adding some basic CI test to prevent a future regression. Not everybody who works on this codebase will have an understanding of this problem.

Some of this may need to be addressed by the FB open source team, because the repo's commits are actually synced out of the fb-internal mercurial repository.

**Comment by GantMan** [comment]
After some research, it seems there's already a `.gitattributes` file in place.   I think I'll break this into 2 PRs.

First and most quickly:  I'll just edit the `.gitattributes` file to make it compliant with safecrlf.

Second, I'll do a PR to the CI that can stop this from happening again.   This process is a bit more complex, but can happen over time once we're covered by PR 1.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
