### ISSUE TITLE
ListView can not use Methods (getScrollResponder, ScrollTo, etc)

### ISSUE THREAD

**Issue by vnshgrg** [facebook/react-native#12726]
`React Native Version ^0.38.0`

I have a ListView which has a referenced as "listViewReference"

`
<ListView ref="listViewReference" ...
`

Trying to access methods of ListView I get following error

`
this.refs.listViewReference.getScrollResponder() is not a function
`

I can not access any methods. I tried `scrollTo()` and `getMetrics()` too but no luck!

I tried referencing with a call too.
`
<ListView ref={(listView) => this.listViewReference = listView} ...
`
Still no luck!

**Comment by ericvicenti** [comment]
There haven't been many changes here, so I think it should work to `this._listView.getScrollResponder().scrollTo()`

If you're using a HOC, refs will also have issues because you actually refer to the outer component. Without seeing your code its hard to see if this is the problem.

Does this work with new versions of RN? Can you provide a reproduction that demonstrates the problem? You can re-open this issue with the additional details.
