### ISSUE TITLE
illegal callback type invocation from native module. This callback type only permits a single invocation from native code

### ISSUE THREAD

**Issue by Sofiane-13** [facebook/react-native#12729]
I developpe a react native application using sqlite.
My Android.node.js : 

```

var databaseName = 'react.db'
//initialiser base de donnée
 sqlite.init(databaseName)
     .then((_) => {
         console.log('database initialized.')
     }
 )
//declarer une requette
var sql = 'INSERT INTO principale(id, nom) VALUES (1, bonjour)'
 var params = ["Create react native android sqlite", 1]
//fermer la base de donnée

export default class sql2 extends Component {
  //function
  insert() {

sqlite.query(sql, params)
 .then((data) => {
     console.log('retrieved: ', data)
 }
)
     }
  render() {
    return (
      <View style={styles.container}>

        <Button title='salut' onPress={this.insert}>Cliquz sur moi</Button>


      </View>
    );
  }
}

```
I have this error : illegal callback type invocation from native module. This callback type only permits a single invocation from native code

**Comment by Braidio** [comment]
Getting this same error when using a custom NativeModule. But only on the android side.

My iOS method of the same name..

```
RCT_EXPORT_METHOD(sendGroupMsg: (NSDictionary *)params errorCallback:(RCTResponseSenderBlock)failureCallback)
```

And my failing Android method 

```
public void sendGroupMsg(ReadableMap params, Callback errorCallback) {
```

Assuming that because they're identical method setups, there shouldn't be an issue..

**Comment by dobrienlzd** [comment]
Facebook anyone?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
