### ISSUE TITLE
'List of devices attached' not showing any device. Also, 'Could not get BatchedBridged' issue.

### ISSUE THREAD

**Issue by prasang7** [facebook/react-native#12763]
### Description
Hi, **I'm new to the react-native** platform. I followed all the steps given here: [React-native Getting-started](https://facebook.github.io/react-native/docs/getting-started.html#content), to setup my development environment. 
### Details
* React Native version: 0.42
* Platform I want to work for: Android
* Operating System: Linux (Ubuntu 16.04.1 LTS 64-bit)
* Phone: OnePlus 2 - AndroidVersion 6.0.1 - Marshmallow

I followed these steps: [running-on-device](https://facebook.github.io/react-native/docs/running-on-device.html), to run the app on my phone connected to my laptop via USB cable. **I've enabled debugging over USB** and **inserted device id in udev rules** with the process mentioned. 

Now when I run `$ adb devices` 
It lists no android device attached. Here's how it looks: 

![ScreenShot](https://cloud.githubusercontent.com/assets/13434598/23656787/1dc77bde-0361-11e7-933b-dc6919203459.jpg)

Also, when I run `$ react-native run-android` 
then my phone shows these messages: 

![SS1](https://cloud.githubusercontent.com/assets/13434598/23656963/e06fb200-0361-11e7-81d4-171079b6549d.png)
![11](https://cloud.githubusercontent.com/assets/13434598/23656975/f074bad8-0361-11e7-9d65-1e4e2ce00bf6.png)

Being totally new to the platform, I really need help. **Can someone please explain what could be wrong here**. Thanks.

**Comment by hramos** [comment]
Ah, I've updated these instructions recently but I am afraid it has been a while since I have gone through the steps for this on Linux. It's possible the instructions need to be updated.

I'll be watching this issue closely for resolution, in case the docs need to be updated.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by VineetKumarKushwaha** [comment]
Hey I am facing this issue with react 0.49.2.Please suggest the solution or any workaround for now ?
