### ISSUE TITLE
Jest snapshot using a ListView fails with unique "key" error

### ISSUE THREAD

**Issue by luisfcofv** [facebook/react-native#12762]
Adding a snapshot test using a ListView fails with the following error:

```
console.error node_modules/react-native/Libraries/Core/ExceptionsManager.js:71
      Warning: Each child in an array or iterator should have a unique "key" prop.
      Check the render method of `ScrollViewMock`.
      It was passed a child from ListViewMock. See https://fb.me/react-warning-keys for more information.
```

Code snippet:

```javascript
export class App extends Component {
  state = {
    dataSource: new ListView.DataSource({ rowHasChanged: (r1, r2) => r1 !== r2 }),
  };

  componentWillReceiveProps({ results }) {
    this.setState({
      dataSource: this.state.dataSource.cloneWithRows(results),
    });
  }

  renderHeader = () => (
    <Header />
  );

  renderRow = resultInfo => (
    <ResultCell resultInfo={resultInfo} />
  )

  renderFooter = () => {
    const { results } = this.props;
    if (results.length >= results.totalItems) {
      return null;
    }

    return <ActivityIndicator />;
  }

  render() {
    return (
      <ListView
        dataSource={this.state.dataSource}
        enableEmptySections
        renderHeader={this.renderHeader}
        onScroll={Keyboard.dismiss}
        renderRow={this.renderRow}
        renderFooter={this.renderFooter}
      />
    );
  }
}
```

Test:
```javascript
test('renders correctly', () => {
  const tree = renderer.create(
    <App results={[]}  />
  ).toJSON();
  expect(tree).toMatchSnapshot();
});
```

react native: **0.42.0**
jest: **19.0.2**
yarn: **0.21.3**
os: **macOS**

**Comment by luisfcofv** [comment]
Removing renderFooter & renderHeader seems to fix the problem; however, I need those props

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by spinningarrow** [comment]
I'm seeing this issue as well with React Native 0.47.1. Is there a way to fix it?

**Comment by keijohyttinen** [comment]
At least warning disappeared for me with a workaround mentioned at
https://github.com/facebook/react-native/issues/12225

**Comment by mohamede1945** [comment]
For me, the workaround was to add `key="footer"` to the footer and you can do the same for header if the warning didn't go away.
