### ISSUE TITLE
WebView has inconsistent behavior across iOS and Android when injecting javascript

### ISSUE THREAD

**Issue by ccdwyer** [facebook/react-native#12769]
--- Please use this template, and delete everything above this line before submitting your issue --- 

### Description

I tried to inject javascript on load into a webview.  It works as expected on iOS devices, but not as expected on Android devices.  On android devices, the page loads, then a white screen comes up, with a word from the script shown.

### Reproduction

https://github.com/ccdwyer/WebViewJSInjectionDemo
Simply running this with iOS and Android will demonstrate what is going wrong.  You should get a google homepage with a red background.  On android you get a white screen that says 'red'.

Example: http://imgur.com/a/XC2Jc

### Solution

The Android version of the webview should execute javascript in the same manner as the iOS webview.

### Additional Information

* React Native version: 0.42
* Platform: Android
* Operating System: MacOS

**Comment by rgoldiez** [comment]
Same issue here.

**Comment by mmazzarolo** [comment]
Same issue, any hint?

**Comment by ccdwyer** [comment]
@mmazzarolo I still don't have a good solution yet for Android. I was porting a chrome extension to what I hoped was a cross platform app.  For now, it looks like it's iOS only.

**Comment by rgoldiez** [comment]
I had issues with Android's WebView (as compared to iOS).  In my case, I found that comments `//...` in the injected JS code caused issues in Android's WebView.  iOS was fine.  When I removed my commented code, the injected JS executed as expected on Android.

**Comment by ccdwyer** [comment]
@rgoldiez This is all that I am trying to inject:
`
const script = "document.body.style.background = 'red';";
if (this.webview) {
  this.webview.injectJavaScript(script);
}
`

And I am getting a blank screen that just says 'red': http://imgur.com/a/RvkP9

This is with react-native 0.44.0.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by dahjelle** [comment]
@rgoldiez 

> I had issues with Android's WebView (as compared to iOS). In my case, I found that comments //... in the injected JS code caused issues in Android's WebView. iOS was fine. When I removed my commented code, the injected JS executed as expected on Android.

For whatever reason, it looks like the Android WebView puts all injected JS on a single line. That means that `//` comments and missing semicolons really mess things up (as well as other things, probably). You can see if it you use Chrome's remote debugging feature to debug code in the web view. You **can** use `/*`-`*/` style comments, though.
