### ISSUE TITLE
Rewrite HMR support in react-native-packager.

### ISSUE THREAD

**Issue by cpojer** [facebook/react-native#12774]
Placeholder issue; we'll spec it out in a bit.

**Comment by cpunion** [comment]
Wow. What new features/improvements about it?

**Comment by cpojer** [comment]
Just code changes, no functional changes for users. We need to clean it up!

**Comment by indexzero** [comment]
Howdy! Thanks for setting this up 😸 ... for anyone interested in the state of the world right now start by reading:

- [React Native Blog post: "Introducing Hot Reloading"](https://facebook.github.io/react-native/blog/2016/03/24/introducing-hot-reloading.html)
- [Dan Abramov on "Hot Reloading in React"](https://medium.com/@dan_abramov/hot-reloading-in-react-1140438583bf#.8a2u7qnlx)

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
