### ISSUE TITLE
state in es6

### ISSUE THREAD

**Issue by nicolaselmir** [facebook/react-native#12809]
Can anyone help me with this: 
  ```
_keyboardWillShow () {
    this.setState({margin:100})
  }
 
  _keyboardWillHide () {
    this.setState({margin:-100})
  }
  
  constructor(props){
    super();
    this.state = { 
      email: null,
      password: null,
      margin:-100
    };
  }

```

Error: this.setState is not a function ...

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
