### ISSUE TITLE
RCTHTTPRequestHandler.h not found, required for certificate pinning

### ISSUE THREAD

**Issue by suparngp** [facebook/react-native#12812]
### Description

In the previous versions of RN, I was overriding RCTHTTPRequestHandler to add NSURLSessionDelegate for certificate pinning. 

With the latest version, I changed the import to `#import <React/RCTHTTPRequestHandler.h>`
But this header is no longer visible in the latest version (0.42). 

Is there any other recommended way to deal with certificate pinning?
### Reproduction

Try to import RCTHTTPRequestHandler.h in an Objective C class and Xcode will show an error.

### Additional Information

* React Native version: 0.42
* Platform: iOS
* Operating System: MacOS

**Comment by marcelosampaio** [comment]
Same issue here

**Comment by marcelosampaio** [comment]
The solution for this is issu is quiet easy! :)

1) In Xcode select React.xcodeproj (Libraries)
2) Drag RCTHTTPRequestHandler.h to 'Build Phases' to Header and Copy Headers sections

Done! :)

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
