### ISSUE TITLE
React Native multi threading?

### ISSUE THREAD

**Issue by Lizhooh** [facebook/react-native#12815]
### Description

Hello, I am a beginner.
In `React Native` how to use similar `web worker` **multi-threaded** operation ?

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
