### ISSUE TITLE
borderStyle ‘dashed’ didn’t work when borderBottomWidth set

### ISSUE THREAD

**Issue by jeremylbq** [facebook/react-native#12817]
`itemLineStyle:{
        marginTop:2.7,
        marginLeft:1.6,
        marginRight:1.6,
        borderBottomWidth:1,
        borderStyle:'dashed'
    }`
AS what I Post above ，it did‘t  worked and show nothing；But When I set borderStyle ：solid，it worked and show a line ， so，is there wrong in my code ？

I just want draw a dashed ， if you have any good idea ， post it ， thank you so much。

**Comment by sdeleon28** [comment]
I can reproduce this. If you set `borderWidth: X`, the four borders get drawn, but if you use `borderBottomWidth` (to achieve the rather common effect of dotted underlining) no borders show up.

**Comment by sdeleon28** [comment]
You can use this workaround -> https://github.com/facebook/react-native/issues/7838#issuecomment-290970249

**Comment by RyanMitchellWilson** [comment]
I'm getting this same problem, any progress on fix? The workaround posted above will not work for me.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by jnrepo** [comment]
Experiencing this issue. Workaround with `dotted` does not work. Anyone know another workaround?

**Comment by kumarks1122** [comment]
Same issue with `dashed` style.

**Comment by luizguilhermefr** [comment]
In my case, `dashed` style takes no effect. Acts like solid. Please reopen.

**Comment by reborne** [comment]
this may sound unobvious, but
add `borderRadius: 0.5 or 1` to @jeremylbq 's style.

works on react-native 0.5 aswell

**Comment by code-matt** [comment]
@reborne That did not work for me

How do bugs like this still exist in such a popular framework? I saw issues talking about this in early 2016. Its exactly as @sdeleon28 described.

**Comment by hramos** [comment]
@luizguilhermefr it doesn't look like the issue meets the criteria to re-open. You may open a new one.

**Comment by spicyboiledfish** [comment]
I have the same issue. Thanks @reborme, it works when I add borderRadius: 0.5 or 1.
