### ISSUE TITLE
upgrade to React native 0.42 and run android has error globalObject.hasOwnProperty

### ISSUE THREAD

**Issue by Micjoyce** [facebook/react-native#12823]
I upgrade 0.40 to 0.42; run ios is ok, run android will get
```

undefined is not a function(evaluating 'globalObject.hasOwnProperty("Promise")') 

```

![image](https://cloud.githubusercontent.com/assets/4250838/23743508/d5ce6644-04eb-11e7-899e-a7faf11abd93.png)

there are my dependencies

```

"@exponent/react-native-action-sheet": "^0.3.0",
		"async": "^2.1.4",
		"clamp": "^1.0.1",
		"lodash": "^4.17.2",
		"md5": "^2.2.1",
		"moment": "^2.13.0",
		"pinyin": "^2.8.0",
		"react": "~15.4.1",
		"react-addons-shallow-compare": "^15.4.1",
		"react-native": "0.42.0",
		"react-native-animatable": "^1.1.0",
		"react-native-cached-image": "https://github.com/Micjoyce/react-native-cached-image.git",
		"react-native-checkbox": "^1.1.0",
		"react-native-code-push": "^1.17.0-beta",
		"react-native-communications": "^2.1.4",
		"react-native-contacts": "^0.8.0",
		"react-native-device-info": "^0.9.7",
		"react-native-easy-grid": "^0.1.7",
		"react-native-fetch-blob": "^0.10.3-beta.1",
		"react-native-fs": "^2.1.0-rc.1",
		"react-native-i18n": "1.0.0",
		"react-native-image-crop-picker": "https://github.com/Micjoyce/react-native-image-crop-picker.git",
		"react-native-image-picker": "^0.25.1",
		"react-native-image-zoom-viewer": "https://github.com/Micjoyce/react-native-image-viewer.git",
		"react-native-invertible-scroll-view": "^1.0.0",
		"react-native-keyboard-aware-scroll-view": "^0.2.4",
		"react-native-meteor": "https://github.com/Micjoyce/react-native-meteor",
		"react-native-parsed-text": "^0.0.16",
		"react-native-root-siblings": "^1.1.2",
		"react-native-router-flux": "^3.37.0",
		"react-native-scrollable-tab-view": "^0.7.1",
		"react-native-splash-screen": "^2.0.0",
		"react-native-vector-icons": "^4.0.0",
		"react-native-wechat": "https://github.com/Micjoyce/react-native-wechat",
		"react-redux": "^4.4.6",
		"redux": "^3.6.0",
		"redux-devtools-extension": "^1.0.0",
		"redux-logger": "^2.7.4",
		"redux-persist": "^4.0.0-beta1",
		"redux-thunk": "^2.1.0",
		"shallowequal": "^0.2.2",
		"style-equal": "^1.0.0"

```

**Comment by Micjoyce** [comment]
It seem  es6-promisify error. because I use react-native-wechat  https://github.com/weflex/react-native-wechat/issues/176

**Comment by jynlix** [comment]
I got this error too

**Comment by lifuzu** [comment]
+1

**Comment by devhyunjae** [comment]
+1

**Comment by wuyunqiang** [comment]
+1
how to fix it?

**Comment by devhyunjae** [comment]
@wuyunqiang  There will be a code using Promisify. Replace that to es6 promise or other.

**Comment by wuyunqiang** [comment]
@devhyunjae  thanks.

**Comment by lipingruan** [comment]
+1008611

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by lukewlms** [comment]
Can anyone on this thread provide a specific example of how to use Promisify with React Native?  The accepted answer is a bit enigmatic to me.

So far I've been unable to hook this up and am promisifying everything manually.
