### ISSUE TITLE
WebView keyboard without arrows and "Done" button?

### ISSUE THREAD

**Issue by lealife** [facebook/react-native#12821]
Copy from https://github.com/alinz/react-native-webview-bridge/issues/54

I know this is more React Native specific, but I figured a lot of people using the bridge would like to have this option.. Is there any way to disable the Arrows and 'Done' button above the keyboard in the webView?

I have a webView that loads a text editor that uses contentEditable text fields. But I have my own editor bar above the keyboard, and the safari bar above the keyboard makes it seem non-native.

Now it's like this: http://i.stack.imgur.com/Uz2Ly.png
But I want my own like this: http://www.geeky-gadgets.com/wp-content/uploads/2015/03/medium.jpg

I have found some solutions on how to do this, but I'm not able to implement it into the native code myself.

This code should work with iOS 9: http://stackoverflow.com/questions/19033292/ios-7-uiwebview-keyboard-issue/19042279#19042279

Here's a Cordova plugin that does the same (hideKeyboardAccessoryBar): https://github.com/driftyco/ionic-plugin-keyboard

**Comment by magicismight** [comment]
Try this repo: https://github.com/magicismight/react-native-advanced-webview
And turn on `hideAccessory` prop.
https://github.com/magicismight/react-native-advanced-webview/blob/master/index.js#L76

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
