### ISSUE TITLE
Can I create a Single-Purpose App  (COSU) app for Android in React Native?

### ISSUE THREAD

**Issue by ernestova** [facebook/react-native#12834]
Is currently React Native ready for a Single-Purpose App (https://developer.android.com/work/cosu.html) ?

**Comment by ericvicenti** [comment]
Yes, I believe this should work fine.

This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
