### ISSUE TITLE
upgrade to v0.35 causes maximum call stack size exceeded

### ISSUE THREAD

**Issue by jcbiznoff** [facebook/react-native#12831]
### Description
I recently upgraded from v0.30 to v0.35 using
react-native-git-upgrade 0.35.0
and both android and ios is throwing error. I also tried manually upgrading and ended up with same result.

Android log:
Maximum call stack size exceeded
checkReactTypeSpec
    checkReactTypeSpec.js:77
validatePropTypes
    ReactElementValidator.js:153
Object.createElement
    ReactElementValidator.js:189
AnimatedComponent.render
    AnimatedImplementation.js:1704
<unknown>
    ReactCompositeComponent.js:793
measureLifeCyclePerf
    ReactCompositeComponent.js:74
ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext
    ReactCompositeComponent.js:792
ReactCompositeComponentWrapper._renderValidatedComponent
    ReactCompositeComponent.js:819
ReactCompositeComponentWrapper._updateRenderedComponent
    ReactCompositeComponent.js:743
ReactCompositeComponentWrapper._performComponentUpdate
    ReactCompositeComponent.js:721

ios log:
Maximum call stack size exceeded
checkReactTypeSpec
    checkReactTypeSpec.js:77
validatePropTypes
    ReactElementValidator.js:153
Object.createElement
    ReactElementValidator.js:189
AnimatedComponent.render
    AnimatedImplementation.js:1704
<unknown>
    ReactCompositeComponent.js:793
measureLifeCyclePerf
    ReactCompositeComponent.js:74
ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext
    ReactCompositeComponent.js:792
ReactCompositeComponentWrapper._renderValidatedComponent
    ReactCompositeComponent.js:819
ReactCompositeComponentWrapper._updateRenderedComponent
    ReactCompositeComponent.js:743
ReactCompositeComponentWrapper._performComponentUpdate
    ReactCompositeComponent.js:721

### Additional Information
* React Native version: reproducible on the latest
* Platform: ios and Android
* Operating System: MaxOS
* Dev tools: Xcode, Android studio 2.3

**Comment by SoloRN** [comment]
I have the same problem on RN 0.42

**Comment by rodolfobarretoweb** [comment]
I have the same issue on RC 0.42. To me the app only run when Hot Reloading is enable.

**Comment by jcbiznoff** [comment]
It seems this had to do with NavigationExperimental I was using in my code with passing ref as props. Removing this got me back on the road. Wish the logs are more descriptive.

**Comment by cdesch** [comment]
Same here in respect to NavigationExperimental

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
