### ISSUE TITLE
Unhandled JS Exception: Invariant Violation: Module name prefixes should've been stripped by the native side but wasn't for RCTJSCExecutor 

### ISSUE THREAD

**Issue by timtawan** [facebook/react-native#12843]
Please help 

react-native-cli: 2.0.1
react-native: 0.42.0

<img width="375" alt="screen shot 2560-03-10 at 15 26 23" src="https://cloud.githubusercontent.com/assets/10970130/23782100/f6fb360c-05a5-11e7-9074-cc9a1791fc17.png">

**Comment by keyian** [comment]
I have the same problem. Did you solve it?

**Comment by rolele** [comment]
Same problem here.
I have this screen when I run: `react-native run-ios`
```
In file included from /Users/others/working/aa_working/js/react-native/the-complete-react-native-and-redux/onwards/albums/node_modules/react-native/Libraries/Geolocation/RCTLocationObserver.m:10: 
/Users/others/working/aa_working/js/react-native/the-complete-react-native-and-redux/onwards/albums/node_modules/react-native/Libraries/Geolocation/RCTLocationObserver.h:10:9: fatal error: 'React/RCTEventEmitter.h' file not found 
#import <React/RCTEventEmitter.h> 
^ 
error: PCH was compiled with module cache path '/Users/others/working/aa_working/js/react-native/the-complete-react-native-and-redux/026-app-outline/albums/ios/build/ModuleCache/1VV67NB87QSZJ', but the path is currently '/Users/others/working/aa_working/js/react-native/the-co
mplete-react-native-and-redux/onwards/albums/ios/build/ModuleCache/1VV67NB87QSZJ' 
2 errors generated. 
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1


** BUILD FAILED **


The following commands produced analyzer issues:
Analyze RCTActionSheetManager.m 
Analyze RCTLocationObserver.m 
(2 commands with analyzer issues) 

The following build commands failed:
CompileC /Users/others/working/aa_working/js/react-native/the-complete-react-native-and-redux/onwards/albums/ios/build/Build/Intermediates/RCTWebSocket.build/Debug-iphonesimulator/RCTWebSocket.build/Objects-normal/x86_64/RCTWebSocketObserver.o RCTWebSocketObserver.m n
ormal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
CompileC /Users/others/working/aa_working/js/react-native/the-complete-react-native-and-redux/onwards/albums/ios/build/Build/Intermediates/RCTLinking.build/Debug-iphonesimulator/RCTLinking.build/Objects-normal/x86_64/RCTLinkingManager.o RCTLinkingManager.m normal x86_
64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
Analyze RCTLocationObserver.m 
(3 failures)

Installing build/Build/Products/Debug-iphonesimulator/albums.app
Launching org.reactjs.native.example.albums
```

If I open the xcode project -> Clean (cmd K) -> Sheme React -> Build (cmd b) -> Scheme myapp -> Run -> then it works.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by nikhilvachhani** [comment]
Please reopen this issue. we have this issue since last couple of weeks.

**Comment by edencakir** [comment]
I have this issue as well.
