### ISSUE TITLE
Application starts crushing after about 1 week of innactivity [iOS]

### ISSUE THREAD

**Issue by IljaDaderko** [facebook/react-native#12847]
react-native 0.42, ios

I'm not sure what this is, but for some reason when I build release to my iPhone, under my developer account application starts crushing after 1 week of inactivity.

Initially everything functions correctly, all use cases pass, I close / open the app, close it from the drawer etc.. and it all works good. After I leave it for about a week and open it up it just crushes, i.e. I click on an icon, it starts expanding into a view and immediately crushes. This used to happen to me in several previous react native versions as well.

I can't debug it, as every time I connect my phone to encode and run the app it seems to somewhat refresh / update it and it works fine as before.

Any one experienced this before, any ideas of what this is?

**Comment by Sh3rawi** [comment]
https://forums.developer.apple.com/thread/51527
This is something from Apple itself, not react-native. Your build will last for 7 days and then you'll have to rebuild it from xcode again.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
