### ISSUE TITLE
React native upgrade to 0.41 doesn't build Android release builds_hangs at bundleReleaseJsAndAssets

### ISSUE THREAD

**Issue by ghprud** [facebook/react-native#12841]
Please read the following carefully before opening a new issue.

--- Please use this template, and delete everything above this line before submitting your issue --- 

### Description

Upgraded to react native 0.41 and tried running the Android builds using gradle

### Reproduction

Go to Android folder and run ./gradlew assembleRelease

### Solution

I don't have any solution for this. 

### Additional Information

* React Native version: 0.41
* Platform: Android
* Operating System: MacOS
* Dev tools: 

More output from running the gradle command:
14:39:26.502 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired.
14:39:26.503 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
14:39:26.503 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
14:39:26.503 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired.
14:39:26.503 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
14:39:36.501 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
14:39:36.502 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
14:39:36.502 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired.
14:39:36.502 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
14:39:36.503 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
14:39:36.503 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired.
14:39:36.503 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.

**Comment by wilomgfx** [comment]
I get the same issue with 0.43.1

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by sidferreira** [comment]
Just having it and I have no idea what can be the issue. Yesterday was working...
