### ISSUE TITLE
react native link question

### ISSUE THREAD

**Issue by huangminlinux** [facebook/react-native#12852]
react-native version
react-native-cli: 0.2.0
react-native: 0.41.2

after rnpm 1.9.0 version https://github.com/rnpm/rnpm/releases/tag/v1.9.0

So when I public my lib, I can add lib in  sharedLibraries, just like that
```
  	"rnpm": {
    	"ios": {
      	"sharedLibraries": [
        	"libz",
        	"UserNotifications",
        	"CoreTelephony",
        	"Security",
        	"CFNetwork",
        	"CoreFoundation",
        	"SystemConfiguration",
        	"Foundation",
        	"UIKit",
        	"libresolv",
        	"CoreGraphics"
      	]
    	}
  	}
```

the problem was that the UserNotification.framework only available in iOS 10, so it could not be required, this framework status should be set to optional
<img width="673" alt="73b5462e-33e9-41a2-aa8c-b7ae94188b27" src="https://cloud.githubusercontent.com/assets/5852088/23794421/fe3798e6-05ca-11e7-9f97-fbd8368fe950.png">

Are there any configuration item to set this framework to optional after ```react-native link```?

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
