### ISSUE TITLE
Documentation: AsyncStorage docs missing vital details

### ISSUE THREAD

**Issue by lll000111** [facebook/react-native#12856]
https://facebook.github.io/react-native/docs/asyncstorage.html

Vital questions that remain unanswered:

- Format of error objects: possible error codes
- What happens when I try to "set" an item that already exists? Will it silently overwrite or raise an error?
- What happens when I try to "get" an item that does not exist? undefined, null or error?

I'm trying to convert node.js code that relies on ndoe.js "fs" module API details like the above, like not overwriting existing files unless "force"-d, or raising an error when trying to access a non-existent file, and I will have to run experiments to try to find out the react-native behavior (which on a laptop and the slow device emulator is quite a chore). This should have been in the documentation.

**Comment by Etheryte** [comment]
As the [current documentation code](https://facebook.github.io/react-native/docs/asyncstorage.html) examples hints, if you try to get an item that doesn't exist, you get `null` instead.

```js
try {
  const value = await AsyncStorage.getItem('@MySuperStore:key');
  if (value !== null){
    // We have data!!
    console.log(value);
  }
}
```

You can confirm this by looking at [the source of AsyncStorage.js, line 84](https://github.com/facebook/react-native/blob/master/Libraries/Storage/AsyncStorage.js#L84):

```js
var value = (result && result[0] && result[0][1]) ? result[0][1] : null;
```

As for setting items, the storage engine used depends on what the currently running device has available ([see the same file, line 19](https://github.com/facebook/react-native/blob/master/Libraries/Storage/AsyncStorage.js#L19)), however they should all silently overwrite items as far as I'm aware.

Perhaps someone else can chime in on the error formats.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
