### ISSUE TITLE
[TextInput] Padding in Text and TextInput renders slightly differently

### ISSUE THREAD

**Issue by oblador** [facebook/react-native#1287]
I'm trying to build a autogrowing `TextInput` and is using a shadow `Text` component to measure the text (I'm sure there's a better way, maybe expose `NSString.boundingRectWithSize`). However I noticed that the padding is slightly differently rendered on the two, it seems `TextInput` has an extra 2px (or 1pt?) horizontal padding causing the text to wrap differently. 

`padding: 0`. `TextInput` first, `Text` last.
![screendump](https://cloud.githubusercontent.com/assets/378279/7644314/82ec93dc-faa3-11e4-95d4-109b60e1ca7c.png)

**Comment by nicklockwood** [comment]
You might want to take a look at #1229 as it looks like what you're trying to do has already been implemented in that PR.

**Comment by oblador** [comment]
@nicklockwood: Thanks, missed that one. This bug still stands though, although maybe not as important :-)

**Comment by brentvatne** [comment]
[Example here](https://rnplay.org/plays/rwvHNg?autoplay=true)

Could you fork this and modify it to produce the same bug?

Thanks @oblador!

**Comment by oblador** [comment]
Made an example of this on [RNPlay](https://rnplay.org/apps/-C2o-w/). Also notice how the vertical padding is different.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/textinput-padding-in-text-and-textinput-renders-slightly-differently

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.

**Comment by oblador** [comment]
There are bigger problems to tackle :-)

**Comment by aleclarson** [comment]
@oblador is this still an issue?
