### ISSUE TITLE
Flex Layout - minWidth property is always used even if more space is available in RN 0.42

### ISSUE THREAD

**Issue by brianfoody** [facebook/react-native#12878]
### Description
If I have a View with flexDirection row and three children with flex 1 I would expect them to fill up all the space of the parent. However if I add a minWidth property to the child views the minWidth is used and leftOver 

### Reproduction

https://github.com/brianfoody/react-native-min-width-issue

None of the red view should be displayed as the children should take up all available space

### Solution

Sorry I'm not familiar with the underlying layout engine. I'm guessing this is related to the switch to Yoga and possibly percentage width support.

### Additional Information

* React Native version:0.42.0
* Platform: iOs
* Operating System: MacOS
* Dev tools: xCode 8.2.1, Simulator 10 and iPhone 6s 10.2

**Comment by sckoh** [comment]
+1

**Comment by guiherzog** [comment]
+1

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by pedro** [comment]
fwiw I'm also running into this issue on 0.45 – seems to be fixed in 0.52.
