### ISSUE TITLE
Upgrade NetInfo for iOS

### ISSUE THREAD

**Issue by yolosaucisson** [facebook/react-native#12882]
### Description

I'm using an iPhone 5S and i have a problem.
Everytime I want to know the network if it's connected to internet or not.
NetInfo returns me "unknown", the same happens when i'm not connected, connected, not connected with SIM card and connected with SIM card.

There is no problem on Android.

### Reproduction

Use NetInfo on an iPhone 5S at least.
Maybe there is the same problem on others.

### Solution

Upgrade NetInfo or add something to Xcode to know the network?

### Additional Information

* React Native version: 0.42
* Platform: iOS 5S
* Operating System: MacOS

**Comment by MattyK14** [comment]
Getting `false` on iOS simulator & iPhone 6 10.3, when isConnected should return `true`.

**Comment by levsero** [comment]
@MattyK14 I assume your issue is the same as https://github.com/facebook/react-native/issues/8615, not clear if @yolosaucisson's issue is the same or different becuase it's returning `unknown` instead of `false`.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
