### ISSUE TITLE
react-native init fails to set up new project, without yarn (Windows)

### ISSUE THREAD

**Issue by mjasnikovs** [facebook/react-native#12898]
On windows, "react-native init" fails to setup proper working environment, if no **yarn** is installed and default npm is used to set up new react-native project.

I got "Cannot find entry file index.android.js in any of the roots" error, i manually patched this issue, and then i get next error "Cannot resolve module react".

I installed **yarn**, executed new project. All issues are gone.

### Additional Information
npm 3.10.10
node 6.10.0
react-native-cli 2.0.1
Windows 7

Path used "C:\hub\sec", where react-native cli was referring to "c:\hub\sec", i don't know, if it had any problems with path's capital letters.

**Comment by liuliangsir** [comment]
+1
I assume that yarn may be the source of evil

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
