### ISSUE TITLE
Image Cache IOS

### ISSUE THREAD

**Issue by pj0579** [facebook/react-native#12894]
Description：

All image is cached, but sometimes some cached pictures don't show when you Shut down the network  into the app  again.

* React Native version:0.39.2
* Platform: IOS
* Operating System:Mac
* Dev tools: Xcode

**Comment by pj0579** [comment]
like this 
![image](https://cloud.githubusercontent.com/assets/20592579/23847576/00877d60-080e-11e7-8e13-bf9b5ba7ee1a.png)

**Comment by pj0579** [comment]
This is a release version

**Comment by pj0579** [comment]
Is the code
![image](https://cloud.githubusercontent.com/assets/20592579/23847650/6585b2a4-080e-11e7-9a9f-e6b4365cbe55.png)

**Comment by pj0579** [comment]
<Image key={1} style={{height: 500,width:500}} source={{uri: "https://img.alicdn.com/imgextra/i3/2989293827/TB2Uzklg9XlpuFjy0FeXXcJbFXa_!!2989293827.jpg"}}/>
              <Image key={3} style={{height: 500,width:500}} source={{uri: "https://img.alicdn.com/tps/i4/TB1AKFuPVXXXXXIXpXXSutbFXXX.jpg_q90.jpg"}}/>
              <Image key={2} style={{height: 500,width:500}} source={{uri: "https://img.alicdn.com/tps/i4/TB1GR8aPVXXXXX9XVXXSutbFXXX.jpg_q90.jpg"}}/>
              <Image key={4} style={{height: 500,width:500}} source={{uri: "https://img.alicdn.com/tps/i4/TB1MaoePVXXXXbJXVXXSutbFXXX.jpg_q90.jpg"}}/>
              <Image key={5} style={{height: 500,width:500}} source={{uri: "https://img.alicdn.com/tps/i4/TB1W0A3PVXXXXX7XFXXSutbFXXX.jpg_q90.jpg"}}/>

**Comment by hramos** [comment]
Do you have specific repro steps that cause this?

**Comment by pj0579** [comment]
@hramos   I have，Is such,The app is only one page，When you have a network in the first open the app at a time，images are ok，then you close the app from the background and shut down the network to open the app.(use my images list)

**Comment by pj0579** [comment]
@hramos 
the image no show will perform this method after  more than ten seconds
![image](https://cloud.githubusercontent.com/assets/20592579/23977671/6eff7478-0a2a-11e7-9d09-8e7fc1e25f4c.png)

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
