### ISSUE TITLE
RCTWebSocketDebugger.xcodeproj

### ISSUE THREAD

**Issue by myusuf3** [facebook/react-native#1290]
This is broken in 0.4.3, it missed `*.h`, `*.m` `*.js` files that used to be there previously. Did you decide to go another way without any docs?

I was that WebSockets in library worked when it was pulled into project, is this the new intended was to get web sockets for debugger working?

**Comment by crucialfelix** [comment]
I have related broken issues with 0.4.3

    XCode is saying RCTWebSocketDebugger.xcodeproj has Workspace Integrity error, Couldn't load project

Opening it manually gives an alert informing us that:

    Project /Users/crucial/code/bathyscaphe-react/node_modules/react-native/Libraries/RCTWebSocketDebugger/RCTWebSocketDebugger.xcodeproj cannot be opened because it is missing its project.pbxproj file.

And my own project fails to build due to linker errors related to RCTWebSocketExecutor which it is executing.

I'm guessing that its been removed deliberately but our old projects still have them referenced.

**Comment by crucialfelix** [comment]
You probably did the same thing as me and updated your react-native for an existing project.

We just need to remove it from our projects

YourProject > Libraries > RCTWebSocketDebugger [should be a blue xcodeproj icon]

Right click on it and delete it.

Build succeeded !

**Comment by ide** [comment]
You'll want to link the new RCTWebSocket library too so that you get back the Chrome debugger and the new WS polyfill. This probably should have been mentioned in the release notes.

Someone else will have to confirm whether React is following semver, but if so, anything numbered 0.x.x is subject to API changes until it hits 1.0.0. That said I think the team generally has maintained backwards compatibility or added warnings during deprecation periods while keeping pace.

**Comment by xinthink** [comment]
How can I link the RCTWebSocket library? There's no xcodeproj under the WebSocket directory?

**Comment by ide** [comment]
The files might already be included then. If the Chrome debugger works for you everything is good.

**Comment by xinthink** [comment]
It doesn't work, there's no . xcodeproj under the WebSocket directory.

but I managed to make one myself, and then linked it to the app project, so it works now.

**Comment by dsibiski** [comment]
Hey guys, @vjeux mentioned that there is a fix in the works. The .xcodeproj got ignored by .hgignore.

**Comment by myusuf3** [comment]
@dsibiski so adding that websocket folder wasn't long term solution?

**Comment by dsibiski** [comment]
@myusuf3 AFAIK, they are working to get it back to an .xcodeproj library as it was before...that's based on a brief conversation I had with @vjeux earlier today. That could very well change. I believe @ide is working on a solution right now and there is an even better solution planned for the future in this Pull Request: #485

**Comment by voronianski** [comment]
+1 Have the same problem

**Comment by vjeux** [comment]
@voronianski: if you upgrade to 0.4.4 it should work fine. Let me know if it doesn't

**Comment by voronianski** [comment]
@vjeux I still have such problem with`0.4.4` here - https://github.com/voronianski/react-native-effects-view/tree/master/example/EffectsApp

![](https://dl.dropboxusercontent.com/u/100463011/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202015-05-16%20%D0%B2%2023.20.45.png)

**Comment by voronianski** [comment]
@vjeux also I'm not sured regarding API changes with working on native modules.

I saw somewhere on twitter that `createReactIOSNativeComponentClass` (https://github.com/voronianski/react-native-effects-view/blob/master/index.ios.js#L50) should be replaced with new method.

**Comment by dsibiski** [comment]
@voronianski If you are still having the linker issue, it looks like it's because you need to remove the `RCTWebSocketDebugger.xcodeproj` library from your app (that's the old one) and add the new `RCTWebSocket.xcodeproj`. See this page for help: http://facebook.github.io/react-native/docs/linking-libraries.html#content

Also don't forget to add the 'libRCTWebSocket.a" file to the "Link Binary With Libraries" Build Phase.

**Comment by gaearon** [comment]
@dsibiski Thanks so much for this tip.

**Comment by dsibiski** [comment]
@gaearon No problem! I'm glad it helped someone. :)

**Comment by AlfonsoPerez** [comment]
Hi there! I am getting the following error while adding `RCTWebsocket.xcodeproj` and linking to it:

    Undefined symbols for architecture x86_64:
    "_RCTGetExecutorID", referenced from:
     ___57-[RCTWebSocketExecutor sendMessage:context:waitForReply:]_block_invoke in         libRCTWebSocket.a(RCTWebSocketExecutor.o)
    "_RCTNullIfNil", referenced from:
      -[RCTWebSocketManager webSocket:didCloseWithCode:reason:wasClean:] in libRCTWebSocket.a(RCTWebSocketManager.o)
    "_RCTRegisterModule", referenced from:
      +[RCTWebSocketManager load] in libRCTWebSocket.a(RCTWebSocketManager.o)
      +[RCTWebSocketExecutor load] in libRCTWebSocket.a(RCTWebSocketExecutor.o)
    "__RCTNotImplementedException", referenced from:
      -[RCTSRWebSocket init] in libRCTWebSocket.a(RCTSRWebSocket.o)
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

Anyone knows why this might happen?,
Thanks!

**Comment by AlfonsoPerez** [comment]
Never mind, I was including the library from the wrong place (ie. Outside of the default search path).
