### ISSUE TITLE
Memory usage does not go down after setting RCTBridge & RCTRootView to nil

### ISSUE THREAD

**Issue by Jarred-Sumner** [facebook/react-native#12906]
### Description

To conserve battery, my iOS app needs to unload all of the React Native code and then load it back in later. 

To try to do that, I manually create a `RCTBridge` and instantiate a `RCTRootView` with that `RCTBridge`. When the old `RCTBridge` and `RCTRootView` gets set to `nil`, I expected it to effectively remove the React Native JS code from running, but it apparently does not fully do that. Memory usage meaningfully grows each time I create a new `RCTBridge` & `RCTRootView`.

### Reproduction

To check that it wasn't just my own code causing this, I created a new app that just instantiates a new `RCTBridge` and `RCTRootView` and sets the former `RCTBridge` (if applicable) to `nil` on a timer.

GitHub repo with test app: https://github.com/jarred-sumner/memorytest

Here's a video of that test app running: https://www.dropbox.com/s/gzne4uvke8wge4y/memory.mov?dl=0

Note that when the application started, it used ~60MB. After about a minute, it was using 90MB of memory. In the non-test app, this is much worse since there's quite a lot more going on.

Steps to reproduce:

1) Create new React Native app using `react-native init`
2) Replace AppDelegate.m with this code:

```objectivec
/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

#import "AppDelegate.h"

#import <React/RCTBundleURLProvider.h>
#import <React/RCTBridge.h>
#import <React/RCTRootView.h>

static id bridge = nil;

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  self.window.rootViewController = rootViewController;
  
  [self setupNative:launchOptions];

  [self.window makeKeyAndVisible];
  return YES;
}

- (void)setupNative:(NSDictionary*)launchOptions {
  NSURL *jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];
  bridge = [[RCTBridge alloc] initWithBundleURL:jsCodeLocation moduleProvider:nil launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge moduleName:@"memorytest" initialProperties:nil];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];
  self.window.rootViewController.view = rootView;
  
  __block id this = self;
  [NSTimer scheduledTimerWithTimeInterval:2 repeats:NO block:^(NSTimer * _Nonnull timer) {
    bridge = nil;
    [this setupNative:launchOptions];
  }];
}

@end
```

3) Watch memory usage go up
### Solution

I'm not exactly sure what the solution looks like. Ideally, setting `RCTRootView` to `nil` should reduce memory usage to where it was before instantiating the `RCTRootView`? It's also possible that there's another way of doing this and I'm just not aware of it. 

### Additional Information

* React Native version: 0.42.0
* Platform: iOS
* Operating System:MacOS
* Dev tools: Xcode

This issue could be related: https://github.com/facebook/react-native/issues/1487

**Comment by Jarred-Sumner** [comment]
It turns out that calling `invalidate` on the `RCTBridge` manually is the cause of this issue. Setting the `RCTBridge` instance to `nil`, instead, fixes it (in my implementation, I set the whole UIViewController containing the `RCTRootView`to `nil`). Calling `invalidate` twice on the `RCTBridge` maybe causes a retain cycle somewhere?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
