### ISSUE TITLE
text getting clipped with certain fonts

### ISSUE THREAD

**Issue by jcharbo** [facebook/react-native#12907]
Hi, I'm using RN 42 in an IOS simulator.  I'm using several google fonts (ttf files) and some of them get clipped and I don't know why.  Using the code below with the google font Pacifico it does what you see in the attached image.  Has anyone encountered this before?

thanks

`<View>
<Text style={{fontFamily:Fonts.type.pacifico,fontSize:44}}>jump</Text>
</View>`

![screen shot 2017-03-13 at 4 03 57 pm](https://cloud.githubusercontent.com/assets/6372919/23875232/b3d25636-0806-11e7-89ec-a21cfb90cc94.png)

**Comment by CatherineThompson** [comment]
Try adding padding to the text style. The text is kept in a rectangular view. When you use a font that slants, some of the text goes outside of the rectangular view and gets hidden. Padding will make the view larger.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
