### ISSUE TITLE
XHR does fire Progress events, but passes no progress information

### ISSUE THREAD

**Issue by GeoffreyPlitt** [facebook/react-native#12911]
### Description

I'm using RN=0.42 and trying to implement a progress-bar for a video upload. We're uploading using XHR, setting Content-Length and Content-Type, and seeing "progress" events fire, but the params sent to the event handler carry no information about progress (i.e. lengthComputable or something about bytes sent).

Our code is essentially this:

```
const upload = (uri) => {
  return new Promise((resolve, reject) => {
    const formdata = new FormData()
    formdata.append('file', {uri: `file://${uri}`, type: 'video/mp4', name: 'upload.mp4'})
    let xhr = new XMLHttpRequest()
    xhr.open('POST', upload_url)
    xhr.setRequestHeader('Content-Length', 10000)
    xhr.setRequestHeader('Content-Type', 'multipart/form-data')
    xhr.onload = resolve
    xhr.onerror = reject
    xhr.upload.addEventListener('progress', (e,a,b,c,d) => console.log('progress', e,a,b,c,d))
    xhr.send(formdata)
  })
})
```

### Reproduction

See above

### Solution

Hopefully someone can point out a parameter (HTTP header?) I'm missing, or perhaps there's a bug in the RN xhr implementation.

### Additional Information

* React Native version: 0.42
* Platform: iOS
* Operating System: Mac
* Dev tools: Atom

**Comment by GeoffreyPlitt** [comment]
Here's what the code above prints in our debugger; notice the a/b/c/d params are NULL.

![screenshot 2017-03-13 16 39 44](https://cloud.githubusercontent.com/assets/382821/23879682/c6e1ef34-080b-11e7-9060-e9cf75c5bc6d.png)

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by GeoffreyPlitt** [comment]
Yes, it should remain open, it never got fixed right?

**Comment by hramos** [comment]
I don't know about that. Are you still seeing this on 0.46?
