### ISSUE TITLE
Build issues caused by outdated compileSdkVersion on Android

### ISSUE THREAD

**Issue by ronocod** [facebook/react-native#12929]
### Description

The `build.gradle` files in the Android templates, sample apps and the ReactAndroid library seem to all use `compileSdkVersion 23`, which is quite an old version and causes build issues with the latest versions of the Android Support Library: https://github.com/tinycreative/react-native-intercom/pull/75, https://github.com/intercom/intercom-android/issues/316

`compileSdkVersion` should generally be set to the latest available stable version, using old versions can cause build issues with newer library versions.

### Reproduction

I've added a sample project here: https://github.com/ronocod/react-native-android-compile
The 1st commit to the repo was the code as generated by RN, the 2nd commit breaks the build by updating to Support Library 25.1.1.

### Solution

* `compileSdkVersion` fields in the `build.gradle` files for the Android templates, sample apps and the ReactAndroid library need to be updated to 25. 
  * Preferably `targetSdkVersion`, `buildToolsVersion` and the Support Library versions would be updated to the latest versions too.
  * I don't have much experience with Buck, but it looks like some of the Buck config files will need to be updated too.
* Documentation and CI setup scripts will need to be updated too as SDK version 25 will be needed, not 23.

I have a PR started here, it probably needs more work though: https://github.com/facebook/react-native/pull/12930
 
As far as I can see, existing React Native apps will have to be updated manually.

### Additional Information

* React Native version: February 2017
* Platform: Android
* Operating System: All
* Dev tools: Android SDK 25, Build Tools 25.0.2

**Comment by hramos** [comment]
Thanks for looking into this. This will also require some support from our team to make sure this does not break any internal tests. For the time being, 23 is the latest version that is officially supported.

**Comment by robclouth** [comment]
Note that the ART library will need to be updated: #13118

**Comment by afilp** [comment]
This issue causes problems to several packages that need version 25 (Intercom-Android being one of them). Can you consider this for change? Thanks!

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by giacomocerquone** [comment]
#16178
I have problem with the version of the sdk and the build tools, can this PR be merged in order to make it work please?
