### ISSUE TITLE
How to store images in Async Storage

### ISSUE THREAD

**Issue by swaroopa94** [facebook/react-native#12922]
Hi,

I am using Async Storage concept to store my data.

I am getting an uri of my image an I want to store that i mage in Async and show the image when i am in offline.
How can I do this.
Can anyone help me in solving this.

**Comment by rmevans9** [comment]
I would say base64 your image which gives a string and then store that. With that said this question would be better suited for Stack Overflow as this issue tracker is used for tracking bugs within React Native. Closing this.

**Comment by rmevans9** [comment]
@facebook-github-bot close

**Comment by hey99xx** [comment]
@rmevans9 looks like github bot did not do its job

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
