### ISSUE TITLE
saveToCameraRoll failed with `Permission denied` error on Android 

### ISSUE THREAD

**Issue by philjoseph** [facebook/react-native#12934]
### Description
saveToCameraRoll failed with `Permission denied` error on Android 
[FILL THIS OUT: Explain what you did, what you expected to happen, and what actually happens.]

### Reproduction
Saving a AWS S3 photo to the device Camera Roll suddenly failed
```
            RNFS.downloadFile(DownloadFileOptions)
                .promise
                .then(() => {
                     CameraRoll.saveToCameraRoll(path, this.state.type) // path = /data/user/0/com.XXX.app/filesimage-xyz.jpg"
                        .then((data) => {
                            RNFS.unlink(path)
                                .then(() => {
                                    console.log('Download and file unlink succeeded');
                                })
                                .catch((err) => {
                                    console.error("RNFS unlink error: ", err.message);
                                });
                            })
                        .catch((error) => { 
                            console.error("Save to Cameral roll  error: ",error.message); 
//error = code:"EUNSPECIFIED"
// framesToPop:1
// message:"Permission denied"
// stack:"Error: Permission denied↵  
                        });
                    })
                .catch((error) => {
                    console.error("RNFS.downloadFile! error: ", error.message);
                });
````

In the android/app/src/main/AndroidManifest.xml i have 
`    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />`
among few other permissions. 

What can cause a permission denied error ? what shall be done at the Manifest level to save to cameraRoll ? 

### Additional Information

* React Native version: [FILL THIS OUT: Does the bug reproduce on the latest RN release?]
Check with V41
* Platform: [FILL THIS OUT: iOS, Android, or both?]
Android inly
* Operating System: [FILL THIS OUT: MacOS, Linux, or Windows?]
Dev MacOS Sierra
* Dev tools: [FILL THIS OUT: Xcode or Android Studio version, iOS or Android SDK version, if applicable]
RN CLI + Android SDK

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

**Comment by philjoseph** [comment]
OK thanks for the quick reply

**Comment by rudyryk** [comment]
I believe this is not a question for Stack Overflow but more looks like documentation request. 

There is *Permissions* section on the [CameraRoll](https://facebook.github.io/react-native/docs/cameraroll.html) reference page. And in this section we can see only instructions for iOS but not for Android. This is misleading because we get false impression that we don't need to ask extra permissions for Android. And actually we need! Working code sample is provided on [Stack Overflow](https://stackoverflow.com/questions/42797443/react-native-savetocameraroll-failed-with-permission-denied-error-on-android) but it doesn't mean documentation should be totally silent about that.

**Comment by paranat9221** [comment]
I have same problem, who already solved this issue??
