### ISSUE TITLE
fetch API on Android doesn't respect credentials: omit

### ISSUE THREAD

**Issue by Ashoat** [facebook/react-native#12956]
### Description

If Android's native networking library detects valid cookies for a particular network request it will always tack those cookies onto the request, even if `credentials: "omit"` is passed to the fetch API.

This problem has been reported multiple times in #1274, which is an related issue that has been closed. I wanted to create a new issue to track it.

This problem makes it very difficult to fully encapsulate cookie logic within Javascript, and necessitates interacting directly with native cookie storage with something like `react-native-cookies`. This is unfortunate, as there is no particular reason that cookies ought to be handled natively, and outside of this problem it is possible to handle cookies entirely in Javascript.

### Reproduction

1. First, get a cookie set on the client by hitting a server endpoint that returns a `Set-Cookie` header.
2. On Android,
```javascript
await fetch(
  credentials: 'omit',
  ...
);
```
3. Add some logging code on the server to see if a `Cookie` header is set by client. Confirm that this is happening.

### Solution

React Native on Android should respect the `credentials: 'omit'` option.

### Additional Information

* React Native version: 42
* Platform: Android only
* Operating System: macOS

**Comment by jtmarmon** [comment]
as far as I can tell this is an issue on iOS as well

**Comment by vijayst** [comment]
I am facing the same issue. Using credentials: 'omit' on Android fetch does not work.

**Comment by jtmarmon** [comment]
for anyone looking for a workaround, since i didn't need cookies at all, i just cleared cookies before each request using https://github.com/joeferraro/react-native-cookies

**Comment by yabeow** [comment]
There is a commit that supposed to be solved this issue, but it not working for me. Any idea?
https://github.com/github/fetch/commit/c389ccd8321a20bf6e713e10e82503a896de1f14

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by kadzier** [comment]
Just ran into this exact issue.  Currently using https://www.npmjs.com/package/react-native-cookie as a workaround; simply clearing the cookies before each request.

**Comment by GetSource1234** [comment]
Spotted the same issue, would be great to have a proper fix.

**Comment by 2DKot** [comment]
If you are using Expo, you can't run `react-native link` to use react-native-cookie.
But you can clear cookies this way:
```javascript
var RCTNetworking = require('RCTNetworking')
function clearCookies () {
  RCTNetworking.clearCookies((cleared) => {
    console.log('Cookies cleared, had cookies=' + cleared.toString())
  })
}
```

**Comment by nicksyndicate** [comment]
would be great if it will be worked as in specification
