### ISSUE TITLE
Could not find a valid GoogleService-Info.plist

### ISSUE THREAD

**Issue by yolosaucisson** [facebook/react-native#12957]
## Description
I installed Firebase/Messaging thanks to Pod.
So I add "pod 'Firebase/Messaging'" in my Podfile.
But everytime I build and run my app on my phone. I have an error that's in the title so the app stops running instantly.

I followed the tutorial and add my certs to the GoogleService-Info.plist file before downloaded it.
I added my plist file in the ios folder and in ios/my-app-name folder to try but always the same problem.

If someone can help me.
Thanks! 

## Device

RN: 0.42
Running on iOS 5S
App can't run

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
