### ISSUE TITLE
iOS geolocation watchPosition Incorrect

### ISSUE THREAD

**Issue by himanshu266** [facebook/react-native#12967]
### Description

Watch location of user on iOS seems to not be using GPS. The accuracy never goes below 65 and the speed is negative, which seems like that the GPS is not kicking in. It works just fine for Android. Also, navigator.geolocation works just fine in the browser with accurate speed and accuracy. (https://codepen.io/himanshu/full/bqoEQN/)

### Reproduction

Reproduced in Expo. (https://sketch.expo.io/S15lAdDsx)

### Solution

React native needs to respect the enableHighAccuracy and distanceFilter flags and return the proper accurate location.

### Additional Information

* React Native version: 0.42
* Platform: iOS
* Operating System: Mac & Test on Device
* Dev tools: xCode

**Comment by mbokowy** [comment]
I've the same problem. How to fix it?

**Comment by jcharlet** [comment]
Hi,
same get negative value for speed and weird coordinates/timestamp. very critical to me since I started implementing an app which works fine on android and am porting it to ios now (to deliver in may).
any workaround ? any visibility on a fix ? are we supposed to vote this up on some other platform than github?


    "react": "15.4.2",
    "react-native": "0.42.3",
platform ios 10.3

thx,
Jeremie

**Comment by jcharlet** [comment]
hi @himanshu266 @mbokowy did you guys find a workaround?

**Comment by himanshu266** [comment]
@jcharlet Yes, I changed this default value to 0. This works for me because I wanted constant updates. You may have a different case.

https://github.com/facebook/react-native/blob/master/Libraries/Geolocation/RCTLocationObserver.m#L28

**Comment by plougsgaard** [comment]
@himanshu266 Let me know if I understand you correctly - you hardcoded the `RCT_DEFAULT_LOCATION_ACCURACY` value to `0.0` inside the `RCTLocationObserver.m` file? And this prevents iOS from just using the network location?

**Comment by himanshu266** [comment]
As the name describes, it's the location accuracy. When you set it to 0, every single time the phone moves, even a bit, new location gets updated. Otherwise it was set to 100 meters, which is pretty big gap.

**Comment by plougsgaard** [comment]
@himanshu266 True, though that should be possible to do with the `distanceFilter` prop too, right? For me the issue isn't that it doesn't update often, it's just that it's very inaccurate because it doesn't seem to use the actual GPS (not an issue on Android).

**Comment by himanshu266** [comment]
Yes, the distanceFilter should work, but if you look lower down in the file you will notice they are doing the math and resetting it back to the default. Hence my fast easy fix for my application was to set the default to 0.

**Comment by plougsgaard** [comment]
I'll try that then, thanks for explaining.

**Comment by jcharlet** [comment]
sorry to ask such a trivial question (am new to the node world): how do you patch a file from a node_modules package ? 

Do I have to replace the value directly in that ./myApp/node_modules/react-native/Libraries/Geolocation/RCTLocationObserver.m (while node_modules is ignored by git and overridden at any npm install). Is there a cleaner way so that it's not in node_modules and in my git codebase?

I cannot monkey patch since it's not a js file..

**Comment by plougsgaard** [comment]
@jcharlet I can confirm that changing the value in the library under `node_modules` does work! 

I think the only real solution is to actually fix the underlying bug in react-native itself 🙂

**Comment by jcharlet** [comment]
thx @plougsgaard !

**Comment by Mellemel** [comment]
Any solution towards improving the accuracy/speed/heading that returns from the geolocation api?

**Comment by clementcontet** [comment]
@himanshu266 thanks for the fix.
But I would rather set `RCT_DEFAULT_LOCATION_ACCURACY`  to `kCLLocationAccuracyBest` instead of `0.0` because the value of these "accuracy constants" are not documented by Apple and may change (if `kCLLocationAccuracyBest` is `0.0`, what is 
`kCLLocationAccuracyBestForNavigation`?)

Back to the root cause, I don't get why this `desiredAccuracy` is changed after we succeed or fail to get a position?

See:
- https://github.com/facebook/react-native/blob/master/Libraries/Geolocation/RCTLocationObserver.m#L312&L316
- https://github.com/facebook/react-native/blob/master/Libraries/Geolocation/RCTLocationObserver.m#L348&L352

And why compare the difference `ABS(_locationManager.desiredAccuracy - RCT_DEFAULT_LOCATION_ACCURACY)` to `0.000001`?? (again, we have no idea how Apple implemented their accuracy constants)

**Comment by Jhonte** [comment]
Wow thanks this was driving my nuts...  Had tried all kinds of combinations and had really weird behavior with watchPosition where the marker sometimes went going 1 km in a straight direction...

The constants are explained here for example https://developer.apple.com/documentation/corelocation/kcllocationaccuracybest (the better accuracy the more battery drain).

Guess it maybe is valid to reset this on a fail, 
https://github.com/facebook/react-native/blob/master/Libraries/Geolocation/RCTLocationObserver.m#L319-L353

But also works to reset it while only fetching one position...  but should not be reset when watching the position.

**Comment by mo22** [comment]
at least the iOS code seems to check for options.accuracy, which is not documented. please try navigator.geolocation.watchPosition(..., ..., { accuracy: 0 });

**Comment by urikphytech** [comment]
Did anyone find a good solution for this? I'm using RN 0.42 and the app isn't using my GPS location. The accuracy is stuck on 65m, but when running Google Maps in the background I get 10m. 
@jcharlet @mo22 @Mellemel

**Comment by likealcohol** [comment]
I'm running expo with react-native, when I make the changes to the corresponding files in react-native/Libraries/Geolocation folder how to I recompile it, because right now I'm just getting a constant accuracy of 65 on iOS and it's doing my head in!
