### ISSUE TITLE
undefined is not a constructor (evaluating 'new window.WebSocket') in setupDevtools.js file

### ISSUE THREAD

**Issue by konstantin-mohin** [facebook/react-native#12971]
# Description

I started getting this error: "undefined is not a constructor (evaluating 'new window.WebSocket('ws://' + hostname+':'+port+'/devtools')')" , it points to the setupDevtools.js:25 file. 

Im using a real android device and if I turn on Debug JS Remotely option the issue disappears.

# Reproduction

Can provide access to the project if needed.

# Additional Information
- React Native version: 0.39.0
- Platform: Android
- Operating System: MacOS

**Comment by ohwhen** [comment]
Ran into the same error, try using:

`import { WebSocketModule } from 'react-native'`

**Comment by konstantin-mohin** [comment]
hi friends, 

I did nothing (except that I've installed several libraries), just continued to develop and now the error has changed (see the attached screen ). I want to again emphasize that the error only occurs when the Remote JS Debugger is turned off.

![screenshot_20170323-194310](https://cloud.githubusercontent.com/assets/14233139/24262416/9ad77216-1002-11e7-889b-a1a067e61cc0.png)

**Comment by Selman555** [comment]
Hi Konstantin,
I'm experiencing the same issues over several projects (about the WebSocket).
The websocket error appears after a second or two and doesn't break the app

I'm guessing the second error you are seeing (about undefined) has nothing to do with the WebSocket. It's got to be just an error that appears first and breaks further execution. That's probably why the WebSocket error doesn't show.
Are you trying to convert an object to json `JSON.stringify` or vica versa using `JSON.parse`? Might be that the variable itself is undefined.

**Comment by konstantin-mohin** [comment]
@Selman555 
hey thanks,

>  Are you trying to convert an object to json
No, I'm not.

I decided to upgrade a hole project to new version of React,
and it solves the issue.

**Comment by Selman555** [comment]
Lucky you, I'm already on the latest version and I'm still having this issue

**Comment by rbermudezg** [comment]
@Selman555 The window.WebSocket is undefined exception usually happens when window global variable has been overwritten.  I hope this can help you.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
