### ISSUE TITLE
Weird 3d transform behavior on Android

### ISSUE THREAD

**Issue by timolins** [facebook/react-native#12972]
### Description

Weird 3d transform behavior on Android.

[This example](https://medium.com/@youngchanje/implementing-cube-in-react-native-cb61b9a7e8c3) should look like this:

![iOS](https://i.imgur.com/9LETFEY.png)

but it looks like this on Android:

![Android](https://i.imgur.com/vvtNUZw.png)

### Reproduction

https://sketch.expo.io/SylzHeuig (iOS isn't fully working too in this example, but it's clearly a different behavior than Android)

### Additional Information

* React Native version: Tried on 0.41.2 and 0.42.0
* Platform: Android
* Operating System: macOS
* Dev tools: Tried Expo and vanilla Xcode

**Comment by nihgwu** [comment]
have test on RN0.43? included a commit which fixes transform.skew on Android

**Comment by hramos** [comment]
Thanks for providing a repro with Sketch, this is very helpful! As of this writing, Sketch is using 0.41 so at least we know this issue occurs on that version.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
