### ISSUE TITLE
Can't Specify Transformer Options when Bundling

### ISSUE THREAD

**Issue by madilks** [facebook/react-native#12982]
### Description

When using the bundle command from the CLI, it is impossible to specify transformer options. 

According to the [documentation](https://github.com/facebook/react-native/tree/master/packager), you should be able to specify a config file with a key `getTransformerOptions` that contains a function that will later return the transformer options. 

The provided file is parsed and read in by the bundle code, but the function stored in `getTransformerOptions` is never called. Instead, inside the definition for the Bundler class the options for the transformer are [hardcoded](https://github.com/facebook/react-native/blob/master/packager/src/Bundler/index.js#L171).

Some context:

When bundling my application, sometimes the transformer will fail with the following [message](https://github.com/facebook/react-native/blob/master/packager/src/JSTransformer/index.js#L101),

I've tried troubleshooting this failure elsewhere but nothing seems to have an impact. I decided to try upping the timeout interval, in case it actually was an issue with the work taking too long. Unfortunately, there is not currently a way to adjust the timeout via the `transformTimeoutInterval` option.

### Reproduction

1. Notice that the `transformTimeoutInterval` is hardcoded [here](https://github.com/facebook/react-native/blob/master/packager/src/JSTransformer/index.js#L75).

Alternatively, if you want to run the related code:

1. Navigate to your project directory
2. Run the following: `node node_modules/react-native/local-cli/cli.js bundle --platform android --entry-file index.android.js --bundle-output [your-bundle-output]`

### Solution

The [Transformer](https://github.com/facebook/react-native/blob/master/packager/src/JSTransformer/index.js) should be updated to accept options specified via `getTransformerOptions` in the initially supplied config file. Additionally, an example config file should be provided to demonstrate its usage.

If this option is intended to be deprecated, the error [message](https://github.com/facebook/react-native/blob/master/packager/src/JSTransformer/index.js#L101) should be updated to stop referring to `transformTimeoutInterval` and the [README.md](https://github.com/facebook/react-native/blob/master/packager/README.md) for the Packager should be updated to stop referring to `getTransformerOptions`.

### Additional Information

* React Native version: 0.40.0 (still hardcoded on latest)
* Platform: n/a
* Operating System: Windows
* Dev tools: npm script run from command line

**Comment by madilks** [comment]
Is there a known work-around for this timeout issue?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
