### ISSUE TITLE
SAMSUNG s6 keyboard without decimal point 

### ISSUE THREAD

**Issue by Rice-M** [facebook/react-native#12988]
### Description

with SAMSUNG s6 TextInput and keyboardType is numeric the decimal point don't see in the keyboard and this only happen in real device

### Reproduction

https://sketch.expo.io/SJtCVpdsg

### Additional Information

React Native version: 0.38
Platform: Android SAMSUNG S6
Operating System: MacOS
Dev tools: MacOS

**Comment by antoinerousseau** [comment]
I can confirm that my `TextInput` with `keyboardType="numeric"` is broken on Samsung Galaxy core prime (Android 5.1.1): the decimal separator is disabled, my users can't input decimal numbers :/

**Comment by xwartz** [comment]
I have fund some iPhone devices also have the same issue. The decimal point becomes a comma.

**Comment by Rice-M** [comment]
@antoinerousseau I change keyboardType="numeric" to default , how did you solve it

**Comment by antoinerousseau** [comment]
I didn't solve it yet, any solution around here?

**Comment by Rice-M** [comment]
Have no idea, but I found that if the phone install other input software, it will be right, so I think maybe it's the SAMSUNG system's bug.

**Comment by antoinerousseau** [comment]
Yes my user solved it by installing the Google Keyboard, but it doesn't solve this bug (that could indeed be Samsung's)

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by kallrobin** [comment]
Hi,
We have also encountered the same issue, and we fixed it by removing `autoCapitalize="none"` from the TextInput component. Hope this helps.

**Comment by antoinerousseau** [comment]
thanks @kallrobin !

**Comment by yenda** [comment]
@kallrobin solutions works on our project too

**Comment by RituKhetan** [comment]
Hi,

I could see the same error on my HTC device.
My TextInput component looks like this:
<TextInput style={styles.input} 
          value={this.state.inputValue} 
          keyboardType="numeric"
          placeholder = "0.00"
          onChangeText = {text => this.setState({inputValue: text})}/>

I cannot see the decimal key on the keyboard on my device.

Can anyone please help?

[I don't have this property autoCapitalize="none" and I still get this error]

**Comment by WaqarShahid147** [comment]
Hi,

I used following keyboartType to include comma in text area:

keyboardType="numbers-and-punctuation"

The result of this is attached.
https://drive.google.com/file/d/18m7lXhbYwjQypLXA1RLGP2sWPG-ZFaUc/view?usp=sharing

**Comment by yangga** [comment]
@WaqarShahid147 

keyboardType="numbers-and-punctuation" shows unnecessary characters. (actually, what i really want is shows only number + decimal point)
I should use your solution, cause it looks there is no good way to solve this perfectly.

thanks, @WaqarShahid147

**Comment by csumrell** [comment]
I have users who also reported this happening on the RN 0.53, one user said they use a LG V20 and the other a Note 4

**Comment by aMarCruz** [comment]
@kallrobin , inputs with `keyboardType="numeric"` was showing default keyboard w/ autoFocus in Androids (6 & 7) , your trick solves the issue! :)

**Comment by joshuapinter** [comment]
@kallrobin We actually had to add `autoCapitalize="none"` in order for the decimal option to show up on the real Samsung device keyboard.

**Comment by vendramini** [comment]
Finally it works here, I'd to add `autoCapitalize: 'words'` for god knows reason.

Tablet Samsung Galaxy Tab E SM-T560.
