### ISSUE TITLE
Geolocation timed out, code 3

### ISSUE THREAD

**Issue by avdept** [facebook/react-native#12996]
### Description

I have geolocation running in my app, followed examples described in docs. IOS version works fine, android however works only on non xiaomi devices. I tried on 2 xiamomi devices, and got `Location request timed out` error. While on samsung devices it works fine.

### Reproduction

```
navigator.geolocation.getCurrentPosition(
            (position) => {
                let initialPosition = JSON.stringify(position);
                console.log(initialPosition);
            },
            (error) => console.log(JSON.stringify(error)),
            {enableHighAccuracy: Platform.OS != 'android', timeout: 2000, maximumAge: 2000 }
        );
```
### Solution

Need to find a way either provide reason why timed out, or just fix it.

### Additional Information

* React Native version: 0.42
* Platform: Android
* Operating System: Mac OS
* Dev tools: Android SDK v23

**Comment by booboothefool** [comment]
Need to check permissions:

Use https://github.com/lucasferreira/react-native-android-permissions or https://facebook.github.io/react-native/docs/permissionsandroid.html.

**Comment by brunolemos** [comment]
Duplicated of #7495

**Comment by pewh** [comment]
Have same issue, too. Check permission is not enough. See my answer at https://github.com/facebook/react-native/issues/7495#issuecomment-287793663

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by nicotroia** [comment]
For anyone else struggling with this issue on android, try removing the `maximumAge: 2000` option parameter. This option was causing geolocation to either timeout or crash the app.

I'm running react-native 0.46.4 btw.

**Comment by yagneshmodh** [comment]
I am also struggling for the same issue. let me know if anybody have solution for this.

I am using RN 0.48

**Comment by cristisavaintelligentbee** [comment]
Has anybody find a solution for this ?

**Comment by kelset** [comment]
Duplicate #7495

**Comment by milon87** [comment]
when working with map:
1. Set permission if you build app with SDK >23 (android)
2. if enableHighAccuracy is on, in that case, check if your phone is Enabled.

**Comment by ajRiverav** [comment]
For those of you who still are experimenting this issue, I was able to solve it by omitting the parameter _maxAge_, e.g.  {enableHighAccuracy: true, timeout: 5000}). 

At least I can confirm this with API level 23 and RN 0.51. I also used had
```
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
```
in the AndroidManifest.xml file. 

About not using _maxAge_, somebody created a pull request and mentions an issue with it ([https://github.com/Clintal/react-native-picker/commit/320003e1dbf6ac03798b9f6842eaa4f1bf77c4eb](https://github.com/Clintal/react-native-picker/commit/320003e1dbf6ac03798b9f6842eaa4f1bf77c4eb))

**Comment by digvijayMobantica** [comment]
{ enableHighAccuracy: false, timeout: 20000, maximumAge: 1000 },

> Make "enableHighAccuracy: false" works for me

**Comment by SirPhemmiey** [comment]
Guys....removing `maximumAge` solved the problem

**Comment by SirPhemmiey** [comment]
@digvijayMobantica , setting `enableHighAccuracy: false` is strongly not encouraged

**Comment by mag1492** [comment]
You can verify the permission before calling getCurrentPosition
```
 if (Platform.OS === 'android') {
      const granted = await PermissionsAndroid.check(PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION);
      if (!granted) {
        return;
      }
    }
...
```
