### ISSUE TITLE
react-native run-ios does not pass environment variables to the packager

### ISSUE THREAD

**Issue by j2kun** [facebook/react-native#13005]
### Description

When you run `react-native run-ios`, and it launches the packager in a separate window, no environment variables from the context session are passed to the packager process.

This breaks any babel plugins that use `process.env`. 

### Reproduction

Clone https://github.com/j2kun/react-native-run-ios-env-bug
`npm install` or `yarn install`

Run

```
export CUSTOM_ENV=1234
react-native run-ios
```

Observe that the env-var is not displayed on the simulator. Optionally add a logging statement to `node_modules/babel-plugin-react-native-config/index.js` to show that the packager thinks `process.env['CUSTOM_ENV']` is `nil`.

Clear the react packager cache (or modify index.ios.js in any way). Run

```
export CUSTOM_ENV=1234
npm start&
react-native run-ios
```

Observe that the app now displays 1234.

### Solution

The current workaround is to manually start the packager in the parent session. It's not so bad, but I consider it a bug in the react-native cli.

### Additional Information

* React Native version: 0.41.2
* Platform: iOS
* Operating System: MacOS Sierra

**Comment by wwwdata** [comment]
@j2kun can you tell me more about your workaround? The only enviornment variable I get in react-native 0.42.2 is the `NODE_ENV` and nothing else. Even if I start the packager manually in my terminal where other ENV variables are set.

**Comment by j2kun** [comment]
@wwwdata I am not entirely sure why there's a difference. 

This came up in the context of hot-swapping environment variables. I worked on this for a while and came up with this [this](http://stackoverflow.com/a/42497592/438830) watchman solution coupled with a custom [babel plugin](https://github.com/j2kun/babel-plugin-react-native-config), which does indeed read from the containing process (eg. [here](https://github.com/j2kun/babel-plugin-react-native-config/blob/master/index.js#L47)).

This may be a shell difference? I'm using zsh. Maybe also a RN version difference?

**Comment by wwwdata** [comment]
Ok, what helped in my case was adding and using this babel plugin:

```json
"babel-plugin-transform-inline-environment-variables": "^6.8.0"
```

After that when resetting the cache and starting with the react native packager, the environment variables were there. If somebody else also runs into that issue. I think the problem was some dead code optimisation by UglifyJS or something weird like that was killing the env variables.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
