### ISSUE TITLE
android:windowSoftInputMode="adjustResize" will not work when StatusBar hidden="true" Android

### ISSUE THREAD

**Issue by CodeXtinction** [facebook/react-native#13000]
Ill provide more info about this issue  #12980

android:windowSoftInputMode="adjustResize" at android/app/src/main/AndroidManifiest.xml  (by default in the lastest version) prevent the content collapses out of the screen when keyboard appears and works well, but here the problem, if you want to hide the StatusBar then adjustResize will not work, content collapses and if you have a ScrollView and many TextInputs you have to hide the keyboard in order to navigate to the next input.

How to reproduce?
here i opened a repo with an example, the main code is in App.js
https://github.com/CodeXtinction/bug-react-native

gif example.
when Statusbar hidden prop is set false, will work well

![alt tag](https://media.giphy.com/media/l0Iy0YYaosV6V1zyM/giphy.gif)

but then this happen when hidden={true}

![alt tag](https://media.giphy.com/media/3o7btQTfZTUGIlGSBO/giphy.gif)

im on Android 6.0
you will find the code and package.json in the repo example provided.

**Comment by ahjsrhj** [comment]
I think this is a bug of Android, you can get more info from [here](https://code.google.com/p/android/issues/detail?id=5497) or [here](http://stackoverflow.com/a/19494006).

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by alizbazar** [comment]
This issue is still occurring for me at least on Android 6.0 and rn48. This was a true mystery bug! I would never would have thought these two things - status bar and window resizing on keyboard - to be somehow related.

**Proposed fix:**
A note could be added to react-native StatusBar documentation that such issue might exist - especially since _android:windowSoftInputMode="adjustResize"_ is a default setting in the latest RN release.

**Comment by shahchaitanya** [comment]
This issue is still occurring for me with latest react native 0.53. A problem occurred while hiding status bar and using android:windowSoftInputMode="adjustResize" property. You should reopen the issue and fix it.

**Comment by terryttsai** [comment]
^ I am also having the same issue as @shahchaitanya

**Comment by evanjmg** [comment]
There is a workaround here -  https://stackoverflow.com/questions/7417123/android-how-to-adjust-layout-in-full-screen-mode-when-softkeyboard-is-visible/19494006#19494006

**Comment by bm-software** [comment]
@reyalpsirc Thanky you for sharing! Your workaround works ;)
