### ISSUE TITLE
Android Modal style issues Samsung Galaxy S5/S6

### ISSUE THREAD

**Issue by arsenslyusarchuk** [facebook/react-native#13035]
### Description

I've faced really strange issue happening on Samsung devices (Galaxy S6/S7 Android 6.0.1, other not tested) ONLY. 
I'm using react-native Modal components in the app, and each component has a button at the bottom of the page (to confirm some action). This button has style `flex: 1` applied to it with parent container styles as: `justifyContent:"space-between"`. So the button is placed at the very bottom of the screen.
On every platform it works great, except Samsung devices, starting from SECOND application run. I mean, that for the first time it renders correctly, but after u close the app (delete from running processes) and run it again -- the button just disappears. 
Again, it's not happening neither on IOS nor on any other Android device (for sure, emulators too). This issue doesn't exist for a regular pages, only for Modal ones. I suspect that this may be a mix of Modal component bugs and Samsung devices, providing their custom launcher.

### Reproduction 

Currently I'm using `react-native: 0.35.0` and tried to upgrade to `0.36, 0.37, 0.38` -- none of those fixes the issue. Because of large project, lots of deps and strict timeframe I cannot upgrade to `>=0.39` as it causes too many issues.
Playing with styles also doesn't give me any effect, until I place this button to be NOT the last element inside the container View, which doesn't suit to my needs, as it should be at the very bottom of the page

Please help me to resolve this issue.
Thanks.

### Additional Information

* React Native version: 0.35, 0.36, 0.37, 0.38
* Platform: Android
* Operating System: MacOS
* Dev tools: Android Studio 2.2.2

**Comment by mikaalanwar** [comment]
Hey there! Can you kindly share the relevant code snippet / source code, so that I'd be able to reproduce the issue easily?

**Comment by arsenslyusarchuk** [comment]
@mikaalanwar Just use React-Native Modal with code inside like this and test it on samsung S6/S7 devices, rerunning app for couple of times (delete from memory and open):

```
<View style={{flex:1, justifyContent:"space-between"}}>
  <View style={{flex:1}}>
    <Text>Hello World</Text>
  </View>
  <Button style={{height: 44, flex: 1}}>
    <Text>Next</Text>
  </Button>
</View>
```

I've managed to fix this issue by using custom animated views instead of modals. But that's not the way it should work

**Comment by rgngl** [comment]
When it breaks can you do a `adb shell dumpsys SurfaceFlinger`? There should be some lines towards the end like this:
```
Hardware Composer state (version 01020000):
  mDebugForceFakeVSync=0
  Display[0] configurations (* current):
    * 0: 1200x1920, xdpi=320.842010, ydpi=322.966003, refresh=16666667, colorTransform=0
  numHwLayers=5, flags=00000000
    type   |  handle  | hint | flag | tr | blnd |   format    |     source crop (l,t,r,b)      |          frame         | name 
-----------+----------+------+------+----+------+-------------+--------------------------------+------------------------+------
       HWC | b339a820 | 0002 | 0000 | 00 | 0100 | RGB_888     |      0,      0,   1200,   1920 |    0,    0, 1200, 1920 | com.android.systemui.ImageWallpaper
       HWC | b6796550 | 0002 | 0000 | 00 | 0105 | RGBA_8888   |      0,      0,   1200,   1920 |    0,    0, 1200, 1920 | com.google.android.googlequicksearchbox/com.google.android.launcher.GEL
       HWC | b6796410 | 0002 | 0000 | 00 | 0105 | RGBA_8888   |      0,      0,   1200,     48 |    0,    0, 1200,   48 | StatusBar
       HWC | b339a550 | 0002 | 0000 | 00 | 0105 | RGBA_8888   |      0,      0,   1200,     96 |    0, 1824, 1200, 1920 | NavigationBar
 FB TARGET | b6b0fb90 | 0000 | 0000 | 00 | 0105 | RGBA_8888   |      0,      0,   1200,   1920 |    0,    0, 1200, 1920 | HWC_FRAMEBUFFER_TARGET
```
Can you see if the `source crop` and the `frame` fields for your app's windows are different? If it's like that I might have a fix for that. See https://github.com/facebook/react-native/pull/13411

**Comment by arsenslyusarchuk** [comment]
@rgngl Hello. After upgrade of Samsung devices to android 7, this bug disappeared. So, it definitely was an issue with the particular touchwiz version which is used on Android 6.0.1, because for devices with pure 6.0.1 no bug was noticed.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by arsenslyusarchuk** [comment]
@hramos Hello. This issue disappeared after system update on Samsung Galaxy S5/S6
