### ISSUE TITLE
Support swift libraries linkage with `react-native link`

### ISSUE THREAD

**Issue by Kureev** [facebook/react-native#13030]
**Motivation:**
Currently, `react-native link` supports only Objective-C libraries. Therefore, some great libraries (like native-navigation) can't be linked with it. I'd like to make a proposal for supporting Swift modules in `react-native link`.

**Linkage process for Swift modules:**
First of all, we need to detect a type of module we want to link. One of the approaches we can take there is to check `package.json` for a special flag (`"isSwiftModule": true`? `false` by default) in `rnpm` section. If flag is set to `true`, use a special linkage process described below.

Swift modules for React Native will always depends on React. As far as React is implemented in Objective-C, we need to add a `<ProjectName>-Bridging-Header.h` if it doesn't exist yet (this file contains Objective-C headers, required by the Swift module). Module developer can specify required headers in the `rnpm` section of his package.json.
Once file is composed / patched, Swift modules needs to be added to the project. My current assumption is that we can re-use logic we have in place for Objective-C modules (right, @grabbou?).
Theoretically, it should be it for most of react-native modules.

wdyt, @grabbou?

**Comment by grabbou** [comment]
I think it's a great idea. I was talking about it with @leland briefly at React Conf and we were meant to follow up on this.

**Comment by Kureev** [comment]
Yeah, my main motivation is to make `react-native link` compatible with `native-navigation`, although I think it'll be useful for lots of developers out there. 

I'll make a PR and let you know.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by vaxxis** [comment]
Hi guys, any update on this matter?
