### ISSUE TITLE
Flatlist example in the docs not rendering

### ISSUE THREAD

**Issue by huyanhh** [facebook/react-native#13037]
### Description

On the documentation for Flatlist, I tried running the example in the browser. I then got an error on the simulator saying "FlatListExample could not be found!"

### Reproduction

[Link to docs](https://facebook.github.io/react-native/releases/next/docs/flatlist.html)

I go onto the docs, and click "Run this example" near the bottom.

### Solution

The documentation for that page needs to be updated with the latest repository.

### Additional Information

* React Native version: 0.43.0
* Platform: Documentation, Google Chrome
* Operating System: MacOS
* Dev tools: None

**Comment by ragnorc** [comment]
#13053

**Comment by ragnorc** [comment]
#13053

**Comment by ragnorc** [comment]
#13053

**Comment by ragnorc** [comment]
#13045

**Comment by hramos** [comment]
I think this is actually affecting more than just FlatList. Other examples are not rendering. RNPlay is going away at the end of the month, so we'll need to either migrate the examples to run in [Sketch](http://sketch.expo.io), or remove the prompt entirely.

**Comment by hramos** [comment]
I took a further look at this. So there's two different types of runnable examples that display in a modal:

1. One-off examples linked from the markdown docs (e.g. https://facebook.github.io/react-native/docs/direct-manipulation.html), which is something someone uploaded to RNPlay long ago - and in some cases, the example no longer exists. In the case of Direct Manipulation, the example was created before RNPlay switched to Expo, and has been disabled: https://rnplay.org/apps/JXkgmQ

2. Then there's the examples in the API docs (such as StatusBar) where we use one of two UIExplorer apps uploaded to appetize.org around two years ago (iOS and Android), and pass along some params to load the correct example. This is why FlatList fails to load in this case, because the UIExplorer app being used here hasn't been updated in some time and does not contain FlatList.

For #1, we can migrate these examples to Sketch. 

For #2, we can update the app on appetize to use a more up to date version of UIExplorer, but we would also need to make this more resilient as the issue will show up again when a new component is added to UIExplorer. Not to say, the examples are likely to get out of sync as the UIExplorer app gets updated in the repo.

**Comment by hramos** [comment]
#1 has been resolved on master, and https://github.com/facebook/react-native/pull/13644 takes care of #2.
