### ISSUE TITLE
cannot open demo in real iphone 6s ios10.2.1

### ISSUE THREAD

**Issue by zhaozy93** [facebook/react-native#13043]
using react-native-cli@2.0.1 create one project named ios4. and then build and run in Xcode on my real iphone 6s ios 10.2.1 and see the ios4 appIcon on my screen.
![wechatimg113](https://cloud.githubusercontent.com/assets/15324670/24131591/7e970e88-0e2a-11e7-93d9-861d14f7e4e6.jpeg)

 however when i open the ios4 app, i will struck on the startup page.
![wechatimg114](https://cloud.githubusercontent.com/assets/15324670/24131592/83a12a4e-0e2a-11e7-8a1c-7106db77dc9b.jpeg)
then about 30s, the ios4 app was crashed.
and i try open it again, this time the app will be opened. like the below img.
![wechatimg115](https://cloud.githubusercontent.com/assets/15324670/24131622/b8e53646-0e2a-11e7-951d-16e6d3e0d0b0.jpeg)

unfortunately, this is a circle. crashed one time, open one time, crashed one time, open one time......

does anyone know this problem or also encounter this problem.

thank you

**Comment by hramos** [comment]
Do you see any errors in the terminal?

**Comment by zhaozy93** [comment]
Sorry, long time not to login github. 
Cannot see any error in terminal. 
but i switch the debug model from yes to no in Dead Code Stripping in Build Settings in Xcode, then the app runs normal in real devices including iPhone 5s with ios10, iPhone 5 with iOS 8,  iPhone 6s with 10.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
