### ISSUE TITLE
Error after upgrade to 0.42.3

### ISSUE THREAD

**Issue by Taakn** [facebook/react-native#13053]
### Description

error after upgrading to latest version of RN. I cannot run my project anymore. I am getting:

node_modules/react-native/packager/src/Bundler/index.js: Unexpected token, expected , (47:26)
  45 |   mainModuleName: string,
  46 |   options: {},
> 47 |   getDependencies: string => Promise<Array<string>>,
     |                           ^
  48 | ) => {} | Promise<{}>;

### Reproduction

run react-native-git-upgrade

### Additional Information

* React Native version: 0.42.3
* Platform: both
* Operating System: MacOS
* Dev tools: Atom, XCode

**Comment by Taakn** [comment]
I couldn't get it working, so I went back to 0.39.2 (0.39.0 wasn't working either). I'm leaving the issue open, but since I moved on from that version I cannot comment on whether or not this is fixed. If you feel that this issue should be closed, please do so.

**Comment by tinajohnson** [comment]
This helped me - https://github.com/yarnpkg/yarn/issues/2696#issuecomment-282239215

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
