### ISSUE TITLE
White screen when opening React Native from existing app

### ISSUE THREAD

**Issue by Pedneri1** [facebook/react-native#13091]
### Description

I am integrating react native to an existing app, it already works by following the docs. But there is a problem, every time I click the button that opens the RN activity/view controller, it takes 2 or 3 seconds in a white screen (loading the bundle). Is there any way to pre load this bundle and avoid this white screen ?

### Reproduction

1. Integrate any existing app with React Native
2. Open the RN screen and check, there is a 2, 3 seconds white screen

### Additional Information

* React Native version: 0.40.0
* Platform: Both
* Development Operating System: MacOS
* Dev tools: XCode, Android Studio

**Comment by JeffreyLeeSpokeo** [comment]
@Pedneri1 I have the same problem. Did you get an answer for this? I thought it was happening only because I was in development and RN has been slow for me in development. However, I tried a production build and white the white screen flash is less, it's still like 3 seconds.

**Comment by sgong-gzy** [comment]
Running into same problem. Any updates on this? Any help is highly appreciated!

**Comment by JeffreyLeeSpokeo** [comment]
@sgong-gzy So I did find a type of solution for it, not sure if it will work for you though. Basically my android app was originally developed in java. From the java side, I click on something to go to another screen that is using React Native. When I first start the app and load my first screen (in java), I build my ReactInstanceManager then I call createReactContextInBackground() on that build. 

If you notice in development, you see it bundle the JS. Originally what I was doing was that every time I go to my React Native screen, I re-bundled my JS. Every time I clicked to go to my React Native screen, I would start a new activity and the onCreate, I would build a new ReactInstanceManager and start the activity. This is what caused the bundling every single time.

My solution in my first paragraph allowed me to create the instance and do the bundling before I even get to the startReactApplication since it's done on a different screen. This way when I do call startReactApplication, it recognizes that the JS is already bundled and it started more quickly. I also had to do the same thing for the onDestroy of the activity where I start the ReactNative application. I needed a new instance when the activity was destroyed because if I didn't it would save state I didn't want.

**Comment by sgong-gzy** [comment]
@JeffreyLeeSpokeo Thanks for the reply! I already have only one ReactNativeHost in MainApplication and is shared among all ReactRootView. But the problem still remains...

**Comment by JeffreyLeeSpokeo** [comment]
I see, well I still see a flash of white, but it's slight so I haven't gotten rid of it entirely as well.

**Comment by sgong-gzy** [comment]
For anyone that still having this problem, I was able to pretty much get around the bundle loading time with random access module bundling + inline require (https://medium.com/@martinbigio/random-access-modules-bundling-is-a-mode-the-rn-packager-has-where-the-output-contains-an-index-f1ccfb20fb65).

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by littlehome-eugene** [comment]
@sgong-gzy can you provide us more detail on how to use random access module bundling + inline require ?
