### ISSUE TITLE
fix webp image size caculate bugs by upgrade dependencies image-size to newest version

### ISSUE THREAD

**Issue by Lxxyx** [facebook/react-native#13102]
### Description
When I try to use webp for app. But some webp images get an error message unsupported file type by image-size@0.3.5.

And I in image-size repo I found a issue image-size/image-size#65.
This is the same problem.

And try image-size^0.5.1 the error fixed.

### Reproduction

[FILL THIS OUT: Try to reproduce your bug on https://sketch.expo.io/ and provide a link. If you can't reproduce the bug on Sketch, provide a sample project. At the very least, provide an example of your code.]

https://incu-feedback.ncuos.com/logo.webp

This is the webp file.

And image-size 0.3.5 can not calculate size but 0.5.1 fixed this bug.

### Solution

[FILL THIS OUT: What needs to be done to address this issue? Ideally, provide a pull request with a fix.]

![image](https://cloud.githubusercontent.com/assets/13161470/24233132/3d457986-0fcb-11e7-9d2c-4e367e4d3672.png)

MyPr
https://github.com/facebook/react-native/pull/12733

**Comment by Lxxyx** [comment]
Is there anyone can help with this bug?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by StevenGBrown** [comment]
The image-size dependency has now been upgraded to 0.6.0: facebook/metro-bundler@7111cf6

I've confirmed that webp images can be displayed with React Native v0.48.0-rc.1.
