### ISSUE TITLE
Is it react-native  broken framework?

### ISSUE THREAD

**Issue by loki4u** [facebook/react-native#13101]
Hi Team,

when i tried to start project from create to deploy in to device. faced lot of issues in each step like installation issue, build issue, no proper docs. etc.. very difficult to find proper solution in some forum also. finally i ended up unhappy with  with react-native.

**Comment by jevakallio** [comment]
Hi loki4u,

I think you misspelled React-native. The "React" is supposed to start with a lowercase r.

Happy to help.

**Comment by omidfi** [comment]
Hi @loki4u, 

Your frustration is understandable. Even though react native might not be very friendly to new developers, but I have seen it working alright in many projects. 

I have a few suggestions that might help you: 

  * Follow the the getting started guide: http://facebook.github.io/react-native/docs/getting-started.html

  * Whenever you hit a problem that you can't solve yourself, or by searching, reach out and ask for help, for example here: https://www.facebook.com/groups/react.native.community/ 

  * Remember that when you are asking for help, you need to explain your problem clearly. Stackoverflow has a nice guide on how to ask your questions so that people can help you most: https://stackoverflow.com/help/how-to-ask

I hope this helps.

**Comment by hramos** [comment]
@loki4u sorry to hear you had a poor experience hear. React Native has several dependencies, requiring a fully working development environment for iOS and Android app development, as well as Node and other JavaScript projects. The team over at [Expo](http://expo.io) have built a product that allows you to build React Native apps without requiring any native dependencies. We recently collaborated on a new product, [Create React Native App](https://facebook.github.io/react-native/blog/2017/03/13/introducing-create-react-native-app.html), which provides you with a fully working environment with just one command.

If you have any specific feedback about which steps did not work well for you, or any specific errors you ran into while getting started, I'd love to hear it. I'm going to go ahead and close this issue - we use GitHub Issues to track bugs, and keeping questions out of it helps us focus on blocking issues - but please do respond with more details whenever you can so we can improve our docs.

**Comment by loki4u** [comment]
HI Team,

Thanks for your kind information about react-native.
