### ISSUE TITLE
Could not get unknown property 'androidSdk' for object of type org.gradle.api.internal.artifacts.repositories.DefaultMavenArtifactRepository.

### ISSUE THREAD

**Issue by RyanRong** [facebook/react-native#13117]
I update my Android SDK 25 and Gradle 3.3,

Error:(22, 0) Could not get unknown property 'androidSdk' for object of type org.gradle.api.internal.artifacts.repositories.DefaultMavenArtifactRepository.
<a href="openFile:/Users/myproject/build.gradle">Open File</a>

**Comment by gengjiawen** [comment]
You need to provide the related gradle file to fix this. And many native android module do not work with SDK 25.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
