### ISSUE TITLE
Get active slide index when using Animated.ScrollView

### ISSUE THREAD

**Issue by grundmanise** [facebook/react-native#13113]
### Description

I have a horizontal `Animated.ScrollView`, how can I get active slide index? Normally I'd hook up some functions to the `onScroll` event, but my `onScroll` is `Animated.event`.
```
Animated.event(
      [{ nativeEvent: { contentOffset: { x: this._scrollX }}}],
      { useNativeDriver: true }
    );
```

How to deal with `Animated.event` and still be able to get active slide index?

### Additional Information

* React Native version: 0.43
* Platform: iOS

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

**Comment by grundmanise** [comment]
Yes, you are absolutely right

**Comment by kshvmdn** [comment]
@grundmanise Running into this same problem, did you end up finding a solution?
