### ISSUE TITLE
Bundler crashes when using npm to install dependencies

### ISSUE THREAD

**Issue by tmpace** [facebook/react-native#13125]
### Description

With an app running in the emulator, when running the command `npm install --save lodash` I get this output:

Bundler: 
```
 ERROR  EPERM: operation not permitted, lstat 'C:\Users\Trevor\Code\Learn\test\node_modules\.staging\lodash-f4bb885f\fp'
{"errno":-4048,"code":"EPERM","syscall":"lstat","path":"C:\\Users\\Trevor\\Code\\Learn\\test\\node_modules\\.staging\\lodash-f4bb885f\\fp"}
Error: EPERM: operation not permitted, lstat 'C:\Users\Trevor\Code\Learn\test\node_modules\.staging\lodash-f4bb885f\fp'
```

Npm error:
```
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Trevor\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "lodash"
npm ERR! node v7.6.0
npm ERR! npm  v3.8.0
npm ERR! path C:\Users\Trevor\Code\Learn\test\node_modules\lodash
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error
npm ERR!     at moveAway (C:\Users\Trevor\AppData\Roaming\npm\node_modules\npm\lib\install\action\finalize.js:38:5)
npm ERR!     at destStatted (C:\Users\Trevor\AppData\Roaming\npm\node_modules\npm\lib\install\action\finalize.js:27:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:114:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\Trevor\Code\Learn\test\node_modules\lodash' -> 'C:\Users\Trevor\Code\Learn\test\node_modules\.lodash.DELETE'
npm ERR!  { Error
npm ERR!     at moveAway (C:\Users\Trevor\AppData\Roaming\npm\node_modules\npm\lib\install\action\finalize.js:38:5)
npm ERR!     at destStatted (C:\Users\Trevor\AppData\Roaming\npm\node_modules\npm\lib\install\action\finalize.js:27:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:114:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\Trevor\Code\Learn\test\node_modules\lodash' -> 'C:\Users\Trevor\Code\Learn\test\node_modules\.lodash.DELETE' parent: 'test' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Trevor\Code\Learn\test\npm-debug.log
```

**Note:** I was running as admin, and my environment variables are set properly, and I do _not_ get errors when using `npm install` when the bundler is not watching my files. 

### Reproduction Steps and Sample Code

I'm honestly not sure - you can try to `npm install` a dependency while the bundler is running, but I haven't been able to find anything regarding this issue online :\

### Solution

No idea - seems to be some sort of permissions issues, I don't know if the bundler modifies the permissions of files it's watching, but I am running as an admin. Ideally I wouldn't have to shut the application down each time I needed to install an outside dependency.

### Additional Information

* React Native version: 
react-native-cli: 2.0.1
react-native: 0.42.3

* Platform: Android

* Development Operating System: Windows 10

* Dev tools:
Android Studio version: 2.3
Android SDK version: 23

Would really appreciate a fix! I love developing in React, but honestly, I may have to just roll native Android development if I can't get this environment issue figured out.

**Comment by tmpace** [comment]
I should note that I have tried switching back to node 6.1.0 to test and that didn't make a difference.

I have also tried a fresh install of Android Studio, as well as Node - no dice.

**Comment by tmpace** [comment]
It seems I've fixed this by using `watchman` - However, this is not apparent anywhere on the official documentation (https://facebook.github.io/react-native/docs/getting-started.html).

Finding a windows version of `watchman` could also be easier.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
