### ISSUE TITLE
how can use react native connect with shared library(.so file)

### ISSUE THREAD

**Issue by diennguyentien** [facebook/react-native#13144]
##Please read the following carefully before opening a new issue.
Your issue may be closed if it does not provide the information required by this template.
### Description

I'm working on a React Native project and I using shared library (.so) for server.but I don't know how to connect. Is there anyway or solutions for connect React Native with (.so) file? Thanks

### Reproduction

 I want to connect between React Native with .so file

### Solution

Add support for connect react native with shared library

### Additional Information

* React Native version: 0.42
* Platform: iOS,  Android 
* Development Operating System: Windows, MacOS
* Dev tools: Android Studio 2.3, Android 6.0

**Comment by jkomyno** [comment]
Please remove iOS platform (you said you're working on Windows and using Android Studio). Also, you should be able to import that .so directly (https://developer.android.com/ndk/guides/prebuilts.html) and create a wrapper for react-native as described here: https://facebook.github.io/react-native/docs/native-modules-android.html

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

**Comment by diennguyentien** [comment]
@Jkomyno: Thanks, I will try.

**Comment by dekemega** [comment]
+1 i stuck on the same problem .. is there any solution ?
