### ISSUE TITLE
require/import of json files do not take native platform extensions in to account

### ISSUE THREAD

**Issue by 3rd-Eden** [facebook/react-native#13158]
### Description

When importing a JSON file through the `import` statement or `require` function it does not take the platform specific extensions like `.ios`, `.native` into account like it does with JavaScript files. 

The assumption was made here that the require flow threats all files in exactly the same way.

### Reproduction Steps and Sample Code

- Create a folder called `example`
- Add an `index.json` and a `index.native.json` file in the `example` folder. Make sure that both files have different JSON content.
- Import `example` folder and log the result.

```js
import example from './example';
console.log(example);
```

The output of the console will now the be the contents of `index.json` instead of `index.native.json`

### Solution

Platform resolution needs to be added to node-hast, specifically at this line:

https://github.com/facebook/react-native/blob/master/packager/src/node-haste/DependencyGraph/ResolutionRequest.js#L450-L462

I'm willing to create a PR for this if this is something you wish to see fixed. 

### Additional Information

* React Native version: 0.42.0
* Platform: All
* Development Operating System: Mac OSX
* Dev tools: [FILL THIS OUT: Xcode or Android Studio version, iOS or Android SDK version, if applicable]

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
