### ISSUE TITLE
Copy button is not working in android emulator, linux

### ISSUE THREAD

**Issue by saigrandhi** [facebook/react-native#13165]
### Description

The copy button in the android emulator is not working on the Linux platform. 

### Reproduction Steps and Sample Code

In order to reproduce this, just create a new react-native app and add a syntax error in index.android.js. Run this app and the error screen will show up but you would not be able to copy the error.
[CopyToClipboard.js has no case for linux](https://github.com/facebook/react-native/blob/master/local-cli/server/util/copyToClipBoard.js )

### Solution

The following solution worked for me:

- add `xsel` binary in a vendor folder inside the util where copyToClipBoard.js is located
- access it by `var xsel = path.join(__dirname, './vendor/xsel');`
- give the binary permissions using `fs` library: `fs.chmodSync(xsel, '0755');`
- update copyToClipBoard.js with a linux platform option.

```
    case 'linux':
          var child = spawn('xsel', ['--clipboard', '--input']);
          child.stdin.end(new Buffer(content, 'utf8'));
          return true;
```

I can make a pull request but I am not sure what tests should be implemented and where to implement them.
### Additional Information

* React Native version: 0.43
* Platform: Android
* Development Operating System: Linux

**Comment by saigrandhi** [comment]
https://github.com/facebook/react-native/commit/0fe0fc038b1cbc0f3be29f1e3a752c2feb153285 resolves this issue. This issue can be closed.

**Comment by saigrandhi** [comment]
https://github.com/facebook/react-native/commit/0fe0fc038b1cbc0f3be29f1e3a752c2feb153285 resolves this issue.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
