### ISSUE TITLE
"ref" callback and "componentDidMount" not being triggered on initial render

### ISSUE THREAD

**Issue by cailenmusselman** [facebook/react-native#13182]
### Description

`ref` callback and `componentDidMount` life-cycle hook is not being triggered until _after_ manually triggering an additional re-render with `setState`.

Also asked on SO, but not getting any responses: http://stackoverflow.com/questions/43009993/react-native-initial-lifecycle-hooks-not-being-called/43010267#43010267

### Reproduction Steps and Sample Code

"constructor", "componentWillMount", and "render" are called immediately upon launching the application, as expected. However, "ref", and "componentDidMount" are not called until manually triggering a re-render via this.setState() after the 5 second delay.

```
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';

class TestText extends Component {

    constructor(props, context) {
        super(props, context);
        console.warn('constructor');
        this.textRef = null;
    }

    componentWillMount() {
        console.warn('willMount');
    }

    componentDidMount() {
        console.warn('didMount');
    }

    render() {
        console.warn('render');
        return (
            <View>
                <Text
                    ref={(me) => {
                        console.warn('ref: ' + (me ? 'not null' : 'null'));
                        this.textRef = me;
                    }}>
                    {'TEST'}
                </Text>
            </View>
        );
    }

}

export default class AwesomeProject extends Component {

  constructor(props, context) {
      super(props, context);
      this.state = {
        test: 0
      };
      setTimeout(() => {
        this.setState({
            test: 1
        });
      }, 5000)
  }

  render() {
    return (
      <View style={styles.container}>
        <TestText />
      </View>
    );
  }

}

const styles = StyleSheet.create({
  container: {
    flex: 1
  }
});

AppRegistry.registerComponent('AwesomeProject', () => AwesomeProject);
```

### Solution

Expected behavior: Shouldn't "ref" and "componentDidMount" be called immediately after rendering. I shouldn't have to `setState` to get those hooks to run.

### Additional Information

* React Native version: 0.42.3
* Platform: Android (maybe iOS as well)
* Development Operating System: Windows
* Dev tools: compileSdkVersion = 23, buildToolsVersion = 23.0.1

**Comment by jjhesk** [comment]
same here ++

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by gauravdhiman** [comment]
Even I am facing this issue.

Here is the test code:
```js
import React, { Component } from 'react';
import {
  Button,
  Container,
  Content,
  Form,
  Item,
  Input,
  Label,
  Text
} from 'native-base';

export default class TestComponent extends Component {
  constructor(props) {
    super(props);
    this.refs = {};
  }

  componentDidMount() {
    console.log('=====>>>>>> 2. In componentDidMount() ....');
    this.refs.detailsField.focus();
  }

  render() {
    const { navigate } = this.props.navigation;
    return (
      <Container>
        <Content>
          <Form>
            <Item floatingLabel last>
              <Label>Details</Label>
              <Input
                ref={c => {
                  this.refs.detailsField = c;
                  console.log('=====>>>>>> 1 ....');
                  console.log(this.refs.detailsField);
                }}
                multiline={true}
                numberOfLines={10}
                style={{ height: 200, textAlignVertical: 'top' }}
                onChangeText={text => this.setState({ details: text })}
              />
            </Item>
          </Form>
        </Content>
      </Container>
    );
  }
}
```

`ref` callback is not getting called on rendering of `Inpput` component. Ideally we should see below console logs
```js
=====>>>>>> 1 ....
=====>>>>>> 2. In componentDidMount() ....
```

But on console I am only seeing
```js
=====>>>>>> 2. In componentDidMount() ....
```

Also seeing below warning / error message from React-Native (as I am calling `this.refs.detailsField.focus()` in `componentDidMount()`
```
Possible Unhandled Promise Rejection (id: 0):
TypeError: undefined is not an object (evaluating 'this.refs.detailsField.focus')
...
....
```
Looks like `ref` callback on `Input` field is not getting called at all.
Is my understanding wrong about `ref` or is it a bug ?

Please try this test case.

**Comment by sourcesoft** [comment]
@gauravdhiman did you find the solution? I have the same problem, ref doesn't get called at all.

**Comment by gauravdhiman** [comment]
@sourcesoft Yes, found the solution. I am using Native Base and in my case the culprit was `floatingLabel` on `<Item floatingLabel last>` component. If I remove `floatingLabel`, `ref` works fine, but with `floatingLabel` I need to use `getRef` as explained [here](https://github.com/GeekyAnts/NativeBase/issues/591).

Here is the code that is working for me. Note the `getRef` in second input field.
```js
<Item floatingLabel last>
    <Label>Address</Label>
    <Input
    onFocus={() => {
        // move to next field so that user an not modify this field manually
        this._detailsField._root.focus();
        // show screen to select an address
        navigate('SearchAddressScreen', {
        onSelectAddress: address => this.saveAddress(address)
        });
    }}
    value={this.state.address.text}
    />
</Item>
<Item floatingLabel last>
    <Label>Details</Label>
    <Input
    getRef={e => (this._detailsField = e)}
    multiline={true}
    numberOfLines={10}
    style={{ height: 200, textAlignVertical: 'top' }}
    onChangeText={text => this.setState({ details: text })}
    />
</Item>
```

**Comment by pennyandsean** [comment]
That's a workaround, not a fix.

**Comment by Bonobomagno** [comment]
If you are using some navigators library( like react-navigation in my case) this issue is still here. Maybe they delay the mount of the screen.
My actual solution is using something like `InteractionManager.runAfterInteractions(() =>functionThatUseTheRef)`.
Always a workaround, but better than arbitrary setTimeout()
