### ISSUE TITLE
Remove Placeholder for AlertIOS

### ISSUE THREAD

**Issue by Maftalion** [facebook/react-native#13189]
### Description

If you set 'secure-text' for AlertIOS.prompt, it will give you a placeholder 'Password' which is an issue because some things I want as secure-text aren't passwords, such as pin numbers. I was wondering if you would be able to remove this placeholder/make it optional/allow us to enter what placeholder we would like there.

### Reproduction Steps and Sample Code

![screen shot 2017-03-28 at 2 16 48 pm](https://cloud.githubusercontent.com/assets/12075600/24428097/1a258bb2-13c2-11e7-9bb4-b30be3c78618.png)

### Solution

What I'm currently doing is going to the RCT_EXPORT_METHOD() inside of RCTAlertManager.m and deleting the line that says textField.placeholder = RCTUIKitLocalizedString(@"Password"). If there is anyway to make this field optional or editable it would be really helpful.

### Additional Information

* React Native version: 0.42.3
* Platform: IOS
* Development Operating System:MacOS
* Dev tools: Xcode

**Comment by hramos** [comment]
This would be useful. Want to send a PR?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
