### ISSUE TITLE
How to avoid re-rendering when we were updating the state?

### ISSUE THREAD

**Issue by Deboracgs** [facebook/react-native#13181]
How to avoid re-rendering when we were updating the state?

I have varius setstate, but i need the calling last and update before other states, how make this?

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
