### ISSUE TITLE
PushNotificationIOS methods resolve with numbers rather than booleans

### ISSUE THREAD

**Issue by dylanpyle** [facebook/react-native#13185]
### Description

The methods `PushNotificationIOS.requestPermissions` and `PushNotificationIOS.checkPermissions` both, according to the documentation and the code itself, resolve with an object in the format:

```
{
  alert: (Boolean),
  badge: (Boolean),
  sound: (Boolean)
}
```

In reality, these seem to instead resolve with an object in the format:
```
{
  alert: (Number; 0 or 1),
  badge: (Number; 0 or 1),
  sound: (Number; 0 or 1)
}
```

### Solution

I'm guessing it's the code itself that's wrong — a boolean value seems more correct & friendly. However, it would be a backwards-incompatible change at this point... maybe better to accept this & fix the docs?

### Additional Information

* React Native version: 0.42.0
* Platform: iOS
* Development Operating System: macOS 10.12.3
* Dev tools: iOS 10.2, simulator

**Comment by dylanpyle** [comment]
nb: can't add a demo link since you have to link native modules — but it's very simple to repro:

```javascript
import { PushNotificationIOS } from 'react-native';

PushNotificationIOS.checkPermissions().then((permissions) => {
  console.log(permissions, typeof permissions.alert);
});
```

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
