### ISSUE TITLE
Block Button no left and right spaces between button and screen

### ISSUE THREAD

**Issue by ianweng** [facebook/react-native#13205]
Code:

```
      <Container>
        <Content>
          <Form>
            <Item floatingLabel>
              <Label>Username</Label>
              <Input
              />
            </Item>
            <Item floatingLabel>
              <Label>Email</Label>
              <Input
                keyboardType="email-address"
                returnKeyType="next"
              />
            </Item>
            <Item floatingLabel last>
              <Label>Password</Label>
              <Input
              />
            </Item>
          </Form>
          <Button block>
            <Text>Primary</Text>
          </Button>
        </Content>
      </Container>
```

Result:

![screen shot 2017-03-30 at 11 10 44](https://cloud.githubusercontent.com/assets/13402148/24479053/f297d766-1539-11e7-93ff-eb8d17ebdcb2.png)

By the way, I also use expo.io, could the issue be caused by using this?

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
