### ISSUE TITLE
Set threshold before ScrollView or ListView move

### ISSUE THREAD

**Issue by sun2rise** [facebook/react-native#13218]
### Description
I am trying to understand how can I set a threshold for the RN ScrollView o  ListView.

This is because if you have multiple vertical scrollable View in a horizontal ScrollView then the horizontal scrolling of the Views is very difficult.

So i just need something that holds the horizontal scrolling until the finger swipe horizontally for a certain pixel-span.

Has anyone a clue about how to archive this? or maybe i shoud make a feature request?
Thank you

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

**Comment by sun2rise** [comment]
Thanks @hramos, actually I posted it 7 days ago. I just thought that maybe here I could increase my chances to find a help.

**Comment by hramos** [comment]
As it happens, GitHub Issues are not the best place to ask questions. We'd like to keep the issue tracker focused on actionable issues that can be addressed with a PR, ideally.
