### ISSUE TITLE
Close Modal when touching the outside

### ISSUE THREAD

**Issue by Gp2mv3** [facebook/react-native#13216]
### Description

I use Modal component in my app. Is it possible to add a parameter to close the modal when the user touches the overlay (outside of the modal content) ? 

### Reproduction Steps and Sample Code
```
<Modal
  animationType={"slide"}
  transparent={true}>
  ...
</Modal>
```

### Solution
Add a parameter ?
```
<Modal
  animationType={"slide"}
  closeOnClick={true}
  transparent={true}>
  ...
</Modal>
```

**Comment by vjeranc** [comment]
TouchableWithoutFeedback inside of Modal is the way to go.

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
