### ISSUE TITLE
[CocoaPods] Add support for the C++ bridge

### ISSUE THREAD

**Issue by ide** [facebook/react-native#13225]
This is an issue to track adding support for the C++ bridge to the Podspec. @mhorowitz is one of the authors of the new bridge. The longer-term plan is to move completely to the C++ bridge while giving people a period of time to transition. At first the C++ bridge will be opt-in, then opt-out, and then the legacy bridge will be removed.

I haven't put much thought into how we want to approach this with the Podspec and wanted to start a discussion here.

cc @alloy @janicduplessis - you guys might have some thoughts

**Comment by mhorowitz** [comment]
Thanks, @ide !  I don't know much about podspecs, but I'll answer whatever I can about the new bridge to get you guys moving.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by ide** [comment]
This is underway anyway so removing Icebox.

**Comment by hramos** [comment]
The icebox script doesn't account for long-running discussions. It's OK to re-open this.

**Comment by mhorowitz** [comment]
At this point, this is "done" in the 0.47 rc.  But I've gotten very little feedback to know if it's actually working for people.

If you use it, and it works for you, please comment here or let me know.

**Comment by TheTekton** [comment]
@mhorowitz Our Podfile is configured for the CxxBridge, in 0.47.2, with no issues to report.

**Comment by ragnorc** [comment]
#14326

**Comment by ide** [comment]
Closing this umbrella issue since basic support is working and people are using it in production.
