### ISSUE TITLE
[babel-preset-react-native] Error with empty destructuring: babelHelpers.objectDesctructuringEmpty is not a function

### ISSUE THREAD

**Issue by leoselig** [facebook/react-native#13234]
### Description

Empty destructuring operators do not work with `react-native-babel-preset`.

### Reproduction Steps and Sample Code

Setup `react-native` with a custom `.babelrc` like this:
```json
{
  "presets": [ "react-native" ]
}
```

Then, somewhere in your code, perform a destructuring on a function argument like this:

```javascript
export default function MyComponent({}: PropsType) {
  // ...
}
```

### Solution

Unsure. Probably the most obvious and quick solution, is to add the missing babel helper function. Unfortunately, I'm can't get my head around how `react-native`s way of juggling the babel config works right now, so I cannot be certain or submit a PR.

However, as I already pointed out in https://github.com/facebook/react-native/issues/4844#issuecomment-290648816 I feel like the general way babel is "instrumented" by `react-native` tends to be more of a hack and seems to be the cause of quite a few bugs

(I'm absolutely not privileged to judge this, but I have some doubts as to whether all this is worth the performance improvements)

### Additional Information

* React Native version: `0.42.3`
* Platform: iOS
* Development Operating System: macOS Sierra (10.12.3)
* Dev tools: Xcode, iOS 10.3, iPhone 6 Simulator

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
