### ISSUE TITLE
Animated doesn't work after setState is called

### ISSUE THREAD

**Issue by xiongxiong** [facebook/react-native#13230]
### Description

I want to perform some change before animation start, so I called setState() before Animated.spring().start(), I expected the component is updated first then animated, but the animation isn't started at all. Is this a bug? If not, how should I do?

### Reproduction

Here's sample code:
...
this.setState({zIndexLeft: 0, zIndexRight: 1});
Animated.spring(this.state.contentPositionRight, {toValue: 200}).start((finished) => {
        this.setState({actionsheetState: -1})
});
...

### Additional Information
* React Native version:0.42.3
* Platform: iOS
* Development Operating System: MacOS 10.12.4
* Dev tools:Xcode 8.3, iOS 10.3

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
