### ISSUE TITLE
Hot Reloading not working with React-navigation (refreshes entire route stack to initialRoute instead of just the component)

### ISSUE THREAD

**Issue by claykohut** [facebook/react-native#13240]
**Description**

I'm having trouble getting hot reloading to work on our app. Changes seem to be submitting / the app shows a banner showing that changes are applied but nothing happens / updates.

If I change the entry point index component to be a stateful component which returns the App component, then changes seem to update but the react-navigator stack resets to the initial route.

Can anyone please help!? I previously was having this error with Navigator, but was told to try updating to react-navigation (which I have) and am still facing the error.

In the state that causes an entire app refresh, the App file is structured like:

```
render(){
      <Provider store={store}>
            <HomeStack />
      </Provider>
}
```

**Additional Information**

React Native version: 0.39.2
Platform: iOS
Development Operating System: MacOS
Dev tools: Xcode

**Comment by hramos** [comment]
cc @ericvicenti

**Comment by frankmarineau** [comment]
I think this happens because react-transform-hmr doesn't support functional components. This means that when you change a component, the component actually being reloaded is its nearest "parent" **class** component. In your case, this happens to be of higher order than your nav stack. When it gets reloaded, your whole nav context is lost.

I was able to get around this by converting the views I load in my navigators to classes. This allows the HMR transform to pick them up and prevents the whole nav stack from being reloaded when they change.

**Comment by claykohut** [comment]
@frankmarineau can you provide a little more insight here?

The components I'm using inside navigation are class based unless I'm missing something

**Comment by jeffreymendez1993** [comment]
Yep ^

**Comment by claykohut** [comment]
@frankmarineau this fixed it for me -- thanks frank!!

**Comment by marstall** [comment]
can someone help me with coding this solution - what, in code, does "converting the components I load in my navigators to classes" look like? Thanks! @frankmarineau

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
