### ISSUE TITLE
[Android] Webview scroll gets stuck when form autocomplete is displayed

### ISSUE THREAD

**Issue by farazs** [facebook/react-native#13241]
### Description

On a Android 7.0 high-resolution device, if you have a webview that goes to a page with a form on it, and that form is completed once, the webview saves the form data. When you go to the same form again and tap on a field, the autocomplete suggestion dropdown is displayed and when this happens the webview scrolls to the top and gets stuck there. When trying to scroll down, the webview scrolls a bit and then jumps back to the top. 

If you have tap on the screen (removing focus from the form), the autocomplete closes and you can once again scroll normally.

This bug does not occur with a normal Android webview, only with the react-native WebView. 

I was **not** able to reproduce it on a Samsung S5 Android 6.0 or in an emulator, only on the S7 Edge Android 7.0 and Pixel XL Android 7.1.1. It is possible it only occurs on higher resolution device.

### Reproduction Steps and Sample Code

Sample react-native app to reproduce: https://github.com/farazs/webview-sample

1. Install the app on a high resolution Android 7+ device (S7 Edge or Pixel XL so far)
2. Run the app and you should see https://www.w3schools.com/html/html_forms.asp in the webview
3. Complete the form and press submit
4. Close and restart the app
5. Tap a form field and clear the contents
6. The autocomplete suggestion dropdown should show up
7. The webview should now be stuck to the top of the page

Sample native android app where bug is not reproducible: https://github.com/farazs/android-webview-form-sample

### Solution

I am not sure why this occurs or what the direct solution is. It seems like some kind of layout bug.

A workaround could be adding a prop to WebView to allow disabling of the autocomplete functionality `view.getSettings().setSaveFormData(false);`

### Additional Information

* React Native version: 0.42.3
* Platform: Android
* Development Operating System: Mac OS X
* Dev tools: Android Studio 2.3
* Affected Android OS: Android 7.0 or later
* Known affected devices: Samsung Galaxy S7 Edge, Google Pixel XL

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
