### ISSUE TITLE
[PROJECT] Provide Clarifications about "Public vs. Facebook Internal Version"

### ISSUE THREAD

**Issue by lazaridis-com** [facebook/react-native#13256]
> Hey all, sorry you are being hit by this -- a couple engineers at FB are actively working on open sourcing our internal fix for this, but it's not a simple change so unfortunately it'll take a while longer. Tentatively, they are hoping to have it open sourced by the end of the year.
source: https://github.com/facebook/react-native/issues/3198#issuecomment-241867280

And then we see a user-base doing kind of an "organized plea", asking the "masters" to give a bit more:

https://react-native.canny.io/feature-requests/p/add-overflow-support-to-android

Is this the way "Facebook Open Source" works? I am **highly** disappointed. 

I think its a matter of project-transparency, that the fact that "Facebook uses internally a far different react-native version" should be clarified. It should be visible in a **very** prominent position within the project documentation, to avoid that adopters get disapointed later on, when realizing that the open-source code is actually very different (and buggier) than the version in use by Facebook.

And please realize: even tiny differences can result in being in practice "far different":

>  but it's not a simple change so unfortunately it'll take a while longer

This indicates that the facebook-internal version is very different.

To be blunt (and clear) :

This kind of s*cks.

**Comment by lacker** [comment]
You make a great point, that Facebook using React Native doesn't necessarily mean that React Native is the right tool for you. It's naturally a bit different how React Native is used at Facebook because the technology started here. So I think it makes more sense to look at some companies that have successfully adopted open source React Native, because their experience will be the most similar to yours. For example:

* Airbnb https://www.youtube.com/watch?v=tUfgQtmG3R0
* Microsoft https://react.jsnews.io/cool-to-see-that-the-new-skype-app-is-using-react-native/
* Uber https://eng.uber.com/ubereats-react-native/

I wish we could open source 100% of the bug fixes that we find internally, and we try to get there, but sometimes it just takes a bit more work than you might expect. I'm sorry! It sounds like you're running into some bug that is frustrating you, and maybe there's some workaround for it in the meantime before someone gets it fixed, so if you have not figured that out I suggest opening a separate issue for it.
