### ISSUE TITLE
Unforunately,  * has stopped. After invalid StyleSheet. From Getting Started

### ISSUE THREAD

**Issue by Trenrod** [facebook/react-native#13269]
### Description
Using Getting started Tutorial to reproduct an error I have with my current project.
When an error occurs during live reload, like having an invalid StyleSheet attribute, application crashes on my android phone as with emulator with "Unfortunately, myapp has stopped."

### Reproduction Steps and Sample Code

Install blank react-native application. Setup Android SDK, start Emulator. Start packager and then react-native run-android.
When its running simply rename an StyleSheet value and save to reload application.

### Solution

Error page should be shown and not leave the application.

### Additional Information

* React Native version: 0.42.3
* Platform: Android
* Development Operating System: Windows 10
* Dev tools: VSC, Android SDK Tools 25.2.5 / Platform 23.4 (Emulator running @)

**Comment by janicduplessis** [comment]
I can confirm the issue. Passing an invalid **value** to a stylesheet prop will cause a native crash, it would be nice to handle the case properly and show a helpful error message.

Repro:
```js
const styles = StyleSheet.create({ marginTop: 'hello' });
```

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
