### ISSUE TITLE
Don't forget to support "react-native-git-upgrade"

### ISSUE THREAD

**Issue by wellyshen** [facebook/react-native#13268]
I found that react-native 0.43.0 has released and I upgraded my RN through "react-native-git-upgrade" but it can't find the exist repo, please support it :

<img width="1279" alt="2017-04-03 10 35 26" src="https://cloud.githubusercontent.com/assets/21308003/24614559/22605658-18be-11e7-85a1-4f20840540ac.png">

**Comment by ncuillery** [comment]
The 0.43.0 hasn't been released yet. It's still in RC 😄 

Please note that there a delay between the release on Github (displayed [here](https://github.com/facebook/react-native/releases)) and the NPM publish. For instance, the version 0.43.0-rc.5 released 3 days ago hasn't been published on NPM yet.

The desired package must have been published on NPM in order to use `react-native-git-upgrade`.

**Comment by ncuillery** [comment]
@facebook-github-bot close
