### ISSUE TITLE
WebView finishes with loading event

### ISSUE THREAD

**Issue by farazs** [facebook/react-native#13279]
### Description

I have noticed this with pages that use angular ui router but it's possible it happens in other cases as well. When switching states on a page with angular ui router, in a small percentage of loads, the last navigation state change event on Android has `loading: true`. If you use a loading indicator, this would cause it to show indefinitely.

This happens because some Android webview event is triggered, usually `onPageFinished` but the progress of the webview is not 100 so `loading` is set as `true` for the event.

I have encountered this on iOS as well but am unable to consistently reproduce. It occurs because `webViewDidFinishLoad` is called multiple times and in a small number of cases `webView.loading` is never false so we never send the finish event.

### Reproduction Steps and Sample Code
Snack/Sketch link: https://snack.expo.io/SkaN34l6x
Github repo: https://github.com/farazs/webview-sample/tree/navigation_state_bug
Video: https://drive.google.com/file/d/0B9SwtBquHoExUkU1ckgxOHJzcWc/view?usp=sharing

Steps:
1. Run app
2. Click on `Alice` or `Bob`link
3. Press `Show random contact` button
4. Wait for new page to load
5. Repeat steps 3 and 4
6. Eventually the loading screen will stay on until you press another link

### Solution

Either always set `loading` to `false` for `onPageFinished` or add an `onProgressChanged` method and send a navigation state change event for that as well.

### Additional Information

* React Native version: 0.42.3
* Platform: Android and iOS
* Development Operating System: MacOS
* Dev tools: Android Studio 2.3 and Xcode 8.3.2

Reproduced on Samsung S5, S7 Edge and iPhone 6S

**Comment by chiraggshah** [comment]
@farazs : I too am facing this. Were you able to fix or a possible workaround?

**Comment by farazs** [comment]
@chiraggshah I'll create a PR with my solution. Had to change some stuff in a fork

**Comment by farazs** [comment]
See #13586. You can cherry pick that onto a fork and use that for a fix in the meantime.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
