### ISSUE TITLE
Feature request: add error code to networking errors

### ISSUE THREAD

**Issue by vkurchatkin** [facebook/react-native#13277]
### Description

It would be useful to be able to interpret networking errors programmatically, for example to be able to check that error is a connection error, or DNS error, etc. This information can be used for error-reporting, generating more precise error messages and determining whether it's possible to retry failed requests.

### Solution

__Option 1.__ Add `code` field to error objects and some constants:

```js
fetch(...)
  .catch(e => console.log(e.code === DNS_ERROR))
```

__Option 2.__ Add `getNetworkingErrorCode` function and some constants:

```js
fetch(...)
  .catch(e => console.log(getNetworkingErrorCode(e) === DNS_ERROR))
```

__Option 3.__ Add a function for each distinguishable error type:

```js
fetch(...)
  .catch(e => console.log(isDnsError(e)))
```

### Additional Information
* React Native version: n/a
* Platform: both
* Development Operating System: n/a
* Dev tools: n/a

**Comment by crisys11** [comment]
Please open this feature request in whatwg-fetch package because react native delegate fetch implementation to this package please see https://github.com/facebook/react-native/blob/292cc82d0ebc437a6f1cdd2e972b3917b7ee05a4/Libraries/Network/fetch.js

**Comment by crisys11** [comment]
Searching  in the whatwg-fetch i found that is possible get the error code and after detect error type

```
function checkStatus(response) {
      if (response.status >= 200 && response.status < 300) {
        return response
      } else {
        var error = new Error(response.statusText)
        error.response = response
        throw error
      }
    }

    function parseJSON(response) {
      return response.json()
    }

    fetch(`http://httpstat.us/500`)
      .then(checkStatus)
      .then(parseJSON)
      .then(function(data) {
        console.error('request succeeded with JSON response', data)
      }).catch(function(error) {
        switch(error.response.status) {
           case 500:
              console.log('internal');
              break;
           case 403:
              console.log('Forbidden');
           ....
        }
        console.error('request failed', JSON.stringify(error))
      })
```

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by vkurchatkin** [comment]
@hramos it is very disappointing that this issue was closed without actually being looked at.  Yes, I believe that it should remain open and yes, I am willing to do the work. But I'm not going to until I can be sure that at least someone is going to look at it and it's not going to closed automatically in 3 months. At the moment it doesn't  seem that contributions are welcome at all.

**Comment by skevy** [comment]
Hey @vkurchatkin -- thanks for pinging on this.

What's your proposal for adding this functionality? As @crisys11 mentioned, we use the whatwg-fetch implementation in React Native, and it seems (based on @crisys11's code snippet) that it may at least have _some_ of the functionality you're looking for?

I would be glad to review a PR (make sure you tag me on it!) if you feel like RN is the best place to add the functionality that you're looking for -- definitely agree that it would be useful.

**Comment by vkurchatkin** [comment]
@skevy I've outlined my proposal in the issue. Option 2 seems the most viable. I'm personally OK with having it only in `XMLHttpRequest`.

> that it may at least have some of the functionality you're looking for?

Yeah, that's not what I'm talking about. You can get status code, for sure. I'm talking about cases where you don't get any response at all.

**Comment by skevy** [comment]
@vkurchatkin ok makes sense. Option 2 seems reasonable to me as well.

Let me know when you have a PR up, and I'll take a look :)
