### ISSUE TITLE
URL query parameter encoding is different on android vs ios

### ISSUE THREAD

**Issue by hasLandon** [facebook/react-native#13281]
#### URL query parameter encoding when using fetch is not handled the same on both iOS and Android

When calling `fetch()` with the following URL query parameter: 
`["AND",["NOT",["EQ","status","expired"]],["LIKE","name","%Geo%"]]`,

When I monitor the actual network request that is executed with charles when running on iOS, the query parameter is encoded as:
![screen shot 2017-04-03 at 2 56 56 pm](https://cloud.githubusercontent.com/assets/21961459/24633740/e7e47fd4-187e-11e7-96a4-d4f4acca1e4a.png)

but on android, it is encoded as:
![screen shot 2017-04-03 at 2 28 53 pm](https://cloud.githubusercontent.com/assets/21961459/24633746/f2cc7c58-187e-11e7-9890-00c205f0985b.png)

Basically, the main difference is that iOS is encoding everything in the URL, but android is only encoding the quotes.

### Reproduction Steps and Sample Code

An example call that would result in the inconsistency when you run it on iOS vs Android and monitor network traffic using an external tool (such as charles) is:

`fetch('http://url.com?queryParamWithArray=["this","is",["a","test"]]');`

On iOS, the url would be transformed to: 
`http://url.com?queryParamWithArray=%5B%22this%22,%22is%22,%5B%22a%22,%22test%22%5D%5D`

Whereas on android the url would be transformed to: 
`http://url.com?queryParamWithArray=[%22this%22,%22is%22,[%22a%22,%22test%22]]`

### Solution

The fetch library being used on both android and ios needs to be consistent in the way it transforms query parameters in URLs.

### Additional Information

* React Native version: 0.42.3
* Platform: Both
* Development Operating System: Mac OS 10.12.4
* Dev tools: iOS 10.3 and Android 6.0

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
