### ISSUE TITLE
Platform is a read only object

### ISSUE THREAD

**Issue by danieljoonlee** [facebook/react-native#13280]
### Description

Seems like `Platform` object from `react-native` is a read only object, and mocking the functions like `Version` isn't possible.

After doing `Object.defineProperty(Platform, "Version", { writable: true })`, I was able to update the object.  Is this intentional?

### Reproduction Steps and Sample Code

Example:
`Platform.Version = 24`

### Solution

Haven't looked too deep into, but if it's something that needs to change I'd like to do a PR for it

### Additional Information

* React Native version: 0.40
* Platform: both

**Comment by ericvicenti** [comment]
I'm not sure why you'd want `Platform.Version` to be writable. Maybe you can mock this out in your test code? Or you could change the value that the native code provides.

**Comment by danieljoonlee** [comment]
Right, so currently using `Object.defineProperty` I can change `Platform.Version` to be writable, otherwise it's read only.

If I'm testing for different android permissions for version `Platform.Version >= 23` and `Platform.Version < 23`.  Then those are two different work flows I need to write tests for.  Seems inconvenient that I can't mock `Platform.Version` without a bypass.

**Comment by hey99xx** [comment]
I think rather than trying to mock internals of React Native, you can create a simple wrapper for it. i.e.

```javascript
var mockablePlatform = {...(require('react-native').Platform)}
if (__DEV__) {
   mockablePlatform.mockVersion = (v) => mockablePlatform.Version = v
}
module.exports = mockablePlatform;
```

Otherwise I would agree that the real Platform object should actually be frozen and not allow `Object.defineProperty(Platform, "Version", { writable: true })`, but the fact that it does allow does not mean you should break it.

**Comment by danieljoonlee** [comment]
Hmm.  What about `Platform.OS`?  It's a string, so it's a lot easier to mock different platforms of `ios` and `android`.  I agree either these things should be mockable easily, or not mockable through React Native.  Regardless, one is a much easier task than the other.

**Comment by hey99xx** [comment]
> What about `Platform.OS`? 

What about it? It's not really different from `Version`.

    mockablePlatform.mockInternal = (key, value) => mockablePlatform[key] = v;

if you really wanted it. What do you propose, a PR that freezes entire `Platform` object? I don't see a standard in this code base that freezes the public APIs (for example all [react-native keys](https://github.com/facebook/react-native/blob/master/Libraries/react-native/react-native-implementation.js#L17) are also writable), but then again I am not a contributor to this project so I'll let FB engineers comment for it.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
