### ISSUE TITLE
Make DrawerNavigator Available Globally

### ISSUE THREAD

**Issue by vineetkumar198715** [facebook/react-native#13292]
I am using both DrawerNavigator and StackNavigator in my app. I have implemented the DrawerNavigator on one screen and from there the Drawer is available for every screen if I switch them using Drawer Options. As soon as use this.props.navigation.navigate and go to other screen, the Drawer is not available anymore. What should I do If I want a Global Drawer? Should I initialize DrawerNavigator in all the files or there is a way to include it from a single location?

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
