### ISSUE TITLE
[iOS] View Border Bleeding

### ISSUE THREAD

**Issue by 509dave16** [facebook/react-native#13305]
### Description
So the goal is to render a grid that doesn't have an outer border. This means rendering no borders on certain sides of the cells. Normally nothing out of the ordinary would happen if this were done on the Web or Android. However in iOS, there's **border bleeding**.

![iOS Sample Image](https://s15.postimg.org/z7dlfw2hn/ios-sample-image.png)
**NOTE: The following issue is related but is not the same because the border radius is causing the bleeding**:  https://github.com/kirankalyan5/react-native-segmented-control-tab/issues/10

### Reproduction Steps and Sample Code
View this Expo Snack Sample: https://snack.expo.io/BklaUnWTl

### Additional Information
* React Native version: 0.26.0 and 0.41.2
* Platform: iOS
* Development Operating System: MacOS
* Dev tools: Xcode 8.3, iOS 8

**Comment by karanjthakkar** [comment]
@509dave16 It is my _guess_ that the issue you are facing is _probably_ because of the decimal borderWidth. I tried changing the `borderWidth` in multiples of 0.5 and that worked perfectly. Also the cutting off part is because your text component is overlapping with the view. You can increase the width/height to fix that. This is a version of your example with the width, height and borderWidth modified: https://snack.expo.io/BkE9Dzf6e Hope that helps!

**Comment by 509dave16** [comment]
@karanjthakkar Appreciate the quick response. Don't see that everyday on Github. I'm surprised you saw the original issue description before I updated it. I took out the part about the overlapping text because it wasn't relevant to the issue title. And I probably should have know better concerning the overlapping elements. In any case, thanks for sharing with me your solution. I never would have guessed or tried dp units of 0.5. Don't know if that's a limitation or a recommendation, but I'm going to run with it. Just looked at project in Snack. Looks beautiful! Can't thank you enough for your help!! I'll close this for now until it comes up again.
