### ISSUE TITLE
rn 0.43.1 upgrade errors: react-addons-shallow-compare

### ISSUE THREAD

**Issue by npomfret** [facebook/react-native#13325]
react-native-git-upgrade failed until I removed all my dependencies from my package.json file with this error:

```
Error: Command 'npm install --save --color=always react-native@0.43.1 react@16.0.0-alpha.6' exited with code 1:
stderr: undefined
```
...(and lots of warnings about `requires a peer of react@>=15.4.0 but none was installed.`)

After removing them the upgrade worked, but when I started the app (after putting the deps' back in) it fails with:

 `error: bundling: UnableToResolveError: Unable to resolve module `react/lib/shallowCompare`

**Comment by jqn** [comment]
Plus one here

**Comment by janicduplessis** [comment]
cc @ide This is probably related to the commit that removes addons deps, looks like it was still needed for 0.43.

**Comment by ide** [comment]
I'm fairly sure the addons aren't used anymore in 0.43. (`git grep addon` shows they aren't used anywhere). I think this bug is related to react-native-git-upgrade as new projects work fine to my knowledge.

**Comment by grabbou** [comment]
Yup, I was also able to successfully run it during my testing, so that shouldn't be an issue.

**Comment by jqn** [comment]
In my case this bugs happens on existing projects, new projects seem to work just fine.

**Comment by MattyK14** [comment]
+1

**Comment by janicduplessis** [comment]
I think the issue is that react@16.0.0-alpha.6 doesn't include the code for the addons anymore so you will need to update react-addons-shallow-compare to ^15.5.0 which doesn't depend on react internals to work. It is possible it is a library that depends on it.

**Comment by dantman** [comment]
@janicduplessis The readme for the latest version of that repo states:

>**Note:**
>This is a legacy React addon, and is no longer maintained.
>
>We don't encourage using it in new code, but it exists for backwards compatibility.  
>The recommended migration path is to use [`React.PureCompon

**Comment by janicduplessis** [comment]
Yea, I don't recommend using it but if your code or a library you use does you should update or move to PureComponent in order to fix this issue.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
