### ISSUE TITLE
No touch event when TextInput has focus 

### ISSUE THREAD

**Issue by zhuyifan2013** [facebook/react-native#13322]
### Description

When TextInput has focus , softkeyboard shows , but cannot touch anywhere except for keyboard and textinput field.

### Reproduction Steps and Sample Code

```
<TextInput
                            style={styles.linkAddressHint}
                            placeholder={strings.pasteHint}
                            autoCapitalize="none"
                            autoCorrect={false}
                            keyboardType='url'
                            // onSubmitEditing={(event) => {
                            //     if (!Utils.isValidURL(this.parsingUrl)) {
                            //         this.parsingUrl = strings.searchURL + this.parsingUrl;
                            //     }
                            //     this._gotoWebPage();
                            // }}
                            onChangeText={(text) => {
                                this.parsingUrl = text;
                                this.setState({
                                    inputValue: text
                                });
                            }}
                            selectTextOnFocus={true}
                            clearButtonMode='while-editing'
                            blurOnSubmit={true}
                            autoFocus={true}
                            value={this.state.inputValue}
                        />
```

### Additional Information

* React Native version: [0.42]
* Platform: [iOS]
* Development Operating System: [MacOS]
* Dev tools: [Xcode 8 iOS10.3]

## SOLUTION
It is not a bug of react-native, it is caused by a library "react-native-popup-dialog"  to intercept my all touch event when keyboard shows , so close this issue

**Comment by rohitgoyal** [comment]
Same here!

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
