### ISSUE TITLE
Remote debugger stops working after importing a library

### ISSUE THREAD

**Issue by Matko95** [facebook/react-native#13323]
### Description

After importing a js library (https://github.com/orhan/react-native-openpgp) if you turn on the remote debugger, the app keeps crashing. 

`
04-05 11:01:41.784  2775  2868 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
04-05 11:01:41.784  2775  2868 E AndroidRuntime: Process: com.lemonmobileapp, PID: 2775
04-05 11:01:41.784  2775  2868 E AndroidRuntime: java.lang.IllegalStateException: Expected a name but was NUMBER
04-05 11:01:41.784  2775  2868 E AndroidRuntime:        at android.util.JsonReader.nextName(JsonReader.java:390)
04-05 11:01:41.784  2775  2868 E AndroidRuntime:        at com.facebook.react.devsupport.JSDebuggerWebSocketClient.onMessage(JSDebuggerWebSocketClient.java:196)
04-05 11:01:41.784  2775  2868 E AndroidRuntime:        at okhttp3.internal.ws.RealWebSocket$1.onMessage(RealWebSocket.java:62)
04-05 11:01:41.784  2775  2868 E AndroidRuntime:        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:242)
04-05 11:01:41.784  2775  2868 E AndroidRuntime:        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:108)
04-05 11:01:41.784  2775  2868 E AndroidRuntime:        at okhttp3.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:97)
04-05 11:01:41.784  2775  2868 E AndroidRuntime:        at okhttp3.ws.WebSocketCall.createWebSocket(WebSocketCall.java:152)
04-05 11:01:41.784  2775  2868 E AndroidRuntime:        at okhttp3.ws.WebSocketCall.access$000(WebSocketCall.java:41)
04-05 11:01:41.784  2775  2868 E AndroidRuntime:        at okhttp3.ws.WebSocketCall$1.onResponse(WebSocketCall.java:97)
04-05 11:01:41.784  2775  2868 E AndroidRuntime:        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:126)
04-05 11:01:41.784  2775  2868 E AndroidRuntime:        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
04-05 11:01:41.784  2775  2868 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
04-05 11:01:41.784  2775  2868 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
04-05 11:01:41.784  2775  2868 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:761)
`

This is the stacktrace that is dumped when the app crashes.

### Reproduction Steps

```
react-native init test
npm install --save react-native-openpgp
react-native link react-native-openpgp
//index.android.js
import * as openpgp from 'react-native-openpgp';
```

### Possible Solution
So far the only solution I see could be in the JSDebuggerWebSocketClient.java, specifically the onMessage method, It could be that the JsonReader doesn't skip some values properly. But that's only a guess.

### Additional Information

* React Native version: [0.41.0]
* Platform: [Android (Possibly both)]
* Development Operating System: [Windows]
* Dev tools: [PhpStorm, Android SDK 23]

**Comment by ValentinBlokhin** [comment]
I have a similar issue with 
[https://github.com/layerhq/layer-websdk/issues/160](url)

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by srinivasdamam** [comment]
@hrEven I'm facing the same problem, please re-open this issue.
