### ISSUE TITLE
`setNativeProps` does not work with `blurRadius`

### ISSUE THREAD

**Issue by yuche** [facebook/react-native#13344]
### Description

I am trying to use the `setNativeProps` function to set Image component's `blurRadius` and it is not working,  Am I missing something?

### Sample Code

```javascript
class BlurRadius extends React.Component {
  constructor(props) {
    super(props)
    this.blurRadius = 0
  }

  componentDidMount() {
    this.interval = setInterval(() => {
      this.blurRadius += 1
      if (this.blurRadius <= 100) {
        this.image.setNativeProps({ blurRadius: this.blurRadius })
      } else {
        clearInterval(this.interval)
      }
    }, 100)
  }
  
  render() {
    return (
      <Image
        ref={component => this.image = component}
        source={{uri: 'a.com/b.jpg'}}
        style={{ width: 100, height: 100  }}
        blurRadius={0}
      />
    )
  }
}
```

### Additional Information

* React Native version: 0.42.3
* Platform: [iOS]
* Development Operating System: [MacOS]

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
