### ISSUE TITLE
React native breaks emulator networking

### ISSUE THREAD

**Issue by aem** [facebook/react-native#13340]
### Description

Quite frankly, I'm not entirely sure. As background, I'm trying to integrate react-native into an existing app. I've followed all of the [instructions](http://facebook.github.io/react-native/docs/integration-with-existing-apps.html) and for a while successfully had React code running alongside native Android code. A couple of days ago I got a new laptop from work and when I tried to run this code on the new laptop nothing was working.

I went back and made sure I had `watchman` and all other external deps installed, double-checked all of my code and it all appears to be ok, but for some reason my component never mounts. Constructor never gets called, log statements in `componentDidMount` are not executed, nothing. I know the JavaScript is loaded properly because log statements in `index.android.js` execute properly, so I'm fairly confident that there's no issue with my JavaScript. However, when I try to mount a component that is registered with `AppRegistry` it doesn't work properly. 

I've opened a Stack Overflow question [here](http://stackoverflow.com/questions/43229683/react-native-component-not-mounting/43239835#43239835) to no avail.

### Reproduction Steps and Sample Code

The relevant code to mount my component and the component itself are described in the SO question linked above. 

### Solution

Hopefully someone with more experience with RN internals might have seen this before? I'm genuinely at a loss. I've done everything from wiping out `node_modules` to wiping the Android SDK and removing all emulator instances from my laptop and starting from scratch. Nothing has remedied the issue. 

### Additional Information

* React Native version: Attempted with both 0.42.3 and 0.43.0
* Platform: Android
* Development Operating System: macOS 10.12
* Dev tools: Android Studio

**Comment by aem** [comment]
Sorry. Forgot to include this in the original issue. My guess that it's related to react native breaking networking is because exclusively when running a my react-native project (only on the branch that has react-native, master doesn't have this problem, and no other Android projects cause this) the following message is logged to the emulator console (output of `~/Library/Android/sdk/tools/emulator`, not the application logs themselves) every 3-4 seconds:

```
CANNOT TRANSLATE guest DNS ip
```

**Comment by taylorren** [comment]
I agree with @aem.

I am running `react-native` generated programs and this message keeps popping up. The emulator goes well on Internet surfing.

**Comment by mdjnewman** [comment]
I'm having the same problem.

ATM I'm taking a look to see if this is only an issue in the latest Android tooling - I wasn't getting this error earlier last week.

Interestingly fetching the bundle is fine, but accessing localhost:4000/foo (for example) using fetch() doesn't work, even though the same URL is accessible through Chrome.

**Comment by NameNull** [comment]
same issue

**Comment by fast-one** [comment]
Same issue

**Comment by baer** [comment]
See this issue on the Android issue tracker

https://issuetracker.google.com/issues/37139091

**Comment by charpeni** [comment]
Thank you for this detailed issue.

Even browsing in Chrome trigger this error, however requests all seem to work correctly.

On a full React Native application, if the packager can't be reached a red screen will be displayed saying that it can't reach X ip address. While on React Native integration into an existing application the application seem to just not work. 

I'd say to verify every IP address in your application and be sure every connections can be reached. I had the same issue `CANNOT TRANSLATE guest DNS ip`, fix IP address fixed the application but I still get the same log output into my emulator. So I guess it's not being popped by React Native.

Just let me know if it was your case, so we can triage this issue.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
