### ISSUE TITLE
java.lang.OutOfMemoryError Android Ram 1GB

### ISSUE THREAD

**Issue by tanmynguyen** [facebook/react-native#13379]
### Description

<img width="906" alt="screen shot 2017-04-07 at 17 00 23" src="https://cloud.githubusercontent.com/assets/11315567/24795522/cc47de6e-1bb3-11e7-8a8b-7379874cf01d.png">

Hi Team.

### Reproduction Steps and Sample Code

 I see issue when view list image in android?

### Solution

<application
      android:name=".MainApplication"
      android:allowBackup="true"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      **android:largeHeap="true"** 
      android:theme="@style/AppTheme">

What needs to be done to address this issue? Ideally, provide a pull request with a fix.

### Additional Information

* React Native version: 0.42
* Platform: Android

**Comment by mobinni** [comment]
Couple of questions:
- Are you using the ListView to show images? 
- What are the dimensions and size of the images you're loading?

Setting up largeHeap does not necessarily solve your problem, it rather masks the problem of your application using a large amount of memory.

I would suggest upgrading to 0.43.2 and using FlatList with virtualization to clean up the memory of your listview. As well as look into what the sizes are of the images you are loading, because I've been able to load list views with 2 000 000 images through virtualization without memory issues

**Comment by tanmynguyen** [comment]
Thanks @mobinni !

> Are you using the ListView to show images?
--> No. I use ScrollView to show list image

> What are the dimensions and size of the images you're loading?
<img width="1123" alt="screen shot 2017-04-13 at 16 35 47" src="https://cloud.githubusercontent.com/assets/11315567/24999325/46470fe8-2067-11e7-9c2d-46f161dbfb9b.png">

**Comment by hramos** [comment]
Please use FlatList in this case.
