### ISSUE TITLE
Why there are show two icon after Installed in the android 

### ISSUE THREAD

**Issue by Hermaner** [facebook/react-native#13378]
Why there are show two icon after Installed in the android 
![111](https://cloud.githubusercontent.com/assets/12965639/24795268/59ef7e32-1bbb-11e7-9289-eb0f244c0c30.jpg)

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
