### ISSUE TITLE
WebView Crashes app when you zoom fully in or out 

### ISSUE THREAD

**Issue by aidan2129** [facebook/react-native#13374]
Description

I tried using the Webview on when i zoom out/in on any site fully it crashes the app every time. I have tested on other websites and i cant get it to happen on sites that don't allowing zooming.

Reproduction Steps and Sample Code

Here is an example of the code being rendered.

```
return (
            <View style={styles.container}>
             <WebView
                    source={{ uri: 'http://www.google.com/' }}
                    style={styles.body} startInLoadingState
                >
    </WebView>
</View>

);
```

Solution

Stop the app crashing when the WebView is fully pinched to zoom in or out.

Additional Information

React Native version: 0.42.0
Platform: Android (Not tested on IOS)
Development Operating System: Linux
Dev tools: Android studio 2.2.3 and Android version is targeted for 6.0.1

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by aidan2129** [comment]
Seems to be fixed in the latest release
