### ISSUE TITLE
'React/RCTEventEmitter.h' file not found - RN 0.43.2

### ISSUE THREAD

**Issue by luckyleap** [facebook/react-native#13371]
### Description
1. Initialized new react native project following the react native getting started.
2. Encounter failed build with the error within terminal:
`'React/RCTEventEmitter.h' file not found`

### Reproduction Steps and Sample Code

`react-native init AwesomeProject`
`cd AwesomeProject`
`react-native run-ios`

Result:
`fatal error: 'React/RCTEventEmitter.h' file not found`

--Running in XCode--
![image](https://cloud.githubusercontent.com/assets/9031090/24787851/7fae0040-1b38-11e7-94a7-65808d743c56.png)

### Additional Information

* React Native version: 0.43.2 (latest)
* Platform: iOS
* Development Operating System: macOS Sierra v10.12.4 (latest)
* Dev tools: XCode v8.3.1 (latest)
* Build Options on Xcode (default)
![image](https://cloud.githubusercontent.com/assets/9031090/24787051/ec794900-1b33-11e7-92b0-7f39b9c25be8.png)

**Comment by guangmingzizai** [comment]
Same issue.

**Comment by giordy** [comment]
I confirm I'm gettting it too unfortunately. RunninUsing React Native 0.43.2 too

**Comment by luckyleap** [comment]
I have seen and done the procedure before. It has not worked for me still :/ 
I tried adding the scheme in the order you described but it has also not worked.
It seems my RCTLinking is still broken because I still get:
'React/RCTEventEmitter.h' file not found in xcode

**Comment by guangmingzizai** [comment]
I solved this problem yesterday with:
1. Replace all `#import "RCT*.h"` with `#import <React/RCT*.h>`.
2. Since I have used CocoaPods, my RN native modules in Pods still had errors. I haven't found the solution, so I moved my RN native modules from Pods to project, it works.

*Ensure your have unchecked `Parallelize Build` and removed all `react-native` related `header search paths` from all targets.*

**Comment by alxvallejo** [comment]
@guangmingzizai The documentation for Firebase says to use react-native as one of the header search paths. Can you explain why you're removing them?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by debrice** [comment]
@hramos I just endup on that thread because I'm facing this issue. It might not be dead

**Comment by hramos** [comment]
@debrice that's entirely possible. See my last comment for next steps.

**Comment by dylanrhodius** [comment]
Sometimes you just need to make sure you are building React first, before building anything else.

![Uploading reactFirst.png…]()

**Comment by hugoh1995** [comment]
Facing the same issue with the latest version of React Native.

**Comment by timsatterfield** [comment]
+1

react-native-cli: 2.0.1
react-native: 0.50.3
osx: 10.13.2
xcode: 9.2

**Comment by jasdeepsingh** [comment]
Having the same issue, any help would be highly appreciated? Anyone?

**Comment by jdnichollsc** [comment]
Same issue here:
```
react-native-cli: 2.0.1
react-native: 0.52.1
```

**Comment by Neuroforge** [comment]
Same issue on mac with Xcode Version 9.2 (9C40b)

Same error, different file!

<img width="875" alt="screen shot 2018-02-01 at 10 28 15 am" src="https://user-images.githubusercontent.com/1474186/35648673-5fa1051e-073b-11e8-93c2-b3a0f5841f24.png">

This procedure did not work for me.... https://github.com/facebook/react-native/issues/12042#issuecomment-275025960

Also, i've tried the following from this link.... (https://github.com/facebook/react-native/issues/12042#issuecomment-275025960)

> To solve the issue, you have to do the following:
> 
> In Xcode, go to the project scheme (Product -> Scheme -> Manage Scheme -> double click your project).
> Click on the 'Build' option at the left pane.
> Uncheck 'Parallelize Build' under Build Options.
> Then in Targets section, click '+' button then search for 'React'. Select it and click 'Add'.
> 'React' should now appear under Targets section. Click and drag it to the top so that it will be the first item in the list (before your project).
> Clean the project and build.

However, i could only get to this part where React was grayed out..... :/

<img width="899" alt="screen shot 2018-02-01 at 10 29 27 am" src="https://user-images.githubusercontent.com/1474186/35648674-619aa834-073b-11e8-98bb-5c7ce6ccfbdd.png">


My project is now just dead in the water. :/

**Comment by gramster** [comment]
Same issue
react: 16.2.0
react-native:0.53.2
MacOS: 10.13.3
XCode: 9.2

**Comment by ideasownersco** [comment]
same issue

**Comment by tseck** [comment]
same issue
any solution yet?

**Comment by tseck** [comment]
hi there,

fyi: *react-native upgrade* did the job for me 👍

**Comment by zedtux** [comment]
I'm having this issue with React-Native 0.55 and Calabash from the `-cal` target (while the non `-cal` target compiles just fine).

**Comment by acomito** [comment]
I had this crop up when I added react-native-sentry
