### ISSUE TITLE
too many images showed abnormal, Who can help me

### ISSUE THREAD

**Issue by zhouffan** [facebook/react-native#13383]
I have a question, the scrollview nested many image picture, then the picture is like a flower screen or display incomplete.Don't know if other people have met, can help with analysis of where should I start.

android : 4.4.2;    rn version: 0.35

![Uploading 20170407183438.jpg…]()

**Comment by zhouffan** [comment]
![20170407183438](https://cloud.githubusercontent.com/assets/10229738/24796891/9476aa0c-1bc1-11e7-9b8a-04db546b8ed0.jpg)

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
