### ISSUE TITLE
right to left 

### ISSUE THREAD

**Issue by cyaxares** [facebook/react-native#13391]
I'm using a RTL language, If  I  change the app into RTL and android device's language is English, the place of Icones in left for e.g turn to right . and If I change it into LTR  and device's language is Arabic for instance, everything located in right turns to left. Is there anyway to fix the app so that everything is showed the same formation??
React-Native Version 0.42.0

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

**Comment by annelorraineuy** [comment]
@cyaxares Read this https://facebook.github.io/react-native/blog/2016/08/19/right-to-left-support-for-react-native-apps.html
