### ISSUE TITLE
Set color of refresh indicator in FlatList

### ISSUE THREAD

**Issue by ragnorc** [facebook/react-native#13392]
With RefreshControl the color of the refresh indicator and some other props could be set. Is this still possible with FlatList?

**Comment by PARAGJYOTI** [comment]
Flatlist is just a higher component based on Virtualizedlist . Look at the source code here https://github.com/facebook/react-native/blob/master/Libraries/Lists/FlatList.js 

So , in order to change the refreshControl color , set the property in the source code or add your own props to it . Run react-native start again to see the changes .

**Comment by PARAGJYOTI** [comment]
Sorry , you have to pass the props into Scrollview Component in VirtualizedList class . See https://github.com/facebook/react-native/blob/master/Libraries/Lists/VirtualizedList.js

**Comment by MattyK14** [comment]
Would be useful if this was a part of the React-Native codebase

**Comment by Jacse** [comment]
@MattyK14 does that still work? Can't find it documented anywhere, seems like `RefreshControl` provided by `VirtualizedList` takes precedence over passed props.

**Comment by MattyK14** [comment]
@Jacse I'm not on 0.46 yet, but as of 0.45.1 it still works.

**Comment by inifaisal** [comment]
just add colors props on RefreshControl
`
<RefreshControl
         refreshing={this.state.isRefreshing}
         onRefresh={this.onRefreshList.bind(this)}
         title="Pull to refresh"
         tintColor="#fff"
         titleColor="#fff"
        colors={["red", "green", "blue"]}
/>
`
