### ISSUE TITLE
WebView inject javascript before window.onload

### ISSUE THREAD

**Issue by ccorcos** [facebook/react-native#13394]
### Description

When using the [WebView API](https://facebook.github.io/react-native/docs/webview.html) to communicate over `postMessage` and inject Javascript using the `injectedJavaScript` prop, the webpage has to wait until `window.onload`.

In the [example](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/messagingtest.html), if you run `window.postMessage('"Hello" from the web view');` without waiting for the button click, you will see an exception because React Native hasn't injected postMessage yet.

### Solution

Not sure about the specifics, but ideally the React Native injected code would run before the document javascript runs.

### Additional Information

react-native-cli: 2.0.1
react-native: 0.43.2
ProductName:	Mac OS X
ProductVersion:	10.12.3
BuildVersion:	16D32
Xcode 8.3
Build version 8E162

**Comment by faceach** [comment]
As React Native use UIWebView, I think you can't inject JavaScript before WebView load finished.

But in WKWebView, you can inject JavaScript at document start via API:
`- (instancetype)initWithSource:(NSString *)source injectionTime:(WKUserScriptInjectionTime)injectionTime forMainFrameOnly:(BOOL)forMainFrameOnly;`

**Comment by ccorcos** [comment]
Hmm. Well you could fetch the HTML as a string and inject JavaScript that way...

I'm considering using React Native instead of Cordova so this might be out of scope.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by carsonwah** [comment]
Experiencing the same problem.
RN:
```
<WebView
  onMessage={this.handleMessage}
  source={{uri: url}} />
```
html js:
```
window.postMessage('hello');
```

It won't work.

So, I use this workaround:
```
setInterval(() => {window.postMessage('hello');}, 500)
```

Another issue talking about this: https://github.com/facebook/react-native/issues/11594

**Comment by diegolaciar** [comment]
Hi @ccorcos 

I'm  trying to do the same as you, also I have the same issue. Did you find a solution ?

Thanks
-----------------------------------------------------------------
@ccorcos "...I'm considering using React Native instead of Cordova..."

**Comment by ccorcos** [comment]
Nope. Using Cordova.
