### ISSUE TITLE
TouchableHighlight vs TouchableWithoutFeedback

### ISSUE THREAD

**Issue by jaygarcia** [facebook/react-native#134]
I noticed a huge issue with TouchableHighlight where there is a significant delay with the onPressIn method being called, making this component next to unusable for real-time feedback.

The TouchableWithoutFeedback component, however provided realtime feedback, but being that it doesn't conform to the same <View> component that TouchableHighlight does, styles break.

![touchable](https://cloud.githubusercontent.com/assets/180031/6560249/2c8e9346-c65f-11e4-8383-5eee080e81ee.gif)

**Comment by jmstout** [comment]
Has this been addressed? I'm experiencing the same delay, regardless of whether the TouchableHighlight component is in a ScrollView or just a View.

It's not the biggest deal, since an easy workaround is to just extend the component and override the delay:
```javascript
class TouchableButton extends TouchableHighlight {
  touchableGetHighlightDelayMS() {
    return 0;
  }
}
```

However, I am wondering if there could be a better implementation. Currently, the stock TouchableHighlight component is noticeably unresponsive.
