### ISSUE TITLE
I am getting "Unable to resolve module `react

### ISSUE THREAD

**Issue by achakra21** [facebook/react-native#13404]
I am getting the below error 

![capture](https://cloud.githubusercontent.com/assets/1450925/24835491/519dc358-1d21-11e7-9239-52cc78cfe834.JPG)
The development server returned response error code: 500

URL: http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false

Body:
{"from":"D:\\AwesomeProject\\index.android.js","to":"react","message":"Unable to resolve module `react` from `D:\\AwesomeProject\\index.android.js`: Module does not exist in the module map or in these directories:\n  D:\\AwesomeProject\\node_modules\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start --reset-cache`.","name":"UnableToResolveError","type":"UnableToResolveError","errors":[{}]}
onResponse
    DevServerHelper.java:332
execute
    RealCall.java:126
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1112
run
    ThreadPoolExecutor.java:587
run
    Thread.java:818
	
	
	{"from":":\\AwesomeProject\\index.android.js","to":"react","message":"Unable to resolve module `react`

i tried every workaround given by the log still it's not working..

**Comment by Air-Miha** [comment]
@achakra21,

Is this the project in question:

https://github.com/achakra21/ReactNative-AwesomeProject

?

Could you include _react-native_ and _react_ as dependencies in your package.json, run _npm install_ and then try again?

**Comment by achakra21** [comment]
Yes right but how it was working previously with out  that ? I Am surprised in fact now i fixed the issue by downgrading the React-Native lib

**Comment by theohdv** [comment]
I think there was a changement in React 0.43 that broke absolute path from require() method. I had to change all my path to relative one and the it worked.

**Comment by achakra21** [comment]
@theohdv  How did you can you put the code

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
