### ISSUE TITLE
D3 visualization has performance issue on Android

### ISSUE THREAD

**Issue by gpminsuk** [facebook/react-native#13400]
### Description

I implemented Bubble data visualization with d3 simulation and it has performance issue only on Android that doesn't happen on iOS.
Bubbles are rendered as 'absolute' position and view with border radius.
`<View
                key={data.id}
                style={{
                  backgroundColor: 'transparent',
                  position: 'absolute',
                  transform: [
                    { translateX: width / 2 - 100 + x },
                    { translateY: height / 2 - 100 + y },
                    { scale: radius / 100 },
                  ]
                }}>
                <View
                  style={{
                    alignItems: 'center',
                    justifyContent: 'center',
                    backgroundColor: 'white',
                    width: 200,
                    height: 200,
                    borderRadius: 100,
                  }}>
                  <Text
                    style={{
                      fontSize: 44,
                      fontWeight: 'bold',
                      color: 'black',
                      padding: 20,
                      backgroundColor: 'transparent'
                    }} numberOfLines={2}>{data.name}</Text>
                </View>
              </View>`
![image](https://cloud.githubusercontent.com/assets/3460594/24830533/ef2cf7e6-1c3c-11e7-929c-84a51626c875.png)
It is very slow on real devices.
Can you please help investigate/diagnose this issue?

### Reproduction Steps and Sample Code

Sample code
https://github.com/gpminsuk/react-native-d3-bubble

### Additional Information

* React Native version: 0.43.2
* Platform: only Android
* Development Operating System: Windows
* Dev tools: vscode

**Comment by ssssssssssss** [comment]
https://facebook.github.io/react-native/docs/view.html#rendertohardwaretextureandroid

Does it help?

**Comment by gpminsuk** [comment]
@ssssssssssss No it didn't help. As in the screenshot, I don't think it is really heavy rendering task. I wonder how it affects performance?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
