### ISSUE TITLE
app:bundleReleaseJsAndAssets depends on har-validator bin

### ISSUE THREAD

**Issue by bilby91** [facebook/react-native#13412]
### Description
Android gradle task `app:bundleReleaseJsAndAssets` depends on har-validator. har-validator is a dependency of the `request` package. The current constraint for `request` is `^2.79.0`. Since `request 2.80` they updated `har-validator` to version 4.2 and this new version doesn't come with the bin executable, they split the project into `har-cli`. This generated an issue when having `request` >= 2.80. 

### Solution

Possible solutions could be to force 2.79 in `request` or add `har-cli` as a dependency. I really don't now source code during the building is the responsable for the hal-validator call.

### Additional Information

* React Native version: 0.41.2
* Platform: Android
* Development Operating System: macOS 10.12.3 (16D32)
* Dev tools: SDK Version 23. Gradle 1.5.0

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
