### ISSUE TITLE
Webview navigateTo

### ISSUE THREAD

**Issue by gerardus1995** [facebook/react-native#13414]
### Description

I've been looking if theres a webview property that allow us to change the page we are currently at. Like a navigateTo so when something happens we can navigate to that page automatically (being later able to use goBack() to go back to all the pages previous to this one).

### Reproduction Steps and Sample Code

In his._onNavigationStateChange.bind(this) i will check the url we are currently at, if some particular url appears, i want to redirect to another different url. How can i achieve that?

              <WebView
                ref={'webview'}
                onNavigationStateChange={this._onNavigationStateChange.bind(this)}
                onLoadStart={()=>{
                  this.setState({refreshing: true});   
                }}
                onLoadEnd={()=>{
                  setTimeout(() => {
                    this.setState({refreshing: false});  
                  }, (Platform.OS=="ios")?0:500);  
                }}
                startInLoadingState
                renderError={this.renderError}
                source={{uri: GLOBAL.WEBVIEW_URL+this.state.country+'/'}}
                injectedJavaScript={'$(".header__main, .favorite, .footer__main, .footer-adbox, .footer-copyright").css({"display": "none"});'}
              /> 

### Additional Information

* React Native version: 0.42.0
* Platform: both
* Development Operating System:MacOS

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

**Comment by kodkisot** [comment]
With such terrible lack of documentation, it took my whole day to figure out how to do exactly the same thing for a social media app login screen. Sufficient explanations are needed at least before redirecting users to stackoverflow.com in my opinion, otherwise, the library's coders have to provide needed support, especially for the developers who're in learning curve just like me. The proof is as below : 

https://facebook.github.io/react-native/docs/webview.html#injectjavascript

As you can see, you get NOTHING.

The main problem of the question is that the setState function is not refreshing the WebView component with a new url, the source.uri is a frozen variable and cannot be changed by any prop type function but one indirect trick, and the users are redirected to unwanted urls, especially on social media apps' login pages. The developer gets stuck, loses time, vice versa.

So let's see how to do the magic (urls are masked, explanations commented out) : 

```
import React, { Component } from 'react';
import { View, WebView } from 'react-native';
const LOGIN_URL = 'https://......';
class myComponent extends Component {
    _onNavigationStateChange(webViewState){
        // set your conditions based on the current url (of the navigation) to keep user in your auth flow safe, 
        // or set your filters based on unwanted urls
        let authFlow = false;
        let condition1 = (webViewState.url.indexOf('some_url_or_its_variable_1') !== -1) : true ? false;
        let condition2 = (webViewState.url.indexOf('some_url_or_its_variable_2') !== -1) : true ? false;
        // go on with the previous logic ()
        if (condition1 || condition2) {
            authFlow = true;
        }
        // debugging is good...
        console.log(condition1, condition2, authFlow);
    
        // warning, danger zone here! The user clicks a link on the social media app's login page
        if(!authFlow && webViewState.loading) { 
            // learn about some underlying thingies
            console.log(this.refs["WebView"]);
            console.log(webViewState);
            // redirect user back to your first login url, BEFORE new navigation url is loaded (see how
            // webViewState.loading is being checked for true, if it's false, then it means the page loading is 
            // complete)
            let redirectCode = `window.location = '${LOGIN_URL}';`;
            this.refs["WebView"].injectJavaScript(redirectCode);
        }
    }
    render() {
        return(
            <View>
                <WebView
                    source={{uri: browserUrl }}
                    scalesPageToFit={false}
                    javaScriptEnabled={true}
                    startInLoadingState={false}
                    scrollEnabled={false}
                    onNavigationStateChange={this._onNavigationStateChange.bind(this) }
                    ref="WebView"
                />
            </View>
        );
    }
}
export default myComponent;
```
Now, I would prefer an example code like above provided by the native library team, but a fair amount of explanation of the logic would be enough as well, I guess. Hope this helps to build a better library and a better community.

**Comment by hramos** [comment]
The docs are hosted in this repo, feel free to send a PR!

**Comment by aliozinan** [comment]
I would love to, if there was a reference point for what stands where for what, instead of pulling my hair till i find them.

**Comment by hramos** [comment]
You can find a link to the actual file that contains the docs by scrolling to the bottom of most docs:

![screen shot 2017-08-28 at 11 16 41 am](https://user-images.githubusercontent.com/165856/29787109-7b2c6c80-8be2-11e7-91cd-1c5512057abc.png)

If you click on that link, you'll see these docs are generated from WebView.ios.js.

**Comment by aliozinan** [comment]
thanks for the info, i ll be releasing this type of tricks upon discovering them
