### ISSUE TITLE
[iOS][Android]is there a way to check the Current Version of an apps

### ISSUE THREAD

**Issue by damnfateh** [facebook/react-native#13423]
![image](https://cloud.githubusercontent.com/assets/7897935/24866117/d40b3580-1e3b-11e7-92e1-c313b525e3dc.png)

is there a way to check the current version in google play store or app store.
I want the app to check the google play store or app store for current version and compare with user's current version if it's not equal then alert for update
there are a lot of libraries, but none are able to check current version in google play store or app store, or if there's any i don't know.
please help....

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
