### ISSUE TITLE
Error after upgrading to React Native v0.43.3

### ISSUE THREAD

**Issue by EgaSetya** [facebook/react-native#13435]
My project was running with no problem after upgrading however I got below error after upgrading:

![852106577_16469732896538723675](https://cloud.githubusercontent.com/assets/8707375/24894115/4415ea2a-1eb2-11e7-98d6-8c640323c861.jpg)

And when I run **npm start** I got below error:
<img width="570" alt="screen shot 2017-04-11 at 12 30 08 pm" src="https://cloud.githubusercontent.com/assets/8707375/24894162/a3376a1a-1eb2-11e7-819c-cd7416d173aa.png">

How can I fix this?

**Comment by sospedra** [comment]
Probably you already tried this but:

1. Close all the RN related processes: the packager, em/simulators, etc.
2. `rm -rf node_modules`
3. `npm i` // `yarn`
4. `watchman watch-del-all`
5. `npm start -- --reset-cache`
6. `react-native run-{os}`

**Comment by EgaSetya** [comment]
I got error on step 3,
<img width="560" alt="screen shot 2017-04-11 at 4 01 00 pm" src="https://cloud.githubusercontent.com/assets/8707375/24901074/245f395c-1ed0-11e7-98df-ab3729d01107.png">

**Comment by MyGuySi** [comment]
Do you have any errors before the screenshot you posted?

I'm getting `@providesModule naming collision` so wondering if you're seeing the same thing

**Comment by sospedra** [comment]
@EgaSetya `EISDIR` use to happen when a `package.json` is not found in the repo. Are you placed at root of your project? Is there a `package.json`? If don't just run `npm init`

**Comment by EgaSetya** [comment]
@MyGuySi I don't have any error before updating my react native version, just a few conflicts at MainApplication.java

@sospedra package.json is there inside the project folder.

**Comment by zhangzhhz** [comment]
i got this a few times. i usually delete the whole node_modules, android/build and android/apps/build directories (Not at my computer now so the build directories listed here may be incorrect, and I only do Android). Then npm i or yarn, followed by react-native start and react native run-android. I use Windows.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
