### ISSUE TITLE
The Windows packager launcher script does not pass all arguments

### ISSUE THREAD

**Issue by idancali** [facebook/react-native#13445]
### Description

I'm hooking into the packager script and on Windows the script does not pass all the arguments, as the non-windows script does.

### Reproduction Steps and Sample Code

If you execute the `packager/launchPackager.bat` with arguments, those arguments are not passed along the the underlaying node process (cli.js)

### Solution

This line in the`packager/launchPackager.bat` script

`node "%~dp0..\local-cli\cli.js" start
`

needs to become this:

`node "%~dp0..\local-cli\cli.js" start %*
`

That's all.

### Additional Information

* React Native version:  [0.43.3]
* Platform: [both]
* Development Operating System: [Windows]
* Dev tools: [not applicable]

**Comment by idancali** [comment]
I'm working on a pull request to fix this.

**Comment by hramos** [comment]
Hi there! This issue is being closed because {:search=>"repo:facebook/react-native is:open is:issue updated:<2017-05-25 -label:\"Good First Task\" -label:\"Help Wanted\" ", :message=>"it has been inactive for a while"}. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
