### ISSUE TITLE
RN43 can't open dev menu when integrating with existing iOS project

### ISSUE THREAD

**Issue by hitbear518** [facebook/react-native#13444]
### Description

I have an iOS app integrating react-native, after upgrade to 0.43.3, cmd+D can't open dev menu any more.
I tried a empt project, i didn't work either.

### Reproduction Steps and Sample Code

I have an empty repo which can reproduce this bug
https://github.com/hitbear518/IntegrationBug

I haven't test Android yet

### Additional Information

* React Native version: 0.43.3
* Platform: iOS
* Development Operating System: Mac OS 10.12.4
* Dev tools: Xcode 8.3.1, Swift 3.0

**Comment by mgerb** [comment]
Experiencing the same issue here except on an actual device (iOS). The shake gesture is not working to bring up the dev menu. I noticed it after I added React to my podfile on 0.42. I upgraded to 0.43.3, but still no success.

I saw a recommendation somewhere to add the subspec 'DevSupport' to the React pod, but that also did not solve the issue for me.

I then removed React from my podfile completely and then the dev menu opened up just fine. This is a frustration for me because I have other dependencies that require React to be in my podfile.

**Comment by hitbear518** [comment]
@mgerb Thank you! add DevSupport to podfile solved my problem.
I'm not sure what do you mean by add React to podfile.

Below is my podfile, hope it will help somewhat

```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'InteTry' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InteTry
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTImage',
    'RCTWebSocket', # needed for debugging
    'RCTNetwork',
    'RCTLinkingIOS', # dependency of react-native-router-flux
    'RCTAnimation', # require by useNativeDriver
    'RCTCameraRoll',
    'RCTActionSheet',
    'RCTGeolocation',
    'DevSupport',
  ]
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

end

```

**Comment by hitbear518** [comment]
🤔After add DevSupport to podfile, it worked fine on simulator, but I encountered another issue`No bundle URL present` on iOS device, I'm not sure what caused this.
