### ISSUE TITLE
[WebView] Caching contents WebView using the cachePolicy

### ISSUE THREAD

**Issue by arunshan** [facebook/react-native#1344]
Currently the UIWebView is not caching the contents of webview. We need a provision to set cachePolicy if there is a boolean prop to set cache policy to the webview.

``` XCode
  NSMutableURLRequest *theRequest = [NSMutableURLRequest requestWithURL:URL cachePolicy:NSURLRequestReturnCacheDataElseLoad timeoutInterval:15.0];
  [_webView loadRequest:theRequest];
```

**Comment by brentvatne** [comment]
@arunshan - looks like a simple change, can you submit a PR?

**Comment by jaygarcia** [comment]
I've submitted a pull request for this.  @brentvatne, if you have any guidance on things that can/should be changed, please feel free.

**Comment by alexisvincent** [comment]
What is the status of this? How can I enable this for my local project in the meantime?

**Comment by alexisvincent** [comment]
@brentvatne Can @jaygarcia's solution be merged?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/webview-caching-contents-webview-using-the-cachepolicy

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by aqnaruto** [comment]
oh,we need webview cathe ,it is very important for me!@mkonicek

**Comment by vvavepacket** [comment]
this is important, pls dont abandon this.

**Comment by NingZaizai** [comment]
on man, why close this

**Comment by indrasantosa** [comment]
Yes! We need this as well

**Comment by sujitpk-perennial** [comment]
any update.. waiting still in feb 18

**Comment by goldengecko** [comment]
Yeah, I need this too.

**Comment by ErickVoodoo** [comment]
So, there are no any news? 
Maybe someone knows how to save loaded HTML and paste it to Webview?

**Comment by goldengecko** [comment]
@ErickVoodoo If you are looking to do that as a workaround instead of having a WebView cache, you could grab the source and save it, then use a webview like `<WebView source={{html:getYourContent()}} />` to load and display the required content. If you also had resources like images and css etc that you wanted to cache locally you'd have to reference them appropriately too - not sure of the details of that side of things, but maybe this would be a starting point.

Definitely not where we _want_ to head, but maybe a workaround that would be useful in the meantime.

**Comment by ErickVoodoo** [comment]
@goldengecko Yesterday I did some work to solve my issue, I save HTML to my local storage, but: there is one issue, CSS and JS code which were pasted in <head> tag were not loaded. So, I saved plain HTML without logic and styles, to be honest, this isn't what I want to get)

**Comment by miraan** [comment]
This would be great. Also, the solution to just save the HTML resource to disk and load with `<WebView source={{html: resource}} />` doesn't let you play with the URL parameters nicely.
