### ISSUE TITLE
OpenGL based native view appears blank when connected to JS debugger on iOS

### ISSUE THREAD

**Issue by tianxind** [facebook/react-native#13451]
### Description

I have enjoyed this framework a lot, but here is something that has been bugging me for a few months: I have written my own UIView that makes OpenGL calls to render itself. It works fine if I don't enable "Debug JS remotely" or "Reload JS" after the app builds and loads the first time. However, if I do those two things above, the OpenGL view will be completely blank. I integrate this view with RN using RCTViewManager.

### Reproduction Steps and Sample Code
I can't really attach all my code here since there are a lot of OpenGL code, but this is how I initialize the OpenGL view:
`  - (instancetype)initWithContext:(EAGLContext *)context
    {
      self = [super init];
      if (self) {
      // Get the layer
      CAEAGLLayer *eaglLayer = (CAEAGLLayer *)self.layer;
    
      eaglLayer.opaque = TRUE;
      eaglLayer.drawableProperties = [NSDictionary dictionaryWithObjectsAndKeys:
                                    [NSNumber numberWithBool:FALSE], 
      kEAGLDrawablePropertyRetainedBacking, kEAGLColorFormatRGBA8, 
      kEAGLDrawablePropertyColorFormat, nil];
    
    _context = context;
    // Initializes the renderer.
    [EAGLContext setCurrentContext:_context];
    _renderer = [[OpenGLRenderer alloc] initWithContext:_context AndDrawable:(id<EAGLDrawable>)self.layer AndScreenScale:self.contentScaleFactor];
    [_renderer setupOpenGLWithDrawable:(id<EAGLDrawable>)self.layer];
    
    _rendering = FALSE;
    _frameInterval = 1;
    _displayLink = nil;
    // Create the display link and set the callback to our drawView method
    _displayLink = [CADisplayLink displayLinkWithTarget:self selector:@selector(drawView:)];
    
    // Set it to our _animationFrameInterval
    [_displayLink setFrameInterval:_frameInterval];
    
    // Have the display link run on the default run loop (and the main thread)
    [_displayLink addToRunLoop:[NSRunLoop currentRunLoop] forMode:NSRunLoopCommonModes];
    _rendering = TRUE;
    
    _lastZoom = 1.0f;
    }
     return self;
  }
`

Here is the code to create a new instance through RCTViewManager:

`- (UIView *)view
{
  PoserView *view = [[PoserView alloc] initWithContext:_context];
  [view setupGestureRecognizers];
  view.delegate = self;
  return view;
}`

### Additional Information

* React Native version: 0.42.3
* Platform: iOS
* Development Operating System: MacOS
* Dev tools: XCode

**Comment by hramos** [comment]
Hi there! This issue is being closed because {:search=>"repo:facebook/react-native is:open is:issue updated:<2017-05-25 -label:\"Good First Task\" -label:\"Help Wanted\" ", :message=>"it has been inactive for a while"}. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
