### ISSUE TITLE
Border turned solid on Android after upgrading from RN 41.2 to 43.3

### ISSUE THREAD

**Issue by RobTS** [facebook/react-native#13464]
As all issues that are somewhat similar are closed, I'm opening this one: The border turned solid after upgrading from RN 41.2 to 43.3. Only Android is faulty, on iOS things work.

Styling:

```
  imagePlaceholder: {
    borderStyle: "dashed",
    margin: 10,
    padding: 30,
    alignItems: "center",
    borderColor: Colors.gray,
    borderWidth: 3
  },
```

**Comment by pawellewandowski** [comment]
+1

**Comment by JonatanRydh** [comment]
Having the same problem. Interestingly the border becomes dashed again if adding a borderRadius larger than zero.

**Comment by chethann** [comment]
Thank you @JonatanRydh. You same a lot of my effort. Hope it gets fixed.

**Comment by jkomyno** [comment]
The bug persists with version 0.44, at least on Android (haven't had the possibility to test on iOS yet), but @JonatanRydh hack did it! You can simply put `borderRadius: 1` to a View and you're done

**Comment by zoharlevin** [comment]
on Android with RN 0.43.1 (Expo SDK 16.0.0):
if the `borderRaidus` is larger than zero that keeps the dashed behavior **only** if using `borderWidth` for all borders but if you use `borderBottomWidth` then you see no border at all (if using `dashed`).
here's the expo:
https://snack.expo.io/Sy-x51Ym-

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by ricbermo** [comment]
Hi, this issue is live on latest RN `0.49.3`. The workaround still works, though.

**Comment by hramos** [comment]
Please submit a new issue.

**Comment by rpavlovs** [comment]
Exact same issue RN 0.50.4
@hramos re-open?

**Comment by hramos** [comment]
Please submit a new issue.
