### ISSUE TITLE
textInput error iOS

### ISSUE THREAD

**Issue by mhdayyoob** [facebook/react-native#13462]
I add a textInput field and run but it never shown on my simulator after I give a style like height-40 after the run the text input were shown. but textInput is hidden by the keyboard. I can't see what I am writing. 

Please fix this.
Thanks in advance

### Additional Information

* React Native version: [0.40]
* Platform: [iOS]
* Development Operating System: [MacOS]
* Dev tools: [ Xcode ]

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
