### ISSUE TITLE
Why does RN 0.43 use React 16.0.0-alpha

### ISSUE THREAD

**Issue by xareelee** [facebook/react-native#13469]
I did not find docs about this question.

The latest stable version of React is `15.5.0`. I did not find any docs about React `16.0.0-alpha`. What are the major changes? 

I have many libs depending on React `15.x`. May I use React `15.5.0` instead of `16.0.0-alpha` with RN `0.43.x`?

**Comment by mobinni** [comment]
I believe this was answered in #13291

**Comment by CodeXtinction** [comment]
yes -_- 

```
react-native-svg@5.1.7 requires a peer of react@>=15.4.0 but none was installed.
```

**Comment by ide** [comment]
This is intentional because React Native is released on a monthly cycle and uses the code from Facebook's trunk, which was using React 16 alpha 6 at the time of creating the release branch.

> I have many libs depending on React 15.x. May I use React 15.5.0 instead of 16.0.0-alpha with RN 0.43.x?
No, RN 0.43 works only with React 16.0.0-alpha.6. Use that precise version.

> react-native-svg@5.1.7 requires a peer of react@>=15.4.0 but none was installed.
This is a nonsensical warning from npm/yarn. There's an issue open on the Yarn repo to improve these warnings (16.0.0-alpha.6 does potentially satisfy >=15.4.0 according to the semver document, it's just that the node-semver library that chooses not to).

**Comment by bensampaio** [comment]
This doesn't make much sense... Why release stable versions dependent on alpha versions? Either release React 16.0.0 or stick to 15.x I would say.

**Comment by kesha-antonov** [comment]
I agree with @bensampaio .
Few libraries do not use react alpha for now so I cannot update RN.

**Comment by xareelee** [comment]
The problem is that many libs depending on React are not going to update the React dependency to `16.0.0-alpha`.

This will raise some errors when testing. See https://github.com/storybooks/storybook/issues/893.

Please try to convince other open-source developers to update the React dependency by adding more docs.

**Comment by mleduque** [comment]
https://github.com/airbnb/enzyme/issues/928#issuecomment-301512728
