### ISSUE TITLE
[WebView] Webview Android 4.1 - mediaPlaybackRequiresUserAction

### ISSUE THREAD

**Issue by andrelimawork** [facebook/react-native#13473]
### Description

Opening a webview in Android 4.1 with the property mediaPlaybackRequiresUserAction = {false} causes the crash of the application.

### Reproduction Steps and Sample Code

Create a webview component with the property mediaPlaybackRequiresUserAction.

   <WebView
              bounces={true}
              automaticallyAdjustContentInsets={false}
              style={styles.webView}
              mediaPlaybackRequiresUserAction = {false}
              allowsInlineMediaPlayback = {false}
              source={{ html: this.state.html }}
              javaScriptEnabled={true}
              domStorageEnabled={true}
              canGoBack={true}
              decelerationRate="normal"
              scalesPageToFit={this.state.scalesPageToFit}
            />

### Solution

What needs to be done to address this issue? Ideally, provide a pull request with a fix.

### Additional Information

* React Native version: 0.43
* Platform: Android
* Development Operating System: MacOS
* Dev tools: Android Studio 1.5.1 SDK 16

Printscreen:
![screenshot_1492015049](https://cloud.githubusercontent.com/assets/1869154/24971760/ee88c0be-1fb0-11e7-9916-3339139ff6b1.png)

**Comment by hramos** [comment]
Can you provide sample code, or ideally a Snack?

**Comment by Luze26** [comment]
Sample code:
`import React, {Component} from 'react';
import {WebView, AppRegistry} from 'react-native';

class App extends Component {
  render() {
    return (
      <WebView
        source={{uri: 'http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_30fps_normal.mp4'}}
        style={{flex: 1}}
        mediaPlaybackRequiresUserAction={false}
      />
    );
  }
}

AppRegistry.registerComponent('Addeekt', () => (
  () => <App/>
));`
Reproduced with RN 0.45.1 and Android 4.1 .

If mediaPlaybackRequiresUserAction is set to false or true, the error appears.
Without mediaPlaybackRequiresUserAction, there is no error but the video is not displayed (the screen stays white).
Everything seems to work fine with Android 5.1

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
