### ISSUE TITLE
Image Source URI vs URL

### ISSUE THREAD

**Issue by mehcode** [facebook/react-native#13478]
When adding an image that references a remote file, Android accepts only `uri` and iOS accepts both `uri` and `url`. This is a frustrating bug as you can be working in iOS fine and it breaks silently in Android (images just don't render). Even in the examples this bug exists: [url](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/ImageExample.js#L659) vs [uri](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/ImageExample.js#L204) in the same file.

Looking at the [type definition](https://github.com/facebook/react-native/blob/master/Libraries/Image/ImageSourcePropType.js#L23), `uri` is the correct one. We should probably have a good error message if you use `url` instead. 

* React Native version: 0.43.0 (but the issue exists on master as well)
* Platform: both
* Development Operating System: MacOS

**Comment by hramos** [comment]
Can you send a PR to fix the documentation issue? We should be using `uri` consistently.

**Comment by mehcode** [comment]
@hramos 👌 https://github.com/facebook/react-native/pull/13496

**Comment by hramos** [comment]
Hi there! This issue is being closed because {:search=>"repo:facebook/react-native is:open is:issue updated:<2017-05-25 -label:\"Good First Task\" -label:\"Help Wanted\" ", :message=>"it has been inactive for a while"}. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
