### ISSUE TITLE
[Android] ReactRootView layout configuration inside native app

### ISSUE THREAD

**Issue by ahetawal-p** [facebook/react-native#13476]
Trying to add a ReactRootView to my existing layout which looks like this 

```
ReactRootView contentView = new ReactRootView(context);
LinearLayout container = (LinearLayout) parent.findViewById(R.id.view_container);
contentView.startReactApplication(reactInstanceManager, "MyComponent", null)
container.addView(contentView, -1, new LinearLayout.LayoutParams(MATCH_PARENT, WRAP_CONTENT));
```
With the above setup, my reactview never gets rendered, since the height is always 0.
I have to explicitly provide the height to my layout as -
```
container.addView(contentView, -1, new LinearLayout.LayoutParams(MATCH_PARENT, 200));
```

How does ReactRootView handles the layout params when embedded inside a android native app ?

**Comment by hslls** [comment]
I encountered the same problem.

**Comment by hramos** [comment]
Hi there! This issue is being closed because {:search=>"repo:facebook/react-native is:open is:issue updated:<2017-05-25 -label:\"Good First Task\" -label:\"Help Wanted\" ", :message=>"it has been inactive for a while"}. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by githubdoramon** [comment]
@ahetawal-p you just saved my life after a lot of struggle, hahahaha.... I can understand why, but people don't seem to give a f*** for using react-native with existing native apps, which I think is the best use for it. Thanks a lot
