### ISSUE TITLE
Packager is not overriding "package.json" browser file when it points to the main file

### ISSUE THREAD

**Issue by alexleonescalera** [facebook/react-native#13474]
### Description

The packager is not correctly overriding a file in `browser` (or `react-native`) field whenever it is pointing to the `main` file. This only happens when using relative paths starting with `./`.

That is:
```json
"main": "index.js",
"browser": {
  "./index.js": "./index-browserify.js"
}
```

This causes code intended only for server to be run on the browser.

The issue was found when using the [`websocket-stream`](https://github.com/maxogden/websocket-stream) library with React Native. Since the override doesn't happen, a "Cannot read property 'property' of undefined' error occurs.

### Reproduction Steps and Sample Code

To reproduce this error, please refer to this repository: https://github.com/alexleonescalera/ReactNative-npm-browser-issue

This React Native app attempts to use a forked `websocket-stream` library to reproduce the error. That fork includes a "hack" that serves as evidence of this being an issue.

**Doesn't work**
```json
"main": "index.js",
"browser": {
  "./index.js": "./stream.js"
}
```

Since `stream.js` is trying to override the `main` file.

**Works (but it is a hack, not a solution)**
```json
"main": "index.js",
"browser": {
  "./main.js": "./stream.js"
}
```

Given you move the contents of `index.js`file to `main.js`, and set `index.js` to simply `require('./main')`.

### Solution

The solution would be to allow the override to work even if the path is prepended by `./`.

The `browser` field documentation states using `./`, so no wonder libraries out there use that approach:
https://github.com/defunctzombie/package-browser-field-spec#spec

### Additional Information

* React Native version:
    ```bash
    react-native-cli: 2.0.1
    react-native: 0.43.2
    ```
* Platform: iOS
* Development Operating System: MacOS Sierra 10.12.4
* Dev tools: XCode 8.3.1, XCode Simulator App v10.0

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
