### ISSUE TITLE
Android Studio Update makes Android Setup Instructions obsolete

### ISSUE THREAD

**Issue by MoonTahoe** [facebook/react-native#13480]
There is a new android studio and the `android` and `android avd` commands have been deprecated. The AVD manager is different, the setup process is different. I was able to update Android Studio, setup an AVD, and run the android app, but the `react-native run-android` command took over 10 minutes to build and launch my project in the AVD.

Currently, the android setup instructions defined in the documentation do not reflect these changes.

**Comment by GuGuss** [comment]
As a side note, to have access to `avdmanager` and `sdkmanager` from the terminal, I simply added `/bin` to the _ANDROID_HOME_ path as followed:
```
export ANDROID_HOME=${HOME}/Library/Android/sdk
export PATH=${PATH}:${ANDROID_HOME}/tools/bin
export PATH=${PATH}:${ANDROID_HOME}/platform-tools
```

**Comment by hramos** [comment]
Hi there! This issue is being closed because {:search=>"repo:facebook/react-native is:open is:issue updated:<2017-05-25 -label:\"Good First Task\" -label:\"Help Wanted\" ", :message=>"it has been inactive for a while"}. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
