### ISSUE TITLE
Multiple image sources with local too

### ISSUE THREAD

**Issue by VinceBT** [facebook/react-native#13493]
Why is this not possible ?
```jsx
<Image
  resizeMode={Image.resizeMode.cover}
  source={[
    { uri: 'http://placehold.it/50x50', width: 50, height: 50 },
    { uri: 'http://placehold.it/500x500', width: 500, height: 500 },
    require('./assets/default_placeholder.jpg'),
  ]}
  style={{ flex: 1 }} />

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

**Comment by VinceBT** [comment]
How would StackOverflow help ? This is just a missing functionality.

Why isn't it possible to say that an image should search for increasing dimensions on the web and then ,if all the images are 404 or not available, chose the default placeholder in lieu of the others ?
