### ISSUE TITLE
Difference between React Bundle and React Release

### ISSUE THREAD

**Issue by ezos86** [facebook/react-native#13494]
`react-native bundle --entry-file index.ios.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios`

vs

`react-native run-ios --configuration Release`

I have run both before and it seems the --configuration Release does a lot more - is this the same as setting the Schema in xcworkspace from Debug to Release ?

This needs to be clarified.

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
