### ISSUE TITLE
[FlatList] shouldItemUpdate called with incorrect {item,index}

### ISSUE THREAD

**Issue by john-cfng** [facebook/react-native#13503]
### Description
symptom:
supply shouldItemUpdate() and data=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 7, 8, 9, 10, 11, ...] to a FlatList with 3 columns
shouldItemUpdate() is called with incorrect data {index: 6, item: 9}
expect {index: 6, item:7} or {index: 8, item 9} 

further investigation:
seems that in FlatList.js, _shouldItemUpdate() does not take numColumns into account when calling shouldItemUpdate()

### Reproduction Steps and Sample Code
obverse the values received in shouldItemUpdate()

```javascript
class AppClass extends React.Component {
    constructor(props) {
        super(props)
        this.data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 7, 8, 9, 10, 11, ] ;
   }
   shouldItemUpdate(props, nextProps) {
        // some code
    }
    render() {
        return (
            <FlatList
                {...(this.modifiedProps)}
                data={this.data}
                numColumns={3}
                shouldItemUpdate={this.shouldItemUpdate}
                renderItem={this.renderItem}>
            </FlatList>
        );
    }
}
```

### Solution
add *numColumns in _shouldItemUpdate function seems to have solved the problem

```javascript
_shouldItemUpdate = (prev, next) => {  
    const {numColumns, shouldItemUpdate} = this.props;  
    if (numColumns > 1) {  
      return prev.item.length !== next.item.length ||  
        prev.item.some((prevItem, ii) => shouldItemUpdate(  
          {item: prevItem, index: prev.index*numColumns + ii},  
          {item: next.item[ii], index: next.index*numColumns + ii},  
        ));  
    } else {  
      return shouldItemUpdate(prev, next);  
    }  
  };
```

### Additional Information

* React Native version: 0.43.2
* Platform: Android 4.1.2 & 7.1.1
* Development Operating System: Win10
* Dev tools: Android SDK Tools 26.0.1

**Comment by hramos** [comment]
Hi there! This issue is being closed because {:search=>"repo:facebook/react-native is:open is:issue updated:<2017-05-25 -label:\"Good First Task\" -label:\"Help Wanted\" ", :message=>"it has been inactive for a while"}. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
