### ISSUE TITLE
Mutex file not found in React

### ISSUE THREAD

**Issue by topher** [facebook/react-native#13508]
After upgrading to RN .43.3 I came across this error during debug build. 

### Xcode 
![screen shot 2017-04-14 at 6 57 50 am](https://cloud.githubusercontent.com/assets/20007602/25045200/d7abc226-20df-11e7-8bad-531753cc534a.png)

### Terminal
 After `react-native start -reset-cache` then `react-native run-ios`
```
The following build commands failed:
	CompileC /Users/chris/Library/Developer/Xcode/DerivedData/Build/Intermediates/Pods.build/Debug-iphonesimulator/React-framework.build/Objects-normal/x86_64/RCTModuleData.o /Users/chris/zelos/zelosApp/node_modules/react-native/React/Base/RCTModuleData.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

## Scheme
I set my scheme to `React-framework` imported from coccoapods. I've also tried replacing framework with React Library from mode modules in my project target but came across the same error.
![screen shot 2017-04-14 at 6 40 15 am](https://cloud.githubusercontent.com/assets/20007602/25045250/282f7ec2-20e0-11e7-9461-8fddc32707a8.png)

## Possible Solutions
I'm thinking it could be an issue with the wrong LD_flags, as `<mutex>` is included (from obj/runtime.h?) and if that is the case, I'm not what the proper flags to link would be. Here is my React-framework.xcconfig. 
```
CLANG_CXX_LANGUAGE_STANDARD = c++14
CONFIGURATION_BUILD_DIR = $PODS_CONFIGURATION_BUILD_DIR/React-framework
FRAMEWORK_SEARCH_PATHS = $(inherited) "$PODS_CONFIGURATION_BUILD_DIR/Yoga-framework"
GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
HEADER_SEARCH_PATHS = "${PODS_ROOT}/Headers/Private" "${PODS_ROOT}/Headers/Public" "${PODS_ROOT}/Headers/Public/GoogleMaps" "${PODS_ROOT}/Headers/Public/React" "${PODS_ROOT}/Headers/Public/Yoga" $(PODS_TARGET_SRCROOT)/ReactCommon
OTHER_LDFLAGS = -l"stdc++" -framework "JavaScriptCore"
PODS_BUILD_DIR = $BUILD_DIR
PODS_CONFIGURATION_BUILD_DIR = $PODS_BUILD_DIR/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
PODS_ROOT = ${SRCROOT}
PODS_TARGET_SRCROOT = ${PODS_ROOT}/../../node_modules/react-native
PRODUCT_BUNDLE_IDENTIFIER = org.cocoapods.${PRODUCT_NAME:rfc1034identifier}
SKIP_INSTALL = YES
```

Any suggestions / similar errors?

* React Native version: [ v0.43.3 ]
*  Coccoapods [ v1.2 ]
* Platform: [ iOS ]
* Development Operating System: [ MacOS ]
* Dev tools: [ Xcode 8,  ]

**Comment by KingDr** [comment]
set `other linker flags` to `-lc++`, not `-lstdc++`

**Comment by hramos** [comment]
Hi there! This issue is being closed because {:search=>"repo:facebook/react-native is:open is:issue updated:<2017-05-25 -label:\"Good First Task\" -label:\"Help Wanted\" ", :message=>"it has been inactive for a while"}. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
