### ISSUE TITLE
react-native bundle command --bundle-output options not working

### ISSUE THREAD

**Issue by nhuthuynh** [facebook/react-native#13514]
**# Issue Description**

I run bundle command a few times and i realized that it do not bundle file main.jsbundle.
I have to run command `npm start` && `curl http://localhost:8081/index.android.bundle?platform=android -o ./android/app/src/main/assets/index.android.bundle` to copy bundle source to my assets file

**# Expectation**
when i run command react-native bundle, it should bundle main.jsbundle file and copy to the path as --bundle-output option.

**# Code Snippets**

```
react-native bundle --entry-file index.android.js --bundle-output ./android/app/src/main/assets/main.jsbundle --dev false --platform android --assets-dest ./android/app/src/main/res/
```
**package.json file**

```
{
    "name": "projectTest",
    "version": "0.0.1",
    "private": true,
    "scripts": {
        "start": "node node_modules/react-native/local-cli/cli.js start",
        "bunle:ios": "react-native bundle --entry-file index.ios.js --bundle-output ./ios/CassiCoupon/main.jsbundle --dev false --platform ios --assets-dest ./ios",
        "copy:ios": "curl http://localhost:8081/index.ios.bundle?platform=ios -o ./ios/CassiCoupon/main.jsbundle",
        "bundle:android": "react-native bundle --entry-file index.android.js --bundle-output ./android/app/src/main/assets/main.jsbundle --dev false --platform android --assets-dest ./android/app/src/main/res/",
        "copy:android": "curl http://localhost:8081/index.android.bundle?platform=android -o ./android/app/src/main/assets/index.android.bundle",
        "build:android": "npm run clear:android && npm run copy:android && npm run bundle:android",
        "build:ios": "",
        "clear:android": "rm -rf ./android/app/src/main/assets/*.*",
        "test": "jest"
    },
    "dependencies": {
        "immutable": "^3.8.1",
        "react": "15.4.2",
        "react-native": "0.42.0",
        "react-native-camera": "git+https://github.com/lwansbrough/react-native-camera.git",
        "react-native-device-info": "^0.10.1",
        "react-native-fbsdk": "^0.5.0",
        "react-native-keyboard-aware-scroll-view": "^0.2.8",
        "react-native-looped-carousel": "^0.1.5",
        "redux-persist-immutable": "^4.2.0"
    },
    "devDependencies": {
        "babel-jest": "19.0.0",
        "babel-preset-react-native": "1.9.1",
        "immutable": "^3.8.1",
        "jest": "19.0.2",
        "react-native-menu": "^0.20.2",
        "react-redux": "^5.0.3",
        "react-test-renderer": "15.4.2",
        "redux": "^3.6.0",
        "redux-form": "^6.6.1",
        "redux-immutablejs": "0.0.8",
        "redux-logger": "^2.8.2",
        "redux-persist": "^4.6.0",
        "redux-thunk": "^2.2.0"
    },
    "jest": {
        "preset": "react-native"
    }
}
```

**Comment by hramos** [comment]
Hi there! This issue is being closed because {:search=>"repo:facebook/react-native is:open is:issue updated:<2017-05-25 -label:\"Good First Task\" -label:\"Help Wanted\" ", :message=>"it has been inactive for a while"}. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
