### ISSUE TITLE
Jest Upgrade Scenario

### ISSUE THREAD

**Issue by jpshelley** [facebook/react-native#13521]
### Description

I've been using the upgrade tools from React Native mentioned in the docs since around version `0.32`. I recently noticed that new projects default with Jest as of `0.38` and the presets differ in certain ways.
This was never picked up by the upgrade tools I used (Some times I would use the rn-diff, others the git tool depending on what worked).
Is this something that can/should be addressed or at least have a section in the documentation about the update and that Jest is now included and `jest-react-native` preset is no longer needed?

### Reproduction Steps and Sample Code

1. `react-native init --version="0.36.0" MyOldApp` - See how old Jest setup looks
2. Perform upgrades up to 0.43.0 or at least 0.38.0
3. Notice that Jest configurations haven't changed

1. `react-native init MyNewJestApp` which should default to 0.43.0 - See how new Jest setup looks
2. Compare to your MyOldApp and notice the difference.

### Solution

* Improve upgrade scenario
* Or at least mention it in the documentation on how to upgrade effectively for Jest.

### Additional Information

* React Native version: [Initial: 0.32.0 - Current 0.43.0]
* Platform: [N/A]
* Development Operating System: [macOS]
* Dev tools: [CLI, VSCode]

**Comment by hramos** [comment]
Hi there! This issue is being closed because {:search=>"repo:facebook/react-native is:open is:issue updated:<2017-05-25 -label:\"Good First Task\" -label:\"Help Wanted\" ", :message=>"it has been inactive for a while"}. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
