### ISSUE TITLE
[Android][ToolbarAndroid][0.43.3] Strange paddingTop style behavior

### ISSUE THREAD

**Issue by terrysahaidak** [facebook/react-native#13523]
### Description

Just trying to make some nice top padding for ToolbarAndroid to get a nice transparent status bar, but realize that paddingTop property in toolbar styles works a little bit strange. Not sure if it a bug of a feature.

Not sure, but I think it had worked like I've expected in ReactNative 0.18 or something like that.

### Reproduction Steps and Sample Code

![image](https://cloud.githubusercontent.com/assets/7809008/25067743/6638e4ce-224d-11e7-9f8d-67cfe64275ba.png)

Icons stay at the same position, title aligns to the center.

Code:
```js
// statusbar
        <StatusBar
          translucent
          backgroundColor="rgba(0,0,0,0.2)"
          barStyle="dark-content" />

// toolbar

      <Toolbar
        actions={actions}
        navIcon={require('./menu.png')
        onIconClicked={this.props.onMenuTap}
        onActionSelected={this.handleActionPress}
        title="Home"
        titleColor="white"
        style={s.toolbar} />

// styles

  toolbar: {
    height: 56,
    paddingTop: 56 + StatusBar.currentHeight,
    backgroundColor: colors.raspberry,
    elevation: 4
  },
```

### Additional Information

* React Native version: 0.43.3
* Platform: Android 5.1
* Development Operating System: macOS Sierra

**Comment by terrysahaidak** [comment]
According to [this](http://blog.raffaeu.com/archive/2015/04/11/android-and-the-transparent-status-bar.aspx) tutorial, paddingTop should work as I've expected.

```java
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_drawer);

   // Retrieve the AppCompact Toolbar
    Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
    setSupportActionBar(toolbar);

   // Set the padding to match the Status Bar height
    toolbar.setPadding(0, getStatusBarHeight(), 0, 0);
}
```

Result is ![toolbar padding](http://blog.raffaeu.com/wp-content/uploads/Android-and-the-transparent-status-bar_1146A/image_6.png)

**Comment by hramos** [comment]
Hi there! This issue is being closed because {:search=>"repo:facebook/react-native is:open is:issue updated:<2017-05-25 -label:\"Good First Task\" -label:\"Help Wanted\" ", :message=>"it has been inactive for a while"}. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
