### ISSUE TITLE
NavigatorIOS optimizations break functional components

### ISSUE THREAD

**Issue by algesten** [facebook/react-native#13539]
### Description

NavigatorIOS method for providing props to the child components `passProps`. A functional component should (at the very least) be redrawn when the props change (argument to function changes), however internal optimizations of NavigatorIOS means the children are never redrawn.

### Reproduction Steps and Sample Code

```javascript
const MyScene= (props) => {
    return (
      <View><Text>{props.message}</Text></View>
    )
}
```

```javascript
const App = (props) => {
  return (
    <NavigatorIOS
      initialRoute={{
        component: MyScene,
        title: 'My Initial Scene',
        // XXX when these props change, no redraw occurs
        passProps: {message:props.incomingMessage}
      }}
      style={{flex: 1}}
    />
  )
}
```

### Solution

Redraws get stuck on the optimization logic on these lines.

https://github.com/facebook/react-native/blob/master/Libraries/Components/Navigation/NavigatorIOS.ios.js#L855-L861

At the very least passing new props should cause a redraw (i.e. treating the function as a `React.PureComponent`), but maybe even better to identify functional components as children and _always_ propagate the parent redraw to them. 

### Additional Information

* React Native version: 0.42.0, 0.43.0
* Platform: iOS
* Development MacOS
* Dev tools: XCode 8.3.1

**Comment by hramos** [comment]
Hi there! This issue is being closed because {:search=>"repo:facebook/react-native is:open is:issue updated:<2017-05-25 -label:\"Good First Task\" -label:\"Help Wanted\" ", :message=>"it has been inactive for a while"}. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
