### ISSUE TITLE
DatePickerAndroid styling not working when provide mode prop

### ISSUE THREAD

**Issue by bennygenel** [facebook/react-native#13538]
### Description

On Android when using native style.xml DatePickerAndroid returns to theme default colors when using mode prop. When you don't use it at all it works fine.

https://github.com/mmazzarolo/react-native-modal-datetime-picker/issues/29

### Reproduction Steps and Sample Code

style.xml

```
<resources>

    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="colorAccent">@color/mainRed</item>
    </style>
    <style name="Dialog.Theme" parent="Theme.AppCompat.Light.Dialog">
        <item name="colorAccent">@color/mainRed</item>
    </style>

</resources>
```

```
DatePickerAndroid.open(); // Styling works fine
DatePickerAndroid.open({mode: 'calendar'}); // Styling is not working
DatePickerAndroid.open({mode: 'spinner'}); // Styling is not working
```

### Solution

Don't know much about native code but I assume that when using mode prop something overrides the styling to default theme.

### Additional Information

* React Native version: "0.43.3"
* Platform: Android
* Development Operating System: MacOS
* Dev tools: Android Studio

**Comment by PARAGJYOTI** [comment]
@bennygenel  Have no Idea why its not working . But you can make your android theme in android studio . 
  Go to tools>Android>Theme Editor and you can create your own theme . I built mine and its working everywhere. First just import the project to android studio. You dont have to touch any files , the studio itself will do it .

**Comment by bennygenel** [comment]
@PARAGJYOTI I already created my own theme. As you can see I set the theme on style.xml and it works fine too unless I use mode prop on DatePickerAndroid as I mentioned before.

**Comment by jtibbertsma** [comment]
This issue appeared for me when updating from 0.43.0 to 0.44.0

**Comment by hramos** [comment]
Hi there! This issue is being closed because {:search=>"repo:facebook/react-native is:open is:issue updated:<2017-05-25 -label:\"Good First Task\" -label:\"Help Wanted\" ", :message=>"it has been inactive for a while"}. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by khrizt** [comment]
Ok, I found out how to apply styles when mode prop is set. The problem was the style names, when the mode prop is set [react native looks for specific styles in the resources](https://github.com/facebook/react-native/blob/1e8f3b11027fe0a7514b4fc97d0798d3c64bc895/ReactAndroid/src/main/java/com/facebook/react/modules/datepicker/DatePickerDialogFragment.java#L68). For spinner mode:

```xml
<style name="SpinnerDatePickerDialog" parent="android:Theme.Material.Light.Dialog">
    <item name="android:datePickerStyle">@style/MyDatePicker</item>
    <item name="android:colorAccent">@color/colorPrimary</item>
    <item name="android:colorControlNormal">@color/colorPrimary</item>
</style>

<style name="MyDatePicker" parent="android:Widget.Material.DatePicker">
    <item name="android:datePickerMode">spinner</item>
</style>
```
No the style with the `datePickerMode` attribute, without it android renders the standard mode not the spinner mode (don't know why). These are the style attributes I found that work, maybe there are others but I haven't found them. Another thing I have not been able to set is the title, but probably this should be done in react-native.

And for calendar mode:

```xml
<style name="CalendarDatePickerDialog" parent="android:Theme.Material.Light.Dialog">
    <item name="android:headerBackground">@color/colorPrimary</item>
    <item name="android:colorControlNormal">@color/colorPrimary</item>
    <item name="android:colorControlHighlight">@color/colorPrimary</item>
    <item name="colorPrimary">@color/colorPrimary</item>
    <item name="colorAccent">@color/colorPrimary</item>
    <item name="textColor">@color/colorPrimary</item>
</style>
```

These style attributes are not fully tested but I think they work. I hope this works for other people.

**Comment by m-vdb** [comment]
thank you @khrizt your solution for the spinner works like a charm! Haven't tested the calendar version.
