### ISSUE TITLE
Could not connect to development server just after `react-native init`

### ISSUE THREAD

**Issue by jaggerwang** [facebook/react-native#13543]
### Description

The ip in bundle url is not my MacBook's local ip `192.168.1.135`.

![image](https://cloud.githubusercontent.com/assets/1255011/25089608/22b9a9c6-23b1-11e7-868a-e054c40069c9.png)

After change host & port in "Dev settings" to "192.168.1.135:8081", it still has the same error. The packager server is running.

![image](https://cloud.githubusercontent.com/assets/1255011/25089895/dd0cc6a4-23b2-11e7-8b16-7507d1e53bec.png)

### Reproduction Steps and Sample Code

```
> react-native init gtgj
> cd gtgj
> react-native run-android
```

### Additional Information

* React Native version: 0.43.3
* Platform: Android
* Development Operating System: MacOS
* Dev tools: react-native

**Comment by PARAGJYOTI** [comment]
Did you run react-native-start or not ? if did try   adb reverse tcp:8081 tcp:8081 on the directory ~/android/sdk/platform-tools

**Comment by jaggerwang** [comment]
@PARAGJYOTI Yes, I'm sure the packager server is running and I do run adb reverse.

**Comment by jaggerwang** [comment]
By the way, `react-native run-ios` is ok, the demo app can run on the iPhone simulator.

**Comment by superbigsoft** [comment]
I had the same issue on Windows. After turning off the firewall so that outside world can connect to the packager server then all good. Hope this help.

**Comment by hramos** [comment]
Hi there! This issue is being closed because {:search=>"repo:facebook/react-native is:open is:issue updated:<2017-05-25 -label:\"Good First Task\" -label:\"Help Wanted\" ", :message=>"it has been inactive for a while"}. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by clecotechAish** [comment]
I am facing the same issue on android real device.
My react-native version is 0.51.0

**Comment by galart** [comment]
+1

**Comment by SolveBugs** [comment]
+1

**Comment by SaniokUA** [comment]
+

**Comment by Louies89** [comment]
Hi All,
I found the same issue while running in **windows environment** and simulating using android simulator.
After doing some trial & error, I found the solution as below:

1>> Change the port in "<Your Project Path>\node_modules\react-native\local-cli\server\server.js" from  `default: process.env.RCT_METRO_PORT || 8081`, to `default: process.env.RCT_METRO_PORT || 9088,`
If the port is blocked or issued to some other application.
**Note**: You can choose any port number, I have choosen 9088
2>> Run the command `react-native run-android --port 9088` (Put your port number here). This port shall be sent to adb running, so that both server and adb shall be in same port.
3>> Now in Android studio simulator, press Ctrl+m, to go for **"Dev Setting"**, then select **Debug Server port & host for Device**, set **"localhost:9088"**.

Now it will start loading the changes you make in your application.

Enjoy coding now :)
