### ISSUE TITLE
Can't decode base64 encoded images provided by ImageStore

### ISSUE THREAD

**Issue by nickcharles** [facebook/react-native#13546]
### Description

I cannot decode the base64 data provided by the ImageStore for my images. I want to send a raw byte stream over the wire to my server, but I cannot produce a byte stream that is a valid jpeg. I haven't tried this yet on iOS, this might be a platform specific problem. Will update with further findings. Looking for discussion on how others have solved this problem.

Do Android and iOS use different base64 encoding standards based on OS and OS version? Looks like ReactNativeFetchBlob has been able to get around this by implementing the decoding step in native code.

### Reproduction Steps and Sample Code

I'm using https://github.com/mathiasbynens/base64 to decode the base64 image, resulting in a broken file. 

```typescript
ImageStore.getBase64ForTag(
    uri,
    (base64ImageData: string): void => {
        const raw = b64.decode(base64ImageData);
        networker.uploadImage(raw);
    },
    (error: any): void => {
        throw Error("Failed to find photo at specified uri);
    });
```

### Solution

There are a bunch of solutions here I imagine, and I'm surprised there isn't a solution readily available here. One way would be provide an api to decode these base64 encoded images so I can get access to the raw bytestream.

### Additional Information

* React Native version: [0.43]
* Platform: [Android]
* Development Operating System: [OS X]
* Dev tools: [Genymotion Android 6.0.0]

**Comment by kasterlod** [comment]
I had a similar problem with image picker to base64 (upload and show in <Image/>).
It seems to be smth like limit of byte to encode by base64?
I don't know, but solution for me was compress an Image before encoding.

greetings

**Comment by nickcharles** [comment]
I ended up using react-native-fetch-blob, it circumvents sending the encoded image over the bridge so it ends up being much faster anyway. I didn't consider what you're suggesting but that could certainly be the issue.

**Comment by hramos** [comment]
Hi there! This issue is being closed because {:search=>"repo:facebook/react-native is:open is:issue updated:<2017-05-25 -label:\"Good First Task\" -label:\"Help Wanted\" ", :message=>"it has been inactive for a while"}. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
