### ISSUE TITLE
Uninstall ReactNative App - Clean User Data using Asyncstorage

### ISSUE THREAD

**Issue by swaroopa94** [facebook/react-native#13542]
Hi,
I am using Async Storage to store some values in my react native app.
I have a login so when I login into the app I am storing my id, when logout I am removing it.

But when uninstalling my app without logout then my data is async storage is not removing that refers to  automatic login when installing the app again.

Can you please tell me how to solve this
this happens in android device and version >6

Thankyou

**Comment by PARAGJYOTI** [comment]
If the app is in development mode , if must have to 'uninstall for all users' going to settings/apps/your-app , if in production mood you don't have to that . Usually it shouldn't happen .

**Comment by swaroopa94** [comment]
My app is in production mode but it is happening only in android version greater than 6 only.
In remaining devices its working fine

**Comment by swaroopa94** [comment]
Hi,
Please anyone tell me how to solve this as its urgent 
my react native version is: 0.43.3

**Comment by Mbompr** [comment]
Hi, I've got the same issue and it simply seems to be the direct cause of  android's new manifest keyword: 
```<android:allowBackup="true">```
You can find more information [on android documentation](https://developer.android.com/guide/topics/data/autobackup.html) but quickly it says that app locally saved data might be backed up on Google Drive on the latest versions of Android. You can disable it either by setting `<android:allowBackup="false">` (true is the default behavior) or by disabling auto backup in your phone's settings.

**Comment by hramos** [comment]
Hi there! This issue is being closed because {:search=>"repo:facebook/react-native is:open is:issue updated:<2017-05-25 -label:\"Good First Task\" -label:\"Help Wanted\" ", :message=>"it has been inactive for a while"}. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by Garib-ka-code** [comment]
Can someone tell me how to clear in IOS as well?
