### ISSUE TITLE
Release notes broken since 0.42

### ISSUE THREAD

**Issue by christophmegusta** [facebook/react-native#13540]
I am new to the React Native world and having fun learning it. Though there is one thing which is confusing me - the Release Notes are empty for every version since 0.42. I really would like to know the difference between React Native versions. Whats new, what did change, what did break etc. 

I am following the links on https://facebook.github.io/react-native/versions.html
so https://github.com/facebook/react-native/releases/tag/v0.41.0 still has it but
https://github.com/facebook/react-native/releases/tag/v0.42.0 does not.

Where can i get this information? Is it in a different place now? Does the documentation need a fix?
Its really confusing for a beginner to not find this information.

Thanks a lot

**Comment by Ehesp** [comment]
It's because the release notes go with the latest minor version. For example 0.42 is [0.42.3](https://github.com/facebook/react-native/releases/tag/v0.42.3).

You can find the latest releases here: https://github.com/facebook/react-native/releases

**Comment by christophmegusta** [comment]
Thanks for that information, Ehesp.
So that release notes compare to the latest minor e.g. 0.42.3 vs 0.42.2 or (as i suppose from the amount of changes) do they compare current major.minor 0.42.3 vs last latest major.minor 0.41.x (whatever latest minor there is)?
How can i find out changes between 2 minors 0.42.3 vs 0.42.2? I guess its down to git cli then?

**Comment by charpeni** [comment]
Sorry for the confusion, as @Ehesp said the release notes are only for minor versions (monthly release).

But you're probably right, before the release notes was always tagged to the version v0.X.0 as linked in [React Native Versions](https://facebook.github.io/react-native/versions.html), but now they're linked to the latest patch. 

cc @grabbou Thoughts?

If you want to know the changes between two patches, you can do this by comparing changes like this: https://github.com/facebook/react-native/compare/v0.43.2...v0.43.3

**Comment by hramos** [comment]
Hi there! This issue is being closed because {:search=>"repo:facebook/react-native is:open is:issue updated:<2017-05-25 -label:\"Good First Task\" -label:\"Help Wanted\" ", :message=>"it has been inactive for a while"}. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
