### ISSUE TITLE
Blog Issue: anchor tags on subheadings do not create correct links

### ISSUE THREAD

**Issue by thurt** [facebook/react-native#13544]
### Description

in title

### Reproduction Steps and Sample Code

1. Visit https://facebook.github.io/react-native/blog/2017/03/13/better-list-views.html
1. mouse over one of the subheadings, which will cause a hash mark "#" to appear 
![screen shot 2017-04-17 at 11 27 05 am](https://cloud.githubusercontent.com/assets/8955144/25093573/d73fe7bc-2360-11e7-8895-61b61e8e3089.png)

1. click the hash mark to create an anchored link.
1. confirm that the anchored link is incorrect b/c it redirects to a different page

### Solution

clicking hash mark should create a correct anchored link.

### Additional Information

* React Native version: n/a
* Platform: n/a
* Development Operating System: n/a
* Dev tools: n/a

**Comment by hramos** [comment]
Hi there! This issue is being closed because {:search=>"repo:facebook/react-native is:open is:issue updated:<2017-05-25 -label:\"Good First Task\" -label:\"Help Wanted\" ", :message=>"it has been inactive for a while"}. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
