### ISSUE TITLE
peerDependencies + shrinkwrap = react version lock-in

### ISSUE THREAD

**Issue by boennemann** [facebook/react-native#13541]
### Description

We're building a react-native app. Dependencies are installed with npm and locked with shrinkwrap.
The way recent react-native versions define their peerDependencies locks us out of using the latest stable react version, because shrinkwrap turns peerDependency mismatches into hard errors.
We would love to move to react 15.5 asap, in order to be ready for 16.0.0.

### Reproduction Steps and Sample Code

Install react-native@0.42.3 with a shrinkwrap file present. Try to install latest react@15.5.0

```
Error: Command failed: npm install -S react@15.5.0
npm WARN saveError Problems were encountered
npm WARN saveError Please correct and try again.
npm WARN saveError peer invalid: react@~15.4.1, required by react-native@0.42.3
npm WARN react-native@0.42.3 requires a peer of react@~15.4.1 but none was installed.
```

The same happens with react-native@0.43.3, because that in turn requires react@16.0.0-alpha.

```
npm WARN saveError Problems were encountered
npm WARN saveError Please correct and try again.
npm WARN saveError peer invalid: react@^15.5.0, required by react-addons-shallow-compare@15.5.0-alpha.0
npm WARN saveError peer invalid: react@16.0.0-alpha.6, required by react-native@0.43.0
```

Yarn has a soft-warning for this: "warning "react-native@0.42.3" has incorrect peer dependency "react@~15.4.1".

### Solution

I couldn't find any information on whether this is an intentional lockout, i.e. react-native@0.42/react-native@0.43 _really are_ incompatible with react@15.5.

A solution would be to release 0.42.4 with a loosened peerDependency of at least ^15.5.0.

Same goes for a potential 0.43.4, which could loosen the peerDependency to something like >= 15.5.0, or ">=15.5.0 < 17.0.0" – unless of course it really isn't compatible with anything other than 16.0.0-alpha (which would be quite weird, for a regular react-native release).

### Additional Information

* React Native version: 0.42.x, 0.43.x
* Platform: both
* Development Operating System: all
* Dev tools: npm, shrinkwrap

**Comment by boennemann** [comment]
Even if we want to upgrade to the react alpha pretty much the entire ecosystem has a `>=15` peerDependency and things are even more broken.

I would really appreciate a small follow-up version for 0.43 that fixes the peerDependency entry.

```
$ npm i -S react-native@latest react@16.0.0-alpha.6
npm WARN saveError Problems were encountered
npm WARN saveError Please correct and try again.
npm WARN saveError peer invalid: react@>=15.3.1, required by lottie-react-native@1.1.1
npm WARN saveError peer invalid: react@>=15.3.1, required by react-native-looped-carousel@0.1.5
npm WARN saveError peer invalid: react@>=15.4.0, required by react-native-svg@5.1.7
npm WARN saveError peer invalid: react@^15.4.2, required by react-test-renderer@15.4.2
npm WARN saveError peer invalid: react@^0.14.0 || ^15.0.0-0, required by styled-components@1.4.4
Ada@2.4.0 /Users/boennemann/Projects/ada/app
└─┬ react-native@0.43.4 
  ├─┬ babel-plugin-transform-async-to-generator@6.16.0 
  │ └── babel-helper-remap-async-to-generator@6.24.1 
  ├─┬ jest-haste-map@19.0.0 
  │ ├─┬ fb-watchman@2.0.0 
  │ │ └── bser@2.0.0 
  │ └─┬ sane@1.5.0 
  │   ├─┬ fb-watchman@1.9.2 
  │   │ └── bser@1.0.2 
  │   └── minimist@1.2.0 
  ├─┬ npmlog@2.0.4
  │ └── are-we-there-yet@1.1.4 
  ├─┬ react-devtools-core@2.0.12 
  │ ├─┬ cross-env@3.2.4 
  │ │ ├─┬ cross-spawn@5.1.0 
  │ │ │ └── lru-cache@4.0.2 
  │ │ └── is-windows@1.0.0 
  │ └─┬ ws@2.3.1 
  │   └── ultron@1.1.0 
  ├─┬ sane@1.4.1
  │ └─┬ fb-watchman@1.9.2 
  │   └── bser@1.0.2 
  ├─┬ ws@1.1.4
  │ └── ultron@1.0.2 
  └── xpipe@1.0.5 

npm WARN lottie-react-native@1.1.1 requires a peer of react@>=15.3.1 but none was installed.
npm WARN react-native-looped-carousel@0.1.5 requires a peer of react@>=15.3.1 but none was installed.
npm WARN react-native-svg@5.1.7 requires a peer of react@>=15.4.0 but none was installed.
npm WARN react-test-renderer@15.4.2 requires a peer of react@^15.4.2 but none was installed.
npm WARN styled-components@1.4.4 requires a peer of react@^0.14.0 || ^15.0.0-0 but none was installed.
```

**Comment by aranda-adapptor** [comment]
Looks like the react-native 0.43.4 *does* have a hard dependency on react 16.0.0-alpha.6. If I just upgrade react-native and leave react at ~15.4.2, I get `Failed to execute 'importScripts' on 'WorkerGlobalScope'` when loading the package on the device. Doing `yarn upgrade react@16.0.0-alpha.6`, things seem to be working but as you noted, there are multiple warnings in the yarn log:

```
warning "react-dom@15.4.2" has incorrect peer dependency "react@^15.4.2".
warning "react-native-maps@0.13.1" has incorrect peer dependency "react@>=15.4.0".
warning "enzyme@2.8.0" has incorrect peer dependency "react@0.13.x || 0.14.x || ^15.0.0-0 || 15.x".
warning "react-test-renderer@15.4.2" has incorrect peer dependency "react@^15.4.2".
warning "react-native-looped-carousel@0.1.6" has incorrect peer dependency "react@>=15.3.1".
```

**Comment by hramos** [comment]
Hi there! This issue is being closed because {:search=>"repo:facebook/react-native is:open is:issue updated:<2017-05-25 -label:\"Good First Task\" -label:\"Help Wanted\" ", :message=>"it has been inactive for a while"}. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
