### ISSUE TITLE
RefreshControl issue:open and close at once

### ISSUE THREAD

**Issue by fiattt** [facebook/react-native#13554]
### Description
If you pass TRUE to the RefreshControl 'refreshing' prop, the component will open and show the spinner until it receives a FALSE value. However, this only happens the first time. second time the 
spinner will open and close at once. 
seem the same with：https://github.com/facebook/react-native/issues/10373

### Reproduction Steps and Sample Code
use the code in: https://facebook.github.io/react-native/docs/refreshcontrol.html and change a bit for sample:

the diff is:
![image](https://cloud.githubusercontent.com/assets/1531440/25116716/10aa75f4-2441-11e7-843f-7bd3398c9af9.png)

the  whole file:[listTestPage.js.zip](https://github.com/facebook/react-native/files/927483/listTestPage.js.zip)

the Reproduction gif:
![bug](https://cloud.githubusercontent.com/assets/1531440/25116913/2f990be6-2442-11e7-9c1b-62640fe90bab.gif)

```js
'use strict';

const React = require('react');
const ReactNative = require('react-native');
const {
    ScrollView,
    StyleSheet,
    RefreshControl,
    Text,
    TouchableWithoutFeedback,
    View,
} = ReactNative;

const styles = StyleSheet.create({
    row: {
        borderColor: 'grey',
        borderWidth: 1,
        padding: 20,
        backgroundColor: '#3a5795',
        margin: 5,
    },
    text: {
        alignSelf: 'center',
        color: '#fff',
    },
    scrollview: {
        flex: 1,
    },
});

class Row extends React.Component {
    _onClick = () => {
        this.props.onClick(this.props.data);
    };

    render() {
        return (
            <TouchableWithoutFeedback onPress={this._onClick} >
                <View style={styles.row}>
                    <Text style={styles.text}>
                        {this.props.data.text + ' (' + this.props.data.clicks + ' clicks)'}
                    </Text>
                </View>
            </TouchableWithoutFeedback>
        );
    }
}

class listTestPage extends React.Component {
    static title = '<RefreshControl>';
    static description = 'Adds pull-to-refresh support to a scrollview.';

    state = {
        isRefreshing: false,
        loaded: 0,
        rowData: Array.from(new Array(20)).map(
            (val, i) => ({text: 'Initial row ' + i, clicks: 0})),
    };

    _onClick = (row) => {
        row.clicks++;
        this.setState({
            rowData: this.state.rowData,
            isRefreshing: true,
        });

        setTimeout(()=>{
            this.setState({
                isRefreshing: false,
            });
        },2000);
    };

    render() {
        const rows = this.state.rowData.map((row, ii) => {
            return <Row key={ii} data={row} onClick={this._onClick}/>;
        });
        return (
            <ScrollView
                style={styles.scrollview}
                refreshControl={
          <RefreshControl
            refreshing={this.state.isRefreshing}
            onRefresh={this._onRefresh}
            tintColor="#ff0000"
            title="Loading..."
            titleColor="#00ff00"
            colors={['#ff0000', '#00ff00', '#0000ff']}
            progressBackgroundColor="#ffff00"
          />
        }>
                {rows}
            </ScrollView>
        );
    }

    _onRefresh = () => {
        this.setState({isRefreshing: true});
        setTimeout(() => {
            // prepend 10 items
            const rowData = Array.from(new Array(10))
                .map((val, i) => ({
                    text: 'Loaded row ' + (+this.state.loaded + i),
                    clicks: 0,
                }))
                .concat(this.state.rowData);

            this.setState({
                loaded: this.state.loaded + 10,
                isRefreshing: false,
                rowData: rowData,
            });
        }, 5000);
    };
}

module.exports = listTestPage;
```

### Additional Information

* React Native version: 0.41.1
* Platform: iOS
* Development Operating System: MacOS
* Dev tools: Xcode 8.3

**Comment by vonovak** [comment]
as a workaround, set `style={{ backgroundColor: 'transparent' }}` on the refreshControl. related: #9294

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by huanganqi** [comment]
+1

**Comment by bdrobinson** [comment]
I'm still finding this to be an issue on 0.48.3.
