### ISSUE TITLE
Default font type on phone

### ISSUE THREAD

**Issue by OkancanCosar** [facebook/react-native#13585]
Hi, 
I notice something. I dont use default font type on my phone(Lg G2 Android 5.0.2).
But charcter missing in react-native project.
<img src="http://1.1m.yt/mkcKIqH.png" width="200" height="350"/>
<img src="http://1.1m.yt/19twb5q.png" width="200" height="350"/>

when I set default font type, working fine. and also genymotion output working fine too
<img src="http://1.1m.yt/kqh3jIW.png" width="200" height="350"/>
<img src="http://1.1m.yt/KvFNgj6.png" width="200" height="350"/>

 it might be bug.

**Comment by ludovic-coder** [comment]
Could you add some code ? Like your styles

**Comment by OkancanCosar** [comment]
actually not irrelivent about the code because there is problem in  [https://play.google.com/store/apps/details?id=host.exp.exponent](expo) app. not showing R in CLEAR

**Comment by hramos** [comment]
Hi there! This issue is being closed because {:search=>"repo:facebook/react-native is:open is:issue updated:<2017-05-25 -label:\"Good First Task\" -label:\"Help Wanted\" ", :message=>"it has been inactive for a while"}. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
