### ISSUE TITLE
image don't show with good shape on iOS

### ISSUE THREAD

**Issue by 7laria** [facebook/react-native#13582]
![whatsapp image 2017-04-19 at 15 38 47](https://cloud.githubusercontent.com/assets/16237713/25183023/b4b5a896-2516-11e7-89f9-1defd1272c59.jpeg)
![photo6032927663913543737](https://cloud.githubusercontent.com/assets/16237713/25183025/b55d33b8-2516-11e7-8401-853bea472a1f.jpg)
  avatarContainer: {
    borderColor: '#9B9B9B',
    borderWidth: 1 / PixelRatio.get(),
    justifyContent: 'center',
        flexDirection:'column',
    alignItems: 'center',
    marginTop:20
  },
  avatar: {

    borderRadius: 100,
    width: 80,
    height: 80,

  }

**Comment by pfulop** [comment]
Border radius should be half of the width (height) if you want to achieve circle. Web css is more forgiving and will just round it up into circle, but in react native you can overshot and create weird shapes.

**Comment by shergin** [comment]
So, it works on Android exactly like it works on web, right?

**Comment by pfulop** [comment]
@shergin from what I saw yes.

**Comment by shergin** [comment]
Yeah, cool, I believe we should fix it on iOS!

**Comment by pfulop** [comment]
@shergin there has been some conversation on this topic in the past https://github.com/facebook/react-native/issues/1572  .

**Comment by shergin** [comment]
Seems that the issue was fixed for custom "border rendering engine", but not for `CALayer` based one.
Is this happening only if we apply the border radius to `<Image>` (not `<View>`) component?

**Comment by hramos** [comment]
Hi there! This issue is being closed because {:search=>"repo:facebook/react-native is:open is:issue updated:<2017-05-25 -label:\"Good First Task\" -label:\"Help Wanted\" ", :message=>"it has been inactive for a while"}. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by shergin** [comment]
We have to fix it. I will try.
