### ISSUE TITLE
Firebase database listen does not work. Websocket handshake 500 error

### ISSUE THREAD

**Issue by steverob** [facebook/react-native#13614]
I am trying to use Firebase with ReactVR and facing some issues with Websocket connection with Fireabase servers for listening to changes in the database. Since ReactVR is all ReactNative, I'm hoping someone here can help me out with this.

This is my code - 

```
export default class WelcomeToVR extends React.Component {

  constructor(){
    super();
    
    var config = {
      apiKey: "<REDACTED>",
      authDomain: "<REDACTED>",
      databaseURL: "<REDACTED>",
      projectId: "<REDACTED>",
      storageBucket: "<REDACTED>",
      messagingSenderId: "<REDACTED>",
    };
    firebase.initializeApp(config);
  }

  componentWillMount() {
    firebase.database().ref(`viewers`).on('child_added', function(data) {
      console.log(data);
    });
  }

  render() {
    return (
      <View>
      </View>
    );
  }
};

AppRegistry.registerComponent('WelcomeToVR', () => WelcomeToVR);

```

This is the error I am seeing in the console - 

```
WebSocket connection to 'wss://kastio-vr.firebaseio.com/.ws?v=5' failed: Error during WebSocket handshake: Unexpected response code: 500

WrappedWebSocket	@	VM1892:37
connect	@	WebSocketModule.js:45
frame	@	ReactNativeContext.js:416
frame	@	createRootView.js:188
_frame	@	VRInstance.js:152
```

Would love some help here. Do I need to do anything special for WebSockets?

**Comment by steverob** [comment]
More details at the issue in ReactVR repo - https://github.com/facebook/react-vr/issues/118

**Comment by steverob** [comment]
Bump. :) sorry.

**Comment by hramos** [comment]
This discussion is probably best for the React-VR repo.

**Comment by alexduros** [comment]
I made a PR that fixes this issue on react-vr repo : https://github.com/facebook/react-vr/pull/169

But I wonder if a fix should be necessary in react-native as I exlain in this comment : https://github.com/facebook/react-vr/issues/118#issuecomment-298197874

In fact, I think that in `WebSocket` library (https://github.com/facebook/react-native/blob/master/Libraries/WebSocket/WebSocket.js#L81), it would be better to return an empty array, instead of a `null` object, because the WebSocket API will add a `Sec-WebSocket-Protocol` as `null` for secured websockets.

**Comment by stefb965** [comment]
Gigi tresors
