### ISSUE TITLE
[43+] Navigator docs are mentioned, but the links are broken:

### ISSUE THREAD

**Issue by jaygarcia** [facebook/react-native#13620]
See: https://facebook.github.io/react-native/releases/next/docs/navigation.html

Find 
```Check out the Navigator API reference for specific examples that cover each of these scenarios.```

The `Navigator API reference` is linked to https://facebook.github.io/react-native/releases/next/docs/navigator.html

That URL is not valid. :(

Navigator is still useful as react-navigation still has problems and is no where as near as flexible today as Navigator is.  :(

**Comment by jaygarcia** [comment]
FWIW, Seems like 0.42 docs are fine. https://facebook.github.io/react-native/releases/0.42/docs/navigator.html

¯\_(ツ)_/¯

**Comment by hramos** [comment]
Navigator is deprecated and has been removed from the core `react-native` package. It can now be installed and imported from `react-native-deprecated-custom-components` instead of `react-native`.

These remaining references are in error and I'll remove them shortly. Docs for the now deprecated Navigator can always be accessed by loading docs for older releases prior to its deprecation.
