### ISSUE TITLE
Multiline TextInput is not centering text or placeholder vertically

### ISSUE THREAD

**Issue by EnriqueDev** [facebook/react-native#13632]
### Description

Hi, I'm trying to center the text into a multiline text input but seems like its not possible.

### Reproduction Steps and Sample Code

`<TextInput
                style={styles.inputStyle}
                placeholder="Type Answer"
                multiline
            />`

`  inputStyle: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center'
    textAlign: 'center',
    fontSize: 16
  },`

### Additional Information

* React Native version: 0.43
* Platform: [Both]
* Development Operating System: [MacOs]
* Dev tools: [Android SDK 23]

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

**Comment by pyjac** [comment]
Having a similar issue.

**Comment by marcin-chudy** [comment]
Setting `textAlignVertical: 'center'` style on the input helped in my case.

**Comment by AE0011** [comment]
any solution?
I have this problem in android 5.0.1

**Comment by shafy** [comment]
Same here `textAlignVertical: 'center'` doesn't help.
