### ISSUE TITLE
Android Alert tuning

### ISSUE THREAD

**Issue by dimmetrius** [facebook/react-native#13659]
### Description

Hello! Is there a way:
to place lowercase text in Alert buttons?
to place Alert buttons vertically?

### Reproduction Steps and Sample Code

```javascript
    Alert.alert(
      'Alert Title',
      'Alert message',
      [
          {text:'first lowercase text button'},
          {text:'second lowercase text button'},
      ]
    )
```
### Result
![Alert](https://api.monosnap.com/rpc/file/download?id=gRmiMdBNLJdBtpl7Tbi88O9D1hz4p9)

### Additional Information

* React Native version: 0.43
* Platform: Android

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
