### ISSUE TITLE
React-native tvOS : How to set focus on specific item in list view?

### ISSUE THREAD

**Issue by BenBenz** [facebook/react-native#13655]
Hello,

I write an tvOS app with react native and I have few list view, I want to set focus on specific item in list view ?

It is possible ?

Thanks for your help

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

**Comment by JulienKode** [comment]
Yes it is possible, with tvOS and react native if you want to force a focusable component to be focus you just need to set hasTVPreferredFocus to true

For example: 
		

```
    <TouchableHighlight
        hasTVPreferredFocus={true}
    	onPress={() => {}}
    >
    	<Text>Hello</Text>
    </TouchableHighlight>
```

You can see this post on Stackoverflow: 
https://stackoverflow.com/questions/43862802/react-native-tvos-how-to-force-a-button-to-be-focused/44700590#44700590
