### ISSUE TITLE
[WebView] WebView types missing

### ISSUE THREAD

**Issue by Kingles** [facebook/react-native#13662]
### Description

WebView has no proper flowtypes.

#### Environment
* `react-native`: 0.43.4
*  `flow-bin`: 0.40.0
1. import WebView
2. use it
3. attempt to access props or exposed functions
4. observe that props and exposed methods (`injectJavaScript`, for example) are not covered by flow.

```js
// @flow
import React, {PureComponent} from 'react';
import {WebView, View, Button} from 'react-native';
import htmlTemplate from './template.html';

export default class TestComponent extends PureComponent {
  webview: ?WebView = null;

  handlePress = () => {
    const {webview} = this;
    if (webview) {
      const script = "alert('sup :3')";
      webview.injectJavaScript(script);
    }
  };
  render() {
    <View>
      <Button onPress={this.handlePress}>
        Press me!
      </Button>
      <WebView
        ref={(webview: WebView) => {
          this.webview = webview;
        }}
        source={htmlTemplate}
      />
    </View>;
  }
}
```

### Solution

Add missing flowtypes to WebView.

### Additional Information

* React Native version: `0.43.4`
* Platform: both
* Development Operating System: MacOS
* Dev tools: N/A

**Comment by hramos** [comment]
Would you consider sending a PR to add these types?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
