### ISSUE TITLE
[FlatList] Toggling FlatList off & on causes absolute View to disappear

### ISSUE THREAD

**Issue by atlanteh** [facebook/react-native#13663]
### Description
When having an absolute View along a ListView, the absolute view is not showing if the ListView is toggled on & off quickly on load

**This happens only in android**

You can see it reproduces here:
https://snack.expo.io/SyfT8-aCg
 If you remove the first "setTimeout" you can see what is expected.

### Additional Information

* React Native version: 0.41.2
* Platform: android only
* Development Operating System: Windows

**Comment by hramos** [comment]
Can you check if this reproduces with `FlatList`?

**Comment by atlanteh** [comment]
Yes, it reproduces with FlatList:
https://snack.expo.io/rJZYC03ZW

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
