### ISSUE TITLE
ScrollView snapToInterval iOS not working [android integration?]

### ISSUE THREAD

**Issue by julesmoretti** [facebook/react-native#13665]
### Description
*Explain what you did:*
Implemented a column ScrollView (say 400 in height) with smaller height cards inside it (say 100 in height).

Added:
```
pagingEnabled
snapToAlignment={'start'}
snapToInterval={100}
```

*what you expected to happen:*
I expected the scroll to stop every 100

*what actually happens:*
but instead kept paging at 400.

### Reproduction Steps and Sample Code

```
    var _scrollView: ScrollView;

    return (
<ScrollView
  pagingEnabled
contentContainerStyle={{height: 400}}
  ref={(scrollView) => { _scrollView = scrollView; }}
  snapToAlignment={'start'}
  snapToInterval={100}
>
{this.state.contentArray.map((text, index) => <Text style={{height: 100} key={index} >{data}</Text>)}
</ScrollView>
```

### Solution

Clearer documentation. And status update with the Android implementation: https://github.com/facebook/react-native/pull/1532

### Additional Information

* React Native version:     "react-native": "0.40.0",
* Platform: iOS (Android ideally)
* Development Operating System: MacOS
* Dev tools: Xcode and iOS emulator iPhone 6

**Comment by uandco** [comment]
Yeah I ran into the same issue and had to look at the source code to figure out you have to turn `pagingEnabled` off when using `snapToInterval`. The code comment is actually super clear about it but it's not specified in the documentation.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
