### ISSUE TITLE
CameraRoll.getPhotos breaks with assetType = photos

### ISSUE THREAD

**Issue by zackify** [facebook/react-native#13671]
### Description

I'm using this library: https://github.com/jeanpan/react-native-camera-roll-picker/blob/master/index.js under the hood it calls the cameraRoll api. When I pass in 'All' for the asset type, it works. When I use 'Photos' as the type, the app crashes inside of the RCTCameraRoll code:

<img width="1139" alt="screen shot 2017-04-26 at 10 11 19 am" src="https://cloud.githubusercontent.com/assets/449136/25438878/c1078c02-2a68-11e7-8454-a30b3fd97d72.png">

### Reproduction Steps and Sample Code

I was going to try and add an example on expo, but it won't work unless you have more than just photos in your camera roll. To reproduce, just call `CameraRoll.getPhotos({assetType: 'Photos'})`

* React Native version: 0.43.4
* Platform: iOS
* Development Operating System: MacOS
* Dev tools: Xcode 8.3.2, iOS 10.3.1

**Comment by elanini** [comment]
Hi zackify, I'm having the same issue. How did you solve it?

**Comment by klvs** [comment]
@zackify I'm running into this problem. I noticed you closed it, did you solve it or find a work around, if so what is it?

**Comment by zackify** [comment]
It works fine when I call that method in my own component. Doesn't seem to
be a bug with React native but rather that 3rd party library. I did the
exact call to get all media types and it worked fine for me, so I closed.

**Comment by pentarex** [comment]
I am having the same issue with CameraRoll from RN.

```javascript
CameraRoll.getPhotos({
            first: 20,
            groupTypes: 'All',
            assetType: 'Photos'
        }).then(r => {
            console.log(r);
            
        }).catch((err) => {
             console.log('gallery', err);
        });
```

The thing is that some photo for some reason filename is missing (maybe iCloud). And I think its crashing because of that (not completely sure), but as I see @zackify also his filename was nil.

It doesn't fail under the simulator, but on my real device, where most of my photos are on iCloud.

**Comment by sujit13666** [comment]
Same Here guys.

**Comment by pentarex** [comment]
The pull request was approved, it only needs to get merged.

**Comment by facuescobar** [comment]
@pentarex was this update merged? 

I can not see it in the latest version of RN

**Comment by pentarex** [comment]
I don’t think. Check my profile for alternative library that I’ve wrote if you want

**Comment by facuescobar** [comment]
@pentarex I did the same update on my project and I think that fixed some cases.

But I'm still having errors with iCloud files, I have reported this https://github.com/facebook/react-native/issues/18159

It's being difficult to find the reason of this bug because I know that is happening for some people, but I couldn't reproduce it 🤯

if you have any idea or suggestion let me know please!

**Comment by pentarex** [comment]
@facuescobar except the thing that I've told you, I have no other clue. Also they are using old framework for the Gallery and this is taking the pictures from iTunes, it has some strange ordering, if you want to test out this one be my guest https://github.com/pentarex/react-native-gallery-manager
