### ISSUE TITLE
RTL with NavigatorIOS

### ISSUE THREAD

**Issue by sticknor** [facebook/react-native#13673]
Are RTL navigator transitions supported for NavigatorIOS?

I have followed the steps [here](https://facebook.github.io/react-native/blog/2016/08/19/right-to-left-support-for-react-native-apps.html) but have been unable to reverse the navigation stack. 

Thanks!

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
