### ISSUE TITLE
[FlatList] FlatList landscape mode bugs getItemLayout

### ISSUE THREAD

**Issue by MrChe** [facebook/react-native#13736]
After orientation mode === `LANDSCAPE` currentIndex = 0.
I have grid item, after select item - open carousel(FlatList) on currentIndex, and if i rotate device my current item in carousel set 0.
This example 

`slider.js`

```
componentDidMount() {
    const wait = new Promise(resolve => setTimeout(resolve, 500));  // Smaller number should work
    wait.then(() => {
      this.list.scrollToIndex({
        viewPosition: 0.5,
        index: this.props.page || 0,
        animated: false,
      });
    });
    this._setScrollTarget(this.props);
  }

componentWillReceiveProps(nextProps) {
    if (...) {
      this._setScrollTarget(nextProps);
    }
  }
_setScrollTarget(props) {
    const {
      width,
      page,
    } = props;
    this.list.scrollToOffset({
        x: ((width) * page),
        y: 0,
        animated: false,
      });
  }
_getItems = (media, width, height) => {
    const { MediaItem, page } = this.props;
    const items = [];
    for (let i = 0; i <= media.length - 1; i++) {
      const item = media[i];
      items.push(
          <MediaItem
            key={`page-${i}`}
            screen={{ width, height }}
            currentIndex={page}
            {...item}
          />,
      );
    }
    return items;
  };
 ...
 const items = this._getItems(media, width, height);
    return (
      <FlatList
        ref={(ref) => { this.list = ref; }}
        style={{
          flex: 1,
        }}
        horizontal
        pagingEnabled
        scrollEnabled={enabled}
        removeClippedSubviews={false}
        scrollToEnd={this._onScrollEnd}
        data={items}
        renderItem={({ item }) => item}
        getItemLayout={this._getItemLayout}
        shouldItemUpdate={this._shouldItemUpdate}
      />
    ); 
```

`Main.js`

```
...
return (
<View
style={{flex: 1}}
onLayout={this._onLayout} // change width/height orientation
>
 <MediaSlider
          media={files} // data files
          MediaItem={FileViewer} // files
          page={selectedIndex} // currentIndex
          width={this.state.layout.width}
          height={this.state.layout.height}
        />
</View>
)
```

this video - http://take.ms/DHdyO

## **Additional Information**

React Native version: v0.43.1
Platform: Both
Operating System: MacOS

**Comment by mobinni** [comment]
I had the exact same issue, it's not an easy one to solve. You basically wanna force a rerender after the rotation with onLayout. This however does not really work reliably. What we ended up opting for was writing native bridging components to give us the rotation value from 0 to 270 through listeners and based on that do a non-native rotation through transforms.

**Comment by sahrens** [comment]
You didn't include your `_getItemLayout` implementation - it's hard to figure out what's wrong with incomplete code.

**Comment by MrChe** [comment]
```
const { height, width } = Dimensions.get('window');

class FileSlider extends PureComponent {
  constructor() {
    super();
    this.state = {
      isLandscape: false,
      layout: {
        height,
        width,
      },
    };
  }

  _onLayout = (event) => {
    this.setState({
      layout: {
        height: event.nativeEvent.layout.height,
        width: event.nativeEvent.layout.width,
      },
    });
  };

return (
      <View
        style={{
          position: 'relative',
          flex: 1,
          backgroundColor: 'black',
        }}
        onLayout={this._onLayout}
      >
        <MediaSlider
          media={files}
          MediaItem={FileViewer}
          selectedIndex={selectedIndex}
          enabled={!videoPlay}
          width={this.state.layout.width}
          height={this.state.layout.height}
          onPageChanged={onItemSelected}
        />
    </View>
)
```

**Comment by MrChe** [comment]
@sahrens 
The only solution at the moment,

`slider.js`
```
componentWillReceiveProps(nextProps) {
    if (
      nextProps.width !== this.props.width
      || nextProps.media !== this.props.media
    ) {
      setTimeout(() => {
        this.list.scrollToIndex({
          viewPosition: 0.5,
          index: this.props.selectedIndex,
          animated: false,
        });
      }, 0);
    }
  }
```
But in this solution there is 1 big minus - this is a delay, and flickering(((

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
