### ISSUE TITLE
back-icon@1.5x.android.png' could not be found

### ISSUE THREAD

**Issue by Sir-hennihau** [facebook/react-native#13731]
Code worked yesterday, but today not anymore. Didn't change a thing. This occured to me multiple times.

I get the following error. Couldnt reliably fix it yet.

> error: bundling: Error: 'node_modules/react-native/Libraries/CustomComponents/NavigationExperimental/assets/back-icon@1.5x.android.png' could not be found, because 'node_modules/react-native/Libraries/CustomComponents/NavigationExperimental/assets' is not a subdirectory of any of the roots  ('/home/sirhennihau/Workspace/next')
    at /home/sirhennihau/Workspace/next/node_modules/react-native/packager/src/AssetServer/index.js:181:13
Bundling `index.android.js`  100.0% (432/432), failed.
Error: 'node_modules/react-native/Libraries/CustomComponents/NavigationExperimental/assets/back-icon@1.5x.android.png' could not be found, because 'node_modules/react-native/Libraries/CustomComponents/NavigationExperimental/assets' is not a subdirectory of any of the roots  ('/home/sirhennihau/Workspace/next')
    at /home/sirhennihau/Workspace/next/node_modules/react-native/packager/src/AssetServer/index.js:181:13
Error: 'node_modules/react-native/Libraries/CustomComponents/NavigationExperimental/assets/back-icon@1.5x.android.png' could not be found, because 'node_modules/react-native/Libraries/CustomComponents/NavigationExperimental/assets' is not a subdirectory of any of the roots  ('/home/sirhennihau/Workspace/next')
    at /home/sirhennihau/Workspace/next/node_modules/react-native/packager/src/AssetServer/index.js:181:13

I run code for a static userinterface mockup. Uses compressed media data in the views.

"dependencies": {
    "react": "16.0.0-alpha.6",
    "react-native": "0.43.3",
    "react-native-video": "^1.0.0"
  }
Run on an Android
Ubuntu 15
Atom, Android SDK, node.js, React-Native-Video.

Any suggestions?

```

 render() {
    return (
      <ScrollView>
        <Text>RnB</Text>
        <ScrollView horizontal={true}>

          <Video
          style={{ flex: 1 }}
          source={require('./app/media/compressed/Chrisbrown-1.mp4')}
          style={{ width: 150, height: 150 }}
          ref={(ref) => {
            this.player = ref
          }}
          muted={true} />

          <Video
          style={{ flex: 1 }}
          source={require('./app/media/compressed/Freestylekendrick-1.mp4')}
          style={{ width: 150, height: 150 }}
          ref={(ref) => {
            this.player = ref
          }}
          muted={true} />
          ...
        {/*
        //Multiple ScrollViews follow here, containing videos and images
        */}
          ...`

**Comment by saubcy** [comment]
you can set a long REACT_NATIVE_FSOP_TIMEOUT, the default value is 15000ms, but if toooooo mutch files if may not enough, but it give a confused error msg...
btw, you can change it in <your project>/node_modules/react-native/packager/src/AssetServer/index.js

**Comment by achuvm** [comment]
Thanks @saubcy! This solved the issue for us because we have ~600MB of assets in the packager.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
