### ISSUE TITLE
onChange/onContentSizeChange not called for <TextInput> when set text to child <Text>

### ISSUE THREAD

**Issue by huangmr** [facebook/react-native#13732]
### Description

onChange/onContentSizeChange not called after setting text to child <Text> in <TextInput>, it only works when sets `value` to it directly (on IOS only).

### Reproduction Steps and Sample Code

Set `text` props to the component doesn't trigger TextInput to expand.

  ***An example of your code is REQUIRED***

```
export class ExpandingTextInput extends React.Component {
  props: Props;
  state: State = {
    height: this.props.minHeight,
  };

  onContentSizeChange = (event) => {
    const height = event.nativeEvent.contentSize.height;
     this.setState({ height });
  };

  render() {
    return (
      <TextInput
        {...this.props}
        multiline
        onContentSizeChange={this. onContentSizeChange}
        style={[this.props.style, { height: this.state.height }]}
      >
        {this.props.children}
      </TextInput>
    )
  }
}
```

and this is how it is being used

```
<ExpandingTextInput {...this.props}>
      <Text>{this.props.text}</Text>
</ExpandingTextInput>
```

### Solution

Still working on one...

### Additional Information

* React Native version: [FILL THIS OUT: Be specific, filling out "latest" here is not enough.]
* Platform: [FILL THIS OUT: iOS, Android, or both?]
* Development Operating System: [FILL THIS OUT: Are you developing on MacOS, Linux, or Windows?]
* Dev tools: [FILL THIS OUT: Xcode or Android Studio version, iOS or Android SDK version, if applicable]

**Comment by mag1492** [comment]
#13732 maybe this can help.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
