### ISSUE TITLE
fs operation timeout but give a confused error message by 'xxx could not be found here, because xxx is not a subdirectory of any of the roots xxx'

### ISSUE THREAD

**Issue by saubcy** [facebook/react-native#13793]
I have a project with tooooo mutch images, and from some day , when package it, it's random show me the error:

>  'node_modules/react-native/Libraries/CustomComponents/NavigationExperimental/assets/back-icon@1.5x.android.png' could not be found, because 'node_modules/react-native/Libraries/CustomComponents/NavigationExperimental/assets' is not a subdirectory of any of the roots ('/home/saubcy/proj/Musus')

at the very beginning, I really believe it cause by path error, until I read the code of 'node_modules/react-native/packager/src/AssetServer/index.js'

> _findRoot(roots, dir, debugInfoFile) {
    return Promise.all(
      roots.map(root => {
        const absRoot = path.resolve(root);
        // important: we want to resolve root + dir
        // to ensure the requested path doesn't traverse beyond root
        const absPath = path.resolve(root, dir);
        return stat(absPath).then(fstat => {
          // keep asset requests from traversing files
          // up from the root (e.g. ../../../etc/hosts)
          if (!absPath.startsWith(absRoot)) {
            return {path: absPath, isValid: false};
          }
          return {path: absPath, isValid: fstat.isDirectory()};
        }, _ => {
          return {path: absPath, isValid: false};   <----------------------- LOOK ME HERE!!
        });
      })
    ).then(stats => {

when the fs op is timeout, the isValid just be setted to false, with out any other message, then next:

> .then(stats => {
    	
    	//console.log("stats.length: " + stats.length)
      for (let i = 0; i < stats.length; i++) {
      	console.log("stats[" + i + "].path: " + stats[i].path + ", isValid: " + stats[i].isValid);
        if (stats[i].isValid) {
          return stats[i].path;    <----------------------- LOOK ME HERE!!
        }
      }
      const rootsString = roots.map(s => `'${s}'`).join(', ');
      throw new Error(     <----------------------- AND HERE!!
        `'${debugInfoFile}' could not be found here, because '${dir}' is not a ` +
        `subdirectory of any of the roots  (${rootsString})`,
      );
    });

the confused error message  throwing...

**Comment by dujushi** [comment]
Great catch. I had the same issue and had to remove some photos to make it work. But it only happens when I use release scheme.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
