### ISSUE TITLE
[ListView] Cryptic errors from renderHeader and renderSectionHeader

### ISSUE THREAD

**Issue by ccheever** [facebook/react-native#1379]
If you try throwing an error from an implementation of `renderRow` or `renderSectionHeader` in a `ListView`, you get a very cryptic error message with a stack trace that doesn't point to the problematic code at all.

A similar problem also occurs if either of those methods returns `undefined`.

It would be good if those weren't so cryptic (maybe wrapped in a `try/catch`?).

**Comment by brentvatne** [comment]
@ccheever - Have any time to put together a PR to fix this? High quality error messages are very important for dev workflow :smile:

**Comment by ccheever** [comment]
@brentvatne - sorry haven't had time yet :/

**Comment by brentvatne** [comment]
:dancer:

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/listview-cryptic-errors-from-renderheader-and-rendersectionheader

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
