### ISSUE TITLE
There is no possibility to catch start/stop pull-to-refresh gesture event of "RefreshControl" component

### ISSUE THREAD

**Issue by valeriik** [facebook/react-native#13803]
**Do you want to request a *feature* or report a *bug*?**
Feature.

**What is the current behavior?**
There is no possibility to catch start/stop pull-to-refresh gesture event of "RefreshControl" component.

**What is the expected behavior?**
Would be great have something like "onPullStart" and "onPullEnd" event to know the moment of start/stop pull-to-refresh gesture.

Related question on [stackoverflow](http://stackoverflow.com/questions/43784388/is-there-a-way-to-catch-start-stop-event-using-pull-to-refresh-gesture-of-listvi).

![3](https://cloud.githubusercontent.com/assets/24571089/25739204/8f773a20-3189-11e7-9aa7-400002a380f1.jpg)

**Comment by vonovak** [comment]
may I just ask what you need that event for?

**Comment by valeriik** [comment]
This also connected with another "bad news" about refreshControl: "Only works for vertical ScrollViews (horizontal prop must be false).".
For example user needs to disable horizontal scroll while vertical scroll (in case we have 2 ListView's: one parent, second nested, like functionality of TabView with scrollable tabs (horizontal scroll)).

There are 3 callbacks to control start/end scrolling content of ListView: "onScroll", "onScrollEndDrag" and "onMomentumScrollEnd". But in Android, when user at the top of ListView and pulling down "onScroll" does't fired (because on Android actually content don't scrolling, but on iOS do).

**Comment by sahir** [comment]
@valeriik did you find any solution

**Comment by cityvoice** [comment]
The refreshControl is too ugly,.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
