### ISSUE TITLE
Has anyone been able to get React-Navigation to work with hot reloading?

### ISSUE THREAD

**Issue by marstall** [facebook/react-native#13822]
Hi all,
Like a good react-native citizen, i upgraded my app to use react-navigation and am enjoying it. 

However, it seems to have broken hot reloading. Now, whenever I make a change, it resets the navigation state. Real time sink there. Can anyone post work-around code, or explain to me what I'm doing wrong? Thanks1

**Comment by hramos** [comment]
Sorry to hear about your trouble. I believe I saw someone file an issue about this elsewhere in the repo. I'll need to close this specific issue here because there isn't sufficient information to act on it. If you want this to remain open, could you update your post to make sure it meets the issue guidelines?
