### ISSUE TITLE
In geoLocation API getcurrentPosition error  

### ISSUE THREAD

**Issue by neilzhengzx** [facebook/react-native#13854]
Description

when I set 'navigator.geolocation.getCurrentPosition' In android, always get error:Location request timed out.the permission is set ok, so I dont know how to get the position. 

Reproduction

navigator.geolocation.getCurrentPosition(
            (position) => {
                let initialPosition = JSON.stringify(position);
                console.log(initialPosition);
            },
            (error) => console.log(JSON.stringify(error)),
            {enableHighAccuracy:true, timeout: 2000}
        );
Solution

Need to find a way why timed out

Additional Information

React Native version: 0.44
Platform: Android
Operating System: Mac OS
Dev tools: Android SDK v23

**Comment by rocwangv** [comment]
+1

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by neilzhengzx** [comment]
when i use react-native with verssion 0.47.1. I can get location
