### ISSUE TITLE
Inspector error when click on component has percentage styles

### ISSUE THREAD

**Issue by tiendn** [facebook/react-native#13871]
## React Native 0.43.4

**Comment by monkey826** [comment]
### Inspector
Sometimes I inspect iOS app with Inspector for seeking some View. 
But when I tapped in some components has percentage style like `marginTop: '7%'`, it has error.
Did anyone have this?
![simulator screen shot may 9 2017 10 29 48 pm](https://cloud.githubusercontent.com/assets/15717476/25859293/44673260-3508-11e7-8b29-2c2bdf3a9266.png)

**Comment by dobrienlzd** [comment]
Not sure it percents are allowed. What makes you think they are? Also have you tried upgrading to 0.44.0
npm install --save react-native@0.44.0  Plus this is really more a react version issue perhaps than native. Check that you have latest version of react installed as well or at least what is in package.json

if not try 
npm install --save react@Alpha-16.0.0.6  or whatever actually specified in package.json

Let us know if this helps, but I don't know that % is supported.

**Comment by monkey826** [comment]
Thanks.
I'm going to try upgrade React Native 0.44 later because my prj used Navigator but in 0.44, its be deleted and replaced by react-navigation. 

Do you have latest version of react native installed ? Any you don't have any trouble when inspect `Component` with `percentage` style? like margin, padding with value is `%`.

**Comment by seanyusa** [comment]
I have this issue as well with a percentage on padding when using the inspector. Version 0.45

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
