### ISSUE TITLE
RNTester doesnt compile. Asks for boost/iterator/iterator_adaptor.hpp

### ISSUE THREAD

**Issue by pvinis** [facebook/react-native#13895]
### Description

Tried to run RNTester. The project doesnt compile for ios. It gives me a `boost/iterator/iterator_adaptor.hpp file not found` on `BitIteratorDetail.h`

### Reproduction Steps and Sample Code

Try to run RNTester

### Solution

Where is boost? Is it the wrong version?

### Additional Information

* React Native version: master@d40a7ea7f98211362f780fa15b105f3a71e0203b
* Platform: iOS
* Development Operating System: macOS
* Dev tools: Xcode

**Comment by sukeyang** [comment]
i have the same question too

**Comment by liushigit** [comment]
I solved this by removing everything in '~/.rncache' and run `react-native run-ios` again. Make sure all the tar balls in the `.rncache` have their integrity.

**Comment by TrustTheBoy** [comment]
Do you have any solution? I follow the @liushigit  method after the implementation, and did not solve this problem

**Comment by pvinis** [comment]
in the latest master a couple of days ago I could compile, but when I put release, it gave an error about folly this time. something is wrong with the setups.

**Comment by superyarik** [comment]
also have folly error now:

[armeabi-v7a] SharedLibrary  : libreactnativejnifb.so
.../react-native/ReactAndroid/../ReactCommon/jschelpers/JSCHelpers.h:23: error: undefined reference to 'folly::stringPrintf(char const*, ...)'
.../react-native/ReactAndroid/../ReactCommon/jschelpers/JSCHelpers.h:35: error: undefined reference to 'folly::stringPrintf(char const*, ...)'
.../react-native/ReactAndroid/../ReactCommon/jschelpers/JSCHelpers.h:35: error: undefined reference to 'folly::stringPrintf(char const*, ...)'
collect2: error: ld returned 1 exit status
make: *** [.../react-native/ReactAndroid/build/tmp/buildReactNdkLib/local/armeabi-v7a/libreactnativejnifb.so] Error 1
make: *** Waiting for unfinished jobs....
make: Leaving directory `.../react-native/ReactAndroid/src/main/jni/react/jni'
:ReactAndroid:buildReactNdkLib FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ReactAndroid:buildReactNdkLib'.
> Process 'command '.../android-ndk-r10e/ndk-build'' finished with non-zero exit value 2

**Comment by Liberty-liu** [comment]
who can help me？i have the same a question too

**Comment by micabe** [comment]
me too

**Comment by musicode** [comment]
how to resolve it?

**Comment by HaseebYousaf** [comment]
+1

**Comment by redgang** [comment]
me too

**Comment by xiangwangfeng** [comment]
I solved this problem by downloading boost 1.63 from boost.org and replace the old one which is downloaded by "[ios-install-third-party.sh](https://github.com/facebook/react-native/blob/master/scripts/ios-install-third-party.sh)"。
The location of boost is "node_modules/react-native/third-party/boost_1_63_0".
But it seems there is no bug in ios-install-third-party.sh

**Comment by iineva** [comment]
# Temporary Solution
Download [boost_1_63_0.tar.gz](https://sourceforge.net/projects/boost/files/boost/1.63.0/) to `~/.rncache/`, replace if exist.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by jackkav** [comment]
This issue is caused by an implementation issue with the following bash script.
https://github.com/facebook/react-native/blob/1e8f3b11027fe0a7514b4fc97d0798d3c64bc895/scripts/ios-install-third-party.sh
Here we should check integrity of file rather than just its existence, then attempt to resume or restart. At the very least the extract failed message should be more obvious.

**Comment by shergin** [comment]
I have no any idea why it is happening, but this fixed the problem for me:
 * `rm -r third-party/boost_1_63_0`
 * `./scripts/ios-install-third-party.sh`
 
Yes, probably we have to add some integrity checks inside `ios-install-third-party.sh`.
PR is welcome. 😄

**Comment by harrycondron** [comment]
Solved this issue by deleting the Podfile for boost, and running `pod install` again, hope this helps 👍
