### ISSUE TITLE
TextInput clearButtonMode not showing when multiline set to true

### ISSUE THREAD

**Issue by opolyo01** [facebook/react-native#13927]
### Description

Here's config props I tried to set on TextInput, but clearButton wouldn't show up
multiline: true,
numberOfLines: 2,
clearButtonMode: "while-editing",

### Reproduction Steps and Sample Code

List all the steps required to reproduce the issue you're reporting. These steps should be clear and concise.

  ***An example of your code is REQUIRED***
render() {
      return (
         <TextInput
                returnkeyType: "done",
                multiline: true,
                numberOfLines: 2,
                clearButtonMode: "while-editing",
         />
      );
   }

### Solution

Add clearbutton

### Additional Information

* React Native version: 42
* Platform: [FILL THIS OUT: iOS, Android, or both?] iOS
* Development Operating System: macOS
* Dev tools: iOS

**Comment by poyannabati** [comment]
Still in 0.45.1

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
