### ISSUE TITLE
react-native link

### ISSUE THREAD

**Issue by makoy21** [facebook/react-native#13943]
Hi, I having this error when installing and linking the react-native-vector-icons.

**Command I ran:**
npm i react-native-vector-icons --save && react-native link react-native-vector-icons

**Result:**
rnpm-install info Linking react-native-vector-icons android dependency
rnpm-install info Android module react-native-vector-icons has been successfully linked
rnpm-install info Linking react-native-vector-icons ios dependency
rnpm-install info iOS module react-native-vector-icons has been successfully linked
rnpm-install info Linking assets to ios project
rnpm-install ERR! Something went wrong while linking. Error: Expected "/*" or ";" but "\"" found.

Expected "/*" or ";" but "\"" found.
* React Native version: 0.43
* Platform: Both
* Development Operating System: macOs

**Comment by renbo809199658** [comment]
after I run react-native link command ,It shows that  the .xcodeproj can't be  parsed error when I what to open the project.And I run react-native second time ,It also show the same logs above(Expected "/*" or ";" but """ found.).

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
