### ISSUE TITLE
How to generate final APK file

### ISSUE THREAD

**Issue by payamka** [facebook/react-native#13967]
Hi
After application development How can I generate final apk file?
I preffer that just do this without signing.

**Comment by mavenave** [comment]
You have to sign it.

**Comment by Kureev** [comment]
Hi @payamka!

You can't distribute / install on real Android device an application w/o a signature. If you want to learn more about it (which I strongly encourage you to do), there is a similar [StackOverflow question](http://stackoverflow.com/questions/23906799/why-should-i-sign-my-application-apk-before-release) that may give you a good insight about application signing in Android world.

You can also use an [official React Native](https://facebook.github.io/react-native/docs/signed-apk-android.html) documentation to generate a signed APK for your application.

I'm about to close this issue because there's nothing to discuss and / or we can do as a React Native team.
