### ISSUE TITLE
Application has not been registered error

### ISSUE THREAD

**Issue by payamka** [facebook/react-native#13964]
Hi
I'm new to React Native. Sometimes after some changes on android app I get this error in emulator:
Application ... has not been registered
Restarting CMD and emulator and etc doesn't fix it!
Why this message is shown and how to fix it?
I'm using Win8.
Thank you!

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
