### ISSUE TITLE
[iOS][RefreshControl] broken after re-enter app

### ISSUE THREAD

**Issue by fokoz** [facebook/react-native#13977]
RefreshControl use with ListView stops spinning and gets stuck(refreshing=true) when go out and re-enter app(press home button and then re-enter app).
I also have tested on ActivityIndicator and it works fine.

## Additional Information

React Native version: 0.43
Platform: iOS
Development Operating System: macOS
Device: Real Device iOS 10

**Comment by flyskywhy** [comment]
If your project use code-push before rn 0.43, you need upgrade to the latest code-push.
That works for me on stuck of ListView (rn 0.43, Android)

**Comment by smartdevth** [comment]
@flyskywhy The issue I've seen is on iOS, what about iOS of your project ? Does it stop spinning when out-in app ?

**Comment by flyskywhy** [comment]
@smartdevth , sorry, I tested my APP again, code-push has no relationship. In my Android case, patch like this

    sed -i "s/Platform.OS === 'ios'/Platform.OS !== 'web'/" node_modules/rn-viewpager/viewpager/ViewPager.js
actually solved my stuck problem, maybe this patch's root cause is ViewPagerAndroid ref to https://github.com/facebook/react-native/issues/13463 , and there is no stuck problem in my iOS project.

**Comment by smartdevth** [comment]
Any update on android? 
Does anybody find this weird thing like me ?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
