### ISSUE TITLE
React native version always gets downloaded from Maven

### ISSUE THREAD

**Issue by idanr84** [facebook/react-native#13974]
Adding third party dependencies to my project that have inside their build gradle :
` ' provided "com.facebook.react:react-native:+'` or 
`'compile "com.facebook.react:react-native:+'`
Causes an old react version (0.20.1) to be downloaded from maven.

In my project I setup my local node modules folder as a local maven, but it doesn't seem to help.
This obviously causes the third party lib to try to compile against an old react native and fail.
What's weird is that my project still uses the local and correct react native version, so basically I have two version :
1. inside my .gradle/cache folder (0.20.1)
2. inside node modules folder (new one)

How can I fix that ?

**Comment by dobrienlzd** [comment]
give react-native:0.44.0 instead or react-native:+ ?

**Comment by idanr84** [comment]
@dobrienlzd these are not my libs, I use third party (like react-native-maps) which have this import inside of them).
This problem only occur in my project btw, when I use the sample Android project that comes with the react native  package everything works, fine even after adding the third party.
Just not sure where exactly the problem lies.

**Comment by Brian-Kaplan** [comment]
i think that this `compile "com.facebook.react:react-native:+`will still download .20.1 into your gradle cache but you should be ignoring that. Did you follow the steps outlined in the docs here https://facebook.github.io/react-native/docs/integration-with-existing-apps.html#prepare-your-current-app ?

**Comment by idanr84** [comment]
Eventually the issue was that in `setting.gradle` I'v put `'project.projectDir'` and not 
> 'rootProject.projectDir'
That caused all third parties to look for react in *their* local project instead of the main project folder.
Stupid mistake, though easy to make :)

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
