### ISSUE TITLE
PushNotificationIOS.scheduleLocalNotification repeatInterval has no affect

### ISSUE THREAD

**Issue by SpecialDOS** [facebook/react-native#13981]
### Description

I'm calling PushNotificationIOS.scheduleLocalNotification and including a `repeatInterval` with value of 'minute'. The local notification is firing as expected once, but is not repeated every minute. When I look inside of the notification as it is returned by `PushNotificationIOS.getScheduledLocalNotifications` the notification object does not have a `repeatInterval` property or anything that looks related to this. I'm wondering if this config property actually does anything?

I'm seeing the same behavior in the simulator 6s, and on my iPhone running iOS 10.

### Reproduction Steps and Sample Code

I am scheduling a local notification as follows:

`
let now = new Date();
now.setHours(13);
now.setMinutes(53);
PushNotificationIOS.scheduleLocalNotification({
  fireDate: now.toISOString(),
  alertBody: 'Im alerting you!',
  repeatInterval: 'minute'
});
`
And as I've said this does fire once successfully at the expect time, it just doesn't repeat after that.

### Solution

I haven't looked into the cause of the issue... Perhaps I have misunderstood the API?

### Additional Information

* React Native version: 0.40.0
* Platform: iOS
* Development Operating System: macOS
* Dev tools: XCode 8.2.1

**Comment by Aleksion** [comment]
I'm  having the same problem. The first one fires as it should, but subsequent ones doesn't. I've only tested it with repeatInterval "minute", but I'm going to record back once I've had time to verify that it's the same for "hour" as well

**Comment by sumesh1993** [comment]
+1

**Comment by scottarivale** [comment]
@SpecialDOS did you ever find a resolution for this? Running into it myself.

**Comment by SpecialDOS** [comment]
Nope

**Comment by scottarivale** [comment]
@SpecialDOS I found the issue I was facing, possibly it's what you are up against as well.  Are you by any chance also using [react-native-notifications](https://github.com/wix/react-native-notifications)?  Turns out that both RNN and PushNotificationIOS both define an `RCTConvert` to convert json into a UILocalNotification.  PushNotificationIOS preserves the 'repeatInterval' property, BUT RNN's version does not and it overwrites the properly functioning version.
I've added a pull request [here](https://github.com/wix/react-native-notifications/pull/97) if you'd like to try the fix locally.
