### ISSUE TITLE
Init proyect fails in compliate version android

### ISSUE THREAD

**Issue by alejonext** [facebook/react-native#13987]
# Description
The project fails following the instructions. In other words, the template fails for android. This generates a Java error.

# Reproduction Steps and Sample Code
No example code, because is the template. Starts proyect and run
```console
$ react-native init myProyect
$ cd myProyect
$ react-native run-android
```
Prints
```console
Building and installing the app on the device (cd android && ./gradlew installDebug)...
Incremental java compilation is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 24.996 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html
```
## Additional Information
* react 16.0.0-alpha.6
* react-native 0.44.0
* Platform : Android
* OS: MacOX Sierra
* Dev tools: Android Studio

**Comment by dobrienlzd** [comment]
try  delete node_modules in your root directory.

    npm install react@16.0.0-alpha.6 --save
     npm install react-native@0.44.0 --save
    npm install

Or just remove any ^ in front of version numbers in package.json and do npm install.

Make sure you have emulator running.  
You might need to run packager using npm start  and then react-native run-android or just npm start and use studio to run Android application as usual. Let us know what happens!

**Comment by alejonext** [comment]
That is not a solution

**Comment by dobrienlzd** [comment]
show us your package.json contents and also tell us what versions of react and react-native are actually installed.  Remember you sometimes need to do:
npm start
then
react-native run-ios/android

npm list | grep 'react@'        // what version is really installed?
npm list | grep 'react-native@'  // what version of react native?

React Native works out of the box.

**Comment by alejonext** [comment]
```
├─┬ react@16.0.0-alpha.6
├─┬ babel-preset-react-native@1.9.2
├─┬ react-native@0.44.0
│ ├── babel-preset-react-native@1.9.2 deduped
```

**Comment by mhannig** [comment]
@alejonext I had the same error; have you installed the Android SDK via brew? Removing gradle via `brew uninstall gradle` and installing the SDK manually did the trick for me.

Be sure to set the correct environment variables afterwards and reload your shell.

**Comment by hramos** [comment]
Hi there! This issue is being closed because {:search=>"repo:facebook/react-native is:open is:issue updated:<2017-05-25 -label:\"Good First Task\" -label:\"Help Wanted\" ", :message=>"it has been inactive for a while"}. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by nlt2390** [comment]
In case someone run into this issue, just open the project in Android Studio, wait a bit for it to update something and then run "react-native run-android" again.

**Comment by madeeha96** [comment]
This issue still exist in react-native: 0.53.0

**Comment by hramos** [comment]
@madeeha96 feel free to open a new issue with any details specific to your problem.

**Comment by madeeha96** [comment]
My issue is resolved now by changing android SDK version

1-) change version of android SDK in build.gradle file 
- Add google() to repositories if it's only jcenter()
 repositories {
        jcenter()
        google()   ----> (add this)
 - dependencies {
       classpath 'com.android.tools.build:gradle:3.0.1'  (previously it was 2.2.3) 

2-) Add following line to graddle-wrapper.properties  
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip  ( upgrade it)
_distributionUrl=https\://services.gradle.org/distributions/gradle-2.14.1-all.zip (previous version)_

3-) Then run 'react-native-run-android' 

works out for me!!!
