### ISSUE TITLE
[TextInput] Scroll its blocked when touch a TextInput with textAlign center

### ISSUE THREAD

**Issue by KarlosQ** [facebook/react-native#13997]
### Description

In Android when I try to scroll touching a TextInput with style {textAlign:'center'} the scroll its blocked.

With textAlign center:

![aligncenter](https://cloud.githubusercontent.com/assets/15233913/26112524/6ea32764-3a58-11e7-90fe-dd6d16c48c49.gif)

Without  textAlign: 

![noalign](https://cloud.githubusercontent.com/assets/15233913/26112530/7331434c-3a58-11e7-877c-1dfc329b64bc.gif)

### Additional Information

* React Native version: 0.44
* Platform: Android
* Development Operating System: macOS
* Dev tools: Android Studio

**Comment by igofind** [comment]
I am facing similar issue but with {textAlign: 'right'}.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by yqz0203** [comment]
any solutions? @KarlosQ

**Comment by Aman40** [comment]
Still exists. Very inconveniencing.
