### ISSUE TITLE
Generate flow files for `react-native`

### ISSUE THREAD

**Issue by ckknight** [facebook/react-native#14007]
### Description

As per https://github.com/facebook/react-native/issues/13238, I would like to be able to use a different version of flow than what `react-native` explicitly requires. This is necessary because our mobile project is in a lerna-style monorepo.

@janicduplessis provided a solution which is to ignore `react-native` and create a type interface for it, so I'm asking how to specifically do that.

### Reproduction Steps and Sample Code

I attempted to use `flow`'s `gen-flow-files`, but was unsuccessful:

```sh
$ $(npm bin)/flow gen-flow-files . --out-dir ../react-native-types/
Found 13295 files, generating libdefs...
Error: Failure("/Users/ckknight/Code/facebook/react-native/react-native-git-upgrade/package.json: Failure(\"Failed to extract the exports of AnyT\")")
```

### Solution

Either a way to generate the flow definitions or a concrete flow definition for `react-native`.

### Additional Information

* React Native version: v0.44.0 (latest as of 2017-05-16)
* Platform: N/A
* Development Operating System: macOS
* Dev tools: N/A

**Comment by sibelius** [comment]
try this https://github.com/entria/yarn-package-boilerplate/blob/master/package.json#L47

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
