### ISSUE TITLE
android build creating too many DEX files

### ISSUE THREAD

**Issue by npomfret** [facebook/react-native#14021]
I'm getting a ClassNotFoundException.  It seems that the default android build is creating an APK that has over 100 DEX files in it (mine has 138!) which isn't apparently allowed on API 21 and 22 devices.  

There some more info [here](https://issuetracker.google.com/issues/37134279).

**Comment by ptomasroos** [comment]
This is because there's too many dependencies in your android app usually. We've been running single dex with reducing dependencies and running multi-dex as well when we had more dependencies. But yes we're not targeting 21 and 22. But I can't really see how this could be a implication of react-native really.

**Comment by npomfret** [comment]
My app has ~170k methods, that should fit into about 3 DEX files right?  It seems some combination of gradle or android has a bug in it where DEX files aren't collapsed.  I understand that some versions of android have a 100 DEX file limit.  

Reducing my API dependency back to 16 resulted in a more sensible APK.  So it seems that it's just not possible to build a working v21 app at the moment.
