### ISSUE TITLE
React-Native 0.44.0 + react alpha 16: Bugs

### ISSUE THREAD

**Issue by igroz777** [facebook/react-native#14020]
### Description

Created a new app with react-native init.

Installed app on emulator. Ran dev server. White screen on emulator. Restarted dev server. No change. Reinstalled app on emulator. No change. Restarted emulator. No change. Restarted emulator again and dev server. App showed up. Restarted system. Ran app on emulator. White screen again.

Above happens off and on. I tried creating a new app. Same experience.

Some of my colleagues experienced the same problem. Running on real devices and emulators.

### Solution

Fix this issue or downgrade react-native cli to use stable versions.

### Additional Information

* React Native version: 0.44.0
* Platform: Android
* Development Operating System:Windows 10 & Windows 8.1

**Comment by stoffern** [comment]
your app code? sounds like you need a `{flex: 1}` style

**Comment by igroz777** [comment]
@stoffern with the default setup. I thought maybe its something on my end but we had a react-native training session in my firm and people who did fresh installs had the issue as well.

**Comment by stoffern** [comment]
Sounds to me like your emulator or device cant reach the "dev server/bundler".
Check that the IP is correct, see docs.

**Comment by rom1k** [comment]
I've had the same white screen bug since upgrading to 0.44.2 (from 0.43.3), on an iOS ad hoc version and in an android emulator. I can't say for sure that the white screen on iOS is related or if it's caused by xcode provisioning shit or something, but I've definitely had it on android and it disappeared after reloading.

Found another issue of the same problem
https://github.com/facebook/react-native/issues/14187

**Comment by igroz777** [comment]
has anyone had any luck in figuring out the issue?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
