### ISSUE TITLE
AccessibilityManager.setAccessibilityContentSizeMultipliers exception

### ISSUE THREAD

**Issue by pietropizzi** [facebook/react-native#14043]
### Description

Since upgrading to React Native 0.44 (from 0.43) when calling `AccessibilityManager.setAccessibilityContentSizeMultipliers` I get this red screen

![simulator screen shot 18 may 2017 13 58 48](https://cloud.githubusercontent.com/assets/410305/26202521/06f5b2ea-3bd8-11e7-990a-8954223f6995.png)

### Reproduction Steps and Sample Code

We call this method in our root component's `componentDidMount` and it worked just fine so far. I created a snack https://snack.expo.io/ryOh1Migb but can not reproduce exception there. I am not sure which version of react-native expo v16 uses though.

### Additional Information

* React Native version: 0.44.0
* Platform: iOS
* Development Operating System: macOS
* Dev tools: Xcode 8.3.2

**Comment by rbressi** [comment]
Looks like the implementation of **RCTDeviceInfo.m** broke this, as the **RCTAccessibilityManagerDidUpdateMultiplierNotification** notification is being posted on the JS thread rather than the main thread, breaking the assertion in **RCTExportedDimensions**.

This is effectively blocking upgrades to RN 0.44 for anyone setting custom accessibility content size multipliers. Is this being looked at for RN 0.45?

**Comment by mmmulani** [comment]
just put a fix in for this, let me know if it's still breaking for you

**Comment by fkgozali** [comment]
i.e. https://github.com/facebook/react-native/commit/112e3767ceae83e9034c25a0358949a20b379358

**Comment by rbressi** [comment]
LGTM, thanks! 👍
