### ISSUE TITLE
Cannot build for android

### ISSUE THREAD

**Issue by Gacnt** [facebook/react-native#14052]
### Description

```
Building and installing the app on the device (cd android && ./gradlew installDebug)...
WARNING: Module 'com.facebook.react:react-native:0.44.0' depends on one or more Android Libraries but is a jar

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not find react-native.jar (com.facebook.react:react-native:0.44.0).
  Searched in the following locations:
      file:/Users/Gacnt/Documents/Mobile/PlayersAreKnown/node_modules/react-native/android/com/facebook/react/react-native/0.44.0/react-native-0.44.0.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.215 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html
```

I'm trying to run `react-native run-android` but I continuously get this error

I've built for iOS no problem, but can't seem to get the Android version to build.

I have my node_modules installed and I'm not sure what else to try, I've been googling for the last 2 hours and have come up with nothing.

And I have ran `react-native link`

### Reproduction Steps and Sample Code

Trying to build for Android

**Comment by FacuAcosta** [comment]
Are you trying to run the app on an actual Android device or on the emulator?

**Comment by Gacnt** [comment]
Emulator

**Comment by FacuAcosta** [comment]
Try to create on the `android` folder in your react-native project a document called `local.properties` and inside this file type `sdk.dir=yourPathToSdk` where yourPathToSdk is the path for the Android SDK. If you don't know where is the SDK located open Android Studio, go to `Preferences > Appearance & Behavior > Android SDK` and copy the path that appears on Android SDK Location into the file you created before. Hope this works! And of course, if you don't have Android Studio installed you need It in order to use the emulator, unless you are using another one.

**Comment by Gacnt** [comment]
Thanks I'll try this once I get home from work and will let you know. Hopefully that works, if this is the case it's weird that it is undocumented in the documentation

**Comment by Brian-Kaplan** [comment]
are you integrating into an existing app? You really have not provided enough information to fix anything

**Comment by Gacnt** [comment]
Sorry Brian. I basically made an app ensuring to use components friendly to
both iOS and Android. I'm not sure what you mean by existing I started the
app with react-native init and built it from there up with no issues
building on iOS only android.

**Comment by Gacnt** [comment]
@FacuAcosta @Brian-Kaplan  Unfortunately this did not resolve the issue

So I initially started the app with `react-native init App`

I've done all the development mostly through the iOS simulator

The only thing I've added that requires a `react-native link` is `react-native-vector-icons`, it is not a very large app at the moment, it only has a `react-navigation` tab bar, and 2 screens, everything works perfectly fine and will build in `xcode`

I've followed the android setup twice through the facebook documentation but when trying to run `react-native run-android` I get 

```
* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-vector-icons'.
      > Could not find react-native.jar (com.facebook.react:react-native:0.44.0).
        Searched in the following locations:
            file:/Users/Gacnt/Documents/Mobile/PlayersAreKnown/node_modules/react-native/android/com/facebook/react/react-native/0.44.0/react-native-0.44.0.jar
```

I'm not sureh ow much more information to provide

**Comment by Gacnt** [comment]
I got it to work by doing

`yarn clean`
`yarn cache clean`
`rm -rf node_modules/ && yarn`

it now builds and there is hope.

**Comment by rajatgupta1993** [comment]
@Gacnt I am facing the exactly same issue and I am using npm . 
do u have any solution other than this ?

**Comment by evasyuk** [comment]
I had the same problem but with output

```

Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find react-native.aar (com.facebook.react:react-native:0.55.3).
  Searched in the following locations:
      https://jcenter.bintray.com/com/facebook/react/react-native/0.55.3/react-native-0.55.3.aar
```

After accessing provided URL via plain HTTP request I response:

```
{
  "errors" : [ {
    "status" : 404,
    "message" : "Could not find resource"
  } ]
}
```


I solved my problem after changing all lines with dependencies for latest react-native release 
from
`compile 'com.facebook.react:react-native:+'`
to
`compile 'com.facebook.react:react-native:0.52.0'`

solved my problem.

Obviously it is a delivery fuck up by react-native maintainers and you need to use some script in order to fix this problem automatically for each 'rm -rf node_modules && npm install' sequence you need to update dependencies again
