### ISSUE TITLE
SecurityException on missing permission in com.facebook.react.modules.location.LocationModule#getCurrentPosition causes app to crash

### ISSUE THREAD

**Issue by TikiTDO** [facebook/react-native#14080]
### Description

I have a situation where an android user opens a page which calls `navigator.geolocation.getCurrentPosition`. This in turn triggers a SecurityException in the function [`getCurrentPostion`](https://github.com/facebook/react-native/blob/2b0282aa69c0bc999aef9444bff7e1dfa54cac48/ReactAndroid/src/main/java/com/facebook/react/modules/location/LocationModule.java#L115) located in `com.facebook.react.modules.location.LocationModule` 

This exception proceeds to crash the app, instead of triggering the error callback of the `navigator.geolocation.getCurrentPosition`. The issue is twofold:

1. The app hard-crashes on this exception, without giving me a chance to gracefully recover from the failure.

2. For some reason the user's install is not detecting the `ACCESS_FINE_LOCATION` specified in the AndroidManifest.xml file. This appears to be a one off, and we're still following up with the user to see if there are any unusual considerations which might trigger such behavior.

### Reproduction Steps and Sample Code

I could not reproduce the issue by disabling the location permission, or making any other user-land modifications that I could imagine.

I had to manually remove `<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>` from the app AndroidManifest.xml file, and accessed the code that attempts to retrieve the location. The resulting exception crashed my application, despite the fact that `navigator.geolocation.getCurrentPosition` was called with an error callback.

I could not reproduce this crash with a debugger attached.

### Solution

At first glace the most obvious solution is to make the [getCurrentPosition function](https://github.com/facebook/react-native/blob/2b0282aa69c0bc999aef9444bff7e1dfa54cac48/ReactAndroid/src/main/java/com/facebook/react/modules/location/LocationModule.java#L140) invoke the error handler, instead of re-throwing an exception. I am not sure if there is a good reason why it isn't already doing so.

Note: The same logic applies to the startObserving function in the same class.

### Additional Information

* React Native version: 0.44
* Platform: Android 7.0 (Original User's platform)
* Development Operating System: Linux
* Dev tools: Android API 25

**Comment by TikiTDO** [comment]
This issue has been affecting quite a few more users than originally thought. Would it be possible to get some feedback as to the proposed solution from someone more familiar with the topic?

**Comment by bilalsyed001** [comment]
Quick work around is to use PermissionsAndroid. http://facebook.github.io/react-native/releases/0.44/docs/permissionsandroid.html#permissionsandroid

**Comment by TikiTDO** [comment]
Ah, many thanks. 

I'm going to submit a pull request with an update to the docs to reference that.

**Comment by hramos** [comment]
Hi there! This issue is being closed because {:search=>"repo:facebook/react-native is:open is:issue updated:<2017-05-25 -label:\"Good First Task\" -label:\"Help Wanted\" ", :message=>"it has been inactive for a while"}. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
