### ISSUE TITLE
react native networking not working after updating xcode to 8.3.2

### ISSUE THREAD

**Issue by alzalabany** [facebook/react-native#14083]
### Description
all of a sudden, all my applications are getting Newtwork request failed after i updated my xcode to 8.3.2,

    Network request failed
    TypeError: Network request failed

i tried changing values in /ios/[projectname]/info.plist but still getting same error, even when i'm calling https:// endpoints.

    <key>NSAppTransportSecurity</key>
    	
    	<dict>
    		<key>NSExceptionDomains</key>
    		<dict>
    			<key>localhost</key>
    			<dict>
    				<key>NSExceptionAllowsInsecureHTTPLoads</key>
    				<true/>
    			</dict>
    		</dict>
    	</dict>

### Reproduction Steps and Sample Code

$ react-native init newProject && cd newProject && react-native run-ios

open index.ios.js and add test

                <Button title="fetch" onPress={async ()=>{
                  const r = await fetch('http://localhost/ivf/system/settings');
                  console.log(r);
                }}/>
                <Button title="fetchs" onPress={async ()=>{
                  const r = await fetch('https://ivf.simpleinfroamtics.com/system/settings').catch(console.log);
                  console.log(r);
                }}/>
by clicking on both links they both will fail with newtwok request failed.

i tried using xhr insteed

    componentDidMount(){
    var request = new XMLHttpRequest();
    request.onreadystatechange = (e) => {
    if (request.readyState !== 4) {
    return;
    }
    
    if (request.status === 200) {
    console.log('success', request.responseText);
    } else {
    console.warn('error');
    }
    };
    
    request.open('GET', 'http://localhost/endpoint/');
    request.send(); //will fail same error yet exactly same error.

how can we fix this ??? i already finished my whole app and i'm waitting to fix this so i can publish :( 

List all the steps required to reproduce the issue you're reporting. These steps should be clear and concise.

* React Native version: 0.44
* Platform: IOS
* Development Operating System: macOs xcode-8.3.2

**Comment by alzalabany** [comment]
its also good to mention, when i tried to use expo "create-react-native-app" and used same code above.
the requests to http://ivf.simple*.com went through successfuly, yet the localhost still fails

**Comment by roszelj** [comment]
I'm having a similar problem, did you find any resolutions?

**Comment by alzalabany** [comment]
must set security transport policies, its mandatory since xcode 8.1+

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
