### ISSUE TITLE
Android: Error calling AppRegistry.runApplication - com.facebook.jni.CppException: Could not get BatchedBridge

### ISSUE THREAD

**Issue by tobymurray** [facebook/react-native#14090]
### Description
Tried to run the default application on my USB-attached Android device, and the application showed a box with "Error calling AppRegistry.runApplication" instead of the expected "Welcome" screen

### Reproduction Steps and Sample Code

To reproduce:
```
$ react-native init test
... <snip> ...
$ cd test/ && react-native run-android
.. <snip> ...
Running /home/user/Android/Sdk/platform-tools/adb -s LGD8522233753e reverse tcp:8081 tcp:8081
Starting the app on LGD8522233753e (/home/user/Android/Sdk/platform-tools/adb -s LGD8522233753e shell am start -n com.test/.MainActivity)...
Starting: Intent { cmp=com.test/.MainActivity }
```
The app crashes on the device. ADB logs (Error and Fatal only):
```
5-22 02:06:55.135 14356 14356 E asset   : setgid: Operation not permitted
05-22 02:06:55.137 14357 14357 E asset   : setgid: Operation not permitted
05-22 02:06:55.216  5214  5542 E bt_btif : No such connection need to be cancelled
05-22 02:06:55.216  5214  5542 E bt_btif : bta_gattc_mark_bg_conn unable to find the bg connection mask for: f0:60:cb:27:82:56
05-22 02:06:55.845 10376 10388 E NativeLibraryHelper: Failed to load assets verifier: 0
05-22 02:07:02.256   316   316 E installd: Couldn't opendir /data/app/vmdl230525447.tmp: No such file or directory
05-22 02:07:02.871  4200 13654 E NetworkScheduler.SR: Invalid parameter app
05-22 02:07:02.871  4200 13654 E NetworkScheduler.SR: Invalid package name : Perhaps you didn't include a PendingIntent in the extras?
05-22 02:07:02.885  4262 10628 E Drive.UninstallOperation: Package still installed com.reactapp
05-22 02:07:03.059  4200  4200 E ctxmgr  : [PlaceFenceHelper]NearbyBuffer is null!
05-22 02:07:03.218 25690  1131 E SecretModeInfo: SettingNotFoundException - getDBSecretMode()
05-22 02:07:03.247 25690 31400 E SecretModeInfo: SettingNotFoundException - getDBSecretMode()
05-22 02:07:03.255 23262 23262 E Finsky  : [1] com.google.android.finsky.wear.bl.a(3): onConnectionFailed: ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}
05-22 02:07:03.533  4200 13654 E NetworkScheduler.SR: Invalid parameter app
05-22 02:07:03.533  4200 13654 E NetworkScheduler.SR: Invalid package name : Perhaps you didn't include a PendingIntent in the extras?
05-22 02:07:03.822  4630  5016 E Surface : getSlotFromBufferLocked: unknown buffer: 0x94463ae0
05-22 02:07:04.199 14510 14536 E         : Unable to load script from assets: index.android.bundle
05-22 02:07:04.209 14510 14539 E unknown:React: Exception in native call
05-22 02:07:04.209 14510 14539 E unknown:React: java.lang.RuntimeException: Error calling AppRegistry.runApplication
05-22 02:07:04.209 14510 14539 E unknown:React: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
05-22 02:07:04.209 14510 14539 E unknown:React: 	at android.os.Handler.handleCallback(Handler.java:739)
05-22 02:07:04.209 14510 14539 E unknown:React: 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-22 02:07:04.209 14510 14539 E unknown:React: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
05-22 02:07:04.209 14510 14539 E unknown:React: 	at android.os.Looper.loop(Looper.java:148)
05-22 02:07:04.209 14510 14539 E unknown:React: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:208)
05-22 02:07:04.209 14510 14539 E unknown:React: 	at java.lang.Thread.run(Thread.java:818)
05-22 02:07:04.209 14510 14539 E unknown:React: Caused by: com.facebook.jni.CppException: Could not get BatchedBridge, make sure your bundle is packaged correctly
05-22 02:07:04.209 14510 14539 E unknown:React: 	... 7 more
05-22 02:07:09.415  4200 13217 E ctxmgr  : [ProducerActiveIntervalImpl]closeActiveInterval: Error: ongoing, trying to close
05-22 02:07:09.473  4200 13217 E ctxmgr  : [ProducerActiveIntervalImpl]closeActiveInterval: Error: ongoing, trying to close
```

### Solution
Reading over #7336, I came across the comment here: https://github.com/facebook/react-native/issues/7336#issuecomment-218130288 - this worked for me. In a different terminal, I ran `react-native start` and I was able to launch the application successfully with `react-native run-android`.

### Additional Information
* React Native version:
```
$ react-native --version
react-native-cli: 2.0.1
react-native: 0.44.0
```
* Platform: I only tried this on Android
* Development Operating System:
```
$ uname -a
Linux desktop 4.10.0-21-generic #23-Ubuntu SMP Fri Apr 28 16:14:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
* Dev tools: 
```
$ cat Android/Sdk/platform-tools/source.properties 
Pkg.UserSrc=false
Pkg.Revision=25.0.6

$ cat Android/Sdk/tools/source.properties 
Pkg.UserSrc=false

Pkg.Revision=26.0.2
Platform.MinPlatformToolsRev=20
Pkg.Dependencies=emulator
Pkg.Path=tools
Pkg.Desc=Android SDK Tools

$ adb version
Android Debug Bridge version 1.0.39
Revision 3db08f2c6889-android
```
```
$ yarn --version
0.24.5
```

**Comment by LDongBristol** [comment]
Thanks! The solution really works! Though it could be combined into a single
`$ react-native start && react-native run-android`
without opening a separate terminal. ;)

**Comment by gitlovenotwar** [comment]
I had the same problem with my physical device. On emulator, the apk build is fine.

**Comment by manujvashist** [comment]
I had a similar problem. 

The problem was when I would do adb devices or react-native run-android I would get "ADB is Not Recognized as an internal or external command".

So my fix was to add the path to adb.exe's parent directory to my Environment Variables and then restart my command prompts. After I did that, adb devices would not throw the "unrecognized internal external blah" and it listed my device. I then ran react-native run-android and on startup no more red screen showing the completely useless error message Error calling AppRegistry.runApplication! :)

So I found ADB was located in my folder:

C:\Users\dell\AppData\Local\Android\sdk\platform-tools\adb.exe
I am on a Windows 10 system. dell is my user name of the computer.

So I went to System Environemnt Variables then found "Path" then clicked "Edit", then clicked "New" and added in "C:\Users\dell\AppData\Local\Android\sdk\platform-tools".

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
