### ISSUE TITLE
React native webView move to another page when wrong url enter

### ISSUE THREAD

**Issue by farrukhbashir** [facebook/react-native#14095]
'I am using the webview when  i enter the wrong url it will redirect to another white screen for a little moment show a pagenotfound screen then navigate to another screen.I am disable the warning then now when i enter wrong url it will redirect to white screen what is the solution i want to open pagenotfound screen as in our browser if pagenotfound..my code is
  ```
 <WebView style={{flex:1,margin:20}}
  ref={WebView_Ref}
  source={{uri: this.state.go}}
/>

```

**Comment by farrukhbashir** [comment]
@rigdern  plz give solution

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
