### ISSUE TITLE
React Native Build Issue

### ISSUE THREAD

**Issue by mohit-pandey** [facebook/react-native#14107]
Hi,

I am trying to update dynamic content in string template, and for that, i found an ES6 solution in [stackoverflow](https://stackoverflow.com/questions/29182244/convert-a-string-to-a-template-string), which works great when tested in [https://es6console.com/j30fwzmy/](https://es6console.com/j30fwzmy/)

```
String.prototype.interpolate = function(params) {
    const names = Object.keys(params),
        vals = Object.values(params)
    return (new Function(...names, `return \`${this}\`;`)(...vals))
}

const template = 'Your Code is ${char}';
const result = template.interpolate({
    char: 2646765789
});
console.log(result);
```

But when i integrated in my app, it doesn't work as expected and throws an error **Invalid character:'`'**, though when tried in debug mode, it works as expected.

**It looks like a babel issue , not sure though, any help!!!**

**package.json**
```
{
  "name": "ABC",
  "version": "0.0.1",
  "private": true,
  "dependencies": {
    "html-entities": "^1.2.0",
    "jwt-decode": "^2.1.0",
    "qs": "^6.3.0",
    "react": "16.0.0-alpha.6",
    "react-addons-shallow-compare": "^15.4.2",
    "react-native": "0.44.0",
    "react-native-i18n": "^1.0.0",
    "react-native-router-flux": "^3.38.0",
    "react-native-splash-screen": "^2.0.0",
    "react-native-vector-icons": "^4.0.0",
    "react-redux": "^5.0.1",
    "redux": "^3.6.0",
    "redux-logger": "^2.7.0",
    "redux-thunk": "^2.1.0",
    "striptags": "^2.2.1",
    "tcomb-form-native": "^0.6.1"
  },
  "devDependencies": {
    "babel-jest": "19.0.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "19.0.2"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
