### ISSUE TITLE
why roundToNearestPixel use 0.4?

### ISSUE THREAD

**Issue by boiawang** [facebook/react-native#14119]
https://github.com/facebook/react-native/blob/346858a5528a95e0fe869f4fd0269aa43b31cae0/Libraries/StyleSheet/StyleSheet.js#L24

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
