### ISSUE TITLE
Change props not re-render the page

### ISSUE THREAD

**Issue by Symous** [facebook/react-native#14121]
Hi,According to the lifecycle of react-native,a changing of props value will lead to componentWillReceiveProps() and then shouldComponentUpdate() and finally render() the page;

But when I change a value of a prop in componentDidMount() like this:
```js
this.props.someProp = aNewValue;
```
the page isn't render and even componentWillReceiveProps() isn't invoked.
What's the reason of this ? Many thanks!

**Comment by lipeiwei-szu** [comment]
@Symous  because props cannot be changed directly, it only can be changed by it's parent component. On the condition, you should use the state of component instead of props. you can see  https://facebook.github.io/react-native/docs/props.html  and  https://facebook.github.io/react-native/docs/state.html

**Comment by Symous** [comment]
@lipeiwei-szu , yeah, I just ignore this even it is writing in the doc.Appreciate that you have solved the trouble comfusing me quite a while. ：-）
