### ISSUE TITLE
Automatic and manual timezone on iOS

### ISSUE THREAD

**Issue by petitmat** [facebook/react-native#14135]
### Description

I've a problem on iOS, when I create a Date("2017-05-23T16:26:58.838+2") object and I want to print hours and minutes in the correct timezone in the app it prints 16:26 on the simulator, and on real iPhone, if Paris is automatically selected as timezone in settings 14:26 is printed. And if Paris is manually selected as timezone the correct hours are printed (16:26). 

How is possible to be different between automatic and manual setting ?

Code is : 
`
let begin = Date("2017-05-23T16:26:58.838+2");
`
`
return(
<Text>
begin.toLocaleTimeString('fr-FR', {timezone:'CET', hour: '2-digit', minute:'2-digit'})
</Text>);
`

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
