### ISSUE TITLE
RCTNetworkingNative.sendRequest in Android does not respect timeout value

### ISSUE THREAD

**Issue by vijayst** [facebook/react-native#14134]
### Description

Used react-native-fetch-polyfill to fetch an API with timeout. The timeout works in iOS but does not work in Android.

### Reproduction Steps and Sample Code

The [fetch-demo repo](https://github.com/vijayst/fetch-demo) has the sample code to reproduce the issue.

```
handleFetch() {
    this.setState({ loading: true });
    fetch('http://82.69.20.215:8085/app.json', { timeout: 5000 })
      .then(response => response.json())
      .then(json => {
        this.setState({ loading: false });
      })
      .catch(err => {
        this.setState({ loading: false });
      });
  }
```

### Solution

RCTNetworkingNative.sendRequest in Android does not timeout for some reason.

### Additional Information

* React Native version: 0.44
* Platform: Android
* Development Operating System: macOS
* Dev tools: VS Code

**Comment by hramos** [comment]
Hi there! This issue is being closed because {:search=>"repo:facebook/react-native is:open is:issue updated:<2017-05-25 -label:\"Good First Task\" -label:\"Help Wanted\" ", :message=>"it has been inactive for a while"}. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by CamiloTerevinto** [comment]
Please don't close this.

I am experiencing the exact same behavior: timeout set at 5000 and it actually timeouts over 2/3 minutes later:

```
import { Component } from 'react';

import { Props, State } from './../react-interfaces';

import fetchTimeout from 'react-native-fetch-polyfill';

export class MyService extends Component<Props, State>
{
    public getMy(): Promise<any>
    {
        return fetchTimeout('http://192.168.0.100:54388/ReactNativeTesting', {timeout: 5000 });
    }
}
```

This is reproducible both in the Android Emulator and on a Samsung Galaxy S6 with Android 7
