### ISSUE TITLE
[Documentation] `style` prop details disappeared from `View` page

### ISSUE THREAD

**Issue by rigdern** [facebook/react-native#14147]
As can be seen in the screenshot, the details for the `style` prop are missing from the `View` docs page. This is a regression between RN 0.43 and 0.44:

![image](https://cloud.githubusercontent.com/assets/199935/26385208/bcdd075c-3ff2-11e7-97e6-5c1e332ad697.png)

**Comment by hramos** [comment]
Thanks for reporting this. We noticed this but have yet to work on a fix.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by rigdern** [comment]
@hramos This issue still repros. Should we reopen it?

**Comment by hramos** [comment]
Yep, definitely want to fix this.

**Comment by RyanMitchellWilson** [comment]
Any update on this?

**Comment by hramos** [comment]
No updates. As far as I am aware, this is still up for grabs.

**Comment by rigdern** [comment]
@RyanMitchellWilson if you need to see more details about `style`, you can look at the RN 0.43 docs as a workaround: http://facebook.github.io/react-native/releases/0.43/docs/view.html#style

**Comment by RyanMitchellWilson** [comment]
Still a problem, can this please be put back into the current documentation and kept up to date?
<img width="647" alt="screen shot 2017-10-23 at 9 27 27 am" src="https://user-images.githubusercontent.com/11371200/31897745-88f90260-b7d4-11e7-8836-2978d8a611b4.png">

**Comment by hramos** [comment]
We've made some changes to the docs recently. We are no longer using react-docgen, so you can go ahead and add the missing props directly to the markdown source for each of these components. The docs are now at https://github.com/facebook/react-native-website.

**Comment by rigdern** [comment]
The solution in the [latest docs](https://facebook.github.io/react-native/docs/next/view.html#style) looks good to me. The `style` prop on the `View` page has a link to the [View Style Props](https://facebook.github.io/react-native/docs/next/view-style-props.html) doc.

**Comment by hramos** [comment]
Great to hear, that's one of the things I had to manually re-create when react-docgen was removed.

**Comment by RyanMitchellWilson** [comment]
Doesn't seem like the problem was fixed, can this be reopened? Still not seeing anything for style in the docs for `View`

<img width="1031" alt="screen shot 2017-12-06 at 2 32 41 pm" src="https://user-images.githubusercontent.com/11371200/33686558-82c33b96-da92-11e7-89af-b434957bc188.png">

**Comment by rigdern** [comment]
@RyanMitchellWilson I think this was fixed in the  [latest version of the docs](https://facebook.github.io/react-native/docs/next/view.html#style) . You can see that `style` is a link.

![image](https://user-images.githubusercontent.com/199935/33686820-f16fb7ac-da8a-11e7-8bc7-04c7a4bdc613.png)

**Comment by RyanMitchellWilson** [comment]
@rigdern that doesn't really help me and others who are using previous versions. Plus when you go to https://facebook.github.io/react-native/ you are not directed to that version of the website, you are placed on the latest version, which currently is 0.51. This issue was meant to fix all the wrong documentation to help the people using those versions of react-native, not just the people using the very latest.

**Comment by rigdern** [comment]
@RyanMitchellWilson that's a good point.

@hramos should the fix be back ported to previous versions of the React Native docs?

**Comment by hramos** [comment]
You can still access past versions of the site by clicking on the version number at the top. Example:

* Version 0.5 style props: https://facebook.github.io/react-native/docs/0.5/view-style-props.html
* Version 0.49 style props: https://facebook.github.io/react-native/docs/0.49/view-style-props.html
* Style props from master: https://facebook.github.io/react-native/docs/next/view-style-props.html

This repository no longer contains the docs. Please do open an issue at https://github.com/facebook/react-native-website if you'd like to suggest changes to the way View style props are documented.

**Comment by RyanMitchellWilson** [comment]
Ya I know you can get to previous versions that is fine, it is not intuitive to get to the master version is what I was saying. 
I guess I'll go open a new issue in react-native-website even though I've had this one open for 7 months.
