### ISSUE TITLE
Native UI how to export custom event width android?

### ISSUE THREAD

**Issue by a289459798** [facebook/react-native#14149]
for example in ios:

RCT_EXPORT_VIEW_PROPERTY(onMapFinish, RCTBubblingEventBlock);
RCT_EXPORT_VIEW_PROPERTY(onMapError, RCTBubblingEventBlock);

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

**Comment by alvaromb** [comment]
@a289459798 AFAIK there's no `RCTBubblingEventBlock` or `RCTDirectEventBlock` in Android, you should use another communication methods like `DeviceEventEmitter`.
