### ISSUE TITLE
EMFILE: too many open files when JS DEV Mode unchecked

### ISSUE THREAD

**Issue by IgorVanian** [facebook/react-native#14153]
### Description

When uncheking JS DEV Mode in the menu, it starts to bundle everything but fails at 100%.
Same thing if I try to assmebleRelease.

### Reproduction Steps and Sample Code

Bundle after uncheck JS DEV MODE

```
React packager ready.

Loading dependency graph, done.
 ERROR  EMFILE: too many open files, open 'C:\***\AppData\Local\Temp\react-native-packager-cache-13O+7lAjc3k0GifOh\arVHbw5bQ=\95\5b267a3976b6a89c279ce3cbd96ee45757b3b4error-guard.js.3325042388'
{"errno":-4066,"code":"EMFILE","syscall":"open","path":"C:\\***\\AppData\\Local\\Temp\\react-native-packager-cache-13O+7lAjc3k0GifOh\\arVHbw5bQ=\\95\\5b267a3976b6a89c279ce3cbd96ee45757b3b4error-guard.js.3325042388"}
Bundling `index.android.js`  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░  99.9% (3373/3374)C:\***\node_modules\react-native\packager\src\lib\TerminalReporter.js:182
      terminal.log(chalk.red(error.stack));
                                  ^

Error: EMFILE: too many open files, open 'C:\***\node_modules\write-file-atomic\index.js'
```

```
> assembleRelease

C:\***\node_modules\write-file-atomic\index.js:127
    throw err
    ^

Error: EMFILE: too many open files, open 'C:\***\AppData\Local\Temp\react-native-packager-cache-13O+7lAjc3k0GifOh\arVHbw5bQ=\49\08204448a68aac1b86bb39500d99d1d8cd798frequire.js.4268275313'
:app:bundleReleaseJsAndAssets FAILED
```

### Additional Information

* React Native version: 0.44.0
* Platform: Android
* Development Operating System: Win10
* Dev tools: React Native CLI

**Comment by brentvatne** [comment]
You'll want to install [watchman](https://facebook.github.io/watchman/docs/install.html) -- notice that there are many issues that discuss this problem already :) https://github.com/facebook/react-native/issues?utf8=%E2%9C%93&q=EMFILE%20

**Comment by IgorVanian** [comment]
Actually, I saw everything, and watchman for Windows seems to be very far from being production ready. I remember installing it some time ago and didn't manage to do anything.

**Comment by brentvatne** [comment]
@IgorVanian - this is a problem that exists on Windows whether you're using react-native or not, and watchman is a way to get around it. As far as production ready goes, well, this runs on your dev machine so it's not really production 😅 . For what it's worth, @dikaiosune is working on an alternative to watchman that would also resolve this problem. Unfortunately it's all out of the scope of the react-native repository as far as I can tell -- we can suggest that you use watchman and that's about it. This is a problem that is deeper in the ecosystem. [Notice that this issue is everywhere](https://www.google.ca/search?q=ERROR+EMFILE%3A+too+many+open+files+on+windows&oq=ERROR+EMFILE%3A+too+many+open+files+on+windows).

**Comment by IgorVanian** [comment]
Thank you for this clear answer ! :)
