### ISSUE TITLE
Changing the highlight color of TextInput

### ISSUE THREAD

**Issue by yasserzubair** [facebook/react-native#14182]
![untitled-1](https://cloud.githubusercontent.com/assets/18016507/26438961/599320de-413f-11e7-8ae8-3e2fba4fd3c6.jpg)

I cannot change the color of the line when the TextInput is focused. Styling is not mentioned in the documentation. Please help.

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
