### ISSUE TITLE
ScrollView does not render flexBasis correctly

### ISSUE THREAD

**Issue by mikehobi** [facebook/react-native#14193]
### Description

In a `View`, when a child has a set `flexBasis` value (ex. `{flexBasis: 28}`), that space of 28px is rendered similar to a fixed `height` or `width` (depending on `flexDirection`).

In a `ScrollView`, that same child with a `flexBasis` of `28` is not rendered with any visible height. The expectation would be that it would render similar to a `View` with a height of `28`

### Reproduction Steps and Sample Code

Here is a code example showing a `View` parent and a `ScrollView` parent wrapping the exact same `Content` component and getting different results:
https://snack.expo.io/HJH8anEbZ

### Solution

Not sure. This might be an issue with yoga.

### Additional Information

* React Native version: ~0.42.3 or greater-ish
* Platform: iOS & Android
* Development Operating System: macOS + Snack
* Dev tools: xcode/snack

**Comment by mikehobi** [comment]
@vjeux @emilsjolander, possibly a problem with the yoga implementation?

**Comment by vjeux** [comment]
I'm no longer working on React Native nor Yoga, sorry :(

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by shergin** [comment]
I still plan to fix it. 😄
