### ISSUE TITLE
Can't change iOS button background color?

### ISSUE THREAD

**Issue by gregblass** [facebook/react-native#14192]
I'm trying to change the background color of a button component on iOS, but for some reason when I try to apply styling to it, nothing happens.

Looking at the documentation, it looks like RN makes the decision for you to stick to iOS and Android design guidelines in regards to buttons.

While I appreciate that notion and generally agree, I would like some of my buttons on iOS to have more of an Android/Material type style, with a solid background and white text.

Should I be using a different component in that case?

**Comment by gregblass** [comment]
Looks like react native elements is using a TouchableHighlight for their button for iOS. Just wondering though, what is the thought process here? Is it really necessary to limit people from styling a button how they want to?

**Comment by hramos** [comment]
This behavior is intentional with <Button />. You should look at the Touchable* classes to do what you're looking for.

For context, Button is relatively new. Until Button was introduced, there was no way to get a standard iOS or Android "button" without figuring out the right set of styles to apply on the appropriate Touchable class for a platform. Button does that for you. If you need custom behavior, you should fall back to the Touchable classes.

**Comment by gregblass** [comment]
That makes sense. Thanks for the explanation!
