### ISSUE TITLE
change prop of native component cause 'Attemp to invoke virtual method'...

### ISSUE THREAD

**Issue by Symous** [facebook/react-native#14205]
Hi, I custom a MapView Component on Android Platfrom.

Everything works well execpt that If I change a prop of the component in componentDidMount method , it will give me an error that 'Attemp to invoke virtual method 'void [my_package_name].[component_name].[method_name]' on a null object reference.

I fount that my mapview component always be null when I invoke the method to change its prop . and the only way I can solve this is I must invoke the method in InteractionManager.runAfterInteractions callback.

my react-native code:
 ```js
addMarkers(positions){
    mapController.addMarkers(findNodeHandle(this),positions);
 }
```

my android code :
```java
@ReactMethod
    public void addMarkers(final int reactTag,ReadableArray positions){
        //the mapView always be null!that is the point!
        final AMapView mapView = (AMapView) getReactApplicationContext().getCurrentActivity().findViewById(reactTag);
        mapView.addMarkers(positions);
    }
```
Anyone know why this happen ? 

PS: React Native version is 0.43.4.

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
