### ISSUE TITLE
<Button>'s shadow disappear when it's ancestor <View> has onLayout in Android

### ISSUE THREAD

**Issue by anjianshi** [facebook/react-native#14216]
### Description
`<Button>`'s shadow disappear when it's ancestor `<View>` has onLayout in Android.
But If the `<View>` is the most outside element of this component, the `<Buttonn>`'s shadow will appear again.

### Reproduction Steps and Sample Code

```javascript
import React, { Component } from 'react'
import { View, Button } from 'react-native'

// shadow disappear
class Example1 extends Component {
    render() {
        return <View style={{padding: 50}}>
            <View onLayout={() => {}}>
                <Button title="Example1" onPress={() => {}} />
            </View>
        </View>
    }
}

// shadow disappear too
class Example2 extends Component {
    render() {
        return <View style={{padding: 50}}>
            <View onLayout={() => {}}>
                <View><View>
                    <Button title="Example2" onPress={() => {}} />
                </View></View>
            </View>
        </View>
    }
}

// shadow *appear*
class Example3 extends Component {
    render() {
        return <View style={{padding: 50}} onLayout={() => {}}>
            <View>
                <View><View>
                    <Button title="Example3" onPress={() => {}} />
                </View></View>
            </View>
        </View>
    }
}
```

![screenshot_1495847156](https://cloud.githubusercontent.com/assets/5005012/26516607/c2270778-42bb-11e7-8b50-04530e0c4fe1.png)

### Additional Information

* React Native version: 0.44.2
* Platform: Android
* Development Operating System: macOS

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by sachabest** [comment]
Hi - I think this is worth re-opening. onLayout seems to ignore `shadowRadius` props of the view on iOS - such that if the content of a view changes and that view has a shadow, `onLayout` returns a `nativeEvent` where the `height` value does not include the aforementioned shadow
