### ISSUE TITLE
NavigatorIOS re-renders previous component even after pushing new scene

### ISSUE THREAD

**Issue by saudpunjwani101** [facebook/react-native#14224]
### Description

It's weird problem I'm having with NavigatorIOS, when I push a new scene the render method of the previous scene re-renders automatically. And it keeps re-rendering the deeper I push in the stack. Something tells me the navigatorIOS is stacking one scene into another, that's why it might be happening.

### Reproduction Steps and Sample Code

let's say I have 2 scenes. SignIn and SignUp. SignIn is my initial render.

     export default class SignIn extends Component {
           render() {
               console.log("signin")
                return (.......)
            }
           onPressSignUp()  {
                this.props.navigator.push(.......)
           }
      }

      export default class SignUp extends Component {
           render() {
               console.log("signup")
                return (.......)
            }
           goBack()  {
                this.props.navigator.pop()
           }
      }

As you can see I have console.logged in the render method to know whether it re-renders or not. When the app starts, it will console.log("signin"), thats good. But when I push to signup, it will not only console.log("signup") but also "signin". However the component has unmounted. I have used the native Navigator and react-native-router-flex, but none of them has this behaviour.

##Additional Info

Also note that only the render method gets called. console.logging in componentWillMount or componentWillUnmount only gets executed once as expected.

Is this a normal behaviour or am I doing something wrong with the navigatorIOS?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
