### ISSUE TITLE
FlatList scroll implementation is not full

### ISSUE THREAD

**Issue by sneerin** [facebook/react-native#14247]
I have a typical use-case, I need to scroll to a certain position in a FlatList that does have different elements size. How can I scroll to a certain element since I can't calculate the height of each element?
And the documentation has something like this on every function related to scrolling:
   * Note: cannot scroll to locations outside the render window without specifying the
   * `getItemLayout` prop.
   */

Please, advice is there any way to scroll to the custom height item.

**Comment by smallpath** [comment]
In 0.43.4，You can scroll to locations without specifying the `getItemLayout` prop, however its performance is not good. I believe the performance issue is the reason why now it must be used along with `getItemLayout`.

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

**Comment by szczepcio95** [comment]
Anyone have any idea with this issue?
