### ISSUE TITLE
Unable to resolve module

### ISSUE THREAD

**Issue by kisubs** [facebook/react-native#14250]
Hello, I've been trying to upgrade from 0.42.3 to 0.44.0 and my project is giving me this error.
Is anyone having the same problem or know the solution?
Thanks!
![screenshot_20170529-214033](https://cloud.githubusercontent.com/assets/24979247/26568375/b8d73abe-44b7-11e7-8f1f-cc83f2a09ca2.png)

**Comment by StevenTB** [comment]
Did you try to remove your `nodes_modules` folder then launching` npm install` command ?

**Comment by kisubs** [comment]
When I delete node_modules then npm install, I get this,
<img width="610" alt="screen shot 2017-05-30 at 9 16 38 am" src="https://cloud.githubusercontent.com/assets/24979247/26593419/d35803c6-4518-11e7-8e3b-0f559a5e365a.png">

**Comment by hramos** [comment]
Does your package.json include the react-proptypes dependency?

**Comment by kisubs** [comment]
@hramos Yes, I tried but did not work. Right now, I'm just migrating code to a new project and hope this works.

**Comment by emrosenf** [comment]
We had this problem too. Turns out RN 44.3 is using React 16.0-alpha (which doesn't have react/lib/ReactPropTypes), but the codemod commit didn't make it until RN 45, https://github.com/facebook/react-native/commit/6564edce5e828685099957741db935cda029ca23

The solution was to upgrade to RN 45.0-rc3. Alternatively, it would seem that using an older version of React 15 would also help, but I'm not sure if you can do that with RN 44
