### ISSUE TITLE
Broken dependences: compile "com.facebook.react:react-native:+"

### ISSUE THREAD

**Issue by iegik** [facebook/react-native#14251]
In our project we decided to stay for some time in RN 0.39.2
But recently a dependency problem appeared:
Suddenly `./gradlew clean` start to crash. After research I found, that line `compile "com.facebook.react:react-native:+"` not work either. So in all module dependences I must to change react-native version exacly (as bellow)!

```
compile "com.facebook.react:react-native:0.39.2"
```

https://github.com/oblador/react-native-vector-icons/issues/480

How to keep that "plus" work, so that will take the project version of RN?

Should I use system variable or prefix for Gradle, to build project in specific version?

**Comment by iegik** [comment]
Useful script:
```
sed -i -- "s/com\.facebook\.react:react-native:[^\"]*/com\.facebook\.react:react-native:0.39.2/" node_modules/**/build.gradle
```

Change 0.39.2 to your project RN version

**Comment by gmlion** [comment]
Thanks @iegik for finding this out. I integrated your script to change all the dependencies in my project (I'm on 0.41.2):
```
sed -i -- "s/com\.facebook\.react:react-native:+/com\.facebook\.react:react-native:0.41.2/" node_modules/**/android/build.gradle
sed -i -- "s/com\.facebook\.react:react-native:+/com\.facebook\.react:react-native:0.41.2/" node_modules/**/android/app/build.gradle
sed -i -- "s/com\.facebook\.react:react-native:+/com\.facebook\.react:react-native:0.41.2/" android/app/build.gradle
```

**Comment by rexjrs** [comment]
```
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-image-crop-picker'.
      > Could not resolve all dependencies for configuration ':react-native-image-crop-picker:_debugPublishCopy'.
         > Could not find com.atlassian.mobile.video:okhttp-ws-compat:3.7.0-atlassian1.
           Required by:
               UFIT:react-native-image-crop-picker:unspecified > com.facebook.react:react-native:0.42.3-atlassian-1
```

how to fix?

**Comment by iegik** [comment]
Try to run script again.
Upgrade RN to 0.42.3 (required by `react-native-image-crop-picker`)

BTW, `node_modules/**/build.gradle` will take both `node_modules/react-native-{module}/android/build.gradle` and `node_modules/react-native-{module}/android/app/build.gradle`

**Comment by chrchm** [comment]
react-native link
work for me

**Comment by gmlion** [comment]
@iegik Ok now I see. To use "**" to recursively explore subdirectories you have to enable "globstar" in bash. It is off by default on Ubuntu and unavailable (afaik) on MacOS

**Comment by icarus-sullivan** [comment]
Hey All,

I'm currently stuck on version 0.39.2 of react-native. 

A quick solution until the jcenter lib is fixed. 

Hardcode your andorid/app/build.gradle version like so ...

`compile 'com.facebook.react:react-native:<your_version_number>'`

Then in your android/build.gradle file add the following. 
```
allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
    configurations.all {
      resolutionStrategy {
        eachDependency { DependencyResolveDetails details ->
          if (details.requested.group == 'com.facebook.react' && details.requested.name == 'react-native') {
            details.useVersion "<your_version_here>"
          }
        }
      }
   }
}
```

The solution was originally found here https://github.com/facebook/react-native/issues/14223

**Comment by ericwooley** [comment]
ugh, but the package i need depends on a specific version for a reason :( Forcing the build to use my usual RN version makes the build pass, but then there are issues with the js packager.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by kesha-antonov** [comment]
Changed 
```
distributionUrl=https\://services.gradle.org/distributions/gradle-4.3-all.zip
```
to
```
distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip
```
And it worked.

In ```android/gradle/wrapper/gradle-wrapper.properties```
