### ISSUE TITLE
Android: Gradle task "install{Falvour}Release" not available upon adding a product flavour to build.gradle. But *Debug is!

### ISSUE THREAD

**Issue by D1no** [facebook/react-native#14258]
### Description
I want to use [android source sets](https://developer.android.com/studio/build/build-variants.html#sourcesets) via product falvors for variations of app icons and configruations.  So I added one product flavor to my `android/app/build.gradle` file.

When I run `$ react-native run-android --variant=staging` from project root, the build fails with an exception.
```bash
FAILURE: Build failed with an exception.

* What went wrong:
Task 'installReleaseStaging' is ambiguous in root project 'shoplink'. Candidates
are: 'installReleaseStagingDebug', 'installReleaseStagingDebugAndroidTest'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to
get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

There is a installReleaseStaging**Debug**, but no installReleaseStaging gradle task for the production version? Even Android Studio seems to pick the other tasks up. But not the vanilla installReleaseStaging, just uninstallReleaseStaging task 🤔 

It also does not work for `react-native run-android --variant=release`
```bash
FAILURE: Build failed with an exception.

* What went wrong:
Task 'installRelease' is ambiguous in root project 'shoplink'. Candidates are: 
'installReleaseStagingDebug', 'installReleaseStaging DebugAndroidTest'.
```

![screen shot 2017-05-30 at 20 07 27](https://cloud.githubusercontent.com/assets/2397125/26598004/17b7a3ea-4574-11e7-95bc-3416927b4a25.png)

When I run the command with staging*Debug* the gradle Task installReleaseStagingDebug seems to be run and the build finishes successful. But that is the dev version.

### Reproduction Steps and Sample Code
Add in your build.gradle file a flavor under ProcutFlavors (i.e. releaseStaging as seen below). Run from root: `$ react-native run-android --variant=staging`

```
    productFlavors {
        releaseStaging {
            applicationId "com.myapp.staging"
        }
    }
```
Outcome: BUILD **FAIL**!

#### However, *Debug leads to a build

Now run with staging**Debug**
`$ react-native run-android --variant=stagingDebug`

Outcome: BUILD **SUCCESSFUL**!

> The same applies to BUILD TYPES (!) in exchange for product flavors.

### *Solution (Approach)*

I searched all over the internet – but nothing worked. I.e. using variant, flavor, configuration as a flag or running the task directly. Also cleaning gradle and deleting node_modules/(.bin) folder(s) does not bring any change. Our CI system fails also on the build.

Is there *maybe* something wrong in the source [react.gradle file [Line 80]](https://github.com/facebook/react-native/blob/0.45-stable/react.gradle#L80)?

I don't know java enough to really figure this out....

Thanks for any quick help... stuck all day on this... meh

### Additional Information

* React Native version: v0.45.0-rc.2 
* Platform: Android (default set-up)
* Development Operating System: macOS
* Dev tools: Android Studio Version 2.3.2, Cradle Version 2.3.2

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by susannepeng** [comment]
@D1no did you end up resolving this? I'm having the exact same problem in my project on react native 0.50.0
