### ISSUE TITLE
CLI runIOS command failed to match full product name

### ISSUE THREAD

**Issue by joro** [facebook/react-native#14278]
### Description

When running "react-native run-ios" command, after buildProject() process, it should return the updated product name. Otherwise it will fall back to project default name. This caused a problem on installing if I have renamed the product.

### Reproduction Steps and Sample Code

The run-ios command will run command located at ./node_modules/react-native/local-cli/runIOS/runIOS.js and build the project. When building the app, it will call buildProject() function, which will collect stdout like this:
    export FRAMEWORK_VERSION=A
    export FULL_PRODUCT_NAME="My Updated App Name.app"
    export GCC3_VERSION=3.3
    export GCC_C_LANGUAGE_STANDARD=gnu99
and put in buildOutput variable. Then it will try to find product name using this regular expression:
   let productNameMatch = /export FULL_PRODUCT_NAME="?(.+).app"$?/.exec(buildOutput);
But the regular expression will fail, then the appName fall back to default project name.

### Solution

Change the regular expression to 
  let productNameMatch = /export FULL_PRODUCT_NAME="?(.+).app"?/.exec(buildOutput);
Or other solution which can match product name properly.

### Additional Information

* React Native version: 0.44.2
* Platform: iOS
* Development Operating System: macOS v10.12.5
* Dev tools: Xcode v8.3.2

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
