### ISSUE TITLE
Cant start new react native project

### ISSUE THREAD

**Issue by sushant23** [facebook/react-native#14282]
I am unable to start new project with react native when I run `react-native run-android` it just gets stuck on `fetching js bundle...` 
![screen shot 2017-06-01 at 10 32 57 am](https://cloud.githubusercontent.com/assets/5249730/26664960/b5348470-46b5-11e7-875e-b85c735c5321.png)

**Comment by SupriyaKalghatgi** [comment]
Try a restart

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
