### ISSUE TITLE
will be remove from app store?

### ISSUE THREAD

**Issue by jsntghf** [facebook/react-native#14297]
If we use React Native, and use code push to fix some bugs, is this safe for review?

**Comment by JoshYuJump** [comment]
It's safe. My App is on App Store and work very well. 
As I know, `Code Push` is safe, `JSPatch` is not.

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
