### ISSUE TITLE
ViewPagerAndroid renders empty dynamically added views after upgrade from v0.42.3 to v0.44.2

### ISSUE THREAD

**Issue by SandraLum** [facebook/react-native#14296]
### Description

I have an array to store children views for ViewPagerAndroid, as I dynamically append views to the array, I am expecting to see newly added views to be rendered as I swipe through the pager, it was working however after the upgrade from v0.42.3 to v0.44.2, it is currently rendering empty views.

### Reproduction Steps and Sample Code
```
 addPage() {
    let pages = this.state.pages
    pages.push(<View style={{ flex: 1 }}><Text>{'New Page'}</Text></View>)
    this.setState({ pages: pages })
  }

  render() {
    return (
      <ViewPagerAndroid ref='viewPager'
        {...this.props}
        style={{ flex: 1 }}>
        {pages}
      </ViewPagerAndroid>
    ) }
```

### Solution

Going through the upgrades changes, it seems to call for a re-render upon layout change on the container. 

I am doing a bad hack for now is to adjust the layout so as to trick a render to occur. Modifying the style with marginBottom of 1px seems subtle enough for me.

```
       <ViewPagerAndroid ref='viewPager'
        {...this.props}
        style={[{flex: 1}, {marginBottom: pages.length % 2 == 0 ? 1 : 0 }]}>
        {pages}
      </ViewPagerAndroid>
```

### Additional Information

* React Native version: v0.44.2
* Platform: Android
* Development Operating System: Windows 10

**Comment by ricardofbarros** [comment]
I'm also experiencing this, so I have also a hack in place to trigger a re-render so the view shows. I also encountered this issue while using (react-native-community/react-native-tab-view)[https://github.com/react-native-community/react-native-tab-view] when using the `lazy` option.

**Comment by bood** [comment]
Should be similar to #13463, see my comment there for a work around fix.

**Comment by itinance** [comment]
We could build a simple workaround this way:

https://github.com/facebook/react-native/issues/13463#issuecomment-310896400

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
