### ISSUE TITLE
react-native link freeze on windows

### ISSUE THREAD

**Issue by isnifer** [facebook/react-native#14307]
## Reporting Bugs

Report a single bug per issue.

### Reproducing bugs
I've created repo https://github.com/isnifer/react-native-windows-issue

### Description
If I add any react-native package and try to link it - link command freezes

### Reproduction Steps and Sample Code
```sh
git clone git@github.com:isnifer/react-native-windows-issue.git

cd react-native-windows-issue

yarn install

react-native link
```

### Solution
I've discovered local-cli/link/link.js and I found that removing this line - https://github.com/facebook/react-native/blob/master/local-cli/link/link.js#L168 help to do not freeze, but I don't know why.

### Additional Information

* React Native version: 0.44.2
* Platform: Both
* Development Operating System: Windows
* Dev tools: git bash

**Comment by isnifer** [comment]
up

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
