### ISSUE TITLE
cannot run app on Android 4.4.2

### ISSUE THREAD

**Issue by arfa123** [facebook/react-native#14306]
I am trying to run app on android, but it shows error:

`Installing APK 'app-debug.apk' on 'XT907 - 4.4.2' for app:debug
Installed on 1 device.

BUILD SUCCESSFUL

Total time: 1 mins 40.331 secs
Running J:\Android\sdk/platform-tools/adb -s TA5970I02S reverse tcp:8081 tcp:8081
error: closed
Could not run adb reverse: Command failed: J:\Android\sdk/platform-tools/adb -s TA5970I02S reverse tcp:8081 tcp:8081
Starting the app on TA5970I02S (J:\Android\sdk/platform-tools/adb -s TA5970I02S shell am start -n com.awesomenavigation/.MainActivity)...
Starting: Intent { cmp=com.awesomenavigation/.MainActivity }`

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
