### ISSUE TITLE
Geolocation does not recover from location being off in Android

### ISSUE THREAD

**Issue by BehzadV** [facebook/react-native#14324]
Ok,
I wanted to get user's location and if location is not turned on, ask user to turn it on and then get it. I have  tried many ways for solving this, however, I might be in the wrong. I have the following code in one of my React Native Components:
```
    watchID: ?number = null;

    componentDidMount = () => {
        this.hookToGeoLocation();
    };

    componentWillUnmount = () => {
        navigator.geolocation.clearWatch(this.watchID);
    };

    hookToGeoLocation = () => {
        let options = {
            enableHighAccuracy: true,
            timeout: 20000,
            maximumAge: 1000
        };

        navigator.geolocation.getCurrentPosition(
            (position) => {
                if(position && position.mocked === false) {
                    console.log(position);
		    this.setState(

		    );
                }
            },
            (error) => {
                console.log(error);
            },
            options
        );
        this.watchID = navigator.geolocation.watchPosition(
            (position) => {
                if(position && position.mocked === false) {
                    ToastAndroid.showWithGravity('Received Location.', ToastAndroid.SHORT, ToastAndroid.CENTER);
                    console.log(position);
                    this.setState(
						
                    );
                }
            },
            (error) => {
                console.log(error);
                switch (error.code){
                    case 1: {
                        ToastAndroid.showWithGravity('Please turn on your Location', ToastAndroid.LONG, ToastAndroid.CENTER);
                    }
                }
            },
            options
        );
    };
```

On Android, this works entirely fine if Location is on BEFORE component is rendered (before componentDidMount). Success callback gets invoked and a position object is received.
However, as you can see, if the Location is not on, I use a ToastAndroid to ask the user to turn it on. Now, if location gets turned on by the user (Which of course happens after componentDidMount is done), absolutely NOTHING happens in the program. It doesn't receive a position. The error callback function does not run. It doesn't time out either (Even after hours, literally). All that happens is that Location icon pops in the status bar and doesn't go away unless componentWillUnmount runs (Again, even after hours).
I already have asked a [question](https://stackoverflow.com/questions/44296337/retrying-geolocation-after-error-in-react-native) on Stack Overflow. Apparently this doesn't happen in iOS (There was no iPhone available for us to test this on). But it keeps happening after android reboot. Also in multiple (three, to be exact) phones.

### Additional Information

* React Native version: 0.44.2
* Platform: Android (SM-G935F - 7.0)
* Development Operating System: Windows 10
* Dev tools: Node 7.9.0

**Comment by hramos** [comment]
Can you make sure to fill out the template properly? We need exact repro steps.

**Comment by BehzadV** [comment]
@hramos OK. Sorry. I'll retry like this:

With the code above, there are two scenarios:

1. (Correct, no issues scenario)
    - Turn on Android's location. 
    - Then, navigate to the above component.
    - Everything runs as expected. Location is received.

2. (Problem)
    - Navigate to the above component.
    - A Toast Android will pop and ask you to turn on your location
    - Now, turn on your location
    - Now nothing happens. No error callbacks. No timing out. And no new position. Only a Location icon in the status bar that only goes away if the component unmounts.

Was it good enough? Or did I miss something?

**Comment by JLWalsh** [comment]
I also share this problem. If I disable the location on the cellphone, geolocation will not throw an error/timeout and do nothing.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by aMarCruz** [comment]
@BehzadV , looks like this module still has issues. In the meantime, you can try [react-native-cross-geolocation](https://github.com/aMarCruz/react-native-cross-geolocation) that was made with the most efficient Google Location API, but needs more test from users.
