### ISSUE TITLE
slow performance, Text over Image

### ISSUE THREAD

**Issue by fast0490f** [facebook/react-native#14327]
Hi, i have next code:
 
```js
<View >
  <Image /> //style width & height 100%
   <Text >value1<Text />
   <Text >value2<Text />
   <Text >value3<Text />
</View>
```
If Text style position: 'absolute' over Image,  setState update text value, perfomance: JS 8 - 15 fps. Else Text style position: 'relative' no over image setState text value, performance: JS 57 - 60    fps. 
 If have 15 - 20 Text and call setState 1000ms of update values, critical js fps 0.  How can I achieve good performance?

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
