### ISSUE TITLE
[0.45.0] Image cannot be rendered after upgrading to 0.45.0

### ISSUE THREAD

**Issue by ethanyanjiali** [facebook/react-native#14389]
### Description

The image doesn't show up after I upgrade to 45. I've set height and width already and checked it through inspector. There's a placeholder but just no image.

### Reproduction Steps and Sample Code

List all the steps required to reproduce the issue you're reporting. These steps should be clear and concise.

```
icon = (<Image style={{width: 15, height: 15}} source={require('../../assets/link.png')} />);

return (
      <View>
        { icon }
      </View>
);
```

this png is a white link symbol with transparent background.

### Additional Information

* React Native version: 0.45.0
* Platform: iOS
* Development Operating System: macOS

**Comment by ethanyanjiali** [comment]
Downgraded to 0.44.0 and it is all good now

**Comment by mkirank** [comment]
I had the same issue, I was using pods and had to add 'RCTImage', in podspec to get this working

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
