### ISSUE TITLE
RCTRootView render finished notification

### ISSUE THREAD

**Issue by willorfang** [facebook/react-native#14390]
Is there a way to get notified when a RCTRootView finished rendering?
This is my scenario: There is an RCTRootView. I need to set its appProperties several times for updating. But I don't want to see the previous render before the new updating takes effect. A "loading view"  should be shown instead.

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
