### ISSUE TITLE
SectionList initialScrollIndex only works for a brief moment

### ISSUE THREAD

**Issue by FMCorz** [facebook/react-native#14397]
### Description

I am using a SectionList with an InitialScrollIndex. The initial scroll happens as it should but only for a brief moment, a second or so. Afterwards the scroll is reset to the top of the list.

### Reproduction Steps and Sample Code

Here is the code sample: https://snack.expo.io/rJAYCsIGb

Click the "Sectioned" button.

IMPORTANT: I could only reproduce this when trying locally!

### Solution

It seems that the bug comes from setting `first` to 0 from within `_updateCellsToRender`. The `_scrollMetrics` seem to contain misleading information as the effective scroll is yet 0, although the rendering started from the expected index. I would need some guidance to help providing a fix.

### Additional Information

* React Native version: 0.45.0
* Platform: Android API 23
* Development Operating System: Linux
* Dev tools: None

### Other issues

Trying this highlighted that the FlatList also has an issue. There is a high latency before the list is displayed, and the scrolled index changes by one when full view is loaded.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
