### ISSUE TITLE
[LayoutAnimation] Add support for delete

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#1440]
This would be incredibly useful - I imagine it was left out because it was probably more difficult to implement than the others. @nicklockwood @sahrens could you detail what issues held this up and what your strategy might be for implementing it? If it seems like something I can take care of I'd be happy to follow up on it.

**Comment by sahrens** [comment]
Yeah, just needs a bit more juggling to keep the view alive while animating it away, or maybe delay the removal - not sure which corner cases are harder to deal with...

**Comment by nickfujita** [comment]
+1

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/layoutanimation-add-support-for-delete

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by brentvatne** [comment]
FYI @janicduplessis is working on this for iOS here: https://github.com/facebook/react-native/pull/6779

If we get that in place, maybe Olivier will be able to add it to Android as well

**Comment by sahrens** [comment]
Author said he was planning to add it to android himself if the iOS stuff goes well.

On Apr 13, 2016, at 6:49 AM, Brent Vatne <notifications@github.com<mailto:notifications@github.com>> wrote:


FYI @janicduplessis<https://github.com/janicduplessis> is working on this for iOS here: #6779<https://github.com/facebook/react-native/pull/6779>

If we get that in place, maybe Olivier will be able to add it to Android as well

**Comment by brentvatne** [comment]
Oh excellent @sahrens :)

**Comment by todorone** [comment]
Is there any news on this? Does `delete` animation work on any of platforms?
