### ISSUE TITLE
Inconsistent naming convention for callback props

### ISSUE THREAD

**Issue by dikarel** [facebook/react-native#14406]
### Description

There are currently 2 different naming conventions being used to name callback props. It's not clear what the official naming convention should be, which makes it harder to:
- Recall the prop name without being forced to open a browser and consult docs
- Name things consistently when developing components

Naming should be consistent, so that it's clear to third-party developers which one is idiomatic.

### Reproduction Steps and Sample Code

1. Go to https://facebook.github.io/react-native/docs/textinput.html
2. Notice that there are 2 different naming conventions being used below: `onChangeFoo` vs. `onFooChange`

<img width="675" alt="screen shot 2017-06-08 at 1 11 23 pm" src="https://user-images.githubusercontent.com/15131271/26948806-85dda494-4c4c-11e7-9c91-84111a74d439.png">

### Solution

Pick either of these conventions and make it consistent everywhere:
- Convention 1: `onChangeFoo`
- Convention 2: `onFooChange`

### Additional Information

* React Native version: 0.45
* Platform: Both
* Development Operating System: Mac OSX
* Dev tools: Visual Studio Code

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
