### ISSUE TITLE
How to open Settings of Android Phone on a button click in our Android App

### ISSUE THREAD

**Issue by arunkumarrmrj** [facebook/react-native#14415]
### Description

I'm using React-Native (0.43.1) for making Android application. There is scenario where I need to check whether internet connectivity is present or not. If there is no internet connectivity then I need show a button which will open device settings (through which user can enable his connectivity).

### Reproduction Steps and Sample Code
Linking.canOpenURL('app-settings:')
      .then(supported => {
        if (!supported) {
          console.log('Can\'t handle url: ' + url);
       } else {
       return Linking.openURL('app-settings:');
      }
  }).catch(err => console.error('An error occurred', err));

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

**Comment by arunkumarrmrj** [comment]
Ok You will send exact answer link

**Comment by windhost** [comment]
+1
