### ISSUE TITLE
Multiline TextInput has different behavior between iOS and Android

### ISSUE THREAD

**Issue by sohobloo** [facebook/react-native#14414]
### Description

Multiline textinput with text over one screen display the text at the beginning on iOS while at the end on Android.
**And I want to know how to make it display at the beginning on Android.**

##### Core code:
```jsx
      <TextInput style={{flexGrow: 1}}
                 value={this.state.content}
                 multiline={true}/>
```

##### Screenshot iOS:
![image](https://user-images.githubusercontent.com/13310861/26965640-40145e66-4d29-11e7-93df-335b92af8b12.png)

##### Screenshot Android:
![image](https://user-images.githubusercontent.com/13310861/26965656-57331c7c-4d29-11e7-8062-204098b5d016.png)

### Solution

Make them the same.

### Additional Information

* React Native version: 0.44.3
* Platform: both
* Development Operating System: macOS
* Dev tools: Xcode 8.3.2, Android Studio 2.3.2, iOS 10.3,  Android SDK 25

**Comment by sohobloo** [comment]
Here is my temporary workaround for Android:

```javascript
  componentDidMount() {
    InteractionManager.runAfterInteractions(() => {
      this.refs.contentInput.setNativeProps({selection: {start: 0, end: 0}});
    });
  }
```

**But with some issues:**
1. Text flash from end to begin. 
2. The cursor will locate at the beginning instead of your first touch coordinate.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by tiaaaa123** [comment]
Does anyone got it fixed? I'm currently having this issue
