### ISSUE TITLE
flexWrap has definite, reproducible buggy behavior (!)

### ISSUE THREAD

**Issue by idibidiart** [facebook/react-native#14429]
## Reporting Bugs

>> Report a single bug per issue.

Since issue #8960 has so many bugs some of which turned out to be normal behavior per the Flexbox spec, I figured we need a new issue that focuses on an actual, definite bug 

Here is the issue, first reported by @EyalSi 

I've made a simple version of the code posted by @EyalSi in #8960  that shows an interesting definitely buggy behavior:

The only difference in the two screens below is a single extra "." after the last "test"

![image1](https://s30.postimg.org/pzskmed0x/Screen_Shot_2017-06-08_at_8.17.00_AM.png)

![image2](https://s10.postimg.org/ai4qxxj89/Screen_Shot_2017-06-08_at_8.10.23_AM.png)

@kulmajaba there is more buggy behavior that I've encountered that may or may not be related to this

```jsx
      <ScrollView > 
          <View style={{flexDirection: 'row',flexWrap:'wrap', backgroundColor: 'orange'}}>
              <View style={{margin: 15, backgroundColor: 'yellow'}}>
              <Text style={{fontSize:20}}> test test test test </Text>
              </View>
              <View style={{margin: 15, backgroundColor: 'yellow'}}>
              <Text style={{fontSize:20}}> test test test </Text>
              </View>
              <View style={{margin: 15, backgroundColor: 'yellow'}}>
              <Text style={{fontSize:20}}> test </Text>
              </View>

              <View style={{margin: 15, backgroundColor: 'red'}}>
              <Text style={{fontSize:20}}> test.. </Text>
              </View>

          </View>
          <Text>
          TEST
          </Text>
      </ScrollView>
```

### Additional Information

* React Native version: 0.43+
* Platform: iOS and Android
* Development Operating System: MacOS
* Dev tools: Expo

**Comment by hramos** [comment]
Do you have a Snack that easily reproduces this?

**Comment by idibidiart** [comment]
@hramos 

here is the buggy version:

https://snack.expo.io/SkhAnauGZ

same code without the bug with only difference being the last Text is "test test" instead of "test"

https://snack.expo.io/BkQtnTOG-

Expo in the Snack simulator fails to load sometimes so if that happens just reload it inside the simulator.

**Comment by idibidiart** [comment]
curious, any update on this? 

@hramos

**Comment by hramos** [comment]
@idibidiart nothing on our side (there's still many open issues to go through and prioritize). Feel free to send a PR if you investigate this further.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
