### ISSUE TITLE
negative value of property transform doesn't work on some android 7.0 devices.

### ISSUE THREAD

**Issue by Feng999** [facebook/react-native#14462]
RN version:  "0.41.2"
devices:
FRD-AL10（honor 8）  EMUI:5.0      android: 7.0
MHA-AL00(Mate9)    EMUI:5.0      android:7.0

On some android device mentioned before , negative value of transform(e.g.. scaleX  scaleY ) doesn't work.  i found this problem when i'm using  the package of [react-native-invertible-scroll-view](https://github.com/expo/react-native-invertible-scroll-view).  It write like this:
```
let styles = StyleSheet.create({
  verticallyInverted: {
    flex: 1,
    transform: [
      { scaleY: -1 },
    ],
  },
  horizontallyInverted: {
    flex: 1,
    transform: [
      { scaleX: -1 },
    ],
  },
});
```
but when i use scaleY which is deprecated directly, like this:
```
let styles = StyleSheet.create({
  verticallyInverted: Platform.select({
    ios: {transform: [{ scaleY: -1 }]},
    android: {scaleY: -1},
  }),
  horizontallyInverted: Platform.select({
    ios: {transform: [{ scaleX: -1 }]},
    android: {scaleX: -1},
  }),
});
```
 it worked!   
Guess there is some thing wrong when get property from transform in native code,  Any ideas how does this fix?

**Comment by yury** [comment]
Confirm at RN 0.43.2 Huawei OS7.0 P10. VTR-L09/VTR-L29

Doesn't work with transform, works with deprecated.

**Comment by ptomasroos** [comment]
This is a real case reported by various user by us as well.

**Comment by Feng999** [comment]
@ptomasroos  how do you guys fix this?

**Comment by janicduplessis** [comment]
Looks like this could be a potential fix https://github.com/facebook/react-native/pull/14560

**Comment by Feng999** [comment]
@janicduplessis  add` {"perspective": 1} `  is a better way to fix this  if it works.  i will try it latter.

**Comment by yury** [comment]
No, `{"perspective": 1}` doesn't help :(

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
