### ISSUE TITLE
How to open external YouTube App from WebView

### ISSUE THREAD

**Issue by Rufyi** [facebook/react-native#14460]
Is there a way I can open the external YouTube app on my phone if I click on a video from my app, using WebView, or any other way besides WebView.

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
