### ISSUE TITLE
TransformPropTypes documentation is not showing up in website menu

### ISSUE THREAD

**Issue by mdrohmann** [facebook/react-native#14473]
It took me a while to find the support for transformations on the website:

Through the website search I could find the permalink: 
http://facebook.github.io/react-native/releases/0.46/docs/transforms.html#transforms
where the "Prev" arrow button links to the LayoutProps and the "Next"-arrow button to the ShadowProps documentation.  But the documentation on "transforms" does not appear in the menu on the left hand side.

It is probably easy to fix, but I couldn't quickly figure out why this is happening.

**Comment by hramos** [comment]
Our React doc generation is a bit flaky at the moment. This is one of a few bugs affecting the autogenerated API docs in the site.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
