### ISSUE TITLE
Using minHeight with flex creates unexpected padding

### ISSUE THREAD

**Issue by lsps9150414** [facebook/react-native#14478]
### code:
```
<View style={{ flex: 1, borderColor: 'orange', borderWidth: 5 }}>
    <View style={{ flex: 1, minHeight: 50, backgroundColor: 'skyblue', borderColor: 'blue', borderWidth: 5 }} />
    <View style={{ flex: 1, backgroundColor: 'pink', borderColor: 'red', borderWidth: 5 }} />
</View>
```

### Screenshot:
Note the white space at the bottom. The two children View does not fill the parent view.
This only happens when `minHeight: 50` is added.
The height of the white space seems to be the same as the value of `minHeight`.

![asset](https://user-images.githubusercontent.com/5022617/27069680-7d78656e-5048-11e7-8944-4abb4f466b9e.PNG)

### Env:
- "expo": "^17.0.0",
- "react": "16.0.0-alpha.6",
- "react-native": "https://github.com/expo/react-native/archive/sdk-17.0.0.tar.gz",

Real Device, both iPhone & Android.

**Comment by ijharulislam** [comment]
You can check my answer on Stackoverflow. 
https://stackoverflow.com/questions/44514465/using-minheight-with-flex-creates-unexpected-padding/44518993#44518993

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
