### ISSUE TITLE
How safe is React Native with React 16 Alpha?

### ISSUE THREAD

**Issue by ryanhomer** [facebook/react-native#14496]
I am currently on React Native **0.42.3**. Since then 0.43, 0.44, 0.45 have been released as stable and 0.46 is around the corner. RN 0.42.3 uses React **15.4.2**. March saw the release of RN 0.43 which started using the React 16.0.0-alpha series and completely skipped version 15.5. This has prevented me from updating React Native as I've been waiting for a official "stable" release of React 16.

We're now in mid June and the official stable Release of React is **15.5.4**. It appears that version 15.6.0 is now entering RC1 and version 16.0.0 is still in alpha.

So, the React world in using React 15.5.4 and the React-Native world is using React 16.0.0-alpha.

1. Does anyone know why React 15.5 was skipped?
2. Is it safe to use a version of React Native 0.43 and up in production?
3. What's the deal with React 16 anyway? It's not even mentioned in the list of [React releases](https://github.com/facebook/react/releases).

**Comment by gaearon** [comment]
The 16 alpha version of `react` package is entirely stable (we are using it in production). It doesn’t really correspond to what we’ll eventually call “React 16” because `react` package itself contains only very simple internals. The bulk of the implementation is synced separately, and right now React Native uses implementation from React 15.

The mismatch in versioning is because React Native has a much faster release cycle than React DOM, and so in order to ensure our internal versions match up, we have to resort to using alphas.

They are alphas in the sense that they’re not ready for the wider ecosystem consumption (e.g. `react-dom` alphas *which, unlike `react` alphas, do include the new engine* have known issues). And some third party libraries may not work with it yet (we encourage third party libraries to start working on supporting `react` package alphas).

But in the sense of general stability, alpha packages of the `react` package itself are completely solid.
