### ISSUE TITLE
FlatList Animate

### ISSUE THREAD

**Issue by yogevlahyani** [facebook/react-native#14497]
Hello, I have a FlatList of lots of rows and I added a scale & opacity animation.
The thing is that it works only once, and all of the items at once, I want it to initiate one by one (The lists loads 10 rows at once onEndReached but the animation variable is a global variable and I can't figure out a way to make it work, I also tried onScroll but didn't managed to make it ..

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
