### ISSUE TITLE
ReactNative.unstable_batchedUpdates is undefined

### ISSUE THREAD

**Issue by Nauzer** [facebook/react-native#14490]
### Description

In my project I use react-native-meteor (which relies on minimongo-cache) to connect to a Meteor backend server. Upon launching I get an error because of ReactNative.unstable_batchedUpdates being undefined. Was there any change introduced why this API is no longer exposed? If so, is there a replacement?

### Reproduction Steps and Sample Code

Create app with react-native init

`import ReactNative from 'react-native'`

Then try to use ReactNative.unstable_batchedUpdates to feed to minimongo-cache db.

Expected outcome: being able to use batchedUpdates function of ReactNative
Actual outcome: ReactNative.unstable_batchedUpdates is undefined

### Solution

I have imported ReactDOM to use its unstable_batchedUpdates function which does the job for now. This is however not a long-term solution for a ReactNative app... No further suggestion atm.

### Additional Information
See also: https://github.com/inProgress-team/react-native-meteor/issues/183

* React Native version: 0.45.0 and 0.45.1
* Platform: both
* Development Operating System: OSX
* Dev tools: Xcode

**Comment by edmundkwok** [comment]
Looks like `'ReactNativeInternals'` (which exported `unstable_batchedUpdates`) was removed from being exposed as per:

https://github.com/facebook/react-native/commit/f3dbddcf2bdc0e4f49dd6f5220360b5ff383e16f#diff-834d77988fd4294e13e3e35533b3e248L161

As an interim fix, we are importing `'ReactNativeInternals'` directly:

```diff
- import ReactNative from 'react-native';
+ import ReactNative from 'react-native/Libraries/Renderer/src/renderers/native/ReactNative'
```

Would the Internals be exposed in a future version of RN or will we have to use this as a solution?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
