### ISSUE TITLE
Keyboard persists when you use the Done/Go button to navigate to a new page

### ISSUE THREAD

**Issue by mmckinley8** [facebook/react-native#14494]
### Description
Prior to upgrading to 0.44.0 I could use the keyboard "Go" button to navigate to a new page. Now, it navigates but the keyboard reappears. I must dismiss the keyboard and trigger the navigation with a non-keyboard button. This also only happens on a fresh installation. After I hard close and reopen, it works.

Explain what you did, what you expected to happen, and what actually happens.

### Reproduction Steps and Sample Code

List all the steps required to reproduce the issue you're reporting. These steps should be clear and concise.

  ***An example of your code or a repro using Snack is REQUIRED***
`<TextInput returnKeyLabel='Go' returnKeyType='go' onSubmitEditing={this.navigateToProfile}  />`

### Solution

`<TextInput returnKeyLabel='Done' returnKeyType='done' onSubmitEditing={Keyboard.dismiss}  />`

What needs to be done to address this issue? Ideally, provide a pull request with a fix.

### Additional Information

* React Native version: [FILL THIS OUT: Be specific, filling out "latest" here is not enough.]
React-Native 0.44.3
* Platform: [FILL THIS OUT: iOS, Android, or both?]
iOS
* Development Operating System: [FILL THIS OUT: Are you developing on macOS, Linux, or Windows?]
macOS
* Dev tools: [FILL THIS OUT: Xcode or Android Studio version, iOS or Android SDK version, if applicable]
Xcode

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by ProteanDev** [comment]
Still getting the same issue with RN 0.52.0

And yes @mmckinley8's solution works.

And RN Team, would you please stop closing issues without providing or at least accepting solutions first? Don't take it personally, but you guys need to address more issue soon than the open source community can find them.
