### ISSUE TITLE
App crashes during launch, built using react-native run-ios --device "name"

### ISSUE THREAD

**Issue by galmis** [facebook/react-native#14500]
### Description

Initially I found that an app built using 'fastlane ios beta' was silently failing during launch. Then I tried running react-native run-ios --device "name" and saw the same issue. In Crashlytics dashboard I can see that the following exception is being thrown "Fatal Exception: RCTFatalException: No bundle URL present. Make sure you're running a packager server or have included a .jsbundle file in your application bundle." 

This works ok in a simulator, also it works fine on a device when using '--configuration Release' flag.

Suggestions how to fix this in #12754, #14118 or stackoverflow didn't help.

### Additional Information

* React Native version: Initially tried on 0.44.3, but then tried fresh projects on 0.39, 0.40, 0.44, 0.45.1
* Platform: iOS
* Development Operating System: macOS Sierra 10.12.5
* Dev tools: XCode 8.3.3

**Comment by bcitdaltond** [comment]
Just a comment: You could just open XCode and push it to your device... :)

- If you opened the project in XCode you would see that the project needs a "Bundle Identifier"  
maybe specifying no '--configuration Release' does not set it.

**Comment by dzjin** [comment]
@galmis how did you end fixing this in fastlane?

My app is crashing on start in testflight, but works fine in the simulator. It started happening after upgrading from react-native 0.44 -> 0.49.5. I just ran `react-native run-ios --configuration Release` and I can recreate what's happening on the phone on the simulator now.

**Comment by wootwoot1234** [comment]
@dzjin did you end up solving this?  Did you make any progress?  I'm seeing the same issue.  It's funny because it's not happening on other apps.

**Comment by dzjin** [comment]
@wootwoot1234 I am. There were quite a few issues.

- My dependencies were out of date. Later RN versions (0.49 I think) required React 16, which had a breaking change. Mostly fixed by updating dependencies.
- I had `nvm` installed (never used it, actually), and had `.nvm` folder, while nvm was pointed at node from io.js days. My understanding is that in release, JS is bundled and served, while in debug, the packager serves JS. When bundling for release, RN was picking up the incorrect node version, because it checks for `~/.nvm`.
- My `npm install -g react-native`'s react version was 0.18 or so, which was the last time I tried to make an RN app. I noticed that when compiling, RN uses the _global_ RN's binaries, as opposed to the local one in `node_modules`. I reinstalled react-native globally.
- .. and more, less drastic things that were corrected on the way

My advice is to first check your dependencies and upgrade them thoroughly. There are tools provided by React to check this for you. And then load up the project in Xcode, and try to manually build them from there until you succeed in building. 

Feel free to private message me for help.

**Comment by rodrijuarez** [comment]
Having the same problem here, I don't know if the problem it's related because I create a WebView of the application or what

**Comment by mvanroon** [comment]
@galmis I ran into the exact same thing. Were you able to debug your --release versions? Was it a Javascript error in the end? Or did you just trial&error the whole thing until it worked?

**Comment by mvanroon** [comment]
@dzjin I ran into the exact same thing. Were you able to debug your --release versions? Was it a Javascript error in the end? Or did you just trial&error the whole thing until it worked?

(by the way I don't think GitHub has private messaging)
