### ISSUE TITLE
Refresh Rate 120fps iPad Pro 2017

### ISSUE THREAD

**Issue by RomualdPercereau** [facebook/react-native#14505]
### Description

The new iPad Pro support a 120 fps refresh rate, but the perf monitor is only showing 60 fps.
I can't tell if the real display speed of the animated librairie is really on 120 fps?

### Reproduction Steps and Sample Code

Run a debug build on an iPad Pro device (not a simulator). 

### Solution

The perf monitor should display as much as 120 fps.

### Additional Information

* React Native version: 0.45
* Platform: iOS - iPad Pro 2017  
* Development Operating System: macOS
* Dev tools: Xcode

**Comment by hramos** [comment]
Can you send a PR? The new hardware is unlikely to be in many of the core contributor's hands, so you're probably in a better spot to look into this.

**Comment by ide** [comment]
You might also want to go through the codebase and see if 1/60 is hardcoded anywhere. IIRC a lot of React Native's scheduling is tied to CADisplayLink, which should account for 120 fps, but there still might be parts of the code that assume 60 fps.

**Comment by RomualdPercereau** [comment]
Yes, I read the code and 60 fps looks to be hardcoded in
 
Libraries/NativeAnimation/Drivers/RCTAnimationDriver.h

`static CGFloat RCTSingleFrameInterval = 1.0 / 60.0;`

Is their anywhere else, is it implemented? I'll try to submit a PR.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by dissidently** [comment]
reopen it, please. If it's not solved... @hramos ,
