### ISSUE TITLE
How do I get Raw folder path in Android

### ISSUE THREAD

**Issue by Ashi90** [facebook/react-native#14515]
I have searched alot but unable to find any solution for fetching up mp3 file from raw folder.

How do I get local mp3 path for playing mp3 from raw folder in Android.

I am using "react-native-audio-streaming" module.

this.chalisa = './song/shree_hanuman_ji_ki_aarti.mp3'

NO LUCK AT ALL :(

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

**Comment by Ashi90** [comment]
Why I asked such kind of question in Stackoverflow,?
Is this question is not related to react native???
I already asked this question on Stackoverflow but not getting any success. 
Please let me know what can I do for solving my problem.
