### ISSUE TITLE
[FlatList] `FlatList` and `SectionList` mocks are not defined in `jest/setup.js`

### ISSUE THREAD

**Issue by david-casagrande** [facebook/react-native#14514]
### Description
using `jest-react-native` and testing a component with `FlatList` or `SectionList` logs an error `Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.`

### Solution

`FlatLlist` and `SectionList` mocks need to be defined in `jest/setup.js` 

### Additional Information

* React Native version: 0.45.1
* Platform: iOS and Android
* Development Operating System: macOS
* Dev tools: Xode 8.1

**Comment by mateen-hussain** [comment]
I'm having a similar issue. I have a component (SearchResultsScreen) rendering below:

`render() {
    let CentresList;
    if(typeof this.state.Centres == 'undefined' ||
              this.state.Centres.length == 0) {
        CentresList = <Text>No results found</Text>
    } else {
        CentresList = <FlatList
          data={this.state.Centres}
          keyExtractor={(item, index) => item._centre_id}
          renderItem={({item}) => <CentreComponent Centre={item}/>}
          ItemSeparatorComponent={() => <ListSeperator />}
        />;
    }
    return(
      <View>
        {CentresList}
        <ListSeperator />
      </View>
    );
  };`

In my jest my test looks like: 

`jest.disableAutomock();
  import React, {Component} from 'react';
  import {shallow, mount, render} from 'enzyme';
  import SearchResultsScreen from '../../src/SearchResultsScreen/index';
  import CentreComponent from '../../src/SearchResultsScreen/CentreComponent';`

 `describe('SearchResultsScreen', () => {
    test.only('renders more than one CentreComponent', () => {
      global.fetch = jest.fn().mockImplementation(() => {
          let kc = [{
               _centre_id: 1,
               name: 'test',
             }, {
            _centre_id: 2,
            name: 'testee',
             }]
          return Promise.resolve({ok: true, json: function(){return kc}});
      });
      const comp = mount(<SearchResultsScreen origin_long='5' origin_lat='2' distance='5'/>);
      expect(comp.find(<CentreComponent/>)).toHaveLength(2);
    });
 });`


When the test runs it fails to render below:

`CentresList = <FlatList
          data={this.state.Centres}
          keyExtractor={(item, index) => item._centre_id}
          renderItem={({item}) => <CentreComponent Centre={item}/>}
          ItemSeparatorComponent={() => <ListSeperator />}
        />;`

As react throws an exception:

`React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of SearchResultsScreen.`

as a result of this my test is failing.

Is there a fix/workaround for it, till the fix is released.

_PS: I'm a newbie to react/Jest/JS, so if you can dumb down the response it will be great of you_
