### ISSUE TITLE
[TextInput Android] Text truncated on start when text longer than TextInput size

### ISSUE THREAD

**Issue by ahetawal-p** [facebook/react-native#14519]
### Description

Trying to use the Android TextInput component, but the text gets cut off in start when text is longer than the component size.
![screen shot 2017-06-14 at 2 44 44 pm](https://user-images.githubusercontent.com/8919529/27156490-1e48212c-5112-11e7-8ca1-8f5cc2f37e18.png) required state
![screen shot 2017-06-14 at 2 11 51 pm](https://user-images.githubusercontent.com/8919529/27156488-1e3428b6-5112-11e7-9074-69a3a31bbb0f.png) actual state

Is there way I can get the text rendered from start or set the cursor at beginning. And only set the cursor to end when this component is focussed or selected ?

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
