### ISSUE TITLE
[Perf] Memory leak in profiler

### ISSUE THREAD

**Issue by jessepollak** [facebook/react-native#1452]
When enabling "Start Profiler" in the Debug menu, there's a consistent memory leak. The primary culripts seem to be `__NSDictionaryI`, `CFString (immutable)` and `CFNumber`. If you disable the profiler, the leak goes away.

![screenshot 2015-05-29 18 46 11](https://cloud.githubusercontent.com/assets/1097953/7895163/0f133b6e-0633-11e5-85ce-ebac20259583.png)

**Comment by ide** [comment]
cc @tadeuzagallo

**Comment by tadeuzagallo** [comment]
@jessepollak What were you running? I just profiled running UIExplorer and my graph wasn't quite as impressive as yours. So it'd be nice to know what was happening during the profiling so I can have a better idea.

But what I can anticipate is that the profiler implementation (if you haven't looked into it) is the simplest possible, it has an array where it stores all the calls, the calls are represented as a dictionary containing a lot of strings and numbers (Thread Name, start & end, name, process id, category and all the args(!)).

The minimum you can have (even if you're application is doing nothing) is 3 events per frame: UI Thread VSync, JS Thread VSync and Dispatch Frame Update. The first 2 are immediate events (a little bit smaller memory-wise) and the other is a complete event. so it'd be 180 events per second. 

The math kind of adds up, if you think that each event has at least 1 NSDictionary, 1 NSArray, 13 NSStrings, 4 NSNumbers (I measured a couple random events found ~200b/event average). so it's 200 * 180ev/s * 35s (your app ran) = 1,260,000b = 1.20mb (your profile shows ~1.60mb of memory shared between dictionaries, strings and numbers retained), and since after you stop the memory is released, I think it's plausible, but let me know if I assumed/calculated anything wrong (math is not my best skill...)

Also trace-viewer accepts another format, a text dump, where you can dump directly to a buffer, but I haven't looked into implementing that myself yet. You can find more information [here](https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview) in case you're interested.

@ide thanks for the tag, always so fast! :)

**Comment by jessepollak** [comment]
That makes total sense to me.

I'm running a component inside of an already existing app. There are no long running animations or anything like that going on in the JS (I've disabled the one that is causing #1454). The only animating thing is a native UIView that I'm using which uses UIView animations, but I don't think that should affect the JS profiler.

Can you give me a little more depth/direction on trace-viewer (or a resource to go read)? To be honest, I'm not even sure where the React Native profiler is exposed (I just enabled it because I've been trying to track down another memory leak, but haven't figured out how to actually use it).

**Comment by jessepollak** [comment]
One other note: all of the memory gets cleared when you do "Stop Profiler", so that definitely points to it as the culprit.

**Comment by tadeuzagallo** [comment]
@jessepollak When you finish a profile it'll convert all the data to JSON, following the format specified by trace-viewer, in the document I've linked above (https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview in case you missed).
Then it saves this JSON dump on your `/tmp` folder, and will try to run trace-viewer's `trace2html` command, if it's in your path (or in a path you might have specified via the environment variable `TRACE_VIEWER_PATH`) it'll convert the data to a trace-viewer graph, and pop in your browser. If it can't find the `trace2html`, it'll output precise information (I think it is, any feedback is welcome) on the server console about where's your data, how to convert it manually (in case you don't want to lose the run), and how to get trace-viewer setup to next profiles.

To get it setup all you need to do is download it from https://github.com/google/trace-viewer and either add `trace2html` to your path, or setup the environment variable, either by `export TRACE_VIEWER_PATH=/path/to/trace-viewer` or by running the server with `TRACE_VIEWER_PATH=/path/to/trace-viewer npm start`

In case you wan't to check the code, you can have a look at [`RCTProfile.h`](https://github.com/facebook/react-native/blob/master/React/Base/RCTProfile.h) and [`RCTProfile.m`](https://github.com/facebook/react-native/blob/master/React/Base/RCTProfile.m), and the server code that dumps the data is available in [`react-packager/src/Server/index.js`](https://github.com/facebook/react-native/blob/master/packager/react-packager/src/Server/index.js).

What you can expect if the profiler works is a graph like this:

![screen shot 2015-05-30 at 19 04 54](https://cloud.githubusercontent.com/assets/764414/7898665/e85823d2-06fe-11e5-9403-2de3654984c7.png)

Please note that the simulator is very unreliable for this kind of profile, the timing is not the same as in the device (this profile is from the simulator since I just took a quick screenshot to attach), but you can notice things like the VSync values on the UI thread and JS threads are completely different, what doesn't make any sense.

This wasn't documented yet because I just wrote it on a sort of hackathon of my own, but might be the time to do so (if any of you guys feel like doing it, the information from this thread should be enough, but feel free to ping me otherwise)

**Comment by paramaggarwal** [comment]
This is amazing @tadeuzagallo. Would be great to add to docs. @brentvatne just published `trace2html` to Homebrew as well.

**Comment by brentvatne** [comment]
> Please note that the simulator is very unreliable for this kind of profile, the timing is not the same as in the device (this profile is from the simulator since I just took a quick screenshot to attach), but you can notice things like the VSync values on the UI thread and JS threads are completely different, what doesn't make any sense.

@tadeuzagallo - is this still true on the most recent version of the profiler? Just looking back of some screenshots I did for release notes last night and it looks like VSync values on UI/JS thread were properly aligned

**Comment by tadeuzagallo** [comment]
@paramaggarwal Thanks! This will be documented soon, @brentvatne adding it to Homebrew was part of his work helping us document it :)

@brentvatne I'm not sure how it can vary, but I just profiled again and apparently yes, look at the screen shot and you'll see, the purple lines (the UI frame delimiter) are totally unaligned with the JS blocks that contain the JS thread tick.

![screen shot 2015-06-23 at 21 49 19](https://cloud.githubusercontent.com/assets/764414/8317069/d56ace08-19f2-11e5-9356-3b7c18f84974.png)

**Comment by avnerbarr** [comment]
I'm late to the party - but this post looks close to what I am researching.
I have an existing app that I would like to integrate RN too. 
I am interested in the cost of the framework. That is the memory and CPU overhead that it adds to the app - Are there any statistics on this? 
As a baseline we could assume only running the tutorial app in an already existing app. 
I would be interested in understanding the deltas added.
Any thoughts how to measure this?

**Comment by brentvatne** [comment]
@avnerbarr - I'm not sure about that, @tadeuzagallo do you have any ideas?

**Comment by tadeuzagallo** [comment]
@avnerbarr Can you add a simple RN view to your app for testing? Running a standalone app wouldn't be quite the same. I'd profile with Xcode Instruments before and after adding the view.

**Comment by avnerbarr** [comment]
I'm interested in a memory requirement "number" more than profiling an app (as a general guideline). 
Is there a technical analysis of the various objects and memory requirements they have? 
For instance how many JS VMs are allocated and their memory profile along with any other resources required to run the framework?
I imagine that the overhead of integrating RN to an existing project is pretty big.
