### ISSUE TITLE
Cannot read property 'string' of undefined | React.PropTypes | LayoutPropTypes.js

### ISSUE THREAD

**Issue by Deevent** [facebook/react-native#14538]
After deleting and reinstalling my node_modules folder, I'm facing an issue that I don't understand in LayoutPropTypes.js file.

In node_modules/react-native/Libraries/StyleSheet/LayoutPropTypes.js
The following variable is undefined : var ReactPropTypes = require('React').PropTypes;

react-native: 0.45.1
react: 16.0.0-alpha.12

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

**Comment by emileNetter** [comment]
I have the same issue !

**Comment by gyetvan-andras** [comment]
I have the same problem. In React 15.5, React.PropTypes deprecated, however as I reviewed RN code base there are lot of use of the deprecated call.

I cannot understand @hramos why he close this issue giving a meaningless answer.

**Comment by hramos** [comment]
If you believe this belongs in the repo, please submit a new issue and make sure to follow the template. Otherwise the issue will be closed. Thanks!

**Comment by Deevent** [comment]
@gyetvan-andras @emileNetter You should make sure that your react version is the same as the one in react-native's dependencies.

**Comment by nikasvan** [comment]
Hey guys, having the same issue, any luck with this?

**Comment by gyetvan-andras** [comment]
@Deevent has the right answer. After ensuring that react version is the same as the one in react-native's dependencies everything worked fine. For this I have to edit package.json to remove ^ from version specs, like the this
`
"react": "16.0.0-alpha.12",
"react-native": "0.45.1",
`
After this, I deleted node_modules, clean watchman and npm cache.
