### ISSUE TITLE
What is MyAppText component??? I have custom font and want to use it throught my app. 

### ISSUE THREAD

**Issue by nguyencaochien** [facebook/react-native#14532]
T have custom font and want to use it throught my app but don't know how to do this. I read Text.md and see that using MyAppText component can resolve it. But where is <MyAppText> and how to write it? 

Please help me.

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
