### ISSUE TITLE
Image not loading from Images.xcassets

### ISSUE THREAD

**Issue by PriyamDutta** [facebook/react-native#14539]
Unable to load images facing the following issue

![simulator screen shot 16-jun-2017 12 24 33 am](https://user-images.githubusercontent.com/21267926/27196981-3426e51e-522a-11e7-8b70-862e26dd3dd9.png)

**Comment by SmirnovW** [comment]
I think this issue should be opened because of an image loading from the Images.xcassets doesn't work as it describes here https://facebook.github.io/react-native/docs/images.html#images-from-hybrid-app-s-resources

I add an image to the Images.xcassets in my project, and I'm trying to get it using the next syntax 
`<Image source={{uri: 'home'}} onError={this.error}/>`
I don't get any errors and I also don't see the image.

**Comment by hramos** [comment]
Can you open a new issue? This one was closed due to a lack of sufficient information.
