### ISSUE TITLE
[Perf] Memory leak with requestAnimationFrame and named anonymous function

### ISSUE THREAD

**Issue by jessepollak** [facebook/react-native#1454]
In a component I've created, I am doing an animation that uses recursion and `window.requestAnimationFrame`. The following code snippet causes this memory leak:

```javascript
var _animation = () => {
    window.requestAnimationFrame(_animation)
}
```

**EDIT: This fix doesn't work. It just causes the code to crash which I somehow missed (but fixes the leak, lol).**

~~Now, if we remove the `var` and put the named anonymous function in the global scope...~~

```javascript
_animation = () => {
    window.requestAnimationFrame(_animation)
}
```

~~Voila, the leak goes away!~~

No idea how to start digging into this one. Let me know if there's any other information I can provide.

Thanks y'all for all of your hard work :)

**Comment by jessepollak** [comment]
NEVERMIND! I wasn't paying enough attention — the fix just throws an error.

**Comment by tadeuzagallo** [comment]
There's indeed a memory leak, after letting the app run for ~90s I noticed an increase in the memory used of ~10mb (40%), but from what I profiled with Xcode, it seems that it's retained by JS. I can see the garbage collection is running but apparently it doesn't collect all the memory. I'll profile it on the chrome debugger soon and update it here.

**Comment by jessepollak** [comment]
How did you determine that it's being retained by JS? The primary culprits seem to be 4kb and 8.5kb mallocs, but to be honest I'm not really sure where those come from. Screenshot for me attached (running in a iPhone 6 simulator on my Macbook Pro).

![screenshot 2015-05-30 09 54 47](https://cloud.githubusercontent.com/assets/1097953/7898350/395111ba-06b2-11e5-8ce8-46bf2c05fdd0.png)

**Comment by tadeuzagallo** [comment]
You have to mark the generations, otherwise you're seeing the memory used by the whole app.
So you mark a generation when the app starts up, and other after a while, and sees the difference:

![screen shot 2015-05-30 at 19 26 44](https://cloud.githubusercontent.com/assets/764414/7898758/2203fdd8-0702-11e5-9e1f-4d6fc6818675.png)

Then you can check where was the memory allocated:

![screen_shot_2015-05-30_at_19_27_26](https://cloud.githubusercontent.com/assets/764414/7898767/9ae40fcc-0702-11e5-9dc1-81171dd0940d.png)

And you'll see that it was allocated by JavaScriptCore.

I ran the chrome debugger very quickly but haven't found the issue yet, will look deeper soon.

**Comment by jessepollak** [comment]
Ah, that makes total sense to me. Generations are so cool, didn't know about them before. 

I know that this is a common memory issue in JS, but that the JS VM in the browser automatically frees the memory after a while (though it can still consume some while it's waiting to be freed). Could the Apple VM not implement that (seems like a big flaw, but figured I'd suggest).

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/perf-memory-leak-with-requestanimationframe-and-named-anonymous-function
