### ISSUE TITLE
Text with adjustsFontSizeToFit turned on will lose fontVariant

### ISSUE THREAD

**Issue by fangpenlin** [facebook/react-native#14542]
<details>
  **Issues that do not describe a bug or do not fill out the template below will be closed**

  We use GitHub Issues exclusively for tracking bugs in React Native.

  - If you're looking for help with your code, consider asking on Stack Overflow instead: http://stackoverflow.com/questions/tagged/react-native
  - Want to know more about future plans? Check out the roadmap: https://github.com/facebook/react-native/wiki/Roadmap
  - Have a feature request that is not covered in the roadmap? Submit it here: https://react-native.canny.io/feature-requests

  ## Reporting bugs

  Want to **report a bug**? Please read the bug reporting guidelines: https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#bugs
</details>

### Description

`Text` view should respect `fontVariant` when `adjustsFontSizeToFit` is true

### Reproduction Steps

Install a custom font that supports old style numbers, like `CeraPRO` in this example. Then add two `Text` with `fontVariant` as ['lining-nums'], one with `adjustsFontSizeToFit` set to `true`, another set to false or just omit it

#### Sample Code

```
<View style={{flex: 1}}>
    <Text style={{
        ontFamily: 'CeraPRO-Regular',
        fontSize: 64,
        fontVariant: ['lining-nums'],
        width: 400,
        height: 200}}
        adjustsFontSizeToFit={true}
        minimumFontScale={0.6}
    >
        9C7 B2A
    </Text>
    <Text style={{
        fontFamily: 'CeraPRO-Regular',
        fontSize: 64,
        fontVariant: ['lining-nums'],
        width: 400,
        height: 200}}
    >
        9C7 B2A
    </Text>
</View>
```

then you will see the first Text with `adjustsFontSizeToFit` to be true is not respecting `fontVariant` style we gave it (so that the number has offset instead of aligning with baseline)

![img_0036](https://user-images.githubusercontent.com/201615/27205523-32ec8a8a-51e6-11e7-8847-fa9a07134b19.PNG)

### Solution

After tracing into the code, it appears to be

https://github.com/facebook/react-native/blob/master/Libraries/Text/RCTShadowText.m#L562

this line

```objc
UIFont *newFont = [font fontWithSize:originalFont.pointSize * scale];
```

for adjusting the font size, somehow `fontWithSize` comes back without the `fontVariant` we set it before. Apple's document didn't say too much about this `fontWithSize`, method, it just says it returns the same font except the size is different. I think it supposes to return a font with the descriptor we set to, but somehow it doesn't. So it's more likely to be a bug of iOS.

I will create a PR shortly to address this issue shortly, to workaround the issue, I will do the same thing as it's done in RCTFont

https://github.com/facebook/react-native/blob/master/React/Views/RCTFont.mm#L314-L320

set the font with descriptor for variant if it's present.

### Additional Information

* React Native version: 0.44.2
* Platform: iOS
* Development Operating System: macOS
* Build tools: Xcode Version 8.3.3 (8E3004b), iOS SDK 10.3

**Comment by fangpenlin** [comment]
Forgot to mention, thanks @jarodl for spotting this bug

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
