### ISSUE TITLE
WebView.props.source.uri is never updated

### ISSUE THREAD

**Issue by savanthongvanh** [facebook/react-native#14556]
WebView uri is never updated.

I'm loading a 3rd party chat client into a webview.  The exit button of this this does history.go(-1)
which is not what I want but I have no control.  My work around is to monitor the webview and call a function  when they hit back.  The problem is that I can't find out from the webview when they go back.  WebView.props.source.uri never changes after it's loaded regardless of where you navigate to.

I would expect it to tell me the uri of the content currently loaded in the page.

Check out my snack that does this [link](https://snack.expo.io/H1bHVDW7W)

import React, { Component } from 'react';
import {WebView } from 'react-native';

var intervalHandle;
  
export default class App extends Component {

  pingWebView (){
    console.log(this.wView.props.source.uri);
  }
  
  render() {
    return (
        <WebView
        ref={(wView)=>{this.wView = wView}}
        source={{uri: "http://www.google.com"}}/>
    );
  }
  
  componentWillUnmount(){
    clearInterval(intervalHandle);
  }

  componentDidMount(){
    console.log('mounted:');
    console.log(this.wView);
    
    intervalHandle = setInterval(this.pingWebView.bind(this), 1000);
  }
}

### Solution

Is this a bug?  Is there a workaround?

### Additional Information

* React Native version: 0.34.1
* Platform: iOS
* Development Operating System: macos 10.12.1

**Comment by savanthongvanh** [comment]
one workaround is this but it's only available during the event

        onLoadEnd={(e)=>{console.log("loaded");console.log(e.nativeEvent.url);}}
        onLoadStart={(e)=>{console.log("loading");console.log(e.nativeEvent.url);}}

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
