### ISSUE TITLE
Something went wrong while linking. 

### ISSUE THREAD

**Issue by giffordjoe** [facebook/react-native#14574]
Err: Something went wrong while linking. Error: Expected "/*", "//", or "{" but "<" found.
Expected "/*", "//", or "{" but "<" found.

Using react-native 0.45.1 and react-native-cli 2.0.1.  This is a new react-native project.

**Comment by ioannis85** [comment]
i have the same problem!!!

**Comment by euandrei** [comment]
Same

**Comment by arijitdey** [comment]
I am having the same problem. Any solution?

**Comment by lra-tapptic** [comment]
Same for me. The usual workaround seems to have to do with HEADER_SEARCH_PATHS being on one line in your .pbxproj file ([see here](https://github.com/facebook/react-native/issues/13461#issuecomment-295124309)) but that doesn't apply to me. A shame that the error doesn't show the line where the error is found.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
