### ISSUE TITLE
marginHorizontal should override marginLeft, marginRight, etc.

### ISSUE THREAD

**Issue by gsklee** [facebook/react-native#14587]
### Description

If a component is styled with something like:

```css
paragraph: {
  marginLeft: 100,
  marginRight: 100
}
```

It will not be able to be overridden later by something like:

```css
paragraph: {
  marginHorizontal: 0
}
```

Which is **not** the desired behavior.

### Reproduction Steps

See the sample code.

#### Sample Code

https://snack.expo.io/rkVGFONQW

### Solution

In CSS, something like:

```css
element: {
  margin-left: 100px,
  marign-right: 100px,
  margin: 0
}
```

Would result in a 0 margin. The styling in React Native should follow it to make for a more consistent styling experience.

### Additional Information

* React Native version: 0.44.3
* Platform: iOS
* Development Operating System: macOS
* Build tools: Xcode / Expo 17.0.0

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
