### ISSUE TITLE
React Native WebView onMessage doesn't work on Android

### ISSUE THREAD

**Issue by fernandofranca** [facebook/react-native#14586]
### Description

WebView's onMessage function never gets called on some Android versions. 

This behaviour is not consistent on the Expo simulator. Test on physical devices.

### Reproduction Steps
Se line 40 on the following snack. 

If you test on a physical device and call `window.postMessage` without the second parameter it will throw "Failed to execute 'postMessage' on 'Window': 2 arguments required, but only 1 present".

The second parameter should be `'*'`.

See postMessage api on Mozilla: https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage

`postMessage` seems to work only after the DOMContentLoaded event but not immediately. Expo simulator catches the two last events, but on a physical device I was able to trigger and receive messages before DOMContentLoaded. I think this should've been clarified on the docs.

#### Sample Code

https://snack.expo.io/HybU5stmW

### Solution

Update the docs. Where is stated:
"window.postMessage accepts one argument, data, which will be available on the event object, event.nativeEvent.data. data must be a string."

Should state:
window.postMessage requires two arguments, data, ...., and `targetOrigin` which should be `'*'`.

### Additional Information

* React Native version: react-native: 0.44.2
* Platform: Android 6.0 and 5.0 (didn't tested on previous versions)
* Development Operating System: macOS 10.12.4
* Build tools: Xcode 8.3.3, Android Studio 2.3

**Comment by hjh5696** [comment]
@fernandofranca I am in the exact same situation.
You mean `window.postMessage (SOME_DATA, '*')` should be used instead of `window.postMessage (SOME_DATA)`. right?
But it does not work.. if I am doing something wrong, please let me know

**Comment by fernandofranca** [comment]
@hjh5696 Yup. 

In my environment `window.postMessage(someString, '*');` works.  YMMV as it's not documented and the behaviour is not consistent.

I'd suggest you to wrap your call in a try/catch and check what kind of error is being thrown.

**Comment by hjh5696** [comment]
@fernandofranca Thank you for reply. However, even if I use try/catch, how do I get an error message within the html code of webview? is it from Android studio?

**Comment by fernandofranca** [comment]
@hjh5696 I didn't knew any other way and had to improvise. 

Eg.: Inside your webview, use the catch block to add a new DOM element containing the stringified error.
```
function printStuff(stuff){
  var el = document.createElement("pre");
  var str = JSON.stringify(stuff);
  el.innerHTML = str;
  document.body.appendChild(el);
}
```
Don't forget: **Do not use // inline comments**

**Comment by hjh5696** [comment]
@fernandofranca Thank you so much! I will let you know when I figure out my problem.

**Comment by hjh5696** [comment]
@fernandofranca I solved my problem. In my case, it worked well in Android 7.1 but not in below versions. I used some arrow functions in my <script></script>, and that was the problem. After I changed them to function(){ }, it works well in below versions.
Thank you for your help!

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by 0x5e** [comment]
My guess:
RN will replace the `window.postMessage` function after webview loaded, so while webview is still loading, `window.postMessage` is not replaced already. The original `window.postMessage` need
two arguments and this function is not what we need.
Here's my workaround:
```
    _postMessage(type, data) {
      if (window.postMessage.length !== 1) {
        console.log('window.postMessage not ready')
        setTimeout(function() {
          _postMessage(type, data);
        }, 500);
        return;
      }

      window.postMessage(JSON.stringify({"type": type, "data": data}));
    },
```

**Comment by tranduykhanh** [comment]
@0x5e Confirm this hacking worked 😄 
Remember to remove any comment, add missing semicolon in injectedJavaScript in order to work!

**Comment by fungilation** [comment]
WebView really needs more love, on [both iOS](https://github.com/facebook/react-native/issues/321#issuecomment-373464088) and Android sides apparently.

**Comment by esipavicius** [comment]
Om it works!!! ;D

`
injectedJavaScript={"
   setTimeout(function(){
      window.postMessage('asdsa', '*');
   },1000);
"}
onMessage={ (event)=>{
    let message  = event.nativeEvent.data;
    console.log(message);
    console.log('message');
} }
`

**Comment by zabipakdel** [comment]
if (window.postMessage.length !== 1) {
  window.postMessage = function(msg) {
    setTimeout(function () {
      console.log('window.postMessage not ready')
      window.postMessage(msg);
    }, 500);
  }
}

how to use that ??
I have problem every one can help me??
