### ISSUE TITLE
[iOS] Overwriting "multipart/mixed" content-type if set explicitely

### ISSUE THREAD

**Issue by stinodes** [facebook/react-native#14597]
### Description

I am trying to send a `multipart/mixed` request, uploading a picture and message to a back-end.
Setting the header `Content-Type: multipart/mixed` works as expected on Android and adds the boundary. On iOS, it defaults to `multipart/form-data`.

Seems to be a bug, unless there are iOS limitations I am not aware of.

### Reproduction Steps

Start a request from javascript, set a `FormData`-instance as body and set the `Content-Type` header to `multipart/mixed`.

#### Sample Code

https://snack.expo.io/B1cRI7rQZ
(Will always produce an error, due to a lack of a public endpoint to fire the request to. Might be able to intercept event somehow.)

### Solution

In `/Libraries/Network/RCTNetworking.mm`, conditionally use the Content-Type header passed from the javascript request at `line: 120`.

### Additional Information

* React Native version: **0.44.0**
* Platform: **iOS**
* Development Operating System: **OS X 10.12.3 (16D32)**
* Build tools: **XCode Version 8.3.2 (8E2002), iOS 9.3.5, React Native packager**

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
