### ISSUE TITLE
initialScrollIndex bug

### ISSUE THREAD

**Issue by Symous** [facebook/react-native#14591]
if I use expression to set initialScrollIndex value , the FlatList will not scroll to the excepted position.
```js
//Not working.
<FlatList
  data = {this.state.items}
  initialScrollIndex = {this.state.items.length > 0 ? 5 : 0 }
  ....
/>
```
But if I give it a value directly it will scroll to the target index.
```js
//Working.
<FlatList
  data = {this.state.items}
  initialScrollIndex = {5}
  ....
/>
```

Is it a bug of RN?I catch this with version 0.45.1 Android.

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
