### ISSUE TITLE
[Bug] Maximum call stack size exceeded if HMR not active

### ISSUE THREAD

**Issue by luchillo17** [facebook/react-native#14614]
### Description

I created an app with CRNA, then ejected to normal RNA, then followed [this tutorial](https://medium.com/@rintoj/react-native-with-typescript-40355a90a5d7) to allow typescript code, at the end when running in device the app returned error `Maximum call stack exceeded`, however it fixes when i activate HMR from the app menu.

### Reproduction Steps

I've linked a repo, just clone, install deps, start `React-Native` packager and run in Android with `react-native run-android`, the red screen with error should show, if nothing shows (not even text) then close the app in emulator and open again.

Lastly to make that red screen go away, open the app menu with Ctrl + M (in linux, idk how to in OSX), and activate HMR.

Actual screen of error:
![image](https://user-images.githubusercontent.com/9698639/27307139-ed9cb894-550d-11e7-8425-bca591161bd2.png)

#### Sample Code

Repo mentioned above: https://github.com/luchillo17/react-native-error-repo

### Additional Information
* React Native version: react-native@0.44.3
* React version: react@16.0.0-alpha.6
* Platform: Android (don't have Mac for test in IOS)
* Development Operating System: Ubuntu 17.04
* Build tools: I've installed most android sdk versions:
![image](https://user-images.githubusercontent.com/9698639/27306786-9fe8cf62-550c-11e7-8222-cf307511528c.png)

**Comment by ValentinBlokhin** [comment]
+1

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
