### ISSUE TITLE
ChromeCustomTab fails to open after building a .aar file (Android) and I get a FATAL EXCEPTION: mqt_native_modules

### ISSUE THREAD

**Issue by MSiddharthReddy** [facebook/react-native#14616]
I am trying to open a ChromeCustomTab through my SDK. The code works fine until I build a .aar file and try using it. I get a FATAL EXCEPTION: mqt_native_modules error where I try to call my react native module. I get a java.lang.ClassNotFoundException: Didn't find class "android.support.customtabs.CustomTabsIntent$Builder" on path:. 

The same code works fine before I build the .aar file. Any thoughts?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
