### ISSUE TITLE
Dealing with FileProvider (Android) globally within React Native and libraries

### ISSUE THREAD

**Issue by iremlopsum** [facebook/react-native#14615]
### Description

If I want to have two libraries, for example [Image Picker](https://github.com/react-community/react-native-image-picker) and [Doc Viewer](https://github.com/philipphecht/react-native-doc-viewer). They both have their own AndroidManifest file that defines a provider with android:name="android.support.v4.content.FileProvider". Which causes an issue because it can't be defined multiple times and it causes a merge issue. As I understand, this needs to be defined globally.

What is the recommended way of dealing with this, so that I as a user can define those things globally and libraries still can give me access to FileProvider?

### Additional Information

* React Native version: 0.45.1,
* Platform: Android
* Development Operating System:Windows

**Comment by hey99xx** [comment]
I think the libraries should be updated to use unique names. See https://stackoverflow.com/questions/43175014/possible-to-use-multiple-authorities-with-fileprovider

**Comment by iremlopsum** [comment]
@hey99xx this is interesting. I currently am stuck with how to approach it. I probably should just fork the libraries and use them as local modules, but this doesn't seem like a scaleable model

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
