### ISSUE TITLE
[FlatList] FlatList when scrolling only 10~30fps in iOS

### ISSUE THREAD

**Issue by Jakevin** [facebook/react-native#14622]
### Description

The item already use PureComponent, but only 10fps~30fps in first scroll #. Have any suggest to fix it?

The data array size is 50 to 300+
```
{
    id:212121231231231231231231,
    title:"Event by Accu"
    time:"2017/06/20 15:00"
    photo:"https://az796311.vo.msecnd.net/userupload/528678acc2df40bebeb32de0f51f2ee5_P440x220.jpg"
}
```
![image](http://g.recordit.co/iBD580bexH.gif)

#### Sample Code

My item

```
class MyListItem extends React.PureComponent {

    _onPress=() => {
            this
                .props
                .onItemClick(this.props.data);
        };

    render() {
                        
        return (
            <TouchableHighlight
                onPress={this._onPress}
            >
                    <View >
                        <Image
                            style={{width:360,height:180}}
                            source={{
                            uri: this.props.photo
                        }}/>
                        
                        <Text
                            style={[
                            styles.text, {
                                fontSize:17,
                                marginTop: 5,
                                marginBottom:5
                            }
                        ]}>{this.props.title}</Text>
                    </View>
            </TouchableHighlight>)
    }
}
```
My FlatList

```
class SampleFlatList extends Component{


    render(){
        return <FlatList    
                data={ this.props.eventList } 
                keyExtractor={ (item, index) => item.id }
                renderItem={ this._renderItem}/>
    }
}

```

### Additional Information

* React: 16.0.0-alpha.12
* React Native version: 0.45.0
* Platform: both
* Development Operating System: mac 10.12.5
* Build tools: xcode & iOS 10.3

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

**Comment by mbashiq** [comment]
@Jakevin Im having an issue with flattest when using 2 of them inside a scrollview. But this issue is not there when I only use one FlatList.
![19398875_1276113855834661_1855043876_n](https://user-images.githubusercontent.com/10618499/27431922-d0f338e8-576b-11e7-8eb4-9f0e5ab4953a.gif)
The blue and purple rows are the FlatLists and you can see the fps drop as I scroll :(
 #14531
