### ISSUE TITLE
FlatList/VirtualizedList bug on the onViewableItemsChanged callback

### ISSUE THREAD

**Issue by javiercr** [facebook/react-native#14629]
### Description

On react-native `0.45.1` the `onViewableItemsChanged` callback is invoked with rows that haven't changed its visibility as part of the `changed` key with `isViewable` set to false.

On the next invocation of the callback those rows appear as visible again. This behaviour was not present in RN `0.44.0` from what I could test.

### Reproduction Steps

1. `git clone https://github.com/javiercr/rn-flatlist-bug-showcase.git`
2. `cd rn-flatlist-bug-showcase && yarn install`
3. `yarn run ios`
4. Enable Remote Debugging (cmd + D)
5. Open console on debugger 
5. Scroll the list and notice how items that are visible are included on `changed` for the `onViewableItemsChanged` callback with `isViewable` set as false.

![rnbugflatlist](https://user-images.githubusercontent.com/855995/27328469-8bad30d2-55b2-11e7-98ae-2a97ff07a6eb.gif)

#### Sample Code

https://github.com/javiercr/rn-flatlist-bug-showcase/blob/master/App.js

### Solution

The behavior for `onViewableItemsChanged` should be the same than in 0.44.0 where rows only get included in the `changed` key when their visibility has actually changed.

### Additional Information

* React Native version: `0.45.1`
* Platform: iOS, not tested in Android yet.
* Development Operating System: macOS
* Build tools: XCode

**Comment by javiercr** [comment]
I just tested this with the latest [v0.46.0](https://github.com/facebook/react-native/releases/tag/v0.46.0) and it seems the bug is gone, but I have no idea what could have fixed this.

I'm leaving this open for the people who are stuck with v0.45.x

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
