### ISSUE TITLE
react.children.only expected to receive a single reactelement child

### ISSUE THREAD

**Issue by lenmoyouziJiangjun** [facebook/react-native#14625]
`var Main = React.createClass({
    getInitialState(){
        return {
            selectTab: 0,
        }
    },
    render(){
        return (
            <TabBarIOS>
                <TabBarIOS.Item
                    title="home"
                    icon={{uri: 'tabbar_home', scale: 2}}
                    onPress={()=>this.tabBarClick(0)}
                    selected={this.state.selectTab===0}
                >

                </TabBarIOS.Item>
                <TabBarIOS.Item
                    title="discover"
                    icon={{uri: 'tabbar_discover', scale: 2}}
                    onPress={()=>this.tabBarClick(1)}
                    selected={this.state.selectTab===1}
                >

                </TabBarIOS.Item>
       </TabBarIOS>
        [)](url)
    },

    tabBarClick(index){
        this.setState({
            selectTab: index,
        })
    }
});`
·
when I delete selected={this.state.selectTab===0} it`s ok 。
`

**Comment by ItsNoHax** [comment]
Somewhere in one of your component's render method you have:

```
<View>
</View>
<View>
</View>
```

Where you should only have 1 parent view:
```
<View>
    <View>
    </View>
<View>
```

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
