### ISSUE TITLE
[iOS] app hang when include CJK characters multiline TextInput 

### ISSUE THREAD

**Issue by yangyi** [facebook/react-native#14628]
### Description

when using CJK chars in multiline TextInput, app hangs, and unresponsive.

### Reproduction Steps

paste sample code in any page of your app, and navigate to the page
#### Sample Code

```javascript
export default class App extends React.Component {
  render() {
    const text = <Text>王者荣耀</Text>
    return (
      <View style={styles.container}>
        <TextInput multiline>
          {text}
        </TextInput>
      </View>
    );
  }
````

I also provide an git repo https://github.com/yangyi/demoinput

### Solution

I replace NaN with CGFLOAT_MAX, that resolve the issue, but I'm not sure why this happens, and the solution is not well tested.

the commit is here

https://github.com/yangyi/react-native/commit/aadebd796d398d88ff26ad4027349876bc9de295

### Additional Information

* React Native version: v0.45.1
* Platform: iOS
* Development Operating System: macOS
* Build tools: XCode Version 8.3.2 (8E2002)

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
