### ISSUE TITLE
what's the different between command react-native and create-react-native-app

### ISSUE THREAD

**Issue by yhjhoo** [facebook/react-native#14659]
I have seen these two commands on the tutorial. However, what's the different? why two different commands to create project?
https://facebook.github.io/react-native/docs/getting-started.html#content

**Comment by hramos** [comment]
The Caveats section explains the main differences. Basically, with CRNA you won't need to install or use Android Studio or Xcode. You simply write JavaScript code, and run it within the Expo app on a device. 

Check out the FAQ for CRNA at https://github.com/react-community/create-react-native-app#faqs, copied here for convenience:

## What API specification should I be looking at while developing?

Apps made with Create React Native App support everything in the Components and APIs sections of the React Native Documentation.

Apps made with Create React Native App also support most of the JavaScript-to-Native APIs provided by the Expo SDK, since they are loaded by the Expo app.

## What are the limitations of Create React Native App?

The main limitation of a Create React Native App project is that it must be written in pure JavaScript and not have any dependencies which rely on custom native code (i.e. ones which require running react-native link to work). This allows the projects to load directly on a phone without native compilation, and also means that it's not necessary to install or use Android Studio or Xcode.

## What if I want to write custom native code for my app?

If you're sure that you need custom native code, please read the ejecting guide.

## How do I get my app into the Play Store/App Store?

If you need to build IPAs and APKs for publishing to the App Store and/or Play Store, you can either eject (see above guide) and build them yourself using Xcode and Android Studio, or you can use a service like Expo's standalone app builds to publish your pure JS app.
