### ISSUE TITLE
React Native TextInput in ListView value by state is stuck

### ISSUE THREAD

**Issue by rexjrs** [facebook/react-native#14651]
### Description

State value locks up when scrolling down a ListView and coming back up. I think the Optimization techniques where rows out of screen view "unrender themselves" of the ListView component messes up the TextInput's value property and locks up.

This describes what I mean.

https://www.youtube.com/watch?v=fq7ITtzRvg4&feature=youtu.be

### Reproduction Steps

Set up a listview with some data. Set up a TextInput with dynamic state value property and onChangeText

#### Sample Code
```
                            <TextInput
                                style={styles.commentInput}
                                placeholder="Say something..."
                                placeholderTextColor="gray"
                                underlineColorAndroid="transparent"
                                multiline={true}
                                blurOnSubmit={true}
                                value={this.state["row"+data.id]}
                                onChangeText={(input) => {this.setState({["row"+data.id]: input})}}
                            />
```

See here for full code snippet:
https://stackoverflow.com/questions/44666538/react-native-listview-textinput-locks-up-from-performance-optimization-rendering

### Additional Information

* React Native version: 0.45.1
* Platform: [FILL THIS OUT: Android confirmed. Maybe IOS?EDIT: BOTH confirmed
* Development Operating System: [FILL THIS OUT: MAC

**Comment by rexjrs** [comment]
I've been stuck on this for a week. Anyone got any comments?

**Comment by hramos** [comment]
Does this still reproduce within a FlatList? ListView is deprecated.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
