### ISSUE TITLE
Keyboard hidden TextInput when changing `android/app/src/main/res/values/styles.xml`

### ISSUE THREAD

**Issue by zphhhhh** [facebook/react-native#14663]
### Description

To let the statusBar be transparent in Android, I add the code to `/android/app/src/main/res/values/styles.xml` that is : 
```
<resources>
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="android:windowTranslucentStatus">true</item>
        <item name="android:windowTranslucentNavigation">true</item>
    </style>
</resources>
```
But then in React Native , `Keyboard` hidden the `TextInput` when focusing.
Before adding that `transparent` codes, the `TextInput` is normal.

### Reproduction Steps

1. `react-native init myproject`
2. edit `/android/app/src/main/res/values/styles.xml`
3. `react-native run-android`

It always be here that `Keyboard` hidden the `TextInput` when focusing .

#### Sample Code
```
import React, { Component } from "react";
import { AppRegistry, StyleSheet, Text, TextInput, View } from "react-native";

export default class rn233 extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <TextInput />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F5FCFF"
  },
  welcome: {
    fontSize: 20,
    textAlign: "center",
    margin: 10
  },
});

AppRegistry.registerComponent("rn233", () => rn233);
```

### Additional Information

* React Native version: 0.45.1
* Platform: Android
* Development Operating System: Windows 10 64 bit, 
* Build tools: Android Studio, actually I just use `react-native run-android` , It should be called Android SDK.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
