### ISSUE TITLE
How to install Geolocation on Non create-rn-apps

### ISSUE THREAD

**Issue by MyTotoro** [facebook/react-native#14669]
### Description

Using `navigator.geolocation` instantly crashes the app, this app wasn't created with create-rn-app
so I'm not sure if that's the problem

### Reproduction Steps

I used ignite `https://github.com/infinitered/ignite` to setup the app

#### Sample Code

```
navigator.geolocation.getCugetCurrentPosition(
      (position) => {
    
        console.tron.log('geolocaiton: ' + position.coords.latitude)
        console.tron.log('geolocaiton: ' + position.coords.longitude)
    
        //
        // this.setState({
        //   region: {
        //     latitude: position.coords.latitude,
        //     longitude: position.coords.longitude,
        //     latitudeDelta: 0.02,
        //     longitudeDelta: 0.02
        //   }
        // })
    
      },
      (error) => {
        console.tron.log('mapCoordError: ' + error.message)
        //this.setState({ mapCoordError: error.message })
      },
      {
        enableHighAccuracy: true,
        timeout: 3000,
        maximumAge: 1000
      })
```
### Solution

Is there a way to install it for RN projects that weren't created with create-rn-app? Is that a hard requirement or is there an import I'm missing

### Additional Information

* React Native version: 
```
"react-native": {
       "version": "0.44.2",
```
* Platform: [FILL THIS OUT: iOS, Android, or both?]
Currently testing on Android 6.1
* Development Operating System: 
mac OS

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
