### ISSUE TITLE
Quick Return of InputText With OnChangeText SetState Callback Erases Text on iOS

### ISSUE THREAD

**Issue by thejacobseely** [facebook/react-native#14690]
### Description
I have an onClick listener set up to respond to InputText onChange (in order to validate user input). However, when you enter text quickly on iOS and press the return key, the text that has been entered will disappear and be replaced with the last text entered.

This bug only happens when the text is changed quickly and the text change calls this.setState. If the onChange function does not call this.setState, the text remains as entered. It is also specific to the Enter key only...selecting another TextInput or any other part of the page will not produce the bug.

I have only been able to reproduce the issue on iOS and only on physical devices...the iOS simulator does not seem to have the bug. I would guess this to be due to processing power.

My best guess is that it is a problem with having to rerender both in the onChangeText and on pressing the Return key.

### Reproduction Steps
1. Create an onChangeText callback and trigger for InputText, have the callback function call this.setState().
2. Run on an iOS device (NOT an emulator).
3. Rapidly enter a character or two and press the "Return" button on the keyboard in quick succession.
4. Watch as the characters you just entered disappear.

#### Sample Code
Callback function (called onChangeText):
```
    //Checks the host name the user has inputted to make sure it is valid and unique.
    validateName = (text) =>
    {
      if(name.test(text) !== true)
      {
        this.setState((state) =>
        {
        return {
          name: text,
          nameError: "The host name cannot contain any spaces.",
        };
        });
      }
      else
      {
        this.setState((state) =>
        {
          return {
            name: text,
            nameError: "",
          };
        });
      }
    }
```

TextInput (in render()):
```
<TextInput
    style={styles.textInput}
    autoCapitalize = "none"
    autoCorrect = {false}
    onChangeText={this.validateName.bind()}
    />
```

### Additional Information

* React Native version: v0.44.0
* Platform: iOS
* Development Operating System: macOS
* Build tools: Xcode 8.3.3

**Comment by LAITONEN** [comment]
I am surprised nobody replied. I have the same problem.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
