### ISSUE TITLE
[iOS] [RN-0.44] #import <React/RCTBundleURLProvider.h> doesn't find the file for build configuration other than Debug

### ISSUE THREAD

**Issue by niconistal** [facebook/react-native#14704]
I've been having this issue only when I build, running on simulator works fine.

At this point I tried to pretty much everything suggested to people having the same issue with no luck.
Any ideas what could be happening here?

![8e90f220-e3c0-11e6-9039-7469b6815adf](https://user-images.githubusercontent.com/899855/27493338-8742414c-5817-11e7-9be7-8b7d53845794.png)

**Comment by whatya** [comment]
i got this error too, tried everything, but failed to solve...

**Comment by whatya** [comment]
the 0.44 is ok to run，but 0.45 can not，maybe is the version problem
i solved this by the following command：
rninit init TaxiApp --source react-native@0.44.0;

**Comment by niconistal** [comment]
I'm trying to fix my existing app, which used to run, but suddenly started giving me this issue

**Comment by whatya** [comment]
maybe your react-native was auto updated to the 0.45

**Comment by Eluss** [comment]
What configurations do you have? Are these the ones that came with initialised project, or did you add new configurations manually?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
