### ISSUE TITLE
Add dynamic import to babel-preset-react-native

### ISSUE THREAD

**Issue by tomkel** [facebook/react-native#14716]
[import()](https://github.com/tc39/proposal-dynamic-import) is [stage 3](https://tc39.github.io/process-document/), meaning 
>The committee expects the feature to be developed and eventually included in the standard - Only incremental changes expected

Please add [`babel-plugin-syntax-dynamic-import`](http://babeljs.io/docs/plugins/syntax-dynamic-import/) and [`babel-plugin-dynamic-import-node`](https://github.com/airbnb/babel-plugin-dynamic-import-node) to the babel config.

**Comment by chirag04** [comment]
you can add this in your project's .babelrc?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
