### ISSUE TITLE
[Android build-tools] Problem in compiling

### ISSUE THREAD

**Issue by gjae** [facebook/react-native#14719]
Hi friends! I have a problem with build-tools 25.0.2 I am trying to use airbnb maps but at the moment of compiling the following problem arises:

/home/<user>/Android/Sdk/build-tools/25.0.2/aapt: 20: /home/<user>/Android/Sdk/build-tools/aapt: Syntax error: Unterminated quoted string`` :react-native-maps:processReleaseResources FAILED

    What went wrong:
    Execution failed for task ':react-native-maps:processReleaseResources'.

    com.android.ide.common.process.ProcessException: Failed to execute aapt

    Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output

BUILD FAILED

# PLEASE helpme i have 4 days with this problem
:(

**Comment by HelloEdit** [comment]
Hello 

Can you update your gradle version following [this step](https://developer.android.com/studio/releases/gradle-plugin.html) ?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
