### ISSUE TITLE
[Layout] When using a 'column' flexBox layout for a view, child views of that view do not stretch to fit.

### ISSUE THREAD

**Issue by oveddan** [facebook/react-native#1472]
In standard w3c html/css flexbox layout, you can declare a div with a `column` `flex-direction`, and have children with `flex-grow`, and those children will stretch to the desired proportions to fit the parent with the `column` `flex-direction`.

See the jsfiddle [here](https://jsfiddle.net/8dLt71j4/1/) - The first column has its two child elements appropriately stretching to fit it.

With `react-native`, `flex` is ignored for views within a view that has `flexDirection: 'column'`.  It also ignores `alignItems: 'stretch'` for that view.  You can see an example in a react playground [here](https://rnplay.org/plays/qO-EvA).

**Comment by vjeux** [comment]
Thanks for the repro case, I need to investigate what's going on.

**Comment by oveddan** [comment]
@vjeux I have some time to work on this.  Want me to take a stab?

**Comment by vjeux** [comment]
@oveddan: would be awesome yeah!

**Comment by oveddan** [comment]
:+1:

**Comment by oveddan** [comment]
@vjeux I believe I figured out why this was happening in my repo case - I need to specify the height of the wrapper element.  When I do, the views within that view **do** get stretched vertically to fit.  

See the react-playground [here](https://rnplay.org/apps/TLwBCQ/) - where all I changed was setting the height of the row element.

Not sure if this is really a bug then!

**Comment by brentvatne** [comment]
@oveddan - you can actually avoid setting an explicit height at all.

The problem seems to be this: if a parent does not have flex, this doesn't work.

[Simplified example **with flex: 1** on container](https://rnplay.org/apps/6xdsLA)
[Same example **without flex: 1** on container](https://rnplay.org/apps/hnymjw)

You'll notice that this is **very** similar to the following change:
![web](https://cloud.githubusercontent.com/assets/90494/8172918/f739055a-137a-11e5-8bba-8c566f685687.gif)

So this behaviour is a bit different in that we can't just say `display: flex` on the parent container and make it work, we have to give it a height or flex value, and then that stretches to the full available container size.

**Comment by oveddan** [comment]
@brentvatne you're totally right - that is what's going on.

**Comment by fatuhoku** [comment]
+1 Facing the exact same issue. I don't believe that a fixed height should need to be set for the child to fill its parent.

**Comment by fatuhoku** [comment]
Am I also right in saying that `justifyContent: 'center'` also seems to get ignored?

**Comment by cancan101** [comment]
I think I am seeing a similar issue with (RN `0.13.2`):
```jsx
<View style={{paddingTop: 165, flexDirection: 'row', backgroundColor: 'red', alignItems: 'stretch'}}>
    <View style={{backgroundColor: 'green'}}>
        <Text>Name:</Text>
        <Text>Description:</Text>
        <Text>Tags:</Text>
    </View>
    <View style={{flex: 1}}>
        <TextInput style={{height: 40, borderColor: 'gray', borderWidth: 1}}/>
        <TextInput style={{height: 40, borderColor: 'gray', borderWidth: 1}}/>
        <TextInput style={{height: 40, borderColor: 'gray', borderWidth: 1}}/>
    </View>
</View>
```
![image](https://cloud.githubusercontent.com/assets/51059/10918093/ea9e03ec-8231-11e5-8414-141f13551f23.png)

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/layout-when-using-a-column-flexbox-layout-for-a-view-child-views-of-that-view-do-not-stretch-to-fit

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
