### ISSUE TITLE
In-App Font Size not changing when user adjusts Dynamic Type settings [iOS]

### ISSUE THREAD

**Issue by SteffeyDev** [facebook/react-native#14725]
### Description

With iOS system applications, when the user leaves an app running in the background, opens the Settings app, adjusts the system text size, and returns to the app, all views in the app refresh their text size to meet the new system font size.  This does not occur with apps written using react native, and the app must be restarted for the system font size change to take effect.  Even when forceUpdate() is called on the entire app, it does not update to match the new system font size.

### Reproduction Steps

1. Create a new react native project using `create-react-native-app` or `react-native init`
2. Run the default app on iOS using `npm start` or `react-native run-ios`
3. Take note of the current text size of the template text
4. Navigate the the iOS Settings app, go to General > Accessibility > Larger Text, and change the font size to the largest size
5.  Double tap on the home button, and return to the react native app
6. Note that the text size has not changed
7. Reload the app by restarting it on iOS or using the reload option from the built in developer tools
8. Note that the font size has changed

Following the same process for iOS system apps that properly support accessibility, at step 6 the font size will either already be updated or will update in front of the users eyes through a basic fade animation, depending on how long the app was in the background.

#### Sample Code

The example code used is the default, stock react native template code, and can be run using the instructions above.

### Solution

Listening for changes in the iOS `UIContentSizeCategoryDidChangeNotification` key can notify the react native app of font size changes, and somehow the default <Text> components need to be told to re-render at a native level or re-draw themselves in a way that captures the new system font size.  The solution will depend largely on how accessibility is currently handled by react native.

My current solution is to detect system font size change and inform the user that they will need to restart the app for the changes to take effect, but this is a hassle for the user and is not consistent with the core iOS accessibility standards.

### Additional Information

* React Native version: 0.45
* Platform: iOS
* Development Operating System: macOS
* Build tools: Xcode 8.3.3, iOS 10.3.2
* Not tested on Android, but may have same issue

**Comment by benvium** [comment]
I worked around this by using Native iOS code to reload the app when the `UIContentSizeCategoryDidChangeNotification` was posted.

```obj-c
  [[NSNotificationCenter defaultCenter] addObserver:self 
  selector:@selector(dynamicTextSizeDidChange) 
  name:UIContentSizeCategoryDidChangeNotification object:nil];
} 

- (void) dynamicTextSizeDidChange {
  [self.rootView.bridge reload];
}
```

Not ideal though as the app restarts..

Seems that a better solution would be to use iOS10's new `adjustsFontsForContentSizeCategory` property on UILabel etc.
See https://useyourloaf.com/blog/auto-adjusting-fonts-for-dynamic-type/

Sadly this isn't exposed by RN (as far as I can tell)

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
