### ISSUE TITLE
onLongPress event never trigger with delayLongPress over 1000ms

### ISSUE THREAD

**Issue by XavierColombel** [facebook/react-native#14737]
### Description
I tried to add a longer delay to `onLongPress` event so I used `delayLongPress` parameter to adjust the delay to 3000ms. The problem is over 1000ms of delay the event never trigger.

### Reproduction Steps

Simply create a new projet with a Touchable and a `delayLongPress` parameter over 1000ms.

#### Sample Code

```
export default class touchable extends Component {
  render() {
    return (
      <View style={styles.container}>
        <TouchableHighlight
          onPress={() => console.log("onPress")}
          onLongPress={() => console.log("onLongPress")}
          delayLongPress={1000}
        >
          <View><Text>Press Me</Text></View>
        </TouchableHighlight>
      </View>
    );
  }
}
```

### Additional Information

* React Native version: 0.45.1
* Platform: iOS (emulator)
* Development Operating System: macOS
* Build tools: Xcode Version 8.3.3 (8E3004b)

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by MichaelBorde** [comment]
I have the same issue. I put a timer to check and onLongPress is triggered after more or less 1000ms.
