### ISSUE TITLE
CLI `install` broken on Windows

### ISSUE THREAD

**Issue by rozele** [facebook/react-native#14745]
<details>
  **Issues that do not describe a bug or do not fill out the template below will be closed**

  We use GitHub Issues exclusively for tracking bugs in React Native.

  - If you're looking for help with your code, consider asking on Stack Overflow instead: http://stackoverflow.com/questions/tagged/react-native
  - Want to know more about future plans? Check out the roadmap: https://github.com/facebook/react-native/wiki/Roadmap
  - Have a feature request that is not covered in the roadmap? Submit it here: https://react-native.canny.io/feature-requests

  ## Reporting bugs

  Want to **report a bug**? Please read the bug reporting guidelines: https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#bugs
</details>

### Description

When you run `react-native install <package>`, the command fails to install anything, but still reports success.

### Reproduction Steps
```
>react-native init myapp
>cd myapp
>react-native install react-native-*
```

### Solution

Fix the local CLI implementation.

### Additional Information

* React Native version: 0.45
* Platform: both
* Development Operating System: Windows

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
