### ISSUE TITLE
[ScrollView] responder capture bug

### ISSUE THREAD

**Issue by magicismight** [facebook/react-native#1475]
Tring to captrue the responder of a ScrollView like this.
```javascript
<View
    onStartShouldSetResponderCapture={() => true}
    onMoveShouldSetResponderCapture={() => true}
>
<ScrollView></ScrollView>
</View>
```
The ScrollView inside can`t get the responder and it should not scroll.
But the ScrollView will scroll sometimes.Just sometimes.
Is this a bug?

**Comment by browniefed** [comment]
@magicismight did you figure this out? If anything you should disable scroll with ScrollVies `scrollEnabled` param if you want it to lock scrolling.

**Comment by jcsmesquita** [comment]
+1

**Comment by christopherdro** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

If you'd like you can create an issue on [Product Pains](https://productpains.com/product/react-native).
ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. 

Also, if this issue is a bug, please consider sending a PR with a fix. Thanks!
