### ISSUE TITLE
react-native-cli is not compatible with npm@5

### ISSUE THREAD

**Issue by johndanek** [facebook/react-native#14767]
### Is this a bug report?

Yes

### Have you read the Bugs section of the Contributing to React Native Guide?

Yes

### Environment

1. `react-native -v`: 
```
react-native-cli: 2.0.1
react-native: 0.45.1
```
2. `node -v`:
```
v8.1.1
```
3. `npm -v`:
```
5.0.4
```
4. `yarn --version` (if you use Yarn):
`0.23.2`

Then, specify:

1. Target Platform (e.g. iOS, Android): Whatever the result of `yarn start` is
2. Development Operating System (e.g. macOS Sierra, Windows 10): macOS Sierra
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): Not relevant

### Steps to Reproduce
Perform the first four steps outlined in the Getting Started (https://facebook.github.io/react-native/docs/getting-started.html) guide with a totally fresh React Native project.
1. `npm install -g create-react-native-app`
2. `create-react-native-app AwesomeProject`
3. `cd AwesomeProject`
4. `npm start`

### Expected Behavior

I thought a dev server would run, or I would see the QR code mentioned in the Getting Started guide. I would expect react-native to be compatible with npm 5.0.4 or give instructions as to how to downgrade (not ideal). I wouldn't expect it to just outright break.

### Actual Behavior

```
➜  /Users/foo/TestApp npm start

> TestApp@0.1.0 start /Users/foo/TestApp
> react-native-scripts start

1:54:47 PM: Starting packager...
***ERROR STARTING PACKAGER***

Error: You are using npm version 5.0.4. Please use an npm version that is >= 3.0.0 and < 5.0.0.
1:54:47 PM: Error starting packager: Error: Couldn't start project. Please fix the errors and restart the project.
    at /xdl/src/Project.js:1038:11
    at Generator.next (<anonymous>)
    at step (/Users/foo/TestApp/node_modules/xdl/build/Project.js:1468:191)
    at /Users/foo/TestApp/node_modules/xdl/build/Project.js:1468:361
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! TestApp@0.1.0 start: `react-native-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the TestApp@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/foo/.npm/_logs/2017-06-28T20_54_47_593Z-debug.log
```

### Reproducible Demo

Explained above.

**Comment by hramos** [comment]
This appears to be an issue with npm 5, as the error states. You can try downgrading to npm 4.

**Comment by gi4nks** [comment]
+1

**Comment by floriancargoet** [comment]
You can downgrade npm with: `npm install -g npm@4`

**Comment by ankitpopli1891** [comment]
Quoting @johndanek again, 
>  I would expect react-native to be compatible with npm 5.0.4 or give instructions as to how to downgrade **(not ideal)**

We understand that `react-native` or `react-native-cli` might not be responsible for the bug, but as the naive users, we do expect it to work gracefully. 

It'd be great if someone can explain the issue, rather than just telling us to downgrade. It would not only help us understand the issue, but we might be able to contribute as well. Even if can't, we'll be able to raise the issue in the right repository.

**Comment by otoinsa** [comment]
And there I thought that there is a new way of setting up a React Native project that is less painful; Turns out it will not work out of the box with the latest software and suggests using yarn (which does not work in parity with npm for git based dependencies)...

Please make this step easier for once! :D

**Comment by hramos** [comment]
@ankitpopli1891 I would start by removing the npm version check, and running the test suites and resolving any issues that may pop up. I'm sure the community would appreciate a PR that removes any issues with npm@5.

**Comment by mattop1709** [comment]
downgrade to npm version 4. Works for me!

**Comment by ide** [comment]
A newer version of npm@5 may work as well. Try using npm 5.1.0 for example.

**Comment by ankitpopli1891** [comment]
@hramos happy to give it a go, will do it this weekend :smiley: 
@ide thanks for the update, will try it out. Thanks :+1:

**Comment by leoafarias** [comment]
I got the same error with npm 5.1.0 had to downgrade

**Comment by ankitpopli1891** [comment]
Just an update, tried replicating the issue with `npm 5.2.0` & everything seems to be working fine. :tada: 

---

Still, I tried replicating the issue, downgraded to `npm 5.0.4`, & tried again:

![image](https://user-images.githubusercontent.com/1699793/28246382-4c1c9f32-6a36-11e7-9dde-e01c8630cd8c.png)

Came across https://github.com/facebook/react-native/issues/9312#issuecomment-267927278 & `react-native-git-upgrade`. The former worked for me.

There were a few other things I did:

 - I was still using `react-native-cli@1.0.0`, upgraded it to `2.0.1`. __Should we notify users that a new version of the cli is available, just like `npm` & `yarn` does that? I don't have a clue how can we do that, not even sure if it's shipped with the latest cli version.__ 
 - I had installed `react-native` globally quite some time back. Removed it. Can't say how it impacts all this, but from what I understand, it shouldn't.
 - Used `react-native start` instead of `npm start`. Although the latter is working fine as well.

---

Encountered this somewhere, but can't replicate it again. expo config file wasn't generated.

![image](https://user-images.githubusercontent.com/1699793/28246398-8d8b56d4-6a36-11e7-8a83-a02d8e7984c3.png)

---

Out of curiousness, was the issue fixed somewhere ? or we were doing something wrong ? Or again, looking in the wrong repository :stuck_out_tongue_winking_eye: ?

**Comment by essaji** [comment]
I just installed yarn & everything worked like charm `brew install yarn`

**Comment by iosdev-republicofapps** [comment]
@hramos any idea when this might be fixed?  I'm just starting out with react-native but can't get it to even create an app due to this bug.  I really appreciate react native being free and I want to use it!  :-)  But this feels like a showstopper and npm doesn't seem to be working on a fix nor does react native ... Any ideas?  This is really impacting a lot of people.  I'd be happy to help - any suggestions?  Thanks!

**Comment by iosdev-republicofapps** [comment]
I have react native running with npm 4.6.1, but as newcomer to both node and react native, it makes me a bit nervous to have to depend on a version of npm that's many versions behind the current stable version of npm.  But it is working ... Let me know if I can help!  :-)  BTW, thanks for all you do making react native available for free - not meaning to be a whiner, just frustrated, that's all.  React native is actually pretty awesome, nice work!

**Comment by ide** [comment]
If you're using create-react-native-app, there's at least one known bug with npm 5 (https://github.com/npm/npm/issues/16893) that prevents it from working and there isn't an obvious and simple workaround. Probably the best way to move forward is to submit a PR to npm.

**Comment by agrcrobles** [comment]
It is working fine for me following the steps above using npm@5.4.2 but still getting the this warning:
```
You are using npm version 5.4.2. There may be bugs in this version, use it at your own risk. We recommend version 4.6.1.
```

**Comment by munirulhakim** [comment]
Downgrade to npm 4 with this commad npm install -g npm@4

**Comment by alvinsight** [comment]
Hi,
Do we know if the new minor versions of npm fixed this ?
According to [this](https://github.com/npm/npm/issues/16893#issuecomment-333553026) it looks like it might ?

**Comment by Zhuinden** [comment]
`npm i -g npm@4`

**Comment by ivanslf** [comment]
If you cannot downgrade npm for some reason, install [yarn](https://yarnpkg.com/lang/en/docs/install/).

**Comment by danielheddelin** [comment]
This appears to still be an issue? 8½ months later, new users still cannot follow the recommended getting started guidelines? Perhaps you should just rewrite the instructions a bit if the solution is 1-year-away?

**Comment by iarna** [comment]
npm should handle yarn generated trees gracefully as of `npm@5.7.1` and as such, this should [no longer be an issue](https://github.com/npm/npm/issues/16893#issuecomment-371651919).

**Comment by ivanslf** [comment]
React Native is the only reason I still have yarn installed.

**Comment by danielheddelin** [comment]
Sorry but I'm not following. I am using npm@5.7.1 and getting 

>
*******************************************************************************
ERROR: npm 5 is not supported yet
*******************************************************************************

It looks like you're using npm 5 which was recently released.

Create React Native App doesn't work with npm 5 yet, unfortunately. We
recommend using npm 4 or yarn until some bugs are resolved.

You can follow the known issues with npm 5 at:
https://github.com/npm/npm/issues/16991

*******************************************************************************
>

**Comment by ivanslf** [comment]
You can use yarn to create your project, then you just delete `node_modules` and run `npm install`.

After that, you are ready to go with `npm start`.

**Comment by AtomStar** [comment]
I upgraded to npm 5.7.1 but still get after create-react-native-app  - Step 4 npm start :

```
    npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /...-debug.log
```

**Comment by danielheddelin** [comment]
I do understand that I can use yarn. But if that's mandatory then perhaps the getting started directions should not instruct to use npm - which doesn't work.

**Comment by ivanslf** [comment]
Actually, npm works fine, but there is a hardcoded lock for `npm@5.x`. That lock can be safely updated to accept `npm@5.7.1` or greater now. Or at least it seems like it does.

**Comment by AtomStar** [comment]
@ivanslf what do I need to remove the lock? Would prefer not having to downgrade to npm 4.6.1

**Comment by danielheddelin** [comment]
Doesn't change the fact that new users cannot trust the getting started guide..

**Comment by ivanslf** [comment]
@AtomStar 

> You can use yarn to create your project, then you just delete node_modules and run npm install.
>
> After that, you are ready to go with npm start.

**Comment by jeffvandyke** [comment]
Last night, I was able to use `create-react-native-app` with yarn installed, and `npm start` worked without problems. I did have to update my global `react-native` package, though. I would double-check `npm outdated -g` if there are still issues. (Linux, Manjaro, npm 5.7.1)

**Comment by putrantoinc** [comment]
npm 5.8.0 has no issue as well

**Comment by avinashwigroup** [comment]
@putrantoinc : Can you please tell me how did you install the 5.8.0 version?

**Comment by mikkotikkanen** [comment]
@avinashwigroup `npm install npm -g`
