### ISSUE TITLE
React-Native “scrollTo” behave differently on Android and iOS when ScrollView height is small

### ISSUE THREAD

**Issue by ebaynaud** [facebook/react-native#14760]
### Description

Please consider this example on iOS: https://snack.expo.io/H1AeNGx4W

- On iOS, clicking on the text will but the text to the top because scrollTo({ y: 250 }) scrolls even if end of scrollView is reached.
- On Android, the text doesn't move.

### Reproduction

https://snack.expo.io/H1AeNGx4W

### Solution

No cool solution yet https://stackoverflow.com/questions/44795520/how-to-make-react-native-scrollto-behave-identically-on-android-than-on-ios-wh

### Additional Information

* React Native version: 0.45.0
* Platform: iOS
* Operating System: MacOS
* Dev tools: Xcode

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by wodCZ** [comment]
Reproduced this in react-native v0.50.3.
