### ISSUE TITLE
Add a develop-time check for a correctly-installed React peer

### ISSUE THREAD

**Issue by AndrewIngram** [facebook/react-native#14765]
I've experienced quite a few issues as a developer using React Native via expo and/or create-react-native-app, and based on my browsing past issues on this repo, I don't seem to be alone.

The root cause seems to be that coming to React Native via this route, I've been utterly unaware of how strictly React Native is coupled to a specific React version. So every time I upgrade dependencies, *something* breaks in a truly opaque way.

A possible solution is to have React Native perform a debug/dev-time check at startup to assert that the installed version of React matches the version specified in peerDependencies, and warn if it doesn't (and ideally provide information as to why this is important).

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
