### ISSUE TITLE
 :react-native-fbsdk:prepareComAndroidSupportCardviewV72500Library Failed(java.lang.NullPointerException (no error message))

### ISSUE THREAD

**Issue by sachinsinghh** [facebook/react-native#14782]
Starting JS server...
Building and installing the app on the device (cd android && ./gradlew installDebug)...
Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:react-native-fbsdk:preBuild UP-TO-DATE
:react-native-fbsdk:preReleaseBuild UP-TO-DATE
:react-native-fbsdk:checkReleaseManifest
:react-native-fbsdk:preDebugAndroidTestBuild UP-TO-DATE
:react-native-fbsdk:preDebugBuild UP-TO-DATE
:react-native-fbsdk:preDebugUnitTestBuild UP-TO-DATE
:react-native-fbsdk:preReleaseUnitTestBuild UP-TO-DATE
:react-native-fbsdk:prepareComAndroidSupportAnimatedVectorDrawable2500Library UP-TO-DATE
:react-native-fbsdk:prepareComAndroidSupportAppcompatV72500Library UP-TO-DATE
:react-native-fbsdk:prepareComAndroidSupportCardviewV72500Library

FAILURE: Build failed with an exception.

* What went wrong:
java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
