### ISSUE TITLE
iOS Release build with Typescript: bundling failed

### ISSUE THREAD

**Issue by thanhtr** [facebook/react-native#14809]
### Environment

* react-native: v0.41.2
* node: v7.10.0
* npm: v4.2.0
* Platform: iOS
* OS: macOS Sierra 10.12
* Xcode: v8.3.3
* Typescript: v2.3.4

### Steps to Reproduce

* Run `react-native run-ios --configuration Release`

### Problems:

* Build succeeded but app crash immediately on launch

### Details:

Cannot find entry file index.ios.js in any of the roots when bundling command run. From the log I can see:

```bash
node /Users/tungtrinh/Projects/doog-app/node_modules/react-native/local-cli/cli.js bundle --entry-file index.ios.js --platform ios --dev false --reset-cache --bundle-output /Users/tungtrinh/Projects/doog-app/ios/build/Build/Products/Release-iphoneos/doog.app/main.jsbundle --assets-dest /Users/tungtrinh/Projects/doog-app/ios/build/Build/Products/Release-iphoneos/doog.app
```

The entry file should be artifacts/index.ios.js as that's my typescript compiled source, which I also specify in AppDelegate.m
```
jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"artifacts/index.ios" fallbackResource:nil];
```

I'd like to know if there's anyway to achieve the correct entry-file for bundling without running manually the command first? I'm trying to setup fastlane for the project.

Thank you very much

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
