### ISSUE TITLE
ScrollView does not show its content properly with some styling

### ISSUE THREAD

**Issue by luqiuyuan** [facebook/react-native#14815]
### Is this a bug report?

Yes

### Have you read the Bugs section of the Contributing to React Native Guide?

Yes

### Environment

1. `react-native -v`: 
react-native-cli: 2.0.1
react-native: 0.45.1

2. `node -v`:
v8.1.2

3. `npm -v`:
5.0.3

4. `yarn --version` (if you use Yarn):
not use yarn

Then, specify:

1. Target Platform (e.g. iOS, Android):
iOS and Android

2. Development Operating System (e.g. macOS Sierra, Windows 10):
macOS Sierra

3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant):
Xcode 8.3.3
Android Studio 2.3
iOS version 10.3.2
Android SDK version 23

### Steps to Reproduce

1. Create a new RN project with react-native init APP
2. Replace the initial codes withe the codes below (The codes might seem unnecessarily complicated, but it was extracted and simplified from a real project as a minimal version to reproduce the issue.):

```
import React, { Component } from 'react';
import {
  AppRegistry,
  Text,
  View,
  ScrollView
} from 'react-native';

export default class App extends Component {
  render() {
    return (
      <View style={{flex:1, paddingTop:50}}>
        <ScrollView contentContainerStyle={{borderWidth:1, borderColor:'red'}}>
          <View style={{flexDirection:'row'}}>
            <View style={{alignItems:'flex-start', backgroundColor:'gray', padding:20}}>
              <View>
                <Text>
                  {'\n'}
                </Text>
              </View>
            </View>
          </View>
          <View style={{height:50}} />
          <View style={{flexDirection:'row'}}>
            <View style={{alignItems:'flex-start', backgroundColor:'gray', padding:20}}>
              <View>
                <Text>
                  row 2
                </Text>
              </View>
            </View>
          </View>
        </ScrollView>
      </View>
    );
  }
}

AppRegistry.registerComponent('App', () => App);
```

3. Run the project on iOS or Android

### Expected Behavior

The codes above simply show two rows in a scroll view. In the first row, it shows a Text component with a linefeed '\n', while in the second row, it shows a Text component with a string 'row 2'.

The expected behaviour is shown as the screenshot below:

![img_0280](https://user-images.githubusercontent.com/27582026/27814817-4765ca9c-604d-11e7-9594-af6b784a2242.PNG)

Where the red border shows the border of the content container of the scroll view.

### Actual Behavior

The actual behaviour is shown below in order of iOS and Android:

![img_0277](https://user-images.githubusercontent.com/27582026/27814386-f63216e2-6049-11e7-8467-67d9fe74d4f6.PNG)

![screenshot_2017-07-03-23-22-29](https://user-images.githubusercontent.com/27582026/27814973-97fd2f80-604e-11e7-8e91-0346fd19e868.jpg)

As you can see, the second row is kicked out of the content container of the scroll view on iOS. On Android, the second row does not even show at all.

### Reproducible Demo

I created an expo demo to show the issue. Just scan the QR code and you will see the issue on the first screen.

https://snack.expo.io/By2lZquNZ

### Notes

I have some notes here to help relieve the work of debugging:

1. Replacing the linefeed '\n' with empty string, the issue remains.
2. In the first row, replacing the linefeed '\n' with any other non-empty string will get rid of this issue.
3. Removing flexDirection:'row' or alignItems:'flex-start' from the first row will get rid of this issue.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by vincenthub** [comment]
Hi @luqiuyuan ,
try this.


 <ScrollView contentContainerStyle={{borderWidth:1, borderColor:'red'}}>
    <View> <------ Add this
        <View style={{flexDirection:'row'}}>
            <View style={{alignItems:'flex-start', backgroundColor:'gray', padding:20}}>
              <View>
                <Text>
                  {'\n'}
                </Text>
              </View>
            </View>
        </View>
    </View> <------ Add this
</ScrollView>
