### ISSUE TITLE
Could not get unknown property 'repositoryUrl' for project ':ReactAndroid'

### ISSUE THREAD

**Issue by SudoPlz** [facebook/react-native#14810]
Hi,

I'm getting that error when trying to [build the RN module from source](https://facebook.github.io/react-native/docs/android-building-from-source.html).

Apparently that's a problem caused by [this line](https://github.com/facebook/react-native/blob/4cff039d78828487009e7832ed54125b181bbbab/ReactAndroid/release.gradle#L15).

Vaiden seems to have a solution for that error as explained [here](https://stackoverflow.com/questions/43967489/could-not-get-unknown-property-repositoryurl-for-project).

I'll create a pull request today.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
