### ISSUE TITLE
view is not render when using surfaceview in some android phone

### ISSUE THREAD

**Issue by luhui** [facebook/react-native#14818]
### Is this a bug report?

YES

### Have you read the Bugs section of the Contributing to React Native Guide?

YES

### Environment

1. `react-native -v`: 
    react-native-cli: 2.0.1
    react-native: 0.45.1
2. `node -v`:
    v8.0.0
3. `npm -v`:
    5.0.4
4. `yarn --version` (if you use Yarn): No

Then, specify:

1. Target Platform (e.g. iOS, Android):
     Android
2. Development Operating System (e.g. macOS Sierra, Windows 10): 
    macOS Sierra
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant):
    compileSdkVersion 23
    buildToolsVersion 24.0.1
    react-native-cli (2.0.1) to build apk

### Steps to Reproduce
1. Write a simple NativeUIComponent for surface view
2. write a code like below

`index.js`
```js

export default class SampleApp extends Component {
  render() {
    return (
      <View style={styles.container}>
        <SurfaceView style={StyleSheet.absoluteFill}/>
        <PopupWindow />
      </View>
    )
  }
}

const styles = StyleSheet.create({
//   container: { //error style with flexbox
//     flex: 1,
//     backgroundColor: 'red'
//   },
//   container: { //error style with shadow + absolute
//       ...StyleSheet.absoluteFillObject,
//       shadowColor: 'black',
//   }
  container: StyleSheet.absoluteFillObject
})

```

PopupWindows.js
```js
export default class PopupWindow extends Component {
  state = {
    show: false
  }
  componentDidMount() {
    setTimeout(() => {
      this.setState({
        show: true
      })
    }, 3000)
  }
  render() {
    console.log('render ' + this.state.show)
    return this.state.show ? (
      <View style={StyleSheet.absoluteFill}>
        <View style={styles.container}>
          <TouchableWithoutFeedback onPress={() => {
              console.log('on click')
              this.setState({
                show: false
                }, () => setTimeout(() => this.setState({show: true}), 3000)
              )}
            }>
            <View>
              <Text style={styles.text}>
              "Hi a Text"
              </Text>
            </View>
          </TouchableWithoutFeedback>
        </View>
      </View>
    ) : null
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  text: {
    color: 'white',
    width: 300,
    height: 240,
    textAlign: 'center',
    backgroundColor: 'orange',
    borderRadius: 10,
  }
})
```

### Expected Behavior

PopupWindow is shown with all test style (relative, absolute, absolute with shadow)

### Actual Behavior

PopupWindows is not being shown when use the style with relative, absolute with shadow.

It is not the same when run in different phone. Here is the record for my testing

| Phone         | System ver.| Result    |
| --------------|:----------:| ----------:|
| Nexus 5       | 5.1.1      | pass       |
| Nexus 6P      | 6.0.1      | pass       |
| Redmi 3x      | 6.0.1      | fail       |
| Galaxy Note 3 | 5.0        | fail       |
| EVA-AL00      | 7.0        | pass       |

### Reproducible Demo

See demo and readme for more detail:

https://github.com/luhui/RNSurfaceViewIssue

**Comment by luhui** [comment]
Simply add a `onLayout` listener to a view also cause this problem

```js
export default class SampleApp extends Component {
  render() {
    return (
      <View 
      style={StyleSheet.absoluteFill}
      onLayout={() => {}}> // PopupWindow will not be shown if we set this line
        <SurfaceView style={StyleSheet.absoluteFill}/>
        <PopupWindow />
      </View>
    )
  }
}
```

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
