### ISSUE TITLE
TextInput right padding is ignored on focus when changing border color on Android

### ISSUE THREAD

**Issue by davidlongest** [facebook/react-native#14814]
### Is this a bug report?

Yes

### Have you read the Bugs section of the Contributing to React Native Guide?

Yes

### Environment

1. `react-native -v`:
```
react-native-cli: 2.0.1
react-native: 0.45.1
```
2. `node -v`: `v7.7.2`
3. `npm -v`: `4.1.2`
4. `yarn --version` (if you use Yarn): `N/A`

Then, specify:

1. Target Platform (e.g. iOS, Android): Android
2. Development Operating System (e.g. macOS Sierra, Windows 10): macOS Sierra 10.12.5
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): Android Studio 2.3.2. Compile SDK 23. Build tools 23.0.1

### Steps to Reproduce

Using the [example project](https://snack.expo.io/ByXLxEOV-)...
1. Note the padding on the right of the two text views
2. Tap or click the second text input
3. Note the text gets flushed to the right
4. Switch focus between the two text inputs
5. Note that text stays flushed to the right
6. Input a single character
7. Note that the padding has been restored on the right
8. Switch focus between the text inputs
9. Note that the text input that had the character input still has right padding

Editing the project to remove the border color from the `focused` style will cause the application to not show this behavior.

### Expected Behavior

When setting a border color without a border width to a TextInput should not cause any visible changes. If having a border color set without setting a border width is bad practice, then a console warning should be emitted.

### Actual Behavior

Changing the border color on a TextInput focus on Android will cause right padding to be ignored until a character is typed into the TextInput.

### Reproducible Demo

https://snack.expo.io/ByXLxEOV-

**Comment by davidlongest** [comment]
Still occurs on react-native 0.46.0

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
