### ISSUE TITLE
ASK about FBSDKPackage

### ISSUE THREAD

**Issue by pisangGoreng** [facebook/react-native#14816]
Hi, im have some trouble about react-native. when im run react-native run-android. its show error about: 
`error: constructor FBSDKPackage in class FBSDKPackage cannot be applied to given types;
            new FBSDKPackage(),
            ^
  required: CallbackManager
  found: no arguments
  reason: actual and formal argument lists differ in length
1 error
:app:compileDebugJavaWithJavac FAILED
`

any suggest to solve this? thanks

**Comment by asgvard** [comment]
Hi,

This issue is definitely related to "react-native-fbsdk" package and not to react-native itself. And it's documentation clearly says that you have to pass "mCallbackManager" into a FBSDKPackage constructor: [Docs](https://github.com/facebook/react-native-fbsdk#3-configure-native-projects).
That's exactly what the error says, "required: CallbackManager, found: no arguments".

**Comment by lwiecek** [comment]
Take a look at `getPackages` function in `MainApplication`. Make sure that `new FBSDKPackage()` is not on the list before  `new FBSDKPackage(mCallbackManager)`. In my case I had it listed twice and that was breaking the build.
