### ISSUE TITLE
When create jsbundle, how to convert image to base64 instead of --asset-dest 

### ISSUE THREAD

**Issue by hellozhangran** [facebook/react-native#14821]
```
react-native bundle --entry-file ./src/pages/profile/profile.ios.js --platform ios --dev true --bundle-output ./ios/bundle/profile.test.bundle --assets-dest ./ios/bundle"
```

i use up command to create a bundle file, But, is there anyway to convert the image to base4 and bundle into jsbundle file 

THANKS

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
