### ISSUE TITLE
expose bridge.dispatchBlock as public method

### ISSUE THREAD

**Issue by gre** [facebook/react-native#14822]
https://github.com/facebook/react-native/blob/403f3560826a2c121d225a527c1cdc07c90a571f/React/Base/RCTBridge%2BPrivate.h#L109

this should be in Bridge public interface IMO.

there are usecase where you want to execute things in the JS thread and this `bridge.dispatchBlock` allows it.
[I'm porting code (gl-react-native) that used to do `executor executeBlockOnJavaScriptQueue`](https://github.com/gre/gl-react/commit/c3a09a7f3f5725ce8ce9d53190b38b0f5b5d1be5#diff-a49448c82a6ffa443941c8441f76c55bL66) but since the javaScriptExecutor is no longer exposed I have found this alternative `dispatchBlock` – however I currently need to `#import "RCTBridge+Private.h"` which I guess is bad

**Comment by gre** [comment]
(if you think this is correct usecase I can provide a PR for this)

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
