### ISSUE TITLE
If FlatList rows>100,IOS drop frame more than ANDROID when scroll.

### ISSUE THREAD

**Issue by gezichenshan** [facebook/react-native#14831]
If FlatList rows>100,IOS drop frame more than ANDROID when scroll.

**Comment by Ehesp** [comment]
Please show a code example.

**Comment by gezichenshan** [comment]
`...
import Row from './row'
import Store from './store'
import Footer from './footer'
export default class CustomComponent10 extends Component {
    renderContent(){
        if(Store.isInit){
            if(Store.files.length>0){
                return (
                    <View style={{flex:1}}>
                        {this.renderList()}
                    </View>
                )
            }else{
                return (
                    <ScrollView
                        refreshControl={
                          <RefreshControl
                            refreshing={Store.refreshing}
                            onRefresh={this._onLoadFromCloud}/>
                        }
                        contentContainerStyle={{flex:1,justifyContent: 'center',alignItems:'center'}}
                        >
                        <View style={{flex:1,justifyContent: 'center',alignItems: 'center'}}>
                            <MinicloudIcon name='empty' style={{fontSize:100,color:'#999'}}/>
                            <View style={{flexDirection:'row'}}>
                                <Text style={{color: '#999',justifyContent: 'center',height:30}}>
                                        empty
                                </Text>
                            </View>
                        </View>
                    </ScrollView>
                )
            }
        }
        return null 
    }
    render() { 
            return (               
                <View style={{flex:1,backgroundColor: '#FFFFFF'}}>
                            {this.renderContent()}
                </View>
            )
    } 
    _onLoadFromCloud() {
        Store.loadFromCloud()
    }
    //渲染列表
    renderList() {  
        return(
            <FlatList
                keyExtractor={item=>item.id}
                ListFooterComponent={Footer}
                refreshControl={
                  <RefreshControl
                    refreshing={Store.refreshing}
                    onRefresh={this._onLoadFromCloud}/>
                }
                getItemLayout={(data, index) => (
                  {length: 55.5, offset: 55.5 * index, index}
                )}
                data={Store.files}
                renderItem={({item,index}) => <Row file={item} store={Store} index={index}/>}
                style={{paddingBottom:Store.dataLength>1?0:30}}/>
        )
    }
}`

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
