### ISSUE TITLE
iOS TextInput color does not change with re-render

### ISSUE THREAD

**Issue by trblandford4** [facebook/react-native#14842]
### Is this a bug report?

Yes

### Have you read the Bugs section of the Contributing to React Native Guide?

Absolutely

### Environment

1. `react-native -v`: `react-native-cli: 2.0.1 react-native: 0.45.1`
2. `node -v`: `v7.7.2`
3. `npm -v`: `4.1.2`

1. Target Platform (e.g. iOS, Android): **iOS**
2. Development Operating System (e.g. macOS Sierra, Windows 10): **macOS Sierra**

### Steps to Reproduce

1. Create a TextInput and a Button.
2. Create a StyleSheet with two separate and distinguishable styles for the TextInput
3. Create a state boolean to select between the styles 
4. Create a style variable that selects between the styles based on state var from step 3.
5. Create a button with a function that set's the state to change the TextInput's style onPress
6. Click button
7. Watch iOS not work. 😭 

### Expected Behavior

All style changes (color, backgroundColor, etc.) are applied to TextInput when the component is re-rendered after a state change.

### Actual Behavior

TextInput text color changes after first button press, but does not change on subsequent presses. 
However, all other styling changes are applied as the component re-renders.

### Reproducible Demo

https://snack.expo.io/SJKDa6q4Z

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by EyalSi** [comment]
It seems like an issue of iOS 11.
checkout @shergin comment at https://github.com/facebook/react-native/issues/16200

**Comment by joelandplus** [comment]
Got this problem in my iOS 11, not sure about previous iOS.
