### ISSUE TITLE
[0.46] multi-ScrollView does not work in Android

### ISSUE THREAD

**Issue by bingfj2008** [facebook/react-native#14849]
### Is this a bug report?

Yes (Maybe?)

### Environment

1. `react-native -0.46`:
2. `node -v`:
3. `npm -v`:
4. `yarn --version` (if you use Yarn):

Then, specify:

1. Target Platform (e.g. iOS, Android):  Android 
2. Development Operating System (e.g. macOS Sierra, Windows 10): Windows 7
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): SDK 25

### Steps to Reproduce

(Write your steps here:)

Use 「ScrollView」together like this:
...
`<ScrollView>` //  The First Scroll View 
&nbsp;&nbsp;&nbsp;&nbsp;`...`
&nbsp;&nbsp;&nbsp;&nbsp;`<View>`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<ScrollView>` //  The Second Scroll View
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`...`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`</ScrollView>`
&nbsp;&nbsp;&nbsp;&nbsp;`</View>`
&nbsp;&nbsp;&nbsp;&nbsp;`...`
`</ScrollView>`

and In  IOS, these two Scroll View can scroll as well,
but In Android, only the first scroll can scroll, the second scroll is freeze.

Is that correct ?? 

Please help !!!!!!

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

example project is here -> https://snack.expo.io/ByUkGrs4b

**Comment by hramos** [comment]
Is this supposed to work? Nesting scroll views does not seem like a good idea.

**Comment by HofmannZ** [comment]
@hramos Two scroll views in the same direction is definitely not a good idea, but a horizontal scroll view inside a vertical scroll view is quite common 😌

**Comment by bingfj2008** [comment]
@hramos In my case what the project I doing now, I have to use the Scroll View like this. So have any solution to fix this or to instead of this?

**Comment by bingfj2008** [comment]
@hramos Unfortunately,  in my case what the project I doing now, i have to use the Scroll View like this. So have any solution to fix this or to instead of this?

**Comment by hramos** [comment]
Right - I would not expect two nested, vertically scrolling views to work well together. In the Snack posted here, it seems like it is working as you would expect - the parent scrollview is the one handling the vertical swipe gestures.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by arminsal1** [comment]
@bingfj2008 Did you find any solution or workaround? I'm trying to do the same thing

**Comment by tuncaulubilge** [comment]
#18299 aims to fix this issue on Android 21 and above.
