### ISSUE TITLE
autoCapitalize setting does not default to 'sentences' on Android

### ISSUE THREAD

**Issue by jkdf2** [facebook/react-native#14846]
### Is this a bug report?

Yes

### Have you read the Bugs section of the Contributing to React Native Guide?

Yes

### Environment

1. `react-native -v`:
```
react-native-cli: 2.0.1
react-native: 0.45.1
```

2. `node -v`:
```
v8.0.0
```

3. `npm -v`:
```
5.0.4
```

4. `yarn --version` (if you use Yarn):
```
0.24.6
```

Then, specify:

1. Target Platform (e.g. iOS, Android): Android
2. Development Operating System (e.g. macOS Sierra, Windows 10): macOS Sierra v10.12.5
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): `Nexus_5X_Android_7.1`

### Steps to Reproduce

1. Create a `TextInput` component without specifying `autoCapitalize`

### Expected Behavior

I would expect both iOS and Android to autoCapitalize between sentences as that is the stated default in the documentation.

### Actual Behavior

Only iOS autoCapitalizes between sentences. Android does not.

### Reproducible Demo

Very, very simple to reproduce:

https://snack.expo.io/rkEgLks4-

You'll notice that by default the iOS keyboard autocaps between sentences and the Android keyboard does not.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
