### ISSUE TITLE
Invalid character: '`' - backticks not supported in JSX anymore?

### ISSUE THREAD

**Issue by fgrs** [facebook/react-native#14850]
with
`let row = { title: "Take photo of ${document}" }`
`let document = "passport"`

I used to be able to use
`<Text>{eval('``' + row.title + '``')}</Text>`

(for some reason backticks are shown twice in this wysiwyg)

but now I get the following error
`Invalid` character: '``'

Anybody else with similar issue?

### Environment

react-native-cli: 1.0.0
react-native: 0.46.0
node: v6.10.0
npm: 3.10.10
yarn: 0.24.6

Platform: Android
OS: Windows
Android Studio

1. `react-native -v`:
2. `node -v`:
3. `npm -v`:
4. `yarn --version` (if you use Yarn):

### Steps to Reproduce

1. react-native run-android
2. navigate to the controller that has `<Text>{eval('``' + row.title + '``')}</Text>` in it

### Expected Behavior

parsing template literals

### Actual Behavior

red error page with
'Invalid character: '`'
at the top

Edited: It works with Remote Debugger turned on

**Comment by brentvatne** [comment]
Hi! Please provide a Snack example for future bug reports as suggested in the issue template. I re-created this on Snack here: https://snack.expo.io/SyBvv56VZ

Notice that it works on iOS and not on Android. As you noted, it also works with the Remote Debugger enabled. This is because the JavaScript engine is different in each of those scenarios and supports different features. iOS uses the latest version of JavaScript Core (JSC) that is included in the OS, Android uses a three-year old version of JSC that is included in React Native, and Chrome uses V8. [Work is being done to update JSC for React Native Android](https://github.com/SoftwareMansion/jsc-android-buildscripts), and when that's done this feature should be there. For now, you can't eval template strings. It works when you don't use eval because it is transpiled by Babel so it doesn't actually run the template string code.

**Comment by angrycans** [comment]
me too

let data = { storeName: "xxxx松哥的杂货铺" };
		let str = "${data.storeName}aaa";
		eval("s=``" + str + "``")

		console.log(s);

Remote Debugger turned on ok
Remote Debugger turned off  Invalid character: '`'

**Comment by angrycans** [comment]
let data = { storeName: "xxxx松哥的杂货铺" };
    let str = "${data.storeName}";
    eval("s=`" + str + "`")

    console.log(s);
