### ISSUE TITLE
set borderRadius topLeft and bottomLeft affects the view displaying

### ISSUE THREAD

**Issue by Creemli** [facebook/react-native#14862]
### Is this a bug report?
* Yes

### Environment

1. `react-native -v`: 0.46.0
2. `node -v`: 8.0.0
3. `npm -v`: 5.0.0
4. `yarn --version` (if you use Yarn): 0.24.4

Then, specify:

1. Target Platform (e.g. iOS, Android): IOS
2. Development Operating System (e.g. macOS Sierra, Windows 10): macOS simulator iphone6sPlus
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): xcode

### Steps to Reproduce

(Write your steps here:)

1. react-native init [ProjectName]
2. add the following code to the render method
```
// if set height to 36, it works well
<View style={{width: 100, height: 35, borderTopLeftRadius: 18,borderBottomLeftRadius: 18, backgroundColor: 'blue'}}/>
```
3. hit run in xcode

### Expected Behavior
![image](https://user-images.githubusercontent.com/5566981/27907468-5ab624a0-627a-11e7-8264-66a1680c6324.png)

(Write what you thought would happen.)

### Actual Behavior
![image](https://user-images.githubusercontent.com/5566981/27907448-407d695e-627a-11e7-83c0-c788090816d3.png)

You can try it everywhere in your RN project. And the IOS simulator must be iphone6sPlus.

Updated: If we set the height to an `even number`, it works well.

**Comment by Creemli** [comment]
@brentvatne  Hi brentvatne, I create a new issue to describe this, and it exists after I have tried in different react-native package version.
I also read the source code in RCTView.m and the others, but i cannot find the reason.

**Comment by Creemli** [comment]
Hi, anyone who can help to check the render code of View?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by patw0929** [comment]
I got same issue when using React Native 0.51.0.
As the updated workaround, if I set the height to an even number, it works.
