### ISSUE TITLE
Automated regression testing

### ISSUE THREAD

**Issue by pokey** [facebook/react-native#14864]
I've taken a couple swings at react native over the past couple years, and every time I do, I run into some recent issue that results in react native not working out-of-the-box when following the getting-started guide.  I don't remember which issue it was the past couple times I tried, but this time around I've hit both #14838 and #14767.  Are there not regression tests, and if there are, is there no automated check to ensure that they pass before merging to master / cutting a release?

Beyond the obvious confusion / frustration this can cause a newbie, I imagine that it probably leads to a reluctance on the part of existing users of the framework to upgrade.  For my part, I'll be hesitant to upgrade RN for fear something will break.

I realize this is pre-1.0 software, but it's been pre-1.0 for more than 2 years, and is widely used.  Maybe it's time to put in place a set of regression tests that are automatically enforced prior to merge / release?

**Comment by otoinsa** [comment]
I've also noticed this in the past year I've been working with RN; so I've grown very cautious of the platform.

I would be really cool if it worked as it should, but I guess we're back to the respective IDE's and programming languages for each of the major mobile platforms.

**Comment by pvinis** [comment]
@otoinsa kind of bitter response.
@pokey i agree, there should be some testing for regressions. these bugs in new releases are a pain to fix, and mess up the ci/cd that we have set up.

**Comment by pokey** [comment]
@pvinis Ok, so there is ci/cd that enforces various tests before release / merge to master, then?  So the issue is that the tests that are already in place and automatically enforced just need to be more extensive?

**Comment by pvinis** [comment]
no no. I mean the bugs mess with my ci/cd I have for my project in react native. when I need to do manual steps like the config.h problem, my server cannot build automatically and I need to intervene. I have no idea what kind of testing they have from Facebook for react native, but I agree we should have some that catch these upgrade problems.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by pvinis** [comment]
i would say this issue is good to stay around, because otherwise it will just get forgotten, and more people will complain for the same problems.
