### ISSUE TITLE
Animated extractOffset w/ non-settled spring doesn't stop animation before setting new value

### ISSUE THREAD

**Issue by browniefed** [facebook/react-native#14877]
### Is this a bug report?
Yes.

### Have you read the Bugs section of the Contributing to React Native Guide?
Yep.

### Environment

react-native-cli: 2.0.1
react-native: 0.45.1

Then, specify:

1. iOS/Android
2. macOS El Capitan

### Steps to Reproduce

1. Create drag animation that uses Animated.spring
2. In onPanResponderGrant call extractOffset
3. Before spring settles press/drag

### Expected Behavior

Nothing should happen as the drag didn't go anywhere

### Actual Behavior

Behavior when pressing before spring animation completes
![](http://i.imgur.com/BlsLxLn.gif)

Behavior when animation completes then press/drag happens
![](http://i.imgur.com/inKJe7b.gif)

### Reproducible Demo

[Snack Demo](https://snack.expo.io/BkXEKc24W)

Doesn't demonstrate super well on Snack, recommend cloning or using QR code for expo app. Uncomment code in `onPanResponderGrant` to see it work properly.

## Possible Solution (Unsure of impact)

The work around is calling `extractOffset` and then `setValue` to `0`. This way I don't have to manually track the offset.

I looked into what the potential issue was but. I attempted to add the `_flush` call to  the `extractOffset` call however things continued to operate incorrectly. 

Which meant the only other thing happening was that the `stop` call wasn't being called on the active animation.

```
    if (this._animation) {
      this._animation.stop();
      this._animation = null;
    }
```
Because `extractOffset` and `flattenOffset` both update the underlying `value` and `offset` without going through `setValue` or `setOffset`. The active animations do not stop.

The unknown impact here is effecting existing animations in action that use `flattenOffset` or `extractOffset` while an animation is running. We would end up stopping them. I'd argue that the Animated library is designed to operate this way, but it could potentially be a breaking change for lots of people?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
