### ISSUE TITLE
Multiple Alerts stacked on iOS instead of being replaced

### ISSUE THREAD

**Issue by Thibaut-Fatus** [facebook/react-native#14873]
### Is this a bug report?

Yes

### Have you read the Bugs section of the Contributing to React Native Guide?

yes

### Environment

react-native-cli: 1.0.0
react-native: 0.43.4 (simulator screenshots) and 0.45.1 (Expo demo)
node: v7.7.4
npm: 4.1.2

Then, specify:

1. Target Platform: iOS
2. Development Operating System macOS Sierra
3. Build tools Xcode (8.3)

### Steps to Reproduce

Displaying successive Alerts on iOS leads to an overlay (multiple Alerts displayed, you need to click them one by one to get back to the app)

```
Alert.alert('title', 'lorem', [
  { text: 'cancel', onPress: () => true },
  { text: 'read', onPress: () => this.doWhatever() },
]);
```

### Expected Behavior

On Android, if an Alert is already displayed when calling `Alert.alert` the new Alert *replace* the previous one. It should be the same on iOS since there is no way to delete / cancel alert without pressing the buttons on it.

### Actual Behavior

Alerts are stacked on iOS instead of being replaced when a new one is created, both on simulator and on device, even build with a release scheme.

<img src="https://user-images.githubusercontent.com/7557608/27933655-99d9bfb6-62a2-11e7-9cf4-ef3d5401b7a5.png" height="250px">
<img src="https://user-images.githubusercontent.com/7557608/27933653-99d7dc46-62a2-11e7-95f1-b56a37e3bc74.png" height="250px">
<img src="https://user-images.githubusercontent.com/7557608/27933656-99da0eda-62a2-11e7-8809-7b6220aeb183.png" height="250px">
<img src="https://user-images.githubusercontent.com/7557608/27933651-99d7cef4-62a2-11e7-8c40-ed8d4a304a32.png" height="250px">
<img src="https://user-images.githubusercontent.com/7557608/27933654-99d8ad92-62a2-11e7-9bc7-05dde1f6acec.png" height="250px">
<img src="https://user-images.githubusercontent.com/7557608/27933652-99d7d1ce-62a2-11e7-82a6-4eb7b3d88dbf.png" height="250px">
<img src="https://user-images.githubusercontent.com/7557608/27933657-99eae746-62a2-11e7-8565-476d09296865.png" height="250px">

### Reproducible Demo

I've setup an Expo project here: run it on iOS to reproduce the bug.

https://github.com/weassur/RNAlertBug

and a snack:

https://snack.expo.io/rynGz03N-

there are no dependencies other than to the Alert API

**Comment by Ehesp** [comment]
I always thought this was expected iOS behaviour. Agreed it's annoying as you can't have the same code base to handle alerts.

**Comment by Thibaut-Fatus** [comment]
This does not look like an expected behaviour

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by Thibaut-Fatus** [comment]
Seems like it should remain open, this is definitely a bug.

**Comment by alexandrzavalii** [comment]
Is there a way to close old Alert before showing the new one ?
