### ISSUE TITLE
Starting new Animation in start callback not cancelling existing animation 

### ISSUE THREAD

**Issue by browniefed** [facebook/react-native#14899]
### Is this a bug report?

Yes.

### Have you read the Bugs section of the Contributing to React Native Guide?

Yes.

### Environment

react-native-cli: 2.0.1
react-native: 0.45.1

Then, specify:

1. Target Platform (e.g. iOS, Android): Both
2. Development Operating System (e.g. macOS Sierra, Windows 10): macOS El Capitan

### Steps to Reproduce

1. Start an animation with `Animated.timing` or any animation
2. Interrupt animation so that `finished` is `false` in `start` callback
3. Trigger another animation on same `Animated.Value`.
4. Notice the first animation isn't cancelled yet, second animation continues

### Expected Behavior

It should have cancelled the first animation before the `start` callback and then executed the second animation.

### Actual Behavior

It executes both at the same time until one of them wins. Requires the use of a `setTimeout` to allow for executing the second animation.

### Reproducible Demo

[Snack Demo](https://snack.expo.io/ByFoH5a4W)

**Comment by browniefed** [comment]
I realize this is likely my issue, in that the same code path is being executed, the `start` callback is being called of the previous `toValue: 0` animation, then we are starting a `toValue: 1` in a sync callback which then the new `toValue: 0` for the second click is started.

This shouldn't be code that is written but it seems like the `toValue: 1` in the callback should be stopped before the `toValue: 0` of the second click kicks in.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
