### ISSUE TITLE
TouchableHighlight component not showing underlayColor on touch unless onPress property is set.

### ISSUE THREAD

**Issue by shadowm2** [facebook/react-native#14908]
### Is this a bug report?
Yes

### Have you read the Bugs section of the Contributing to React Native Guide?
No

### Environment

1. `react-native -v`: react-native-cli: 2.0.1          react-native: 0.45.1
2. `node -v`: v6.11.0
3. `npm -v`: 3.10.10
4. `yarn --version` (if you use Yarn): 0.27.5

Then, specify:

1. Target Platform (e.g. iOS, Android): Android
2. Development Operating System (e.g. macOS Sierra, Windows 10): Ubuntu 16.04
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): SDK 23

### Steps to Reproduce

(Write your steps here:)
1. Create a TouchableHighlight component with a Text as child with some text in it.
2. Tap on visible Text component and nothing happens(underlay color doesn't affect the text).
3. Add onPress={aFunction} and it then tap on Text component and underlay color affects the text.

### Expected Behavior

I expected the TouchableHighlight component to show underlay color on touch but it doesn't.
### Actual Behavior
The TouchableHighlight only shows underlay color on tap, when the onPress property is set for it.

[Touching button with onPress property ](https://ibb.co/m1wFza)
[Touching button without onPresss property](https://ibb.co/jK58Ka)
### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)
Here's the sample code for this.
```
import React from 'react';
import {Text, View, StyleSheet, TouchableHighlight} from 'react-native';


export default class StopWatch extends React.Component {
  constructor(props){
    super(props);
    this.styles = this.createStyle();
  };
  submitform() {};
  render() {
    return(
    <View style={this.styles.container}>
        <View style={this.styles.buttonWrapper}>
          <TouchableHighlight style={this.styles.button} onPress={this.submitform} underlayColor="gray">
            <Text>Start</Text>
          </TouchableHighlight>
          <TouchableHighlight style={this.styles.button} underlayColor="gray">
            <Text>Lap</Text>
          </TouchableHighlight>
        </View>
    </View>
    )
  };

  createStyle() {
    return StyleSheet.create({
      container: {
        flex: 1,
        borderColor: 'red',
        borderWidth: 4,
        alignItems: 'stretch'
      }, buttonWrapper: {
        flex: 3,
        borderColor: 'black',
        borderWidth: 4,
        flexDirection : 'row',
        justifyContent: 'space-around',
        alignItems: 'center'
      }, button: {
        borderRadius: 100,
        borderWidth: 4,
        width: 100,
        height: 100,
        justifyContent: 'center',
        alignItems: 'center'
      }
    });
  };
}

```

**Comment by hramos** [comment]
Is there a particular use case you have in mind where you would use a TouchableHighlight but not actually assign a `onPress` function? Why not use a plain old Text component in that case?

**Comment by shadowm2** [comment]
@hramos I understand what you're trying to say and actually i have my created my sample application successfully but it just bothers me knowing that i'm living in side of a bug like this.

**Comment by hramos** [comment]
Fair enough. Seems like something that shouldn't be too hard to fix, feel free to send a PR!

**Comment by shadowm2** [comment]
@hramos Sorry I don't know what a PR is. Can you please explain it to me ?

**Comment by hramos** [comment]
PR = pull request. You can dive into the TouchableHighlight or TouchableWithoutFeedback files and see if you can fix the underlying issue, then submit the fix back to the repo.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by fedealconada** [comment]
@hramos I think this issue is still happening...

**Comment by elan** [comment]
Can confirm.

**Comment by hramos** [comment]
New issue, please.

**Comment by AliHammoud** [comment]
Hit this particular bug myself.
