### ISSUE TITLE
[Android] No possible to handle JavaScript addListener event on native side

### ISSUE THREAD

**Issue by sytolk** [facebook/react-native#14905]
I'm looking this code:
https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/uimanager/events/EventDispatcher.java#L144

Correct me if I'm wrong but there is not clean solution how to handle JavaScript call to `addListener("event")` method from `NativeEventEmitter.js` on native - Java side.

If I have on native side Java listeners it's need to add/remove them according to add/remove on JavaScript side.

**Comment by Ehesp** [comment]
Because your compiling the native code, you can't dynamically set the event values, nor dynamically add/remove listeners.

What you need to do is subscribe to a general event on JS side, which your native side emits too. For example JS:

```js
import { NativeModules, NativeEventEmitter } from 'react-native';
import EventEmitter from 'react-native/Libraries/EventEmitter/EventEmitter';

const Package = NativeModules.MyPackage;
const EventEmitter = new NativeEventEmitter(Package);

const SharedEventEmitter = new EventEmitter();

// Listen for native events
EventEmitter.addListener('package_event', (event) => {
  const { id } = event;

  // Emit JS event
  SharedEventEmitter.emit(`package_event_${id}`, event);
});
```

Now using your native code, you can emit to `package_event` with a WritableMap/NSDictionary with an ID value and any other data.

**Comment by sytolk** [comment]
@Ehesp thanks but I want to handle subscription for events .addListener() method call in native side
https://stackoverflow.com/questions/44821313/react-native-handle-on-java-side-addlistener

**Comment by Ehesp** [comment]
Can't you handle the events client side, then call a native function with
the data?

Not actually tried listening for events native side, whether it's even
possible I don't know.

**Comment by sytolk** [comment]
Yes I can call native method like @ReactMethod eventListeningStartedOnJS() but I don't think this is cleanest solution. For iOS we can extend RCTEventEmitter and handle this:
```
/// This method will be called when the first event listener is added.
- (void)startObserving {}

/// This method will be called when the last event listener is removed.
- (void)stopObserving {}
```
Can we have the same for Android?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
