### ISSUE TITLE
[TabBarIOS] Customizing TabBar

### ISSUE THREAD

**Issue by ranyefet** [facebook/react-native#1490]
Hi guys,

Thanks for the great work!
I've noticed that master includes new useful properties for TabBar.
 - barTintColor
 - tintColor

Is there a way to add the following:
 - Remove the top border
 - Control the label text size & position
 - Control Icon size

Can someone point me to the right direction?

Your help is appreciated
Ran.

**Comment by cmcewen** [comment]
You can modify all of those properties natively: 
* http://stackoverflow.com/questions/14371343/ios-uitabbar-remove-top-shadow-gradient-line
*https://developer.apple.com/library/ios/documentation/UIKit/Reference/UITabBarItem_Class/index.html#//apple_ref/occ/cl/UITabBarItem

However, since it sounds like you want a really custom TabBar, I'd probably recommend just building your with a Navigator under a custom View.

**Comment by alinz** [comment]
You can also use the open source extension of Tab bar such as [react-native-icons](https://github.com/corymsmith/react-native-icons#custom-tab-bar) if you don't want to extend it yourself.

**Comment by browniefed** [comment]
@brentvatne open source solution now exists, and recommendations made. Closeable.

**Comment by cwRichardKim** [comment]
@ranyefet what did you do to solve this problem?  If I create a native component for this, does that mean I have to create an entire UITabBarController natively or can I somehow make a file with just that property?  Thanks!
