### ISSUE TITLE
Wrong usage of lodash.uniq in local-cli/link/link.js (should be uniqBy?) causes flow errors

### ISSUE THREAD

**Issue by Strayer** [facebook/react-native#14927]
### Is this a bug report?

Yes

### Have you read the Bugs section of the Contributing to React Native Guide?

Yes

### Environment

1. `react-native -v`: 0.46.1
2. `node -v`: v8.1.3
3. `npm -v`: 5.1.0
4. `yarn --version`: 0.27.5
5. `react-native-cli`: 2.0.1

Then, specify:

1. Target Platform (e.g. iOS, Android): both
2. Development Operating System (e.g. macOS Sierra, Windows 10): macOS Sierra
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): not relevant

### Steps to Reproduce

1. add lodash and flow-typed to a new app
2. install flow types via flow-typed install
3. run flow on unmodified react-native app

### Expected Behavior

No Flow errors should occur, uniq (or uniqBy) function should be properly used.

### Actual Behavior

Flow validation will fail because of incorrect usage of uniq function:

```
yarn run v0.27.5
$ "/Users/strayer/tmp/ReactNativeLodashFlowWarning/node_modules/.bin/flow"
Launching Flow server for /Users/strayer/tmp/ReactNativeLodashFlowWarning
Spawned flow server (pid=23674)
Logs will go to /private/tmp/flow/zSUserszSstrayerzStmpzSReactNativeLodashFlowWarning.log
node_modules/react-native/local-cli/link/link.js:38
 38: const dedupeAssets = (assets) => uniq(assets, asset => path.basename(asset));
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ unused function argument
  139:     uniq<T>(array: ?Array<T>): Array<T>;
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type expects no more than 1 argument. See lib: flow-typed/npm/lodash_v4.x.x.js:139


Found 1 error
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Reproducible Demo

Prepared repository: https://github.com/Strayer/ReactNativeLodashFlowWarning

Steps to create reproducible demo:

1. react-native init ReactNativeLodashFlowWarning
2. cd ReactNativeLodashFlowWarning
3. yarn add --dev flow-bin@^0.47.0 flow-typed
4. yarn add lodash
5. yarn run flow-typed install

**Comment by stevehollaar** [comment]
Is there any good way of suppressing library flow errors like this? If I add:
```
<PROJECT_ROOT>/node_modules/react-native/local-cli
```
to `.flowconfig`'s `[ignore]` section, I get:
```
node_modules/react-native/Libraries/Image/AssetSourceResolver.js:27
 27: const assetPathUtils = require('../../local-cli/bundle/assetPathUtils');
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ../../local-cli/bundle/assetPathUtils. Required module not found
```

**Comment by rusfearuth** [comment]
This is a bug.

**Comment by Strayer** [comment]
The easiest way to suppress this error seems to be this:

```
[ignore]
.*/node_modules/react-native/local-cli/link/link.js

[options]
module.name_mapper='^./link/link$' -> 'emptyObject'
```

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by jkimbo** [comment]
In case anyone comes across this issue again - this is fixed by https://github.com/facebook/react-native/commit/df8d0d1db9203cc87ad3682e6138b2a9ed714365
