### ISSUE TITLE
Navigator and UITabbarController has some conflict on iOS.

### ISSUE THREAD

**Issue by huangcheng1** [facebook/react-native#14926]
1. react-native 0.43.4:
2. node 4.5.0:
3. npm 3.10.7:

when i create a UIWindow with rootController is UITabbarController, and the UITabbarController contain some UINavigationConller . then , i push a new vc contain RCTRootView with full screen , native UINavigationBar is hiden , and hidesBottomBarWhenPushed is YES . final appear RCTView bounds is not correct .

this is layer preview

[image](http://7xpas5.com1.z0.glb.clouddn.com/FCBF8979B39CB7766CEA96055BA240FB.jpg)

this is my some code

`
UINavigationController = UINavigationController.rootVC(new vc);
UITabbarController = new UITabbarController(@[@UINavigationController,@xx])
window.rootViewController = UITabbarController

RNVC = UIViewController.addSubView(RCTRootView)
RNVC.navigationBarHidden=yes
`

maybe don't make me clear. sorry

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
