### ISSUE TITLE
Re-sizing image components on Android

### ISSUE THREAD

**Issue by ben-brott** [facebook/react-native#14937]
I am rendering an `Image` component inside of a `Text` component on Android. I want to resize the image based on its aspect ratio. I fetch the image's dimensions and trigger a re-render in `componentDidMount` (also tried using `componentWillMount`), but the image is not  actually re-rendering as expected. I am trying to re-render the image because `resizeMode={'contain'}` had no effect. This works fine if the `Image` component is NOT inside of a `Text` component.

### Environment

react-native version: 0.45.1
node version: 7.7.2
npm version: 4.1.2 
Target Platform: Android
Development OS: macOS Sierra

### Steps to Reproduce

1. Render an `Image` component inside of a `Text` component. 
2. In `componentDidMount`, set state variables to update the `width` and `height` of the `Image` component.

### Expected Behavior

The complete image should be rendered without getting cut off. The image size should change based on its aspect ratio.

### Actual Behavior

The image is rendered using its default dimensions. The remote JS debugger shows that the `render()` function is getting called again, but these changes are not displayed on-screen.

![image](https://user-images.githubusercontent.com/29098354/28037527-a32092a4-6589-11e7-8212-712ee8679573.png)

The image in the first line has its dimensions set explicitly to the fetched dimensions. The image in the second line is the one that should be updating.

### Reproducible Demo

https://snack.expo.io/HJHneUbrZ

### Current Workaround

Changing the image's source triggers the expected re-rendering.

In addition to saving state variables for the correct dimensions, if you use another variable for the images source, and just add a space to the end, you get the expected behavior.

OR

Originally render the image using an empty string for its source, then set the appropriate source using a state variable.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
