### ISSUE TITLE
DrawerLayoutAndroid: changing drawerWidth is broken

### ISSUE THREAD

**Issue by arv** [facebook/react-native#14978]
### Is this a bug report?

Yes

### Have you read the Bugs section of the Contributing to React Native Guide?

Yes

### Environment

1. `react-native -v`: 0.46.1
2. `node -v`: v7.10.0
3. `npm -v`: 4.2.0
4. `yarn --version` (if you use Yarn): 0.23.2

Then, specify:

1. Target Platform (e.g. iOS, Android): Android
2. Development Operating System (e.g. macOS Sierra, Windows 10): macOS Sierra
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): Not relevant

### Steps to Reproduce

Using `DrawerLayoutAndroid` changing the `drawerWidth` leads to incorrect layout.

1. Open a drawer (DrawerLayoutAndroid) (for example by swiping from the left edge)
2. Change the `drawerWidth` prop.

### Expected Behavior

I expect the width to change and the layout of the component in the drawer to have the same with as the drawer.

### Actual Behavior

The width of the component inside the drawer changes but the drawer itself does not change its width.

At startup:

![screenshot_20170712-110726](https://user-images.githubusercontent.com/45845/28132735-8d71df70-66f2-11e7-83ad-65c44186b013.png)

Clicking 100 leads to

![screenshot_20170712-110732](https://user-images.githubusercontent.com/45845/28132740-92aa5882-66f2-11e7-80c9-c996ad664d67.png)

Clicking 400 leads to

![screenshot_20170712-110737](https://user-images.githubusercontent.com/45845/28132742-95605f72-66f2-11e7-9870-1bd84daca34e.png)

### Reproducible Demo

Open the drawer by swiping from the left.
Click the buttons to change the `drawerWidth`.

A runnable demo can be found at: 
https://snack.expo.io/SkG-BkNSW

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
