### ISSUE TITLE
[Scrollview] scrollTo behaviour different in Android than iOS

### ISSUE THREAD

**Issue by sirilicious** [facebook/react-native#14976]
### Is this a bug report?

Yes

### Have you read the Bugs section of the Contributing to React Native Guide?

Yes

### Environment

react-native-cli: 2.0.1
react-native: 0.45.1
node: v7.10.0
npm: 4.6.1
yarn: n/a

Target Platform: Android
Development Operating System: macOS Sierra
Build tools: Android Studio 2.3.3, Android 4.4.2

### Steps to Reproduce  --  Expected & Actual Behavior

1. Open [https://snack.expo.io/H1Atpa7H-](https://snack.expo.io/H1Atpa7H-)
2. Use iOS preview and click on 'scroll to last paragraph' -> scrollview scrolls down to last paragraph (what is expected) -> OK
3. Switch to Android preview and click also on 'scroll to last paragraph' -> scrollview does not scroll down to last paragraph -> not OK

**Comment by hramos** [comment]
Can you elaborate on steps 2 and 3 - what is expected and what actually happens?

**Comment by asreedha** [comment]
I believe scroll to lastparagraph is not actually scrolling to last paragraph on Android by touching on "scroll to lastparagraph" on the android app screen for Expo after scanning QR code.(which is the bug), while it DOES scroll to last paragraph in iOS by following similar steps(which is expected behavior). 

And I believe the solution would make Android scroll to last paragraph successfully by touching on "scroll to lastparagraph" on the android app screen for Expo after scanning QR code.

Please let me know if that clarifies.
