### ISSUE TITLE
App crashes when logging an error with console.error

### ISSUE THREAD

**Issue by LukasKnuthImagineOn** [facebook/react-native#14998]
### Environment

1. `react-native -v`: `react-native-cli: 2.0.1 | react-native: 0.42.0`
2. `node -v`: `v6.10.0`
3. `npm -v`: `3.10.10`
4. `yarn --version` (if you use Yarn): Not used

Then, specify:

- Target Platform: Android

- Development Operating System: Android 6.0.1

- Build tools: Gradle, SDK 25

### Steps to Reproduce

(Write your steps here:)

1. Wrap a `JSON.parse` in a try-catch block
2. Log the caught error with `console.error`
3. The log shows
4. Immediately after, the application crashes

### Expected Behavior

The log should show but the application shouldn't crash

### Actual Behavior

The StackTrace, read via Android Device Monitor:

```
07-13 12:26:31.245: E/AndroidRuntime(20641): FATAL EXCEPTION: main
07-13 12:26:31.245: E/AndroidRuntime(20641): Process: com.p2ar, PID: 20641
07-13 12:26:31.245: E/AndroidRuntime(20641): com.facebook.react.bridge.UnexpectedNativeTypeException: TypeError: expected dynamic type `int64', but had type `null'
07-13 12:26:31.245: E/AndroidRuntime(20641): 	at com.facebook.react.bridge.ReadableNativeMap.getInt(Native Method)
07-13 12:26:31.245: E/AndroidRuntime(20641): 	at com.facebook.react.devsupport.StackTraceHelper.convertJsStackTrace(StackTraceHelper.java:103)
07-13 12:26:31.245: E/AndroidRuntime(20641): 	at com.facebook.react.devsupport.DevSupportManagerImpl$3.run(DevSupportManagerImpl.java:287)
07-13 12:26:31.245: E/AndroidRuntime(20641): 	at android.os.Handler.handleCallback(Handler.java:739)
07-13 12:26:31.245: E/AndroidRuntime(20641): 	at android.os.Handler.dispatchMessage(Handler.java:95)
07-13 12:26:31.245: E/AndroidRuntime(20641): 	at android.os.Looper.loop(Looper.java:168)
07-13 12:26:31.245: E/AndroidRuntime(20641): 	at android.app.ActivityThread.main(ActivityThread.java:5885)
07-13 12:26:31.245: E/AndroidRuntime(20641): 	at java.lang.reflect.Method.invoke(Native Method)
07-13 12:26:31.245: E/AndroidRuntime(20641): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
07-13 12:26:31.245: E/AndroidRuntime(20641): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
```

Screenshot of the logged React Native error:
![screenshot](https://user-images.githubusercontent.com/22296305/28162591-f3639e56-67c7-11e7-8806-d242de75ae2d.png)

### Reproducible Demo

Anywhere in your app:

```
let parsed: ?Object = null;
try {
    eventSource = JSON.parse(someString);
} catch (err) {
    console.error(err);
}
```

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
