### ISSUE TITLE
Image.onPartialLoad doesn't work with progressive JPEG

### ISSUE THREAD

**Issue by cooperka** [facebook/react-native#15005]
### Expected behavior

I expected progressive JPEG images to render progressively by default, with callbacks for `onPartialLoad` during rendering. According to the [Image docs](https://facebook.github.io/react-native/docs/image.html#onpartialload) for `onPartialLoad`:

> (iOS only) Invoked when a partial load of the image is complete. The definition of what constitutes a "partial load" is loader specific though this is meant for progressive JPEG loads.

### Actual behavior

The callback is never invoked, and the progressive JPEG image doesn't render at all until the entire file has been downloaded.

Tested on iOS 10.3 using an iPhone 6s simulator with React Native v0.44.3.

### Possible solution

Fresco (the FB library React Native uses to render images, if I understand correctly) [supports progressive JPEG rendering](http://frescolib.org/docs/progressive-jpegs.html) with a simple flag `setProgressiveRenderingEnabled(true)`. The docs aren't very clear about why this isn't just the default; I assume it's due to performance concerns with the CPU doing more work to render progressively.

Would you be open to a PR that supports this flag? Either way, the docs should probably be updated to clarify that progressive JPEG is not currently supported by React Native.

**Update**: Turns out Fresco is Android only. Facebook wrote an [article about using PJPEG on iOS](https://code.facebook.com/posts/857662304298232/faster-photos-in-facebook-for-ios/), but it's not clear how they achieved it. There's [Concorde](https://github.com/contentful-labs/Concorde), but it's likely too large of a library to be worth including in React Native.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
