### ISSUE TITLE
[Android] Switch thumbTintColor gets reseted

### ISSUE THREAD

**Issue by DenizTemizer** [facebook/react-native#15002]
### Environment

1. `react-native -v`: 0.46.2
2. `node -v`: 8.0.0
3. `npm -v`: 5.2.0

Then, specify:

- Target Platform: Android

- Development Operating System: macOS 10.12.5

### Steps to Reproduce

1. Create empty project on with newest version
2. Add a switch component with a thumbTintColor property and test it
```jsx
<Switch
  onValueChange={ val => this.setState({ switcher: val }) }
  value={ this.state.switcher }
  thumbTintColor="#FF0000"
 />
```

### Expected Behavior

When toggling the switch to on the thumbTintColor should be used.

### Actual Behavior

After first toggling the thumbTintColor will be reseted.
When toggling the switch to on now the thumbTintColor has the color 'teal'.

**Comment by hramos** [comment]
Can you post a Snack or at minimum screenshots of the issue?

**Comment by DenizTemizer** [comment]
After component init:
![initial](https://user-images.githubusercontent.com/16053154/28202971-fac2cd38-6877-11e7-81fc-1d0e3988b12a.png)

After first toggle:
![firsttoggle](https://user-images.githubusercontent.com/16053154/28202972-fd98a302-6877-11e7-88f3-f5572e1d3e03.png)

After second toggle:
![secondtoggle](https://user-images.githubusercontent.com/16053154/28202975-feff51aa-6877-11e7-8b7a-b77bf8bcd250.png)

I would have expected that this color replaces the 'teal / dark green' color on the active switch.
Also the color should be persistent.

**Comment by hramos** [comment]
If I recall correctly, someone submitted this as a bug some time ago and it turned out that the native switch on Android behaves in a similar manner. In other words, the issue is with the native control.

**Comment by DenizTemizer** [comment]
Did some researches but couldn't find a similar bug reported on native code.
I may look into it but I guess if this is a bug on react-native side it will be something requiring deeper knowledge about how react-native works inside.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by gmantovani97** [comment]
I had the same issue on Android.

**# Environment**

1. react-native -v:  2.0.1
2. node -v: 8.11.1
3. npm -v: 5.6.0
