### ISSUE TITLE
Image.prefetch does not work as expected on ios

### ISSUE THREAD

**Issue by brkyldz** [facebook/react-native#15004]
### Is this a bug report?

Yes.

### Have you read the Bugs section of the Contributing to React Native Guide?

Yes.

### Environment

1. `react-native -v`: 0.43.3
2. `node -v`: 7.10.0
3. `npm -v`: 5.0.3
4. `yarn --version` (if you use Yarn): 0.24.6

- Target Platform: iOS

- Development Operating System: macOS

- Build tools: Xcode
Yes, the issue is specific to iOS.

### Steps to Reproduce

1. Prefetch a set of images.
2. After prefetching is completed, show those images in sequential with prop `source={{uri: ..., cache: 'only-if-cached'}}`

### Expected Behavior

Since the images were prefetched, all images should be shown in order.

### Actual Behavior

Sometimes, only the first image is shown and the others are not shown just only on ios. It is weird because all images are prefetched and they should be cached.

### Reproducible Demo

https://snack.expo.io/rJDaNz8rZ

**Comment by hramos** [comment]
Thanks for the issue! Sorry to ask, but can you update your post to ensure it fits the issue guidelines? You should see a template when you create a new issue with further instructions.

**Comment by brkyldz** [comment]
Of course, I did.

**Comment by hramos** [comment]
Thank you!

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
