### ISSUE TITLE
Link command does not have very good error messages

### ISSUE THREAD

**Issue by mark0978** [facebook/react-native#15017]
This is a bug report/feature request for better error messages from the link command.  If it can't find the files to write the link statements into, it should gripe, especially if the folders those files should be in don't exist.  The link command lacks a -verbose option so you can see what it is trying to do as well.  In general link appears to be barely usable due to the lack of diagnostics it can/will emit.

### Environment

1. `react-native-cli: 2.0.1`   `react-native: 0.45.1`
2. `node -v`: `6.9.4`
3. `npm -v`: `4.1.2`
4. `yarn --version` (if you use Yarn):

- Target Platform: iOS and Android
- Development Operating System: macOS 10.11.6
- Build tools:  Started with create-react-native-app, using react-native to build

### Steps to Reproduce

1. Pretend you know nothing about react-native (first app, seasoned developer)
2. Create a brand new app with `create-react-native-app`
3. Add the camera:
`npm install react-native-camera@https://github.com/lwansbrough/react-native-camera.git --save`
`react-native link react-native-camera`
4. Don't get any error message from the linking process
5. `npm start`
6. Load app with QR code, app crashes with 'CameraManager.aspect` error
7. Look up error message
8. See references to other people with same problem
9. Notice references to files and directories you don't have in your app
10.  Finally figure out you have to eject the project from create-react-native-app to get those folders/files
11. Finally it works

### Expected Behavior

Link would provide an error message indicating it can't link anything because you don't have `these files` with an extra comment that you might need to eject the project to create those files.

Couple of hours saved.

### Actual Behavior

See steps above

### Reproducible Demo

Follow the steps above to reproduce.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by mark0978** [comment]
I realize it's your repo, and you can do as you please, but if you want to discourage people from taking the time to write detailed issues, you have found the perfect way to do it.  Take a detailed issue and then just close it because it has been open too long.  Don't bother to actually investigate it or fix it, just close it.

With the patent rider in the license, it probably won't matter, since we'll have to drop using react anyway, but it does seem like this is something that should have been a simple fix that was just closed to reduce some count.
