### ISSUE TITLE
Systrace is not enabled for JSC on Android

### ISSUE THREAD

**Issue by MarcoPolo** [facebook/react-native#15022]
### Is this a bug report?
Yes

### Environment

- `react-native -v`: 0.46

- Target Platform: Android

- Development Operating System: macOS

### Steps to Reproduce

Systrace module in RN depends on hooks like `nativeTraceBeginSection` to exists (see https://github.com/facebook/react-native/blob/master/Libraries/Performance/Systrace.js#L134). But they are added [here](https://github.com/facebook/react-native/blob/master/ReactCommon/cxxreact/JSCTracing.cpp#L420) which isn't run becuase it requires `fbsystrace.h` [to exist](https://github.com/facebook/react-native/blob/master/ReactCommon/cxxreact/JSCTracing.cpp#L8).

1. Try to use Systrace module. Fails because it's missing `nativeTraceBeginSection` and/or `nativeTraceBeginSection`
2. Try to add those by enabling `WITH_JSC_EXTRA_TRACING`. Fails because it's missing `fbsystrace.h`

### Expected Behavior

Would be really helpful to be able to see what JSC is doing within a systrace on android

**Comment by jayshah123** [comment]
I have filed a similar issue regarding missing systrace due to fbsystrace.h @ https://github.com/facebook/react-native/issues/14394

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
