### ISSUE TITLE
StyleSheet.flatten is returning frozen object. No need to be frozen, and not documented

### ISSUE THREAD

**Issue by Noitidart** [facebook/react-native#15037]
### Is this a bug report?
Yes. At the very least, if no one agrees that it "should not be frozen", then the docs need to be updated".

### Have you read the Bugs section of the Contributing to React Native Guide?
Yes

### Environment

1. `react-native -v`: 0.46.3
2. `node -v`: 7.8.0
3. `npm -v`: 5.1.0
4. `yarn --version` (if you use Yarn): n/a

Then, specify:

- Target Platform: iOS

- Development Operating System: macOS 10.12.5 (16F73)

- Build tools: None. Just regular `react-native run-ios`.

### Steps to Reproduce

(Write your steps here:)

1. `const styles = StyleSheet.create({ text:{ backgroundColor:'red' } });`
2. Now do `const flatNew = StyleSheet.flatten(styles.text);`
3. Now `Object.isFrozen(flatNew)` is `true`. There is no need for this freeze. It should be mutable. If you really want it immutable, then docs need update. - http://facebook.github.io/react-native/releases/0.46/docs/stylesheet.html#flatten

### Expected Behavior

There is no need for this freeze. It should be mutable. If you really want it immutable, then docs need update. - http://facebook.github.io/react-native/releases/0.46/docs/stylesheet.html#flatten

### Actual Behavior

Object is frozen, it cannot be mutated.

### Reproducible Demo

Link to expo reproducible: https://snack.expo.io/B1A17ZYrZ

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
