### ISSUE TITLE
App disappears from the screen  when 'share' and 'complete action with' dialog shows up.

### ISSUE THREAD

**Issue by sandropoluan** [facebook/react-native#15047]
### Is this a bug report?

YES

### Have you read the Bugs section of the Contributing to React Native Guide?

YES

### Environment

1. `react-native 0.44`
2. `node -6.10.3`
3. `npm -3.10.10`
4.  `Device:  XIAOMI Redmi Note 2`

Then, specify:

- Target Platform:  Android

- Development Operating System: Windows 7

- Build tools: 25.0.3

### Expected Behavior

When the dialog shows up, app should stay on the screen , and the dialog should be on front of the app.

### Actual Behavior

App disappears from the screen  when the dialog shows up.
![videotogif_2017 07 17_14 00 10](https://user-images.githubusercontent.com/11922251/28257369-ceb37472-6afc-11e7-987b-9cd3c57627a5.gif)

![videotogif_2017 07 15_01 26 25](https://user-images.githubusercontent.com/11922251/28257376-e570f2ca-6afc-11e7-91bc-92ac7646c852.gif)

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
