### ISSUE TITLE
Unable to resolve module core-module from ...

### ISSUE THREAD

**Issue by sm2017** [facebook/react-native#15048]
I have the following code 

```js
const https = require('https');
const http = require('http');
const url = require('url');
```

I have problem with core nodejs modules , react-native show the `Unable to resolve module "http" from ... This might be related to https://github.com/facebook/react-native/issues/4968` error

I see This might be related to https://github.com/facebook/react-native/issues/4968 and follow it but not solved and I think core module is different

**Comment by jasonmerino** [comment]
AFAIK there is no official support for many (all?) of the core node modules in React Native and it doesn't look like there's any movement toward supporting them. Although, there are many other libraries out there that can be used as a direct replacement for core node modules. For the `url` module you could use the [`url` module on NPM](https://www.npmjs.com/package/url).

For making HTTP requests React Native comes with a [polyfill for window.fetch](http://facebook.github.io/react-native/releases/0.46/docs/network.html#using-fetch). But I have also seen others use [axios](https://www.npmjs.com/package/axios) because they prefer how it works.

For more information on what the plan for supporting core node modules is you could peruse these issues. #9709 #375 #1871

In my experience for things like this you are going to need to go out and find alternatives to the core modules for use in your project and sometimes adjust your implementation a bit to fit the replacement module.
