### ISSUE TITLE
[Android] Unable to load file-based unbundle with custom JSBundleFolder

### ISSUE THREAD

**Issue by vuduclong0309** [facebook/react-native#15050]
### Is this a bug report?

Yes, also a feature request

### Have you read the Bugs section of the Contributing to React Native Guide?

Yes

### Environment

1. `react-native -v`: react-native-cli: 2.0.1
2. `node -v`: v8.1.0
3. `npm -v`: 5.0.3
4. `yarn --version`: not applicable

- Target Platform: Android

- Development Operating System: MacOS Sierra

- Build tools: Android Studio/Command Line Tools

### Steps to Reproduce

Step 1: Create a new project, override getJSBundleFile() function of MainApplication.java
```
public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage()
      );
    }

    @Nullable
    @Override
    protected String getJSBundleFile() {
      Log.d("I",Environment.getExternalStorageDirectory().getAbsolutePath() + "/split/index.android.bundle");
      return Environment.getExternalStorageDirectory().getAbsolutePath() + "/split/js-modules";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }
}
```

Step 2: generate file-based unbundle using  `react-native unbundle --platform android --dev false --entry-file index.android.js --bundle-output ./unbundle/index.android.bundle --assets-dest ./unbundle`

Step 3: generate apk file and install apk into android device.
Step 4: put generated unbundle file in custom directory folder of the device

### Expected Behavior

The application should load bundle file and module correctly

### Actual Behavior

Application can recognise and load script from index.android.bundle, but cannot load all of the module in js-modules folder, thus returning "Requiring Unknown Module" issues

<img width="277" alt="screen shot 2017-07-04 at 6 11 39 pm" src="https://user-images.githubusercontent.com/16941282/28258910-4e8c2e1a-6b06-11e7-82dd-0517cbf7a198.png">

### Reproducible Demo

https://github.com/vuduclong0309/React-native-issue-reproducible-demo.git

*Note: When I don't override the function and put unbundle into assets folder of apk file, the application still can load bundle correctly

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
