### ISSUE TITLE
Debug JS Remotely in RN version 0.45.0 and above.

### ISSUE THREAD

**Issue by tarang9211** [facebook/react-native#15074]
### Is this a bug report?

(write your answer here)

### Have you read the Bugs section of the Contributing to React Native Guide?

(Write your answer here.)

### Environment

1. `react-native -v`: `v0.45.0 and above`
2. `node -v`: `v7.0.0`
3. `npm -v`: `v3.10.8`
4. `yarn --version` (if you use Yarn): `v0.24.6`

Then, specify:

- Target Platform: iOS 10

- Development Operating System: macOS Sierra 10.12.5

- Build tools: Xcode 8.3.3 (8E3004b)

### Steps to Reproduce

1. Create a component that performs a network request (preferably using fetch) in `componentDidMount`. Make this component the first screen to be displayed in the app.
For example, here is the network request I am making:
``` javascript
checkForUpdate()
    .then((isSupported) => {
      this.setState({ isSupported })
      console.log(isSupported)
    })
    .catch((err) => {
      console.log(err)
    })
```
2. The app should be running on your device now. Shake the device and select `Debug JS remotely`
Even after ensuring the server code is properly handled, the promise does not resolve or reject.
3. Now, press the Home button on your iPhone. The value of the promise will get logged.

### Expected Behavior

The promise should resolve or reject without the need to press the physical Home button on the phone.

### Actual Behavior

Absolutely nothing related to the network is getting logged. As soon as the physical home button is pressed, the app functions as normal.

Note, this works absolutely fine in react-native `0.44.0`. If I upgrade to `0.45.0 and above`, the bug starts to occur when I remotely debug.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
