### ISSUE TITLE
Passing big string to WebView failed.

### ISSUE THREAD

**Issue by hz0324** [facebook/react-native#15076]
I am tring to pass a local file to WebView. After searching around, I think the following method is a promising approach.

Get base64 code for the local file and pass it to WebView as a string, and inside the WebView, decode base64 to file object.

However, when I use the base64 code as the parameter for `webview.postMessage(base64)` , nothing happened. Keep everything untouched, hard-code a short string as the parameter for postMessage(msg), everything works fine, the code in WebView part can get the value.

I don't what happened. Is there a limitation for the parameter of postMessage() ? Or a bug for RN WebView?

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

**Comment by hz0324** [comment]
@hramos  Nope, I think it maybe a bug. 

Later yesterday, I found that, the code is working fine on emulator, but failed on real device. It is wired, I spent whole afternoon working on it, just find out it may by problem with debuging on real device.

**Comment by limemloh** [comment]
+1

**Comment by njustice4all** [comment]
+1

**Comment by jiasaichao** [comment]
+1
