### ISSUE TITLE
Aligning React Native Animated and AnimatedJS

### ISSUE THREAD

**Issue by souporserious** [facebook/react-native#15085]
Hello, I read through the contributing guide and I wasn't sure where to post this since I'm not sure it's a feature or an actual React Native issue, but more of a want/question. Please feel free to close this and I can post where it is appropriate.

I've spoke recently with @browniefed and @lelandrichardson about this to get their thoughts on this and wanted to see about getting React Native Animated aligned with AnimatedJS. It seems this has been [posted about before](https://github.com/facebook/react-native/issues/11029) and was closed. Not really sure why though?

I come from a web background and use React on the web mostly, and I've benefited greatly from the AnimatedJS repo by being able to go and read tutorials for React Native and then use the same code on the web. I'd love to align these API's and let the web get better, official support for Animated. I understand @necolas and @lelandrichardson are using AnimatedJS in their respective libraries, so hopefully this shows a need for more web support. I can see a great benefit in having one animation solution that we can all contribute to and end users can benefit from the same API. I love the whole idea of applying "learn once, write anywhere" to animation.

@browniefed brought up some good points, and said that it would probably be best to try and split up React Native Animated in here first, and once that is done, copy it over to the AnimatedJS repo, and then finally see about React Native pointing to use AnimatedJS code. I understand this is a pretty big challenge, and there are a lot of moving parts, but I wanted to gather feedback and see if anyone else has thought about this or is willing to see this happen. I am more than happy to start splitting up files in here and get the ball rolling, I would just want to make sure there is approval for this before submitting a PR or anything.

[I filed and issue a couple of weeks ago with AnimatedJS](https://github.com/animatedjs/animated/issues/75) to get these same thoughts and @vjeux seemed to be on board with it. I was looking around the repo and came [across this](https://github.com/facebook/react-native/blob/master/Libraries/Animated/src/AnimatedWeb.js), but not sure how that is meant to be used? Again, I'd love to hear React Native's thoughts on this. I'm willing to put in whatever work to make this happen 😁

**Comment by necolas** [comment]
To clarify, react-native-web includes `Animated` for compatibility purposes, but the current implementation of the `animated` library has no "native driver" equivalent for web. Running animations on the main thread is not performant in a browser, and I'm not recommending people use `Animated` on web if they can avoid it and use CSS transitions/animations or `element.animate` instead.

**Comment by hramos** [comment]
@souporserious we generally try to avoid using issues for discussion, as we've been fighting a high number of open issues for several months now. I still think this is worth discussing and perhaps you can find a better forum off GitHub. Perhaps you can look up the owners for the relevant pieces of code, and tag them here once you have opened an entry in Canny.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
