### ISSUE TITLE
does react native support indexeddb

### ISSUE THREAD

**Issue by crazybits** [facebook/react-native#15119]
i am refactoring a web app with RN, and web app is using IndexedDB as the storage, now the RN app can not work properly when disable the debug model, i would like to know whether RN support IndexedDB? any suggestion if the answer is not.

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

**Comment by bryanrideshark** [comment]
Considering this is the authoritative repository, it would make sense to answer with two questions:

Does React Native, either implicitly or explicitly, support Indexed DB?

If no, are there plans to support Indexed DB in the future?

Punting this question really shouldn't be done without at _least_ an authoritative answer to those two questions.
