### ISSUE TITLE
How to access Android styles.xml and apply style to react native text?

### ISSUE THREAD

**Issue by rajsuvariya** [facebook/react-native#15169]
I have some predefined styles in android in my hybrid app. How can I access those styles???

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

**Comment by rajsuvariya** [comment]
No one answers such questions on stackoverflow. I asked few and people started down voting it and stackoverflow banned my aacount :(

**Comment by hramos** [comment]
That's unfortunate. Can you link to the question here? I'd like to understand why it got you banned.

In any case, the issue tracker is not an appropriate place for questions.
