### ISSUE TITLE
[NavigatorIOS] Move to OSSLibraries folder

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#1519]
In order to be able to better support community contributions and make clear that this library is not currently a priority for Facebook, the plan is to try moving this component to a separate directory that is not managed in the same way by the sync process.

1. Move `NavigatorIOS.ios.js` to new folder `OSSLibraries/NavigatorIOS/NavigatorIOS.ios.js`
2. [RCTNavigator code](https://github.com/facebook/react-native/search?utf8=%E2%9C%93&q=RCTNavigator) to that folder, and in new Xcode project

**Comment by grabbou** [comment]
@brentvatne what about keeping the structure inside `OSSLibraries` somehow similar to the `Libraries` so it's easier to just move around instead of investigating the whole folder from scratch?

**Comment by jsierles** [comment]
What about a separate repository?

**Comment by brentvatne** [comment]
@grabbou - makes sense, so `OSSLibraries/Components/NavigatorIOS`?

**Comment by brentvatne** [comment]
@jsierles - @ide @vjeux and I discussed this and it may happen eventually but at the moment it would complicate things a bit too much on the Facebook end, so this is a step towards that

**Comment by jsierles** [comment]
Sounds good!

**Comment by grabbou** [comment]
@brentvatne - Yes. This kind of stuff. So it's possible to move other bits as well (currently there are none, but who knows ;) ). Anyway, will send over something by the end of the week and then we can discuss the structure further.

**Comment by brentvatne** [comment]
@grabbou - interested in doing this still?

**Comment by grabbou** [comment]
Thanks for reminding. Yep, I am going to have some time this week to get few entry-level issues done :)

**Comment by grabbou** [comment]
Will land today!

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/navigatorios-move-to-osslibraries-folder

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
