### ISSUE TITLE
Newline added in multiline, blurOnSubmit TextInput on press 'Enter' AFTER pasting

### ISSUE THREAD

**Issue by Palisand** [facebook/react-native#15205]
### Is this a bug report?

Yes, yes it is.

### Have you read the Bugs section of the How to Contribute guide?

Yes

### Environment

1. `react-native -v`:  `react-native-cli: 2.0.1 react-native: 0.46.1`

2. `node -v`: `v7.8.0`
3. `npm -v`: `4.6.1`

- Target Platform: **iOS**

- Development Operating System: **macOS X El Capitan (10.11.6)**

- Build tools: **Expo**

### Steps to Reproduce

1. Paste some text on a `TextInput` with `multiline` and `blurOnSubmit` set
2. Press Enter/Return on keyboard
3. Notice (and scratch head) the newline that appears

### Expected Behavior

A newline should not be inserted on Enter/Return press when `blurOnSubmit` is `true`, even
after pasting.

### Actual Behavior

A newline **was** inserted.

### Reproducible Demo

https://snack.expo.io/SJte7YSL-

**Comment by Palisand** [comment]
In addition, pressing Return also enables CAPS (just like https://github.com/facebook/react-native/issues/15155). The key difference here is **the bug occurs after pasting text**.

**Comment by SuhairZain** [comment]
Hi @shergin, are there any updates on this issue?

**Comment by meggamind** [comment]
@SuhairZain, @shergin  : Can I pick this issue ?

**Comment by SuhairZain** [comment]
@meggamind I believe this has been fixed in the latest release ([0.53.0](https://github.com/facebook/react-native/releases/tag/v0.53.0)). I had this issue on a Redmi 3S Prime running MIUI 8 and Android 6 with RN 0.47.1. For me it works when upgrading to the latest version.

Please check if the latest release fixes it for you or not.

**Comment by FranciscoMSM** [comment]
I checked both in Android and iOS and it seems to be fixed in 0.55.4

**Comment by ferrannp** [comment]
Hello there 👋 this issue has been reported for an old version of React Native. Ideally we'd like everyone to be using 0.59 (see the [awesome changes](https://facebook.github.io/react-native/blog/2019/03/12/releasing-react-native-059) it brought) but we know updating can be a pain. We are going to close this issue because it's from a version before 0.57, which is really old.

But please, if it's actually still an issue with 0.59 please comment below and we can reopen it 😊
