### ISSUE TITLE
Unable to fix "PropTypes has been moved to a separate package."

### ISSUE THREAD

**Issue by agerson** [facebook/react-native#15204]
One of the modules I use, [react-native-spinkit](https://github.com/maxs15/react-native-spinkit), started throwing this error after I updated to RN v.46. I went into the file causing the error (node_modules/react-native-spinkit/index.js) and made the changes described in [Migrating from React.PropTypes](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes). I even tried automatically applying the changes with [jscodeshift](https://github.com/reactjs/react-codemod#react-proptypes-to-prop-types). Then I ran:

`watchman watch-del-all && rm -rf node_modules/ && yarn cache clean && yarn install && yarn start -- --reset-cache
`

However, I am still getting this warning. I want to help a project I use. What am I doing wrong?

[Code before](https://github.com/maxs15/react-native-spinkit/blob/6a53f5be6e0ff630d194c7174a8fba680b058186/index.js)

[Code after](https://gist.github.com/agerson/1f100838fe7aa478a310cf177036f154)

**Comment by hramos** [comment]
It sounds like you edited the file locally (I don't see the change at https://github.com/maxs15/react-native-spinkit/blob/master/index.js). If that is the case, this has no effect because you're deleting `node_modules/` and reinstalling the module using Yarn. You'll want to open a pull request against `react-native-spinkit` so that the change is included upstream.

Closing as this does not appear to be an issue with RN.

**Comment by agerson** [comment]
Sorry, you are right! However, I tried running it before that command and it still produced the error, even though the changes were most certainly in place in the file.
