### ISSUE TITLE
[View] Inconsistent implementation of View between dev and prod

### ISSUE THREAD

**Issue by flashlizi** [facebook/react-native#1521]
The export of class `View`:

*  on `dev=true` - class `View` exports as `ReactClassMixin + ReactComponent`
* on `dev=false` - class `View` exports as  `ReactIOSNativeComponent` (ReactMultiChild + ReactIOSNativeComponent.Mixin + NativeMethodsMixin + ReactIOSComponentMixin)

I think this is because of performance. But when we use `ref` to get a reference to a component, it returns different things on `dev=true` and `dev=false`, it sucks. any idea?

**Comment by ide** [comment]
@flashlizi could you tell us some of the inconsistencies that are giving you trouble?

**Comment by flashlizi** [comment]
For example, In some case I would like to get the current `ReactElement` of a component, usually I can use `component._currentElement` to do so, but:

```
// dev=false
this.refs.xxx._currentElement // ok
this.refs.xxx._renderedChildren // ok

//dev=true
this.refs.xxx._currentElement // undefined
this.refs.xxx._reactInternalInstace._currentElement // it works, but weird
this.refs.xxx._renderedChildren // undefined
```

**Comment by ide** [comment]
@spicyj any thoughts? or know how to get the current element from a component (or if that's something intentionally kept private because it will break in React.next?)

@flashlizi my suggestion for the short-term (since you are using a private API) is to write a helper function that smooths over the differences. But this might break in a future version of React...

```js
function getCurrentElement(component) {
  return component._currentElement || component._reactInternalInstance._currentElement;
}
```

**Comment by flashlizi** [comment]
@ida  This is always a risk, It's better to smooth all the differences.

**Comment by spicyj** [comment]
Instead of rendering `<Monkey ref="monkey" color={this.state.color} />` and accessing `this.refs.monkey._currentElement.props.color`, just access `this.state.color` (for example). We don't have an API for getting the element because it's already exactly what you returned from render. If you really need a copy of the element itself, you can even store it on your instance (`this.foo = <Foo />; return foo;`). We also don't have an API for this because in a future React, stateless components could potentially exist without a public component instance and your ref would just evaluate to `null`.

`._currentElement` and `._renderedChildren` are both implementation details and their use is not supported. So as filed, your bug report would be a wontfix. *That said*, it is possible to make the mistake of accessing `this.refs.monkey.props` without understanding that `.props` on a component instance (that you didn't implement) is not public API, which works in dev but not prod. We ran into this once at FB. Since we don't currently have a good way to indicate that that isn't supported (e.g., by letting composites expose a separate "public instance" with only the properties they want to expose and keeping `.setState`, etc on the internal instance only) we should still fix this bug. I don't know what the overhead of doing the wrapper is. Maybe we can drop it. Maybe we need to be more clever about doing the propTypes check.

**Comment by ida** [comment]
@flashlizi: I think you accidentally pinged me, just saying, so @ide doesn't miss anything :-)

**Comment by flashlizi** [comment]
@spicyj  

There are also some public APIs expose on prod but not on dev. such as `moveChild`, `createChild`, `removeChild` (in `ReactMultiChild.Mixin`) etc.

Is there any way to traverse all children of a component except using `_renderedChildren` ?

**Comment by spicyj** [comment]
Those are also not public, but I understand that they could seem that way.

No, there isn't. You should refactor your code to not need to inspect the rendered tree. Without a more specific problem statement, I can't really suggest how.
