### ISSUE TITLE
React Native remove Default launcher or splash screen in IOS

### ISSUE THREAD

**Issue by hanishsharma** [facebook/react-native#15224]
I am learning react native. When I create react native project, it automatically create a splash or launcher screen in IOS project. My requirement is, I don't want splash or launcher screen. In android, it is possible, but in case of IOS, I am not able to remove the default screen. Please help.

Thanks in advance.

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
