### ISSUE TITLE
Creating Release Build.

### ISSUE THREAD

**Issue by Ethan0007** [facebook/react-native#15235]
Hey Guys,
Did you encounter the said issue below?
I'm trying to publish the App in IOS version but unfortunately I'm unable to move because of the issue. The App is stuck in the Login Screen when trying to authenticate. Also I already updated the Build Configuration into Release.
Or anyone can post here the exact/updated steps or document on publishing the IOS version.
#Thanks
RN 0.43

![error](https://user-images.githubusercontent.com/12542052/28676149-7d2c40a2-731c-11e7-9bc0-1354ae7cec20.JPG)

**Comment by chirag04** [comment]
@facebook-github-bot stack-overflow

**Comment by chirag04** [comment]
Hey @Ethan0007, thanks for posting this! This issue looks like a question that would be best asked on [Stack Overflow](http://stackoverflow.com/questions/tagged/react-native). Stack Overflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.
