### ISSUE TITLE
How to render items of a section in a single row in SectionList

### ISSUE THREAD

**Issue by DevaLee** [facebook/react-native#15335]
### Is this a bug report?
I  want render many  items of a section in a single row
I found a method : in section render One item,the item have many component ,I do not know,wheather it could be reused，I think, when item's count is large,  it could use high internal storage in this way, Does have any other methods to render many  items of a section in a single row

### Have you read the Bugs section of the How to Contribute guide?

(Write your answer here.)

### Environment

1. `react-native -v`:
2. `node -v`:
3. `npm -v`:
4. `yarn --version`:

Then, specify:

- Target Platform:

- Development Operating System:

- Build tools:

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
