### ISSUE TITLE
ViewPagerAndroid peekEnabled property

### ISSUE THREAD

**Issue by numez** [facebook/react-native#15368]
How to properly use the "peekEnabled" property on ViewPagerAndroid ?
`<ViewPagerAndroid
        peekEnabled={true}
      >{this.props.children}</ViewPagerAndroid>`

 
**I want something like this**
![peek](https://user-images.githubusercontent.com/6752432/28971387-0b75aa3c-792c-11e7-9c1c-4c39676d70b7.png)

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

**Comment by koox00** [comment]
@hramos maybe this is indeed a bug,  
seems that `peekEnabled` to work as expected needs `ViewPagerAndroid` to have padding since it sets `clipToPadding` to `false` but child views style is set to `position: absolute` and `right,left,top,bottom: 0` so the parent's container padding has no effect.

**Comment by hramos** [comment]
Can you open a new issue?
