### ISSUE TITLE
Is there an easy way to change the default port when i type in react-native run-android?

### ISSUE THREAD

**Issue by arfaWong** [facebook/react-native#15412]
My steps to change the default port:
1. react-native start --port 9999.
2. react-native run-android.
3. change the port in the app.

Is there an easy way?

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
