### ISSUE TITLE
Simulator is showing the wrong screen

### ISSUE THREAD

**Issue by jordan-miguel** [facebook/react-native#15551]
I've just started a new project with `react-native-init`, the build was successful. However the simulator screen isn't showing the text that from my index.ios.js file. Instead I'm shown an iPhone home screen (see picture).

I've tried rebooting the Simulator.

![screen shot 2017-08-18 at 18 28 21](https://user-images.githubusercontent.com/14114089/29470124-0e18347c-8443-11e7-989b-274fdff72a32.png)

**Comment by jordan-miguel** [comment]
Update - now I'm seeing the following error.

![screen shot 2017-08-18 at 19 05 48](https://user-images.githubusercontent.com/14114089/29471553-4da97e0c-8448-11e7-937c-091456ea3cb8.png)

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
