### ISSUE TITLE
iOS SoftKeyboard return button not working

### ISSUE THREAD

**Issue by symphonicz** [facebook/react-native#15580]
i try to create simple project and use **TextInput**.

I run this project on iOS device but when i type the text in TextInput and press **Return** button on iOS keyboard it's don't hide the keyboard down but on Android Device it's working

this's my code :
` <TextInput 
        style={{ width: 200, height: 40, borderColor: 'gray', borderWidth: 1 }}
        />`

**Comment by SRandazzo** [comment]
try
```
<TextInput blurOnSubmit={true}>
```

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
