### ISSUE TITLE
[Sample project] shouldn't gitignore project.xcworkspace

### ISSUE THREAD

**Issue by itsananderson** [facebook/react-native#1560]
See discussion in https://github.com/facebook/react-native/pull/463 where @ide explained why just xcuserdata should be ignored, rather than all of project.xcworkspace.

In this commit: https://github.com/facebook/react-native/commit/9b513ede77442636b39a7eb283c537eb231b33e6, `project.xcworkspace` was added to the .gitignore, as well as the sample project's _gitignore file.

One place where this is causing issues is Visual Studio Online, which requires an xcworkspace file to configure automated builds. If I understand correctly, the CocoaSpec project also recommends opening the project.xcworkspace instead of the xcodeproj, so it seems like that would also cause issues.

The workaround here is pretty easy... just remove the `project.xcworkspace` line from the `.gitignore` after running `react-native init`, but would it be a better default to not ignore `project.xcworkspace`?

**Comment by ide** [comment]
I think it should be fine but may clash with fb's internal workflow (I'm not sure if this is indeed the case -- just a potential issue) cc @frantic

**Comment by browniefed** [comment]
@brentvatne seems like this can be closed, seems user land fix is easiest. Or maybe it's a react-native init option.

**Comment by brentvatne** [comment]
@browniefed - let's leave this open a bit longer to see what @frantic thinks :)

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/sample-project-shouldnt-gitignore-projectxcworkspace

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
