### ISSUE TITLE
[NavigatorIOS] Unable to change barTintColor and title once it is set

### ISSUE THREAD

**Issue by cem2ran** [facebook/react-native#1561]
I'd like to dynamically change the title and color of the Navigator. I'm testing on 0.6.0-rc
Is this possible or should I dive into the internals? rnplay: https://rnplay.org/apps/kilXnA

![navigatorios](https://cloud.githubusercontent.com/assets/959142/8042308/c2ac04f6-0e1e-11e5-9942-ed453608a463.png)

**Comment by maplebaby** [comment]
+1

**Comment by tantou** [comment]
no one fix this bug? the `resetTo` can't change the title

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/navigatorios-unable-to-change-bartintcolor-and-title-once-it-is-set

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
