### ISSUE TITLE
How can we show Split View Container in react-native in only i Pads and Tablets.

### ISSUE THREAD

**Issue by lavarajallu** [facebook/react-native#15627]
hello, 

i am Developing mobile Application it's showing i pads land scape side Splitview. is it possible in react native like this
[https://developer.apple.com/ios/human-interface-guidelines/ui-views/split-views/](url)

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
