### ISSUE TITLE
how to post 0x31 0x01 0x00 unit8array data using fetch on android platform

### ISSUE THREAD

**Issue by h124551753** [facebook/react-native#15630]
I post unit8array data eg.[0x31, 0x01, 0x00, 0x01] using fetch, i used follow function to

```
function Utf8ArrayToStr(unit8array) {
  var out, i, len, c;

  out = "";
  len = array.length;
  i = 0;
  while(i < len) {
    c = array[i++];
    let temp = String.fromCharCode(c);
    out = out + temp;
  }
  return out;
}
```

parseint unit8array data to a string, then using fetch post it to server on ios work well. but it can not send 0x00 to serve on android;   it seems post data end with 0x00.  
In this case, it can only post [0x31, 0x01] to server successfully。

how can i fixed it...

thinks

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
