### ISSUE TITLE
Official guide build fail with expo

### ISSUE THREAD

**Issue by kaytrance** [facebook/react-native#15673]
I am following exactly the official "Get Started" guide on how to install react-native. The installation with `npm install -g create-react-native-app` went without errors. Then I ran `create-react-native-app AwesomeProject` and it gave me a lot of errors something related to gitmodules:

```
npm ERR! git submodule -q update --init --recursive: shell-init: error retrieving current directory: getcwd: cannot access parent directories: Bad address
npm ERR! git submodule -q update --init --recursive: job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Bad address
npm ERR! git submodule -q update --init --recursive: job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Bad address
npm ERR! git submodule -q update --init --recursive: job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Bad address
npm ERR! git submodule -q update --init --recursive: job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Bad address
npm ERR! git submodule -q update --init --recursive: chdir: error retrieving current directory: getcwd: cannot access parent directories: Bad address
npm ERR! git submodule -q update --init --recursive: /mingw64/libexec/git-core/git-sh-setup: line 342: cd: .git: Not a directory
npm ERR! git submodule -q update --init --recursive: Unable to determine absolute path of git directory
npm ERR! git submodule -q update --init --recursive:
npm ERR! git submodule -q update --init --recursive: shell-init: error retrieving current directory: getcwd: cannot access parent directories: Bad address
npm ERR! git submodule -q update --init --recursive: job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Bad address
npm ERR! git submodule -q update --init --recursive: job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Bad address
npm ERR! git submodule -q update --init --recursive: job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Bad address
npm ERR! git submodule -q update --init --recursive: job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Bad address
npm ERR! git submodule -q update --init --recursive: chdir: error retrieving current directory: getcwd: cannot access parent directories: Bad address
npm ERR! git submodule -q update --init --recursive: /mingw64/libexec/git-core/git-sh-setup: line 342: cd: .git: Not a directory
npm ERR! git submodule -q update --init --recursive: Unable to determine absolute path of git directory
npm ERR! git submodule -q update --init --recursive:
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:204:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:891:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm WARN addRemoteGit  expo/node-websql#18.0.0 resetting remote C:\Users\vadimamo\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expo-node-websql-git-18-0-0-8213877d because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:204:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:891:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\vadimamo\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:expo/node-websql.git C:\Users\vadimamo\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expo-node-websql-git-18-0-0-8213877d: Cloning into bare repository 'C:\Users\vadimamo\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expo-node-websql-git-18-0-0-8213877d'...
npm ERR! git clone --template=C:\Users\vadimamo\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:expo/node-websql.git C:\Users\vadimamo\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expo-node-websql-git-18-0-0-8213877d: Connection reset by 192.30.253.113
npm ERR! git clone --template=C:\Users\vadimamo\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:expo/node-websql.git C:\Users\vadimamo\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expo-node-websql-git-18-0-0-8213877d: fatal: Could not read from remote repository.
npm ERR! git clone --template=C:\Users\vadimamo\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:expo/node-websql.git C:\Users\vadimamo\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expo-node-websql-git-18-0-0-8213877d:
npm ERR! git clone --template=C:\Users\vadimamo\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:expo/node-websql.git C:\Users\vadimamo\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expo-node-websql-git-18-0-0-8213877d: Please make sure you have the correct access rights
npm ERR! git clone --template=C:\Users\vadimamo\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:expo/node-websql.git C:\Users\vadimamo\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expo-node-websql-git-18-0-0-8213877d: and the repository exists.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\vadimamo\\soft\\nodejs\\node.exe" "C:\\Users\\vadimamo\\soft\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\vadimamo\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:expo/node-websql.git C:\Users\vadimamo\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expo-node-websql-git-18-0-0-8213877d
npm ERR! Cloning into bare repository 'C:\Users\vadimamo\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expo-node-websql-git-18-0-0-8213877d'...
npm ERR! Connection reset by 192.30.253.113
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\vadimamo\dev\AwesomeProject\npm-debug.log
```

Please advice how can errors be fixed. Thank you!

**Comment by kelset** [comment]
It looks like something is wrong in the tools you are using, like `node`,  `npm` or  `git`. Which version are you using for each of these tools? Can you update them and try again?

**Comment by ide** [comment]
Looks like you have an issue with your network: `Connection reset by 192.30.253.113`

**Comment by GowthamJeeva** [comment]
npm ERR! git fetch -a origin (git://github.com/expo/node-websql.git) fatal: unab                                                                                                                le to connect to github.com:
npm ERR! git fetch -a origin (git://github.com/expo/node-websql.git) github.com[                                                                                                                0: 192.30.253.113]: errno=No such file or directory
npm ERR! git fetch -a origin (git://github.com/expo/node-websql.git) github.com[                                                                                                                1: 192.30.253.112]: errno=No such file or directory
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config -                                                                                                                -get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:198:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:891:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child                                                                                                                _process.js:226:5)
npm WARN addRemoteGit  expo/node-websql#18.0.0 resetting remote C:\Users\Hi                                                                                                    \AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-expo-node-websql-g                                                                                                                it-18-0-0-9423671b because of error: { Error: Command failed: git -c core.longpa                                                                                                                ths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:198:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:891:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child                                                                                                                _process.js:226:5)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.ori                                                                                                                gin.url' }
npm WARN deprecated connect@2.30.2: connect 2.x series is deprecated


npm Error.. Trying to do create-react-native-app "appname",but it fails as above log..
Can anyone please help me with this

**Comment by kelset** [comment]
@GowthamJeeva looks like you have issues with your internet connection to GitHub. Try to do a simple `git clone` of any repo.

**Comment by GowthamJeeva** [comment]
Ya i tried to clone. That's fine!!!

**Comment by kelset** [comment]
Have a look at this [SO answer](https://stackoverflow.com/a/31745910/1473216), I think it may help.
