### ISSUE TITLE
[Error Message] Cryptic Error Message for a Missing Import

### ISSUE THREAD

**Issue by sreejithr** [facebook/react-native#1569]
I just have a `ListView` with `TouchableOpacity` rows. I set the `dataSource` at `componentWillMount` and it crashes with:

```
Error:
stack: 
  ReactCompositeComponentMixin.updateComponent           index.ios.bundle:16483
  ReactPerf.measure.wrapper [as updateComponent]         index.ios.bundle:4931
  ReactCompositeComponentMixin.receiveComponent          index.ios.bundle:16392
  Object.ReactReconciler.receiveComponent                index.ios.bundle:5059
  Object.ReactChildReconciler.updateChildren             index.ios.bundle:20007
  ReactMultiChild.Mixin._updateChildren                  index.ios.bundle:19772
  ReactMultiChild.Mixin.updateChildren                   index.ios.bundle:19746
  ReactIOSNativeComponent.Mixin.receiveComponent         index.ios.bundle:18104
  Object.ReactReconciler.receiveComponent                index.ios.bundle:5059
  ReactCompositeComponentMixin._updateRenderedComponent  index.ios.bundle:16629
 URL: undefined
 line: undefined
 message: Cannot read property 'context' of null
```
I hunt around for 20 minutes to find that I haven't required `TouchableOpacity`. Shouldn't the error messages be meaningful?

**Comment by rxb** [comment]
Thanks for posting this issue. Just ran into the same situation and would have been scratching my head all day.

**Comment by browniefed** [comment]
@brentvatne same as https://github.com/facebook/react-native/issues/2217 could consolidate to one.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/error-message-cryptic-error-message-for-a-missing-import

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
