### ISSUE TITLE
Touchable talkback accessibility hints

### ISSUE THREAD

**Issue by victor-carvalho** [facebook/react-native#15699]
When we set "clickable" on Android, it reads a button like this:
> My label, Button. Double tap to activate.

But I when I use a React Native Button, Talkback says just:
> My label, Button.

There is anyway to set that the view is "clickable" like in Android to give these hints?

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
