### ISSUE TITLE
[XmlHttpRequest] xhr.upload.onprogress not works 

### ISSUE THREAD

**Issue by 1stman** [facebook/react-native#15709]
i trying to upload video with youtube v3 api, and have some dilemma. When i use `FormData` , `xhr.upload.onprogress` is working. But then youtube api return processing error, because FormData add some data to file object. So, i use something like `xhr.send({uri: url});` and it works, video is uploading, BUT `xhr.upload.onprogress` stopped working. I still don't know why...
P.S. sorry for my ugly english

1. `react-native v0.47.2`:
2. `node v8.2.1`:
3. `npm v5.3.0`:

Then, specify:

- Target Platform: Android
- Development Operating System: MacOS
- Build tools: Android SDK

**Comment by hramos** [comment]
@facebook-github-bot stackoverflow

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

**Comment by 1stman** [comment]
@hramos do yo really think, it's not a bug if `xhr.upload.onprogress` isn't working without `FormData`?

**Comment by hramos** [comment]
Without seeing additional information, I can't arrive at that conclusion. Feel free to open a new issue, making sure to fill out the entire template.
