### ISSUE TITLE
HTML entity codes of Special Text characters getting Currency Symbols

### ISSUE THREAD

**Issue by lavarajallu** [facebook/react-native#15703]
Hello, 
How it is Possible to find out the Currency Symbol like,
I mentioned if i am given like . ` &pound;`(this is HTML entity ,how it is Converted to Currency Symbol like as pound symbol `£` ).

**Comment by levibuzolic** [comment]
@lavarajallu I don't think your question is strictly related to React Native, but if I understand your problem correctly you should be able to use a library like [html-entities](https://www.npmjs.com/package/html-entities) to decode/encode HTML Character Entities.

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

**Comment by lavarajallu** [comment]
@levibuzolic  Thanks a lot.......
