### ISSUE TITLE
Is expected that RCTFont file in react module has a .mm extension

### ISSUE THREAD

**Issue by humbertojuliao3** [facebook/react-native#15727]
I only asking that, because I don't find any other example of that

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
