### ISSUE TITLE
Modify the android project structure default name，like 'app'

### ISSUE THREAD

**Issue by zfn2010** [facebook/react-native#15787]
how to configure android project name if i don't use the default name 'app'

**Comment by Ehesp** [comment]
Why do you need to change it?

**Comment by zfn2010** [comment]
@Ehesp  
two reason
1.I use RN integration with existing Apps,I do not want to change the name that already exists
2.The android project has multiple modules name, means that I rename all the modules into 'app',it's trouble

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
