### ISSUE TITLE
ScrollView contentOffset bug

### ISSUE THREAD

**Issue by vivalaakam** [facebook/react-native#15808]
Hi! in RN 0.48.1 doesn`t work contentOffset when component is initialized.
Here is example for reproduction https://github.com/vivalaakam/rn_issue

In this example after initialize i will be see second screen, named 'Welcome to screen #2'

In version 0.47.2 it work as well

1. `react-native -v`
```
react-native-cli: 2.0.1
react-native: 0.48.1
```
2. `node -v`
```
v8.4.0
```
3. `npm -v`
```
5.4.0
```
4. `yarn --version`
```
0.27.5
```

**Comment by stage88** [comment]
This is probably related to 1d22f8fb27e9432e357401ce6f6cede4d710472c, the scenario the commit addresses doesn't apply to me so i have replaced line 319 in node_modules/react-native/React/Views/RCTScrollView.m with 

`// self.contentOffset = CGPointMake(
//   MAX(0, MIN(originalOffset.x, fullContentSize.width - boundsSize.width)),
//   MAX(0, MIN(originalOffset.y, fullContentSize.height - boundsSize.height)));
self.contentOffset= originalOffset;`

That fixes my negative offset with refresh control problem, it will have to do until the issue is fixed.

**Comment by shergin** [comment]
Well, the problem with this issue is that `contentOffset` prop should not exist in the first place. (And it does not exist on Android.)
Could we use `scrollTo` method instead?

**Comment by janicduplessis** [comment]
@shergin I think we should try landing https://github.com/facebook/react-native/pull/15670 to fix that regression

**Comment by wschurman** [comment]
From what I can tell, the design of the Android refresh control is sufficiently different enough to not need an initial offset. `scrollTo` works for offsets in general but I'm not sure how to get it to work in the initial paint. The only implementation I was able to figure out got a bit messy and has a delay since the `scrollTo` method can only be run once the ref is set. Any ideas?

```js
_scrollViewRef: any;
_didExecuteInitialScrollTo: bool;

_tryInitialScroll() {
  if (!this._didExecuteInitialScrollTo && this._scrollViewRef) {
    this._didExecuteInitialScrollTo = true;
    requestAnimationFrame(() => { // doesn't seem to work on RN 0.48 without this, works without on RN 0.47 though
      this._scrollViewRef.scrollTo({ x: 0, y: -60, animated: false });
    });
  }
}

render() {
  return (
    <ScrollView
      ref={(view) => { 
        this._scrollViewRef = view; 
        this._tryInitialScroll(); 
      }}
    />
  );
}
```

**Comment by krizpoon** [comment]
I have similar problem and solved it with:

```
self.contentOffset = CGPointMake(
    MAX(-contentInset.left, MIN(originalOffset.x, fullContentSize.width - boundsSize.width)),
    MAX(-contentInset.top, MIN(originalOffset.y, fullContentSize.height - boundsSize.height)));
```

**Comment by henrikra** [comment]
@shergin Could you explain more why `contentOffset` prop should not exists? For example now on Android I have to do weird hacks to init scroll view's position to something that I want.

**Comment by skv-headless** [comment]
@shergin android `ScrollView` doesn't have content offset bug `ViewPager` has.

**Comment by shergin** [comment]
@henrikra It was discussed here several times. And yes, it is kinda controversial; we will not introduce breaking change before we have a consensus, but I pesonally think this prop should be removed.
The problem with this props is that it is unclear when (at which stage) we have to enforce/apply the offset, it causes bugs and unexpected behaviors. (And, I assume, the situation became much worse with async Fiber.) Such kind of momentum values should be represented as methods, not props.

**Comment by henrikra** [comment]
@shergin Okay so what would be ideal api for this? Do you have suggestions? Since we have to do the offsetting on native level so there isn't any flickering like now :/
