### ISSUE TITLE
FlatList initialNumToRender appears to have no effect

### ISSUE THREAD

**Issue by burennto** [facebook/react-native#15807]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`: 0.48.1
2. `node -v`: 8.4.0
3. `yarn --version`: 0.27.5

- Target Platform: iOS & Android
- Development Operating System: macOS 10.12.6

### Steps to Reproduce

1) Pass an array of 30 items to FlatList as the data, specifying an `initialNumToRender` of 5
2) Log to console as part of each `renderItem`
3) Render the FlatList but don't scroll
4) Check debug output

### Expected Behavior

Only the first 5 (or few) items should render, and the remaining should only render when the FlatList scrolls.

### Actual Behavior

Seems like the `initialNumToRender` is initially respected, but for some reason every item is then rendered before the FlatList is scrolled.

Log:

```
renderItem 1
renderItem 2
renderItem 3
renderItem 4
renderItem 5
renderItem 1
renderItem 2
renderItem 3
renderItem 4
renderItem 5
renderItem 6
renderItem 7
renderItem 8
renderItem 9
renderItem 10
renderItem 11
renderItem 12
renderItem 13
renderItem 14
renderItem 15
...
```

### Reproducible Demo

https://github.com/burennto/FlatListRenderBugDemo.git

Build and inspect the debug console.

Thank you.

**Comment by wuyunqiang** [comment]
Maybe you add  windowSize={5} will be ok.

**Comment by burennto** [comment]
@wuyunqiang Thanks for the suggestion but it didn't seem to make a difference...

**Comment by truongthanh1303** [comment]
I have the same issue!

**Comment by iampmat** [comment]
same issue!

**Comment by bdrobinson** [comment]
I'm no expert but as I understand it I think you're seeing the correct behaviour. After `initialNumToRender` rows have been rendered, `FlatList` will release the JS thread, allowing the user to interact with the page. However, `FlatList` will then starts rendering off-screen rows in batches (using a `setInterval`), so that when the user does start scrolling, a decent-sized buffer has already been built up so they don't see any blank rows.

The documentation is quite sparse for `VirtualizedList`, but if you look at the props it takes you can get an idea for how it works – have a google for `maxToRenderPerBatch`, `updateCellsBatchingPeriod` and `windowSize`.

**Comment by TalG18** [comment]
Same issue here, initialNumToRender has not effect.
`
      <FlatList keyboardShouldPersistTaps='always'
data={this.props.sections} 
keyExtractor={(l) => l.key}
                removeClippedSubviews={true}
                renderItem={this._renderItem.bind(this)}
                initialNumToRender={1}
      />
`

**Comment by Hermanya** [comment]
As @bdrobinson pointed out, `initialNumToRender` on its own is not enough. You also need to set `maxToRenderPerBatch` and `windowSize`.
It's very odd that the first two variables are not derived from `windowSize` automatically.
