### ISSUE TITLE
Webview don't display image

### ISSUE THREAD

**Issue by navata** [facebook/react-native#15861]
This is my code and it can't display image.
```
<WebView
   source={{html: `<img src='//i.pinimg.com/564x/41/76/2e/41762e489565279690334d5d38815b0f.jpg'>` }}
   style={{flex: 1}}
   javaScriptEnabled={true}
>
</WebView>
```

But I change src='https://i.pinimg.com/564x/41/76/2e/41762e489565279690334d5d38815b0f.jpg' and it work.
Why? Please help me

**Comment by RD1991** [comment]
May be a simple example for this if you try searching the string 
'//i.pinimg.com/564x/41/76/2e/41762e489565279690334d5d38815b0f.jpg' on URL bar (Chrome) then it will search in local system, but when you search using 
'https://i.pinimg.com/564x/41/76/2e/41762e489565279690334d5d38815b0f.jpg' or 
'http://i.pinimg.com/564x/41/76/2e/41762e489565279690334d5d38815b0f.jpg' it searches on the web. 

So instead of passing the string without HTTP just prepend it with http. 

I think it is happening because RN tries to search in your code/directory when http is not passed.

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
