### ISSUE TITLE
[Navigator] Navigator transition bug

### ISSUE THREAD

**Issue by magicismight** [facebook/react-native#1601]
The View which will be replaced in the Navigator didn`t animate to disappear,
It disappear once the transition starts.

`react-native\Libraries\CustomComponents\Navigator\Navigator.js`
```javascript
_resetUpdatingRange: function() {
  //this.state.updatingRangeStart = 0;
  this.state.updatingRangeLength = this.state.routeStack.length;
},
```
After I removed the first line,it works fine.

**Comment by ardalann** [comment]
Why are you setting ``this.state`` property directly instead of using ``this.setState`` method?

**Comment by ericvicenti** [comment]
@magicismight It is difficult to see what the problem is based on your description. The navigator is able to animate views away, but you might be using it differently than we do. Can you show a simplified example of this bug on rnplay.org, and describe what you expect to happen compared to what is actually happening?

@ardalann, that snippet is from RN's Navigator.js. This technique of setting state directly isn't recommended, but it can be used to mutate state while avoiding a re-render. Rendering/reconciliation can be very slow and interfere with the navigator animations/gestures. This "updating range" logic is old and we have better optimization techniques which we will switch to in the future.

**Comment by asamiller** [comment]
I ran into this issue and traced it back to my `onWillFocus` handler. I was calling `setState` inside the `onWillFocus` handler. After taking out the `setState` call, the components stopped disappearing at the beginning of the transition.
