### ISSUE TITLE
React native Image prefetch

### ISSUE THREAD

**Issue by robinlery** [facebook/react-native#16023]
### Is this a bug report?

No

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

  Environment:
    OS:  macOS Sierra 10.12.6
    Node:  7.7.3
    Yarn:  1.0.1
    npm:  4.1.2
    Watchman:  4.7.0
    Xcode:  Xcode 8.3.3 Build version 8E3004b
    Android Studio:  2.3 AI-162.4069837

  Packages: (wanted => installed)
    react-native: 0.47.0
    react: 16.0.0-alpha.12

  Target Platform: iOS, Android

### Problem

I am having difficulties to understand Image prefetch. In the [doc's ](http://facebook.github.io/react-native/docs/image.html#prefetch)there is not much explanation about it:

> Prefetches a remote image for later use by downloading it to the disk cache

Could you please help me understand the following about Image prefetch:

1. Suppose a user uploads a profile image, and the image's URL is stored in the AsyncStorage.

  - Should I run `Image.prefetch(UserStore.profileImageUrl)` only once after successful upload. And use prefetched image in the components normally like `<Imagesource={{uri: UserStore.profileImageUrl}}/>`

  - Or should I always run `Image.prefetch(UserStore.profileImageUrl)` before using that image in the component, then only run `<Imagesource={{uri: UserStore.profileImageUrl}}/>`

2. Suppose, later on, the user changes their profile image by uploading a new image and after successful upload, I will prefetch the new image. Will the previously cached image still exist on the disk?

  - If yes, won't it occupy a lot of space in the device if there are lots of prefetched images?

3. Is there any way to manually remove the prefetched image from the disk?

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
