### ISSUE TITLE
How to pass query parameters in react native WebSocket connection

### ISSUE THREAD

**Issue by KakarN** [facebook/react-native#16041]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

  Packages: (wanted => installed)
    "react": "16.0.0-alpha.12",
    "react-native": "^0.47.0",

  Target Platform: iOS, android

### Steps to Reproduce

I have a server where I can make a WebSocket connection. When a device makes a WebSocket connection (when the app starts/splash screen), the server looks for the query parameter in the URL, which has the auth token of the user and if the token is correct, the connection is approved, else connection is rejected.

This is how the code looks on the react native client side:

```
const socket = new WebSocket(`ws://${website}/?token=${value}`);
socket.onmessage = (messageEvent) => {
    console.log('>>> socket on message:', messageEvent.data);
};
socket.onopen = function () {
    socket.send("hello world connection");
};
socket.onclose = () => {
    console.log('Socket disconnected');
};
```

This works fine in my iOS emulator, and the iOS emulator has a WebSocket connection to mine server. However, I have an android phone (testing via LAN), and when I open the app, I get an error saying:

> Unable to set ws://192.xxx.xx.xx/token=aut sfiseft2sefsefs..... as default origin header

But, if I remove the query param from the URL

`const socket = new WebSocket(`ws://${website}`);`

This works fine, but since I cannot pass the token in the query params, I get an error from the server.

How can I pass query parameters to the WebSocket connection in android? Am I missing something?

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

**Comment by junmich** [comment]
I have the same problem. Anyone have a solution? thanks
