### ISSUE TITLE
flex: 1 changes the height of the View

### ISSUE THREAD

**Issue by DavitVosk** [facebook/react-native#16065]
### Is this a bug report?

No

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Steps to Reproduce

1. flex:1 changes the height of the View container (I am using onLayout prop on the View)

### Expected Behavior

The onLayout prop of the View had to be returned the actual height of the mobile (namely it should be the same as Dimensions.get('window').height) 
### Actual Behavior
At first it returns Dimensions.get('window').height and then returns Dimensions.get('window').height minus 25px

I want to get the mobile height using onLayout prop of container View. The returned data is 25px less than the original height of the mobile (saying original I meant SCREEN_HEIGHT = Dimensions.get('window').height). Actually I need onLayout prop to calculate children View height, but the investigation showed that I receive the issue as described above. Please help to solve the problem. 
I also attach the log of 'SCREEN_HEIGHT' and 'event.nativeEvent.layout': https://prnt.sc/gofryl

### Reproducible Demo

https://gist.github.com/anonymous/349ce590d6a7a9a1da607fa3932792db

**Comment by M-Izadmehr** [comment]
**Short Answer:**
There is no problem here, you only did not notice `NavBar`. The onLayout gives you total the hight of your specefic View (i.e. total height of page minus the hight of `NavBar`).
**Complete Answer:**
The purpose of `flex:1`  is to:
    `To specify the length of the item, relative to the rest of the flexible items inside the same container.`
Consequently, when you use `flex:1` on a `View`, the expected behaviour is to fill the remaining area of the page proportionately. 
For example, if you have two `View`s in the page,
 1- header component with specefic height (say, 25px)
 2- the `View` of the page, with `flex:1`,
The View is going to fill all the page below header, Therefore when you use `onLayout` to get dimension of the `View`, you expect:
 *  the height to to be 25 px less than ` Dimensions.get('window').height`, 
 * and the width to be equal to ` Dimensions.get('window').width`

which is what happens in your case.
If  you delete the `NavBar` component from your page (and its View) by writing `flex:1` for the other view the result will be equal to ` Dimensions.get('window').height`.

**Comment by DavitVosk** [comment]
Thanks for your answer. But unfortunately NavBar height is not problem here. For example, if even I take simple View (not contatining any items) and gives {flex: 1} style to this View, then onLayout prop at first returns 592px height, and after several milliseconds it returns 567px (namely 592px - 25px). This data was taken for my mobile. I also had tested on genymotion mobile, and in this case again I receive 2 heights: one is the same as Dimensions.get('window').height, and the second one is less than that value (but in this case it is less with 24px). So I think, these calculations are based on mobile real height.

**Comment by DavitVosk** [comment]
Yes you are right, the onLayout should give total the hight of specefic View (i.e. total height of page minus the hight of NavBar), but I don't receive this. Namely, if Dimensions.get('window').height = 592px, and NavBar height is 70px, so onLayout prop at first returns 522px (592px-70px) AND after this it returns 497px (522px-25px). To note, my container View contains only 2 Views: one for NavBar and second View, for which I want to apply onLayout prop
