### ISSUE TITLE
[fetch] How can I override response's charset?

### ISSUE THREAD

**Issue by castlesix** [facebook/react-native#1614]
When response's charset is empty, responseText is null.

**Comment by nicklockwood** [comment]
Hmm. It should default to UTF-8 if not specified.

Can you tell me the URL that you're trying to download?

**Comment by castlesix** [comment]
URL is 'http://www.jgkids.or.kr/toy/toy_list_sadang.asp'.

Content-Type is text/html. charset is null.

![2015-06-17 10 25 44](https://cloud.githubusercontent.com/assets/2731297/8198004/4254cec8-14db-11e5-9dea-7dabe78a2dee.png)

By modifying RCTDataManager.m, the response is OK.

**Comment by satya164** [comment]
Hey and thanks for reporting this!

There's an awesome place to ask question like this one: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see your question, you can vote on answers and mark question as answered etc. This lets us keep a list of bug reports and feature requests on github and especially [Product Pains](https://productpains.com/product/react-native/?tab=top) (again, with voting which is really nice).

If you think StackOverflow works for you please consider posting there instead and closing this issue.

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)
