### ISSUE TITLE
[Bridge] is it possible to get JavaScriptCore's JSContext somehow?

### ISSUE THREAD

**Issue by plandem** [facebook/react-native#1618]
Why do i need it? Sometimes i just want to use javascript directly and don't create wrappers to emit events to/from JS to get values.

```
class SimpleApp extends React.Component {
	render() {
		return (
...view
		)
	}

	validate(data) {
		return -100;
	}
}
```

For example, i would like to get value from 'SimpleApp.prototype.validate'. Just want to call it directly.

In my case, i have one bundle with visuals and some functions that has no any connection to visual part. Right now we have only:
```
React.AppRegistry.registerRunnable('validate', function(data) { return -100; });
```
and call it from objective-c:
```
[_bridge enqueueJSCall:@"AppRegistry.runApplication" args:@[@"validate", @[@2, @2]]]
```
But current implementation does not allow to get value from js. So my question again - is it possible to get JSContext to do next:
```
JSValue *validator = context[@"SimpleApp.prototype.validate"];
JSValue *result = [validator callWithArguments:@[@5] ];
```

**Comment by ide** [comment]
@plandem It's not very well supported at the moment. You will have issues with React's event loop if the JS functions you invoke directly from Obj-C do any kind of async work. Directly using the JSContext will bypass the code path that React takes to start an iteration of its event loop. Also if your JS throws an unhandled error you may have to handle it yourself. And even though JSC is mostly thread-safe, you should make sure to use the JSContext only on the same JS thread as the one that React will use.

But since you asked... currently the best approach is to subclass RCTContextExecutor and define `init` to return `-[super initWithJavaScriptThread:globalContextRef:]`, which allows you to inject your own JSContextRef as the second argument. Expose this JSContext/JSContextRef to the rest of your app via NSNotificationCenter or a global variable. Then set up an RCTBridge like so:

```js
RCTBridge *bridge = [RCTBridge alloc];  // warranty not included
bridge.executorClass = [YourCustomExecutor class];
bridge = [bridge initWithBundleURL:url moduleProvider:nil launchOptions:launchOptions];

RCTRootView *root = [[RCTRootView alloc] initWithBridge:bridge moduleName:@"YourAppKey"];
```

I'm going to close this because as you can see it's really not well-supported but it does work if you know what you're doing and are willing to dive into the full stack.

**Comment by plandem** [comment]
Thanks, for help. Yes, i have reasons to use it. It's not for any heavy tasks/async and etc. In my case i just need to move some 'value formatters' to JS side, because some visual parts will be there. But in other cases i will need just 'value formatters' without any visual parts. So i want to use same way - formatters from JS. It's mostly native app and only some parts ("modules") in React
