### ISSUE TITLE
react-native-git-upgrade does not respect android package name

### ISSUE THREAD

**Issue by nikolaik** [facebook/react-native#16217]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

```
Environment:
  OS:  Linux 4.10
  Node:  6.10.3
  Yarn:  1.1.0
  npm:  3.10.10
  Watchman:  4.7.0
Error: unable to print environment info
{ Error: not found: xcodebuild
    (snip stacktrace)
```

### Steps to Reproduce

1. Run `react-native init MyProject --version 0.48.3`
2. Rename your `com.myproject` package / applicationId to `com.my.new.project` according to this SO answer: https://stackoverflow.com/a/37390022/543864
3. Run `react-native-git-upgrade` to upgrade to 0.49.1 (or higher) which failes silently like described in #12112

There is a similar issue #11163 from when MainApplication.java was introduced in 0.29.

### Expected Behavior

Running react-native-git-upgrade in step 3 uses the current Android package name by either parsing AndroidManifest.xml or accepting the package name as a param (ie. `react-native-git-upgrade --package com.my.new.project` and patches MainApplication.java in the correct path (ie. `com/my/new/project`).

It looks like `react-native init` took a package param in version [0.38](https://github.com/facebook/react-native/blob/0.38-stable/local-cli/generator-android/index.js) which was later removed. That code could be used as a basis for either a `--package` option to react-native-git-upgrade or parsing AndroidManifest.xml. What is the best approach?

### Actual Behavior

Running `react-native-git-upgrade` in step 3 fails silently like described in #12112 because it tried to patch a file that is not in the git index. It tried to patch `com/myproject/MainApplication.java` instead of `com/my/new/project/MainApplication.java`.

### Reproducible Demo

Follow the steps under Steps to Reproduce.

**Comment by richardgirges** [comment]
I just ran into this same issue. I had to rename my android package to make react-native-git-upgrade happy, do the upgrade, then rename it back. Not a recommended solution.

**Comment by seratonik** [comment]
Same issue here, attempted a manual upgrade and having some troubles. Will try @richardgirges's workaround.

**Comment by nikolaik** [comment]
My workaround (this time) was to copy my existing MainApplication.java to the path react-native-git-upgrade expects, run the upgrade and then copy the file back to the correct path.

**Comment by SirNeuman** [comment]
yeah... @nikolaik's workaround worked for me. Not sure where react-native-git-upgrade is getting the old package name from. I couldn't find any references to the old name of my package anywhere in my code

**Comment by jordanmkoncz** [comment]
I'm experiencing the same issue as I changed my Android package name to be in the form `com.companyname.appname` instead of the default form `com.appname` that `react-native init` generates.

@SirNeuman `react-native-git-upgrade` gets the package name by looking at the `name` value in your `package.json`. It assumes that this matches the name of your app, and then it also assumes that your Android package name is still in the form that it was when the project was generated, i.e. `com.appname`.

It seems like it should be possible to update `react-native-git-upgrade` so that it is able to figure out your *actual* package name; it could just pull this from your `android/app/src/main/AndroidManifest.xml` file since the location of that file does not change (unlike the location of the `MainActivity.java` file) and the `manifest` node has a `package` attribute with the correct value of the Android package name.

In the meantime, I was also able to use the workaround posted by @nikolaik.

**Comment by nikolaik** [comment]
This will keep affecting people for every update of the `MainApplication.java` template file. I like  @jordanmkoncz 's approach.

**Comment by jordanmkoncz** [comment]
Yeah this issue should definitely remain open. It seems like it should be fairly easy/straightforward to fix (at least with my suggested solution of inspecting `android/app/src/main/AndroidManifest.xml`) and would save people from having to do these annoying workarounds every time they upgrade React Native.

**Comment by ntomallen** [comment]
Is there a place someone could submit a PR to try to fix this issue?
