### ISSUE TITLE
CameraRoll.saveToCameraRoll saves animated gif as static images

### ISSUE THREAD

**Issue by mferranti** [facebook/react-native#16223]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes
### Environment

  Environment:
    OS:  macOS Sierra 10.12.6
    Node:  8.4.0
    Yarn:  Not Found
    npm:  5.3.0
    Watchman:  4.5.0
    Xcode:  Xcode 9.0 Build version 9A235
    Android Studio:  Not Found

    Packages:
      react: 16.0.0-alpha.12
      react-native: 0.47.2
    
   Target Platform: iOS (10.3)

### Steps to Reproduce

(Write your steps here:)

1. Create new project
2. Save a gif with camera roll. `CameraRoll.saveToCameraRoll('https://k60.kn3.net/B/1/5/9/2/D/971.gif');`

### Expected Behavior

The gif should be animated.

### Actual Behavior

The gif was saved in photo album but is an static image. It hasn't got animation and only the first frame is shown.
Maybe is related with #16117
 
### Reproducible Demo

  Here is an example code to reproduce. But snack does not allow to see the images of the device. I think.
  https://snack.expo.io/BkAe8yE2Z

**Comment by ConorKelleher** [comment]
+1

**Comment by tafty** [comment]
I've also found this to be the case. Works fine on Android.

```
    react: 16.0.0-alpha.12
    react-native: 0.47.1
```

**Comment by nikhammerellis** [comment]
+1

**Comment by nikhammerellis** [comment]
I too am having the static gif issue. I have gifs stored in firebase storage and have them displaying properly in a react native iOS app and in a React CMS for the iOS app.

I am wondering if gifs are considered movies? Because in the CameraRoll Documentation it says this: "On iOS, the tag can be any image URI (including local, remote asset-library and base64 data URIs) or a local video file URI (remote or data URIs are not supported for saving video at this time)."

It's that last bit, "remote or data URIs are not supported for saving video at this time", that I am starting to think is the problem with gifs stored "remotely" on firebase. Appears to only save the first frame of the gif.

**Comment by ConorKelleher** [comment]
+1

**Comment by pianzinan** [comment]
+1

**Comment by shenjo** [comment]
+1

**Comment by adrianboisclair** [comment]
+1

**Comment by wxsms** [comment]
+1

**Comment by fearmear** [comment]
Reproduces on 0.57.4

**Comment by cpojer** [comment]
This issue has been moved to react-native-community/react-native-cameraroll#16.

**Comment by yanjie311** [comment]
+1
