### ISSUE TITLE
Update react-native

### ISSUE THREAD

**Issue by wtfil** [facebook/react-native#1623]
Hi!

First of all thank you for amazing technology!
I have some with issue with updating `react-native` for existing app. I would like to have latest native part of `react-native` but I don't know how to do it.

Right now I have only one solution:
1) `react-native init NewApp`
2) copy all `js` files from old app to new one, configure build steps in xcode.

Is there any other production solution for this?
Thx!

**Comment by ide** [comment]
If you're familiar with Xcode projects and CocoaPods then downloading react-native from npm and using the podspec under node_modules works well since you just regenerate the Pods project whenever you update react-native. You'll have to run the packager manually too.

If that isn't something you're familiar with then the approach you've outlined seems the most robust to me but is often unnecessary. I would try to upgrade the react-native npm package, see if the project still compiles, and create a new project if that doesn't work.

**Comment by wtfil** [comment]
@ide thx for replay!
I am totally nooby with xcode, but  now I at least have keywords for googling:)

**Comment by wtfil** [comment]
@ide just updated react with npm (changed version from `0.5.0` to `git@github.com:facebook/react-native.git`) and everything works now with new `RCTPromiseRejectBlock` and  `RCTPromiseResolveBlock` features.
Any xcode manipulations weren't needed!
Closing  issue
