### ISSUE TITLE
Animated.event() with useNativeDriver returns an object, not a function

### ISSUE THREAD

**Issue by Leeds-eBooks** [facebook/react-native#16250]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  7.8.0
  Yarn:  1.0.1
  npm:  4.2.0
  Watchman:  4.7.0
  Xcode:  Xcode 9.0 Build version 9A235
  Android Studio:  Not Found

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.1 => 0.49.1

  Target Platform: iOS (11)

### Steps to Reproduce

I just hit https://github.com/facebook/react-native/issues/13377 but with `onScroll` on a `ScrollView`. [This line](https://github.com/facebook/react-native/blob/f9be64aea05fe76dd93b72ec7e49e744988e0935/Libraries/Animated/src/AnimatedImplementation.js#L500) checks if I have used `useNativeDriver`, and if so, returns the `AnimatedEvent` object, not a function. Therefore, any prop expecting a function – `onScroll`, `onPanResponderMove` or any other – will throw an error.

Is this a bug or expected behaviour? If `useNativeDriver` cannot be used with any prop expecting a function, this should be documented.

**Comment by DragonRaider5** [comment]
This is expected behaviour, as the PanResponder doesn't support native animations yet, because it's implemented in pure JS - hence it can't generate native events, as it **has** to pass the JS to native bridge to update the animations (because it handles touches in JS). Furthermore it even has to pass the bridge twice and performs worse than standard JS animations (which already can be pretty laggy), due to the fact, that the touch also has to be passed to the JS side, making it like this:

Native                 |   JS
Touch Event ->  |   handle touch
                            |   adjust animation
Animate               | <- new animated value

Problem: The communication over the JS - native bridge is pretty expensive. You could try using something like https://github.com/wix/react-native-interactable (it says experimental, but in my experience it's quiet stable - don't quote me on that tho), which has native implementations with animations, callbacks and configurable physics so you can do quiet a lot with it.

**Comment by Leeds-eBooks** [comment]
@DragonRaider5 Thanks for your reply, but I think this is still unexpected behaviour. My use case doesn't involve `PanResponder` at all.

`Animated.event()` with `useNativeDriver` doesn't work with `onScroll` either, and the docs specifically say [here](http://facebook.github.io/react-native/docs/animations.html#using-the-native-driver) that:
>The native driver also works with Animated.event. This is specially useful for animations that follow the scroll position as without the native driver, the animation will always run a frame behind the gesture due to the async nature of React Native.

Just to be totally clear: the bug I am reporting is that **`useNativeDriver` cannot currently be used with any prop expecting a function, including `onScroll`**.

**Comment by DragonRaider5** [comment]
Hi,
are you using an `Animated.ScrollView`?

**Comment by Leeds-eBooks** [comment]
Amazing, that fixed it! Thanks so much. I had no idea I had to use an `Animated` component on the source of the event as well as the target of the animation (I am not animating the `ScrollView` itself).

I think maybe this should be highlighted in the docs? The docs currently say "Only animatable components can be animated", they don't mention that the source of `onScroll` events should also be `Animated`.

**Comment by DragonRaider5** [comment]
You're welcome 👍  it already says so in the docs, look closer at the given example - but you're right, it's a tiny detail easy to overlook. Highlighting might help there.
Happy to have helped 😃

**Comment by ryanab** [comment]
Same issue same solution; thanks @DragonRaider5

**Comment by MSSPL-PiyaleeMaiti** [comment]
@DragonRaider5 If I use `Flalist` for animated then can I use `Animated.FlatList` ?  Is this `Animated.FlatList`  supported fully with others features of FlatList?
