### ISSUE TITLE
How can I call Text Selector on a Text component?

### ISSUE THREAD

**Issue by gHashTag** [facebook/react-native#16338]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Steps to Reproduce

How can I call Text Selector on a Text component?

### Expected Behavior

I do not know how to solve this problem

### Actual Behavior

I tried to find libraries, but did not find
In the end I want to get this:
![text-selection android-9f56b6e3](https://user-images.githubusercontent.com/6774813/31509464-412ea400-af8a-11e7-907a-4d0e5bc029ea.gif)

### Reproducible Demo

How to be?

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
