### ISSUE TITLE
RotateY does not work on ios

### ISSUE THREAD

**Issue by thg303** [facebook/react-native#16366]
### Is this a bug report?
Yes.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes.

### Environment
```
Environment:
  OS:  macOS Sierra 10.12.6
  Node:  8.2.1
  Yarn:  0.27.5
  npm:  5.3.0
  Watchman:  4.9.0
  Xcode:  Xcode 8.3.3 Build version 8E3004b
  Android Studio:  Not Found

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: 0.48.1 => 0.48.1
```

### Steps to Reproduce
1. create a new react-native app
2. add this to the style of a `view` component:
```
<View style={{transform: [{rotateY: '45deg'}]}} >
...
</View>
```

### Expected Behavior
Correct behaviour is to rotate the view around Y axis, which is what we see in the android build.
https://ibin.co/3dkJexd90tBA.jpg

### Actual Behavior
 it sort of scales in Y axis instead of rotating. looks like the `transform` attribute in the style is not processed well. 
https://ibin.co/3dkUu8yBvCE9.jpg

### Reproducible Demo
https://snack.expo.io/HJYdqtR2Z

**Comment by Kureev** [comment]
Hi @thg303!

I just checked the demo you shared, looks fine to me:
![image](https://user-images.githubusercontent.com/2273613/31578684-98a83154-b126-11e7-882e-515bf8a4d9d7.png)

**Comment by thg303** [comment]
so is it the ios simulator bug @Kureev, can you confirm it please?

**Comment by Kureev** [comment]
Hi @thg303! Yeah, indeed, seems to be reproducible on iOS

**Comment by aamctustwo** [comment]
This appears to be a bug.

On iOS, you need to specify the perspective (using the `m34` property on the transform matrix), which is why simply using `CATransform3DRotate` on the identity matrix is insufficient.

As an example, look at how Apple set it up in their example for `CATransformLayer`: https://developer.apple.com/documentation/quartzcore/catransformlayer

I have created an Xcode Playground in which you can use for exploration. It sets up a similar Rotate on Y axis by 45-degree transform, but adds the `m34` value to the matrix. This example can be found: https://github.com/aamctustwo/RotationExample

React-Native creates this transform in: https://github.com/facebook/react-native/blob/1e8f3b11027fe0a7514b4fc97d0798d3c64bc895/React/Views/RCTConvert%2BTransform.m

**Comment by aamctustwo** [comment]
@thg303 As a work-around, you can specify a perspective value (before the rotation) to get a similar looking result on both Android and iOS. Note that the perspective needs to be applied prior to the rotation to get the correct results. You can play around with the values, but likely somewhere between 500 and 1000 will give you the effect you're looking for.

Original code:
```javascript
transform:[ 
  {rotateY: '45deg'}
]
```

New code:
```javascript
transform:[
  {perspective: 500},
  {rotateY: '45deg'}
]
```

**Comment by thg303** [comment]
thanks @aamctustwo it worked!

**Comment by woowalker** [comment]
yes, and what is more, you must place _**{perspective: 500}**_ before your transform style, otherwise it still not work, i try it hard......

**Comment by wcandillon** [comment]
@thg303 @woowalker on Android there is a default perspective set. I struggling to find its value. I have a 3d rotation that depends on the perspective value. Works great on iOS but fails on Android because, I don't know which value I should assume for the perspective: https://snack.expo.io/@wcandillon/instagram-stories

I looked at the source code and tried some values like 1280, 1280*density, or 1280*density*5 without success.
I would love to know which transform to apply in order to "revert" the effect of the default perspective on Android.

Did ou guys manage to crack this?
