### ISSUE TITLE
react-native-xcode.sh should still sort out IP when SKIP_BUNDLING

### ISSUE THREAD

**Issue by jliebrand** [facebook/react-native#16520]
I'm using SKIP_BUNDLING=true when running on my iPad. This works fine, but it skips the entire react-native-xcode.sh script, which means the IP detection is never run.

Skip bundling should just skip the bundling, but still do the other steps.

**Comment by Knight704** [comment]
Agree with @jliebrand, I'm faced with the same situation. Here are more info

### Environment
OS:  macOS Sierra 10.12.6
Node:  9.0.0
Yarn:  0.24.6
npm:  5.5.1
Watchman:  4.9.0
Xcode:  Xcode 9.1 Build version 9B55
Android Studio:  2.3 AI-162.3934792

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: 0.48.4 => 0.48.4

### Steps to Reproduce
1. Run ```SKIP_BUNDLING=true react-native run-ios --device```
2. Wait app build and install on device
3. Open app

### Expected Behavior
4. App loads bundle from local packager

### Actual Behavior
4. App shows 'No bundle url present'
SKIP_BUNDLING shouldn't abort react-native-xcode.sh script too early to allow making important IP config steps.
