### ISSUE TITLE
Unable to open Atom when clicking error line

### ISSUE THREAD

**Issue by James2516** [facebook/react-native#16532]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment

  Environment:
  OS:  macOS Sierra 10.12.6
  Node:  8.6.0
  Yarn:  Not Found
  npm:  5.5.1
  Watchman:  4.7.0
  Xcode:  Xcode 8.3.3 Build version 8E3004b
  Android Studio:  2.3 AI-162.4069837

### Steps to Reproduce

When i got an error and click on the file to open the corresponding file on IDE, i got an error `LSOpenURLsWithRole() failed for the application /Applications/Atom.app with error -10810.`. 

I'm able to open atom from terminal with `open -a /Applications/Atom.app`.

Is React-native having trouble finding which project folder the error file resides in?

**Comment by Kureev** [comment]
Hi @James2516! It doesn't look like the problem is related to React Native itself. Please, open corresponding issue in Atom repository.

By the way, it seems to be a pretty popular issue. I managed to find lots of people with similar problem. You can follow a corresponding thread here: https://github.com/atom/atom/issues/3093

**Comment by Kureev** [comment]
@facebook-github-bot close
