### ISSUE TITLE
[Bridge] add -injectJSON:... to RCTJavaScriptExecutor

### ISSUE THREAD

**Issue by jwyld** [facebook/react-native#1661]
Currently, there is a method for injecting text (-injectJSONText:...), but it would be convenient to inject a JSON object.

Ideally, it would be best to offload the RCTStringify onto the JavaScript queue as well.  I'm profiling the startup time of the bridge, and the JS queue at that time is mostly idle.  The bridge could produce the config and toss the whole blob over to the other queue while it continues to do more work.

**Comment by tadeuzagallo** [comment]
Can you submit a PR for that? :smiley:

**Comment by brentvatne** [comment]
ping @jwyld

**Comment by jwyld** [comment]
React Native support has been reduced in priority for my application, so a PR will not be coming anytime soon.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/bridge-add-injectjson-to-rctjavascriptexecutor

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is heavily focused working on performance.
