### ISSUE TITLE
React Native version mismatch. JavaScirpt version:0.49.3 ,Native version:0.50.3

### ISSUE THREAD

**Issue by jackbabyyyy** [facebook/react-native#16762]
### Is this a bug report?

(write your answer here)

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by darina-techery** [comment]
Check out this thread: https://github.com/expo/expo/issues/923

**Comment by ide** [comment]
The mismatch means that the version of your JS and your native code don't match. Closing this since this isn't a bug with React Native. Please post if you have a suggestion for how to communicate this more clearly, the fundamental problem is that the JS doesn't work with the native code though so there's no way we can make this magically work.

**Comment by oleksandr-yefremov** [comment]
Note: If you are seeing this error on freshly init'ed app, try checking your local maven repo (`~/.m2`) and remove any `com.facebook.react` packages over there or comment out `mavenLocal()` in `app/build.gradle`. I had a modified package which was standing in the way because react dependency version is *plus* `compile "com.facebook.react:react-native:+"`.

**Comment by afilp** [comment]
@oleksandr-yefremov I am in Windows and commented out `mavenLocal`, still no luck.

Note that I have an ejected EXPO project and I still get this error.
How can I get rid of 0.49, in favor of 0.50.3 that I am using in package.json?

Thanks!

**Comment by SamiChab** [comment]
You probably forgot to close your React Packager (terminal) which is running with a different version of react native. Try to close it and restart your app again

**Comment by programatt** [comment]
@SamiChab that is exactly what it was for me! Thanks

**Comment by xanderberkein** [comment]
For others with the same problem on iOS with CocoaPods:

Like ide hinted above, the React version specified in my Podfile didn't match the JS version. React was specified in my Podfile (I needed this for a package with native dependencies), but the React pod didn't automatically get upgraded by using `react-native-git-upgrade`.

The fix is to upgrade the installed pods yourself, by `running cd ios && pod install`.

**Comment by system65** [comment]
`react-native upgrade` solved the issue for me.

**Comment by harikrishnanp** [comment]
1) Kill metro bundler by `killall node`
2) Uninstall the app from emulator
3) `react-native run-android` or `react-native run-ios`

**Comment by tidydee** [comment]
> You probably forgot to close your React Packager (terminal) which is running with a different version of react native. Try to close it and restart your app again
^^^ Was exactly what caused my issue.

**Comment by misheki** [comment]
@harikrishnanp Thanks man! Uninstalling the app was what did it for me!

**Comment by hungdev** [comment]
i resolved by using: react-native start --reset-cache

**Comment by ZionChang** [comment]
I try all you said, it's not working. It only happen in android real device. Can anyone help?

**Comment by ajithes1** [comment]
@harikrishnanp  thank you broooh :) :+1:  :100: :1st_place_medal:

**Comment by sterswift** [comment]
@hungdev It took a long to reset cache in your case? Cause I'm waiting about 10 minutes seeing 'Loading dependency graph, done' and do not know should I continue wait or press 'ctrl + c'

**Comment by asadallahi** [comment]
@ZionChang 
I have the same problem. Did you solve that?

**Comment by AgungPrabowo** [comment]
@harikrishnanp thank bro uninstall app in emulator, solved

**Comment by ZionChang** [comment]
I have to change the version of rn to solve this  @asadallahi

**Comment by KirankumarDafda** [comment]
I am still getting this error in android, after trying all the above solution

React Native version mismatch.
JavaScript version: 0.50.4
Native version: 0.55.3

##While in cmd
>react-native -version
react-native-cli: 2.0.1
react-native: 0.50.4

I have restarted my command prompt, visual studio and finally my system too.

**Comment by sandeep0607** [comment]
open terminal inside your project folder
step1- sudo npm install -g react-native-git-upgrade
step2- react-native-git-upgrade
after this delete the two highlighted lines in manifest.xml for the conflict named '>>>then and >>>>after'
step3- watch-del-all && react-native start --reset-cache
now run your command react-native run-android

**Comment by Vinu-MysteriousTechVision** [comment]
@SamiChab Thanks, you saved my day. The solution worked for me.

**Comment by goeroeku** [comment]
@SamiChab  Thanks a lot...
If solution from @SamiChab not work, try combine with solution from @harikrishnanp
