### ISSUE TITLE
[Docs] Navigator example should be more complete

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#1692]
It should have multiple scenes, often this is the first place people will look to and this isn't so clear

**Comment by constantx** [comment]
:+1:

**Comment by cyprusglobe** [comment]
:+1:

**Comment by yelled3** [comment]
I would also suggest mentioning nesting a `Navigator` inside another `Navigator`, which is a fairly common use case in iOS.

**Comment by zachguo** [comment]
Where's the example for `Navigator`? I can only find examples for `NavigatorIOS`?

It's also helpful to include an example showing how to use `Navigator.navigationBar` in `Modal`, like those Apple uses when setting up VPN and Medical ID.

**Comment by alvaromb** [comment]
:+1:

**Comment by alvaromb** [comment]
I would be nice to have an example like this https://github.com/facebook/react-native/issues/2576.

**Comment by isikfsc** [comment]
I would also suggest mentioning nesting a Navigator inside another Navigator, which is a fairly common use case in iOS.
+1

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/docs-navigator-example-should-be-more-complete

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
