### ISSUE TITLE
WebView onNavigationStateChange Unable to monitor Jump page events of react-router

### ISSUE THREAD

**Issue by TrustTheBoy** [facebook/react-native#16975]
### Is this a bug report?  
> Yes
### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
> Yes
### Environment
 > OS:  macOS Sierra 10.12.6
Node:  v7.10.0
Yarn:  0.27.5
npm:  4.2.0
Watchman:  4.7.0
Xcode:  Xcode Version 9.2 beta (9C32c) 
Android Studio:  2.3 
react-native: all
react: 16.0.0
Target Platform: iOS (8-11.2) android(4.4.4-8.0)  

#### 1.react => router.js

```jsx
export default () => (
    <div>
        <Switch>
            <Route exact path="/" component={createComponent(Home)}/>
            <Route path="/page1" component={createComponent(Page1)}/>
            <Route path="/counter" component={createComponent(Counter)}/>
            <Route path="/userinfo" component={createComponent(UserInfo)}/>
            <Route component={createComponent(NotFound)}/>
        </Switch>
    </div>
);
```
![image](https://user-images.githubusercontent.com/20201085/33231055-8f7d5162-d229-11e7-8066-863dccf3f7f0.png)

#### 2. react native => WebView.js
```javascript
onNavigationStateChange = (navState) => {
   console.log(navState)
}
```
### The first load will be executed, and then the similar jump will not listen
![image](https://user-images.githubusercontent.com/20201085/33231105-a22dbcec-d22a-11e7-9f92-0cc18ae5006a.png)

**Comment by iamdurui** [comment]
yes ,I also have this problem

**Comment by uuau99999** [comment]
I have faced this problem. It it likely caused by the implementation of onNavigationChange event trigger.  onNavigationChange will only be called when the url actually change, and however, will not be called if the page your webview is trying to open is a SPA,  which is navigating without actually change url directly and use window.history api to modify the url dynamically or just use hash url directly. So to make your webview compatible with this kind of web page, you may need some event listener to monitor such behavior. For example, try injecting the following code in your webview:


(function(history){
        var pushState = history.pushState;
        var back = history.back;
        function updateNavState(currTitle) {
          setTimeout(function () {
            window.postMessage(JSON.stringify({
              type: 'navStateChange',
              navState: {
                 url: location.protocol + '//' + location.host + location.pathname,
                 title: currTitle ? currTitle : document.title
              }
            }));
          }, 100);
        };
        history.pushState = function(state) {
          updateNavState();
          return pushState.apply(history, arguments);
        };
        history.back = function() {
          updateNavState();
          return back.apply(history);
        };
        window.onload = function() {
          updateNavState();
        };
        window.onpopstate = function() {
          updateNavState();
        };
        window.onhashchange = function() {
          updateNavState();
        };
        new MutationObserver(function(mutations) {
          updateNavState(mutations[0].target.text);
        }).observe(
            document.querySelector('title'),
            { attributes: true, childList: true }
        );
        new WebKitMutationObserver(function(mutations) {
          updateNavState(mutations[0].target.text);
        }).observe(
            document.querySelector('title'),
            { attributes: true, childList: true }
        );
      })(window.history);



P.S. MutationObserver is used to monitor the title change event of the web page.
The code above may work fine in android but however in ios it may trigger useless onLoad event in webview which may affect the performance. I'm still seeking a solution to it.
Hope it might help u.
