### ISSUE TITLE
[RFC] Switch between compile modes via ENV vars

### ISSUE THREAD

**Issue by mattapperson** [facebook/react-native#1697]
I would like to propose the use of env vars to switch between OPTION 1 and OPTION 2 of how to load code in an iOS project. The url and port could also be done in this way. This will make it easier for the community to build tools for RN that will just work out of the box. Along with this, changing the default entry point for an app would also be nice for integrating with things like Mocha or what not for testing without having to move files around.

**Comment by brentvatne** [comment]
@mattapperson - what about dealing with multiple projects on one machine?

**Comment by mattapperson** [comment]
Env vars are nice because they can be controlled from the cli, that's my real goal here

**Comment by brentvatne** [comment]
Makes sense

**Comment by bparadie** [comment]
@mattapperson The proposal put forward in #1546 is about being able to configure debug port and ip address via `Info.plist` and I think ENV support is a valuable feature that one could build on top of that `Info.plist` approach. Roughly as follows: One could create different `Info.plist` files for each distinct environment/target that you would then activate via ENV. By doing so the XCode folks would be able to drive configurations through targets as well as CLI folks like you.

What do you think?

**Comment by mattapperson** [comment]
While I don't think that's bad, I would ideally like to override almost any config item via the cli

**Comment by bparadie** [comment]
Hmm, using a setup with different `Info.plist` files would probably not work well with overriding configs via the CLI. The CLI could only override configs if there were a custom `Info.plist`. 
Would that be acceptable?

**Comment by frantic** [comment]
Our practice shows that environment variables should be used as last resort, because it's extremely hard to debug, especially in large systems and across multiple projects. Unfortunately we still haven't figured a good way to switch between loading from development server vs loading from file. The approach we take internally is we have code that checks if pre-packaged bundle exists and uses that, otherwise it will try to connect to packager on fixed port.

**Comment by auser** [comment]
I wrote a module to do this with `babel` and `babelrc`: https://www.npmjs.com/package/babel-plugin-replace-config-vars

Might help?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/rfc-switch-between-compile-modes-via-env-vars

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
