### ISSUE TITLE
Modal not working as expected inside ScrollView

### ISSUE THREAD

**Issue by jalalat** [facebook/react-native#17002]
Is this a bug report?

Yes
Have you read the Contributing Guidelines?

Yes
Environment

    react-native -v: 0.45.1
    node -v: v7.10.0
    npm -v: 4.6.1
    yarn --version: 0.24.4

Then, specify:

    Target Platform: Android, iOS
    Development Operating System: Windows 10
    Build tools: Expo
    Issue tested on: Android

Steps to Reproduce

    Use Modal in the code (as specified in the example: https://facebook.github.io/react-native/docs/modal.html) within ScrollView (not there in the example).
    Add two views in the modal as specified in the example
    In the Internal View add a text box (TextInput) and Button.
    Add some text in the TextInput and click on the Button to send response back to the parent component.
    The first click on the button hides the keyboard. onPress event does not get triggered.
    Click again on the same button and this time Modal is hidden and Parent component gets the text data.
    This issue occurs only when Modal is used inside ScrollView. If you replace ScrollView with View then you will get the expected behavior.

Expected Behavior

    When user clicks on the Button for the first time then then onPress event should get triggered. Text data from TextInput should be logged to console.

Actual Behavior

    When button is clicked the keyboard hides -> that's good. However onPress event does not get triggered.
    When button is clicked again -> only then the onPress event get triggered.
    The same behavior occurs if i click on the back button (on the bottom right hand side; next to home screen on Android phone).

Reproducible Demo

https://snack.expo.io/S1WS11JKZ

**Comment by RyanMitchellWilson** [comment]
That sounds like it could be related to the `keyboardShouldPersistTaps` prop on a scrollview. Check out the prop here and see if you can get what you need with this. https://facebook.github.io/react-native/docs/scrollview.html#keyboardshouldpersisttaps

If you look `never` is the set default and that setting causes the keyboard to dismiss when you press away from it but the children will not receive the press. I suggest using the `handled` setting which will allow the children to receive the tap but the keyboard wont automatically disappear but you can then use the Keyboard api to close the keyboard when you press the button. 
https://facebook.github.io/react-native/docs/keyboard.html

Sounds like your problem is related to this but if not, I am not sure what the problem would be.

**Comment by jalalat** [comment]
Yup it solved the issue on Button. Other problem was when you use back button on Android phone (not on the app) it dismissed the keyboard but kept the modal. So i used the Keyboard event listener like this to dismiss the modal when back button is pressed:
```
Keyboard.addListener('keyboardDidHide', this._keyboardDidHide);

_keyboardDidHide = () => {
	// Do something to hide the Modal
	console.log('keyboard hidden');
}
```
