### ISSUE TITLE
Poor performance in Android production build

### ISSUE THREAD

**Issue by BG687** [facebook/react-native#17033]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

  Environment:
    npm: 4.2.0
    Watchman:  4.6.0
    Android Studio:  2.3.3

  Packages: (wanted => installed)
    react: 15.6.1 => 15.6.1
    react-native 0.50.3 => 0.50.3
    react-redux: 5.0.6 => 5.0.6
    redux: 3.7.2 => 3.7.2,

### Steps to Reproduce

So, my react-native app's performance is good in production mode in iOS -- native-feeling transitions, smooth animations, etc. However, on Android, we have serious performance issues -- multi-second delays for simple transitions, choppy animations, etc. The app is basically great in iOS and not usable in Android.

We have tried to follow the react native performance docs. We have taken out all the console logs, swapped ListViews with FlatViews and SectionViews, made animations useNativeDriver, etc.

We have also followed the guides for building in production mode -- turn debuggable to false in the app's build.gradle, set the build-variant to release, generate a signed APK with a keystore .jks file, etc. etc.

We have tested Android performance on the emulator and on two devices -- on a new Galaxy S8 and a 2013 Nexus 7 tablet. The performance is poor on both devices. We have deleted the cache, uninstalled the app, cleaned the build folder, and rebuilt many times.

Any ideas on how to fix this? It is odd that there is such a big performance hit in Android, and we are thinking there could be something easily remedied that we are missing.

(Write your steps here:)

1. Improve react native performance in line with docs
2. Change build gradle files and build variant to prepare for production build
3. Generate signed APK
4. Test on device

### Expected Behavior

We thought performance in Android would be similar to the performance of production builds in iOS

### Actual Behavior

Performance is very slow, as described two sections above. 

### Reproducible Demo

Since this is an issue related to building in Android Studio, a demo may not be very useful here. Just note that ALL transitions are very slow in Android but normal / fast in iOS. We have tried using different navigation libraries, including react-navigation, but that has not helped with this issue.

**Comment by jamsch** [comment]
Here's some tips I picked up from building a few apps.

1. Try to use FlatList/SectionList where you can and not `array.map()` as it allows for asynchronous rendering of components in your viewport which is important for mobile devices.
2. Parent components that have updates to state/props will attempt to re-render all of it's child components. It's up to you to make sure that all your child components should update or not by using `shouldComponentUpdate` or changing the components to a PureComponent. There's often times where you don't even know that components are re-rendering when they shouldn't be. 
3. Make sure that you are removing duplicate routes in your navigation state. React Navigation will typically have any screen you have in your navigation state rendered. State-heavy screens may suffer in performance especially when there's background state updates. It's also easy to add more routes to your navigation route and more difficult to take them off. You'd sometimes fall in to situations of having to call `NavigationActions.reset` and pass in a custom navigation state just so that routes aren't rendered twice. This issue is even present in their sample app.
4. Make sure that the screen you're trying to navigate to isn't *heavy* on it's initial render. react-navigation will only transition to the screen once it's typically fully rendered. One thing that could help is configuring `initialNumToRender` on your FlatList/SectionList component. Otherwise this may take seconds to render new screens using react-navigation.
5. The `renderItem` function should render stateless list item components. If it needs state context (e.g. whether the list item is expanded or selected), it should be using the parent's state as seen in the [documentation](https://facebook.github.io/react-native/docs/flatlist.html).
6. Unusual things may start happening if you render more than one FlatList/SectionList/VirtualizedList in one component (e.g. rendering only the current render batch and no more).
7. Develop Android-first. iOS performance is guaranteed and you will notice performance issues sooner before having to rebuild much of your code base. React-Native was built first with iOS-only support.

react-navigation is a not very performant library especially for Android. It solely uses React Native's library as a basis for all it's navigation logic which means any additional screens/views are all loaded on to the one activity/viewcontroller which gives 'native-like' navigation but not true navigation. If you went to inspect the app on iOS while the app was running you'd see that the screens in your navigation state are essentially rendered and layered on top of each other.

**Comment by zhanghuiyun** [comment]
FlatList 'pull-up load more' Sometimes do not trigger, sometimes trigger, do not trigger, you need to roll back a roll。My onEndReachedThreshold is already set to 0.1。Is there any way to fix this problem?

**Comment by bolan9999** [comment]
FlatList and SectionList is bad performance. Try this,please. may be it is a surprise for you

https://github.com/bolan9999/react-native-largelist

**Comment by barghi** [comment]
+1 
same issue here

**Comment by calvinkei** [comment]
same issue, it is not about flatlist, it is the whole app being crazily slow. even takes more than 5 seconds for simple navigation. and the app works perfect on ios
