### ISSUE TITLE
Packager cannot switch between projects

### ISSUE THREAD

**Issue by uber5001** [facebook/react-native#1710]
When switching from one project to another, the packager doesn't switch contexts correctly. Usually, this is in the form of:
 
    Error: Invariant Violation: Application AwesomeProject has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent

The packager seems to run code from the previously open project. I think the app fails because it is registering a different application name.

Currently, my solution is to close the packager (and the chrome debugging tab, if need be; see #1709) before switching to the next project.

**Comment by jtremback** [comment]
Yes, I too have this problem. Hasn't been a huge disruption. I now just always run it with `npm start`.

**Comment by brentvatne** [comment]
@uber5001 - I don't think this is super high priority because of the following:

1. It's not easy to fix: the packager server just sits there waiting for requests, when one comes in it serves the JS, done, wait again. We could post to the server something like "hey switch and start serving this project now" , but what if that's running a different React Native version? Then we need to have the packager restart itself from that directory. That's just one case I can think of.

2. Frequently changing projects is not that common, and closing the packager is not a big hassle.

If you'd like to submit a fix it would be welcome though! Closing this issue but hope you submit a PR for it :smile:
