### ISSUE TITLE
[FlatList]  FlatList rows are rendered,but it's white.

### ISSUE THREAD

**Issue by RyanRong** [facebook/react-native#17152]
`
<ScrollView
                    refreshControl={
                                <RefreshControl
                                    refreshing={this.state.isRefreshing}
                                    onRefresh={this._onRefresh.bind(this)}
                                     tintColor="#192c4d"
                                     title="  refresh......."
                                     titleColor={'red'}
                                 />}
                    onScroll={this._onScroll.bind(this)}
                    style={{ flex: 1, backgroundColor:'white',marginTop:-20}}>
                    {this.renderHeader()}
                    <View style={{ flex: 1}}>
                        < FlatList
                            key={(this.state.horizontal ? 'h' : 'v')}
                            ref={this.listRef.bind(this)}
                            style={{ flex: 1,  backgroundColor: 'white' }}
                            renderItem={this.renderItem.bind(this)}
                            itemHeight={PIC_ITEM_HEIGHT}
                            renderHeader={this.state.awardHeader&&this.state.awardHeader.isReceive==0?this.renderListHeader.bind(this):undefined}
                            numberOfRow={(this.state.horizontal ? 3 : 1)}
                    }
                            onRefresh={this.onRefresh.bind(this)}
                            onEndReached={this.onInfinite.bind(this)}
                            initialNumToRender={12}
                            removeClippedSubviews={false}
                        >
                        </FlatList>
                    </View>
                </ScrollView>
`

**Comment by gonzalezchris** [comment]
@RyanRong were you able to solve this issue? Im having the same issue on android. When I refresh the Listview, the list items are rendered but do not appear. I can still tap on the list items but they do not show up....

**Comment by JaxGit** [comment]
@RyanRong @gonzalezchris 
I ran into the same issue on Android and finally found the solution for it: 

Do NOT apply style (especially with backgroundColor) to FlatList itself, apply to it's wrapper instead. 
(If there was a time you are rendering a loading screen and the FlatList is completely destroyed and re-created later after loading, this bug won't be triggered, however this may not be the UX you want)

If you try to apply a red backgroundColor to FlatList, after pull-to-refresh you can actually see a big red screen without any content displaying, while all the invisible contents are actually underneath and accepting tap etc. 

So it might be because of a bug about zIndex after pull-to-refresh, which is working well on iOS.

**Comment by ddxxtony** [comment]
the solution of @JaxGit works
