### ISSUE TITLE
Android: Expose HyphenationFrequency on Text

### ISSUE THREAD

**Issue by sebaslogen** [facebook/react-native#17199]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

  OS: Windows 10
  Node: 9.2.1
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  2.3.0.0 AI-162.4069837

Packages: (wanted => installed)
  react: ^16.2.0 => 16.2.0
  react-native: ^0.50.4 => 0.50.4

  Target Platform: Android (6)

### Steps to Reproduce

Using a Text view in Android and iOS to show text with hyphenation characters: in iOS the text is displayed using the whole line width with hyphen characters but in Android the text lines break usually without showing hyphen characters when needed, making the text look ugly in Android and not using the full width of the line.

The problem in Android is that TextView attribute `hyphenationFrequency` is set to **HYPHENATION_FREQUENCY_NORMAL** by default and the desired behavior consistent with iOS is to use **HYPHENATION_FREQUENCY_FULL** in the React Native ReactTextView

Example:

Current Adnroid outcome:
_"very long sentences
usually break line incorrect-
ly"_

Expected Adnroid outcome:
_"in very long senten-
ces break line correc-
tly"_

Reproduction steps
1. Create a text component
2. Use this long hyphenated text in a ReactTextView
`
"Free&shy;lan&shy;ce&shy;jour&shy;na&shy;list Free&shy;lan&shy;ce&shy;jour&shy;na&shy;list Free&shy;lan&shy;ce&shy;jour&shy;na&shy;list Free&shy;lan&shy;ce&shy;jour&shy;na&shy;list Free&shy;lan&shy;ce&shy;jour&shy;na&shy;list Free&shy;lan&shy;ce&shy;jour&shy;na&shy;list Free&shy;lan&shy;ce&shy;jour&shy;na&shy;list Free&shy;lan&shy;ce&shy;jour&shy;na&shy;list Free&shy;lan&shy;ce&shy;jour&shy;na&shy;list"
`
3. Make sure the screen width is small enough so the text has to break a couple of times (phone portrait mode)

### Expected Behavior

At the end of the lines there are hyphen characters breaking long words before text continues to the next line.
The text has a similar line breaking with hyphens in Android and iOS.

### Actual Behavior

At the end of the lines there are no hyphen characters breaking long words before text continues to the next line and text lines don't use the full width of the text view, leaving big white spaces at the end of a line.
The text has different line breaking structure and most lines don't show hyphens in Android compared to iOS.

### Reproducible Demo

https://snack.expo.io/Syh0901MM

**Comment by sebaslogen** [comment]
Still reproducible.

**Comment by mgtitimoli** [comment]
This is not an issue itself, but a feature request that to summarize, there is currently no way to set [hyphenation frequency](https://developer.android.com/reference/android/widget/TextView#androidhyphenationfrequency) on Android.

Having no way to set this reduces the control over how the platform breaks text as there are time that's not enough to set `textBreakingStrategy` to `simple` to avoid cutting words in the middle, where setting `hyphenation frequency` to `none` leaves no other alternative to the OS and cutting is entirely prevented. 

Currently it's set to normal as it can be seen [here](https://github.com/facebook/react-native/blob/47910f0cadda30099bc6f5dfda03a69babd663a7/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactTextShadowNode.java#L91) and [here](https://github.com/facebook/react-native/blob/47910f0cadda30099bc6f5dfda03a69babd663a7/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactTextShadowNode.java#L125) where IMHO a better default would have been `none` or exposing this to the user as this issue is asking for.
