### ISSUE TITLE
React native apk (release and debug both) is crashing in higher version (greater than lollipop), Due to Permission issues?

### ISSUE THREAD

**Issue by sunnynegi** [facebook/react-native#17259]
I am working on a react native application. I am able to install and run working app in lower android versions (below Lollipop). But unable to ask permission upfront in higher versions of Android. Can someone please point me to how i can solve the issue and what should i do to debug it?

### Is this a bug report?

No
 

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Yes)

 

  Environment:
  OS:  Linux 4.4
  Node:  7.10.1
  Yarn:  0.27.5
  npm:  4.2.0
  Watchman:  Not Found
  Xcode:  N/A
  Android Studio:  3.0 AI-171.4443003

  Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.5 => 0.49.5

**Comment by jmahatpure01** [comment]
It must be showing some errors in debug mode when crashing. Or you can read the crash logs for the error. If it is caused by permissions then manually allow your app those permissions from the settings and try running again.
Use this for asking permissions: https://github.com/yonahforst/react-native-permissions
