### ISSUE TITLE
`display: none` behavior differs between iOS & Android — onLayout fired inconsistently

### ISSUE THREAD

**Issue by jamesreggio** [facebook/react-native#17294]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.9.1
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: 4.4.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.51.0 => 0.51.0

Target Platform: iOS 11 + Android API 26

### Steps to Reproduce

1. Add an `onLayout` handler to a `View`
2. Record the initial layout
3. Apply `display: 'none'` styling to the `View`

### Expected Behavior

The `onLayout` handler is not fired.

### Actual Behavior

On iOS, the `onLayout` handler is not fired (correct behavior).

On Android, the `onLayout` handler is fired, and the `nativeEvent: layout` contains a `height` and `width` of 0.

**This is a problem for two reasons:**

1. Platform inconsistency is fundamentally problematic, especially for core features, like layout.
1. When a `View` is updated to a `height` and `width` of 0, lots of things go wrong. `react-native-svg` throws errors. `react-navigation` throws errors. Many people do not code in a manner that is resilient to a view transitioning from non-zero dimensions to zero dimensions.

### Reproducible Demo

Snack that demonstrates the problem: https://snack.expo.io/H1pui4OMz

Video of the Snack running on iOS and Android. Note that iOS doesn't increment the `onLayout` calls when I toggle `display: none`, whereas Android does.

#### iOS

![2017-12-20-rn-display-none-ios](https://user-images.githubusercontent.com/822205/34225483-a8a00a1c-e594-11e7-8d97-f9927e40a946.gif)

#### Android

![2017-12-20-rn-display-none-android](https://user-images.githubusercontent.com/822205/34225487-ab274ade-e594-11e7-95dd-fcb863a54718.gif)

**Comment by jamesreggio** [comment]
cc: @woehrl01, who implemented `display: none` on Android
cc: @shergin, who implemented `display: none` on iOS

**Comment by woehrl01** [comment]
@jamesreggio I'm not the implementer of `display: none` for android, but for yoga itself, so I'm not the right person here. 

But the problem is that the [Android code](https://github.com/facebook/react-native/blob/90a42396b9c9d3dce18f04fadb9679b3bbdc1a1b/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIImplementation.java#L949) does not handle `display: none` by itself, [while the IOS code](https://github.com/facebook/react-native/blob/0ae4c47daa6280d2931d8bbf89612b2f1cb106d4/React/Views/RCTShadowView.m#L200)  + [this here](https://github.com/facebook/react-native/blob/0ae4c47daa6280d2931d8bbf89612b2f1cb106d4/React/Views/UIView%2BReact.m#L89) does.
