### ISSUE TITLE
Font issue on Android 4.x WebView

### ISSUE THREAD

**Issue by huynhtansi** [facebook/react-native#17385]
### Is this a bug report?

Yes. It appears when [this commit](https://github.com/facebook/react-native/commit/59d9f8ca5eb96b4b455b60ed170dfb05bc9c7251) is merged. On RN 0.50.0 above, Android 4.x WebView cannot display text/html format.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS High Sierra 10.13.2
  Node: 8.9.1
  Yarn: Not Found
  npm: 5.5.1
  Watchman: Not Found
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.0 => 0.50.0

  Target Platform: Android 4.1.2 (API 16)

### Steps to Reproduce

Render this component:

`export default class TestWebView extends Component<{}> {

    render() {
        const html = "<html>\n <body>" +
        "※Facebook，並びにGoogle＋へ許可なく投稿がされることはありません。" +
        "</body>\n</html>";

        return (
            <WebView
				style={{flex:1}}
				source={{html}}/>
        );
    }
}`

### Expected Behavior

![expect_behavior](https://user-images.githubusercontent.com/16728346/34433940-40e0bc8c-ecb5-11e7-9d03-0893b8356e98.png)

### Actual Behavior

![actual_behavior](https://user-images.githubusercontent.com/16728346/34433917-0a1b8af6-ecb5-11e7-8373-e6a9d826530f.png)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by lvmtam** [comment]
I have the same issue :(

**Comment by derakhshanfar** [comment]
same issue

**Comment by derakhshanfar** [comment]
@adrianomelo thanks but how can i upgrade react-native that refer to specific commit or tag when it is not releaseon NPM?

**Comment by huynhtansi** [comment]
@adrianomelo same question with @derakhshanfar. Should we create a PR to react-native repo? BTW, I will clone your repo to check again.

**Comment by adrianomelo** [comment]
@derakhshanfar, I can see two options if you need the fix for this problem asap. The first choice is using an older React Native version while the fix is not published. I guess that 0.49 is working fine. The second option is using a fork of React Native with my commit. You can use [my branch ](https://github.com/adrianomelo/react-native/tree/loadurl)if you don't want to fork RN. In this case, you can follow [this](https://facebook.github.io/react-native/docs/android-building-from-source.html) tutorial on how to use RN built from the source replacing:

`npm install --save github:facebook/react-native#master`
with:
`npm install --save github:adrianomelo/react-native#loadurl`

I don't recommend the second approach unless you are an experienced developer. This process usually takes a lot of time. Maintaining a fork is not fun. :)

@huynhtansi, I already [submitted](https://github.com/facebook/react-native/pull/17394) a pull request with a fix for it. However, if you can test, it would be awesome. You can comment on the PR and it might speed up the process of merging it to upstream.

**Comment by GrigoryPtashko** [comment]
Same here.

**Comment by GrigoryPtashko** [comment]
This is really bad. I've almost finished my app before submission to the Google Play and stumbed upon this issue. Is there a workaround for this?

**Comment by GrigoryPtashko** [comment]
Guys! Here's the solution that worked for me. On `Platform.OS === 'android'` add `baseUrl: ''` to `source` property of the `WebView`. UTF-8 displays correctly then!

**Comment by huynhtansi** [comment]
Hi @GrigoryPtashko , how to resolve in case I load a string html in source property? btw, it's still a problem in v0.53.0 and newer.

**Comment by GrigoryPtashko** [comment]
@huynhtansi see my comment above. `baseUrl` must be `''`.
