### ISSUE TITLE
CSS3 3D properties implementation

### ISSUE THREAD

**Issue by jamesharvey2** [facebook/react-native#17616]
### Is this a bug report?

This is a crucial feature request

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

  Environment:
    OS:  macOS Sierra 10.12.6
    Node:  8.4.0
    Yarn:  0.27.5
    npm:  5.4.0
    Watchman:  4.7.0
    Xcode:  Xcode 8.3.3 Build version 8E3004b
    Android Studio:  2.3 AI-162.4069837

  Packages: (wanted => installed)
    react-native: 0.48.1 => 0.48.1
    react: 16.0.0-alpha.12 => 16.0.0-alpha.12

  Target Platform: iOS (10.3)

### Steps to Reproduce

Try to use CSS3's 3D properties on React Native's StyleSheet. And it will not work.
https://www.w3schools.com/css/css3_3dtransforms.asp

1. Start a react native project.
2. Use CSS3 Properties on StyleSheet
3. It will not work....

### Expected Behavior

React Native will fully support CSS3 3D properties using its StyleSheet.

### Actual Behavior

React Native's stylesheet doesn't work with CSS3 3D properties...

### Reproducible Demo

All React Native apps are demos of this problem. It should implement CSS3 3D properties ASAP to help creative make what they want.

**Comment by adrianfalleiro** [comment]
@jamesharvey2 What properties specifically are you having issues with?

React Native has support for `transform` and `perspective` and `backfaceVisibility`.

You apply a transform in a StyleSheet in the following way:
```
const styles = StyleSheet.create({
  component: {
    transform: [
      {translateX: 50},
      {rotateY: '60deg'}
    ]
  }
});
```

More information can be found in the documentation: https://facebook.github.io/react-native/docs/transforms.html

**Comment by lwinkyawmyat** [comment]
@facebook-github-bot answered

**Comment by wcandillon** [comment]
@adrianfalleiro: on Android there is a default perspective set. I struggling to find it's value. I have a 3d rotation that depends on the perspective value. Works great on iOS but fails on Android because, I don't know which value I should assume for the perspective: https://snack.expo.io/@wcandillon/instagram-stories

I looked at the source code and tried some values like 1280, 1280*density, or 1280*density*5 without success.
I would love to know which transform to apply in order to "revert" the effect of the default perspective on Android.
