### ISSUE TITLE
Emulator is not working: Execution failed for task ':app:installDebug'.

### ISSUE THREAD

**Issue by radjivC** [facebook/react-native#17714]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment

I'm on MacOSX Sierra 10.13

  Environment:
    OS:  macOS Sierra 10.13
    Node:  8.9.1
    react-native: 0.52.0
    Watchman:  4.9.0
    Android Studio:  3.0 AI-171.4443003

  Packages: (wanted => installed)
    react-native: 5.6.0
    react: 16.2.0

  Target Platform:  Android oreo

### Steps to Reproduce
After a fresh install, I try to run the simulator for android

- Launch The emulator
- react-native run-android

### Expected Behavior
working

### Actual Behavior

I get this error and I have no way to make the simulator running

Any idea? I'm desperate

Thanks
```
> Task :app:installDebug
Skipping device 'emulator-5554' (emulator-5554): Device is OFFLINE.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:installDebug'.
> com.android.builder.testing.api.DeviceException: No online devices found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
26 actionable tasks: 2 executed, 24 up-to-date
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment.
```

**Comment by MehdiAlouafi** [comment]
> Task :app:installDebug
Skipping device 'emulator-5554' (emulator-5554): Device is OFFLINE.

Here is the important part, your emulator, since it is not working, fail to have the app installed on it.

Are you sure that your emulator is up and running ?
If you connect a device with usb does it work ?
Do you have atleast one emulator in `Tools > Android > AVD Manager' ?

Go to `Android Studio > SDK Manager` and see if 'Android Emulator' is checked.

Either way this issue is, I think, not related to react-native per say but more with 'you' because the main issue here is that your emulator is not working.
