### ISSUE TITLE
[Text] Add support for vertical-align style property

### ISSUE THREAD

**Issue by fatuhoku** [facebook/react-native#1774]
I've marked the line rectangle with faint red:

![ios simulator screen shot 28 jun 2015 21 32 30](https://cloud.githubusercontent.com/assets/430233/8398203/b3aa6c44-1ddd-11e5-8b7d-17d49c50797e.png)

The text is sitting on the bottom of that rectangle. i.e. it's anchored to the bottom.

I was expecting the line spacing to be below the text, i.e. text should be anchored to the top of the line rectangle.

When will support of this come?

**Comment by MossP** [comment]
Not a perfect solution and I'm not sure if it's going to be implemented but could you not offset the `<Text/>' element inside a view and negative margin that to compensate for the difference? You would need to add `overflow:'hidden'` to the outer element too if you cannot have any invisible overlapping elements.

e.g. https://rnplay.org/apps/MKdiOw

**Comment by fatuhoku** [comment]
@MossP Hmmm!! That's good thinking. It's a possible solution for sure, and seems watertight.  I'll give that a try soon...

**Comment by MossP** [comment]
I'll get this closed for now and if you're still having problems give me a shout and we'll look at re-opening it.

One to close for now @brentvatne, thanks.

**Comment by brentvatne** [comment]
This seems like a reasonable request - support for [vertical-align](https://developer.mozilla.org/en/docs/Web/CSS/vertical-align), or at least some subset of it, would be a valuable addition to the core.

**Comment by coyer** [comment]
I have this problem too. on IOS, text is bottom align and on Android, text at the top position of rect. how do I ?

**Comment by guyca** [comment]
Aligning text is pretty annoying right now and requires way too much work. Is the only way to align text today is to wrap the <Text> element inside some container and align the whole View inside the wrapping container ?

**Comment by cpjolicoeur** [comment]
Doesn't flexbox already handle this via `flexDirection` and `alignItems` combo?

**Comment by aboutqx** [comment]
@cpjolicoeur it seems not working.

**Comment by fatuhoku** [comment]
@cpjolicoeur `flexDirection` and `alignItems` might suffice for single line `Text` elements, but `vertical-align` is necessary when you're working with multiline `Text` elements.

**Comment by aboutqx** [comment]
@fatuhoku That's is right,when you want 2 or more lines to be in vectical center,you need to add a container to wrapp them.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/text-add-support-for-vertical-align-style-property

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by BenBenz** [comment]
this feature is now available or not ?

**Comment by AdriaRios** [comment]
Any updates?

**Comment by Athaphian** [comment]
No it is not available. Even in late 2017 creating a simple superscript in React Native seems an impossible task.
