### ISSUE TITLE
update react native from 0.52.0 to 0.53.0 , shadow become textshadow

### ISSUE THREAD

**Issue by jeodiong** [facebook/react-native#17870]
### Is this a bug report?
yes
### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
yes
### Environment
  Environment:
    OS:  macOS Sierra 10.13.2
    Node:  8.9.0
    npm:  5.5.1
    Watchman:  4.9.0
    Xcode:  Xcode 9.2

  Packages:
    "react-native": "0.53.0",
    "react": "16.2.0",
  Target Platform: iOS (10.3)

### Steps to Reproduce
1.update react native from 0.52 to 0.53

### Expected Behavior
![image](https://user-images.githubusercontent.com/8166360/35854093-5e345554-0b6a-11e8-911f-3fca89bb8b91.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/8166360/35854247-d0767d04-0b6a-11e8-90ab-a5615358b712.png)

I did not change my code ,just update react native, and shadow changed
![image](https://user-images.githubusercontent.com/8166360/35854277-e33743b0-0b6a-11e8-96ed-dee9b508e0cd.png)
![image](https://user-images.githubusercontent.com/8166360/35854284-eb39946e-0b6a-11e8-91c2-344bcb0e6380.png)

### Reproducible Demo
https://github.com/jeodiong/qafClient

**Comment by jeodiong** [comment]
all my box-shadow disapear, and become textshadow 
![image](https://user-images.githubusercontent.com/8166360/35857213-6840968a-0b73-11e8-8f24-bbb311df6221.png)

**Comment by jeodiong** [comment]
I try again ,0.52.0 is fine

**Comment by kesha-antonov** [comment]
+1 !!!
How to fix it?

**Comment by kesha-antonov** [comment]
@jeodiong Hello! Did you find a solution?

**Comment by jeodiong** [comment]
No, using 0.52.0

**Comment by jeodiong** [comment]
@kesha-antonov No, using 0.52.0

**Comment by futuun** [comment]
Everything is fine when you set `backgroundColor` for every view with shadow

**Comment by joshyhargreaves** [comment]
This definitely seems to be an issue to shadows on transparent views, and if a color is not applied, it seems to be applied to any nested subviews of that view.

Here, unless a background color is set on the parent view, a shadow is applied to an inner absolutely positioned view.

https://github.com/joshyhargreaves/react-native-shadow-regression-demo-0.53
Snack which demonstrates the expected behavior: (https://snack.expo.io/SJrNN3BuG)

It looks like @shergin did some work on shadows in 0.52 https://github.com/facebook/react-native/commits/master/React/Views/RCTShadowView.m. Any ideas on this one @shergin ?

# 0.52
<image src="https://user-images.githubusercontent.com/1807207/36858677-bb8e8bb6-1d49-11e8-94b6-c65a0fc97b7c.png" width="300" />

# 0.53
<image src="https://user-images.githubusercontent.com/1807207/36859045-3f3a6a42-1d4b-11e8-8a5f-6d871ba5b360.png" width="300" />

**Comment by anonrig** [comment]
I'm having the same exact issue

**Comment by thomasobrien99** [comment]
Having same issue on 0.54, using @futuun's fix for now. (However it doesn't work to set the backgroundColor to transparent).

**Comment by jhalborg** [comment]
+1, can confirm that using `backgroundColor` on the views solves the issue

**Comment by DanGDroid** [comment]
@react-native-bot 

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.11.3
  Yarn: 1.7.0
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4670197

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.53.0 => 0.53.0
