### ISSUE TITLE
Does the run-ios command require Chrome to be installed?

### ISSUE THREAD

**Issue by arnoldbird** [facebook/react-native#17883]
### Is this a bug report?

No, probably not.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 9.5.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.52.0

### Steps to Reproduce

1.  On a machine running Mac OS without Chrome installed, create a new project with `create-react-native-app`
2. Change into project directory.  Run `npm start`.
3. In another terminal tab, change into project directory.
4. Run `react-native run-ios`

### Expected Behavior

Simulator starts up and loads my app.

### Actual Behavior

Simulator never starts, or starts but my app is a white screen.  I have had a variety of problems which are really too difficult to isolate.  Some of it may be due to incompatibility between expo and react-native-debugger, but I believe one problem is simply that I did not have Chrome installed.  I'm just wondering if it's a dependency or somehow becomes one.   I think it may be that once you install expo, the run-ios command does something different than it did before.  It could be that expo has taken over the run-ios command -- just a theory.  I don't know if expo may have given me some feedback during the install that it depends on Chrome, and I didn't notice.

The simulator definitely worked at times before I installed Chrome, but was extremely buggy -- mostly just not loading or loading a white screen, or showing a red "Runtime not ready for debugging" screen.  There is much more information about my case in this Stack Overflow question: https://stackoverflow.com/questions/48647704/how-to-restore-functioning-simulator-when-react-native-run-ios-stops-working

I do think the simulator became more inconsistent, or seemed to, after I installed expo.

### Reproducible Demo

Just follow the steps at https://facebook.github.io/react-native/docs/getting-started.html for getting started.  But do so on a machine that does not have Chrome.  Then run `react-native run-ios` in the project.

**Comment by hoscarcito** [comment]
Hi buddy! Maybe I'm not understanding you, but in order to run `react-native run-ios` you need to eject the app created with `create-react-native-app`.
If you really created the app with the `create-react-native-app` command, then you shouldn't have an iOS folder with the native code needed to execute in the simulator. I guess you ran `react-native init` instead. I'm sure it's not possible what you did because you are not compiling anything to be executed on the simulator.
Check the .bash_history or the deleted files in the trash folder to see what kind of project have you created
Cheers!

**Comment by arnoldbird** [comment]
@hoscarcito 

"in order to run react-native run-ios you need to eject the app created with create-react-native-app.
If you really created the app with the create-react-native-app command, "

I have run the `create-react-native-app` command many times in the past few days as I learn how all the tools work and try to debug my approaches and/or the tools themselves.  Because I'm new to react, I am creating new apps frequently (and deleting the old app) to ensure that any problems I encounter are not the result of a coding mistake I've made.  I'm actually not familiar with the `react-native init` command, though it's possible I've run that command at some point in the past week.  I don't recognize it.  I don't see it at the "getting started" docs -- https://facebook.github.io/react-native/docs/getting-started.html -- so I don't think there's any reason I would have run that command.

I don't know what you mean by "eject."  The steps to reproduce are as I've described in the issue -- I have to change to another terminal tab to run `react-native run-ios`, as I indicated.

I am really not sure if this is all academic.  I don't yet know if the issue I've posted here is just academic or if there might actually be a bug.  It sounds like you think the `run-ios` command should not depend on Chrome, even if I have installed expo.  In my experience of the past few days, it seems there is a dependency on Chrome somewhere.

In a way, this might be academic, because so many developers have Chrome installed.  In fact, now that I've installed it, I plan to keep it.  However, it took me a while to figure out that I needed it.

**Comment by hoscarcito** [comment]
Hi again @arnoldbird!
You have two ways to create a React-Native app. One is with `create-react-native-app` and the other is with `react-native`. Both are packages that you install globally. The differences are that the first one creates a project that run an expo server with the QR code on the CLI, so with your expo app you can scan it and the expo app will connect with your expo server and "compile" your app and display it trough its interface. The other one creates an entire project with all the native code necessary to compile it natively for both platforms and also compiles a bundle for the JS which when you are debugging the app (in the simulator or in the device connected trough USB/WiFi) the bundle is made every time you refresh the app by the packager. When you are done with the create-react-native-app you should `eject` the app, that command will generate the native projects and remove all the expo code.
I recommend you read the entire documentation, especially [Running your app on a simulator or virtual device](https://facebook.github.io/react-native/docs/getting-started.html#running-your-app-on-a-simulator-or-virtual-device) then [the caveats](https://facebook.github.io/react-native/docs/getting-started.html#caveats) and last but not least pay attention to the beginning of the document the tab **Building Projects with Native Code** in the same document.
Chrome is not part of React-Native nor you need it. It's a tool that connect with the packager if you hit the **Debug JS Remotelly** button in the device/simulator developer menu.

To clarify what I said in my last comment, if you have the app in your simulator is because you created the app with `react-native init appName` and then `react-native run-ios` that creates and install the app in the simulator. if you deleted the app folder in your OS, you are not deleting the app in the simulator, so when you launch the app it will try to connect with the packager, so when you created another app in the same folder with `create-react-native-app appName` probably you started the packager and it could compile the JS bundle for the app because were the same files in the same folder. It was just a casualty.

If you have any issue please read the [Troubleshooting guide](https://facebook.github.io/react-native/docs/troubleshooting.html#content) and watch some videos on YouTube, just follow the instructions step by step and it should work.

I think **this issue should be closed** as it is not a bug nor a problem with the documentation.

**Comment by arnoldbird** [comment]
I had been thinking of the simulator as being much like a web browser.  I didn't realize it was more like a server with my app running on it.  But it is documented, and reading the entire documentation is probably not a bad idea!
