### ISSUE TITLE
ImagePickerIOS videoMode fails

### ISSUE THREAD

**Issue by radreamer** [facebook/react-native#17989]
### Is this a bug report?

YES

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

YES

### Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.5.0
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.2.0 => 16.2.0
  react-native: ^0.53.0 => 0.53.0

### Steps to Reproduce

Try to open camera dialog with video mode

```
ImagePickerIOS.openCameraDialog(
                {
                  videoMode: true,
                },
                imgTag => {
                  // handle imgTag
                },
                err => {
                  // handle error
                }
              )
```

### Expected Behavior

Camera dialog should open with image and video modes

### Actual Behavior

`openCameraDialog` method returns error:
![screen shot 2018-02-15 at 3 00 22 pm](https://user-images.githubusercontent.com/16123063/36257792-fc5d734e-1260-11e8-8b43-c66a3471111d.png)

### Reproducible Demo

https://snack.expo.io/BJheNWXwf

**Comment by jcarver989** [comment]
@radreamer & @hramos - I just ran into this myself. 

 `RCTImagePickerManager.m` appears to be just not setting the mediaTypes field inside of the `openCameraDialog` method. As seen here: 
https://github.com/facebook/react-native/blob/master/Libraries/CameraRoll/RCTImagePickerManager.m#L62

So the video/movie mediaType isn't set and thus it will crash when you specify `videoMode: true`. 

Since the same file already retrieves the available mediaTypes, as seen here: https://github.com/facebook/react-native/blob/master/Libraries/CameraRoll/RCTImagePickerManager.m#L41

We can resolve the issue by just inserting these two lines, starting at line 62 (linked above).
```
NSArray<NSString *> *availableMediaTypes = [UIImagePickerController availableMediaTypesForSourceType:UIImagePickerControllerSourceTypeCamera];
   imagePicker.mediaTypes = availableMediaTypes;
```
Which fixes the issue. 

Happy to submit a PR if that'd help.
