### ISSUE TITLE
[ViewPagerAndroid] Incorrect behaviour of Text with onPress

### ISSUE THREAD

**Issue by Jpunt** [facebook/react-native#18097]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.2.1
  Yarn: 0.27.5
  npm: 5.3.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.2.0 => 16.2.0
  react-native: ^0.53.3 => 0.53.3

### Steps to Reproduce

- Render a `ViewPagerAndroid` with a nested `Text` 
- Add an `onPress` to the deepest `Text`
- Press the text
- Swipe away
- Release the text

### Expected Behavior

The `onPress` should not be fired.

### Actual Behavior

The `onPress` is fired.

### Reproducible Demo

https://snack.expo.io/@jpunt/viewpagerandroid-bug

![viewpagerandroid](https://user-images.githubusercontent.com/190501/36593472-1af184dc-189a-11e8-9f50-f692ff20037a.gif)

**Comment by kholiavko-roman** [comment]
The same problem if put `Text` wit `selectable` prop inside - the text cannot be selected. 
```
<Text selectable>
 Test text
</Text> 
```

**Comment by kholiavko-roman** [comment]
I found that this problem is because of `collapsable: false` in [ViewPagerAndroid.android.js](https://github.com/facebook/react-native/blob/0.54-stable/Libraries/Components/ViewPager/ViewPagerAndroid.android.js#L179)
Without this prop I cant select text inside ViewPagerAndroid, but in this case I cannot markup my page.
I try to fix it, but I didn't found a solution. 

@hramos, @janicduplessis Guys, any idea ? We very need this functionality in near time.

**Comment by hramos** [comment]
Sorry, nothing to add. If this were a regression, it might warrant looking a bit more into it. This seems like something where two components do not work necessarily as expected when used in a particular way together. These types of issues we leave to the community to investigate and address if there is a need.

**Comment by cpojer** [comment]
This issue has been moved to react-native-community/react-native-viewpager#11.
