### ISSUE TITLE
Can't find a way to update view after change language

### ISSUE THREAD

**Issue by omriattiya** [facebook/react-native#18150]
Hello!
I want to support language change (manually by user).
I'm using [react-native-i18n](https://github.com/AlexanderZaytsev/react-native-i18n) for that.
I found how to change the displayed language at run time but I didn't find how to update the current view.
### My Code

![image](https://user-images.githubusercontent.com/26112374/36838988-53a4790c-1d49-11e8-9708-ca4da4f2bb6f.png)

### Environment

Environment:
  OS: Windows 10
  Node: 8.9.4
  Yarn: 1.3.2
  npm: 4.0.5
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.0.0.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.3 => 0.53.3
### Expected Behavior

When I use `I18n.locale ='en';` not in function.. just as it is, the text will be in English and when I use `I18n.locale ='he';` the text will be in Hebrew.
However I need to change the language at run time. So I want that when I click each button the language will change and will be displayed. 

### Actual Behavior

Nothing happened.. I assume I need to reload / re-render / update the view but I didn't find how to.

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
