### ISSUE TITLE
react-native integration objective c

### ISSUE THREAD

**Issue by cihanbas** [facebook/react-native#18158]
Hi I have a problem 
I have two app

 first app react native app
second app objective c app

repo :

> https://github.com/cihanbas/integration_objective_c/tree/master/

I couldn't integrate , Although I read those docs 

> https://facebook.github.io/react-native/docs/integration-with-existing-apps.html

> https://www.raywenderlich.com/136047/react-native-existing-app

> https://hashrocket.com/blog/posts/tips-and-tricks-from-integrating-react-native-with-existing-native-apps

 but ı don't understand 

### Environment
  OS: macOS High Sierra 10.13.3
  Node: 9.6.1
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.3 => 0.53.3

### Expected Behavior

> objective c  app

<img width="250" alt="ekran resmi 2018-03-01 19 28 05" src="https://user-images.githubusercontent.com/20416272/36855975-ec7ee1a8-1d85-11e8-8943-cb612874b7cd.png">

> native app 

<img width="250" alt="ekran resmi 2018-03-01 19 28 51" src="https://user-images.githubusercontent.com/20416272/36856004-ff117204-1d85-11e8-8e00-8e0e889ba448.png">

<img width="250" alt="ekran resmi 2018-03-01 19 35 14" src="https://user-images.githubusercontent.com/20416272/36856384-f6f05c10-1d86-11e8-89e7-e03f4caf84d4.png">

I want  click the ` go to Objective c app ` open the objective c app  ,

click the  ` Go to React Native app` open react native app 

Would you help me

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

**Comment by cihanbas** [comment]
thank you for answer but it is react-native problem so can is open maybe there is someone to help me

**Comment by hramos** [comment]
Please do give Stack Overflow a try. As it happens, GitHub Issues is not a help forum.
