### ISSUE TITLE
[WebView] WebView android show nothing expect scroll bar in the right

### ISSUE THREAD

**Issue by Donhv** [facebook/react-native#18192]
I have a question about web-view. I have webview in A.js(only webview)
First time into the app webview work well but when I change screen from A to another component a few times webview in Component A load complete but it show nothing.(except  scroll in the right inside webview is show). I try change url but it still not work. Anyone can help me?
Problem appear both devices & emulator

"react": "16.2.0",
"react-native": "^0.52.2",

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
