### ISSUE TITLE
iOS doesn't showing the exact color from the javascript.

### ISSUE THREAD

**Issue by batmanhit** [facebook/react-native#18198]
I am having trouble with showing the exact color in the iOS.

### Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.9.4
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: 0.54.0 => 0.54.0

### Expected Behavior

The iOS should show the exact color like the android.

### Actual Behavior

<img width="782" alt="screen shot 2018-03-05 at 12 04 01 pm" src="https://user-images.githubusercontent.com/30376020/36963811-20957d0e-206e-11e8-8c78-bd85cc07e40f.png">

<View style={[styles.container, {backgroundColor: Platform.select({
        ios: '#2eb017',
        android: '#2eb017', 
})}]}>

I have tracked color from Photoshop and found out that android is showing the right color but ios is not.
<img width="373" alt="screenshot at mar 05 12-11-43" src="https://user-images.githubusercontent.com/30376020/36963891-643c519a-206e-11e8-9e98-b33b158bbe57.png">

**Comment by vovkasm** [comment]
Why do your think that "The iOS should show the exact color like the android"? First of all, do your measure color on the real device?

Your process of compare colors is very questionable. And can involve not only RN, but also simulator/emulator behavior, screenshot tool etc...
First of all, I would suggest to make same measure without RN at all. Make empty Android project and set background in theme. Make ios single screen project in Xcode and set the same background.

**Comment by cooleagle8837** [comment]
Actually, I detected this issue from the real devices and I tried to reproduce it on the simulators and it worked like that.
If you wish, I can provide you the screenshots from the real devices.

**Comment by vovkasm** [comment]
I think it may be a bug in RN, but to be sure, we can experiment with native projects before. If this RN bug, I'd first try to look at this direction: [UIColor - Color and Color Spaces](https://developer.apple.com/documentation/uikit/uicolor#1968626).

Because RN currently translates colors to native representation directly without any magic (well, almost :-) ):
- [processColor.js](https://github.com/facebook/react-native/blob/0.54-stable/Libraries/StyleSheet/processColor.js#L19) - called when style props prepared to send to native part
- [normalizeColor.js](https://github.com/facebook/react-native/blob/0.54-stable/Libraries/StyleSheet/normalizeColor.js#L15)
- [RCTConvert.m](https://github.com/facebook/react-native/blob/0.54-stable/React/Base/RCTConvert.m#L475) 

js part crossplatform, the only different part is in [processColor.js](https://github.com/facebook/react-native/blob/0.54-stable/Libraries/StyleSheet/processColor.js#L32-L38)

**Comment by cooleagle8837** [comment]
Thanks for this advice, @vovkasm.
Is there any workaround to make it work exactly?

**Comment by vovkasm** [comment]
I don't know, sorry. In the past we experienced same problem and did not do anything because it was not valuable for us. In the end the users of most applications probably not care of color precision. And our past applications was not targeted to graphics designers )))
So when I discovered this issue, I thought that I can share some info if you or anyone else wish to investigate deeper and fix it.
