### ISSUE TITLE
Xcode build fails when importing React after fresh integration

### ISSUE THREAD

**Issue by steven-diaz** [facebook/react-native#18205]
Followed the [Integrate with Existing Apps](https://facebook.github.io/react-native/docs/integration-with-existing-apps.html) guide.

After dealing with issues [#17764](https://github.com/facebook/react-native/pull/17764) & [#16039](https://github.com/facebook/react-native/issues/16039), the project finally compiled with no errors. Then, simply `import React` in a swift source file and building results in the following error.

<img width="924" alt="screen shot 2018-03-05 at 3 52 43 pm" src="https://user-images.githubusercontent.com/20306622/36999160-478348e6-208d-11e8-99ea-5e776a7a0ab8.png">

### Environment

Environment:
  OS: macOS High Sierra 10.13.2
  Node: 9.7.1
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: ^0.54.0 => 0.54.0

### Expected Behavior

No build errors when importing React

### Actual Behavior

Build error on importing React

### Steps to Reproduce

- `yarn add react-native`
- Address [#17764](https://github.com/facebook/react-native/pull/17764) with yoga.podspec changes: `spec.public_header_files = 'yoga/Yoga.h', 'yoga/YGEnums.h', 'yoga/YGMacros.h'`
- `pod install`
- Address [#16039](https://github.com/facebook/react-native/issues/16039) by changing import to `<React/fishhook.h>`
- Build successfully
- `import React`
- Build error

**Comment by carrchr** [comment]
I have an almost identical setup (Node: 9.5.0 and macOS 10.12.6) and a [shell script](https://github.com/facebook/react-native/pull/17764#issuecomment-367943213) that patches the podspecs. Rolling back to react-native 0.53.3 works as expected.

**Comment by Plo4ox** [comment]
@carrchr It is cool if it still work in 0.53.3 (I didn't took the time to re-test it ^^) but as I said in my issue, It is always better to be able to have the latest version of a framework with its latest features :)
@steven-diaz Thanks for reporting the issue. After reproducing your issue, I really think that React-Native developers seem to use obj-C++ but that is not the right thing to do if they want iOS developer to be able to use their framework easily.
As Apple say [here](https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/index.html):
`You cannot import C++ code directly into Swift. Instead, create an Objective-C or C wrapper for C++ code.`
and in your case it is what happens.
They are passing references by doing `CGSize &minimumSize`, which is working in ObjC++ but not in Objc, instead of `CGSize * minimumSize`
I don't know what to do. I don't think that creating a huge patch is the best solution but, well that's what I'm doing for now :)

**Comment by studyro** [comment]
I'm seeing this issue too.

So projects that use Swift can't compile with React Native 0.54+ ? It's 😢.

**Comment by inDream** [comment]
@studyro You could follow this fix: https://github.com/facebook/yoga/issues/711#issuecomment-374605785

**Comment by studyro** [comment]
@inDream Thanks, didn't be aware of post-install hacks. Running good now.

**Comment by lucasleelz** [comment]
Same issue
