### ISSUE TITLE
React Native - Cannot find entry file index.android in any of the roots.

### ISSUE THREAD

**Issue by kojongick** [facebook/react-native#18217]
I was developing an Android app using React Native. I was trying to use an emulator to run an application using an Android device, and then trying to run it again as an emulator.
Previously, when using Windows, I solved the problem by using "adb reverse tcp:8081 tcp:8081" method, but this method was not solved in the process of developing with mac today. Please help me somebody.

![2018-03-06 16 48 39](https://user-images.githubusercontent.com/29746074/37020185-4c2b047a-215e-11e8-9e36-88c775684ccc.png)

__

**Comment by AdrianMrn** [comment]
Make sure your version of React Native on your Mac is up to date. What do you get when you type `react-native -v` in your terminal?

**Comment by AdrianMrn** [comment]
#https://github.com/facebook/react-native/issues/14246

**Comment by hannigand** [comment]
Getting the same problem on iOS.

![screen shot 2018-03-06 at 10 13 19](https://user-images.githubusercontent.com/5614282/37026685-0aaca7ce-2127-11e8-8597-4ad64064880e.png)

react-native: 0.53.0

**Comment by AdrianMrn** [comment]
In that case, I'm at a loss..

When you're running `react-native run-ios[/android]`, it's looking for an index.ios[/android].js file, which doesn't exist past react-native 0.51 (or earlier, idk). That's why I thought you were running an older version.

I'm sure this is a recurring issue and somebody else will be able to answer your question, sorry I couldn't be of more help.

**Comment by hannigand** [comment]
No worries @AdrianMrn, all discussion is welcome. It's very bizarre that it has been working in the past but I've only got this problem this morning.

**Comment by kojongick** [comment]
@AdrianMrn 
my react-native version is
react-native-cli: 2.0.1
react-native: 0.53.3

**Comment by AdrianMrn** [comment]
@kojongick @hannigand if you still haven't fixed this, a temporary workaround could be to create 2 files called `index.android.js` and `index.ios.js`, and copy+pasting what you have in `index.js` into these files.

**Comment by alexxsanchezm** [comment]
I know this issue is closed, but to anyother else out must know this happened after a react native upgrade. I'm currently using:

RN:  0.56
RN-CLI: 2.0.1

My guess the server is running with a different version and looking for index.[android/ios].js file. Although if I create a new project, It runs as expected.

**Comment by abn0rmal-d0ct0r** [comment]
React Native Cli --> 2.0.1
React Native --> 0.57.2

And I still get the same error. Looks like the only to get out is to create index.android/ios.js file and duplicate the files.

**Comment by Navil** [comment]
You can also just create `index.android.js` in the root directory and add only following line to it: `import './index.js';`.
That way, you won't have to duplicate the content of your `index.js`.
