### ISSUE TITLE
RN 0.54 - Stylesheet Flow types incompatible with spread operator

### ISSUE THREAD

**Issue by michel-p** [facebook/react-native#18277]
Hi everyone, since the last react-native update, all my Stylesheet files are generating flow errors because of the spread Operator. Can someone help me resolve it ?

### Environment
  OS: macOS High Sierra 10.13.3
  Node: 8.6.0
  Yarn: 1.3.2
  npm: 5.3.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: 0.54.0 => 0.54.0

### Expected Behavior

No flow error, recognizing spread.

### Actual Behavior
![image](https://user-images.githubusercontent.com/9078109/37157453-356ff0f6-22e9-11e8-9ce5-1aaba72b6d19.png)

### Steps to Reproduce

Just use a spread operator in a Stylesheet definition.
![image](https://user-images.githubusercontent.com/9078109/37157408-1119ac7e-22e9-11e8-8864-7fb0827e4207.png)

**Comment by TheSavior** [comment]
Unfortunately, due to a bug in Flow, stylesheets don’t support being spread into. My recommendation is to create a second style that is just fonts.BnpSansCondensed and pass your component an array containing both styles.

The good news is that flow will start enforcing that only view styles can be passed to view, and only text styles can be passed to text.
