### ISSUE TITLE
How to achieve multi-level list content in an accordion?

### ISSUE THREAD

**Issue by TechSatya** [facebook/react-native#18314]
I want to implement accordion or collapsible kind of things, on which each row has several levels of row consists of Text, Icon, an Add function.

For now instance, I wanted to know, how can I achieve multi-level rows under each accordion's header or title?
Any such libraries which can help me out to resolve this issue are most welcome.
**react-native-collapsible didn't help me out!!

You can have a clear view basically what I want, by looking at the below image;

![4_1 school threads](https://user-images.githubusercontent.com/27278747/37239560-292ee5fa-2464-11e8-93bc-bbb43087fb7c.png)

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
