### ISSUE TITLE
Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference

### ISSUE THREAD

**Issue by Karrthik12** [facebook/react-native#18397]
I am running the Android application with `react-native run-android`. The application crashing at the entry with the following error

> Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference

### Environment

Environment:
  OS: Windows 10
  Node: 6.10.2
  Yarn: 1.5.1
  npm: 3.10.10
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

The machine does have Android Studio and Android SDK.

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0-alpha.2
  react-native: 0.54.2 => 0.54.2

### Expected Behavior

The application should open normally

### Actual Behavior

The application is crashing with the following errors.
![screenshot_20180315-193330](https://user-images.githubusercontent.com/36851487/37468027-d37dd206-2887-11e8-9b25-3076f7481c39.png)

### Steps to Reproduce

As this is a private project cannot give the code and steps to reproduce.

**Comment by hramos** [comment]
This issue is not actionable without code or steps to reproduce.

**Comment by dreindoRT** [comment]
```javascript
componentDidMount() {
    this.getBanner();
  }
  
  getBanner = () => {
    fetch(API_URL_BANNER, {
      method: 'POST',
      headers: {
        Accept: 'application/json',
        'Content-Type': 'application/json'
      },
      body : JSON.stringify(
        {server_key: SERVER_KEY, client_key: CLIENT_KEY}),
      })
        .then((response) => response.json()).then((responseJson) => {
      // Showing response message coming from server after inserting records.
          responseJson = responseJson['data'];
          console.log(responseJson);
        }).catch((error) => {
      console.error(error);
    });
  }
```

I got same issue here, error  show where I get data from API, and in log show 

**ReactNative: CatalystInstanceImpl.destroy() start
ReactNative: CatalystInstanceImpl.destroy() end**


FYI I use 
**"react": "16.3.0-alpha.1",
    "react-native": "0.54.2",**

**Comment by slegaitis** [comment]
+1

**Comment by hramos** [comment]
Please open a new issue.

**Comment by Dilshanf3** [comment]
I faced the same issue and the thing is that i haven't export the value of API_URL that i have created in another page,because of that  it gives an error(Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference ).
I fixed my issue by exporting the value that i have created.

**Comment by danihodovic** [comment]
I've ran into the same issue. The error message originates from 

https://github.com/facebook/react-native/blob/e636eb60d7c8cff3a73183e02d9d457d32a6ec53/ReactAndroid/src/main/java/com/facebook/react/modules/blob/BlobModule.java#L82

```
String scheme = uri.getScheme();
boolean isRemote = scheme.equals("http") || scheme.equals("https");
```
One line 81 the developer tries to extract the scheme (http/https) the request is using, but the method `uri.getScheme()` is returning `null` if your request url has no scheme. Line 82 attempts to call a virtual method which doesn't exist for `nulls`. 

Add a scheme to your request and the problem should go away.

We should submit a PR to provide a clearer error message when the request doesn't have a scheme.

**Comment by lourencogui** [comment]
Anyone solve it?

**Comment by muhammadtahakhan** [comment]
I've  same issue.

**Comment by enagorny** [comment]
As @danihodovic  explained this error due to providing `null` url for network request. In my case urls stored in `.env` file and we are using https://github.com/luggit/react-native-config for this. But I've not configured build.gradle file as described in https://github.com/luggit/react-native-config#extra-step-for-android .

**Comment by AbdelhalimAhmed** [comment]
any progress?

**Comment by leudanielm** [comment]
In my case, it only happens if I disable `JS Dev Mode` from `Dev Settings` on Android.
Once I enable it and reload the app, the exception is gone.

**Comment by trachanh1609** [comment]
I used **fetch(SERVER_URL)** also got the same error message "Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference" .

As @danihodovic indicated, this crashed because **uri** was _null_ in **uri.getScheme()** on line 81. So I printed out my **SERVER_URL** and noticed that it was _undefined_ due to importing error. I fixed my **uri** and now it's working.

If you get the same message as mine, check your URI before it crashes :
```
console.warn(SERVER_URL)
fetch(SERVER_URL)
// more code
```
