### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jcampbell05** [facebook/react-native#18429]
Where is your roadmap ?

On your blog you say you made one, on your roadmap you say you will post it on your blog monthly. But there hasn't been a monthly post since January.

I think the React Native community deserves better communication than this :)

**Comment by jcampbell05** [comment]
It contains all relevant information

**Comment by faizalshap** [comment]
I agree. I also end up same. I guess the devs are too busy :)

**Comment by hramos** [comment]
Hi! I recently removed the roadmap from the wiki as it had fallen significantly out of date and the monthly meeting release notes had significantly more information.

At our next meeting, I will present a proposal to our contributors to be more transparent about what is being worked on which may entail going back to the old wiki approach.

**Comment by Gulci** [comment]
Hey @hramos , are [these](https://facebook.github.io/react-native/blog/2018/01/09/react-native-monthly-6.html) the latest meeting notes you're referring to?

**Comment by hramos** [comment]
Yes, I am referring to the monthly meeting blog posts.

**Comment by hramos** [comment]
Answered.

**Comment by jcampbell05** [comment]
Not answered,.

The last one was in January, so you can't call it "monthly". 

When is the next one likely to be ? Will these be monthly one day ? Is there anyway the community can help to make them monthly ?

**Comment by wowzaaa** [comment]
@hramos i do not want to be rude but i think u answered a different question

i ended up on this issue because i was doing a flutter VS RN comparison ... and even though flutter is too immature for me to invest time in ... it does bring some good ideas to the table

so .. based on this context ... i was curious to see the road-map for RN ... the wish-list ... ideal scenario .... the "if everything goes perfect we would love to go there" scenario ... because this way i would have some info on future plans ... no matter if they get delayed / postponed / canceled

i honestly think it is a must for such a big community ... i am a RN fan but i cannot answer the question "where are you going from here?" ... it is just a feedback for the contributors/maintainers ... i think some of us are a bit in the dark :) without this piece of info

cheers

**Comment by hramos** [comment]
@wowzaaa answered in https://github.com/facebook/react-native/issues/18429#issuecomment-375031515
