### ISSUE TITLE
react-native run-android throws error

### ISSUE THREAD

**Issue by dverma4u** [facebook/react-native#18537]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

React-native run-android shows starting js server... but no server is started like it was starting before (nodejs winodow opens) and in the end it show following error: 

```
    Running C:\users\deepa\appdata\local\android\sdk/platform-tools/adb -s 
    192.168.105.101:5555 reverse tcp:8081 tcp:8081
    Starting the app on 192.168.105.101:5555 
    (C:\users\deepa\appdata\local\android\sdk/platform-tools/adb -s 
    192.168.105.101:5555 shell am start -n 
    com.aptencemobileapp/com.aptencemobileapp.MainActivity)...
    Starting: Intent { cmp=com.aptencemobileapp/.MainActivity }
    events.js:183
      throw er; // Unhandled 'error' event
      ^

    Error: spawn cmd.exe ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

Please someone help me!

## Environment
Environment:
  OS: Windows 10
  Node: 8.10.0
  Yarn: Not Found
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: ^0.52.1 => 0.52.2

## Steps to Reproduce`
`react-native run-android

## Expected Behavior
Server should start and opens application in emulator.

## Actual Behavior
 throw er; // Unhandled 'error' event

**Comment by Spartan-Arun** [comment]
i'm getting following error in new version

What is wrong?
app is not getting build in to my phone.

on running $react-native run-android on windows cmd

gradle repo is getting downloded and installed while installing application to device I'm getting this error

Exception in thread "main" java.lang.NullPointerException
at org.gradle.wrapper.BootstrapMainStarter.findLauncherJar(BootstrapMain
Starter.java:34)
at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.ja
va:25)
at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

Where does it happen?
it happens on graddle I guess i don't know clearly

How do we replicate the issue?
just use command react-native run-android

How important is this (1-5)?
I am not even able to create a sample hello world app because of this issue.

Expected behavior (i.e. solution)
App should open in my android device

**Comment by umutaktas** [comment]
if you are you sure, node.js is installed successfuly on your system, please check system environment variables and add C:\windows\system32 in system variables Paths
