### ISSUE TITLE
Question : Is it possible to programmatically trigger the status-bar-tap scroll-to-top?

### ISSUE THREAD

**Issue by MossP** [facebook/react-native#1861]
The status-bar-tap does a very good job of finding the correct listview on the page and scrolling to the top. Is it possible to call this programmatically?

**Comment by brentvatne** [comment]
Hi @MossP! This is a question best suited for StackOverflow! People there are very motivated to help because of their funny point system which acts as some sort of magical virtual currency for programmer pride, whereas here we are more concerned with bugs and feature requests.

That said, the answer for this is `this.refs.yourListViewRef.getScrollResponder().scrollTo(someX, someY)`

**Comment by MossP** [comment]
Thanks @brentvatne . I had been using this but found with tabbars sometimes the route to component weren't available. never-the-less I'll keep to stackoverflow for this type of question. Thanks.

Ps. I think you guys are doing an amazing job with react-native. I don't think I've ever been as excited about a language or framework. :+1:

**Comment by brentvatne** [comment]
:smile: :tada:
