### ISSUE TITLE
[CI] Failing test_android: java.lang.NullPointerException in 4 Android tests

### ISSUE THREAD

**Issue by getaaron** [facebook/react-native#18637]
Several CircleCI builds show the same 4 failing Android tests

## Examples

https://circleci.com/gh/facebook/react-native/39082
https://circleci.com/gh/facebook/react-native/39036
https://circleci.com/gh/facebook/react-native/38936
https://circleci.com/gh/facebook/react-native/38899

## Common CircleCI output

Your build ran **150 tests** with **4 failures**

1. testBorderColor - com.facebook.react.views.image.ReactImagePropertyTest

```
java.lang.NullPointerException
```

2. testImageInvalidResizeMode - com.facebook.react.views.image.ReactImagePropertyTest

```
java.lang.NullPointerException
```

3. testRoundedCorners - com.facebook.react.views.image.ReactImagePropertyTest

```
java.lang.NullPointerException
```

4. testTintColor - com.facebook.react.views.image.ReactImagePropertyTest

```
java.lang.NullPointerException
```

**Comment by getaaron** [comment]
@react-native-bot remove android tag

**Comment by PatriceVignola** [comment]
I ran the tests locally on my machine and found out (kinda) where the NullPointerException occurs. Basically, in `ReactAndroid/src/test/java/com/facebook/react/views/image/ReactImagePropertyTest.java`, line 61, there's a `Fresco.initialize(mContext);` line, and the NullPointerException occurs inside of the initialize tree on the Fresco side. I found the method [over here](https://github.com/facebook/fresco/blob/e5b19f5cebc547c140dfee6c25f62fb27e6f4443/drawee-backends/drawee-pipeline/src/main/java/com/facebook/drawee/backends/pipeline/Fresco.java#L48), but since it's not in the React Native codebase, I don't know how I should investigate and test this problem. Of course, if I comment out that line, the tests fail later because they probably need Fresco to be initialized.

I just recently started to read through the React Native codebase, and I'm trying to find an issue that I can fix for my first contribution. But I don't know what the usual process is when the problem seems to be located in another project. Should I just raise an issue on the Fresco repo and let them investigate it, or is there a way I can help on the React Native side? The test prerequisites are already all set up on my machine so it's very easy to make a change and test whether it's working or not.

Thanks!

**Comment by getaaron** [comment]
@PatriceVignola Are you able to validate whether `mContext` is valid? It’s totally ok for you to open an issue there and link to this one!

**Comment by PatriceVignola** [comment]
Hey @getaaron, you were right, the problem is in `mContext`. More specifically, the issue is that [`RuntimeEnvironment.application.getApplicationInfo().nativeLibraryDir == null`](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/test/java/com/facebook/react/views/image/ReactImagePropertyTest.java#L56). Since this is null, [SoLoader is unable to initialize its `soSource`](https://github.com/facebook/SoLoader/blob/master/java/com/facebook/soloader/ApplicationSoSource.java#L37) and throws an IO exception.

I'm not familiar with `Robolectric` though. Are we supposed to mock RuntimeEnvironment.application or `RuntimeEnvironment.application.getApplicationInfo().nativeLibraryDir` when testing? `RuntimeEnvironment.application` is `static` and `public`, and I don't know when it's initialized or when `nativeLibraryDir` is initialized. Maybe you have an idea?

**Comment by getaaron** [comment]
I have no idea, sadly. Maybe @hramos or @bestander know?

**Comment by bestander** [comment]
Looks Fresco related, maybe some libraries can't be found https://github.com/facebook/SoLoader/blob/master/java/com/facebook/soloader/SoLoader.java#L201

**Comment by AndrewJack** [comment]
This might fix this? https://github.com/facebook/fresco/issues/2060#issuecomment-369551729
