### ISSUE TITLE
ReadableMap.getString(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by sequencer08** [facebook/react-native#18817]
# Please help!

I got this error after upgrading to react native latest version.

## Environment

 OS: macOS Sierra 10.12.6
 Node: 6.11.1
 Yarn: Not Found
 npm: 3.10.10
 Watchman: 4.9.0
 Xcode: Xcode 9.2 Build version 9C40b
 Android Studio: 3.0 AI-171.4443003

## Expected Behavior
App crashed

![screen shot 2018-04-12 at 10 49 05 am](https://user-images.githubusercontent.com/38305614/38653860-5a7427ca-3e3f-11e8-91c2-c90a62ace095.png)

**Comment by sequencer08** [comment]
Any fix for this?

**Comment by hey99xx** [comment]
hard to tell what's going wrong without your JS code. The erroring line is at https://github.com/facebook/react-native/blob/0.55-stable/ReactAndroid/src/main/java/com/facebook/react/modules/blob/FileReaderModule.java#L43 and from JS the caller is likely https://github.com/facebook/react-native/blob/0.55-stable/Libraries/Blob/FileReader.js#L112 so I'd guess you're passing null data somewhere.

**Comment by Fujiwaranosai** [comment]
I also faced this issue with RN 0.54.0 and it happens all the time when I tap on a yellow warning and dismiss it. If I set `console.disableYellowBox = true` from the beginning, this problem will not occur anymore. It looks like something's wrong with the yellow box.

**Comment by sequencer08** [comment]
@hey99xx Yes. I also noticed that the error shows any time. I'm not passing any null data somewhere. Guys any fix for this? It's been a week now and I got the same error.

**Comment by sequencer08** [comment]
BIG THANKS RN!

**Comment by aloptrbl** [comment]
@sequencer08 hi did you found the solution? I am also have this issue.

**Comment by fufuninja** [comment]
seeing the same issue on 0.55.0, but putting console.disableYellowBox = true as suggested by  @Fujiwaranosai worked.

**Comment by xfry** [comment]
I found this kind of errors happen when we dont pass all the params needed for some implementation. For example: When we gonna implement Geolocation, the `navigator.geolocation.getCurrentPosition` will be waiting we pass it three parameters `(positionFn, errorFn, optionsObjetc)` some o this are optionals, but not at all just because if you forget to put the options object, you will receive this error:

> ReadableMap.getString(java.lang.String)' on a null object reference

Then, just have it in mind, always pass all the parameters it does not matter if it is an empty function or object.
