### ISSUE TITLE
TypeError: In this environment the sources for assign MUST be an object. This error is a performance optimization and not spec compliant.

### ISSUE THREAD

**Issue by selabie68** [facebook/react-native#19009]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment

```
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.11.1
  Yarn: 1.5.1
  npm: 6.0.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4670197

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.3 => 0.55.3
```
![simulator screen shot - iphone 6 - 2018-04-25 at 15 07 38](https://user-images.githubusercontent.com/5601142/39227163-6e7e3458-489a-11e8-91ee-a3d0fbceaa05.png)

## Steps to Reproduce

Happens on loading of app.

**Comment by fungilation** [comment]
I'm hitting the same, in multiple components on Android and only Android:
```javascript
				<View
					style={[
						styles.stickyHeader,
						{
							width: viewWidth,
							...(stickyHeaderHeight ? { height: stickyHeaderHeight } : null),
						},
					]}
				>
...
```
(in my forked version of https://github.com/maxs15/react-native-modalbox/blob/master/index.js)

Redbox error:
<img width="471" alt="screenshot 2018-05-03 22 46 43" src="https://user-images.githubusercontent.com/3803466/39614811-81364a8e-4f27-11e8-9721-a5d37b7ea2c8.png">

By process of elimination, I tried taking out components that included the offending line that triggered the same `In this environment the sources for assign MUST be an object...` error. I take one component out, another component gives the same error. (above snippet is one sample of where error triggers)

Looking at https://github.com/facebook/react-native/blob/0.54-stable/Libraries/polyfills/Object.es6.js which throws this error. This error is thrown only when __DEV__ is true. So why bother? I breaks my app in dev and only in dev, when it should have allowed my app to continue executing. (hitting Dismiss on redbox ends with my app stalled on a white screen)

Can this error be changed to a console.warn instead of a redbox on __DEV__?

**Comment by fungilation** [comment]
Hey stupid bot, there's plenty of description here including screenshots.

**Comment by blackflame007** [comment]
The bot is right, I had the exact same error message and I just fixed it. Your error message is just not telling you your error. I was working in an Expo react native project with the Animated library dealing with rotation. To rotate with degrees one must use a string ex '-120deg'. My error was I put '-120eg' on my strings. I'd say you are sending data as the wrong type in one of your files.  @fungilation @selabie68

**Comment by J-S-Thomas** [comment]
Im having the same error following Scott Talinski (level up) tutorial called React Native For Everyone (video #12) cant figure out wtf is going on here. iOS and Android is bugging out. where the hell is View(at YellowBox.js:425)?

**Comment by marcoautiero** [comment]
@fungilation I just noticed a particular in your code, similar to a particular in my code
you're trying to add an object property in this way:
`...(stickyHeaderHeight ? { height: stickyHeaderHeight } : null),
`
but this should be

`...(stickyHeaderHeight ? { height: stickyHeaderHeight } : {}),
`

As well as I was trying to use 

`...(caloriesInDay && { calories: caloriesArr.reduce((a,b)=>{return a+b},0)} )
`
but the right way is
`...(caloriesInDay ? { calories: caloriesArr.reduce((a,b)=>{return a+b},0)} : {} )
`

**Comment by fungilation** [comment]
Interesting. I've since avoided the issue at init by always assigning a `int` to `stickyHeaderHeight`.

**Comment by skiral** [comment]
I faced the same issue, the issue happens when you try to use spread operator on a non object|array
...(NON_OBJECT_OR_ARRAY) will fail

**Comment by jasperkuperus** [comment]
For me, the error happened when passing something different than an `Object` to a prop that has a proptype of `Object`.

**Comment by ldgarcia** [comment]
In my case I incorrectly curried a function inside my component class:

````javascript
  // Incorrect, with typo
  renderFoo = (x) = (y) => {}
 // Correct
 renderFoo = (x) => (y) => {}
````

**Comment by Sumit-Chakole** [comment]
> I faced the same issue, the issue happens when you try to use spread operator on a non object|array
> ...(NON_OBJECT_OR_ARRAY) will fail
> I am experiencing it in JSX.

This explaination is absolutely correct!
