### ISSUE TITLE
NetInfo.getConnectionInfo() return unknown for iOS

### ISSUE THREAD

**Issue by Chatharaju** [facebook/react-native#19039]
I have the following code to detect the connection type. Android works fine but for iOS it returns unknown  

` NetInfo.getConnectionInfo().then((connectionInfo) => {
      console.tron.log('connectionInfo')
      console.tron.log(connectionInfo)
    })`

I am currently using RN version : 0.50.4 and iOS 11.3

**Comment by capozzid** [comment]
Hi, here is a workaround if you want to make it work for both Android/iOS

```
const getConnectionInfo = async () => {
  if (Platform.OS === 'ios') {
    return new Promise((resolve, reject) => {
      const connectionHandler = connectionInfo => {
        NetInfo.removeEventListener('connectionChange', connectionHandler)

        resolve(connectionInfo)
      }

      NetInfo.addEventListener('connectionChange', connectionHandler)
    })
  }

  return NetInfo.getConnectionInfo()
}
```

and then when you want to use it instead of directly call 

`const connectionInfo = await NetInfo.getConnectionInfo()`

you do it that way 

`const connectionInfo = await getConnectionInfo()`

From, of course, an asynchrone function other wise it won't work because of the "await" word

**Comment by brax10ward** [comment]
@capozzid Thanks for the workaround!
