### ISSUE TITLE
Image onError logs undefined on Android

### ISSUE THREAD

**Issue by connorwaslo** [facebook/react-native#19073]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment

OS: Windows 10
  Node: 8.2.1
  Yarn: 1.3.2
  npm: 5.8.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4670197

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.0 => 0.55.0

## Steps to Reproduce

    <ImageBackground style={{ flex: 1 }}
                                 resizeMode='stretch'
                                 onError={({ nativeEvent: {error} }) => console.log('Error:', error) }
                                 source={require('../../res/images/img.png')}>
        {/* Children */}
    </ImageBackground>

## Expected Behavior

Logging error variable should print the reason that the Image is not being loaded.

## Actual Behavior

error is undefined.

**Comment by lzrski** [comment]
I am also affected by this. In my case I am loading many (thousands) images in a `FlatList`. On Android some of them are not loaded and `onError` callback is being called, but the argument to it doesn't seem to contain any useful information (just as OP described `error.nativeEvent.error === undefined`. So I'm left to trial and error and  guesswork to understand the reason.

Perhaps it's related to #7440

For reference, also reported here: https://stackoverflow.com/questions/49136720/react-native-image-how-to-use-onerror#comment85402686_49137662

In my particular case I suspect it's some kind of memory or other resource related problem, as same images are loaded if I limit the total number of images. IOS doesn't seem to be affected, perhaps due to a better performance.

**Comment by edo1493** [comment]
Same

**Comment by vitorebatista** [comment]
Same here...

**Comment by Jyrno42** [comment]
not stale

**Comment by FibreFoX** [comment]
As far as I can tell, this issue contains the same as #18502 ... which one should stay open?! Or are they different?
