### ISSUE TITLE
on iOS TextInput native value is not matching provided value prop

### ISSUE THREAD

**Issue by mydesweb** [facebook/react-native#19167]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

on iOS TextInput native value is not matching provided value prop, on Android is working as expected

basically there is no way to manipulate / filter / replace what the user is typing in a TextInput on iOS, the TextInput is ignoring provided value prop or probably TextInput is not re-rendered accordingly, hope you can fix it - it is quite important 

## Steps to Reproduce

```
class ControlledInput extends React.Component {
  onChangeText = (text) => {
    this.setState({ inputValue: 'this text should always suppress user typed text but will not work on iOS' })
  }
  render() {
    const { inputValue } = this.state
    return (
      <TextInput
         onChangeText={this.onChangeText}
         value={inputValue}
      />
    )
  }
}
```

## Environment
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.9.1
  Yarn: 1.6.0
  npm: 5.7.1
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.3 => 0.55.3

**Comment by mydesweb** [comment]
@react-native-bot I added also Repro Steps

**Comment by jnberry** [comment]
Same issue here.  However, it seems that the TextInput will update with the state value if that state value is modified from the last render.  Otherwise, the TextInput uses what the user typed, not what is passed in via the value prop.

As you said, this prevents input filtering.

Environment:
OS: macOS High Sierra 10.13.4
Node: 8.1.2
Yarn: Not Found
npm: 5.6.0
Watchman: 4.7.0
Xcode: Xcode 9.3 Build version 9E145
Android Studio: Not Found

Packages: (wanted => installed)
react: 16.3.1 => 16.3.1
react-native: 0.55.4 => 0.55.4

**Comment by francisli** [comment]
Maybe a duplicate of #18874 ...?
