### ISSUE TITLE
Unable to run Vanilla App in High Sierra with 0.55.4

### ISSUE THREAD

**Issue by ChaseWPDEV** [facebook/react-native#19218]
- [X ] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [ X] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ X] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

Unable to complete react-native run-its for vanilla project in High Sierra 10.12 with Xcode 8.

Receiving:
CompileC /Users/chasegru/NativeDRC/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTShadowView+Internal.o Views/RCTShadowView+Internal.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

before abort.

## Environment

Environment:
  OS: macOS High Sierra 10.13
  Node: 10.1.0
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 8.3.3 Build version 8E3004b
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

## Steps to Reproduce

react-native init (project_
cd (project)
react-native run-ios

## Expected Behavior

Launch vanilla app

## Actual Behavior

Aborts Compile.

**Comment by ChaseWPDEV** [comment]
@hramos What additional information is needed?

**Comment by ChaseWPDEV** [comment]
Sure thing. Full log of the failed build attached.
[log.txt](https://github.com/facebook/react-native/files/2005819/log.txt)

**Comment by flowforever** [comment]
I Solved this problem by upgrading my XCode from 8.x to 9.x

**Comment by duhseekoh** [comment]
Would love a compatibility matrix for RN -> Xcode. Does that exist in some form anywhere? Couldnt track anything down in the release notes.

**Comment by rowdyrabbit** [comment]
@duhseekoh I would also love to see this compatibility matrix - upgrading Xcode isn't an option for me right now, so I'm a bit stuck

**Comment by dbnex14** [comment]
I had the same issue, except I was in El Capitan.  In order to fix the issue and be able to run my apps, I had to update XCode to latest (I was at 8.2).  But that was not possible in El Capitan, latest XCode required High Sierra.
So, I updated to High Sierra just today, then tried updating XCode and like it did on El Capitan, it just stuck in endless Wait loop and nothing would update even after leaving it for 5 hours.
So, I got sick and tired of it, I went and uninstalled XCode (drag it to trash), then went to [https://developer.apple.com/download/more/ ](https://developer.apple.com/download/more/ ) and downloaded latest XCode 9.3.1 xib file.
I unarchived it and dragged XCode app to my Applications in MacBook Pro
Then started XCode to complete installation.

After this, I was able to run my react-native apps again in both iOS and Android.

Here are the details I provided on Stack Overflow  [https://stackoverflow.com/questions/50477166/attempt-to-update-xcode-ends-in-endless-wait](https://stackoverflow.com/questions/50477166/attempt-to-update-xcode-ends-in-endless-wait)

Hope someone will find this useful

**Comment by kelset** [comment]
> Would love a compatibility matrix for RN -> Xcode. Does that exist in some form anywhere? Couldnt track anything down in the release notes.

It doesn't because it's not "react-native" related. It's a matter of macOs & XCode versions over which we have no control / no clear dependency with.

As mentioned in some other places/issues, react native is an environment with many moving parts, and we don't have control over many of them (ex. gradle, NDK, cocoapods, etc etc).

The general rule of thumb is to *not* jump on the latest version of anything if not strictly necessary.

Moreover usually these kind of issue surface / are detected quickly so please keep an eye on open issues before upgrading **anything**

**Comment by kelset** [comment]
That said, @dbnex14 solution of installing XCode from the dev website is the safest / more reliable - so @ChaseWPDEV I suggest you follow it and please comment if it doesn't fix it.

**Comment by Kielan** [comment]
agreed as has been said before, it needs to be way more clear for developers how react and xcode are interacting, it's open source so it's not black boxed, but after keeping my eye on react native for a while it's really a bummer this doesn't exist, and leads one to believe those building react native don't understand what they are interfacing with either, not an insult if this is true, but developers who don't personally know maintainers really can't know.
