### ISSUE TITLE
[Idea: StyleSheet] let StyleSheet entries define functions instead of object literals

### ISSUE THREAD

**Issue by ide** [facebook/react-native#193]
When writing stylesheets I often find my style rules depend on each other. For example, the color of some text should match the tintColor of an icon. In the interests of writing a concise stylesheet with a low maintenance cost here's a sketch of an idea:

```js
var styles = StyleSheet.create({
  icon() {
    return {
      tintColor: '#101010',
    };
  },
  text() {
    return {
      color: this.icon().tintColor,
    };
  },
});
```

`StyleSheet.create` would invoke all of the functions (w/memoization and cycle detection) and return an object that resembles today's stylesheet objects that you'd use as `styles.icon` and `styles.text`. I like this a lot more than defining some variable like `var iconAndTextColor = '#101010'` at the top because (a) I can skip thinking of a variable name and (b) if I were to delete the icon or text style then I'd want to inline the variable in the remaining style.

The main thing I don't like about this is the extra lines it takes up but unfortunately I couldn't get a terser variant to parse with the ES6 grammar:

```js
var styles = StyleSheet.create({
  icon: () => {
    tintColor: '#101010',
  },
  text: (self) => {
    color: self.icon().tintColor,
  },
});
```

**Comment by ide** [comment]
@vjeux do you have a tag for "good first bug" or something similar to highlight this for potential contributors? I'd like to see this direction get explored and there's a good chance it will make writing stylesheets a lot nicer.

**Comment by vjeux** [comment]
We should create a tag for this. But, for this, I'd rather want people to make separate npm module and if any catches then incorporate it in core.

**Comment by grabbou** [comment]
What I am doing in my current project (highly inspired by React source code) is...

```js
import {paragraphBase} from '../app/app.style.js';
export default Stylesheet.create({
   container: {
        ...paragraphBase,
        fontSize: 20
   }
});
```

Function expressions are definitely something worth exploring, especially when we consider writing `media-query` like stylesheets that export different properties depending on the device width.

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by lemonmade** [comment]
From my perspective, this creates more complexity than it reduces. At Shopify, we have a central utility whose job it is to provide colors to other components. Our experience (and this is definitely mirrored by conventions in Sass/ Less) is that it is easier for designers to contribute changes/ verify a design when colors are all together in a simple package, and it's easier for front-end devs to reason about what they are actually doing when a central utility takes away the guesswork.

At its simplest, it looks something like this:

```javascript
// utilities/colors.js
export default {
  gray: rgb(180, 180, 180),
  red: rgb(255, 53, 58)
  // etc
};

// components/component.js
import Colors from '../utilities/colors';

const styles = StyleSheet.create({
  text: { color: Colors.gray } 
});
```

This adds a bit more work (since you have to import your colors everywhere you need them) but makes things much more maintainable, shareable, etc.

Anything that needs to be expressed as more than a single style can either be included in the way @grabbou showed or (my preference, since I find multiple styles being shared usually means you have a distinct component), just make a new React element that encapsulates those styles (for example, a `Paragraph` class) and allow people to pass props to the element for particular variations (i.e., `this.props.size` can be enumerable and you dynamically add a style object for the relevant size in `Paragraph#render`.

**Comment by dralletje** [comment]
I have no meaning in this, just made it :stuck_out_tongue_closed_eyes: 
https://gist.github.com/dralletje/1784826c8c3d2e7e3a08

It's a gist now, but if you don't want to I can publish it on npm :grin:

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/idea-stylesheet-let-stylesheet-entries-define-functions-instead-of-object-literals

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
