### ISSUE TITLE
ReadableMap getInt truncates since 0.54.0

### ISSUE THREAD

**Issue by mattijsf** [facebook/react-native#19338]
Since 0.54.0 invoking `getInt` truncates `Double` values from `ReadableMap`.
I filed this bug because I could not find documentation and didn't see this particular change mentioned in the [0.54.0 release notes](https://github.com/facebook/react-native/releases/tag/v0.54.0) apart from:
> Refactored bridge ReadableNativeMap and ReadableNativeArray to add centralized accesses 
So I basically expected an Exception when reading an int from a double value in ReadableMap.

We used a snippets taken from: 
https://github.com/gigya/ReactNative-Demo/blob/master/android/app/src/main/java/com/gigyareactnative/JsonConvert.java

It basically comes down to the fact that ReadableMap has no way to tell whether or not a value is a Integer or Double (since they are all doubles). So in this particular `JsonConvert` snippet it used the `UnexpectedNativeTypeException` to determine whether or not to use write an `Integer` or a `Double` into the Json object (which is bad but okay).

For now we updated the above JsonConvert logic to just write `Double` values at all time which should be okay. I was just wondering whether or not this side-effect of the refactor mentioned in the release notes is a bug or a feature.

## Environment
```
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.3.0
  Yarn: 1.3.2
  npm: 6.0.1
  Watchman: 4.9.0
  Xcode: Xcode 9.3.1 Build version 9E501
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4
```

## Steps to Reproduce
Run the following instrumented test on `0.53.3` vs.`0.54.0`
```
@RunWith(AndroidJUnit4.class)
public class ReadableMapInstrumentedTest {

    @BeforeClass
    public static void setUpBeforeClass() {
        Context context = InstrumentationRegistry.getTargetContext();
        SoLoader.init(context, false);
    }

    @Test(expected = UnexpectedNativeTypeException.class)
    public void testGetInt() {
        WritableNativeMap map = new WritableNativeMap();
        map.putDouble("double", 2.1d);
        map.getInt("double");
    }
}
```

## Expected Behavior
0.53.3: Test Succeeds
0.54.0: Test Succeeds

## Actual Behavior
0.53.3: Test Succeeds
0.54.0: Test Fails

**Comment by hey99xx** [comment]
Based on my reading on the code, yes, it will truncate after the commits linked in 0.54 release notes. Specifically this line is the one truncating, and it looks like the author knew exactly what he was doing since he commented it: 

https://github.com/facebook/react-native/blob/7891805d22e3fdc821961ff0ccc5c450c3d625c8/ReactAndroid/src/main/java/com/facebook/react/bridge/ReadableNativeMap.java#L158-L159

 To me it's not the worst regression, but certainly broke your expectation of `UnexpectedNativeTypeException` in the code that you've linked. Unless FB wants to change the code again, going forward it may be a better idea to use `Math.rint` as seen as this class inside RN:

https://github.com/facebook/react-native/blob/26684cf3adf4094eb6c405d345a75bf8c7c0bf88/ReactAndroid/src/main/java/com/facebook/react/bridge/Arguments.java#L337-L345
