### ISSUE TITLE
add ReactRootView in RelativeLayout, will cause endless loop

### ISSUE THREAD

**Issue by killerJava** [facebook/react-native#19403]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment

System:
OS: Windows 7 6.1
CPU: x64 Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
Memory: 1.46 GB / 7.88 GB
IDEs:
Android Studio 3.0.1
Build #AI-171.4443003, built on November 10, 2017
JRE: 1.8.0_152-release-915-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

## Steps to Reproduce

add ReactRootView in RelativeLayout, we see onMeasure code in ReactRootView:

1

**updateRootLayoutSpecs(mWidthMeasureSpec, mHeightMeasureSpec);**

2

this method will call **YGNodeCalculateLayout** func in Yoga.cpp.

3

if the root node has changed, yoga set node has a new layout flag. reflect in YGJNI.CPP 
      obj->setFieldValue<jboolean>(hasNewLayoutField, true);
      YGTransferLayoutDirection(root, obj);
      root->setHasNewLayout(false);

4

this flag will cause to put node to mOperations, and wait to update:
      mUIViewOperationQueue.enqueueUpdateLayout(
          toUpdate.getNativeParent().getReactTag(),
          tag,
          x,
          y,
          toUpdate.getScreenWidth(),
          toUpdate.getScreenHeight());

5

in **NativeViewHierarchyManager** class, **updateLayout** will call ReactRootView' requestLayout:
      if (parent instanceof RootView) {
        parent.requestLayout();
      }

requestLayout ----->   onMeasure, loop ...

because RelativeLayout will measure child twice, but the height is diffrent between two measures:
ReactRootView: onMeasure: width is 1080, height is 1728

ReactRootView: onMeasure: width is 1080, height is 1581

hope can fix this question in ReactRootView

## Expected Behavior

not occur always call onMeasure func

## Actual Behavior

always call onMeasure in ReactRootView, 

RelativeLayout will measure child twice:
ReactRootView: onMeasure: width is 1080, height is 1728
ReactRootView: onMeasure: width is 1080, height is 1581

height changed, will call NativeViewHierarchyManager.updateLayout func, in this func, will
call ReactRootView.requestLayout, requestLayout will cause measue child, cause endless loop

**Comment by LyCharlie** [comment]
I have the same problem , I solve it by relpace relativelayout with linearlayout , but I don't think it is a good way, sometimes it may course overdraw

**Comment by hramos** [comment]
This issue can be improved by providing a small code sample that reproduces the issue.

**Comment by allenhsu** [comment]
We've encountered this problem as well, I think the problem is that with RelativeLayout, if you have used something like `layout_above` (in our case, a container view above bottom bar), `measure` and `onMeasure` of [`ReactRootView`](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/ReactRootView.java#L166) will be called twice with different height.

The first time to calculate max height, the second time to calculate exact height. Since the container is set to match parent's size, the first time it's height is set to parent's height (screen height most of the time). The second time, it's parent's height minus bottom bar's height. Since the two heights are different, it triggers layout of RN components, this layout somehow triggered measure/layout of the app again. Thus, it becomes a dead loop.

We resolved this by using LinearLayout instead of RelativeLayout as well, but I think it can and should be fixed in [`ReactRootView`](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/ReactRootView.java#L166).

My question is, why `updateRootLayoutSpecs` is called in `onMeasure` rather than in `onLayout`?
