### ISSUE TITLE
 getDeviceId: Neither user 10183 nor current process has android.permission.READ_PHONE_STATE

### ISSUE THREAD

**Issue by nahidmbstu** [facebook/react-native#19517]
## Environment
 ubuntu 16.03
"react": "16.3.1",
"react-native": "0.55.3",
device : android One , or virtual device

## Description
after the app is installed . if i try remote debugger it gives me this error
 getDeviceId: Neither user 10183 nor current process has android.permission.READ_PHONE_STATE

## Steps to Reproduce
  install app . turn on remote debugging

in adroidmenifest.xml file i have added this line

  `  <uses-permission android:name="android.permission.READ_PHONE_STATE"/>`

**Comment by hey99xx** [comment]
`READ_PHONE_STATE` is a dangerous level permission, so besides adding to your AndroidManifest.xml, you would have to ask it at runtime. In JS code you can use https://facebook.github.io/react-native/docs/permissionsandroid.html to do that.

But I also suggest you edit your issue using the template, and show the code sample that fails, otherwise you won't get too much help. I cannot find any method in RN called `getDeviceId`.

**Comment by nahidmbstu** [comment]
where should i ask for this permission . which file in project ? @hey99xx
