### ISSUE TITLE
[Animated] some Animated bugs

### ISSUE THREAD

**Issue by magicismight** [facebook/react-native#1951]
Animated is very awesome.but there are some bugs in Animated.

1.
the spring callback won`t be called at once the animation finished.
the callback has something like 200ms delay.
``` javascript
Animated.spring(
  this.state.height,
  {
    toValue: this._height,
    friction: 8,
    tension: 80
  }
).start(callback);
```

2.
When using Animated.timing and set easing as `Easing.back`  or`Easing.elastic`.
The element won\`t animate any more. It just jump to the last frame.
`Easing.in` and `Easing.inOut(Easing.ease)` works fine 

```javascript
Animated.timing(
this.state.height,
  {
    toValue: 0,
    easing: Easing.back, // or Easing.elastic
    duration: 200
  }
).start(callback);
```

**Comment by brentvatne** [comment]
Hello @magicismight!

1. I believe the issue here is that it takes longer to acquiesce the animation than it appears to - the values may change very gradually as it gets towards the end before settling on the final value.

2.  Both `back` and `elastic` need to have values passed in that effect the characteristics of the animation - https://github.com/facebook/react-native/blob/e3afc4efd815791e2fc4035f29232ade283e6d8e/Libraries/Animation/Animated/Easing.js#L79-L103 - so if you change your example to `easing: Easing.back()` or `easing: Easing.back(1.5)` those will work. Same goes for elastic: `easing: Easing.elastic()` etc.

If you'd like to update documentation for these to be more clear that could be cool! :smile:

**Comment by tedjames** [comment]
Hey @magicismight and @brentvatne, has anyone made any progress towards fixing that 200ms delay for the callback? It's still an existing issue that to my knowledge, has not yet been addressed.
