### ISSUE TITLE
macOS Support with 10.14's UIKit

### ISSUE THREAD

**Issue by keplersj** [facebook/react-native#19559]
## For Discussion

Minutes ago Apple announced that the upcoming macOS 10.14 will support applications written with UIKit. Because React Native already implements iOS functionality using UIKit, will React Native support macOS using this existing codebase? Or will desktop functionality continue to be implemented outside of this repo like with [react-native-macos](https://github.com/ptmt/react-native-macos) (implemented with Cocoa/AppKit)?

**Comment by jeveloper** [comment]
You're quick :)

**Comment by avioli** [comment]
Given [react-native-macos](https://github.com/ptmt/react-native-macos) requires macOS 10.11, then 10.14 is not too big of a jump as minimum requirement.

I only hope Apple rolls out docs for macOS [UIKit](https://developer.apple.com/documentation/uikit) support.

I wonder if the coordinate system is "fixed" - by default, the view’s coordinate system origin is located at the lower left on the Mac, not the upper left as on iOS.

**Comment by keplersj** [comment]
@notjosh Did some experimentation and it looks like it'll completely possible in the future!

[notjosh's twitter thread](https://twitter.com/notjosh/status/1005241332032565248)

[notjosh's GitHub repo](https://github.com/notjosh/Marzipants)

**Comment by notjosh** [comment]
hi! yes, it's very possible! three main things needed changing in `react-native`:

1. converting `CADisplayLink` (I just used a 1/60 timer because `CVDisplayLink` is a pain, and [it looks like](https://twitter.com/notjosh/status/1005211013875208194) we can probably use the macOS `CADisplayLink` eventually anyway)
1. adding macOS targets to each of the projects
1. add some `#if TARGET_OS_OSX`/`#if TARGET_OS_IPHONE` kind of checks for any unsupported code blocks (similar as is done for tvOS)

I can probably whittle it down to a patch if there's any significant interest?

**Comment by shirakaba** [comment]
Great interest here. I've been using react-native-macos and even released a [WKWebView component](https://github.com/shirakaba/react-native-wkwebview) for it (can be used as reference for making a macOS target, but honestly there's not much to it). It's a pity to have to deploy only to the latest macOS, but worth it in the long run to piggyback all the dev efforts relating to UIKit. react-native-macos has always been chasing behind RN master, and this would be a great way to keep the functionality in sync.

**Comment by ptmt** [comment]
Let's wait for the next WWDC happening this June. I expect great stuff
coming from Apple regarding IOSMac.
