### ISSUE TITLE
react-native run-ios doesn't start the JS compiler.

### ISSUE THREAD

**Issue by scerelli** [facebook/react-native#19566]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native version: https://github.com/facebook/react-native/releases
  - [x] Run `react-native info` in your terminal and paste its contents under "Environment"
  - [x] Let us know how to reproduce the issue. Include a code sample, share a project, or
    share an app that reproduces the issue using https://snack.expo.io/

## Environment
```
Scanning folders for symlinks in /Users/vood/dev/peanut/node_modules (13ms)

Environment:
  OS: macOS High Sierra 10.13.5
  Node: 8.11.2
  Yarn: 1.7.0
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.3 => 0.55.3
```

## Description
After the Update from RN from 0.51 to 0.55 it seems that `react-native run-ios` doesn't fire the JS compiler anymore. I'm not the only affected by this problem. I asked in the discord channel before writing here and other people experienced this issue after updating to the last version of react.

## Steps to Reproduce
Just update from an older version of react-native to the last one (0.55).

## Expected Behavior
`react-native run-ios` shall start the JS compiler.

## Actual Behavior
`react-native run-ios` doesn't start the JS compiler.

**Comment by hramos** [comment]
Are there other existing issues about this? 0.55 has been out for a while, I'm surprised if this is only surfacing now.

**Comment by alexindigo** [comment]
I'd guess, because default way now is to run it via expo, so there is fewer eyes on this path now.
_I'm having similar issue_

**Comment by iosdev-republicofapps** [comment]
Just as a data point, I'm running RN 0.55.2 on macOS 10.13.4 and `react-native run-ios` works for me.  So I'm not sure if the issue is with the upgrade to RN 0.55.3 or with the upgrade to macOS 10.13.5.  I was just going to upgrade to macOS 10.13.5 but now I'm not sure if I should hold off until this is resolved ...

I'm currently using expo, but I need to eject next week when I add some custom native code and a third-party native SDK.  So I'm worried about what might happen then.

Please advise if I should hold off on upgrading to macOS 10.13.5.  Thanks!

**Comment by scerelli** [comment]
I don't think is related to the 10.13.5 because if you run android it works. I think is more related to the upgrade because even on the `Reactiflux` channel I found people that had my same problem but all of them have upgraded RN from an older version.
