### ISSUE TITLE
Unable to load source map: RCTDataManager module is not available

### ISSUE THREAD

**Issue by steve-ng** [facebook/react-native#1960]
After upgrading to react-native 0.7.0, i encounter this error. Anyone else encounter this too?

**Comment by achang28** [comment]
I've noticed the same after upgrading from React Native 0.5.0 to 0.7.1, but also another error messages that I believer are related.  So i started another project from scratch (without adding any additional code), and found that after installing some particular React Native modules, the following error message begin to appear, even after shutting down, and restarting all the prescribed applications (e.g Terminal, Xcode, Chrome):

"Cannot read property 'None' of undefined", "undefined is not an object (evaluating 'RCTScrollViewConsts.KeyboardDismissMode.None')

Oddly enough, when turning on Chrome Debugger, the UI would switch to the following error message:
"Cannot read property 'None' of undefined".

**Comment by mikesurowiec** [comment]
If you look at the package.json of react-native-device-display and react-native-viewport, you'll see that they require older versions of react-native (and they require it as a dependency, rather than a peerDependency).

To make packages like that work when you want to use newer versions of react, what I've done is remove ```YOURPROJECT/node_modules/SOMEDEP/node_modules/react-native```. If you look in there you'll see an older version of react-native.

I doubt it's the best solution, but it worked for the quick and dirty upgrade

**Comment by achang28** [comment]
@mikesurowiec:  worked like a charm, and it's better than nothing.  Thanks for the (clear) advice.

**Comment by slooker** [comment]
I only have a single dependency in YOURPROJECT/node_modules, and it's react-native.  There's no other dependencies or instances of react-native in my node_modules directory, and I'm still getting this error.

**Comment by sahrens** [comment]
Does this still happen to you on the latest version?  Try restarting the packager, doing a clean recompile, etc.  Also, try creating a new project with react-native init NewProj and copy your JS and other files into it.

If none of that fixes it, please re-open.
