### ISSUE TITLE
[WebView] onScroll

### ISSUE THREAD

**Issue by cleercode** [facebook/react-native#1961]
Would like to be able to set an `onScroll` handler for a WebView.

**Comment by MossP** [comment]
:+1:  Although I am looking into how I could do this with what's already available. 
I think it could be possible using https://github.com/alinz/react-native-webview-bridge If I succeed when I get a chance to look at it, I'll post back.

**Comment by brentvatne** [comment]
Nobody working on this but a PR is welcome!

**Comment by MossP** [comment]
A simple use case for this would be to be able to handle the onScroll so that a navbar (or other interaction elements) could be hidden based on the scroll event. Probably more of a community thing though. I will be looking into this sometime soon.

**Comment by wilcosheh** [comment]
@MossP So do you have some ideas?

**Comment by kinhunt** [comment]
@MossP So do you have some ideas?

**Comment by MossP** [comment]
Ah, sorry @wilcosheh I somehow missed your comment. @kinhunt. I have some ideas but the requirement for it in the app i was writing was removed so I didn't flesh them out fully. Injecting script using the https://github.com/alinz/react-native-webview-bridge and checking for the state of scroll inside the webview and passing that back.. the issue i thought of though was that the scroll events may overlap and you would be hiding one thing and creating an incverted scroll inside the webview which then may unhide the navbar again. To get around this it could be on a delay but I didn;t get that far.

**Comment by kinhunt** [comment]
@MossP it's a smart workaround and the bridge module is cool. I will give it a try, the overlap issue seems to be difficult to solve.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/webview-onscroll

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
