### ISSUE TITLE
Debugging broken on Genymotion

### ISSUE THREAD

**Issue by aloifolia** [facebook/react-native#19641]
## Environment
Environment:
  OS: macOS Sierra 10.12.6
  Node: 10.3.0
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.3934792

Packages: (wanted => installed)
  react: 16.4.0 => 16.4.0
  react-native: 0.55.4 => 0.55.4

## Description
As soon as I hit the "Debug Js Remotely" button, a tab in the browser opens. This tab has the address 1.0.3.2:8081. The app then crashes with the message "Timeout while connecting to remote debugger". If I switch to localhost:8081 manually and reload the app, the tab stays at this address, but the _Sources_ are not loaded in the Chrome Dev Tools. 

## Steps to Reproduce
- start a virtual device on Genymotion
- start the app with `yarn run android`
- when the app is visible in the simulator, start remote js debugging
- wait a few seconds

## Expected Behavior
A browser tab with the address localhost:8081 should be opened. Chrome Dev Tools should load all available _Sources_.

## Actual Behavior
A browser tab with the address 10.03.2:8081 is opened. The app crashes after a few seconds.
<img width="430" alt="screen shot 2018-06-10 at 17 23 22" src="https://user-images.githubusercontent.com/1295054/41203156-80ed4266-6cd3-11e8-822c-087cfc1ab656.png">

**Comment by pulkit-mital** [comment]
I am facing the same issue. 

**Environment**

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.11.1
  Yarn: 0.21.3
  npm: 5.6.0
  Watchman: 4.4.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.3.2 => 16.3.2
  react-native: ^0.55.4 => 0.55.4

**Description**

I have also tried with Android Studio AVD and android phones as well. But facing the same issue, **Unable to connect with remote debugger**
When I click on "Debug JS Remotely" it opens [](http://10.0.3.2:8081/debugger-ui/ ) url instead of [](http://localhost:8081/debugger-ui/) which gets hanged and shows **site can't be reached**. Please look into this issue as we are not able to debug the code.

**Comment by kelset** [comment]
Closing as stale. Please open a new issue if issue still occur.
