### ISSUE TITLE
[Transforms] transform-origin support

### ISSUE THREAD

**Issue by cleercode** [facebook/react-native#1964]
Do Views have an equivalent of the CSS property [`transform-origin`](http://www.w3schools.com/cssref/css3_pr_transform-origin.asp)?

**Comment by chirag04** [comment]
Not yet. As per my conversation with @sahrens  and @vjeux  We will need to add it to support perspective transformations.

Can you PR?

**Comment by chirag04** [comment]
Reading from here: https://developer.mozilla.org/en-US/docs/Web/CSS/transform-origin
```
The transform-origin property lets you modify the origin for transformations of an element. For example, the transform-origin of the rotate() function is the centre of rotation. (This property is applied by first translating the element by the negated value of the property, then applying the element's transform, then translating by the property value.)
```

It seems you can still do it but just translating, then applying the transforms u want, and translating again. Does that solve?

@cleercode  Would love to know the usecase and some example.

**Comment by lelandrichardson** [comment]
@cleercode @chirag04 I'm working on implementing this right now. Use case was something I wanted to rotate as if it the axis was the left, instead of the middle.

Implementing transform-origin in terms of pixels is super easy, but I'm trying to follow the spec for allowing percent and keywords such as `left`, `center`, etc. (which are just short hand for percent values).

Anyone have any guidance on how to accomplish the ability to use percentage values? It would need to require knowledge of the width/height of the element, which I don't think we have at this stage, right?

**Comment by chirag04** [comment]
Nice. I would be interesting to have transform-origin. For now i would worry about having just numbers for it.

percent in general is not supported anywhere in react-native. Not sure why. We can implement percent as the next step i guess if required.

**Comment by lelandrichardson** [comment]
I'll submit the PR for just the numbers, then we can talk about how to implement the rest of the spec with percents & keywords.

I imagine percent isn't implemented in RN because for the most part, flexbox prevents the need for it. This is an exception where the transform property is implemented outside of flexbox, but still might require some knowledge of the element's size...

**Comment by lelandrichardson** [comment]
@chirag04 so there's a bit of a problem...

The way I've implemented this, I've basically set it up so that the user can specify x, y, z offsets from the "default origin", which is the middle of the element.

It looks like the w3c spec has the default set to the middle of the element, but the default is `50% 50% 0`, not `0 0 0`.

The way I have it working, if the user specifies `transformOrigin: { x: 2, y: 2}`, this results in the origin being `2px, 2px` from the center, whereas the w3c spec puts `transform-origin: 2px 2px` as `2px, 2px` from the *bottom left* of the element.

I'm happy to submit what I have, but this might present a problem as far as deviating from the expected behavior of an existing CSS property (as opposed to just not supporting it).

What do you think?  @vjeux , perhaps you have some thoughts?

**Comment by sahrens** [comment]
We should definitely match the web behavior where possible.

**Comment by lelandrichardson** [comment]
@sahrens agreed. does anyone have any thoughts on how to extract the width/height of the element in order to make this possible?  From what I can tell, supporting transform-origin in this way is not going to be easily possible without completely changing the location of these calculations to somewhere where we have this information handy. 

It's kind of a bummer, because implementing this as from the point of view of the center of the element, rather than the bottom left, is really simple.

**Comment by chirag04** [comment]
@lelandrichardson  Not sure if ``measure`` can help you extract the width/height of the element. Once you have that, i think it will be easy to do the manipulation.

**Comment by lelandrichardson** [comment]
@chirag04 `measure` would certainly allow me to emulate the spec in user-land, but not sure how to use it here.

Without moving a ton of code, this is all basically taking place in `precomputeStyle`, which has no knowledge of what element it is applying the style to. We could pull this stuff "up" one level and go into `computeUpdatedProperties`, but doing something that drastic feels quite wrong to me at this stage.

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/transforms-transform-origin-support

**Comment by jmurzy** [comment]
@lelandrichardson have you made further progress on this?

🍻

**Comment by alexHlebnikov** [comment]
Is there any way to emulate this? In my case I can't rotate icon properly without this property.

**Comment by lelandrichardson** [comment]
@alexHlebnikov transform origin is implemented as a matrix transformation by a translation matrix to the resulting transform matrix.  You can implement this currently by setting the `transformMatrix` style property, instead of the `transform` property, and doing the matrix operations yourself. If your transform is simple, this will likely end up as a fairly simple array of 16 numbers, some of which you will need to multiply appropriately from what you are using currently. Looking at the code in #2106 might help give you some context.

I talked to @vjeux about this PR some time ago and he seemed to agree that we could merge it in despite the difference from the web spec. If I get some time, I may try to revive the PR...

**Comment by af7** [comment]
Is this to be merged? I really needed it and using the matrix is not a nice solution. Thanks!

**Comment by faceyspacey** [comment]
+1

**Comment by westcoastavgallery** [comment]
+1

**Comment by joshuasoehn** [comment]
+1 what's the status of this?

**Comment by Obooman** [comment]
+1

**Comment by f0rr0** [comment]
+1

**Comment by utopianism** [comment]
+1

**Comment by btk** [comment]
+1

**Comment by dmbrowne** [comment]
+1

**Comment by rendomnet** [comment]
+1

**Comment by Jazz747** [comment]
+1 Come on, we need this badly!!

**Comment by orenklein** [comment]
+1 
If this one will be implemented we can easily replace animation of height or width with scaleY or scaleX which let us getting the most out of native driver feature.

**Comment by faceyspacey** [comment]
what's the latest on this?

**Comment by MrToph** [comment]
Also interested in this feature :)

**Comment by Jazz747** [comment]
+1, how can we make the devs notice this asap?

**Comment by fossage** [comment]
+1

**Comment by jmurzy** [comment]
In case anyone else is interested, I wrote up a blog post about implementing `transform-origin` in React Native using `matrix` transformations:

https://commitocracy.com/implementing-foldview-in-react-native-e970011f98b8

🍺

**Comment by iddan** [comment]
Isn't this issue should be in [yoga](https://github.com/facebook/yoga)?

**Comment by jtag05** [comment]
Are there any plans for implementing this?

**Comment by nextriot** [comment]
+1

**Comment by ThatGuySam** [comment]
+1

**Comment by IvarBorthen** [comment]
+1

**Comment by everdrone** [comment]
+1

**Comment by hvsy** [comment]
+1

**Comment by ryanscottaudio** [comment]
`transformMatrix` is [deprecated](https://facebook.github.io/react-native/docs/transforms.html#transformmatrix), so I'm not sure that's a good solution at this point

**Comment by micsun-al** [comment]
+1

**Comment by kosiakMD** [comment]
+1

**Comment by Komeyl94** [comment]
+1

**Comment by agrublev** [comment]
+1

**Comment by deehuey** [comment]
+1

**Comment by muygrafico** [comment]
+1

**Comment by miguelocarvajal** [comment]
+1

**Comment by youpen** [comment]
+1

**Comment by brayan9413** [comment]
+1

**Comment by patrickkempff** [comment]
+1

**Comment by numez** [comment]
+1

**Comment by gastonmorixe** [comment]
+1

**Comment by trsh** [comment]
transformMatrix is listed as Deprecated! What now?

**Comment by sfatih** [comment]
@trsh as i can see in source of RN there is still transformMatrix. You can use it like this:
![ss](https://user-images.githubusercontent.com/11010650/36154040-32ad5a08-10e1-11e8-959d-2cc3a347f021.png)

**Comment by sahrens** [comment]
@trsh: I think @sfatih is saying that you can use the non-deprecated `transform: [{matrix: ...}]` support instead of the deprecated `transformMatrix` to apply your own transform-origin equivalent to any transform you want to perform.

**Comment by trsh** [comment]
@sahrens why would anybody mention something so obvious (that I can use transform and roll my own transform-origin logic)? All this topic is about, that we want "transform-origin" to be a in-the-box feature for react-native. Because it's a struggle to calculate those deltas and scale for example by left top corner. Matrix kind of was a small relief.

**Comment by zxcv551133** [comment]
+1

**Comment by filipef101** [comment]
@trsh How did you solve? what matrix did you apply?

**Comment by trsh** [comment]
@filipef101 . No, I won't add deprecated features for a new project. I calculated it manually - I do scale, and then compensate (-translateX, -translateY) deltas from left and top. I will not share my code, as it's **dumb** and doesn't work very well. I suggest to take 3rd party math lib with matrix's calculate it your self, and then supply values for the transform. If you don't have fixed dimensions you will also need `onLayout` even to get needed dimensions.

**Comment by filipef101** [comment]
@trsh thanks! I actually solved with some trippy views and rotation, I actually applied the rotation using 3d matrix but it was the same not based on corner

**Comment by anish000kumar** [comment]
+1

**Comment by barghi** [comment]
+1

**Comment by michaeltrim** [comment]
+1

**Comment by victorwads** [comment]
+1
