### ISSUE TITLE
[ListView] Sometimes the listView onEndReached event can't fire

### ISSUE THREAD

**Issue by soliury** [facebook/react-native#1967]
Just see https://github.com/facebook/react-native/pull/1921

I have try to change the source but , I failed. 

Any body have some idea?

**Comment by soliury** [comment]
Is there anybody know the bug? Or this is not a bug, and they are designed in this way.

@brentvatne

**Comment by brentvatne** [comment]
Hey @soliury! Could you post a small reproducible example of this? It would help me to investigate

**Comment by soliury** [comment]
I think it may be not a bug, it is designed to be that, I have fixed this by another way, But I still want to know if this is to be designed to this. 

This is the reproducible example:

```
    onEndReached() {
        this._fetchTopic('get')
    }

    onScroll(e) {
        if (e.nativeEvent.contentOffset.y < -90) {
            this._fetchTopic('update')
        }
    }

    _fetchTopic(type) {
        if (this.isFreshing) {
            if (type == 'get') {
                this.setState({
                    getTopicError: 'fetchFailed'
                })
            }
            return
        }


        this.isFreshing = true
        this.setState({
            isLoading: true,
            loadingType: type
        })

        var page = (type == 'update') ? 1 : this.page + 1
        var tab = this.props.tab.name
        var actions = this.props.actions
        var getTopics = actions.getTopicsByTab
        var updateTopics = actions.updateTopicsByTab

        TopicService.req.getTopicsByTab({
            page: page,
            tab: tab,
            limit: 10
        })
            .then(topics=> {
                LayoutAnimation.configureNext(LayoutAnimation.Presets.spring)
                type == 'update' ? updateTopics(topics, tab) : getTopics(topics, tab)
                return null
            })
            .catch(err=> {
                console.warn(err)
                if (type == 'get') {
                    return err
                }
            })
            .done((err)=> {
                this.isFreshing = false
                this.setState({
                    isLoading: false,
                    err: err
                })
                this.page = page
            })
    }
```

So when the `_fetchTopic()` is update tab topic, at the same time I pull down to the bottom, it will fire the event `onEndReached`, and then it will run `_fetchTopic('get')`, but because the `this.isFreshing` is true, so it will do nothing , and return.  And after the `update` is finish, pull down to the bottom, it won't fire the event because it have fired once. 

I think it may be not a bug of ListView, it is designed to fired the event at a `ListView content size length`. So if , for example, at the length of `800`, fired the event and do nothing. this event don't cause the listView length change, so it will not fire the event again. 

Sorry, my english is not good, can you understand? 

If there is any unclear, just `@` me .

**Comment by jacob-israel-turner** [comment]
I'm having a similar issue.  Is there a way to reset the watcher after content is loaded?

**Comment by MossP** [comment]
Forgive me if this isn't completely accurate but.. `onEndReached` is for when the render-ahead has reached the end, not when the user has scrolled to the end. The idea is that this happens before the user gets there so that cells are preloaded for a better UI experience. To catch the actual scrolled-to-end event you can do so via `onScroll`. In your `onScroll` assigned function; check for the limits on the content length/offset and visible size to determine if the user has reached the end or not.

e.g. 
```
	onScroll: function(){
		if (this.refs.listview.scrollProperties.offset + this.refs.listview.scrollProperties.visibleLength >= this.refs.listview.scrollProperties.contentLength){
			this.scrollEndReached();
		}

    render: function(){
		return (
			<View style={styles.container}>
				<ListView
					ref="listview"
					onScroll={this.onScroll}
					dataSource={this.state.dataSource}
					renderRow={this.renderRow}
					renderScene={this.renderScene}
					renderHeader={this.renderHeader}
					renderFooter={this.renderFooter}
					onEndReached={this.onEndReached}
					onEndReachedThreshold={2000}
					automaticallyAdjustContentInsets={false}
					keyboardDismissMode="on-drag"
					keyboardShouldPersistTaps={true}
					showsVerticalScrollIndicator={true} />
			</View>
		);
}
```

**Comment by aleclarson** [comment]
`onEndReached` was primarily designed as a way to load more content in an "infinite" `ListView` once the user has scrolled close enough to the end of the `ListView` (specified by `onEndReachedThreshold`).

The `ListView` caches its `contentLength` when `onEndReached` is called ([seen here](https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/ListView/ListView.js#L578)). It then uses that cached `contentLength` to make sure `onEndReached` is only called once (unless the `contentLength` is changed to a new value).

IMO, it's confusing and should be changed. It's easy enough to cache the `contentLength` on your own if you want `onEndReached` to be called only when more rows need to be asynchronously rendered.

```js
onEndReached: function(e) {
  var contentLength = this.scrollProperties.contentLength;
  if (this.state.contentLength !== contentLength) {
    this.setState({ contentLength: contentLength });
    // Load more rows asynchronously
  }
}
```

**Comment by soliury** [comment]
Yes. I agree to change this, and let the user to handle the onEndReached Event fire.

**Comment by aleclarson** [comment]
PR #2440 addresses this issue

**Comment by soliury** [comment]
@aleclarson  well done.

**Comment by zrmedia** [comment]
i get same issue.  i have a api with 4 pages and this only get 2 page. how to fix that.

**Comment by MrPluto** [comment]
+1 here

**Comment by sahrens** [comment]
This should be fixed in the new FlatList component - let me know if you have issues with that.

**Comment by MossP** [comment]
@sahrens This new FlatList component is great and handles this much better but the underlying VirtualizedList does fail at being able to pull extra data for a list that may have changed since it was last requested (imagine a comment pages that needs to be able to pull new comments into the bottom of a list) as it prevents repeated calls in the list size has not changed. I'm looking at submitting a PR for it but haven't figured out the best way to handle it from everyones point of view rather than just my use case. I'm trying to look into the way ListView + [exponent/react-native-infinite-scroll-view](https://github.com/exponent/react-native-infinite-scroll-view) work together but you might already have something in mind?

For my use case I added a negative tolerance to the repeat checks in VirtualizedList so that upward swipes at the end of a list trigger onEndReached regardless of whether the list data had changed. It worked but displaying an indicator in the footer causes the list to keep re-triggering itself - easily fixed for me by excluding that size but maybe I should ensure that the footer height is excluded from the calculations to make it workable for everyone?

**Comment by sahrens** [comment]
Kinda sounds like you want a pull to refresh but at the bottom instead of top? That's not a very common case so we probably won't support that explicitly. Is it tricky for you to use an onScroll listener to get what you need?

**Comment by sahrens** [comment]
Although I might have misunderstood - I'll need to check the code more carefully to compare the implementation to ListView.

**Comment by MossP** [comment]
Yeah. I could do that. I had suggested that earlier in the thread for the original ListView, but @aleclarson had gone one step further suggesting that the repeat block get removed. His suggestion was the one that went forward in [your commit](https://github.com/facebook/react-native/commit/a4f7aa4853bb3385ed25ef5b1d7f86c58a59420c). I was merely skipping ahead to the second level fix this time around.

Of course my use case is - like you said - pull-to-refresh in both directions so I don't expect that to be baked in. Just to have the indefinite lock removed from the VirtualizedList for users scrolling around in a list.

**Comment by MossP** [comment]
See before and after checks in [ListView](https://github.com/facebook/react-native/commit/a4f7aa4853bb3385ed25ef5b1d7f86c58a59420c#diff-b4c8e4c7b175f06ffa084d8dca28e86aR597) and [VirtualizedListView](https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/Lists/VirtualizedList.js#L591)

Also the new docs for FlatList have incorrect params for Header/Footer component. Shall I submit a PR to correct the [Docs](https://facebook.github.io/react-native/releases/next/docs/flatlist.html#listfootercomponent) or are the params incorrect in FlatList/VirtualizedList?

**Comment by MossP** [comment]
To clarify on the above. It's the ListFooterComponent and ListHeaderComponent params that are incorrect (FooterComponent and HeaderComponent respectively).

**Comment by sahrens** [comment]
@MossP: which error has been fixed?

Yeah, I just forgot to update the docs when I updating the component naming. @evv: we should merge the docs fix into the RC.

**Comment by MossP** [comment]
@sahrens It was the error with the inconsistent params in FlatList / SectionList / VirtualizedList. I missed your commit from a few days ago.

The only remaining thing is whether we choose to make the onEndReach changes to VirtualizedList as they were with ListView (i.e allowing a user to re-trigger the onEndReach if they move outside and back again).

**Comment by Nealyang** [comment]
I'm having a similar issue.

**Comment by titkov5** [comment]
and me

**Comment by grubstarstar** [comment]
I think I'm having this issue with FlatList in react-native@0.43.2

I am paginating result sets in a list so I get exactly 10 every time I change the search filter. My items render fixed height so obviously the content length will be the same every time. I assume this is why the onEndReached is not called. It's only when I hit a search that returned less than 10 that I get onEndReached firing again, I assume it's because the content length has changed.

I looked at PR [2440](https://github.com/facebook/react-native/pull/2440/files) but that appears to be on ListView not FlatView. What's the best work around for this? Should I implement this using ListView instead?

**Comment by parkerproject** [comment]
I decided to use [https://github.com/expo/react-native-infinite-scroll-view](https://github.com/expo/react-native-infinite-scroll-view)

**Comment by parkerproject** [comment]
I had a similar issue of `onEndReached` not called but after playing around I discovered it had to do with the UI components(Native-Base) library I was using.
I suggest using the FlatList with no parent component and see if it works.
