### ISSUE TITLE
[ListView] Not sticky sectionHeaders

### ISSUE THREAD

**Issue by yelled3** [facebook/react-native#1974]
according to the docs:

> renderSectionHeader function #
(sectionData, sectionID) => renderable
If provided, a sticky header is rendered for this section. The **sticky behavior** means that it will scroll with the content at the top of the section until it reaches the top of the screen, at which point it will stick to the top until it is pushed off the screen by the next section header.

is it possible to make the ListView sectionHeader appear like a regular row, e.i like regular UITableView?

**Comment by ide** [comment]
AFAIK no but you could render plain rows to look like headers to get the look you want.

**Comment by ccheever** [comment]
Maybe the documentation should be updated to let people know they can just use a regular row if they want non-sticky headers? I bet its common for people to want this.

But otherwise, this can probably be closed @brentvatne / @ide ?

If someone is really motivated, she/he could write an application level component that would work just like ListView except with an option to toggle sticky/non-stick headers, and with non-sticky headers, it would just make renderSectionHeader return an empty view always, and insert header sections, which would each contain a single row that was rendered using the old renderSectionHeader method, before each section passed into the component. So I don't think there needs to be any change to core here.

**Comment by sahrens** [comment]
I don't think this is a major issue for people since you can just render the header as a row, so I'm going to close this out.

**Comment by Jpoliachik** [comment]
Found this out by accident, but if you put your ListView inside a ScrollView, the headers will not be sticky.

**Comment by jasonmerino** [comment]
@Jpoliachik Thanks for the tip there. Works like a charm.

**Comment by MITDelian** [comment]
ugh wish I found @Jpoliachik's comment 15 mins ago! Might be worth noting in the documentation that stickiness doesn't work in a ScrollView

**Comment by tomauty** [comment]
Putting ListView inside of ScrollView shouldn't be considered a sustainable workaround. There are big performance implications for very large lists.

**Comment by askrzynski** [comment]
@MITDelian, stickiness works the same in scrollview as without. It is just the nature of scrollview that table has maximum size and content is not scrolled inside it. This "fix" is rather hack then solution and should be used very carefully because of large lists (as @tomauty explained).

On native iOS this stickiness can be disabled by creating UITableView with "grouped" style and that can only be done in constructor.

**Comment by mcampsall** [comment]
My app does not have large lists and @Jpoliachik's solution worked a charm, thanks!

**Comment by satya164** [comment]
How about adding a prop to disable sticky headers? Anyone up for a PR?

**Comment by oldo** [comment]
@Jpoliachik You are a lifesaver! I have spent hours now trying to work out why my ListView headers weren't sticking... Thank you!!

**Comment by austincline09** [comment]
If you put a ListView inside of a ScrollView it might help to set scrollEnabled=false for the ListView props. This fixed a scroll hang issue for me
