### ISSUE TITLE
Memory leak when animated component is unmounted (via retained MessageQueue success callbacks)

### ISSUE THREAD

**Issue by keithkml** [facebook/react-native#19826]
## Environment
```
  OS: macOS High Sierra 10.13.5
  Node: 8.11.1
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: ~0.55.2 => 0.55.4
```
## Description
When an animated component is unmounted in the middle of an animation, the success callback passed to `Animation.start()` is retained in memory forever.

This happens because the callback is never called, and thus never [cleared](https://github.com/facebook/react-native/blob/d01ab66b47a173a62eef6261e2415f0619fefcbb/Libraries/BatchedBridge/MessageQueue.js#L394).

You can see in the screenshot below that `MessageQueue._successCallbacks` contains hundreds of functions after a few minutes of running the demo app I provided.

I was able to reproduce this on iOS and on Android. On iOS, I verified the V8 heap size and retained objects in `MessageQueue` using Safari's Remote Debugger on my Mac. But I'm actually not sure how to attach a JS debugger to a live Android app. That said, the app appears to run out of RAM quickly on Android, in fact more quickly than on iOS.

This issue seems to happen regardless of whether `useNativeDriver` is enabled.

## Reproducible Demo
https://snack.expo.io/HJ6sZZObX

## Screenshots

<img width="1360" alt="screen shot 2018-06-20 at 12 29 25 pm" src="https://user-images.githubusercontent.com/7430512/41671852-60903cac-7486-11e8-9624-d90222f5d769.png">

<img width="804" alt="screen shot 2018-06-20 at 12 30 49 pm" src="https://user-images.githubusercontent.com/7430512/41671867-69841464-7486-11e8-8a61-2d0949335b34.png">

<img width="1261" alt="screen shot 2018-06-20 at 12 35 43 pm" src="https://user-images.githubusercontent.com/7430512/41671900-79e2c7d8-7486-11e8-8256-71a42b2e93d6.png">

**Comment by kmagiera** [comment]
Hey @keithkml 

I've been experiencing a memory leak issue related to animated and found your report while searching for issues on RN repo.

I investigated your sample app and I think that in your case the problem is a bug in your application code.

So what happens in your case is that you have an infinite loop that spawns new animations regardless of if the component is mounted. You can compare your code to just calling `setInterval` in `didMount` and never stopping that process in `willUnmount`. Since you re-create that component 100 times a second it allocates 100 new infinite code loops.

It appears like animated releases the callback properly when component gets unmounted. In your case you just create a new one immediately after even if the component gets detached.  I modified your snack example to use `finished` attribute of the callback and if `finished == false` it means the animation has been stopped. In which case we don't want to start a new one as it means the component got unmounted. See changes in `loopAnimation` and `componentDidMount` here: https://snack.expo.io/SkC74G5QQ

Relevant code bits from RN repo explaining that the callback gets called properly:
1) Here we call `__detach` on animated value when animated component gets unmounted: https://github.com/facebook/react-native/blob/e708010d18f938e2d6b6424cfc9485d8e5dd2800/Libraries/Animated/src/createAnimatedComponent.js#L43
2) Detach propagates along animated nodes graph down to AnimatedValue object we started animation for. As you can see we call `stopAnimation` there: https://github.com/facebook/react-native/blob/e708010d18f938e2d6b6424cfc9485d8e5dd2800/Libraries/Animated/src/nodes/AnimatedValue.js#L92
3) Here is an implementation of `stopAnimation` method that calls `stop` method on animation object: https://github.com/facebook/react-native/blob/e708010d18f938e2d6b6424cfc9485d8e5dd2800/Libraries/Animated/src/nodes/AnimatedValue.js#L246
4) Each animation type (timing, spring etc) implements stop method that calls into the callback with `finished: false` parameter set. Here is an example for timing: https://github.com/facebook/react-native/blob/e708010d18f938e2d6b6424cfc9485d8e5dd2800/Libraries/Animated/src/animations/TimingAnimation.js#L148

**Comment by kmagiera** [comment]
So as mentioned above the callback gets in fact called (with `finished: false`) because of the fact the value is indirectly attached to the view that gets unmounted. The issue I've been observing that is causing a memory leak is when you don't actually use animated value in a view. In that case it is unable to tell when it gets detached and the callback will never be called.

I modified your snack to demonstrate that issue. The only change was that I commented out `transform` section of `circleStyle` in `render` method: https://snack.expo.io/rkr6If9mm

The above is obviously a mistake that is much harder to make, but if you have many animated values in your component and a couple people changing the code over time it may happen that you have some animations running on nodes that are not being used.

**Comment by keithkml** [comment]
Hi @kmagiera – very interesting and thank you for investigating.

I guess perhaps this bug report, then, is regarding documentation. I never would have expected the callback to be executed when an animation was canceled. In fact, I'm not sure the callback is even documented at all – I recall having to poke through tutorials and sample code to find that.
