### ISSUE TITLE
[View] Enable rasterization of views

### ISSUE THREAD

**Issue by Intellicode** [facebook/react-native#1986]
To increase the performance of scrolling when having views with shadows, it is possible to use

```
  layer.shouldRasterize = YES;
  layer.rasterizationScale = [UIScreen mainScreen].scale;
```

It would be nice if these settings could be made available through a property on the view. I could make a pull request with this feature if there are no objections to have this option enabled.

**Comment by ide** [comment]
`<View rasterize>` would be really great to have IMO, not only for static list cells but also for the stickers and bobbles in @sahrens' animation demo. cc @nicklockwood and @a2 for their thoughts.

**Comment by nicklockwood** [comment]
We have discussed this. We don't like using it internally because it's a black box in terms of when the cache is cleared or the snapshot recaptured. That makes it very difficult to give clear guidelines for when it should be used, or to predict when it will improve performance or make it worse.

It feels like the greater control that React gives us over layout should mean we can build a better version of this ourselves, that doesn't need to cope with arbitrary view mutations, and can work in a documented, deterministic fashion.

That said, nobody is currently working on such a feature, so I don't mind adding this for now as an iOS-specific property that may eventually go away again. cc: @vjeux, who may have thoughts on the matter.

**Comment by nicklockwood** [comment]
There's also a question of implementation. Would it be better to make this a property of `<View>`, or to add a `<Rasterized>` component that has the property baked in?

The case for making it a property are that you might want to toggle it on and off based on state (e.g. whether the view is currently animating). But should we encourage that?

**Comment by ide** [comment]
The thing I liked about exposing `shouldRasterize` is that similar opt-in flags have been useful in other view libs I've used - specifically `translateZ(0)` in CSS and `shouldRasterizeDescendants` in AsyncDisplayKit. The CSS case is interesting to me because the browser does try to optimize rendering and has similar control over layout, yet on occasion it's worthwhile to force a new graphics context with `translateZ(0)` and profile the speed and memory usage. I would like to try toggling rasterization when investigating perf bottlenecks, even if it might not pan out.

I guess I think that RN can expose `shouldRasterize` without encouraging it and can refer to the Apple docs and WWDC sessions for guidance. Session 240 from 2012 talks about, "when and how to use rasterization and snapshotting to create gliding animations" for example.

**Comment by ide** [comment]
As a reference point it looks like Android exposes a somewhat similar prop (renderToHardwareTextureAndroid). If that's working well for FB then it could make sense to add shouldRasterizeIOS.

**Comment by nicklockwood** [comment]
Yeah, the prop is similar but based on the discussions we've had with the Android team, the use cases are different, so if we do expose shouldRasterize, it should probably have a different name.
