### ISSUE TITLE
Denial of Service in Ejected React Native Project with npm

### ISSUE THREAD

**Issue by kirananagar** [facebook/react-native#19923]
# Description 

I ran npm audit in my project to look for dependencies, and one of the ones returned was: 
<img width="580" alt="screen shot 2018-06-27 at 11 04 17 am" src="https://user-images.githubusercontent.com/25674315/41955638-72546206-79fe-11e8-8136-a7fd7f377ee7.png">

I followed the advisories in nodesecurity.io, which recommended I upgrade ws to at least 3.3.1. Even after upgrading, the vulnerability does not resolve. ws --version returns 5.2.1. Any advice?

## Environment
Environment:
  OS: macOS Sierra 10.12.6
  Node: 10.4.1
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: ~0.55.2 => 0.55.4

**Comment by vovkasm** [comment]
@kirananagar As I far as I know:
1. ws used as dev dependency only
2. 0.56 fix it already

By the way do you really track real usage of ws in RN? Because:
1. The presence of this warnings does not mean a real vulnerabilities to a particular project.
2. The absence of these warnings does not mean the absence of vulnerabilities :-)

**Comment by kirananagar** [comment]
@vovkasm I'm not sure if I tracked real usage of ws in RN (And the fact I'm not sure makes me think I probably didn't 😬). I'm really new to all this, what's the best way to look at real usage and determine actual vulnerabilities in my project?
