### ISSUE TITLE
`react-native run-ios --device` not behaving like `react-native run-android --device`

### ISSUE THREAD

**Issue by Sean-Brown** [facebook/react-native#19946]
## Environment
Environment:
  OS: macOS High Sierra 10.13.5
  Node: 6.9.1
  Yarn: 1.7.0
  npm: 3.10.8
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

## Description
The `react-native run-android --device` command will build the application, install it on the device, and then launch the application on the device. The `react-native run-ios --device` command is not working completely: the command builds the application and installs it on the device correctly, however it will typically hang forever after that without ever launching the application. Most of the time it just hangs with the following message:

> ** BUILD SUCCEEDED **
> 
> 
> installing and launching your app on [my device name]

Only on rare occasions does it get past this step and it then prints something like "shake the device and enable JS debugging", which will make everything work as expected. However this is exceedingly rare, the majority of the time the cli just hangs.

## Reproducible Demo

- Initialize a new project: `react-native init TestRn`
- *in XCode create the provisioning profile for the app*
- Run: `react-native run-ios --device` -- the majority of the time it will build and install correctly but it will almost always hang when trying to connect with the javascript debugger (at least that's what I suspect it's doing when it hangs).

Note I'm testing this on an iPhone with the following specs:

- Version: 10.3.3
- Model: ME553LL/A

What's more is that the app will install and launch correctly 100% of the time if it's run through XCode, however this isn't an option for me because I can't debug any of the react-native javascript in XCode (unless there is a way that I'm not aware of).

**Comment by CrazyPython** [comment]
@Sean-Brown Run it in Xcode and shake your device. Press "Debug JS Remotely." From there you can debug your app, as it launches in chrome. I have personally debugged RN from Xcode and WebStorm simultaneously on 0.56.0-rc.4.

What do you mean by "hang"? Where does it stop? This bug report is quite vague, I suggest you look into this issue further yourself.

**Comment by CrazyPython** [comment]
@Sean-Brown Have you tried opening the app manually?

**Comment by Sean-Brown** [comment]
I was able to finally get debugging working by:

- running `react-native start`
- then in VS Code choosing the "Attach to Packager" debugging option
- then opening up the app on the iPhone, shaking the phone, and choosing the "Debug JS Remotely" option

I can work with this for now but I would prefer the simplicity of `react-native run-ios --device` (this works for android 100% of the time).

**Comment by CrazyPython** [comment]
yep, I believe that's the normal build process

@facebook-github-bot close

**Comment by Sean-Brown** [comment]
I'll close this as an issue if the `react-native run-ios --device` command is "working as intended", although based on the behavior of the `run-android` command I'd expect that `run-ios` would work similarly.

**Comment by CrazyPython** [comment]
Can you edit your original issue title and description to describe what you mean as working as intended?

>    running react-native start

`react-native run-ios` runs React Native in a new Terminal.app window automatically for me
>    then in VS Code choosing the "Attach to Packager" debugging option

React Native tooling can't do this step for you. This is editor-specific
>    then opening up the app on the iPhone,

I suppose opening up the app that could be automated.
>  shaking the phone, and choosing the "Debug JS Remotely" option

Shaking the phone and activating "Debug JS Remotely" should not be automatic. The app loads much slower for me when I don't use that option, and I often use my device to test. It's possible to add a command line option to do that upon app launch.

The React Native core team has more pressing things to think about, such as React Native's internal redesign. External contributors are typically the ones to fix bugs. If this issue is important to you, I encourage you to open a pull request. You can always [install from your own fork](https://stackoverflow.com/questions/17509669/how-to-install-an-npm-package-from-github-directly) or from [a local directory](https://stackoverflow.com/a/40116358).

**Comment by Sean-Brown** [comment]
The OP was essentially:

- when I run `react-native run-android --device` it automatically builds and installs the application on my device, then launches the app on the device
- when I run `react-native run-ios --device` it automatically builds and installs the application on my device, but it is unable to launch the app on the device and the CLI just hangs forever

I'm saying that the behavior of these two commands should be consistent.

Where I'm seeing this issue is in Visual Studio Code: I want to debug with the "Debug iOS" option. The "Debug Android" option works perfectly in VS Code but "Debug iOS" hangs.

**Comment by CrazyPython** [comment]
Have you tried running the command on a normal shell? VS Code is unaffiliated with React Native.

**Comment by Sean-Brown** [comment]
Yeah I tried in the default Mac terminal as well as iTerm2 and they both were having  the same issue with the `react-native run-ios --devices` command.

**Comment by CrazyPython** [comment]
Please edit your original issue to reflect this new information. Maintainers are more likely to implement your idea if the title and issue body are correct.

**Comment by Sean-Brown** [comment]
OK and thanks for taking the time to work with me on this issue.

**Comment by Sharathnasa** [comment]
@CrazyPython Same issue i'm also facing. If run from the Xcode its running fine. If give command from webstorm terminal or mac terminal `react-native run-ios --devices` its stuck for ever and ever.

**Comment by CrazyPython** [comment]
If you can launch it from your phone manually after running `react-native run-ios`, I think this is a minor issue. If you want to fix it yourself, go ahead. But it seems like the React Native community at large has bigger things to worry about.

**Comment by bogdant** [comment]
I am running into this issue also, it repro's consistently in multiple installations of RN from scratch.

"If you can launch it from your phone manually after running react-native run-ios, I think this is a minor issue."

The fact that it says "installing and LAUNCHING" and then hangs is not minor. There is no indication the app was deployed, no progress indicator (except the first time when previously the app didn't exist on the phone.) You're essentially sitting waiting for a sign that it's done and nothing happens.

Please revisit the severity assessment.

**Comment by CrazyPython** [comment]
What do you mean by hang? I'm fairly sure react-native-cli exits after the install process is over.

> There is no indication the app was deployed, no progress indicator (except the first time when previously the app didn't exist on the phone.) You're essentially sitting waiting for a sign that it's done and nothing happens.

Granted, there is certainly a documentation issue here. I can understand your frustration if you expected the app to launch itself and you waited a long time. This 

> Please revisit the severity assessment.

I'm not in any way a member of the React Native team- I'm simply trying to assist them in prioritizing issues. I'd say this issue is just frustrating- and it's not the only outstanding frustrating issue for the React Native community, many community libraries have similar frustrating issue.

That being said [the relevant code is here](https://github.com/facebook/react-native/blob/a1302392577789faab79dad0cb39b147464e0e42/local-cli/runIOS/runIOS.js#L251). You can edit out the "and launching" part, or you could dive deeper and see why it's not launching on the simulator. Over half of React Native's monthly code changes come from contributors, so don't be afraid to send a PR.

**Comment by buddhamangler** [comment]
I am experiencing this same exact issue.  At first i thought it was a problem with vscode and react-native-tools but i seem to get the same experience from the command line.  I have to start packager, attach to packager from vscode, then manually open app.  When testing things like notifications where i have to put the app in the background and then click on the notification i get strange behavior like 'packager not ready for debug' or the chrome browser debug window flying open and colliding with vscode.

**Comment by CrazyPython** [comment]
@bogdant, you're right. Can you see if the issue appears in 

@StevePotter could you read @bogdant's post and try to fix the bug? You were the last person you who touched the code. Y'all could check if the issue appears in v0.49.4, making sure Product Name and Scheme are the same in Xcode.

**Comment by danielmhanover** [comment]
I've run into this same issue - it's worth mentioning that if you change the `jsCodeLocation` from the network bundle to the local pre-bundled one, the issue no longer arises. This is almost definitely a network problem.

**Comment by mifi** [comment]
I think this is a regression, because it used to work before.
