### ISSUE TITLE
[Packager] Watchman fails silently if no root_files are found (ex. .git)

### ISSUE THREAD

**Issue by jaredly** [facebook/react-native#2042]
I kept getting this error:

```
 ERROR  Watcher took too long to load
Try running `watchman version` from your terminal
https://facebook.github.io/watchman/docs/troubleshooting.html
Error: Watcher took too long to load
Try running `watchman version` from your terminal
https://facebook.github.io/watchman/docs/troubleshooting.html
    at [object Object]._onTimeout (/Users/jaredly/clone/meditrate/node_modules/react-native/packager/react-packager/src/FileWatcher/index.js:98:16)
    at Timer.listOnTimeout (timers.js:110:15)

See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.
```

And reinstalled watchman a bunch of times, restarted my mac, etc...

Digging into the `sane` package, and adding [this patch](https://github.com/amasad/sane/pull/51), I was able to discover that the actual watchman error (it was working just fine) was:

```
resolve_projpath: none of the files listed in global config root_files are present in path `{the project root}` or any of its parent directories
```

Which really meant: running `git init` [solved everything](https://facebook.github.io/watchman/docs/config.html#root-files). But I wasted a lot of time wondering why things were broken.

So I think the right thing to do here is turn off [`enforce_root_files`](https://facebook.github.io/watchman/docs/config.html#enforce-root-files).

**Comment by wez** [comment]
@jaredly FWIW, at FB, we require enforce_root_files to be set to avoid having folks unwittingly create overlapping watches.  Because our source trees are so large this is a very real cause of performance and reliability issues with watching the filesystem, and is in fact the reason why this feature even exists :-)

@amasad is this a side effect of using watch-project exclusively now in sane?  Do we know if the only people that are hitting this are at FB?  I don't believe that folks outside FB will have the root files restrictions enabled, and certainly not by default.  It would be great to double check what is happening there as watch-project is supposed to fall back to watching the directory of interest if we can't locate a root.

**Comment by jaredly** [comment]
Ok -- yeah I guess it's just because of the watchman config in `/etc/watchman.json`.
This is an error that we should be able to detect though (as soon as sane exposes error events), and report.

**Comment by linshu123** [comment]
I just spent half an hour on this problem. It should really be documented in the troubleshooting page.
