### ISSUE TITLE
undefined is not an object (evaluating 'r.default')

### ISSUE THREAD

**Issue by dubu012** [facebook/react-native#20422]
Start with debug.apk on device

 "dependencies": {
    "native-base": "^2.7.1",
    "react": "16.4.1",
    "react-native": "0.56.0",
    "react-native-elements": "^0.19.1",
    "react-native-snap-carousel": "^3.7.2",
    "react-native-swiper": "^1.5.13",
    "react-native-vector-icons": "^4.6.0",
    "react-navigation": "^1.5.11"
  },
  "devDependencies": {
    "babel-jest": "23.4.0",
    "babel-preset-react-native": "5.0.2",
    "jest": "23.4.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
![11111111111](https://user-images.githubusercontent.com/33801302/43310661-2b1c0c86-91c3-11e8-925c-0289a7b201e9.png)

**Comment by Anujmoglix** [comment]
Still didn't get the solution of it, please respond.

**Comment by ashishchauhan05** [comment]
So the cause of error is just stupid.
In node_modules/react-navigation/src/navigators/DrawerNavigator.js there is imported TabRouter, which seems like component (starts with upper case), but in reality is just function, so when the code reaches const contentRouter = TabRouter(routeConfigs, tabsConfig); it throws that error because it does not resolve it as function? It does not even run it.
This is some new babel config stuff or something, which is just weird space of js for me...

So one way to fix this is to rename all TabRouter in that file to tabRouter. I hate to modify node_modules files, I bet there must be way to say to compiler (or whatever) that TabRouter as function is ok?

Its working for me.

**Comment by lbelavoir** [comment]
@ashishchauhan05  Instead of modifying the `node_modules` folder you can also edit your import as the following one:
`import { DrawerNavigator as drawerNavigator } from 'react-navigation'`
