### ISSUE TITLE
v0.8.0-rc.2 cannot resolve symbolic linked modules

### ISSUE THREAD

**Issue by xinthink** [facebook/react-native#2076]
Hi,
I'm using [`npm link`](https://docs.npmjs.com/cli/link) command to test my custom native component (in a demo app, it's opensource too), before it can be published to npm. 

It worked fine with `v0.7.1` and the previous. But `v0.8.0-rc.2` complaints `Unable to resolve module XXX`, thrown at `require.js:249`

It seems the problem is that [`npm link`](https://docs.npmjs.com/cli/link) results in symbolic link, for example:

    my_app
       |-- node_modules
              |-- react-native 
              |-- my-module -> ~/.npm/my-module (another symbolic link pointing to my local module)

However, it does work if I copy all the files to `node_modules/my-module`, but I don't think it's a good solution.

I'd appreciate that it could be fixed when `0.8` is finally released.

**Comment by brentvatne** [comment]
Hi there! Thanks for letting us know that it's not working for you in 0.8.0, I pointed that out in #637 where this problem is being tracked - I hope we can get a fix in for 0.8 but realistically that might not happen unless someone from the community lends @amasad a hand. If you want to investigate a fix it would be much appreciated!

**Comment by quentinyang** [comment]
I met the same issue too. Any one can solve it now?
