### ISSUE TITLE
Images intermittently disappear on Android

### ISSUE THREAD

**Issue by getaaron** [facebook/react-native#20898]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

Images intermittently disappear on Android

Several issues reported in https://github.com/facebook/react-native/issues/13600 which was closed due to being stale but the issue still persists

Using RN 0.55 (can't use 0.56 due to babel 7 and jest mock incompatibilities)

### Note / Possible Workaround

In my testing, this issue only occurs when importing images like:

```
<Image source={require('./my-icon.png')} />
```

But if I import via:

```
import myIcon from './my-icon.png';
```

then it works fine.

See the blog post [Quick Tip: Images in React-Native on Android Not Loading](https://blog.coop.software/2018/08/quick-tip-images-on-react-native-and.html) for more on this.

## Environment
Scanning folders for symlinks in /Users/aaronbrager/[REDACTED]/node_modules (17ms)

Environment:
  OS: macOS 10.14
  Node: 10.8.0
  Yarn: 1.9.4
  npm: 6.2.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

[skip envinfo]

## Possible cause

fresco has a cache pool for decoded bitmap, with a default size determined by the available runtime memory:

https://github.com/facebook/fresco/blob/3ccf021877571cc66c1cf28ecc82788f83579ad3/imagepipeline/src/main/java/com/facebook/imagepipeline/memory/BitmapCounterProvider.java#L32-L39

When the amount of memory is insufficient it throws an exception:

https://github.com/facebook/fresco/blob/8731cca73e5a4bd44387657dacd1f4562e549854/imagepipeline/src/main/java/com/facebook/imagepipeline/memory/BasePool.java#L237-L245

When this happens, React Native eats the exception and fails silently (see line 71):

https://github.com/facebook/react-native/blob/5c2720b089dd0fb277771b0ac8b0e7788c493e5d/ReactAndroid/src/main/java/com/facebook/react/modules/fresco/SystraceRequestListener.java#L45-L82

Instead of failing silently, React Native should do something (increase memory, free resources, clear cache… not sure) to ensure that the image being rendered appears.

Initial research done by @fatfatson (see https://github.com/facebook/react-native/issues/13600#issuecomment-370754425)

**Comment by getaaron** [comment]
As noted above I can’t update, but the issue I highlighted in the RN code base still appears in the latest build

**Comment by getaaron** [comment]
@hramos is there anyone you know of who worked on the RN/fresco integration who could look at this and at least tell me if I'm onto something?

**Comment by akhilaantony111** [comment]
It doesn't work for me

**Comment by sudobrackets** [comment]
Hi folks, Anyone have idea to resolve this issue

**Comment by redthree** [comment]
Hi, I'd like to add some evidence to this issue.

I'm developing an app made with **React Native** that uses [React Navigation](https://reactnavigation.org) to move between views. On one view I have a list of images which are local assets, called with `require`. 

Navigating into the view with the list of images one time was fine, return to the previous view then going again to the list of images made that some of them disappear. 

This is the sequence:
View 1 -> Ok
View 2 -> Ok
View 1 -> Ok
View 2 -> Fail
View 1 -> Fail

I was thinking of giving up and even started another version with Flutter, then I review the code that I wrote and found that to go back to the previous view I was doing this from the second view:

`this.props.navigation.push('View1')` instead of `this.props.navigation.goBack()`

Once I change it to `goBack()` the problem disappear. According to the React Navigation documentation the `goBack()` function hooks into the hardware back button.

> On Android, React Navigation hooks in to the hardware back button and fires the goBack() function for you when the user presses it, so it behaves as the user would expect.

My problem was clearly related to the React Navigation implementation, I hope this can help to solve this issue.

This are the dependencies use in my project:

```
"dependencies": {
    "@sentry/browser": "^4.4.1",
    "firebase": "^5.7.0",
    "lodash": "^4.17.11",
    "react": "16.6.1",
    "react-native": "0.57.7",
    "react-native-device-info": "^0.24.3",
    "react-native-gesture-handler": "^1.0.10",
    "react-native-image-progress": "^1.1.1",
    "react-native-linear-gradient": "^2.5.3",
    "react-navigation": "^3.0.7",
    "uuid": "^3.3.2"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.50.0",
    "react-test-renderer": "16.6.1"
  }```

**Comment by dulmandakh** [comment]
Hello there 👋 this issue has been reported for an old version of React Native. Ideally we'd like everyone to be using 0.59 (see the [awesome changes](https://facebook.github.io/react-native/blog/2019/03/12/releasing-react-native-059) it brought) but we know updating can be a pain. We are going to close this issue because it's from a version before 0.57, which is really old.

But please, if it's actually still an issue with 0.59 please comment below and we can reopen it. Even better, please send us a pull request with a fix 😊

**Comment by blackcodeblue** [comment]
I just ran into this issue using 0.59. In fact, even Text components won't render, likely due to memory issues.
