### ISSUE TITLE
React Native project initial compilation error

### ISSUE THREAD

**Issue by DreySkee** [facebook/react-native#2107]
Hi,

I created a new React Native project and ran it in Xcode. I get following error in the terminal and can't figure how to fix:

 ERROR  EACCES, permission denied '/Users/andrey.pokrovskiy/.babel.json'
{"errno":3,"code":"EACCES","path":"/Users/andrey.pokrovskiy/.babel.json","syscall":"open"}
Error: EACCES, permission denied '/Users/andrey.pokrovskiy/.babel.json'
    at Object.fs.openSync (evalmachine.<anonymous>:438:18)
    at Object.fs.writeFileSync (evalmachine.<anonymous>:977:15)
    at save (/Users/andrey.pokrovskiy/Desktop/lab/NewiOsApp/node_modules/react-native/node_modules/babel-core/lib/api/register/cache.js:35:19)
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:906:3

I've tried chown the file and looked for a solution but no luck.

Meanwhile Xcode throws Apple Mach-o linker error with 25 errors inside.
I never worked with Xcode so have no clue what that means.

Seemingly easy installation turned into a nightmare for me. 
Any help would be appreciated!

**Comment by brentvatne** [comment]
Hi there! You're best off trying out StackOverflow for this kind of question because I don't believe this is an issue with React Native, but rather the system configuration on your end - if it turns out to be a bug then please come back here and ping me and we can investigate further :smile: In addition to StackOverflow, there are some other issues that may be useful for you: https://github.com/facebook/react-native/issues?utf8=%E2%9C%93&q=EACCES

**Comment by Teddywow** [comment]
sudo chmod 777 /Users/xxxx/.babel.json

**Comment by rajeshm20** [comment]
yes baby....it works great..thanks
sudo chmod 777 /Users/username/.babel.json

and again react-native init <YourProject>
