### ISSUE TITLE
[TextInput] Ability to style text within a TextInput

### ISSUE THREAD

**Issue by ehd** [facebook/react-native#2109]
![bacon panca](https://cloud.githubusercontent.com/assets/76208/8874552/4c12c826-3212-11e5-9e93-a392f46497a8.png)

Say I have a `TextInput` and a parser that recognizes `Pancakes` as a keyword. When a user types, the parser re-parses the input and the style should change accordingly:

![bacon-pancakes](https://cloud.githubusercontent.com/assets/76208/8874565/6d843e68-3212-11e5-938d-c47562559a0b.png)

In order to do this I'd have to style the `TextInput`'s current value while the user is typing. My questions:

- Is it possible to change the value at all?
- Is it possible to have styled text within a `TextInput`?
- Is this something that core would consider useful, or is this an ecosystem module?

**Comment by nicklockwood** [comment]
We don't currently expose an API to style subranges of text in a <TextInput>, although it is possible to specify an attributed string using the underlying iOS UITextView API, so it could be done in theory.

It would probably have to be implemented by allowing <Text> nodes to be placed inside a <TextInput>, so that there was a node to attach the styles to other than the <textInput> itself.

This would certainly be useful, and feels like it should be implemented in the core component rather than a plugin.

Pull requests welcome :-)

**Comment by ehd** [comment]
Thanks for the detail answer, I'll give the pull request a try :-)

**Comment by alfonsodev** [comment]
@ehd any progress on this ?  thanks

**Comment by olivierlesnicki** [comment]
@ehd how do you style the text cursor to appear green?

**Comment by nicklockwood** [comment]
@olivierlesnicki the cursor color is derived from the view's tintColor. We don't expose it in JS, but you can set it on your native UIWindow or RCTRootView and it will propagate down to all subviews. E.g, put this in your AppDelegate:

      self.window.tintColor = [UIColor greenColor];

**Comment by ehd** [comment]
This is now part of [v0.15.0-rc](https://github.com/facebook/react-native/releases/tag/v0.15.0-rc) :fireworks: 

Thanks @nicklockwood! Do you know who could review setSelectionRange here #2668?
