### ISSUE TITLE
You need to call create() at least once to create the singleton

### ISSUE THREAD

**Issue by dharmik** [facebook/react-native#21435]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.11.4
  Yarn: Not Found
  npm: 6.4.1
  Watchman: 4.6.0
  Xcode: Xcode 9.0 Build version 9A235
  Android Studio: 3.1 AI-173.4907809

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

## Description
![screenshot_20181001-124245](https://user-images.githubusercontent.com/1510175/46274708-04148080-c578-11e8-833e-63ddcd31730b.png)

## Reproducible Demo
Have no proper steps but some time happen and sometimes not.

**Comment by sharmahdk13s** [comment]
I am facing that same issue but not able to reproduce it. @dharmik 

If I change my device and reinstall it again it solves and sometimes it not.

**Comment by hey99xx** [comment]
BackgroundTaskManager is not part of react-native, it's part of https://github.com/jamesisaac/react-native-background-task so your issue is in the wrong place.

Also please read [the Android section of that library's README file](https://github.com/jamesisaac/react-native-background-task#android), they mention you need to call `BackgroundTaskPackage.useContext(this);` to be able to use the library. I'm pretty sure you're missing that.
