### ISSUE TITLE
App crashes on clicking more option on TabBar iOS 

### ISSUE THREAD

**Issue by venk-aw** [facebook/react-native#2147]
When you have too many items in a TabBar, app gives you the option of 'more'. But when you click on that one, app crashes.

Found that the index for that 'more' TabBar item is out of index. 
This is happening in RCTTabBar.m in TabBar Controller Delegate method.

**Comment by browniefed** [comment]
@venk-aw is this still happening for you with latest .11-rc? Can you supply a recreation on rnplay.org

**Comment by brentvatne** [comment]
Closing until example provided because I don't think this still happens

**Comment by alvaromb** [comment]
@brentvatne this is still happening.

**Comment by alvaromb** [comment]
<img width="687" alt="screen shot 2016-10-05 at 15 08 55" src="https://cloud.githubusercontent.com/assets/289640/19114293/acbc8040-8b0d-11e6-9fae-8366128c2dcd.png">

Here you have an screenshot of the error happening under `v0.33`.

**Comment by bangnguyensea** [comment]
Not fixed yet, I use React Native 0.46.4

**Comment by brentvatne** [comment]
I don't know if many people actually use TabBarIOS, perhaps it should be removed from core? cc @hramos

**Comment by hramos** [comment]
Ah, I'm a big fan of TabBarIOS and TabBarIOS.Item for iOS-only apps, as it renders a native UITabBar. That said, it's not ideal for use in React Native apps due to its imperative APIs. 

From what I can tell, it's not used internally at Facebook, however. This seems like a good candidate for removing from core.
