### ISSUE TITLE
[ListView] Nested items are locked if another tab is clicked while ListView is still 'scrolling'

### ISSUE THREAD

**Issue by MossP** [facebook/react-native#2152]
If you have a `<ListView/>` inside a `<Navigator/>` and a `<TabBarIOS/>` Navigation between the tabs will cause the ListView to lock up if it was still scrolling at the time that it was navigated away from.

Returning to the list view will yield no click information until it has been scrolled and allowed - at least a small amount - to decelerate.

I have uploaded an example of the bug at RNPlay https://rnplay.org/apps/IpHZ6g/edit

If you scroll the first tab, and click tab 2 *while it's still scrolling* then navigate back to tab1, you will not be able to click anything until it has been scrolled again. (If you can click you will get an intentional RSOD)

**Comment by dsibiski** [comment]
Your example seems to be broken, the `ListView` doesn't scroll down...

**Comment by MossP** [comment]
It scrolls fine? I've just scrolled, can you not scroll at all (by flicking up to page down)?

**Comment by browniefed** [comment]
@MossP any news on this. I was able to reproduce it but it took me some time.

**Comment by MossP** [comment]
No update, it's still an issue in 0.11-rc. To trigger it easily just scroll the contents on the first tab, and while it's decelerating, click 'tab 2'.

When you then click tab 1 - you will notice that you are unable to click it.

I've changed the way that I've illustrated the error as the intentional crash was probably confusing. It will now popup an alert box if the click works, or nothing will happen if it doesn't (after switching tabs whilst decelerating).

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/listview-nested-items-are-locked-if-another-tab-is-clicked-while-listview-is-still-scrolling

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is heavily focused working on performance.
