### ISSUE TITLE
Settings.watchKeys(...) callback not fired when Settings.set() is used

### ISSUE THREAD

**Issue by benzman81** [facebook/react-native#21607]
- [ ] Review the documentation: https://facebook.github.io/react-native
  - [ ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 57.88 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      npm: 5.6.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: 0.57.0 => 0.57.0
    npmGlobalPackages:
      react-native-app-id: 0.0.5
      react-native-cli: 2.0.1

## Description
When registering a callback via Settings.watchKeys, then it is never called if a value for a watched key is changed via Settings.set(). Only if I add a Settings.bundle to Xcode and change the Value via the iOS Settings app, then the callback is called.

## Reproducible Demo
Simply register a callback on "foo" via Settings.watchKeys and call Settings.set{foo:"new Value"} later. The callback will not be called.

**Comment by TroX-oO** [comment]
Hello, I've been through the same issue, and i've checked the ios native implementation. It is clearly written that no update should be triggered when a value is set with the method Settings.set()

https://github.com/facebook/react-native/blob/44fe9904ace426088e20727212cccce8796b8068/Libraries/Settings/RCTSettingsManager.m#L82

I don't know why it is implemented like this, but it seems to be the expected behaviour.
It is a bit surprising that the documentation does not mention this case however.

https://facebook.github.io/react-native/docs/settings

As a workaround, instead of counting on the watchkeys, I will trigger an action as well as setting my property in UserDefaults.
