### ISSUE TITLE
[ListView] Is there a layout-only view available in RN?

### ISSUE THREAD

**Issue by paramaggarwal** [facebook/react-native#2162]
My use-case is to implement an infinite list view by only rendering rows that are are returned from `onChangeVisibleRows` and not add native subviews for everything else. But they should be considered in the layout tree so that they take up there space.

Currently I listen to `onLayout` event, and then set an empty `View` with top, left, height, width set as the response from `onLayout` when all the views were in their place. This means that there still is a native subview added, and hence when I use the View Debugger in Xcode, I still see lots of subviews in the ListView's contentView. Ideally anything that is not on screen should not render at all.

Hence something like a `<View>` component that actually does not add views to native view hierarchy is what I am looking for!

**Comment by ide** [comment]
There is not a layout-only view. There used to be an optimization to infer which views affected only layout but it was reverted because it broke a couple things and was complicated.

For your specific problems you can set removeClippedSubviews to remove off-screen rows. That's what we do with https://github.com/exponentjs/react-native-infinite-scroll-view and it works well.

**Comment by paramaggarwal** [comment]
Ah, that's true. `removeClippedSubviews` would do the same. Thanks @ide.

**Comment by paramaggarwal** [comment]
@ide 

1. `ListView` provides `onEndReached ` and `onEndReachedThreshold`. Looks like https://github.com/exponentjs/react-native-infinite-scroll-view provides the same functionality?
2. Using `removeClippedSubview` still keeps a reference to the views and hence the views still do take up memory, right? Meaning as user scrolls down, the memory use will grow linearly?

**Comment by ide** [comment]
1. Yes there is overlap in behavior. The infinite scroll view works for all scroll views (not just list views). Also infinite scroll view is more of a controlled component: its owner passes down props like isLoadingMore and canLoadMore. I would like to learn which API is more useful in complex applications.

2. I believe the native views are retained (not 100% sure though) but in 0.9.0 or 0.10.0, images and text will be removed from the layers. The views are retained because they could be stateful.

**Comment by paramaggarwal** [comment]
That clarifies. Thanks @ide.
