### ISSUE TITLE
[Leak] React Native built as a dynamic framework leaks (?) JSContexts

### ISSUE THREAD

**Issue by ide** [facebook/react-native#2165]
I built RN as a dynamic framework (`@import React` is pretty sweet) and saw that after reloading, the Safari Develop menu would continue to show entries for JSContexts that should have been deallocated. It's possible to connect to them although entering any expression in the console causes the app to crash inside of JSC. Switching back to static libraries fixes the issue.

**Comment by jaygarcia** [comment]
This is pretty cool.  I've theorized about this over the past few months.

**Comment by ide** [comment]
I tried to make an isolated repro (Podfile with `use_frameworks!`) but no dice so far.

**Comment by jaygarcia** [comment]
It was my understanding that Apple only allowed static libs (.a) to be included by 3rd party devs.  Is my understanding wrong or outdated?

**Comment by ide** [comment]
iOS 8+ support dynamic frameworks signed by Apple.

**Comment by jaygarcia** [comment]
Ah!! Many thanks.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/leak-react-native-built-as-a-dynamic-framework-leaks-jscontexts

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
