### ISSUE TITLE
Native `presentViewController` causes the main RN frozen?

### ISSUE THREAD

**Issue by liuda101** [facebook/react-native#2170]
In my RN code, I use `ONFEPresentView.presentView({})`. Then in the `AccountLogin` RN code, I use `ONFEPresentView.dismissView({})`. No error exported. But after dismiss, the main RN application is not responsiable. 

This is my code:

```
#import "ONFEPresentView.h"
#import "RCTRootView.h"

@implementation ONFEPresentView

RCT_EXPORT_MODULE();

RCT_EXPORT_METHOD(presentView:(NSDictionary *)options)
{
  
  UIViewController *modalViewController = [[UIViewController alloc] init];
  modalViewController.modalPresentationStyle = UIModalPresentationFullScreen;
  modalViewController.title = options[@"title"];
  
  dispatch_async(dispatch_get_main_queue(), ^{
    UIViewController *root = [[[[UIApplication sharedApplication] delegate] window] rootViewController];
    
    
    NSURL *jsCodeLocation;
    
    jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/login.ios.bundle"];
    
    RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                        moduleName:@"AccountLogin"
                                                     launchOptions:nil];
    
    [modalViewController setView:rootView];
    
    [root presentViewController:modalViewController animated:YES completion:nil];
  });
}

RCT_EXPORT_METHOD(dismissView:(NSDictionary *)options)
{
  
  dispatch_async(dispatch_get_main_queue(), ^{
    UIViewController *root = [[[[UIApplication sharedApplication] delegate] window] rootViewController];
    
    [root dismissViewControllerAnimated:YES completion:nil];
  });
}




@end

```

**Comment by udfalkso** [comment]
Hi @liuda101 Did you ever solve this issue?  Thanks

**Comment by brentvatne** [comment]
cc @dsibiski

**Comment by dsibiski** [comment]
@liuda101 One of the problems here is that you are creating a new `RCTRootView` (and thus a new JS bridge) **within** your current JS bridge. The reason this is problematic is because when you create a new JS bridge, it instantiates all bridge modules, including `ONFEPresentView`. In this case for the 2nd time. So most likely those multiple instances of that bridge module is screwing things up.

There are a couple ways that you can possibly handle this...the easiest would be to use the `moduleProvider` block on `RCTBridge` to pass in the current instance of `ONFEPresentView`. This **might** solve the problem.

Here is how you could do that, instead of only creating a `RCTRootView`, do this:

```
RCTBridge *bridge = [[RCTBridge alloc] initWithBundleURL:jsCodeLocation 
                                          moduleProvider:^ NSArray *{
                                            return @[self];
                                          }
                                           launchOptions:nil];

RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge moduleName: @"AccountLogin"];
```

Another way may be to re-organize things slightly here. You can see an example that might help you in thinking about things a little differently in my example repo here: https://github.com/dsibiski/react-native-embedded-app-example

The "Advanced" example, "Native Modal With RN Navigation" shows another way to possible handle this problem of needing to communicate with a bridge module that contains another root view. (it doesn't address this exact use-case, but it's close)

**Comment by brentvatne** [comment]
Thanks @dsibiski for the fantastic reply! Awesome repo you have going there!

**Comment by dsibiski** [comment]
Thanks @brentvatne :)
