### ISSUE TITLE
[PushNotifications] implicit declaration of function 'RCTNullIfNil' is invalid in C99

### ISSUE THREAD

**Issue by edo1493** [facebook/react-native#2174]
I am trying to import PushNotificationIOS, but I somehow get this: 
![screen shot 2015-07-30 at 15 59 01](https://cloud.githubusercontent.com/assets/2309030/8986415/08bb9ee2-36d4-11e5-923a-181b79a7c3ed.png)

Has anyone seen it? 
I am using the latest version of PushNotificationIOS.

**Comment by PhilippKrone** [comment]
I have the same error message in other cases, e.g. "RCTJSErrorFromNSError". Currently using master.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/pushnotifications-implicit-declaration-of-function-rctnullifnil-is-invalid-in-c99

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is heavily focused working on performance.
