### ISSUE TITLE
Multiple Dev Menu's on Device

### ISSUE THREAD

**Issue by afisherdev** [facebook/react-native#21747]
- [ ] Review the documentation: https://facebook.github.io/react-native
  - [ ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment

  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 29.78 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 9.4/9F1027a - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.5.2 => 16.5.2
      react-native: ^0.57.2 => 0.57.2
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-camera: 1.3.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
## Description
Whenever I load my app onto my real device it displays 2 Developer Menu's on top of each other.

## Reproducible Demo
Initialize a new react app and run it on a device. Shake the device for the developer menu and watch 2 menu's pop up on top of each other.
![img_0483](https://user-images.githubusercontent.com/29619059/46858360-ff459d00-cdbf-11e8-8918-294463710ab2.GIF)

**Comment by bashbers** [comment]
Your first dev menu has an additional entry named "Start systrace".

**Comment by kelset** [comment]
I can confirm that this happens still to me with latest version (0.57.8) but it's intermittent, and if I kill the app & simulator & restart it goes away.

**Comment by vrgimael** [comment]
Happens to me too on 0.58.3 with pretty much a fresh project + cocoa pods

**Comment by vrgimael** [comment]
Damn, just spent a few hours trying to figure this out (I thought it might have something to do with the pods but it seems that's not the problem).

Just noticed something interesting that makes sense with what @kelset said about the glitch being intermittent and seeming to go away when you kill the app:

There's another issue happening here in which when I launch the app (from closed, not background) this error comes up for a second "Unable to find module for DevLoadingView" (does this happen to you guys too?) and then the app loads normally (seems like the loading screen needs fixing guys). During this one second, however, the button to force reload the app appears at the bottom as part of the dev UI.

The double dev menu glitch only happens here when I tap this reload button quickly - if I just wait through the "DevLoadingView" error this glitch does not happen, consistently.

I guess tapping reload forces the dev menu (or maybe some other things too) to spawn twice.

Hope this helps someone with investigating this issue, I won't have time to look much further now.

**Comment by Meox92** [comment]
Same problem here, sometime the first menu shows 'Enable remote debug' and the second 'Disable remote debug' or viceversa...

**Comment by cpojer** [comment]
Does anybody know how we can repro this reliably so we can fix this?

**Comment by danielmtavares** [comment]
It's happening to me as well on the iOS simulator on 0.58.6. Unfortunately I have no identified reliable steps to repro it.

**Comment by kelset** [comment]
I think I've actually seen a PR with a fix for this. Does it still happen in latest 59? 🤔

**Comment by jacobwallstrom** [comment]
It still happens on 0.59.5

**Comment by mcavaliere** [comment]
Happening on 0.59.9 as well.

**Comment by Villar74** [comment]
Happening on 0.60.0

**Comment by JonnyBurger** [comment]
I had this option enabled, and when I disabled it the problem went away:

![Screenshot 2019-07-10 at 13 38 17](https://user-images.githubusercontent.com/1629785/60966256-1b0ead00-a318-11e9-93dd-473952439f4f.png)

Although I'm not sure why I enabled it in the first place, curious if this is the same issue for other people.

**Comment by kelset** [comment]
@JonnyBurger would you mind trying to open a PR that sets that flag to false for the template? Sounds like it may be it 🤔

**Comment by JonnyBurger** [comment]
@kelset In the current template the flag is already set to false.. it must have previously been true or something else must have happened so that it got set to true on my project 🤔

**Comment by yolpsoftware** [comment]
Still happens with 0.60.5

**Comment by yolpsoftware** [comment]
I don't have exact reproduction steps, but I think it often happens when you do this:

- Enable Hot Reloading
- Enable JS debugging in Chrome devtools
- Set some breakpoints so that the debugger pauses
- Now, while the debugger is paused, change a current file to trigger Hot Reloading

I just checked, and unfortunately I couldn't reproduce the problem by doing this **once**. However, I had this problem twice after exactly that scenario (no idea what scenario was before that).

**Comment by JonnyBurger** [comment]
It happened to me recently again and I also think it gets triggered by a combination of Remote Debugging, Hot Reloading, running on device after some time (programming your app for a while, reloading often, making mistakes). Must remember to set some breakpoints next time and report here!

**Comment by yolpsoftware** [comment]
The issue happened to me many times on the simulator, so I don't think running on device is a factor.

**Comment by kelset** [comment]
Can anyone check if it still happens with the first 61 rc?

I also believe it's related to what @JonnyBurger mentions - and maybe with the introduction of Fast Refresh it's fixed?

**Comment by JonnyBurger** [comment]
Still happens, BUUT I have managed to set some breakpoints!

This line here gets called twice:
https://github.com/facebook/react-native/blob/master/React/DevSupport/RCTDevMenu.m#L115-L118

So when the **shake notification** gets sent just once, the callback gets called twice!
https://github.com/facebook/react-native/blob/master/React/DevSupport/RCTDevMenu.m#L31

I did a quick test and adding `      [[NSNotificationCenter defaultCenter] removeObserver:self name:RCTShowDevMenuNotification object:nil];
` is **not** a viable fix since `self` is different and will therefore not remove the old listener.

Here is the stacktrace of when RCTDevMenu gets initialized for the second time and triggers the bug:

<details>
#0	0x00000001050ae654 in -[RCTDevMenu init] at /Users/jonnyburger/bestande/node_modules/react-native/React/DevSupport/RCTDevMenu.m:115
#1	0x0000000105001f24 in ::__44-[RCTModuleData initWithModuleClass:bridge:]_block_invoke() at /Users/jonnyburger/bestande/node_modules/react-native/React/Base/RCTModuleData.mm:77
#2	0x00000001050028cc in ::-[RCTModuleData setUpInstanceAndBridge]() at /Users/jonnyburger/bestande/node_modules/react-native/React/Base/RCTModuleData.mm:124
#3	0x00000001050048fc in ::__25-[RCTModuleData instance]_block_invoke() at /Users/jonnyburger/bestande/node_modules/react-native/React/Base/RCTModuleData.mm:294
#4	0x000000010507a40c in RCTUnsafeExecuteOnMainQueueSync at /Users/jonnyburger/bestande/node_modules/react-native/React/Base/RCTUtils.m:267
#5	0x000000010500463c in ::-[RCTModuleData instance]() at /Users/jonnyburger/bestande/node_modules/react-native/React/Base/RCTModuleData.mm:293
#6	0x0000000104f99318 in ::-[RCTCxxBridge moduleForName:lazilyLoadIfNecessary:](NSString *, BOOL) at /Users/jonnyburger/bestande/node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm:488
#7	0x0000000104f99920 in ::-[RCTCxxBridge moduleForClass:](Class) at /Users/jonnyburger/bestande/node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm:524
#8	0x00000001050b21e8 in -[RCTBridge(RCTDevMenu) devMenu] at /Users/jonnyburger/bestande/node_modules/react-native/React/DevSupport/RCTDevMenu.m:483
#9	0x000000010501dc30 in -[RCTPerfMonitor setBridge:] at /Users/jonnyburger/bestande/node_modules/react-native/React/Profiler/RCTPerfMonitor.m:144
#10	0x00000001cd7088d0 in -[NSObject(NSKeyValueCoding) setValue:forKey:] ()
#11	0x0000000105002fa0 in ::-[RCTModuleData setBridgeForInstance]() at /Users/jonnyburger/bestande/node_modules/react-native/React/Base/RCTModuleData.mm:175
#12	0x0000000105002b28 in ::-[RCTModuleData setUpInstanceAndBridge]() at /Users/jonnyburger/bestande/node_modules/react-native/React/Base/RCTModuleData.mm:144
#13	0x00000001050048fc in ::__25-[RCTModuleData instance]_block_invoke() at /Users/jonnyburger/bestande/node_modules/react-native/React/Base/RCTModuleData.mm:294
#14	0x000000010507a40c in RCTUnsafeExecuteOnMainQueueSync at /Users/jonnyburger/bestande/node_modules/react-native/React/Base/RCTUtils.m:267
#15	0x000000010500463c in ::-[RCTModuleData instance]() at /Users/jonnyburger/bestande/node_modules/react-native/React/Base/RCTModuleData.mm:293
#16	0x0000000104f9e2e8 in ::__49-[RCTCxxBridge _prepareModulesWithDispatchGroup:]_block_invoke() at /Users/jonnyburger/bestande/node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm:859

</details>

**Comment by JonnyBurger** [comment]
@stale Please keep it open!

**Comment by brmk** [comment]
Happens to me on 0.61.4

**Comment by heresmyinfo** [comment]
Happening to me on 0.61.4 too - maddening.

**Comment by export-mike** [comment]
happening to me on 0.61.5

**Comment by juanlet** [comment]
Happening to me on 0.61.5

**Comment by yolpsoftware** [comment]
Happening on 0.61.4.

**Comment by stephanoparaskeva** [comment]
2 Dev Menus, Keep getting error saying 'not ready to debug'  and my Mac overheats like crazy in general. What is going wrong?

**Comment by renatobenks** [comment]
I have been faced a lot of times this thing happening, and it sounds to happen just in iOS.

by the way, it just happens when I use `CTRL + CMD + Z` which I just use when the `CMD + D` doesn't work.

**Comment by l1fe** [comment]
Is there an update on this? This seems very annoying!

**Comment by renatobenks** [comment]
I didn't fix that yet @l1fe, even didn't find any workaround, sometimes it happens, and other times just don't 😕

**Comment by origamih** [comment]
This is super annoying and frustrated and a HUGE waste of time. It also cause unexpected crash when open React Debugger.

**Comment by HimiGame** [comment]
I use Xcode to recompile the running project to solve this problem

**Comment by hitsthings** [comment]
Possibly related: I've sometimes seen sort of a "recursive" component tree in the standalone React Devtools. Like the root component has a root component as its child (so there might actually be two full apps running?). Haven't found a repro though. I suspect related to Fast Refresh and toggling Debug on and off.

**Comment by JonnyBurger** [comment]
@Stale Please keep it open again!

**Comment by sbrighiu** [comment]
Anything new?

**Comment by davidvmckay** [comment]
Still happening in 0.63.4

**Comment by lukewlms** [comment]
In Simulator top menu: Device -> "Erase All Content and Settings..." seems to take care of this.

A bit of a nuclear option but in my case only took a minute or two.

([StackOverflow source](https://stackoverflow.com/a/39293961/152711))

**Comment by Thunermay** [comment]
Any fixed for newest version?

**Comment by aarshad786** [comment]
Exists in React 0.64.1 as well...

I have been seeing that proper refresh of bundle happens only when both reload are clicked in dev menu.. just one reload shows un-deallocated React components

**Comment by kfernandes29** [comment]
Still happening

**Comment by ilkkaylik** [comment]
Still happening in 0.65.2

**Comment by kg-currenxie** [comment]
Same here. 0.65.0

**Comment by jmhungdev** [comment]
still happening in 0.67.1

**Comment by joeljerushan** [comment]
`"react-native": "0.70.6",` still have this issue <br/>
![Simulator Screen Recording - iPhone X - 2023-01-06 at 17 10 02](https://user-images.githubusercontent.com/10111309/211005601-6cf5a37f-de82-46ea-8edd-86ed3e0f1fd0.gif)

**Comment by robsco** [comment]
I was glad this bug appeared for me as It meant I could go back to using Chrome to view my logs, on a different machine to Xcode.

Then it randomly went again.

Safe to say, this issue still persists, 0.70.6

Now, how can I get the menu to appear that allows me to "Debug JS Remotely" that was ideal.

**Comment by popejrh19** [comment]
Unsubscribe

William Pope Jr

**Comment by cortinico** [comment]
Closing as stale
