### ISSUE TITLE
../react-native-xcode.sh no such file or directory

### ISSUE THREAD

**Issue by sure1243jupiter** [facebook/react-native#21808]
I am using

## Environment

  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
      Memory: 36.65 MB / 4.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: 3.3.15 => 3.3.15 
      react: 16.3.0-alpha.1 => 16.3.0-alpha.1 
      react-native: ^0.57.3 => 0.57.3 
    npmGlobalPackages:
      react-native-cli: 2.0.1

[skip envinfo]

## Description

`/Users/xcodeclub/Library/Developer/Xcode/DerivedData/Lea*****y/Build/Intermediates.noindex/demo.build/Debug-iphonesimulator/demo.build/Script-00DD1BFF1BD5951E006B06BC.sh: line 3: ../node_modules/react-native/scripts/react-native-xcode.sh: No such file or directory`

I am getting this issue and not able to run in iOS but able to run in android
 I have also checked the build phases of my project in Xcode and there 

```
export NODE_BINARY=node
../node_modules/react-native/scripts/react-native-xcode.sh
```

actually the file exists in the given path but when I am building the project it is giving error no such file or directory

 I am not able to understand what the exact issue may be

**Comment by ferrannp** [comment]
Hello there 👋 this issue has been reported for an old version of React Native. Ideally we'd like everyone to be using 0.59 (see the [awesome changes](https://facebook.github.io/react-native/blog/2019/03/12/releasing-react-native-059) it brought) but we know updating can be a pain. We are going to close this issue because it's from a version before 0.57, which is really old.

But please, if it's actually still an issue with 0.59 please comment below and we can reopen it 😊

**Comment by jarednapier** [comment]
I am having this exact issue. I am using 0.59.9.

**Comment by quocbaovu15101996** [comment]
> I am having this exact issue. I am using 0.59.9.
> 
> EDIT: For anyone having this issue, for me it had to do with my project's file structure. I used 'react-native init' to create my project so I am not sure if that is different than using Expo, but I changed the path and it found the script. In my case I had to change:
> 
> ```
> export NODE_BINARY=node
> ../node_modules/react-native/scripts/react-native-xcode.sh
> ```
> 
> to
> 
> ```
> export NODE_BINARY=node
> ../../../node_modules/react-native/scripts/react-native-xcode.sh
> ```
> 
> Hope this helps.

not work for me. I'm using rn 0.59.8

**Comment by jarednapier** [comment]
Your project's file structure might be different. In my case, it was just pointing to the wrong place so I had to correct it. Also, if you haven't, switch to the Legacy Build system in your Xcode Project Settings.

**Comment by diivyu** [comment]
> I am having this exact issue. I am using 0.59.9.
> 
> EDIT: For anyone having this issue, for me it had to do with my project's file structure. I used 'react-native init' to create my project so I am not sure if that is different than using Expo, but I changed the path and it found the script. In my case I had to change:
> 
> ```
> export NODE_BINARY=node
> ../node_modules/react-native/scripts/react-native-xcode.sh
> ```
> 
> to
> 
> ```
> export NODE_BINARY=node
> ../../../node_modules/react-native/scripts/react-native-xcode.sh
> ```
> 
> Hope this helps.

Not worked for me. I'm using rn 0.59.1.

**Comment by jarednapier** [comment]
> Your project's file structure might be different. In my case, it was just pointing to the wrong place so I had to correct it. Also, if you haven't, switch to the Legacy Build system in your Xcode Project Settings.

**Comment by diivyu** [comment]
I just cross-checked that, it's not pointing to the wrong location and also the project is switched to Legacy Build System.
I  just cleaned the project. After cleaning, the x-code is showing the error but also it is letting the build to be successful.

**Comment by jarednapier** [comment]
Hmm, is the project that the error is occurring for your main project? When some RN packages install, Xcode will by default build the project from that specific package. For example, I used a sliding panel package that included all of the target files to build it so Xcode included that in the build process. I say this because if you say it is pointing to the right place you must be mistaken on your initial location. This leads me to think that this error is occurring for a target that isn't necessary.

**Comment by diivyu** [comment]
Yes the error is in the main project.
