### ISSUE TITLE
[Image] Getting intrinsic Image size in the onLoad event

### ISSUE THREAD

**Issue by dubert** [facebook/react-native#2180]
I really needed to get the actual image size from a network image, so I could use it in styling my app.

@paramaggarwal showed me how to do it in this issue https://github.com/facebook/react-native/issues/494 and suggested I submit a PR for it. 

I saw a comment somewhere by @vjeux that reworking Image was planned. Should I go ahead and do this? Or will it be unnecessary soon? Or am I a unique use-case?

**Comment by paramaggarwal** [comment]
I think the reworking of image is what the change from separate RCTNetworkImage and RCTStaticImage to a single RCTImageView was. I guess it should be fine, and I think it is good information to have available to JS.

**Comment by MossP** [comment]
+1 I have posted on [stackoverflow](http://stackoverflow.com/questions/31654244/react-native-retrieve-actual-image-sizes) about this  .. tumbleweed. I hadn't noticed https://github.com/facebook/react-native/issues/494, @paramaggarwal, so I may look into this now, too.

**Comment by MossP** [comment]
ps. you are not a unique use-case :)

**Comment by nicklockwood** [comment]
I can confirm we aren't working on changing or extending the current implementation of RCTImageView in the next few weeks, if you'd like to propose any new functionality or file any PRs.

**Comment by paramaggarwal** [comment]
That means you can go for it @dubert! Looking forward to the PR.

**Comment by dubert** [comment]
Working on it, just kind of stuck right here: https://github.com/facebook/react-native/issues/2234

**Comment by dubert** [comment]
Submitted a PR: https://github.com/facebook/react-native/pull/2364

**Comment by MossP** [comment]
Shame that this never made it in. Manual patching is now more complex as Master has changed so much..

**Comment by nicklockwood** [comment]
As I said in the PR feedback, we need to provide a way to preload images and get their dimensions, but doing it onscreen with `<Image>` like this is not really the right way :-/

**Comment by MossP** [comment]
I understand, thanks @nicklockwood. Thanks also to @dubert for the solutions provided.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/image-getting-intrinsic-image-size-in-the-onload-event

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by JeroenNelen** [comment]
Is this currently being looked at or in? Are there any, currently working, solutions?
This is very annoying as we don't want to stretch loaded images because then they would become pixelated and the sizes can vary so we cannot set a specific height either.
Hopefully someone has some suggestions?

Kind regards,
