### ISSUE TITLE
toLocaleString only works in remote debug on Android

### ISSUE THREAD

**Issue by Dagurmart** [facebook/react-native#21833]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Environment:
  OS: Windows 10
  Node: 8.11.3
  Yarn: 1.9.4
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4907809

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

## Description
This code
```
const vat = Number(0.02).toLocaleString(undefined,
      {
        style: 'percent',
        minimumFractionDigits: 2,
        maximumFractionDigits: 20
      })

```
gives you "2%" when debugging but 0.02 if you turn off remote debugging. This is not a problem on iOS.

**Comment by hey99xx** [comment]
> [x] Search for existing issues:

Did you really search existing issues, I highly doubt it? https://github.com/facebook/react-native/search?q=toLocaleString&type=Issues

This problem is already known, Android ships with an old version of JS engine that doesn't have improved `toLocaleString`. While debugging you use Chrome's JS engine instead of the app's so the bug doesn't show up there.

**Comment by radko93** [comment]
@hey99xx answered your question. You can look up and replace Android JS engine yourself if you want to.
