### ISSUE TITLE
keyboard hiding TextInput component

### ISSUE THREAD

**Issue by agentS** [facebook/react-native#2189]
I'm having the issue that the keyboard is hiding a `TextInput` component wrapped inside a `ScrollView` preventing the user from seeing the input. The first screenshot shows the `TextInput`when the keyboard is invisible.

![img_0011](https://cloud.githubusercontent.com/assets/5032736/9008935/d7f65f8e-379d-11e5-8c07-bc7814b67ae6.jpg)

The second one shows the input component covered by the keyboard.

![img_0012](https://cloud.githubusercontent.com/assets/5032736/9008941/e20f10c4-379d-11e5-86a0-da077fcbef72.jpg)

As a workaround I have added an invisible `View` at the bottom of the `ScrollView` delivering surprisingly satisfying results. Sorry for the German localization.

**Comment by brentvatne** [comment]
Hi there! This library might be useful to you: https://github.com/johanneslumpe/react-native-keyboardevents - in particular, check out the [How to move a view when the keyboard shows up](https://github.com/johanneslumpe/react-native-keyboardevents#how-to-move-a-view-when-the-keyboard-shows-up) section of the README.

Ping me if this doesn't work for you! Otherwise I'll close this issue :) Thanks for the detailed report!

**Comment by agentS** [comment]
Thanks a lot, that works :)
