### ISSUE TITLE
[NavigatorIOS] Multiple Taps Stacks Next View Redundantly

### ISSUE THREAD

**Issue by geirman** [facebook/react-native#2190]
## Actual Behavior: 
When I tap a NavigatorIOS item multiple times before the transition, the next view is added to the navigation stack multiple times as well. 

## Expected Behavior: 
I would expect that it would only be possible to add the next view to the navigation stack one time no matter how many times I'm able tap the nav item.

## Screencast of the Behavior
http://screencast.com/t/Hr4KmAF8AjIy

**Comment by browniefed** [comment]
@geirman your screencast link doesn't work anymore. Also NavigatorIOS is not being actively worked on by anyone and is designated Community responsibility. It is recommended that you use Navigator instead.

@brentvatne community issue.

**Comment by geirman** [comment]
@browniefed sorry it's taken me so long to refresh that link. I had a problem with that previous account and had to remove all data. In any case, here's a fresh, working screencast.

http://screencast.com/t/VPgg7y3kFjIb

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/navigatorios-multiple-taps-stacks-next-view-redundantly

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
