### ISSUE TITLE
Error Linking IOS Native Module in "Release" Mode

### ISSUE THREAD

**Issue by pranatha** [facebook/react-native#22036]
### React Native Environment Info:
System:
OS: macOS Mojave 10.14
CPU: x64 Intel(R) Core(TM) i5 @ 2.3GHz
Memory: 8.00 GB 2133MHz LPDDR3
Binaries:
Node: 8.9.4 - /usr/local/bin/node
Yarn: 1.5.1 - /usr/local/bin/yarn
npm: 5.6.0 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
 
SDKs:
iOS SDK:
Platforms: iOS
 
IDEs:
Xcode: 10.0 (10A255)  - /usr/bin/xcodebuild
npmPackages:
react: 16.6.0-alpha.8af6728
react-native: 0.57.4 => 0.57.4
npmGlobalPackages:
react-native-cli: 2.0.1

### Build System:
- Legacy Build System

### Description
- I have a native module called BluetoothModule
- Already followed the steps for linking library :
   https://facebook.github.io/react-native/docs/linking-libraries-ios
- Succeed compile in “Debug” scheme
- But failed compile in “Release” scheme with this error
   _ld: library not found for -lBluetoothModule
   clang: error: linker command failed with exit code 1 ( use -v to see invocation)_

Any idea what is going wrong?

**Comment by musicode** [comment]
+1, any updates about it?

**Comment by Titozzz** [comment]
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗
