### ISSUE TITLE
accessible = {false} not working in Android

### ISSUE THREAD

**Issue by bmbmjmdm** [facebook/react-native#22086]
## Environment
  OS: Windows 10
  Node: 8.11.3
  Yarn: Not Found
  npm: 6.4.1
  Watchman: 4.9.4
  Xcode: N/A
  Android Studio: Version  1.4.0.0 AI-141.2343393
Packages: (wanted => installed)
  react: 16.5.0 => 16.5.0
  react-native: ~0.57.2 => 0.57.2 

## Description
Setting the property "accessible" to {false} on a UI element doesn't appear to do anything. 

## Reproducible Demo
Create a parent text element and add 2 child text elements within it. Set the child text elements to accessible={true} and the parent to accessible={false}. Run on android with voice assistance. Notice the parent text element will receive focus and not the children, which is not expected behavior when the parent has accessible={false}

**Comment by bmbmjmdm** [comment]
I'm using a create-react-native-app project, which depends on Expo. Here:

https://docs.expo.io/versions/latest/sdk/#sdk-version

shows that Expo supports up to v0.55.4

**Comment by bmbmjmdm** [comment]
Ran a fresh react native project using v0.57.2, reproduced the problem

**Comment by bartolkaruza** [comment]
fresh project on 0.57.4?

**Comment by bmbmjmdm** [comment]
Just tried, same result

**Comment by bartolkaruza** [comment]
If I understand the `<Text />` component on Android correctly, it actually turns nested text into a single `TextView`. Because there is only one actual `TextView` from your three `Text` components, there is only one accessible element (the parent). Try wrapping the child `Text` components in a parent `View` component, which should translate into three actual views on the native side. Wrapping will work differently in that case though.

**Comment by palexs** [comment]
In my case using `importantForAccessibility={'no'}` helped opt-out a `Text` component from accessibility reach.

**Comment by TheSavior** [comment]
@bartolkaruza's comment seems like it explains the issue and that this is working as expected.
