### ISSUE TITLE
Android: Timers do not run if specified before App mounts

### ISSUE THREAD

**Issue by EdwardDrapkin** [facebook/react-native#22089]
- [X] Review the documentation: https://facebook.github.io/react-native
  - [X] Search for existing issues: https://github.com/facebook/react-native/issues
  - [X] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```

  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 40.69 MB / 16.00 GB
      Shell: 4.4.23 - /usr/local/bin/bash
    Binaries:
      Node: 10.12.0 - /var/folders/7r/_djt8b5s0tn_c2dmpdcwhjn40000gn/T/yarn--1541193013040-0.8521692356694159/node
      Yarn: 1.12.1 - /var/folders/7r/_djt8b5s0tn_c2dmpdcwhjn40000gn/T/yarn--1541193013040-0.8521692356694159/yarn
      npm: 6.4.1 - ~/.nvs/node/10.12.0/x64/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 25.0.3, 26.0.2, 26.0.3, 27.0.3, 28.0.1
        API Levels: 23, 24, 25, 26, 27, 28
    IDEs:
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.6.0 => 16.6.0
      react-native: ^0.57.3 => 0.57.4

```

## Description
If you call `setTimeout` or `setInterval` as the very first thing in the application, before any calls to react-native itself, they will never run.  They do in iOS.

## Reproducible Demo

Wrap your startup AppRegistry call in a setTimeout:

```
setTimeout(() => AppRegistry.registerComponent(appName, () => App), 100);
```

**Comment by bartolkaruza** [comment]
Just out of curiosity, what exactly is the use case for this? I thought the `registerComponent` call needed to be within the first event loop of the app, which is not the case if you wrap it in a setTimeout. I'm not sure if it is related to the issue, but there is a particular error thrown if the app is not registered before the [`runApplication`](https://github.com/facebook/react-native/blob/1151c096dab17e5d9a6ac05b61aacecd4305f3db/Libraries/ReactNative/AppRegistry.js#L178) is called. Can you check your `adb logcat` output for that error?

**Comment by EdwardDrapkin** [comment]
Nothing happens, like ever.  No log messages or errors, the function just never gets called.  It gets called immediately if you set the timeout to 0, however.  

We have to make a network request to determine which content pane to show users on app launch based on their remote session state... since NetInfo is [also broken before React Native launches on Android](https://github.com/facebook/react-native/issues/18130) I was trying to use setTimeout to handle slow network requests.  On iOS, we can use NetInfo before React-Native launches to immediately display a "network required" error message and exit the application; on Android, I was trying to find a way to avoid launching all of react-native if the network request was going to fail anyway.

I'm going to have to work around this by launching the application into a headless component of some sort that can use NetInfo and it is going to greatly increase the complexity of the app boot process.  

iOS boot looks something like: `(await NetInfo.isConnected.fetch()) ? showApp() : showWarning()` and Android boot is gonna have to do that all of that in an otherwise useless component's `componentDidMount()` unless there's a better way to ensure network connectivity before launching the app?

**Comment by bartolkaruza** [comment]
There are two considerations you might consider for moving this logic into an actual component instead of pre `registerComponent`, UX and semantics:
UX is the situation where NetInfo returns connected, but you are not able to actually reach your server. Think of the `walled garden` state of wifi hotspots or other network issues while the device thinks it is connected. In those cases you would want to display some loading indication while your app is loading (and the request to your server is timing out), followed by displaying the warning on the actual timeout.
The second, semantics, is that you are considering `registerComponent` as `startApp`, which is not what `registerComponent` means; it actually registers a particular React component to a specific namespace. Therefore it should be done as early as possible and the application logic should be moved until after this point.
This is just my opinion on how you can avoid this issue entirely, I'm not saying there might not be an actual inconsistency between Android and iOS. I think you might not want to worry about that, if you simply change the order of initialisation to a more stable post `registerComponent` approach.
