### ISSUE TITLE
onLayout not called until 2-3 seconds after view is rendered/visible

### ISSUE THREAD

**Issue by thomasarogers** [facebook/react-native#22085]
## Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
      Memory: 155.73 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.4 - ~/.nvm/versions/node/v8.11.4/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v8.11.4/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2
        API Levels: 23, 26, 27, 28
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728 
      react-native: ^0.57.1 => 0.57.1 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

## Description
I have a SectionList and am trying to implement scrollToLocation upon its display. My rows have variable height so in order to scroll to an accurate position I need to store the height of each row for use in the GetLayout method on the SectionList. For each row component I pass it a function to onLayout which passes the rows height from the event to the parent SectionList component to store and use in the GetLayout function and scrollToLocation call.

` handleCellDraw = (e) => {
 if(this.props.isSectionList) {
        this.props.addRowHeight(e, this.props.index)
      }
    }`

Upon receiving the row height the method below calculates the average row height as an estimation and stores it in state. However all the calls from onLayout are not coming through until 2-3 seconds after the SectionList is visible on the screen so GetLayout cannot get an average row height which results in scrollToLocation not functioning

`calculateAverageRowHeight = (e, index) => {
        let rowHeights = Array.from(this.state.rowHeights)
        rowHeights[index] = e.nativeEvent.layout.height
        let total = 0
        rowHeights.forEach((row) => {
            total += row
        }) 
        this.setState({rowHeights: rowHeights, averageRowHeight: total/rowHeights.length})
    }`

Spent some more time testing and the event onLayout returns seems to be very inconsistent often not having height / width values just undefined?

**Comment by bartolkaruza** [comment]
How dynamic are your views in height? Do you have any way to calculate the height based on the data before rendering? If you do, that is usually the way to go with `Section/FlatList` as any variable height will cause unstable scrolling and other issues. You need to provide an exact calculation to [`getItemLayout`](https://facebook.github.io/react-native/docs/flatlist#getitemlayout) for a stable experience.

Typically you can make minor adjustments to the design to make a fixed height for rows work or fixed height for several types of rows, that can be pre-calculated before rendering.

**Comment by thomasarogers** [comment]
Unfortunately the row height is fairly variable between 100 - 250 pixels roughly as the content can differ quite drastically. The issue isn't with the calculation it is that onLayout is not being called so getLayout cannot get a list of the row heights and do any accurate calculation. Ive tried initiating animations / logging once onLayout is called but all calls to it happen 2-3 seconds after the components mounted / displayed.

**Comment by bartolkaruza** [comment]
So I don't think this will work for a SectionList, as a dynamic height based on post layout calculations has never lead to a stable list for me before. It sounds like onLayout is actually called always, but late? You could consider hiding the list until after this point and only showing it when the onLayout has come through for all items. Some items further down the list will be rendered only after you scroll to them and their onLayout therefore will only be called after this render, because the SectionList is a VirtualizedList. So that will break your item height calculations when scrolling. If your list is not long, you could consider simply putting the views inside a ScrollView, which would avoid all of these height issues but potentially cause some performance drop for long lists.

**Comment by bristoljon** [comment]
@thomasarogers isn't that what `scrollToLocation` is for? i.e. scrolling to an item index so that you don't need to know rendered heights?

https://facebook.github.io/react-native/docs/sectionlist#scrolltolocation

**Comment by dulmandakh** [comment]
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗
