### ISSUE TITLE
[Discussion][CI] Migrate to Azure DevOps(formerly vsts)

### ISSUE THREAD

**Issue by gengjiawen** [facebook/react-native#22148]
MS annoucement: https://azure.microsoft.com/en-us/blog/introducing-azure-devops/.
## Pros: 
* Free for opensource and unlimited time, circleci masOS plan has fee and also has limit time.
* Support linux, macOS, windows, we can have a unify ci for mainstream os.
## Cons:
* Bug, currently you even can't see the build log.
* Circle ci can ssh to remote machine, which is very convenient.

**Comment by axe-fb** [comment]
I pinged folks at Microsoft to see how we can proceed on this.

**Comment by willsmythe** [comment]
(moving the questions/conversations here)

@gengjiawen - can you provide more details on what you are (well, aren't) seeing? Are you able to access the build results view in Azure Pipelines? If so, what log are you expecting to see something in, but aren't?

If the Azure Pipelines project is public, can you send a link to your build?

**Comment by gengjiawen** [comment]
@willsmythe see https://github.com/MicrosoftDocs/pipelines-xcode/issues/1

**Comment by willsmythe** [comment]
@gengjiawen - not sure if you saw my comment or not. Here is a staged version of the pipeline referenced by the issue above: https://dev.azure.com/willsmythe/pipelines-xcode/_build/results?buildId=106&view=logs

Have you already created a pipeline for react-native? If not, I can stage one and we can go from there.

**Comment by gengjiawen** [comment]
@willsmythe I see that. But I may need more time to look into this for now I am concentrating on new jsc.

**Comment by willsmythe** [comment]
@gengjiawen - no worries. 

To get the ball rolling, I created an initial azure-pipelines.yml that builds on Windows (essentially replacing AppVeyor). I will start stubbing in steps for Linux and macOS as well. Here are the relevant files:

* [azure-pipelines.yml](https://github.com/willsmythe/react-native/blob/master/.azure-pipelines/azure-pipelines.yml): defines the jobs to run, references other files which contain the detailed steps
* [azure-pipelines-windows.yml](https://github.com/willsmythe/react-native/blob/master/.azure-pipelines/azure-pipelines-windows.yml): build steps for Windows

I had to tweak one test (`ios::writePlist should write a `.plist` file`) due to differences in line endings, but I would probably fix this a little differently (i.e. add a .gitattributes entry for `__fixtures__/Info.plist` that ensures LF line endings are preserved when the file is checked out on Windows). This would avoid the change in `writePlist`. The other option is to skip the test on Windows (`xit`). 

Build results are here:
https://willsmythe.visualstudio.com/react-native/_build?definitionId=26&_a=summary

[![image](https://user-images.githubusercontent.com/2503052/48776654-74996d00-ec9e-11e8-956e-1548ac7fdf0e.png)](https://willsmythe.visualstudio.com/react-native/_build/results?buildId=130&view=logs)

And the test results:
![image](https://user-images.githubusercontent.com/2503052/48776728-9561c280-ec9e-11e8-80e1-e7f09413eee7.png)

I added a `test-ci-win` NPM run script (since you can't set variables at the start of the script on Windows), but I would likely just create a CI jest config file that could be referenced instead (it would set the reporter, test results file path, etc).

**Comment by gengjiawen** [comment]
excellent work.

**Comment by gengjiawen** [comment]
@willsmythe How about we try docker build on linux. I did somework on https://github.com/facebook/react-native/pull/21477. I don't know vsts has docker layer caching or something.

**Comment by gengjiawen** [comment]
Also do vsts has ssh function on linux build, I think it's super important for test.

**Comment by gengjiawen** [comment]
@willsmythe I run into some 401 error when setting up my account. Can you help on this ?

**Comment by willsmythe** [comment]
@gengjiawen  - sure --- feel free to send me an email (wismythe at microsoft.com) with the name of your Azure DevOps org and the account you tried to sign in with.

I had hoped to play with the Linux/Docker build last week, but got sidetracked on another project. My goal is to have something running this week ...

**Comment by gengjiawen** [comment]
I googled and make it work. Thanks.

**Comment by gengjiawen** [comment]
I have tried azcure pipeline in this project, https://github.com/react-native-community/ci-sample.

**Comment by cpojer** [comment]
Given that this issue is a proposal to change all of our CI to a new system, I think this should go into the [discussions and proposals](https://github.com/react-native-community/discussions-and-proposals) repository with a clear explanation of the work to be done and the benefits and trade-offs it will bring.
