### ISSUE TITLE
React-native link only links to 1st Xcode target

### ISSUE THREAD

**Issue by dev6james** [facebook/react-native#22162]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
      Memory: 53.57 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.1 - ~/.nvm/versions/node/v8.9.1/bin/node
      Yarn: 1.3.2 - ~/.nvm/versions/node/v8.9.1/bin/yarn
      npm: 5.5.1 - ~/.nvm/versions/node/v8.9.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 19.1.0, 20.0.0, 21.1.2, 22.0.1, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.0, 28.0.1
        API Levels: 22, 23, 24, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.4.14 => 16.4.18
      @types/react-native: ^0.57.6 => 0.57.6
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728
      react-native: 0.57.3 => 0.57.3
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native: 0.50.3

## Description
If you have multiple targets in Xcode, and try to link a new dependency with react-native link, it will only link for the first Xcode target.

This is a problem for us as I can already see the bugs being opened where one of the builds we distribute has bugs because of an unlinked dependency in the target. 

The desired behaviour would be either one (or both) of the following:
- `react-native link` will link all targets by default
- allow a `--target=""` flag for react-native link, so that each target can be linked via the cli

## Reproducible Demo
1. Create an ejected RN project
2. Add a second target in Xcode
3. Install a new project dependency and then run `react-native link` to link that dependency
4. Look at the Linked Frameworks & Libraries in Xcode under both targets. The new library will only be listed under your first target.

Note, this was opened in the past and has been auto-closed several times.
https://github.com/facebook/react-native/issues/18503
https://github.com/facebook/react-native/issues/17381

**Comment by bartolkaruza** [comment]
I was just wondering what the expectation is with opening the issue for the third time? React Native Xcode projects with multiple targets are a more advanced setup. I've personally become accustomed to react-native link only working in the most simple setups, where more advanced setups require manual linking and at the very least a manual check of what the result was of running `react-native link`. I understand the convenience factor, but I doubt it will be something someone else will solve for you.

Why not have a look at CLI source code and consider adding it yourself through a PR? [This](https://github.com/facebook/react-native/blob/0a39cda39a83313fa1628759b2735d58ffcc02ec/local-cli/link/ios/addSharedLibraries.js#L20) might be a good starting point.

**Comment by radex** [comment]
agreed, this is IMHO not worth changing — if you want to have an expert Xcode setup, use Xcode

**Comment by dev6james** [comment]
Is having more than 1 target really an "expert Xcode setup". Are we saying that React Native should only provide abstractions for the most simple projects and anything more than that means go native and lose a ton of convenience? What is the downside to having a more powerful cli?

@bartolkaruza I would like to contribute although I was hoping that if was not too arduous a change that it'd be a lot faster and easier for an existing contributor. If it's came up several times then there is demand out there and my goal was to reinforce that demand.  I may look into it if needs must though.

**Comment by radex** [comment]
> Is having more than 1 target really an "expert Xcode setup".

Yes! Not in the sense that it's hard, but that it's a very Xcode-specific thing. If you're adding custom targets, you're already familiar with Xcode basics

> anything more than that means go native and lose a ton of convenience? 

I disagree with the premise. Knowing Xcode and Android Studio (&gradle...) basics is necessary (and not hard) if you're going to do something non-standard, like having custom Xcode targets.

**Comment by bartolkaruza** [comment]
I would just like to add a way to deal with library dependencies in Xcode that I use for every project that has more than 1 target.

Instead of duplicating the dependencies to each target, I create a single Cocoa Touch Library target (named base), to which I add all dependencies. Then that base target is added as a dependency to all other targets. It is a more DRY approach to dependencies in Xcode and works well with react-native link if you make sure the base target is the first one in the list.

Add this:
![screen shot 2018-11-07 at 10 43 41](https://user-images.githubusercontent.com/1605731/48178510-8f89ea00-e34c-11e8-9a32-804f1c7a635d.png)

Make sure it's at the top: 
![screen shot 2018-11-07 at 10 44 19](https://user-images.githubusercontent.com/1605731/48178516-9b75ac00-e34c-11e8-97f2-47bbf3c11244.png)

This target has your deps:
![screen shot 2018-11-07 at 10 49 33](https://user-images.githubusercontent.com/1605731/48178527-b34d3000-e34c-11e8-8254-6f467bfd1ef2.png)

Your targets just have this list of deps:
![screen shot 2018-11-07 at 10 44 29](https://user-images.githubusercontent.com/1605731/48178532-b8aa7a80-e34c-11e8-9c42-f88cf416a2a5.png)

Hope the base library approach helps you find that convenience back :)

This approach would not work if we change the behaviour of `react-native link` to add it to each target. So I think it may be hard to foresee the impact of your proposed change on all the various Xcode project setups out there. People do things in different ways and assuming each target *should* have each dependency linked is dangerous.

**Comment by bartolkaruza** [comment]
Moved to https://github.com/react-native-community/react-native-cli/issues/41

@kelset close
