### ISSUE TITLE
VirtualizedList + getItemLayout only renders initialNumToRender items

### ISSUE THREAD

**Issue by rodalmeida** [facebook/react-native#22194]
- [ ] Review the documentation: https://facebook.github.io/react-native
  - [ ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
 System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 67.67 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 9.2.0 - ~/.nvm/versions/node/v9.2.0/bin/node
      npm: 5.5.1 - ~/.nvm/versions/node/v9.2.0/bin/npm
      Watchman: 4.6.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        Build Tools: 23.0.1, 25.0.0, 25.0.2, 26.0.1, 26.0.2, 27.0.3, 28.0.3
        API Levels: 23, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
```

## Description
I understand this issue was already opened before (#15734) but nothing was done to solve it and it seems major as you can only use some FlatList and SectionList features if you specify `getItemLayout`

As already described before, the issue happens on the line 1708 of `VirtualizedList`, this code,
```
const onLayout =
      /* $FlowFixMe(>=0.68.0 site=react_native_fb) This comment suppresses an
       * error found when Flow v0.68 was deployed. To see the error delete this
       * comment and run Flow. */
      getItemLayout && !parentProps.debug && !fillRateHelper.enabled()
        ? undefined
        : this.props.onLayout;
```
doesn't even make sense.

## Reproducible Demo
You can see more info about this here #15734

**Comment by bartolkaruza** [comment]
Could you post an actual reproducible demo/snack for this? Both the linked issue and this issue do not provide this. I'd like to have a look, but I'm not sure what exact case is causing the issue. I know the base FlatList/SectionList works, even with a getItemLayout (which is really recommended for avoiding scrolling glitches and raw performance!). I have seen many Flatlist implementations containing subtle implementation side bugs, that cause various issues, so if you could point me to a repro, we can rule this out.

I personally think the Flatlist getItemLayout is a bit complicated to implement, because of the offset measure being absolute from the top;
```
getItemLayout={(data, index) => (
    {length: ITEM_HEIGHT, offset: ITEM_HEIGHT * index, index}
  )}
```
If you get this calculation wrong by a single pixel, it causes various artefacts in the list scrolling and rendering behaviour. I suspect that 99% of the issues everyone is experiencing with Flatlist are related to this.

About the onLayout not being called, why does this not make sense for you? You already have this information *ahead* of rendering if you are actually able to implement `getItemLayout`. What would you use `onLayout` for if you already know where each element is?

(PS the issue template is there for a reason)

**Comment by nar213** [comment]
This issue is still present in React-Native 0.58.4 and needs to be addressed. Work arounds of providing `initialNumToRender={data.length}` or removing `getItemLayout` have serious performance implications for large FlatLists.

**Comment by coolguy001tv** [comment]
@nar213 Hi, I am facing the same issue using SectionList with rn 0.58.1. 
The replacing  did solve the issue but it's not the final solution.
So why it should be undefined here?
https://github.com/facebook/react-native/blob/19492b730b6779486f83d5ddbaeeb870cb3d5e9c/Libraries/Lists/VirtualizedList.js#L1721-L1723

**Comment by nar213** [comment]
@coolguy001tv 

I didn't find a solution that I was convinced enough by to open a PR. I think it should be undefined when you provide getItemLayout as onLayout is invoked on layout changes and on mount, it provides a native event with layout information, this should be redundant if you've provided the layout information in the function getItemLayout. 

When I had the issue there was always a tail-spacer being generated at the end of the list of items, but it would never disappear irrespective of scroll position. I could not always reproduce this behaviour, however it seemed that if I opened the flatlist whilst heavy operations or animations were occurring the bug was more likely to occur. Additionally the tail-spacer would disappear and show the remaining items when I had hot reload enabled and I made a change to the flatlist file.

https://github.com/facebook/react-native/blob/19492b730b6779486f83d5ddbaeeb870cb3d5e9c/Libraries/Lists/VirtualizedList.js#L861-L877

**Comment by coolguy001tv** [comment]
@nar213 Sorry for the late reply.
My situation is like yours mostly. As I can always see a tail-spacer too. The difference is that tail-spacer would not disappear even if I hot reload.
But accidentally we bypass this bug.
In my situation, I use react-navigation.  I have 2 pages: Page A and Page B. Page A has an infinite loop animation, and Page B is my SectionList page.
When navigating from Page A to Page B, the bug happens in Page B. But if I remove Page A's animation, the bug in Page B disappears.

**Comment by nar213** [comment]
@coolguy001tv 

I also use react-navigation and I think it's entirely possible that the reason my tail spacer issue happens is because a LayoutAnimation tries to fire in the previous page. I think it sounds like we can create a reproducible demo to show this issue, however I have a feeling this could be an issue for react-navigation team not react-native team, as probably makes sense not to get rid of tail spacer whilst animations are firing.

**Comment by coolguy001tv** [comment]
@nar213 The bug seems to be related to react-navigation. And I created one example [here with expo](https://snack.expo.io/@coolguy/section-list-test) to show this bug.
If I comment the line 57 in PageA.js (`// this.animateCollect();`), the SectionList in PageB shows OK; but if I uncomment the line 57 in PageA.js, the bug happens.
If you want to test this in your phone, after commenting line 57, please quit the app and reenter, the hot reload seems to be wrong after commenting.

**Comment by coolguy001tv** [comment]
I put a new issues in react-navigation [here](https://github.com/react-navigation/react-navigation/issues/5652)

**Comment by dbarth** [comment]
Been debugging a similar issue with RN 0.55.3. In my case, some items in the FlatList had a shimmer animation running with Animated.loop. Reverting to a plain Animated.timing resolved the problem.
Referring to the issue opened in the previous comment, setting isInteraction:false seems necessary on all elements of the animation (A.delay() doesn't support that unfortunately).

**Comment by idris** [comment]
@rodalmeida can you please add env info or add `[skip envinfo]` so this issue can be re-opened?
https://github.com/facebook/react-native/issues/22194#issuecomment-436588080

**Comment by yurnery** [comment]
I have the same problem, and I found the solutions for hours, these ways can fix this issue: 
1. remove the `getItemLayout` method
   - this way can render all Items, but in my case, I need the `flatList.scrollToIndex` method, so it is not work for me
2. specific `initialNumToRender={data.length}`: 
   - this way can work but it is a bad idea, if the data is large enough then  the performance is a question.
3. finally, I found the cause of this issue in my case, the situation is like this, when ScreenA call an Animated API, and push to ScreenB without the Animation stop, and ScreenB has a flatList like above, the bug is appear, to fix this, you just config the `isInteraction: false` in your Animated API, like this 
```
 Animated.timing(this.state.animatedValue, {
      toValue:value,
      duration:duration,
      isInteraction: false
    }).start();
```
