### ISSUE TITLE
[DatePickerIOS] Invalid prop types for DatePickerIOS

### ISSUE THREAD

**Issue by admmasters** [facebook/react-native#2222]
There seems to be a regression here. RCTDatePickerIOS internally wants us to pass prop types of type Date but for some reason the getTime() method is being called on the props passed to DatePickerIOS. I'm wondering if there is some part refactoring going on here, but at present it is broken for the datetime mode.

**Comment by nicklockwood** [comment]
We can't send JavaScript Date objects across the bridge, which uses JSON as the transport medium, so we convert the date to a timestamp (milliseconds since 1/1/1970) and then convert that back to a date on the native side.

It looks like the logic is correct. Can you dig a bit deeper and try to work out why the datetime value isn't what you expect? Maybe it's a timezone issue?

**Comment by admmasters** [comment]
Its odd because I'm getting that warning on the sample code and in the app I'm currently working on and it never used to throw this error on earlier versions ( I'm ultra OCD about console log warnings/errors ) - I'll dig a bit deeper and come back to you. FWIW I was not touching timezones explicitly before just sending the prop for date as 'new Date()'.

**Comment by brentvatne** [comment]
Can you post an example app @admmasters?

**Comment by admmasters** [comment]
Yep - sorry, been so busy (got some deadlines!). When I get a chance I will do this...

**Comment by admmasters** [comment]
Hmmm seems to be working now - but still getting some invalid props messages in the console.
