### ISSUE TITLE
HeadlessJs doesnt start javascript task if the app is closed

### ISSUE THREAD

**Issue by gvetsa** [facebook/react-native#22238]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
      Memory: 7.63 GB / 15.89 GB
    Binaries:
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.1.0.0 AI-173.4907809

## Description
Describe your issue in detail. Include screenshots if needed. If this is a regression, let us know.
**I am starting HeadlessJs task using broadcast receiver and listening for sms messages, which works fine completely when the app is in foreground or in background but if the app is closed then HeadlessJs task doesnt fire or trigger.**

## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, share a project, or     share an app that reproduces the issue using https://snack.expo.io/. Please follow the guidelines for providing a MCVE: https://stackoverflow.com/help/mcve

**Comment by dulmandakh** [comment]
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗
