### ISSUE TITLE
Packager fails because crawler throws error

### ISSUE THREAD

**Issue by mosch** [facebook/react-native#2231]
I upgraded from react-native 0.6 to 0.8 - everything went well first.
Now out of nowhere the packager fails when i run it:

    [11:02:32 AM] <START> fs crawl
    TypeError: Cannot read property 'root' of null`
    …

[packager/react-packager/src/DependencyResolver/crawlers/index.js#L16](https://github.com/facebook/react-native/blob/v0.8.0/packager/react-packager/src/DependencyResolver/crawlers/index.js#L16)

I played around with the command line parameters of the packager, but this doesn't seem to help.

Any thought where to start tracking this issue down?

**Comment by mosch** [comment]
@amasad can you help on this?

**Comment by eldh** [comment]
I got around this by re-installing watchman.

**Comment by jhabdas** [comment]
Thanks @eldh. This issue was tripping me up for a few days. I had tried reinstalling watchman to resolve this but your experience had me be sure to update brew before I reinstalled, as without update brew was trying to install watchman `3.2.0` (which throws the error on my system) versus `3.7.0` which works just fine now.

`brew uninstall watchman && brew update && brew install watchman`

**Comment by amasad** [comment]
I think your watchman version must be old. But I was hoping this would be a backwards compatible change. I'll find a fix for this. Thanks.

**Comment by pfeilbr** [comment]
re-installing watchman fixed the issue for me also

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/packager-fails-because-crawler-throws-error

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
