### ISSUE TITLE
 Keyboard appears and disappears

### ISSUE THREAD

**Issue by amitsin6h** [facebook/react-native#22408]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
React Native Environment Info:
    System:
      OS: Linux 4.15 elementary OS 5.0 Juno
      CPU: (4) x64 Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
      Memory: 1.66 GB / 7.69 GB
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 8.13.0 - /usr/bin/node
      Yarn: 1.12.3 - /usr/bin/yarn
      npm: 6.4.1 - /usr/bin/npm
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
    npmPackages:
      react: 16.6.1 => 16.6.1 
      react-native: 0.57.5 => 0.57.5 

## Reproducible Demo
`<Router>`
        `<Stack key="root">`
          `<Scene key="login" component={LoginScreen} title="Login" />`
          `<Scene  key="signup" component={SignupSreen} title="Account Setup" />`
        `</Stack>`
`</Router>`

## Description
I have two screen `login` and `signup` when user visit any of the screen. Keyboard disappears
automatically when tapped in input filed. I have tried with ScrollView, View and also tried to use keyboardshouldpersisttaps but no luck.

**Comment by FibreFoX** [comment]
Can you give a little bit more details, how the scenes are made? Probably it's not an RN problem, but a fluke inside your component.

**Comment by dulmandakh** [comment]
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗

**Comment by haolipang** [comment]
Hi there, I'm facing the same issue now. Did you manage to find the solution?
