### ISSUE TITLE
[Text] Emoji does not respect color: 'transparent'

### ISSUE THREAD

**Issue by bobspace** [facebook/react-native#2241]
In a `<Text>` component with a style of `color: 'transparent'`, the emoji is not hidden. Adding `opacity: 0` hides the emoji, but impacts performance.

**Comment by ide** [comment]
Looks like alpha should be honored: https://jsfiddle.net/tyo2mn4k/1/

cc @a2, @nicklockwood

**Comment by nicklockwood** [comment]
Only in Chrome. In Safari the Emoji is rendered with full opacity.

**Comment by nicklockwood** [comment]
It seems to me there are two issues here:

1) Emoji don't respect the alpha component of the text color. AFAICT this is an intentional design decision on Apple's part, and the behavior is not consistent between browsers, so it's not clear to me what the right course of action is. To implement this we would probably have to change the implementation of RCTText so that we render into a buffer image with full alpha, and then draw that buffer back into the view with a uniform alpha applied. That would probably be quite expensive, and would get very complex when dealing with rich text that has multiple colors applied.

2) It looks like we don't expose the `hidden` property of UIView directly, and so the only way to hide a view is to set its opacity to zero. I assumed that this would have the same performance as setting `hidden=YES`, but if it doesn't then we should probably add some logic to hide views when they are fully transparent (this isn't as straightforward as it sounds though, due to layout animations).

**Comment by ide** [comment]
That's a good point about Safari. Firefox ignores the opacity too, except when it's completely transparent in which case it simulates hidden=YES. So there's basically no consistency or precedent.

I don't understand why opacity = 0 (compositing nothing) would be more expensive than transparent text (compositing an opaque background) -- @bobspace can you elaborate?

**Comment by ide** [comment]
> To implement this we would probably have to change the implementation of RCTText so that we render into a buffer image with full alpha, and then draw that buffer back into the view with a uniform alpha applied.

I agree the complexity is probably not warranted especially since `opacity` is supported anyway.

**Comment by satya164** [comment]
Closing this as this can easily be acheived with opacity.
