### ISSUE TITLE
Expo update causes debugging endpoint without debugging being turned on.

### ISSUE THREAD

**Issue by bugs181** [facebook/react-native#22441]
- [√] Review the documentation: https://facebook.github.io/react-native
  - [√] Search for existing issues: https://github.com/facebook/react-native/issues
  - [√] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Run `react-native info` in your terminal and paste its contents here.
    `bash: react-native: command not found`

## Description
The latest update in Expo causes my API endpoint to receive what looks like the debugging/inspection endpoint. The local API server I'm using runs on port 8082.

    [GET] /inspector/device?name=Levi's%20iPhone&app=host.exp.Exponent

I do not have debugging or inspect turned on in the Expo App. Is there a way to disable this?

`app.json`

     "sdkVersion": "31.0.0",
     
`package.json`

       "dependencies": {
              "expo": "^31.0.0",
              "react": "16.5.0",
              "react-native": "https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz",
       }

## Reproducible Demo
Any new Expo project from `expo init` causes this to happen.

**Comment by bartolkaruza** [comment]
Hi @bugs181, can you post this issue on [expo](http://github.com/expo/expo) please? Expo builds on top of React Native and uses quite a bit of custom setup. 

If you have this issue with a `react-native init` project, instead of `expo init`, this might be an issue relating to both environments. You can install the `react-native` cli command using `yarn global add react-native-cli` or `npm install -g react-native-cli`.

**Comment by bugs181** [comment]
Closing issue and moving to Expo issue tracker.
