### ISSUE TITLE
[TextInput] TextInput focus issue in ScrollView in 0.9.0-rc

### ISSUE THREAD

**Issue by mrspeaker** [facebook/react-native#2247]
A TextInput inside a ScrollView is broken in 0.9.0-rc (worked in 0.8.0). When you give it focus then click in it again, it loses focus instantly - and the iOS "paste" bubble shows and hides quickly. This is especially a problem if you have code that runs onBlur.

    <ScrollView>
        <TextInput
          style={{ height: 30, borderWidth: 1, borderColor: "#ddd" }}
        />
    </ScrollView>;

If you change ScrollView to a plain View, then it works correctly.

**Comment by mrspeaker** [comment]
It seems like the bug was introduced in this commit: https://github.com/facebook/react-native/commit/e01f90784f961ad88a4cde114089bc5839207d29 (it was not present in 9e4af68d91b3c5a321627bd393e4a3991bf94db1)

**Comment by ldesplat** [comment]
I am seeing the same change in behavior. I have verified it works in 0.8.0 and fails in 0.9.0-rc. Though, I am not sure if it is a bug fix or if it is an introduced bug.
Setting `keyboardShouldPersistTaps={true}` (in iOS) on the scrollView allows you to go around the problem. You will now have to take care of dismissing the keyboard in some situations...

**Comment by brentvatne** [comment]
Thanks for the report @mrspeaker - I've noticed this one as well. cc @sahrens

**Comment by xinthink** [comment]
With RN 0.13.0, I found two issues related to TextInput inside a ScrollView

- Android, I have to click twice to get the TextInput focused
- iOS, if the "input1" get focused first, and then click the "input2", `isFocused` will be `false`

```jsx
      <ScrollView>
        <TextInput
          ref="input1"
          style={{width: 78, height: 38}}
          placeholder="text one"
        />
        <TextInput
          ref="input2"
          style={{width: 78, height: 38}}
          placeholder="text two"
          onFocus={()=>console.log('input2 focused: ' + this.refs.input2.isFocused())}
        />
      </ScrollView>
```

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/textinput-textinput-focus-issue-in-scrollview-in-090-rc

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by eeeman1** [comment]
the problem remains, version react-native 0.52
