### ISSUE TITLE
Parsing Realm object in FlatList its to slow 

### ISSUE THREAD

**Issue by benhartouz** [facebook/react-native#22559]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
React Native Environment Info:
    System:
      OS: macOS 10.14.1
      CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
      Memory: 334.15 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.4 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.0, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.1, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.3.1 => 16.3.1 
      react-native: 0.57 => 0.57.7 
    npmGlobalPackages:
      react-native-rename: 2.2.2

## Description
I'm using Realmjs as a database for my react-native application but when I try to rendring a Realm objects in my FlatList view its take a lot of time and its to slow.
https://realm.io/docs/javascript/latest/#react-native-listview

**Comment by bartolkaruza** [comment]
This issue is missing a minimal reproduction. Can you add a link to a Github repo which can be used to show the issue? Ideally, a maintainer should be able to reproduce in these minimal steps:
1. clone
2. yarn
3. react-native run-ios

There is nothing actionable for maintainers in the issue as you describe it right now. This issue needs a git repo example as opposed to an expo snack because of the native dependency.

Also, slow compared to what? First render, scrolling? Is the scrolling smooth, but the data doesn't show if you scroll far down or is the scrolling stuttering? There are many possible interpretations to 'it is slow'.

If you provide this information, someone can have a look and help resolve the issue.

**Comment by benhartouz** [comment]
@bartolkaruza thank you for your response, 
The main problem is when FlatList rendering Realm data.
`<FlatList
                data={this.state.data}
                extraData={this.state.data}
                keyExtractor={this._keyExtractor}
                renderItem={this._renderItem}
                ItemSeparatorComponent={this._itemSeparatorComponent}
                onEndReached={() => {
                  setTimeout(() => {
                    this.setState(
                      {
                        pagination: this.state.pagination + 1
                      },
                      () => {
                        if (this.props.settings.connection) {
                          this._search();
                        } else {
                          this._paginationRealm();
                        }
                      }
                    );
                  }, 400);
                }}
                initialNumToRender={8}
                maxToRenderPerBatch={2}
                onEndReachedThreshold={0.5}
              />`

**Comment by bartolkaruza** [comment]
That is still not enough to reproduce, unfortunately.
