### ISSUE TITLE
Old Keyboard (iOS7?) still in use

### ISSUE THREAD

**Issue by jacob-israel-turner** [facebook/react-native#2259]
On the left, the current keyboard (in the messages app) on an iPhone 6, iOS 8. On the right, the same phone and iOS version, but in a React Native app.

![Old Keyboard](http://i.imgur.com/Cexu9pi.jpg)

It took a designer to point this one out.  We're under the impression that the keyboard in use by React Native is outdated.  [This](https://rnplay.org/apps/Imr3ZA/edit) playground app shows the same old keyboard.

**Comment by jeanregisser** [comment]
Seeing your screenshot, it looks like your app is running in compatibility mode on an iPhone 6.
i.e. iOS doesn't see your app as supporting the native resolution on iPhone 6/6 Plus.

That's probably because you don't have a LaunchImage for iPhone 6/6 Plus.
If your app runs on iOS 7, LaunchScreen.xib is not supported there (it was introduced in iOS 8) and you must have the LaunchImage-667h@2x.png and LaunchImage-736h@3x.png in your app bundle. 
You can specify them using the asset catalog.

**Comment by jacob-israel-turner** [comment]
Thanks @jeanregisser, I just saw [this SO](http://stackoverflow.com/questions/25754942/how-to-enable-native-resolution-for-apps-on-iphone-6-and-6-plus) post explaining it.  Issue soon to be resolved!
