### ISSUE TITLE
Promises act odd when debugging in chrome

### ISSUE THREAD

**Issue by RWOverdijk** [facebook/react-native#2286]
When enabling Debug in chrome (simulator), using promises acts up for me.

```javascript
var foo = {
  bar () {
    this.getLocation().then((loc) => {
      console.log(loc);
    });
  },

  getLocation () {
    var p = new Promise((resolve, reject) => {
      navigator.geolocation.getCurrentPosition(position => {
        console.log('going to resolve');
        resolve(position);
      }, error => {
        console.log('going to reject');
        reject(error);
      }, {
        enableHighAccuracy: false,
        timeout           : 20000,
        maximumAge        : 15000
      });
    });

    p.then(position => {
      console.log('called in here');
      return position;
    });

    return p;
  },
};

foo.bar();
```

Sometimes (when it has to look up the position because timeout has expired) I’m getting "going to resolve” logged but nothing else. No “called in here” and no `loc` in the method I’m calling this from.

**Comment by brentvatne** [comment]
This actually looks like a dup of #2603 but with more information :) So let's keep this one open.

**Comment by mattdenner** [comment]
We've been seeing this issue recently too and (a very preliminary) investigation seems to suggest that it is to do with core-js attempting to detect the behaviour of `Promise`.  Specifically our use of babel pulls in this code and triggers the check on [this line](https://github.com/zloirock/core-js/blob/master/library/modules/es6.promise.js#L43) in core-js, setting `works` to false.

In our case changing our webpack use of babel to not have `optional: ["runtime"]` and the app ran without need us to click on the simulator.  Our app then breaks later which we need to look at!

I don't know if that's any help and, as I said, it's a very preliminary investigation.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/promises-act-odd-when-debugging-in-chrome

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is heavily focused working on performance.
