### ISSUE TITLE
[PushNotificationIOS] Unable to request permission

### ISSUE THREAD

**Issue by NishanthShankar** [facebook/react-native#2290]
I get the error `registerForRemoteNotificationTypes: is not supported in iOS 8.0 and later.`

I am able to request permissions if i change 

#if __IPHONE_OS_VERSION_MIN_REQUIRED >= __IPHONE_8_0 
to
#if __IPHONE_OS_VERSION_MIN_REQUIRED < __IPHONE_8_0

Line no: 141 in 8.0
Line no 155 in current master

**Comment by justinmakaila** [comment]
I'm having issues with this as well, only my issue is due to `RCTPushNotificationManager` on L:16 of `PushNotificationIOS.js` being undefined. I logged out the contents of `react-native.NativeModules` and I don't see `PushNotificationManager` in there.

**Comment by potsypantsy** [comment]
@NishanthShankar I tried making a pr for this earlier today. However, I am unable to get the tests to pass :( https://github.com/facebook/react-native/pull/2302

**Comment by NishanthShankar** [comment]
@potsypantsy made that minor change and it seems to pass the tests. Not sure why the earlier pr failed though

**Comment by potsypantsy** [comment]
@NishanthShankar I think the fix I was going for is a little different.

**Comment by strefethen** [comment]
The above check should be a runtime, not a compile time check. For example, we compile our app with support for 7.0 and the logic here fixes the app to one version of the other rather than dynamically handling it at runtime. I started working on a PR for this but thought I would search around for related issues first.

**Comment by NishanthShankar** [comment]
Will look into making the check at runtime then. 
But I guess, based on what you said, the existing code prevents people from targeting iOS8 and have to build only on iOS 7

**Comment by edo1493** [comment]
I am using 0.9.0 and iOS7.0 as a deployment target, but I still get this?

**Comment by MrMuetze** [comment]
I found that this is still an issue. Decides to use the wrong request function. Target is iOS 9 with Xcode 7.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/pushnotificationios-unable-to-request-permission

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
