### ISSUE TITLE
Question on dynamics refs

### ISSUE THREAD

**Issue by sidhacks** [facebook/react-native#2293]
On the react.js side we are using refs as this.refs.refName.getDOMNode

How can we get to the ref node based on the ref ID? I intend to make it active / inactive based on some logic.

What is the way to make it work in react-native as there is no DOM available.

Thanks in advance

**Comment by negativetwelve** [comment]
Say you have a component and you render it with the following code:

```
class MyComponent extends React.Component {

  render() {
    return (
      <ListView
        ref={listView => this._listView = listView}
        {...otherProps}
      />
    );
  }

}
```

You can then reference the component with `this._listView`. You can also just set the ref to a string (such as `listView`) and access using `this.refs.listView`.

The content on this page also applies to react native. https://facebook.github.io/react/docs/more-about-refs.html

**Comment by sidhacks** [comment]
No Actually my requirement is to use the refs dynamically


var Example1=React.createClass({
_toggleExpanded(name) {
  
 AlertIOS.alert(name);/** name is working **/
 this.refs.name.setNativeProps({collapsed:'false'});  / ** showing error as undefine**/ 
},
render:function(){
 var self=this;
     navLinks.navs.map(function(nav,index){ 
        var name="navlink"+index;
          return  (<--View key={"navlink"+index}> 
              <--TouchableHighlight onPress={this._toggleExpanded.bind(self,name)}  underlayColor="#ffa456">
                    <--View >
                      <--Text style={[styles.orgNameColor,styles.marginbottom]}>{nav.orgName}</Text>
                    <--/View>
                <--/TouchableHighlight>
                 <--Collapsible ref={component => this._name = component} collapsed={"true"}  duration={1500}>
                    <--View >
                      <--LoopWithNavElements navLinks={self.props.navLinks}   />
                    <--/View>
                <--/Collapsible>
              <--/View>)       
    },self)
   }
})

the above code is the instance where I need to handle the refs dynamically and get the element node using ref

**Comment by negativetwelve** [comment]
Could you by chance format the code using code formatting?

It looks like you're trying to refer to the `Collapsible` components but you're creating them in a loop and as a result, always setting `this._name` to the ref of the last component.

`this.refs` is just a javascript object which you can access dynamically just as you would any other object.

To make this work, you can add a string ref to your Collapsible (using the index so that you aren't overriding the same variable each time) and then using `this.refs[name]` to get the correct node.

Something like:

```
...
<Collapsible ref={name} />
...
```

Then:

```
_toggleExpanded(name) {
  this.refs[name].setNativeProps({collapsed: false});
}
```

Structuring this as two separate components would allow you to have a single ref per component where your loop will just be rendering a bunch of these components. Then you could put the `toggleExpanded` method in that sub component to call on the single ref directly.

**Comment by negativetwelve** [comment]
Hope you got it to work! I just also wanted to add that this sort of question is better served by Stack Overflow, we should try to keep issues relatively clean with actual bugs / feature discussions for react native itself.

**Comment by sidhacks** [comment]
Thanks.. we adopted another flow approach on our navigation.

**Comment by ide** [comment]
@negativetwelve thanks for chiming in
