### ISSUE TITLE
[Image] Support rendering image buffers

### ISSUE THREAD

**Issue by aleclarson** [facebook/react-native#2294]
I would like to use the `Buffer` class from [this repo](https://github.com/feross/buffer) to render my `Image` components with.

```coffee
React = require "react-native"
Buffer = require "buffer"
{ fetch } = require "fetch"

class MyComponent extends React.Component
  constructor: ->
    @state =
      loaded: no
      buffer: null

  componentWillMount: ->
    fetch(url).then (res) =>
      @setState
        buffer: new Buffer res._bodyText

  render: ->
    React.createElement React.Image,
      buffer: @state.buffer
```

This would be useful when creating images programmatically, using your own image loader, or even a custom `Image` component.

Will this ever be supported?

**Comment by ide** [comment]
Buffers specifically probably won't be supported on the native side for awhile because there's no C API to efficiently access the buffer contents or so I've been told.

If performance is a concern you'd probably want to keep the image bytes exclusively in Obj-C/Java and write native modules to manipulate the images (ex: a native module could write the bytes to disk and pass a file path to JS, which gets set as an Image source). Passing lots of bytes from native to JS with the fetch API will clog the bridge between the two languages and block touch events and other time-sensitive UI input.

**Comment by nicklockwood** [comment]
Yeah, the only way to transfer binary data between React JS and native right now is as a base64-encoded string, which we're generally discouraging for now because the performance is not good.

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/image-support-rendering-image-buffers
