### ISSUE TITLE
Websocket causing OutOfMemory in OkHttp on Android

### ISSUE THREAD

**Issue by mllrmat** [facebook/react-native#22957]
## Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
      Memory: 40.98 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.12.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 21, 23, 24, 25, 26, 27
        Build Tools: 23.0.1, 23.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.1, 27.0.3, 28.0.3
        System Images: android-19 | ARM EABI v7a, android-23 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.7.0 => 16.7.0 
      react-native: ^0.57.8 => 0.57.8 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

## Description
I use a websocket connection to a server to transmit data. I need to keep this connection open, so when I recieve a 'close' event, I am reconnecting the websocket. At some point the application fails with a OutOfMemory exception in the native modules (OkHttp). The stacktrace from crashlytics is attached. 

[by.gets.pickupstation.dev_issue_2_crash_5C375F5F03960001364BB67EC8A4FD19_DNE_0_v2.txt](https://github.com/facebook/react-native/files/2748915/by.gets.pickupstation.dev_issue_2_crash_5C375F5F03960001364BB67EC8A4FD19_DNE_0_v2.txt)

**Comment by dulmandakh** [comment]
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗
