### ISSUE TITLE
React native have serious compatibility issue with Facebook Audience Network

### ISSUE THREAD

**Issue by MiracleDeveloper** [facebook/react-native#23002]
- [V ] Review the documentation: https://facebook.github.io/react-native
  - [V] Search for existing issues: https://github.com/facebook/react-native/issues
  - [V ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
the latest version of react-native and facebook audience network

## Description

There's only one repo for facebook audience network with react-native app.
The repo is located at https://github.com/callstack/react-native-fbads

There is a very serious and blocking issue that MediaView always show blurred under react-native app.
You can refers to the issue from the link below
https://github.com/callstack/react-native-fbads/issues/132

It seems the author have contacted the fb team for the help but it seems there's no efficient way to track or communicate this issue.
The facebook audience network is not open source and a black box from users and it indeed trigger blocking compatibility issue (i.e. can't show bigger image in native ads).
We guess the MediaView implementation have conflicted the current react native ways to resize the components.
It might be audience network issue or react native design.
But there is no place for us to post audience network issue.
We ask for the help how we can make this serious issue more advanced.
Many people have suffered the issues and can't do anything further but only wait.

## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, share a project, or     share an app that reproduces the issue using https://snack.expo.io/. Please follow the guidelines for providing a MCVE: https://stackoverflow.com/help/mcve
Integrate the MediaView in react native and show the mediaview, the image always seems blurred.

**Comment by HolaMan** [comment]
++

We have suffered the same issue and it's really important for all related app developer.
Please help on the issue

**Comment by hramos** [comment]
Thanks for raising the issue, however I do not think the issue tracker for React Native is the proper place for this. Please continue using https://github.com/callstack/react-native-fbads/issues/132 as the centralized place for any discussion around this issue.

**Comment by HolaMan** [comment]
We can discuss a lot in that thread, and no one have ability to change or fix the bug because it require the team of react native and facebook audience network's help to fix it.

So if the issue is closed, is there any further and helpful way which can make progress?

**Comment by hramos** [comment]
I'd be happy to work with the folks at Callstack to resolve this through another channel - they know how to reach me.

**Comment by HolaMan** [comment]
@hramos 
It's really nice to have your help and support. 
Thank you very much,

I just raised the issues and the author just feedback their response
https://github.com/callstack/react-native-fbads/issues/132

Suraj-Tiwari (one of the author of callstack)
i tried to file issue and contact them with no proper response from them so
i think they won't resolve this issue. atleast for now

erandagan 
It's not the RN team's responsibility, but Audience Network's. They don't
support RN officially at the moment.


We have try to directly use Audience Network SDK in native environment and it works even in react native app with native Activity.
But if we directly use inject the component into react native virutal DOM, the issue happens.
It seems Audience Networks have some kinds of mechanism which is not compatible to react native virtual DOM.
There's no way for us to workaround because audience network is not open source. 

This issue is very serious because it means

every react-native app developer which want to earn revenue from FB audience network native ads, they can't because of this issue. The issue also trigger no impression for the app developer which results in no revenue.

We have no good channel to ask help for audience network's help, but I guess it might take some kinds of cooperation of RN and Ads team to resolve.

Sorry for the bothering and thanks for caring this issue.

**Comment by HolaMan** [comment]
@hramos 
We have reported the issues to audience network and no concrete progress for weeks.
Might you have any suggestion or right channel for us to reach out the right person?
