### ISSUE TITLE
[Navigator] Popping a Navigator destroys refs

### ISSUE THREAD

**Issue by pushrax** [facebook/react-native#2300]
Say you have component structure:

```jsx
render() {
  return <Navigator ref="nav" renderScene={renderScene} ... />
}

renderScene() {
  return <View ref="foo" />
}
```

1. On initial render, `refs.nav.refs.foo` is correctly set.
2. If you push a route, `refs.nav.refs.foo` is correctly updated.
3. After popping, key `foo` isn't present in `refs.nav.refs` at all.

If `ref="foo"` is defined by a function `f` instead:

1. `f` is called once by the View for the first route, passing the ref correctly.
2. `f` is called once by the View for the first route, passing null, then once passing the original ref (wat?). Then it's called once for the second route, passing the ref correctly.
3. `f` is called once for the first route, passing `null`, the once for the second route, passing `null`, then once for the first route again passing the ref correctly.

So in the end the last call is always correct, but ends up not correctly updating the `refs` object if a string is specified instead of a function.

**Comment by chandu0101** [comment]
>The next big (and probably most invasive change for a while) will be replacing string refs. Most can be automatically converted. #reactjs

>Use callback refs e.g. <div ref={n => this.node = n} /> to avoid having to do any upgrade work. Allows you to move work from life-cycles too

**Comment by ilansas** [comment]
Yep, I have the same problem ...

**Comment by ide** [comment]
You should receive a warning with string refs on routes. If this is not the case it is a bug.

The behavior with the ref switching between a component and null is expected behavior of React and is not specific to React Native. It passes in null whenever the ref function changes, which is on every render because you're passing in a new arrow function.

Popping should destroy the ref because you're unmounting the component. It would be bad if the ref weren't destroyed, leaking memory and causing unexpected side effects.

If you need to keep UI state around, use jumpBack instead of pop. If you need to keep other state around, use Flux or any other state management pattern of your choice.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/navigator-popping-a-navigator-destroys-refs

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.

**Comment by pushrax** [comment]
This issue was not about the behaviour of passing `null` to the callback, it was about the `refs` object being mutated incorrectly. I'm no longer using React Native though so I'm not sure if it's still an issue.
