### ISSUE TITLE
Autoscroll half of TextInput when its padding is set to '0'

### ISSUE THREAD

**Issue by shaktalles** [facebook/react-native#23067]
- [ x ] Review the documentation: https://facebook.github.io/react-native
  - [ x ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ x ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment

  React Native Environment Info:
    System:
      OS: Linux 4.15 Linux Mint 19 (Tara)
      CPU: (4) x64 Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
      Memory: 464.16 MB / 7.70 GB
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 11.4.0 - ~/.nvm/versions/node/v11.4.0/bin/node
      npm: 6.5.0 - ~/.nvm/versions/node/v11.4.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      react: 16.6.1 => 16.6.1 
      react-native: 0.57.7 => 0.57.7 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-linear-gradient: 2.5.3

## Description
When TextInput padding is set to '0' (zero), autoscroll will align exactly with the bottom of the text, covering part of the input field. This behavior happens in ScrollView and KeyboardAvoidingView too.

![20190118_141028](https://user-images.githubusercontent.com/24679343/51398575-0e5c8980-1b2b-11e9-9c7b-f8555d6f86ff.png)

Desired behavior: autoscroll should roll the input field completely into view.

**Comment by dulmandakh** [comment]
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗
