### ISSUE TITLE
[TouchableWithoutFeedback] does not add a wrapper Animated.View

### ISSUE THREAD

**Issue by ide** [facebook/react-native#2309]
@vjeux for a consistent API did you want all the Touchable components to have a wrapper Animated.View?

**Comment by vjeux** [comment]
In our codebase we haven't yet needed to animated touchable components. In any case, I just added View, Image and Text for shorthands, you can do

```
var AnimatedTouchableHighlight = Animated.createAnimatedWrapper(TouchableHighlight);
```

I'd like to limit the set of default ones as this means we've got to require them and then you may introduce cyclic dependencies, loading things that you don't need...

**Comment by ide** [comment]
I mean that TouchableBounce and TouchableOpacity now add their own Animated.View to the component hierarchy but TouchableHighlight and TouchableWithoutFeedback don't add a wrapper view, so they have different APIs now.

**Comment by vjeux** [comment]
Oh yeah, need to fix it. I tried to change TouchableHighlight to set the background color instead of fading in the opacity but the text flashes which is super bad. Need to fix this bug before we can move on. Great thing is that they are already making new views so we'll be able to just allow more than one child without breaking the users

**Comment by dvine-multimedia** [comment]
Just wanted to suggest, that the newly added Animated.view might be the cause for some regressions. See #2148.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/touchablewithoutfeedback-does-not-add-a-wrapper-animatedview

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is heavily focused working on performance.
