### ISSUE TITLE
React Native does not honor Intent.putExtra(Intent.EXTRA_PROCESS_TEXT, STRING)

### ISSUE THREAD

**Issue by tylerssn** [facebook/react-native#23129]
## Environment
```
  React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 495.81 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.3.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 23, 27
        Build Tools: 27.0.3
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
```

## Description
I have an android app that takes advantage of Androids new `Intent.EXTRA_PROCESS_TEXT` via: 

```xml
<intent-filter>
        <action android:name="android.intent.action.PROCESS_TEXT" />
        <category android:name="android.intent.category.DEFAULT" />
        <data android:mimeType="text/plain" />
</intent-filter>
```

This intent appends a menu item to Androids cut/copy/paste menu so that one can, for example, translate selected text and return the new value to the highlighted text as a replacement. I've noticed that react native apps, such as Messenger, that use app state to update the text fields do not update the selected text when the result is returned via:

```java
            Intent intent = new Intent();
            intent.putExtra(Intent.EXTRA_PROCESS_TEXT, outputText);
            setResult(RESULT_OK, intent);
            finish()
```

The code above has been tested in various apps and react native apps are the only ones that do not display the new value (in my limited testing).

## Reproducible Demo
1. Configure your test android device to have the `Intent.EXTRA_PROCESS_TEXT` feature described above. It can be part of your existing react native app or a fresh android app - we only care that it can be called: https://medium.com/androiddevelopers/custom-text-selection-actions-with-action-process-text-191f792d2999
2. Test working functionality: Open your contacts app, type text into any input field, highlight it, and select your newly added menu item. You should see the text replaced with your new value in your input field.
3. Test "broken" functionality: Open a react native app that uses state-managed input fields (Facebook Messenger is a good test) and repeat Step 2. You should see that your text is no longer highlighted, but it has not been replaced.

**Comment by kelset** [comment]
Hello there 👋 this issue seems to have a really low activity on it.

Because of this inactivity, we are closing it - but please feel free to comment and post a repro for version 0.59 and we'll gladly re-open it 🤗

That said, I'm a bit confused by your reporting:

1. you mention that you are using Expo, so this issue would need to be open there
1. the repro steps you have written are a bit generic, making it super hard to actually get to a test app that can show the issue you mention
1. you base your report on the fact that FB Messanger is a RN app - which actually isn't

Please let me know if this issue is actually reproducible in a `react-native init`'ed app (on version 0.59) - ideally posting a link to a repo that has a test app already set up to recreate the issue.
