### ISSUE TITLE
Upgrade "connect" to a modern version (or look into koa/express)

### ISSUE THREAD

**Issue by ide** [facebook/react-native#2317]
The packager is using an old version of connect which has some vulnerabilities (in practice probably not an issue but would be good to fix) and the API has changed a bunch. Most small Node servers are using koa or express now so it could be good to upgrade to one of those.

This work should be fairly accessible to potential contributors who have JS experience and are looking for a challenging but accessible task if someone wants to work on a PR.

**Comment by ide** [comment]
cc @amasad - this work should be mostly contained to the packager frontend but tell me if it'd be stepping on toes

**Comment by amasad** [comment]
I think we should be good. We have a few more middlewares internally that needs to be tested by they seem fairly straightforward.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/upgrade-connect-to-a-modern-version-or-look-into-koaexpress

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is heavily focused working on performance.
