### ISSUE TITLE
[TextInput] maxLength doesn't work correctly with multibyte characters

### ISSUE THREAD

**Issue by ide** [facebook/react-native#2343]
As shown in #1945, TextInput's maxLength prop doesn't work with Chinese characters. It's probably looking at the number of bytes and should be counting codepoints or glyphs instead.

![textinput maxlength issue](https://cloud.githubusercontent.com/assets/703164/9030405/af3fbde0-39d4-11e5-923c-2aaebd0de4a1.gif)

While we're at it, does anyone want to stress test the single/multiline TextInput components with all sorts of Unicode using Naughty Keyboard? https://github.com/Palleas/NaughtyKeyboard/

**Comment by sahrens** [comment]
Probably a just need to use unicode length instead of byte length - want to send a PR?

**Comment by ide** [comment]
I opened this since @monyxie mentioned it in #1945. Perhaps someone with non-English apps who needs this feature would like to work on it? 

> unicode length instead of byte length
It might be a little trickier than this if we want to limit the number of glyphs. IIRC combining diacritical marks take up multiple Unicode codepoints but are rendered as one character like ў.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/textinput-maxlength-doesnt-work-correctly-with-multibyte-characters

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is heavily focused working on performance.

**Comment by lavystord** [comment]
Any update？？

**Comment by chengxiaole** [comment]
Any update ? ? ?

**Comment by jamessawyer** [comment]
Any news?
