### ISSUE TITLE
Error on react-native run-android

### ISSUE THREAD

**Issue by alisteroz1985** [facebook/react-native#23481]
I am trying the example app but I have not been able to get the android emulator to work. this is the error i receive when I run the command:  react-native run-android. 

Starting JS server...
Building and installing the app on the device (cd android && ./gradlew installDebug)...

FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type PluginResolutionStrategyInternal using BuildScopeServices.createPluginResolutionStrategy().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

Command failed: ./gradlew installDebug

Error: Command failed: ./gradlew installDebug
    at checkExecSyncError (child_process.js:616:11)
    at Object.execFileSync (child_process.js:634:13)
    at runOnAllDevices (/Users/alister/Desktop/AppDev/AwesomeProject/node_modules/react-native/local-cli/runAndroid/runAndroid.js:299:19)
    at buildAndRun (/Users/alister/Desktop/AppDev/AwesomeProject/node_modules/react-native/local-cli/runAndroid/runAndroid.js:135:12)
    at isPackagerRunning.then.result (/Users/alister/Desktop/AppDev/AwesomeProject/node_modules/react-native/local-cli/runAndroid/runAndroid.js:65:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by clovisdasilvaneto** [comment]
hey @alisteroz1985 I was having the same error, but I solved it by changing my JAVA_HOME version, because I was using java 11, but for some reason android is not compatible with it and I change to java 8 and now it works :) 

If you do not know how to change your java version, follow this steps bellow:

1. Open your `.profile` file (if you don't have it created, you can create a new one, or use your .bash_profile)
2. Put the follow line: 
```
export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
```
3. Save and close it
4. In your terminal, you can put: `source ~/.profile`
5. Run `react-native run-android` again and it should works!

**Comment by georgiosApo** [comment]
What really solved my issue was to simply follow the docs over at:
https://facebook.github.io/react-native/docs/getting-started
Make sure to pick the right options when choosing targets (Expo/bare & iOS/Android).
Setup takes a couple of minutes but it works flawless after that on my end.
Good luck.
