### ISSUE TITLE
App Crashed when not set sections.data for sectionList

### ISSUE THREAD

**Issue by hweister** [facebook/react-native#23526]
## 🐛 Bug Report
For SectionList, if user don't set data field for sections property, app will crash.

## To Reproduce
Just as described above, set sections=[{data: undefined},{data: undefined}] for SectionList.

## Expected Behavior
Either update the document, notice user data is a "must have" key for section define
or update VirtualizedSectionList.js file, check if section.data is defined, before call section.data.length.

**Comment by ericlewis** [comment]
@hweister, you must set them to empty arrays instead of undefined. I’m not sure the expected behavior should be to silently fail for misshapen section data, it makes more sense to me to error out in this scenario so you can figure out how it happened. If you prefer it to not crash, ensure you set empty arrays.

**Comment by dulmandakh** [comment]
I think you should be doing this, if you want to render empty list.

```javascript
sections=[{data: undefined},{data: undefined}]
```
