### ISSUE TITLE
[ScrollView] "Pull to refresh" by setting contentInset causes jitter

### ISSUE THREAD

**Issue by hayeah** [facebook/react-native#2356]
I am trying to implement "pull to refresh" UI for ScrollView. The strategy I am using is:

1. Use a positive contentInset to hide the refresh header, and,
2. When vertical scroll exceeds a certain distance, set contentInset to 0 to show the refresh header.

```js
// https://github.com/hayeah/rn-ScrollViewContentInsetChangeJitter/blob/a5d58d9acf83ac07f86332351b5550237cf1b2fa/index.ios.js#L22-L61
var REFRESH_HEADER_HEIGHT = 50;

var ScrollViewContentInsetChangeJitter = React.createClass({
  getInitialState: function() {
    return {
      topInset: -REFRESH_HEADER_HEIGHT,
    };
  },

  handleScroll: function(e) {
    var {contentInset,contentOffset} = e.nativeEvent;
    console.log("offset y",contentOffset.y);
    if(contentOffset.y < 0 && this.state.topInset != 0) {
      this.setState({topInset: 0});
    }
  },

  hideHeader: function() {
    console.log("hide header");
    this.setState({topInset: -REFRESH_HEADER_HEIGHT});
  },

  render: function() {
    return (
      <ScrollView style={styles.scrollView}
        contentOffset={{y: -this.state.topInset}} /* reset initial offset */
        contentInset={{top: this.state.topInset}}
        onScroll={this.handleScroll}
        scrollEventThrottle={4}
        automaticallyAdjustContentInsets={false}>
        <Image style={styles.image} source={require("image!hikers")}/>

        <View style={styles.refreshHeader}>
          <TouchableOpacity onPress={this.hideHeader}>
            <Text>Tap to hide refresh header</Text>
          </TouchableOpacity>
        </View>

      </ScrollView>
    );
  }
});
```

This works, but with an animation bug that causes the content to jump down after the contentInset is set to 0. The following video illustrates this problem:

[![](https://i.ytimg.com/vi/s7AtL673v4U/hqdefault.jpg)](https://youtu.be/s7AtL673v4U)

Having investigated the issue, it's not a ReactNative bug. It seems to be an UIScrollView issue, which I explain [in more details separately](hayeah/rn-ScrollViewContentInsetChangeJitter).

@jsdf's [RefreshableListView](https://github.com/jsdf/react-native-refreshable-listview) also exhibit this problem. Because of this bug, I don't know if there's a way to implement the classic "pull to refresh" UI... 

Any idea or workaround?

**Comment by negativetwelve** [comment]
I currently have an implementation that I haven't gotten around to open sourcing yet but it essentially follows this format:

An outer view that contains the refreshable component and the scroll view itself. When the scrollview decides it needs to refresh, it sets a `marginTop` on the `contentContainer` of the scroll view so that the hidden refreshable component behind it is shown.

Essentially something like:

```
<View>
  <RefreshIndicator />
  <ScrollView
    contentContainerStyle={this.styleContentContainer()}
  />
</View>

styleContentContainer() {
  return [
    this.state.isRefreshing && {marginTop: this.props.minimumPullDownDistance},
  ];
}
```

Also, I don't actually call the refresh until the user lifts up the current touch (otherwise you run into a problem where if the user pulls down and never lifts up, the page will continuously refresh).

I believe I got this technique by looking at a bunch of different refresh components and combining the best parts of each, but I can't remember which one specifically did this so apologies for not giving credit for this idea!

**Comment by hayeah** [comment]
@negativetwelve wouldn't setting marginTop also cause a jump? It seems to behave like:

![margin-strategy](https://cloud.githubusercontent.com/assets/50120/9301308/089c9210-4500-11e5-895f-64d1dc32f9ab.png)

**Comment by negativetwelve** [comment]
The scrollview is positioned to cover the "pull to refresh indicator". Say your distance to refresh is set to 60. As you pull down, you're pulling the component from 0 -> 60. When it reaches 60, it adds a margin to the top so that it stays at 60. The reason why this works is because I'm not starting the refresh until *after* the user lets go. If the user drags more than 60 pixels down, no margin will have been added yet.

Then when the user lets go, the margin will appear stopping the component from scrolling back to 0 and keeping it at 60 until the refresh completes.

Correct me if I'm wrong, but in your component, you're setting the values as the user scrolls so if the user holds the scrollview down, there's a possibility (which happens pretty much every time) where the user will have their scroll offset added to the artificial offset that you're adding causing the white box to appear.

Sorry for not providing any code, the component is unfortunately coupled with some other logic (working with promises for the actual request) making it hard to pull out just these parts.

**Comment by ide** [comment]
I wrote refreshable-scroll-view which doesn't have jitter but has issues when ending the PTR animation. When I restore the contentInset it seems to immediately stop any scroll animations that are in progress. It's close to a production-quality component and handles insets fairly well (incl automatic insets) and this is the last issue that keeps it from being really great. https://github.com/exponentjs/react-native-refreshable-scroll-view

**Comment by negativetwelve** [comment]
These aren't currently documented but you might find use for:

* onScrollBeginDrag
* onMomentumScrollEnd
* onResponderGrant
* onResponderRelease

[Here's](https://github.com/facebook/react-native/blob/master/Libraries/Components/ScrollView/ScrollView.js#L367) the relevant lines of code.

Yes, they are undocumented -- currently I'm unsure if that's because they're "private" or because the documentation hasn't been updated to reflect this. According to #1410, it seems like the latter :)

**Comment by hayeah** [comment]
@negativetwelve ah, using onResponderRelease does make the jitter go away. But it also causes the in-progress scroll up animation to stop abruptly.

See this video:

[![](https://i.ytimg.com/vi/uLu6SOKEQs4/hqdefault.jpg)](https://youtu.be/uLu6SOKEQs4)

**Comment by negativetwelve** [comment]
Here's what I'm doing:

```
  render() {
    return (
      <View
        style={[this.styles.container, this.props.style]}>
        {this.renderHeader()}
        <ScrollView
          {...this.props}
          ref={'scrollView'}
          style={this.styles.scrollView}
          contentContainerStyle={this.styleContentContainer()}
          onScroll={this._handleScroll}
          onResponderGrant={this._handleResponderGrant}
          onResponderRelease={this._handleResponderRelease}
          scrollEventThrottle={this.props.scrollEventThrottle}
        />
      </View>
    );
  }

  // --------------------------------------------------
  // Styles
  // --------------------------------------------------
  styleContentContainer() {
    return [
      this.state.isRefreshing && {marginTop: this.props.minimumPullDownDistance},
    ];
  }

  static styles = {
    container: {
      flex: 1,
    },

    scrollView: {
      backgroundColor: Colors.transparent,

      position: 'absolute',
      top:      0,
      left:     0,
      right:    0,
      bottom:   0,
    },
  }
```

Mainly, you want to position the scrollview to take up the entire view (with a transparent background to let the header (refresh component) show through). The `marginTop` should go on the `contentContainerStyle` prop, not the style of the scrollview itself. Hope this helps!

**Comment by hayeah** [comment]
@ide taking @negativetwelve hint to use onResponderRelease callback, I got a "perfect" version working, no jitter or abrupt stop. 

It changes contentInset to show refresh header, which works fine from onResponderRelease. Hiding the refresh header is a more convoluted two steps process.

1. Add negative margin to the scroll view upward to hide the refresh header, use LayoutAnimation to move it into place.
2. After LayoutAnimation is completed, change contentInset from 0 to negative.

A more straightforward approach for hiding the refresh header might be to set contentOffset to 0 after changing contentInset. But it turned out that if you set contentOffset in anyway, you'd get abrupt scrolling animation.

Video Demo here: https://www.youtube.com/watch?v=obFk891ZolU&feature=youtu.be

Code here: https://github.com/hayeah/rn-ScrollViewContentInsetChangeJitter/blob/inset-working/index.ios.js

(P.S. I am still trying to get @negativetwelve's marginTop approach to work, will report back)

**Comment by negativetwelve** [comment]
@hayeah not sure if this is what you want, but my implementation follows what the main facebook app does. If you notice, the indicator is always behind the scroll view and no matter how much you pull down, the component is always in the same spot. Then you don't have to deal with the negative offsets and imo, a slightly better user experience because the spinner will always be in a constant position (not dragged by the user).

Glad you got a version working though!

**Comment by hayeah** [comment]
@negativetwelve thanks for all the help, really appreciated it :+1: 

I've tried putting marginTop in the contentContainer per your suggestion. It works, but there's still that awkward stuttering with the scroll animation.

Here's my code (using the marginTop approach)... not sure what's wrong.

https://github.com/hayeah/rn-ScrollViewContentInsetChangeJitter/blob/fa9669eb6dbb21e61012f88219681b793e721d39/index.ios.js#L62

If you could find time to open source a demo of your solution that'd be great! I‘d really love to throw away my kludge... if I can use your solution instead.

P.S. I've modified my PTR demo so the refresh indicator stays at the same spot.

[<img width="459" alt="screen shot 2015-08-17 at 10 30 46 pm" src="https://cloud.githubusercontent.com/assets/50120/9307215/ab7faf24-452f-11e5-8486-978f60593ba9.png">](https://youtu.be/Vu7wRLML2-w)

[Code](https://github.com/hayeah/rn-ScrollViewContentInsetChangeJitter/blob/inset-working/index.ios.js)

**Comment by negativetwelve** [comment]
@hayeah I'll let you know when I get around to doing that, super busy with a lot of other stuff right now but it is on my todo list :)

your video here looks almost exactly like mine -- I'm facing some issues with vertical scroll views inside of horizontal scroll views and touch responders which intercepts some touches causing the scrolling to stop abruptly. Not sure if that's what you're seeing but the issue is being tracked here #41
