### ISSUE TITLE
iOS & Android: Enable views to be nested within <Text>

### ISSUE THREAD

**Issue by JosephDunivan** [facebook/react-native#23601]
@rigdern 

### Issue: 
Developers must use overly complicated methods to achieve nested touchable components within a `<Text>` component by wrapping it in a view and setting multiple flex css styles. Same goes for any other component intended to be nested within a `<Text>` component. With the workaround I provided, it will break the second any styling is changed, or when text length increases. Developers need to update css styling for every variation of text length.

### Affects: 
iOS and Android

### Expected Functionality: 
Being able to nest views inline within a text component, such as Touchable Opacity, or Image. 

### Steps to Reproduce: 
Install react native project with react-native init and open in iOS Simulator iPhone X running iOS 11 or 12. Then copy and paste code provided.

### Image of issue
![Image of issue](https://raw.githubusercontent.com/JosephDunivan/ReactNativeTextIssue/master/Simulator%20Screen%20Shot%20-%20iPhone%20X%20-%202019-02-22%20at%2009.17.57.png)

### Image of Expected Functionality when nesting views
![Image of Fixed Issue](https://raw.githubusercontent.com/JosephDunivan/ReactNativeTextIssue/master/Simulator%20Screen%20Shot%20-%20iPhone%20X%20-%202019-02-22%20at%2009.18.43.png)

The issue is 100% reliant on `textSize` and the `width` of the Component. For this reason please use iOS simulator running iOS 11 or 12, on a iPhone X. 

### Code Snippet where "feature"(error) occurs 
``` react-native
/**
 *
 * @format
 * @flow
 * @lint-ignore-every XPLATJSCOPYRIGHT1
 */

import React, {Component} from 'react';
import {
  Platform, 
  StyleSheet, 
  Text, 
  View, 
  StatusBar, 
  Image, 
  TouchableOpacity,
  ScrollView,
  Dimensions
} from 'react-native';

var screen_width = Dimensions.get('window').width - 40

type Props = {};
export default class App extends Component<Props> {
  render() {
    return (
      <View style={styles.background}>
      <StatusBar barStyle="light-content"/>
        <View style={styles.container}>
          <View style={styles.wrap_text}>
            <Text style={styles.text}>By creating a new account or signing in with Facebook, you are agreeing to our </Text>
            <TouchableOpacity>
              <Text style={styles.text_touchable}>Terms of Service </Text>
            </TouchableOpacity>
            <Text style={styles.text}>and </Text>
            <TouchableOpacity>
              <Text style={styles.text_touchable}>Privacy Policy.</Text>
            </TouchableOpacity>
          </View>
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  background: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#182B42',
  },
  container: {
    marginTop: 80,
    marginBottom: 30,
    marginLeft: 20,
    marginRight: 20,
    width: screen_width,
  },
  wrap_text: {
      flexWrap: 'wrap',
      flexDirection: 'row',
      justifyContent: 'center',
      width: 350,
  },
  text: {
    lineHeight: 25,
    fontSize: 11,
    color: '#738395',
  },
  text_touchable: {
    color: '#FFFFFF',
    lineHeight: 25,
    fontSize: 11,
    textDecorationLine: 'underline',
  },
});
```

#### The goal is to get all elements on the same line. 
```react-native
/**
 *
 * @format
 * @flow
 * @lint-ignore-every XPLATJSCOPYRIGHT1
 */

import React, {Component} from 'react';
import {
  Platform, 
  StyleSheet, 
  Text, 
  View, 
  StatusBar, 
  Image, 
  TouchableOpacity,
  ScrollView,
  Dimensions
} from 'react-native';

var screen_width = Dimensions.get('window').width - 40

type Props = {};
export default class App extends Component<Props> {
  render() {
    return (
      <View style={styles.background}>
      <StatusBar barStyle="light-content"/>
        <View style={styles.container}>
          <View style={styles.wrap_text}>
            <Text style={styles.text}>By creating a new account or signing in with Facebook, </Text>
            <Text style={styles.text}>you are agreeing to our </Text>
            <TouchableOpacity>
              <Text style={styles.text_touchable}>Terms of Service </Text>
            </TouchableOpacity>
            <Text style={styles.text}>and </Text>
            <TouchableOpacity>
              <Text style={styles.text_touchable}>Privacy Policy.</Text>
            </TouchableOpacity>
          </View>
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  background: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#182B42',
  },
  container: {
    marginTop: 80,
    marginBottom: 30,
    marginLeft: 20,
    marginRight: 20,
    width: screen_width,
  },
  wrap_text: {
      flexWrap: 'wrap',
      flexDirection: 'row',
      justifyContent: 'center',
      width: 350,
  },
  text: {
    lineHeight: 25,
    fontSize: 11,
    color: '#738395',
  },
  text_touchable: {
    color: '#FFFFFF',
    lineHeight: 25,
    fontSize: 11,
    textDecorationLine: 'underline',
  },
});
```
### Expected functionality
```react-native
/**
 *
 * @format
 * @flow
 * @lint-ignore-every XPLATJSCOPYRIGHT1
 */

import React, {Component} from 'react';
import {
  Platform, 
  StyleSheet, 
  Text, 
  View, 
  StatusBar, 
  Image, 
  TouchableOpacity,
  ScrollView,
  Dimensions
} from 'react-native';

var screen_width = Dimensions.get('window').width - 40

type Props = {};
export default class App extends Component<Props> {
  render() {
    return (
      <View style={styles.background}>
      <StatusBar barStyle="light-content"/>
        <View style={styles.container}>
          <View style={styles.wrap_text}>
            <Text style={styles.text}>By creating a new account or signing in with Facebook, 
            you are agreeing to our 
              <TouchableOpacity>
                <Text style={styles.text_touchable}>Terms of Service </Text>
              </TouchableOpacity> 
            and
              <TouchableOpacity>
                <Text style={styles.text_touchable}>Privacy Policy.</Text>
              </TouchableOpacity>
            </Text>
          </View>
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  background: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#182B42',
  },
  container: {
    marginTop: 80,
    marginBottom: 30,
    marginLeft: 20,
    marginRight: 20,
    width: screen_width,
  },
  wrap_text: {
      flexWrap: 'wrap',
      flexDirection: 'row',
      justifyContent: 'center',
      width: 350,
  },
  text: {
    lineHeight: 25,
    fontSize: 11,
    color: '#738395',
  },
  text_touchable: {
    color: '#FFFFFF',
    lineHeight: 25,
    fontSize: 11,
    textDecorationLine: 'underline',
  },
});
```

**Comment by JosephDunivan** [comment]
@rigdern 
Please Reopen issue.

**Comment by rigdern** [comment]
@JosephDunivan I don't have the ability to reopen closed issues. I recommend following the bot's feedback and using an issue template.

I read through your full report above. Here are my thoughts:

### User Scenario

The user scenario you want to solve is you want to have pressable text that gives the user feedback when they're pressing it.

### Solution 1: Enhance `Text` `onPress` feature

One solution would be to go in the direction of the `Text` component's `onPress` prop. For example, we could extend `Text` to have `onPressStart` and `onPressEnd` events so that you could use those hooks to style the text how you want. Or `Text` could show a default visual when it's pressed.

### Solution 2: Enhance inline view feature

Another solution would be to go in the direction of inline views. Here's a summary of the state of inline views and what you'd need:
  - iOS already implements inline views but it's disabled. We're waiting for the Android implementation to be completed before enabling the inline views feature.
  - The Android inline view feature is currently being code reviewed: https://github.com/facebook/react-native/pull/23195
  - You'll need inline views to support taking on the size of the text content inside of it. The iOS inline view implementation supports this but the Android one does not. The Android implementation currently requires that you specify the width and height of the inline view as props.
  - You'll need the text inside of the inline view to have the proper vertical alignment relative to the text outside of the inline view. To illustrate this problem, I ran your last code snippet on iOS with inline views enabled:
  ![image](https://user-images.githubusercontent.com/199935/53528933-f5d37d80-3a9f-11e9-974d-d49792e2190d.png)

### Closing Thoughts

I suspect solution 1 will be easier to pull off. In fact, it looks like `Text` already has code for rendering a highlight when the text is pressed:
  - [Code to track when `Text` is being pressed](https://github.com/facebook/react-native/blob/10c835214160cc5a5726c8dd9f0d42a0275d198b/Libraries/Text/Text.js#L225-L234)
  - [`Text's` `suppressHighlighting` prop](https://facebook.github.io/react-native/docs/text#suppresshighlighting) for disabling the default highlight on press effect
