### ISSUE TITLE
[NavigatorIOS] Linking NavigatorIOS with UINavigationController stack (obj C)

### ISSUE THREAD

**Issue by gudmundurmar** [facebook/react-native#2362]
Now I've read the instruction on how to [integrate React Native into your Objective C app.]( 
https://facebook.github.io/react-native/docs/embedded-app-ios.html#content)

Is it possible to link the stack of your UINavigationController (Objective C navigator) with the [NavigatorIOS](https://facebook.github.io/react-native/docs/navigatorios.html#content) in React Native?

**Comment by axelg12** [comment]
+1 this would be very useful !

**Comment by axelg12** [comment]
cc @vjeux

**Comment by brentvatne** [comment]
@clayallsopp has done this and from what I can tell he would not recommend it.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/navigatorios-linking-navigatorios-with-uinavigationcontroller-stack-obj-c

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is heavily focused working on performance.
