### ISSUE TITLE
set FontFamily for some device Android (Oppo,...)

### ISSUE THREAD

**Issue by huyvm** [facebook/react-native#23914]
With some Oppo device, have bugs when use system font. Lost some word. 
Can fix it by add line code for Text.js in Text Component Library React Native:
`if(Platform.OS == 'android') {
      newProps = { ...newProps, style: [newProps.style, {fontFamily: ''}]}
}`
I hope RN in new version will fix this bug.

**Comment by dulmandakh** [comment]
@huyvm could you please specify the system font

**Comment by kelset** [comment]
@huyvm as explained by the bot, we can't help you without all the necessary information.

I'm going to close this unless you can provide a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting) for RN 0.59.

All of this said, I also suggest that you open a PR that implements your proposed fix, so that it can be further discussed and directly tested 🤗
