### ISSUE TITLE
SDK is upgraded to 28. On Android 9.0, when text is displayed in multiple lines, the last line is displayed in half, just as the whole text does not calculate the line spacing.

### ISSUE THREAD

**Issue by thinkzh** [facebook/react-native#23918]
![image](https://user-images.githubusercontent.com/48543389/54338408-c6f70300-466c-11e9-813c-771732b3751f.png)

**Comment by dulmandakh** [comment]
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗

**Comment by gaodeng** [comment]
@dulmandakh  This bug is easy to reproduce.please reopen it.

**Comment by dulmandakh** [comment]
please provide demo code that I can use to reproduce the issue. Thank you

**Comment by gaodeng** [comment]
> please provide demo code that I can use to reproduce the issue. Thank you

hi here is the demo repository.
https://github.com/gaodeng/TextClipedIssue

![IMAGE 2019-04-08 17:36:57](https://user-images.githubusercontent.com/1118249/55714252-e93e2f80-5a24-11e9-8bda-c94039822dd6.jpg)

**Comment by dulmandakh** [comment]
Thank you, now we can work on it.

**Comment by thinkzh** [comment]
> 
> Thank you, now we can work on it.



When will it be revised and released?

**Comment by gaodeng** [comment]
any progress?

**Comment by dulmandakh** [comment]
nope, had no time to dig into the issue
