### ISSUE TITLE
'React/RCTRootView.h' file not found

### ISSUE THREAD

**Issue by YYL1999** [facebook/react-native#23952]
l cannot run the project,because 'React/RCTRootView.h' file not found.so what should l do??

**Comment by RyanElliott10** [comment]
Try building `React` before the entire project. This may also be an issue with how you have your build scheme setup -- make sure you to not have `Parallelize Build` selected.

Xcode -> Project Scheme -> Manage Schemes -> Double Click on yours -> Build -> Uncheck `Parallelize Build`

**Comment by akaralar** [comment]
I faced the same issue. Tried building `React` first but it didn't fix the issue. `Parallelize Build` is unselected as well. 

I faced this issue when I tried to install `react-native-fbsdk` via cocoapods. Not only with `react-native-fbsdk` but packages had similar errors, files not found that belong to the `React` project. Cocoapods installs a version of `React` where there is only a `Core` folder in the pod, and the files not found were in other folders in `React`. I worked around the issue by linking manually instead of installing with cocoapods.

**Comment by YYL1999** [comment]
> Schemes

thanks .I redesigned a project that has been solved.

**Comment by YYL1999** [comment]
> 我遇到了同样的问题。先尝试建筑，`React`但没有解决问题。`Parallelize Build`也是未被选中的。
> 
> 当我尝试`react-native-fbsdk`通过cocoapods 安装时，我遇到了这个问题。不仅有`react-native-fbsdk`一些其他包有类似的错误，找不到属于该`React`项目的文件。这些库中常见的事情了，我是用的CocoaPods（安装它们按的结果`react-native link <package>`。的CocoaPods安装某个版本的`React`那里是只有`Core`在群文件夹，并在未找到的文件存在于其他文件夹`React`包含在主要项目。我通过手动链接而不是用cocoapods安装来解决这个问题。

I redesigned a project that has been solved.thanks

**Comment by michalchudziak** [comment]
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗
