### ISSUE TITLE
[DatePickerIOS] "Warning: Failed propType..." even when required propTypes are provided to DatePickerIOS

### ISSUE THREAD

**Issue by kevinold** [facebook/react-native#2397]
I am receiving errors for required propTypes in 0.9.0 even though they are provided to DatePickerIOS, **even though the UI renders successfully and I am able to interact with the datepicker**.

This code:

```
<DatePickerIOS
  style={styles.button}
  date={new Date(this.state.date)}
  mode="date"
  onDateChange={this.onDateChange}
/>
```

Triggers these warnings in the Chrome debugger-ui console:

```
Warning: Failed propType: Invalid prop `date` supplied to `RCTDatePicker`, expected instance of `Date`. Check the render method of `DatePickerIOS`.

Warning: Failed propType: Required prop `onDateChange` was not specified in `RCTDatePicker`. Check the render method of `DatePickerIOS`.
```
![screen shot 2015-08-21 at 10 09 54 am](https://cloud.githubusercontent.com/assets/21967/9412360/e7aa612e-47f0-11e5-93af-b7166971f200.png)
![screen shot 2015-08-21 at 10 09 34 am](https://cloud.githubusercontent.com/assets/21967/9412361/e7ac231a-47f0-11e5-8fbf-f2a2648f59c9.png)

**Comment by truewh** [comment]
I just got this error as well. Besides, DatePickerIOS rolls back to present time by it self.

**Comment by kevinold** [comment]
@vjeux Great chatting today!  This was the issue I mentioned.

**Comment by chlela** [comment]
I'm still seeing the same issue with 0.11.0-rc update

**Comment by coderdave** [comment]
Seeing this issue also.

**Comment by ide** [comment]
@Vjeux who owns DatePickerIOS (or is it better as a community responsibility)?

**Comment by vjeux** [comment]
@sahrens do you know what's going on here?

**Comment by sahrens** [comment]
That is weird - possible bug in PropTypes with instanceOf?

The resetting thing is a kp that we're looking at internally.

**Comment by brentvatne** [comment]
https://github.com/facebook/react-native/commit/33036b1f01c1e3816745bfe9c243a478445559ee

Is it fixed after this?

**Comment by alvaromb** [comment]
The warning disappears if you change this line https://github.com/facebook/react-native/blob/master/Libraries/Components/DatePicker/DatePickerIOS.ios.js#L124 to send the ``Date`` instance instead of the timestamp:

```javascript
date={props.date}
// Instead of
date={props.date.getTime()}
```

If yo do so, you have to change all the date props to send ``Date`` objects in the ``DatePickerIOS`` component. Doing that does not affect the component behaviour because the method ``+ NSDate:`` of ``RCTConvert`` checks that if the date provided is a string it creates a ``NSDateFormatter`` to parse the date and create a ``NSDate`` object. 

The exact line that's raising the warning is located in the file ``ReactElementValidator.js:260`` as you can see in the following screenshot:

<img width="603" alt="screen shot 2015-09-25 at 11 35 17" src="https://cloud.githubusercontent.com/assets/289640/10097497/c2c03e5c-6379-11e5-86f4-409b7d47de6b.png">

It seems that the native component is expecting a date instance, if you check the ``RCTDatePickerManager.m`` file (https://github.com/facebook/react-native/blob/33036b1f01c1e3816745bfe9c243a478445559ee/React/Views/RCTDatePickerManager.m#L37), you can see this:

```objc
RCT_EXPORT_VIEW_PROPERTY(date, NSDate)
```

I'm not completely sure, but it seems that this is the line that expects a ``Date`` object instance. If the js component sends a timestamp, maybe it should be changed from ``NSDate`` to ``NSTimeInterval``.

For me the solution should be changing the js component to send ``Date`` instances instead of using ``getTime()`` to pass the timestamp. This forces the ``RCTConvert`` to create an ``NSDateFormatter`` instance, but it does this just once so the performance should not be a problem.

@vjeux @nicklockwood please let me know if this solution works for you and I'll send a PR.

**Comment by mschwartz** [comment]
```javascript
class BirthdayField extends Component {
    constructor() {
        super();
        this.state = {
            date: new Date(),
            ageText: '',
            age: {
                years: 0,
                months: 0
            }
        };
    }
    
    render() {
        return (
            <View >
            <Text style={styles.label}>Birthday</Text>
            <Text>{this.state.ageText}</Text>
            <DatePickerIOS
            style={styles.picker}
            mode="date"
            date={this.state.date}
            onDateChange={(e) => {
                this.onDateChange(e);
            }}
            />
            </View>
            );
    }
    
    onDateChange(date) {
        var msPerMonth = 365 * 24 * 60 * 60 * 1000 / 12,
            now = new Date(),
            diff = now - date,
            monthsFloat = diff / msPerMonth,
            years = parseInt(monthsFloat / 12, 10),
            months = parseInt(monthsFloat - years * 12, 10),
            age = {
                years: years,
                months: months
            };

        this.setState({
            date: date,
            age: age,
            ageText: 'You are ' + age.years + ' years ' + age.months + ' months old.'
        });
    }
}
```

Yields two warnings in Chrome Dev Tools:

![image](https://cloud.githubusercontent.com/assets/329637/10136522/d6a3f15c-65a9-11e5-9f5a-02280d0e888e.png)

**Comment by mschwartz** [comment]
I'd add the suggestion that inspection be used to find onDateChange() method on the class so it doesn't have to be specified as an attribute to the DatePickerIOS tag.

**Comment by cgarvis** [comment]
`minimumDate` also throws failed prop warnings.

**Comment by ilansas** [comment]
I've got this for : 
- date
- onDateChange
- minimumDate
- maximumDate

Not sure for the other properties.

**Comment by andyyou** [comment]
I got a strange thing that my DatePickerIOS work fine but console still show me warning

**Comment by christopherdro** [comment]
Closing this. Will be tracked here #4547

**Comment by Kitloo** [comment]
So the solution is????
