### ISSUE TITLE
update react-native to 0.59, build error

### ISSUE THREAD

**Issue by linmiss** [facebook/react-native#23972]
## 🐛 Bug Report

'React/RCTFileReaderModule.h' file not found(RCTBlob)
## To Reproduce

use xcode build
## Environment

React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 527.59 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.0.0 - ~/.nvm/versions/node/v10.0.0/bin/node
      Yarn: 1.13.0 - ~/.nvm/versions/node/v10.0.0/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.0.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 28
        Build Tools: 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.4 => 16.8.4 
      react-native: ^0.59.0 => 0.59.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
xcode: 10.1 (10B61)

**Comment by linmiss** [comment]
@react-native-bot Thanks

**Comment by ferrannp** [comment]
Hello there 👋 this issue seems to be related to your experience upgrading between versions. We know this has been a [long lasting pain for the community](https://github.com/react-native-community/discussions-and-proposals/issues/68) so starting v0.59 we have introduced a new flow via the [new CLI](https://facebook.github.io/react-native/blog/#cli-improvements).

To upgrade to that version, you may still need to do some manual steps – we suggest you use [rn-diff-repo](https://github.com/pvinis/rn-diff-purge) to accomplish this.

Given that this is not strictly a bug with the library itself I'll close this, but if someone can create a repro that has this issue with a freshly created `react-native init` project we can reopen it and discuss it further 🤗
