### ISSUE TITLE
react-native-image-crop-picker

### ISSUE THREAD

**Issue by Akdcpa** [facebook/react-native#23975]
export default class App extends Component<{}>{

  Camera = () => {
    ImagePicker.openCamera({
      mediaType: 'video',
    }).then(image => {
      console.log(image);
    });
   }
 render() {
    return ( <Button
                onPress={ this.Camera } 
                title={"Go Back"}
                style={styles.buttons}  />
     );
![Screenshot_20190316-172908](https://user-images.githubusercontent.com/41290930/54474973-b92eb280-4811-11e9-93d5-ee32b220713b.png)

  }
}

**Comment by patrickkempff** [comment]
@Akdcpa thank you for reaching out. I am closing this issue because it does not follow the issue template. 

If you think the issue is a bug or regression in the core React Native library, please feel free to file a new issue and follow the template. Make sure to include steps to reproduce the behavior. Thank you!
