### ISSUE TITLE
Duplicate decleration App 

### ISSUE THREAD

**Issue by avi2108** [facebook/react-native#23976]
## 🐛 Bug Report

Getting error "duplicate declaration App" in react-native/scripts/index.js while building android app . Tried creating project with 0.59.1 and also tried with 0.58.4 react-native versions but no luck.

Attaching the screen shot of error.
![Screenshot_1552739463](https://user-images.githubusercontent.com/6064489/54475333-0b71d280-4816-11e9-9d2a-a73544ed3873.png)

[](url)
## Environment

info
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
      Memory: 5.68 GB / 15.66 GB
    Binaries:
      Node: 10.15.1 - C:\nodeJs\node.EXE
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.7.0 - C:\nodeJs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5199772

**Comment by avi2108** [comment]
updated issue with  environment info @react-native-bot

**Comment by avi2108** [comment]
Please suggest me how to resolve this. am stuck due to this.

**Comment by Titozzz** [comment]
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗
