### ISSUE TITLE
React Native ScrollView Crushes on Android Apk

### ISSUE THREAD

**Issue by Ahmed-Imam** [facebook/react-native#23974]
My App is working fine in debug mode but on released apk it crushes, the app launches fine and I can navigate to all the pages where there is no scrollview in it but when ever I try to scroll or press any view inside the scrollview it crushes, I tried removing the scrollview and everything works fine. my codes is as follow:

```
<SafeAreaView style={{flex:1}}>
  <ScrollView>
      <SomeComponents/>
  </ScrollView>
</SafeAreaView>
```

**Comment by patrickkempff** [comment]
@Ahmed-Imam thank you for reaching out. I am closing this issue because it does not follow the issue template.

If you think the issue is a bug or regression in the core React Native library, please feel free to file a new issue and follow the template. Make sure to include steps to reproduce the behavior. Thank you!
