### ISSUE TITLE
ScrollView Text bug

### ISSUE THREAD

**Issue by ydostyle** [facebook/react-native#24047]
Insert a long text in the scrollview will  page blank. a scroll bar appears but don't show the words.
The attachment is the text content.
bug in rn0.58
[](![image](https://user-images.githubusercontent.com/22721444/54655608-86c8d200-4afd-11e9-8fc8-e490eae4ba65.png))
[a.txt](https://github.com/facebook/react-native/files/2986349/a.txt)

**Comment by bartolkaruza** [comment]
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗
