### ISSUE TITLE
Array[...rest] in Signed apk

### ISSUE THREAD

**Issue by Tesse-rato** [facebook/react-native#24072]
> react: 16.6.3

> react-native: "0.58.5

https://ibb.co/Vtmb6Tv

The bug appears only in the signed apk, with no exception of error, it just does not work, execution stops and the application does not break

`function func(arg){
  let array = [...arg]; 
}`

**Comment by Salakar** [comment]
Hey @Tesse-rato 👋 thanks for the report

Please could you provide more information here? I'm not sure here what you mean by it does not work; can you please provide a full code example of expected behaviour vs actual behaviour. Thanks

I'll close this issue for now but happy to re-open this should you be able to update it with more information (let me know).

**Comment by Tesse-rato** [comment]
ok i try, sorry about english

**Comment by Tesse-rato** [comment]
Hey
