### ISSUE TITLE
[ScrollView] Shouldn't become responder if scrollEnabled is false

### ISSUE THREAD

**Issue by hayeah** [facebook/react-native#2411]
I am doing a sortable list proof-of-concept with ReactNative. One of the effects I want to achieve is to auto-scroll a long list if the dragged item is near the bottom (or top) of the screen. Like so:

![sortable-list-native-demo](https://cloud.githubusercontent.com/assets/50120/9426483/74b517e4-4977-11e5-8287-1f6d3c7882a4.gif)

To prevent scroll view from scrolling while an item is dragged, I set ScrollView's "scrollEnabled" prop to false, which seems to do the trick. The only problem is if I use the `scrollTo` method to programmatically scroll, the scrollView mistakenly thinks a user-initiated scroll event occurred, and tries to steal the responder status.

The chain of events is illustrated by these diagrams:

![scrollview-responder-stealing](https://cloud.githubusercontent.com/assets/50120/9426493/a219fc30-4978-11e5-966f-65512ded7e9d.jpg)

The way to fix this problem is to check whether scrollEnabled is false in [scrollResponderHandleScrollShouldSetResponder](https://github.com/facebook/react-native/blob/4b420cc0956e21f9e9623e460bde42e12d2ddccf/Libraries/Components/ScrollResponder.js#L137).

**Comment by ide** [comment]
cc @jordwalke @spicyj

**Comment by hayeah** [comment]
PR upcoming... not sure if this fix would cause other problems

**Comment by chirag04** [comment]
@hayeah awesome demo! I was looking for a solution like this. Is the code open sourced for the sortable list?

**Comment by hayeah** [comment]
@chirag04 coming soon. Writing the README

**Comment by hayeah** [comment]
@chirag04 See [react-native-SortableList](https://github.com/hayeah/react-native-SortableList)

**Comment by chirag04** [comment]
:+1:

**Comment by iostalk** [comment]
@vjeux @brentvatne @ide @spicyj 
Awesome demo! I was looking for a solution like this, do you have a solution for this situation now?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/scrollview-shouldnt-become-responder-if-scrollenabled-is-false

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
