### ISSUE TITLE
Scroll View Percentage Problem

### ISSUE THREAD

**Issue by RichyNs** [facebook/react-native#24146]
I have a parent component which is a scrollView inside of it the children component are all percentage, the scroll is not working, is it cause of the percentage? Can we use ScrollView with percentage?

**Comment by JKCooper2** [comment]
Reason is because percentages are based on the parent container, and in a ScrollView you have the actual container (size of the view port), and then a contentContainer inside (size of all elements) inside that.

You can make it work like this: https://snack.expo.io/@jkcooper/rn24146---scrollview-percentage, but if you want to use things like scrollTo, it's a lot easier just using fixed heights for elements.
