### ISSUE TITLE
iOS and Android not woking on run

### ISSUE THREAD

**Issue by akhilsanker** [facebook/react-native#24227]
## 🐛 Bug Report

After upgrading react-native form 0.57.8 to 0.59.2, both run android and ios are not working.
Getting 'linker command failed with exit code 1 (use -v to see invocation)' error while running the app via Xcode(10.1) and unable to run ios command through terminal.

## To Reproduce
1. Upgraded react-native npm from 0.57.8 to 0.59.2
2. react-native run-ios not working with terminal.
3. Try to run app through Xcode.
4. Run fails with the error : 'linker command failed with exit code 1 (use -v to see invocation)'

## Expected Behavior

To run the application in the simulator, like verison 0.57.8

## Environment
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: ^0.59.2 => 0.59.2 

    npmGlobalPackages:
      react-native-cli: 2.0.1

    Binaries:
      Node: 8.9.1 - /usr/local/bin/node
      Yarn: 1.5.1 - /usr/local/bin/yarn
      npm: 5.5.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman

    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild

**Comment by kelset** [comment]
Hello there 👋 this issue seems to be related to your experience upgrading between versions. We know this has been a [long lasting pain for the community](https://github.com/react-native-community/discussions-and-proposals/issues/68) so starting v0.59 we have introduced a new flow via the [new CLI](https://facebook.github.io/react-native/blog/#cli-improvements).

To upgrade to that version, you may still need to do some manual steps – we suggest you use [rn-diff-repo](https://github.com/pvinis/rn-diff-purge) to accomplish this.

Given that this is not strictly a bug with the library itself I'll close this, but if someone can create a repro that has this issue with a freshly created `react-native init` project we can reopen it and discuss it further 🤗


Also, when the error is "linker command failed with exit code 1" the actual error is a different one. Probably you didn't add the new JSI lib required? Check the changelog for details!

**Comment by akhilsanker** [comment]
Hi @kelset,

Thanks for the reply.
But in react-native 0.57.8, there is no such 'linker command failed with exit code 1 (use -v to see invocation)' error while run-ios.
Do you have any other workaround for this error ?

Thanks
