### ISSUE TITLE
[ListView] Repeatable crash in ListView w/ Section Headers

### ISSUE THREAD

**Issue by studio-dude** [facebook/react-native#2422]
I've been plagued by a problem where a large ListView crashes. The bug may be similar to https://github.com/facebook/react-native/issues/2173. but I've managed to create a [repeatable version on React Playground](https://rnplay.org/apps/AEKwrw). To experience the crash, just keep scrolling down. 

I found the dataset could not be made of sections of equal length (like what you'll find in the ListView Examples).

Appears to still be present in 0.10.0-rc.

Here's the error:

![img_4249](https://cloud.githubusercontent.com/assets/11240184/9433001/b955ce98-49e0-11e5-9648-9fbc0329a2c9.PNG)

**Comment by brentvatne** [comment]
@ide - any ideas?

**Comment by ide** [comment]
Seems like this could be a race condition. Here's a guess without having read the code: the props are applied to the RCTScrollViewManager non-atomically. If the sticky header indices were set before the children and the native UIScrollView kept scrolling needed to render the next sticky header, it could try to render a sticky header whose index is in the sticky-header-index set but whose view is not yet in the RCTScrollView's children. If this is the case, the quick fix could be to silently ignore this error if sticky header index >= number of children. The better fix (which would solve some problems with RCTImage) would be for RN to set native properties atomically.

cc @sahrens

**Comment by sahrens** [comment]
I'm not sure "non-atomic" is quite the right characterization, but there
might be a chance for the layout computation of the children on the shadow
thread to get behind the simple property update of the header indices, but
I'm pretty sure the actual view creation will always happen in the same
UIBatch as the header indices though, even if the layout isn't fully up to
date so I still wouldn't expect it to crash because of this...

**Comment by jerolimov** [comment]
I had a similar issue and finally find that my `renderSeparator` method wasn't implemented (returns null) but defined in the ListView.

In my case this was the reason why the ScrollView `stickyHeaderIndices` was not defined correctly by the ListView. Maybe you can check this in your code or test my really simple fix in PR #5800.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/listview-repeatable-crash-in-listview-w-section-headers

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
