### ISSUE TITLE
[Image] EXC_BAD_ACCESS in [RCTImageDownloader _downloadDataForURL:progressBlock:block:

### ISSUE THREAD

**Issue by walkaboutlanguages** [facebook/react-native#2437]
Scene with a horizontal ListView, containing photos occasionally produces this error.  
#2	0x0000000109141259 in __62-[RCTImageDownloader _downloadDataForURL:progressBlock:block:]_block_invoke27 at /path/to/project/node_modules/react-native/Libraries/Image/RCTImageDownloader.m:107

Xcode screenshot attached for reference.

![screen-shot-2015-08-25-at-2 23 32-pm](https://cloud.githubusercontent.com/assets/10919/9480135/320061ea-4b36-11e5-9626-7b80c5532a3a.jpg)

**Comment by feichngr** [comment]
I'm currently hitting this a lot with fast(-ish) changing GIFs loaded from asset bundles.
Especially iPhone 5s on iOS 9.1 (both simulated and real devices) seems prone to this.
I created a small project which reproduces this problem every time in a matter of seconds
[https://github.com/feichngr/react-native-2437](https://github.com/feichngr/react-native-2437]

**Comment by nicklockwood** [comment]
That's very helpful, thanks! We've seen this reported a couple of times but I've had real trouble trying to reproduce it.

**Comment by nicklockwood** [comment]
It looks like this is basically being caused by an OOM (Out Of Memory) happening inside the imageDecoder. The exact location of the error varies, but disabling the GIF decoder fixes it.

Our GIF decoder is very memory intensive because it decodes all of the image frames immediately instead of one-by-one as they play. This is better for performance, but worse for memory usage, and it can be disastrous for very large GIFs.

This example is super-helpful though, because it taxes the GIF decoder much more than any of our existing tests. I'll see what I can do to improve its memory performance.

**Comment by feichngr** [comment]
Thank you for looking into this so quickly.

I played around a bit more and I might be wrong (I'm not an iOS or ObjC programmer) but to me it looks 
more like use-after-free or race condition or something similar, rather than OOM.

It sometimes fails even on an iPad Pro simulator - which should have plenty of RAM - after only cycling through 5-10 GIFs and Xcode only showing ~90 MB of memory usage.

I don't know if improving efficiency would alleviate this problem.

**Comment by feichngr** [comment]
I'm sorry, but I'm very confident by now that this is caused by a race condition in which RCTImageLoader is deallocated before or while decodeImageData is called.
I updated my test project with a very simple case in which EXC_BAD_ACCESS is thrown most of the time (I was only able to try it on Xcode simulators, old emulated devices work best) and total size of all decoded frames should be less than 100 MB.

Maybe this is already fixed with the changes you made to RCTImageLoader recently?

**Comment by nicklockwood** [comment]
RCTImageLoader is a bridge module whose lifetime is tied to the bridge - the only way it would be deallocated is if you Cmd-R to refresh, or kill the app.

It's possible that there is more than one bug at work here, but I ran your example against the latest codebase and still saw it crash in the same place shown in the original issue, as well as other places like the decoding step.

**Comment by nicklockwood** [comment]
Well, you were right - it wasn't an OOM. I was accessing NSURLCache from two different threads. For some reason it was worse when decoding more image frames, but it would eventually crash even for individual images if you left it running long enough.

The good news is, it's fixed: https://github.com/facebook/react-native/commit/0fe074acbd460fc34aa8f43e51d30ed7e149cebb

**Comment by feichngr** [comment]
Great to hear it's fixed. Thank you so much for taking the time. 👍
