### ISSUE TITLE
[tests] UIManager.js mutates NativeModules, failing after jest.resetModules()

### ISSUE THREAD

**Issue by ide** [facebook/react-native#24401]
## 🐛 Bug Report
UIManager.js mutates NativeModules, which is mocked by setup.js. The mutation is done in a way that is not idempotent, causing fields of the UIManager to be undefined on the second run.

In an application, UIManager.js is run just once because all modules are singletons in JS. The exception is when we take over the module system with something like Jest. Calling `jest.resetModules()` clears the module cache, which includes UIManager.js but not setup.js. As a result, the second time UIManager.js is run, it gets an already mutated version of NativeModules.

## To Reproduce
Write a Jest test with two specs loading the UIManager and `jest.resetModules()` in an `afterEach` block.

## Expected Behavior
`jest.resetModules()` should not cause RN tests to fail.

## Code Example
```js
afterEach(() => {
  jest.resetModules();
});

it(`a`, () => {
  require('react-native').findNodeHandle;
});

it(`b`, () => {
  require('react-native').findNodeHandle;
});
```

## Environment
This is with RN 0.59.3.

**Comment by kelset** [comment]
Hello there 👋 this issue seems to have been inactive for the past few years. Because of this, it's likely that the issue is not a high priority anymore or it has been solved by OP; for these reasons, we'll close it.

But please, if it's actually still an issue with latest (RN64 at the time of writing) please comment below and we can reopen it or please send a Pull Request with a fix 😊
