### ISSUE TITLE
[NavigatorIOS] integration with navigator in existing native app

### ISSUE THREAD

**Issue by axelg12** [facebook/react-native#2442]
I been integrating React Native into my exiting application and everything has been going well. 
By far my biggest problem is combining the exiting Obj-c navigator with React-Native NavigatorIOS.  

Is there any way to combine the two, allowing people to navigate from the Obj-C part of the application to the new React-Native part and then back? Something like initializing the NavigatorIOS with routes from the Obj-C part.

Hope this makes a little sense

Regards

**Comment by ssssssssssss** [comment]
You may find the NavigatorIOS's backing viewcontroller and use it in your native code.

**Comment by axelg12** [comment]
Hmm I don't quite understand. Can you give some more details ?

**Comment by brentvatne** [comment]
@axelg12 - you'll have a hard time getting support for NavigatorIOS because most React Native developers only use the Navigator component [(read about the differences here)](https://facebook.github.io/react-native/docs/navigator-comparison.html#content). @ssssssssssss suggestion seems to be on track, but I'm not sure that I'd recommend using this, it seems like a potentially brittle solution - I think you're better off just using a native obj-c navigator and rendering React Native views in the different routes.

**Comment by ssssssssssss** [comment]
···
- (RCTRootView *)sceneReactNavigator {
    UIView *parent = (UIView *)self.reactSuperview;
    while(parent != nil) {
        if([parent.nextResponder isKindOfClass:[UINavigationController class]]) {
            return (RCTRootView *)parent.nextResponder;
        }
        parent = (UIView *)parent.reactSuperview;
    }
    return nil;
}
···
Find the this view's backing navigation controller.

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/navigatorios-integration-with-navigator-in-existing-native-app
