### ISSUE TITLE
'folly/fbstring.h' file not found inside react-native/ReactCommon/better/string.h 

### ISSUE THREAD

**Issue by GriffithBeliever** [facebook/react-native#24514]
## 🐛 Bug Report
I am trying to compile an ios project to which I upgraded react-native to 0.59,
I am getting an error 'folly/fbstring.h' file not found inside react-native/ReactCommon/better/string.h 

## To Reproduce
I am running my code on:
 react-native: 0.59
xcode 10.2

## Expected Behavior
Build Succeeding

## Code Example
Podfile: 
`
platform :ios, '9.0'

def production_pods
    use_frameworks!
    source 'https://github.com/CocoaPods/Specs.git'

    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'React', subspecs: [
    'Core',
    'CxxBridge',
    'RCTActionSheet',
    'RCTCameraRoll',
    'RCTGeolocation',
    'RCTImage',
    'RCTNetwork',
    'RCTPushNotification',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'RCTLinkingIOS',
    'DevSupport',
    ], path: '../node_modules/react-native'

    # Add new pods below this line
    pod 'Firebase/Core', '~> 5.15.0'
    pod 'FirebaseCore'

    # Crashlytics
    pod 'Fabric'
    pod 'Crashlytics'

    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'GooglePlacePicker'

    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
end
`

for the package.json i have react-native 0.59.3 installed and react 16.6.3

## Environment
`info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
      Memory: 537.93 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 9.3.0 - /usr/local/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 6.1.0 - /usr/local/bin/npm
      Watchman: 4.9.1 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.2, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.0, 28.0.0
        System Images: android-25 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom
    IDEs:
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.6.3 => 16.6.3 
      react-native: ^0.59.0 => 0.59.3 
    npmGlobalPackages:
      react-native-background-timer: 2.1.1
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7`

**Comment by kelset** [comment]
Hello there 👋 this issue seems to be related to your experience upgrading between versions. We know this has been a [long lasting pain for the community](https://github.com/react-native-community/discussions-and-proposals/issues/68) so starting v0.59 we have introduced a new flow via the [new CLI](https://facebook.github.io/react-native/blog/#cli-improvements).

I'd suggest you use [rn-diff-repo](https://github.com/pvinis/rn-diff-purge) to double check that you did all the necessary steps/changes while upgrading.

Given that this is not strictly a bug with the library itself I'll close this, but if you can create a repro that has this issue with a freshly created `react-native init` project we can reopen it and investigate it further 🤗

**Comment by Nordzisko** [comment]
@GriffithBeliever Did you manage to resolve this issue ?
