### ISSUE TITLE
No audio on iphone but have on the ios simulator

### ISSUE THREAD

**Issue by LazzySloth** [facebook/react-native#24525]
I'm using Consruct 2 to make ahtml5 game and uses react native webview to run the game on iOS. The game's audio works perfectly on the iOS simulator but it's not working when running on an iphone. It was working fine a few weeks ago but suddenly fail after I update my iphone to iOS12.2.

**Comment by kelset** [comment]
Hello there 👋 this issue seems to be related to react-native-webview, so please open an issue on the dedicated repo: https://github.com/react-native-community/react-native-webview

Also, without a repro it will be really hard for them to help you, so please consider creating one when posting the issue there.
