### ISSUE TITLE
Modal / Alert don't block UI immediately

### ISSUE THREAD

**Issue by vnakidailo** [facebook/react-native#24528]
## 🐛 Bug Report
There is a small, really tiny timeframe window before Modal & Alert elements block user input (at least on android).
So it is possible to press a button twice (which, for example, shows Modal / Alert), or press any other element, while Modal / Alert is firing up.
Tested on emulator & android device.

I am new to react native, so maybe I'm just missing something.

## To Reproduce
Run the repro project below; press either button multiple times with almost no delay between presses (much easier to do on a slow running emulator; on a device i need to try several times before I can repro it)

## Expected Behavior
User must no be able to interact with UI after either Modal or Alert have been called to show up.

## Code Example
https://github.com/vnakidailo/spikes-modalalertnonblockrep

## Environment
info 
  React Native Environment Info:
    System:
      OS: macOS Sierra 10.12.6
      CPU: (8) x64 Intel(R) Core(TM) i7-2675QM CPU @ 2.20GHz
      Memory: 2.22 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 28, 9
        Build Tools: 21.1.2, 22.0.1, 23.0.1, 23.0.2, 23.0.3, 24.0.1, 24.0.3, 25.0.0, 25.0.3, 28.0.3
        System Images: android-23 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.6 => 16.8.6 
      react-native: 0.59.6 => 0.59.6 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by JKCooper2** [comment]
This is due to react updates/re-renders being asynchronous. If you need to block UI after the first press you can use a non-state based variable (e.g. this.allowButtonPress = true/false) to look after whether the button should update the state (and have the onPress check this value to see whether it fires)

When you press on the button set it from true to false (will be synchronous, but won't cause a re-render), and let your other state updates to trigger the modal to display. Just make sure to set it back to allow button presses once they close the modal.

**Comment by vnakidailo** [comment]
> This is due to react updates/re-renders being asynchronous. 

I have tested with
`
    <Button
      disabled={this.state.buttonPressedTimes > 0}
      onPress={() => {
        this.setState(state => ({buttonPressedTimes: state.buttonPressedTimes + 1}))
      }}
    />
`
And it only allows pressing the button once, while Modal / Alert allow pressing button multiple times until they block. I'd think it's a separate issue.

> If you need to block UI after the first press you can use a non-state based variable (e.g. this.allowButtonPress = true/false)
While this fixes multiple presses issue, it also forces me to implement this behaviour for any other buttons in form, form's inputs, and even for a navigator 'back' button (including disabling hardware 'back' button).

**Comment by JKCooper2** [comment]
You can't use a state update to block a state update because the issue is it's asynchronous in the first place...

Create a variable inside your constructor just called `this.allowButtonPress = true`, and then in your Button do:
```
// This will probably need to be a class function to work properly
onPress = () =>  {
        if (!this.allowButtonPress) return;
        this.allowButtonPress = false;
        ...regular button logic
}

render() {
    return ( 
      <Button
        onPress={this.onPress}
      />
    )
}
```

**Comment by JKCooper2** [comment]
Although tbh it's probably easier you just use a library like lodash's debounce functionality: https://lodash.com/docs/4.17.11#debounce

**Comment by vnakidailo** [comment]
So, it is working as intended?
Just another detail: when using Alert, the hardware 'back' button blocks immediately, but the react navigation 'back' button doesn't. So it is possible to show an alert and go back from screen with alert presented (but only by the React's soft button).

**Comment by JKCooper2** [comment]
Hmm... I believe neither Alert nor Modal should be treated as synchronous blockers as I think they rely on Reacts render cycle to display/cause their effects.

When the Alert is called, because it is a function call it may fire some synchronous behaviour (like blocking the hardware back button) before it renders. It would only be expected for the alert to know about device specific blocking, so if you did want to block react-navigation you would need to wrap your own alert calling function that did that.

Apologies if this doesn't help what you are trying to achieve
