### ISSUE TITLE
Discussion: Flex padding issue

### ISSUE THREAD

**Issue by hanbitkim** [facebook/react-native#24521]
For example, screen width = 300, two views with flex: 1
in this case, each view occupy 150 width
but, if the paddingLeft or paddingRight is added to style in only one view
widths are not same. 
It seems that flex calculated except for the padding.
is it right?

**Comment by JKCooper2** [comment]
Yes. Flex is about how the unused space is distributed. If you have two images with width 100px within a container of 300px, and both have flex one, then there is 100px left that's split between each image.

If you add a padding to one of the images of 10px, then the unused px is now 90px (300px original -100px for the first image, 110px for the second image + the 10px padding).
The remaning 90px is then split 45px each because they have flex one, and so it looks like the one with the padding is getting more.

One solution is to apply a fixed width to each item that is the item width + padding, but only apply padding on the second.

In any case, this isn't a react native issue, and is better asked as a question on somewhere like https://www.reactiflux.com/ on need-help or styling channels.
