### ISSUE TITLE
When I click on my ReactNative for a quick switch on the current page, my ReactNative version is 0.50.4 and the program crashes with the error message:

### ISSUE THREAD

**Issue by ColdBlooded-Fan** [facebook/react-native#24613]
com.complexenforclaelaw E/unknown:ReactNative: Exception in native call
com.facebook.react.uimanager.IllegalViewOperationException: Trying to set local data for view with unknown tag: 340### ###

**Comment by ColdBlooded-Fan** [comment]
someone can help me

**Comment by olajidenewton** [comment]
update your react

**Comment by jaysbytes** [comment]
Can you please provide more info about your environment, react-native version and some code for reproduction? Btw this kind of issues should be posted on stack overflow rather than in a GitHub issue.

**Comment by michalchudziak** [comment]
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗
