### ISSUE TITLE
react-native run-ios getting stuck at 'Loading dependency graph, done'

### ISSUE THREAD

**Issue by vikalpjain** [facebook/react-native#24657]
## 🐛 Bug Report
For my react-native project, which was working fine till 2 days back, react-native run-ios command started getting stuck at 'Loading dependency graph, done'. After trying various things without success, I deleted the project and created a brand new project following instructions at https://facebook.github.io/react-native/docs/getting-started. I took React Native Cli Quickstart route. Even this brand new project is getting stuck at same place. React-native run-android works fine.
![Screenshot 2019-04-30 at 9 37 57 AM](https://user-images.githubusercontent.com/1462005/56940414-eddd9b80-6b2b-11e9-9084-e2d73955d819.png)

## To Reproduce
Create a brand new ract-native project with react-native init ypm. Then run react-native run-ios. iOS simulator is launched and app is installed. When I click on app icon, it does not move beyond default splash screen.
![Screenshot 2019-04-30 at 9 41 00 AM](https://user-images.githubusercontent.com/1462005/56940463-3eed8f80-6b2c-11e9-99bf-7d850c501663.png)

## Expected Behavior
iOS simulator should launch, app should get installed and run. Simulator is getting launched. App does get installed. But when I click on App icon, Metro Bundler gets stuck at 'Loading dependency graph, done'

## Code Example
I've tried to uninstall and install node using brew. 
Uninstalled and installed Watchman.
Deleted node_modules

## Environment
React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
      Memory: 58.78 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.14.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 26, 28
        Build Tools: 28.0.3
        System Images: android-26 | Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.5 => 0.59.5 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by vedmant** [comment]
I have the same issue, there is no clear hint how to fix it.

**Comment by matt-oakes** [comment]
"Loading dependency graph, done" means that Metro has started successfully. That is not an issue.

The issue seems to be that the app is not making a connection to the Metro bundler to get the JS bundle.

Can you answer a few questions for me:

* How are you starting the iOS app? Through `react-native run-ios` or through Xcode? Does using the other method work correctly?
* If you are running through Xcode, do you have any breakpoints set (check the breakpoints tab in the left panel)? Are any being triggered?
* Have you tried with a different simulator? You can do this through Xcode.
* Have you tried clearing the simulator? You can do this through `Hardware -> Erase all content and settings`.

**Comment by dulmandakh** [comment]
@vikalpjain I suspect that you have circular dependencies and it's causing problems. Please check your code.

**Comment by vikalpjain** [comment]
> "Loading dependency graph, done" means that Metro has started successfully. That is not an issue.
> 
> The issue seems to be that the app is not making a connection to the Metro bundler to get the JS bundle.
> 
> Can you answer a few questions for me:
> 
> * How are you starting the iOS app? Through `react-native run-ios` or through Xcode? Does using the other method work correctly?
> * If you are running through Xcode, do you have any breakpoints set (check the breakpoints tab in the left panel)? Are any being triggered?
> * Have you tried with a different simulator? You can do this through Xcode.
> * Have you tried clearing the simulator? You can do this through `Hardware -> Erase all content and settings`.

I'm starting it using react-native run-ios. Will try from XCode also and update.

**Comment by GreenRidingHood** [comment]
@vikalpjain yes, pls update, i know probably dependencies related, because i dont have any problem in my other project (xcode10 and last version of RN). I dont see any error in both way if i run my app (from terminal and from xcode). And without error very frustrating, even cmd+d not working for debugging :( . I created this project from new RN project, after many attempt to run my project on new xcode.

**Comment by GreenRidingHood** [comment]
@vikalpjain i found a clue at apple forum, simulator can be problem, try running USB connected device. I am trying, i will update

**Comment by vikalpjain** [comment]
Sure. I'm still stuck. Tried building and running it from XCode but that
also is stuck.

**Comment by GreenRidingHood** [comment]
@vikalpjain maybe not issue for you but i was seeing xcode console these #24023 issues, 
and that comment https://github.com/facebook/react-native/issues/24023#issuecomment-474608280  helped me, yes i am still stuck on metro-bundler but at least i am seeing different error on device

**Comment by GokulDharumar** [comment]
i have the same issue... it get stuck with loading dependency graph when i run react-native run-ios. But works when i run from xcode
