### ISSUE TITLE
Wrap view around its content

### ISSUE THREAD

**Issue by aksonov** [facebook/react-native#2465]
How to wrap view around its content? I want to make View black border and backgroundColor around children text, but no luck. 
```
'use strict';
var React = require('react-native');
var {Text, View} = React;
var Generated = React.createClass({
    render(){
        return (
            <View>
                <View style={{position:'absolute', top: 50, left: 50, borderWidth:2,backgroundColor:'red'}} onLayout={(evt)=>console.log(evt.nativeEvent.layout)}>
                    <Text style={{position:'absolute',top:100,left:100}}>Hello world</Text>
                    <Text style={{position:'absolute',top:150,left:150}}>Hello world</Text>
                    <Text style={{position:'absolute',top:200,left:200}}>Hello world</Text>
                </View>
            </View>
        );
    }
});
module.exports = Generated;
```
![ios simulator screen shot 27 2015 18 24 55](https://cloud.githubusercontent.com/assets/1321329/9526326/f77b2c30-4ce8-11e5-9d68-274b30706b51.png)

**Comment by brentvatne** [comment]
This is just like regular css, the problem is that you absolute position the items inside of that container, so it's not factored into layout in the same way. If you are going to absolute position the children then you need to give it a width/height. This kind of question is better suited for StackOverflow or IRC :) Good luck!
