### ISSUE TITLE
Cannot set property popable of undefined

### ISSUE THREAD

**Issue by svipas** [facebook/react-native#24699]
## 🐛 Bug Report

![image](https://user-images.githubusercontent.com/10441177/57124441-8410fc00-6d8e-11e9-8389-b107181beb07.png)

## To Reproduce

I don't know to reproduce it, but we are using this code:

```ts
const task: PromiseTask = {
    name: 'active_worker_task',
    gen: fn
};

const interactionTask = () => this._interactionManager.runAfterInteractions(task).then();
```

What is really weird it happens unexpectedly, so I don't know how to reproduce it. We are using this type of code to perform some tasks to allow smooth animations since it runs after animations.

## Expected Behavior

To not throw this type of error when using `runAfterInteractions`.

## Environment

```
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 445.96 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /usr/local/opt/node@10/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/opt/node@10/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.4 => 0.59.4
```

**Comment by kelset** [comment]
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Also, surely this doesn't make things simple to debug either:

> What is really weird it happens unexpectedly, so I don't know how to reproduce it.

😓

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗
