### ISSUE TITLE
Discussion: Appium support for webdriverio react$ and react$$

### ISSUE THREAD

**Issue by simonDominos** [facebook/react-native#24774]
We're currently looking to utilise the new WebdriverIO react$ and react$$ commands which target the React/ReactNative JSX through Appium. I initially posted the enhancement on the Appium Git page [here](https://github.com/appium/appium/issues/12600)

However it looks like we Appium would need an enhancement from React Native and there are suggestions in the above link that if we could build some sort of driver that would allow Appium to target the React/React Native JSX.

I believe this enhancement would be a great feature (if possible). Thoughts?

**Comment by Junting-Liu** [comment]
I am using appium  and webdriverio  to develop the e2e test for the react native app. When finding elements, i need to write different code for android and ios. I think it would be very convenient if i can find element by using the method like react$ or react$$.

By the way, Does anyone know why react-native-master test ios by detox， but  test  android by appium？

**Comment by christian-bromann** [comment]
As the maintainer of WebdriverIO I would like to give a bit more context: the `react$` and `react$$` are commands that run JavaScript in a web context (browser on desktop or mobile devices) in which the React application is running. They use the [`resq`](https://www.npmjs.com/package/resq) library that was particularly developed for this use case. I am not entirely sure what this can look like for the native context especially since we can't run arbitrary JavaScript in there.
