### ISSUE TITLE
Bundle Error

### ISSUE THREAD

**Issue by jonas-weimar** [facebook/react-native#24804]
So my build succeeded but my metro bundler throws this error:
![Bildschirmfoto 2019-05-10 um 17 15 17](https://user-images.githubusercontent.com/38507420/57537810-5526f700-7347-11e9-85f3-2b84e36b42c6.png)
I do not know why this happens. But my last step was to include the react-native-linear-gradient package as told in their docs.

React Native version:
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (4) x64 Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz
      Memory: 275.65 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.6.0 - /usr/local/bin/node
      Yarn: 1.5.1 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.6 => 16.8.6 
      react-native: ^0.59.7 => 0.59.7 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1

**Comment by kelset** [comment]
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Also, you seem to suggest that maybe something went wrong when you added the linear-gradient - and metro is saying that it can't file a podgenerated file. Maybe something went wrong when you installed the library?

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗
