### ISSUE TITLE
APP very caton when use 4G. 

### ISSUE THREAD

**Issue by CocoaZX** [facebook/react-native#24816]
APP very caton when use 4G.
Like navigation push animation will take more 10 seconds.
But it's ok when use wifi.

React Native version:

React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
      Memory: 27.61 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.11.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 26, 27, 28
        Build Tools: 25.0.0, 25.0.2, 25.0.3, 28.0.3
        System Images: android-Q | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.3 => 0.59.3
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

## Steps To Reproduce

1.
2.

 Look like all animation thread block.

**Comment by turnrye** [comment]
Hey @CocoaZX, this is unlikely to be a bug in React Native. Without a lot more detail, it's hard to help here. Please consider adding more details or closing this issue.

**Comment by CocoaZX** [comment]
Well...that's strange. Because every animation is very caton . like view A navigation push view B will take so long , seem like view B network data ahead of time(in componentDidMount) .But when I use debugger to see the sequence of them , they are in normal sequence .
Dose anyone have this problem before?

**Comment by CocoaZX** [comment]
And it's just happen in Android&4G,iOS is good

**Comment by kelset** [comment]
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

That said, this seems to suggest that you do some fetches that are blocking the JS thread when loading the components (maybe you have the server interaction in the constructor?), I suggest you try to debug that.

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗

**Comment by CocoaZX** [comment]
We use react-navigation to do the navigation.Can you try it ?

**Comment by CocoaZX** [comment]
Found this , I connect a Intranet IP with synchronous

**Comment by yoyo0427** [comment]
@CocoaZX 

How did you solve this problem?

**Comment by CocoaZX** [comment]
Yeah,It's my problem
