### ISSUE TITLE
Print: Entry, ":CFBundleIdentifier", Does Not Exist

### ISSUE THREAD

**Issue by craigcosmo** [facebook/react-native#24831]
after the react-native run ios command, I got this bug

```
Installing build/Build/Products/Debug-iphonesimulator/example.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/example.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

React Native version:

Environment:
  OS:  macOS 10.14.2
  Node:  10.15.3
  Yarn:  0.17.10
  npm:  6.4.1
  Watchman:  4.6.0
  Xcode:  Xcode 10.1 Build version 10B61
  Android Studio:  3.3 AI-182.5107.16.33.5314842

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.x => 0.52.3

## Steps To Reproduce

1. clone this repo https://github.com/archriss/react-native-snap-carousel/tree/master/example
2. run react-native run-ios

Describe what you expected to happen:

the demo app run in simulator

Snack, code example, or link to a repository:

 https://github.com/archriss/react-native-snap-carousel/tree/master/example

**Comment by ralph-dev** [comment]
Sometimes you can have old or duplicated pods in your project. This is a snapshot from when i had a problem before and how our company solved it! Let me know if this works and good luck!

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/cheapreats.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
DELETE THIS LINE FROM Podfile: + pod 'react-native-blur', :path => '../node_modules/react-native-blur'

Notice* If the app breaks suddenly make sure none of the packages in package.json is using this symbol "^" since it can cause unexpected errors.

**Comment by hramos** [comment]
@craigcosmo can you update your React Native version? 0.52 is several versions behind (we're at 0.59 right now).
