### ISSUE TITLE
[README] Display a badge showing this week's on-call

### ISSUE THREAD

**Issue by ide** [facebook/react-native#2485]
By badge I mean one of these:

[![npm version](https://badge.fury.io/js/react-native.svg)](http://badge.fury.io/js/react-native)

with the current on-call. cc @vjeux we briefly talked about this

The library lots of people use for badges: https://github.com/badges/shields

**Comment by vjeux** [comment]
:+1: cc @yungsters

**Comment by brentvatne** [comment]
:+1: :boom:

**Comment by fredemmott** [comment]
cc me. Happy to review this or build it if it's not done before I have time.

**Comment by vjeux** [comment]
@fredemmott awesome :) I don't think anyone is working on it

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/readme-display-a-badge-showing-this-weeks-on-call

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is heavily focused working on performance.
