### ISSUE TITLE
[NavigatorIOS] push flicker 0.10.0

### ISSUE THREAD

**Issue by adrian-social-prod** [facebook/react-native#2490]
Since updating from 0.8.0 to 0.10.0 there is now a noticeable white flicker of the current route view when pushing a new route into the navigator.

**Comment by brentvatne** [comment]
Thanks for filing the issue! NavigatorIOS isn't actively maintained by the React Native team because most people use Navigator, so this is a very low priority fix. I'd encourage you to dive in and try to fix it yourself, if you have any issues with that you can ask people in StackOverflow, on Slack, or mention them here on this issue!

**Comment by oblador** [comment]
:disappointed: 

`Navigator` swipe back doesn't feel "native", is often dropping frames for non-trivial views and is not nearly as performant as `NavigatorIOS`. Even RN apps released by Facebook seem to struggle with this since they defer most of the rendering until after the transitions have finished. 

IMHO the RN team should reconsider the decision of dropping `NavigatorIOS` from their responsibilities until a viable option exists. I'm baffled that two of the absolute key components of iOS apps (the other being tableviews) doesn't have official support.

**Comment by brentvatne** [comment]
@oblador - there are two things that will help a lot with this 1) moving Navigator to use `Animated` for all transitions 2) optimizing `Animated` so that it just starts the animation from the JS thread and then the rest happens on the main UI thread. @sahrens could tell you more about that if you're curious.

I agreed this is not ideal but I think right now the tradeoff being made is to invest in building something that is best for the future instead of putting time into something that is not used at Facebook and that will not be so useful in the near future when these animations are more performant. That said, the community outside of Facebook is very large, so if there are a few people interested in making this better you could perhaps create a channel on Reactiflux and work on it together! I'm sure you would agree it does not make a lot of sense for people that will never use it to work on it :)

**Comment by adrian-social-prod** [comment]
The 'Navigator' documentation and examples are very limited and it's hard to get it working. I'm not sure 'Animated' is documented. IOS worked well

**Comment by alvaromb** [comment]
The ``Navigator`` component is not animating when navigating to a view with a quite big form (+30 fields), but once the ``Navigator`` has loaded the form view, it does animate pop and push to other views. Is this the issue you guys are experiencing?

**Comment by adrian-social-prod** [comment]
this about a flicker in NavigatorIOS

**Comment by oblador** [comment]
@adrian-social-prod: sorry for hijacking :-(

**Comment by brentvatne** [comment]
@adrian-social-prod @oblador - I went ahead and created `#navigator-ios` on Reactiflux - http://www.reactiflux.com/ - feel free to join and discuss / collaborate on NavigatorIOS. I encourage anyone reading this that prefers using NavigatorIOS to join the channel!

@ide @vjeux and I have discussed pulled it out into a separate module, but for a variety of reasons which we can discuss further in Slack, we had to postpone this. In particular, if you look into the code that drives NavigatorIOS you'll see that it's littered throughout various parts of react-native, so it would be hard to just pull it out cleanly.

**Comment by sahrens** [comment]
Plus, since we don't use it internally at Facebook, we're pretty quick to accept and merge pull requests if @ide or @brentvatne sign off on it.

**Comment by oblador** [comment]
Commit https://github.com/facebook/react-native/commit/a4ef7abebb01a3f968aae41c84d878b3bc93e025 fixes this issue :+1: :bow:

**Comment by ide** [comment]
Closing this out ^
