### ISSUE TITLE
glog-0.3.5 getting logging.h not found in iOS

### ISSUE THREAD

**Issue by Harsh2402** [facebook/react-native#24990]
When I tried to run the app from Xcode(10.1) then getting the following error.
logging.h not found.

It's working fine while running an app in Android.

      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 
      Node: 8.11.4
      Yarn: 1.16.0
      Xcode: 10.1

**Comment by rainytooo** [comment]
I have solved this problem because the downloaded `glog` and `double-conversion` are corrupted, delete the package under `~/.rncache`, and then download the following files into this directory.

* https://github.com/google/double-conversion/releases
* https://github.com/google/glog/releases

Then recompile, Good luck!

**Comment by ericlewis** [comment]
The advice above is only for versions of RN prior to 58, you can also try removing: `/users/youruserhere/Library/Caches/com.facebook.ReactNativeBuild` or even better, just clearing node_modules and reinstalling. Feel free to reopen this issue if you still have trouble. The issue is indeed usually because of a corrupt install.

**Comment by ajijoyo** [comment]
I have a similar issue `folly-2018.10.22.00/folly/detail/RangeCommon.h:22:10: 'glog/logging.h' file not found` 
```npmPackages:
      react: ^16.8.6 => 16.8.6 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      react-native-cli: 2.0.1

working fine in android but not in iOS

working well when on react-native: 0.55 but I need an update to 64Bit

**Comment by basmaebraheim** [comment]
what version should I start with and it will build correctly?

**Comment by pmatsinopoulos** [comment]
I have the same issue when running `react-native run-ios`.

This is my `react-native info` output.

```
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
      Memory: 2.04 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.17.3 - /usr/local/Cellar/yvm/3.5.0/shim/yarn
      npm: 6.10.0 - ~/.nvm/versions/node/v10.15.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
      Android SDK:
        API Levels: 23, 24, 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.5 => 0.59.5 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

```
I am blocked for many hours now. Can anyone help? Thank you very much in advance.

**Comment by gmondada** [comment]
If `xcode-select -p` prints a path that contains spaces, I get a very similar problem. Check where Xcode.app and remove any space from its folder path.
