### ISSUE TITLE
Paste feature not working on TextInput (Android)

### ISSUE THREAD

**Issue by pramodsharma403** [facebook/react-native#25038]
React Native version: 0.58.6

## Steps To Reproduce

1. Adding TextInput with the bottom bar screen
2. Copy text & try to paste in TextInput which is on screen with Bottom Tab Bar
3. Paste option not showing

Device - MI A1 (9.0)

Describe what you expected to happen:
Paste feature should work.

Snack, code example, or link to a repository:

<TextInput
					style={GLOBAL_STYLE.TextInputStyle}
					placeholder={'Job Title'}
					onChangeText={jobTitle => this.setState({ jobTitle })}
					value={this.state.jobTitle}
				/>

This is text input which on Tab Bar Screen.

"react": "16.6.3",
"react-native": "0.58.6",
"react-navigation": "^3.3.2",

**Comment by Hermanyo** [comment]
Can you do a minimal reproduction of this? With `TextInput` inside the `Bottom Tab Bar` and publish it here? 

If you are using `ScrollView`/`FlatList`, try to add props `removeClippedSubviews={false}`([#18926](https://github.com/facebook/react-native/issues/18926) and [#9958](https://github.com/facebook/react-native/issues/9958))

**Comment by dishantwalia** [comment]
#https://github.com/react-navigation/tabs/issues/135

**Comment by AzizStark** [comment]
removeClippedSubviews={false}

I tried the above solution but its not working.

Someone please find a solution for this issue.

**Comment by AzizStark** [comment]
I was using createMaterialBottomNavigator from react-navigator which caused this issue for me.

I spent to whole night trying to fix this. The problem is the removeClippedSubviews is set as true. After setting it to false the clipboard appeared.
react-navigation uses **react-native-paper** which is also has this setting that prevents the clipboard options  from appearing.

I solved this by setting it to false in four files.

**Path to files:**

1. \\..\node_modules\react-navigation-material-bottom-tabs\node_modules\react-navigation-tabs\src\views\ResourceSavingScene.js

2. \\..\node_modules\react-navigation-tabs\src\views\ResourceSavingScene.js

3. \\..\node_modules\react-navigation-drawer\dist\view\ResourceSavingScene.js

4. \\..\node_modules\react-navigation-material-bottom-tabs\node_modules\react-navigation-tabs\dist\views\ResourceSavingScene.js

5. \\..\node_modules\react-native-paper\src\components\BottomNavigation.js

--

 ```
removeClippedSubviews={
                  // On iOS, set removeClippedSubviews to true only when not focused
                  // This is an workaround for a bug where the clipped view never re-appears
                  Platform.OS === 'ios' ? navigationState.index !== index : true  //<--  set this to false
                }
```

**Comment by PrakashRNale** [comment]
Yes it is working after fixing this one. But how will it work if we clone our repository at other place as node_modules gets created on **npm install**. Also how will it work on deployment as we never push our node modules to github
