### ISSUE TITLE
[Image] RCTImageDownloader should support 3xx requests

### ISSUE THREAD

**Issue by janmonschke** [facebook/react-native#2509]
A fix from `0.9.0` (https://github.com/facebook/react-native/commit/d1a82c4af120c7c8562d8c4774c939bd59a4cd77) makes image requests that return `3xx` responses look like errors. Ideally, the downloader should follow the alternative URLs provided in the HTTP responses.

**Comment by janmonschke** [comment]
Interestingly, when removing the app and starting fresh, the images resolve properly even though they all have a `301` response that links to the current URL. When I start the app for a second time, it does not resolve the images properly. Maybe it has something to do with caching?

**Comment by janmonschke** [comment]
It looks more and more like a caching problem because images requested with `https` load all the time. I guess those are not cached ;)

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/image-rctimagedownloader-should-support-3xx-requests

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is heavily focused working on performance.
