### ISSUE TITLE
undefined is not an object (evaluating \'RCTWebSocketManager.connect\')

### ISSUE THREAD

**Issue by gran33** [facebook/react-native#2513]
Getting red screen with this error:
Error: undefined is not an object (evaluating \'RCTWebSocketManager.connect\')

Using v0.10.0.

See also here:
http://stackoverflow.com/questions/32330988/error-undefined-is-not-an-object-evaluating-rctwebsocketmanager-connect

10x In advance!

**Comment by MattFoley** [comment]
Same thing happened to me recently. As far as I can tell, there has been a change so that when building your JS in dev mode, you have to include the RCTWebSocket library in your native application. I'm not sure if this is also an issue with release builds.

**Comment by brentvatne** [comment]
If you are using Cocoapods you will need to use this in dev mode in order to support Chrome debugging :smile:

**Comment by jhabdas** [comment]
I just hit the `RCTWebSocketManager.connect` issue upgrading [Lumpen Radio](https://github.com/jhabdas/lumpen-radio) to React Native `v0.11.0` (for Node 4.x and Android). I use Cocoapods in my project but nothing needed to change with my pods. What I did to resolve the problem was to re-link the binary with the WebSocket library. In other words, add `libRTCWebSocket.a` to the *Link Binary with Libraries* section of your app target's *Build Phases* under settings. Hope that makes sense.

**Comment by nicotroia** [comment]
I'm still getting this issue, 2 years later :). 

Running react-native 0.45.1

This only happens when running on android, so I'm wondering if there's a way to link the RCTWebSocketManager (or whichever) binary via android? Like somewhere in settings.gradle or build.gradle dependencies?

Thanks for any input!

**Comment by jhabdas** [comment]
@nicotroia did you see my comment directly above yours on how I resolved it? Have you tried that? If not, please try and drop in a constructive feedback so other constructive comments don't get buried. If you have questions, please head to StackOverflow or similar.

**Comment by jhabdas** [comment]
@nicotroia did you have a chance to try [the solution I mentioned](https://github.com/facebook/react-native/issues/2513#issuecomment-141563793) in late '15? If so what were your results?
