### ISSUE TITLE
[Packager] Export packager server as a JS API

### ISSUE THREAD

**Issue by amccloud** [facebook/react-native#2518]
It would be nice to control the packager server with JS. A good example of when this would be needed https://github.com/mjohnston/react-native-webpack-server/blob/master/lib/Server.js#L313-L323

Thoughts?

**Comment by ccheever** [comment]
I think the packager is being split out to be separate from the rest of RN. Just a tangential FYI. 

+1 on this issue. I would like this a lot and it would help make one of my projects more robust.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/packager-export-packager-server-as-a-js-api

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is heavily focused working on performance.
