### ISSUE TITLE
"not implemented" error when upgrading react-native from 0.57.8 to 0.59.8 or 0.59.9

### ISSUE THREAD

**Issue by kaisontan** [facebook/react-native#25187]
Hi, I was upgrading my react-native Android app from v0.57.8 to v0.59.9. However, after upgrading, my app can not start and stuck at the "not implemented" error as shown below:
![Screenshot_20190607-172608_DBOS UAT](https://user-images.githubusercontent.com/41769691/59095123-4a618100-894a-11e9-9119-49ba3d70bd5d.jpg)

I try to downgrade to v0.59.8 but still hit the same error. After an investigation, I found out the issues is properly due to importing, I tried to comment out some import and my app can start. I have cross check all the imports was fine, but have no idea why hit "not implemented" error. 

In addition, since in v0.59.0, there are changes in Metro, where a new file metro.config.js was added for inline requires features as below:
![image](https://user-images.githubusercontent.com/41769691/59095418-06bb4700-894b-11e9-8f4b-984c007fc4e0.png)

I tried to set the inlineRequired to true. My app can start at first, but click on a button will cause "not implemented" error to pop up again.  So, I suspect the error is caused by Importing/Require in the new Metro. I also tried to build production version and it crashed when open. 

 Any idea what is the cause for this issue? Thank you for your help.

React Native version:
![image](https://user-images.githubusercontent.com/41769691/59095722-c3150d00-894b-11e9-90f5-7c8f63a46601.png)

## Steps To Reproduce

1. upgrade to react-native to v0.59.9 from v0.57.8.

Describe what you expected to happen:
1. The app should start normally.

**Comment by kelset** [comment]
Hello there 👋 this issue seems to be related to your experience upgrading between versions. We know this has been a [long lasting pain for the community](https://github.com/react-native-community/discussions-and-proposals/issues/68) so starting v0.59 we have introduced a new flow via the [new CLI](https://facebook.github.io/react-native/blog/#cli-improvements).

I'd suggest you use [rn-diff-repo](https://github.com/pvinis/rn-diff-purge) to double check that you did all the necessary steps/changes while upgrading.

Also, maybe it's just a matter of some cache not being cleaned properly? Try running:

```
rm -rf node_modules;
rm -rf $TMPDIR/react-native-packager-cache-*;
rm -rf $TMPDIR/metro-*;
rm -rf $TMPDIR/react-*;
rm -rf $TMPDIR/haste-*;
watchman watch-del-all;
yarn;
yarn start --reset-cache; (for starting the bundler)
```

Given that this is not strictly a bug with the library itself I'll close this, but if you can create a repro that has this issue with a freshly created `react-native init` project we can reopen it and investigate it further 🤗

**Comment by markowork** [comment]
@kaisontan did you fix this, I have the same issue :/

**Comment by kaisontan** [comment]
Hi, @markowork . Yes, I managed to solved this.

I found out the issues is due to importing of module 'url-search-params' in one of my file. I solved by removing the import, install another package and override global polyfill. 

![image](https://user-images.githubusercontent.com/41769691/59188981-821b3380-8bab-11e9-83bb-1c4a2df49b85.png)

![image](https://user-images.githubusercontent.com/41769691/59189014-9f500200-8bab-11e9-9f41-098138bc223e.png)

You can read more from this post: 
https://github.com/facebook/react-native/issues/23922

Hope this help you.

**Comment by markowork** [comment]
Thank you @kaisontan, it did!
