### ISSUE TITLE
[Border] If width is set through Animated, then borderRadius seems to be ignored

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#2521]

**Comment by dralletje** [comment]
Any idea what it could be? (I looked into the Animated source but just couldn't figure out anything, maybe it has to do with setNativeProps itself?)

**Comment by brentvatne** [comment]
@a2 @nicklockwood - @dralletje expressed interest in trying to fix this so any guidance for him would be great :) if we animate borderRadius at the same time as width it's not a problem, so it seems like it's just an issue when you're using `setNativeProps` to set the width and not re-applying any borderRadius.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/border-if-width-is-set-through-animated-then-borderradius-seems-to-be-ignored

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is heavily focused working on performance.

**Comment by rh389** [comment]
I just encountered something similar (in RN 0.33) when animating `borderColor`. Despite having a fixed `borderRadius: 15`, I was seeing two borders on the same `View`, one square and black and one coloured with a radius. 

I had been setting `borderColor = null` as an instance/member variable of my component class then setting it to an interpolated value (driven by a separate `Animated.Value`) in `componentDidMount`. What fixed the issue for me was making sure the initial, pre-mount value was an actual colour.

(So, I guess this is something to do with the way borders are calculated pre-mount?)
