### ISSUE TITLE
[Packager] "snippet" field in packager errors contains ANSI color codes

### ISSUE THREAD

**Issue by ide** [facebook/react-native#2522]
Ex:
```
"snippet":"\u001b[0m  56 |     \u001b[32m}\u001b[39m\u001b[1m;\u001b[22m\n  57 |     \u001b[36mreturn\u001b[39m \u001b[34m\u001b[1m(\u001b[22m\u001b[39m\n> 58 |       View style\u001b[1m=\u001b[22m\u001b[32m{\u001b[39mstyles\u001b[1m.\u001b[22mcontainer\u001b[32m}\u001b[39m\u001b[1m>\u001b[22m\n     |            ^\n  59 |         \u001b[1m<\u001b[22mScrollView\n  60 |           ref\u001b[1m=\u001b[22m\u001b[31m\"scrollView\"\u001b[39m\n  61 |           contentInset\u001b[1m=\u001b[22m\u001b[32m{\u001b[39mcontentInset\u001b[32m}\u001b[39m\u001b[0m"
```

@amasad are you looking into this or would you take a PR instead?

**Comment by amasad** [comment]
Pretty sure this comes from Babel: https://github.com/facebook/react-native/blob/master/packager/react-packager/src/JSTransformer/index.js#L175
Could be my fault for using undocumented APIs though :P

cc @sebmck

**Comment by sebmck** [comment]
You'll need to add the `highlightCode: false` option to `babel.transform`.

**Comment by browniefed** [comment]
PR here https://github.com/facebook/react-native/pull/2662
Assume it won't be accepted since packager is moving to separate repo

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/packager-snippet-field-in-packager-errors-contains-ansi-color-codes

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is heavily focused working on performance.
