### ISSUE TITLE
[TextInput] Text jumps vertically on focus/blur for some font sizes

### ISSUE THREAD

**Issue by gpbl** [facebook/react-native#2523]
Wherever I use a `<TextInput />`, I get this behavior when focusing/blurring the field:

<img src="https://cloud.githubusercontent.com/assets/120693/9623566/ed74ea9c-5142-11e5-9688-ce801d00aef5.gif" height="100" />

[See this playground app](https://rnplay.org/apps/fyHaFg).

Is there a way to avoid it?

**Comment by ide** [comment]
@sahrens would you happen to know if this is how UIKit behaves? I seem to remember seeing this behavior when using UITextFields (w/o React Native)...

**Comment by gpbl** [comment]
Good catch, it comes out it depends by the font size: i've updated the playground app. For `fontSize <= 15` it does not happen 😓

It is a UIKit behavior. [Here](http://stackoverflow.com/questions/9674566/text-in-uitextfield-moves-up-after-editing-center-while-editing) they point out there are [two methods](http://stackoverflow.com/questions/8535760/uitextfield-textrectforbounds-vs-editingrectforbounds) for setting the `UITextField` bounds, one when editing and one not. Wondering if react-native can help the developer to fix this...

**Comment by ide** [comment]
Want to send a PR?

**Comment by gpbl** [comment]
I can *try* 😅 but first i'd like to discuss the possibile solutions: for example, I'd add a `editingRectBounds` prop (iOS only) to wrap the [native method](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UITextField_Class/index.html#//apple_ref/occ/instm/UITextField/editingRectForBounds:), because the causes of the issues could be different, e.g. custom fonts, sizes.

**Comment by sahrens** [comment]
Yeah, UIKit also has this terrible behavior where pasting large blocks of
text into text views messes up the scroll position. Repros on many apps.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/textinput-text-jumps-vertically-on-focusblur-for-some-font-sizes

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is heavily focused working on performance.
