### ISSUE TITLE
PushNotificationIOS.addEventListener for notification never gets called when the application is in a killed state and the notification is tapped

### ISSUE THREAD

**Issue by nairabhijit** [facebook/react-native#25377]
when the app is in a killed state, I receive notification and I tap on it, PushNotificationIOS.addEventListener for notification is never called. Everything works fine though in app running state. I rechecked my configuration many a times, did implemented many solutions posted by people on github for a similar issue but without progress

**Comment by ecreeth** [comment]
@nairabhijit  You need to provide a little more information, so that the problem can be understood and with it resolve faster. For this you must follow [this](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) guide.  Thanks for reporting this!

See [React Native Info](https://github.com/react-native-community/cli/blob/master/docs/commands.md#info)
