### ISSUE TITLE
Adding *.xcworkspace to gitignore

### ISSUE THREAD

**Issue by SaeedZhiany** [facebook/react-native#25403]
React Native version: 0.60.0 RC2

## Steps To Reproduce

1. react-native init RN060 --version react-native@next
2. go to project directory and open `.gitignore` file

Describe what you expected to happen:
running `pod install` causes a new [PROJECT_NAME].xcworkspace has been created.
already just `project.xcworkspace` has been ignored in `.gitingore` file. I think it's better to replace `project.xcworkspace` with `*.xcworkspace` to ignore pod creation too.

**Comment by kelset** [comment]
👋 there - thanks for raising it.

I looked a bit into it, and it seems that that line in the gitignore was caused by a really old commit that was generating via a yeoman template -> https://github.com/facebook/react-native/commit/f83675d1915b5e77638c117c82f8641cea367ffe

I actually think that you don't want to have the *.xcworkspace to be ignored, but I may be wrong.

Would you mind opening a PR with your solution (https://github.com/facebook/react-native/blob/master/template/_gitignore#L23) this is the file, so that it can be looked into / discussed more?

**Comment by SaeedZhiany** [comment]
@kelset 

I already submit a [PR](https://github.com/facebook/react-native/pull/25404) for it, but it closes by @cpojer and I didn't know what's the exact reason for it.
I raised this issue according to current `gitignore` file. I thought if the `project.xcworkspace` must be ignored, so probably we don't need the new  `[PROJECT_NAME].xcworkspace` file generated by `pod install` command too, because it can be regenerated every time someone creates or clones a react-native project, e.g. we may need to run `pod install` after `npm install`.

What do you think?

**Comment by SaeedZhiany** [comment]
Recently I'm using react-native-firebase in my project and I use pods for [IOS installation steps](https://rnfirebase.io/docs/v5.x.x/installation/ios#Option-1:-Cocoapods-(Recommended)), so it creates a new `.xcworkspace` with my project name and I already have two `.xcworkspace` files. (let assume my project name is `Test`)

- project.xcworkspace

- Test.xcworkspace

From react-native-firebase documentation:
> You need to use the ios/[YOUR APP NAME].xcworkspace instead of the ios/[YOUR APP NAME].xcproj file from now on.

I looked into 0.60.x-RC changelogs and I see that pods will be supported by default in 0.60 version. So I thought maybe it's necessary to ignore all `.xcworkspace` files instead of `project.xcworkspace` file only because of any cases `pod install` creates more than one `.xcworkspace` files like mine.

**Comment by kelset** [comment]
I looked at your PR, and as I mentioned, we should simply remove that line because that file is actually something that you should have in your git history (we are actually taking care of that in another PR, here -> https://github.com/facebook/react-native/pull/25451).

Related to the fact that you have two .xcworkspace, I think that something went wrong with your configuration 🤔 there should be only one.

**Comment by SaeedZhiany** [comment]
> Related to the fact that you have two .xcworkspace, I think that something went wrong with your configuration 🤔 there should be only one.

I have two because I currently using RN0.59.9 and as I mentioned before the second file has been created because of `pod install` command in ios installation steps of react-native-firebase, they already mention on their documentation that there will be two `.xcworkspace` files on my repository after the command.
> You need to use the ios/[YOUR APP NAME].xcworkspace instead of the ios/[YOUR APP NAME].xcproj file from now on.

So, can you approve this? Do I must revert my project's `.gitignore` file to be `project.xcworkspace` and commit the `.xcworkspace` file created by `pod install`? and I wait for 0.60 stable release for a stable solution?

**Comment by SaeedZhiany** [comment]
this is my ios directory after `pod install`

<img width="227" alt="Annotation 2019-07-03 082417" src="https://user-images.githubusercontent.com/13766432/60562453-e2496380-9d6c-11e9-8652-0058d9321c00.png">

Actually, it's my bad, I didn't read the files extension totally :D (I'm sorry). one of them is `.xcworkspace` and the other is `.xcodeproj`, and according to your advice I will remove the `*.xcworkspace` line  (or `project.xcworkspace` from original template) from my `.gitignore` file
> we should simply remove that line because that file is actually something that you should have in your git history

**Comment by kelset** [comment]
No worries 🤗
