### ISSUE TITLE
Number of Lines starts at wrong place

### ISSUE THREAD

**Issue by vikramkh** [facebook/react-native#25434]
When you set NumberOfLines on a text props, the text starts on the last line and not the first. I'm pretty sure this is a bug. Is there any way around this? I tried setting textAlignVertical to top but it didn't work.

**Comment by kelset** [comment]
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗
