### ISSUE TITLE
Crash NoClassDefFoundError: com.facebook.react.TurboReactPackage$ModuleHolderProvider

### ISSUE THREAD

**Issue by allanjsx** [facebook/react-native#25443]
React Native version:
0.59.9

## Steps To Reproduce
I see it only happens on Android 4.4.2, it caused a native crash:
`TurboReactPackage.java, line 75 java.lang.NoClassDefFoundError: com.facebook.react.TurboReactPackage$ModuleHolderProvider`

**Callstack**:
```
    com.facebook.react.TurboReactPackage$1$1.next TurboReactPackage.java:75
    com.facebook.react.TurboReactPackage$1$1.next TurboReactPackage.java:64
    com.facebook.react.NativeModuleRegistryBuilder.processPackage NativeModuleRegistryBuilder.java:45
    com.facebook.react.ReactInstanceManager.processPackage ReactInstanceManager.java:1212
    com.facebook.react.ReactInstanceManager.processPackages ReactInstanceManager.java:1182
    com.facebook.react.ReactInstanceManager.createReactContext ReactInstanceManager.java:1120
    com.facebook.react.ReactInstanceManager.access$900 ReactInstanceManager.java:123
    com.facebook.react.ReactInstanceManager$5.run ReactInstanceManager.java:943
    java.lang.Thread.run Thread.java:841
```

**Comment by kelset** [comment]
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗
