### ISSUE TITLE
[Tests] Move tests to run on iPhone 6 and 64-bit architecture

### ISSUE THREAD

**Issue by ide** [facebook/react-native#2544]
The tests currently run against the old 32-bit armv7 devices and 4" screens (iPhone 5 specifically) -- any reason not to target the most recent devices? especially with the new iPhone coming next week?

**Comment by ide** [comment]
@sahrens is there a reason for the tests to target old devices, or does this task make sense? I can help with this in a couple of weeks if someone else from the community or fb doesn't get around to it.

**Comment by sahrens** [comment]
Really we should run on both, but that will require some rejiggering and recording new reference images for all the snapshot tests.  It also makes it a little more burdensome to change tests that require updating the snapshots, but probably worth it.

While we're only running on one device/config, I think it's better to be on older devices because they get much less organic usage (especially from developers) and bugs are more likely to slip past local testing.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/tests-move-tests-to-run-on-iphone-6-and-64-bit-architecture

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is heavily focused working on performance.
