### ISSUE TITLE
react-native module conflict between android support and androidx [Android]

### ISSUE THREAD

**Issue by NitishAgrawal** [facebook/react-native#25468]
I have multiple modules in my react-native project but I just update react-native version from 0.57.8 to 0.59.9 and after resolving all issue I am facing the issue with android support and androidx library. Most modules are using android support but react-native-video using androidx and it's creating issue but I need to use react-native-video with latest version (4.x). I have tried with many research and try to check with different version of react-native-video but no luck.

Can any one assist me that how can I use both andriodx and android support libraries with different modules simultaneously in a project?
Or any other solution of this issue.

**Comment by bhaskarGyan** [comment]
Can you check you app dependencies with ./gradlew app:dependencies. I faced similar issue in my project due to react-native-device-info since it was using "com.google.android.gms:play-services-gcm:${safeExtGet('googlePlayServicesVersion', '**+**')}" as dependency which was pulling the androidx as its dependencies .

for me the resolution was adding below to app/build.gradle

configurations.all {
    resolutionStrategy.force 'com.google.android.gms:play-services-gcm:16.1.0', 'com.google.android.gms:play-services-basement:15.0.1'
}

**Comment by zlei123456** [comment]
see https://github.com/zlei123456/toAndroidX

I solved this problem in this way, based on online solutions and official documentation.

**Comment by NitishAgrawal** [comment]
I solved by excluding some files from my notification module.
