### ISSUE TITLE
fatal error: 'UIKit/UIUserActivity.h' file not found

### ISSUE THREAD

**Issue by lehang123** [facebook/react-native#25492]
I just follow the step on the fackbook guide and try to run iOS with the awesome project

React Native version:
     react-native-cli: 2.0.1
     react-native: 0.60.0
Xcode version : 
    Version 9.4.1 (9F2000)

when I run react-native run-ios

info In file included from /Users/gonglehan/Desktop/WonderWorld/ProjectN/node_modules/react-native/Libraries/LinkingIOS/RCTLinkingManager.m:8:
/Users/gonglehan/Desktop/WonderWorld/ProjectN/node_modules/react-native/Libraries/LinkingIOS/RCTLinkingManager.h:10:9: fatal error: 'UIKit/UIUserActivity.h' file not found
#import <UIKit/UIUserActivity.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

info 

error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening ProjectN.xcworkspace. Run CLI with --verbose flag for more details.
** BUILD FAILED **

I tried finding this head file from xCode but I found nothing, and when I deleted the #import <UIKit/UIUserActivity.h> from the RCTLinkingManager file. It works fine, however whenever I do another npm install (for example new library or sth). The code come back, and i have to command it again.

**Comment by kelset** [comment]
Can you check if you have pods installed correctly? It seems to me it's the same issue as https://github.com/facebook/react-native/issues/25480

**Comment by lehang123** [comment]
I tried to update the Xcode to 10.2 but it requires a higher macOS version. And for some reason my Mac doesn’t shows me the options to update, I’m currently in macOS 10.13: High Sierra

**Comment by lehang123** [comment]
> Can you check if you have pods installed correctly? It seems to me it's the same issue as #25480
> 
> Also, it seems that you are using an old version of Xcode - can you try and update to 10.2?

Thanks man ! it's like what you said, I updated Xcode to 10.2.1, then it works

**Comment by kelset** [comment]
cool :) thanks for letting me know :)

**Comment by vijaykmittalmu** [comment]
> > Can you check if you have pods installed correctly? It seems to me it's the same issue as #25480
> > Also, it seems that you are using an old version of Xcode - can you try and update to 10.2?
> 
> Thanks man ! it's like what you said, I updated Xcode to 10.2.1, then it works

I was facing above-mentioned issue since last 3-4 days and we can also resolve this issue without update Xcode 10.2.1 because I was facing this issue when I create RN project with 0.60.0 RN version but if I create RN Project with another downgrade version like 0.59.4 then it's started working fine.

command use:  react-native init project_name --version 0.59.4

**Comment by ben-pritchard** [comment]
I was able to resolve this without upgrading my Xcode (thank god, still using 9.3).

The build terminal output showed that there were 3 packages that I had linked manually that I needed to unlink (via: `react-native unlink PACKAGE-NAME`) so that the autolinking could work.

After running that command for the 3 packages I had linked manually, I ran an `npm install` and `react-native run-ios` and everything worked.

**Comment by SeanRenet** [comment]
> I was facing above-mentioned issue since last 3-4 days and we can also resolve this issue without update Xcode 10.2.1 because I was facing this issue when I create RN project with 0.60.0 RN version but if I create RN Project with another downgrade version like 0.59.4 then it's started working fine.
> 
> command use: react-native init project_name --version 0.59.4

OMG This needs to be on the website.  A whole day of googling and this is what worked.  Fixed on the rando errors react was throwing.
.

**Comment by ankur-sardar** [comment]
Have you fixed this issue? Can anyone please tell me a solution for this? In my case, from XCode I can run the app but can not run the app from the command line (`react-native run-ios`)

**Comment by petheameya** [comment]
I am using Xcode 10.3 and I am also facing same issue

**Comment by leitom** [comment]
works for me with: react-native init project_name --version 0.59.4

**Comment by s3vi26** [comment]
> > I was facing above-mentioned issue since last 3-4 days and we can also resolve this issue without update Xcode 10.2.1 because I was facing this issue when I create RN project with 0.60.0 RN version but if I create RN Project with another downgrade version like 0.59.4 then it's started working fine.
> > command use: react-native init project_name --version 0.59.4
> 
> OMG This needs to be on the website. A whole day of googling and this is what worked. Fixed all the rando errors react was throwing.
> .

Seriously! Thank you for this!

**Comment by danielidt** [comment]
im unable to update my xcode version past 9.2, is there no other way around this??

**Comment by rajsuvariya** [comment]
I have just created a project with react native version 0.60.4 and haven't done anything and if I try to run react-native run-ios it gives me this error. I am using xCode v9.3. I can not upgrade as this is the max version supported with my current mac os

**Comment by shokki96** [comment]
same issue with version 0.61.4 & xCode v9.4.1

**Comment by LAITONEN** [comment]
Same with macOS 10.13.6, react-native 0.61.5, Xcode 9.4 (which is a minimum supported version according to the website)

**Comment by LAITONEN** [comment]
Ok, I got it. Had issues setting-up a new project after not using React-Native for a lot of time.

My system:
- macOS High Sierra 10.13.6
- XCode 9.4

Had to reinstall the project in order to use the installation guide from version 0.59.0, because the installation guide from 0.61 uses approach with `npx react-native ...`, which disallows the usage of react-native below 0.60 (quite totalitarian). 0.59.0 was still using the global version of `react-native` installed through `npm`.

**In other words:**
Reinstall the project by removing the old one and use the steps mentioned in the "Getting Started" guide of React-Native 0.59.0 (or any other version compatible with your version of OS and XCode) to install your project again. No need to delete any `build` or `node_modules` or installing `pods` again and so forth, **just pick the version of React-Native compatible with your macOS and Xcode (by downgrading and reinstalling the project until you get it)** and no need to upgrade to the latest versions, they are developed for the latest systems, if you don't want to buy the latest devices to support the latest software (OS) or you can't afford them, just stay with the old ones - it's totally fine :)
