### ISSUE TITLE
GeoLocation Library not present in most recent version

### ISSUE THREAD

**Issue by Grapetoast** [facebook/react-native#25499]
React Native version: 0.60.0

## Steps To Reproduce

1. react-native init test
2. edit pods to include geolocation
3. atempt pod install
4. observe error due to inability to find Geolocation node_module
5. check '../node_modules/react-native/Geolocation
6. The library is not present

Describe what you expected to happen:
1. react-native init test
2. edit pods to include geolocation
3. atempt pod install
4.pod installs correctly
5. navigator.geolocation.getCurrentPosition should not error

**Comment by matt-oakes** [comment]
This module has been extracted out to [here](https://github.com/react-native-community/react-native-geolocation) as part of Lean Core. This was due to an issue where Apple was rejecting apps which declared privacy requirement strings (like for location), but didn't actually use them.

Follow the instructions in the project linked above to migrate to the new library. All of the API and the code is identical.
