### ISSUE TITLE
[Init] Move react-native init code into its own npm package to reduce dependencies

### ISSUE THREAD

**Issue by ide** [facebook/react-native#2554]
Some of the dependencies in package.json are rather big -- yeoman-generator consumes 31MB and is never used except to create a new project for example.

**Comment by grabbou** [comment]
Is this something new contributors can try to do? Sounds like something I can do.

**Comment by ide** [comment]
@grabbou yes please, go for it! As much as possible we want the existing react-native-cli package to keep working since many people have it installed.

My current thinking is that the local-cli directory should have its own package.json that isn't published to npm. The react-native-cli program downloads react-native from npm and runs a script within react-native: this is where something like "cd local-cli && npm install --production" should run.

cc @frantic

**Comment by grabbou** [comment]
@brentvatne same here, probably. I'll have some time this week to get that done.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/init-move-react-native-init-code-into-its-own-npm-package-to-reduce-dependencies

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is heavily focused working on performance.
