### ISSUE TITLE
Is Xcode 9.4 supported? UIKit/UIUserActivity.h' file not found

### ISSUE THREAD

**Issue by AnderLuiz** [facebook/react-native#25578]
The getting-started docs (https://facebook.github.io/react-native/docs/getting-started) says Xcode >= 9.4 is supported.  But I always get a compilation error in 9.4 version: 

`UIKit/UIUserActivity.h' file not found`

The issue (#25492) was closed because an update to Xcode 10.2 solved the problem, but it's not really a solution.

If not supported, I think the docs should be updated. If supported, the issue #25492 should be open again.

React Native version: 0.60

## Steps To Reproduce

1. Follow the getting-started guide with Xcode 9.4 and Rn. 0.60

**Comment by phemieny7** [comment]
Currently facing the same challenge all day long, @AnderLuiz Can you help out my mac too can't install  latest OS so i had to stick with 9.4

**Comment by AnderLuiz** [comment]
I still facing the issue with Xcode 9.4, but I installed Xcode 10.2 [this way](https://stackoverflow.com/questions/55596733/is-it-possible-to-install-xcode-10-2-on-high-sierra-10-13-6/55645290#55645290) . I just downloaded the Xcode, edited the files and copied Xcode 10.2 to applications folder as 'Xcode'.

**Comment by ben-pritchard** [comment]
I was able to resolve this without upgrading my Xcode (thank god, still using 9.3).

For me, the reason is because the build terminal output showed that there were 3 packages that I had linked manually that I needed to unlink (via: `react-native unlink PACKAGE-NAME`) so that the autolinking could work.

After running that command for the 3 packages I had linked manually, I ran an `npm install` and `react-native run-ios` and everything worked.

(Same comment I put into #25492 )
