### ISSUE TITLE
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65

### ISSUE THREAD

**Issue by hepf888** [facebook/react-native#25586]
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening MeiTuan.xcodeproj. Run CLI with --verbose flag for more details.

React Native version:
0.60
Xcode: 10.2.1

**Comment by SpawnAtis** [comment]
@hepf888 open your project(```ios/app.xcworkspace```) in Xcode -> Product -> Build -> Check error messages

**Comment by kelset** [comment]
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗

**Comment by AlbertVilaCalvo** [comment]
I just got this error after upgrading to 0.60.4 (from 0.59.2).

To fix it I've had to rename the xcworkspace folder from `gazella.xcworkspace` to `Gazella.xcworkspace`.

I could successfully run the project from within XCode, but got the error when doing `react-native run-ios` on the terminal. Now everything works fine.

**Comment by septe01** [comment]
> gazella.xcworkspace

please location this file

**Comment by AlbertVilaCalvo** [comment]
@septe01 it will have a different name in your project, but it will end with `.xcworkspace `
