### ISSUE TITLE
Cannot convert undefined value to object, js engine: hermes

### ISSUE THREAD

**Issue by xxRockOnxx** [facebook/react-native#25634]
Setting `enableHermes` to `true` would cause `Cannot convert undefined value to object, js engine: hermes`.

Confirmed it by setting the value to `false` and rebuilding.

React Native version:
System:
    OS: Linux 5.0 Antergos Linux undefined
    CPU: (8) x64 Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
    Memory: 2.91 GB / 7.77 GB
    Shell: 5.7.1 - /usr/bin/zsh
  Binaries:
    Node: 11.14.0 - /usr/bin/node
    Yarn: 1.16.0 - /usr/bin/yarn
    npm: 6.9.0 - /usr/bin/npm
  SDKs:
    Android SDK:
      API Levels: 28
      Build Tools: 28.0.3
  IDEs:
    Android Studio: 3.3
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.3 => 0.60.3

## Steps To Reproduce

1. Follow upgrade guide from `0.60.0` to `0.60.3`
2. enable `enableHermes` in `app/build.gradle`
3. `./gradlew clean`
4. `react-native run-android`

Describe what you expected to happen:
Should work just fine as before.

**Comment by ithustle** [comment]
Anything?

**Comment by sevensevener** [comment]
same error. building not possible

**Comment by rszalski** [comment]
@xxRockOnxx Try debugging JS in Chrome debugger and enable „Pause on exceptions”. This way you should be able to at least see where the problem originates. It would be good to have a minimal reproducible example to work with.

I had the same issue but it turned out that it wasn’t actually Hermes (actually it was Reactotron trying to notify me of subscriptions to an incorrectly configured Redux store). I’m mentioning this because I also though that disabling Hermes fixed the issue, but it was only coincidentally related and stateful.

**Comment by xxRockOnxx** [comment]
That's weird, it's working now and I haven't even touched the code since I wrote this issue because I went out of town.

I tried re-enabling it again and tried to give Chrome Debugger a try like @rszalski suggested so I'll be able to see what's wrong but the error mentioned in the OP did not show up.

Pretty sure there were no changes made based on Git status

**Comment by xxRockOnxx** [comment]
That's weird. The error mentioned in the OP is not showing up anymore.

I re-enabled the `enableHermes` option and tried the suggestion of @rszalski but it just worked and build without any exceptions.

Pretty sure I did not changed anything as I went out of town since I opened this issue and Git status did not show any changes (aside from re-enabling the `enableHermes`)

**Comment by hackdie** [comment]
having same error, any idea?

**Comment by rszalski** [comment]
> having same error, any idea?

@hackdie this is probably not a Hermes-related error but rather a normal JS error. The string `js engine: hermes` is there just to inform you that you've enabled Hermes correctly, and is not part of the actual error text. But it can be confusing at first.

I'd try doing a binary search on your components (meaning, comment half of them out, see if the error is there, if not, comment the other half out, etc.) to pinpoint where this originates. It's possible that you are just passing an `undefined` where an object is expected.

There might be something that makes Hermes more susceptible to this issue (which would give the perception of being _caused_ by Hermes), but I don't know the internals, just a thought.

**Comment by mikefogg** [comment]
I just wanted to throw it out there that I know this isn't super helpful, but I'm getting the same issue when using Hermes only. I tried simplifying things down as much as possible, but am currently only seeing this issue:

1) On the first load after a fresh install (before a reload)
2) When Hermes is enabled

I simplified things as much as possible, and my App.js is now simply:

```
# App.js

import React from 'react'
import { View, Text } from 'react-native'

const App = () => {
  return (
    <View style={{ backgroundColor: 'red', height: 200 }}>
        <Text>Here is text</Text>
    </View>
  )
}

export default App
```

and index.android.js is:

```
# index.android.js

import { AppRegistry } from 'react-native';
import App from './App';
import { name as appName } from './app.json';

AppRegistry.registerComponent(appName, () => App);
```

<img width="322" alt="Screen Shot 2019-08-20 at 2 44 20 PM" src="https://user-images.githubusercontent.com/4834250/63379086-2f06ef00-c359-11e9-87f7-cf104ea5167e.png">

I can't see where in there I could be introducing a JS error... any thoughts on what may be causing this or any other debugging? Since it's happening before I can connect to the Debugger it's not an easy one. Disabling Hermes fixes the issue for now...

**Comment by DaniAkash** [comment]
It happened when `inlineRequires` are enabled in `metro.config.js`. Try disabling it and run the build again...
```
module.exports = {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: true,
        inlineRequires: false
      }
    })
  }
};
```
