### ISSUE TITLE
[Touchable] scroll on ListView will trigger onPress event

### ISSUE THREAD

**Issue by jabez128** [facebook/react-native#2569]
I bind a onPress event on every item in a ListView, and when I scroll on the LIstView, I often trigger onPress Event by accident.  is there any way to make the ListView item be not so "sensitive" ? thx!

**Comment by brentvatne** [comment]
Are you sure that you are not using `onPressIn`?

**Comment by ide** [comment]
I've hit this too. I think it's worse on slow devices when doing lots of work. Sometimes the scroll responder doesn't suppress the press gesture. If you rapidly scroll down an infinite feed of content eventually you will hit a snag and tap into one of the feed items.

**Comment by christopherdro** [comment]
I've come across this as well.

**Comment by brentvatne** [comment]
@christopherdro - do you have any time to investigate this? It seems like what should happen is that when scrolling we should not be passing touch events through to child views. For example, open up the Twitter app on your phone and scroll through the feed - notice that if you tap on something it will stop scrolling but it won't actually navigate to the details for that tweet.

**Comment by burgalon** [comment]
I'm also experiencing this, especially on slow devices.
I was able to make it very apparent when using react-native-sqlite with a big DB (50K rows / 500MB) which was somehow loading the system causing press events instead of scroll

**Comment by aleclarson** [comment]
:+1:

**Comment by brentvatne** [comment]
Yeah this is annoying :(

Upvote it here: https://productpains.com/post/react-native/onpress-event-triggered-while-scrolling-in-listview/

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/touchable-scroll-on-listview-will-trigger-onpress-event

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
