### ISSUE TITLE
On freshly initialized app: Error type 3: MainActivity doesn not exist

### ISSUE THREAD

**Issue by viocost** [facebook/react-native#25706]
Trying to build "Hello world" following "Get started" instructions.
All listed dependencies are installed according to the documentation.

When trying to run freshly initialized app I get  following error:
```

BUILD SUCCESSFUL in 18s
27 actionable tasks: 4 executed, 23 up-to-date
adb server version (41) doesn't match this client (39); killing...
* daemon started successfully
info Connecting to the development server...
info Starting the app on "2f50ff1"...
Starting: Intent { cmp=com.islandsm/.MainActivity }
Error type 3
Error: Activity class {com.islandsm/com.islandsm.MainActivity} does not exist.
a@debian:~/projects/islandsm$ react-native info
info Fetching system and libraries information...


```
React Native version:

System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (8) x64 Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz
    Memory: 1.84 GB / 15.58 GB
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 10.15.2 - /usr/bin/node
    npm: 5.8.0 - /usr/bin/npm
    Watchman: 4.9.4 - /usr/local/bin/watchman
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.3 => 0.60.3 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1

## Steps To Reproduce
While android device is connected to USB and listed in adb devices

1. react-native init HelloWorld
2. cd HelloWorld
3. react-native run-android
4. On the android device allow installation
5. See the error
 

Describe what you expected to happen:
Expected fresh app to run without any issues on my android device

Snack, code example, or link to a repository:
the code from the template is untouched.

**Comment by brasrox** [comment]
same here using react-native init rn6xteste

info Connecting to the development server...
info Starting the app on "emulator-5554"...
Starting: Intent { cmp=com.rn6xteste/.MainActivity }
Error type 3
Error: Activity class {com.rn6xteste/com.rn6xteste.MainActivity} does not exist.

**Comment by cbedoy** [comment]
I have the same error

```
29 actionable tasks: 7 executed, 22 up-to-date
info Connecting to the development server...
info Starting the app on "0076bfc00804"...
Starting: Intent { cmp=cbedoy.rntabs/.MainActivity }
Error type 3
Error: Activity class {cbedoy.rntabs/cbedoy.rntabs.MainActivity} does not exist.
```

**Comment by adrienthiery** [comment]
Hi guys,

I'm not in the same situation, but I had the same error after upgrading my project to the latest version of RN.

The reason was that actually some duplication happened in my debug `AndroidManifest.xml`, although Android studio never hinted anything about it except a red underline (that I of course never saw before today)

![Screen Shot 2019-09-11 at 6 38 52 PM](https://user-images.githubusercontent.com/2392118/64716832-6cc3e700-d4c3-11e9-8a15-cdb5bfb42067.png)

![Screen Shot 2019-09-11 at 6 32 17 PM](https://user-images.githubusercontent.com/2392118/64716806-5f0e6180-d4c3-11e9-9a1d-c89f6ef482d9.png)

Removing the duplicated file and rebuilding made it work (of course).

The hint that made me find that was my problem was that it was building for release correctly (`react-native run-android --variant=release`).

If that's not your problem, I found a whole lot of other possibilities quickly summarized there : http://veesivee.com/error-type-3-error-activity-class-does-not-exist/

**Comment by mk0116** [comment]
same here.

`
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1920 file(s) to forward-jetify. Using 4 workers...
info JS server already running.
info Installing the app...
info Connecting to the development server...
info Starting the app on "ce0117110bfa9e0f05"...
Starting: Intent { cmp=co.aienglish/.MainActivity }
Error type 3
Error: Activity class {co.aienglish/co.aienglish.MainActivity} does not exist.

`

**Comment by mk0116** [comment]
I found the solution.
In my case, gradlew and gradlew.bat files were outdated.
Just create a new project with react-native init command and copy the files into your project.
