### ISSUE TITLE
[Modal] Command+R with modal open doesn't hides modal

### ISSUE THREAD

**Issue by alvaromb** [facebook/react-native#2601]
I have a modal component that is made visible using a button. If the modal is present and I press ``Cmd+R``, the app reloads but the modal maintains visible. The modal is shown depending on a Redux state that has an initial value set to ``false``, so it should not be displayed initially.

![modal](https://cloud.githubusercontent.com/assets/289640/9734877/e6b4e394-5636-11e5-8538-530c4283a864.gif)

**Comment by ide** [comment]
cc @a2 maybe Modal needs to be torn down on invalidation.

**Comment by brentvatne** [comment]
This is what I did in my overlay module (which I use for modal): https://github.com/brentvatne/react-native-overlay/blob/master/RNOverlay.m#L77-L82

**Comment by grabbou** [comment]
This is the case for ActionSheet as well (at least it used to be with React 0.10)

**Comment by jasonmerino** [comment]
This happens for me also when I have live reload enabled and a modal view is present when I save. The modal stays and I can't dismiss it after the live reload. It needs a rebuild of the project to resolve it.

**Comment by despairblue** [comment]
@jasonmerino you can also close the app (really closing the app: double press the home button and swipe it up) and open it again.

Also this is fixed on 0.11.

**Comment by jasonmerino** [comment]
@despairblue Great news that it's fixed in 0.11! The closing the app doesn't work for me as I'm working in the simulator and serving the app from localhost. When I go to close the app it crashes the run that's happening in Xcode. 

It's not that bad to deal with, especially if it's fixed in the upcoming release, just thought I'd chime in since the live reload aspect hadn't been mentioned. :)

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/modal-commandr-with-modal-open-doesnt-hides-modal

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
