### ISSUE TITLE
[Modal] Add presentation and transition style options

### ISSUE THREAD

**Issue by DaleJefferson** [facebook/react-native#2613]
Currently the only option for the modal presentation style is UIModalPresentationFullScreen, we are building an iPad application using React Native and a form sheet presentation style is often preferred.

I've tried to emulate the form sheet by adding a dark transparent background but it's not quite the same.

Fake Form Sheet

![fullscreen](https://cloud.githubusercontent.com/assets/375005/9756527/e06aff90-56d2-11e5-9a22-4d7dbd5b2ae9.gif)

Real Form Sheet (by adding UIModalPresentationFormSheet)

![formsheet](https://cloud.githubusercontent.com/assets/375005/9756562/1f39f352-56d3-11e5-979c-6c5d15dba317.gif)

Notice the fading in of the dark background and the nice rounded corners.

This could be as simple as adding a new prop 

```jsx
<Modal animated={true} visible={true} presentationStyle="FormSheet">
```

```objc
typedef enum {
   UIModalPresentationFullScreen = 0,
   UIModalPresentationPageSheet,
   UIModalPresentationFormSheet,
   UIModalPresentationCurrentContext,
   UIModalPresentationCustom,
   UIModalPresentationOverFullScreen,
   UIModalPresentationOverCurrentContext,
   UIModalPresentationPopover,
   UIModalPresentationNone = -1
} UIModalPresentationStyle;
```

**Comment by hufeng** [comment]
cool ~

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/modal-add-presentation-and-transition-style-options

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is heavily focused working on performance.
