### ISSUE TITLE
React Native app working fine in Remote Debugging (chrome) but Normally Hanging

### ISSUE THREAD

**Issue by rajashekar545** [facebook/react-native#26134]
React Native android app running fine when am using remote debug in chrome but when am running it normally its just hanging. there's no error or any sort of information related to it.
How to fix this issue ? 

React Native version:

## Steps To Reproduce

1.react-native run-android
2.Start Remote JS Debugging ( Working fine)
3. without Remote Debugging its always in Hung state

**Comment by Spacarar** [comment]
Same issue here, when I turn off remote debugging, I can't click anything in my app anymore. the scrollView on the home page is still working, but I can't even close a yellow box warning or open my react-navigation drawer. No idea what could be causing it, the only thing I've been able to find has to deal with `Date()` functions and invalid formatting, but even after removing any date functions temporarily, the app is still not functional without remote js debugging turned on.

**Comment by Spacarar** [comment]
AH! I was writing about having the same issue. But this is likely due to the different javascript environment between the chrome debugger and the native device. 
https://github.com/facebook/react-native/issues/25032#issuecomment-497542464
`console.log` statements won't work without the debugger turned on.

`Date()` statements with invalid formats might be able to be inferred by chrome and not by a real device. https://stackoverflow.com/questions/41874676/react-native-code-doesnt-work-without-remote-debugger-enabled

try looking for these issues in your project and try again.

**Comment by RichardLindhout** [comment]
Hermes is slow in debug mode. Disable hermes or use remote debugging.

**Comment by DuffmanBE** [comment]
Issue was related to date at our company as @Spacarar suggested. The database contained a faulty date going back to 1753. The debugger had no issue handling this but the real device did and just crashed.
