### ISSUE TITLE
[Bridge] ios app Memory consume too fast  when I use [ initWithBridge: moduleName:] api

### ISSUE THREAD

**Issue by fsp1990** [facebook/react-native#2624]
I  invoke
 '_rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation moduleName:@"xxxxx" launchOptions:nil];'  in  - (void)viewDidLoad;   
And invoke ‘_rootView = [_rootView initWithBridge:_rootView.bridge moduleName:@"xxxxx"];’  in - (void) viewWillAppear:(BOOL)animated.   

so  when often invoke viewWillAppear.   the  memory warning  happen

**Comment by ide** [comment]
Could you please investigate to see whether the memory is consumed by lots of root views, or if it's because you are creating a lot of views in general?

**Comment by brentvatne** [comment]
Yeah as @ide said we need some more information on what views are being created here, could you provide us with some more extensive sample code that reproduce the issue for you?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/bridge-ios-app-memory-consume-too-fast-when-i-use-initwithbridge-modulename-api

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is heavily focused working on performance.
