### ISSUE TITLE
[ScrollView] scrollToTop method that respects content insets

### ISSUE THREAD

**Issue by ide** [facebook/react-native#2637]
`scrollToTop` is quite useful to have but there are two approaches that come to mind:

1. Implement it natively. This is easy to do on iOS and Android. Downside is that it's not flexible -- we can scroll only to the top.

2. Send the content insets from native to JS when the ScrollView is first mounted, and any time after that when the content insets change. There might be some complexity around serializing the order of events that I'm not accounting for, so this code needs to be written thoughtfully. Once JS has content insets, it can implement `scrollToTop` as `scrollTo(-contentInsets.top)`. This offers a bunch of flexibility since application code can use the content insets for other calculations. Downside is that we're sending events from native to JS and incurring bidirectional data flow.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/scrollview-scrolltotop-method-that-respects-content-insets

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is heavily focused working on performance.
