### ISSUE TITLE
ListView  onEndReached   only  trigger  once 

### ISSUE THREAD

**Issue by nice2mu** [facebook/react-native#2665]
1, pull down    onEndReached  triggered 

2, pull  up

3, pull  down   ,  can't   trigger   onEndReached

**Comment by hufeng** [comment]
yes, we met the same problem. 

ListView's Source:
```javascript
if (nearEnd &&
        this.props.onEndReached &&
        this.scrollProperties.contentLength !== this._sentEndForContentLength &&
        this.state.curRenderedRowsCount === this.props.dataSource.getRowCount()) {
      this._sentEndForContentLength = this.scrollProperties.contentLength;
      this.props.onEndReached(e);
    } else {
      this._renderMoreRowsIfNeeded();
    }
```
because, this.scrollProperties.contentLength !== this._sentEndForContentLength 

return false

**Comment by jhau** [comment]
I am seeing the same problem too

**Comment by simondelacourt** [comment]
I've noticed the same problem, and I can't really find a way to fix it.

**Comment by pangers** [comment]
Same problem here

**Comment by paramaggarwal** [comment]
PR already open on https://github.com/facebook/react-native/pull/2440.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/listview-onendreached-only-trigger-once-

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
