### ISSUE TITLE
how to  presentViewController   without  NavigatorIOS  ?  

### ISSUE THREAD

**Issue by nice2mu** [facebook/react-native#2669]
My main frame is a  Tabbar 

and I get a  ListView in it .  how  to   click a row  and show a  new View not in tabor

**Comment by christopherdro** [comment]
Your going to have wrap your application with Navigator.
 
You can see an example here: https://rnplay.org/apps/-P8G_w

@ide @brentvatne Close. Duplicate #1489

**Comment by nice2mu** [comment]
@christopherdro 
thanks very much!

but   I  think this is not a  perfect  solution .   
because we are write app,  so there is a "Page" thing . 
so I think react native should implement this concept .

**Comment by nice2mu** [comment]
@christopherdro 

current we rennder  every new view  only  if  we have the RCTRootView . 
We  only have just one RCTRootView .  like we only have one  canvas for painting.

But  in ios and android ,  there is a  thing  go to a  new  empty  canvas . 
current in react native  we can only   use Navigator   or   repaint canvas  to do this.

**Comment by nice2mu** [comment]
@christopherdro 

In Android  -> startActivity
In iOS        ->  presentViewController


So I   scrupulous    think this is nesscery.  could we take  this   feature  in  consideration .

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/how-to-presentviewcontroller-without-navigatorios-

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.

**Comment by mkonicek** [comment]
@facebook-github-bot stack-overflow
