### ISSUE TITLE
setTimeout not working when remote debugging is enabled

### ISSUE THREAD

**Issue by programmingprince** [facebook/react-native#26828]
I am trying to load a second screen after some timeout. The second screen does not open up even after waiting for a long time.

React Native version: 0.60.5

## Steps To Reproduce

1. Suppose I am on a Screen A.
2. From A, I want to open Screen B after timeout of 100 ms. I used the following code in componentDidMount of Screen A.

setTimeout(() => {
                    navigation.navigate("ScreenB");
}, 100)

But, ScreenB does not open up even after waiting for a long time.

**Comment by mmahdigh** [comment]
If you could reproduce your issue in a separate git repo, people could help you much faster and better.

**Comment by TiagoGouvea** [comment]
Facing the same. 

On [that](https://github.com/facebook/react-native/issues/9030#issuecomment-235639617) comment they say It's related to the difference between device and computer clock.

And another old issue related to that: #4470

**Comment by ThaJay** [comment]
I have exactly https://github.com/facebook/react-native/issues/4470 but the issue is old and closed. When debugger is activated the following code executes before the time has passed. Without debugging the code executes after the time has passed.
```
    const timeout = 60 * 1000
    const t1 = moment()

    global.setTimeout(
      () => {
        const t2 = moment()
        console.log('setTimeout', timeout, ', result:', t2 - t1)
      },
      timeout
    )
```
without debugging:
```
 LOG  setTimeout 60000 , result: 60012
// If I change it from 60 to 4:
 LOG  setTimeout 4000 , result: 8263
```
with debugging:
```
setTimeout 60000 , result: 42189
// If I change it from 60 to 4:
setTimeout 4000 , result: 194
```
If this is about device and host clocks being different, would it be better to just choose one clock and stick with that?
