### ISSUE TITLE
[Android][Linux] react-native init freeze

### ISSUE THREAD

**Issue by riston** [facebook/react-native#2688]
I am using Arch Linux with Node.js v0.12.7. Installed the cli package `react-native`. When I run the command `react-native init some-random-name`, the so called spinner never stops and does nothing. Besides this the project directory gets created with 2332 files and size about ~53MB. Inside the project directory there are `node_modules` and `package.json` file. Only module that's installed is `react-native`.

Is there any binary run after the package installation which might be OS specific ?

How to add more debugging/verbose output for the cli commands ?

**Comment by kmagiera** [comment]
@riston please check getting started instruction for iojs version you should install instead of node. We don't support linux for now as we still have a bunch of scripts that calls applescript directly (see https://github.com/facebook/react-native/issues/2684).
One of those scripts is responsible for launching packager dev server which seems like you haven't started. To start manually you can do `react-native start` in your app directory

**Comment by kmagiera** [comment]
Closing this one in favor for other tasks that rely on linux support https://github.com/facebook/react-native/issues/2684

**Comment by satya164** [comment]
@kmagiera Why the `iojs` requirement? Aren't `iojs` and `node merged now?

**Comment by ide** [comment]
@satya164 as of the latest release Node 4 is supported. The main thing is that legacy Node (0.10 and 0.12) are not supported.

**Comment by satya164** [comment]
@ide Ah, ok. Thanks for the clarification.
