### ISSUE TITLE
Android platform checks and possible irrelevant code paths still exist in this repo

### ISSUE THREAD

**Issue by jondot** [facebook/react-native#269]
See here

```
Libraries/Components/ScrollView/ScrollView.js
276:    } else if (Platform.OS === 'android') {
332:if (Platform.OS === 'android') {
```
And here
```
Libraries/JavaScriptAppEngine/Initialization/ExceptionsManager.js
69:  if (Platform.OS === 'android') {
```
It's probably safe, because the codepath never executes on `iOS`, but still there's references to Android views which I'm sure are still internal and not open source.

**Comment by vjeux** [comment]
We're not ready yet to be open source first so any pull request has to go through our internal codebase and pass our internal tests that include android. We want to open source android sooner than later so that it doesn't become a big issue but until then, we'll have to live with those checks i'm afraid :(
