### ISSUE TITLE
Fast reload all page

### ISSUE THREAD

**Issue by HoSheiMa** [facebook/react-native#26907]
When i change any thing in rn fast reload as default change it but if i scroll the page and wanna change some thing in page fast reload refresh all page and return me to top of page and i not need that and need change text without back to top

**Comment by ralph-dev** [comment]
I believe this is not possible in React Native becuase the scroll value is not saved. My suggestion would be
1) Place a simple ScrollTo Function for yourself just for testing
2) Create your component using StoryBook https://storybook.js.org/

**Comment by HoSheiMa** [comment]
I believe this problem just fix.soon from rn core team because it's make work with hot reload is completely hard

**Comment by ralph-dev** [comment]
In that case check this paragraph out about fast refresh maybe your exporting non React components.

Finally, if you edit a file that's imported by modules outside of the React tree, Fast Refresh will fall back to doing a full reload. You might have a file which renders a React component but also exports a value that is imported by a non-React component. For example, maybe your component also exports a constant, and a non-React utility module imports it. In that case, consider migrating the query to a separate file and importing it into both files. This will re-enable Fast Refresh to work. Other cases can usually be solved in a similar way.

**Comment by HoSheiMa** [comment]
I try using same feature in flutter and work great in rn see not work ed

**Comment by karthik-balasubramanyam15** [comment]
I have a similar problem, I'm using React Native version 0.61.4 for mobile app development.

For instance, I am working on a modal which opens after when a specific condition is achieved. With hot reloading before, making any new modifications to the design was easy since only the modal would refresh. But with fast refresh, it takes me back to the base level and I would have to again satisfy the conditions to find the right page and continue  working, this consumes a lot of time. 

Is there a way we can disable fast refresh and enable hot reloading?
