### ISSUE TITLE
stickyHeaderIndices not works good in react-native

### ISSUE THREAD

**Issue by nihp** [facebook/react-native#26908]
I am using ScrollView from react-native and I do not need to scroll the header. I am using stickyHeaderIndices = {[0]}

Steps to reproduce:

1. Scroll the screen from the Top

**Comment by terrysahaidak** [comment]
Hi @nihp, it would be really cool if you provide reproducing example at least using snack.expo.io

It will help a lot.

**Comment by nihp** [comment]
Kindly refer this snack expo. 

Kindly try to scroll up from the beginning of the screen.

https://snack.expo.io/@niph/stickyheader

**Comment by terrysahaidak** [comment]
This is the expected behavior since when you scroll up it over scrolls the whole scroll view content. You may notice the same behavior on any other iOS app. If you want it to be "sticky" at the top in that particular example, use `position: absolute` as a header style instead. Also, you may want to turn off a bouncing effect on a scroll view, it won't allow to over scroll.

**Comment by LukhiKartik** [comment]
Same issue. It doesn't looks good in iPhone x model. It will stick over status bar.
