### ISSUE TITLE
'com.facebook.jni.CppException: Could not get BatchedBridge, make sure your bundle is packaged correctly ' error on signed apk when published on play store

### ISSUE THREAD

**Issue by abolfazlyounesi** [facebook/react-native#26930]
this is the stackoverflow link https://stackoverflow.com/questions/58477318/i-get-com-facebook-jni-cppexception-could-not-get-batchedbridge-make-sure-your

**Comment by vladp** [comment]
@abolfazlyounesi  were you able to solve this?
I am running into same issue and suggestions from 2016-2017 about not having 'adb' in the path -- are not helping

**Comment by danieltov** [comment]
Same issues here! Could it be Hermes related? https://github.com/facebook/react-native/issues/26252

**Comment by vladp** [comment]
I have seen this issue in several conditions. All turned out to be my fault.
Here is the list (from memory)

- Between RN 0.60 and 0.61 location of Hermes node_modules package changed. It needs to be correctly specified in your project (not app level) build.gradle.  Check the RN template for detail.
If not correct hermes shared lib will not be packaged, and will cause this error.

- My project has React native web and React native, all built from the same tree.
  I had babel.config.js that was aliasing react-native-web to react-native, even for Android builds.
 this generate this silent problem

- I had wrong appName in `AppRegistry.registerComponent(appName, () => App);` in the index file

- the index file name did not match between android/app/build.gradle  react project.react.ext.entryFile and `getMainComponentName` function override

**Comment by abolfazlyounesi** [comment]
Hi yes I solved the problem
I disabled Hermes and everything is ok after that

**Comment by kevinbtesar** [comment]
> Hi yes I solved the problem I disabled Hermes and everything is ok after that

@abolfazlyounesi  -- Yep, that was it. Thank you much! That was getting super frustrating. I'm almost certain I built a working release apk with Hermes enabled but who knows. Maybe I made some other change with proguard that was breaking Hermes on release builds. 

**Other methods that did NOT work**:

- node node_modules/react-native/local-cli/cli.js bundle --platform android --dev true --reset-cache --entry-file index.android.js
- adb reverse tcp:8081 tcp:8081 adb 
- reverse tcp:8081 tcp:8081 inside \Android\sdk\platform-tools
- ./gradlew clean
- manifest.xml and build.gradle changes

**Comment by olegwn** [comment]
still encountering this at 0.61.5 :( any solutions? I want hermes enabled for release builds

**Comment by kevinbtesar** [comment]
@olegwn Got it! Hermes active in release builds! For me it was very simple. I had the following in my dependencies. Though I'm unsure why it's only relevant to release builds but if either flavor of JSC is enabled that will cause the Hermes engine to fail. What ends up happening is all the view elements fail rendering. 
 
So if you find either of the following libraries included as a dependency, remove them if you want Hermes to work. 
```
if (useIntlJsc) {
        implementation 'org.webkit:android-jsc-intl:+'
} else {
        implementation 'org.webkit:android-jsc:+'
}
```

Additional Note:
I also have this rule in my proguard, though it didn't help with this issue.. Or maybe it did and that's why only debug builds ran...
`-keep class com.facebook.hermes.unicode.** { *; }`


For informational purposes, here is how I introduce Hermes into my React Native project. From <project_root>/android/app/build.gradle:
```
project.ext.react = [
        entryFile: "index.js",
        enableHermes: true,  // clean and rebuild if changing
        hermesCommand: "../../node_modules/hermes-engine/%OS-BIN%/hermes",
]
```
React Native had the following in app/build.gradle by default:
`def enableHermes = project.ext.react.get("enableHermes", false)`

Then my dependencies look like this:
```
dependencies {
    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/"
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }

    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation project(':_myLibrary')
}
```

My usage of JSC turned out to be in my project library, which was crashing release builds.

**Comment by Evan-Younan** [comment]
@kevinbtesar Something out of what you did worked for me. I was trying to resolve this for hours. I think it had to do with removing:

```
if (useIntlJsc) {
        implementation 'org.webkit:android-jsc-intl:+'
} else {
        implementation 'org.webkit:android-jsc:+'
}

```

**Comment by samuely4ng** [comment]
> @olegwn Got it! Hermes active in release builds! For me it was very simple. I had the following in my dependencies. Though I'm unsure why it's only relevant to release builds but if either flavor of JSC is enabled that will cause the Hermes engine to fail. What ends up happening is all the view elements fail rendering.
> 
> So if you find either of the following libraries included as a dependency, remove them if you want Hermes to work.
> 
> ```
> if (useIntlJsc) {
>         implementation 'org.webkit:android-jsc-intl:+'
> } else {
>         implementation 'org.webkit:android-jsc:+'
> }
> ```
> 
> Additional Note:
> I also have this rule in my proguard, though it didn't help with this issue.. Or maybe it did and that's why only debug builds ran...
> `-keep class com.facebook.hermes.unicode.** { *; }`
> 
> For informational purposes, here is how I introduce Hermes into my React Native project. From <project_root>/android/app/build.gradle:
> 
> ```
> project.ext.react = [
>         entryFile: "index.js",
>         enableHermes: true,  // clean and rebuild if changing
>         hermesCommand: "../../node_modules/hermes-engine/%OS-BIN%/hermes",
> ]
> ```
> 
> React Native had the following in app/build.gradle by default:
> `def enableHermes = project.ext.react.get("enableHermes", false)`
> 
> Then my dependencies look like this:
> 
> ```
> dependencies {
>     if (enableHermes) {
>         def hermesPath = "../../node_modules/hermes-engine/android/"
>         debugImplementation files(hermesPath + "hermes-debug.aar")
>         releaseImplementation files(hermesPath + "hermes-release.aar")
>     } else {
>         implementation jscFlavor
>     }
> 
>     implementation fileTree(include: ['*.jar'], dir: 'libs')
>     implementation project(':_myLibrary')
> }
> ```
> 
> My usage of JSC turned out to be in my project library, which was crashing release builds.

Thank you so much!!! I can confirm that removing the useIntlJsc block fixed this for me. 👍

**Comment by kyle-ssg** [comment]
A warning around this, I have a feeling that when upgrading to react-native 0.64.0, commenting out the following seems to cause an issue. For now I've had to downgrade to 0.63 to allow for the above fix.

```
if (useIntlJsc) {
        implementation 'org.webkit:android-jsc-intl:+'
} else {
        implementation 'org.webkit:android-jsc:+'
}
```

**Comment by Doko-Demo-Doa** [comment]
For me, it was caused by `@cometchat-pro/react-native-calls` dependency. Its `build.gradle` is:

```groovy
dependencies {
    //noinspection GradleDynamicVersion
    implementation 'com.facebook.react:react-native:+'  // From node_modules
    implementation 'com.cometchat:pro-android-calls-sdk:2.0.2')
}
```

Hilariously, the native Android SDK depends on `react-native` so I had to exclude some inner dependencies for it to work:

```groovy
dependencies {
    //noinspection GradleDynamicVersion
    implementation 'com.facebook.react:react-native:+'  // From node_modules
    implementation ('com.cometchat:pro-android-calls-sdk:2.0.2') {
        exclude group: 'com.facebook.react', module: 'react-native-community_netinfo'
        exclude group: 'com.facebook.react', module: 'react-native-background-timer'
        exclude group: 'org.webkit', module: 'android-jsc' // This
    }
}
```
