### ISSUE TITLE
[iOS] Add platform automatically to the bundle URL

### ISSUE THREAD

**Issue by negativetwelve** [facebook/react-native#2705]
It seems like in the current master, several of the example apps are broken because they are missing `?platform=ios`. On React Native Android, it seems like the `?platform=android` is automatically added when the application is inited.

Are there plans to do something similar on iOS? Would a good spot be in this method?
https://github.com/facebook/react-native/blob/master/React/Base/RCTBridge.m#L187

I'd be more than happy to make this change but wanted to ask here first.

**Comment by ide** [comment]
Rather than the bridge it's better to make this change in the packager (e.g. default to platform = ios if unspecified, and print a warning/deprecation message). @amasad is planning to move the packager into a dedicated repository shortly so you'll have to wait a little bit. In the meantime, fixing up the URLs in the AppDelegates of the sample apps would be appreciated.

**Comment by negativetwelve** [comment]
Hmm yeah I was tracking the packager migration stuff, sounds good about waiting.

Not sure if putting it in the packager is the best thing. Seems like the platform should be tied to the runtime. They're doing this on android (https://github.com/facebook/react-native/blob/42eb5464fd8a65ed84b799de5d4dc225349449be/ReactAndroid/src/main/java/com/facebook/react/devsupport/DevServerHelper.java#L56)

I'll fix up the URLs and get that in ASAP!

**Comment by ide** [comment]
The iOS project should specify `platform=ios` but that should happen where the bundle URL is specified (in this case, the AppDelegate). The patch to the packager is just something to tide existing apps for a month or two till they get updated.

**Comment by negativetwelve** [comment]
Ahh okay, I misunderstood, that sounds good to me!

**Comment by mkonicek** [comment]
I'll take this one, I removed `?platform=ios` in the Movies app because I assumed it would be inferred from `.ios` in the URL: https://github.com/facebook/react-native/blob/master/Examples/Movies/Movies/AppDelegate.m#L40

cc @amasad

**Comment by mkonicek** [comment]
@javache Is this the right place to add `?platform=ios` to all requests automatically?
https://github.com/facebook/react-native/blob/master/React/Base/RCTBridge.m#L187

It's important for cases like `/index.js` where the platform can't be inferred from the extension. I like sending the platform explicitly better than making iOS the default platform in the packager.

**Comment by ide** [comment]
@mkonicek the bridge shouldn't have knowledge of the URL structure. My proposal is: all new projects should specify platform=ios themselves in their query strings, and making the packager default to ios is just a temporary way to let people know they need to change their existing apps.

**Comment by mkonicek** [comment]
I agree it probably shouldn't be in `RCTBridge`, was just echoing the original question.

On Android we add the request param automatically, we could do the same on iOS? Why having to specify `?platform=ios` in each app separately when the framework knows it's an iOS app?

See https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/devsupport/DevServerHelper.java#L57

**Comment by ide** [comment]
The main reason is to give developers flexibility and clean URLs -- if you're using a custom packager server then you might use HTTP headers or some other way to learn the client's platform.

**Comment by mkonicek** [comment]
@ide Using a custom packager is a good point. Should we close this then?

**Comment by ide** [comment]
Let's keep this open till the packager is in it's own repo and we can open a new issue over there. I'll tag this issue w/packager so it's easy for us to find.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/ios-add-platform-automatically-to-the-bundle-url

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
