### ISSUE TITLE
Android: Text component not selectable when removeClippedSubviews

### ISSUE THREAD

**Issue by cristianoccazinsp** [facebook/react-native#27107]
React Native version:

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Memory: 22.99 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    npm: 6.12.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28
      Build Tools: 28.0.3
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 11.2/11B52 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.11.0 => 16.11.0 
    react-native: 0.61.3 => 0.61.3
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    create-react-native-module: 0.10.2
    react-native-cli: 2.0.1
```

## Steps To Reproduce

1. Render a `<Text selectable={true}>test</Text>` component inside a ScrollView with `removeClippedSubviews={true}` on Android
2. Try to copy paste text. Text is not selectable by long pressing

Describe what you expected to happen:
Text should be selectable regardless of removeClippedSubviews

Snack, code example, screenshot, or link to a repository:

**Comment by xutm** [comment]
Any process？

**Comment by cristianoccazinsp** [comment]
Still an issue

**Comment by cristianoccazinsp** [comment]
Still an issue

**Comment by fabriziobertoglio1987** [comment]
Thanks for the issue report. I tested your used case by adding `removeClippedSubviews={true}` to the `Animated.FlatList` component in my branch https://github.com/facebook/react-native/pull/28952

This issue is fixed with https://github.com/facebook/react-native/pull/28952 Thanks a lot

**<details><summary>CLICK TO OPEN TESTS RESULTS</summary>**
<p>

the onPressHandler is triggered when we set `onPressDisabled: false`

| **AFTER** | 
|:-------------------------:|
| <video src="https://user-images.githubusercontent.com/24992535/109151707-cc22bf00-776a-11eb-8531-e457d98ce61b.mp4" width="700" height="" /> |

the text is selected when we set `onPressDisabled: false`

| **AFTER** | 
|:-------------------------:|
| <video src="https://user-images.githubusercontent.com/24992535/109151735-d6dd5400-776a-11eb-8737-8dec54037f19.mp4" width="700" height="" /> |

</p>
</details>
