### ISSUE TITLE
[iOS] Throw a fatal error if bundled js not present?

### ISSUE THREAD

**Issue by rreusser** [facebook/react-native#2734]
It took me a couple hours to get to the bottom of an issue in which my Debug build worked fine, but Release failed silently, giving only a blank white screen. The issue is the line:

```objective-c
jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
```

If `main.jsbundle` doesn't exist or if it's misnamed or if it's not copied when building, the app fails silently with no error logged and no fatal exit. In my case, I missed [Running on Device (iOS)#Troubleshooting](https://facebook.github.io/react-native/docs/running-on-device-ios.html#troubleshooting). I had an old project that didn't copy main.jsbundle on build and there was no indication this was the source of the issue.

Is it reasonable to imagine that even a production app could throw a fatal error or at least log a warning if you've completely botched your setup? Since I didn't know how it works normally and since I, like lots of others around here, am not versed in iOS development, this was a moderately frustrating issue to debug (i.e. turning on debug mode makes the error go away).

Thanks!

**Comment by mkonicek** [comment]
Seems reasonable to me. @nicklockwood What do you think? Can you triage this to someone on iOS if you like the idea?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/ios-throw-a-fatal-error-if-bundled-js-not-present

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is heavily focused working on performance.
