### ISSUE TITLE
[android] reload js hangs app until it is force closed and restarted

### ISSUE THREAD

**Issue by Wingie** [facebook/react-native#2747]
just started with react native development yesterday; got everything set up and working fine except auto reloading.
after i make some changes in the js file, i see in the node server window that it has finished generating and i go to the shake menu and reload js.
at this point, i dont see my changes in the app and the chrome debug extension also doesnt find react. if i try to shake again, the app doesnt open the dev menu any longer. it has hung, not sure what i should be looking for in logcat... but nothing wierd there.
but force closing the app and starting it again makes the app show the old js site for a second and then a new page.
also, setting up autoreload has this wierd thing of reloading the app continuously even when i'm not doing any changes to the source.
i'm using node 4.0.0 if it helps.

**Comment by mkonicek** [comment]
Since you said "try to shake again" I assume this is on a physical device, not an emulator?

Can you do the steps here?
https://facebook.github.io/react-native/docs/running-on-device-android.html

Can you please use Stack Overflow to ask questions tagged `react-native` and only open issues if something's broken? http://stackoverflow.com/questions/tagged/react-native

This helps us use the Github issues as a reference for bugs that need to be fixed.

**Comment by Wingie** [comment]
Yeah, i'm reporting a bug where sometimes after you do JSreload the android app hangs.
closing the app on the device and restarting it fixes the issue.
i sometimes see older code - code i was doing a while back on the screen so maybe its loading from a sort of cache instead of the packager server?

**Comment by qbig** [comment]
Hi @Wingie. Can you reproduce this in a more predictable manner ?

**Comment by jsierles** [comment]
@facebook-github-bot no-reply
