### ISSUE TITLE
Geolocation with TabBarIOS passes props every second

### ISSUE THREAD

**Issue by cmhsu** [facebook/react-native#2748]
I have Geolocation in a map view which is the first TabBarIOS item. whenever I click on another tab bar to go to another view, props gets passed every second. Even if the TabBarIOS item doesn't have any props, the geolocation from the map view tab will still pass an empty prop object {} every single second. Is there any way around this?

This is a sample VideoTab that gets an empty object as props passed to it every second (even though VIdeoTab has no props!):
< TabBarIOS.Item
            title="Video"
            icon={ require('image!video') }
            onPress={ () => this.changeTab('video') }
            selected={ this.state.selectedTab === 'video' }>
            < VideoTab />
          </ TabBarIOS.Item>

**Comment by brentvatne** [comment]
Hi @cmhsu! This type of question is better suited for StackOverflow, please create a question there and tag it with react-native :smile: We're more concerned here with bugs and feature requests. If it turns out that this is a bug, ping me and I can reopen the issue!

Thanks and good luck! :smile: :rocket:
