### ISSUE TITLE
iOS: Linking.openURL(href) cannot open universal link in app (safari instead)

### ISSUE THREAD

**Issue by brandonpearcy** [facebook/react-native#27486]
Reposting an issue that was closed because of an old version of RN. https://github.com/facebook/react-native/issues/26584

Many of us have reproduced it on the latest RN. 

## Original issue
My app has already set up deeplink and universal linking for iOS, applinks for android. It works perfectly for months until I found a use case that Linking.openURL(href) fails on iOS.

```
              // If I click this url in external browser, my native app will be launch because I've already handled universal link
              const href = "https://my-universal-link-supported-domain.com/foo/bar";
              Linking.canOpenURL(href).then(supported => {
                if (supported) {
                  Linking.openURL(href);
                }
              });
```

## Steps To Reproduce
1. Setup deeplink, universal link for ios, app-links for android
1. Execute: Linking.openURL(href)
1. Fail to open href by native app on iOS (opened by Safari instead), still work on Android
1. Then, copy the same universal link to another application like Slack, Notes, etc
1. Open the link from there, and observe that it does open correctly in the target app (not Safari)

## Describe what you expected to happen:
iOS only: URL was opened by Safari on iOS .
URL was opened by the app normally on Android

## Expected
URL was opened in the app on iOS

## React Native version:
```
$ react-native info
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 177.45 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.15.1 - ~/.nvm/versions/node/v8.15.1/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.15.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-log-ios: 1.0.1
```

**Comment by ksulliva** [comment]
From what I understand, this is an issue with iOS, not with React Native. Universal links appear to work differently on iOS and Android, and this is one of the ways iOS is different. Here's what I've discovered while testing.

### Android Behavior
If an app is registered to handle a specific URL, it will always open in that app, regardless of how that link was opened.

### iOS Behavior
iOS alters how universal links are handled based on either the source application, or the source domain (in the case of Safari).  Here are a couple of examples involving a hypothetical app (HomeViewer):
- If I search for a specific home in Safari using Google, and tap on the search result for a HomeViewer home, that will open in the app.
- If i go to homeviewer.com in Safari, and then tap the link to a specific home, that home will open in Safari and not in the HomeViewer app. This appears to be because you were already on the HomeViewer website, and so you likely wish to continue in Safari rather than being kicked out to the app.
- If someone sends me a text message link to a HomeViewer home, that will open in the app.
- If I tap a link to a HomeViewer home from a 3rd party app, that will open in the app.
- If I tap a link to a HomeViewer home from within the HomeViewer app, that will open in Safari. This appears to be by design, presumably Apple believes that by using the `UIApplication` `openURL` method, you're signaling that you want to open that link in a different app.

There are likely many more edge cases with iOS, but these are a couple of the ones I've found.

### Possible Workaround
My solution was to simply replace all calls to `Linking.openURL()` with a custom function that first checks if my application can open the URL. If it can, I handle the navigation using the same router function I use for universal links. And if it can't handle the URL, then I call `Linking.openURL()`.
