### ISSUE TITLE
[Windows] Are there any plans to support creating Windows apps?

### ISSUE THREAD

**Issue by starquake** [facebook/react-native#2758]
Are there any plans to support Windows? Or hasn't there been anything decided just yet

If there is support for Windows? This should make a pretty good alternative to making Cordova Apps with cross-platform UI libraries. Or an alternative for Xamarin.

**Comment by gebhart** [comment]
+1

I changed the index.js of react-native-cli to use cross-spawn and I changed run-packager.js so that it directly launches node instead of a shell script, so "react-native start" and "react-native run-android" work. But I still have troubles when downloading the JS bundle. Then the server seems to hang.

**Comment by foghina** [comment]
Yes, we are looking into Windows support, but don't have a timeframe. Note that only Android development will work on Windows, as iOS still requires Xcode which only works on OSX.

@gebhart that sounds like a very good start. What version of node are you using?

**Comment by mryonax** [comment]
@gebharton on Windows, the packager crashes with OOM error, due to [these lines](https://github.com/facebook/react-native/blob/master/packager/react-packager/src/DependencyResolver/DependencyGraph/ResolutionRequest.js#L228-L234):
```javascript
for (let currDir = path.dirname(fromModule.path);
     currDir !== '/'; // never end on windows
     currDir = path.dirname(currDir)) {
  searchQueue.push(
    path.join(currDir, 'node_modules', realModuleName)
  );
}
```

If I'm not mistaken, the problem can be solved something like this
```javascript
for (let prevDir = '', currDir = path.dirname(fromModule.path);
     currDir !== prevDir;
     prevDir = currDir, currDir = path.dirname(currDir)) {
// ...

```

**Comment by starquake** [comment]
Just to make clear: I meant was the ability to create apps to run on Windows.

**Comment by ide** [comment]
I believe a C++ Windows target is highly unlikely to come any time soon, since mobile is the primary focus and web and OS X are easier targets. Facebook also has very little desktop software.

As a pragmatic solution, you could run your React code in Electron (or your React Native code with the help of https://github.com/necolas/react-native-web or similar -- people are doing this) and get most of the benefits.

(Someone from Facebook -- go ahead and reopen this issue if building Windows apps is going to happen any time soon...)

**Comment by starquake** [comment]
I mean Windows apps in the Windows Store. Like this one from facebook: https://www.microsoft.com/en-us/store/apps/facebook/9wzdncrfj2wl

**Comment by starquake** [comment]
@ide or @foghina Maybe my initial question wasn't very clear but could you please take the time to answer the question? The question is this:

Will there be any way to create apps for Windows Phone/Windows Mobile/Metro apps/Universal apps. I mean apps running on a Windows tablet or phone device. Just like this facebook app. https://www.microsoft.com/en-us/store/apps/facebook/9wzdncrfj2wl

As I mentioned this would be a great alternative to Cordova Apps. Or one of these alternatives:
Xamarin
https://xamarin.com/

NativeScript
https://www.nativescript.org/

Tabris.js
https://tabrisjs.com/

Trigger.io
https://trigger.io/

Thanks!

**Comment by ide** [comment]
I haven't heard about any plans to support Windows/Windows Phone, but I don't speak for FB so someone else will have to confirm.

My own observation is that React Native is far from its full potential on iOS and Android and we need all hands on deck to realize that opportunity. That's how we are going to help developers benefit the largest number of people -- [over 90% of the mobile device market](https://en.wikipedia.org/wiki/Usage_share_of_operating_systems#Mobile_devices) in this case.

Having said that, React 0.14 splits React from ReactDOM in order to encourage more backends for React, such as React Canvas, React WebGL, etc. So the door is wide open for anyone who wants to target Windows -- especially WinJS apps.

**Comment by starquake** [comment]
Okay thanks for the response!

**Comment by BenLeggieroNCR** [comment]
> I don't speak for FB so someone else will have to confirm.
Would you please reopen this issue and ask that someone else to confirm?

**Comment by vjeux** [comment]
No one is working on it neither any prototype has ever been started by the team.

**Comment by yajiex** [comment]
https://github.com/ReactWindows/react-native-windows

**Comment by awebdeveloper** [comment]
https://blogs.windows.com/buildingapps/2016/04/13/react-native-on-the-universal-windows-platform/#u25iGfkOAfXGKVGL.97
