### ISSUE TITLE
[iOS][NavigatorIOS][Style] Update NavigatorIOS itemWrapperStyle on button press

### ISSUE THREAD

**Issue by edcs** [facebook/react-native#2759]
Is it possible to update style properties on the fly? I have defined a `<NavigatorIOS/>` element like so:

```javascript
return (
    <NavigatorIOS
        ref="nav"
        style={styles.nav}
        itemWrapperStyle={{flex: 1, marginRight: 0}}
        initialRoute={{
            title: 'Title',
            component: Map,
            leftButtonTitle: 'Left',
            onLeftButtonPress: this.handleLeftButtonPress,
            rightButtonTitle: 'Right',
            onRightButtonPress: this.handleRightButtonPress,
        }}
    />
);
```

My left button press handler looks like this:

```javascript
handleLeftButtonPress: function () {
    this.refs.nav.props.itemWrapperStyle = {flex: 1, marginRight: 100};
},
```

However this doesn't work as `itemWrapperStyle` is read-only. I've looked through the source code and can't seem to find a setter for this property but can't find one. Is what I'm doing possible? Essentially I'd like a hidden menu to be revealed when the left button is pressed.

**Comment by JonathanWi** [comment]
+1

**Comment by mkonicek** [comment]
Does this work for you?

    itemWrapperStyle={this.state.navigatorItemWrapperStyle}

    ...

    handleLeftButtonPress: function () {
      this.setState({itemWrapperStyle: {flex: 1, marginRight: 100}});
    },

Note that React doesn't work with setters but updates your UI on state changes, making the minimal required changes: https://facebook.github.io/react/docs/interactivity-and-dynamic-uis.html

Can you please use Stack Overflow to ask questions and tag them with react-native? http://stackoverflow.com/questions/tagged/react-native

This helps us keep track of bugs that need to be fixed in Github issues.

**Comment by edcs** [comment]
Got it - thanks! Will use Stack Overflow in future too :+1:
