### ISSUE TITLE
Variable tooltip in Chrome debugging

### ISSUE THREAD

**Issue by bitfriend** [facebook/react-native#27738]
React Native version: 0.59.9

## Steps To Reproduce

1. When you set package.json as following, debug tooltip is not displayed.
```
  "devDependencies": {
    "@babel/core": "^7.7.4",
    "@babel/runtime": "^7.7.4",
    "babel-jest": "^24.9.0",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.57.0",
    "react-test-renderer": "16.8.3"
  },
```
2. When you set package.json as following, debug tooltip is displayed.
```
  "devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/runtime": "^7.5.5",
    "babel-jest": "^24.8.0",
    "jest": "^24.8.0",
    "metro-react-native-babel-preset": "^0.55.0",
    "react-test-renderer": "16.8.3"
  },

```

Describe what you expected to happen:
Currently, developers can use old devDependencies to display debug tooltip.
If problem in these dependencies is fixed, they can work without change of devDependencies or chrome setting ("Use hardware acceleration when available").

Snack, code example, screenshot, or link to a repository:
https://www.linkedin.com/feed/update/urn:li:activity:6621768930556030976/

**Comment by fabriziobertoglio1987** [comment]
thanks for opening this issue @bitfriend  

As you mentioned there is an open issue at [https://support.google.com/chrome/thread/16855096?hl=en](https://support.google.com/chrome/thread/16855096?hl=en) 

Users on `chrome v79.0.3945.79` are not capable of dislaying the `tooltip` inside their `chrome developer tools` as displayed in the below image. This issue is connected to `chrome v79.0.3945.79`.

![image](https://user-images.githubusercontent.com/24992535/72245816-ad5a7b00-35f1-11ea-870f-bc07bf5ba5ad.png)

The issue seems to not be present on chrome `79.0.3945.117 (Official Build) (64-bit)` as I tested personally with the below screenshot.

![Screen Shot 2020-01-13 at 10 49 35](https://user-images.githubusercontent.com/24992535/72246248-95cfc200-35f2-11ea-9e10-d42019167b19.png)

as explained in [the following answer](https://support.google.com/chrome/thread/16855096?hl=en&msgid=25241076) and [in the following stackoverflow discussion](https://stackoverflow.com/a/50662069/7295772), the problem can be solved by 

**by turning off "Use hardware acceleration when available" in my Chrome settings**

**Comment by bitfriend** [comment]
I just mean there seems to be problem in devDependencies.

```
  "devDependencies": {
    "@babel/core": "^7.7.4",
    "@babel/runtime": "^7.7.4",
    "babel-jest": "^24.9.0",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.57.0",
    "react-test-renderer": "16.8.3"
  },

```

**Comment by fabriziobertoglio1987** [comment]
`jest`/`react-test-rendered` are used to run test cases, `babel` to compile `es6` to `es5` so I don't see any reason why they would influence and cause this issue.

Maybe the issue is connected with metro bundler which could be responsible for starting the debugger process?

you should check `"Use hardware acceleration when available"` is in your chrome settings and tell us if it changes depending on those dependencies

**Comment by bitfriend** [comment]
Of course, when "Use hardware acceleration when available" is off, tooitip is displayed.
But some developers may need this options.
Currently, developers can use old devDependencies to display debug tooltip.
If problem in new dependencies is fixed, they can work without change of devDependencies or chrome setting ("Use hardware acceleration when available").
I hope you will read my first post carefully.
