### ISSUE TITLE
Unable to auto reconnect back to metro server

### ISSUE THREAD

**Issue by 1nfinite** [facebook/react-native#27747]
OS Version: Windows 10
React Native version: 0.61.5

## Steps To Reproduce
1. Plug in USB cable from android device to computer
2. Run `react-native run-android`
3. Unplug cable
4. Plug cable back

**Describe what you expected to happen:**
Currently need to rerun ` react-native run-android` command after unplug and plug cable to connect back to metro server. Expect auto reconnect.

**Comment by fabriziobertoglio1987** [comment]
To solve this issue I would ask for your collaboration to break down the problem:

1) what is the output of the command `adb devices` once you reconnect the device?
2) are you using `USB 2.0` or `3.0`?
3) consider reviewing issues/documentation on [`facebook/metro`](https://github.com/facebook/metro/issues), [`react-native-community/cli`](https://github.com/react-native-community/cli) and reviewing [their documentation](https://facebook.github.io/metro/docs/en/getting-started)

If this issue is not connected with `metro`, but with the [`react-native cli`](https://github.com/react-native-community/cli) consider following this steps from the [doc page](https://facebook.github.io/react-native/docs/running-on-device#connecting-to-the-development-server-1):

1) running `adb -s <device name> reverse tcp:8081 tcp:8081` where device name is taken from output of `adb devices`
2) as [by this instructions](https://facebook.github.io/react-native/docs/running-on-device#method-2-connect-via-wi-fi) explicitly set the ip of your metro server. 
Run `ifconfig` or the windows alternative to get your machine ip and set that ip in your android phone. 

>Open the in-app Developer menu. 5. Go to **Dev Settings** → **Debug server host & port for device**. 6. Type in your machine's IP address and the port of the local dev server (e.g. 10.0.1.1:8081). 7. Go back to the **Developer menu** and select **Reload JS**. 

3) `react-native run-android [options]` takes an option parameter as explained in the [docs](https://github.com/react-native-community/cli/blob/master/docs/commands.md#run-android) which could help you fix this issue

4) Please reproduce this issue and include the relevant output from [`react-native log-android`](https://github.com/react-native-community/cli/blob/master/docs/commands.md#log-android)
