### ISSUE TITLE
Linking local React Native Library requires an entry in `dependencies` in `package.json`

### ISSUE THREAD

**Issue by graphan** [facebook/react-native#27740]
Linking local React Native Library requires an entry in `dependencies` in `package.json`.

### Steps To Reproduce

Let's imagine we have the following code structure:
```
- components
- native_app
- node_modules
```
where:
- `node_modules` contains a React Native Library hoisted from `components`
- `native_app` contains a React Native App

then you can link the library with the app running:
`cd native_app && react-native link react-native-webview`

**But**, this requires the following entry in `native_app/package.json`:
```
...
"dependencies": {
   "react-native-webview": "file:./../node_modules/react-native-webview"
}
...
```

And this is a problem, because for monorepo projects both `yarn install` and `lerna bootstrap` are failing with an error of not existing file.

**React Native version:**
```
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 151.45 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 23, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.2
      System Images: android-27 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

The issue is mentioned also here: https://github.com/yarnpkg/yarn/issues/7678#issuecomment-573331670

**Comment by fabriziobertoglio1987** [comment]
thanks @graphan for opening the issue and please let me clearify a couple of doubts that I have related to your post:

1) The structure of your project is:

```
- components
- ios
- android
- node_modules
```
from the root of your project you run `react-native link <your library>`

2) Since `react-native@0.60` you don't run anymore `react-native link` command
3) The native files managing dependencies changed syntax between `rn-0.59`-`rn0.60`. You can see [the full `git-diff` of the ios/android files at react-native upgrade helper](https://react-native-community.github.io/upgrade-helper/?from=0.59.10&to=0.60.6) 

in particular `rn-0.59` android file `MainApplication.java` was using the following syntax

```java
public class MainApplication extends Application implements ReactApplication {
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage()
      );
```

`rn-0.60.5` is using 

```java
public class MainApplication extends Application implements ReactApplication {
    @Override
    protected List<ReactPackage> getPackages() {
      @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
      // Packages that cannot be autolinked yet can be added manually here, for example:
      // packages.add(new MyReactNativePackage());
      return packages;
    }
```

you can manually add packages using `package.add(new YouNativeModule());`

4) `react-native-webview` is compatible with `react-native 0.60` so no need to do the linking
I have `rn-webview` installed without linking in my mobile app 

My [`package.json`](https://github.com/fabriziobertoglio1987/surf-react-native/blob/master/package.json#L50)

My [podfile](https://github.com/fabriziobertoglio1987/surf-react-native/blob/master/ios/Podfile) and [MainApplication.java](https://github.com/fabriziobertoglio1987/surf-react-native/blob/master/android/app/src/main/java/com/surfapp/MainApplication.java#L30)

5) If you are having issues with automatic linking I suggest you to read about `manual linking` for both ios and android

**Comment by graphan** [comment]
Thank you @fabriziobertoglio1987 for the help. 🙏 

The thing is that I need to keep a structure of the project as mentioned in the first post, so to be more specific it is:
```
- components
- native_app
---> ios
---> android
- node_modules
- web_app
```
Then, we can share components between web and native apps easily.

In this case, I would leave the option for running: `react-native link`

However, the command could accept a relative path to a library, so that we don't have to add anything in `dependencies` in `package.json` and then it would result in the following code:
```java
public class MainApplication extends Application implements ReactApplication {
    @Override
    protected List<ReactPackage> getPackages() {
      @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
      // Packages that cannot be autolinked yet can be added manually here, for example:
      packages.add(new MyReactNativePackage());
      packages.add(new MyReactNativePackage2());
      return packages;
    }
```

What do you think about that?
