### ISSUE TITLE
VirtualizedList - on list update, app slow perform.

### ISSUE THREAD

**Issue by avneesh30** [facebook/react-native#27791]
React Native version: 0.61

Hi React-Native team,

I have used VirtualizedList, add the device in the list on scanning Bluetooth and also update the list, according to device status on Bluetooth scan.
I have added approx 250+ devices. My problem is, on the update list, my app performance very slow, scroll smooth but touch event not work properly. 

code : -
```
<VirtualizedList
            data={items}
            extraData={items}
            keyExtractor={this._keyExtractor}
            initialNumToRender={10}
            maxToRenderPerBatch={10}
            renderItem={(item) => this._renderItem(item)}
            getItemLayout={this.getItemLayout}
            windowSize={10}
            //ItemSeparatorComponent={this.renderSeparator}
            ListEmptyComponent={() => {
                return (
                    <View>
                        <View>
                            <Text>{`Data Not Found`}</Text>
                        </View>
                    </View>
                )
            }}
            ListFooterComponent={() => {
                return null
            }}
            ListHeaderComponent={() => {
                return null
            }}
            getItem={(data, index) => {
                return data[index]

            }}
            getItemCount={(data, index) => {
                let toReturn = 0;
                if (data) {
                    toReturn = data.length;
                }
                return toReturn;
            }}
            onEndReached={(info) => {
                // console.log('onEndReached, info=', info);
            }}
            onViewableItemsChanged={(info) => {
                // console.log('onViewableItemsChanged, info=', info);
            }}
        />
```

![Screenshot_20200117-112929](https://user-images.githubusercontent.com/12480358/72588594-d8f5a200-391e-11ea-91ea-163a65ff7a1c.jpg)

**Comment by emilisb** [comment]
That is because your code is not optimized. You use inline functions for renders, meaning a new instance of a function is created and all items are re-rendered every time something changes. React has to re-render all your elements, even though only some of them change.

Instead of inlining functions like this:
```
renderItem={(item) => this._renderItem(item)}
ListFooterComponent={() => {
    return null
}}
 ListHeaderComponent={() => {
    return null
}}
....................
onEndReached={(info) => {
    // console.log('onEndReached, info=', info);
}}
```

pass a reference to same function like this:
```
renderItem={this._renderItem}
ListFooterComponent={this.renderFooter}
ListHeaderComponent={this.renderHeader}
........................
onEndReached={this.onEndReached}
```

Then, to optimize renders, in your renderItem function return a PureComponent:
```
class Device extends React.PureComponent {
........
}

_renderItem = (item) => {
    return <Device name={item.name} date={item.date} someOtherProp={item.blahBlahBlah} />
}
```

Make sure only items that have changed are re-rendered. You can use React debugger to find unnecessary rendered component. Alternatively, you can use `@welldone-software/why-did-you-render`

You can read more about React optimization here:
https://medium.com/wix-engineering/two-mistakes-in-react-js-we-keep-doing-over-and-over-again-b1aea20fb3f0
