### ISSUE TITLE
(iOS) Placeholder in TextInput do not placed in center with textAlign = center

### ISSUE THREAD

**Issue by ObidosDev** [facebook/react-native#27899]
React Native version: 0.61.5
iPhone 7
iOS 13.3

## Steps To Reproduce
Code below

Describe what you expected to happen:
Placeholder should be at center of the TextInput, but for some reason it is place only last symbol to center and other part on left side

Snack, code example, screenshot, or link to a repository:
`text: {
    includeFontPadding: false,
    width: 60,
    backgroundColor: 'red',
    fontSize: 13,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: 0,
    textAlign: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    color: 'grey'
  },`

`<TextInput
key={'searchFieldKey'}
        ref={this._searchTextInputRef}
            style={styles.text}
            placeholderTextColor={'grey'}
            placeholder={'Search'}
            underlineColorAndroid={'#00000000'}
            autoCorrect={false}
            autoCapitalize={'none'}
            clearButtonMode={'always'}
            returnKeyType={'done'}
          />`

![photo_2020-01-29 21 12 51](https://user-images.githubusercontent.com/16224235/73389104-25a48a00-42dc-11ea-94b0-cfb5e1041826.jpeg)

**Comment by pritikum94** [comment]
@ObidosDev 1: try to increase TextInput width . eg: 120. SO that your placeholder will get sufficient space to get displayed. 
2: Also, as you have given clearButtonMode={'always'}, you are allowed to type input/show placeholder within total width- (cleatButton width). 
This is the reason its not showing your placeholder in center

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-01-30 at 18 23 23](https://user-images.githubusercontent.com/60466789/73451465-af606000-438d-11ea-9cc8-5bc1c4aefde5.png)
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-01-30 at 18 23 25](https://user-images.githubusercontent.com/60466789/73451467-aff8f680-438d-11ea-945b-2817235cf91f.png)

**Comment by subbotnik-dinarys** [comment]
@pritikum94 but 60 it is enough for word 'Search', but it is cropped. Ok, now it is clear about space on left side (not visible)

**Comment by ObidosDev** [comment]
@pritikum94  but 60 it is enough for word 'Search', but it is cropped. Ok, now it is clear about space on left side (not visible)
