### ISSUE TITLE
 Sectionlist component works very slowly with mobx

### ISSUE THREAD

**Issue by frtlec** [facebook/react-native#27961]
**Description:**
Hi, I haven't been able to overcome this problem despite trying a lot

I have add / delete buttons for each element of the SectionList component.

these buttons move according to the property of the object
`{item.btnLevel == 0 ?...add button:..delete button}`

These add and remove events make changes to item.btnLevel in the store.
however, annoying waiting delays occur when these buttons are pressed
for example, bearable delays for the top 10 items of the list, but the problem increases as the list grows

Sometimes JS drops to FPS -2 in developer mode, 
For this I called the list 10 ar 10 ar, but this somewhat reduces the problem

this issue was not a solution either
https://facebook.github.io/react-native/docs/optimizing-flatlist-configuration

I share the codes below (github repository) 

React Native version:
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
    Memory: 7.59 GB / 15.92 GB
  Binaries:
    Node: 11.6.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.5.0-next.0 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 25, 27, 28
      Build Tools: 28.0.3, 29.0.2
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5791312
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
      mobx: "^5.15.4",
   mobx-react: "^6.1.4",

## Expected Results

why not fluent and fast, 
It shouldn't be so slow.Help:( 

## Snack, code example, screenshot, or link to a repository:

https://github.com/frtlec/SectionListMobx.git

**Comment by jeremy-deutsch** [comment]
This is likely an issue with the code, not with React Native.

However, have you tried profiling your app's performance? If the problem lies with too many components re-running, you can use the [Devtools profiler](https://reactjs.org/blog/2018/09/10/introducing-the-react-profiler.html) to check which components are being re-run when you add or remove a list item. Remember to use Devtools v3, since v4 isn't compatible with React Native yet!

Good luck!
