### ISSUE TITLE
[IOS: Voiceover]: Incorrect narration for Switch in React Native 0.61 version

### ISSUE THREAD

**Issue by IshaTyagi** [facebook/react-native#27989]
Description:
VoiceOver: ‘0 button’ when switch is on off mode. When we double tap on it, it is getting ‘On’ mode and narrating as ‘1’.

Also, 0 and 1 are coming in Value field of accessibility inspector tool of Xcode.

![image](https://user-images.githubusercontent.com/30119136/74023301-5912a300-49c5-11ea-81ed-9035806ab39d.png)

React Native version: 0.61

## Expected Results
 It should narrate off and on

**Comment by hramos** [comment]
Can you make sure to run `react-native info` and paste the output into your issue? Then we'd need to see an example of the code used to reproduce this, as well as a list of steps. This is all covered in the issue template.

**Comment by boggsey** [comment]
I have the same issue, so providing more information below:

## React Native Info
```
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 550.31 MB / 16.00 GB
    Shell: 5.6 - /usr/local/bin/zsh
  Binaries:
    Node: 12.3.1 - ~/.nvm/versions/node/v12.3.1/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.3.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 26.0.0, 26.0.3, 28.0.3
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native: 0.60.4
```

## Steps To Reproduce
- Clone https://github.com/boggsey/switch-voice-over
- Run the project in Xcode
- Open the Accessibility Inspector
- Run Voice Over on the Switch element
- Voice Over reads a value of 0 - Change Switch value to true in order to get a Voice Over value of 1
- Trait reads "Button"

## Expected Results
- Voice Over value should read "On" or "Off".
- Trait should read "Switch"

I admit that these are just my opinions but 0 and 1 do not seem like meaningful values for visually impaired users. Also, why have an accessibility role of Switch if "Switch" is never read?

**Comment by smjurek** [comment]
The issue persists after upgrading to 0.62.2

**Comment by danielimmke** [comment]
I'm also experiencing this issue

**Comment by boggsey** [comment]
I'm providing a screenshot of the Layout in Flipper. You can see that `UIAccessibilityTraitButton` is true, `isAccessibilityElement` is true and `accessibilityValue` is either 0 or 1. Currently, the switch reads `Fragrance Status Toggle, 0, Button`

![Screen Shot 2020-08-31 at 7 16 25 PM](https://user-images.githubusercontent.com/1815842/91777783-bf0f8380-ebbe-11ea-8b8b-9a379355bc18.png)

It seems as though this is not inheriting the UIAccessibilityTraits of a Switch per some of the reading I've been doing in this thread. https://stackoverflow.com/a/52825111/1052437 - I don't know that much about switches, but I'm going to keep looking for more information.

**Comment by boggsey** [comment]
Coming back to this after some time to leave a note that this may actually be an issue with the OSX Accessibility Inspector. I reviewed accessibility with a few actual iOS devices and the component was read as Switch instead of Button. I haven't gone back to check to see if this was an issue that was resolved with an iOS upgrade, though. Are any of you able to test this with an actual device now?
