### ISSUE TITLE
[ios] Argument list too long compilation error for React Native 0.11

### ISSUE THREAD

**Issue by aksonov** [facebook/react-native#2799]
After upgrade, got this error (it was ok with 0.10.1)
```
Argument list too long: recursive header expansion failed at /Users/aksonov/Documents/PZ/node_modules/react-native/node_modules/yeoman-environment/node_modules/globby/node_modules/glob/node_modules/minimatch.
```

**Comment by mkonicek** [comment]
Thanks for reporting! Can you post the full stack trace please?

**Comment by aksonov** [comment]
It is compile error, not runtime, i don't see any stack trace.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/ios-argument-list-too-long-compilation-error-for-react-native-011

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
