### ISSUE TITLE
Problem with TextInput lineHeight on iOS

### ISSUE THREAD

**Issue by tohellandback** [facebook/react-native#28012]
Hi, guys! Did someone facing the same issue with lineHeight on iOS ? any solution ? 

React Native version: "0.61.5"

Android:
<img width="478" alt="Screenshot 2020-02-10 at 16 21 04" src="https://user-images.githubusercontent.com/53395835/74153462-bdca3980-4c21-11ea-899d-0480f2002004.png">

iOS:
<img width="429" alt="Screenshot 2020-02-10 at 16 21 13" src="https://user-images.githubusercontent.com/53395835/74153477-c458b100-4c21-11ea-8f6a-113ad158c1c5.png">

<img width="340" alt="Screenshot 2020-06-03 at 20 23 56" src="https://user-images.githubusercontent.com/53395835/83668180-3b062980-a5d8-11ea-8d3d-a45380542c5a.png">

Code: 
```
import React from 'react'
import { View, TextInput, StyleSheet } from 'react-native'

export default function Example () {
  return (
    <View style={styles.wrapper}>
      <TextInput style={styles.input} placeholder='Hello World!' />
    </View>
  )
}

const styles = StyleSheet.create({
  wrapper: {
    height: '100%',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'lightgray'
  },
  input: {
    height: 32,
    minWidth: 120,
    lineHeight: 32,
    borderWidth: 1,
    backgroundColor: 'white',
    padding: 0,
    fontSize: 14
  }
})
```

same on 0.62.2 version

rn info: 

```
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 404.19 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.2.0 - ~/.nvm/versions/node/v14.2.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v14.2.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.13.1 => 16.13.1
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by mikelros** [comment]
Same here. Hope it's fixed soon 👍

**Comment by konstantin-shkel** [comment]
same on 0.62.2

**Comment by Esxiel** [comment]
Here to confirm that the problem persists in 0.63.0 as well

**Comment by askel4dd** [comment]
Applied changes from https://github.com/facebook/react-native/pull/29262 using [patch-package](https://www.npmjs.com/package/patch-package) to fix this

**Comment by saskaak** [comment]
@askel4dd That doesn't seem to fix the issue. 

It seems that the problem only happens on iOS with large `fontSize`-`lineHeight` differences. (In the original example `fontSize: 14` and `lineHeight: 32`.) The workaround for me right now is to set `lineHeight: null` and use a wrapper `View` to achieve correct positioning.

**Comment by dann1609** [comment]
the issue is still present.

**Comment by filiptdz** [comment]
For the past few years I've just avoided using `lineHeight` on React Native, as it's more trouble than it's worth. However, while you can add padding to a single line there's no decent hack for multiline text. Hopefully there's a solution soon.

**Comment by Akronae** [comment]
Same boat here

**Comment by Akronae** [comment]
> same on 0.62.2
> 
> rn info
> 
> System: OS: macOS 10.15.4 CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz Memory: 102.72 MB / 16.00 GB Shell: 5.7.1 - /bin/zsh Binaries: Node: 12.15.0 - /usr/local/bin/node Yarn: 1.22.4 - /usr/local/bin/yarn npm: 6.13.4 - /usr/local/bin/npm Watchman: 4.9.0 - /usr/local/bin/watchman Managers: CocoaPods: 1.8.4 - /usr/local/bin/pod SDKs: iOS SDK: Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1 Android SDK: Not Found IDEs: Android Studio: 3.5 AI-191.8026.42.35.6010548 Xcode: 11.2.1/11B53 - /usr/bin/xcodebuild Languages: Java: 10.0.2 - /usr/bin/javac Python: 2.7.15 - /usr/local/bin/python npmPackages: @react-native-community/cli: Not Found react: 16.11.0 => 16.11.0 react-native: 0.62.2 => 0.62.2 npmGlobalPackages: _react-native_: Not Found

The author seems not to be active anymore, however plenty have provided some versions, and I would say that this happens on any version..

**Comment by fabriziobertoglio1987** [comment]
I corrected the formatting. The issue environment info were commented.

**Comment by fabriziobertoglio1987** [comment]
### What is the root cause of that problem?
The issue is caused by adding lineHeight to TextInput (Issue https://github.com/facebook/react-native/issues/28012).

### What changes do you think we should make in order to solve the problem?

Fix react-native TextInput (iOS) font metrics (descent) to avoid cutting text when setting the lineHeight ( https://stackoverflow.com/a/27631737/7295772).


1) react-native TextInput is just a wrapper around the iOS API [UITextField](https://github.com/facebook/react-native/blob/247a913af000aa5912ef9acfca8a834a17c28f59/packages/react-native/React/Fabric/Mounting/ComponentViews/TextInput/RCTTextInputComponentView.mm#L69)
2) the TextInput text is styled with [NSAttributedString](https://developer.apple.com/documentation/foundation/nsattributedstring) 


The issue only reproduces with TextInput, but not with Text, while both manage text style using the same API [RCTAttributedTextUtils](https://github.com/facebook/react-native/blob/33ebb5d6365c3dd5d5214afc42c373d265280e27/packages/react-native/ReactCommon/react/renderer/textlayoutmanager/platform/ios/react/renderer/textlayoutmanager/RCTAttributedTextUtils.mm#L421).

The text is cut when setting the lineHeight prop. The TextInput component sets the [lineHeight](https://github.com/facebook/react-native/blob/291f79948e4b2e904a091972811fa00c0bbc60c2/packages/react-native/React/Fabric/Mounting/ComponentViews/TextInput/RCTTextInputComponentView.mm#L196-L199
) without checking the font size of the text (RCTAttributedTextUtils#[RCTNSTextAttributesFromTextAttributes](https://github.com/facebook/react-native/blob/33ebb5d6365c3dd5d5214afc42c373d265280e27/packages/react-native/ReactCommon/react/renderer/textlayoutmanager/platform/ios/react/renderer/textlayoutmanager/RCTAttributedTextUtils.mm#L235-L240)). Text and TextInput component use shared API AttributedText to style the Text in the TextInput, but TextInput currently misses this logic ([RCTApplyBaselineOffset](https://github.com/facebook/react-native/blob/33ebb5d6365c3dd5d5214afc42c373d265280e27/packages/react-native/ReactCommon/react/renderer/textlayoutmanager/platform/ios/react/renderer/textlayoutmanager/RCTAttributedTextUtils.mm#L384-L426)). It was tested with this video (https://github.com/Expensify/App/issues/17767#issuecomment-1526631224) in the Expensify App. Changing RCTApplyBaselineOffset does not change the baseline of the AttributedText in the TextInput, but changes the baseline of the appended Text.


As we can see the Text is cut if lineHeight is lower then Text height ([image](https://user-images.githubusercontent.com/24992535/235051365-ad5f3f47-ab57-47ca-9383-b09a4f07913f.png))


Commenting the code and the Text is not cut ([image](https://user-images.githubusercontent.com/24992535/235051393-24a2e310-30f9-489c-a833-0e83a292a35b.png))

It is caused by the missing implementation in the TextInput of [RCTBaselineOffset](https://github.com/facebook/react-native/blob/33ebb5d6365c3dd5d5214afc42c373d265280e27/packages/react-native/ReactCommon/react/renderer/textlayoutmanager/platform/ios/react/renderer/textlayoutmanager/RCTAttributedTextUtils.mm#L384-L426), which correctly sets the Text baseline and avoids cutting the text



RCTTextInputComponentView generates the text with [RCTNSTextAttributesFromTextAttributes](https://github.com/facebook/react-native/blob/247a913af000aa5912ef9acfca8a834a17c28f59/packages/react-native/React/Fabric/Mounting/ComponentViews/TextInput/RCTTextInputComponentView.mm#L196-L199) instead of [RCTNSAttributedStringFromAttributedString](https://github.com/facebook/react-native/blob/33ebb5d6365c3dd5d5214afc42c373d265280e27/packages/react-native/ReactCommon/react/renderer/textlayoutmanager/platform/ios/react/renderer/textlayoutmanager/RCTAttributedTextUtils.mm#L428)

RCTBaselineOffset changes the text baseline (see the above screenshots and https://github.com/Expensify/App/issues/17767#issuecomment-1526631224) and avoids this regression with Text component, but it is not implemented for TextInput component.

- The Text is not cut while using Text component. 
- Text and TextInput components use the same API to style the text (AttributedString). 
- The Text component applies custom logic when applying lineHeight lineHeight ([RCTBaselineOffset](https://github.com/facebook/react-native/blob/33ebb5d6365c3dd5d5214afc42c373d265280e27/packages/react-native/ReactCommon/react/renderer/textlayoutmanager/platform/ios/react/renderer/textlayoutmanager/RCTAttributedTextUtils.mm#L480)). The logic modifies the text fontMetrics and avoids cutting the text.
- There is a missing implementation of RCTBaselineOffset in TextInput, which causes the regression.

**Comment by fabriziobertoglio1987** [comment]
1) Text is not correctly aligned in TextInput

https://user-images.githubusercontent.com/24992535/235340821-10b2ad06-6010-46e9-bb21-17afc688147c.png

2) Result after fixing the text baseline with hardcoded value (for testing purposes) without modifying the placeholder baseline 

https://user-images.githubusercontent.com/24992535/235340852-27a1b709-dc51-4996-9409-993544194a61.png
https://user-images.githubusercontent.com/24992535/235340930-ab521ff3-a222-4fd2-a647-a7fe7996d115.png

**Comment by fabriziobertoglio1987** [comment]
Example from Issue https://github.com/facebook/react-native/issues/28012

Text is not correctly aligned when using lineHeight and height in a TextInput.

<details><summary>Before applying the fix </summary>
<p>

<video src="https://user-images.githubusercontent.com/24992535/235421165-e1553caf-ef32-4223-8ffb-13aee320953f.mp4" width="200" />

</p>
</details>

<details><summary>After applying the fix</summary>
<p>

<video src="https://user-images.githubusercontent.com/24992535/235421377-23bbee11-adde-40de-9ded-a293f4010bbb.mp4 " width="200" />

https://user-images.githubusercontent.com/24992535/235421238-302c1cd6-806a-491d-9321-eeb03815a9b5.mp4
</p>
</details>

**Comment by bryanltobing** [comment]
Is there a workaround for this? still happening in RN `v0.72.3`

**Comment by kimjson** [comment]
@bryanltobing you can try applying [this fix](https://github.com/facebook/react-native/pull/38359/files) using [patch-package](https://www.npmjs.com/package/patch-package)
