### ISSUE TITLE
[0.62.0-rc.2] console.warn while enabling Logbox causes App crash in iOS

### ISSUE THREAD

**Issue by Naturalclar** [facebook/react-native#28086]
Description:

Using `console.warn` while having Logbox on with `unstable_enableLogBox` causes iOS to crash.
`console.log`, or `console.error` does not cause this problem.
It's working fine on Android.

React Native version:

    Run `react-native info` in your terminal and copy the results here.
```
npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Memory: 75.79 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.1 - /var/folders/fd/m5mq98bs7k78g706wfysdngc0000gn/T/fnm-shell-2082864/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.12.1 - /var/folders/fd/m5mq98bs7k78g706wfysdngc0000gn/T/fnm-shell-2082864/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 26, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.0-rc.2 => 0.62.0-rc.2
```

## Steps To Reproduce

    Provide a detailed list of steps that reproduce the issue.
    Issues without reproduction steps or code are likely to stall.

1. npx react-native init RNTest --version 0.62.0-rc.2
2. add `require('react-native').unstable_enableLogBox();` in `index.js` in root.
3. add `console.warn('Test Warning') inside `App.js` before return.
4. react-native ios

## Expected Results

- iOS to not crash

## Snack, code example, screenshot, or link to a repository:

Repo with minimal code for repro: 
https://github.com/Naturalclar/RNTest

**Comment by rickhanlonii** [comment]
Hey @Naturalclar, thanks for filing and for proving the repro repo.

The root cause here is that the FLEXNetworkObserver that Flipper DevTools use to inspect network requests does not work with the base64 encoded image data that LogBox uses for the close icon. If you disable the images in LogBox, there's no crash:

![Screen Shot 2020-02-19 at 12 04 06 PM](https://user-images.githubusercontent.com/2440089/74832772-f2b84980-530f-11ea-9ab7-323b0aaf6260.png)

Here's the crash:

![Screen Shot 2020-02-19 at 12 01 14 PM](https://user-images.githubusercontent.com/2440089/74832790-fcda4800-530f-11ea-80b9-1d4b378dc120.png)

We're actually already switched these base64 images over to resource files on master, so we can cherry pick that to 0.62 to fix!

**Comment by rickhanlonii** [comment]
[Cherry-picked](https://github.com/facebook/react-native/commit/90e21dfd6558ea235b636c80e6a79305a48dc622) to 0.62 and confirmed that this is fixed:

![Screen Shot 2020-02-19 at 12 13 57 PM](https://user-images.githubusercontent.com/2440089/74833464-6a3aa880-5311-11ea-9f80-037600ec5fa8.png)
