### ISSUE TITLE
new Date('01/30/2020') is different on android and ios

### ISSUE THREAD

**Issue by Patys** [facebook/react-native#28097]
Description:
`new Date('01/30/2020')` is NaN for android without debug. 

React Native version:
  npmPackages:
    react: 16.12.0 => 16.12.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1
    react-native-create-library: 3.1.2
    react-native-git-upgrade: 0.2.7

## Steps To Reproduce
Make console logs:
```
console.log('01/30/2020')
console.log(new Date('01/30/2020'))
```
Android with debug or iOS:
```
LOG  01/30/2020
LOG  2020-01-29T23:00:00.000Z
```
Android without debug:
```
 LOG  01/30/2020
 LOG  Date { NaN }
```

## Expected Results
Same as iOS so:  2020-01-29T23:00:00.000Z

**Comment by hramos** [comment]
React Native uses `JavaScriptCore.framework` on iOS. Since this is provided by the OS, the specific version is tied to the iOS version. It will differ across iOS 11, iOS 12, and iOS 13 devices. On Android, the JSC version is pinned with each React Native version (or you can [use Hermes](https://facebook.github.io/react-native/docs/hermes)). Furthermore, when debugging is enabled, your app is using Chrome's JavaScript VM (V8) instead.

The recommendation here is to use a third party date manipulation library instead of relying on the built-in `Date`, due to the differences in behavior across JavaScript VMs.
