### ISSUE TITLE
android sdk doesn't exist

### ISSUE THREAD

**Issue by pyaesone17** [facebook/react-native#2830]
i have got this error but sdk is exist in that path and i defined in local.properties file like this sdk.dir =/usr/local/bin/android-sdk  
* What went wrong:
A problem occurred configuring project ':app'.
> The SDK directory '/usr/local/bin/android-sdk  ' does not exist.

**Comment by foghina** [comment]
Can you please use Stack Overflow to ask questions and tag them with react-native?

http://stackoverflow.com/questions/tagged/react-native

This helps us keep track of bugs that need to be fixed in Github issues.

**Comment by AndrewBestbier** [comment]
@pyaesone17 , I got this error and it was because I had put my local.properties file in the root folder of the app. It worked when I placed it in the android folder

**Comment by pyaesone17** [comment]
I put it inside the android but it still cant find

**Comment by AndrewBestbier** [comment]
Okay, so my path was also different to the docs. My path was: sdk.dir=/usr/local/Cellar/android-sdk/24.2.

When you run the android command in your terminal, the Android SDK Manager should pop up. The path to your sdk (if you are on a mac) should be near the top of the window.

**Comment by foghina** [comment]
@AndrewBestbier the real path of the SDK is indeed `/usr/local/Cellar/android-sdk/<some-version>`. However, homebrew always symlinks the latest version as `/usr/local/opt/android-sdk`. We recommend setting `ANDROID_HOME` or `local.properties/sdk.dir` to this symlink so that when you run `brew update && brew upgrade` you automatically get the latest version in your project.

**Comment by AndrewBestbier** [comment]
@foghina Thanks :) I'll change that

**Comment by yashvekaria** [comment]
**For Linux Users**

Your app is not getting the path of android-sdk, so If you are using linux (ubuntu), than you need to add a file named "local.properties" and save it inside the android folder, which is created inside your app folder.

You need to add below line inside local.properties file, which is the path of your android-sdk lies inside your system inside system in order to run the app.

`sdk.dir=/opt/android-sdk/`

save and rerun the command *react-native run-android*

**OR**

you can open terminal, type

**sudo nano ~/.bashrc**

and paste the below path at the end of the file

**export ANDROID_HOME="/opt/android-sdk/"**

and *restart your computer* and run again *react-native run-android* after that.

**Note:- If you put set path in .bashrc file, then you don't even need to create local.properties file.**

**Comment by avorona** [comment]
@ thanks, your answer helped  me on Ubuntu
