### ISSUE TITLE
Random white or faded components on android

### ISSUE THREAD

**Issue by conleymon** [facebook/react-native#28345]
React Native version: .59 and .61
Platform: Android
Built with Expo, but same problem reported with AirBNB 

At random times, individual components render as faded or completely white on Android. This problem is not related to the splash screen. I have not been able to notice a pattern, but I did read that this was one of the problems AirBNB ran into (https://softwareengineeringdaily.com/2018/09/24/show-summary-react-native-at-airbnb/). Their solution was to disable initializing Fresco. Is there a clean way to do this? Is there any work around otherwise?

Thanks,
Conley

## Steps To Reproduce
Unfortunately, the problem is not reliably reproducible. But it seems prevalent enough for the RN maintenance team to address, none the less.

## Expected Results
Non-faded components

## Snack, code example, screenshot, or link to a repository:
Again, not reproducible

**Comment by safaiyeh** [comment]
Hi @conleymon the team would need a repo that demonstrates the issue in order to investigate this. Could you provide a repo and a way to get it to happen? For example, "refresh this screen 10 times and you see it 1/10.."

Also can you include your react native environment info?

**Comment by DatConley** [comment]
Hi, I've not had time to get a working reproduction up, but I have narrowed the problem down on my project to a conflict between onLayout and LayoutAnimation.configureNext. basically, it seems like when onLayout is fired before the layoutAnimation is completed the render is abandoned at whatever state it was in when onLayout was called. That's why there are varying degrees of opacity when it happens. My environment is RN .61, Using react-navigation 4, expo 37, on Android 9
