### ISSUE TITLE
[iOS][NavigatorIOS] - Drag gesture area is too large - need advice on where to fix this.

### ISSUE THREAD

**Issue by jaygarcia** [facebook/react-native#2840]
IIRC, I wrote an issue for this before, or mentioned it in another but cannot find any trace.

I'm digging into RCTNavigator.m and its related manager and I can't figure out how the gesture area is configured at the top.  It seems that the drag-down gesture area should be constrained to some size that any developer should be able to set (such as a top-toolbar or a NavigatorBar).

However, it's some *large* value that is bleeding into my apps' View area (see below).  Any direction on how I can work through this, would be appreciated.  

![drag](https://cloud.githubusercontent.com/assets/180031/9961912/12589088-5df1-11e5-8d56-1f40e4003b34.gif)

**Comment by ide** [comment]
Agreed that making this programmatically configurable would be good. Really depends on the the design of the product and it's too early for Navigator to try and anticipate all use cases.

I think it's controlled in the SceneConfig so you could try looking there first.

**Comment by jaygarcia** [comment]
Thanks @ide. I'll dig in.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/iosnavigatorios-drag-gesture-area-is-too-large-need-advice-on-where-to-fix-this

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
