### ISSUE TITLE
Unable to link resources like fonts using autolinking in v0.62.0 

### ISSUE THREAD

**Issue by ajaybhatia** [facebook/react-native#28430]
In RN v0.62.0 the resources are not getting autolink even after creating react-native.config.js with proper assets path. 

Fix right now (on android) is to manually place all assets in android/src/main/res. Don't know about iOS because I only use android setup.

**Comment by harshvitra** [comment]
**Works for ios**

### For android - 
The path where react-native link stored the fonts was - `android/src/main/assets/fonts`
Path should be - `android/app/src/main/assets/fonts`

I manually changed the path and it fixed it

**Comment by thymikee** [comment]
@harshvitra this should be fixed in the latest version of React Native CLI (v4.5). 
Please [update the `@react-native-community/cli`](https://github.com/react-native-community/cli#updating-the-cli) to the latest version. 
Furthermore, if you find issues with autolinking, please file the issue here: https://github.com/react-native-community/cli
