### ISSUE TITLE
Vibration.vibrate API with mandatory parameter on IOS

### ISSUE THREAD

**Issue by Gerlison** [facebook/react-native#28440]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Following the Doc, [here](https://reactnative.dev/docs/vibration), all **vibrate** method parameters are optional, but on v0.62 of react-native, this parameters are treated as mandatary. An error is thrown in case of not passing that

## React Native version:
react-native-cli: 2.0.1
react-native: 0.62.0

## Steps To Reproduce
Just try to use vibration on iOS without passing parameters.

## Expected Results
An Error is thrown.

**Comment by Frans-L** [comment]
Related to this: https://github.com/facebook/react-native/issues/27920

There is already PR about it https://github.com/facebook/react-native/pull/27951 that is published in February. Unfortunately, it may have been forgotten because Covid-19. 

Hopefully, the patch will be released as soon as possible. The vibration is currently unusable.
