### ISSUE TITLE
react-native init can't use in China

### ISSUE THREAD

**Issue by WG-Com** [facebook/react-native#2845]
```sh
react-native init hello
This will walk you through creating a new React Native project in /Users/username/hello

downloading all the time 

```
Is there any other way?

**Comment by mkonicek** [comment]
You need to be able to access:
https://www.npmjs.com/
https://bintray.com/bintray/jcenter

Can you please use Stack Overflow to ask questions and tag them with react-native? http://stackoverflow.com/questions/tagged/react-native

This helps us keep track of bugs that need to be fixed in Github issues.

**Comment by WG-Com** [comment]
sorry , i spent half hour to download it , and it's ok now , npmjs and bintray is normal to visit
