### ISSUE TITLE
Look into detecting Android SDK path

### ISSUE THREAD

**Issue by mkonicek** [facebook/react-native#2851]
Does installing via Google's website define `ANDROID_HOME` so that `react-native run-android` just works out of the box? If not, make it easier to get started.

**Comment by mkonicek** [comment]
See https://twitter.com/hswolff/status/644950492737617920

**Comment by mkonicek** [comment]
I'll assign this one to Felix for now because he had code in the CLI to auto-detect the SDK path.

**Comment by foghina** [comment]
Installing Android Studio does *not* define `ANDROID_HOME`. Instead it comes pre-configured to point to an internal (i.e. `/Applications/Android Studio.app/...`) SDK installation and it just writes that into new projects' `local.properties` files. Since we're generating our projects from the command line, we don't have access to that. Perhaps it's time to write an Android Studio plugin...

**Comment by mkonicek** [comment]
OK that makes sense. Maybe we could try to find the SDK under `/Applications/Android Studio.app/...` and if that fails print an explanatory message about setting `~/ANDROID_HOME` (or just link to docs so it's easier to update the message).

**Comment by roysG** [comment]
Stack in the same problem, any news ?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/look-into-detecting-android-sdk-path

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
