### ISSUE TITLE
ToolbarAndroid title and subtitle cannot be styled by StyleSheet

### ISSUE THREAD

**Issue by saidimu** [facebook/react-native#2859]
As per the [documentation](https://facebook.github.io/react-native/docs/toolbarandroid.html#content) they can only be styled via props (`titleColor` and `subtitleColor`).

It appears only the toolbar's `backgroundColor` and `height` can be styled via StyleSheet.

**Comment by andreicoman11** [comment]
cc @foghina

**Comment by foghina** [comment]
I swear I started writing a comment on this at some point, but I can't find it.

Anyway, I'd say that this is by design. The toolbar's title and subtitle appearance (anything else than color) can only be customized via style resources (see [setTitleTextAppearance]), which can only be changed by recompiling the APK. Furthermore, we don't (and probably won't) have a mapping between `StyleSheet` and Android's `TextAppearance`.

If you need advanced control over the text appearance of your toolbar, you might want to implement the whole widget in JS.

[setTitleTextAppearance]: https://developer.android.com/reference/android/support/v7/widget/Toolbar.html#setTitleTextAppearance(android.content.Context,%20int)

**Comment by lwansbrough** [comment]
Also the toolbar actions cannot have a color applied to them in my tests.
