### ISSUE TITLE
Allow exporting by assigning to 'this'

### ISSUE THREAD

**Issue by WebReflection** [facebook/react-native#2862]
Apologies in advance  'cause I cannot even test this thing right now and double check, but it is since about kinda ever that in CommonJS node modules the `this` context is the exports itself.

``` js
// this is method.js
// this === module.exports
this.method = function () {
  console.log('here I am');
};

// this is from node console
require('./method').method();
```

The reason this is historically handy is that you can have a single file that exports through `this.functionality = function () {}` and have it working both as global/window script (so that `functionality` will be globally available on the DOM, as example) and as module.

There are people filing bugs about the fact apparently React-native didn't implement the module context in such way so here I am warning few modules out there might just break for such simple, and historically assumed, reason.

By any chance this can  be fixed?

Thanks and Best Regards

**Comment by vjeux** [comment]
cc @amasad

**Comment by sebmarkbage** [comment]
For context to anyone following along about the complexities involved here. They're not obvious unless you've followed this subject carefully.

`this` was at one point supposed to refer to the global object even in ES2015 module scopes. If that was true then platform implementors like React Native trying to implement a future and backwards compatible environment would not have any way to do so.

Additionally, there was no consistent way to get to the global object in other module systems. Therefore Facebook stuck with `this` meaning the global object until this was settled.

However, ES2015 changed so that `this` at top level module scope remains undefined which means that any future ES2015 module probably won't rely on `this` having any meaning. In theory they could but in practice they won't.

That opens up the possibility for an environment to be non-compliant but backwards compatible with CommonJS. That's a subtle detail but practical.

However, to update Facebook code and the code of people using React Native we first need to write a ["codemod" script](https://github.com/facebook/jscodeshift) that codemods all uses of `this` to something else.

Now since there are no consistent way to get to the global there is no single target that we can codemod this to. There is a proposal for `System.global` but that hasn't be stabilized yet.

We could potentially rely on `self` but that has to be investigated.

If anyone wants to help out fixing this, they could start by writing and open sourcing such a codemod script that we and others can use, but we would also need to figure out if the `self` target is reliable or if we can add a polyfill for `System.global` in all these environments.

Thanks for reporting, @WebReflection

**Comment by sebmarkbage** [comment]
I think that for code that only runs in Facebook environments `global` would be fine.

**Comment by christopherdro** [comment]
@facebook-github-bot answered

**Comment by christopherdro** [comment]
@facebook-github-bot answered

**Comment by sebmarkbage** [comment]
This is not a question per say. This is still an open and important issue/bug to be solved.

**Comment by christopherdro** [comment]
@sebmarkbage Sorry about that, there was a previous bot command that never went through so I tried updating it during the triage sessions.

**Comment by jkrems** [comment]
Just run into this while trying to use `msgpack-lite` in React Native. It depends on [`int64-buffer`](https://github.com/kawanet/int64-buffer) which uses the fact that `this` points to `exports` and silently turns into `module.exports = {}`.

**Comment by lacker** [comment]
At this point it seems that this is more of a feature request than a bug so I think I should close this issue and we should just consider this to be the way that React Native imports operate for now. We would definitely be open to a PR that changes this, but it also seems like a reasonably massively breaking change so it might just get kicked around a while and then ignored. IMO the best approach would be for modules to stop relying on this behavior.
