### ISSUE TITLE
 app is crashing on startup  "RN version 0.62.x" release variant 

### ISSUE THREAD

**Issue by naved971** [facebook/react-native#28667]
react-native run-android --variant=release

![image](https://user-images.githubusercontent.com/6028491/79579568-cd11ab80-80d8-11ea-99ab-edc479de62d3.png)

**Comment by dudeinthemirror** [comment]
I had the same issue after migrating from `0.59.9` to `0.62.0`. Fixed by adding this in the `android/build.gradle` file:
```
        maven {
          // Android JSC is installed from npm
          url("$rootProject.projectDir/../src/node_modules/jsc-android/dist")
        }
```
under `allProjects`
NOTE: you might need to edit the actual path to your node_modules and you might have $rootDir instead of $rootProject.projectDir i.e.
```
 url("$rootDir/../node_modules/jsc-android/dist")
```
So allProjects looks like this:

```
allprojects {
    repositories {
        mavenLocal()
        maven { 
          // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
          url("$rootProject.projectDir/../src/node_modules/react-native/android")
        }
        maven {
          // Android JSC is installed from npm
          url("$rootProject.projectDir/../src/node_modules/jsc-android/dist")
        }
        google()
        jcenter()
        maven { url "https://www.jitpack.io" }
    }
```

**Comment by GeronimoKTT** [comment]
Apparently your issue is linked to hermes,....it's kinda usual on that version of RN.
Do you have hermes enabled?

If yes try:
`npm i hermes-engine`

1. And add this line `hermesCommand: "../../node_modules/hermes-engine/%OS-BIN%/hermes",` after `enableHermes: false ,  // clean and rebuild if changing` in **android/app/build.gradle** located in the array `project.ext.react`

2. then change your hermes path in **android/app/build.gradle** to:
`def hermesPath = "../../node_modules/hermes-engine/android/";`

3. and just in case, try making sure that after **def hermesPath** you have : `releaseImplementation files(hermesPath + "hermes-release.aar")`

Good luck

**Comment by rolivegab** [comment]
I hame the same problem, with default template project:

```
npx react-native init TestProject
cd TestProject
npx react-native run-android --variant=release
```

and app crashes, with that message
![image](https://user-images.githubusercontent.com/7359906/79639256-00981880-8161-11ea-83f5-c8e54f65f567.png)

in development mode, with npx react-native run-android, application works as usual.
using (uname -a) `Linux rolivegab 5.4.0-24-generic #28-Ubuntu SMP Thu Apr 9 22:16:42 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

Ubuntu 20.04 LTS Focal Fossa

**Comment by GeronimoKTT** [comment]
Can you try running `adb logcat *:S ReactNative:V ReactNativeJS:V` on a different terminal while doing your **....--variant-release** for me to have more infos?

**Comment by rolivegab** [comment]
I tried to run that command, but:
```
adb logcat *:S ReactNative:V ReactNativeJS:V
zsh: no matches found: *:S
```

but if I try: `npx react-native log-android`, output is:

```
npx react-native log-android
info Starting logkitty
[11:09:37] D | ReactNative ▶︎ ReactInstanceManager.ctor()

[11:09:37] D | ReactNative ▶︎ ReactInstanceManager.createReactContextInBackground()
                           │ ReactInstanceManager.recreateReactContextInBackgroundInner()
                           │ ReactInstanceManager.recreateReactContextInBackgroundFromBundleLoader()
                           │ ReactInstanceManager.recreateReactContextInBackground()
                           └ ReactInstanceManager.runCreateReactContextOnNewThread()
```

**Comment by GeronimoKTT** [comment]
Ok even `react-native log-android` will do,...now can you capture the output at the specific point where your app crashes and send it?

**Comment by rolivegab** [comment]
Thats the problem, with react-native log-android, the log is just what i sended on last comment.

I updated last comment with `adb logcat` logs, from specific parts when i open the app and it crashes.
Maybe it'll help to figure out what's happening.

**Comment by GeronimoKTT** [comment]
Ok, try adding this line `android:usesCleartextTraffic="true"` in your **AndroidManifest.xml**

But from your **logs** it looks like these lines can help understand the issue:
`04-18 11:12:53.974 15502 15502 E SoLoader: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: "/data/data/com.novizinhofornecedor/lib-main/libc++_shared.so" has unexpected e_machine: 40 (EM_ARM)`

`04-18 11:12:53.974 15502 15502 W System.err: com.facebook.soloader.SoLoader$WrongAbiError: APK was built for a different platform`   <-----This line especially.

1. So the next thing you could try is to change this line 
`def enableSeparateBuildPerCPUArchitecture = false` in your **android/app/build.gradle** to `def enableSeparateBuildPerCPUArchitecture = true`

2. Then, in the same file, try changing 
`def enableHermes = project.ext.react.get("enableHermes", true);` to `def enableHermes = project.ext.react.get("enableHermes", false);`

3. Then delete your **android/app/build** and **node_modules** folders.

4. And first, run `react-native run-android`, then after that your `react-native run-android --variant=release`.

**Comment by rolivegab** [comment]
I changed my OS from Ubuntu 20.04 LTS to fedora 31, but the problem still exist.

So, I skip step `android:usesCleartextTraffic="true"`, and changed just `def enableSeparateBuildPerCPUArchitecture = false` to `def enableSeparateBuildPerCPUArchitecture = true`

As `def enableHermes = project.ext.react.get("enableHermes", false);` already false on project, I skip that step too.

And i install NDK (side-by-side), because of https://stackoverflow.com/questions/53437653/android-studio-missing-strip-tool, but i think its unrelated...
![image](https://user-images.githubusercontent.com/7359906/79684915-52957880-820b-11ea-8a10-13c24f71bc40.png)

After delete android/app/build and node_modules -> npx react-native start --reset-cache,

1. npx react-native run-android worked
2. npx react-native run-android --variant=release worked

Thank you!

**Comment by aharon87** [comment]
I upgrade to 0.62.2 from 0.62.1 and  this implementation first line in dependencies
`    implementation fileTree(dir: "libs", include: ["*.jar"])`
to dependencies
and deleting 
        ndk {
            abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64'
        }

**Comment by evanlesmez** [comment]
@rolivegab @GeronimoKTT  Thank you! You helped me fix the libhermes.so Unsatisfied Link Error for me on React Native 0.62.2, Ubuntu 18.04.
- `android/app/build.gradle` -> `enableSeparateBuildPerCPUArchitecture = true`
- `enableHermes = false`
- NDK side by side installed `https://stackoverflow.com/questions/53437653/android-studio-missing-strip-tool `

**Comment by crrobinson14** [comment]
I found this thread while searching for the initially reported "missing libhermes" issue but solved it the opposite way some others seem to have. In my case I forced `enableHermes: true` in my `project.ext.react[]` config. This worked for me in a relatively-fresh React Native app project running RN `0.62.2`.

**Comment by Liqiankun** [comment]
@evanlesmez It solved my problem. Love you^^

**Comment by olawalejuwonm** [comment]
> I'm also having the same issue.
> 
> here's my log, when running adb logcat
> 
> ![image](https://user-images.githubusercontent.com/52759812/170093096-8a5b5b7e-9960-4286-bc86-42a6fac7dc22.png) ![image](https://user-images.githubusercontent.com/52759812/170093108-f693b5bc-6958-4468-9bbb-d8445895335c.png) ![image](https://user-images.githubusercontent.com/52759812/170093118-aacc76eb-8061-4d66-8492-6b266824ea00.png) ![image](https://user-images.githubusercontent.com/52759812/170093132-a5663d87-3402-4ea4-b7eb-e205ab7c4d96.png) ![image](https://user-images.githubusercontent.com/52759812/170093139-21d99b5a-80f3-425f-b61b-29ae80b4dd77.png) ![image](https://user-images.githubusercontent.com/52759812/170093156-c724abed-24ac-45c2-9f46-d69f7086c053.png)

@evanlesmez and others please help
