### ISSUE TITLE
[Android] Warnings of Native components not existing

### ISSUE THREAD

**Issue by luqin** [facebook/react-native#2868]
```
W/ReactNativeJS( 6077): 'Warning: Native component for "RCTModalHostView" does not exist'
W/ReactNativeJS( 6077): 'Warning: Native component for "RCTTextView" does not exist'
W/ReactNativeJS( 6077): 'Warning: Native component for "RCTTextField" does not exist'
D/ReactNativeJS( 6077): 'Running application "SampleApp" with appParams: {"initialProps":{},"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF'
```

**Comment by io3** [comment]
packager server:
```
[00:21:32] <END>   Crawling File System (6210ms)
[00:21:32] <START> Building in-memory fs for JavaScript
[00:21:32] <END>   Building in-memory fs for JavaScript (307ms)
[00:21:32] <START> Building in-memory fs for Assets
[00:21:32] <END>   Building in-memory fs for Assets (288ms)
[00:21:32] <START> Building Haste Map
[00:21:33] <START> Building (deprecated) Asset Map
[00:21:33] <END>   Building (deprecated) Asset Map (184ms)
[00:21:34] <END>   Building Haste Map (1258ms)
[00:21:34] <END>   Building Dependency Graph (8065ms)
transforming [=                                       ] 3% 9/312[00:21:48] <START> request:/index.android.bundle?platform=android
[00:21:48] <START> find dependencies
[00:21:48] <END>   find dependencies (454ms)
[00:21:48] <START> transform
transforming [========================================] 100% 312/312
[00:21:54] <END>   transform (5207ms)
[00:21:54] <END>   request:/index.android.bundle?platform=android (5680ms)
::ffff:10.0.0.4 - - [19/Sep/2015:16:21:56 +0000] "GET /flow/ HTTP/1.1" 404 18 "-" "okhttp/2.4.0"
[00:22:20] <START> request:/index.android.bundle?platform=android
[00:22:20] <END>   request:/index.android.bundle?platform=android (15ms)
::ffff:10.0.0.4 - - [19/Sep/2015:16:23:08 +0000] "GET /flow/ HTTP/1.1" 404 18 "-" "okhttp/2.4.0"
```

**Comment by corbt** [comment]
For what it's worth I get those three warnings as well in the console when running React Native on android from a mac. It hasn't seemed to cause any trouble so far though.

**Comment by marsprince** [comment]
Oh,I got the same,how to use React Developer Tools in chrome to debug my android app?

**Comment by hufeng** [comment]
no @UIProp

**Comment by LucasZheng** [comment]
I got the same,how to use React Developer Tools in chrome to debug my android app?

**Comment by zenlambda** [comment]
I think this issue may have been fixed on master (I haven't tested the latest master though):

https://github.com/facebook/react-native/commit/d1e316fce3ddd01b43ee3361bee75e07b5e460ed

**Comment by gerrywastaken** [comment]
@ide There are a lot of issues being closed without a close message.

zenlambda said "**I think** this issue **may** have been fixed (**I haven't tested** the latest master though)".

If this was the reason why it's being closed, then it would be helpful to have a mention in a close message. Anyway I don't mean to pick on you, I've seen this a lot and I do greatly appreciate all the hard work of everybody on the React Native team. The closing without a messages is just getting a little frustrating when reading tickets and I'm hoping you might be able to bring it up with the team.

On a side note. If the above commit is the fix for this bug, is it missing a fix for RCTModalHostView? I can only see an exclusion for TextView and TextField.

Again, thanks heaps for all your work.

**Comment by ide** [comment]
@gerrywastaken thanks for your feedback. sorry it's been frustrating for you. I closed this issue because of zenlambda's note and I believe you're right about RCTModalHostView so let's reopen this.

**Comment by syarul** [comment]
@zenlambda that fix does not solve the issue.

**Comment by zenlambda** [comment]
Sorry guys, clearly I missed something (cc @syarul ).

**Comment by gerrywastaken** [comment]
@ide @zenlambda All good and thanks for the responses. :+1:

**Comment by andreicoman11** [comment]
This warning appears when JS asks for a native module that does not exist. This sometimes happens when a cross-platform component asks for native modules (as was the case for TextInput - in iOS you get warnings about android native components missing, in android you get warnings about iOS native components missing). RCTModalHostView is a similar case, since it's being required from a cross-platform JS component, but the android side hasn't been open sourced yet.
We're working on having all such warnings removed, but they are just that - warnings. They don't stop anything from working properly.

**Comment by jblack10101** [comment]
Still seeing this warning when running an Android app.

**Comment by mdcsfk** [comment]
`RCTModalHostView` - which component uses it?

**Comment by cavillo** [comment]
This might be helpful

http://stackoverflow.com/a/35765665/6055518

**Comment by satya164** [comment]
Closing since this is no longer an issue with latest builds.

**Comment by rops** [comment]
We are still seeing the warning on Android with RN 0.23.1. By looking at the android jar, it does contain the needed classes though. Ideas?

**Comment by gerrywastaken** [comment]
@rops As this has been closed you will probably have to tag @satya164 in your question.

**Comment by satya164** [comment]
@rops You might be referencing the old version in your `build.gradle` file. Try running `react-native upgrade` in your project to update your files.

**Comment by rops** [comment]
@satya164 found out what the problem was. Gradle couldn't find RN from node_modules ( we moved it around ), so it was fetching it from npm, where the latest version is 20.something. Nasty!
