### ISSUE TITLE
onLayout is not getting triggered when view is transforming using Animated.View

### ISSUE THREAD

**Issue by jackyleehong** [facebook/react-native#28775]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
I am trying to get the current View y position when my view is translating, but the onLayut is not getting triggered when the transform value change.

## React Native version:
System:
OS: macOS 10.15.4
CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
Memory: 47.71 MB / 16.00 GB
Shell: 5.7.1 - /bin/zsh
Binaries:
Node: 13.6.0 - /usr/local/bin/node
Yarn: 1.21.1 - /usr/local/bin/yarn
npm: 6.13.4 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
SDKs:
iOS SDK:
Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
Android SDK:
API Levels: 28, 29
Build Tools: 28.0.3, 29.0.2
System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
Android NDK: 17.2.4988734
IDEs:
Android Studio: 3.6 AI-192.7142.36.36.6241897
Xcode: 11.4/11E146 - /usr/bin/xcodebuild
npmPackages:
react: 16.9.0 => 16.9.0
react-native: 0.61.4 => 0.61.4

## Expected Results
Expect to get current Y value from onLayout function when it is translating.

**Comment by vovkasm** [comment]
It's because layout process not involved in transformations at all. Actually `Animated` can't change any properties that can change layout of component tree.

**Comment by VictorioMolina** [comment]
Have the same problem bro? Did you fix it?

**Comment by AndrewMorsillo** [comment]
@vovkasm In that case do you happen to know a method to deal with getting the size and position of elements with a transform or a parent that has a transform? 

Does that also mean that if you use a transform on a parent element the .measure and `onLayout nativeEvent.layout` will always be wrong by the amount the parent is transformed?

If this is the case -- that all children of transformed elements have incorrect onLayout and .measure results -- then it certainly needs to be put in the documentation!

**Comment by AndrewMorsillo** [comment]
So here's all of the undocumented or buggy behavior I've encountered with onLayout and .measure so far:

1. `onLayout` doesn't get called in some conditions (seemingly when an element is moved by a parent resizing)
2. `measure` returns undefined on android unless there's an `onLayout` or `collapsible: false` on the view
3. `onLayout` doesn't take transforms into account, it returns the "internal" size of the view not the size displayed on the screen
4. `onLayout` doesn't fire for animations of transforms (which is pretty much all animations since only transforms and opacity can use native driver) -- that's this issue
5. `measure` returns different values for `width` and `height` than `onLayout`. It returns scaled values if any parent is scaled as opposed to the raw values. Docs suggest the opposite. 
6. `onLayout` Will return wrong/random values during component mount in some (maybe all?) cases if the view or any parent is being animated.

These add up to big frustrations. I don't know how many hours I've lost at this point writing stuff that *should* work per the docs only to eventually figure out the above list and work around it. These things should at least be documented so others don't have to go through the same thing.

Here's an issue on the documentation repo collecting some of these things: https://github.com/facebook/react-native-website/issues/2056

**Comment by ricbermo** [comment]
hello @AndrewMorsillo thanks for sharing this. I was wondering if it could be posible to share this singleton you created? Thanks in advance

**Comment by PEZO19** [comment]
hi @AndrewMorsillo, that was really helpful, I am facing the same issues. I'd be interested too in the singleton and also what edge cases you could not solve with it (and how did you solve these?). Based on you said "I've worked around it mostly"...

**Comment by audrew** [comment]
I experience the same issue with ```onLayout```. Maybe someone has a snippet of workaround? here's my code...

```
onLayout={() => { 
                    map.current.animateCamera({
                        center: { latitude: location?.coords?.latitude, longitude: location?.coords?.longitude },
                        zoom: zoomLevel,
                        heading: 50,
                        pitch: pitchLevel,
                        altitude: 5,
                    })
                }}
```
