### ISSUE TITLE
[cli] Command `run-android` unrecognized.

### ISSUE THREAD

**Issue by xinthink** [facebook/react-native#2880]
I'm following [the quick start guide](https://facebook.github.io/react-native/docs/getting-started.html#quick-start) to create a RN app, but got the error message:

    Command `run-android` unrecognized. Did you mean to run this inside a react-native project?

and the command `react-native android` is also unrecognized.

Environment:
- node v4.0.0 (npm v2.14.2)
- RN v0.11.0

**Comment by shinriyo** [comment]
thank you `eact-native run-android` was fine

**Comment by revaret** [comment]
same issues happens to me also

**Comment by codingwithus** [comment]
same issues happens to me also

**Comment by pcqpcq** [comment]
copy directory "node_modules" to my project fixed.
you can find "node_modules" in demo project.

so i guess we should run "react-native init" or "react-native android" first.

**Comment by mkonicek** [comment]
Did you change to your app's folder? Just updated the Getting Started guide to make this clearer:
https://github.com/facebook/react-native/blob/master/docs/GettingStarted.md

**Comment by pcqpcq** [comment]
i don't think what you have updated is useful to this issue
https://github.com/facebook/react-native/commit/a0ccebc460b42ae2b2517f2118ca0cbfe00d6e98#diff-c427a522f4ea08a4c045a518ac721ce9

**Comment by xinthink** [comment]
Thanks @pcqpcq,  changing directory did fix my problem.

**Comment by mbylstra** [comment]
If you are using a version of react-native-cli less than 0.12, any error will get swallowed and you'll see the error "Command `run-android` unrecognized", regardless of what the actual error is. In my case, I was running the command from the correct directory, but lodash had somehow gotten into a corrupt state. Doing `npm uninstall lodash` and `npm install lodash` fixed the problem for me.

The react-native-cli in v0.12.0-rc will not squash errors: https://github.com/facebook/react-native/commit/373c8777f6bad3a935089bd4c59bf2e15896de63.

What I did was hack my installed version of react-native-cli (found using `which react-native`) so that the error is logged to the console.

**Comment by deeppatidar** [comment]
Command `run-android` unrecognized. Did you mean to run this inside a react-native project?
Getting same issue i have tried all possible stuff but still doesn't working

**Comment by 9mm** [comment]
Im getting same thing... it's on an existing project that I just did a fresh npm install on. It worked before, so maybe an updated package broke it?

**Comment by bmichal** [comment]
Had the same issue, it turned out I did not have /node_modules directory inside.
Running`npm install` solved the problem.

**Comment by windmxf** [comment]
miss **node_modules**  directory

**Comment by gathole** [comment]
I am learning react native and Trying to run this project https://github.com/FaridSafi/react-native-gifted-messenger

but all the time getting the error 

```
gathole$ react-native run-android
Command `run-android` unrecognized. Did you mean to run this inside a react-native project?
```

Can someone please help me out to run this project

**Comment by FrancisShi** [comment]
yep  "npm install"  fix the problem

**Comment by yashvekaria** [comment]
try **react-native android** instead of _react-native run-android_

**Comment by vhrv** [comment]
same issues happens to me also

**Comment by MayeuldP** [comment]
@vhrv Did you try 'npm install' and after that 'react-native run-android' ? Same issues for me and this, fix the problem. Maybe be patient, because 'npm install' was a bit long !

**Comment by yashvekaria** [comment]
App is not getting the path of android-sdk, so If you are using  linux (ubuntu), than you need to add a fine named "**local.properties**" and save it inside the android folder, which is created inside your app folder.

You need to add below line inside _local.properties_ file, which is the path of your android-sdk lies inside your system inside system in order to run the app.

`sdk.dir=/opt/android-sdk/`

save and rerun the command _react-native run-android_

**Comment by uriklar** [comment]
I was receiving the error:
```  Unrecognized command 'run-andriod'```

I followed [this guide](http://facebook.github.io/react-native/releases/0.23/docs/android-setup.html) but I put the line:
```
# If you installed the SDK via Homebrew, otherwise ~/Library/Android/sdk
export ANDROID_HOME=/usr/local/opt/android-sdk
```
in my .bash-profile file. When I put it in .bashrc file (and restarted terminal) the command ```react-native run-andriod``` worked.

**Comment by noopesh17** [comment]
I am was outside the project while running 'run-android' command. I just navigated to to project by below command:
cd AwesomPoject

And then run the command. It worked like a charm.

**Comment by Gapur** [comment]
Are you sure that the correct directory? Look at directory of project.

**Comment by marcellodesales** [comment]
So, I still can't get it to run... I'm trying to bootstrap it from a Docker image https://github.com/MaximeD/docker-react-native#get-image

```
dev@kauai:~/app$ echo $ANDROID_HOME 
/usr/local/android-sdk-linux

dev@kauai:~/app$ react-native run-android
Scanning 2 folders for symlinks in /home/dev/app/node_modules (0ms)
Android project not found. Maybe run react-native android first?
dev@kauai:~/app$ react-native android    
Scanning 2 folders for symlinks in /home/dev/app/node_modules (0ms)

  Unrecognized command 'android'
  Run react-native --help to see list of all available commands
```

However, I do have the command `android`...

```
dev@kauai:~/app$ which android
/usr/local/android-sdk-linux/tools/android

dev@kauai:~/app$ android version
Error: Expected verb after global parameters but found 'version' instead.

       Usage:
       android [global options] action [action options]
       Global options:
  -h --help       : Help on a specific command.
  -v --verbose    : Verbose mode, shows errors, warnings and all messages.
     --clear-cache: Clear the SDK Manager repository manifest cache.
  -s --silent     : Silent mode, shows errors only.
...
...
```

**Comment by manjeets12** [comment]
ok if you have configured your project or machine with yarn and used npm install in your project than your project will break with the same error.
solution - delete node_module flder
than use yarn install followed by react-native run-android

**Comment by doukasd** [comment]
@manjeets12 exactly, my issue is that I had used `npm install`.

Just running `yarn install` fixed the error for me.

**Comment by Mardii-D-King** [comment]
Had the same issue but then i came across this solution to run `yarn add react-native-cli`.

**Comment by Mohammed-Saeed** [comment]
Hay Gays i tried to run  react-native run-android

but my terminal told me to install npm so i did that but it give me the following Error --
 

C:\Users\MohamedSaeed>cd AwesomeProject

C:\Users\MohamedSaeed\AwesomeProject>react-native run-android
Command `run-android` unrecognized. Make sure that you have run `npm install` an
d that you are inside a react-native project.

C:\Users\MohamedSaeed\AwesomeProject>react-native android
Command `android` unrecognized. Make sure that you have run `npm install` and th
at you are inside a react-native project.

C:\Users\MohamedSaeed\AwesomeProject>npm install
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (C:\Program Files\nodejs\node_modu
les\npm\node_modules\which\which.js:14:12)
npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_mo
dules\which\which.js:69:19)
npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_mo
dules\which\which.js:81:29)
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\which\which.js:90:16
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\graceful-fs\polyfills.js:264:29
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15)
npm WARN addRemoteGit  expo/node-websql#18.0.0 resetting remote C:\Users\Mohamed
Saeed\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expo-node-websql-git
-18-0-0-17a6eb60 because of error: { Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (C:\Program Files\nodejs\node_modu
les\npm\node_modules\which\which.js:14:12)
npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_mo
dules\which\which.js:69:19)
npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_mo
dules\which\which.js:81:29)
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\which\which.js:90:16
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\graceful-fs\polyfills.js:264:29
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOGIT'
}
npm ERR! git clone --template=C:\Users\MohamedSaeed\AppData\Roaming\npm-cache\_g
it-remotes\_templates --mirror git://github.com/expo/node-websql.git C:\Users\Mo
hamedSaeed\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expo-node-websq
l-git-18-0-0-17a6eb60: undefined
npm ERR! git clone --template=C:\Users\MohamedSaeed\AppData\Roaming\npm-cache\_g
it-remotes\_templates --mirror git://github.com/expo/node-websql.git C:\Users\Mo
hamedSaeed\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expo-node-websq
l-git-18-0-0-17a6eb60: undefined
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (C:\Program Files\nodejs\node_modu
les\npm\node_modules\which\which.js:14:12)
npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_mo
dules\which\which.js:69:19)
npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_mo
dules\which\which.js:81:29)
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\which\which.js:90:16
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\graceful-fs\polyfills.js:264:29
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15)
npm WARN addRemoteGit  expo/node-websql#18.0.0 resetting remote C:\Users\Mohamed
Saeed\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-expo-node-webs
ql-git-18-0-0-9423671b because of error: { Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (C:\Program Files\nodejs\node_modu
les\npm\node_modules\which\which.js:14:12)
npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_mo
dules\which\which.js:69:19)
npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_mo
dules\which\which.js:81:29)
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\which\which.js:90:16
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\graceful-fs\polyfills.js:264:29
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOGIT'
}
npm ERR! git clone --template=C:\Users\MohamedSaeed\AppData\Roaming\npm-cache\_g
it-remotes\_templates --mirror https://github.com/expo/node-websql.git C:\Users\
MohamedSaeed\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-expo-no
de-websql-git-18-0-0-9423671b: undefined
npm ERR! git clone --template=C:\Users\MohamedSaeed\AppData\Roaming\npm-cache\_g
it-remotes\_templates --mirror https://github.com/expo/node-websql.git C:\Users\
MohamedSaeed\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-expo-no
de-websql-git-18-0-0-9423671b: undefined
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (C:\Program Files\nodejs\node_modu
les\npm\node_modules\which\which.js:14:12)
npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_mo
dules\which\which.js:69:19)
npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_mo
dules\which\which.js:81:29)
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\which\which.js:90:16
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\graceful-fs\polyfills.js:264:29
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15)
npm WARN addRemoteGit  expo/node-websql#18.0.0 resetting remote C:\Users\Mohamed
Saeed\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expo-node-websql-git
-18-0-0-8213877d because of error: { Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (C:\Program Files\nodejs\node_modu
les\npm\node_modules\which\which.js:14:12)
npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_mo
dules\which\which.js:69:19)
npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_mo
dules\which\which.js:81:29)
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\which\which.js:90:16
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\graceful-fs\polyfills.js:264:29
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOGIT'
}
npm ERR! git clone --template=C:\Users\MohamedSaeed\AppData\Roaming\npm-cache\_g
it-remotes\_templates --mirror git@github.com:expo/node-websql.git C:\Users\Moha
medSaeed\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expo-node-websql-
git-18-0-0-8213877d: undefined
npm ERR! git clone --template=C:\Users\MohamedSaeed\AppData\Roaming\npm-cache\_g
it-remotes\_templates --mirror git@github.com:expo/node-websql.git C:\Users\Moha
medSaeed\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expo-node-websql-
git-18-0-0-8213877d: undefined
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\MohamedSaeed\AwesomeProject\npm-debug.log

C:\Users\MohamedSaeed\AwesomeProject>

**Comment by Abydars** [comment]
use yarn instead of npm

**Comment by bimix** [comment]
using just Yarn command fixes it but unfortunately i have to do it always when i run the emulator and it takes time!

**Comment by slesulvy** [comment]
@doukasd Thank you

**Comment by alexandre-thauvin** [comment]
I am the same issue that all...

I'm on the correct directory (root of my project, the node_modules folder is here).
I added the export in my bashrc
I deleted the node_modules folder and I used yarn install and run "react-native run-android" and "react-native android" ...

**Comment by luizvidoto** [comment]
Delete node_modules folder and run these two commands worked for me!! 
`yarn install`
`yarn add react-native-cli`

**Comment by fuyue111** [comment]
I had the same issue when i installed react-native-action-bar, maybe the installed package broke it.
Running npm install solved the problem.

**Comment by kanhaiya8542** [comment]
navigate the **proper path** to run this command - *react-native run-android *

**Comment by pankajnvhatkar** [comment]
npm uninstall lodash and npm install lodash fixed the problem for me

**Comment by serzahke** [comment]
make sure about the android studio or other emulator be opened, when execute this common:
`react-native run-android`
