### ISSUE TITLE
load big local file crash the app

### ISSUE THREAD

**Issue by nosensezzz** [facebook/react-native#2881]
After I upgrade my ios to ios 9, my app crashed when I launch it, after debug, I found out it is because I tried to load a 5mb local json file, it did not crashed when I use ios 8.

I think it is not react native issue, but still want to ask you guys, do you experience same issue like me? how do you resolved it? ( I guess if there is not a good solution, i have to handle it on server side and just add one more api call )

**Comment by nosensezzz** [comment]
I feel when we first launch the application, there is a loading period, if we load big file there, it should be fine, so the question change to, can we load some file during the app prepare period? how can we access to that period.

like something "OnLaunch" or "AppInitial"

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/load-big-local-file-crash-the-app

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
