### ISSUE TITLE
[Android] lint failed with InvalidPackage: Package not included in Android

### ISSUE THREAD

**Issue by xinthink** [facebook/react-native#2882]
Lint task results in an `InvalidPackage` error: 
`Invalid package reference in library; not included in Android: java.nio.file. Referenced from okio.Okio.`

**Comment by alvinwoon** [comment]
+1

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-lint-failed-with-invalidpackage-package-not-included-in-android

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by antonzy** [comment]
+1
