### ISSUE TITLE
packager doesnot work after a few minutes

### ISSUE THREAD

**Issue by shipengyan** [facebook/react-native#2888]
windows10
`node node_modules/react-native/packager/packager.js`
![qq 20150920202401](https://cloud.githubusercontent.com/assets/1212932/9980732/e9750f2a-5fd5-11e5-8a8a-b3dd1bcc9068.png)

**Comment by jaygarcia** [comment]
Please add [windows] tag to this

**Comment by ide** [comment]
Good idea.

**Comment by christopherdro** [comment]
@jaygarcia @shipengyan Any updates on this?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/packager-doesnot-work-after-a-few-minutes

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
