### ISSUE TITLE
Touchables translated into view are not pressable on android

### ISSUE THREAD

**Issue by bdrobinson** [facebook/react-native#28894]
## Description
When a touchable is rendered offscreen (or possibly just outside the bounds of its parent) but moved into view using `translateX`/`translateY`, it cannot be pressed. This bug is only present on Android, and works fine on iOS.

There's been a few issues related to this that have been closed due to inactivity, so I'm opening a new one. They are:

- https://github.com/facebook/react-native/issues/27647 by @AdamGerthel
- https://github.com/facebook/react-native/issues/26219 by @lehresman (whose repro snack I copy+pasted for this issue)
- https://github.com/facebook/react-native/issues/19637 by @floriancargoet which seems very closely related, but that particular issue was fixed by https://github.com/facebook/react-native/pull/25836

(@AdamGerthel and @lehresman I'd be interested to know if you got any further debugging these issues?)

## React Native version:
0.61.2

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Open the snack https://snack.expo.io/@bdrobinson/android-offscreen-touchable-bug on an android device

## Expected Results
When you press the left/right buttons, both should be expected to respond to your touches (you can run on iOS to verify this). However, on Android only the left one responds to touches, whereas the right doesn't.

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/@bdrobinson/android-offscreen-touchable-bug (copy+pasted from https://github.com/facebook/react-native/issues/26219)

**Comment by AdamGerthel** [comment]
> (@AdamGerthel and @lehresman I'd be interested to know if you got any further debugging these issues?)

I've used workarounds to solve it in the different cases I've had this issue:

- https://github.com/react-native-community/react-native-svg/issues/1221#issuecomment-570234997
- In another issue I had, I solved it by putting an invisible view behind the touchable surface, so when the touchable was moved outside of the parent view using translate, the parent actually grew in size at the same time (but the user can not tell there's a difference).

**Comment by skay97** [comment]
@AdamGerthel I am facing a similar issue and wanted to see if you could provide some more clarification. By putting an invisible view behind the touchable surface, do you mean you wrapped the touchable opacity in a view that had no styles?
In my case, I am translating my FAB, however due to the transformations, I can no longer click the opacity. Due to which, I am having to use the `top` and `bottom` properties instead. I would have no issue utilizing those properties, it's just that I also can't use native driver without transforming.

**Comment by AdamGerthel** [comment]
@skay97 My code is too obscure for it to make immediate sense and it would take me too much time to rewrite it as a re-usable sample. Basically I first render this view: `<View style={{ height: x }} />` where `x` is the height of the view that is un-clickable on Android. I use `onLayout` on the Animated View to get the height of the view, and then pass it to the other view (which is placed "behind" the animated one). Exactly how to use these values depend on what you're trying to achieve, which transforms you're using etc.

**Comment by fabriziobertoglio1987** [comment]
This line does not take in consideration the `transformation` effect. It calculates the number of child present on the screen before applying the transformation (https://github.com/facebook/react-native/issues/27333#issuecomment-657566412)

https://github.com/facebook/react-native/blob/0060b5de559cd9c785a2a2a6c66f58088fea4dd2/ReactAndroid/src/main/java/com/facebook/react/uimanager/TouchTargetHelper.java#L114-L115

The number of child `i` is used to loop around each children of the `viewGroup` and check if the touch was done inside that `View`, but as the value `childIndex` was calculated before the `transformation`, the button `View` is not included in this loop

https://github.com/facebook/react-native/blob/0060b5de559cd9c785a2a2a6c66f58088fea4dd2/ReactAndroid/src/main/java/com/facebook/react/uimanager/TouchTargetHelper.java#L119-L122

this is the logic checking that click `x, y` was performed inside the `Button` View

https://github.com/facebook/react-native/blob/0060b5de559cd9c785a2a2a6c66f58088fea4dd2/ReactAndroid/src/main/java/com/facebook/react/uimanager/TouchTargetHelper.java#L124-L134

I need to apply the transformation before calculation the number of childrens

https://github.com/facebook/react-native/blob/0060b5de559cd9c785a2a2a6c66f58088fea4dd2/ReactAndroid/src/main/java/com/facebook/react/uimanager/TouchTargetHelper.java#L115

I'll try to prepare a pull request tomorrow

Thanks a lot
I wish you a good day
Fabrizio Bertoglio

**Comment by fabriziobertoglio1987** [comment]
https://github.com/facebook/react-native/blob/03489539146556ec5ba6ba07ac338ce200f5b0f4/ReactAndroid/src/main/java/com/facebook/react/uimanager/BaseViewManager.java#L320

The transformation is not yet applied and [getChildCount](https://developer.android.com/reference/android/view/ViewGroup#getChildCount()) will return `1`. The loop runs and does not check that onTouchEvent `x, y` coordinates are in the button area.

https://github.com/facebook/react-native/blob/0060b5de559cd9c785a2a2a6c66f58088fea4dd2/ReactAndroid/src/main/java/com/facebook/react/uimanager/TouchTargetHelper.java#L115-L119


I can detect that the child `child` has been transformed like this

https://github.com/facebook/react-native/blob/0060b5de559cd9c785a2a2a6c66f58088fea4dd2/ReactAndroid/src/main/java/com/facebook/react/uimanager/TouchTargetHelper.java#L122
```java
        Matrix childMatrix = child.getMatrix();
        Log.w("TESTING::TouchTargetHelper", "childMatrix.isIdentity(): " + childMatrix.isIdentity());
        // Logs false for ViewGroup id 0x17 - a transformation has been applied and not taked in consideration
``` 

![image](https://user-images.githubusercontent.com/24992535/87408445-c30e2480-c5c3-11ea-8f56-0c2d2fc15b80.png)

calling `setTranslationX` and re-executing the process could fix this issue, I'll be testing this afternoon.

https://github.com/facebook/react-native/blob/03489539146556ec5ba6ba07ac338ce200f5b0f4/ReactAndroid/src/main/java/com/facebook/react/uimanager/BaseViewManager.java#L324

**Comment by fabriziobertoglio1987** [comment]
My opinion is that issue https://github.com/facebook/react-native/issues/28894 and https://github.com/facebook/react-native/issues/27333 created by @bdrobinson and @AdamGerthel **should be closed**. 

Both issues do not include acceptable reproducible examples. 

@AdamGerthel in https://github.com/facebook/react-native/issues/27333 should have just applied `{ height: integer }` as his container has `height = 0`.

@bdrobinson you can just fix https://github.com/facebook/react-native/issues/28894 by specifying the correct width of the View you want to transform. The View is not clickable because you apply `width: Dimensions.get('window').width()` and then shift the View 50% to the left. After transform your View Width is 50% of the Screen.

Unluckily same and probably a duplicate of https://github.com/facebook/react-native/issues/27333#issuecomment-657566412

```javascript
const styles = StyleSheet.create({
  outerContainer: {
  },
  innerContainer: {
    flexDirection: 'row',
    width:1800,
    transform: [{translateX: -200}]
  },
});
```

If you want the ViewGroup to be clickable with a transform, you need to make sure it has the correct width. I invested a lot of time in both issues to find this mistake, so I would be thankful if you could close both issues. 

Thanks
I wish you a good day
Fabrizio Bertoglio

**Comment by bdrobinson** [comment]
Thanks for looking into it so closely @fabriziobertoglio1987! You clearly understand the problem space a lot better than I do so I'm happy to defer to your opinion to make sure that this issue doesn't cause unnecessary noise for maintainers.

However, I would question whether this is indeed an "invalid example" since it works on iOS and fails on Android?

**Comment by chaselal** [comment]
This is still an issue. Use `translateX` to position a view outside the viewport -> animate the view into the viewport using `translateX` -> the view does not receive touch. Touches pass through to the views behind the animated-in view.

**Comment by chaselal** [comment]
One use case is:

- show a list of items
- touch an item
- open a detail view that slides in from the right edge of the screen, with an animation such that the view slides into view instead of just appearing
- the view does not receive touch on Android

**Comment by AdamGerthel** [comment]
I agree that this is still an issue, and I don't agree with what @fabriziobertoglio1987 is saying either. The fact that a view is interpreted as having `height: 0` does not mean that I assigned `height: 0` to it (which I clearly haven't). My sample works in both iOS and Web, but not Android, and I'm following very basic CSS principles, which is what is expected when using React Native. The fault lies with RN/Android, not my code.

**Comment by hellogerard** [comment]
I tried all the ideas mentioned above and nothing worked.

...I found replacement touchables from `react-native-gesture-handler` and it worked right away. Drop-in replacement. Just replace your `react-native` imports with:

```js
import {
  TouchableNativeFeedback,
  TouchableHighlight,
  TouchableOpacity,
  TouchableWithoutFeedback,
} from 'react-native-gesture-handler';
```

**Comment by AnnaSearl** [comment]
I get the same issue, I want to make a dropdown，in IOS everything is OK， but android is not work, Who can help me...

**Comment by mrousavy** [comment]
I'm experiencing the same issue. It's a real bummer, because I've created a custom horizontal swiper (carousel), and `<Pressable>`/`<TouchableWithoutFeedback>` components are not pressable on android at all. The only workaround I've found so far is by using the `TouchableWithoutFeedback` export from `react-native-gesture-handler` since that does not use the JS touch responder system.

@fabriziobertoglio1987 you mentioned you'd prepare a pull request - did you find a native fix for this?

**Comment by fabriziobertoglio1987** [comment]
@mrousavy thanks for the reply 

If I still remember well my research explained in https://github.com/facebook/react-native/issues/28894#issuecomment-658262246 made me conclude that ReactAndroid will restrict touch events to parent view area available, so for example if you transform the parent view or set height/width = 0, then you can not touch the TouchableWithoutFeedback

This is included in the ReactNative Touchable docs as I explained in https://github.com/facebook/react-native/issues/27333#issuecomment-657566412

<image src="https://user-images.githubusercontent.com/24992535/101063556-358f9900-3593-11eb-943d-18dae5f23321.png" width="600" />

I may be wrong, but I don't see an easy solution for this limitation. Thanks a lot.

**Comment by paulduthoit** [comment]
Hi ! Has anyone found a solution while waiting for the problem to be resolved ? Thanks.

**Comment by lelukas** [comment]
Also, don't if anyone noticed it but the same happens with FlatLists

**Comment by TomasSestak** [comment]
Still valid issue i think

**Comment by hotaryuzaki** [comment]
> I tried all the ideas mentioned above and nothing worked.
> 
> ...I found replacement touchables from `react-native-gesture-handler` and it worked right away. Drop-in replacement. Just replace your `react-native` imports with:
> 
> ```js
> import {
>   TouchableNativeFeedback,
>   TouchableHighlight,
>   TouchableOpacity,
>   TouchableWithoutFeedback,
> } from 'react-native-gesture-handler';
> ```

yes its works.
but its has other issue, if underneath the icon has onpress so it will fire also.

**Comment by hotaryuzaki** [comment]
> I'm organizing my next tasks. Are you still interested in adopting a fix for this issue? Or have you already implemented a workaround? If you are interested, I will work on a solution. Thanks

I think this issue is an important one, because it will be raised to anyone who has a bigger icon in the middle of the bottom tab bar

**Comment by nowakowski-damian** [comment]
Hi @fabOnReact, is there any update on that issue?

I have exactly the same issue with `ReactViewGroup`. I'm using a new Fabric architecture with RN Screens. My 'ReactViewGroup' is created in JS and I use its `nativeId` to find it on the native side using `ReactFindViewUtil.findView()`.
Whenever I try to change it location using `.y `or `.translationY` it change position correctly but looses ability to be pressed (touchables still see it in the old position).

I've tried several things like:
- wrapping view in `FabricEnabledViewGroup` container to call `.updateState()` directly on the translated view, so the new coordinates will be passed to JS side
- programmatically removing view, changing it LayoutParams and adding again (hoped that new new coordinates will be passed to JS side upon the view creation)
- invoking almost any "update-related" function inside `ReactViewGroup` in hope it will update touchables coordinates on the JS side
- setting padding/margin instead of translation in hope it will fix the issue
Neither of which brought positive results...

In general it looks like moving something natively on the Android screen does not equal the PressRect bounds movement. It can be easily confirmed by adding some logs that print coordinates of view's pressable area and physical click coordinates - physical click coordinates are always outside of the view's pressable area as it remains in the old position (before the translation).

Some example logs:
`
 LOG  Region top 1168.5714111328125
 LOG  Region bottom 1265.047607421875
 LOG  Region left -3.23809814453125
 LOG  Region right 360.19049072265625
 LOG  Click Page X 226.6666717529297
 LOG  Click Page Y 866.6666870117188
`
Region top, bottom, left, right - coordinates of touchable region
Click Page X,Y - coordinates of user click

It can be fixed when replacing regular touchables with gesture-handler touchables, but it's more like a temporary workaround then a real fix, due to huge performance impact.

**Comment by bilalhasmie006** [comment]
A temporary workaround:

I was able to fix the issue where my input fields became unpressable after animations by replacing translateY with top or bottom, and translateX with left or right. This problem started after switching to the new architecture—it was working fine before.


             `<MotiView
              key="createAccountDetails"
              from={{
                opacity: 0,
                // translateY: 100,
                top: 100,
              }}
              animate={{
                opacity: 1,
                top: 0,
                // translateY: 0,
                // translateX: 0,
              }}
              exit={{
                opacity: 0,
                // translateY: 100,
                top: 100,
              }}
              style={{}}
              className="h-full flex-1 w-full"
            >
              <FormikInput
                name="email"
                autoComplete="username"
                secureTextEntry={false}
              />
              <FormikInput
                disableBuiltInState
                name="password"
                autoComplete="password"
              />

              <LinkText to="ForgotPassword" dismissKeyboard>
                forgot password?
              </LinkText>
            </MotiView>`

Try replacing translateY with top or bottom, depending on your use case.
