### ISSUE TITLE
Unrecognized platform: web error when trying to use `platform=web` on the packager

### ISSUE THREAD

**Issue by sudhirj** [facebook/react-native#2895]
Is there any reason why platform=web is unsupported on the packager? There seem to be other references in code to it being possible.

**Comment by ide** [comment]
The plan is for the packager to be moved into a dedicated repo to address this use case, so you can use the packager for web w/out downloading all of react-native. We'll ask you to resubmit your PR to that new repo when it is ready.

**Comment by darkyen** [comment]
@ide is there a chance of using a cross platform task runner like gulp for packager in future ?

**Comment by ide** [comment]
I think so but it is not a priority AFAIK.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/unrecognized-platform-web-error-when-trying-to-use-platformweb-on-the-packager

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.

**Comment by RangerMauve** [comment]
Sorry to revive this, but it seems like a pretty small fix and would make a "hybrid" approach to React-Native easy and appealing. However I don't see this being voted up enough on the product pains tracker due to it being more obscure than most of the other issues on there.

**Comment by sudhirj** [comment]
Oddly enough, there was slide by @spicyj where he talked about doing just this - wouldn't something as simple as this go a really long way towards enabling iOS+Android+Web development against the same codebase?

**Comment by aleclarson** [comment]
Are there still plans to move the `react-packager` to its own repository?

I would love to use it instead of `webpack` for my `react-native-web` project.

**Comment by ericvicenti** [comment]
cc @cpojer

**Comment by aleclarson** [comment]
> The plan is for the packager to be moved into a dedicated repo to address this use case, so you can use the packager for web w/out downloading all of react-native.

I would argue this isn't strictly necessary, since users of `react-native-web` likely have `react-native` installed as well.

Though, I still believe a `react-native-packager` repo would be beneficial to its development if it's maintained as well as the `react-native` repo is.
