### ISSUE TITLE
onChangeText calls after onSubmitEditing if auto complete has a highlighted option

### ISSUE THREAD

**Issue by special-character** [facebook/react-native#29073]
# Description
When autocomplete is enabled and has a valid option, the `onChangeText` callback fires with the autocomplete suggestion after `onSubmitEditing` has already been called. In this case, the `onChangeText` can overwrite any clearing that was done as a result of the `onSubmitEditing`. Any actions that are used as a part of `onSubmitEditing` are not up to date because the `onChangeText` with the autocorrect is called after.

## React Native version:
```
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Memory: 1.24 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Have a TextInput with autocorrect enabled
2. Add `onChangeText` and `onSubmitEditing` listeners
3. Type something on iOS that has an autocorrect option highlighted (don't manually select it)
4. Hit return 

## Expected Results
The `onChangeText` fires before `onSubmitEditing` with the autocorrect suggestion. This would make clearing the text input work and also make the `onChangeText` accurate for submitting with changed autocorrect text.

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/@notatrojanhorse/adequate-cake

**Comment by lachenmayer** [comment]
We're also affected by this - in our case, we have a chat text input box which "sometimes" does not clear text properly. This happens exactly in the scenario where an autocorrect is suggested, but not accepted by the user before submitting, as noted here.

There seems to be no way to detect whether an `onChange` event was caused by autocorrect or the user typing, so there doesn't seem to be any way of working around this for now.

**Comment by special-character** [comment]
For anyone else looking at this, I also confirmed today that I see the same thing in in expo 38 (RN 62.2).

**Comment by yenda** [comment]
I can confirm the bug, and it gets worth when you submit through a button because `onChange` is not even called.
In the case of OP, you can use state to ignore the edit after submitting
In my case with a button, I rely on a timeout on iOS to clear the input again after 100ms. 

Those are just workarounds and hopefully this gets fixed.

**Comment by bruuuuuuuce** [comment]
I can also confirm its happening for me. I am using expo version 40. The work around that I am currently using is, when I submit my text,
```
setTimeout(() => setText(''), 50);
```
wait 50ms before I clear the text input text.

**Comment by efstathiosntonas** [comment]
any updates on this one?

**Comment by dynamiccarrots** [comment]
I am also having this issue and want to avoid having a delay on submit to wait for the state to update

**Comment by janwirth** [comment]
I am experiencing this issue today.
