### ISSUE TITLE
Appearance.getColorScheme() always returns 'light'.

### ISSUE THREAD

**Issue by hearingguo** [facebook/react-native#29144]
Appearance.getColorScheme() always returns 'light'.

**React Native version:**
System:
    OS:  macOS 10.14.5
    CPU:  2.3 GHz Intel Core i5
    Memory: 16 GB 2133 MHz LPDDR3
  Binaries:
    Node: v12.16.2
    Yarn: 1.7.0
    npm: 6.14.4
    Watchman: Not Found
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4
  IDEs:
    Xcode: 10.3
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0
    react-native: 0.62.2

**Steps To Reproduce**
1、import { AppState, Appearance } from 'react-native';
2、Appearance.getColorScheme()

**Expected Results**
it always returns 'light'.

**Comment by dubiao** [comment]
And sometimes, when I add a listener by `Appearance.addChangeListener(callback)`, the `callback` calls with('dark') and immeditly calls with('light') when my app goes to background.

**Comment by troZee** [comment]
I have encountered this issue on my One Plus 7TPro

**Comment by chrisglein** [comment]
I have heard that there may be some intentional workaround for web debugging that forces light mode, but I don't know if that's documented anywhere. I'm hearing that 2nd hand.

**Comment by magrinj** [comment]
@hearingguo Happened to me too, try without debugging mode it should works !

**Comment by chrisglein** [comment]
Confirmed in the docs now:

> Note: getColorScheme() will always return light when debugging with Chrome.

https://reactnative.dev/docs/appearance#getcolorscheme

**Comment by yawnr** [comment]
@chrisglein Does this work for you right now? I'm on the latest stable release (0.63.4) and get "light" every time on a simulator and a physical device both running iOS 14.4.

I'm not debugging and must be a separate issue because I'm not getting into [this block](https://github.com/facebook/react-native/blob/master/Libraries/Utilities/Appearance.js#L63) anyway

**Comment by niklasgrewe** [comment]
@yawnr i have the same issue... did you find a solution or any workaround?

**Comment by yawnr** [comment]
@niklasgrewe actually yeah this ended up being my mistake and the color scheme was overridden to “light” in the Info.plist 🤦

**Comment by niklasgrewe** [comment]
@yawnr great I'm happy for you, however I haven't changed anything specific to iOS or Android. I have set up a new project with Expo and still it doesn't work. Do you have any idea what this could be? Interestingly, it works with the `react-native-appearance` package, which was once provided by Expo but has now been archived, because `react-native` have a build-in module for that case.
