### ISSUE TITLE
Improve LogBox error and warning tester in RNTester

### ISSUE THREAD

**Issue by rickhanlonii** [facebook/react-native#29161]
## Overview

In RNTester we have a surface to test crashes, however this only handles a few cases.

Let's improve this screen to cover all cases:

**Logging**
- Native log warnings (e.g. calls RCTLogWarn)
- Native log errors (e.g. calls RCTLogError)
- Native log fatals (e.g. calls RCTLogFatal)
- console errors
- console warnings
- React warnings

**Syntax Errors**
- LogBox syntax errors
- Native syntax errors

**JavaScript Errors**
- Unhandled JavaScript errors
- JavaScript errors thrown in render with no error boundary
- JavaScript errors thrown in render with an error boundary

**Native crashes**
- Native module errors (e.g. invalid method argument)

**Comment by mikehardy** [comment]
I have run into a couple cases where it would be nice to be able to simply inspect native RedBox state.
Something like `RedBox.isShowing(): boolean` - for library maintainers this would allow e2e harnesses to catch native errors that otherwise are invisible, e.g. https://github.com/invertase/notifee/issues/212

I can slice in my own observing implementation of LogBox.addLog and LogBox.addException but there's no way in javascript to slice in to the RedBox things at the native level, and no way to inspect RedBox state that I know of?

Something like that would allow that surface area to be more testable, along with the already-exported dismiss method and maybe in tandem with an exported "trigger redbox" method

**Comment by rickhanlonii** [comment]
@mikehardy that seem tricky - if the JS thread is running, then native errors should almost all go to LogBox. If they don't, we should make them. If the JS thread isn't running then you can't call something like RedBox.isShowing().

Long term, I'd like to see LogBox moved to a separate bundle/VM so that it's stable and can be used for all errors, even when the JS thread for the application has crashes. If we do that, then there would be no native "Redbox" only LogBox.
