### ISSUE TITLE
[Android] Custom Fonts Not Working

### ISSUE THREAD

**Issue by marcshilling** [facebook/react-native#2919]
Opening a new issue since the discussion on #1167 seems out of place (closed/iOS issue).

Custom font files are not loading on Android.

I've tried putting the .ttf (and .otf) files in both /assets and /assets/fonts (I had to the do the latter in a native Android project). And then I declare text like so:

```javascript
<Text style={{fontFamily: 'FuturaStd-ExtraBold'}}>Hello World</Text>
```

And just for the record - I'm using the same exact font files and declaring `<Text>` the exact same way in an iOS React Native project and they are working.

The workaround suggested in the referenced issue seems to simply replace the default app font with a custom font file. This is not sufficient as I need multiple different custom fonts in my app.

**Comment by mkonicek** [comment]
@andreicoman11 Is `fontFamily` supported on Android?

**Comment by andreicoman11** [comment]
We don't currently support loading custom fonts from assets.

**Comment by geolivero** [comment]
Is there a workaround that we can use. It would help a lot if this information is listed on the React Native Docs ;)

**Comment by BerndWessels** [comment]
+1 We are using Icon Fonts a lot and desperately need this feature. Unfortunately react-native-icons is not yet working on Android either :(
Please help enable this feature.
Thank you
Bernd

**Comment by mkonicek** [comment]
@BerndWessels We should have this feature but might take a while until we have bandwidth to look into it. Would you be up for sending a pull request?

**Comment by BerndWessels** [comment]
I will have a look into it, but hopefully a "real" Android expert can come up with something, since I am not very experienced on the native site.

**Comment by corymsmith** [comment]
@mkonicek I was considering doing a PR for this, since most of the typeface stuff on Android is encapsulated in CustomStyleSpan.java I'm curious on some of the core team members thoughts on where fonts should be loaded from assets. 

Since this requires a context it would have to happen elsewhere and I'm assuming we would want a global Typeface cache as well. 
```java
Typeface.createFromAsset(getContext(), "customfont.ttf");
```

**Comment by andreicoman11** [comment]
Thanks for looking into this!
You need the AssetManager from the context in order to load the custom font. You can get it by: 
1. add a ReactTextViewManager constructor that gets the context from the package
2. get the AssetManager from the context and pass it to the constructor of ReactTextShadowNode
3. give the AssetManager from the ReactTextShadowNode to the CustomStyleSpan constructor
4. get the new Typeface in the CustomStyleSpan constructor and cache it in the existing typeface cache
@kmagiera do you know if there's anything wrong with this/if it can be done in a better way without passing the Context to the ShadowNodes?

**Comment by corymsmith** [comment]
That was my main concern, whether I should be passing the context all the way down into the shadow node itself

**Comment by efung** [comment]
As mentioned in [this comment](https://github.com/facebook/react-native/issues/1167#issuecomment-144077138), perhaps we can load custom fonts by calling (new) methods on `ReactInstanceManager`, that associate a `fontFamily` name with a `.ttf` file?

**Comment by andreicoman11** [comment]
Added in https://github.com/facebook/react-native/commit/bfeaa6a4f531cfc18c097bc9ffb6a8dbe3ddc702
