### ISSUE TITLE
[Request: PushNotificationIOS] Track and remove scheduled notifications

### ISSUE THREAD

**Issue by adamterlson** [facebook/react-native#2920]
Is there a way to track and subsequently remove scheduled local notifications?

My naive usage wish would be something like:

```
var ref = PushNotificationIOS.scheduleLocalNotification({
      fireDate: new Date().toISOString(),
      alertBody: 'Something'
});

PushNotificationIOS.removeLocalNotification(ref);
```

**Comment by adamterlson** [comment]
So I was fixing to create a PR for this but ran into difficulties.  In iOS land, one would create the UILocalNotification object and presumably be able to stash it between calling `scheduleLocalNotification` followed by `removeLocalNotification`, passing the same object.

The difficulty here is that we convert a plain JS object into the UILocalNotification object but completely lose all reference to it after creation.

One possible approach (understanding I know nothing of iOS development) might be to generate a unique key for the UILocalNotification object, set it in the userInfo for the notification, pass that to the user (as `ref` above) and then when doing a `cancelLocalNotification`, retrieve the UILocalNotification object first by looping through the list on `scheduledLocalNotifications`.

I welcome feedback on this approach!

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/request-pushnotificationios-track-and-remove-scheduled-notifications

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.

**Comment by joshuapinter** [comment]
FYI, this can be done now by using the `userInfo` object when scheduling the local notification. Like so: 

```js
PushNotificationIOS.scheduleLocalNotification({
  alertBody: "I'm going to get cancelled. Sad Face.",
  fireDate: new Date( 2019, 10, 01 ),
  userInfo: { id: 1 }
});

cancelLocalNotifications({ id: 1 });
```
