### ISSUE TITLE
[Executor] Change "Debug in Safari" to run in WKWebView

### ISSUE THREAD

**Issue by ide** [facebook/react-native#2926]
The Safari debugging tools are much better for WKWebView. UIWebView is in a kind of neglected state, so I believe that WKWebView offers a better debugging experience. Since neither are used in production I expect this change to be alright but want to confirm with the FB team.

cc @vjeux @javache

**Comment by vjeux** [comment]
I haven't seen anyone use the Safari debugger in a while so sounds good to me

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/executor-change-debug-in-safari-to-run-in-wkwebview

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
