### ISSUE TITLE
On Android, TextInputs within a `position: absolute` view that's inside another view with onLayout can't be focused

### ISSUE THREAD

**Issue by hsource** [facebook/react-native#29308]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description

Given a hierarchy of views:

1. `<View>` with onLayout prop
2. `<View>` that has `position: 'absolute'` style
3. A TextInput

Text inside the TextInput can't be selected. Removing the first view's onLayout prop or the second view's `position: 'absolute'` will allow text in the TextInput to be selected.

## React Native version:

v0.62.2

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Render inside a component the following:

```tsx
import * as React from 'react';
import { TextInput, View, Text } from 'react-native';

export default function App() {
  return (
    <View style={{ flex: 1 }}>
      {
        // Remove the onLayout for the text to become selectable
      }
      <View onLayout={() => {}}>
        <View
          style={{
            position: 'absolute',
            width: '100%',
            top: 50,
            paddingHorizontal: 8,
          }}
        >
          <Text style={{ marginBottom: 10 }} wrap>
            The following text should be selectable. For some reason, it's not
            selectable on Android when placed inside the original
            KeyboardAvoidingView or any View with an onLayout callback.
          </Text>
          <TextInput defaultValue="Try selecting this text" />
        </View>
      </View>
    </View>
  );
}
```
2. On Android, try to select text inside the TextInput

## Expected Results
Describe what you expected to happen.

The text should be selected

## Snack, code example, screenshot, or link to a repository:

https://snack.expo.io/@harrytravelchime/react-native-issue-29308

**Comment by Shuo-Mr** [comment]
I also encountered a similar problem. When the view is absolutely positioned, internal events cannot be triggered, but positioning can be triggered to cover subsequent events, such as Scrollview's scroll event. I think it may be due to hierarchy, but I can't make a mask like thing on the outer layer of the positioned view, because it will affect the layout of peers. I hope someone can help me.



So your problem here, I think, is due to the absolute positioning.

**Comment by farshed** [comment]
Touchables inside absolutely positioned View not working either

**Comment by safaiyeh** [comment]
Interesting bug, I was able to see this in the snack. I've seen some PRs and issues relating to hierarchy of view elements. I wonder if one of those would help (don't have a list of them handy on me right now)

**Comment by anhquan291** [comment]
Same problem here. It works just fine on iOS but Android.

**Comment by fabriziobertoglio1987** [comment]
from quick troubleshooting I notice that `onTouchEvent` is not triggered when we use `absolute` position

https://github.com/facebook/react-native/blob/fb974ced7d68aed498efdc1ecb45d736364b3373/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java#L202

I troubleshooted something similar https://github.com/facebook/react-native/issues/27333#issuecomment-646135349 and https://github.com/facebook/react-native/issues/27333#issuecomment-657566412 but in this case I think this is an actual bug.

Also many information about this issue are included in https://github.com/facebook/react-native/issues/29911 https://github.com/facebook/react-native/issues/25441 https://github.com/facebook/react-native/issues/28694

Most of the time this can be fixed using react-native-gesture-handler component, but in this case it is not possible. I further investigate.

**Comment by ella33** [comment]
Same problem here.

**Comment by fabriziobertoglio1987** [comment]
for similar reason of https://github.com/facebook/react-native/issues/27333#issuecomment-657566412

https://reactnative.dev/docs/touchablewithoutfeedback#hitslop
>The touch area never extends past the parent view bounds and the Z-index of sibling views always takes precedence if a touch hits two overlapping views.

The parent is absolute positioned and has computed `height` of `0`, does not allow you to click/press on the childs.

In the example included in this issue `child.getBottom()` and `child.getTop()` are equal, because the element with `absolute` positioning (`nativeID="2"` in my example) has `height = 0`.

https://github.com/facebook/react-native/blob/0060b5de559cd9c785a2a2a6c66f58088fea4dd2/ReactAndroid/src/main/java/com/facebook/react/uimanager/TouchTargetHelper.java#L178-L180

I fixed the example by giving height parent parent > height of child:

**<details><summary>CLICK TO OPEN UPDATED EXAMPLE - CODE</summary>**
<p>

```javascript
class RewriteExampleInvalidCharacters extends React.Component<
  $FlowFixMeProps,
  any,
> {
  constructor(props) {
    super(props);
    this.state = {text: ''};
  }
  render() {
    return (
      <View
        nativeID="1"
        style={{backgroundColor: 'yellow', height: 150}}
        onLayout={() => {}}>
        <View
          nativeID="2"
          style={{
            position: 'absolute',
            top: 0,
            bottom: 0,
            left: 0,
            right: 0,
            zIndex: 2,
            height: 100,
            backgroundColor: 'red',
          }}>
          <TextInput nativeID="3" defaultValue="Try selecting this text" />
        </View>
      </View>
    );
  }
}
```

</p>
</details>

**<details><summary>CLICK TO OPEN UPDATED EXAMPLE - VIDEO</summary>**
<p>


|  | 
|:-------------------------:|
| <video src="https://user-images.githubusercontent.com/24992535/110342197-6b796900-802b-11eb-9390-3083560df210.mp4" width="700" height="" /> |

```javascript
      <View
        nativeID="1"
        style={{backgroundColor: 'yellow'}}
        onLayout={() => {}}>
        <View
          nativeID="2"
          style={{
            position: 'absolute',
            top: 0,
            bottom: 0,
            left: 0,
            right: 0,
            zIndex: 2,
            // height: 100,
            backgroundColor: 'red',
          }}>
          <TextInput nativeID="3" defaultValue="Try selecting this text" />
        </View>
      </View>
```

| parent height = 0 | 
|:-------------------------:|
| <video src="https://user-images.githubusercontent.com/24992535/110344565-e93e7400-802d-11eb-8335-ad83232fadd7.mp4" width="700" height="" /> |

```javascript
      <View
        nativeID="1"
        style={{backgroundColor: 'yellow', height: 150}}
        onLayout={() => {}}>
        <View
          nativeID="2"
          style={{
            position: 'absolute',
            top: 0,
            bottom: 0,
            left: 0,
            right: 0,
            zIndex: 2,
            // height: 100,
            backgroundColor: 'red',
          }}>
          <TextInput nativeID="3" defaultValue="Try selecting this text" />
        </View>
      </View>
```

| parent View height > 0 | 
|:-------------------------:|
| <video src="https://user-images.githubusercontent.com/24992535/110344351-aed4d700-802d-11eb-847a-5f1dd89bf5eb.mp4" width="700" height="" /> |






</p>
</details>

**Comment by RigottiG** [comment]
I'm facing same issue here

**Comment by PaoloGuimalan** [comment]
Hey guys I've fixed mine and this might fix yours! The thing that is happening when you position a view as absolute, the view automatically being placed at the bottom of Z index placement. So basically react native uses the html concepts about z Index. We cannot focus the textinputs and touchables within the absolute view because when we click it we are clicking the View which positioned in the same place the absolute view is at. So we need to elevate the absolute view by putting "zIndex: 1" or "zIndex: 1000", depending on how many elements your absolute view overlapped. So basically this not a bug, it's just a plain old html concept we missed.

**Comment by hsource** [comment]
The root cause of this issue is #37181
