### ISSUE TITLE
use overflow:hidden and borderRadius crash on some android9 and android10 devices

### ISSUE THREAD

**Issue by jinshiyi11** [facebook/react-native#29312]
## Description  
We found a crash on some android 9 and android 10 devices（xiaomi ,vivo).

https://github.com/facebook/react-native/pull/28881 Fixes this issue

The crash is fixed when we use `setLayerType(View.LAYER_TYPE_HARDWARE, null)` in `com.facebook.react.views.view.ReactViewGroup#dispatchOverflowDraw` as @fabriziobertoglio1987 suggested in https://github.com/facebook/react-native/pull/28881

The crash happens on RenderThread, likes below:
![image](https://user-images.githubusercontent.com/3433961/87006656-a5237700-c1f3-11ea-9f6f-cf0ea726816f.png)

## React Native version:
react native: 0.60.5
android: 9
device: Vivo x23,MI 8,etc.

## Steps To Reproduce
our code likes below.it crash sometimes.if we remove ```overflow: 'hidden'```,the crash disappeared.
```
<ImageBackground source={picSrc} style={styles .container}>
        <View style={PendantStyle.topContainer}>
            <Text>
             aaaaa
            </Text>   
        </View>
</ImageBackground>

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    borderBottomLeftRadius: pxToDp2x(15),
    borderBottomRightRadius: pxToDp2x(15),
    overflow: 'hidden'
  }
}
```

**Comment by fabriziobertoglio1987** [comment]
Thanks for the report. Could you please refactor the message as following: (if you agree)

```
We found a crash on some android 9 and android 10 devices（xiaomi ,vivo).

https://github.com/facebook/react-native/pull/28881 Fixes this issue

The crash is fixed when we use `setLayerType(View.LAYER_TYPE_HARDWARE, null)` in `com.facebook.react.views.view.ReactViewGroup#dispatchOverflowDraw` as @fabriziobertoglio1987 suggested in https://github.com/facebook/react-native/pull/28881
```

**Comment by fabriziobertoglio1987** [comment]
additionally you can build from source my react native version https://github.com/fabriziobertoglio1987/react-native/tree/rotation-issue-sdk-24-28

and install it in your project instead of the version from facebook as by this guide https://github.com/facebook/react-native/wiki/Building-from-source#publish-your-own-version-of-react-native

**Comment by jinshiyi11** [comment]
> refactor

ok

**Comment by fabriziobertoglio1987** [comment]
This is strange, because 

https://github.com/facebook/react-native/blob/bd3868643d29e93610e19312571a9736df2cbdf8/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewGroup.java#L276-L280

is only enabled for versions older then JellyBean 

which means your applications is crashing because of [LAYER_TYPE_NONE](https://developer.android.com/reference/android/view/View#LAYER_TYPE_NONE)

https://github.com/facebook/react-native/search?q=LAYER_TYPE_NONE&unscoped_q=LAYER_TYPE_NONE

**Comment by fabriziobertoglio1987** [comment]
can you reproduce without `<Text>` and `<ImageBackground>`

Thanks

**Comment by fabriziobertoglio1987** [comment]
does the bug persist after using `setLayerType(LAYER_TYPE_NONE, null)`? Thanks

**Comment by fabriziobertoglio1987** [comment]
this issue is not stale, I wrote a pr that fixes this issue. 

>We found a crash on some android 9 and android 10 devices（xiaomi ,vivo).
> https://github.com/facebook/react-native/pull/28881 Fixes this issue

**Comment by fabriziobertoglio1987** [comment]
You could try fixing this by using prop rendertohardwaretextureandroid with value of `true`

 https://reactnative.dev/docs/view#rendertohardwaretextureandroid
 https://github.com/facebook/react-native/pull/28881#issuecomment-892404892

**Comment by josiah-roberts** [comment]
+1, also encountering this crash.

**Comment by arifos** [comment]
react-native 0.64.3, still encountering this issue. Crash goes way after removing overflow style from View.
