### ISSUE TITLE
snake_case prop names for Pressable

### ISSUE THREAD

**Issue by ethanneff** [facebook/react-native#29361]
## Description
Why are their underscore prop names for `<Pressable />`? For example: `android_ripple` `android_disableSound`. This goes against convention. Docs https://reactnative.dev/docs/next/pressable#props

## React Native version:
`0.63.0`

## Expected Results
`camelCase` instead of `snake_case`

**Comment by fabriziobertoglio1987** [comment]
`android_ripple` is correct .. they did some discussion on callstack board

**Comment by ferdicus** [comment]
Can you please provide a link @fabriziobertoglio1987, I would be interested in what the reasoning is behind using snake_case for some properties and camelCase for others, as literally no other component does this....

**Comment by ferdicus** [comment]
After looking into this, I guess it makes sense (hear me out :)) - when you think about separating APIs dependent on platform and you want to be super explicit about it, you could go for a naming scheme like: `platform_`<nameOfMethod/Property>. 

It just sticks out like a sore thumb, because all other props are available to both platforms. However, if you check the codebase, there are plenty of `android_` and `ios_`.
