### ISSUE TITLE
[Modal] Modal does not resize on screen rotation

### ISSUE THREAD

**Issue by DaleJefferson** [facebook/react-native#2936]
Open a modal and then rotate the screen, I would expect the views to relayout as they normally do.

![simulator screen shot 22 sep 2015 14 40 09](https://cloud.githubusercontent.com/assets/375005/10019897/d8096b60-6137-11e5-8c46-07cb0fc52a33.png)
![simulator screen shot 22 sep 2015 14 40 27](https://cloud.githubusercontent.com/assets/375005/10019903/e0d75630-6137-11e5-9ea0-f61722520f16.png)

* React Native 0.11 Stable
* iOS 9
* iPad Air 2 simulator

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/modal-modal-does-not-resize-on-screen-rotation

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.

**Comment by VinceJou** [comment]
Hi, we encountered the same problem, does anyone have a solution ?
The productPains ticket doesn't seem way more alive :D

**Comment by esamelson** [comment]
I'm running into the same issue when rotating modals exclusively on Android devices (seems to work fine on iOS). Have tried calling forceUpdate() in the onLayout prop of various views, both in and outside of the Modal, but nothing seems to work. Any suggestions?

**Comment by GedoonS** [comment]
Just in case you run into this while searching, try adding
supportedOrientations={['portrait', 'landscape']} prop to the modal
