### ISSUE TITLE
CI has been busted for too long

### ISSUE THREAD

**Issue by nsimmons** [facebook/react-native#2939]
I found the root cause and put up an issue https://github.com/facebook/fbjs/issues/58

@brentvatne @cpojer @vjeux would be good to get some traction on fixing CI. Let me know if there is anything I can do to help.

**Comment by vjeux** [comment]
Thanks for the detailed issue. For context, our jest setup was completely different between internal and external and overall we had only a few tests running and they were ultra slow. @cpojer is doing a lot of work to upgrade jest, improve performance, fix tests... We've prioritized doing the bulk of the work rather than trying not to break travis. But thankfully this is near the end

**Comment by cpojer** [comment]
Yes, I'm on it. I'll resolve these issues today. There are some intricacies to how we sync out internal changes to GitHub and I was unaware of how some of the android stuff worked. This is a test infra issue, nothing else is broken :)

**Comment by nsimmons** [comment]
Thanks for jumping on this so quickly guys. Appreciated :) I will rebase my PRs once this issue is closed.

**Comment by cpojer** [comment]
There seem to be other issues unrelated to the test infra, see the travis output #2942. This doesn't repro locally.

**Comment by nsimmons** [comment]
I am seeing the same thing now with latest master. Tests pass locally, but CI is borked. I'll see if I can figure it out. Please update issue if you guys have figured it out as well.

**Comment by mkonicek** [comment]
Looks like there are 2 CLI tests that are consistently failing now, will look into fixing them. Example job:
https://travis-ci.org/facebook/react-native/jobs/81828731

**Comment by ide** [comment]
@mkonicek the yeoman tests are pretty flaky https://github.com/facebook/react-native/issues/2974. We should either mock "fs" for better isolation between the tests or disable them for now.

**Comment by mkonicek** [comment]
Good point, will take a look with @foghina.

**Comment by nsimmons** [comment]
It's strange because the yeoman tests are fine locally. I was thinking maybe the failures depend on the test ordering and there is some kind of test state leaking between tests?

**Comment by ide** [comment]
The yeoman tests sometimes fail locally for me. I spent a couple hours trying to fix them and didn't make a lot of progress other than eliminating some possible issues. I agree that the problem could be related to scheduling (especially because the Travis hosts have fewer cores -- maybe just one core) since those tests write to the actual file system and call into global APIs so there isn't a lot of isolation between tests.

**Comment by ide** [comment]
Tests are green (still known to be flaky in theory but that appears to have been mitigated significantly. 9/9 of the last CLI test runs were all green).

**Comment by cpojer** [comment]
:tada:

**Comment by nsimmons** [comment]
Success!
