### ISSUE TITLE
react-native-template-typescript error

### ISSUE THREAD

**Issue by cmnstmntmn** [facebook/react-native#29428]
i'm trying to install RN with typescript template and i'm getting this error:

```shell
error An unexpected error occurred: "https://registry.yarnpkg.com/react-native-template-react-native-template-typescript: Not found".
```

an indeed https://registry.yarnpkg.com/react-native-template-react-native-template-typescript is returning

```json
{"error":"Not found"}
```

**Comment by SConaway** [comment]
What command did you use? The docs say to use `npx react-native init AwesomeTSProject --template react-native-template-typescript` which works fine.

**Comment by cmnstmntmn** [comment]
@SConaway well it seems the 

```
npx react-native init AwesomeTSProject --template typescript
```

works fine

as far as i can see the link to fetch the template is constructed this way 

`https://registry.yarnpkg.com/react-native-template-` + `TEMPLATE_ARGS`

so having react-native-template-typescript will produce an invalid url (the one in the error)

**Comment by SConaway** [comment]
That means that you are using an incorrect version of `react-native`'s cli. I just tried it before I posted. 

Try running `npm ls -g --depth 0` to list any packages you have installed globally. If `react-native` or `@react-native-community/cli` appear, run `npm uninstall -g <whichever one showed up>`. 

Additionally, if you use `yarn`, run `yarn global list` to see if either shows up. If so, uninstall it via `yarn global remove <whichever one showed up>`.

Hope this helps. I ran into this previously due to global rn packages.

**Comment by idhowardgj94** [comment]
I believe there is a version gap between npm registry and newest version.

I notice that the newest version in npm is v2.0.1

and it have been 4 years since it's last publish,

and the newest version in this project is v4.10.1,

which is npx react-native will use.

I'm not exactly know how npx work,

but it indeed a version problem.

remove the global react-native-cli, and use npx react-natvie solve the problem.

**Comment by SConaway** [comment]
`react-native-cli` has been deprecated for 4 years. It should be removed. You could install `react-native` or `@react-native-community/cli` globally (not recommended). Instead, the best way is to use `npx`. `npx` installs whatever package you ask it to into a temporary directory where it's then run and removed. This is preferred, since it will use either a locally installed one in your project or it will use the latest version.

**Comment by idhowardgj94** [comment]
I believe I set up environment step by step from official website.
I think `install` section need to be updated.

anyway, problem solved. thank for help :)

**Comment by SConaway** [comment]
Glad it's solved. I think this issue should be closed then
