### ISSUE TITLE
[ImagePickerIOS] Dialogs won't show from ActionSheetIOS

### ISSUE THREAD

**Issue by christopherdro** [facebook/react-native#2951]
I'm noticing that both `openCameraDialog` and `openSelectDialog` don't show properly when called from ActionSheetIOS.

I ended up replacing the viewController with `[[[[UIApplication sharedApplication] delegate] window] rootViewController]` as a temporary fix.

@nicklockwood @yusefnapora I noticed you guys have been working on this. Any ideas?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/imagepickerios-dialogs-wont-show-from-actionsheetios

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
