### ISSUE TITLE
TouchableWithoutFeedback is highlighting when I long press it in ios.

### ISSUE THREAD

**Issue by Shing-Ho** [facebook/react-native#29556]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
TouchableWithoutFeedback is highlighting when I long press it in ios.

## React Native version:
System:
    OS: macOS 10.15.3
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 883.04 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.13.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_191 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: https://github.com/expo/react-native/archive/sdk-38.0.0.tar.gz => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
## Steps To Reproduce
```
<TouchableWithoutFeedback key={idx} onLongPress={() => this.normalTextPressed(item.text)}>
            <Text>
              {item.text}
            </Text>
          </TouchableWithoutFeedback>
```
long press the button and it is highlighting

## Expected Results
not highlighting

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by chrisglein** [comment]
Put together a Snack to hopefully help zero in on this one: https://snack.expo.io/@chrisglein/repro29556

I've confirmed that this repros on iOS but not on Android or Web.

**Comment by Shing-Ho** [comment]
```
          <Text key={idx} suppressHighlighting={true} onLongPress={() => this.normalTextPressed(item.text)}>
            {item.text}
          </Text>
```
It's fixed now using these texts.

**Comment by Shing-Ho** [comment]
But hope this fixed in TouchableWithoutFeedback

**Comment by chrisglein** [comment]
Ah, so it's `Text`, not the `TouchableWithoutFeedback` that's adding the highlight. Based on the docs, it looks like this is an expected platform difference on iOS: https://reactnative.dev/docs/text#suppresshighlighting
(as strange as that might seem)
Sounds like this by design.

**Comment by anngbaum** [comment]
One small note here since it tripped me up -- the docs claim that the default value for `suppressHighlighting` is false, which would indicate (at least to me) that the highlighting would occur independently of any other handling/wrappers.

`When true, no visual change is made when text is pressed down. By default, a gray oval highlights the text on press down.`

In practice, though, the highlighting only occurred when wrapped in a Touchable element, or if I added an onPress handler to the Text element directly. Otherwise, I'm not able to trigger the native highlighting behavior, even when I explicitly set `suppressHighlighting` to false. This led me down the same path explained here -- trying to figure out why it was tied somehow to `TouchableWithoutFeedback`.

As a small clarification, it might be nice to just add a note that suppressHighlighting default behavior is tied in to other handlers, or whatever behavior is intended there.

Thanks!
