### ISSUE TITLE
ToolbarAndroid doesn't seem to appear?

### ISSUE THREAD

**Issue by russjr08** [facebook/react-native#2957]
It seems the ToolbarAndroid component doesn't want to play right with me... Either that, or I'm doing something wrong here.

I've created a test app here https://rnplay.org/apps/CHOsPg

I can't seem to get the component to work, and a couple of other users on Reddit were having issues with it too.

**Comment by foghina** [comment]
You should set `alignItems` to `stretch` (which is also the default) on your `container`, or give your toolbar an explicit width. With `alignItems` set to `center` and no explicit width, the toolbar is given 0 implicit width.

In the future, can you please use Stack Overflow to ask questions and tag them with react-native? http://stackoverflow.com/questions/tagged/react-native

This helps us keep track of bugs that need to be fixed in Github issues. Thanks!

**Comment by xcchcaptain** [comment]
met the same problem ,it should be add to the doc

**Comment by hiteshsahu** [comment]
**You need to assign both height and width to the toolbar otherwise it won't renders**

This is how you need to do 

```

    <ToolbarAndroid
            style={styles.toolbar}
            title="Movies"
            navIcon={require("../../ic_launcher.png")}
            onActionSelected={this.onActionSelected}
            titleColor= "000"
            actions = {[
              {title: "Log out", show: "never"}
            ]}
            />


 toolbar: {
   backgroundColor: '#2196F3',
   height: 56,
   alignSelf: 'stretch',
   textAlign: 'center',
 },

onActionSelected(position) {
  }


```

Result

![screenshot_1493030133](https://cloud.githubusercontent.com/assets/4076925/25333573/61706180-2908-11e7-9497-009a2c58ac03.png)
