### ISSUE TITLE
Cannot find entry file Examples/Movies/MoviesApp.js in any of the roots

### ISSUE THREAD

**Issue by vincentqiu** [facebook/react-native#2964]
only  MoviesApp.ios.js  MoviesApp.android.js

**Comment by mkonicek** [comment]
Hey @vincentqiu, the Movies App should not contain `MoviesApp.js` and no one should depend on it.

Can you please provide the exact steps to get this error?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/cannot-find-entry-file-examplesmoviesmoviesappjs-in-any-of-the-roots

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
