### ISSUE TITLE
Linking.openURL doesn't open app in android 9 and 10

### ISSUE THREAD

**Issue by imansalhi** [facebook/react-native#29682]
## Description
`Linking.openURL(intent link)`  doesn't the open app in android version 10 and 9, whereas it works on lower versions of Android 

## React Native version:
"react-native": "0.62.2"

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.set intent link ([+](https://developer.android.com/training/app-links/deep-linking))
2.run a background job or use some services which has background job. i use react-native-firebase `messaging().setBackgroundMessageHandler`
3.place `Linking.openURL(intent link)` in background function 

## Expected Results
Open the app by intent link immediately when `Linking.openURL(intent link)` runs.

**Comment by safaiyeh** [comment]
hi @imansalhi thanks for the issue. Can you provide a repro? You mentioned react-native-firebase, can you confirm the functionality doesn't work from a scratch template

**Comment by gedeagas** [comment]
@imansalhi you can't start `Intent` from a background process in the newer android version. These restrictions help minimize interruptions for the user and keep the user more in control of what's shown on their screen. Because `Linking.openURL` rely on Android intent the same rules applies.

You can read more about this here.
https://developer.android.com/guide/components/activities/background-starts.
