### ISSUE TITLE
ListView behaves differently when placed inside a View with flexdirection set as 'row'

### ISSUE THREAD

**Issue by muneesa** [facebook/react-native#2969]
Hi,

For some reason, ListView inserts unnecessary gap on the top, if placed inside a view with flexdirection set as 'row', as if it's already pulled all the way down. It works fine, if ListView is the only component to render. Please try this code:

```javascript
var TestClass = React.createClass({
  getInitialState: function() {
  var ds = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2});
  return {
    dataSource: ds.cloneWithRows(['r1', 'r2']),
  };
},
  render() {
    return(
      <View style = {{flexDirection: 'row', marginTop: 25}} >
      <Text>Testing</Text>
      <ListView
      dataSource={this.state.dataSource}
      renderRow={(rowData) => <Text> {rowData} </Text>} />
      </View>
  )},
});
```
Please let me know if this is the expected behaviour or am I missing something.

**Comment by christopherdro** [comment]
Generally you shouldn't have to wrap your listView with another view.

If your trying to add content either before or after your listView, I would recommend taking a look at the`renderHeader` and `renderFooter` props.

**Comment by muneesa** [comment]
That makes sense if a ListView is the only component on the screen. What if, I have a title and want to display a list, to the right of that title? Anyway, I managed to solve the issue by setting this property to false:

    automaticallyAdjustContentInsets={false}

Thanks for your reply.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/listview-behaves-differently-when-placed-inside-a-view-with-flexdirection-set-as-row

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
