### ISSUE TITLE
[Android] Last HAXM library doesn't work with x86 emulators on Mac OS

### ISSUE THREAD

**Issue by blackswanny** [facebook/react-native#2971]
Not related to react-native directly, however
Currently HAXM Intel library doesn't work with Intel x86 emulators on Mac OS for most intel processors (core 2 duo, core i5 ate least).According to the link below this bug will not be fixed soon.
So Mac OS devs, trying to follow react-native getting started manual will fail to to so.
Please, add a warning in manual or remove HAXM from installation list.

https://software.intel.com/en-us/forums/android-applications-on-intel-architecture/topic/536330

**Comment by mkonicek** [comment]
Thanks for reporting!

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-last-haxm-library-doesnt-work-with-x86-emulators-on-mac-os

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
