### ISSUE TITLE
[Tests] Build cache archiving

### ISSUE THREAD

**Issue by ide** [facebook/react-native#2977]
By caching node_modules we can reduce the test times by 20-30%. This is a proposal for how to do that:

Uploading:

- When Travis runs tests for merge commits the host has access to encryption keys. (These keys are not exposed to test runs by PRs.)
- The keys can be used to decrypt AWS credentials that are stored in the Travis config file
- After `npm install` successfully completes, we asynchronously tar+gzip node_modules and upload it to S3 using the decrypted credentials. 
- The entry in S3 needs to be keyed off of a couple things like Node's native module version and the OS X environment (e.g. "xcode7"). I don't think we need to include package.json or npm-shrinkwrap.json in the key -- if we download node_modules with some extra or missing modules that's OK.

Downloading:

- When a new test runs, we compute the cache archive key and download the archive from S3.
- After extracting node_modules we run `npm install`, which should get node_modules to match npm-shrinkwrap.json (need to verify this)

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/tests-build-cache-archiving

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
