### ISSUE TITLE
[Packager] Packager should warn if you're using an old version of Watchman

### ISSUE THREAD

**Issue by ide** [facebook/react-native#2978]
Let's surface these issues in a visible way since sometimes people are running software from a couple weeks or months back.

**Comment by mkonicek** [comment]
Really like the idea! @martinbigio What do you think?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/packager-packager-should-warn-if-youre-using-an-old-version-of-watchman

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
