### ISSUE TITLE
React Native App Bundle Version Code (Weird Number) - 

### ISSUE THREAD

**Issue by dpedneka** [facebook/react-native#29790]
React Native App Version changes when Uploaded on Play Store  
Version - 3145730 (1.0)
Version - 6291460 (2.0)

Is this because of APP Bundle?

To Release app we followed the following process.
https://reactnative.dev/docs/signed-apk-android

$ ./gradlew bundleRelease

Why this behaviour? Is it normal or is there any changes we need to do resolve this error.

**Comment by gedeagas** [comment]
Hi @dpedneka this happens because https://github.com/facebook/react-native/blob/7694b32a88078278457dd8721eb61da9c4ac0f5a/template/android/app/build.gradle#L176 your versionCode is lower than the previous apk. The current calculation on versionCodeOverride is unpredictable.

V1.0 200
```versionCode 200
versionName "1.0"```

V2.0 1
```versionCode 1
versionName "2.0"```

even tho the version name changes to v2 the version code is lower than the previous build. because of this, the build will be rejected. The current implementation makes the calculated build number unpredictable and seems arbitrary. I am in the process of making a pr to change the default build calculation closer to google implementation of build number in a flutter.  `abiVersionCode * 1000 + variant.versionCode`. 

With this change,

```versionCode 4
versionName "4.0"```

With this change the result of `versionCode` 4 for `armeabi-v7a` will be 1004 (1*1000+4) instead of the seemingly arbitrary 1048580 ( 1*1048576+4).

**Comment by devlopersabbir** [comment]
## there are any solutions to solve this problem??

I have tried to rebuild it as aab 3/4 times with the changed version from the `package.json` version also `app.json` versions.

**Still I got the same problem**
![image](https://github.com/facebook/react-native/assets/82939905/8345c1bb-5972-4f73-af18-111e5fabde3e)

**Comment by farhan363** [comment]
try adding versionCode line in package.json
 "name": "shashlick-driver",
  "version": "2.0.0",
  "versionCode": 2,
  "main": "node_modules/expo/AppEntry.js",
