### ISSUE TITLE
[ListView] Notifying owner of metrics availabilty with onCalculateMetrics

### ISSUE THREAD

**Issue by ide** [facebook/react-native#2988]
We're using ListView to scroll to a row after the ListView has mounted (relevant use case for FB would be in the UFI when you have a permalink to a specific comment).

One of the things we need to do this right is the height of the scrollable content (i.e. sum of the row and separator heights), which is provided by `getMetrics().contentLength`. However, `contentLength` is sometimes null so we're currently getting the InnerScrollView ref and measuring its node, but it would be nicer to be able to rely on `contentLength` by having an event such as `onCalculateMetrics`.

Alternatively exposing an `onContentContainerLayout` prop would address this as well.

We'll put up a PR if either of these solutions are palatable.

cc @sahrens

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/listview-notifying-owner-of-metrics-availabilty-with-oncalculatemetrics

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
