### ISSUE TITLE
Fatal Crash: Expected Android API level 21+ but was 30

### ISSUE THREAD

**Issue by lorenc-tomasz** [facebook/react-native#30101]
Hi,
when I was targeting the SDK 30, i got `Fatal Crash: Expected Android API level 21+ but was 30`.

React-Native: 0.63.3

The workaround was to use recet okhttp. `implementation("com.squareup.okhttp3:okhttp:4.9.0")`

**Comment by lorenc-tomasz** [comment]
It's fixed with implementation("com.squareup.okhttp3:okhttp:3.14.9").

React Native now uses the `OKHTTP_VERSION=3.12.12` that will crash on Android 11.

Look into changelog here: https://square.github.io/okhttp/changelog_3x/#version-3147

**Comment by lorenc-tomasz** [comment]
@grabbou Could you please look into that, please?

**Comment by safaiyeh** [comment]
Hey @lorenc-tomasz thanks for the issue! I'll submit a PR for this

**Comment by lorenc-tomasz** [comment]
Thank you :)

**Comment by safaiyeh** [comment]
https://github.com/facebook/react-native/pull/30104

**Comment by fabriziobertoglio1987** [comment]
react native 0.63.4 bumped the okhttp dependency

https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#v0634
https://github.com/facebook/react-native/commit/0f6fcb2c2788dc7150f6c3673a8f4f9d8f929441
https://github.com/facebook/react-native/pull/30104#issuecomment-704970648

This issue is solved

**Comment by lorenc-tomasz** [comment]
Still I had to bump version to 3.14.7 to resolve the issue, but based on master it can be marked as resolved.
