### ISSUE TITLE
Update library libjpeg-turbo from 1.5.3 to 2.0.5 due to security vulnerabilities

### ISSUE THREAD

**Issue by veerareddy17** [facebook/react-native#30186]
Hi,
I found vulnerability with older version of libjpeg-turbo 1.5.3 in react native 0.63  , could you please look into it and fix .
Here is the screenshot

![libjpeg-turbo issue](https://user-images.githubusercontent.com/31662609/96122704-87129480-0f0f-11eb-88a1-478474cafff4.png)

**Comment by verareddy17** [comment]
> ⚠️	Missing Environment Information
> ℹ️	Your issue may be missing information about your development environment. You can obtain the missing information by running `react-native info` in a cons

we were unable to figure it out by running react-native info.  please look into screen shot here

![react-native info console](https://user-images.githubusercontent.com/31662609/96126904-e07bc300-0f11-11eb-9522-28b9c490dadf.png)

**Comment by safaiyeh** [comment]
Hi @verareddy17 thanks for the issue. A quick search I can't pinpoint where this library is being used. Do you have some context on which dependency might be using this?

**Comment by verareddy17** [comment]
it's been using internally while creating  new project  with this command **react-native init proejct_name**

**Comment by LucaBuonocore** [comment]
Hi, has this vulnerability been fixed?

**Comment by M9lab** [comment]
same here!

**Comment by feeza10250** [comment]
Is there a solution?

**Comment by KFrysztak** [comment]
any update on this one?

**Comment by yogendrajs** [comment]
Any update team?

**Comment by digdas** [comment]
same here!

**Comment by CristopherJonas** [comment]
well, How can we update this lib ? I didn't find it in my project

**Comment by hpelitebook745G2** [comment]
Any updates on this?

**Comment by dwxw** [comment]
A recent pentest report highlighted this issue for our app.  How can I help fix this?  Any tips where to start with a PR?  Thanks.

**Comment by cowen-slimmingworld** [comment]
Any update on this?

**Comment by cortinico** [comment]
Closing as `libnative-imagetranscoder.so` is not produced by React Native (at least not as of RN 0.70) so this issue is either stale or caused by an external dependency

**Comment by nisarmalhi46** [comment]
Any solution for this?
@veerareddy17

**Comment by thitoo-yf** [comment]
Any Solution? And Faced in Rn 0.70.3

**Comment by bdeweygit** [comment]
@cortinico you are correct, it is caused by an external dependency.

libjpeg-turbo is a C library used by the nativeimagetranscoder module in Fresco - the image management library used by React Native for Android. The libjpeg-turbo version with the CVE has been integrated into the project for the past 5 years or so. The latest version of Fresco continues to use this version, so there is no existent upgrade path that resolves the CVE. See [this issue](https://github.com/facebook/fresco/issues/2482). A new release of Fresco will need to be made. React Native currently uses Fresco 2.5.0 [here](https://github.com/facebook/react-native/blob/6115ce53a2df4449769e4b9b6ca95fc29955fff0/ReactAndroid/gradle.properties#L11), but latest is 3.0.0. It might be easier to try making a patch release 2.5.1 that addresses this issue only, rather than trying to upgrade the major version.

**Comment by bdeweygit** [comment]
> Please open a newer issue on the Fresco repo mentioning that this CVE is still happening on Fresco 3.0.0 and we can get this prioritized.

@cortinico see [issue](https://github.com/facebook/fresco/issues/2728).

**Comment by try-catch-stack** [comment]
Any updates on this? It's been over 8 Months since the [issue](https://github.com/facebook/fresco/issues/2728) was reported on The Fresco repo.

**Comment by mnt** [comment]
@cortinico I made a PR for the [issue](https://github.com/facebook/fresco/issues/2728).

**Comment by codegunner21** [comment]
The fixed was merged and is part of Fresco 3.2.0....

Is there a PR for React Native to update Fresco?  The dependency files I'm able to see still list the Fresco version as 2.5

**Comment by cortinico** [comment]
> Is there a PR for React Native to update Fresco? The dependency files I'm able to see still list the Fresco version as 2.5

We bumped Fresco to 3.2.0 here https://github.com/facebook/react-native/commit/744024be7f95970bdd786931bdf10dd50c515124

It will be shipped in 0.75.0
