### ISSUE TITLE
ios on selectionChange does not work with multiline set to true

### ISSUE THREAD

**Issue by VivekNeel** [facebook/react-native#30298]
## Description
I have a basic text input with multiline set to true. Additionally it has `selection` and `onSelectionChange` props set which causes cursor to move to initial position whenever there is change in `onChangeText`.

Here it's the video : https://streamable.com/bchsz4

Here it's the repro : https://github.com/VivekNeel/IOS_SELECTION_CHANGE
Here it's the sample code : 

      <TextInput
          onChangeText={handleChange}
          value={value}
          multiline
          selection={selection}
          onSelectionChange={handleSelection}
          placeholder="Enter a text"
          style={{marginTop: 100, marginHorizontal: 16}}
        />

## React Native version:
```
  "react": "16.13.1",
    "react-native": "0.63.3"
```

## Steps To Reproduce

1. clone https://github.com/VivekNeel/IOS_SELECTION_CHANGE
2. run yarn run ios and type some thing in the text input

## Expected Results
when typing in a text input using selection , onSelectionChange and multilne, cursor position should not get reset

## Snack, code example, screenshot, or link to a repository:
https://github.com/VivekNeel/IOS_SELECTION_CHANGE
https://stackoverflow.com/questions/64639411/ios-react-native-onselectionchange-moves-cursor-to-initial-position-when-multlin

**Comment by yum650350** [comment]
I put `console.log` in `node_modules/react-native/Libraries/Components/TextInput/TextInput.js` and found out the `onChange` and `onSelectionChange` orders are different between multi-line and single-line `TextInput`

### single-line: onChange -> onSelectionChange
![ezgif-3-8c337b408a76](https://user-images.githubusercontent.com/48589760/97878051-1239ba00-1d59-11eb-923b-cbb5d2679203.gif)

### multi-line: onSelectionChange -> onChange
![ezgif-3-c126d826aec0](https://user-images.githubusercontent.com/48589760/97878100-1ebe1280-1d59-11eb-8887-f0b43a59466a.gif)



Not sure but it seems like a bug because of [this comment](https://github.com/facebook/react-native/blob/36b0f7d19bcc430d4567f60b9e2c92435538cd6c/React/Fabric/Mounting/ComponentViews/TextInput/RCTTextInputComponentView.mm#L42), it says:
```
 JavaScript depends on `onChange` to be called before `onSelectionChange`
```

**Comment by VivekNeel** [comment]
> I put `console.log` in `node_modules/react-native/Libraries/Components/TextInput/TextInput.js` and found out the `onChange` and `onSelectionChange` orders are different between multi-line and single-line `TextInput`
> 
> ### single-line: onChange -> onSelectionChange
> ![ezgif-3-8c337b408a76](https://user-images.githubusercontent.com/48589760/97878051-1239ba00-1d59-11eb-923b-cbb5d2679203.gif)
> 
> ### multi-line: onSelectionChange -> onChange
> ![ezgif-3-c126d826aec0](https://user-images.githubusercontent.com/48589760/97878100-1ebe1280-1d59-11eb-8887-f0b43a59466a.gif)
> 
> Not sure but it seems like a bug because of [this comment](https://github.com/facebook/react-native/blob/36b0f7d19bcc430d4567f60b9e2c92435538cd6c/React/Fabric/Mounting/ComponentViews/TextInput/RCTTextInputComponentView.mm#L42), it says:
> 
> ```
>  JavaScript depends on `onChange` to be called before `onSelectionChange`
> ```

Do you know of a way to get selection from either ref or native props?

On web, I can do something like event.target.selectionStart

**Comment by yum650350** [comment]
@VivekNeel For me I'll just use `onSelectionChange` and get it from using `useState`, it's simpler. If you don't want the cursor position to be reset on text changed, just remove the selection prop of the TextInput, like below

```javascript
<TextInput
          onChangeText={handleChange}
          value={value}
          multiline
          // selection={selection}   <----- remove this
          onSelectionChange={handleSelection}
          placeholder="Enter a text"
          style={{marginTop: 100, marginHorizontal: 16}} />
```

**Comment by jasongaare** [comment]
I'm experiencing this exact issue too, however I need the the `selection` prop on my component, because at times I want to dictate the select when the user is moving the cursor around.

Generally if I am not dictating the selection I can set it to `undefined` a la:

```jsx
this.setState({ selection: undefined })

<TextInput
  selection={this.state.selection}
   ...
/>
```

but when I do need to set the selection (I am highlighting an entire word in some cases whenever the cursor position lands within the word), the behavior is as described above, where the order those are called resets the cursor position to 0.

I've yet to find a good workaround for this yet

**Comment by jasongaare** [comment]
actually for now, I've found that using `setNativeProps` to control selection, rather than using the prop on the text input, seems to be an adequate workaround, one that does not trigger the undesired `onChange`

https://github.com/facebook/react-native/issues/29780#issuecomment-716971630

**Comment by eeshankeni** [comment]
Damn this problem still exists in 2023. My cursor keeps moving to the first position when selection is used. Fortunately setNativeProps can be used to force the cursor to go wherever i want it to.

**Comment by cubuspl42** [comment]
This issue deserves some love 💔

**Comment by hannojg** [comment]
This looks like it was never fixed, just want to add that I can't reproduce this on version 0.73.x
