### ISSUE TITLE
Facebook has taken the name of my open source project

### ISSUE THREAD

**Issue by dessant** [facebook/react-native#30395]
Hi, I'm the maintainer of Label Actions, a GitHub app that [Facebook has been using](https://github.com/facebook/react-native/commit/f9c2157141b8fcddcb2d2c576c952f2ce7daedda) for the React Native repository.

EDIT: I've seen some folks claiming that these are just the personal actions of a Facebook employee, and it has nothing to do with Facebook, here is the commit on this repository that swaps out my app with the newly created action during an internal review process at Facebook: https://github.com/facebook/react-native/commit/f9c2157141b8fcddcb2d2c576c952f2ce7daedda

https://github.com/dessant/label-actions

It has come to my attention that one of your collegues at Facebook has reimplemented the app with almost the same features and configuration syntax using GitHub actions, and shared it on GitHub using the same project name.

https://github.com/hramos/label-actions

The action has been published on the GitHub Marketplace using the same name as my open source project, preventing me from publishing my project as a GitHub action using the project name.

Despite your bot taking heavy inspiration from my project, and despite taking the name of my project, you haven't credited me or the original project in any way, possibly not complying with the MIT license.

The GitHub app is part of a set of open source projects that are funded by contributors. By hijacking the name of my project, and taking it's name on GitHub Marketplace, you are making it harder for the project to receive donations.

In the last month this is the second time that Facebook has caused me grief that borders on illegality. Recently I have signed up for [Wit.ai](https://wit.ai) by creating a Facebook account. The account was automatically blocked after a couple of days for no reason, and I have been asked to provide additional personal data, after which the account has remained banned.

Facebook has a photo of my face that they have requested during review, my legal name and date of birth, my verified email address and phone number, and I cannot exercise any control over this data, only download it, which is obviously illegal under GDPR.

I have reached out to the Wit.ai team at Facebook, but so far my request for help has been ignored.

You can find more details about the issue here: https://github.com/wit-ai/wit/issues/1946

Please find a different name for the action that has been published on GitHub Marketplace, and change the name of the repository.

Please also reach out to your collegues at Wit.ai, or the people who can override automated blocks at Facebook, so that I receive due process for my Facebook account, and avoid having to file a GDPR complaint regarding the loss of control over my personal data.

**Comment by dsignr** [comment]
Shame on Facebook for such a crass move. If you're a developer behind this change, you should reflect upon your action and make it right as this could be you in the future - bullied by a giant, greedy and ruthless corporation.

**Comment by umair-akbar** [comment]
IANAL. This is a violation of the entirety of GDPR Article 17 Subsections (1), (2), (3), GDPR Article 18, Subsection (1a)(1b)(1c), (2), (3).

They have made finding contact details extremely difficult. 

https://feedback-form.truste.com/watchdog/request

They utilise either trustE (linked above), or can be contacted by mail:

Facebook, Inc.
ATTN: Privacy Operations
1601 Willow Road
Menlo Park, CA 94025

https://www.facebook.com/privacy/explanation (scroll to bottom).

**Comment by dorianmariefr** [comment]
this was posted to HN 10 minutes after being created https://news.ycombinator.com/item?id=25103487

**Comment by AkshatM** [comment]
This  should be cross-posted on https://github.com/hramos/label-actions/issues

**Comment by f6v** [comment]
Can it be that @hramos never even heard of OP's project before?

**Comment by PedroBatista** [comment]
This is what happens when a group of people have been getting away with so many violations and some crimes for so many years.

This is not a "mistake", but I bet the people behind this didn't lose sleep, because nothing bad happens..

**Comment by NiklasBr** [comment]
> Can it be that @hramos never even heard of OP's project before?

@f6v No, check the first link in the to the commit where they renamed it from "dessant/label-actions" to "marketplace/actions"

**Comment by lloydjatkinson** [comment]
> > Can it be that @hramos never even heard of OP's project before?
> 
> @f6v No, check the [first link in the post to the commit](https://github.com/facebook/react-native/commit/f9c2157141b8fcddcb2d2c576c952f2ce7daedda) where they renamed it from "dessant/label-actions" to "marketplace/actions"

This removes all doubt that this was not intentional. Fuck Facebook.

**Comment by vanyakosmos** [comment]
@f6v they knew about project and used it here before. But still I can believe that they reimplemented it from scratch.
About taking the name: I think that it's more like  "the early bird catches the worm". After all the name is pretty generic, straightforward and idiomatic for github actions.
And they probably don't need to comply with MIT either, because the idea itself is not licensed.

**Comment by dsignr** [comment]
Facebook has actually started censoring the comments in here. Wow. Just wow.

**Comment by TheSavior** [comment]
Hey @dessant thanks for flagging this. I'm sure that this was unintentional. While we look into this I'm going to lock the issue to prevent more off-topic comments so we can focus on getting this fixed for you.

**Comment by hramos** [comment]
Hi @dessant, I totally see where you're coming from and I'm sorry for the disruption.

To clarify what happened:

- I originally added your project to the React Native CI.
- Later, I needed to migrate our workflow to GH Actions. Your project did not support that, so I wrote a different implementation from scratch in a few hours. I kept the same configuration format and scoped it under @hramos. I thought that I credited your project as inspiration, but clearly I didn't, and I'm sorry for that mistake.
- I couldn't use the Action without registering it on Marketplace, so I registered it under the same name. It hasn't occurred to me that you would later attempt to do the same, but this makes sense, and I agree you deserve to have the original name there.

To mitigate your concern, I plan to:

- Add an "inspiration" section to my project's README that clearly credits your project with the idea and the configuration format.
- Rename my project on GitHub Marketplace to something unique.
- If your project already implements GitHub Actions, I'd be happy to switch us over to using it again. Alternatively, please get in touch via hramos@fb.com so that I can transfer the original name back to you. I can't simply delete it now because since this thread is highly visible, someone else will likely squat it after it frees up. I haven't seen a reachout from you so far but my apologies if I missed it.

Thank you for bringing this up!

I will also forward your complaint about Wit.ai to the relevant team.

**Comment by dessant** [comment]
Hi @hramos, thanks for reaching out both here and in private! Recently I have begun to port some of my apps to actions, such as [Lock Threads](https://github.com/marketplace/actions/lock-threads) or [Support Requests](https://github.com/marketplace/actions/support-requests), keeping the original project names. Label Actions was held back because I was waiting for GitHub actions to gain support for [structured data input](https://github.community/t/can-action-inputs-be-arrays/16457), so that a separate configuration file is no longer needed for listing the labels. Please hold the action name for now, I will reach out in the near future to make the transfer.

Thanks for also forwarding my other issue to Wit.ai. The way the Facebook account was disabled and my personal data kept in state that is at odds with GDPR has been definitely an experience that has pushed me to go immediately public when I've discovered this project naming issue today.

**Comment by peaceiris** [comment]
> I couldn't use the Action without registering it on Marketplace, so I registered it under the same name.

This is false. We can run an action without publishing it on the GitHub Marketplace.
FYI.

**Comment by dessant** [comment]
We've sorted it out with @hramos, and Label Actions is now available on the GitHub Marketplace. Thanks everyone for your help and support!

https://github.com/marketplace/actions/label-actions
