### ISSUE TITLE
PDF Images and Xcode 6+

### ISSUE THREAD

**Issue by aphillipo** [facebook/react-native#3039]
Hi there, I'm building a project in React Native and absolutely loving it for fast simple builds of apps.  Even wrapping native Objective C code has been made so easy!

One feature that I can't seem to get working is using PDFs in xcassets - I've no idea how I should be referencing them in my react native project.  Any ideas on how I go about using this feature from react native?  Thanks!

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/pdf-images-and-xcode-6

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
