### ISSUE TITLE
android controlled text input not working as expected (duplicates the given string)

### ISSUE THREAD

**Issue by Niryo** [facebook/react-native#30393]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
basically this is a reopening of this issue: #19085
on my Xiaomi a1 device, when trying to use a controlled textInput, the input goes crazy and start adding duplications of the current string. Adding `visible-password` to keyboardType solves the issue, but it doesn't fit my use-case.

## React Native version:
react-native@0.62.2

## Steps To Reproduce
1. create a controlled textInput
2. test it on xiaomi A1 device

**Comment by fabriziobertoglio1987** [comment]
my pr https://github.com/facebook/react-native/pull/29070 written to fix a similar issue in TextInput may offer some guidance in understanding how TextInput state in ReactNative TextInput.js and ReactAndroid TextInput component is stored...

https://github.com/facebook/react-native/pull/29070 was trying to fix issue caused by `getText().replace(0, length(), spannableStringBuilder)`

`.replace()` will duplicate letters when using capitalize, but If I try to use `EditText` method `setText()` the problem is solved.

The difference between `setText()` and `replace()`:

- `replace()` causes this type of bugs (duplication) when using wrong `start` `end` position
```
const text = "my text";
text.replace(2,7);
console.log("text", text);
// "my my text" (aproximately!!)
```
- `setText` will reset the cursor position, we fix this saving previous position state and then calling `setPosition` after [`setText()`](https://github.com/facebook/react-native/pull/29070/files#diff-b941f6bcdff5060918b3091d619bae6ac105c05229ab635e33ded4fcba5bf2a7R528)
- calling `setPosition` can cause out of bounds errors if `new_position > text.length`
https://github.com/facebook/react-native/pull/29070#issuecomment-647716585 `setSpan(5 ... 5) ends beyond length 4`. Fixed with [this check](https://github.com/facebook/react-native/pull/29070/files#diff-b941f6bcdff5060918b3091d619bae6ac105c05229ab635e33ded4fcba5bf2a7R317-R31

As explained https://github.com/facebook/react-native/pull/29070#issuecomment-683436866 and https://github.com/facebook/react-native/issues/29063#issuecomment-658671896, if you set the TextInput value state in JavaScript and then change the text (for example `w i t h s p a c e` in `withspace`), the Java side of TextInput (ReactEditText.java) does not keep track of this internal state and triggers the errors described above. This is where my pr fails to fix this issue. The two below test cases:

| **Android Controlled Comp replace Chars with Capitalized letters** | **Android Controlled Component replace Spaces** | 
|:-------------------------:|:-------------------------:|
| <img src="https://user-images.githubusercontent.com/24992535/94347196-84b8cb00-0032-11eb-85a8-9787066bb78d.gif" width="250" />| <img src="https://user-images.githubusercontent.com/24992535/94347281-0ad51180-0033-11eb-9a60-47fa0e7ab210.gif" width="250" /> |

as you can see in my pr https://github.com/facebook/react-native/pull/29070/files#diff-637b194a475487dde7656c3f35995fbe49c800b79b19be01e89ffe22ac98df49R125-R134 and the above gifs, I was able to create TextInput which would fully control the TextInput state (position and value) on the JS Side, this way finding a workaround around the limitations of the current Java/JavaScript API

But I believe this is not a good solution as it introduces a regression on iOS and I think the TextInput.js setEffect callback responsible for updating the TextInput value and position state variables should be modified to handle the above functionalities

for this reason and given the limited amount of time available, I decided to work on other easier to solve issues.

Thanks a lot
Good luck :pray:

**Comment by fabriziobertoglio1987** [comment]
I wrote a pr for this issue https://github.com/facebook/react-native/issues/11068
This issue may be related to https://github.com/facebook/react-native/pull/29070 Thanks

**Comment by fabriziobertoglio1987** [comment]
> Please, is it possible to merge this PR in the next version ?

To answer the question of when the pr https://github.com/facebook/react-native/pull/29070 which fixes this issue will be released in the next version of React Native, I suggest you to follow the discussions at https://github.com/react-native-community/releases/issues by subscribing to those threads. The process of releasing a new version with a bug fix is the following:

- an Issue is opened in facebook/react-native
- a contributor writes a Pull Request to fix/close the react-native Issue
- The Pull Request is merged in Master
- For each realease (the upcoming one is 0.64.1) there will be a separate discussion on https://github.com/react-native-community/releases/issues where anyone can request a commit to be cherrypicked from master. The link need to be from the a **commit** from master (for ex. https://github.com/facebook/react-native/pull/29157#issuecomment-651430945) and not a Pull Request not yet merged in master :peace_symbol: :pray:

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot

**Comment by fabOnReact** [comment]
This PR is included in the [react-native-improved](https://github.com/fabriziobertoglio1987/react-native-improved) library:

# react-native-improved

- **Supports ONLY react-native 0.73**.
- Supports only old architechture (new architechture is WIP)

## Set-up

In package.json

```diff
 "scripts": {
+  "postinstall": "yarn run react-native-patch"
 }
```

Then

## npm

```sh
npm install react-native-improved --save-dev
```

## yarn v1

```sh
yarn add react-native-improved --dev
```
