### ISSUE TITLE
autoCorrect={false} is not working for TextInput

### ISSUE THREAD

**Issue by 1Ajay** [facebook/react-native#30453]

**Comment by Belgin-Android** [comment]
@1Ajay More Information Needed

**Comment by 1Ajay** [comment]
@Belgin-Android Thanks for replaying.. 

         ```
<TextInput
                label="firstName"
                 [**autoCorrect={false}**]
                returnKeyType="next"
                value={inputs.firstName}
                underlineColorAndroid={'transparent'}
                placeholder="First Name"
                onChangeText={handleFieldChange('firstName')}
                autoCapitalize="none"
              />
```
I am using the above code but on the keyboard, it's s autocorrect is still visible I am attaching the screenshot for more clarification.
(url
![Screenshot from 2020-11-29 20-08-08](https://user-images.githubusercontent.com/29257275/100544957-3bc60280-327f-11eb-93ce-929f50076729.png)
)

**Comment by chrisglein** [comment]
Put this in a [snack](https://snack.expo.io/@chrisglein/repro30453) to try the repro.

Changing [autoCorrect](https://reactnative.dev/docs/next/textinput#autocorrect) does indeed disable automatic correction. If I type "speling" with `autoCorrect={true}` it will be changed to "spelling". If specify `autoCorrect={false}` it does not. In both cases the suggestions that are part of the keyboard show up, but I don't believe that's supposed to be suppressed. This is expected behavior from the native platform.
