### ISSUE TITLE
[StyleSheets] "undefined" overrides values previously set in an array of styles

### ISSUE THREAD

**Issue by ide** [facebook/react-native#3045]
If you have multiple styles in an array, `undefined` clobbers prior entries:
```js
style={[
  { height: 10 },
  { height: undefined },
]}
```

I think it is useful to be able to "delete" entries with `null` but am less sure about `undefined`. I generally dislike distinguishing between `null` and `undefined`, but believe it is the lesser of two evils compared to distinguishing between `undefined` and "does not have (own) property".

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/stylesheets-undefined-overrides-values-previously-set-in-an-array-of-styles

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
