### ISSUE TITLE
[Packager] The same file is marked as a duplicate

### ISSUE THREAD

**Issue by ide** [facebook/react-native#3047]
In the logs I see:

```
WARNING: Found multiple haste modules or packages with the name `Component`. Please fix this by adding it to the blacklist or deleting the modules keeping only one.
One of the following modules will be selected at random:
/Users/ide/Code/project/Component.js
/Users/ide/Code/project/Component.js
```

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/packager-the-same-file-is-marked-as-a-duplicate

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
