### ISSUE TITLE
Orientation change produce same width and height

### ISSUE THREAD

**Issue by harishrhareesh** [facebook/react-native#30565]
when ever orientation changes the screen and window height and width return same value

some of the functionality not working  which depend on dimension. 
For ex: a modal backdrop  only working for half screen.

React Native version:
0.63.2

 Platform: android
  

Landscape view:
![WhatsApp Image 2020-12-11 at 11 21 54 AM](https://user-images.githubusercontent.com/68229033/101868598-b528f380-3ba3-11eb-8364-10f0207892b2.jpeg)

**Comment by oleksandr-dziuban** [comment]
Hi, issue with Dimension change event listener is partially fixed in 0.63.4, but I can confirm, we have problems now with Dimensions.get('screen') on iOS and Android in react-native@0.63.4.
Width and height of the screen are changing like are in Dimensions.get('window'). This is Incorrect behaviour. Device screen width/height should be the same when we change device orientation. Only the window width/height should be changed.

**Comment by oleksandr-dziuban** [comment]
https://github.com/facebook/react-native/issues/30577
