### ISSUE TITLE
One UI 3.0 Dimensions Screen Width is not returning the correct value

### ISSUE THREAD

**Issue by trizin** [facebook/react-native#30638]
## Description
Hello,
Two users recently reported that the screen is too big and doesn't fit on Samsung Galaxy S20 Ultra devices using Android 11. 

## React Native version:
```
System:
    OS: Linux 5.8 Pop!_OS 20.10
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
    Memory: 8.12 GB / 15.64 GB
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 12.18.2 - /usr/bin/node
    Yarn: Not Found
    npm: 6.14.8 - /usr/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: javac 14 - /usr/lib/jvm/jdk-14/bin/javac
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Snack, code example, screenshot, or link to a repository:
I use `Dimensions.get("window").width` make the elements on screen responsive. In One UI 3.0, when the device resolution is set to WQHD, elements are being scaled.

Code:
```
import React from 'react';
import {View, Text, Dimensions} from 'react-native';

export default class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      width: Dimensions.get('window').width,
      height: Dimensions.get('window').height,
      window: Dimensions.get('window'),
      screen: Dimensions.get('screen'),
    };
  }
  render() {
    return (
      <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
        <View
          style={{
            height: 50,
            width: this.state.width,
            backgroundColor: 'green',
          }}>
          <Text>Full width view</Text>
        </View>
        <Text style={{fontSize: this.state.width / 15, textAlign: 'center'}}>
          This is a text 15
        </Text>
        <Text style={{fontSize: this.state.width / 13, textAlign: 'center'}}>
          This is a text 13
        </Text>
        <Text style={{textAlign: 'center'}}>
          screen:{JSON.stringify(this.state.screen)}
        </Text>
        <Text style={{textAlign: 'center'}}>
          window:{JSON.stringify(this.state.window)}
        </Text>
      </View>
    );
  }
}
```
Screenshots:
S20 Ultra Android 11 WQHD
![S20 Ultra Android 11 WQHD](https://user-images.githubusercontent.com/25263018/103680315-0d7ec580-4f97-11eb-9733-638cf24eb04e.PNG)
S20 Ultra Android 11 FHD
![S20 Ultra Android 11 FHD](https://user-images.githubusercontent.com/25263018/103680318-0f488900-4f97-11eb-8bdf-cba67442c7ff.PNG)

I hope the issue is clear.

**Comment by trizin** [comment]
Same problem with the Samsung Galaxy Note 20 Ultra. I think the issue is related to One UI 3.0.

**Comment by trizin** [comment]
Setting the device's screen resolution to 2400x1080 fixes the issue. The problem only appears when the device's screen resolution is set to 3200x1400.

**Comment by trizin** [comment]
@nkrkv I've solved the problem with
```
let scaleFactor = Dimensions.get("screen").scale / Dimensions.get("window").scale;
const screen_height = Dimensions.get("window").height * scaleFactor;
const screen_width = Dimensions.get("window").width * scaleFactor;
```
Thus you scale the elements back to their original size.

**Comment by nkrkv** [comment]
@trizin It works as an emergency kludge but be aware that the bug also affects animations with `useNativeDriver: true`. Looks like the animated transforms live in another system of coordinates. A workaround is still to be discovered.

**Comment by nkrkv** [comment]
As for animations, it looks like applying an interpolation from `[0, 1]` to `[0, scaleFactor]` to all `translateX` and `translateY` around the app fixes them. Here `scaleFactor` is computed as in the @trizin comment:

```js
let scaleFactor = Dimensions.get("screen").scale / Dimensions.get("window").scale;
```

Nevertheless, this is a big and fragile hack. Looking forward for more details.

**Comment by Shanghai-** [comment]
I'm also experiencing this issue on Samsung Galaxy S20 phones. Unfortunately, this hack does not help in my case, as I intentionally use unscaled pixel sizes for most elements in my app, which means that the incorrect scale factor blows my whole layout up too big for the screen. Would love to see a fix for this soon.

**Comment by Shanghai-** [comment]
@trizin was the reproduction you included in your original issue part of a standalone repository? If so, could you upload and link it to this bug? I just created a new React Native in an attempt to get a minimum reproduction case myself, but I'm seeing correct scaling. No idea where this clean app differs from my production one.

**Comment by trizin** [comment]
@Shanghai- That was a project I've created to explain the issue. Unfortunately, I've deleted the project from the disk. The project didn't have any external dependencies, only an App.js file which I shared up there. Create a project with RN 0.63.4 and change the App.js with the code I shared. This should be enough to reproduce the issue.

**Comment by Shanghai-** [comment]
> Create a project with RN 0.63.4 and change the App.js with the code I shared. This should be enough to reproduce the issue.

I did exactly that, but the scaling is working correctly in the resulting test app. And if I swap over to my app on the same phone, it still scales wrong. Either there's another layer missing that creates the issue, or it's not consistent (which seems unlikely).

**Comment by Maddoc42** [comment]
I don't believe this applies just to values from `Dimensions`, but rather **all** views are scaled up. As can be seen in the original two screenshots, the unstyled text "Full width view" is larger in the first screenshot.

In our app we have the same issue, that a) `Dimensions` returns incorrect values and that b) all elements have gotten larger. This seems to be limited to Samsung devices only and can usually be triggered by rotating the device a few times.

What confuses me though, why aren't more people experiencing this issue? Is this due to some obscure combination of libraries?

**Comment by luisnaranjo733** [comment]
Adding on to what's already been said, I believe the root cause has to do with OneUI 3.0. It seems like devices on OneUI 2.5 do not experience this, but some devices on 3.0 do. My theory based on what I've heard from others is that the latest OneUI builds that are rolling out right now actually fix this. I'm wary to upgrade myself, even though I have an update pending, because then I might not be able to repro this bug and have a hope at finding a workaround for it.

By the way, here's an anonymized data set I collected that I'm basing my guesses on.

Device name | Device model | OneUI Version | Android Version | OS build number | System resolution | Repro/no repro? | Any additional   notes/observations
-- | -- | -- | -- | -- | -- | -- | --
S20 Ultra 5G | SM-G988U1 | 3.0 | 11 | RP1A.200720.012.G988U1UEU1CTKJ | WQHD+ | Repro | This is the OneUI   build with the suspected bug
S20 Ultra 5G | SM-G988U1 | 3.0 | 11 | RP1A.200720.012.G988U1UEU1CTKJ | FHD+ | No repro |  
S20 Ultra 5G | SM-G988U1 | 3.0 | 11 | RP1A.200720.012.G988U1UEU1CTKJ | WQHD+ | No repro |  
S20 Ultra 5G | SM-G988U1 | 3.0 | 11 | RP1A.200720.012.G988U1UEU1CTKJ | FHD+ | No repro |  
S20 Ultra 5G | SM-G988U1 | 3.0 | 11 | RP1A.200720.012.G988U1UEU1CTLB | WQHD+ | No Repro | Updated Jan 25,   fixed the issue. We think this is the latest build with the fix
S20 Ultra 5G | SM-G988U1 | 2.5 | 10 | QP1A.190711.020.G988U1UES1BTK1 | WQHD+ | No Repro |  
Galaxy S9 | SM-G960U1 | 2.5 | 10 | QP1A.190711.020.G960U1UEU8FTL2 | WQHD+ | No Repro |  
Galaxy S9 | SM-G960U1 | 2.5 | 10 | QP1A.190711.020.G960U1UEU8FTL2 | FHD+ | No Repro |  
S20 Ultra 5G | SM-G988U1 | 2.5 | 10 | CP1A.190711.020.G988U1UES1BTIG | FHD+ | No Repro |  
S20 5G | SM-G981U | 2.1 | 10 | QP1A.190711.020.G981USQU1ATD1 | WQHD+   FHD+ | No repro |  
Galaxy Fold | SM-F916U | 2.5 | 10 | QP1A.190711.020.F916USQU0ATFE |   | No repro |  
Galaxy Note 20   Ultra | SM-N986U1 | 3.0 | 11 | RP1A.200720.012.N986U1UEU1CTLB | HD+ (1544x720) | No repro | Samsung Software   Update from 1/21
Galaxy Note 20   Ultra | SM-N986U1 | 3.0 | 11 | RP1A.200720.012.N986U1UEU1CTLB | WQHD+ | No repro |  
Galaxy Note 20   Ultra | SM-N986U1 | 3.0 | 11 | RP1A.200720.012.N986U1UES1CUA1 | WQHD+ and FHD+ | No repro | Samsung Software   Update from 2/1
S20 Ultra 5G | SM-G988U1 | 3.0 | 11 | RP1A.2000720.012.G988U1UEU1CTKJ | WQHD+ | Repro | Reproes across app   launches


That being said, I _do_ think there is an app level workaround that exists for devices on bugged builds of OneUI. Even if this eventually goes away by itself if we do nothing (as OneUI builds roll out naturally over time), it would be great to understand what that workaround is so that RN apps that are experiencing this can use that as a short term solution.

I believe this app level workaround is a really subtle Android thing. I don't think it's necessarily a react-native thing. Here's why:
@trizin posted a great App.tsx snippet on how to repro this bug. But I bootstrapped a vanilla react-native@0.63.4 project ([link](https://github.com/luisnaranjo733/RN-OneUI3-repro/blob/main/App.tsx)) and pasted that App.tsx in and this **does not repro.** (as @Shanghai- pointed out). However, if I paste that _same_ JS source into another app that **does** repro, I can see this happen. Additionally, there are other RN apps where this doesn't happen and it's not immediately obvious why some are impacted while others are not.

This leads me to believe that there is some obscure, unexpected line(s) of code that can workaround this issue. The trouble is that this is hard to find, and there's not much alternative besides brute force trial and error. It would be helpful if we could get confirmation that there even is a bug in OneUI and what that bug is, how it was patched, etc, so we could understand how to work around it.

I've tried a number of things to find it, with no success. I've tried replacing various files of an app where this issue is present with corresponding files from the vanilla RN 63 project linked above where this issue is not present. If anyone else is able to dig around and come up with any leads, it would be really awesome if they could share them on this thread. Here are the areas I've tried and didn't come up with anything meaningful.
- Android manifest
- project level build.gradle
- app level build.gradle
- Removing linked native modules
- MainActivity
- MainApplication

I would love to see how these findings compare to what the previous commenters on this thread are seeing.

**Comment by Maddoc42** [comment]
Possible hint: below are two screenshots from a single user showing the same screen. First screenshot is how things should look like, second screenshot is how things do look like after rotating the app a few times or sometimes after starting the app directly.

<img width="455" alt="Screenshot 2021-02-04 at 15 26 15" src="https://user-images.githubusercontent.com/1794729/106906712-bc7d0100-66fd-11eb-9489-38cb3954748d.png">

<img width="482" alt="Screenshot 2021-02-04 at 15 26 23" src="https://user-images.githubusercontent.com/1794729/106906738-c1da4b80-66fd-11eb-91ee-02e708451d01.png">

Note how in the second screenshot everything is rendered slightly larger **except** the grey bar behind the number? The text and images are all standard RN elements with usually fixed sizes (image top right is supposed to be 40x40). The grey bar however is a `react-native-svg` `Rect` element with a fixed height of 16 (https://github.com/react-native-svg/react-native-svg). So whatever react-native-svg is doing for rendering is not affected by this, regular RN elements are though.  We're using `react-native-svg@12.1.0`.

**Comment by Shanghai-** [comment]
Important note re @luisnaranjo733's device table: **I can still reproduce this** on build RP1A.200720.012.G988U1UEU1CTLB with a Samsung S20. Everything is fine on app launch, but rotating the phone into landscape mode (if the app supports it) induces the same scaling issue, and it remains after rotating back to portrait. So updated builds still don't completely fix this issue, only mitigate it for portrait-only apps.

**Comment by luisnaranjo733** [comment]
This doesn't repro for me anymore. It may have been fixed by the OS. I believe this issue can be closed now.

**Comment by richtea99** [comment]
We had a similar incorrect resolution issue but in an Android app.
It may be worth going direct to Samsung Developer support for help. We were impressed - normally big companies like Samsung aren't interested, so kudos to them for listening.

In case there's a connection, our feedback from Samsung dev support is that our specific issue (which is just the same as the above - a 1080 wide screen returning a resolution of 810, and only on Android 11 One UI 3.0) is due to be fixed in the OS in software version EUBA or EUB9.
However no date was confirmed - but 1-2 months is the estimate.

**Comment by trizin** [comment]
I'm closing the issue since it has been resolved with the new One U.I update.
