### ISSUE TITLE
[Gestures] Stylus support for iPad Pro

### ISSUE THREAD

**Issue by ide** [facebook/react-native#3065]
iOS 9.1 adds support for iPad Pro with stylus support:

Stylus:
- altitudeAngle - for Apple Pencil, which the docs refer to as a stylus... but who wants a stylus?! ;)
- azimuthAngleInView(view) / azimuthUnitVectorInView(view) - we probably want to reimplement these since the shadow hierarchy can differ from the UIView hierarchy

**Comment by rami2929** [comment]
+1 for Apple Pencil support.

**Comment by hkrish** [comment]
:+1:

**Comment by mgiachetti** [comment]
👍

**Comment by mjracca** [comment]
👍

**Comment by neiker** [comment]
+1

**Comment by danielaconsti** [comment]
+1

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/gestures-stylus-support-for-ipad-pro

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
