### ISSUE TITLE
The Keyboard.addListener('keyboardDidShow') method is not executed when the Android phone screen is horizontal

### ISSUE THREAD

**Issue by jiangjiatao** [facebook/react-native#30661]
The Keyboard.addListener('keyboardDidShow') method is not executed when the Android phone screen is horizontal

**Comment by jiangjiatao** [comment]
![image](https://user-images.githubusercontent.com/18566483/103341441-e66d5300-4ac1-11eb-8d14-769c2a79ea57.png)

**Comment by jiangjiatao** [comment]
![image](https://user-images.githubusercontent.com/18566483/103341874-fcc7de80-4ac2-11eb-8ff2-91a92e496657.png)

**Comment by fabriziobertoglio1987** [comment]
I tried to google how to implement this in Android/Java, could not find any solution

The current solution we implemented is based on this StackOverflow solution https://stackoverflow.com/a/26964010/11452286 and works only on Portrait

When the user opens the keyboard in Lanscape mode , it will cover the entire screen, on other use cases it would not (screenshot below). In this use cases (for ex. see Gmail), may be necessary using KeyboardingAvoidingView or keyboardDidShow/Hide

**<details><summary>CLICK TO OPEN TESTS RESULTS</summary>**
<p>

![image](https://user-images.githubusercontent.com/24992535/109188245-043df800-7793-11eb-8542-191575dbc387.png)


</p>
</details>

The issue here is that `getRootView().getWindowVisibleDisplayFrame(mVisibleViewArea)` does not detect any change when using Horizontal mode (except inverting width/height).

https://github.com/facebook/react-native/blob/eeb36f470929c2fdd8e1ed69898a5ba9144b8715/ReactAndroid/src/main/java/com/facebook/react/ReactRootView.java#L763

**<details><summary>CLICK TO OPEN TESTS RESULTS</summary>**
<p>

Portrait

```
02-25 18:02:56.900  4083  4083 W unknown:TESTING::: mVisibleViewArea: Rect(0, 72 - 1080, 1029)
02-25 18:03:00.576  4083  4083 W unknown:TESTING::: mVisibleViewArea: Rect(0, 72 - 1080, 1776)
```
Landscape

```
02-25 18:03:16.349  4083  4083 W unknown:TESTING::: mVisibleViewArea: Rect(0, 72 - 1776, 1080)
```
</p>
</details>
