### ISSUE TITLE
[iOS] Slow view shadows

### ISSUE THREAD

**Issue by rreusser** [facebook/react-native#3098]
We finally realized our scrolling bottleneck was entirely the view shadows. It appears our only way forward is to remove the shadows or fake them with background images.

I dug a little and it looks like view shadows are implemented by transferring properties onto the layer at [`React/Views/RCTViewManager.m:121`](https://github.com/facebook/react-native/blob/master/React/Views/RCTViewManager.m#L121-L124) Everything I've read says that `shadowPath` and `shouldRasterize` can greatly improve rendering speed, but it appears they're not currently used. Due to my limited experience, I'd have to dig a fair amount to implement this so before I try, is it conceivable that these features could be used to optimize shadows?

**Comment by ide** [comment]
shouldRasterize is exposed as a prop called shouldRasterizeIOS if you want to try that but I think you are right about setting the shadowPath. In fact that is probably the correct behavior since iOS's regular shadows are more sophisticated than web and probably Android from my reading of the docs. For example if you put a shadow on a view with a transparent background, iOS will apply the shadow to the subviews instead because it looks at what pixels are opaque. If that's the case we should look into using shadowPath by default and exposing a prop to override that setting to preserve the system's abilities.

cc @nicklockwood

**Comment by rreusser** [comment]
My fault entirely! I think I grepped for `shadowPath` but I clearly would have found `shouldRasterizeIOS` if I'd searched for that correctly. I can confirm that it helps quite a bit, although I'll have to educate myself on further benefits of and differences with `shadowPath`.

Side note: sorry for the additional noise I could have solved on my own! Y'all are doing a remarkable job of keeping up with the influx of issues. It's greatly appreciated!

**Comment by ide** [comment]
Thanks for the raising the issue with shadowPath... that's the kind of thing React Native can implement by default in a lot of cases and let you build apps that could be faster than unoptimized UIKit ones =D

**Comment by ide** [comment]
shadowPath support for components with opaque backgrounds added here: https://github.com/facebook/react-native/commit/e4c53c28aea7e067e48f5c8c0100c7cafc031b06
