### ISSUE TITLE
[Init] Allow overriding of the react-native module from init script

### ISSUE THREAD

**Issue by ide** [facebook/react-native#3102]
The gist is: `REACT_NATIVE_PACKAGE_ID=facebook/react-native react-native init Project` if you want to install from somewhere other than the latest package on npm.

This change will need to go in react-native-cli but isn't meant to be user-facing anyway.

**Comment by philikon** [comment]
:+1:

**Comment by chirag04** [comment]
:+1:

**Comment by grabbou** [comment]
Looks like a good first task.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/init-allow-overriding-of-the-react-native-module-from-init-script

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
