### ISSUE TITLE
Hint & element text not being properly combined

### ISSUE THREAD

**Issue by amarlette** [facebook/react-native#31056]
## Description
Hint set on an element without an accessibilityLabel, does *not* pull in descendant text to use as its label but instead announces the hint only. 

This issue is covered in-depth by parent issue #30847, please check there for more details.

## React Native version:
v 0.63

**Comment by blavalla** [comment]
Just as a note here, the cause for this is that we are actually adding the hint as part of the contentDescription.  This is because Android has no "accessibilityHint" property like iOS does, and instead its hint system is related to specific actions.

React Native *does* let you set labels for default actions like click, which will announce the hint "Double tap to <label>", but since the accessibilityHint prop exists for iOS it is also sort-of supported on Android to have a quasi-iOS-like experience.

Honestly, I see two paths forward here.

1. Formally make accessibilityHint an iOS-only property, with documentation that states that if you want to set hints on Android, you should use the accessibilityActions prop.

2. Re-implement accessibilityHint on Android so that rather that concatenate into the contentDescription, it sets the toolTipText property on the AccessibilityNodeInfo (not on the view). This is the closest analog to iOS's hint that Android has, as the text is announced *after* the contentDescription rather than part of it. It will will not adhere to users preferences on whether they want hints disabled or not, and still has no pause before it like real hints have, but it's far closer than using the contentDescription directly.

**Comment by kacieb** [comment]
Option 2. makes the most sense to me, as removing it from Android entirely will likely break accessibility in unexpected ways across Android.

**Comment by jychiao** [comment]
commenting here to reference https://github.com/facebook/react-native/issues/26739, an existing issue that myself and several others have been hoping to get attention on. does it seem like the issue described here could be the cause of this issue?

**Comment by blavalla** [comment]
@jychiao, I just looked through the attached issue, and I don't think it's directly related, but I *do* know the cause of the attached issue (which I will comment on that issue with).

Sorry for the delay on this, I work on Android accessibility, but have only recently started working with React Native, so I wasn't aware of many of these problems until recently :)

**Comment by blavalla** [comment]
@jychiao, actually after reading through that whole issue, part of it is in fact related to this issue.  The main cause of the issue here is that accessibilityHint is using the contentDescription property on Android, as "accessibilityHint" is not a concept that is native to that platform.  Due to concatenating text into the contentDescription it causes both this issue, as well as the issue with accessibilityHint in the issue you referenced.

I'm writing up a more thorough explanation in that issue that will explain *why* it's broken, as well as propose a potential solution.

**Comment by fabriziobertoglio1987** [comment]
<details><summary>adding hint text with setTooltipText</summary>
<p>

https://user-images.githubusercontent.com/24992535/183646208-e074de4c-fc58-40ed-8369-1f5bf980343a.mp4

</p>
</details>
