### ISSUE TITLE
iOS 14.4 : Style property 'height' is not supported by native animated module

### ISSUE THREAD

**Issue by CharlesQuint** [facebook/react-native#31071]
## Description
Hello everyone,

I am having an issue with iOS 14.4 and the TextInput component in React Navigation Stack.
First of all, I do not encounter the problem on iOS 13.X versions.

When I press a basic TextInput, I encounter the following error:
Style property 'height' is not supported by native animated module

Thx in advance.

## React Native version:
```
System:
    OS: macOS 11.2.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 34.75 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.3 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```
## Steps To Reproduce

1. Click on TextInput

## Expected Results
Describe what you expected to happen.
Write in TextInput

## Snack, code example, screenshot, or link to a repository:
```
import React, { Component } from 'react';
import { TextInput } from 'react-native';

export interface Props {
}

interface State {
    value: string;
}

class Search extends Component<Props, State> {
    constructor(props: Props | Readonly<Props>) {
        super(props);
        this.state = {
            value: "",
        }
    }

    render() {
        return (
            <TextInput 
                style={{ height: 40, width: "100%", backgroundColor: "#000" }}
                value={this.state.value}
                onChangeText={(text) => this.setState({ value: text })} />
        );
    }
}

export default Search;
```

![Simulator Screen Shot - iPhone 12 Pro - 2021-02-28 at 21 41 41](https://user-images.githubusercontent.com/65077275/109432962-137caa00-7a0e-11eb-82b3-686a1ab0a6dd.png)

**Comment by JoshuaGross** [comment]
The issue is pretty much described in the error message - animating the "height" property (and other layout properties) in this way is explicitly not supported for native animations. You can convert it to a native JS animation or use LayoutAnimations instead.

The reason is that changing height, width, other layout props, etc, requires going through a full layout pass that can impact other nodes around the node being animated; but native animations *only* animate the node under your control. JS animations are slower, but an update from JS will allow native to do a full layout of the screen every time the prop is updated. Similar with LayoutAnimations.
