### ISSUE TITLE
[Feature Request] Implement `navigator.permissions`

### ISSUE THREAD

**Issue by cgarvis** [facebook/react-native#3120]
I specifically would like to know if the user has allowed geolocation.

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/permissions

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/feature-request-implement-navigatorpermissions

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
