### ISSUE TITLE
[Style] Border style of Image on Android does not work

### ISSUE THREAD

**Issue by Hkmu** [facebook/react-native#3124]
Hello,I have a test of React Native on android.It seems that the border style of Image component does not work. But it works on iOS. I tried many ways but it still does not work.

    'use strict';

    var React = require('react-native');
    var {
      AppRegistry,
      StyleSheet,
      Text,
      Image,
      View,
    } = React;

    var animated = React.createClass({
      render: function() {
      return (
       <View style={styles.container}>
        <View style={styles.horizontal}>
          <Image
            source={{uri: "http://img5.duitang.com/uploads/item/201504/21/20150421H4340_uv24P.thumb.224_0.jpeg"}}
            style={[
              styles.img,
            ]}
          />
        </View>
      </View>
      );
     },
    });

    var styles = StyleSheet.create({
      container: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#FFFFFF',
    },
    welcome: {
      fontSize: 20,
      textAlign: 'center',
      margin: 10,
    },
    instructions: {
      textAlign: 'center',
      color: '#333333',
      marginBottom: 5,
    },
    img: {
      width: 80,
      height: 80,
      borderRadius: 40,
      borderWidth: 10,
      borderColor: "#2785C3"
     }
    });

    AppRegistry.registerComponent('animated', () => animated);

The result screenshot:

![border style does not work](https://cloud.githubusercontent.com/assets/3169251/10172643/00a0dc12-6713-11e5-9d8c-4bb9e67d7816.jpeg)

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/style-border-style-of-image-on-android-does-not-work

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
