### ISSUE TITLE
Debugging in the iPhone is slow and fails

### ISSUE THREAD

**Issue by stanleycyang** [facebook/react-native#3125]
It works sporadically on my iPhone when I am testing the application (**Note**: I am using `react-native-camera module`.)

Image of error:

![slack for ios upload](https://cloud.githubusercontent.com/assets/3037893/10174236/8c1ce3c4-669d-11e5-966b-597c366ca531.png)

**Comment by ide** [comment]
One thing to check: is your phone reliably on the same LAN?

**Comment by stanleycyang** [comment]
Yes. It still takes a lot of time to start debugging

**Comment by brentvatne** [comment]
Are you debugging in Chrome? This could be heavily dependent too on the speed of your computer -- sometimes I have issues like this when using Macbook Air, but on Macbook Pro it works fine. Try starting your debugging session with the dev tools closed in Chrome. Then when you're connected, open dev tools and do what you need to do

If you are not debugging in Chrome, there must be some issue with your LAN because this works quite well even when downloading the bundle from the web, eg: in [Exponent](http://exponentjs.com) and [React Native Playground](https://rnplay.org)
