### ISSUE TITLE
[Image] No suitable image URL loader found for

### ISSUE THREAD

**Issue by Mokto** [facebook/react-native#3127]
Hi guys,

I'm stuck by an issue when updating to react-native@0.12.0-rc : "No suitable image URL loader found for".

This issue seems to be occurring when image uri is not correct (non existing images).

Thanks !

Please let me know if you need anything else.

**Comment by brentvatne** [comment]
@Mokto - iOS or Android?

**Comment by Mokto** [comment]
Sorry, i forgot to mention this.

IOS only !

Thanks.

**Comment by ide** [comment]
Could you post a short snippet of your image JSX to show what code can cause this bug? Nonexistent image can mean a couple different things.

**Comment by Mokto** [comment]
Sure !

```javascript
<Image
        source={{uri: album.cover}}
/>
```

You have to know that sometimes album.cover is an empty string. In this case, the message "No suitable image URL loader found for" is occuring. (only in 0.12.0-rc, not in 0.11.0).

I will be more accurate next time.

**Comment by ide** [comment]
Thanks for the detail!

**Comment by grabbou** [comment]
Maybe a simple `invariant` would've been enough for this? @ide

**Comment by ide** [comment]
I'd prefer a warning since the failure is obvious in a lot of cases (you don't see your image) and breaking the app is harsh for such a recoverable mistake. My current belief is that it should be hard to accidentally break RN at the JS level and hard to intentionally break it at the native level. That will require more work on our part but lead to better UX and DX with this forgiveness.

**Comment by grabbou** [comment]
Yeah, sorry, meant warning but wrote `invariant` automatically.

**Comment by dralletje** [comment]
What I did now is rendering a View with the same style whenever an empty uri is encountered, couldn't think of something better.

**Comment by ToccaLeee** [comment]
@javache  @ide  react-native 0.14.2 
No suitable image URL loader found for http://localhost:8081/assets/ReactNative/images/icon_arrow@2x.png?platform=ios&hash=c9eb04f153e31bb617334f96267a0f22. You may need to  import the RCTNetworking library in order to load images

my code:
require('../../../images/icon_service_center.png')

I am pretty sure that the image icon_arrow@2x.png is in http://localhost:8081/assets/ReactNative/images/ directory.

**Comment by Pabloicaza** [comment]
I know this is old but for me adding 'http://' to localhost:3000/ solved the problem.
