### ISSUE TITLE
rootViewController presentViewController The pop-up viewController disappears in a moment

### ISSUE THREAD

**Issue by SilmeLyy** [facebook/react-native#31285]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
RCTPresentedViewController() presentViewController The pop-up viewController disappears in a moment

## React Native version:
System:
    OS: macOS 11.2.1
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 41.15 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.2 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.14.9 - /usr/local/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_101 - /usr/bin/javac
    Python: 2.7.17 - /Library/Frameworks/Python.framework/Versions/2.7/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.
1.

https://user-images.githubusercontent.com/16344196/113242325-4a7efd80-92e3-11eb-9ebd-ad27b8f1c0d7.mp4

2.

QLPreviewController* cntr = [[QLPreviewController alloc] init];
            cntr.delegate = weakSelf;
            cntr.dataSource = weakSelf;
            if (callback) {
                callback(@[[NSNull null], @"Data"]);
            }
            UIViewController* root = [[[UIApplication sharedApplication] keyWindow] rootViewController];
            while (root.presentedViewController) {
                root = [root presentedViewController];
            }
            [root presentViewController:cntr animated:YES completion:nil];

**Comment by obayit** [comment]
I know this is too old, but I hope this comment help someone else.

The problem is that iOS does not allow multiple modals to be presented at the same time, only one is allowed. Here `RCTPresentedViewController()` is returning a ViewController for the modal being presented! It is probably the loading component you are using, because in the video I see the lodaing spinner show just before the modal. Since the Loading spinner is actaully a modal, you can not display another one. So the solution is to simply not show the Loading modal here.

I also noticed that in a simulator the second modal will not disappear (which is confusing, it only disappears in a real device), they must have allowed multiple modals to be shown in a simulator for some reason!
