### ISSUE TITLE
com.facebook.react.ImageLoaderURLRequestQueue

### ISSUE THREAD

**Issue by alicancelik** [facebook/react-native#31312]
Hey everyone. I can not repro this bug but firebase show more than i expected. Actually i have no idea what caused this error. This is why i need your help.

## Description

Crashed: com.facebook.react.ImageLoaderURLRequestQueue
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000

## React Native version:
0.61.5

## Steps To Reproduce
I can not reproduce

## Expected Results
There should be no mistake

## Snack, code example, screenshot, or link to a repository:
![image](https://user-images.githubusercontent.com/26031105/113696362-8f87a300-96da-11eb-9dd1-7e4923008f35.png)

**Comment by iit2008047** [comment]
need help

**Comment by cortinico** [comment]
Hey,
We're cleaning up the React Native issue tracker to make sure we focus on the most important issues first.

I'm closing this one because it's stale and related to a version of React Native we no longer support. If the issue persists on the latest version, please re-open a new issue and reference this one.

Moreover, we generally can't fix issues just by looking at a stacktrace reported from your crash reporting platform. Please provide a reproducer in your future reports.

Thank you.
