### ISSUE TITLE
[Style] Buggy behavior when toggling styles on Android

### ISSUE THREAD

**Issue by jozan** [facebook/react-native#3144]
Demo: https://rnplay.org/apps/NXhltw
Code is in `App/Task.js` at line 14.

The same code works on iOS as intended.

**What should happen:**

1. Press on task to mark it done → Green circle appears
2. Press on the same task again → Green circle disappears and orange ring appears
3. Press on the same task again → Orange ring disappears and green circle appears

**Steps to reproduce:**

1. Press on task to mark it done → Green circle should appear
2. Press on the same task again → Green circle should disappear and orange ring should appear. ___But orange ring never appears on Android.___
3. Press on the same task again → Orange ring should disappear and green circle should appear. ___Instead of green circle a green rectangle appears.___

**Comment by brentvatne** [comment]
cc @kmagiera

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/style-buggy-behavior-when-toggling-styles-on-android

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
