### ISSUE TITLE
Starting May 5th, you must let us know why your app requires broad storage access

### ISSUE THREAD

**Issue by Maharshi01** [facebook/react-native#31470]
Recently, i got this alert in play store inbox...

![Screenshot 2021-05-03 at 8 56 46 PM](https://user-images.githubusercontent.com/48430425/116897183-9a3e4500-ac52-11eb-8d62-bd7cd272b5f6.png)

Till Android 10, everything is fine with permission, we can easily pick an image from the gallery if we have this permission READ_EXTERNAL_STORAGE, WRITE_EXTERNAL_STORAGE android 10 for a temporary fix I added requestLegacyExternalStorage="true" but after Android 11 this flag will be ignored.

I have lots of doubts for android 10,11 regarding permissions and flag requestLegacyExternalStorage="true"
- Will READ_EXTERNAL_STORAGE, WRITE_EXTERNAL_STORAGE permissions be deprecated for android 10 and 11

- Can we still use requestLegacyExternalStorage="true"  for android 10 ?

-If I want to pick an image for Android devices should I need MANGAE_EXTERNAL_STORAGE permission or not?

**Comment by tomwanzek** [comment]
@Maharshi01 We have just investigated this question in our app. With RN Firebase Analytics/Messaging/App modules (11.3.3) installed, they are not the root cause for us.

We have however been able to pin it down (for us anyway) to https://github.com/Instabug/Instabug-React-Native/issues/582 

On the Instabug side, we have acknowledgement of the issue (from their Customer Happiness Team 😄 ) and they are working on it (at least on the Native SDK level, for the RN SDK we are waiting for feedback, as it is all fresh hot off the press).

Not sure, if this directly helps you, but in any case, you can take the approach I mentioned in the referenced ticket to find out which SDK might be causing it, if your own source `AndroidManifest.xml` file is clean on its own.

**Comment by Maharshi01** [comment]
Thanks @tomwanzek.bt those permissions are not merged by any 3-party SDK, I am explicitly using for some reasons.
