### ISSUE TITLE
Invariant Violation: Module JSTimers is not a registered callable module(calling callTimers). Getting Issue due to react-native-device-info package in lerna setup.

### ISSUE THREAD

**Issue by rsoni5519** [facebook/react-native#31508]
## React Native version:
0.64.0

## Steps To Reproduce
https://github.com/rsoni5519/lerna-react-native
Please use above link and follow the steps described in README.md.
![Module_JsTimer_Issue2](https://user-images.githubusercontent.com/11362091/117761160-82fbea80-b244-11eb-8621-4eaa88d75b2d.JPG)
![StepsToReproduce](https://user-images.githubusercontent.com/11362091/117761166-842d1780-b244-11eb-8eb6-2cb991e1208f.JPG)

## Expected Results
The App should work when we are clicking on Track buttons. it should console values for respective button events.
userAgent and screenSize should work for DeviceInfo and Dimensions.

**Comment by vishalkhoje** [comment]
Error occurred  because of cyclic dependency of react-native pakcage.

Use this repository for solution [a link] (https://github.com/vishalkhoje/cyclicImportReactNative)!

 1. Here problem is install **react-native-device-info** package as
    dependency into your root project not in your custom package.
 2. In your custom package use react-native-device-info adn react-native as a peer dependancy.
Ex. This is in your custom package.json file, important is version of package is same as root project package.json file.

```
"peerDependencies": {
    "react-native": "^0.64.1",
    "@types/react-native": "^0.64.5",
    "react-native-device-info": "^8.1.2"
  }
```

This will solve your problem.


![Output screenshot:] 
<img width="1775" alt="Screenshot 2021-07-01 at 7 39 18 PM" src="https://user-images.githubusercontent.com/36984676/124142784-2a103c00-daa8-11eb-842f-23caf3f08354.png">
