### ISSUE TITLE
[ListView] Extra rows rendered when datasource is updated

### ISSUE THREAD

**Issue by dnbrwstr** [facebook/react-native#3156]
I'm attempting to use ListView to render a long list (hundreds of items), the head of which is frequently updated. 

I'd prefer to only render as many rows as absolutely necessary, but as of [this commit](https://github.com/facebook/react-native/commit/3393b8653425ae797d4f5a5f25ad339e6fa8181a), ListView renders a new page of rows each time the datasource is updated.

It looks like the intention is to make sure we attempt to render at least a page's worth of items when the data source is updated. Would something like this work instead?

````
var rowsToRender = Math.min(
  Math.max(state.currentRenderedRowsCount, props.pageSize),
  props.dataSource.getRowCount()
);
````

**Comment by NishanthShankar** [comment]
Facing the same issue

**Comment by browniefed** [comment]
Is this still happening?

**Comment by damusnet** [comment]
@facebook-github-bot label Needs Response from Author

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/listview-extra-rows-rendered-when-datasource-is-updated

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
