### ISSUE TITLE
[Android] Native component "does not exist" if it doesn't define UIProps

### ISSUE THREAD

**Issue by yanni858** [facebook/react-native#3164]
As a first attempt to create a native RN Android component I tried something very simple; something that doesn't require any properties.

I kept getting this error in the log output, and the component wouldn't render:

    'Warning: Native component for "SimpleTest" does not exist'

After many attempts, I found that even the most trivial example must export UIProps, or it won't work.  Adding these two lines to the class that extends SimpleViewManager made it work:

        @UIProp(UIProp.Type.STRING)
        public static final String PROP_FOO = "foo";

Ideally the component should work also without defining a property that it doesn't need.

**Comment by corbt** [comment]
Yeah this issue was also identified in #2856. @kmagiera said that he's making large changes to the ViewManager API, so hopefully this will be fixed in the next release.

**Comment by kmagiera** [comment]
Yes, I landed https://github.com/facebook/react-native/commit/5623c831b3a938e234df18dd5b4c82c4ddf2f2c7 couple of days ago. Have you tried this on master?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-native-component-does-not-exist-if-it-doesnt-define-uiprops

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
