### ISSUE TITLE
[Gestures] Support Reachability

### ISSUE THREAD

**Issue by grabbou** [facebook/react-native#3172]
Currently, when you double tap your home button to move the top half of content on the screen down to the bottom, it won't return to it's original position after any Text or Touchable is tapped. 

I believe this is because that's probably handled on a system level, but if there's any way to work around this issue - it would be certainly a nice addition.

**Comment by ide** [comment]
Interesting -- anyone know how UIKit apps tell iOS that there was a user interaction and to cancel reachability?

**Comment by leafduo** [comment]
Tapping a native `UIButton` doesn't necessarily mean cancelling reachability. I don't know the exact logic, but pushing or present a view controller, the appearance and disappearance of keyboard and inactivity in a small amount of time would cancel reachability.

**Comment by brentvatne** [comment]
Maybe this behaviour could be built into React Native core, rather than manually implemented on a case-by-case basis. @leafduo - do you know where we could dig up a list of these cases?

**Comment by leafduo** [comment]
I learn them from my daily usage, and I don't think Apple has any documentation about them. (it will be a surprise if there is one)

I guess Apple hardcode some logic in `UINavigationController` and keyboard management code, and calling some probable private APIs. React Native should find a way to trigger the cancellation and place it in `Navigator` and `NavigatorIOS`. I guess keyboard maybe already works properly, since React Native is using native keyboard.

**Comment by grabbou** [comment]
http://stackoverflow.com/a/26371321 btw

**Comment by ide** [comment]
My take on private APIs is that it will send the wrong message if we include them in core even though major apps like Instagram use them. But if someone wants to publish a module to npm that calls into them that's their right to free speech.

**Comment by aleclarson** [comment]
> You could also experiment with subclassing UIWindow and overriding setFrame:. Set a breakpoint in this method, and if it fires when you enable Reachability, you can look at the stack trace for more information.

This could be a suitable fix that can be part of the core. Though you'll probably have to check for orientation changes here, too.

-

Or maybe it's easier for Facebook to contact Apple about letting React Native apps use the private `_deactivateReachability` method? Seems reasonable to me.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/gestures-support-reachability

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
