### ISSUE TITLE
renderSectionHeader elements exists beyond container

### ISSUE THREAD

**Issue by toomass** [facebook/react-native#3179]
It appears the the sticky sections headers are pushed into adjacent elements, occasionally rendering those elements unresponsive if they have touch actions associated with them.  I have included a screen capture of the element inspector to show that this header element is still there -- though it is not visible. This is the shaded region at the top of the screen.  In this examples the list view is nested in the tab of a react-native-scrollable-tab-view.   

![simulator screen shot oct 1 2015 11 32 27 am](https://cloud.githubusercontent.com/assets/6033506/10230073/3066d7d0-6830-11e5-82d5-fb0c5de60e35.png)

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/rendersectionheader-elements-exists-beyond-container

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.

**Comment by SeanXiao1988** [comment]
+1

please help
