### ISSUE TITLE
Non-fatal Exception: io.invertase.firebase.crashlytics.JavaScriptError

### ISSUE THREAD

**Issue by navneet-bm-ai** [facebook/react-native#31818]
## Description
"Home" has not been registered. This can happen if: * Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it, and restart it in the current project. * A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
We have created a Prod release build. But sometimes we are facing this issue on the released version of the app and also it leads to the crash in the app.
Home is one the bottom tab which we have in our app. For navigation, we are using react-native-navigation.

## React Native version:
0.63.3

**Comment by cortinico** [comment]
Hey,
We're cleaning up the React Native issue tracker to make sure we focus on the most important issues first.

I'm closing this one because it's stale and related to a version of React Native we no longer support. If the issue persists on the latest version, please re-open a new issue and reference this one.

Moreover, we generally can't fix issues just by looking at a stacktrace reported from your crash reporting platform. Please provide a reproducer in your future reports.

Thank you.
