### ISSUE TITLE
Android TextInput rendering with small height

### ISSUE THREAD

**Issue by mkonicek** [facebook/react-native#3182]
https://rnplay.org/apps/XYV08Q

If you change the height to 45+ it looks fine. Also i need to give textInput style a padding: 0 to make sure it is aligned properly. Not sure what is adding a vertical padding to the textInput.

**Comment by andreicoman11** [comment]
The theme is adding its own padding, and it also decides at what padding the underline will be. If you don't set height, you don't have these problems. It's best to just set the fontSize, and let the system draw it for you.

**Comment by chirag04** [comment]
@andreicoman11  going by your explanation here(https://github.com/facebook/react-native/pull/2730#issuecomment-144862047) setting a height and reseting the padding manually makes perfect sense. It's working fine.

Incase where height is small, the underline should not cut the text though. Height is 20 and text is placed properly.

![code](https://cloud.githubusercontent.com/assets/954063/10228452/be998e2a-6840-11e5-9fc8-744350dc12a6.png)

**Comment by andreicoman11** [comment]
The problem is that the padding of the underline is also set by the system. If you force the TextInput to have a certain height, the system has no choice but set the underline where it's dictated to.
We haven't looked into changing or setting the underline padding though, that might be a cool thing to do.

**Comment by mkonicek** [comment]
@chirag04 have you managed the get the desired result by using height and padding, or only setting font size?

**Comment by chirag04** [comment]
Nope. Using height and padding makes the text look fine. however the underline is not placed below the text. As @andreicoman11 mentioned, underline padding also needs to be set. Not sure how to do it though.

I'm happy to work out a PR if @andreicoman11 or you can guide me to setting the padding on underline as well.

**Comment by andreicoman11** [comment]
Checked underline padding: unfortunately, it cannot be changed. The underline is defined in an image that already contains some padding - that image is set as the background for the text input, and the padding inside of it cannot be changed.
There are two options here:
1. Set the underline color to transparent.
2. Don't set height. With fontSize set, the system knows how to draw the TextInput correctly, so that you don't have to worry about such issues.

**Comment by chirag04** [comment]
Cool. I will experiment with option 1. I think option 1 can work if textInput can support border. So that i can just set a border around it without any underline to show a textinput. It is more like ios i guess but will work.

border's around textinput doesn't work at this point i guess.

**Comment by yinzSE** [comment]
`backgroundColor` can remove the `underline`,
I use `<View/>` wrap `<TextInput/>`, then change `<View/>'s` style.
 as below:
```javascript
<View style={{borderWidth:1,margin:10}}>
    <TextInput style={{backgroundColor:'#fff'}} placeholder="账号"/>
</View>
```

**Comment by andreicoman11** [comment]
Added this to known issues.
https://github.com/facebook/react-native/blob/master/docs/KnownIssues.md#text-input-border
