### ISSUE TITLE
Last curly brace or last bracket is missing in fetch response 

### ISSUE THREAD

**Issue by brnaldomesi** [facebook/react-native#31854]
## Description
Sometimes(but often) last curly brace or last bracket is missing from fetch response.
It is correct in Postman but not in React Native.

## React Native version:
0.64

## Steps To Reproduce

1. Call fetch method in React native Component until you get an error.

## Expected Results
Result should be same as postman response but sometimes it's incorrect.
Last curly brace or last bracket is missing in fetch response.

## Snack, code example
async changePasswordFromApi(password, newPassword) {
    var param = { password: password, newpassword: newPassword };
    var token = await getToken();

    return fetch(address.changePassword(), {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        'Authorization': 'Bearer ' + token
      },
      body: JSON.stringify(param)
    })
      .then(response => response.text())
      .then((data) => {
        //Sometimes `data` is missing last curly brace or last bracket.
      })
      .catch((error) => {
        console.log("------------- Change Password Error" + error)
        return null;
      });
  }

**Comment by youcef-zaidi** [comment]
i suggest that you try `then(response => response.json())` insead of `then(response => response.text())`

**Comment by brnaldomesi** [comment]
> i suggest that you try `then(response => response.json())` insead of `then(response => response.text())`

I also tried that but not work.

**Comment by youcef-zaidi** [comment]
your are expecting what from your api Exacly ? a json object that contain an array ?

**Comment by brnaldomesi** [comment]
> your are expecting what from your api Exacly ? a json object that contain an array ?

two types.
1. An array that contains json object.
2. A json object (it can contain array)

**Comment by youcef-zaidi** [comment]
when you use the js's fetch method with the header Accept: "application/json" so you should receive only one Json object (and that only Json object can contain as much key/value pairs "the values may be of any data type but keys must be strings")

So you should check the way you organised the data you sent from the backend first, it must be only one json object.
you can arrange all the data you want in an array then you can convert it into an json object and return it

and finallly you use `then(response => response.json())` in order to parse the json object into a valid javascript array

**Comment by rectified95** [comment]
This doesn't look like a React Native issue - the framework depends on other libraries for HTTP functionality.
