### ISSUE TITLE
[Windows] require from directory starting with u

### ISSUE THREAD

**Issue by davidgilbertson** [facebook/react-native#3191]
react-native: 0.11.4
Node: 4.1.1
Android: 5.1.1
OS: Windows 10 (sorry)

I have a `constants.js` file that I want to require into another file, say `MyComponent.js`. If it's in a folder called `utils` and I do this: `var constants = require('../utils/constants.js');` I get an error. In the Chrome dev tools saying `Uncaught SyntaxError: Unexpected token ILLEGAL` with a reference to the first line of `MyComponent.js`.

Now the odd part, if I rename the constants directory from `utils` to `cats` then it works fine. `z` as a directory name also works. `u` fails, `utilities` fails, you get the idea.

Now more odd, even if the line is commented out I still get the error.

...oh, I've just had a flashback to a bug I saw many years ago, "/u" has some special meaning and it's breaking something.

More oddness, this line, commented out, causes the error:
```
//var colorConstants = require('../utils/constants.js');
```
only if the file actually exists. If no such file exists, then no error occurs. 

Also, this line (same text, just multi-line comments) does not cause the error:
```
/*var colorConstants = require('../utils/constants.js');*/
```
So require statements behind a line comment are parsed?

**Comment by satya164** [comment]
It's probably because of `\u`? as windows uses `\` for paths?

**Comment by mkonicek** [comment]
This is strange, could it be because `/` is being replaced by a `\` on Windows somewhere which makes this a `\u`?
See https://msdn.microsoft.com/en-us/library/2yfce773(v=vs.94).aspx

Looks like require statements in comments are parsed but shouldn't.

I don't have a Windows machine. Could you try debugging why this is happening by changing `node_modules/react-native/packager`? All the files are there so you can add println statements to them and see where this is happening.

**Comment by mkonicek** [comment]
One place to debug the comment would be https://github.com/facebook/react-native/blob/master/packager/react-packager/src/DependencyResolver/DependencyGraph/docblock.js

**Comment by mkonicek** [comment]
Thanks for reporting! Would you be up for sending a PR that fixes this? We need Windows support to be  a community effort as none of the RN team are Windows users.

**Comment by davidgilbertson** [comment]
I'd be up for giving it a crack... if someone could offer some background on what's going on that would be great. I.e., does RN override 'require()` then parse the string passed in? Is that what `DependencyResolver` is?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/windows-require-from-directory-starting-with-u

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
