### ISSUE TITLE
Pressed Debug in Safari: endless loop

### ISSUE THREAD

**Issue by mschipperheyn** [facebook/react-native#3200]
I accidently pressed debug in Safari. Now I'm in this endless loop in RCTWebViewExecutor
- (void)setUp
{
  if (!_webView) {
    _webView = [UIWebView new];
  }

Opening http://localhost:8081/debugger-ui in Safari doesn't help and the context menu is not available to change back to Chrome.

**Comment by mschipperheyn** [comment]
I did manage to load the app successfully on another (simulated) phone type, but this did not seem to help the one (iPhone 6) where I clicked the Debug on Safari. There must be some cache not being removed with cmd + shift + K

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/pressed-debug-in-safari-endless-loop

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
