### ISSUE TITLE
useImperativeHandle is invalid

### ISSUE THREAD

**Issue by BooYeu** [facebook/react-native#32105]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
When I navigate back and navigate it again with different key, params.useImperativeHandle is invalid

## React Native version:
0.65.1

## Steps To Reproduce

the code like this:

```
const MyInput = forwardRef((props,ref)=>{
  useImperativeHandle(ref,()=>({
    test(){
      console.warn('test');
    }
  }));
  return (
    <TextInput placeholder={props.value} />
  );
});

const MyInsidePage = ({route}) => {
  const inputRef = useRef(null);
  useEffect(() => {
    setTimeOut(()=>inputRef.current.test(),5000);
  }, []);
  return (
    <View>
      <MyInput ref={inputRef} value={route.params.text} />
    </View>
  );
}

const Index = ({navigation}) =>{
  return (
    <View>
      <Text onPress={()=>navigation.navigate({name:'MyInsidePage',params:{text:'page1'},key:'MyInsidePage_1'})}>go to 1</Text>
      <Text onPress={()=>navigation.navigate({name:'MyInsidePage',params:{text:'page2'},key:'MyInsidePage_2'})}>go to 2</Text>
    </View>
  );
}
```

The steps are:

1. go page 1.
2. navigate back
3. go page 2.(show errors)

The package version:

"@react-navigation/native": "^6.0.2",
"@react-navigation/native-stack": "^6.1.0",
"react-native": "^0.65.1",

## Expected Results
no error

## Snack, code example, screenshot, or link to a repository:
![WechatIMG1](https://user-images.githubusercontent.com/16587763/131115825-93053ef9-119f-42da-9515-08e968d76ca3.jpeg)

**Comment by yousseftarekkh** [comment]
@BooYeu Can you show the actual code snippet to provide a more clear insight of your implementation?
Also consider using [Snack - Expo](https://snack.expo.dev/) to properly demonstrate the issue you're facing and help visualize the use case.

#### Observations
I can see that you're calling the method `share` that has the following implementation, or something like that.
```ts
const share = useCallback(() => {
  shareActionSheet.current.show();
}, [])
```
Make sure that while using a ref somewhere within your code that points to a component, make sure that this ref has been successfully set to the corresponding value, keeping in mind the mounting of the target component and all that.

#### Semi-Educated Guess
I believe the behavior you're getting is because you're mounting/unmounting the component via your navigation. Thus within your `MyInput` component; the following happens:
1. `MyInput` component mounted. The `ref` is **asynchronously** assigned to the corresponding component.
2. `MyInput` component unmounted. The `ref` refers to `null` since the component is no longer there. The `ref` is **asynchronously** set to `null`.
3. `MyInput` component did not mount yet but was subject to getting up there to your screen. The `ref` gets called via your `share` function to execute a method through `forwardRef`ing, but the `ref` was still pointing to `null`. 
4. Bam, a crash occurs.

I am not sure but it might be the scenario that occurred.

#### Conclusion
While dealing with refs use the [Operator - Optional Chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) operator which is `?.` to properly access objects and avoid crashes and such. 
```ts
const share = useCallback(() => {
  shareActionSheet.current?.show(); /* < added the optional chaining operator */
  /* rest of your code */
}, [])
```

**Comment by 452MJ** [comment]
try
```jsx
const share = useCallback(() => {
  shareActionSheet.current?.show(); 
}, [shareActionSheet])/* < added shareActionSheet */
```

**Comment by BooYeu** [comment]
I found the error is react-native-hold-menu or react-native-reanimated~~I will submit issue in them. thank you all very much !!!!!
