### ISSUE TITLE
main.jsbundle does not exist

### ISSUE THREAD

**Issue by taduyde** [facebook/react-native#32108]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
- Use xcode to archive the new build, 
- Xcode throw the error
+ echo 'error: File /Users/robert/Library/Developer/Xcode/DerivedData/Kolbev-bphgvwixleedtdevmalrlelxeekn/Build/Intermediates.noindex/ArchiveIntermediates/Kolbev/BuildProductsPath/Release-iphoneos/Kolbev.app/main.jsbundle does not exist. This must be a bug with'
error: File /Users/robert/Library/Developer/Xcode/DerivedData/Kolbev-bphgvwixleedtdevmalrlelxeekn/Build/Intermediates.noindex/ArchiveIntermediates/Kolbev/BuildProductsPath/Release-iphoneos/Kolbev.app/main.jsbundle does not exist. This must be a bug with
+ echo 'React Native, please report it here: https://github.com/facebook/react-native/issues'
React Native, please report it here: https://github.com/facebook/react-native/issues
+ exit 2

## React Native version:
System:
    OS: macOS 11.5.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 914.61 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.22.1 - ~/.nvm/versions/node/v12.22.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v12.22.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 21, 22, 23, 24, 25, 26, 27, 28, 29, 30
      Build Tools: 23.0.3, 25.0.2, 25.0.3, 27.0.3, 28.0.3, 29.0.0, 29.0.2, 29.0.3, 30.0.2
      System Images: android-27 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_201 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.1 => 0.65.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by BenjErgizerBunny** [comment]
Have you found any solutions?  This is only happening when running in release or staging mode, not debug

**Comment by tonypangs** [comment]
I also encountered this error when making an archive build. 😔

### Environment
node: 14.17.6
react: 17.0.2
react-native: 0.65.1
realm: 10.7.0

**Comment by BenjErgizerBunny** [comment]
@taduyde and @tonypangs did this issue also begin after upgrading react-native from an older version or is this happening fro you with a fresh ```npx react-native init NewProject``` on 0.65.1?

**Comment by taduyde** [comment]
> @taduyde and @tonypangs did this issue also begin after upgrading react-native from an older version or is this happening fro you with a fresh `npx react-native init NewProject` on 0.65.1?

Hi @BenjErgizerBunny , both, from old and also use this command "npx react-native init NewProject"

**Comment by tonypangs** [comment]
I fixed this solution on my side.
It is becos the node version on xcode shell is below 14 which is not aligned with global environment. 
(probably conflict of nvm and node)
You can check its version in xcode by adding `node -v` to **react-native-xcode.sh**
then inspect the version number in xcode error message.

To upgrade xcode node version, run
`sudo npm install -g n`
`n install stable`

**Comment by antoxi4** [comment]
> I fixed this solution on my side.
> It is becos the node version on xcode shell is below 14 which is not aligned with global environment.
> (probably conflict of nvm and node)
> You can check its version in xcode by adding `node -v` to **react-native-xcode.sh**
> then inspect the version number in xcode error message.
> 
> To upgrade xcode node version, run
> `sudo npm install -g n`
> `n install stable`

I have same issue, and on global env i use node 14.17.3  the same in xcode 14.17.3. So i guess this trouble not in the node versions mismatch.

**Comment by egadstar** [comment]
I've hit this as well.

0.64.2 - Debug and Archive both work

0.65.1 - Debug works; however, Archive generates an error while creating the bundle during the "node /node_modules/react-native/cli.js bundle --entry-file index.js --platform ios --dev false --reset-cache --bundle-output..." cmd

If I run the command directly in my terminal, it is successful.

**Comment by aljs** [comment]
If you've installed node via brew, you can fix it by changing this line in Xcode **Build Phases->Bundle React Native code and images**:
`export NODE_BINARY=node`
to this one:
`export NODE_BINARY=/usr/local/opt/node/bin/node`

**Comment by cschaffr** [comment]
Any updates for this issue?
It happens with clean projects ... I tried a few:
- "npx react-native init MyApp --template react-native-template-typescript"
- "npx react-native init TestProjTS --template react-native-template-typescript --version 0.65.1"
- "react-native init TestProj --version 0.65.1"

I always get the same error....
Its not working for archives and as soon as I set Scheme to Release

**Comment by murrple-1** [comment]
Thought I'd toss in... just a little above the error for me, there are a couple lines of errors during the bunding:
```2021-10-09T15:12:52,310: [] while computing sockname: failed to create /usr/local/var/run/watchman/username-state: No such file or directory

Watchman:  watchman --no-pretty get-sockname returned with exit code=1, signal=null, stderr= 2021-10-09T15:12:52,310: [] while computing sockname: failed to create /usr/local/var/run/watchman/username-state: No such file or directory```

might be a `watchman` issue?

**Comment by Gabsys** [comment]
> If you've installed node via brew, you can fix it by changing this line in Xcode **Build Phases->Bundle React Native code and images**: `export NODE_BINARY=node` to this one: `export NODE_BINARY=/usr/local/opt/node/bin/node`

This solved the issue for me!

**Comment by rabiaasif** [comment]
> If you've installed node via brew, you can fix it by changing this line in Xcode **Build Phases->Bundle React Native code and images**: `export NODE_BINARY=node` to this one: `export NODE_BINARY=/usr/local/opt/node/bin/node`

THIS WORKED FOR ME THANK YOU!!!!

**Comment by syedamirali14** [comment]
this command helped me `npx react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios`

**Comment by wSedlacek** [comment]
For those encountering this issue, it is probably coming from the `/* Bundle React Native code and images */` section of your `project.pbxproj`

This is configured with a shellScript, typically `export NODE_BINARY=node\n../node_modules/react-native/scripts/react-native-xcode.sh`

The error specifically comes form this line here
https://github.com/facebook/react-native/blob/2fdbf6a10fe67fa3209a51a1105a97c16991f561/scripts/react-native-xcode.sh#L185-L189

It is prompted with the `$BUNDLE_FILE` does not exist while not making a dev build.
In my case this is because this line failed for me:
https://github.com/facebook/react-native/blob/2fdbf6a10fe67fa3209a51a1105a97c16991f561/scripts/react-native-xcode.sh#L153-L162

The error it gave wasn't shown during the xcode build, by adding an `echo` at the start of line 153 to get the command it was running then run it manually.
In my case the error was
```
error The resource `/Users/wsedlacek/Code/temp/example/index.js` was not found.
```

In my project I didn't have a `index.js` as I was using a monorepo, so the `ENTRY_FILE` needed to be configured.
So I added `ENTRY_FILE=apps/template/src/main.ts` to prefix the `react-native-xcode.sh` command in the `project.pbxproj` and my issue was solved.

**Comment by JDMathew** [comment]
I fixed this by removing `main.jsbundle` from Copy Bundle Resources under Build Phases in Xcode

**Comment by lrob7325** [comment]
This was happening to me using Expo 46 and EAS. I spent 3 days trying to resolve it. A combination of things I found on StackOverflow and here helped. Step 5 was essential and critical for having successful EAS builds. Everything else after are for those using the latest version of Expo and React Native, and can't compile locally or on Expo's EAS server.

1. ran "react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios"
2. Added "main.jsbundle" to the Xcode workspace.
3. Selected "Build Phases" and expanded "Copy Bundle Resources"
4. Dragged (or you can click the + icon) main.jsbundle into the section
5. I searched my repo for "main.jsbundle" and saw it was in the ".gitignore" and I removed all instances of it from the file.
6. Now that the repo wasn't excluding the main.jsbundle file in uploads and zips, it was able to compile!

For Expo 45+ and/or React-Native 0.69.4 users:
1. Since the latest version of React-Native deprecated ViewPropTypes, I ran "yarn add deprecated-react-native-prop-types"
2. Then I created a folder called "scripts" as a subdirectory of "src"
3. I located the "index.js" file in "node_modules/react-native" and copied it into my new "src/scripts" folder
4. In the "src/scripts/index.js" file, I replaced the Deprecated Prop Types around lines 436 with:
// Deprecated Prop Types
  get ColorPropType(): $FlowFixMe {
    return require("deprecated-react-native-prop-types").ColorPropType;
  },
  get EdgeInsetsPropType(): $FlowFixMe {
    return require("deprecated-react-native-prop-types").EdgeInsetsPropType;
  },
  get PointPropType(): $FlowFixMe {
    return require("deprecated-react-native-prop-types").PointPropType;
  },
  get ViewPropTypes(): $FlowFixMe {
    return require("deprecated-react-native-prop-types").ViewPropTypes;
  },
};

5. I then added the postinstall package to run commands after yarn is completed "yarn add postinstall"
6. I added this script to copy the edited index.js to the node_modules/react-native folder after yarn install completes 
- "patch-react-native": "PATCH_PATH=$(pwd)/script_patches/react-native/index.js && NODE_PATH=$(pwd)/node_modules/react-native/index.js && cp $PATCH_PATH $NODE_PATH"
7. Next add a postinstall script: "postinstall": "yarn patch-react-native"
8. Now with all of these steps I provided, I was able to build locally and on the eas server since the index.js files is getting replaced.

Hopefully, all of this can help future devs, or at least bits and pieces. This was a 55 hours journey, and I really want to help those who were forced to upgrade due to 3rd party libraries. For me, it was the integration of the Square Reader SDK.

Lastly, I really wish I had all of the urls, and usernames to provide thanks, and give credit, to. It was a lot of googling with trial and error.

**Comment by jhoow** [comment]
> this command helped me `npx react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios`

That's exactly what helped me too.

**Comment by Jongkeun** [comment]
It looks like react-native doesn't use `/opt/homebrew/bin/watchman`.
I added a symbolic link like this this fixed my issue.

```
ln -s  /opt/homebrew/bin/watchman /usr/local/bin/watchman 
```

**Comment by iSaBo96** [comment]
If i generate the bundle with "npx react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios" new, i get the error 
`error Failed to load configuration of your project.
info Run CLI with --verbose flag for more details.
`

I i add "--verbose", no information given.

**Comment by wSedlacek** [comment]
@iSaBo96 I have experienced this issue when missing dependencies in my `package.json`.

You can try to run `react-native config` as documented here: https://github.com/react-native-community/cli/blob/main/docs/commands.md#config

If the config doesn't look right, or has an error running that command check that your package.json and `react-native.config.js` are configured properly. If you are using `nx` then make sure you have run `nx sync-deps <project-name>`

**Comment by Vi-dot** [comment]
> if you are using a monorepo/yarn workspaces you're going to want to define the PROJECT_ROOT at the top of your Bundle React Native code and images script
> 
> ```
> export PROJECT_ROOT=$PWD/..
> ```
> 
> that's the build phase that was failing for me and this fixed it ^

yeaaah thank you !

**Comment by NguyenVanVietPoLy** [comment]
> * export NODE_BINARY=node
>   export PROJECT_ROOT=$PWD/..
>   ../node_modules/react-native/scripts/react-native-xcode.sh

thanks!!!

**Comment by garkuwa** [comment]
There are numerous reasons why you can get such an error "main.jsbundle does not exist". I got it when I my code had syntax errors (missing commas in styled-component entities), and I had to build the app with RN CLI instead of Xcode to see these errors.

**Comment by tranminhnhat1005** [comment]
I see that you have found a very good solution by creating a `main.jsbundle` file and adding it to the project.
But I also tried to find a different way with the intention of not creating a file but editing the `$NODE_BINARY` variable.
I use the output of the `which node` command to copy the result and replace it in the following location:

`"$NODE_BINARY" $NODE_ARGS "$CLI_PATH" $BUNDLE_COMMAND \ $CONFIG_ARG \ --entry-file "$ENTRY_FILE" \ --platform "$BUNDLE_PLATFORM" \ --dev $DEV \ --reset-cache \ --bundle-output "$BUNDLE_FILE" \ --assets-dest "$DEST" \ $EXTRA_ARGS \ $EXTRA_PACKAGER_ARGS`

change to

`which node  =>  PATH_TO_NODE/node/v16.15.1/bin/node`

`"PATH_TO_NODE/node/v16.15.1/bin/node" $NODE_ARGS "$CLI_PATH" $BUNDLE_COMMAND \ $CONFIG_ARG \ --entry-file "$ENTRY_FILE" \ --platform "$BUNDLE_PLATFORM" \ --dev $DEV \ --reset-cache \ --bundle-output "$BUNDLE_FILE" \ --assets-dest "$DEST" \ $EXTRA_ARGS \ $EXTRA_PACKAGER_ARGS`

Hope it useful.

**Comment by MrGru** [comment]
> if you are using a monorepo/yarn workspaces you're going to want to define the PROJECT_ROOT at the top of your Bundle React Native code and images script
> 
> ```
> export PROJECT_ROOT=$PWD/..
> ```
> 
> that's the build phase that was failing for me and this fixed it ^

I'm using nx, do you know how to fix this issue with nx monorepo

**Comment by Harisene** [comment]
I recently upgraded my React Native project from 0.64.0 to 0.73. I'm also getting this issue.

**Comment by YASH-CODE1** [comment]
> I fixed this by removing `main.jsbundle` from Copy Bundle Resources under Build Phases in Xcode

Such a simple solution, this is what exactly helped me, thanks a lot @JDMathew

**Comment by avinash-capsitech** [comment]
After added "main.jsbubdle" in iOS manually all latest changes are not update on file save and metro server disconnect after app successfully launched,Any solution...?

Thanks in advance

**Comment by nikolal** [comment]
My fix was:

`npx react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios`

Thanks to the: https://github.com/facebook/react-native/issues/32108#issuecomment-1449824810

**Comment by tinchomengo** [comment]
> For me it turned out that one of the .js files imported a file from a directory with incorrect case (folder vs Folder). Happened because when changing the case of a file/directory git doesn't recognize it unless specified explicitly. Make sure all your imports are correct.

This was exactly the issue that was making my React Native Bitrise pipeline crash, thank you. It's now solved and working.

Even though I changed the file name, the VSCode Git plugin seemed to push the same filename without the uppercase. I simply modified the imports and pushed that.
