### ISSUE TITLE
Width of PickerIOS.Item equal to the width of the PickerIOS only works in NavigatorIOS

### ISSUE THREAD

**Issue by chenkun24** [facebook/react-native#3211]
In simple page PickerIOS.item's width cannot change by style.
And in NavigatorIOS it equals to the width of PickerIOS.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/width-of-pickeriositem-equal-to-the-width-of-the-pickerios-only-works-in-navigatorios

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
