### ISSUE TITLE
React Native - Text/Emoji is not vertically aligning in view

### ISSUE THREAD

**Issue by Parveshdhull** [facebook/react-native#32198]
## Description
I tried several configurations, but I am unable to vertically center Text/Emoji inside a view

## React Native version:
0.65
I tested on "https://reactnative.dev/docs/text"

## Steps To Reproduce
This is the code I am using:
```
import React, { useState } from "react";
import { View, Text } from "react-native";

const TextInANest = () => {
  return (
    <View style={{width: 200, height: 200, backgroundColor: "red", justifyContent: "center", alignContent: "center"}}>
    <Text style = {{fontSize: 100, textAlign: "center", backgroundColor: "black"}}>
    🥺
    </Text>
    </View>
  );
};
export default TextInANest;
```

## Expected Results
Emoji should be in center

## Current Result (See gap above and below emoji)
![image](https://user-images.githubusercontent.com/17097240/133142951-4f5c83c3-969d-4671-9953-7289870bc5cf.png)

## Snack, code example, screenshot, or link to a repository:
Related stack overflow question: https://stackoverflow.com/questions/69167282/react-native-text-emoji-is-not-vertically-aligning-in-view

**Comment by TheLonelyAstronaut** [comment]
Just set lineHeight same as fontSize
![image](https://user-images.githubusercontent.com/50376577/133292197-2cf42f59-4e8f-4265-9544-206e49b7c08c.png)

**Comment by Parveshdhull** [comment]
No It is also not working.
I am attaching two screenshots, one from chrome and another from my android device

![image](https://user-images.githubusercontent.com/17097240/133302704-d3d89a63-0d32-4cad-b91a-3cd7553be1a0.png)

![Screenshot_2021-09-14-22-38-07-37](https://user-images.githubusercontent.com/17097240/133302755-23aaf9ed-c576-424b-a034-0b633580b40f.png)

**Comment by edison16029** [comment]
The issue is with the emoji itself rather than your styling. I tried to zoom in the emoji to get a clearer picture of what is happening.

You need to set the textAlignVertical to one of ['top', 'center', 'bottom'] to align it vertically. However, since in your code you are not giving any explicit height, it is automatically aligned to center vertically. However, as it can be seen from the following screenshots, the emoji is not vertically symmetric.

`<Text style = {{fontSize: 150, textAlignVertical: 'center', backgroundColor: "green", height: '50%'}}>
        🥺
        </Text>`
        
![Screenshot_1632151549](https://user-images.githubusercontent.com/42208749/134029307-3c055032-18a6-4b7b-b484-58bd491cd38b.png) ![Screenshot_1632151553](https://user-images.githubusercontent.com/42208749/134029500-12c46c99-2117-4180-a36f-f482751402ff.png) ![Screenshot_1632151559](https://user-images.githubusercontent.com/42208749/134029580-3df59ef9-23c9-4271-83c7-5d5569f99428.png)

**Comment by Parveshdhull** [comment]
Hi @edison16029,
Thanks for your comment, but I don't think it is something to do with emojis. I tried using text "O" and it showed the same behavior.

**Comment by Parveshdhull** [comment]
Looks like issue is only in android and web, not is ios.
