### ISSUE TITLE
React-Native Redux new reducer won't update until i reinstall my app

### ISSUE THREAD

**Issue by bartodt** [facebook/react-native#32201]
Hello! I added a new reducer to my app but it wont appear in the app until i reinstall it. Any idea of what is happening?

Thanks.

**Comment by yousseftarekkh** [comment]
@bartodt I think this might be more of a redux related issue. Since the issue here is with `redux` not `react-native`. Correct me if I am wrong please.

However, can you provide more information about the current case you're facing? Also include some snippets for the redux setup and the reducer to make sure it's not a `react-native` related issue.

**Comment by TheLonelyAstronaut** [comment]
Do you use redux-persist?

**Comment by bartodt** [comment]
> Hi, do you use redux-persist?

Yes! I am using redux-persist. Does this has to do something with this problem?

**Comment by TheLonelyAstronaut** [comment]
> > Hi, do you use redux-persist?
> 
> 
> 
> Yes! I am using redux-persist. Does this has to do something with this problem?


With redux persist you should write a migrations and version then to add new state to storage without reinstall. Check persist docs for more info.

**Comment by bartodt** [comment]
> With redux persist you should write a migrations and version this changes to add new state to storage without reinstall. Check persist docs for more info.

Oh my god, you are my hero. I've spent days trying to find the solution and you gave me the right answer. Thank you very much.
