### ISSUE TITLE
[Android] prop `pointerEvents` not respected on TextView

### ISSUE THREAD

**Issue by xinthink** [facebook/react-native#3220]
`Text` intercepted pointer events even when the `pointerEvents` prop set to `none`

code producing the problem:

```jsx
class TouchOnTextView extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      locationX: 0,
      locationY: 0,
    };
  }

  _onTouch({nativeEvent: {locationX, locationY}}) {
    this.setState({locationX, locationY});
  }

  render() {
    return (
      <Text
        pointerEvents="none"
        onStartShouldSetResponder={() => true}
        onMoveShouldSetResponder={() => false}
        onResponderGrant={this._onTouch.bind(this)}
        onResponderReject={this._onTouch.bind(this)}
        onResponderMove={this._onTouch.bind(this)}
        onResponderRelease={this._onTouch.bind(this)}
        onResponderTerminationRequest={() => true}
        onResponderTerminate={this._onTouch.bind(this)}
        style={{
          width: 300,
          height: 150,
          backgroundColor: 'rgba(100,200,100,.5)',
        }}
        >
        Touches: {this.state.locationX.toFixed(0)}, {this.state.locationY.toFixed(0)}
      </Text>
    );
  }
}
```

`_onTouch` shouldn't expected to be called, but it did on Android

**Comment by satya164** [comment]
@xinthink is this still an issue?

**Comment by xinthink** [comment]
Yes, I tested the above snippet on RN 0.17.0, the Responder callbacks still got invoked.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-prop-pointerevents-not-respected-on-textview

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
