### ISSUE TITLE
[Animated] Handling unexpected pauses gracefully

### ISSUE THREAD

**Issue by ide** [facebook/react-native#3221]
Currently Animated looks at the delta from the current time to the start time (time elapsed since start) to compute the current frame. This means that if we miss a frame deadline, Animated skips to the next frame and the stutter is significant.

Another policy is to display each keyframe, leading to a slower but smoother animation that completes at a later time. One use case is in games where the player wants to see all frames even if they are slow because it's bad if the game state suddenly jumps ahead.

**Comment by ide** [comment]
Just want to mention this isn't hi-pri but thought it was worth noting and experimenting with (e.g. bootcamp task even) to see if it makes apps feel better in some situations.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/animated-handling-unexpected-pauses-gracefully

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
