### ISSUE TITLE
ios 15 can't run in xcode react-native 0.59.9

### ISSUE THREAD

**Issue by Joker20000** [facebook/react-native#32267]
System:
      OS: macOS 11.6
      CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
      Memory: 695.96 MB / 16.00 GB
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.17.0 - /usr/local/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 23, 26, 27, 28, 29, 30, 31
        Build Tools: 28.0.3, 29.0.0, 29.0.3, 31.0.0
        System Images: android-26 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7621141
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild

the same code, run on ios 14

![image](https://user-images.githubusercontent.com/38452925/134801580-076d168a-f8df-4795-8f07-fdc27bc04bb8.png)

**Comment by alexDtorres** [comment]
Seems like iOS 15 will no longer let apps mutate symbol bindings at runtime, even when Debugging.

Does this mean local Metro server will break?.. I'll have to try in Xcode before speculating further.

**Comment by kevinkho1996** [comment]
Yeah, I also experienced the same thing. Do you have a solution for this problem? @Joker20000 

Trying with `react-native run-ios --simulator="iPhone 11"` will crash on the splashscreen and this warning appears: **"You can’t open the application "app_name" because this application is not supported on this Mac."**.

React native ver: 0.60.xx
Mac os: Monterey
