### ISSUE TITLE
`Linking.canOpenURL(url)` returns `false` in a context where `Linking.openURL(url)` works

### ISSUE THREAD

**Issue by BenStirrup** [facebook/react-native#32311]
## Description
`Linking.canOpenURL(url)` returns `false` despite the fact that `Linking.openURL(url)` works.
Only on certain android devices, for example OnePlus 9 Pro (Android 11) and Samsung Galaxy S10 (Android 11).
In opposition, it works on a OnePlus 5 (Android 11) and a Samsung Galaxy S9 (Android 11).

## React Native version:
0.64.2

## Steps To Reproduce
1. Try `Linking.canOpenURL(url)`
2. If it returns `false`, remove it and try then `Linking.openURL(url)` (within a try/catch for code safety), it should work.

## Expected Results
`Linking.canOpenURL(url)` should return `true` in a context where `Linking.openURL(url)` does open the url.

## Snack, code example, screenshot, or link to a repository:
Commit that we used to fix this issue : https://github.com/pass-culture/pass-culture-app-native/commit/7add481a5acd9d8735cd092e37d9df1c03e4a44e by removing `Linking.canOpenURL(url)` since we cannot "trust" it.

**Comment by osamaqarem** [comment]
The issue is caused by not specifying what apps we intend to access in the `AndroidManifest.xml` when targeting Android 11
https://developer.android.com/training/package-visibility

Here is an example fix which registers the signature of mail apps so that `Linking.canOpenURL` works correctly for `mailto` links:
https://github.com/chirag04/react-native-mail/pull/175/files
