### ISSUE TITLE
ios: cannot dismiss Modal

### ISSUE THREAD

**Issue by pritamsoni-hsr** [facebook/react-native#32329]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
When modal is dismissed the whole screen turns black. see video

## React Native version:
```
System:
    OS: macOS 11.6
    CPU: (8) x64 Apple M1
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    npm: 7.6.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  IDEs:
    Android Studio: Not Found
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_302 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: ~0.66.0 => 0.66.0
    react-native-macos: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.  use this [code](https://snack.expo.dev/@pritamsoni.hsr/restless-cereal) with react native 0.66 on iOS

![video](https://user-images.githubusercontent.com/23050213/135847538-81794191-c124-47d0-9182-90a4447cf603.MP4)

RCTModalHostViewController is what's blocking the screen
![Screenshot 2021-10-04 at 6 54 47 pm](https://user-images.githubusercontent.com/23050213/135859216-b7dc6524-00a4-4656-93da-608c0c837723.jpg)

![Screenshot 2021-10-04 at 6 49 43 pm](https://user-images.githubusercontent.com/23050213/135859267-f94eed0c-48e4-402a-956b-d4a408b33154.jpg)
.

**Comment by Hannes-Endare** [comment]
Having the same problem.

**Comment by Miraj98** [comment]
Yep, facing the same issue. I am on react-native version `0.65.1`

**Comment by pritamsoni-hsr** [comment]
replaced all the `RCTModal*` files with 0.63(which was working), this RCTModalManager files seems to be new, which has `_shouldEmit` **state** and `stopObserving` method, tried to remove the boolean check from [this](https://github.com/facebook/react-native/blob/7923804c28aac731396f0db112cb6c3a9d30c08f/React/Views/RCTModalManager.m#L38) statement stil not working

**Comment by superguineapig** [comment]
I just encountered this on an upgrade from `0.64.1` -> `0.66.0` (iOS X - 15 _simulator_). Traced it down to a [3rd party component](https://github.com/lawnstarter/react-native-picker-select) that is using a **transparent** `Modal` [under the hood](https://github.com/lawnstarter/react-native-picker-select/blob/ca6488c2eef5c776a8071400c8b7987712d43397/src/index.js#L431).

In this case it's even more insidious since the modal is set as `transparent`; Once displayed the modal's view never dismisses, and it swallows all touch events on the entire screen rendering the app effectively frozen. 

An experimental attempt to pass through a `pointerEvents: 'box-none'` prop had no effect as a workaround.

**However**, When in the simulator AND debugging is active, the Modal dismisses properly.

**Comment by effektsvk** [comment]
I had similar issue, but I'm using `react-native-modal`. After dismissing, the `Modal` also changed to `transparent` and only found it thanks to Xcode's "Debug View Hierarchy"... Also I was upgrading from `0.64.0` to `0.66.0`.

I'm having this issue in both debug and release, though. Happens on iOS 15 Simulator (debug), iPhone 12 mini (release) and iPhone 6S (release).

I didn't try debugging with Chrome because it causes my app to instantly crash and I have to reinstall it to even disable debugger 😅 But it's possible it's some kind of race condition, as Chrome decreases performance (**I think**).

**Comment by sharifhh** [comment]
+1 screen freezes after modal dismissing

**Comment by losh11** [comment]
I have a similar issue. My screen didn't turn black, but the entire app becomes unresponsive. Upgraded from RN 0.64.2 to 0.66, literally no other packages changed. 

I tried out the Modal component as part of the React Native standard library, also react-native-modal and react-native-paper's modal - they all had this same behaviour. I believe they are all wrapped versions of Modal from RN?

**Comment by lirimincodeks** [comment]
+1 app freezes on modal close  and  in some other libraries.

**Comment by effektsvk** [comment]
I just tested it without Flipper (just removed it from the Podfile, run `pod install` and rebuilt) but unfortunately for me the issue is still there. 😢

**Comment by smboy86** [comment]
in my case,

```
<Modal        
      animationType="fade"
      transparent={false}
      visible={isVisible}
      onRequestClose={() => onCloseModal(false)}>
```

'transparent true -> false'
if fix this, it works fine,

**Comment by dotansimha** [comment]
> I just tested it without Flipper (just removed it from the Podfile, run `pod install` and rebuilt) but unfortunately for me the issue is still there. 😢

I see, it seems inconsistent actually, at least for me. One thing is sure: When you open DevTool and debug in Chrome, it works well, right?

**Comment by NoerNova** [comment]
Screen freezing on a couple of situations for me, 

- Modal (react-native) -> no issue on react-native-paper's Modal
- FlatList and Animated.Flatlist on re-render, reload -> {flex: 1} on parent not help.

**BTW. all stuff works fine with opening debugging mode (Debug with Chrome) 🧐**

**Comment by effektsvk** [comment]
Just bumped into this while reading [`react-navigation` documentation](https://reactnavigation.org/docs/drawer-navigator/#uselegacyimplementation) 😅 So it makes sense why it works with Chrome debugger...
![image](https://user-images.githubusercontent.com/10141960/136594900-6e3e1a5e-13cb-44b3-8a4f-9972ddcc9974.png)

(cc: @dotansimha @NoerNova)

**Comment by supervons** [comment]
Same issue , i removed react-native-reanimated, everything works.

**Comment by dotansimha** [comment]
> Just bumped into this while reading [`react-navigation` documentation](https://reactnavigation.org/docs/drawer-navigator/#uselegacyimplementation) 😅 Although this is for drawer navigator, I'm assuming it applies to others as well. So it makes sense why it works with Chrome debugger... ![image](https://user-images.githubusercontent.com/10141960/136594900-6e3e1a5e-13cb-44b3-8a4f-9972ddcc9974.png)
> 
> (cc: @dotansimha @NoerNova)

Yeah, makes sense. But as far as I know, the Stack navigator doesn't have `useLegacyImplementation` or a similar flag :/

**Comment by Dmitry-GH** [comment]
Hey! For me, it looks like the problem is in "react-native-reanimated" lib. 
I downgraded it for now to fix it. Details: https://github.com/software-mansion/react-native-reanimated/issues/2244#issuecomment-940386618

**Comment by Dmitry-GH** [comment]
> A temporary workaround (that worked for me) _without_ having to downgrade anything, i.e. it **works** with the following:
> 
> ```json
> ...
> "react-native": "0.66.0",
> "react-native-reanimated": "^2.3.0-beta.2",
> ...
> ```
> 
> is to disable the autoinstall of Reanimated (during compilation) in your Podfile per their own [documentation here](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation#ios)
> 
> ```ruby
> post_install do |installer|
>    installer.pods_project.targets.each do |target|
>        target.build_configurations.each do |config|
>            config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '-DDONT_AUTOINSTALL_REANIMATED'
>        end
>    end
> end
> ```
> 
> Remember to `pod install` after changing the Podfile
> 
> This allowed my setup to compile and run normally without experiencing the zombie `UITransitionView` after dismissing a modal.
> 
> #### side note
> $0.02: I'm not convinced that the problem lies strictly within `react-native-reanimated` itself, but is manifest when some magic combination of `react-native`, `react-native-screens`, `@react-navigation/*`, and `react-native-reanimated` alter the native view hierarchy (UIKit) or inject event blocks that cause some async problems/race condition.
> 
> Additionally, a cursory search (google/SO) for `UITransitionView` has hits for "stuck" views going back 5+ years.
> 
> The latest versions of RN and Reanimated may have just "tickled" an old UIKit bug... 🤷

Hey, thanks for posting your solution! And your side note sounds logical and interesting to me!

Just out of curiosity: what is the downside of disabling the autoinstall of some package (reanimated in our case)? How it affects their work (dev/prod)? 
Sorry, for me it sounds like fully disabling the module in some way, so I want to learn more about it.
Thanks in advance!

**Comment by superguineapig** [comment]
@Dmitry-GH I'm not super familiar with the internals of Reanimated, but I believe it provides (at least) 2 main features for developers:

- A more expressive, pure JavaScript (vs JSX) API for scripting animations/animated behaviors
- The ability to ensure animations are calculated and executed on a native thread; so interpolations would be calculated on the native side as opposed to on the JS VM side and then having to sync over the bridge back into native (potentially several times per second). Pushing the animation stuff into native frees things up to handle events (touch) and trigger UI changes in a timely fashion.

With that, library and component authors can leverage the Reanimated lib to make things visually smooth and performant when there are complex UI transformations/layering/gesture effects, etc...

The potential downside to disabling the compiled code might be visual/performance issues in certain situations. They emphasize animations in response to gestures.

(Speculation) I would imagine that most of the mainstream dependent libraries conditionally depend on reanimated so disabling it will probably fall-back to regular RN behavior.

Not sure what happens if you've coded against Reanimated's API directly...no op perhaps...

Anyway, I'm not all that familiar with the implementation.

They have a good description of what purpose Reanimated serves [over here](https://docs.swmansion.com/react-native-reanimated/docs/#motivation)

**Comment by lzach83** [comment]
@cjhines Im in the same situation, amazing how fragile these things are.

**Comment by littleski** [comment]
Hello,
Version 2.2.3 of react-reanimated seems to fix the issue on our side.
Regards

**Comment by rodgomesc** [comment]
any solution for `v2.3-betaX` ? , this is not working in beta versions that's necessary for run @mrousavy  vision-camera, so because a modal issue i lot a camera lib ˆ.ˆ

**Comment by rodgomesc** [comment]
well, passing `coverScreen={false}` prop for `react-native-modal` seems to be a workaround for this as well, thanks for the help

**Comment by erikkjernlie** [comment]
Thank you so much 🔥 I had this problem with `react-native-modal` and `react-native-parallax-scroll-view`, but after upgrading from "2.3.0-beta" to "2.2.3", everything works perfectly 🙌

**Comment by mouessam** [comment]
issue still exists with react-native: `0.66.3` and react-native-reanimated: `2.2.3`

**Comment by 14bscsskazmi** [comment]
> Another update -- Here's what I ended up doing:
> 
> ```
> <View style={{flex: 1}}>
>     <Modal visible={isVisible}></Modal>
> </View>
> ```
> 
> This seemed to work, though I'm not sure why wrapping it with a View with flex: 1 is needed 🤔
> 
> I also then noticed that if I have multiple modals on the same page, this issue is only fixed for the first one (likely because of the `flex: 1`). So I updated the code to be
> 
> ```
> {isFirstModalVisible && (
>     <View style={{flex: 1}}>
>         <Modal visible={isFirstModalVisible}></Modal>
>     </View>
> )}
> 
> {isSecondModalVisible && (
>     <View style={{flex: 1}}>
>         <Modal visible={isSecondModalVisible}></Modal>
>     </View>
> )}
> ```
> 
> That way the modals are only rendered when visible, and there's only 1 modal on a page at a time.
> 
> This has solved my issue for now, but I wish I didn't have to do all this. Really hoping this issue is looked into.

Ohhh man!!! you saved the day. Thanks alot.

**Comment by denisk20** [comment]
Upgrading react-native-reanimated from 2.3.0-beta.2 to 2.3.0-beta.4 resolved the issue for me.

**Comment by chris-cornell** [comment]
i'm not using `react-native-reanimated` in my project and still facing this issue.

**Comment by johnjoshuadablo** [comment]
Still an issue on "react-native-reanimated": "2.2.4" and "react-native": "0.66.3"

**Comment by johnjoshuadablo** [comment]
> Another update -- Here's what I ended up doing:
> 
> ```
> <View style={{flex: 1}}>
>     <Modal visible={isVisible}></Modal>
> </View>
> ```
> 
> This seemed to work, though I'm not sure why wrapping it with a View with flex: 1 is needed 🤔
> 
> I also then noticed that if I have multiple modals on the same page, this issue is only fixed for the first one (likely because of the `flex: 1`). So I updated the code to be
> 
> ```
> {isFirstModalVisible && (
>     <View style={{flex: 1}}>
>         <Modal visible={isFirstModalVisible}></Modal>
>     </View>
> )}
> 
> {isSecondModalVisible && (
>     <View style={{flex: 1}}>
>         <Modal visible={isSecondModalVisible}></Modal>
>     </View>
> )}
> ```
> 
> That way the modals are only rendered when visible, and there's only 1 modal on a page at a time.
> 
> This has solved my issue for now, but I wish I didn't have to do all this. Really hoping this issue is looked into.



This worked for me initially but It has some issues when trying to open another modal again after closing this one. :( 

I also tried this with "react-native-reanimated": "2.2.4" and "react-native": "0.66.3" . Issue still persists on my end.

**Comment by denisk20** [comment]
> i'm not using react-native-reanimated in my project and still facing this issue.
@chris-cornell Check your .lock file -- it might have been pulled as a transitive dependency. I don't use it too, but `react-native-modal` does.

**Comment by effektsvk** [comment]
@chris-cornell Even easier way to check it is `yarn why react-native-reanimated`, it will show you which dependency is using it.
