### ISSUE TITLE
[Android] borderXxxColor props not respected when borderRadius set

### ISSUE THREAD

**Issue by xinthink** [facebook/react-native#3235]
I'm trying to draw a multi-colored circle, using the following snippet:

            <View style={{
                width: 64,
                height: 64,
                borderRadius: 32,
                borderColor: 'blue',
                borderBottomColor: 'green',
                borderLeftColor: 'green',
                borderRightColor: 'blue',
                borderTopColor: 'blue',
                borderWidth: 2,
              }}
            />

it should looks like this:
![2015-10-05 11 28 46](https://cloud.githubusercontent.com/assets/390805/10272620/32da8ebc-6b55-11e5-8064-79ac122933aa.png)

but I got a blue circle on Android, it seems that `borderXXXColor` props are not respected if `borderRadius` > 0

**Comment by andreicoman11** [comment]
Thank you for reporting! Looks like a bug in fresco, will pass this to them.

**Comment by PhilippKrone** [comment]
@andreicoman11 Did you open an issue in fresco? I do have the same issue and would like to subscribe to the issue :)

**Comment by JaRail** [comment]
I'm not sure what this has to do with Fresco. I'm new to this code but Fresco seems related to images.

It looks like the draw code for Views splits down two paths based on border radius.
https://github.com/facebook/react-native/blob/62e8ddc20561a39c3c839ab9f83c95493df117c0/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewBackgroundDrawable.java#L88-L95

When you don't have a borderRadius set, it goes through drawRectangularBackgroundWithBorders(). That handles the case where you have different border colors. It draws your borders as four rectangles.

For rounded corners, that goes into drawRoundedBackgroundWithBorders(). This method only cares about borderWidth and borderColor.

So in addition to borderXxxColor, borderXxxWidth is ignored.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-borderxxxcolor-props-not-respected-when-borderradius-set

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by arnavyagnik** [comment]
+1
I am getting the same behaviour, in ios it works fine and in android it does not obey color property if radius is present.

**Comment by KevinHu2014** [comment]
+1

**Comment by matiascba** [comment]
+1

**Comment by jreziga** [comment]
+1
