### ISSUE TITLE
Requiring classes within NativeModules fails

### ISSUE THREAD

**Issue by jamesfzhang** [facebook/react-native#3247]
I just encountered a weird issue where this fails on the simulator but works on my device:

```js
var AudioPlayer = require('react-native').NativeModules.AudioPlayer;
```

`AudioPlayer` is `undefined`. The interesting thing is that this works just fine on my iPhone, but not on the simulator. I've tried restarting the node server, XCode, etc.

All the standard native modules are available, just not any of the ones I created.

EDIT: This problem only seems to happen for my 5S and 6 simulator, not the 6S.

**Comment by cosmith** [comment]
Same thing here, I can't access `Geolocation.getCurrentPosition`... it stopped working after I switched to the CocoaPods version when installing https://github.com/facebook/react-native-fbsdk

**Comment by cosmith** [comment]
It actually doesn't work on my device either, so it might be something else. Investigating...

**Comment by cosmith** [comment]
Ok, if you're using cocoapods make sure to include all relevant subspecs... might help someone :) and it was probably not the same error as you @jamesfzhang, sorry.

```ruby
pod 'React', :subspecs => [
  'Core', 'RCTImage', 'RCTNetwork', 'RCTText', 'RCTWebSocket', 
  'RCTGeolocation', 'RCTActionSheet', 'RCTLinkingIOS'
], :path => '../node_modules/react-native'
```

**Comment by jamesfzhang** [comment]
Yep, different error but good catch, @cosmith.

**Comment by ide** [comment]
Doesn't really answer why this is happening but you could try clearing DerivedData and resetting your simulator content & settings.

**Comment by jamesfzhang** [comment]
Tried clearing DerivedData & simulator, but didn't really do anything. Tried every version and device and it's only broken on simulator 5S and 6. Do you know if this will be a problem when I submit the app?

**Comment by ide** [comment]
My guess is that it'll be fine. It could be an OS issue if somehow your 5s/6 sims are on iOS 8 but everything else is on iOS 9 though I don't think that's the case.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/requiring-classes-within-nativemodules-fails

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
