### ISSUE TITLE
[Image Layout] How to let image height to be auto?

### ISSUE THREAD

**Issue by yinzSE** [facebook/react-native#3259]
Hi, I get images from web and you know which are without fixed width or height.
However I want display the image with `screen width` and let them height auto.

**Comment by Emory-M** [comment]
Same issue, React-Native Android, I want put an unknown height Image from uri

**Comment by mrtone** [comment]
+1

**Comment by christopherdro** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

If you'd like you can create an issue on [Product Pains](https://productpains.com/product/react-native).
ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. 

Also, if this issue is a bug, please consider sending a PR with a fix. Thanks!
