### ISSUE TITLE
[Android] Dimension module doesn't give correct height after orientation change

### ISSUE THREAD

**Issue by satya164** [facebook/react-native#3264]
When orientation changes, the height and width are basically flipped. But the dimension module still gives the old height and width.

**Comment by foghina** [comment]
These should be an easy fix, PR would be appreciated.

**Comment by satya164** [comment]
@foghina Seems that the dimensions are defined as constants on the native side.

**Comment by kmagiera** [comment]
We should restrain from using dimensions as a constants in JS. In fact it would be better if we just delete Dimensions module completely as using it could be harmful. We can consider using react context for passing those but it needs to be clear that dimensions could change and this can happen not only due to orientation change (e.g. on iOS when incoming call bar is active)

**Comment by satya164** [comment]
@kmagiera What do you mean by harmful?

**Comment by kmagiera** [comment]
I've seen people trying to use dimensions consts to fix the height (or position) of some of the elements on the screen. In that case when you turn "incoming call" bar on iOS (or when hotspot is enabled) that element will go offscreen or will be cropped which is a bad user experience. Also people don't usually test their apps with incoming call bar on, so this is difficult to be noticed by dev teams. RN provides a better ways to position or stretch such elements. From our experience, in most of the cases it's sufficient to use flex properties to achieve the same goals (onLayout would be the last resort)

**Comment by satya164** [comment]
@kmagiera Understood. Thanks.

**Comment by satya164** [comment]
Fixed in b653d43e2e9d8a5506818b47d69993328132bbe4
