### ISSUE TITLE
[Android] [TextInput] When the window is moved up, touchables are messed up

### ISSUE THREAD

**Issue by satya164** [facebook/react-native#3265]
When I've a textinput at the bottom of the screen, and I focus the text input, the whole screen moves up. After that, the button coordinates are all messed up. If I've a button just alongside the input and I click it, it doesn't work.

Demo - https://rnplay.org/apps/1aY6yw

I've not set this up on rnplay, but what exactly happens is, the point which would be there if the screen hadn't moved up gets clicked (if there was a touchable at that place).

![screenshot_2015-10-07-18-45-32](https://cloud.githubusercontent.com/assets/1174278/10338440/ba16f10c-6d23-11e5-8da6-f39f70da0196.png)

Here a modal menu is shows which would have been shown if the chat bubbles were clicked.

I guess this is not specific to TextInput, and happens everytime the window gets moved up for any reason.

A pretty serious bug, I think.

**Comment by andreicoman11** [comment]
https://github.com/facebook/react-native/commit/c805157cac6acbb74690f209fe7bfd9ea51f8e55 fixes the part where clicking the button after the keyboard shows up does nothing (because of a bug in touch handling).
The part where the screen moves up is because of the `android:windowSoftInputMode` property, which was discussed to some extent here https://github.com/facebook/react-native/commit/c805157cac6acbb74690f209fe7bfd9ea51f8e55. Hope it helps!

**Comment by satya164** [comment]
@andreicoman11 Thank you. Will try building the app with master and report back.
