### ISSUE TITLE
[iOS]React Native gesture conflicts with native gesture

### ISSUE THREAD

**Issue by folist** [facebook/react-native#3280]
hi，I use a TouchableOpacity as a button, and this RCTRootView is added as a child view of UIScrollView.  When I drag this RCTRootView and then relex, TouchableOpacity's onPress is called（I don't want that in fact）. After debug, I find that when other gesture recognized, RCTTouchHandler can't receive touchesCancelled:withEvent:  message. How about send that message at touchesEnded:withEvent:? When touches ended, check if other gesture triggered,  if that, send touchesCancelled:withEvent: to self.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/iosreact-native-gesture-conflicts-with-native-gesture

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.

**Comment by guodong000** [comment]
in `RCTRootView.h`
```
/**
 * Calling this will result in emitting a "touches cancelled" event to js,
 * which effectively cancels all js "gesture recognizers" such as as touchable
 * (unless they explicitely ignore cancellation events, but noone should do that).
 *
 * This API is exposed for integration purposes where you embed RN rootView
 * in a native view with a native gesture recognizer,
 * whose activation should prevent any in-flight js "gesture recognizer" from activating.
 *
 * An example would be RN rootView embedded in an UIScrollView.
 * When you touch down on a touchable component and drag your finger up,
 * you don't want any touch to be registered as soon as the UIScrollView starts scrolling.
 *
 * Note that this doesn't help with tapping on a touchable element that is being scrolled,
 * unless you can call cancelTouches exactly between "touches began" and "touches ended" events.
 * This is a reason why this API may be soon removed in favor of a better solution.
 */
- (void)cancelTouches;
```

**Comment by hey99xx** [comment]
@guodong000 This is a fantastic solution. This worked great in my app. I'm slightly concerned about this line

> This is a reason why this API may be soon removed in favor of a better solution.

but it looks like it's staying for now. Hopefully it is documented on the main github docs website one day.

**Comment by shergin** [comment]
The fix https://github.com/facebook/react-native/commit/c68a70862168cd3df751c5110a0062493397dc9d should fix this problem, so we don't need to call `cancelTouches`.

**Comment by hey99xx** [comment]
I don't see how this removes my need for `cancelTouches`. Can you explain how your commit removes the need for this call?

Also see that the same API exists on Android, just with a different name. In fact it's the only method of the RootView interface https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/uimanager/RootView.java#L19-L23

As these are public functions people could have dependency on, please publish an alternative path in case you remove `cancelTouches` as we might still need it.

**Comment by shergin** [comment]
@hey99xx When your long press gesture recognizer will switch state to "recognized", iOS will ask RN gesture recognizer about possibility of simultaneous recognition, and in this case RN will fail self recognition, and it will cancel touches automatically.

Probably, there are cases where `cancelTouches` is only one possible solution, and because of this it's unlikely that this method will be completely removed soon.

I don't know how it works on Android, unfortunately.

**Comment by hey99xx** [comment]
> When your long press gesture recognizer will switch state to "recognized", iOS will ask RN gesture recognizer about possibility of simultaneous recognition, and in this case RN will fail self recognition, and it will cancel touches automatically.

Is this what will happen after your commit? I see the long press gesture recognizer goes into `UIGestureRecognizerStateBegan` and at this state it starts the animation, and notifies me. However React Native does not do anything at this stage, hence I need to call `cancelTouches`. If this behavior is fixed by your commit in future versions, all sounds good to me as I can delete my code as well.

**Comment by shergin** [comment]
Yes, you are right, actually switching an external gesture recognizer to "begun" also should fail RN gesture recognizer (and cancel touches as result).
