### ISSUE TITLE
npm ERR! fetch failed http://registry.cnpmjs.org/esprima-fb/download/esprima-fb-3001.1.0-dev-harmony-fb.tgz

### ISSUE THREAD

**Issue by GoldenForest** [facebook/react-native#3281]
npm ERR! fetch failed http://registry.cnpmjs.org/esprima-fb/download/esprima-fb-3001.1.0-dev-harmony-fb.tgz

**Comment by ide** [comment]
I think cnpmjs could be the problem. Can you configure your npm settings to read from the global npm repo?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/npm-err-fetch-failed-httpregistrycnpmjsorgesprima-fbdownloadesprima-fb-300110-dev-harmony-fbtgz

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
