### ISSUE TITLE
PinchResponder, RotationResponder, LongPressResponder, SwipeResponder

### ISSUE THREAD

**Issue by DaleJefferson** [facebook/react-native#3284]
We have a PanResponder is there any plans for other responders?

```
UITapGestureRecognizer
UIPinchGestureRecognizer
UIPanGestureRecognizer
UISwipeGestureRecognizer
UIRotationGestureRecognizer
UILongPressGestureRecognizer
```

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/pinchresponder-rotationresponder-longpressresponder-swiperesponder

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.

**Comment by mkonicek** [comment]
We should have a good generic solution for gestures but no one is currently working on this.

**Comment by mkonicek** [comment]
@facebook-github-bot answered
