### ISSUE TITLE
[TextInput] Adding textTransform to TextInput styles

### ISSUE THREAD

**Issue by ide** [facebook/react-native#3294]
Values are: none (default), capitalize, uppercase, lowercase. While I'd love for these to be implemented in JS we don't have a synchronous bridge. @vjeux just want to check with you that you would be on board with textTransform for input components.

**Comment by grabbou** [comment]
It reminds me of my issue when I requested the above for the Text component as well

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/textinput-adding-texttransform-to-textinput-styles

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.

**Comment by mbashiq** [comment]
You can uppercase the TextInput values like this : 
`<TextInput style={styles.input} autoCapitalize="characters"/>`
