### ISSUE TITLE
[Android] Shared Element Activity Transition

### ISSUE THREAD

**Issue by skv-headless** [facebook/react-native#3301]
https://github.com/codepath/android_guides/wiki/Shared-Element-Activity-Transition

![68747470733a2f2f692e696d6775722e636f6d2f72556b6b66555a2e676966](https://cloud.githubusercontent.com/assets/1488195/10389828/eeac499e-6e7c-11e5-87cd-13092f33b420.gif)

Is it possible to make such transition with react native?

**Comment by brentvatne** [comment]
cc @mkonicek @kmagiera

**Comment by mkonicek** [comment]
We don't expose the Android transition API but take a look at the Animated:
https://facebook.github.io/react-native/docs/animated.html

Can you please use Stack Overflow to ask questions and tag them with react-native? http://stackoverflow.com/questions/tagged/react-native

Many people from the community hang out on Stack Overflow and will be able to see your question. Using Stack Overflow for questions also helps us use Github issues to keep track of bugs that need to be fixed.

**Comment by samuelkraft** [comment]
@skv-headless Did you find a way to do this?

**Comment by asarazan** [comment]
Seeing that @samuelkraft's SO post has been [downvoted and abandoned](http://stackoverflow.com/questions/36770035/react-native-how-to-do-a-shared-element-zoom-transition-using-navigator), I wonder if the devs could please pick it up here? This is a hugely important issue for Android devs who care about platform convention.

**Comment by sonnylazuardi** [comment]
👍

**Comment by shilch** [comment]
👍

**Comment by samuelkraft** [comment]
I think the only possible way to do this right now is showing a placeholder/copy of the element in your root view on tap - animating and then showing the "real" view after the animation. @brentvatne describes if briefly in [this talk](https://youtu.be/cI9bDvDEsYE?t=25m47s). 
It gets pretty messy after a while and because this is such a common pattern for mobile apps I'd love an easier solution..

**Comment by shilch** [comment]
Thanks for sharing a workaround!

**Comment by brentvatne** [comment]
@lelandrichardson is working on something at Airbnb ([see this tweet](https://twitter.com/intelligibabble/status/764161292248637442)) and @janicduplessis is experimenting with this for [ex-navigation](https://github.com/exponentjs/ex-navigation), so hopefully we'll have a better answer to this in the next couple of months.

**Comment by samuelkraft** [comment]
That's great news! Can't wait! 👍

**Comment by SudoPlz** [comment]
I'd LOOOVE that as well! Please share even if it's not production ready, perhaps the community can help!

**Comment by lelandrichardson** [comment]
For more context: We have shared element transitions working and are using it in our app (i believe currently all of the RN ones are behind experiment flags still, but will be in production soon).  The way we do this is fully native (as opposed to how @janicduplessis is doing it, more js-centric), and is more or less coupled with our navigation library as well, which I hope to be open sourcing in the next couple of months.

FWIW, I hope to also implement [this proposal](https://github.com/facebook/react-native/issues/9855) at some point which will make doing things like this (and more) from JS-land a lot easier, and should also hopefully make @janicduplessis's solution a lot more performant.

If anyone is curious about how the iOS side of this was implemented (don't have public details on the android side yet), i wrote a somewhat lengthy gist about it here: https://gist.github.com/lelandrichardson/a37baf613fd96ff2b52711dc78094cc2

**Comment by gaston23** [comment]
I have some questions... :) 

1) What if the shared element is an ongoing playing video? Say using react-native-video, If we create a new instance it will redownload it from the internet, pausing. 

2) how could this transition (specially for dismissal) be iteractive? Again, imagine if the shared element is a video.

Is there any way we could move the original native view of the element we want freely from one place to another?

Natively in iOS It would be extremely easy because we have the UIView pointer and we can manipulate it remove/insert it wherever we want, and the video would keep playing. More over when the animation ends, we could still reuse the original video object (not creating a new one). 

Thank you

**Comment by janicduplessis** [comment]
@gaston23 This won't be possible with the current implementation since we create the view multiple times to animate it from one screen to the other. Reusing the same view for the transition would make it a lot harder to implement and work properly with the layout of both screens. 

Not sure what the best solution for that use case would be but maybe a custom component the is rendered on top of the navigator that resizes itself during the screen transitions or maybe write a custom native component.

**Comment by king6cong** [comment]
Any updates? 😸

**Comment by braco** [comment]
Just out of curiosity, why is it not enough to use `LayoutAnimation.configureNext()` for this effect?

https://medium.com/@Jpoliachik/react-native-s-layoutanimation-is-awesome-4a4d317afd3e#.ntn7h53jh
