### ISSUE TITLE
Nested scrollview is not working in react native android but working in ios ?

### ISSUE THREAD

**Issue by prashanthnani** [facebook/react-native#3303]
```
<ScrollView>  
    <View> <Text>Hello</Text> </View> 
    <View><Text>Hello</Text>  </View> 
    <View><Text>Hello</Text>  </View> 
    <View><Text>Hello</Text>  </View> 
    <View>       
        <ScrollView>
            <View> <Text>Hello</Text> </View>         
            <View><Text>Hello</Text>  </View>         
            <View><Text>Hello</Text>  </View>          
            <View><Text>Hello</Text>  </View>      
        </ScrollView> 
    </View> 
</ScrollView>

```

**Comment by foghina** [comment]
I think @andreicoman11 was looking into something similar.

**Comment by foghina** [comment]
Or was it @kmagiera? :)

**Comment by kmagiera** [comment]
Can you provide some more details on how it's "not working":
1) crashing app?
2) causing red box?
3) not rendering anything?
4) not scrolling?

**Comment by satya164** [comment]
@prashanthnani Any updates?

**Comment by mpretty-homepass** [comment]
Just my 2 cents - Android doesn't actually handle nested scroll views that well, have you tried testing the UI using native Android to see if the behaviour differs at all?

**Comment by satya164** [comment]
Closing since no response. Let's re-open if you're still having the issue.

**Comment by cuitianze** [comment]
a horizontal scrollview with nested vertical scrollview will crash the app.

Android version: 4.4.4 KTU84P   (MI 3)

**Comment by minkesh** [comment]
I thinks @prashanthnani means to say it's not scrolling. Same issue with me too.

**Comment by tommychoo** [comment]
I have same issue too, have any ways to solve ?

**Comment by divyekhanna** [comment]
Same issue here

**Comment by Rashhh** [comment]
Same issue here

**Comment by colin3dmax** [comment]
Same issue here

**Comment by ranjithnori** [comment]
Any updates / monkey patches to fix this ? Facing the same issue on android.

**Comment by satya164** [comment]
No one is working on this AFAIK.

**Comment by ABleas** [comment]
In my case it occasionally works, but it's really difficult to get the child scroller to scroll. I am wondering how scrollers are done on Android, because I can't find any reference to NestedScrollView in RN source?

I have vertical scrollers inside a horizontal (paged) scrolling parent, which is pretty much how the Facebook app works on Android. So they are doing *something* to get that working smoothly. Any tips @satya164? :)

**Comment by chuyik** [comment]
I found out if a horizontal ScrollView is inside a vertical ScrollView, the horizontal one will become hard to swipe on Android.
What I mean is the swipe gesture is easily recognized as a scroll gesture, and it's hard for me to do something like a Carousel inside a ScrollView because I have to implement the gesture recognizer for this with a PanResponder to prevent a bad user experience.

**Comment by urnotzhaoll** [comment]
any solutions?

**Comment by rajsuvariya** [comment]
any updates?

**Comment by mikelambert** [comment]
Vertical inside vertical, or horizontal inside horizontal, is a native android problem, and there are a lot of hacky workarounds out there on stackoverflow of folks trying to fix it. I don't know much more about that.

As far having a vertical inside horizontal (or vice versa), this also appears to be a native Android problem. `ScrollView` children are dependent on the parent scrollview "passing" the touch event to the child. But the parent is basically configured with a certain `mTouchSlop` (which I can't find a way to override, even in native Java code), which causes it to absorb drags beyond that slop. Since the slop appears to be set low, it often prioritizes scrolling in the *outer* scrollview, and makes it difficult to scroll in the inner one.

No idea on a fix. In my case, I may need to revert back to using something like a `react-native-viewpager` (which handles the scroll thresholds itself in JS, and is roughly equivalent to the `FlatList` functionality I want). Though I recognize that only helps my specific use case, and probably won't help most of you.

**Comment by Rpeanut** [comment]
any updates?

**Comment by shukerullah** [comment]
any updates?

**Comment by boliveira** [comment]
Any updates? :)

**Comment by Cygnus2112** [comment]
Any updates?

**Comment by ashrithks** [comment]
https://gist.github.com/ashrithks/8d97f928d92643468a26e29c4d2dbb67

try the above ,
expo link:-
https://snack.expo.io/S11vIpHA-

hacky way

**Comment by Sergeypt423** [comment]
@ashrithks 
Your solutions is not working in TabNavigator.

I used KeyboardAwareScrollView(vertical) in TabNavigator and inside the vertical scrollview, there's a horizontal scrollview.

Gesture swiping horizontal only recognised with TabNavigator not with horizontal scrollview.

Any Idea?

thanks

**Comment by ashrithks** [comment]
@Sergeypt423 
The above example is for vertical scroll views, with tab navigator, u have handle the scroll responders, In your case u have tab , vertical and horizontal scroll views ,

**Comment by Sergeypt423** [comment]
In my case, there is vertical scroll view and inside of it, there's horizontal scroll view.
I've tried your solution but I'm not sure how I can do it with responders.
Could you help me?

Here's my code
<KeyboardAwareScrollView resetScrollToCoords={{ x: 0, y: 0 }}>
        <View style={styles.container}>
          <View style={styles.buttonContainer}>
            <View style={styles.cardContainer}>
              <ScrollView
                style={{
                  height: height(18) + 15,
                  paddingTop: 5,
                  paddingBottom: 10,
                  marginLeft: 15,
                  marginRight: 15,
                  paddingLeft: 5,
                  paddingRight: 5,
                }}
                horizontal
              >
                {props.contractImages.map((item, key) => {
                  return (
                    <View style={styles.pageView}>
                      <Image
                        style={{
                          width: width(33) - 23,
                          height: height(18),
                          overflow: 'hidden',
                          borderRadius: 5,
                        }}
                        source={{ uri: item.path }}
                        resizeMode="stretch"
                      />

                      <TouchableOpacity
                        style={{
                          position: 'absolute',
                          marginTop: height(18) - 25,
                          marginLeft: 5,
                          width: 20,
                          height: 20,
                        }}
                        onPress={() => props._deleteContractImage(key)}
                      >
                        <Image
                          source={images.trashIcon}
                          style={{ flex: 1, position: 'absolute' }}
                          resizeMode="contain"
                        />
                      </TouchableOpacity>
                    </View>
                  );
                })}
                <View style={styles.pageView}>
                  <TouchableOpacity
                    style={{ flex: 1, justifyContent: 'center' }}
                    onPress={_showContractsCopyScreen}
                  >
                    <Image
                      source={images.addTab}
                      style={{ width: 25, height: 25, alignSelf: 'center' }}
                      resizeMode="stretch"
                    />
                  </TouchableOpacity>
                </View>
              </ScrollView>
            </View>
            <View style={{ height: 10 }} />
          </View>
        </View>
        
      </KeyboardAwareScrollView>

**Comment by Sergeypt423** [comment]
Here's my code
<KeyboardAwareScrollView resetScrollToCoords={{ x: 0, y: 0 }}>
            <View style={styles.cardContainer}>
              <ScrollView
                horizontal
              >
                {props.contractImages.map((item, key) => {
                  return (
                    <View style={styles.pageView}>
                      <TouchableOpacity
                        onPress={() => props._deleteContractImage(key)}
                      >
                      </TouchableOpacity>
                    </View>
                  );
                })}
              </ScrollView>
            </View>
</KeyboardAwareScrollView>

**Comment by iksent** [comment]
https://snack.expo.io/S11vIpHA-

Solution works for me, thank you, ashrithks

react-native: "0.48.4"

**Comment by Elijen** [comment]
Stale bot is a nice way of reducing open issues count, but does it really help anybody? 🤬

**Comment by rajsuvariya** [comment]
No, it doesn't. There are several issues which are not being looked at and
then stale bot closes it due to inactivity and developers like me working
in solution based companies with tight deadlines suffers a lot.

-- 
Raj Suvariya
*Android / React Native Developer*
Kuliza Technologies, Bangalore
Medium : https://medium.com/@rajsuvariya
m: +91-9099809050
<https://www.facebook.com/profile.php?id=100006523120386>
<https://twitter.com/RAJ_SUVARIYA>
<https://www.linkedin.com/in/rajpatel039/>

**Comment by murthy474** [comment]
is there any solution for ScrollView

**Comment by AndrejGajdos** [comment]
+1

**Comment by kwes01** [comment]
is there any solution?

**Comment by santhosh77h** [comment]
is there any solution available?
