### ISSUE TITLE
[ListView] Style/Wrapper on custom sections

### ISSUE THREAD

**Issue by Mokto** [facebook/react-native#3318]
Hi !

I have a ListView with two different sections.

The first one is classic, but I have to set a custom style (or wrapper) only on the second section (flexDirection: 'row', flexWrap: 'wrap' in my case).
I can only set it on ListView but it breaks the first section.

I think this is a needed feature, but I might be wrong. (I could make a PR if needed)

Please let me know if you need anything else.

![capture d ecran 2015-10-09 a 21 56 02](https://cloud.githubusercontent.com/assets/5103928/10408609/96174082-6ed0-11e5-9072-e2d405e2a8f4.png)

**Comment by mikearmstrong001** [comment]
Many thanks for your thoughts, PRs are always considered

**Comment by vjeux** [comment]
Can you provide a example of what's broken on rnplay.org and a concrete suggestion for the fix, I'm not really sure what is broken from your description and screenshot

**Comment by ide** [comment]
He wants a different flex layout per section, which means we would need to wrap each section's rows in a View instead of all of the rows + section headers being siblings of each other.

**Comment by Mokto** [comment]
@ide exactly ;)

**Comment by Mokto** [comment]
It could be an optional renderSection attribute:

renderSection={(sectionName, elements, renderRow) => <View>{renderRow()}</View>}

which is by default 
renderSection={(sectionName, elements, renderRow) => {renderRow()} }

Something like this.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/listview-stylewrapper-on-custom-sections

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
