### ISSUE TITLE
Update documentation. requireNativeComponent don't expose View in "Native UI Components" Documentation  

### ISSUE THREAD

**Issue by kostiakoval** [facebook/react-native#3338]
I follow the tutorial Step by step, how to make a custom View Component from here.
https://facebook.github.io/react-native/docs/native-components-ios.html#content

This code doesn't work for me.
```js
var { requireNativeComponent } = require('react-native');

// requireNativeComponent automatically resolves this to "RCTMapManager"
module.exports = requireNativeComponent('RCTMap', null);
```
I had to specify variable name when requiring native component.
```js
var { requireNativeComponent } = require('react-native');
var MyView = requireNativeComponent('RCTMyView', null);
module.exports = MyView
```

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/update-documentation-requirenativecomponent-dont-expose-view-in-native-ui-components-documentation-

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
