### ISSUE TITLE
[Android] [Idea] Use stetho to inspect network requests

### ISSUE THREAD

**Issue by satya164** [facebook/react-native#3339]
Currently it's not possible to inspect network requests as they are polyfilled using Native code. May be we could somehow use Stetho to be able to inspect these?

http://facebook.github.io/stetho/

cc @ide @mkonicek

**Comment by ide** [comment]
Sounds cool. Is there a clean way we can let people inject add it to the OkHttp clients that RN makes?

**Comment by satya164** [comment]
It seems that we have to attach the interceptor manually to the each OkHttp client. Since people cannot modify React Native's code, may be there might be a public API to add interceptors, or React Native can support Stetho by default. I've not thought much about the API though.

**Comment by mikearmstrong001** [comment]
We are always looking for thoughts on what would make good dev tools so thank you! I'll let @mkonicek comment on his thoughts and priorities.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-idea-use-stetho-to-inspect-network-requests

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.

**Comment by mkonicek** [comment]
It would be cool if the Chrome Network tab showed network requests.
