### ISSUE TITLE
set ImageBackground style with height: '50%' backgroundImage got 25% height 

### ISSUE THREAD

**Issue by mingyili** [facebook/react-native#33513]
### Description

When I set the height of ImageBackground to 50%, it seems that both the Image and its container got 50% height, turn out the image got 25% but not 50% height to the ImageBackground container.
react-native 0.62.2 is 50%
react-native 0.67.2 is 25%
all the '%' style got the same problem

### Version

0.67.2

### Output of `npx react-native info`

nothing

### Steps to reproduce

```javascript
<View style={{ width: 400, height: 400, backgroundColor: '#333' }}>
  <ImageBackground
    style={[{ width: '100%', height: '50%', backgroundColor: '#aaa' }]}
    source={require("./images/bg.png")}>
    <Text style={{ color: '#fff' }}>contexts</Text>
  </ImageBackground>
</View>
```
![image](https://user-images.githubusercontent.com/5360986/160534971-6ae6d170-70f2-4778-bca0-d9ec3c2cb984.png)

**Comment by Marcoo09** [comment]
The problem seems to be related to the fact that the Image component on ImageBackground implementation is using a flattenedStyle that depends on style, the same one that is used in the container View, so the container has a width of 50% and the nested image also has 50% so => 25 %
<img width="929" alt="image" src="https://user-images.githubusercontent.com/18408823/160684614-3c06a7da-eaa0-452d-999d-2e08af5b0513.png">
You should use imageStyle instead of style
<img width="526" alt="image" src="https://user-images.githubusercontent.com/18408823/160684973-9ffccb54-9109-4fe3-8814-20efdbaa46fe.png">
