### ISSUE TITLE
react-native bundle --minify doesn't set dev to false

### ISSUE THREAD

**Issue by syousif94** [facebook/react-native#3368]
running 0.12.0, --minify argument no longer sets dev to false

running react-native bundle does set dev to false

**Comment by jabez128** [comment]
in `AppDelegate.m` file, add 

```objective-c
#define DEBUG 0
#define RCT_DEV 0
#define RCT_DEBUG 0
```

**Comment by javache** [comment]
@martinbigio Should we change the default value for dev? It's currently also inconsistent with the documentation on https://facebook.github.io/react-native/docs/running-on-device-ios.html

**Comment by martinbigio** [comment]
What's the dev env variable used for? The big problem I see is that the `--minify` option is not getting used. I'll fix this asap. Also just updated the docs with the breaking changes on the `react-native bundle` API, but I might tweak the API a bit more

**Comment by jedt** [comment]
@martinbigio according to the react-native cli bundle 

Usage: react-native bundle [options]

Options:
  --dev		sets DEV flag to true
  --minify	minify js bundle
  --root		add another root(s) to be used in bundling in this project
  --assetRoots		specify the root directories of app assets
  --out		specify the output file
  --url		specify the bundle file url
  --platform		specify the platform(android/ios)

Should dev=true hide the top black bar? because bundling even without --minify flag doesn't hide this.

**Comment by ide** [comment]
dev=true doesn't hide the black bar. What's going on there is that the binary was built in DEBUG mode instead of RELEASE. What dev=true does is tell the JS to set `__DEV__ = false`, which skips things like prop type checking in React.

**Comment by martinbigio** [comment]
Do you guys mean the black top bar that is shown when loading the JS bundle right? So, then this change didn't break anything or I got it wrong?

**Comment by jedt** [comment]
@martinbigio Nope, sorry I may have I caused confusion. The bug is valid and can be replicated. 

For the on the Xcode console log:

When I bundle using:
`$ react-native bundle --platform=ios --minify`

I then run Xcode on the device, I get the log result:
`2015-10-15 07:41:20.483 [info][tid:com.facebook.React.JavaScript] 'Running application "ReactPayments" with appParams: {"rootTag":1,"initialProps":{}}. __DEV__ === 1, development-level warning are ON, performance optimizations are OFF'`

But when I bundle using 
`$ react-native bundle --platform=ios`

I run Xcode , i get this:
`2015-10-15 07:44:47.531 [info][tid:com.facebook.React.JavaScript] 'Running application "ReactPayments" with appParams: {"rootTag":1,"initialProps":{}}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON'`

**Comment by gre** [comment]
I was getting into the same problem, and notice this in the documentation: http://facebook.github.io/react-native/docs/debugging.html#debugging-react-native-apps

See in the Hints.

You need to deploy your app in Release mode, not in Debug (by switching in XCode / Scheme).

**Comment by martinbigio** [comment]
Looks like @gre is right. Please re-open if you're still having issues after doing what he suggests :)

**Comment by gre** [comment]
We need to make this more obvious in the documentation I think. It took me maybe 30min to find it ;)

**Comment by rreusser** [comment]
I'm similarly struggling to process the documentation and understand how to test a production Android build. (i.e. the equivalent of the 'Release' scheme in XCode).

[Running on Device](http://facebook.github.io/react-native/docs/running-on-device-android.html#content) covers dev mode just fine, and [Generating Signed APK](http://facebook.github.io/react-native/docs/signed-apk-android.html#content) covers publishing, but there's some middle ground equivalent to [Using Offline Bundle](http://facebook.github.io/react-native/docs/running-on-device-ios.html#using-offline-bundle) in the iOS guide that doesn't readily present itself for Android. Is there an Android equivalent?

**Comment by rreusser** [comment]
Sorry, slightly OT. I can open open a new issue if that's best. I'm never quite sure whether opening issues for the sake of community understanding is mostly problematic noise for the developers actually doing the work.

**Comment by af7** [comment]
I agree with the ""Release for production" page, covering also some info related to Xcode for someone that have never used Xcode before (in terms of creating react native project, not everything of course!).

**Comment by deehuey** [comment]
Is there no easy way to turn react optimizations ON while deving so i can test how fast something is in real world?

**Comment by Metroxe** [comment]
@deehuey did you ever figure out how to turn react optimizations ON?
