### ISSUE TITLE
0.68.1 issue with find-node.sh

### ISSUE THREAD

**Issue by billnbell** [facebook/react-native#33695]
### New Version

0.68.1

### Old Version

0.68.0

### Build Target(s)

12

### Output of `react-native info`

System:
    OS: macOS 12.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 353.81 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/bill/.rvm/gems/ruby-2.7.4/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 25, 26, 27, 28, 29, 30, 31
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0
      System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64, android-R | Google APIs Intel x86 Atom, chromeos-67 | Chrome OS 67
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14.1 - /usr/local/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: ^0.68.1 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

OK, 

I tried fixing this - but unsuccessful. I am using nvm, and set .nvmrc. I keep getting error on building.
I can fix it by going into node_modules/react-native/scripts/find-node.sh and changing to set +x instead of set -x.

It is getting confused on node.

I am unsure how to fix it.

**Comment by fortmarek** [comment]
Hey @billnbell 👋 

Can you post the reproduction steps as well?

**Comment by cipolleschi** [comment]
Can you explain better what issue are you finding?

For more context: `find-node.sh` is the old way to let RN search for node. We have now introduced the `.xcode.env` and `.xcode.env.local` files to help users in configuring their environment.

The priority is that `.xcode.env.local` will be used, if there. Otherwise, the system will use `.xcode.env`. The last resort is to use `find-node.sh`.

My suggestion is to update `.xcode.env.local` with the output of `command -v node` and to setup the `.xcode.env` file properly for the CI. The `.xcode.env` file already contains a suggestion on how to configure `nvm`

**Comment by billnbell** [comment]
this is super old and was fixed by setting right node version.
