### ISSUE TITLE
[Robustness] Redbox on Android destroys the JS bridge

### ISSUE THREAD

**Issue by ide** [facebook/react-native#3370]
Sometimes when you get a redbox on Android the JS bridge stops working and you have to reload the entire app. From working with RN iOS it's been really good that the native layer is fairly robust and doesn't often crash or stop the app from working. Additionally you can implement your own policy to reconstruct the bridge or just keep the app in its current state when a fatal error occurs and sometimes the latter is preferable when you can deal with the errors.

**Comment by foghina** [comment]
I recently had a look at this and actually fixed it temporarily (3dcc234), but that made some internal tests flaky which suggests these exceptions leave the bridge in a bad state, so it got reverted (1d8d3d7).

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/robustness-redbox-on-android-destroys-the-js-bridge

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
