### ISSUE TITLE
[Network] Android doesn't respect Cache-Control max-age set by server

### ISSUE THREAD

**Issue by PaulBGD** [facebook/react-native#3372]
When using fetch to fetch a resource that is sent with the header of Cache-Control set to a max-age (mine being 2592000) it doesn't respect it on the next fetch and will get new data every time. This doesn't happen on iOS.

**Comment by javache** [comment]
@kmagiera Is this specific to OkHttp?

**Comment by PaulBGD** [comment]
I'm not sure sorry, I haven't done "Android development" before trying it with React.

**Comment by kmagiera** [comment]
I believe this might be a problem with okhttp setup. I can look into this tomorrow

**Comment by PaulBGD** [comment]
Looking into this, it looks like we'll need to use the [HttpResponseCache](https://developer.android.com/reference/android/net/http/HttpResponseCache.html) then call `setResponseCache(HttpResponseCache.getInstalled())` on our client instance.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/network-android-doesnt-respect-cache-control-max-age-set-by-server

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
