### ISSUE TITLE
React Devtools tab not showing up in Chrome Devtools after upgrading to 0.12

### ISSUE THREAD

**Issue by gnestor** [facebook/react-native#3373]
Is anyone else experiencing this? I downgraded to 0.11 and the "React" tab returned.

**Comment by ide** [comment]
Known issue and needs work: https://github.com/facebook/react-devtools/issues/229

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/react-devtools-tab-not-showing-up-in-chrome-devtools-after-upgrading-to-012

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
