### ISSUE TITLE
View requires explicit height to render inside a ListView if empty on 0.12.0

### ISSUE THREAD

**Issue by chriskurzeja** [facebook/react-native#3381]
I've implemented a simple renderRow function that uses an empty view that has a background colour applied on one side and the other side has row data. You can see the example working in 0.11.4 here https://rnplay.org/apps/kyAXMA. 

This behaviour is inconsistent with the 0.12.0 version. The only way to get the empty coloured view to render is to specify a height. I would expect alignItems: 'stretch' on the parent view to be sufficient to make this behave as I'd expect. 

Has something been changed between versions? Is there a more appropriate way to be doing this?

Thanks

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/view-requires-explicit-height-to-render-inside-a-listview-if-empty-on-0120

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
