### ISSUE TITLE
ScrollView with stickyHeaderIndices and contentOffset

### ISSUE THREAD

**Issue by roine** [facebook/react-native#3386]
React Native: 0.14

I can't use `stickyHeaderIndices` in conjunction with `contentOffset`, it returns:

> Sticky header index 1 was outside the range {0,0}

If I remove one or the other each feature works as expected, but together they just won't.

**Comment by arilitan** [comment]
this issue has been driving me nuts! anyone having any luck?

**Comment by watert** [comment]
It seems when there's contentOffset prop, the scroll view will did scroll action before rendering its children nodes, and the scroll action will triggers sticky header method, and causes this out of range error. I think it is a bug needed to be fixed by official team.

But a temporary solution is to change the `stickyHeaderIndicies` value when the component is mounted, just like this:

```javascript
// the component
componentDidMount(){
	this.setState({stickyHeaderIndices:[0]})
},
getInitialState(){
	return {stickyHeaderIndices:[]}
},
// when rendering scrollview props
stickyHeaderIndices={this.state.stickyHeaderIndices}
```

**Comment by sercanov** [comment]
+1 with @watert 
It only happens when ListView has contentOffset property.

**Comment by nicklockwood** [comment]
I believe this is already fixed in latest master branch.

**Comment by christopherdro** [comment]
@facebook-github-bot answered
