### ISSUE TITLE
If view style height is set to 0, it will behave similar to "auto" in div's

### ISSUE THREAD

**Issue by yrokhlin** [facebook/react-native#3397]
If you set a <View> height style to 0, it will act as if it's auto height, the work around currently is to set it to 0.01, but this doesn't seem right.

**Comment by browniefed** [comment]
Just ran into this as well. Seems that something updated in the .11.4 => .12 caused this to happen. Unsure if this is a react-native issue or a css-layout issue.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/if-view-style-height-is-set-to-0-it-will-behave-similar-to-auto-in-divs

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
