### ISSUE TITLE
Make running inside Chrome Web Worker optional

### ISSUE THREAD

**Issue by nktpro** [facebook/react-native#3400]
The change to use worker in Chrome dev mode broke crucial tools:

- React Dev Tools [no longer works](https://github.com/facebook/react-devtools/issues/229)
- WebStorm (or any Intellij-based IDEs) Chrome remote debugger can't debug workers, and there's [no support for that in near sight.](https://youtrack.jetbrains.com/oauth?state=%2Fissue%2FWEB-7986)
- Hot module replacement with react-native-webpack-server [stopped working](https://github.com/mjohnston/react-native-webpack-server/issues/103)

Tooling is what matters the most for any tech stack. Sandboxing browser specific APIs is helpful but most of the time it's trivial to find and fix the violating code paths. It's not worth it over losing existing working tools.

At the minimum couldn't we just make it optional, i.e: `http://localhost:8081/debugger-ui?run-inside-worker` vs forcing it by default?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/make-running-inside-chrome-web-worker-optional

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
