### ISSUE TITLE
Centering things vertically in a container requires the parent of container to have a given height

### ISSUE THREAD

**Issue by drager** [facebook/react-native#3412]
When trying to use flexbox and centering things vertically that are in a container the parent of the container must have a given height.

I have made an example at rnplay which you can check out here: https://rnplay.org/apps/ZntqsQ
Just uncomment the height of the parent and the text will be centered.

The issue is present in both iOS and Android and React Native 0.11 and 0.12.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/centering-things-vertically-in-a-container-requires-the-parent-of-container-to-have-a-given-height

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.

**Comment by drager** [comment]
Hi, I see. Thanks for the response.
