### ISSUE TITLE
App crashes when switching back from another app in Simulator

### ISSUE THREAD

**Issue by idibidiart** [facebook/react-native#3417]
<img width="375" alt="screen shot 2015-10-14 at 10 35 36 am" src="https://cloud.githubusercontent.com/assets/1288823/10492239/cf1792be-725f-11e5-847e-084790a6a5f4.png">

Was running RN app, switch projects in XCode to run an Objective-C app, switched back and got this error.

This seems to be the offending handler:

    @autobind
    _kbWillShow(frames) {

        LayoutAnimation.configureNext(LayoutAnimation.create(0, 'keyboard'))
        this.setState({kbHeight: frames.endCoordinates.height});
        this.setState({kbOn: true})

    }

I tried passing a properly structured object to configureNext with property having a value but it kept throwing the same error.

Also, I don't seem to be able to unhook this event using this:

    // componentWillUnmount() {

    //     DeviceEventEmitter.removeListener('keyboardWillShow', this._kbWillShow)
       
    //     DeviceEventEmitter.removeListener('keyboardWillHide', this._kbWillHide)

    //     DeviceEventEmitter.removeListener('keyboardDidShow', this._kbDidShow)
                
    //     DeviceEventEmitter.removeListener('keyboardDidHide', this._kbDidHide)
    // } 

It throws an error saying DeviceEventEmitter.removeListener is not a function.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/app-crashes-when-switching-back-from-another-app-in-simulator

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
