### ISSUE TITLE
NavigatorIOS - Quickly tapping back causes RedBox

### ISSUE THREAD

**Issue by jaygarcia** [facebook/react-native#343]
This has to be resolved.   The navigator UI will be something that people will depend on heavily. :(

![navigator](https://cloud.githubusercontent.com/assets/180031/6869306/7eb170e0-d469-11e4-9b85-44a798589db0.gif)

**Comment by brentvatne** [comment]
:+1:

**Comment by sahrens** [comment]
cc @evv - looks like we just need to handle the case of rapid tapping on the back button.

**Comment by ericvicenti** [comment]
This looks quite important, but because we use `Navigator` internally (which still needs a lot of work), I can't spend much time fixing `NavigatorIOS`.

If anybody wants to look into this, here is where you would start:

https://github.com/facebook/react-native/blob/72d3d724a3a0c6bc46981efd0dad8f7f61121a47/React/Views/RCTNavigator.m#L495

**Comment by brentvatne** [comment]
Rapidly tapping back button in simulator and I can't reproduce this, will reopen if this is still the case
