### ISSUE TITLE
[Reopened] How to change port on RN 68 for IOS?

### ISSUE THREAD

**Issue by gentlee** [facebook/react-native#34302]
### Description

[30708](https://github.com/facebook/react-native/issues/30708) is still actual.

### Version

0.68.2

### Output of `npx react-native info`

https://github.com/facebook/react-native/issues/30708

### Steps to reproduce

https://github.com/facebook/react-native/issues/30708

### Snack, code example, screenshot, or link to a repository

https://github.com/facebook/react-native/issues/30708

**Comment by cortinico** [comment]
> [30708](https://github.com/facebook/react-native/issues/30708) is still actual.

The fix is actually merged: https://github.com/facebook/react-native/commit/7dc0b5153e4eb91c333238a58fe8c75a47cb5f81

It will land in RN 0.70.

If you wish to have this backported to a previous version, you need to comment in the corresponding discussion here https://github.com/reactwg/react-native-releases/
