### ISSUE TITLE
[NavigatorIOS] props.navigator.replace is not working

### ISSUE THREAD

**Issue by rocmanzhao** [facebook/react-native#3435]
I noticed that when I call props.navigator.replace, the setState method and the render method are called, but nothing happen to the UI. And, I've confirmed that the state is correctly changed.

**Comment by ericvicenti** [comment]
Do you have a minimal example (like an rnplay.org link) of this bug that we can reproduce and see why the replace isn't working?

I don't think we have had any troubles with our internal usage of Navigator replace. cc @hedgerwang

**Comment by rocmanzhao** [comment]
Please be noticed that what I'm using is the NavigatorIOS. And I found that the issue is becasue the RCTNavItem does not modify the coresponding NavigationItem when it (the RCTnavItem) is modifed. I've fixed it by modifying the RCTNavItem code. I'll post what I've modifed later.

**Comment by rocman** [comment]
Hi here's the minimal example of the bug:
https://www.rnplay.org/apps/oLxGDw

**Comment by rocman** [comment]
And here's my modifcations:
https://github.com/facebook/react-native/pull/3457#issuecomment-148653832

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/navigatorios-propsnavigatorreplace-is-not-working

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
