### ISSUE TITLE
Multiple Modal components

### ISSUE THREAD

**Issue by maxs15** [facebook/react-native#3445]
It is currently impossible to create multiple Modal components.
Here is the warning that appears:
`
Warning: Attempt to present <RCTModalHostViewController: 0x7f89e4f8c2a0>  on <UIViewController: 0x7f89e4903770> which is already presenting <RCTModalHostViewController: 0x7f89e4f84f10>
`

I don't know if it is something you did on purpose but I think it would be a huge plus to be able to render multiple modals.

**Comment by javache** [comment]
This is currently not possible, I'm working on supporting this. For now you should be able to nest <Modal> components to achieve this behaviour.

**Comment by maxs15** [comment]
Ok great, thanks @javache !

**Comment by pvenkatakrishnan** [comment]
Is this done in 0.19. I am running into the same issue and trying to put a safari view controller on a RCTModalHostViewController. This is not possible on

**Comment by ianakiara** [comment]
+1

**Comment by mschipperheyn** [comment]
+1

**Comment by mschipperheyn** [comment]
How does this nesting work?

**Comment by dbuarque** [comment]
+1

**Comment by mstuart** [comment]
+1

**Comment by SteveMellross** [comment]
+1
Any progress on this?

**Comment by javache** [comment]
You should be able to present them as `<Modal><Text>A</Text><Modal><Text>B</Text></Modal>

**Comment by fostertime** [comment]
@javache so in the scenario you mention here, you would simply setState for visible on both at the same time if you wanted the nested <Modal>?

**Comment by pvenkatakrishnan** [comment]
how will this work if i wanted to present a SFVC on top of of a modal or vice versa ?

**Comment by wootwoot1234** [comment]
Any progress on this?

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/multiple-modal-components

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
