### ISSUE TITLE
Cannot read 'setNativeProps' of undefined. The sequel.

### ISSUE THREAD

**Issue by admmasters** [facebook/react-native#3447]
There is an existing issue ( #2310) but the stacktrace appears a little different. The crash occurs whenever one of the pickers (Date/PickerIOS)'s onChange events fire. This occurs on the latest master but not on 0.13-rc. I have not had time to bisect yet, but happy to if this remains an issue.
![simulator screen shot 15 oct 2015 15 31 40](https://cloud.githubusercontent.com/assets/335607/10517249/d8bc916c-7353-11e5-8907-04a444acfd72.png)

**Comment by admmasters** [comment]
![simulator screen shot 17 oct 2015 09 40 22](https://cloud.githubusercontent.com/assets/335607/10557834/23fea2ae-74b3-11e5-82b3-a8b75764fced.png)

**Comment by bryanlarsen** [comment]
This occurs for me when I change the visibility of the picker onValueChange.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/cannot-read-setnativeprops-of-undefined-the-sequel

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
