### ISSUE TITLE
[DevMenu] No way to persistently add custom menu items

### ISSUE THREAD

**Issue by Sidnicious** [facebook/react-native#3466]
If I set a root view up like this…

```swift
let rootView = RCTRootView(…)
rootView.bridge.devMenu.addItem(RCTDevMenuItem.buttonItemWithTitle("Custom menu item") {…})
```

…then the custom menu item doesn't appear. As far as I can tell, this is because when the dev menu is created it asynchronously [applies its settings](https://github.com/facebook/react-native/blob/2608efccb6d81e2abc5571522455e641caf330ea/React/Modules/RCTDevMenu.m#L210-L212), including one which sets `executorClass` to `RCTWebSocketExecutor`. The change in executor class causes the bridge itself to be [reloaded](https://github.com/facebook/react-native/blob/2608efccb6d81e2abc5571522455e641caf330ea/React/Modules/RCTDevMenu.m#L563) (most of which also happens asynchronously), which recreates the dev menu and tosses out my customization.

This feels like a bug. Is there a way that reloading could not blow everything away?

**Comment by Sidnicious** [comment]
Hmm, the custom menu item is also blown away when the app reloads. Maybe the issue is just that there's no way to persistently add custom dev menu items?

**Comment by javache** [comment]
When you call it immediately it won't work since the native modules are initialised asynchronously.

Can you try adding a listener for `RCTDidCreateNativeModules` and adding your custom menu item at that point? This listener will also be invoked every time the bridge is reloaded.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/devmenu-no-way-to-persistently-add-custom-menu-items

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by jsoendermann** [comment]
I was looking for a solution to this problem and ended up working around it by adding an [initialize](https://github.com/jsoendermann/react-native-async-storage-dev-menu-item/blob/master/RCTAsyncStorageDevMenuItem/RCTAsyncStorageDevMenuItem/RCTAsyncStorageDevMenuItem.m#L18) function to my native module that I call from [a JavaScript file](https://github.com/jsoendermann/react-native-async-storage-dev-menu-item/blob/master/index.js#L12) I `import` in my app.js.
