### ISSUE TITLE
Error: IconImage has no propType for native prop SMXIconImage.scaleX of native type number

### ISSUE THREAD

**Issue by awesomepankaj** [facebook/react-native#3478]
I just updated my React Native version to 0.13.0 and then I am getting error:-

Error: IconImage has no propType for native prop SMXIconImage.scaleX of native type number

in android.

**Comment by zenlambda** [comment]
@awesomepankaj I think this issue is the version of [corymsmith/react-native-icons](https://github.com/corymsmith/react-native-icons) you are using is not sufficiently up to date to use with react-native 0.13.0-rc . Luckily it seems someone *might* have merged the changes you are looking for into master for that project. [Check them out!](https://github.com/corymsmith/react-native-icons/commit/9f3877bcaf4abd0c162ef319ed1c64f0381a5362#diff-0c2db2d803d8d86ff247fc35e56bc324R51).

**Comment by awesomepankaj** [comment]
thanks its works.

**Comment by icefoggy** [comment]
@zenlambda 
So we need declare these propTypes for every native UI module?

**Comment by zenlambda** [comment]
@icefoggy I think this is a question for react-native devs. I noticed I had to add the following changes to my prop types after the 0.13-rc release. I can't point to any specific documentation that states that these propTypes are necessary, but adding them did resolve my problem (and this issue). 

```js
propTypes: {
   scaleX: PropTypes.number,
   scaleY: PropTypes.number,
   translateY: PropTypes.number,
   translateX: PropTypes.number,
   rotation: PropTypes.number,
}
```

I haven't tried, but do you think if we followed the latest native component instructions for android that they would work? If not then its possible a documentation change is necessary.

**Comment by zenlambda** [comment]
@icefoggy One of my native components was affected again by new properties appearing in the BaseViewManager. I'm now using the following code to shield my components from these changes:

```javascript
import objectAssign from 'object-assign';
import React from 'react-native';
let {View, PropTypes} = React;

let MyNativeComponent = React.createClass({
   propTypes: objectAssign({}, View.propTypes, {
        myProp: PropTypes.bool
   }),

   // the rest of MyNativeComponent
});
