### ISSUE TITLE
map constructor does not accept arguments

### ISSUE THREAD

**Issue by despairblue** [facebook/react-native#3480]
Doing this: `new Map([[1, 1]])` leads to the error `Map constructor does not accept arguments` being thrown while running in jscore. It works fine in chrome, though its using v8's native Map.

Shouldn't babel insert the core-js polyfill, which should make jscore standard compliant?

**Comment by vjeux** [comment]
I'm in pto for two weeks, won't look into it sorry :(

**Comment by despairblue** [comment]
No problem, I think I found out why that is. Probably because of #2000.
So for now I just have to stick the data types JSC supports natively.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/map-constructor-does-not-accept-arguments

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
