### ISSUE TITLE
DatePickerIos causes bad performance

### ISSUE THREAD

**Issue by eyaleizenberg** [facebook/react-native#3517]
I have a view which pushes to another view which has 2 DatePickerIos, one for date, and one for time.
Transitioning to the second page takes relatively a long time. I can obviously put a loading indicator and then after the transition finishes change it, however, I don't think that a page that has 2 pickers should be so 'heavy' to render...

ideas?

**Comment by brentvatne** [comment]
Can you post a screen recording or demo of this on rnplay.org as per the issue posting guidelines? With the FPS monitor on, does this cause slowdown on the JS thread or UI thread?

Selectively loading only certain components during the transition is good practice at the moment:
https://facebook.github.io/react-native/docs/performance.html#slow-navigator-transitions

**Comment by christopherdro** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

If you'd like you can create an issue on [Product Pains](https://productpains.com/product/react-native
).
ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. 

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bug fixes as the core team is focused on performance. Thanks!
