### ISSUE TITLE
[ListView] Avoid re-render all items if only one is changed

### ISSUE THREAD

**Issue by aksonov** [facebook/react-native#3518]
If i change one item in datasource, why ListView re-render all of them? I have list of topics and want to have possibility of favorite/unfavorite them. I see real noticed delay (changes are not seen immediately). I'm using Flux approach, store changes one element in the list, but ListView calls "renderRow" for each item, not only for changed ones, why?

**Comment by chirag04** [comment]
You can check if rowHasChanged while creating listView DataSource.
eg:
``var ds = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2})``

you can be more specific rather than just ``r1 !== r2``. maybe: ``r1.favCount !== r2.favCount``

if renderRow renders a component than you can add ``shouldComponentUpdate`` to that component to avoid the re-render.

**Comment by ide** [comment]
@chirag04's answer is correct. You can put your heuristic in the data source or each row component or both.
