### ISSUE TITLE
[Android] Error with basic generated code when trying to inspect an element

### ISSUE THREAD

**Issue by Dorian** [facebook/react-native#3521]
On Android, I generated an app (eg: `react-native init FoodShip`) then ran it on an emulator API 23.

When doing F2, then "Inspect Element" then tapping some text I get this error:

<img width="300" alt="screen shot 2015-10-18 at 9 24 55 pm" src="https://cloud.githubusercontent.com/assets/129149/10589567/4a12946e-76ac-11e5-9020-a0fb966bd23c.png">

**Comment by jforaker** [comment]
+1 
I have been working on an Android app for a couple months now, both 0.12 and 0.13 have had this problem and it has gone on ignored. Sad to see that facebook isn't concerned with giving the android devs a good experience.

**Comment by christopherdro** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

If you'd like you can create an issue on [Product Pains](https://productpains.com/product/react-native).
ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. 

Also, if this issue is a bug, please consider sending a PR with a fix. Thanks!
