### ISSUE TITLE
How to get the current script's dirname?

### ISSUE THREAD

**Issue by iostalk** [facebook/react-native#354]
Such as __dirname in nodejs

**Comment by colinramsay** [comment]
I'm going to link to the StackOverflow answer I gave you here:

http://stackoverflow.com/a/29301756/125680

And my blog post on the same thing:

http://colinramsay.co.uk/2015/03/27/react-native-simple-native-module.html

I think this is a straightforward approach that probably gives you more flexibility than actually having __dirname anyway.

**Comment by iostalk** [comment]
Thank you very much, but I want to get current script's dirname, and I didn't understand your method

**Comment by lwansbrough** [comment]
@iostalk The method that @colinramsay describes is probably what you're looking for. The caveat is that it makes use of a native module which must be communicated with asynchronously. If you can provide a better explanation as to why you need the app's root directory, perhaps you'd get an answer sooner. I had the same problem, but realized I didn't actually need to reference the root directory.

**Comment by iostalk** [comment]
Where is the script path?I cannot find it

**Comment by iostalk** [comment]
I want to download or load some online scripts to execute, so I need to know the script root path and how can I download and execute in it

**Comment by iostalk** [comment]
And I am very curious because I cannot find out where ReactNative framework puts our scripts and how them being executed ?

**Comment by sahrens** [comment]
I'm not sure I understand your question - React Native doesn't really "put" the JavaScript files anywhere - they just live in the directory structure of your project. if you use the CLI via "react-native init MyProject" then it just creates one file, index.ios.js, in the MyProject folder it creates. The library code lives in node_modules/react-native/Libraries.

When you run your app, the packager reads these files off disk, and bundles them into a single script that it delivers to the app over localhost. This script only lives in memory in the app.

If you want to publish your app to the App Store, then you can manually save this file with curl -o, then put it wherever you want in the app bundle, and change your AppDelegate.m to point to this local file instead of localhost.

Does that help?  If not, what exactly are you trying to accomplish.

**Comment by lwansbrough** [comment]
@sahrens I think he wants to do RCE which is not allowed on the App Store

**Comment by iostalk** [comment]
Yes I want to do something that not allowed by App Store

**Comment by iostalk** [comment]
@sahrens Thank u ,are u the core team member of RN ?

**Comment by sahrens** [comment]
Yeah, I'm on the core team.

**Comment by iostalk** [comment]
I get you!That's awesome!
It' s very nice of you, my English is such poor and sorry for that.

**Comment by yorkie** [comment]
BTW, what's the RCE?

**Comment by ide** [comment]
I'm guessing Remote Code Execution?

**Comment by yorkie** [comment]
Thanks, I see @ide :-)
