### ISSUE TITLE
ListView should support using raw data (ImmutableList) as data source and reconcile changes

### ISSUE THREAD

**Issue by bordoley** [facebook/react-native#3544]
I'm currently using a ListView within a stateless ReactComponent, and would ideally publish the state to the component as an Immutable.List via the enclosing component's props. Right now this isn't possible due to ListView requiring data be provided as a ListView.DataSource, which is used to track changes to the data set. Pushing the state management into user space code tends to break the nice functional abstraction provided by React, where React reconciles the state changes for you.

In the interim, I'm mapping my state pump by folding over the values it produces and emitting a ListView.DataSource. This works, but pushes react data structures into my application code, which at this point is fully UI agnostic. Has any thought been given to encapsulating the dataset reconciliation logic within the ListView components itself? I can imagine being able to provide an ImmutableList as the data prop, along with a comparison function for list values (in lieu of actual value type comparison, which would be preferable).

For reference, here is a sample app I wrote that has to deal with this issue: https://github.com/bordoley/RelaX/blob/master/examples/react-native/FacebookFeedExample/index.ios.js#L24

**Comment by brentvatne** [comment]
Could you provide an API proposal for this, taking into account section headers?

**Comment by ide** [comment]
I recommend writing a helper component that accepts an Immutable.List and renders a ListView. The helper component would have a bit of state, but the rest of your code (esp the code that uses your helper component would be stateless).

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/listview-should-support-using-raw-data-immutablelist-as-data-source-and-reconcile-changes

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by cooperka** [comment]
Hi @bordoley, if this is still an issue for you I recommend taking a look at https://github.com/cooperka/react-native-immutable-list-view. I wrote it to solve this exact problem. I hope it can be of help to you and anyone else having the same pains.
