### ISSUE TITLE
App mounts but loads into blank screen when activating Debugger after upgrade

### ISSUE THREAD

**Issue by bcye** [facebook/react-native#35487]
### New Version

0.63.4

### Old Version

0.70.5

### Build Target(s)

Android Physical Device in Debug

### Output of `react-native info`

System:
    OS: Linux 6.0 Pop!_OS 22.04 LTS
    CPU: (16) x64 AMD Ryzen 9 5900HX with Radeon Graphics
    Memory: 3.67 GB / 15.03 GB
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.13.2 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: 2022.10.31.00 - /home/linuxbrew/.linuxbrew/bin/watchman
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: ^0.70.5 => 0.70.5 
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

When I try debugging the app via pressing "Debug" in the Developer Menu, the app reloads to a blank screen. React seems to successfully mount as I am seeing logs from some useeffects in the console. This happens with both the VS Code Debugger and the Debugger-UI in a browser tab, as well as on Windows and Linux. I am not using Hermes. There seems to be a memory issue, as after about a minute the computer starts being sluggish and in case of the browser, the debugger-ui tab crashes. If I open the Developer Menu on the blank screen, it still reads "Debug" instead of "Stop debugging". When I am not debugging the app loads and functions fine.

**Comment by CMLCNL** [comment]
Issue with DevTools menu causing white screen in React Native app

I'm experiencing an issue where my React Native app is showing a white screen when I open the DevTools menu. I'm running the app on macOS 13.1 with an M1 Pro processor using Node v18.0.0.

Here's the output of react-native info:

System:
OS: macOS 13.1
CPU: (10) arm64 Apple M1 Pro
Memory: 106.94 MB / 16.00 GB
Shell: 5.8.1 - /bin/zsh
Binaries:
Node: 18.0.0 - ~/.nvm/versions/node/v18.0.0/bin/node
Yarn: Not Found
npm: 8.6.0 - ~/.nvm/versions/node/v18.0.0/bin/npm
Watchman: 2023.03.20.00 - /opt/homebrew/bin/watchman
Managers:
CocoaPods: 1.11.3 - /Users/efecantekin/.rbenv/shims/pod
SDKs:
iOS SDK:
Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
Android SDK: Not Found
IDEs:
Android Studio: 2022.1 AI-221.6008.13.2211.9619390
Xcode: 14.2/14C18 - /usr/bin/xcodebuild
Languages:
Java: 11.0.16 - /usr/bin/javac
npmPackages:
@react-native-community/cli: 10.2.0 => 10.2.0
react: 18.2.0 => 18.2.0
react-native: 0.71.3 => 0.71.3
react-native-macos: Not Found
npmGlobalPackages:

Steps to reproduce:

Open the DevTools menu in the app.
Observe that the app's screen turns white and does not display any content.
Expected behavior:
The app's content should still be visible when the DevTools menu is open.

Actual behavior:
The app's screen turns white and does not display any content when the DevTools menu is open.

Additional information:
I have checked the console log for any error messages and have not found any relevant errors. I have also tried restarting the app and clearing its cache, but the issue persists.

Thank you for your help in addressing this issue!
