### ISSUE TITLE
Fetch API not defined in Jest tests

### ISSUE THREAD

**Issue by tom-sherman** [facebook/react-native#35563]
### Description

With a fresh React Native project, fetch API is not available in jest tests, even when running under Node 18.

### Version

0.70.6

### Output of `npx react-native info`

```
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 719.89 MB / 16.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 18.12.1 - ~/.local/share/nvm/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.local/share/nvm/v18.12.1/bin/yarn
    npm: 8.13.2 - /opt/homebrew/bin/npm
    Watchman: 2022.11.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. `npx @react-native-community/cli init ReactNativeHeadersTest`
2. Install JS dependencies
3. Add a call to eg. `Headers` in App.js
4. Run the tests

### Snack, code example, screenshot, or link to a repository

https://github.com/tom-sherman/ReactNativeHeadersTest

**Comment by jwoyame** [comment]
This looks to be fixed in the latest version of React Native.

The linked project was created using `"jest": "^26.6.3"`. Version 28 of Jest [added the ability to use global fetch](https://jestjs.io/blog/2022/04/25/jest-28#all-nodejs-globals), including the `fetch` included in Node.js 18. Changing the package.json to `"jest": "^28"` makes the fetch error go away. Also, the `.node-version` file specifies 16, which can call some Node version managers to still use 16.

The latest version of React Native, as of this writing, is using Node 18 and `"jest": "^29.2.1"` so fetch should work out of the box.
