### ISSUE TITLE
npx react-native init fails on Installing Bundler

### ISSUE THREAD

**Issue by abdul-ahad-devs** [facebook/react-native#35669]
### Description

I have been trying to create a new react-native app with the command `npx react-native init SamepleApp` but it fails on Installing Bundler with the following issue

`✖ Installing Bundler
error /Library/Ruby/Site/2.6.0/rubygems.rb:265:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
	from /Library/Ruby/Site/2.6.0/rubygems.rb:284:in `activate_bin_path'
	from /usr/bin/bundle:23:in `<main>'

✖ Installing Bundler
error Error: Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/next/environment-setup and follow the React Native CLI QuickStart guide for macOS and iOS.
Error: Error: Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/next/environment-setup and follow the React Native CLI QuickStart guide for macOS and iOS.
    at createFromTemplate (/Users/mac/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/commands/init/init.js:169:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.initialize [as func] (/Users/mac/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/commands/init/init.js:222:3)
    at async Command.handleAction (/Users/mac/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/index.js:140:9)
info Run CLI with --verbose flag for more details.`

I tried updating my ruby version to the latest version but it also did not help. Also tried bundle install in my project by it also failed

I have been using MacBook Pro 2017 with Intel Chip and my ruby version is 2.6.10p210, Node version is v16.17.1 and no react-native-CLI is globally installed.

### Version

0.70.6

### Output of `npx react-native info`

System:
    OS: macOS 13.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 76.06 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
    Watchman: 2022.12.05.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK: Not Found
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Open your terminal.
2. Run `npx react-native init SampleApp`
3. Issue got reproduced

### Snack, code example, screenshot, or link to a repository

<img width="1680" alt="Screenshot 2022-12-17 at 7 54 09 PM" src="https://user-images.githubusercontent.com/55701320/208249152-9be5f0af-39e0-4efd-b1e8-0b9e8e1d8cab.png">

**Comment by raselldev** [comment]
same with me!

dear developer, please give me tips for this bugs.

**Comment by abdul-ahad-devs** [comment]
@raselldev I am stuck in this issue since last week and have tried all solutions available on the Internet. Tried updating ruby versions but none of them helpd me

**Comment by ZohaibAhmad786** [comment]
Same with me. Please help to figure out the problem so we can start to create new projects

**Comment by CoderKb** [comment]
same with me!

**Comment by abdul-ahad-devs** [comment]
Did you all try to update your Ruby version?

**Comment by raselldev** [comment]
Dear @abdul-ahad-devs @CoderKb ,

I think for now we need expo to generate new react template. 
This for temporary solution.

**Comment by longhai97** [comment]
I have same error :(

**Comment by peggy1000423** [comment]
I had the same problem before. I solved it by the following steps.
-updated **node version** to current LTS version (**v18.12.1**). 
-updated **ruby version** to **2.7.6p219** (using rbenv).
-installed **watchman** using homebrew (brew install watchman)
-installed **cocoapods** using homebrew (brew install cocoapods). If there is cocoapods that install by Ruby gem command, you need to uninstall first(sudo gem uninstall cocoapods). 
Then,  create your project again. (**npx react-native init AppName**)

Hope it helps!

**Comment by sadafliaqat2nov** [comment]
@abdul-ahad-devs same with me, did you find any solution?

**Comment by abdul-ahad-devs** [comment]
Hey @sadafliaqat2nov, I have got a solution for this issue.  Follow below steps to resolve this issue:

1. Install rbenv and install Ruby using  it with `rbenv install 3.1.3`.
2. After installing it set it to your global Ruby version with the command `rbenv global 3.1.3`.
3. If this command does not work, try uninstalling this version and reinstalling it. This thing helped me and then I was able to set ny recent version of Ruby to global version.

Let me explain that what does `rbenv global 3.1.3` or `rbenv local 3.1.3` does for you. Basically it generates a .ruby-version file in your respective folder and it appends the the version 3.1.3 in it. 

In case of new application, when cocoapods are being installed, React native cli is somehow unable to detect the relevant Ruby version and it fails with exceptions. This is happening after the recent upgrade of react-native version of 0.70.x. React Native cli now expects ^2.7.5 Ruby version while MaC is using 2.6.10p even in its latest OS.

Now after following my above solution, you will need to open a relevant folder in your terminal (please make sure that any of you folder does not have spaces in its name, otherwise it will lead to other issues). After that, run this command `npx react-native init SampleApp `

May be this command will again fail on Insalling Bundler. Just go inside your ios directory and run `rbenv local 3.1.3`. A .ruby_version file will be generated. Now run `pod install ` and boom 💥 All Pods will be installed and your app will be ready.

Note: You will need to run `rbenv local 3.1.3` everytime when you initialize a new react native project until this bug gets officially fixed.

Thanks!

**Comment by abdul-ahad-devs** [comment]
Closing this issue with [this solution](https://github.com/facebook/react-native/issues/35669#issuecomment-1380997518)

**Comment by devansh-nigam** [comment]
Is there a way to make sure that when we execute `npm react-native init demo`, the process does not go to installing bundler at all. I have seen it not installing bundler at all in my friend's setup of react native, is it due to the fact that I once tried to mess around with the ruby versions using a ruby-package-manager like `rbenv`

**Comment by devansh-nigam** [comment]
So this is what eventually works, the bundler fails when we try to setup our barebone react native cli project using `npx react-native init demo` but then you `cd demo` and `cd ios` and run the command `pod install` to finish up what failed bundled could not at the first step. After that `cd .. && npm run ios` would work.

**Comment by JaySingh86** [comment]
> So this is what eventually works, the bundler fails when we try to setup our barebone react native cli project using `npx react-native init demo` but then you `cd demo` and `cd ios` and run the command `pod install` to finish up what failed bundled could not at the first step. After that `cd .. && npm run ios` would work.

this is correct

**Comment by AngelRmrz** [comment]
Issue 

When i'm trying to initialize a new project using npx react-native init i have the next error logs 

<img width="693" alt="Captura de pantalla 2023-10-20 a la(s) 3 49 14 p m" src="https://github.com/facebook/react-native/assets/69778769/203feb4f-9650-4d0d-a5cb-942eac399cf5">

I have also been trying to follow the guides:

- https://github.com/facebook/react-native/issues/35873
- https://github.com/facebook/react-native/issues/35669#issuecomment-1380997518

However, both solutions end in the same error that is displayed at the beginning. I would appreciate any comments on the configuration that I have to make to my system or if a total reset is necessary.

The problem is displayed on a macbook pro m2 with macOs Sonoma

The following images are for more information:

The output for the command `rbenv list`

<img width="696" alt="Captura de pantalla 2023-10-20 a la(s) 3 56 38 p m" src="https://github.com/facebook/react-native/assets/69778769/beab5369-b3ab-4520-88f7-bc8898745602">

The output for the command `rvm list`

<img width="844" alt="Captura de pantalla 2023-10-20 a la(s) 3 58 02 p m" src="https://github.com/facebook/react-native/assets/69778769/af8f605a-53ab-4bf2-9be4-9947a0cef9c0">

System:
  OS: macOS 14.0
  CPU: (8) arm64 Apple M2
  Memory: 234.83 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.8.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.1.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.10.09.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods: Not Found
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 2.7.6
    path: /Users/angelrmrz/.rvm/rubies/ruby-2.7.6/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.6
    wanted: 0.72.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
