### ISSUE TITLE
[Android] Text view weird truncating bug

### ISSUE THREAD

**Issue by holyxiaoxin** [facebook/react-native#3567]
Text View works fine in most cases. But strings like "is" and "si" have their second character left out in the render. Something kinky is going on. (:

**Comment by satya164** [comment]
Yeah. Even very short text like "Hello" get truncated, while long texts show just fine.

**Comment by holyxiaoxin** [comment]
I have an update: Take a look at my gist. https://gist.github.com/holyxiaoxin/051aa1bb95e21f391b51

The problem is that when i create a multiline <Text/> words like "is", "si", "ls", "sl", doesn't get their 2nd character rendered. Any idea why?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-text-view-weird-truncating-bug

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
