### ISSUE TITLE
Bug in expo rn project for pnpm

### ISSUE THREAD

**Issue by ramiljs** [facebook/react-native#35700]
### Description

bug pnpm for expo-cli (react-native)

### Version

version 0.70.5

### Output of `npx react-native info`

npx react-native info

### Steps to reproduce

pnpm expo-cli

### Snack, code example, screenshot, or link to a repository

![1 1](https://user-images.githubusercontent.com/89657343/208940846-3767bf76-4970-4985-b40d-d5c9af76c87b.PNG)

![1 2](https://user-images.githubusercontent.com/89657343/208940870-2ab553f3-e2d0-405a-8bb9-9364ff2642bc.PNG)

![1 3](https://user-images.githubusercontent.com/89657343/208940891-e01b40ce-945f-459d-a4bf-34036d6ae6f5.PNG)

**Comment by cortinico** [comment]
> bug pnpm for expo-cli (react-native)

Hi @ramiljs 
Thanks for reporting this issue.

It seems like this issue is actually unrelated to React Native core. Please open this issue against this other repository:

https://github.com/expo-cli/expo-cli/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.
