### ISSUE TITLE
[Animated] Optimize by moving animation to a high priority thread

### ISSUE THREAD

**Issue by oblador** [facebook/react-native#3579]
Loving the `Animated` API, but in some areas, such as interpolating on scroll events, the performance is not always 100%. There's been talk of moving that part off the JS thread into native code since 0.8.0, but couldn't find an issue tracking this. 

I think animation performance affects UX of basically every app and will solve some issues with `Navigator` among others. Would be nice to hear if this is being worked on or if help is wanted.

**Comment by skv-headless** [comment]
:+1:

**Comment by chirag04** [comment]
it would be help to add help wanted tag if this is not worked on at fb.

cc @ide  @sahrens @vjeux

**Comment by PhilippKrone** [comment]
@oblador Does it mean that you are going to work on this? ;)

**Comment by oblador** [comment]
@PhilippKrone: Talked to vjeux on reactiflux a few days about it and from I what understood it's being worked on and that he recently spun up a whole team just working with performance optimizations.

**Comment by vjeux** [comment]
Right now the focus of the team is on start performance. No one is actively working on animation perf

**Comment by oblador** [comment]
Related [Product Pains post](https://productpains.com/post/react-native/offload-some-animations-from-js-thread-for-better-perf/).

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/animated-optimize-by-moving-animation-to-a-high-priority-thread

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by jnak** [comment]
@mkonicek There is already a [product pains post here](https://productpains.com/post/react-native/offload-some-animations-from-js-thread-for-better-perf/) that has already 151 votes. 

You should delete the one you just created

**Comment by ide** [comment]
This is landing soon for Android anyway.

**Comment by oblador** [comment]
@ide: Yes, that's very exciting; props to the exponent team for that! Still needed for iOS though :-)
