### ISSUE TITLE
Warning: Native component for "RCTSnapshot" does not exist

### ISSUE THREAD

**Issue by guiguan** [facebook/react-native#3598]
I got this warning in 0.13.0-rc release:

2015-10-22 21:18:37.186 [warn][tid:com.facebook.React.JavaScript] 'Warning: Native component for "RCTSnapshot" does not exist'

Any help would be appreciated :)

**Comment by ide** [comment]
This is happening because we bundle and initialize components even when you don't use them at all. Ultimately we need to switch to ES6 modules and have the packager strip out unimported code but that's not going to happen soon.

It's just a warning so this isn't hi pri but it is noisy and extra bytes in your bundle. Anyone have ideas how to package only what you use? Do we need to make the packager trace which exports you use instead of which files?

**Comment by guiguan** [comment]
Thank you @ide for the quick reply and explanation. I guess we will just wait for the ES6 switching :)

**Comment by tmitchel2** [comment]
Pretty sure this means you can't start ReactNative at all when debugging in chrome because warnings are logged to the console and then thrown as a proper Error.

**Comment by despairblue** [comment]
@tmitchel2 nope, this one does not lead to a red box

**Comment by alexisohayon** [comment]
+1 I've got this error too, no red box.

**Comment by niftylettuce** [comment]
:+1: same error, no red box

**Comment by xnfa** [comment]
+1 same error

**Comment by phpscrpt** [comment]
+1 here

**Comment by anback** [comment]
+1 here

**Comment by eyaleizenberg** [comment]
+1

**Comment by sunny-g** [comment]
+1: same error, no red box

**Comment by nevir** [comment]
+1 cannot debug in chrome due to this

**Comment by despairblue** [comment]
@nevir how does that prevent you from debugging exactly?

**Comment by guiguan** [comment]
This problem has been fixed in [0.14.0](https://github.com/facebook/react-native/releases/tag/0.14.0)

**Comment by Yidada** [comment]
Got it ! Thanks a lot !
