### ISSUE TITLE
Your Ruby version is 2.6.8, but your Gemfile specified 2.7.6 error while enabling new architecture on react-native iOS

### ISSUE THREAD

**Issue by PritishSawant** [facebook/react-native#36002]
### Description

I have already gone through [this](https://stackoverflow.com/questions/74189532/your-ruby-version-is-2-6-8-but-your-gemfile-specified-2-7-5) post

I am facing this issue on my new react-native project version 0.71.1 while enabling the new architecture for iOS

I have done all the below steps

```
$ brew update
$ brew install ruby-build
$ brew install rbenv

$ rbenv install 2.7.6
$ rbenv global 2.7.6

echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.zshrc
echo 'eval "$(rbenv init -)"' >> ~/.zshrc
```

When I run `ruby --version` I get `ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [x86_64-darwin22]` which is the correct ruby version required to enable new architecture on iOS

but when I run `bundle install && RCT_NEW_ARCH_ENABLED=1 bundle exec pod install` I still get error saying

`Your Ruby version is 2.6.10, but your Gemfile specified 2.7.6`

### Version

0.71.1

### Output of `npx react-native info`

error Unrecognized command "info".
info Run "react-native --help" to see a list of all available commands.

### Steps to reproduce

Install a new react-native project version 0.71.1, go to the iOS directory and run `bundle install && RCT_NEW_ARCH_ENABLED=1 bundle exec pod install`

### Snack, code example, screenshot, or link to a repository

<img width="1155" alt="215389622-941eb7cf-27c9-4f94-ac8b-b84f1cf88dcf" src="https://user-images.githubusercontent.com/24708929/215407993-0905928f-1268-4c92-9cb6-b7bcaa36b0f9.png">

**Comment by parthkanani93** [comment]
+++

**Comment by iBotPeaches** [comment]
These aren't the easiest things to track down, but I'm guessing since this exact report is in many places - you might be feeling that pain. Or you missed something extremely easy like not restarting the terminal after injecting items to the zsh profile.

 * https://www.reddit.com/r/reactnative/comments/10ot4pe/your_ruby_version_is_268_but_your_gemfile/
 * https://github.com/reactwg/react-native-new-architecture/discussions/108
 * https://github.com/facebook/react-native/issues/35873#issuecomment-1408079446
 
What I think you should do is go through this https://github.com/facebook/react-native/issues/35873#issuecomment-1408079446 post again, but do the investigation - not just get to the end result for a specific user and test that. Since you really want to see what your `$PATH` is during that execution. See if you have a different binary fighting for priority.
 
This outside of a bug in CLI is normally a mixed up PATH and trading priorities of things. If we look at your initial post - I don't see this line in the install guide, nor did we do it when configuring rbenv. So why is this here? rbenv init sets up everything as described here - https://github.com/rbenv/rbenv#how-rbenv-hooks-into-your-shell

```
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.zshrc
```

What I'll say is I find that `gem install bundler` proxies correctly with rbenv and sets it up for `bundle install` to properly operate. I can't say that is your problem though because I can't see your path.

**Comment by PritishSawant** [comment]
I restarted the terminal multiple times


This is my path

`/Users/transformhub/.rbenv/shims:/Users/transformhub/.rbenv/bin:/opt/homebrew/opt/ruby/bin:/Users/transformhub/.gem/bin:/Users/transformhub/.pyenv/bin:/Users/transformhub/.pyenv/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/transformhub/Desktop/flutter/bin :/usr/local/go/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/transformhub/Library/Android/sdk/platform-tools:/Users/transformhub/Users/transformhub/Desktop/flutter/bin:/Users/transformhub/Android/Sdk/tools:/Users/transformhub/Android/Sdk/tools/bin:/Users/transformhub/Android/Sdk/platform-tools:/Library/Frameworks/Python.framework/Versions/3.9/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/transformhub/Desktop/flutter/bin:/Users/transformhub/.cargo/bin`

**Comment by cipolleschi** [comment]
What happens when you run `which ruby` or `command -v ruby`?
You should have something like: `/Users/transformhub/.rbenv/shims` 

btw, from your path, you have multiple references to different ruby versions (only in the first line):

/Users/transformhub/**.rbenv/shims:**/Users/transformhub/**.rbenv/bin:**/opt/homebrew/opt/**ruby/bin**:/Users/transformhub/.gem/bin:

Not sure how it actually works, but it could be that it takes the last path it founds (which is the homebrew ruby) and it could be on the wrong version.

Please, try to uninstall ruby from brew, if you don't need it.

Secondly, not sure if it helps, but in my PATH I personally only have the `.rbenv/shims` path, not the `.rbenv/bin`. (But I don't think this could be the cause of the problem)

**Comment by PritishSawant** [comment]
<img width="438" alt="Screenshot 2023-01-31 at 8 19 45 PM" src="https://user-images.githubusercontent.com/24708929/215793273-fdb6ebeb-f14f-4f41-ae0f-5cc58613213a.png">

I get the proper output

**Comment by PritishSawant** [comment]
If I try to uninstall ruby via home-brew I get error saying `Error: No such keg: /usr/local/Cellar/ruby`

**Comment by cipolleschi** [comment]
so it looks like you have a dirty path, somehow...
try to 
```
PATH=/Users/transformhub/.rbenv/shims:/Users/transformhub/.gem/bin:/Users/transformhub/.pyenv/bin:/Users/transformhub/.pyenv/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/transformhub/Desktop/flutter/bin :/usr/local/go/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/transformhub/Library/Android/sdk/platform-tools:/Users/transformhub/Users/transformhub/Desktop/flutter/bin:/Users/transformhub/Android/Sdk/tools:/Users/transformhub/Android/Sdk/tools/bin:/Users/transformhub/Android/Sdk/platform-tools:/Library/Frameworks/Python.framework/Versions/3.9/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/transformhub/Desktop/flutter/bin:/Users/transformhub/.cargo/bin
```
I removed the homebrew's ruby and let's see what happens. 
Your setup is correct, there is something that makes bundler resolve to the wrong ruby.

**Comment by PritishSawant** [comment]
Same issue
<img width="1437" alt="Screenshot 2023-01-31 at 9 54 35 PM" src="https://user-images.githubusercontent.com/24708929/215820018-898fd672-6c3d-4ed1-9bb5-cd1631ef7734.png">

**Comment by PritishSawant** [comment]
`bundle install --redownload` # Forces a redownload of all gems on the gemfile, assigning them to the new bundler

**Comment by Rache-lBronfman** [comment]
> `bundle install --redownload` # Forces a redownload of all gems on the gemfile, assigning them to the new bundler

I still stuck exactly in this issue, 
I writed it: `bundle install --redownload`
and got:
`Could not locate Gemfile`
any solution?

**Comment by BraveEvidence** [comment]
This might help https://www.youtube.com/watch?v=K3bm8wOKrhk

**Comment by cipolleschi** [comment]
@BraveEvidence @Rache-lBronfman I'm sorry for this. We are updating React Native so that it won't enforce any specific versions of Ruby anymore.

Meanwhile, we suggest to:
1. [Install `rbenv`](If that causes some weird import cycle, we can then understand whether it make sense to move them to the Parsers.)
2.  Run `rbenv install 2.7.6`
3. Navigate to your `project/ios` folder   
4. Run `rbenv local 2.7.6` to set the Ruby version for your project
5. Run `bundle install`
6. Run `bundle exec pod intall`

Let me know if this works.

**Comment by hungvu193** [comment]
@cipolleschi It doesn't work for me:
<img width="1510" alt="Screen Shot 2023-03-02 at 19 41 57" src="https://user-images.githubusercontent.com/16502320/222431784-ce2f2cae-4a1e-46e8-bdc4-6646e526a69d.png">

**Comment by cipolleschi** [comment]
The error is cut here. Could you provide the full error?

@hungvu193 Could you provide a repro? (I have an M1 pro as well)

Which version of React Native are you running?
Are you using `bundle install` and `bundle exec pod install` instructions? Those should take care of downloading the right versions for the M1 machines.

**Comment by 2b-dev** [comment]
I use Apple silicon M1 and this work for me

- brew uninstall ruby

Install RVM 
- rm -rf ~/.rvm
- curl -L https://get.rvm.io | bash -s stable
- source ~/.rvm/scripts/rvm
- rvm install 2.7.6
- rvm --default use 2.7.6

I restart and run npx react-native@latest init ProjectName
at Installing Bundler will ask to install CocoaPods
I choose Yes, with gem (may require sudo )

and finish create ReactNative Project

sorry I'm not good in English

**Comment by muffafa** [comment]
> I use Apple silicon M1 and this work for me
> 
> * brew uninstall ruby
> 
> Install RVM
> 
> * rm -rf ~/.rvm
> * curl -L https://get.rvm.io | bash -s stable
> * source ~/.rvm/scripts/rvm
> * rvm install 2.7.6
> * rvm --default use 2.7.6
> 
> I restart and run npx react-native@latest init ProjectName at Installing Bundler will ask to install CocoaPods I choose Yes, with gem (may require sudo )
> 
> and finish create ReactNative Project
> 
> sorry I'm not good in English

you saved my life thank you man

**Comment by hungvu193** [comment]
> The error is cut here. Could you provide the full error?
> 
> 
> 
> @hungvu193 Could you provide a repro? (I have an M1 pro as well)
> 
> 
> 
> Which version of React Native are you running?
> 
> Are you using `bundle install` and `bundle exec pod install` instructions? Those should take care of downloading the right versions for the M1 machines.

I do. So my problem is I used macbook chip intel, then I moved all the data to Macbook chip M1. So I need to uninstall cocoapod then install it again with arch command and problem solved.

**Comment by nayabatir1** [comment]
@2b-dev I followed your steps but I'm getting this error. Also after restarting my system ruby version was 2.6.10. Had to change default version again.

<img width="570" alt="image" src="https://user-images.githubusercontent.com/91016903/222981416-33a4a978-f6ef-453e-9e2b-53b03f59a450.png">

**Comment by Rache-lBronfman** [comment]
After trying all the suggestions with no success, I used react-native doctor command and now it works fine.

**Comment by uchennajohn** [comment]
> @2b-dev I followed your steps but I'm getting this error. Also after restarting my system ruby version was 2.6.10. Had to change default version again.
> 
> <img alt="image" width="570" src="https://user-images.githubusercontent.com/91016903/222981416-33a4a978-f6ef-453e-9e2b-53b03f59a450.png">


im having same issues, would love too know how you fixed yours

**Comment by cipolleschi** [comment]
Hi there, we are moving away from forcing a specific version of Ruby in RN 0.72. This would mitigate the issue you all are facing.

To solve your issue quickly, you can:
1. remove the `.ruby-version` file from your project
2. update the Gemfile as it follows:
```diff
source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
- ruby File.read(File.join(__dir__, '.ruby-version')).strip
+ ruby ">= 2.6.10" 

gem 'cocoapods', '~> 1.11', '>= 1.11.3'
```
This would be the default setup from 0.72 forward, so it should be safe.

Let me know if that works.

**Comment by uchennajohn** [comment]
![Screenshot 2023-03-09 at 16 25 32](https://user-images.githubusercontent.com/54621011/224071463-c6725ed5-2820-475c-98e9-289a602df44c.png)


im still getting same issues

**Comment by cipolleschi** [comment]
That's weird... what happens if you run these commands?
```
cd wegro/ios
bundle install
bundle exec pod install
```
