### ISSUE TITLE
Passing Map data structure to cloneWithRowsAndSections method

### ISSUE THREAD

**Issue by JeanLebrument** [facebook/react-native#3608]
Hello,

Because I need to order a hash table, I use a `Map` data structure to be able to sort the data inside before displaying it in my `ListView`. 

But I notice that the ListView component doesn't display the data passed in parameter if the parameter if of type of `Map`. 

But if I convert my map object to a plain old `Object`, it works.

```
const orderedContactsObject = {};

orderedContacts.forEach((value, key) => {
  orderedContactsObject[key] = value;
});
```

Is this a bug or is this a desired behaviour?

Best,
Jean

**Comment by ide** [comment]
Maps are not supported though it probably makes sense to support built-in JS types in ListViewDataSource. In the meantime there is a function you can pass to the DataSource constructor that's something like getDataFromBlob that lets you implement how to get values out of your data object (in this case the Map). cc @sahrens

**Comment by JeanLebrument** [comment]
I'm looking forward to hear about this guys! :+1:

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/passing-map-data-structure-to-clonewithrowsandsections-method

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
