### ISSUE TITLE
[Packager] Handling duplicate Haste modules by scoping them to npm packages

### ISSUE THREAD

**Issue by ide** [facebook/react-native#3618]
There is currently an issue with the packager where all Haste modules in a project, including its npm packages under node_modules, are in a global namespace. So if React Native includes a file with `@providesModule invariant` and you install a different npm package with another file that also contains `@providesModule invariant`, the packager will create a bundle that defines `invariant` twice! (There are two `__d('invariant', ...)` calls in the bundle, with the two different modules.

One nice solution for this is to scope Haste module names to the current npm package. So if you're within the react-native package, you can require any module by its Haste name. But if you're outside of the react-native package, you can't reach inside with something like `require('ScrollView')` for example -- you have to use the public interface: `let { ScrollView } = require('react-native')`. By scoping the Haste modules to each npm package, this also means that we can have two files that both contain `@providesModule invariant` and they won't conflict as long as they are in separate npm packages.

cc @martinbigio

**Comment by skevy** [comment]
According to this comment by @amasad - https://github.com/facebook/react-native/issues/1437#issuecomment-138471281 - `node_modules` should not be scanned at all for `@providesModule`.

Currently, the packager is attempting to do this, though it's just broken. There is code to prevent it in certain places in the packager, but during the read of a module, it doesn't look for whether it's in  `providesModuleNodeModules` before it assigns an `id`.

If that's fixed, would it make this not necessary, because this wouldn't happen (unless it's a package from Facebooks infra)?

**Comment by skevy** [comment]
Or actually, I guess if a project is using `@providesModule` or is using a package that they WANT to use `@providesModule` from, then this would be necessary.

**Comment by negativetwelve** [comment]
I think this is a pretty big issue. My project currently depends on both React and React Native. When I import RN using `import React from 'react-native';`, it correctly tries to import from `react-native.js` but that file [on this line](https://github.com/facebook/react-native/blob/6ec4d65aec4e2795a1845236fb8cd25462910816/Libraries/react-native/react-native.js#L20) tries to import from vanilla React since both files have the `@providesModule React` declared in them. Then I run into issues with process and document not defined.

Keeping the `@providesModule` scoped to a package would solve my issue I believe. Currently looking at the packager code to see what's changed since 0.13-rc.

**Comment by skevy** [comment]
@negativetwelve try this pr and let me know if it either fixes your issue or at least results in a different error: https://github.com/facebook/react-native/pull/3625

**Comment by negativetwelve** [comment]
@skevy thanks for the PR, I think that fixed it. My project now finds the correct React, the issue I'm facing now only pertains to chrome debugging where `document` is undefined. It is referencing `ReactErrorUtils` from `react` but that might be an error on our side.

**Comment by skevy** [comment]
@negativetwelve what packages in your project need "react", out of curiosity?

**Comment by negativetwelve** [comment]
@skevy we have a ton of shared code between our web and RN apps (datastores, actions, analytics modules, etc.). I'm still waiting for the day that RN doesn't keep it's own version of React in the repo. We're almost there now that React and React DOM are separated!

**Comment by martinbigio** [comment]
in the short term, the problem should be fixed by definning your own `rn-cli.config.js` file with a function `getBlacklistedRE` that adds one of the modules that is duplicate. See `default.config.js` for an example

**Comment by skevy** [comment]
@martinbigio I tried that, but that doesn't fix it, unfortunately, for the reasons explained in #3625

**Comment by jsierles** [comment]
@ide @martinbigio Is this still an issue?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/packager-handling-duplicate-haste-modules-by-scoping-them-to-npm-packages

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
