### ISSUE TITLE
error Unrecognized command "run-android".

### ISSUE THREAD

**Issue by maniac-tech** [facebook/react-native#36235]
### Description

I have an existing [react-native](https://github.com/maniac-tech/react-native-expo-read-sms) project, which is currently broken, and is showing the following error:

```
error Unrecognized command "run-android".
```

### Version

0.71.3

### Output of `npx react-native info`

```
System:
    OS: macOS 12.5.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 46.17 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
    npm: 9.5.0 - ~/.nvm/versions/node/v14.20.0/bin/npm
    Watchman: 2023.02.20.00 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 30, 31, 32, 33
      Build Tools: 23.0.1, 30.0.2, 30.0.3, 33.0.0
      System Images: android-30 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: /undefined - /usr/bin/xcodebuild
  npmGlobalPackages:
    react-native: 0.71.3
```

### Steps to reproduce

Just pull, and run `npx react-native run-android`

### Snack, code example, screenshot, or link to a repository

https://github.com/maniac-tech/react-native-expo-read-sms

**Comment by cortinico** [comment]
Thanks for providing a reproducer.
The issue is that the linked project is not a valid RN project.

Specifically you have a peerDependency on RN 0.41:
https://github.com/maniac-tech/react-native-expo-read-sms/blob/ceb1eaca2a2b309724e64b9d4bd964206c26f510/package.json#L17-L19

That's how the package.json of a RN project should look like:
https://github.com/facebook/react-native/blob/d9321c0866a9270f8aae0d37c11584f819bc11ce/template/package.json#L12-L32
