### ISSUE TITLE
[Question] Working with an existing UINavigationController

### ISSUE THREAD

**Issue by kenwheeler** [facebook/react-native#3637]
Are there any suggestions around getting React to work with an existing UINavigationController?

We are trying to embed a react-native view as a part of a larger iOS application.

cc @javache @angelodipaolo

**Comment by chirag04** [comment]
Maybe relevant:
https://facebook.github.io/react-native/docs/embedded-app-ios.html
https://github.com/dsibiski/react-native-hybrid-app-examples

**Comment by angelodipaolo** [comment]
Our goals are to: 

1. launch a RN app (via a `RCTView` wrapped in a `UIViewController`) on to an existing `UINavigationController` instance
2. enable RN's `NavigatorIOS` API to work with this existing `UINavigationController` instance

We were able to accomplish (1) by embeding a `RCTView` in a `UIViewController` that gets pushed on to the existing `UINavigationController`. Now we need to be able to use the Navigator API in React to push/pop React views on to this navigation controller.

I was hoping we could simply replace our existing `UINavigationController` with `RCTNavigationController` but it is unclear how we could interact with the instance of `RCTNavigationController` from React since it will be initialized before the React app is launched.

Another idea was to wrap NavigatorIOS in a custom component and subclass `RCTNavigationController`. When the `RCTView` is created that launches the React app we could pass a reference to our custom `NavigatorIOS` component as a prop.

Any advice and guidance are greatly appreciated!

**Comment by dsibiski** [comment]
This is definitely not an easy thing to do.

Do you absolutely need to have a UIViewController wrapping the RN app? Are you planning on pushing views onto it from the Native side as well? A little more insight on what you're trying to do may help us come up with an alternative.

If you know for sure that there is no other option, you might be able to use the `moduleProvider` block when creating your bridge, you can pass in an already created instance of a native module (perhaps your UINavigationController), more info about this can be found in the Advanced section here: https://github.com/dsibiski/react-native-hybrid-app-examples#advanced

**Comment by javache** [comment]
One option is create a custom native module that you pass a reference to your navigation controller. You can then open new views on that navigation controller as follows

    var navigator = require('NativeModules).MyNavigatorClass;
    navigator.openProfile(id);
    navigator.openURL('https://m.facebook.com/profile.php')

We use a similar strategy in Facebook for iOS.

**Comment by angelodipaolo** [comment]
thanks for all of the help. we have a solution working now so @kenwheeler feel free to close

**Comment by dsibiski** [comment]
@angelodipaolo: Would it be possible to give an idea of how your solution works? I think it would be great for the community as I've heard of others wanting to do something like this. Thanks!

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/question-working-with-an-existing-uinavigationcontroller

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
