### ISSUE TITLE
Infinite Scroll Memory Issues

### ISSUE THREAD

**Issue by mihirsoni** [facebook/react-native#3656]
Hi , 

I know many people are having this issue , but this is to get the workarounds or proper solutions.

I ran Movie Example given  in this repository. I just made normal user search where I will have result and will let it scroll to find what I want and as it has implemented infinite scroll I went till couple of pages(~5). When I check memory usage it eats up **lots of memory**, and it increase in **linear fashion** , it keeps increasing as you scroll.

I tried couple of other way (other Listviews) , but that is not solving our problem. Any good thoughts or workarounds for the same ?

It will be difficult for anyone to make shippable product with this flow. 

Attaching the screenshot.
 
<img width="1280" alt="screen shot 2015-10-24 at 4 38 50 pm" src="https://cloud.githubusercontent.com/assets/578861/10710258/1dc5eb66-7a6e-11e5-9498-d670436fbcf7.png">

<img width="1280" alt="screen shot 2015-10-24 at 4 40 04 pm" src="https://cloud.githubusercontent.com/assets/578861/10710259/342a7bb0-7a6e-11e5-994f-5598a8cd92fa.png">

**Comment by satya164** [comment]
Are you using `removeClippedSubviews` ?

**Comment by mihirsoni** [comment]
@satya164  Yes I did try that also , that doesn't solve any problem in performance.

**Comment by maraujop** [comment]
You might want to check out https://github.com/sghiassy/react-native-sglistview

**Comment by mihirsoni** [comment]
@maraujop  Yup , I have did that but I find it the if you scroll fast it gives you blank screen.

**Comment by hufeng** [comment]
Yes, React-Native@0.15 have the same problem.

**Comment by theinventor** [comment]
We are having super bad performance scrolling lists. Making the app feel like a webview when you scroll a few pages very quickly. 

If that's this issue - yes please help :)

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/infinite-scroll-memory-issues

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by sscaff1** [comment]
Any updates on this? I'm finding that with a long list my memory increases linearly with every pagination.

**Comment by roysG** [comment]
Any update?
