### ISSUE TITLE
Geolocation fix not included in 0.13.0?

### ISSUE THREAD

**Issue by kanerogers** [facebook/react-native#3674]
Hi, guys!

In 0.12.0, a bug in `Libraries/Geolocation/RCTLocationObserver.m` meant registering for location events would spam callbacks hundreds of times per minute.

Luckily, the following fix was merged into master a couple weeks ago:

https://github.com/facebook/react-native/commit/aacd2d90a4a511f1e39e7473b888b6f9fb1b723e

I've just updated to 0.13.0, and found that the patch hasn't made its way in yet. I've manually patched `Libraries/Geolocation/RCTLocationObserver.m` again to make my app work, but Geolocation is not very useful in React Native without this patch.

Any idea when it will be included in a release? Patching node modules by hand creeps me out. :smile:

**Comment by ide** [comment]
There is approximately a four-week cycle between code going into master and landing in release, with an RC release at the two-week midpoint. Since that commit went in 13 days ago, it missed the 0.13-rc cut-off, and we generally do a code freeze between RC and final release. So anyway that commit will go out with 0.14-rc (coming soon).

**Comment by kanerogers** [comment]
Sweet! Thanks, James.

You guys are doing an amazing job. Thanks for making my life great. 😊

K
