### ISSUE TITLE
Image doesn't react to `stretch`

### ISSUE THREAD

**Issue by bgryszko** [facebook/react-native#3686]
When using new Image component, it set width and height of the image and override stretch behaviour when using flexbox. 

Previously, to have stretched in column image and contained in the height of 50 I could do:
```
<View style={{flexDirection: 'row'}}>
  <View style={{flex: 1}}>
     <Image source={require('./image.png')} style={{ height: 50 }} resizeMode="contain" />
  </View>
  <View style={{flex: 1}}>
     ...
  </View>
</View>
```

Now the image won't be stretched – it would be aligned to the left with its width set. 
I've found workaround, by setting image' style to `width: null`, but I'm wondering what's expected behaviour?

**Comment by astreet** [comment]
Can you create an https://rnplay.org/ app that demonstrates the issue you're talking about?

**Comment by isair** [comment]
@astreet I believe this issue happens when an Image component loads a local image file using the new asset system. In my app I used to have a background image component with style `{ position: 'absolute', top: 0, right: 0, bottom: 0, left: 0 }` and `resizeMode="cover"`. When I updated to react-native 0.14.2 and moved on to using the new asset system, this image component stopped covering the whole screen and became the size of the image source instead.

I'll create a demo app when I can.

**Comment by astreet** [comment]
@foghina do you know why this might have changed?

**Comment by foghina** [comment]
What platform(s) is this happening on? Probably related to loading from network vs. resource. Does it work if you do a prod build?

**Comment by isair** [comment]
For me it does also happen on a production build, and on iOS and Android.

**Comment by nicholasalanbrown** [comment]
I'm also seeing this behavior.

**Comment by peterwilli** [comment]
Is there any news on this? I got the same problem +1

**Comment by peterwilli** [comment]
@isair I tried your method and worked when using 'stretch' as well. Thanks!

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/image-doesnt-react-to-stretch

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
