### ISSUE TITLE
[Animated] Animated.Value() has removeAllListeners() but Animated.ValueXY() does not

### ISSUE THREAD

**Issue by dubert** [facebook/react-native#3694]
Is there a specific reason for this? If not I can submit a PR with the added function.

**Comment by ide** [comment]
cc @vjeux

**Comment by christopherdro** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

If you'd like you can create an issue on [Product Pains](https://productpains.com/product/react-native).
ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. 

Also, if this issue is a bug, please consider sending a PR with a fix. Thanks!
