### ISSUE TITLE
Ability to run-android and not start server in new window

### ISSUE THREAD

**Issue by niftylettuce** [facebook/react-native#3695]
E.g. `react-native run-android --no-server`

and it wouldn't call <https://github.com/facebook/react-native/blob/7e53ee1095ac956887dd6a20d19a403096472660/private-cli/src/runAndroid/runAndroid.js#L122>

**Comment by astreet** [comment]
If this is an important part of your flow, we'd probably accept a pull request

**Comment by trave7er** [comment]
https://github.com/facebook/react-native/pull/5675

**Comment by trave7er** [comment]
hi @niftylettuce , could you explain why you need this feature in your flow and take a look at my PR #5675 ? Thanks

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/ability-to-run-android-and-not-start-server-in-new-window

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
