### ISSUE TITLE
superagent recommendation does not actually work

### ISSUE THREAD

**Issue by vishnevskiy** [facebook/react-native#370]
In the network section of the docs it recommends using `superagent` but when you npm install and require it you end up seeing something like this.

"Unexpected end of script"

https://www.dropbox.com/s/xcixxwmwrkhn2ly/Screenshot%202015-03-27%2015.18.40.png?dl=0

Removing the require resolves it.

**Comment by aackerman** [comment]
It appears to be an issue with the `debug` module dependency of superagent. The module has incorrectly determined that it is running in a node environment and is throwing an error.

But you're right, I'm seeing the same error.

**Comment by vjeux** [comment]
This file is:
https://github.com/facebook/react-native/blob/master/Libraries/JavaScriptAppEngine/Initialization/InitializeJavaScriptAppEngine.js

**Comment by vishnevskiy** [comment]
I actually tried importing `superagent/lib/client` directly and it resulted in the same problem.

**Comment by kyle-ssg** [comment]
+1 , I'd ported a fairly large project over to react using superagent as recommended. It wouldn't take long to move to something like fetch, but it's still rather annoying. Is there a more generic I can follow which covers this issue?

**Comment by philipshurpik** [comment]
Hi! 
You can try 'superagent/lib/client' but you need to modify require statements at the top of file:
var Emitter = require('component-emitter');
var reduce = require('reduce-component');
Because React Native doesn't correctly handle 'browser' section in package.json.

Also you can try my fork that is work with React Native:
https://github.com/philipshurpik/superagent
It has some other little fixes...

**Comment by amasad** [comment]
The packager now looks at the `browser` field. superagent should be usable once they publish a new version following this PR https://github.com/visionmedia/superagent/pull/621 which just makes it not depend on a `location` object on the global object.
