### ISSUE TITLE
URLSearchParams produces incorrect querystring

### ISSUE THREAD

**Issue by mlgpuntnl** [facebook/react-native#37247]
### Description

The `URLSearchParams` object produces an incorrect querystring when you construct it with "A record of string keys and string values"
MDN docs: [https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/URLSearchParams)

```
const test = new URLSearchParams([
    ['key1', '23'],
    ['key2', '25'],
    ['key3', '44']
])
console.log(test.toString())
console.log(decodeURIComponent(test.toString()));
```
Output in browser:
```
key1=23&key2=25&key3=44
key1=23&key2=25&key3=44
```
Output in React native (Android & IOS)
```
0=key1%2C23&1=key2%2C25&2=key3%2C44
0=key1,23&1=key2,25&2=key3,44
```

### React Native Version

0.71.7

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz
    Memory: 4.53 GB / 15.94 GB
  Binaries:
    Node: 19.8.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.7 => 0.71.7
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Create a react native project:
`npx create-expo-app test-app`

Place the folowing snippet at the top of your `App()` function in `App.js`
```
  const data = [
    ['key1', '23'],
    ['key2', '25'],
    ['key3', '44']
  ]
  const test = new URLSearchParams(data)
  console.log(test.toString());
```

Run the project
`npm run start`

Scan the QR code and check your console

### Snack, code example, screenshot, or link to a repository

Snack example
[https://snack.expo.dev/oqdkk1hN-](https://snack.expo.dev/oqdkk1hN-)
Note that the issue does not occur on the web variant

**Comment by jmoyers14** [comment]
The issue is the constructor for URLSearchParams only supports objects:
https://github.com/facebook/react-native/blob/27b631e5b07a056d4bced19fb24537c156d2f8fa/packages/react-native/Libraries/Blob/URL.js#L60

If passed an array the constructor will iterate it's keys which are 0, 1, 2, etc and use them as the URL parameter names.

The react-native implementation is a lot simpler than the one from node, for example. 
https://github.com/nodejs/node/blob/f16f41c5b3cf2345abc7bd4d5e951a43479ce4a7/lib/internal/url.js#L332

Probably the team has not had time to devote to it yet. For now I'm patching URLSearchParams with my own very simple implementation

```
class MyURLSearchParams extends URLSearchParams {
    constructor(params: any) {
        super(params)
        if (Array.isArray(params))  {
            // @ts-ignore
            this._searchParams = params;
        }
}
global.URLSearchParams = MyURLSearchParams;
```
