### ISSUE TITLE
FontStyle 'italic' not working on iOS

### ISSUE THREAD

**Issue by Girum** [facebook/react-native#37277]
### Description

Hi! I'm using so many different texts in my app. Some with the react-native-render-html. But when I have to use fontStyle: 'italic', it's not working on iOS (even in the <Text> component).

![Screenshot 2023-05-05 at 11 02 00](https://user-images.githubusercontent.com/1349300/236479987-a7aa4689-1b12-4280-ae88-204f0b4681c6.png)

In android it works perfectly, but in iOS not workin (custom os default fonts).

I extreme need the Italic fonts =(

### React Native Version

0.70.6

### Output of `npx react-native info`

-

### Steps to reproduce

-

### Snack, code example, screenshot, or link to a repository

`<Text style={{ fontStyle: 'italic' }} >Italic</Text>`

**Comment by aliceInWahed** [comment]
Yes I have some problem, loading italic on iOS. Android is showing fine

**Comment by Qyohu** [comment]
I have some problem

**Comment by aliceInWahed** [comment]
my problem was caused by the ttf file used wasn't having the correct full name as the font name. 
![Screenshot 2023-08-09 at 12 21 46 PM](https://github.com/facebook/react-native/assets/79141836/8d2c62a3-7052-41ef-8484-89be335d5f22)

make sure the ttf file u used has the correct full name as ur font name.

**Comment by jvegax** [comment]
I have the same problem.

`Inter italic` font is not working as expected **only on iOS devices**

**Comment by ArseniiLyzenko** [comment]
Bumping into the same problem!

**Comment by jvegax** [comment]
Found solution _**for my rn project**_

## Solution 1 (worked for me)

1) Open your **/ios** folder with **Xcode**
2) Clic on your project folder icon
  2.1) Go to **/Resources**
  2.2) Clic on your **_italic font name_** ( in my case is Roboto-Italic )
  
![1](https://github.com/facebook/react-native/assets/49287932/26318bfa-b8fe-4363-8ba2-94b16008c330)

3) Configure the target membership of your font
   3.1) Select all targets
![Captura de pantalla 2023-11-17 a las 12 40 34](https://github.com/facebook/react-native/assets/49287932/6b20f3f1-afec-40c8-9198-7fec28c001e5)

## Solution 2

This solution is useful in case you have more than 3 variants of the same font, for example your project works with Inter font and you have installed
- Inter-Medium
- Inter-Regular
- Inter-SemiBold
- Inter-Italic

In this case, you have more than 3 variants of the same font, and you need to choose one of them, and use something like [FontForge](https://fontforge.org/en-US/downloads/mac-dl/) to change the font name in order to avoid this iOS restriction of the maximum number of font variants

**Comment by williamjayjay** [comment]
ward
