### ISSUE TITLE
packager strict mode error

### ISSUE THREAD

**Issue by h3r2on** [facebook/react-native#3775]
I have a fresh install of OSX 10.11 and went through the getting started setup. When I open Xcode and hit run i get the following error:

    /Users/MyUser/MyProject/node_modules/react-native/packager/packager.js:15
    const fs = require('fs');
    ^^^^^
    SyntaxError: Use of const in strict mode.

it's like it's not picking up ES6 support...

Environment:
* mac OS 10.11.1
* node v4.2.1
* react-native-cli 0.1.7
* react-native 0.13.2
* watchman 3.9.0
* Xcode 7.1

**Comment by mkascel** [comment]
@h3r2on I just ran into this also, the issue on my end was that `~/.bashrc` wasn't getting sourced when launching a new terminal window, so NVM wasn't loading (you need node v4 to get the ES6 stuff to work).  

Since OS X treats every new terminal as a login shell (which only sources `.bash_profile`), you need to create a `.bash_profile` in your root that sources `.bashrc`. This `.bash_profile` worked for me:

```
if [ -f ~/.bashrc ]; then
   source ~/.bashrc
fi
```

**Comment by h3r2on** [comment]
@mkascel yup did'nt think about that. totally fixed it.

**Comment by phaddius** [comment]
@mkascel @h3r2on  I'm running into this as well, but I've never had a .bashrc file.  Can I ask what is in your .bashrc that makes this work?

**Comment by olivierlesnicki** [comment]
@phaddius you might want to check your `node version` ...

**Comment by mkascel** [comment]
@phaddius Have you installed NVM yet?  When you do that, the install should add a couple of lines to your .bashrc (I assume it creates it if it doesn't exist) to load NVM on a new shell.  It will add something like this:

```
export NVM_DIR="[Your home directory]/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
```

**Comment by phaddius** [comment]
Ah got it.  That loading of nvm actually got written into my .bash_profile upon install, and it does run by the packager.  The problem was my node version was not set to the latest, because I run another node web stack that I haven't upgraded, and it's still on 0.10.  I fixed it for now by adding `nvm use 4.2.1` to my .bash_profile, but is there a config file where I can only set the version when running react native, and leave it to the old version when running my web stack?

**Comment by mkascel** [comment]
Looks like there was a design decision by the nvm team to not have any kind of config parsing that would run an "auto use" command on a per-project basis, but there are various workarounds and additional packages people have used to achieve this.  IMO it's probably not worth the overhead/additional dependencies or configs when you can just do an `nvm use` as needed, but if you want to follow the thread, it's [here](https://github.com/creationix/nvm/issues/110).

**Comment by phaddius** [comment]
Understood and agreed.  Thanks for the info.

**Comment by lrettig** [comment]
Could someone please help me understand how Xcode knows to run `npm start` (or otherwise run the packager) automatically as part of the run process? I don't see any scripts added under Build Phases or the schemes. Thanks!
