### ISSUE TITLE
Add support for initWithBarButtonSystemItem to Right Button Item in NavigatorIOS

### ISSUE THREAD

**Issue by cancan101** [facebook/react-native#3783]
Currently there is no way to use the [`initWithBarButtonSystemItem`](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIBarButtonItem_Class/index.html#//apple_ref/occ/instm/UIBarButtonItem/initWithBarButtonSystemItem:target:action:) [when creating the Right Button Item in `NavigatorIOS`](https://github.com/facebook/react-native/blob/62e8ddc20561a39c3c839ab9f83c95493df117c0/React/Views/RCTNavItem.m#L104-L125).

This means that the [pre-made system buttons](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIBarButtonItem_Class/index.html#//apple_ref/c/tdef/UIBarButtonSystemItem) cannot be accessed. 

See also:
* http://stackoverflow.com/questions/29323069/how-to-display-an-icon-in-react-native

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/add-support-for-initwithbarbuttonsystemitem-to-right-button-item-in-navigatorios

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
