### ISSUE TITLE
Support for rightBarButtonItems (multiple Right Buttons) in NavigatorIOS

### ISSUE THREAD

**Issue by cancan101** [facebook/react-native#3784]
IOS Support multiple right buttons through the [`rightBarButtonItems`](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UINavigationItem_Class/index.html#//apple_ref/occ/instp/UINavigationItem/rightBarButtonItems) property. [Currently this is not supported by NavigatorIOS](https://github.com/facebook/react-native/blob/62e8ddc20561a39c3c839ab9f83c95493df117c0/React/Views/RCTNavItem.m#L104-L125).

**Comment by yejodido** [comment]
+1

**Comment by christopherdro** [comment]
Hi there! This issue is being closed because it is a feature request and not a bug. 

If you'd like you, can create an issue on [Product Pains](https://productpains.com/product/react-native).
ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. 

Thanks!

**Comment by cancan101** [comment]
posted: https://productpains.com/post/react-native/support-for-rightbarbuttonitems-multiple-right-buttons-in-navigatorios
