### ISSUE TITLE
Screen mirroring (airplay) is broken 

### ISSUE THREAD

**Issue by Chayuan** [facebook/react-native#37848]
### Description

The IOS screen mirroring feature is broken when a native alert is displayed.
The alert will only appear on the mirroring screen and not on the Iphone, preventing any interaction with it.

Occurs on IOS

The minimal reproduction uses expo managed, but ejecting won't solve the issue. 

### React Native Version

0.71.7

### Output of `npx react-native info`

 OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 102.20 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
    Watchman: 2023.02.13.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.1.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.8 => 0.71.8
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

- Start the project on your phone
- Start mirroring on a compatible screen like your Macbook screen
- On your phone, press the alert button.

-> The alert will only be shown on the mirroring screen but not on the phone

### Snack, code example, screenshot, or link to a repository

https://github.com/Chayuan/expo-screen-mirroring-issue

**Comment by Chayuan** [comment]
Edit : We were able to resolve the issue with airplay by reverting [this commit.](https://github.com/facebook/react-native/commit/0c53420a7af306d629350e1244e8e2ccae08a312)

**Comment by Pranav-yadav** [comment]
> Edit : We were able to resolve the issue with airplay by reverting [this commit.](https://github.com/facebook/react-native/commit/0c53420a7af306d629350e1244e8e2ccae08a312)
> 
> Edit 2 : Upgrading to react-native 0.71.10 does not fix the issue.

Cc: @cipolleschi

**Comment by cipolleschi** [comment]
Hi @Chayuan, thank you for opening the issue.
To properly investigate the issue, we would need a repro with an app created with the CLI, not with expo.

Could you double check that by:
- creating a new app with the CLI
- moving your `App.js` in the newly created app
- airplaying and clicking the button
The issue is still there? With that setup, we can work something out.

I don't think that reverting https://github.com/facebook/react-native/commit/0c53420a7af306d629350e1244e8e2ccae08a312 is a good long term solution as we introduced it to support the SceneDelegate approach with is the standard for modern iOS apps.

**Comment by Chayuan** [comment]
Hi @cipolleschi, thanks for the answer.

[Here](https://github.com/Chayuan/airplay-issue) is the minimal reproduction using the cli, I can confirm the issue is still there.

**Comment by cipolleschi** [comment]
Thanks! I hope to find some time this or next week to look into that. 👍

**Comment by dnamrata0805** [comment]
Hi we're facing the same issue.. is there any update on this?

**Comment by cipolleschi** [comment]
Not yet, sorry. Had been dragged away by other issues. :(

**Comment by dnamrata0805** [comment]
I see :( is there any plan to work on this soon-ish? It would help a lot to know an estimation for timeline

**Comment by csaicharan** [comment]
> Thanks! I hope to find some time this or next week to look into that. 👍

@cipolleschi Did you manage to find some time to look into this issue?

**Comment by cipolleschi** [comment]
Could you provide a repro for this using React Native vanilla, and with [this template](https://github.com/react-native-community/reproducer-react-native)?
I saw that the provided repro above is using Expo, and that's not good for me.

**Comment by csaicharan** [comment]
> Could you provide a repro for this using React Native vanilla, and with [this template](https://github.com/react-native-community/reproducer-react-native)?
> I saw that the provided repro above is using Expo, and that's not good for me.

Updated this [repo](https://github.com/csaicharan/screen-share-issue) using the mentioned template and find the reproduction steps [here](https://github.com/csaicharan/screen-share-issue/blob/main/REPRODUCE.md).

**Comment by cipolleschi** [comment]
I had a look at the issue recently but I couldn't test it properly as I don't have any mirroring enabled device at home or in the office. 
However, **we don't do anything specific with React Native to interact with AirPlay**. 
Can you check how a native app which just display an alert interact in that scenario?

---

One thing I noticed with external screens is that the alert is presented in that screen:
![Screenshot 2023-11-13 at 15 07 09](https://github.com/facebook/react-native/assets/11162307/bafbcd13-3258-4b45-927b-667f0a47f7ea)

While a Native App seems not to present the same behavior:
![Screenshot 2023-11-13 at 15 08 55](https://github.com/facebook/react-native/assets/11162307/cd72cc2b-52e1-4127-9d01-a98660e53787)

This difference can be due to how React Native handles the `Screens`. With two screens, we can choose which one to use with the `UIScreen` APIs.
However, while mirroring, we should still have a single Screen, so I don't think this is super relevant.

**Comment by csaicharan** [comment]
> I had a look at the issue recently but I couldn't test it properly as I don't have any mirroring enabled device at home or in the office. However, **we don't do anything specific with React Native to interact with AirPlay**. Can you check how a native app which just display an alert interact in that scenario?
> 
> One thing I noticed with external screens is that the alert is presented in that screen: ![Screenshot 2023-11-13 at 15 07 09](https://user-images.githubusercontent.com/11162307/282500072-bafbcd13-3258-4b45-927b-667f0a47f7ea.png)
> 
> While a Native App seems not to present the same behavior: ![Screenshot 2023-11-13 at 15 08 55](https://user-images.githubusercontent.com/11162307/282500561-cd72cc2b-52e1-4127-9d01-a98660e53787.png)
> 
> This difference can be due to how React Native handles the `Screens`. With two screens, we can choose which one to use with the `UIScreen` APIs. However, while mirroring, we should still have a single Screen, so I don't think this is super relevant.

Thanks for looking into it, I have checked the alerts with native apps and it's working without an issue. 

FYI: This issue does not occur in react-native version 0.71.0.
