### ISSUE TITLE
[IOS] After integrat to exist project, how to handle some unexpected error

### ISSUE THREAD

**Issue by RandyZ** [facebook/react-native#3792]
After integrat to exist project, how to handle some unexpected error in IOS and Android native code?

For example, Network is unreachable or some error from React Native view.

Thanks!

By the way. Sorry，I forget close my previous question！

**Comment by mkonicek** [comment]
Hey @RandyZ, please use Stack Overflow to ask questions: stackoverflow.com/questions/tagged/react-native

Your question is more likely to be answered there by the community and it also helps us keep track of bugs and feature requests in github issues.

I'll close this as it is a question rather than an issue.

**Comment by mkonicek** [comment]
It will be also helpful to provide examples of what errors you're trying to handle. A lot of APIs have an error callback.

**Comment by RandyZ** [comment]
Thanks, got it.
