### ISSUE TITLE
Exporting Swift Value Types

### ISSUE THREAD

**Issue by tsaizhenling** [facebook/react-native#3793]
background:

we have a mature IOS project for which we are trying to use reactNative only for some parts of the application. so we already have built an extensive Model layer natively and we intend to keep it native. we also have plans to migrate this Model layer to Swift Value Types. 

ideally we would like to be able to export our new Model layer as swift value types to js.

Question:

the guide covers how we should export a class with `RCT_EXTERN_MODULE` and `RCT_EXTERN_METHOD`. can we do the same with a swift struct?

**Comment by jsierles** [comment]
Hey and thanks for posting this!

There's an awesome place to post code / ask question first before filing an issue: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see and answer your question. This lets us use the github bug tracker for bugs.

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)

**Comment by ide** [comment]
Also regarding Swift specifically, it is not a top priority for React Native to support Swift at this time. In the near future we'll add a page to the documentation listing features that are out of scope ("non-goals"), Swift being one of them.
