### ISSUE TITLE
Could not find any matches for com.facebook.react:react-native:+ as no versions of com.facebook.react:react-native are available.

### ISSUE THREAD

**Issue by sleaper** [facebook/react-native#37936]
### Description

When I run `npx react-native run-android` I get this error:
```
* What went wrong:
Could not determine the dependencies of task ':react-native-async-storage_async-storage:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':react-native-async-storage_async-storage:debugCompileClasspath'.
   > Could not find any matches for com.facebook.react:react-native:+ as no versions of com.facebook.react:react-native are available.
     Required by:
         project :react-native-async-storage_async-storage
```

### React Native Version

0.71.11

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 34.81 GB / 46.97 GB
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 9.1.2 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: AI-221.6008.13.2211.9477386
  Languages:
    Java: 11.0.19 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: ^11.3.1 => 11.3.1 
    react: Not Found
    react-native: 0.71.11 => 0.71.11 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Cannot reproduce

### Snack, code example, screenshot, or link to a repository

My android/build.gradle:
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        kotlinVersion = "1.7.0"
        minSdkVersion = 23
        compileSdkVersion = 33
        targetSdkVersion = 33

        VisionCameraCodeScanner_targetSdkVersion = 33
        VisionCameraCodeScanner_compileSdkVersion = 33

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.3.1")
        classpath("com.facebook.react:react-native-gradle-plugin")
        // WARNING: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath 'com.google.gms:google-services:4.3.14'
    }
}
```

**Comment by sleaper** [comment]
When I remove @react-native-async-storage/async-storage and try to rebuild. I get this error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':react-native-biometrics:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':react-native-biometrics:debugCompileClasspath'.
   > Could not find any matches for com.facebook.react:react-native:+ as no versions of com.facebook.react:react-native are available.
     Required by:
         project :react-native-biometrics
```

**Comment by sleaper** [comment]
Then when I remove `react-native-biometrics` and rebuild. I get this error:
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':react-native-bootsplash:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':react-native-bootsplash:debugCompileClasspath'.
   > Could not find any matches for com.facebook.react:react-native:+ as no versions of com.facebook.react:react-native are available.
     Required by:
         project :react-native-bootsplash
```

**Comment by cortinico** [comment]
@sleaper can you please share your `android/app/build.gradle` file?

**Comment by cortinico** [comment]
> apply from: "../../../node_modules/react-native-code-push/android/codepush.gradle"

> apply from: "../../../node_modules/react-native-vector-icons/fonts.gradle"

Could you try to remove those 2 lines and report back if the issue is solved? I have the suspect you're using either a old version of CodePush or Vector Icons.

Moreover, could you share your `package.json`?

**Comment by sleaper** [comment]
> > apply from: "../../../node_modules/react-native-code-push/android/codepush.gradle"
> 
> > apply from: "../../../node_modules/react-native-vector-icons/fonts.gradle"
> 
> Could you try to remove those 2 lines and report back if the issue is solved? I have the suspect you're using either a old version of CodePush or Vector Icons.
> 
> Moreover, could you share your `package.json`?

I removed those 2 lines and the error still persists. Here is my package.json:
```
{
  "name": "authier-mobile-app",
  "version": "1.0.9",
  "license": "AGPL-3.0-or-later",
  "scripts": {
    "android": "pnpm exec react-native run-android",
    "ios": "react-native run-ios",
    "start2": "react-native start --port 8088",
    "start": "react-native start",
    "start:nocache": "react-native start --reset-cache",
    "test": "jest",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx",
    "adb:reverse": "adb reverse tcp:8088 tcp:8088",
    "gen": "graphql-codegen",
    "lingui:extract": "lingui extract",
    "lingui:compile": "lingui compile",
    "killPort": "lsof -ti tcp:8088 | xargs kill",
    "postinstall": "./scripts/copyNodeModulesHack.mjs",
    "pod:install": "cd ios && pod install",
    "cleanDerivedData": "rm -rf ~/Library/Developer/Xcode/DerivedData",
    "buildRelease": "cd android && ./gradlew clean && ./gradlew bundleRelease",
    "installBundle": "npx react-native run-android --mode=release",
    "postversion": "react-native-version"
  },
  "reactNativePermissionsIOS": [
    "Camera",
    "FaceID",
    "Notifications"
  ],
  "dependencies": {
    "@apollo/client": "^3.7.15",
    "@babel/preset-env": "^7.22.2",
    "@babel/preset-react": "^7.22.3",
    "@hookform/resolvers": "^2.9.11",
    "@lingui/core": "^4.2.0",
    "@lingui/react": "^4.2.0",
    "@react-native-clipboard/clipboard": "^1.11.2",
    "@react-native-community/cli": "^11.3.1",
    "@react-native-community/cli-platform-android": "^11.3.1",
    "@react-native-community/cli-platform-ios": "^11.3.1",
    "@react-native-community/netinfo": "^9.3.10",
    "@react-native-firebase/app": "^17.5.0",
    "@react-native-firebase/messaging": "^17.5.0",
    "@react-native-masked-view/masked-view": "^0.2.9",
    "@react-native/metro-config": "^0.72.6",
    "@react-navigation/bottom-tabs": "^6.5.7",
    "@react-navigation/drawer": "^6.6.2",
    "@react-navigation/material-top-tabs": "^6.6.2",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "@react-navigation/stack": "^6.3.16",
    "@rnx-kit/babel-preset-metro-react-native": "^1.1.4",
    "@rnx-kit/cli": "^0.16.9",
    "@rnx-kit/metro-config": "^1.3.6",
    "@rnx-kit/metro-resolver-symlinks": "^0.1.28",
    "@sentry/react-native": "5.5.0",
    "@shopify/flash-list": "^1.4.3",
    "@testing-library/react": "^14.0.0",
    "@ts-react/form": "^1.6.4",
    "apollo-link-http": "^1.5.17",
    "apollo-link-queue": "^3.1.0",
    "apollo-link-retry": "^2.2.16",
    "apollo-link-serialize": "^4.0.0",
    "apollo-link-token-refresh": "^0.6.0",
    "apollo3-cache-persist": "^0.14.1",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "cross-fetch": "^3.1.6",
    "date-fns": "^2.30.0",
    "formik": "^2.4.0",
    "graphql": "^16.6.0",
    "graphql-tools": "^9.0.0",
    "intl": "^1.2.5",
    "jest-environment-node": "^29.5.0",
    "jsc-android": "^250231.0.0",
    "jssha": "^3.3.0",
    "jwt-decode": "^3.1.2",
    "make-plural": "^7.3.0",
    "ms": "^2.1.3",
    "native-base": "^3.4.28",
    "query-string": "^8.1.0",
    "react": "18.2.0",
    "react-hook-form": "^7.44.2",
    "react-native": "0.71.11",
    "react-native-bootsplash": "4.7.0",
    "react-native-camera": "^4.2.1",
    "react-native-circular-progress-indicator": "^4.4.2",
    "react-native-code-push": "^8.0.2",
    "react-native-device-info": "^10.6.0",
    "react-native-fast-image": "^8.6.3",
    "react-native-gesture-handler": "2.10.1",
    "react-native-get-random-values": "^1.9.0",
    "react-native-gradle-plugin": "^0.72.1",
    "react-native-mmkv": "^2.8.0",
    "react-native-pager-view": "^6.2.0",
    "react-native-permissions": "^3.8.0",
    "react-native-qrcode-scanner": "^1.6.0",
    "react-native-reanimated": "^2.17.0",
    "react-native-safe-area-context": "4.5.3",
    "react-native-screens": "^3.20.0",
    "react-native-sensitive-info": "^6.0.0-alpha.9",
    "react-native-svg": "13.9.0",
    "react-native-tab-view": "^3.5.1",
    "react-native-url-polyfill": "^1.3.0",
    "react-native-uuid": "^2.0.1",
    "react-native-vector-icons": "^9.2.0",
    "react-native-vision-camera": "^2.15.4",
    "react-native-webview": "12.1.0",
    "react-native-webview-crypto": "^0.0.25",
    "react-query": "^3.39.3",
    "styled-system": "^5.1.5",
    "text-decoding": "^1.0.0",
    "vision-camera-code-scanner": "^0.2.0",
    "zod": "^3.21.4",
    "zustand": "^4.3.8",
    "zxcvbn-typescript": "^5.0.1"
  },
  "devDependencies": {
    "@apollo/react-testing": "^4.0.0",
    "@babel/core": "^7.22.1",
    "@babel/preset-typescript": "^7.21.5",
    "@babel/runtime": "^7.22.3",
    "@jest/globals": "^29.5.0",
    "@lingui/cli": "^4.2.0",
    "@lingui/macro": "^4.2.0",
    "@react-native-community/eslint-config": "^3.2.0",
    "@testing-library/react-native": "^12.1.2",
    "@types/crypto-js": "^4.1.1",
    "@types/jest": "^29.5.2",
    "@types/react": "^18.2.12",
    "@types/react-native": "^0.72.2",
    "@types/react-native-vector-icons": "^6.4.13",
    "@types/react-test-renderer": "^18.0.0",
    "appcenter-cli": "^2.13.8",
    "babel-jest": "^29.5.0",
    "babel-plugin-macros": "^3.1.0",
    "babel-plugin-module-resolver": "^5.0.0",
    "eslint": "^8.41.0",
    "jest": "^29.5.0",
    "metro-react-native-babel-preset": "0.76.5",
    "prettier": "^2.8.8",
    "pretty-quick": "^3.1.3",
    "react-native-codegen": "^0.72.0",
    "react-native-dotenv": "^3.4.8",
    "react-native-version": "^4.0.0",
    "react-test-renderer": "18.2.0",
    "typescript": "^5.1.3"
  },
  "jest": {
    "testEnvironmentOptions": {},
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ],
    "transformIgnorePatterns": [
      "node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg)"
    ],
    "setupFiles": [
      "./jestSetup.js"
    ]
  }
}

```

**Comment by cortinico** [comment]
```
    "react-native-gradle-plugin": "^0.72.1",
```

You need to remove this line from your `package.json` (why you had it in the first place)?

**Comment by sleaper** [comment]
> ```
>     "react-native-gradle-plugin": "^0.72.1",
> ```
> 
> You need to remove this line from your `package.json` (why you had it in the first place)?

We actually had this package for some time. I don't really remember why we added that. However yesterday it worked seamlessly. Maybe I forgot to update my node_modules.
You are an absolute legend. Saved my day!

**Comment by litinskii** [comment]
this problem comes with react-native-screens@3.12.0 they add dependency
<img width="583" alt="image" src="https://github.com/facebook/react-native/assets/10028441/12f1196d-ce99-47f4-ba1e-088e5385806b">

**Comment by abed-obaah** [comment]
when i run eas build i get the 

Running 'gradlew :app:bundleRelease' in /home/expo/workingdir/build/android
Downloading https://services.gradle.org/distributions/gradle-7.5.1-all.zip
10%
20%.
30
%.
40%.
50%.
60%.
70%.
80%
90%
100%
Welcome to Gradle 7.5.1!
Here are the highlights of this release:
 - Support for Java 18
 - Support for building with Groovy 4
- Much more responsive continuous builds
 - Improved diagnostics for dependency resolution
For more details see https://docs.gradle.org/7.5.1/release-notes.html
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.5.1/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build
> Task :expo-updates-gradle-plugin:pluginDescriptors
> Task :expo-updates-gradle-plugin:processResources
> Task :react-native-gradle-plugin:pluginDescriptors
> Task :react-native-gradle-plugin:processResources
> Task :expo-dev-launcher-gradle-plugin:pluginDescriptors
> Task :expo-dev-launcher-gradle-plugin:processResources
> Task :expo-dev-launcher-gradle-plugin:compileKotlin
> Task :expo-dev-launcher-gradle-plugin:compileJava
NO-SOURCE
> Task :expo-dev-launcher-gradle-plugin:classes
> Task :expo-dev-launcher-gradle-plugin:jar
> Task :expo-dev-launcher-gradle-plugin:inspectClassesForKotlinIC
> Task :react-native-gradle-plugin:compileKotlin
> Task :react-native-gradle-plugin:compileJava NO-SOURCE
> Task :react-native-gradle-plugin:classes
> Task :react-native-gradle-plugin:inspectClassesForKotlinIC
> Task :react-native-gradle-plugin:jar
> Task :expo-updates-gradle-plugin:compileKotlin
> Task :expo-updates-gradle-plugin:compileJava NO-SOURCE
> Task :expo-updates-gradle-plugin:classes
> Task :expo-updates-gradle-plugin:jar
> Task :expo-updates-gradle-plugin:inspectClassesForKotlinIC
> Configure project :app
 ℹ️  Applying gradle plugin 'expo-dev-launcher-gradle-plugin' (expo-dev-launcher@2.4.14)
 ℹ️  Applying gradle plugin 'expo-updates-gradle-plugin' (expo-updates@0.18.17)
Stop expo-updates app.manifest generation because ReactExtension is not registered
> Configure project :expo-av
Checking the license for package CMake 3.22.1 in /home/expo/Android/Sdk/licenses
License for package CMake 3.22.1 accepted.
Preparing "Install CMake 3.22.1 (revision: 3.22.1)".
"Install CMake 3.22.1 (revision: 3.22.1)" ready.
Installing CMake 3.22.1 in /home/expo/Android/Sdk/cmake/3.22.1
"Install CMake 3.22.1 (revision: 3.22.1)" complete.
"Install CMake 3.22.1 (revision: 3.22.1)" finished.
> Configure project :expo-linear-gradient
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.
> Configure project :expo
Using expo modules
  - expo-application (5.3.1)
  - expo-av (13.4.1)
  - expo-camera (13.4.4)
  - expo-clipboard (4.3.1)
  - expo-constants (14.4.2)
  - expo-dev-client (2.4.12)
  - expo-dev-launcher (2.4.14)
  - expo-dev-menu (3.2.2)
  - expo-device (5.4.0)
  - expo-document-picker (11.5.4)
  - expo-eas-client (0.6.0)
  - expo-file-system (15.4.4)
  - expo-font (11.4.0)
  - expo-haptics (12.4.0)
  - expo-image-loader (4.3.0)
  - expo-image-manipulator (11.3.0)
  - expo-image-picker (14.3.2)
  - expo-json-utils (0.7.1)
  - expo-keep-awake (12.3.0)
  - expo-linear-gradient (11.4.0)
  - expo-location (16.1.0)
  - expo-manifests (0.7.2)
  - expo-media-library (15.4.1)
  - expo-modules-core (1.5.12)
  - expo-modules-core$android-annotation (1.5.12)
  - expo-modules-core$android-annotation-processor (1.5.12)
- expo-navigation-bar (2.3.0)
  - expo-notifications (0.20.1)
  - expo-permissions (14.4.0)
  - expo-sharing (11.5.0)
  - expo-splash-screen (0.20.5)
  - expo-structured-headers (3.3.0)
  - expo-updates (0.18.17)
> Configure project :qore-id_react-native-qoreid-sdk
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.
> Configure project :react-native-firebase_app
:react-native-firebase_app package.json found at /home/expo/workingdir/build/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_app:firebase.bom using default value: 31.4.0
:react-native-firebase_app:play.play-services-auth using default value: 20.3.0
:react-native-firebase_app package.json found at /home/expo/workingdir/build/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_app:version set from package.json: 17.5.0 (17,5,0 - 17005000)
:react-native-firebase_app:android.compileSdk using custom value: 31
:react-native-firebase_app:android.targetSdk using custom value: 31
:react-native-firebase_app:android.minSdk using custom value: 21
:react-native-firebase_app:reactNativeAndroidDir /home/expo/workingdir/build/node_modules/react-native/android
> Configure project :react-native-firebase_auth
:react-native-firebase_auth package.json found at /home/expo/workingdir/build/node_modules/@react-native-firebase/auth/package.json
:react-native-firebase_app package.json found at /home/expo/workingdir/build/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_auth:firebase.bom using default value: 31.4.0
:react-native-firebase_auth package.json found at /home/expo/workingdir/build/node_modules/@react-native-firebase/auth/package.json
:react-native-firebase_auth:version set from package.json: 17.5.0 (17,5,0 - 17005000)
:react-native-firebase_auth:android.compileSdk using custom value: 31
:react-native-firebase_auth:android.targetSdk using custom value: 31
:react-native-firebase_auth:android.minSdk using custom value: 21
:react-native-firebase_auth:reactNativeAndroidDir /home/expo/workingdir/build/node_modules/react-native/android
> Configure project :react-native-firebase_database
:react-native-firebase_database package.json found at /home/expo/workingdir/build/node_modules/@react-native-firebase/database/package.json
:react-native-firebase_app package.json found at /home/expo/workingdir/build/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_database:firebase.bom using default value: 31.4.0
:react-native-firebase_database package.json found at /home/expo/workingdir/build/node_modules/@react-native-firebase/database/package.json
:react-native-firebase_database:version set from package.json: 17.5.0 (17,5,0 - 17005000)
:react-native-firebase_database:android.compileSdk using custom value: 31
:react-native-firebase_database:android.targetSdk using custom value: 31
:react-native-firebase_database:android.minSdk using custom value: 21
:react-native-firebase_database:reactNativeAndroidDir /home/expo/workingdir/build/node_modules/react-native/android
> Configure project :react-native-firebase_firestore
:react-native-firebase_firestore package.json found at /home/expo/workingdir/build/node_modules/@react-native-firebase/firestore/package.json
:react-native-firebase_app package.json found at /home/expo/workingdir/build/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_firestore:firebase.bom using default value: 31.4.0
:react-native-firebase_firestore package.json found at /home/expo/workingdir/build/node_modules/@react-native-firebase/firestore/package.json
:react-native-firebase_firestore:version set from package.json: 17.5.0 (17,5,0 - 17005000)
:react-native-firebase_firestore:android.compileSdk using custom value: 31
:react-native-firebase_firestore:android.targetSdk using custom value: 31
:react-native-firebase_firestore:android.minSdk using custom value: 21
:react-native-firebase_firestore:reactNativeAndroidDir /home/expo/workingdir/build/node_modules/react-native/android
> Configure project :react-native-firebase_messaging
:react-native-firebase_messaging package.json found at /home/expo/workingdir/build/node_modules/@react-native-firebase/messaging/package.json
:react-native-firebase_app package.json found at /home/expo/workingdir/build/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_messaging:firebase.bom using default value: 31.4.0
:react-native-firebase_messaging package.json found at /home/expo/workingdir/build/node_modules/@react-native-firebase/messaging/package.json
:react-native-firebase_messaging:version set from package.json: 17.5.0 (17,5,0 - 17005000)
:react-native-firebase_messaging:android.compileSdk using custom value: 31
:react-native-firebase_messaging:android.targetSdk using custom value: 31
:react-native-firebase_messaging:android.minSdk using custom value: 21
:react-native-firebase_messaging:reactNativeAndroidDir /home/expo/workingdir/build/node_modules/react-native/android
> Configure project :react-native-reanimated
No AAR for react-native-reanimated found. Attempting to build from source.
Android gradle plugin: 7.4.2
Gradle: 7.5.1
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.
Checking the license for package NDK (Side by side) 23.1.7779620 in /home/expo/Android/Sdk/licenses
License for package NDK (Side by side) 23.1.7779620 accepted.
Preparing "Install NDK (Side by side) 23.1.7779620 (revision: 23.1.7779620)".
"Install NDK (Side by side) 23.1.7779620 (revision: 23.1.7779620)" ready.
Installing NDK (Side by side) 23.1.7779620 in /home/expo/Android/Sdk/ndk/23.1.7779620
"Install NDK (Side by side) 23.1.7779620 (revision: 23.1.7779620)" complete.
"Install NDK (Side by side) 23.1.7779620 (revision: 23.1.7779620)" finished.
FAILURE: Build failed with an exception.
* What went wrong:
Could not determine the dependencies of task ':app:buildReleasePreBundle'.
> Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
   > Could not find com.facebook.react:react-native:0.72.6.
     Searched in the following locations:
       - file:/home/expo/.m2/repository/com/facebook/react/react-native/0.72.6/react-native-0.72.6.pom
       - file:/home/expo/workingdir/build/node_modules/react-native/android/com/facebook/react/react-native/0.72.6/react-native-0.72.6.pom
       - file:/home/expo/workingdir/build/node_modules/jsc-android/dist/com/facebook/react/react-native/0.72.6/react-native-0.72.6.pom
       - https://dl.google.com/dl/android/maven2/com/facebook/react/react-native/0.72.6/react-native-0.72.6.pom
       - https://www.jitpack.io/com/facebook/react/react-native/0.72.6/react-native-0.72.6.pom
       - file:/home/expo/workingdir/build/node_modules/expo-camera/android/maven/com/facebook/react/react-native/0.72.6/react-native-0.72.6.pom
     Required by:
         project :app
         project :app > project :pusher_pusher-websocket-react-native
         project :app > project :qore-id_react-native-qoreid-sdk
         project :app > project :react-native-async-storage_async-storage
         project :app > project :react-native-community_datetimepicker
         project :app > project :react-native-community_geolocation
         project :app > project :react-native-community_netinfo
         project :app > project :react-native-community_viewpager
project :app > project :react-native-firebase_app
project :app > project :react-native-firebase_auth
         project :app > project :react-native-firebase_database
         project :app > project :react-native-firebase_firestore
         project :app > project :react-native-firebase_messaging
         project :app > project :react-native-picker_picker
         project :app > project :expo
         project :app > project :lottie-react-native
         project :app > project :react-native-config
         project :app > project :react-native-geolocation-service
project :app > project :react-native-get-random-values
         project :app > project :react-native-image-picker
         project :app > project :react-native-maps
         project :app > project :react-native-paystack-webview
         project :app > project :react-native-safe-area-context
         project :app > project :react-native-screens
         project :app > project :react-native-sms-retriever
         project :app > project :react-native-ssl-pinning
         project :app > project :react-native-svg
         project :app > project :react-native-sweet-alert
         project :app > project :react-native-webview
         project :app > project :react-native-wheel-pick
         project :app > project :expo > project :expo-modules-core
         project :app > project :expo > project :expo-av
         project :app > project :expo > project :expo-dev-launcher
         project :app > project :expo > project :expo-dev-menu
         project :app > project :expo > project :expo-splash-screen
         project :app > project :expo > project :expo-updates
         project :app > project :expo > project :expo-dev-launcher > project :expo-dev-menu-interface
   > Could not find com.facebook.react:react-android:.
     Required by:
         project :app > project :react-native-gesture-handler
         project :app > project :react-native-reanimated
> Could not find com.facebook.react:hermes-android:.
     Required by:
         project :app > project :react-native-reanimated
   > Could not find com.facetec.sdk:facetec:9.6.38.
     Searched in the following locations:
       - http://10.4.1.4:8081/artifactory/libs-release/com/facetec/sdk/facetec/9.6.38/facetec-9.6.38.pom
       - file:/home/expo/.m2/repository/com/facetec/sdk/facetec/9.6.38/facetec-9.6.38.pom
       - file:/home/expo/workingdir/build/node_modules/react-native/android/com/facetec/sdk/facetec/9.6.38/facetec-9.6.38.pom
       - file:/home/expo/workingdir/build/node_modules/jsc-android/dist/com/facetec/sdk/facetec/9.6.38/facetec-9.6.38.pom
       - https://dl.google.com/dl/android/maven2/com/facetec/sdk/facetec/9.6.38/facetec-9.6.38.pom
       - https://repo.maven.apache.org/maven2/com/facetec/sdk/facetec/9.6.38/facetec-9.6.38.pom
       - https://www.jitpack.io/com/facetec/sdk/facetec/9.6.38/facetec-9.6.38.pom
       - file:/home/expo/workingdir/build/node_modules/expo-camera/android/maven/com/facetec/sdk/facetec/9.6.38/facetec-9.6.38.pom
     Required by:
         project :app > project :qore-id_react-native-qoreid-sdk > com.qoreid:qoreid-sdk:1.1.32
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 4m 28s
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
15 actionable tasks: 15 executed

**Comment by VGerris** [comment]
perhaps late, but use gradle 8.x and Java SDK 17, that is what most react native libs use.
