### ISSUE TITLE
react-native init hangs over time

### ISSUE THREAD

**Issue by gitlovenotwar** [facebook/react-native#3798]
It seems no one has ever solved this one yet so I reopen the issue. It hangs over time with no response at all. More people still encountering the problem. Adding --verbose as stated here https://github.com/facebook/react-native/issues/2806 shows now some log. I'm having this issue
<pre>events.js:141 - Unhandled 'error' event, Error: spawn npm ENOENT</pre>
Can some explain what's happening? Thanks.

**Comment by qianjiahao** [comment]
i got the same problem , could you have something to resolve it ?

**Comment by sundaravelit** [comment]
add `react-native init ProjectName --verbose` option

**Comment by gphilipp** [comment]
Tried today with react-native 0.17.  have a lot of these in the console after typing something like 
`react-native init MyProject --verbose` :

```
(...)
npm info retry will retry, error on last attempt: Error: connect ETIMEDOUT 185.31.17.162:443
(...)
```

**Comment by gphilipp** [comment]
Probably related to https://github.com/npm/npm/issues/9862.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/react-native-init-hangs-over-time

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
