### ISSUE TITLE
Passing styles down to custom component doesn't work

### ISSUE THREAD

**Issue by roman01la** [facebook/react-native#380]
I've tried to pass an object with some styles to custom component:
```jsx
let childStyle = { color: '#242424' };
<MyComp style={childStyle}>text</MyComp>
```

And pick it up inside of `MyComp` component like this:
```jsx
let styles = StyleSheet.create({

  text: Object.assign({ fontSize: 12 }, this.props.style)
});

<Text style={styles.text}>{this.props.children}</Text>
```

But it seems styles didn't apply. When I `console.log(styles.text)` there's only a weird number: 30.

**Comment by vjeux** [comment]
So, StyleSheet.create turns the style object into a number that references an internal cache. The idea is to be able to send those numbers to native instead of serializing the style object over and over again. This is a cheap immutable persistent datastructure.

You can do <Text style={[styles.first, styles.second]}> instead of Object.assign
