### ISSUE TITLE
Subsequent Views clip overflowing content of previous views

### ISSUE THREAD

**Issue by mschipperheyn** [facebook/react-native#3814]
So, if I position an element absolutely to make it overflow it's containing View. Any subsequent View which is non transparent will clip the overflowing content. It seems like any subsequent View gets a z-index higher than a previous one

	<View style={{
	marginHorizontal:12,
	borderRadius:2,
	borderWidth:1,
	}}>
	  <View style={{
		  flex:0,
		  height:175
	  }}>
		<View style={{
			position:'absolute',
			bottom:-24,
			right:16,
		}}>
			<FABButton icon="plus"/>
		</View>
	  </View>

	  <View style={{
		flex:0,

	  }}>
		<View style={{
			marginTop:24,
			marginHorizontal:24,
			marginBottom:16
		}}>
		  <Text style={[fontSize:24}>My Title</Text>
		  <Text style={{fontSize:14}}>My subtitle</Text>
		</View>
	  </View>
	</View>

**Comment by mschipperheyn** [comment]
A workaround obvious is putting it in the following view and set top:-24.

**Comment by satya164** [comment]
Currently you need to put the element at the end if you want it at the top.

**Comment by mschipperheyn** [comment]
Yes, and this basically means that you end up with absolute in stead relative positioning. Which makes designing for various screen sizes more laborious and error prone.

**Comment by satya164** [comment]
@mschipperheyn Yeah, at least supporting flex-order can solve this

**Comment by mschipperheyn** [comment]
exactly

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/subsequent-views-clip-overflowing-content-of-previous-views

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
