### ISSUE TITLE
Native exceptions when manipulating ART children without a surface

### ISSUE THREAD

**Issue by spicyj** [facebook/react-native#3815]
Rendering this component throws a cryptic error on the native side because every ART Group should be mounted in a Surface and it gets confused. 

```js
'use strict';

var React = require('react-native');
var ReactART = require('ReactNativeART');

var {View} = React;
var {Group} = ReactART;

var ArtBug = React.createClass({
  getInitialState: function() {
    return {showGroup: true};
  },
  componentDidMount: function() {
    this.setState({showGroup: false});
  },
  render: function() {
    return (
      <View>{this.state.showGroup && <Group />}</View>
    );
  },
});

module.exports = ArtBug;
```

We should probably throw an error earlier for this case. One way to do it would be to use context to pass down some flag from the Surface and throw if it's not present in the other components.

**Comment by browniefed** [comment]
@facebook-github-bot label Good First Task

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/native-exceptions-when-manipulating-art-children-without-a-surface

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
