### ISSUE TITLE
[Android] Reload bridge

### ISSUE THREAD

**Issue by PhilippKrone** [facebook/react-native#3824]
Hello,

is there any (public) method which reloads the bridge entirely, analogous to  [self.bridge reload] in iOS? I've tried the following but it seems to not really work (the progress dialog is not getting dismissed):

````javascript
        DevSupportManager mDevSupportManager = mActivity.getDevSupportManager();
        mDevSupportManager.handleReloadJS();
````

**Comment by PhilippKrone** [comment]
Update: Is this the correct one?

````javascript
        UiThreadUtil.runOnUiThread(
                new Runnable() {
                    @Override
                    public void run() {
                        reactActivity.getReactInstanceManager().createReactContextInBackground();
                    }
                }
        );
````

**Comment by shahankit** [comment]
@PhilippKrone Did you find how to do so finally?

**Comment by PhilippKrone** [comment]
@shahankit I'm using the code snipped pasted above.

**Comment by shahankit** [comment]
ok

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-reload-bridge

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
