### ISSUE TITLE
shadowSpread property

### ISSUE THREAD

**Issue by niftylettuce** [facebook/react-native#3826]
Can we get something like this?

```js
var style = StyleSheet.create({
  shadowColor: '#206561',
  shadowOffset: {
    width: 0,
    height: 1
    },
    shadowOpacity: 1,
    shadowRadius: 2
    shadowSpread: 0 // <---- so it doesn't have curves as the Actual has below?  not sure...
});
```

The expected result is to have a drop shadow that spans the entire width of the container to the edges.

Expected:

![screen shot 2015-11-01 at 1 35 25 pm](https://cloud.githubusercontent.com/assets/523141/10870629/7360c39a-809d-11e5-9151-84f9a0df2e71.png)

Actual:

![screen shot 2015-11-01 at 1 35 20 pm](https://cloud.githubusercontent.com/assets/523141/10870631/7785ec02-809d-11e5-95b5-6dad57510802.png)

**Comment by browniefed** [comment]
@facebook-github-bot label Feature Request

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/shadowspread-property

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
