### ISSUE TITLE
Prevent a WebView from becoming a responder

### ISSUE THREAD

**Issue by aleclarson** [facebook/react-native#3828]
I've tried adding a `PanResponder` to a `View` that holds the `WebView` as a child. But when trying to use `onStartShouldSetPanResponderCapture`, the `WebView` still responds to the touch.

A workaround is to set the `WebView`'s `scrollEnabled` to `false` inside `onPanResponderGrant`, but that doesn't prevent the text zoom/selection from being triggered.

**Comment by cmcewen** [comment]
Try a transparent `View` absolutely positioned over the the `WebView` maybe?

**Comment by aleclarson** [comment]
@cmcewen The problem there is that the touch is already being handled by the time the `View` is there to block the touch.

**Comment by aleclarson** [comment]
I could take advantage of `- (void)sendEvent:(UIEvent *)event` in `UIWindow` to intercept the touch before it is sent to the `UIWebView`, but that may not be applicable here depending on how touch handling is done in React Native.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/prevent-a-webview-from-becoming-a-responder

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
