### ISSUE TITLE
[PushNotification] RCTPushNotificationManager.h not found

### ISSUE THREAD

**Issue by jihopark** [facebook/react-native#3831]
I followed everything here (https://facebook.github.io/react-native/docs/pushnotificationios.html
) to use PushNotification on iOS, but when I try to build the app, I get the following error. 

`RCTPushNotificationManager.h file not found`

I even added `RCTPushNotification.xcodeproj` to Libraries but it still get the same error.

**Comment by jihopark** [comment]
fixed by following
https://facebook.github.io/react-native/docs/linking-libraries-ios.html

**Comment by yychun1217** [comment]
just encountered this issue, thx.

**Comment by jihopark** [comment]
i think https://facebook.github.io/react-native/docs/pushnotificationios.html
should include details about linking libraries

**Comment by niftylettuce** [comment]
Yeah, definitely.  Please update the docs.  @jihopark can you please re-open this issue? /cc @yychun1217 @ide

**Comment by brentvatne** [comment]
@niftylettuce @jihopark - can you submit a pull request please?

**Comment by niftylettuce** [comment]
@brentvatne I now get some weird archive error message... I can't submit a PR till I figure this out.  I wish there were clear instructions for this.

**Comment by niftylettuce** [comment]
![screen shot 2015-11-07 at 6 17 57 pm](https://cloud.githubusercontent.com/assets/523141/11017861/003af53c-857c-11e5-812a-bd9e53402871.png)

**Comment by niftylettuce** [comment]
Here's the error:
![screen shot 2015-11-07 at 6 18 59 pm](https://cloud.githubusercontent.com/assets/523141/11017862/0a38f214-857c-11e5-957a-ab857bc81277.png)

It's not an archive for some reason

**Comment by niftylettuce** [comment]
![screen shot 2015-11-07 at 7 03 01 pm](https://cloud.githubusercontent.com/assets/523141/11017997/30823600-8582-11e5-81e9-b4b284e18bba.png)

**Comment by niftylettuce** [comment]
https://github.com/facebook/react-native/pull/1979#issue-94795697

**Comment by niftylettuce** [comment]
https://medium.com/@DannyvanderJagt/how-to-use-push-notifications-in-react-native-41e8b14aadae

**Comment by niftylettuce** [comment]
Fixed it, I went into the XCode project for RCTPushNotifications, rebuilt it there after linking headers, and then went and rebuilt my main project. https://github.com/facebook/react-native/issues/1613#issuecomment-154769032

**Comment by krxsky** [comment]
I just had this issue and was able to fix it with the above comments but there was a gotcha for me...
for adding the header search path, I needed to add `$(SRCROOT)/../node_modules/react-native/Libraries/PushNotificationIOS` instead of `$(SRCROOT)/node_modules/react-native/Libraries/PushNotificationIOS` for my project to work. (My project was just updated to 0.14.2 from 0.12.0) 
Hope this helps

**Comment by shaikhussian** [comment]
@krxsky what you said is correct it is working for me, have you get any pushNotification alert and device token

**Comment by christopherdro** [comment]
Looks like RCTPushNotification.xcodeproj is excluded from the rest of the libraries when creating a new project? @ide @nicklockwood Is this intentional?

To get this to work on master I had to add the project files, binary under build phases, and `$(SRCROOT)/../node_modules/react-native/Libraries` to my projects header search path.

We can update the docs explaining this if the project has been intentionally left out.

**Comment by ide** [comment]
Let's update the docs.

**Comment by nicklockwood** [comment]
@christopherdro yes, it's intentional. Apple rejects apps for referencing certain APIs if they aren't used, and PushNotifications is one such API.
