### ISSUE TITLE
require.ensure support

### ISSUE THREAD

**Issue by guanyuxin** [facebook/react-native#3856]
The interface "require.ensure" have been removed since commit D2544415, so is the splitting bundle into multiple part feature still in development?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/requireensure-support

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
