### ISSUE TITLE
[Navigator] How can I change the swipe-back and swipe forward route?

### ISSUE THREAD

**Issue by elisei-timofte** [facebook/react-native#3860]
Hi @ericvicenti, I'm using navigator and I want to override the swipe functionality. Right know, when I swipe back it gets me to the last route from the stack (the normal behavior), but I want on swipe-back to do something else. Is this possible?

Thanks!

**Comment by willatthewindow** [comment]
Gestures that are detected by Navigator are part of the scene config.  You can manipulate the scene config by passing a `configureScene` prop https://facebook.github.io/react-native/docs/navigator.html#configurescene

It works just like `renderScene`, getting called once for each scene render except you return a scene config object instead of a component.  Start by looking at the existing scene configs and try overriding some of the properties to see how they work.

You'll be interested in the `gestures` property.  The value of the property is an object whose keys are the action that gesture will trigger and whose values are the descriptors of the gesture.  Unfortunately the only actions supported are `pop`, `jumpBack` and `jumpForward`.  So unless one of these is what you want to do you'll have to implement your own custom gesture recogniser (see https://facebook.github.io/react-native/docs/panresponder.html).

If you do implement your own gesture recogniser for swipe-left remember to disable the default `pop` gesture in Navigator by providing a scene config with an empty `gestures` object e.g.

````javascript
Object.assign({}, Navigator.SceneConfigs.FloatFromRight, {gestures: {}})
```

**Comment by elisei-timofte** [comment]
Thanks for explaining that. Now I know where to dig. I'll try and I'll come back with other questions if needed
