### ISSUE TITLE
frame drops(fps) while using ListView cell component with shadow style

### ISSUE THREAD

**Issue by xiekw2010** [facebook/react-native#3861]
frame drops(fps) while using ListView cell component with shadow style

```ruby
  shadowLine: {
    shadowColor: '#999999',
    shadowOpacity: 0.8,
    shadowRadius: 1,
    shadowOffset: {
      height: 2,
      width: 1
    },
  },
```

**Comment by kinhunt** [comment]
+1

**Comment by christopherdro** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

If you'd like you can create an issue on [Product Pains](https://productpains.com/product/react-native).
ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. 

Also, if this issue is a bug, please consider sending a PR with a fix. Thanks!
