### ISSUE TITLE
pod react in my own project

### ISSUE THREAD

**Issue by hahaGitHub** [facebook/react-native#3875]
hi,i have a question.
pod react in my own project.i use the RCTRootView.by the url ,I can get the view.but i meet a problem.
it is a warning. could you tell me why? thank you very much.
[warn][tid:com.facebook.React.JavaScript] 'devtools socket errored', { [Error: The operation couldn’t be completed. Connection refused]
line: 14510,
column: 39,
sourceURL: 'http://localhost/index.ios.bundle' }

in my browser,input the url,and then the url is normal.

**Comment by NixusCN** [comment]
In iPhone ? 
Or in simulator ?
If in iPhone, you need to change the ip in AppDelegate.m with the ip of your LAN

**Comment by satya164** [comment]
Hey and thanks for reporting this!

There's an awesome place to ask question like this one: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see your question, you can vote on answers and mark question as answered etc. This lets us keep a list of bug reports and feature requests on github and especially [Product Pains](https://productpains.com/product/react-native/?tab=top) (again, with voting which is really nice).

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)
