### ISSUE TITLE
Failed to establish session

### ISSUE THREAD

**Issue by huangzhiyang166** [facebook/react-native#3880]
Failed to establish session

**Comment by PhilippKrone** [comment]
@huangzhiyang166 Could you please give a little bit more detail concerning what/when/where/etc.?

**Comment by christopherdro** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

If you'd like you can create an issue on [Product Pains](https://productpains.com/product/react-native).
ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. 

Also, if this issue is a bug, please consider sending a PR with a fix. Thanks!
