### ISSUE TITLE
[Packager] dynamic requires

### ISSUE THREAD

**Issue by gajuro** [facebook/react-native#3882]
I really need a way to require json files dynamically.

As I read in the [docs](http://facebook.github.io/react-native/docs/image.html#static-resources) you deliberately made it so I have to write the file name for pictures. Does the same rule have to be applied to all file types?

**Comment by ide** [comment]
Anything that you want the build system to package up needs to be statically referenced. Client systems are different than Node in this regard because there's a preprocessing step when building the app.

If you need to load JSON files dynamically, you should use the networking APIs that RN offers and/or the native filesystem APIs to read the JSON.

**Comment by gajuro** [comment]
Hey Ide,

Thank you for your prompt answer.

Can you please point me to some docs about the native filesystem API? I don't see anything related in the APIs section of the docs.

I did find [another repo](https://github.com/johanneslumpe/react-native-fs) that seems to handle these needs. Is this what you meant in the first place?

**Comment by ide** [comment]
By native filesystem API I mean you'd bridge it yourself.
