### ISSUE TITLE
ios7.1.1: UIExplorer: Modal does't work correctly

### ISSUE THREAD

**Issue by nvcken** [facebook/react-native#3890]
I test on device iphone 5.
When click on button Present, the modal show on black background instead overlay
![12212203_422549201266883_18771498_n](https://cloud.githubusercontent.com/assets/3489866/10944958/2753c318-834e-11e5-9289-31c89faae112.jpg)

**Comment by nvcken** [comment]
ping

**Comment by SFantasy** [comment]
Hi @nvcken 

Got the same issue on iOS7. Any solution yet?

**Comment by kitt1987** [comment]
same issue here.

**Comment by nvcken** [comment]
@SFantasy 
not yet

**Comment by jsntghf** [comment]
same issue on iOS7.

**Comment by windylcx** [comment]
Got the same issue on iOS7. when i use a third-party picker lib which is implements with Modal,the problem occurs,and i try the modal with a empty project,just copy the code snippet in the docs,still the same. hope for a solution.

**Comment by akzhou** [comment]
Got the same issue on iOS7. Any solution yet?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/ios711-uiexplorer-modal-doest-work-correctly

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
