### ISSUE TITLE
Linking.openURL https://forms.gle/ will go back and forth between app and browser on Android

### ISSUE THREAD

**Issue by roadmanfong** [facebook/react-native#38918]
### Description

When I use Linking.openURL short url generated by google form on Android phone,
It will go to browser and back to app show a loading animation and got browser again, 
but iOS doesn't have this behavior

### React Native Version

0.70.5

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 13.5
    CPU: (8) arm64 Apple M1
    Memory: 162.13 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.0/bin/yarn
    npm: 9.8.0 - ~/.nvm/versions/node/v16.15.0/bin/npm
    Watchman: 2022.02.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.72.3 is now available (your project is running on v0.70.5).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.72.3
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.70.5
info For more info, check out "https://reactnative.dev/docs/upgrading".

### Steps to reproduce

On android device, Linking.openURL short url generated by google form

### Snack, screenshot, or link to a repository

https://snack.expo.dev/@steven.fong/google-form-short-link-issue-on-android

Here is the example movie
https://github.com/facebook/react-native/assets/2047789/b65b374a-a356-4007-bae2-a3ec3c8f0b57

**Comment by jakex7** [comment]
Hi!
I discovered that the issue isn't related to react-native. Instead, it originates from the `forms.gle` link itself. Even when you attempt to access the shortened link through the default messaging app, the outcome remains consistent, as demonstrated in the video below.  This is probably related to the fact that the `forms.gle` link is a `Firebase DynamicLink` instead of a regular URL.
I hope I've clarified things a bit. @roadmanfong if you'd like to eliminate this redirection, you need to utilize a regular, unshortened link.


https://github.com/facebook/react-native/assets/39670088/ad75f721-3447-4358-9adc-67b13339037d

**Comment by roadmanfong** [comment]
Got it. thanks for explanation
