### ISSUE TITLE
SwitchIOS and SwitchAndroid Styling

### ISSUE THREAD

**Issue by niftylettuce** [facebook/react-native#3894]
How can we style the border of a SwitchIOS?  See below -- how can I style that black border?

![screen shot 2015-11-04 at 12 44 28 pm](https://cloud.githubusercontent.com/assets/523141/10946729/e3a54b66-82f1-11e5-894f-b1ccbb6c9528.png)

Also, how come there is no styling props for SwitchAndroid?

**Comment by christopherdro** [comment]
Looks like styling for Android isn't supported at the moment.

For styling the border on IOS you need to set the `tintColor` prop.
More information inside the docs: 
https://facebook.github.io/react-native/docs/switchios.html#tintcolor

Please remember to close this issue if it solves your problem. Thanks!

**Comment by christopherdro** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

If you'd like you can create an issue on [Product Pains](https://productpains.com/product/react-native).
ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. 

Also, if this issue is a bug or a feature request, please consider sending a PR. Thanks!
