### ISSUE TITLE
Warning: Failed propType: Invariant Violation: Invalid prop `type` of value `ThemeAttrAndroid`

### ISSUE THREAD

**Issue by pyadav** [facebook/react-native#3904]
I am getting this error in android project  Seem like an error

'Warning: Failed propType: Invariant Violation: Invalid prop `type` of value `ThemeAttrAndroid` supplied to `TouchableNativeFeedback`, expected one of ["RippleAndroid"].\nBad object: {\n  "type": "ThemeAttrAndroid",\n  "attribute": "selectableItemBackground"\n} Check the render method of `TouchFeedback`.'

**Comment by KeithZhang** [comment]
as the warning says, just add a background props,like this: background={TouchableNativeFeedback.Ripple()}, the waining disappear

**Comment by baoti** [comment]
`PropTypes.oneOfType` couldn't work with checkers which throws Error.(https://github.com/facebook/react-native/blob/f2545bafc967661beeefc3778c06532982a6addc/Libraries/Components/Touchable/TouchableNativeFeedback.android.js#L37)

[createStrictShapeTypeChecker](https://github.com/facebook/react-native/blob/62e8ddc20561a39c3c839ab9f83c95493df117c0/Libraries/Utilities/createStrictShapeTypeChecker.js#L73) checker should return `Error` instead of throw `Error`.

**Comment by cspkop** [comment]
@KeithZhang Thanks!
Replacing the  background={TouchableNativeFeedback.SelectableBackground()}  with background={TouchableNativeFeedback.Ripple()} removes the warning.

**Comment by satya164** [comment]
@ide @mkonicek Is the warning necessary? There is a already a default value set to `TouchableNativeFeedback.SelectableBackground()`.

@cspkop Note that using `TouchableNativeFeedback.Ripple()` will crash your app below Android 5.0.

**Comment by baoti** [comment]
There is a bug to combine `PropTypes.oneOfType` with `createStrictShapeTypeChecker`.

**Comment by cspkop** [comment]
@satya164 Then how we can get rid of this warning?

**Comment by satya164** [comment]
@cspkop For now you can ignore it. It doesn't do any harm.

**Comment by satya164** [comment]
@cspkop For now you can ignore it. It doesn't do any harm. In my app, I've done the following,

```
import React from "react-native";

const {
	TouchableNativeFeedback,
	TouchableHighlight,
	Platform
} = React;

export default class TouchFeedback extends React.Component {
	render() {
		if (Platform.OS === "android" && Platform.Version >= 23) {
			return (
				<TouchableNativeFeedback {...this.props} background={TouchableNativeFeedback.Ripple(this.props.pressColor)}>
					{this.props.children}
				</TouchableNativeFeedback>
			);
		} else {
			return (
				<TouchableHighlight {...this.props} underlayColor={this.props.pressColor}>
					{this.props.children}
				</TouchableHighlight>
			);
		}
	}
}

TouchFeedback.propTypes = {
	pressColor: React.PropTypes.string,
	children: React.PropTypes.node.isRequired
};
```

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/warning-failed-proptype-invariant-violation-invalid-prop-type-of-value-themeattrandroid

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
