### ISSUE TITLE
React Native production ready?

### ISSUE THREAD

**Issue by pkamenarsky** [facebook/react-native#3907]
We're currently in the process of evaluating different cross-platform mobile frameworks.

Seeing that this repository has over 700 open issues, how production ready is React Native really (both on iOS and Android?)

**Comment by ide** [comment]
If your team members have a go-getter attitude and the engineering skills to do iOS and Android development anyway, then I would recommend prototyping with RN to evaluate it further. A couple tips I have are: read the source code when something is unclear, build your own native components when they aren't already implemented, and go into RN with the understanding that it is not the DOM nor Cocoa/Android and you will have to learn a new technology that has different strengths and weaknesses. If those tips seem alright to you & your team then I'd say you have the right mindset to be successful with RN. I thought this post lent good perspective as well: https://medium.com/ios-os-x-development/an-ios-developer-on-react-native-1f24786c29f0

**Comment by brentvatne** [comment]
I agree with @ide and would add also:

- a significant number of the open issues are actually questions (eg: this issue, or "how do i do x?") and troubleshooting (eg: error running packager on windows, can't get watchman to run, etc).
- read the [React Native ProductPains](https://productpains.com/product/react-native/) list for a good idea of where people are having the biggest issues right now instead of Github issues.
- iOS is further along than Android, but Facebook has released apps powered entirely by React Native on both platforms, as have many other companies (see: https://facebook.github.io/react-native/showcase.html)

I would also suggest looking at what apps have been built with the cross-platform tools that you're evaluating, try them out and see which ones are closest to what you want. Try to make a simple app in each and see which best suits your needs.
