### ISSUE TITLE
TextInput is missing in ScrollView in iOS but not in Android

### ISSUE THREAD

**Issue by yychun1217** [facebook/react-native#3910]
My TextInput is missing inside ScrollView for iOS. It works fine on android.
Included is the sample app using Playground.

https://rnplay.org/apps/KtTZ2g

You could see that android is showing the TextInput, but the iOS's one does not show it.

These kind of bugs is making me crazy...

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/textinput-is-missing-in-scrollview-in-ios-but-not-in-android

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
