### ISSUE TITLE
AnimatedScrollView error

### ISSUE THREAD

**Issue by G-Ri-F** [facebook/react-native#3911]
The following code throw exception

    var AnimatedScrollView = Animated.createAnimatedComponent(ScrollView) 
	var Catalog = React.createClass({
		render: function() {
			return (
					<AnimatedScrollView contentOffset={{x:0,y:new Animated.Value(0)}}>
					</AnimatedScrollView>
			)
		},
	})
exception

    JSON value '{
	    "_animation" = "<null>";
	    "_children" =     (
	    );
	    "_listeners" =     {
	    };
	    "_offset" = 0;
	    "_value" = 0;
	}' of type NSDictionary cannot be converted

**Comment by brentvatne** [comment]
Animated is only supported on styles currently. cc @lelandrichardson

**Comment by browniefed** [comment]
Technically not on only styles, just on anything that is simple value. It will not traverse array/objects to find animated values

**Comment by lelandrichardson** [comment]
one thought here is if we could augment the `createAnimatedComponent` API to allow you to select props that are animate-able:

```
var AnimatedScrollView = Animated.createAnimatedComponent(ScrollView, { contentOffset: true });
```

I haven't dug into it, but I think that API is likely not giving us enough information... but something like this might:

```
var AnimatedScrollView = Animated.createAnimatedComponent(ScrollView, { 
  getAnimatedProps(props) {
    return {
      contentOffset: {
        x: props.contentOffset.x,
        y: props.contentOffset.y.__getValue(),
      },
    };
  },
});
```

This would likely allow us to extend the animated props of certain components beyond style, and having to have a new constructor for every type of animated prop.

cc @vjeux

**Comment by lelandrichardson** [comment]
you could also define `getAnimatedProps` as a static method on the component and have the API look for that by default...

**Comment by browniefed** [comment]
I think it'd be nice to be able to define our own custom Animated values that can return arbitrary values. So in our case we could create a new type of `Animated.Value` that when requested would return an object. That way when the Animated component traverses all props it would find it, and we wouldn't have to call out specific props for animation.

**Comment by vjeux** [comment]
FYI, I'm in parental leave for 2.5 months so I'm unlikely going to work on this, but I like where this discussion is going, I can't wait to see prototypes to figure out which is the best :)

**Comment by browniefed** [comment]
Technically we would only need to export `AnimatedWithChildren`, then the user would need to implement the private methods like `__getValue`, `__getAnimatedValue`, `__attach`, and `__detach`. To make it easier could probably just expose a `createAnimatedValue` on the `Animated` object and it could take the values `getValue`, `getAnimatedValue`, `attach`, and `detach` and anything else necessary and return the ability to have anything be an Animated value?

**Comment by lelandrichardson** [comment]
I had to do a similar thing for getting animated values to work with the map component:

https://github.com/lelandrichardson/react-native-mapview/blob/master/components/AnimatedRegion.js

exporting `AnimatedWithChildren` would definitely allow people to extend to create more of their own... i think additional changes, potentially to the `Animated.createAnimatedComponent` would also be needed in order to really let people take advantage of the API.

The big thing is we have to make sure that any newly exposed public APIs wouldn't hinder the eventual goal of getting the Animated API to be offloaded to a high-priority native thread.

**Comment by vjeux** [comment]
We should include @kmagiera who's working on running Animated off of the js thread and see how this would impact his work.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/animatedscrollview-error

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
