### ISSUE TITLE
TranformMatrix strange behavior

### ISSUE THREAD

**Issue by WellDone2094** [facebook/react-native#3919]
I'm trying to use transform matrix to modify an Image, i can't use just transform because i want to use the translate Z which is missing. The problem is that i can't get it work, i'm trying to use this matrix
```
[1, 0, 0, 200,
 0, 1, 0, 100,
 0, 0, 1, 0,
 0, 0, 0, 1]
``` 
that should be the same as 
```
transform: [
{translateX: 200},
{translateY: 100}
]
```
 but i get a huge blinking yellow thing that should be my image since is the same yellow but the sape of the yello thing is not like my image. i think there is some problem with the Z coordinate but i tried to translate z by -100 and +100 and nothing changes.

**Comment by WellDone2094** [comment]
Doing other test i discovered that the problem is only with the translation. If i use rotation and scale matrix there are no problems but as soon i use translation on x or y axis the result is not correct

**Comment by mangogogos** [comment]
Out of curiosity what platform are you working on?

**Comment by WellDone2094** [comment]
i'm working on iPhone 5s with iOS 8.1.2

**Comment by xwenliang** [comment]
i'm run into the same question

**Comment by sairion** [comment]
I'm dealing with some animation using z axis and overall impression is react native does not have good way to represent z axis.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/tranformmatrix-strange-behavior

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
