### ISSUE TITLE
Flexbox does not work if a parent size is determined by child dimensions

### ISSUE THREAD

**Issue by jjshammas** [facebook/react-native#3929]
I have noticed that if:

- A parent element does not have an explicit width/height
- AND A child element (such as a text layer) determines the width and height of that parent

…then all flex box properties (such as centering or growing) completely break on both the parent and its children.

This has forced me to attach functions to the `onLayout` prop and place explicit widths/heights on the parent when React calculates its size.

Is this by design? I am running into this issue nearly every day.

**Comment by grabbou** [comment]
Could you provide a React Native Playground example with reproduced issue? Thanks!

**Comment by hufeng** [comment]
maybe it's a bug. https://github.com/facebook/react-native/issues/1234

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/flexbox-does-not-work-if-a-parent-size-is-determined-by-child-dimensions

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
