### ISSUE TITLE
How to dynamically create config file based off NODE_ENV flag?

### ISSUE THREAD

**Issue by niftylettuce** [facebook/react-native#3936]
If I were to run `npm run bundle` and bundle my app (e.g. via `react-native bundle`), then I would like my API endpoint to switch to the production endpoint in my code.  My API endpoint is defined in a helper function which in turn uses ES6's `fetch` function.

Right now I'm having to comment/uncomment the production and development domain names in the definition, for example:

```js
let endpoint = 'https://api.myserver.com';
// let endpoint = 'http://localhost:3000' ;
```

Is there a dynamic way to configure this?  E.g. have some file be dynamically generated on boot?  I'm using webpack and react-native-webpack-server as well.

**Comment by ide** [comment]
This isn't a completely generalized solution and nor does it make use of NODE_ENV... but might address your specific use case: there's a special variable called __DEV__ that gets set based on whether you load the bundle with ?dev=true or ?dev=false. When bundling up your JS you'd typically use dev=false (in fact that might be enforced.. would have to read the code).

**Comment by niftylettuce** [comment]
How do I access this variable?  `global.DEV`?

**Comment by ide** [comment]
It's a global, just `__DEV__` (`global.__DEV__ might also work but different static analyzers in the JS ecosystem might not like `global`)

**Comment by niftylettuce** [comment]
What's the road map for dynamically generating this?   What if I want other
configurations?

**Comment by niftylettuce** [comment]
Also thank you @ide - I was able to get it working for now using `__DEV__`.  :+1:

**Comment by ide** [comment]
Roadmap-wise: my gut thought is that Babel 6 is the answer. With .babelrc you can load any plugin you want, which lets you hack on the AST pretty arbitrarily.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/how-to-dynamically-create-config-file-based-off-nodeenv-flag

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
