### ISSUE TITLE
[Navigator] Top scene always forces sub-scenes to 0 opacity

### ISSUE THREAD

**Issue by cjbell** [facebook/react-native#3964]
I'm trying to implement a modal scene, triggered by pushing a scene to a `Navigator` and using the `FloatFromBottom` SceneConfig to make it appear as a modal (as per the docs, being the recommended approach). Now that works fine for all situations where you'd like the modal to occupy 100% of the screen height / width, but for modals where you'd like the scene beneath to still be visible this is currently not possible.

Here's a video example to illustrate what's currently happening:
https://www.dropbox.com/s/sd82or6umlzo654/rn-scene-opacity-420.mov?dl=0

I've dug through the Navigator code, and I can see that when the transition has finished there's a call made to `_hideScenes` which calls `_disableScene` on every scene loaded and forces the style to have an opacity of 0 through `SCENE_DISABLED_NATIVE_PROPS `. You can see this here: https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/Navigator/Navigator.js#L527-L528

I believe there's a valid use-case here of not wanting to always hide the last scene, but currently this is not possible as these props are forced. I'm also aware there are other ways to implement this behavior, but I'd rather rely on the already written transition animations and management that Navigator provides rather than implementing custom open / close animations etc. I can also see others running into this issue, especially as iOS is using more of these style views.

In my mind, it would be perfect to be able to do this in the `SceneConfig` itself, but I'm totally open to other suggestions and would love to hear opinions before trying to resolve this and PR it myself.

Thanks very much and let me know if you'd like more detail.

**Comment by ide** [comment]
cc @ericvicenti @hedgerwang

**Comment by rileybracken** [comment]
Any updates on this?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/navigator-top-scene-always-forces-sub-scenes-to-0-opacity

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
