### ISSUE TITLE
Rounded Image with stretch mode doesn't work

### ISSUE THREAD

**Issue by inithink** [facebook/react-native#3967]
I'm trying to make a circular image with a resized (stretch) image.

It seems 'borderRadius' doesn't work when it used with resizeMode.

Here is the code
```
<Image source={require('./image/main.jpg')}
    resizeMode={Image.resizeMode.stretch}
    style={{width: 50, height: 50, borderRadius: 25}}
/>
```

**Comment by yychun1217** [comment]
maybe you could surround the image with a view, and style the view's borderRadius instead of the image's

**Comment by inithink** [comment]
The result is same too.
It overflow parent's view...

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/rounded-image-with-stretch-mode-doesnt-work

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by xavieramoros** [comment]
Just in case it helps, it's working in my case. 

I have an image (within another view also with rounded corners) that uses resizemode "stretch".  
Using borderRadius works but being specific about which border, using borderBottomRightRadius, doesn't

My view:
```
      <View style={[styles.shade]}>
        <Image style={[styles.shadeImage]} 
              source={require("../img/portada_degradat_curt.png")} 
              defaultSource={require("../img/portada_degradat_curt.png")} 
              resizeMode={'stretch'} />
      </View>

```
Styles:
```
  shade: {
    position: 'absolute',
    bottom: 0 
    right: 0
    left: 0
    borderBottomLeftRadius: radius, 
    borderBottomRightRadius: radius,
  },
  shadeImage: {
    height: 250, 
    transform: [{ rotate: '180deg'}],
    borderRadius: 15,

    /* Specific radius doesn't work:
    borderBottomRightRadius: 15,
    borderBottomLeftRadius: 15,
    borderTopRightRadius: 15,
    borderTopLeftRadius: 15,
    */
    
  },

```

RN: 0.48.8
Tested in iOS
