### ISSUE TITLE
Following Example steps leads to Error consistently

### ISSUE THREAD

**Issue by Tom-E** [facebook/react-native#3970]
If I follow the example steps provided in README.md (clone, cd, npm install, run any .xcodeproj in Examples) I hit the following error about Invariant Violation: EventPluginRegistry: Cannot inject event plugin ordering more than once. You are likely trying to load more than one copy of React.

![screen shot 2015-11-06 at 10 39 59 pm](https://cloud.githubusercontent.com/assets/708952/11013961/56c2ea68-84d7-11e5-8366-59532bf2aaf2.png)

**Comment by liuyaodong** [comment]
I have encountered the same issue today, when I cloned the latest version of this project. However, it worked perfectly 3 days ago.

**Comment by mbrock** [comment]
I also have this problem with the current master (0bcd01e5c4c45068cdedbd3ede071283a77eb894). I'm going to try to bisect it.

**Comment by alliemeng** [comment]
Confirmed, cloning 66f7fed works

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/following-example-steps-leads-to-error-consistently

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
