### ISSUE TITLE
Assets with spaces don't work

### ISSUE THREAD

**Issue by malkomalko** [facebook/react-native#3985]
It looks like the new asset system replaces spaces with the encoded %20 when trying to require.

**Comment by ide** [comment]
cc @frantic

**Comment by mosesoak** [comment]
+1 on this. Eager to convert an existing project with lots of images. Please post any workarounds here as well.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/assets-with-spaces-dont-work

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
