### ISSUE TITLE
[NavigatorIOS] [Request] Make it easy to update `navigationBarHidden`

### ISSUE THREAD

**Issue by erdostom** [facebook/react-native#3987]
Please move this from a prop to an attribute on the `route`, as suggested in the 2nd answer here:

https://stackoverflow.com/a/32602546

Had to resort to this after several hours of setState -> render -> loops.

Thank you very much.

**Comment by browniefed** [comment]
@facebook-github-bot label Community Responsibility

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/navigatorios-request-make-it-easy-to-update-navigationbarhidden

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
