### ISSUE TITLE
Using 'require' inside injectedJavaScript attribute on WebView component does not work

### ISSUE THREAD

**Issue by tomkur** [facebook/react-native#4000]
I am using WebView component to render some content unavailable easily in native environment (namely high quality charts). I am using Browserify to manage dependencies in WebView. I would like to inject JavaScript when the page loads and properly use 'require' to avoid globals. I have following component definition:
```xml
<!-- omitting other attributes for brevity --> 
<WebView
  url='webview/html/chart.html'
  injectedJavaScript="require('chart').callSomeMethod()"
/>
```

I get the following error:

```
Error while loading: Unable to resolve module chart from /Users/tomkur/react-apps/Charts/js/components/Chart.js: Invalid directory /Users/node_modules/chart
```

When I move the JS to `<script>` tag in `chart.html` the problem is gone, but I don't want to do that (I would like `chart.html` to serve as a template for different rendered charts)

I think the reason is that RN scans my JS file in search for 'require' to build dependency tree and it ignores the fact that this occurrence is within string attribute and should be passed through to html without preprocessing.

**Comment by ide** [comment]
Can you try `require.call(null, 'chart').callSomeMethod()` to verify that it is a false positive with the RN static analyzer?

**Comment by tomkur** [comment]
It works just fine when calling either:
1. `require.call(null, 'chart').callSomeMethod()`
2. or `const r = require; r('chart').callSomeMethod()`

So it's probably a false positive with the analyzer. The workaround you provided is good enough for me for now, but it would be nice to have clean solution anyway.

Great thanks for your help!

**Comment by ide** [comment]
Thanks for investigating! Looks like there is a bug here. cc @martinbigio

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/using-require-inside-injectedjavascript-attribute-on-webview-component-does-not-work

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
