### ISSUE TITLE
[Android] How use expansion files with react native?

### ISSUE THREAD

**Issue by liesislukas** [facebook/react-native#4020]
Hi, 

Building app with 600+ images. Apk file size is ~450MB. Google Play limits upload up to 100MB, only option is to use apk expension files. 

http://developer.android.com/google/play/expansion-files.html

What is best way to use those with react?

**Comment by satya164** [comment]
Hey and thanks for reporting this!

There's an awesome place to ask question like this one: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see your question, you can vote on answers and mark question as answered etc. This lets us keep a list of bug reports and feature requests on github and especially [Product Pains](https://productpains.com/product/react-native/?tab=top) (again, with voting which is really nice).

If you think StackOverflow works for you please consider posting there instead and closing this issue.

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)
