### ISSUE TITLE
[android] upgrade to latest okhttp version

### ISSUE THREAD

**Issue by jaredly** [facebook/react-native#4021]
2.5.0 was released in August, superceding 2.4.0 (which react-native depends on) which was released in May
Is this as simple as a change to the gradle deps file? As a point release, it shouldn't™ be backwards incompatible

**Comment by ide** [comment]
cc @kmagiera (and @mkonicek if you're not on PTO yet)

**Comment by kmagiera** [comment]
Thanks for reporting, I've upgraded gradle config in caf111e

**Comment by christopherdro** [comment]
Update: 
 Looks like 3.1.2 is the latest stable release. Also, they changed the maven group to `okttp3` to reflect the new version. See: https://github.com/square/okhttp/pull/2118

@kmagiera Thoughts on upgrading? Seems like there have been a good amount of improvements made. https://github.com/square/okhttp/blob/master/CHANGELOG.md

**Comment by AndrewJack** [comment]
Started some work to upgrade to v3. However the Facebook team had some [concerns](https://github.com/facebook/react-native/pull/6113#issuecomment-188185464).

- Updating to v3 will boat apps still using OkHttp 2 (May switch later on)
- Updating to 2.7.4 would break for anyone relying on 2.5 or earlier - due to some web socket API changes in 2.6.
- The package name change between v2 and v3 helps by not breaking existing versions of OkHttp 2

**Comment by aoriani** [comment]
A concern that I have is that React-Native imposes a certain version of OkHttp to the hosting app. That is particularly bad for existing apps that are already using OkHttp and want to use  React-Native to implement some new functionality.  In my particular case  we use OkHttp 2.7.4 whereas React-Native 0.20 uses 2.5.0.  As noticed above there's some incompatibility between those two OkHttp 2.x versions. 

One could say that I could just downgrade to 2.5. and be happy, but that is not desirable. Most of the features of my app rely on network, making OkHttp a vital library for our app. And as such, it is very important that I should be able to pick its version. If some critical bug or security is found, I want to be able to quickly upgrade OkHttp. However in the current situation I am tied to whatever version is defined by React-Native. 

Is there any plans to solve the strict version dependency to OkHttp or to a particular network library?. I would think that people using pure Volley would not like to add a new networking library to bloat their APK.  That could be a barrier to for existing apps to adopt React-Native.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-upgrade-to-latest-okhttp-version

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
