### ISSUE TITLE
stateless function components don't work

### ISSUE THREAD

**Issue by jaredly** [facebook/react-native#4023]
There's an error about the component being a frozen object that can't be modified. I'll try to get a stacktrace here

this is version 0.14.0

**Comment by skevy** [comment]
@jaredly This commit which is not yet released -- https://github.com/facebook/react-native/commit/bbee3c6f60c1ab2ff0d8c49ab3ae18d6760e647b -- brought React 0.14 up to date. Previously it was using an old beta1 version of 0.14.

If you try with master...does it work as expected?

**Comment by ide** [comment]
AFAIK RN isn't quite yet on React 0.14 but is ready to be once the Flow infrastructure can handle it. Sometime this week or next was the estimate IIRC?

**Comment by skevy** [comment]
@ide it's not fully on React 0.14 so that you can do something like `require('react')`...but the underlying lib  SHOULD be a full version of React 0.14 now (after that commit I linked to above), with some hacky overrides here and there. AFAIK things like stateless components should work as of that commit. But @jaredly let me know if I'm wrong! :)

**Comment by ide** [comment]
Oh snap. That's awesome.

**Comment by chandu0101** [comment]
with rn 0.15.0-rc i am getting following error 

<img width="368" alt="screen shot 2015-11-13 at 9 39 47 am" src="https://cloud.githubusercontent.com/assets/2179670/11138627/add2ba3c-89ea-11e5-9f56-2db493b331c1.png">

**Comment by admmasters** [comment]
@chandu0101 same issue here.

**Comment by chandu0101** [comment]
they're working fine in 0.16.0-rc with one exception! (#4380)

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/stateless-function-components-dont-work

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
