### ISSUE TITLE
Making own EventPlugin possible / events bubbling

### ISSUE THREAD

**Issue by aichi** [facebook/react-native#4040]
Hi,
  I was hitting the issue in events bubbling. Imagine two touchable highlights wrapped to each other. There is only 'shouldSet' event bubbling but when some component declares concern others don't receive that touch event anymore. This is so restrictive and behaving differently than on Web.

I was thinking about making own EventPlugin which will not be so restrictive but I hit the issue with registering. EventPluginHub is prepared for multiple plugins pretty well except for later registering. 

Hackish way is this:

```
var EventPluginHub = require('EventPluginHub');
var SyntheticEvent = require('SyntheticEvent');
var EventPluginRegistry = require('EventPluginRegistry');
var IOSDefaultEventPluginOrder = require('IOSDefaultEventPluginOrder');
var ResponderEventPlugin = require('ResponderEventPlugin');
var IOSNativeBridgeEventPlugin = require('IOSNativeBridgeEventPlugin');

var extractEvents = (topLevelType, topLevelTarget, topLevelTargetID, nativeEvent, nativeEventTarget) => {
    return SyntheticEvent.getPooled(null, topLevelTargetID, nativeEvent, nativeEventTarget);
};

var X = {
    extractEvents: extractEvents
};
IOSDefaultEventPluginOrder.push('X');
EventPluginRegistry._resetEventPlugins();
EventPluginHub.injection.injectEventPluginOrder(IOSDefaultEventPluginOrder);
EventPluginHub.injection.injectEventPluginsByName({
    'X': X,
    'ResponderEventPlugin': ResponderEventPlugin,
    'IOSNativeBridgeEventPlugin': IOSNativeBridgeEventPlugin
});
```

Or am I missing something and I can have multiple responders getting the same touch event at same time like on web?

**Comment by aichi** [comment]
We are hitting this in real life when we try to have TouchableHighlight (TouchableMixin) around PanResponder. It works vice versa but not this way. I thought that it would work if I return false from onStartShouldSetPanResponder and true from  onMoveShouldSetPanResponder but it doesn't.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/making-own-eventplugin-possible-events-bubbling

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
