### ISSUE TITLE
[Android] Touch timestamp key different from iOS

### ISSUE THREAD

**Issue by scottlangendyk** [facebook/react-native#4046]
As demonstrated here https://rnplay.org/apps/batXmQ

The key for timestamps on touch events is "timeStamp" on android and "timestamp" on iOS. If the documentation is to be taken as the source of truth, then the iOS name is correct.

**Comment by christopherdro** [comment]
Will try and go this sometime today if I can.

**Comment by msathis** [comment]
@christopherdro https://github.com/facebook/react-native/blob/fa884ee5e656b8cb03d000d49f1b1456a7b21784/ReactAndroid/src/main/java/com/facebook/react/uimanager/events/TouchesHelper.java#L27 
Is this the place to change? I can submit a PR, if you haven't done it already.

**Comment by christopherdro** [comment]
@msathis I haven't had a chance to take a look yet but that looks right to me.

cc @kmagiera and @mkonicek

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-touch-timestamp-key-different-from-ios

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
