### ISSUE TITLE
[Android]About onresume event

### ISSUE THREAD

**Issue by TanTan-TT** [facebook/react-native#4048]
When Android app is resumed, I want to do some check. So right now I cannot subscribe an event from js code.

**Comment by marsprince** [comment]
+1 my android app broken because of onresume

**Comment by christopherdro** [comment]
@mkonicek What do you think about adding 
```
mCurrentReactContext
  .getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class)
  .emit("event", null);
```
 `onResume` and `onPause` in [ReactInstanceManagerImpl.java](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/ReactInstanceManagerImpl.java)?

Just tested it real quick and it seems to work.

**Comment by bodyflex** [comment]
+1

**Comment by richarddewit** [comment]
+1

**Comment by richarddewit** [comment]
@christopherdro - I tried implementing that piece of code (with `'onResume'` and `'onPause'` instead of `'event'`) in ReactInstanceManagerImpl.java to `onResume` and `onPause`, and listening to them via [DeviceEventManagerModule ](https://facebook.github.io/react-native/docs/native-modules-android.html#sending-events-to-javascript) but I can't get them to fire..

When I listen to `toggleElementInspector` (it's in the same file) and open the inspector, it does fire.

**Comment by satya164** [comment]
Closing as Android has AppState now - https://github.com/facebook/react-native/commit/1b7d7b0a78484bda82618246dab34f5d554464ba
