### ISSUE TITLE
Generating a signed apk gives me WhiteScreen

### ISSUE THREAD

**Issue by BigPun86** [facebook/react-native#4051]
If i follow the instructions on the React Native Site [Generate Signed APK](https://facebook.github.io/react-native/docs/signed-apk-android.html) my apk file which i have generated won´t work. I have followed exactly all the instructions but as soon as i install the apk on my device or emulator it shows me a white screen...
Did somebody experience the same issue? I am running on RN 0.14.2

**Comment by felipebueno** [comment]
Hi, @BigPun86. Did you run this commands before ```assembeRelease```?
```
$ mkdir -p android/app/src/main/assets

$ react-native bundle --platform android --dev false --entry-file index.android.js \
  --bundle-output android/app/src/main/assets/index.android.bundle \
  --assets-dest android/app/src/main/res/
```

I ask you because I always forget :smile:

**Comment by BigPun86** [comment]
Yes i did. But i mostly forget that too 😀 now it works After i downgraden to 0.13 

Gesendet mit TypeMail

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/generating-a-signed-apk-gives-me-whitescreen

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by francisrod01** [comment]
@felipebueno this solution is good but it not solved to me.
I running this code as `development` and works fine! but as `production` I continue seen white screen event with a `<ActiveIndicator />` component loading before async call from axios and external API.

**Comment by vijaya06** [comment]
i also have this error please help me!
