### ISSUE TITLE
Some NPM packages don't work

### ISSUE THREAD

**Issue by bmcmahen** [facebook/react-native#406]
I've come across a few npm modules that don't appear to work correctly. Notably, [event-emitter](https://www.npmjs.com/package/event-emitter) has issues importing `es5-ext/object/assign`, and [debug](https://github.com/visionmedia/debug) doesn't appear to work with the chrome dev-tools. I suspect that small alterations to the module themselves (to take into account yet another working environment) may be necessary, but there could also be issues with the packager, too.

**Comment by NovaDev94** [comment]
I can't get it work with `lodash` too.

`var _ = require('lodash');` and `var lodash = require('lodash');` both return an empty object.

Take a look at the `bundle` file generated by packager, the code for `lodash` is there.

**Comment by jgable** [comment]
I've also had a hard time getting some modules to work.  I was able to get lodash to work by using the `lodash-node` version. But, things like Backbone are not.

It looks like the packager thinks the exported function is a factory for creating the module, but the factory (in lodash) is not actually detecting a node environment and instead the export ends up being undefined.

I'll keep digging in the bundle and report if I find anything useful.

**Comment by nicinabox** [comment]
I had to use the lodash-cli to build a node version for React: `lodash exports=node`

**Comment by jgable** [comment]
It looks like, at least in the case of backbone (and probably regular underscore/lodash), that it checks for a [`define && define.amd`](https://github.com/jashkenas/backbone/blob/master/backbone.js#L11) to determine whether to use AMD versus commonJS style exports.

Why does the packager set `define.amd` if it's preferring commonJS exports?  Is it just because that's what the polyfill had initially?  Can we remove that?

I guess, the follow up question would be, if we do allow AMD style defines, why aren't they working for lodash, et. al.

**Comment by jgable** [comment]
@nicinabox The `lodash-node` package on npm should work for you without making a custom build; at least it has for me so far.  `npm install lodash-node --save` and then `var _ = require('lodash-node');`.

**Comment by nicinabox** [comment]
I think [it's been deprecated](https://github.com/lodash/lodash-node#deprecated) though.

**Comment by jgable** [comment]
When I comment out this [`define.amd = {}`](https://github.com/facebook/react-native/blob/master/packager/react-packager/src/DependencyResolver/haste/polyfills/require.js#L595) I am able to load lodash and backbone (well, backbone is a little trickier because it depends on underscore) without a problem.

**Comment by vjeux** [comment]
For the amd issue, here's our code responsible for it. https://github.com/facebook/react-native/blob/master/packager/react-packager/src/DependencyResolver/haste/polyfills/require.js#L597 I'm unsure why we define this global.

**Comment by vjeux** [comment]
Woops @jgable beat me to it!

**Comment by siuying** [comment]
package [he](https://github.com/mathiasbynens/he) shows same issue.

```javascript
	// Some AMD build optimizers, like r.js, check for specific condition patterns
	// like the following:
	if (
		typeof define == 'function' &&
		typeof define.amd == 'object' &&
		define.amd
	) {
		define(function() {
			return he;
		});
	}	else if (freeExports && !freeExports.nodeType) {
		if (freeModule) { // in Node.js or RingoJS v0.8.0+
			freeModule.exports = he;
		} else { // in Narwhal or RingoJS v0.7.0-
			for (var key in he) {
				has(he, key) && (freeExports[key] = he[key]);
			}
		}
	} else { // in Rhino or a web browser
		root.he = he;
	}
```

**Comment by danibal** [comment]
I have the same issue with `async`,

`var async = require('async');
console.log(_);// {}`

**Comment by amasad** [comment]
fixed via #581 will publish v0.3.2 soon

**Comment by broonage** [comment]
Naive question alert, but why not support AMD?

**Comment by vjeux** [comment]
@broonage: we're building a new js environment (others are browser, web worker, node) and need to figure out what we support. We want to support as few things as possible so that it is easier to maintain and has less bugs overall. It turns out that the community pretty much settled on commonjs and not AMD so this is what we chose to implement. Having two things to do the same thing is usually not a great idea.

If in the future AMD makes a big comeback and there are big incentives to implement it, we could. But trying to keep it as simple as possible for now :)

**Comment by broonage** [comment]
@vjeux: Thanks, good to know. I'm trying to re-use some existing web modules in a project which use AMD (define), so I have to edit all the files so they are working with require() calls and module.exports=CoolReactNativeModule. I guess no other way about it. :)
Thanks again.

**Comment by vjeux** [comment]
@cpojer would suggest you to write a codemod for this :p
