### ISSUE TITLE
Packager is required to live in node_modules of app

### ISSUE THREAD

**Issue by allenhartwig** [facebook/react-native#408]
When working on a react-native fork, it is desirable to have your apps symlink to your repo directory rather than each app having their own instance of react-native in node_modules. Currently this is not supported by packager, as it assumes that the directory's physical location is within the projects node_module folder.

https://github.com/facebook/react-native/blob/master/packager/packager.js#L49-L55

**Comment by amasad** [comment]
Do you have any suggestion on what the best way to handle this?

**Comment by sahrens** [comment]
Can you run the packager manually from your fork with --root <path/to/project>?

**Comment by allenhartwig** [comment]
@sahrens starting packager.sh with --root does work. @amasad thoughts on starting packager with `npm run start -- <project dir>`  rather than `npm start` and have package.sh relay the parameter as --root to packager.js? This way nothing is inferred and allows react-native's location to be completely independent of the app project.

**Comment by sahrens** [comment]
It's preferred that each project has its own copy of the packager in node_modules for typical development so you don't have to worry about versioning between libs. 

This doesn't really work with multiple React Native projects yet since the packager runs continuously on the same port, but there is discussion of adding a status endpoint so you could kill a currently running packager if it reports the wrong version via status and start the right one for that project automatically.

**Comment by allenhartwig** [comment]
I've resolved this issue by creating a `start.sh` file in my app root, changing my `package.json` in my app root to utilize it for `npm start` and in `start.sh` I have the following:

```bash
THIS_DIR=$(dirname "$0")
node_modules/react-native/packager/packager.sh --root $THIS_DIR
```
