### ISSUE TITLE
new asset system crashes bundle command on Windows

### ISSUE THREAD

**Issue by bramstieperaere** [facebook/react-native#4103]
when using the new asset system style for images on Windows, e.g.

```javascript
<Image source={require('./my-icon.png')} />
```

creating the bundle crashes :

gradlew assemble

uncaught error Error: spawn mkdir ENOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)

this is caused by following code in saveBundleAndMap.js:

```javascript
function copy(src, dest, callback) {
  const destDir = path.dirname(dest);
  execFile('mkdir', ['-p', destDir], err => {
    if (err) {
      return callback(err);
    }
    fs.createReadStream(src)
      .pipe(fs.createWriteStream(dest))
      .on('finish', callback);
  });
}
```

this calls mkdir on OS level, but mkdir behaves different in Windows. 

this can be fixed using https://www.npmjs.com/package/mkdirp

```javascript
const mkdirp = require('mkdirp')

function copy(src, dest, callback) {
  const destDir = path.dirname(dest);

  mkdirp(destDir, err => {
    if (err) {
      return callback(err);
    }
    fs.createReadStream(src)
      .pipe(fs.createWriteStream(dest))
      .on('finish', callback);
  });
}
```

**Comment by mkonicek** [comment]
@facebook-github-bot bugfix

**Comment by mkonicek** [comment]
@facebook-github-bot bugfix

**Comment by mkonicek** [comment]
@facebook-github-bot bugfix

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/new-asset-system-crashes-bundle-command-on-windows

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
