### ISSUE TITLE
Android instructions are missing details

### ISSUE THREAD

**Issue by mroch** [facebook/react-native#4125]
A couple of notes from trying to get running on android for the first time:

- you *have* to install API 23, even if you want to build for 5.1. It would be helpful to mention in the guide that 23 is required regardless of target version, since I thought it was just assuming I wanted to build for 6.0 (see #3617)

- Android SDK Build-tools has been updated to 23.0.2, so 23.0.1 wasn't installed by default and I had to manually install that when the build failed.

- I also had to install Extras > Android Support Repository (see http://stackoverflow.com/questions/33023018/react-native-awesome-project-not-building-android-project)

**Comment by mikearmstrong001** [comment]
Thanks for the information, many of the detail are located at http://facebook.github.io/react-native/docs/android-setup.html, but we should update the build tools info.

**Comment by ide** [comment]
Could we make the build tool version number in the Gradle file match a version range according to semver? I looked into a bit and the version matching with "+" is slightly bizarre... from my reading it does a prefix match rather than parsing the version string. But maybe there's a sane way to say match 23.0.x?

**Comment by nmccready** [comment]
@mroch can you leave a URL or instructions on how to manually install 23.0.1?

**Comment by nmccready** [comment]
nvm installing android extras got it to build

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-instructions-are-missing-details

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
