### ISSUE TITLE
ReactNativeART propTypes key is undefined

### ISSUE THREAD

**Issue by steida** [facebook/react-native#4134]
I updated from 0.12 to 0.14: `Warning: Failed propType: Cannot read property 'width' of undefined`, because Component.propTypes are undefined.

```
AnimatedComponent.propTypes = {
  style: function(props, propName, componentName) {
    for (var key in ViewStylePropTypes) {
      if (!Component.propTypes[key] && props[key] !== undefined) {
        console.error(
          'You are setting the style `{ ' + key + ': ... }` as a prop. You ' +
          'should nest it in a style object. ' +
          'E.g. `{ style: { ' + key + ': ... } }`'
        );
      }
    }
  }
};
```

The problem is, Component.propTypes is undefined. Component is shape in my case.

```
Shape.propTypes = Shape.propTypes || {};
const AnimatedShape = Animated.createAnimatedComponent(Shape);
```
will introduce another error:

You are setting the style `{ opacity: ... }` as a prop. You should nest it in a style object. E.g. `{ style: { opacity: ... } }`

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/reactnativeart-proptypes-key-is-undefined

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
