### ISSUE TITLE
setNetworkActivityIndicatorVisible(true) persists after refresh

### ISSUE THREAD

**Issue by cancan101** [facebook/react-native#4161]
Even after I refresh the app (command+R), a previous call to `setNetworkActivityIndicatorVisible(true)` still causes the spinner to show in the status bar.

**Comment by christopherdro** [comment]
@cancan101 Thats because using cmd+R refreshes and code changes done on the JS side and since `setNetworkActivityIndicatorVisible` is making a native call it will continue executing until you set it to false, or rebuild the app through xcode.

**Comment by cancan101** [comment]
Right but there could be some default hooks on  the refresh to clear some state on the native side,  no?

**Comment by christopherdro** [comment]
Sure if that is something you would like to look into, a PR would be greatly appreciated :)
However, at the moment I don't think this is crucial enough to be open as an issue.

**Comment by cancan101** [comment]
Same issue seems to apply to hiding  the status bar which is more of an problem.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/setnetworkactivityindicatorvisibletrue-persists-after-refresh

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
