### ISSUE TITLE
[RCTPerformanceLogger.m:29] Unbalanced calls start/end for tag 5

### ISSUE THREAD

**Issue by rocman** [facebook/react-native#4163]
When more than one RCTRootView exist and share a RCTBridge, it prints "[RCTPerformanceLogger.m:29] Unbalanced calls start/end for tag 5".

**Comment by ide** [comment]
cc @tadeuzagallo @javache

**Comment by geirman** [comment]
cc @tadeuzagallo @javache once more

**Comment by timhaines** [comment]
This is in [productpains](https://productpains.com/post/react-native/rctperformanceloggerm29-unbalanced-calls-startend-for-tag-5) (unresolved)

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/rctperformanceloggerm29-unbalanced-calls-startend-for-tag-5

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
