### ISSUE TITLE
Support for borderStyle property on RCTTextField

### ISSUE THREAD

**Issue by patoroco** [facebook/react-native#4182]
Hi,

should be good to have bridge-support for borderStyle in <TextInput /> component as is explained in https://developer.apple.com/library/ios/documentation/UIKit/Reference/UITextField_Class/index.html#//apple_ref/c/tdef/UITextBorderStyle

Border style is used on iOS to style TextField with solid border, rounded borders, etc. I know that this is possible to emulate wrapping TextInput in a View, but I think that should be better to use native support for that instead of need two layers for that.

What do you think about that?

**Comment by ide** [comment]
Would be nice to have. As you mention there is a simple workaround so this isn't a top priority. The quickest way to get this feature would be to send a PR if you want to do that.

**Comment by chirag04** [comment]
@christopherdro How about supporting ``borderStyle`` as a style property on any view in IOS. borderStyle is already supported on android as a style property.


https://facebook.github.io/react-native/docs/view.html#style

**Comment by patoroco** [comment]
Only to follow up, I would like to note that we're currently using two different styles for iOS / android:

```
search_input_ios: {
    flex: 1,
    fontSize: 18,
    backgroundColor: 'white',
    color: '#F2600F',
    borderRadius: 2.5,
    paddingLeft: 10,
    marginVertical: 10,
    marginLeft: 0,
    marginRight: 10,
 },
 search_input_android: {
    color: 'white',
    flex: 1,
    fontSize: 18,
 }
```

<img width="378" alt="screen shot 2015-11-18 at 18 10 08" src="https://cloud.githubusercontent.com/assets/701909/11248107/b1885806-8e1f-11e5-9c64-34c3fcfcd244.png">

The result is enough for us, but I continue thinking that it should be good to have an specific property for that.

**Comment by christopherdro** [comment]
@chirag04 I actually don't have this working yet. I wasn't aware that it would referenced here if I pushed a commit to my own forked version of RN. I will however take a look at your comment and see if I can get it all working.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/support-for-borderstyle-property-on-rcttextfield

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
