### ISSUE TITLE
XMLHttpRequest Polyfill on IOS Does not Set statusText on Response

### ISSUE THREAD

**Issue by cancan101** [facebook/react-native#4184]
[This line](https://github.com/facebook/react-native/blob/854689dcfaa7dc13e8ee5dec69f9f7a569595dd1/Libraries/Fetch/fetch.js#L375) seems to always read an `undefined`.

Seems to [be missing from here](https://github.com/facebook/react-native/blob/532c9112b475def95873673698c65ca4e29e2770/Libraries/Network/XMLHttpRequestBase.js).

Tracing this a little further, the event [originates in native code here](https://github.com/facebook/react-native/blob/5b796cec341b17954aad868927136319956be4e2/Libraries/Network/RCTNetworking.m#L347-L363).

And it looks like `NSHTTPURLResponse` should have [`localizedStringForStatusCode`](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSHTTPURLResponse_Class/#//apple_ref/occ/clm/NSHTTPURLResponse/localizedStringForStatusCode:) though according to [SO](http://stackoverflow.com/questions/6372047/can-i-access-reason-phrase-from-the-http-status-line-in-nshttpurlresponse) this is not exactly the same.

**Comment by mkonicek** [comment]
Thanks for reporting this @cancan101! Would you be up for sending a pull request? :)

**Comment by detunized** [comment]
I experience the same on Android. `response.statusText` in `fetch` callback is always `undefined`. `response.status` is correct though.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/xmlhttprequest-polyfill-on-ios-does-not-set-statustext-on-response

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by githubdoramon** [comment]
Why was this closed???? The problem remains... It is not possible to get the statusText on fetch requests... What can be done?

**Comment by ToKaDev** [comment]
Same issue here statusText : undefined on http 400. What can i do?

**Comment by ToKaDev** [comment]
Hm, it seems that the statusText property is not passed from the native implementation in Java/ObjectiveC to the JS implementation. (Only the status code is passed).

I think we need to extend this response callback to pass the statusText property.
