### ISSUE TITLE
[ActionSheetIOS] hides behind keyboard

### ISSUE THREAD

**Issue by jasonmerino** [facebook/react-native#4192]
I'm working on some comment functionality in my current project and I'm wanting to prompt the user to make sure they want to discard what they've written when they tap the Cancel button. The problem is that when I'm showing the ActionSheetIOS the options show up behind the keyboard like this.

<img width="487" alt="screenshot 2015-11-17 15 45 48" src="https://cloud.githubusercontent.com/assets/1660279/11228565/52899848-8d42-11e5-87c4-9152b4c57a99.png">

I've got around this by calling blur on the selected input before showing the action sheet, but then the items that are pinned to the top of the keyboard don't animate back down before the action sheet shows and it looks like this.

<img width="487" alt="screenshot 2015-11-17 15 48 08" src="https://cloud.githubusercontent.com/assets/1660279/11228600/9f00f630-8d42-11e5-86d6-d90d3b75bf96.png">

I will set a timeout to get around this little problem but I've seen action sheets on top of keyboards in other apps and I'm wondering if I've just missed something in my configuration. I checked around the interwebs and didn't see anything regarding this particular problem. Any help would be appreciated.

Thanks.

**Comment by skevy** [comment]
@jasonmerino what version of RN?

**Comment by jasonmerino** [comment]
RN 0.12.0. I've got a current branch to upgrade us to 0.14.2 that is about ready to be merged. I can chime back in with how it's behaving on that version also.

**Comment by skevy** [comment]
So, this may be fixed. What's happening is that the ActionSheet, in 0.12.0, is being placed on the React Native container view controller, rather than on the main window's view controller. This would cause the behavior you're seeing. There was a commit 13 days ago that, I'm pretty sure (as sure as I can be without testing it) solved the issue. Let us know!

**Comment by jasonmerino** [comment]
@skevy Looks like the ActionSheet hides the keyboard itself now, as far as I can tell. Is there any way to get it to show up on top of the keyboard? Now, since it autohides the keyboard when I tap an action in the action sheet the keyboard comes back up right away which leaves me with a strange progression of animations as I'm closing a modal if the user discards the comment. So the UI does this:

1. User taps close button
1. Keyboard hides
1. Action sheet shows
1. User taps discard comment action
1. Action sheet hides
1. Keyboard shows
1. Modal hides which in turn causes the keyboard to hide again

That last step is kind of strange but I don't currently see a way around it unless manually blur like before or I can get the action sheet to show above the keyboard.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/actionsheetios-hides-behind-keyboard

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
