### ISSUE TITLE
FileReader not found when running on device

### ISSUE THREAD

**Issue by RyGuyM** [facebook/react-native#4214]
I'm trying to use the FileReader in Javascript to read some data I'm dealing with. It works fine when I run the code in simulator but when I switch to my phone I get FileReader variable not found.

`const reader = new FileReader();`

I thought FileReader was supported as part of JavaScriptCore. It looks like it is used in the fetch library as well. Any help would be appreciated?

**Comment by ide** [comment]
Are you running the same version of iOS? And not using the Chrome debugger on the simulator?

**Comment by RyGuyM** [comment]
I am running the same version of iOS (9.1). I am using Chrome debugger in the simulator and I understand that when I'm doing that I'm using Chrome's V8 engine but apart from that I still don't see why the FileReader would not be present as part of the JavaScriptCore. I'll try running without Chrome debugger and see if I get a different result.

**Comment by ide** [comment]
To my knowledge FileReader isn't part of JS. It's probably a browser API.

**Comment by RyGuyM** [comment]
It doesn't work with Chrome debugger turned off. How does the implementation in `react-native/Libraries/Fetch/fetch.js` work? Is the function `readBlobAsArrayBuffer` never called?

**Comment by ide** [comment]
Not really sure -- RN doesn't (and can't right now) implement all the browser APIs so it might not be supported.

**Comment by RyGuyM** [comment]
Makes sense, I'll find a work around. I'm mostly curious now why that `react-native/Libraries/Fetch/fetch.js` file exists, is it just for debugging?

**Comment by ide** [comment]
It's used for doing basic GET, POST etc with JSON params and images. Just not everything is implemented.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/filereader-not-found-when-running-on-device

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
