### ISSUE TITLE
pod install react-native build 'RCTRootView.h' not found solution

### ISSUE THREAD

**Issue by AliThink** [facebook/react-native#4219]
![111](https://cloud.githubusercontent.com/assets/7530684/11262033/2bd36840-8eb5-11e5-8359-586ff6a07aab.jpg)
you can try this,if you meet the same problem .
podspec of react-native headers file structure changed.

**Comment by KavanBahrami** [comment]
Are you saying set it to recursive if its not, or that it being recursive is the problem?

**Comment by AliThink** [comment]
^_^Should set it recursive ,if use the podspec online. 
Because of React Native pod version just updated to 0.13.0-rc.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/pod-install-react-native-build-rctrootviewh-not-found-solution

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
