### ISSUE TITLE
[Navigator] immediatelyResetRouteStack does not update Navigator's title

### ISSUE THREAD

**Issue by yuyaohshimo** [facebook/react-native#4233]
Navigator's title is not updated by calling `immediatelyResetRouteStack` method in version `0.14.2`.
My workaround is below:

```
nav.immediatelyResetRouteStack([]); // call with blank stack
setTimeout(function() {
  nav.immediatelyResetRouteStack(newStack);
}, 0);
```

**Comment by brentvatne** [comment]
cc @hedgerwang @ericvicenti

**Comment by fender** [comment]
+1

**Comment by chirag04** [comment]
@fender @yuyaohshimo I just tried this in my app using react-native 0.15. Title seems to update fine. Not sure about 0.14 tho. Can you guys share some code or a repo case?

**Comment by fender** [comment]
If it makes a difference, it was in an async callback.
```
const self = this;
if (this.state.email.length && this.state.password.length) {
  Parse.User.logIn(this.state.email, this.state.password).then(user => {
    self.props.navigator.immediatelyResetRouteStack([]);
    setTimeout(function() {
      self.props.navigator.immediatelyResetRouteStack([{component: LobbyScreen}]);
    }, 0);
  }, (error) => self.setState({error: `Error: ${error.code} ${error.message}`}));
}
```

**Comment by yuyaohshimo** [comment]
@chirag04 

I created sample code:
https://gist.github.com/yuyaohshimo/9d2d4ff8d28123eacc87

I tried using 0.14.2 and 0.15.0, but title was not updated.

**Comment by timzaak** [comment]
0.16 does not work correctly.

**Comment by hedgerwang** [comment]
thanks for reporting this. we are working on the fix now.

**Comment by timzaak** [comment]
And In android, when you use `navigator.push(...)`. your RightButton will dismiss.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/navigator-immediatelyresetroutestack-does-not-update-navigators-title

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
