### ISSUE TITLE
[Packager] support pass through flags to Uglify

### ISSUE THREAD

**Issue by mvayngrib** [facebook/react-native#4271]
e.g. mangle: false

or there could be two ops
```bash
react-native bundle --minify
react-native bundle --uglify
```

**Comment by jsierles** [comment]
Hey @mvayngrib! Thanks for opening the issue.

We are closing it because it's a feature request, and we're trying to focus issues on bugs.

If this can't be implemented as a standalone [npm](https://npmjs.org) module free to send us a Pull Request or create an entry on [Product Pains](https://productpains.com/product/react-native). It has a voting system and if the feature gets upvoted enough it might get implemented.
