### ISSUE TITLE
[Android][Text] any plans to implement allowFontScaling on Android?

### ISSUE THREAD

**Issue by han4wluc** [facebook/react-native#4273]
`allowFontScaling=false` works only for iOS right now.
I'd like to use it in my Android app.
Does anyone know how to disable fontScaling on Android?

**Comment by mkonicek** [comment]
Hey and thanks for reporting this!

This issue looks like a question - please use [Stack Overflow](http://stackoverflow.com/questions/tagged/react-native) for questions. It's the best system for Q&A and the best way to get questions answered.

Many people from the community hang out on Stack Overflow and will be able to see your question and be more likely to answer because of the reputation system. If after reading this you think your question is better suited for Stack Overflow, please consider closing this issue.

**Comment by mkonicek** [comment]
Hey and thanks for reporting this!

There's an awesome place to ask question like this one: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see your question, you can vote on answers and mark question as answered etc. This lets us keep a list of bug reports and feature requests on github and especially [Product Pains](https://productpains.com/product/react-native/?tab=top) (again, with voting which is really nice).

If you think StackOverflow works for you please consider posting there instead and closing this issue.

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)

**Comment by bcalik** [comment]
This is an important feature for design purposes, must be implemented.
