### ISSUE TITLE
Image shrinking bug when inside of a ScrollView

### ISSUE THREAD

**Issue by IlyasM** [facebook/react-native#4279]
Whenever I have Image and try to resize it from bigger to smaller width, it works fine here is rn play link for that https://rnplay.org/apps/RdGQuQ.

 But when  Image is inside of a ScrollView  there is a strange bug happening when Image goes from bigger width to smaller (here is the link https://rnplay.org/apps/Uv4sWg) The right side of the image moves faster than the left for some reason, and that is why there is an unwanted flickering effect caused by right side going too fast(faster than left side) in decreasing direction and then some movements in increasing direction as if it 'catches up' with the left side. 

Is there any workaround for this bug?

**Comment by almasakchabayev** [comment]
+1

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/image-shrinking-bug-when-inside-of-a-scrollview

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
