### ISSUE TITLE
Mistaken endless interval in setupDevtools.js

### ISSUE THREAD

**Issue by rocman** [facebook/react-native#4282]
in setupDevtools(https://github.com/facebook/react-native/blob/master/Libraries/Devtools/setupDevtools.js), the method 'tryToConnect' starts a interval which expecting a message with an evt.data which starts with 'eval:'.
After searching in the code, I found that there seams to be nowhere sending the message expected. And so, the interval is invoked again and again.

**Comment by rocman** [comment]
And, as a result, memory consumes again and agian every 500ms.

**Comment by rocman** [comment]
PS: the behaviour I described above exists on "stable 1.4".
On the later version, the setupDevtools.js makes a small change, changing the port to connect from 8081 to 8097(which is strange.) It results in a more memory consuming behaviour, of which ws.onerror is called again and agian with a error message saying "The operation couldn’t be completed. Connection refused"

**Comment by rocman** [comment]
Here's my tries to fix the issue: https://github.com/facebook/react-native/pull/4283 https://github.com/facebook/react-native/pull/4284

**Comment by rocman** [comment]
And here's a issue seams relative https://github.com/facebook/react-native/issues/3953

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/mistaken-endless-interval-in-setupdevtoolsjs

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
