### ISSUE TITLE
Invalid directory /Users/node_modules/react-native

### ISSUE THREAD

**Issue by jonaswindey** [facebook/react-native#4296]
I'm getting this error when I add react to an empty react-native project

Steps to reproduce:

`react-native init test`

Go to /test and edit add react (npm i --save react) or modify package json like this:
```
{
  name: "test",
  version: "0.0.1",
  private: true,
  scripts: {
  start: "react-native start"
},
dependencies: {
    react: "^0.14.3",
    react-native: "^0.14.2"
  }
}
```

Run the iOS project and I get the following error:

```
2015-11-23 11:33:19.073 [error][tid:main][RCTBatchedBridge.m:436] Error while loading: Unable to resolve module react-native from /Users/jonas/Development/3nit/myabi-native/myabi/index.ios.js: Invalid directory /Users/node_modules/react-native
2015-11-23
```

using node 5.0.0 on OS X El Capitan

**Comment by jonaswindey** [comment]
I think this one might be related too (getting the same error when I add superagent to my package.json)
http://stackoverflow.com/questions/33840112/invalid-directory-users-node-modules-superagent-with-react-native

**Comment by jonaswindey** [comment]
Downgrading npm3 works. But is it really not possible to use npm3 with react-native?

**Comment by fender** [comment]
@jonaswindey Which Node version and npm version are you using? I have a similar issue over at http://stackoverflow.com/questions/33843542/using-pubnub-with-react-native/33866190 but couldn't solve it by downgrading.

**Comment by jonaswindey** [comment]
I'm using Node 5.0.0 and was using npm 3 but it helped to downgrade to npm2.

**Comment by nc** [comment]
:+1:

**Comment by toadums** [comment]
:+1:

**Comment by shohey1226** [comment]
:+1:

**Comment by ide** [comment]
This error is probably showing up because the node_modules resolution algorithm crawls up the directory hierarchy. I agree the error message is confusing.

Cc @martinbigio

**Comment by dbrugne** [comment]
:+1:

**Comment by zhjx19892008** [comment]
Failed to resolve, for help

**Comment by arypurnomoz** [comment]
:+1:

**Comment by fatuhoku** [comment]
Got the same error but for Parse. I really do expect things to Just Work when using NPM

**Comment by ide** [comment]
@fatuhoku To set expectations, things aren't going to Just Work when pulling from npm because npm is a repository of code for several different platforms.

Just as how we don't expect `npm install express` to work in the browser, many npm packages won't work in React Native unless they have (a) been explicitly written for React Native or (b) are pure JavaScript that uses the libraries in [the JavaScript spec](http://www.ecma-international.org/ecma-262/6.0/).

**Comment by skevy** [comment]
Hey everyone, can you all try:

1) upgrading to latest RN
2) `watchman watch-del-all`
2) `rm -rf $TMPDIR/react-native-packager-*`
3) restart the packager

And let me know if that fixes the issue?

**Comment by jeffcressman** [comment]
I've been having similar issues with path lookups for npm modules having `/Users/node_modules` prepended to a relative path name, e.g. `var thing = require('./my-module')` instead of using `__dir` to construct a full path.

To explore this further I just created a test React Native app and when I launched it in XCode the packager was trying to look up modules in the previous project I had been working in.

The steps 

1) `watchman watch-del-all1
2) `rm -rf $TMPDIR/react-packager-*`

cleared up the issue of running the wrong code. 

Note that the path in @skevy's example above should be `$TMPDIR/react-packager-*` instead of `$TMPDIR/react-native-packager-*`.

**Comment by skevy** [comment]
@jeffcressman thanks for the correction! Updated the comment. :)

I'm gonna close this particular issue, as it seems that it is directly related to watchman and packager caches...but @jeffcressman please feel free to open another when you get a sample app put together (and tag me on it!) :)

**Comment by lrettig** [comment]
+1

This issue keeps happening to me sporadically with a seemingly random set of npm modules. The solution proposed by @skevy in https://github.com/facebook/react-native/issues/4296#issuecomment-164078248 seems to work each time.

Why does this keep happening? I'm running the latest RN.

Thanks.

**Comment by lilac** [comment]
RN on 0.17, but the previously mentioned workaround
```watchman watch-del-all
 rm -rf $TMPDIR/react-packager-*
```
does not work for me.

**Comment by af7** [comment]
It does not work for me either.

**Comment by andpor** [comment]
this workaround does not work for me either. installed everything fresh with RN 0.18.0 and still having this issue with packager.

**Comment by alizbazar** [comment]
Same issue here... :/

**Comment by ghamaide** [comment]
Same issue here. Did all mentioned above. Downgraded to NPM 2 too. Still the same issue.

**Comment by lilac** [comment]
I've resolved this issue by changing the js file from `index.ios.js` to `index.js`. I guess the problem relates to js module search.

**Comment by levda** [comment]
Node js have group of possible folders that can contain modules. When you install one module sometimes module can be dependent to other modules. You have to install this dependancies manual. For example if the error is like /Users/node_modules/module you have to install "npm install -S module". It is showing error as missing path in /Users/node_modules because this is the last element of array full with possible paths (for MAC).

Full list of paths by OS : https://www.npmjs.com/package/npm-paths
