### ISSUE TITLE
Cannot change content of multiline TextInput in iOS

### ISSUE THREAD

**Issue by mtford90** [facebook/react-native#4307]
I'm running the 0.15 rc and neither methods I tried (`clearInputViaNativeProps`/`clearTextInputViaState`) worked when attempting to reset the `TextInput`

```js

clearInputViaNativeProps() {
      // this.refs.messageInput.refs.input.setNativeProps({
      //  text: ''
      // });
      this.refs.messageInput.setNativeProps({
        text: ''
      });
}

clearTextInputViaState() {
    this.setState({
        messageText: ''
    });
}

render() {
   return <TextInput
          multiline={true}
          onKeyPress={this.handleTextInputKeyPress.bind(this)}
          ref='messageInput'
          value={this.state.messageText}/>;
}
```

**Comment by mtford90** [comment]
#4290 could be the same issue

**Comment by mtford90** [comment]
I just delved into this a bit further - the culprit is this method in `RCTTextView.m`:

```Obj-C
- (void)setText:(NSString *)text
{
  NSInteger eventLag = _nativeEventCount - _mostRecentEventCount;
  if (eventLag == 0 && ![text isEqualToString:_textView.text]) {
    UITextRange *selection = _textView.selectedTextRange;
    _textView.text = text;
    [self _setPlaceholderVisibility];
    [self updateTextViewFrame];
    _textView.selectedTextRange = selection; // maintain cursor position/selection - this is robust to out of bounds
  } else if (eventLag > RCTTextUpdateLagWarningThreshold) {
    RCTLogWarn(@"Native TextInput(%@) is %zd events ahead of JS - try to make your JS faster.", self.text, eventLag);
  }
}
```

`eventLag` is always `1` and so nothing ever happens... I'm not familiar with the concept of event lag so not sure what's going on here, but if I remove the `eventLag == 0` check everything works as expected.

**Comment by mtford90** [comment]
I still have to do this though:

```
this.refs.messageInput.setNativeProps({
    text: ''
});
```

Should `RCTTextView` not be controlled?

**Comment by nc** [comment]
:+1:

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/cannot-change-content-of-multiline-textinput-in-ios

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
