### ISSUE TITLE
Differentiate view/defaultView creation

### ISSUE THREAD

**Issue by skatou** [facebook/react-native#4316]
Hi,

When a RCTViewManager call -(UIView*)view method, it is possible to know whether the call is for rendered view or default view?

Without this option I am not able to customize the defaultView further say don't set delegate property.

Thanks.

**Comment by skevy** [comment]
@skatou I'm confused by your question. Could you provide more information as to what you're trying to do?

**Comment by ide** [comment]
@skatou this is not supported. You could work around it by sending a dummy prop from JS whenever the component is rendered and that would tell you which view is truly on the screen.

@nicklockwood do you think it's desirable to expose whether a view is the template default view?

**Comment by jeanregisser** [comment]
I have a use case here where I'm using a shared video player instance and I determined I was in the rendered view and not in the default view since `willMoveToSuperview` was called.
This is an alternative to setting a dummy prop from JS.

```swift
// This is in the implementation of the view created by the view manager
override func willMoveToSuperview(newSuperview: UIView?) {
    super.willMoveToSuperview(newSuperview)

    // We're in the rendered view (and not in the default view)

    // Since we're sharing the player view and react
    // needs new view instances when calling the viewManager.view
    // we make sure only the displayed view has the player view with the video
    if player.view.superview != self {
        addSubview(player.view)
    }
}
```

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/differentiate-viewdefaultview-creation

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
