### ISSUE TITLE
After setting padding for the parent element, the absolute positioning of the child element is inaccurate

### ISSUE THREAD

**Issue by ShaoGongBra** [facebook/react-native#43206]
### Description

The child element is set to left: 0 and is positioned within the padding, which does not match the actual performance

### Steps to reproduce

```jsx
<View style={{padding: 20,height: 100, backgroundColor: '#f2f2f2'}}>
  <View  style={{height: 20, width: 20, backgroundColor: '#666', position: 'absolute', left: 20, top: 20}} />
</View>
```

### React Native Version

0.71

### Affected Platforms

Runtime - Android, Runtime - iOS

### Areas

Fabric - The New Renderer

### Output of `npx react-native info`

```text
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 16.30 GB / 31.87 GB
  Binaries:
    Node: 18.19.0 - ~\AppData\Local\Temp\yarn--1709026031687-0.9586875619600348\node.CMD
    Yarn: 1.22.21 - ~\AppData\Local\Temp\yarn--1709026031687-0.9586875619600348\yarn.CMD
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
  IDEs:
    Android Studio: AI-223.8836.35.2231.11005911
    Visual Studio: 17.8.34322.80 (Visual Studio Community 2022)
  Languages:
    Java: 11.0.21
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.2.0 => 18.2.0
    react-native: ~0.71.11 => 0.71.15
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Stacktrace or Logs

```text
no
```

### Reproducer

no

**Comment by cortinico** [comment]
Is this New Architecture specific? Have you tried on the Old Architecture?

**Comment by ShaoGongBra** [comment]
@cortinico I am certain that this problem is encountered on the new architecture. When I encounter it again, I will put the example up. I feel that it only appears under certain specific conditions

**Comment by joevilches** [comment]
@NickGerleman Yes this situation is covered in those list of things, specifically in #41684. Although the fix in there was more about the priority of insets in the case both `left` and `right` are defined (among other things). I do not recall this specific situation being broken and it seems like it should be working based on the [legacy positioning logic](https://github.com/facebook/react-native/blob/0555fdd93afb00b6b25ba7ace76b0d65b7458c9e/packages/react-native/ReactCommon/yoga/yoga/algorithm/CalculateLayout.cpp#L1034). I was not able to repro either with the strict layout conformance off.

**Comment by cortinico** [comment]
> When I encounter it again, I will put the example up. I feel that it only appears under certain specific conditions

Closing as we cannot reproduce + for the reasons mentioned by @joevilches. If you can consistently reproduce, please open a new issue. Plus ideally try on the latest stable (0.73) as it would help us investigate/fix

**Comment by DivadOger** [comment]
I know that issue was closed, but I just ran up to this issue (or very similar) 🤔 
I'm trying to position an absolute element in the center, so I'm using percentage values for `top` and `left`. However, when I add padding to the parent element, it no longer centers it.

Case 1 (without padding):
<img width="382" alt="no-padding" src="https://github.com/user-attachments/assets/d166f053-e218-4262-a405-a566a353f1c4" />

Case 2 (with padding):
<img width="382" alt="padding" src="https://github.com/user-attachments/assets/25595f63-90f2-448a-8461-27b74c646be5" />

Example code:
```
<View
  style={{
    height: 120,
    // padding: 20, (case 2)
    backgroundColor: '#bdafac',
  }}
>
  <View
    style={{
      width: 20,
      height: 20,
      position: 'absolute',
      left: '50%',
      top: '50%',
      transform: [
        {
          translateX: -10,
        },
        {
          translateY: -10,
        },
      ],
      backgroundColor: '#000000',
    }}
  />
</View>
```

**Comment by joevilches** [comment]
@DivadOger this is actually known incorrect behavior in Yoga. We have fixed this problem, but due to breaking changes we have not enabled this fix by default (existing UI could break if we did). If you need this behavior, you can make use of the `experimental_layoutConformance` prop on `View` like so:

```
<View
  style={{
    height: 120,
    padding: 20,
    backgroundColor: '#bdafac',
  }}
 experimental_layoutConformance="strict"
>
  // child view
</View>
```

FYI @NickGerleman recently changed this in https://github.com/facebook/react-native/pull/48188 to instead use a component, but that shouldn't be in 0.76.5

Also should note this is `experimental`, so there is likelihood of this functionality changing over time (case in point, the PR linked above). Additionally, it may change other aspects related to layout and not just this single bugfix.

**Comment by DivadOger** [comment]
@joevilches  Super thanks for answering and explaining the problem! 🙌 
For now, I think the experimental prop will work out well because in our case, it's in an isolated use case/component.

**Comment by mattaningram** [comment]
@joevilches I am experiencing this same Yoga behavior in a brand new Expo RN app. It doesn't appear `experimental_layoutConformance="strict"` is a thing anymore, do I need to use this component? I can't find any documentation about it.

**Comment by ShaoGongBra** [comment]
The new version has switched to the experimental_LayoutConformance component, and components nested within this component will automatically take effect without the need to specify attributes for each View

**Comment by mattaningram** [comment]
@ShaoGongBra thanks that worked great!
