### ISSUE TITLE
[RCTDevMenu] Swizzle of motionEnded:withEvent: over riding existing implementations

### ISSUE THREAD

**Issue by MattFoley** [facebook/react-native#4330]
I use the shake gesture in my app, and the current implementation of `RCT_motionEnded:withEvent:` is squashing my implementation. I'd like to change this method to call the existing implementation if one exists. (whether it be implemented via category or previous swizzle)

Would this be a desired pull request? If so, is there an existing preferred style of this type of swizzling in the React Native code base? (I've been storing procs via a static typedef variable when I will need to call the initial implementation eventually.)

**Comment by christopherdro** [comment]
@MattFoley You can see the original implementation here
https://github.com/facebook/react-native/blob/0764e4ef293eb19da6b52c74df5f154e04854e70/React/Modules/RCTDevMenu.m#L156.

I was able to create my own method to override this but couldn't really find a way a nice way to switch between my own and the dev menu.

Here's how that looked.
https://gist.github.com/christopherdro/8418aa334ec5e6027f0d

Hope this helps. :)

**Comment by MattFoley** [comment]
I was looking there when I posted this issue, and I thought about implementing something similar to your solution, but I don't think that's a permanent solution for React Native.

It would be pretty easy for me to fix this so both any existing implementation and the RN implementations are both called, and that is much more developer friendly.

**Comment by christopherdro** [comment]
Nice, that would be a really awesome addition!

**Comment by MattFoley** [comment]
Glad to hear it. It may take me a few days to get to it, but I will eventually and I'll link back to this issue when I do.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/rctdevmenu-swizzle-of-motionendedwithevent-over-riding-existing-implementations

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by AustinChou** [comment]
Same issue here, Instabug not working under Debug build type, but working under Release. 
This makes difficult to test Instabug settings.
