### ISSUE TITLE
[ListView] Calls setState after component has unmounted

### ISSUE THREAD

**Issue by Kuzmin** [facebook/react-native#4335]
After updating my app to react-native 0.15.0 from 0.11.4, I noticed the following warnings popping up in the XCode console in big numbers:

```
'Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the ListView component.'
```

It logs a big amount of these messages, and basically halts the app during this. 

I traced the issue a bit and found that the error message was added in react 0.13.0, and it is located in this file in the React repo: https://github.com/facebook/react/blob/401e6f10587b09d4e725763984957cf309dfdc30/src/isomorphic/modern/class/ReactNoopUpdateQueue.js

I also looked at the `setState` calls made in the `ListView` component, and found that it is the `setState` call in the `_pageInNewRows` method that triggers these warnings. (The other `setState` calls seem to not get called after unmounting).

Adding a check with `this.isMounted` as follows solved this locally for me. (I'm sure this has implications that I haven't thought about though.)

```
  _pageInNewRows: function() {
    if (!this.isMounted()) {
      return;
    }
```

The product impact from this is that it suddenly halts the app for me when these huge log outputs are printed.

**Comment by Kuzmin** [comment]
Sorry, pressed the submit button a bit early. It's now updated with everything properly.

**Comment by mihirsoni** [comment]
@Kuzmin  If it has solve your problem , please close the issue.

From next time onwards , please please ask such kind of questions to http://stackoverflow.com/ with ```react-native``` tags..

**Comment by Kuzmin** [comment]
@mihirsoni I "solved" my problem by patching the `ListView` class in `react-native`. So I think that this should stay open.

**Comment by admmasters** [comment]
@mihirsoni I also think this should stay open as its a bug - like @Kuzmin my fix for this issue was to edit the React Native source code locally/on my own fork. Also AFAIK this.isMounted seems to be considered bad practice, or at the very least code smell: https://github.com/facebook/react/issues/3417  .

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/listview-calls-setstate-after-component-has-unmounted

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by Kuzmin** [comment]
Thanks @mkonicek. I checked the source code and the method I describe above seems to have be removed in newer version. I think it's plausible that this bug is no longer present. I'll try sending a PR if it comes up again for me.

Thanks for all your work on React Native!
