### ISSUE TITLE
RCTThirdPartyFabricComponentsProvider always generated in React-Fabric filepath

### ISSUE THREAD

**Issue by nanatlantica** [facebook/react-native#43359]
### Description

RCTThirdPartyFabricComponentsProvider always generated in React-Fabric filepath
not in the -outpath param specified path

### Steps to reproduce

node node_modules/react_native/scripts/generate-codegen-artifacts.js \
    --path SampleApp/ \
    --outputPath <an/output/path> \

### React Native Version

0.72.5

### Affected Platforms

Runtime - iOS

### Areas

Codegen

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.2.1
  CPU: (8) arm64 Apple M1 Pro
  Memory: 147.52 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.5.1
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.21
    path: /opt/homebrew/bin/yarn
  npm:
    version: 9.8.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2024.01.15.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.11.3
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 20.0.1
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.5
    wanted: 0.72.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: false
  newArchEnabled: true
```

### Stacktrace or Logs

```text
nothing
```

### Reproducer

https://github.com/nanatlantica/RNDynamic

### Screenshots and Videos

Can I put the files generated by codegen into another repo, to make react-native repo no need to update frequently

**Comment by cipolleschi** [comment]
Actually, this file ends up in `React-RCTFabric`, slightly different.
Anyway, that's correct for the time being. 

That's the right path for that file. The file needs access to RCTFabric files and RCTFabric uses this file, that's why we generate it there. Otherwise, generating it in the React-Codegen path, that will create a circular dependency:
- React-Codegen will depend on React-RCTFabric.
- React-RCTFabric will depend  React-Codegen.

We are already working toward disentangling this, but for the time being, that's the correct behavior.
