### ISSUE TITLE
[iOS][WebView] Error loading page Domain: WebKitErrorDomain Error Code: 101

### ISSUE THREAD

**Issue by han4wluc** [facebook/react-native#4337]
<img width="275" alt="screen shot 2015-11-24 at 19 26 06" src="https://cloud.githubusercontent.com/assets/8134740/11388349/37a913e4-9370-11e5-892d-9ffe6d7d1986.png">

I load a webview page and the first page is displayed without problem. but when I click in a link, I have this error page displayed while the page is loading. After the pages is finished loading, the loaded page is displayed. But I don't know why there is this error message while the page is loading.

My webview looks like this:
```
        <WebView style={{position:'absolute', width: deviceWidth, height: deviceHeight-48, marginBottom:48}}
            ref={WEBVIEW_REF}
            url={this.props.url}
            injectedJavaScript={this.props.injectedJavaScript}
            onShouldStartLoadWithRequest={this.onShouldStartLoadWithRequest}
            startInLoadingState={this.props.startInLoadingState}
            onNavigationStateChange={this.onNavigationStateChange}
        />
```

**Comment by satya164** [comment]
Hey and thanks for reporting this!

There's an awesome place to ask question like this one: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see your question, you can vote on answers and mark question as answered etc. This lets us keep a list of bug reports and feature requests on github and especially [Product Pains](https://productpains.com/product/react-native/?tab=top) (again, with voting which is really nice).

If you think StackOverflow works for you please consider posting there instead and closing this issue.

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)

**Comment by satya164** [comment]
Also, I found a relevant link on StackOverflow for you - http://stackoverflow.com/questions/1528060/uiwebview-error-while-loading-url
