### ISSUE TITLE
 image.capInsets not work in branch 0.16-stable and master

### ISSUE THREAD

**Issue by nowaits** [facebook/react-native#4346]
2eb8068cf17f603823fb7fb41beacd0a997a7629 [2eb8068] RCTDecodeImageWithData function adjust the scale of image which lead to  image.capInsets not work well

**Comment by ide** [comment]
cc @javache @nicklockwood

Also if anyone would like to help, adding a capInsets example to the UIExplorer (if one doesn't already exist) would be helpful and we could add it to the snapshot test suite.

**Comment by nicklockwood** [comment]
There is a capInsets example in the Image example in UIExplorer, and I think that still works because we're not applying image scaling to static images (yet). But yeah, this is a problem.

The fix is basically to disable image pre-scaling in the loading pipeline when capInsets is set, which should be fairly straightforward.

**Comment by nowaits** [comment]
i have tried the Image example in UIExplorer, it's appearance is not ok, the background is enlarged without use of capInsets, so i think it's still a problem

**Comment by nowaits** [comment]
the problem has been fixed b672294, thx~
