### ISSUE TITLE
Inject IP Address of Host into DEFINE Constant to make Device Development Easier in XCode

### ISSUE THREAD

**Issue by cancan101** [facebook/react-native#4351]
According to [the docs](https://facebook.github.io/react-native/docs/running-on-device-ios.html#content): 
>Change the IP in the URL from localhost to your laptop's IP. On Mac, you can find the IP address in System Preferences / Network.

It would be cool to use something like [suggestion 2 in this SO post](http://stackoverflow.com/a/7944940/2638485) to inject a define constant such that I don't have to change my source code every time my IP changes.

**Comment by chirag04** [comment]
@cancan101 Like the comment on SO, I too feel option 2 is kindof hacky. However i have heard people using services like https://ngrok.com/ etc.

@ide @brentvatne thoughts?

**Comment by cancan101** [comment]
ngrok looks cool but it still means that each developer needs to modify the source to point to his ngrok. I agree that for any given developer it simplifies the number of code updates.

**Comment by ide** [comment]
ngrok is a no-go because it supports only HTTP unless you have a paid account.

Whatever solution we ship, it needs to be very simple and reliable, and easy to diagnose when things go wrong.

**Comment by aleclarson** [comment]
I would love to see this. :heart_eyes: 

[Here's the Product Pains page for this issue! :wink:](https://productpains.com/post/react-native/inject-ip-address-of-host-into-define-constant-to-make-device-development-easier-in-xcode/)

**Comment by aleclarson** [comment]
#6362 and #6345 both have a go at fixing this issue

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/inject-ip-address-of-host-into-define-constant-to-make-device-development-easier-in-xcode

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
