### ISSUE TITLE
[ListView] Prevent rendering during an interaction?

### ISSUE THREAD

**Issue by aleclarson** [facebook/react-native#4359]
I noticed that extreme jitter occurs if a `ListView` renders rows during a pan interaction. Is there any way to stop the `ListView` from rendering rows (maybe using `InteractionManager`)? Thanks!

**Comment by brentvatne** [comment]
I implemented this but not sure if it's something that will go into core: https://github.com/facebook/react-native/issues/2990

**Comment by aleclarson** [comment]
Fantastic. Thanks, @brentvatne.

Any reason(s) for this not making it into core? It seems to be the only solution for avoiding `ListView` jitter during animation and user interaction. Isn't that something a lot of people need?

**Comment by brentvatne** [comment]
@aleclarson - Well perhaps it could make it actually.. I've been working on something else recently to throttle paging in new rows with `requestIdleCallback` and had some good success with that too. Combined they make interactions in apps with heavy use of ListViews seem smoother / snappier in a subtle yet certainly noticeable way. Wish I could share a video of a comparison but it's for a private project atm :(

**Comment by brentvatne** [comment]
Also, @sahrens is doing a lot of work on ListView :)

**Comment by aleclarson** [comment]
Exciting times! Janky `ListView`s make me physically ill. :smile:

**Comment by sahrens** [comment]
I think using interaction manager is something we want to do, although it's not usually a problem because people don't often navigate before the ListView finishes rendering. You may want to adjust your initial size and other variables to mitigate.

requestIdleCallback could be cool too.

cc @nicklockwood

**Comment by aleclarson** [comment]
> although it's not usually a problem because people don't often navigate before the ListView finishes rendering

What about long lists? Paging in new rows while the user is scrolling can result in jankiness depending on the complexity of the row view; even if `pageSize` is limited to one. This is especially noticeable when `Image` elements are used.

-

Also, this case could benefit from `InteractionManager`:

> I navigate to a `ListView` and it starts paging in new rows before its superview has completed its entrance animation. 

-

On a side note, it could be useful to have a `preventRowRendering` prop in the case that:

> I tap something to navigate away from the `ListView` before it's done paging in new rows. The `ListView` can be returned to, so it cannot be unmounted.

-

How does `requestIdleCallback` work?

**Comment by ide** [comment]
Is there a small but powerful prop we could add to ListView's API to configure the incremental rendering behavior? For example, some people might want to use InteractionManager, some people want to use requestIdleCallback, and others might want to use other heuristics such as capping the number of rows per frame (`pageSize`).

Here's a first take at an API:
```js
<ListView
   shouldRenderRow={(rowData, sectionId, rowId, <what else?>) => boolean}
/>
```

For convenience we may want to also pass in the number of rows rendered during this pass of the JS event loop -- implementing `pageSize` is trivial:
```js
shouldRenderRow={(rowData, sectionId, rowId, numberOfMarginalRowsRendered) =>
  numberOfMarginalRowsRendered < pageSize
}
```

The main things I like about this approach is that ListView doesn't become more of a monster API and it pushes the complexity out of the component and into userspace.

**Comment by sahrens** [comment]
Another option would be to inject a task queue into ListView, which could
be InteractionManager, or a simple queue that checks a shouldRenderRow
function? Seems like maybe the most flexible option?

**Comment by machard** [comment]
it does not solve all the problems listed here but for navigation fluidity related problems, you can check https://github.com/machard/react-native-advanced-navigation

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/listview-prevent-rendering-during-an-interaction

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
