### ISSUE TITLE
Is this an issue or not about style(flexbox)

### ISSUE THREAD

**Issue by andyyou** [facebook/react-native#4360]
I am attempt to describe the problem but I am not sure is that a issue or just I don't understand the knowledge of this. Base on my CSS experience I can do the effect like this [CodePen demo](http://codepen.io/andyyou/pen/RWzGBZ#0)

For example, I have three levels of structure `.father`, `.son` and `.grandson` the father element has dynamic elements inside and son too. I hope `.son` element can use `position: absolute` to cover fit upon `.father` then inside `.son` can work as normal flexbox.

Of course I know that react-native is not totally same with CSS so I want to check the situation as follow video

[video link](https://youtu.be/Rgm9Erw7RrA)

The question is I want to flexbox ability in a `absolute` container(element) but some properties from it's parent element will effect children element inside that I don't want.

[UPDATE]
this is my [sample code](https://gist.github.com/andyyou/fe7bcff8edd5eef0bb5f) seems [playground](https://rnplay.org/) is broken right now so I just post my code

**Comment by chirag04** [comment]
You can wrap ``<Text>Hello sandbox</Text>`` elements in a ``<View style="textSons">`` and apply the padding there.

**Comment by andyyou** [comment]
@chirag04 Thanks for your suggestion I have completed my requirement by avoid this situation. I just want to figure out about that behavior :)

**Comment by satya164** [comment]
Hey and thanks for reporting this!

There's an awesome place to ask question like this one: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see your question, you can vote on answers and mark question as answered etc. This lets us keep a list of bug reports and feature requests on github and especially [Product Pains](https://productpains.com/product/react-native/?tab=top) (again, with voting which is really nice).

If you think StackOverflow works for you please consider posting there instead and closing this issue.

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)
