### ISSUE TITLE
[RCTText] Cached TextStorage not hit because of rounded width

### ISSUE THREAD

**Issue by cxfeng1** [facebook/react-native#4361]
In method  `buildTextStorageForWidth`, we use `_cachedTextStorageWidth` and `_cachedTextStorage`  to store NSTextStorage.

```
  if (_cachedTextStorage && width == _cachedTextStorageWidth) {
    return _cachedTextStorage;
  }
```

While the text's property is updated,  we construct a width to see if the NSTextStorage is built already.

```
  UIEdgeInsets padding = self.paddingAsInsets;
  CGFloat width = self.frame.size.width - (padding.left + padding.right);
  NSTextStorage *textStorage = [self buildTextStorageForWidth:width];
```

But here the width is not exactly same as the width before,  because `self.frame.size.width` is a rounded one.

```
  CGRect frame = {{
    RCTRoundPixelValue(node->layout.position[CSS_LEFT]),
    RCTRoundPixelValue(node->layout.position[CSS_TOP]),
  }, {
    RCTRoundPixelValue(absoluteBottomRight.x - absoluteTopLeft.x),
    RCTRoundPixelValue(absoluteBottomRight.y - absoluteTopLeft.y)
  }};

  if (!CGRectEqualToRect(frame, _frame)) {
    _frame = frame;
    [viewsWithNewFrame addObject:self];
  }
```

For example , the width used to layout may be 100.0123456,  the width to detect cache will be 100, which cause the text cache not hit even though using the same text and properties.

The first question is why the width and height should be rounded here ?

If they must be rounded, can we use a different value to store the unrounded frame?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/rcttext-cached-textstorage-not-hit-because-of-rounded-width

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
