### ISSUE TITLE
How does `.bundle?dev=true` work?

### ISSUE THREAD

**Issue by jdrydn** [facebook/react-native#437]
```
[NSURL URLWithString:@"http://localhost:8081/Examples/UIExplorer/UIExplorerApp.includeRequire.runModule.bundle?dev=true"];
```

I'm guessing this enables some form of development mode. Is there any examples of how the JavaScript can check for this development mode flag?

**Comment by vjeux** [comment]
There's a global variable __DEV__ being set or not.

When doing 

```
if (__DEV__) {

}
```

The code inside will be completely stripped out in production.

Beware, you should NEVER change the runtime behavior of the code between dev in prod, otherwise you're going to have hell of a time trying to debug some super weird issues reported by your users.

**Comment by jdrydn** [comment]
That's awesome, thanks for getting back to me!

> Beware, you should NEVER change the runtime behavior of the code between dev in prod, otherwise you're going to have hell of a time trying to debug some super weird issues reported by your users.

So this style shouldn't be used to modify config files, for example? It should all be the same?

**Comment by vjeux** [comment]
We use it internally to add a lot of warnings. For example all the propTypes warn in dev to help the developer but in prod all the code for them is removed to make the app faster.
