### ISSUE TITLE
[SegmentedControlIOS] Add setTitleTextAttributes to customize font stlying

### ISSUE THREAD

**Issue by hasen6** [facebook/react-native#4379]
Any ideas how this is done? I added a style component to SegmentedControlIOS with fontSize but it didn't change anything.

**Comment by christopherdro** [comment]
After a bit of research it appears we need to access [setTitleTextAttributes] (https://developer.apple.com/library/prerelease/ios/documentation/UIKit/Reference/UISegmentedControl_Class/index.html#//apple_ref/occ/instm/UISegmentedControl/setTitleTextAttributes:forState:) in order to add custom font and size. 

Unfortunately that feature is not currently implemented yet, if you think this is something you can tackle a PR would be greatly appreciated. :)

I'll go ahead and label accordingly and see if we can get more info.

@brentvatne @ide Any suggestions on the best way to approach this?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/segmentedcontrolios-add-settitletextattributes-to-customize-font-stlying

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by gwendall** [comment]
+1
