### ISSUE TITLE
Support stateless function components in AppRegistry.registerComponent 

### ISSUE THREAD

**Issue by chandu0101** [facebook/react-native#4380]
Finally stateless functional components working in 0.16.0-rc, props to rn team :)

can we have functional components support in  `AppRegistry.registerComponent ` ?

**Comment by mkotsbak** [comment]
I don't see the need for functional component in Scala. What do you gain over just using a function like this: https://github.com/mkotsbak/Javabin-SriReactNativeDemo/blob/master/mobile/src/main/scala/sri/templates/crossplatform/mobile/AlcoMeter.scala#L26-L30

I see maybe in JS you get types and default values, but that is not needed in Sri, as you have both types, default values and named parameters:

```
  def beerImages(numberOfBeers: Int = 1) = {
    View(style = styles.beers)(
      (0 to numberOfBeers - 1) map beerImage
    )
  }
```

**Comment by mkotsbak** [comment]
See also https://news.ycombinator.com/item?id=10348391

**Comment by chandu0101** [comment]
@mkotsbak  i think u posted in wrong thread ;)

**Comment by mkotsbak** [comment]
Ah sorry, yes the above comment was supposed to be for the Sri project.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/support-stateless-function-components-in-appregistryregistercomponent-

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
