### ISSUE TITLE
Naming collision detected

### ISSUE THREAD

**Issue by scriptjs** [facebook/react-native#4402]
#3558 is without a resolution and with some work arounds that may or may not work.

**Comment by scriptjs** [comment]
I have rn-cli.config.js and others the blacklist approach but they don't seem to do anything.

http://stackoverflow.com/questions/30049111/how-to-blacklist-specific-node-modules-of-my-packages-dependencies-in-react-nat

http://stackoverflow.com/questions/32798701/is-there-a-way-to-make-react-native-ignore-some-files-that-not-to-bundle-them

**Comment by scriptjs** [comment]
@satya164 Any movement on this?

**Comment by satya164** [comment]
cc @brentvatne

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/naming-collision-detected

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
