### ISSUE TITLE
first click is of no effect when focusing on TextInput and then click elsewhere

### ISSUE THREAD

**Issue by Sandon** [facebook/react-native#4422]
![picture](https://cbu01.alicdn.com/cms/upload/2015/172/005/2500271_81076344.png)

as showed above, focus on the TextInput, then click elsewhere. 
The first click on green area is of effect.
The first click on red area is * of no effect * ( it's a ListView ). The same thing happens on the first click of hardware back button on Android when previously focusing on TextInput.

Is it a bug or that I omit something ? ( the version of react-native I use is 0.16.0-rc )

**Comment by satya164** [comment]
You need to add `shouldKeyboardPersistTaps={true}` on the `ListView`.

**Comment by satya164** [comment]
You need to add `keyboardShouldPersistTaps={true}` on the `ListView`.

There's an awesome place to ask question like this one: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see your question, you can vote on answers and mark question as answered etc. This lets us keep a list of bug reports and feature requests on github and especially [Product Pains](https://productpains.com/product/react-native/?tab=top) (again, with voting which is really nice).

If you think StackOverflow works for you please consider posting there instead and closing this issue.

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)

**Comment by Sandon** [comment]
Thanks a lot.
