### ISSUE TITLE
[AlertIOS] Support for Enabling / Disabling Buttons on AlertIOS based on Text Contents

### ISSUE THREAD

**Issue by cancan101** [facebook/react-native#4430]
Along the lines of the [SO question](http://stackoverflow.com/questions/24474762/check-on-uialertcontroller-textfield-for-enabling-the-button), provide function to enable / disable buttons in `AlertIOS` based on text contents.

**Comment by skevy** [comment]
@cancan101 This is an interesting idea. Marking this as community responsibility, as I don't think this is something that the core team would get to in the near future, but I can see its utility.

Seems like the biggest hurtle hear would be the imperative nature of the AlertIOS code. Right now, it's meant to perform one simple action. But it could be made into something a bit more declarative and "React-y". I'm not sure if that has a place in core...it might be better solved as an external module that provides a more robust wrapper around UIAlertView (or perhaps even implement something cross-platform). Though, if the API ended up being really good, I could see it living in React Native proper in the future.

Perhaps this is something you could take on? :)

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/alertios-support-for-enabling-disabling-buttons-on-alertios-based-on-text-contents

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
