### ISSUE TITLE
Make Babel major version configurable

### ISSUE THREAD

**Issue by idibidiart** [facebook/react-native#4437]
Given the following issues popped up in Babel 6:

1. [Decorators cannot be used with RN 0.16..0-rc] (https://phabricator.babeljs.io/T2645)
2. [Can't export default class that extends base class] (https://phabricator.babeljs.io/T2694)

The first one being a serious issue as a lot of RN projects out there rely on @autobind decorator (and having to replace with the ugliness that is .bind(this) everywhere is just too much to ask for given that a fix in is the works) 

So, I'm wondering if it would be wise to allow the version of Babel used by RN to be configurable (maybe within the range of one major version number e.g. 5.x to 6.x)

**Comment by ide** [comment]
I don't think the Babel version will be configurable because Facebook's infra has already moved on and it's like steering a big ship. Babel touches too many things for it to simply be a matter of changing the version number in package.json.

The decorators are a big issue. I'm going to work on it myself since the ecosystem needs something out there, but would appreciate help from someone who's written Babel plugins before.

**Comment by idibidiart** [comment]
@sebmck @loganfsmyth FYI

That would be great @ide 

Will be posting all future feature requests to ProductPains.
