### ISSUE TITLE
Expect custom baseline function to not return NaN

### ISSUE THREAD

**Issue by rushikeshc7** [facebook/react-native#44406]
The App gets crashed when I clicked on a particular button. When I pressed that button, abort() function gets called from yoga.cpp file. The App is working fine in android, only getting this issue while running on iOS. Check the following image for reference.
![Screenshot 2019-09-04 at 8 38 58 PM](https://user-images.githubusercontent.com/46434036/64267480-14856600-cf54-11e9-887d-e067fd4a8dac.png)
It shows "Expect custom baseline function to not return NaN" this error in debug window. I am not getting why this is happening, please help me with the solution.

**Comment by j-piasecki** [comment]
I tried to dig into the crash from the [second comment](https://github.com/facebook/react-native/issues/44406#issuecomment-2093708800). It's still reproducible on the current `main` branch and it looks like it's caused by the baseline being calculated without the text node being measured first.

I'm not sure if that's the real cause but removing [this early return](https://github.com/facebook/react-native/blob/756f89aa59cba78cba39b22a338a3a48bcb38f1b/packages/react-native/ReactCommon/yoga/yoga/algorithm/CalculateLayout.cpp#L1299) prevents the crash from happening.

**Comment by hughyyyy** [comment]
I am having this issue with alignItem: 'baseline' on Yoga crash too. This should be looked into.

**Comment by vijayaragavanmr-stack** [comment]
> [@rushikeshc7](https://github.com/rushikeshc7) that code is to replicate the error. The issue is by the style `alignItems : 'baseline'`, if you remove that style the error disappears. Search in your code where you are using a component with `alignItems : 'baseline'` style and have a child (in any level) with `width `and `height `styles at the same time, and try replace to `alignItems : 'flex-end'` in the parent, or remove width o height in the child, this solve the issue to me.

the issue has fixed thanks for the simple solution.
