### ISSUE TITLE
Array.from polyfill should call iterator's optional return() method on exceptions

### ISSUE THREAD

**Issue by appden** [facebook/react-native#4443]
If the mapping function throws an exception, then the iterator's `return()` method should be called (if present) according to the ES6 spec.

**Comment by satya164** [comment]
@appden A PR will be great.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/arrayfrom-polyfill-should-call-iterators-optional-return-method-on-exceptions

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
