### ISSUE TITLE
First example on README is broken

### ISSUE THREAD

**Issue by danawoodman** [facebook/react-native#445]
From what I can tell, the [first example on the README](https://github.com/facebook/react-native#native-ios-components) is broken and omits required props that will fail if used as is. This might be a point of confusion for new users, as it was for me.

`icon`, `onPress`, `selected` are all required props but are missing from the example, perhaps they could be added  in?

https://github.com/facebook/react-native/blob/72d3d724a3a0c6bc46981efd0dad8f7f61121a47/Libraries/Components/TabBarIOS/TabBarItemIOS.ios.js

**Comment by kennydee** [comment]
Got the same problem, and it confused me, also because i can't find a good way to deal with the icon field.

The example in the UIExplorer project is pretty strange with the _ix_DEPRECATED function call :)
https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/TabBarExample.js

So i also think, a quick fix + clarification on this example should help new users.

Thanks

**Comment by kennydee** [comment]
I think the main point of this issue is not valid anymore because of all the evolution made on the TabBarIOS and UIExplorer project. so this issue can be closed

I also think, as @danawoodman did, that this first example of the website lack a lot of things to not confuse new users: see this other issue #759
