### ISSUE TITLE
Javascript and Native development interdependency?

### ISSUE THREAD

**Issue by MattFoley** [facebook/react-native#4452]
I'm starting to move deeper into RN distribution and I was curious about the interdependency of the JS and the native sides of React Native. 

Should developers always plan on updating the native libraries of React Native when updating the JS side? Will there be a time in the future when the Javascript side of React Native will be updated more actively than the native side? 

It occurs to me that the native side of React Native could reach a point of relative stability prior to the JS, and that React Native itself could even be updated without Native code changes. Are there any plans for this?

Thanks!

**Comment by satya164** [comment]
I usually push updates to JavaScript side when no native APIs have changed. If Native APIs have changed, I do a full app update.

**Comment by ide** [comment]
I don't think that's the right level of separation -- there are three layers:

App JS
RN JS
RN native

Today, due to technical reasons, the App JS and RN JS are bundled together. But conceptually it's correct to draw a box around the RN JS and RN native pieces, both of which make up the public API. It's the App JS's interfacing with the RN pieces that we want to stabilize.

So I think the question to ask is: will the public API -- regardless of whether its written in JS or native -- become stable? I think the answer is yes but it's probably best for RN to move fast at this time for at least six months to a couple years.

One way to achieve stability faster is to make this react-native truly a repo for core functionality and move things like ListView, Navigator, TouchableX, maybe even Image and Text into their own packages. That way the API of Navigator could drastically change without forcing RN Core to do a major version bump.

But right now for pragmatic reasons, the contents of this repo is code that Facebook maintains because it's too much overhead to version smaller projects separately, and monolithic repos are much easier to work with than tons of smaller repos if you're a single organization.

**Comment by brentvatne** [comment]
Closing this because answers here seem complete :)
