### ISSUE TITLE
[TextInput] Text disappears on blur 

### ISSUE THREAD

**Issue by yuyaohshimo** [facebook/react-native#4456]
1. Type text in TextInput 1 with Japanese keyboard.

  ![simulator screen shot dec 1 2015 11 53 42 am](https://cloud.githubusercontent.com/assets/3455528/11491236/5981ac26-9823-11e5-8791-e25814e02685.png)

2. Blur TextInput 1 and focus TextInput 2 without tapping `確定` (enter) button. Text in TextInput 1 disappears. (If tap `確定` (enter) button before blurring TextInput1, text does not disappear)

  ![simulator screen shot dec 1 2015 11 54 30 am](https://cloud.githubusercontent.com/assets/3455528/11491288/df7293cc-9823-11e5-9918-ffdaddec71c7.png)

**Comment by dannibje** [comment]
Im having this problem as well.  Runnig this.refs.textInput2.focus() in the onChange function for textInput1, causes it to clear.

**Comment by hubertwang** [comment]
I have exactly the same problem as @dannibje . Text in input1 disappeared when call input2.focus().

**Comment by rclai** [comment]
Is this by any chance related to [this issue](https://github.com/facebook/react-native/issues/4845)?

**Comment by geirman** [comment]
@yuyaohshimo is this issue still valid? I realize it's been a while, @rclai has asked you a question that's gone unanswered, and perhaps this has been fixed in code or in a later release. If the issue persists, perhaps you could help us by creating an example we can execute and inspect ourselves on rnplay.org or something we can clone.

**Comment by geirman** [comment]
@facebook-github-bot no-reply
