### ISSUE TITLE
[Android] Emulator displays weird error messages

### ISSUE THREAD

**Issue by tomazahlin** [facebook/react-native#4471]
During developing, for almost any kind of mistake that I do in the code, for example:

- Forget to import components which are used inside render() method
- Comments inside return function in the render() method
- Using undeclared variables
- Trying to access unexisting property of an object
And lots more... 

I always get this error message:

TypeError: expected dynamic type 'double', but had type 'null' (constructing arguments for RKUIManager.updateView at argument index 0)

This error has absolutely no useful information and instead I should get the right error displayed, for example with the file name and line (position) where the mistake is.

Maybe it is just me doing something wrong, but I also tried different things, for example putting console.log(test); (where test is not declared) in different parts of application. Sometimes I get the right error saying that the test is not defined, sometimes I get the red error page with the above message, sometimes no error at all and app just breaks.

Can someone explain me what I am doing wrong, or if this is a bug, I think it is a very important one, because it is impossible to develop with such a framework.

Please help.

Tomaž

**Comment by satya164** [comment]
Hey @tomazahlin , Thanks for reporting the issue. We definitely need better error messages for this. BTW you should consider using a linter like [ESLint](http://eslint.org) to avoid these kinds of errors.

**Comment by mkonicek** [comment]
Can you post this on product pains so people can vote on it?

See the comment above:

> If this is a feature request or a bug that you would like to be fixed by the team, please report it on Product Pains. It has a ranking feature that lets us focus on the most important issues the community is experiencing.

**Comment by rayshih** [comment]
I encounter this error message today. And I found in my case, it's related to animation.
It's like: Animation render was triggered after the view disappeared.
If I set the transform value to fix number, then it won't crash anymore.

**Comment by mkonicek** [comment]
cc @kmagiera in case it's related to animations.

**Comment by johannesspohr** [comment]
Am I the only one who is extremely annoyed by this? I keep getting this error for all kinds of reasons and it gives absolutely no information about where to start debugging. About 80 % of development time in react native I am commenting out components and reinserting them to try to figure out which component caused the error.

**Comment by tomazahlin** [comment]
@johannesspohr Exactly the same case for me. I also spent so much time commenting things out during development. But I got used to it, and now I find mistakes faster, because I know what to search for. It is extremely important that the React Native team improves the error messages, I think everyone could agree with that.

**Comment by kmagiera** [comment]
From the description it looks like the issue is with `UIManager.updateView` method that receive `null` instead of view tag. If this happens as a part of animation its most likely caused by the call here: [NativeMethodsMixin.js#L123](https://github.com/facebook/react-native/blob/6f1417c84982e0705912b57bf9d1aaaf1476d7d9/Libraries/ReactIOS/NativeMethodsMixin.js#L123) which means that `findNodeHandle` call returns `null`. From the implementation of [findNodeHandle](https://github.com/facebook/react-native/blob/62e8ddc20561a39c3c839ab9f83c95493df117c0/Libraries/ReactNative/findNodeHandle.js) it looks the method will return `null` if the component has not been mounted (which is true as from your description it seems like you experience this issue when you have an error in your `render` method that prevents component from being mounted).


@rayshih @tomazahlin will you be able to provide a simple 1 file app that would illustrate this problem? It's also weird that you are not seeing this on iOS as it looks like we also have that constraint on the iOS bridge implementation that prevents from passing `null` to `updateView` ([see it here](https://github.com/facebook/react-native/blob/f7df3bb78abcccffabdffb813ef5f117d9521713/React/Modules/RCTUIManager.m#L878)) and the JS should run the same on both platforms in the case described by you

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-emulator-displays-weird-error-messages

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
