### ISSUE TITLE
[Navigator] Interactive Pop Gesture Doesn't "Lock" Native View Being Popped

### ISSUE THREAD

**Issue by marcshilling** [facebook/react-native#4472]
Setup: my `Navigator` is pushing a React Native view which wraps a Native UI (Objective-C) view. When I then drag from the left edge to pop said view, the view continues to receive pointer events during the interactive pop. Check the gif: http://i.imgur.com/GdNE7xN.gifv. I would expect that view to be "locked" as soon as I begin the pan gesture.

Interestingly, this doesn't happen when interactively popping full-React views. It seems like the `pointerEvents='none'` isn't getting passed down to native land. Although it is strange that it's happening here where my native UI view is wrapped in a `<View>`

**Comment by marcshilling** [comment]
Tagging @skevy cause he told me to.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/navigator-interactive-pop-gesture-doesnt-lock-native-view-being-popped

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
