### ISSUE TITLE
Scroll View Issue

### ISSUE THREAD

**Issue by georgi-kovachev** [facebook/react-native#4480]
I am having layout issue with ScrollView
When I use View it was displaying like this.
http://collabshot.com/show/Kis4aJ

http://pastebin.com/Yagt8X38

When I changed it to scrollview
http://collabshot.com/show/f3lEtM

http://pastebin.com/zK0HnjaN

And here are the styles
content: {
    flex: 1,            
    paddingTop: 10,
    paddingLeft: 10,
    paddingRight: 10,
    flexDirection: 'column',
    backgroundColor: '#000000',
    
  },
  transmit: {
    height: 100,    
    borderWidth: 1,    
  },

  messages: {
    flex: 1,
    backgroundColor: '#ffff00',
    
  }

Looking for help.
Thanks

**Comment by satya164** [comment]
Hey @georgi-kovachev . thanks for reporting this! You can try setting the `contentContainerStyle` of the `ScrollView`.

BTW, there's an awesome place to ask question like this one: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see your question, you can vote on answers and mark question as answered etc. This lets us keep a list of bug reports and feature requests on github and especially [Product Pains](https://productpains.com/product/react-native/?tab=top) (again, with voting which is really nice).

If you think StackOverflow works for you please consider posting there instead and closing this issue.

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)
