### ISSUE TITLE
a require() inside a string will break the packager

### ISSUE THREAD

**Issue by gre** [facebook/react-native#4495]
Following code will make the packager looking up for a `"foo"` package

```
console.log('require("foo")');
```

My use-case was for console.logging some warning:

```js
console.warn(`Please add this in your file: require("foo")`);
```

workaround is to do this uglyness:

```js
console.warn(`Please add this in your file: ${"require"}("foo")`);
```

**Comment by skevy** [comment]
oooo! good catch. Needs to be fixed here: https://github.com/facebook/react-native/blob/master/packager/react-packager/src/DependencyResolver/lib/replacePatterns.js

This is kind of tough regex to write because it's got so many edge cases. It would be great if we already knew the AST of the file at this point from babylon, as we could use that to find the require rather than an imperfect regex. I feel like that probably comes with a performance issue though, though I'm not sure how big of one (but probably a lot just to search for requires)...

cc @martinbigio

**Comment by cpojer** [comment]
We can't really depend on ASTs for this. In jest, for example, we might not even parse the source into an AST at all.

**Comment by martinbigio** [comment]
@skevy I actually have a facebook internal pull request to introduce an internal transforms pipeline that integrates with the external transformer. This should help here. cc @davidaurelio

**Comment by skevy** [comment]
@cpojer I totally understand...really just an idea (an admittedly not fully thought out one)

@martinbigio that's great. We'll keep this open, and if the PR lands and you happen to remember, ping me on it! :)

**Comment by jsierles** [comment]
@martinbigio did the internal PR make it for this? I'm wondering if this issue should stay open, given there is a workaround and it's probably not a common requirement.

**Comment by martinbigio** [comment]
@gre does this still repros? I think we may have fixed this already

**Comment by gre** [comment]
this is fixed on `master`

**Comment by davidaurelio** [comment]
right, it should work from revision 9d09efdd53017877328a9fbaef2fd2cfd31352fc on

**Comment by gre** [comment]
great, thanks!
