### ISSUE TITLE
[Need Help][Community] Unable to connect to chrome debugger from Device/Genymotion

### ISSUE THREAD

**Issue by bozzmob** [facebook/react-native#4500]
Hi all,

I am having the problem where I am not able to debug my application using chrome debugger. It is too sluggish and heavy to use android studio and use its terminal. Being a javascript styled application, Android Studio debugging doesn't suit well.

I am able to see the device in chrome(advanced settings). But, when I click on "Debug in Chrome", I get the following error-

![screenshot from 2015-12-02 20 34 19](https://cloud.githubusercontent.com/assets/1252941/11534532/34f9f134-9935-11e5-8759-b82fe25c8a95.png)

Here is my devices page on chrome-

![screenshot from 2015-12-02 20 38 18](https://cloud.githubusercontent.com/assets/1252941/11534534/36f874f6-9935-11e5-9a3f-b9aa1757ad74.png)

My Development Environment-
Ubuntu 14.04
Chrome 46.0.24(64bit)

Please help me with this issue.

**Comment by bozzmob** [comment]
Better screenshot-

![screenshot from 2015-12-02 20 56 07](https://cloud.githubusercontent.com/assets/1252941/11534889/31ba86c6-9937-11e5-9c32-75e6bbcfbd7c.png)

**Comment by satya164** [comment]
Hey and thanks for reporting this!

There's an awesome place to ask question like this one: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see your question, you can vote on answers and mark question as answered etc. This lets us keep a list of bug reports and feature requests on github and especially [Product Pains](https://productpains.com/product/react-native/?tab=top) (again, with voting which is really nice).

If you think StackOverflow works for you please consider posting there instead and closing this issue.

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)

**Comment by bozzmob** [comment]
Yes. @satya164 Thanks :) I will consider.

**Comment by bozzmob** [comment]
Tracking the same issue on [Stackoverflow](http://stackoverflow.com/questions/34058073/unable-to-connect-to-chrome-debugger-from-device-genymotion)
