### ISSUE TITLE
Adding custom fonts in react native cli not working (using yarn as package manager )

### ISSUE THREAD

**Issue by indresh149** [facebook/react-native#45072]
### Description

I have applied the same steps like previously i am doing to add fonts but not working with yarn package manager

### Steps to reproduce

1. Add custom fonts in assets/fonts
2. Add react-native.config.js file
3. Run the project

### React Native Version

0.74

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
No
```

### Stacktrace or Logs

```text
No
```

### Reproducer

No

**Comment by cortinico** [comment]
Hi,
Thanks for reporting this issue.

It seems like this issue is actually unrelated to React Native core. Please open this issue against this other repository:

https://github.com/react-native-community/cli/issues

I'll be closing this but please comment if the other repo points back to us as a issue in the core of React Native.

**Comment by indresh149** [comment]
@cortinico Thanks for the guidance.
