### ISSUE TITLE
v0.15.0 - Inaccurate error with "Looks like you installed react-native globally"

### ISSUE THREAD

**Issue by niftylettuce** [facebook/react-native#4515]
Seems to be an odd bug when running with `npm start` vs. `react-native start` (perhaps due to it using `react-native` from the `./node_modules/.bin/react-native` folder?

![screen shot 2015-12-02 at 9 49 50 pm](https://cloud.githubusercontent.com/assets/523141/11550504/aa1c7000-993e-11e5-83f7-602ff6d67282.png)
![screen shot 2015-12-02 at 9 48 22 pm](https://cloud.githubusercontent.com/assets/523141/11550505/aa200260-993e-11e5-8fd4-6ffef8037068.png)

**Comment by niftylettuce** [comment]
This is from a fresh `react-native init`.

**Comment by niftylettuce** [comment]
You can also see I don't have it installed globally per the recommended uninstallation of global package (so this is why I mention it is inaccurate).

**Comment by satya164** [comment]
@niftylettuce Which package do you have installed globally? `react-native` or `react-native-cli`?

**Comment by niftylettuce** [comment]
react native cli

**Comment by ide** [comment]
I can repro this too but not sure about the cause.

**Comment by niftylettuce** [comment]
I think its because package.json loads node_modules/.bin as environment
commands to use

**Comment by altern8tif** [comment]
I'm getting the same error on `npm@3.5.0` and `react-native-cli@0.1.7`

**Comment by gre** [comment]
one workaround is to `npm install --save-dev react-native-cli`

**Comment by jjshammas** [comment]
@gre thank you so much for that workaround. Fixed the issue for me.

I'm only seeing this problem when building on a Mac via Jenkins. Not locally on any dev machine.

**Comment by svkurowski** [comment]
Okay, some steps to reproduce (Mac OS X 10.11.2, npm 3.5.2, nodejs 5.3.0).

```bash
cd /tmp
npm install -g react-native-cli
react-native init test
cd test
ls -l /usr/local/bin | grep react # react-native -> ../lib/node_modules/react-native-cli/index.js
ls -l node_modules/.bin | grep react # react-native -> ../react-native/local-cli/wrong-react-native.js
npm run start # Looks like you installed react-native globally, maybe you meant react-native-cli?
```
This happens because npm prepends `node_modules/.bin` to the `PATH` environment variable.
As suggested above we try to fix this:
```bash
npm install --save-dev react-native-cli
ls -l /usr/local/bin | grep react # react-native -> ../lib/node_modules/react-native-cli/index.js
# bingo, it's working
```
However, will this also work on a fresh machine?
```bash
rm -Rf node_modules
npm install
ls -l node_modules/.bin | grep react # react-native -> ../react-native/local-cli/wrong-react-native.js
# Oops, not working again
```
At this moment, `package.json` looks like this:
```json
{
  "name": "test",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start"
  },
  "dependencies": {
    "react-native": "^0.18.0-rc"
  },
  "devDependencies": {
    "react-native-cli": "^0.1.10"
  }
}
```
Remove `react-native-cli` from the `devDependencies` and insert it **before `react-native`** as a normal dependency like this:
```json
  "dependencies": {
    "react-native-cli": "^0.1.10",
    "react-native": "^0.18.0-rc"
  }
```
Then run
```bash
rm -Rf node_modules
npm install
ls -l /usr/local/bin | grep react # react-native -> ../lib/node_modules/react-native-cli/index.js
# bingo, it's working
```
Putting `react-native-cli` after `react-native` does also not work. The binary names from `react-native-cli` and `react-native` have a conflict, apparently `npm` prefers the on from the first listed normal (non-dev) dependency.

So until this gets fixed, the only reliable way seems to be to either list `react-native-cli` before `react-native` in the dependencies (however I don't know whether this behavior of `npm` is undefined) or install `react-native-cli` globally and run `react-native start` instead of `npm run start`.

**Comment by satya164** [comment]
cc @mkonicek

**Comment by mkonicek** [comment]
Can you try:

    $ npm uninstall -g react-native-cli
    $ npm install -g react-native-cli


    $ react-native --version
    # Should print:
    react-native-cli: 0.1.10
    react-native: n/a - not inside a React Native project directory

**Comment by mkonicek** [comment]
`npm start` is defined in your package.json, `"start": "react-native start"` is wrong due to a bug I introduced in an older version of the global CLI, please change that to:

    {
      "name": "MyApp",
      "version": "0.0.1",
      "private": true,
      "scripts": {
        "start": "node node_modules/react-native/local-cli/cli.js start"
      },
      "dependencies": {
        "react-native": "rn_version_you_are_using"
      }
    }

The new global CLI will generate package.json like that, sorry about the breakage!

To upgrade:

     npm uninstall -g react-native-cli
     npm install -g react-native-cli

(and fix package.json for all your apps)

If this doesn't resolve the issue let's reopen.

I don't understand why `"react-native-cli"` would be in the dependencies or dev dependencies of your app. Your app doesn't need the CLI.

**Comment by wootwoot1234** [comment]
@mkonicek  Thanks!

**Comment by kaminskypavel** [comment]
@mkonicek thanks for sharing!

**Comment by mirza99** [comment]
I had the same issue even after uninstalling `react-native` and `react-native-cli`. When looking in `/usr/local/lib/node_modules` there was no `react-native-*` 
I use nvm so the modules was installed under `~/.nvm/versions/node/v8.0.0/bin/` (you have to look in your currently used version). Hope it helps
