### ISSUE TITLE
[iOS] AlertIOS can't work in componentDidMount, RN verison is 0.15.0

### ISSUE THREAD

**Issue by KeithZhang** [facebook/react-native#4528]
![image](https://cloud.githubusercontent.com/assets/2190059/11557289/e588aae8-99e6-11e5-9278-06a5a7c979db.png)

**Comment by ranyefet** [comment]
+1
I also get this error *sometimes*. using v0.15

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/ios-alertios-cant-work-in-componentdidmount-rn-verison-is-0150

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
