### ISSUE TITLE
Platform.constants.reactNativeVersion.prerelease should be a string

### ISSUE THREAD

**Issue by necolas** [facebook/react-native#45393]
### Description

The latest 0.75 RC has prerelease as a number, `0`, but it should be typed and set as a string.

### Steps to reproduce

https://github.com/facebook/react-strict-dom/pull/163

### React Native Version

0.75.0-rc4

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
.
```

### Stacktrace or Logs

```text
.
```

### Reproducer

https://github.com/facebook/react-strict-dom/pull/163

**Comment by NickGerleman** [comment]
This was fixed by https://github.com/facebook/react-native/commit/95d9cdf228e33d5651f41ebf5e14e80962fae118

**Comment by necolas** [comment]
Does that commit need to be cherry picked for 0.75 then? The current RC is setting the value to 0

**Comment by NickGerleman** [comment]
If we want the fix in 0.75 RCs, then we would want to make a pick request here: https://github.com/reactwg/react-native-releases/issues/new?assignees=&labels=Type%3A+Pick+Request&projects=&template=pick_request_form.yml&title=%5B0.XX%5D+Title

The issue would also naturally resolve itself in final 0.75 release (since it's not a prerelease), or 0.76 RC.

**Comment by necolas** [comment]
> The issue would also naturally resolve itself in final 0.75 release (since it's not a prerelease), or 0.76 RC.

Ok that works. Thanks for the clarification
