### ISSUE TITLE
Extremely difficult to press a custom font icon

### ISSUE THREAD

**Issue by rclai** [facebook/react-native#4569]
This is iOS, RN 0.15.0, on a new gen iPod.

Not sure if anyone else is dealing with this.

I'm using a custom icon set from Fontastic, not from the react-native-icons library. I included them manually as a TTF and in the Info.plist.

I have one of these:

```jsx
<TouchableOpacity onPress={...}>
  {/* a wrapper component that wraps a Text component with fontFamily: "my-icons" */}
  <Icon icon="ellipses" /> 
</TouchableOpacity>
```
The presses are almost impossible to trigger to the point that in order for them to work consistently, I have to use my left index finger and press it at a specific angle.

I don't have fat fingers.

I even gave the TouchableOpacity a hefty padding, a background color of red, and it did help a bit, however, the edges are not very responsive, it still has to be a touch right in the center.

**Comment by satya164** [comment]
Hey @rclai , thanks for reporting this!

You could try playing with padding/wrapping the icon inside a `<View />` to see if this works.

There's an awesome place to ask question like this one: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see your question, you can vote on answers and mark question as answered etc. This lets us keep a list of bug reports and feature requests on github and especially [Product Pains](https://productpains.com/product/react-native/?tab=top) (again, with voting which is really nice).

If you think StackOverflow works for you please consider posting there instead and closing this issue.

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)
