### ISSUE TITLE
[NavigatorIOS] [PushNotification] Looking for a way to hook into push notifcation and display certain route

### ISSUE THREAD

**Issue by myusuf3** [facebook/react-native#4571]
We currently sending out push notifications for various things in our app. I was looking for a way to go to certain route when the app is opened from a push notification so it shows data relevant to the push notification. 

We are currently using `NavigationIOS`, and I know I can hook into push notifications from `AppDeletegate` is there a way there to hook into route stack?

**Comment by satya164** [comment]
Hey @myusuf3 . You could get the initial notification with `PushNotificationIOS.popInitialNotification()` (http://facebook.github.io/react-native/docs/pushnotificationios.html#popinitialnotification) and parse the URL from which the app was opened, then set the `initialRoute` property of the navigator accordingly (http://facebook.github.io/react-native/docs/navigator.html#initialroute). However I've not tested this.

There's an awesome place to ask question like this one: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see your question, you can vote on answers and mark question as answered etc. This lets us keep a list of bug reports and feature requests on github and especially [Product Pains](https://productpains.com/product/react-native/?tab=top) (again, with voting which is really nice).

If you think StackOverflow works for you please consider posting there instead and closing this issue.

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)

**Comment by skevy** [comment]
Closing for now, but @myusuf3 feel free to link to your stack overflow post here to make it easier for people to find if they come searching for your problem on this issue tracker!
