### ISSUE TITLE
Horizontal Scrollview not scrolling

### ISSUE THREAD

**Issue by isikfsc** [facebook/react-native#4589]
I have an example [here](https://rnplay.org/apps/BcHMPQ).
In the scrollview of the starting app scene, the library, scrolling does not work properly. Scrollview, in line 84, is scrollEnabled, horizontal, has pagingEnabled (to simulate tabs), and directionalLockEnabled.

Is that a bug or related to scrollview issues exist, or I just miss something?

**Comment by brentvatne** [comment]
The problem is that you are rendering a bunch of `ListView`s inside of the `ScrollView`. Each `ListView` also has its own `ScrollView`. So you might want to reconsider how you are organizing it, maybe you just have a `View` on the outside and `ListViews` that are horizontally scrollable on the inside.

Either way, this isn't a bug as far as I can tell, so it's better suited for StackOverflow if you have any more questions :) Good luck!
