### ISSUE TITLE
0.16.0: `[plugin]` has no propType for native prop `[plugin].renderToHardwareTextureAndroid` of native type `boolean`

### ISSUE THREAD

**Issue by jforaker** [facebook/react-native#4605]
Android:  After updating to 0.16.0 many third party plugins including https://github.com/brentvatne/react-native-video, https://github.com/brentvatne/react-native-linear-gradient, https://github.com/mapbox/react-native-mapbox-gl are causing the errors to be thrown:

``RCTMapbox` has no propType for native prop `RCTMapbox.renderToHardwareTextureAndroid` of native type `boolean``

After manually setting the `renderToHardwareTextureAndroid` Proptype in the plugin, it proceeds to throw more Proptype errors for all of the following :

```
  renderToHardwareTextureAndroid

  onLayout

  accessibilityLiveRegion

  accessibilityComponentType

  importantForAccessibility

  accessibilityLabel

  testID
```

Again manually adding in the plugin seems to make the issue go away, but in some cases (Video / LinearGradient @brentvatne ) the plugin completely stops working. Obviously I do not want manually edit anything in `node_modules` so this should be addressed.

**Comment by brentvatne** [comment]
This seems to have been introduced with [this commit](https://github.com/facebook/react-native/commit/7cd7591f0466bc8aca617f75f5fd2dee53712846) - in particular I think it is [this line](https://github.com/facebook/react-native/commit/7cd7591f0466bc8aca617f75f5fd2dee53712846#diff-83f7cd6ecb04a71192394763ab6fcb87L43). cc @mkonicek

**Comment by brentvatne** [comment]
Nevermind @jforaker - I looked into this myself :)

**Comment by sospartan** [comment]
+1

**Comment by kmagiera** [comment]
We've migrated all internal RN components to declare their propTypes inheritance explicitly in dd09c88571f5397346903e0e8c73224cbf40c862. This allows for better control on which props can be used. In order to make those third-party components to work it should be sufficient to add `...View.propTypes` to the map of `propTypes` in the component definition (see dd09c88571f5397346903e0e8c73224cbf40c862 for an example).

I apologize as this should've been marked as a breaking change so that ppl have time to update their libs before the release.

**Comment by brentvatne** [comment]
Ahh, that makes sense. Thanks @kmagiera! I updated the release notes here: https://github.com/facebook/react-native/releases/tag/v0.16.0
