### ISSUE TITLE
[iOS] [Image] GIFs are faded out after switching and returning to app

### ISSUE THREAD

**Issue by feichngr** [facebook/react-native#4606]
Switching from an app build with React Native v0.16 to a different one causes displayed GIFs (both when loaded from asset resources or via require) to fade out and not be displayed again.

Causing an update of the Image component (i.e. by modifying the style) makes the GIF appear again.

**Comment by feichngr** [comment]
Here is a small demo project to demonstrate the problem:
[feichngr/react-native-4606](https://github.com/feichngr/react-native-4606)

**Comment by brentvatne** [comment]
cc @nicklockwood

**Comment by nicklockwood** [comment]
Makes sense: it's a CAAnimation under the hood, and those get cancelled when the app is backgrounded. I'll need to add some logic to resume the animation again after app returns to foreground.

**Comment by cantlin** [comment]
Just a note to say I stumbled on this one too, and am also hacking around the problem by arbitrarily changing the component's state.

**Comment by jwyld** [comment]
There's actually a couple problems.  First, the CAKeyFrameAnimation needs to be saved and re-added to the layer on the image view.  Second, the animation is set on the image during load and decode, but when the animation is added to the layer, the image itself is not passed along.  This results in the image view's image not having the CAKeyFrameAnimation.  The image with the animation is only valid during the lifetime of the setImageBlock.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/ios-image-gifs-are-faded-out-after-switching-and-returning-to-app

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
