### ISSUE TITLE
[Docs] Missing information about properties on params passed into callbacks

### ISSUE THREAD

**Issue by inickel** [facebook/react-native#4608]
when i read docs like `http://facebook.github.io/react-native/docs/textinput.html`
the TextInput component;
when i declare the props with the name of onFocus, onBlur....eg. 
there have nothing about the event function's arguments description ,
and i have to print all arguments in the console's window, can we put some more details just like:
```onBlur``` :```function (event:object)```
```event argument:description```
```Callback that is called when the text input is blurred```

**Comment by oviava** [comment]
@brentvatne I would love to pick this up. I'm having issues understanding how I would tag the properties for the appropriate docs to be generated. Should I just add as a comment underneath


```
onBlur function 

Callback that is called when the text input is blurred

function(event: object)
```

ideally would want something like

```
onBlur function (event: object)

Callback that is called when the text input is blurred
```

**Comment by satya164** [comment]
@oviava I don't think docs are generated for arguments right now. May be we need to manually write them down for now.

**Comment by oviava** [comment]
was just checking react-docgen - i'm 99% sure there's no way for this to be parsed right now. will literally have to change every comment to include the information on the callback

**Comment by oviava** [comment]
for this particular issue - maybe create a events doc page specifically for rn? https://facebook.github.io/react/docs/events.html

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/docs-missing-information-about-properties-on-params-passed-into-callbacks

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
