### ISSUE TITLE
[Android] 0.16 stable margin/padding messed up

### ISSUE THREAD

**Issue by seph14** [facebook/react-native#4614]
In the newest release 0.16, on Android, margin/padding seem to be messed up, margin are considered as padding. Not sure if this is related to the new shadow stuff.

**Comment by skevy** [comment]
@seph14 thanks for reporting! Could you help us out and give us a test case that would allow us to reproduce this issue?

**Comment by satya164** [comment]
@seph14 Any updates on this?

**Comment by seph14** [comment]
Hi,

sorry for the late response. 

So I was trying to do a quote styling text, and the code was like this:

```javascript
<View style={{marginLeft:-20, marginBottom:20,flexDirection:'row', marginTop:3,paddingTop:6,borderLeftWidth:4,borderLeftColor:#2d2d2d}}>
    <Text>...</Text>
</View>
```

I don't have exactly the code as we worked around this by adding a view just to draw the left border, but in this case, the border will be the same height with the outmost view - i.e. the marginBottom applied to the view is being considered as paddingBottom

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-016-stable-marginpadding-messed-up

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
