### ISSUE TITLE
[Android] Add Integration Tests

### ISSUE THREAD

**Issue by ssnau** [facebook/react-native#4631]
Currently, Integration Tests is only available for iOS and there is no TestModule implementation for Android which make it is hard to write test for android.

It is possible to make [Integration Tests (iOS only)](https://facebook.github.io/react-native/docs/testing.html#integration-tests-ios-only) work both on iOS and Android?

**Comment by brentvatne** [comment]
cc @bestander

**Comment by bestander** [comment]
Now we have Integration tests for Android.
I'll edit docs and close the issue.

**Comment by leafduo** [comment]
:+1:

**Comment by ssnau** [comment]
Great!

**Comment by bootstraponline** [comment]
Updated docs would be nice.

**Comment by bestander** [comment]
A heads up, I work on making [BUCK](http://buckbuild.com) a first class citizen for RN OSS build.
This will make us move faster and it blocks me from doing the docs how e2e tests should be done.
Stay tuned :)

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-add-integration-tests

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
