### ISSUE TITLE
[Navigator] Add willblur and didblur events

### ISSUE THREAD

**Issue by rclai** [facebook/react-native#4643]
It would be nice to implement this because I'm trying to do some navigation bar animations during route transitions.

I know https://github.com/facebook/react-native/issues/1153 addressed it, saying that it may happen, but I just wanted to bump it.

**Comment by Kudo** [comment]
Still waiting https://github.com/facebook/react-native/pull/4419

**Comment by rclai** [comment]
Let's make this happen!

**Comment by rclai** [comment]
On a side-note, one temporary work-around was to use `InteractionManager.runAfterInteractions()`.

**Comment by machard** [comment]
Hi @rclai ,

In the mean time, you can check https://github.com/machard/react-native-advanced-navigation where onFocus, onWillFocus, onWillBlur, onBlur helpers are implemented and navigationBar animation during route transition is also supported.

**Comment by Kudo** [comment]
Another alternative is to use [ExNavigator](https://github.com/exponentjs/ex-navigator) which support `onWillBlur` and `onDidBlur` as well.  You could further check [its implementation](https://github.com/exponentjs/ex-navigator/blob/master/ExRouteRenderer.js#L191-L234) in detail which is very simple and you may implement one by your own if need.

**Comment by rclai** [comment]
Should I put this in the back-burner since this library is going kaput?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/navigator-add-willblur-and-didblur-events

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
