### ISSUE TITLE
[Layout] maxHeight, minHeight, maxWidth, minWidth are unimplemented

### ISSUE THREAD

**Issue by Thomas101** [facebook/react-native#4644]
Hey,

Are there any special circumstances that the new max & min, width & height styles work under? I've been playing around and not been able to get them to take any effect. E.g. multiple combinations of the following all seem to ignore the provided values!

```js
return (
      <View style={{ backgroundColor:'yellow', justifyContent:'space-between', flexDirection:'row'}}>
        <View style={{ backgroundColor:'blue', width:200, height:200, flex:1}}>
        </View>
        <View style={{ backgroundColor:'red', minWidth:50, maxWidth:200, width:150, height:150, minHeight:50, maxHeight:200, flex:1}}>
        </View>
      </View>
    )
```

Thanks very much!

**Comment by ide** [comment]
Last I heard these properties are not correctly implemented in css-layout. We should document that or name the properties something like maxHeight_EXPERIMENTAL...

**Comment by narychen** [comment]
It really doesn't work. 
I try to make a chatting bubble using the flex row layout, maxWidth cannot limit the width of the bubble. The content of bubble always being in one line, overflow and not wrapping.
Only found the column solution https://github.com/facebook/react-native/issues/1438
But it's obviously not perfect and have limits when you want to implement more complicated layout.
When should it be fixed?

**Comment by vitalets** [comment]
+1 for that!

**Comment by colinmegill** [comment]
Just ran into this and found this issue, I seem to be having the problem on web. flexbox seems to work with height, but not minheight.

**Comment by aleclarson** [comment]
+1

**Comment by quqii** [comment]
+1

**Comment by mkonicek** [comment]
Can someone please post this on [Product Pains](https://productpains.com/product/react-native/?tab=top) so that people can vote on this and we know how important this is to the community relative to other feature requests?

**Comment by daemonchen** [comment]
I update `rn` to version `0.20.0`, and then the `minHeight`  doesn't work.

**Comment by mkonicek** [comment]
@daemonchen Yes it's not implemented, please post this on [Product Pains](https://productpains.com/product/react-native/?tab=top) so that people can vote on this and we know how important this is to the community relative to other feature requests.

**Comment by geirman** [comment]
This issue has already been submitted to Product Pains (see: [[Layout] CSS min-height/max-height](https://productpains.com/post/react-native/layout-css-min-heightmax-height) and currently only has 26 votes. Please upvote if this is important to you. Also note that this issue was previously reported and closed #1284. 

I wasn't able to find anywhere in the react-native docs where these attributes were listed, so I don't think there's a opportunity or need to update the documentation to clarify that this hasn't yet been implemented as @ide suggests. If I'm wrong, point me toward the docs and I'll be happy to make the clarification and submit a PR.

I think it's safe to close for the same reason brent closed #1284. this shall live on in product pains for now.

@facebook-github-bot close

**Comment by browniefed** [comment]
@facebook-github-bot close

**Comment by geirman** [comment]
@browniefed I guess the close request has to be made in it's own comment? Didn't realize. Thanks!
