### ISSUE TITLE
[Animated] Animating a View height to zero causes craziness

### ISSUE THREAD

**Issue by rclai** [facebook/react-native#4651]
I'm using a spring animation on the height property of a view. How do you make the spring "not spring", aka, not go to a negative number, when it reaches zero?

**Comment by ide** [comment]
There are configuration properties on `interpolate` in the Animated library called `extrapolateLeft` and `extrapolateRight` that can be set to "clamp". Something like this:

```js
// in your event handler to trigger the spring
Animated.spring(this._animValue, springConfig).start();

// in render()
<Animated.View style={{
  someProp: this._animValue.interpolate({
    extrapolateRight: 'clamp',
    <other fields>
  })
}} />
```

https://github.com/facebook/react-native/blob/master/Libraries/Animated/src/Interpolation.js#L106

In the future, please use resources like Stack Overflow for questions since we try to use the GitHub issue tracker primarily for core bug fixes.
