### ISSUE TITLE
MapView - set annotations title/subtitle/callout to be visible on load

### ISSUE THREAD

**Issue by BenjaminConant** [facebook/react-native#4656]
Greetings, 

I am working on a react native app that uses MapView. I have the map loading and have annotations with coordinates, titles, and subtitles. I can't find any documentation about how I might make an annotation display its title / subtitle / callouts without first clicking on it. Anybody know how to do this? It would be really great if annotations had a prop like `titleVisible` or something! 

this a current definition of an annotation 
```
     {
        longitude: -73.981831,
        latitude: 40.733481,
        title: 'Pickup',
        subtitle: 'a subtitle',
        hasLeftCallout: true,
        hasRightCallout: true,
      }
```

it would be great if I could do something like 

```
     {
        longitude: -73.981831,
        latitude: 40.733481,
        title: 'Pickup',
        subtitle: 'a subtitle',
        hasLeftCallout: true,
        hasRightCallout: true,
        titleVisible: true
      }
```

and have the annotation title be visible when the map loads

**Comment by skevy** [comment]
@BenjaminConant are you working on iOS or Android?

This functionality is specific to each platform...this is one of those things that, if you have the bandwidth, may be better discussed in a PR. There has to be some thought given to both the external API of MapView as well as the internal implementations. There are many features of Maps that are not implemented currently (such as more robust annotation support), and are not currently on FB's roadmap.

Marking this as "community responsibility".

**Comment by af7** [comment]
I would also need this if someone was interested to implement it, thanks!

**Comment by lelandrichardson** [comment]
@af7 this is currently possible using my library: https://github.com/lelandrichardson/react-native-maps

```
somethingHappened() {
  this.refs.markerICareAbout.showCallout();
}
```

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/mapview-set-annotations-titlesubtitlecallout-to-be-visible-on-load

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
