### ISSUE TITLE
[Android] onLongPress event has no timestamp

### ISSUE THREAD

**Issue by seph14** [facebook/react-native#4662]
I'm wondering if this is something missed in 0.16 or there is by design. As I remembered in the 0.16 doc it  states that Android event format has been aligned with iOS.

**Comment by mkonicek** [comment]
@facebook-github-bot bugfix

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-onlongpress-event-has-no-timestamp

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
