### ISSUE TITLE
"react-native run-android" always get error after upgrade 0.16.1

### ISSUE THREAD

**Issue by tbruceyu** [facebook/react-native#4664]
The react-native in Android is a library dependency defined with this line 'compile "com.facebook.react:react-native:0.16.+"' . But after I build my simple project which initialized by "react init" command, I always get the following error:
![e52f1cea-e44e-4cb2-ba3f-61a70b84f4f9](https://cloud.githubusercontent.com/assets/1342575/11678307/77e0d0b6-9e81-11e5-9553-0d8dc44433cb.png)
After revert  react-native library  to 0.16.0, it would be OK.

**Comment by gs-akhan** [comment]
I am sorry to say this. Lot of things break after upgrading 0.14 -> 0.15 -> 0.16..  I am sure lot of people using react-native for production apps and if this kind of issues prevail then it becomes very difficult !!
Thanks

**Comment by skevy** [comment]
@gs-akhan you're right, but currently React Native is not stable software. Things move extremely quickly, and there is only a guarantee of relative stability. The team has chosen this approach over keeping things stable, at the moment, because it allows React Native (as a new and up-and-coming framework) to iterate more quickly. This approach is the reason why Android support is out (and close to being in feature parity with iOS) less than a year after RN iOS's release. Really, this mindset is the reason React Native exists at all. :)

Hopefully, in the next several months, we'll get to a point where the APIs (and feature set) is a bit more stable, and we can follow Semver better, to allow for more dependability and less breaking changes between releases.

**Comment by skevy** [comment]
@tbruceyu it seems like the top of your error got cut off. It looks like it might be some type of packager error. Would you be able to provide more information here?

Thanks.

**Comment by satya164** [comment]
@tbruceyu Any updates?

**Comment by tbruceyu** [comment]
@satya164 Sorry for my delayed response. But I count not reproduce this issue in the same project again after degrading to 0.16 and then recover to 0.16.+. I think I should firstly close this issue. If the same error occur again, I'll produce more and more information and reopen a new issue. Thanks for all your help.
