### ISSUE TITLE
[Q] poor touch performance on android

### ISSUE THREAD

**Issue by lxsameer** [facebook/react-native#4666]
Hi, I'm experiencing poor performance on android using `ListView` on `production` , development mode is ok. 

Any idea about this ?

**Comment by satya164** [comment]
@lxsameer Hey, thanks for the report. Can you explain more what do you mean by poor performance? Is the touch response time slow? Can you give some sample code?

**Comment by lxsameer** [comment]
@satya16 I used both `TouchableHighlight` and `TouchableOpacity` within my `ListView` items. In the development mode every thing is ok and animations are smooth but, after releasing the production apk, touch action trigger by a 3 to 5 second delay. I'll try to put some code in this issue too

**Comment by satya164** [comment]
@lxsameer Hmm... Production APK should be a lot faster than dev mode. Are the items rendering while you try to tap something? Is any other expensive operation going on? Have you tried decreasing the `pageSize`?

**Comment by lxsameer** [comment]
I have a fix list of 30 item array, and I don't do anything during touch event. I just push a route to navigator.

**Comment by ide** [comment]
Can you use the systrace tools to figure out what is going on? This is the guide for how to use them: https://facebook.github.io/react-native/docs/android-ui-performance.html

**Comment by lxsameer** [comment]
Yeah sure

**Comment by arathunku** [comment]
Hello,

I've got the similar problem. Looks like my touch events are delayed by 5-7 seconds on the production build (js mode off). From the systrace it looks like it's spending a lot of time on the `JSCall__RCTEventEmitter_receiveTouches`

![image](https://cloud.githubusercontent.com/assets/749393/12199617/bf23aab6-b619-11e5-925f-165b67d9e912.png)
![image](https://cloud.githubusercontent.com/assets/749393/12199699/7b1eb576-b61a-11e5-960e-bd09ae0520c5.png)

Is this a desired behavior or it might be some error on my side? I've tried setting  `shouldComponentUpdate` to false and disabling render on not currently visible views (I'm using Navigator) but it doesn't improve the situation at all. 

In the attachment, I'm putting systrace from 1 transition (10s long) but I had to change the extension from `.html` to `.txt` because GitHub would accept it otherwise :confused: 


__________________
[trace.txt](https://github.com/facebook/react-native/files/82766/trace.txt)

**Comment by arathunku** [comment]
@lxsameer would you mind reopening the issue or should I create the new one with the same problem? Or maybe you've found the fix that's why it's closed?

**Comment by lxsameer** [comment]
@arathunku mine was due to use a pre-mature loop in my code.

**Comment by arathunku** [comment]
@lxsameer thanks. Then it looks like I've got a different problem.

@ide, should I open a new issue regarding touch performance or it's fine as it is now?
