### ISSUE TITLE
Packager hangs indefinitely on require('redux') in v0.16.0

### ISSUE THREAD

**Issue by anshul** [facebook/react-native#4674]
`[6:57:52 PM] <START> transform
transforming [======================================= ] 97% 383/395`

and it stays hung there for hours...

**Comment by Sunify** [comment]
I have error with redux when i try make a bundle:
uncaught error Error: ReferenceError: [BABEL] /Users/sunify/react-native/CoachingApp/node_modules/redux/lib/index.js: Unknown option: /Users/sunify/react-native/CoachingApp/node_modules/redux/.babelrc.stage

**Comment by ide** [comment]
Redux and React Native 0.16 are incompatible until Babel 6's babelrc resolver matches Babel 5's.

**Comment by holyxiaoxin** [comment]
I believe this is the [issue](http://babeljs.io/blog/2015/10/29/6.0.0/). Any patch to this for the moment? Or we have to wait for the next version release of react-native before we can use external packages?

**Comment by Sunify** [comment]
I think you can use custom transformer with babel 5 (--transformer option for packager and react-native bundle).

**Comment by pr1ntr** [comment]
I was having this problem. Then I found this issue and upon opening my computer I found that the last thing i was looking at was this:

https://github.com/alinz/example-react-native-redux/blob/master/Counter/package.json

I looked at @alinz package json and I notice he removes the .babelrc from all his node modules folder. I am not really even sure how this works but for some reason, despite not having any other babelrc file, it does. I am able to import redux fine after running that command. I don't think this a permanent solution but it does work.

**Comment by alinz** [comment]
@pr1ntr as @ide  mentioned this is babel6 issue which it's incompatible with babel 5 rc files. The real problem is redux included babelrc into repo. Redux's baberc is incompatibale with babel6. So they need to either fixes their babelrc or remove it.

@jaysoo found that removing all babelrc files in all node_modules except the ones in packager will fixes the issue of redux for short time.

**Comment by gaearon** [comment]
Just released `redux@3.0.5` that doesn't ship `.babelrc`.

**Comment by christopherdro** [comment]
Nice @gaearon.

@anshul @pr1ntr Can you guys confirm that this working now so we can close the issue?

Thanks!

**Comment by gaearon** [comment]
I also released `react-redux@3.1.1` (3.x is what RN users use for now) without `.babelrc`.

**Comment by jaysoo** [comment]
@christopherdro @anshul @pr1ntr Can confirm that this fixes it for redux. Might be other node modules that have same problem, but bug should be filed on their repo.

**Comment by satya164** [comment]
Closing this for now. Let's reopen if issue persists.

**Comment by alinz** [comment]
@gaearon This is still happening I think redux itself still uses `.babelrc.stage`. Here's the error I'm getting,

```js
{
    message: "TransformError: Counter/node_modules/redux/lib/index.js: [BABEL] Counter/node_modules/redux/lib/index.js: Unknown option: Counter/node_modules/redux/.babelrc.stage",
    type: "TransformError",
    errors: [ { } ]
}
```

The workaround for now is to use the following bash script to get rid of all `babelrc` files except react-native's ones in order to get the code working.

```bash
cd node_modules; find . -name .babelrc | grep -v packager | xargs rm
```

@satya164 this issue needs to be reopened.

**Comment by ide** [comment]
The current solution of having every package maintainer (who uses Babel) need to remember to exclude .babelrc is not scalable. We need an option in Babel to say: ignore only the .babelrc files under node_modules.

**Comment by alinz** [comment]
@ide agree with your proposal but Babel6 has introduces a lot of api changes. I think  this solution would be good for short time. I believe 3rd party modules need to be updated to be compatible with Babel6 or we end up with a lot of messy compatibility code and hacks. 

Do you think putting `.babelrc` in `.npmignore` would be a bad idea? since npm module should be a production code.

**Comment by satya164** [comment]
@alinz  There is another discussion regarding the issues arising due to the Babel upgrade (not only for Redux, but all 3-rd party libraries which have a `.babelrc`). - https://github.com/facebook/react-native/issues/4062

**Comment by alinz** [comment]
@satya164 thanks!
