### ISSUE TITLE
NSDate Support Between Native and JavaScript

### ISSUE THREAD

**Issue by joewood** [facebook/react-native#4685]
Right now, when any NSDate data is passed between native and JavaScript over the bridge it throws an error. I have to remember to scan the datatypes being returned and convert NSDate's over to strings or epoch offsets. 

Why isn't NSDate supported as a native data-type? Is this performance driven?  Could it be added as a optional feature for specific modules?

**Comment by christopherdro** [comment]
Related: #4049

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/nsdate-support-between-native-and-javascript

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
