### ISSUE TITLE
the android images look like very strange

### ISSUE THREAD

**Issue by gitdevdxy** [facebook/react-native#4692]
thanks

```
<Image
        style={{backgroundColor: 'rgb(205, 128, 6)'}}
        resizeMode='contain'
        source={require('image!ic_create_black_48dp')} />
```

the `ic_create_black_48dp.png` is copy from UIExplorer, i put the png to res/drawable.
this pic is 96*96px,in android device it's look like very big , why?
i tried to put the png in drawable-hdpi、drawable-xhdpi、drawable-xxhdpi

forgive me my english is not good,

**Comment by satya164** [comment]
Hey and thanks for reporting this!

There's an awesome place to ask question like this one: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see your question, you can vote on answers and mark question as answered etc. This lets us keep a list of bug reports and feature requests on github and especially [Product Pains](https://productpains.com/product/react-native/?tab=top) (again, with voting which is really nice).

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)
