### ISSUE TITLE
RCTImageLoader is adding png extension to all files missing extension

### ISSUE THREAD

**Issue by anttimo** [facebook/react-native#4705]
I ran into this issue when image taken with camera didn't show in Image component. By using onError callback on the Image I found out that it was trying to open the given path png extension. Is the extension required by something or why is it added?

Relevant code https://github.com/facebook/react-native/blob/b67229485834113674b25bda193a7426bf44cfc8/Libraries/Image/RCTImageLoader.m#L294

**Comment by brentvatne** [comment]
@anttimo - I think this is a pragmatic default -- most of the images you use will be PNGs.

cc @nicklockwood

**Comment by nicklockwood** [comment]
The implementation is perhaps a bit over-aggressive. This was to fix an issue where

**Comment by anttimo** [comment]
Thanks for the replies. It's just bit surprising when the image loading fails for no apparent reason so first checking the non-extension version would be nice. While PNGs are most common with the UI elements for example the pictures you take with the camera are commonly JPGs and that was the use in our case.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/rctimageloader-is-adding-png-extension-to-all-files-missing-extension

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
