### ISSUE TITLE
ActionSheetIOS Email sharing Modal on back makes the app gone [bug?]

### ISSUE THREAD

**Issue by imton** [facebook/react-native#4707]
Guys,

After using ActionSheetIOS, when choosing for example to share by email, when done/back the app become completely black and unresponsive.

Examining the view hierarchy, it seems the modal stills on place even after transition, and the app is not back.

Quick demo of what is happening: https://s3.amazonaws.com/reeeeact/react_modal.mov

Any idea why? Thx!

**Comment by brentvatne** [comment]
Strange! @imton - did you ever solve this? :(

**Comment by imton** [comment]
@brentvatne nope. Just implemented my own sharing custom stuff to avoid this.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/actionsheetios-email-sharing-modal-on-back-makes-the-app-gone-bug

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
