### ISSUE TITLE
Clarify desired bug reporting process

### ISSUE THREAD

**Issue by ExplodingCabbage** [facebook/react-native#4709]
When I open an issue on this repo, @facebook-github-bot comes along (as it doubtless will here) and suggests I report it on [product pains](https://productpains.com/product/react-native) if I would like it "to be fixed by the team".

I'm entirely unclear on what to do in response to this advice and I suspect others are also. This is exacerbated both by the fact that I'm unfamiliar with Product Pains and by the fact that the [contribution guidelines](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md) don't mention Product Pains at all.

Since presumably all issues anyone ever reports are issues that they want fixed (whether by Facebook's devs or anyone else), does this advice apply to all issues, ever? Or only to some subset? If so, what's that subset?

Should I duplicate the issue I just created on Product Pains? If so, should I close the GitHub issue?

Should I create future issues only on Product Pains, not on GitHub?

Is your intention to move away from GitHub issues and use Product Pains as your primary issue tracker? If so, why not write a script to migrate everything and then close this repository to issues?

Making the instructions on this clearer would probably help your contributors conform to whatever way you want them to report things; at the moment I can't tell if I'm doing the right thing or not because the instructions are not clear to me.

**Comment by udfalkso** [comment]
Agreed, this is a big problem for RN.  Product Pains is simply not good enough to replace GitHub issues for bug reporting.  

It lacks search, so I can't see if my problem has already been submitted by someone else yet already.  You won't get prioritization this way, but a lot of duplicate issues intead.  I can't add a screenshot.  I can't tag things.  etc. etc.  

Perhaps every issue here can have an auto-generated counterpart on Product Pains that links back to the issue here for the details?  Then Product Pains can simply be used for prioritization and nothing more.

**Comment by jaygarcia** [comment]
Product pains is a horrible idea and should be removed in lieu of a true bug reporting solution.

**Comment by satya164** [comment]
@jaygarcia Do you have any other solutions in mind? One big reason of using Product Pains is that the GH issue tracker is unmanagable and it's hard to prioritize anything, and Product Pain's voting feature is useful to better prioritize issues.

cc @vjeux @mkonicek @ide

**Comment by udfalkso** [comment]
I'm considering writing a simple script that goes through all the open github issues and generates a sorted list based on some metrics.  Some function of # participants, # subscribers, # of comments, # commits, etc.  Would that perhaps help you guys with prioritization?

**Comment by vjeux** [comment]
@udfalkso @brentvatne actually implemented something like this but it didn't give us actionable feedback. Having a clear +1 button on the issues you want fixed is a much better indicator instead of guessing. I would really love if github would give us a +1 button and we could sort by it, but it is no, so we have to figure out another way.

@ExplodingCabbage the truth is that we have no idea what we are doing and just experimenting :) This is why the instructions are not clear. If you have ideas on how to improve the messaging, here's the text: https://github.com/facebook/react-native/blob/master/bots/NewIssueGreeting.md

**Comment by ExplodingCabbage** [comment]
So, I'm just a peon and have never done any substantial work on open source projects nor explored the variety of bug tracking software available. But I know enough to know GitHub issues certainly aren't ideal - there's no built-in triage (although you can hack it with labels) and no proper system for voting on issues (which results in long pages of ":+1:  fix plzzz" posts on popular issues on large projects) - which is presumably why some projects host their code on GitHub but close the GitHub issue tracker and use an alternative. But I don't know enough to offer any sensible advice on the merits of using GitHub vs a completely different issue tracker.

But one definitely positive change you *could* make to the current status quo would be to have @facebook-github-bot automatically open a Product Pains issue for every GitHub issue and connect the two via links. That would solve the unsearchability issue raised by @udfalkso (you could just search on GitHub and then follow the link to Product Pains), leave issue openers less confused than we are currently, and give you better data. I might look into implementing this later if @facebook-github-bot's soul is under source control here.

**Comment by udfalkso** [comment]
Perhaps a forum based on http://www.discourse.org/ would be a stronger option than Product Pains (which is severely lacking).  

It has worked well for Ionic:
forum.ionicframework.com

Another example:
http://www.discourse.org/

**Comment by vjeux** [comment]
@udfalkso we already have Discourse setup for React and it seems like there are react-native questions already posted there. Maybe we should highlight it more. @ide and @mkonicek what do you think? Sounds like a good idea to me

**Comment by vjeux** [comment]
Looks like ionic is super active, with 115 posts today. React one is a lot smaller with 8 posts yesterday.

**Comment by ide** [comment]
I like the idea of forums but would really like to find an alternative to Discourse which I find hard to use. Honestly I'd prefer a subreddit like r/reactnativehelp or something.

**Comment by ippa** [comment]
I have a similar view as OP on productpains. Also.. it wants me to create Yet another account just to press an upvote button without the option to login with my github-account.

I thought udfalksos suggestion on sorting open issues sounded good, too bad it never gave good results according to vjeux. But I also got the impression it could have been tweaked more? Is productpains really giving better results right now in comparisson to the old issue-sorting-method?

How about also counting the classic "+1" msg? I understand it's kind of spammy, but ppl do use it.. even when they're told not to :).

**Comment by ide** [comment]
^ cc @arasmussen: github login could be good to add for "products" that are actually code projects

**Comment by mkonicek** [comment]
> Since presumably all issues anyone ever reports are issues that they want fixed

Actually, a lot (probably >50%) of the issues are **questions** (like "How to render a static image?") that should go to Stack Overflow.

The message says:

> If this is a feature request or a bug that you would like to be fixed by the team, please report it on Product Pains.
...
> If you don't know how to do something or not sure whether some behavior is expected or a bug, please ask on StackOverflow ...

If we could automatically and reliably identify questions, it would be cool to tailor the message based on that. I have something in the works, it's not perfect yet but want to give it a try. Then, knowing the issue is very likely a feature request / bug, we could make the message shorter and clearer and even automatically link to Product Pains as you said.

Highlighting Discourse sounds OK to me although I never use it (only use Github, Stack Overflow and Product Pains). It's in the [README](https://github.com/facebook/react-native#getting-help) but adding it to the [bot message](https://github.com/facebook/react-native/blob/master/bots/NewIssueGreeting.md) or even better the footer on the website once we have it sounds good.

>  if @facebook-github-bot's soul is under source control here.

That would be awesome! The codebase is written in Hack and has quite a bit of fb-specific code though (checking which github users are fb employees for example, writing to fb dbs), not sure yet we can open source all of it.

@udfalkso:

> [Product Pains] lacks search, so I can't see if my problem has already been submitted by someone else yet already. You won't get prioritization this way, but a lot of duplicate issues instead. I can't add a screenshot. I can't link a code change back to an issue elegantly etc. etc.

That's true but they can add these features. I think search itself doesn't help with duplicates. What helps is what Stack Overflow does when they automatically show you related questions as you're typing yours. Product Pains could implement that. Actually Product Pains is moving very fast and they might even surpass the features github issues have. See https://productpains.com/product/product-pains/?tab=top

But yeah, we're still experimenting trying to find the best solution. Another alternative could be using Phabricator like Babel did. The number of subscribers on an issue can be used for voting: https://phabricator.babeljs.io/T2645

**Comment by mkonicek** [comment]
I've just tweaked the bot message a bit: https://github.com/facebook/react-native/blob/master/bots/NewIssueGreeting.md

**Comment by jaygarcia** [comment]
Thanks @mkonicek.  That new message is better!

As far as a bug tracking tool,  ( i know that I put my thoughts out on Discord days after PP was chosen) this wheel has been invented 23908472039874291874 times already.   Why not just choose something that's already widely used and supported by large OSS projects?

Usage of PP is a huge mistake.

**Comment by satya164** [comment]
> always mention the version of React Native

@mkonicek We should also ask to specify the platform. Many users don't specify the platform while reporting bugs.

**Comment by mkonicek** [comment]
@satya164 Feel free to update the message.

**Comment by mkonicek** [comment]
@jaygarcia Actually it's only thanks to Product Pains that it's not clear what the highest-pri things to work on are. With github issues, there was no way to sort or filter the issues based on any criteria (e.g. "number of comments") to get this list:
https://productpains.com/product/react-native/?tab=top

Yes, we could use Phabricator or Jira too but Product Pains has been working well so far. They move fast and add features we request which I'm not sure is the case with the other systems. Again, still experimenting and we might switch to Phabricator later. For now Product Pains helps the project a lot.

**Comment by arasmussen** [comment]
Hey all, I work on Product Pains full time. I used to work on React Native at Facebook.

I've been hearing great things about PP from the React team at FB so it's a bit startling to see the opposite from the community in this thread.

> They move fast and add features we request which I'm not sure is the case with the other systems.

I'd like to reiterate what @mkonicek has said. I am working full time on the feature requests I receive. Last week that was post statuses. This week it's post search, image comments, and more.

If you have feedback for how I can make Product Pains better, feel free to shoot me an email directly at andrew@productpains.com, I'm very responsive. Or even better post and vote on Product Pains! http://productpains.com/product/product-pains/?tab=top

> github login could be good to add for "products" that are actually code projects

The reason we ask that you make an account to vote is because we need to associate the vote with an identity otherwise people could make infinite votes and then the data wouldn't be as useful or accurate. People can make multiple accounts but that's a lot of effort.

If supporting GitHub login in addition would make a lot of people happier, I'd be glad to support it. You can vote on that here: https://productpains.com/post/product-pains/log-in-with-github/

**Comment by satya164** [comment]
@mkonicek Thanks. Will do.

**Comment by jaygarcia** [comment]
@mkonicek moving to a well-known and well supported bug tracker tool would've done that w/out the need to invest in another tool. Absolutely no offense to @arasmussen (great work there).  

We all recognize that GH Issues is not scalable for the amount of traffic that this project receives. :-\

**Comment by mkonicek** [comment]
Thanks for the hard work on Product Pains @arasmussen!

**Comment by brentvatne** [comment]
@jaygarcia - moving all issues to another platform is a huge project. we have considered Phabricator but nobody has time right now to do that. I agree that Product Pains is working excellent so far :)

**Comment by arasmussen** [comment]
Hey guys, just a heads up that Product Pains now supports login via GitHub and Twitter. If you already have an account then you can connect your GitHub account at https://productpains.com/settings/auth. Thanks!

**Comment by mkonicek** [comment]
This is awesome @arasmussen!

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/clarify-desired-bug-reporting-process

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
