### ISSUE TITLE
[Navigator] Add events when pan responder is active

### ISSUE THREAD

**Issue by rclai** [facebook/react-native#4714]
https://github.com/facebook/react-native/blob/ce7c0b735f476a4618fd0d68fc39157a0bdb4f57/Libraries/CustomComponents/Navigator/Navigator.js#L330-L335

It would be nice to be able to hook into the gesture pan handlers via props being able to access the route, the native event and the gesture state.

Or emit custom pan handler events for the navigation context similar to didfocus and willfocus. Perhaps panstart, panmove, panend?

For example, if I'm on a scene that has a video playing, and I swipe back, I'd like to stop the video as soon as I'm swiping back.

**Comment by rclai** [comment]
Should I put this in the back-burner since this library is going to be deprecated?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/navigator-add-events-when-pan-responder-is-active

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
