### ISSUE TITLE
[iOS] Numerical HTTP Headers

### ISSUE THREAD

**Issue by JAStanton** [facebook/react-native#4715]
I caught an exception setting a HTTP header that was a number and not a string (my app build number). It would be nice if it was cast for me :)

**Comment by BillyBarbaro** [comment]
Hi there.  I'm new to the community and was hoping to take this issue on as a first task.  I started playing around with it; however, I can't seem to reproduce it.

I tried testing it with a piece of code like this:

    var obj = {
        method: 'POST',
        headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json',
            'Origin': '',
            'Host': 'raw.githubusercontent.com',
            'Build-Number': 19299294093,
        },
    }

    fetch(REQUEST_URL, obj)
        .then((response) => response.json())
        .then((responseData) => {
            console.log(responseData);
        })
        .done();

With this, I got the response I was expecting (although the request I made wasn't dependent on the 'Build-Number' header).  Any chance you could help me pin down this issue a little more so I can help do a little work on it?  Thanks!

**Comment by JAStanton** [comment]
Strange that's more or less exactly what I did. Lemme go back and check the
react version I was on

**Comment by brentvatne** [comment]
@BillyBarbaro - wow awesome thank you for looking into this.

@JAStanton - did you ever get to look into this?

**Comment by trave7er** [comment]
I encountered this problem before, @BillyBarbaro could you a larger number? I remember my number was a timestamp, which is several order of magnitude larger.

@JAStanton @brentvatne

**Comment by trave7er** [comment]
@BillyBarbaro @JAStanton @brentvatne - ok, I was wrong. So the problem occurred again only when I used a **browserified superagent** to make http requests. And I haven't checked why **fetch** is fine, but I have opened a PR https://github.com/facebook/react-native/pull/6094 to address this issue. Please take a look,

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/ios-numerical-http-headers

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
