### ISSUE TITLE
A little cleaner home-site proposal

### ISSUE THREAD

**Issue by gaston23** [facebook/react-native#4720]
Hey guys,

Had a little time and tried to clean up a little the home and docs. It was done in under some minutes, so its nowhere near finished. But if you like it, I can finish it and issue a PR.

POC (check only this!)
http://imton.github.io/react-native/
http://imton.github.io/react-native/docs/getting-started.html
http://imton.github.io/react-native/docs/animations.html

![image](https://cloud.githubusercontent.com/assets/637225/11727158/18453bca-9f61-11e5-8825-c17c977ac9ae.png)

![image](https://cloud.githubusercontent.com/assets/637225/11727163/21e6b514-9f61-11e5-98c2-f0faa4a6527d.png)

![image](https://cloud.githubusercontent.com/assets/637225/11727169/2b5aa9f2-9f61-11e5-8236-69638005736c.png)

**Comment by ide** [comment]
Looks nice cc @vjeux 

One piece of feedback is that I'd make the teal banner on the home page way smaller -- about as tall as the nav bar -- since doesn't communicate very much.

**Comment by vjeux** [comment]
Thanks for sharing!

## Aesthetics

We're trying to keep the same design aesthetics on our front-end open source projects so that they feel like they belong together:

- http://facebook.github.io/jest/
- http://facebook.github.io/react-native/
- http://flowtype.org/
- http://facebook.github.io/react/
- ...

I'm not opposed to making react-native have a design upgrade but this feel to me like it's a bigger departure and doesn't provide much value.

## Space

You've added whitespace everywhere. While this makes for a pretty looking website, this is harmful for readability. There's much less information displayed and you need to scroll more for no good reason. If you put the two side by side, the old one showed a lot more information. If anything, I'm actually not happy with how few information we show on the current page and think we could display much more.

<img width="1435" alt="screen shot 2015-12-10 at 1 44 22 pm" src="https://cloud.githubusercontent.com/assets/197597/11729445/2c7f0b88-9f44-11e5-940d-95349175b3c8.png">
<img width="1435" alt="screen shot 2015-12-10 at 1 44 24 pm" src="https://cloud.githubusercontent.com/assets/197597/11729446/2c86a280-9f44-11e5-9ba7-f6fd7ccc7876.png">


## Conclusion

I'm not very clear how this design is better than the previous one. It loses the "brand" aspect shared with the other websites and has a lot less information density. Would you mind selling it to me, I'm sure I'm missing something :)

**Comment by imton** [comment]
Hey @vjeux I completely understand your position. Let me go by each of your points.

*Readability & Space*
While I agree the hero is huge and currently provides no value, I think my plan there is to make the hero valuable. Haven't had the time to make a proper hero that adds value, that's why I just added more space to it, for future improvement. 

I, personally, believe readability is better in my version. I think adding spacing, shrinking content wrappers max-widths and letting people scroll freely (more) actually improves readably. But hey, It's my POV. 

* Aesthetics *
You are totally right here. This breaks other react projects styles. This is just a quick POC, so don't take it so seriously. 

I personally think react and react-native is the future of development going forward. This is one or two years is going to be everywhere. The reason why I did this now, is because I feel the home/site doesn't look forward-thinking, it looks quite old.

Well, that's my personal view, I can try to improve it much more when I have some free time.

**Comment by vjeux** [comment]
"I feel the home/site doesn't look forward-thinking, it looks quite old."

This is what happens when you let an engineer (me) be in charge of designing those websites ;)

Also, it's been a conscious decision to not make it look shiny. My experience is that the more shiny the website looks, the less good the technology is. But, this was 3 years ago when React was a random small project. Lot of things changed since then and it's probably a good time to do a facelift to make it more legit :)

Let me give a round of comments on the design

**Comment by vjeux** [comment]
Overall I really like the direction this is going. I can see us shipping it :)

- I like the color. Gives an identity to the project, the current blue is really bad.
- For the text, I would find a middle ground. Make the width bigger and the line height smaller.
- The header height is weird. It is really big but the text is small. Either bump the font size or reduce the height.
- Header is missing the React Native name. This is pretty important imo, the logo isn't enough.
- I like the full black background.
- I like the way the header is structured, I would just make everything less spacey :p
- The button looks wayyy better
- The left menu doesn't need all that spacing. Right now it's super annoying when you are at the bottom already. Maybe change the design so that we can collapse things? Idk
- I want to put a search box somewhere, if you can think about where while you are working on this.

**Comment by satya164** [comment]
Looks pretty @imton . Looking forward to a prettier website with @vjeux 's points :)

**Comment by skevy** [comment]
This is looking really cool @imton! Thanks so much for taking the time to start thinking about it. I agree with @vjeux about search...I think adding that functionality at the same time as we do a redesign would be valuable.

**Comment by vjeux** [comment]
For search, we should use Algolia who wanted to build the one for React itself: https://github.com/facebook/react/issues/4807

**Comment by skevy** [comment]
Yep! I've used Algolia before, it's awesome.

**Comment by imton** [comment]
Thank you guys for the feedback. A little bit busy, will keep iterating slowly, but I promise I will take care of this :)

Some updates to the home. Still alpha. 

I think we should put killer example there in the hero, for iOS and Android and let the switch. Would be nice to show the result of it too.

![screen shot 2015-12-11 at 10 25 28 pm](https://cloud.githubusercontent.com/assets/637225/11759280/22fe2da6-a056-11e5-93fa-f63539a2220b.png)

**Comment by vjeux** [comment]
I like having code example at the top, shows that it's for developers :)

**Comment by imton** [comment]
some minor fixes and some ideas popping up, feedback? ideas?

![screen shot 2015-12-12 at 4 44 04 am](https://cloud.githubusercontent.com/assets/637225/11760855/19d88606-a08b-11e5-8fad-0dcf4e8b3fb9.png)

![screen shot 2015-12-12 at 4 44 13 am](https://cloud.githubusercontent.com/assets/637225/11760854/19d483ee-a08b-11e5-9172-f020e119b9c7.png)

**Comment by ide** [comment]
Some thoughts:
 - teal hero would look better without the top padding so that the code sample touches the bottom of the nav bar
 - the grid of components is hard to read compared to a list. i'm not sure the components should go on the home page, as opposed to the docs section.
 - where a grid could be good is if we had screenshots of the components so that someone sees one and says, "yes! i want an action sheet component."

**Comment by ippa** [comment]
Nice work! I really like code-examples, right away webppl see what little (familiar) code can give them native performance.

Suggestions, how about either:
- Making the example not tied to iOS + a comment "this compiles to native ios and android"
- Having tabs on top of the examplebox "index.android.js", "index.ios.js" which shows off specific platform features. Bonus idea: detect osx/ios and show ios-example pre-selected, detect windows/linux/android and show android-example pre-selected.

If you like example-box-tabs we could also show of a simple ES2015-example with class and super() which IMHO renders for cleaner code. Maybe that should even be the default? 

I also agree with everything ide said.

**Comment by iamdustan** [comment]
All I was for Christmas is React and friends docs formatted for my mobile device. 

🎄

**Comment by imton** [comment]
@iamdustan we will get there, eventually :)

**Comment by jsierles** [comment]
Would be nice also to include runnable examples in your design. We have a baseline setup for this, but are still working on details of how to make the simulators show up on all doc pages. However, it's doable and would be a great addition! I think having one right on the main page would be awesome.

Here's an example of a working runnable example from UIExplorer:

https://facebook.github.io/react-native/docs/alertios.html#content

**Comment by imton** [comment]
@jsierles great idea. Sadly that UIExplorer runnable throws lots of red errors. While I love appetize.io it is some kind slow to start up. I'd prefer to think some other ideas that show the things working right away (mini-videos/ gifs/ canvas...?)

**Comment by jsierles** [comment]
Hmm, the example is working for me. The advantage to using appetize is that the examples are interactive, and we can update as UIExplorer changes without having to do videos manually: I don't think anyone wants to do that work!

**Comment by imton** [comment]
@jo

Best,

Gaston
+59898704249

**Comment by christopherdro** [comment]
@imton Any updates?

**Comment by imton** [comment]
@christopherdro everyday I try to find the time to do this. I probably will this week. Don't expect 100% finished by first commit.

**Comment by christopherdro** [comment]
@imton :+1: Sounds good! Thanks.

**Comment by ranyefet** [comment]
Laravel Documentation is one of the best I've seen/read, could be a good inspiration ;)
https://laravel.com/docs/5.2

**Comment by 9mm** [comment]
2 comments

Homepage:

* I think the code samples are too large (down 2 font pixels maybe?)

Inner page:

* The font is way too small... compare information density of old vs new...

![image](https://cloud.githubusercontent.com/assets/1386207/12072644/3fa37e94-b0b8-11e5-815a-e626dfeb0fa9.png)

![image](https://cloud.githubusercontent.com/assets/1386207/12072647/4b7557ec-b0b8-11e5-8389-bbb9794b7791.png)

The inner docs areas I feel need a lot of work because looking at the mockup gives me a headache, whereas the original is very easy on your eyes while you're trying to read documentation for hours.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/a-little-cleaner-home-site-proposal

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by mkonicek** [comment]
Wow I've just seen this. @imton did you end up sending a PR for this or do you still plan to?

**Comment by imton** [comment]
@mkonicek ok, I will try to do it try to do it this week! :) sorry I've been quite busy

**Comment by lacker** [comment]
We altered a lot of docs stuff since this was last posted, although mostly just content. I think it would be pretty cool to have visual help here but it's probably better to operate off a PR. Actually if someone's interested in this perhaps ping me directly so we can sync up on what is good stuff to do here. Anyway I am going to close this issue for now as it seems that it is no longer useful.
