### ISSUE TITLE
ListView Grid Layout doesn't show full content

### ISSUE THREAD

**Issue by shadowpage** [facebook/react-native#4728]
In official UIExplorer example, Grid Layout only shows 11 cells while it has 100 cells: 
![1](https://cloud.githubusercontent.com/assets/6863595/11738808/df32ebe6-a020-11e5-8415-45f1f2ce1992.png)

I have to scroll down a little so the rest of the cells can be shown:
![2](https://cloud.githubusercontent.com/assets/6863595/11738855/5a3d5fec-a021-11e5-8503-d2926729a36c.png)

**Comment by jaygarcia** [comment]
Hi @shadowpage, please feel free to close this issue. There are a few bug reports regarding ListView that have a lot of discussion. :) 
For example: https://github.com/facebook/react-native/issues/1831

All the best!

**Comment by shadowpage** [comment]
Hi @jaygarcia, it's not exactly the same issue with #1831, since grid layout works on 0.11rc (and older version).

I think listview wants to show 11 lines so it requests 11 cells because it believes there's only one cell per line. If it knows there're 3 cells per line it would request 33 cells then there would be no problem at all! :)

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/listview-grid-layout-doesnt-show-full-content

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
