### ISSUE TITLE
Programmatic focus of `TextInput` in `useEffect` fails silently in Bridgeless mode on iOS

### ISSUE THREAD

**Issue by QichenZhu** [facebook/react-native#47359]
### Description

The `focus()` method of `TextInput` in `useEffect` doesn't work in Bridgeless mode on iOS. The input is not focused, and the soft keyboard doesn’t appear.

Even worse, the `isFocused()` method returns `true` regardless, so future calls to `focus()` are ignored because it considers the input already focused.

### Steps to reproduce

1. Build and run the iOS app with New Arch enabled.

```Bash
cd ReproducerApp
yarn
bundle install
cd ios
RCT_NEW_ARCH_ENABLED=1 pod install
cd ..
yarn ios
```

2. Check if the `TextInput` is focused initially. If so, the test passes. If not, proceed to steps 3-5.

3. Click the Focus button.

4. Click the Blur button.

5. Click the Focus button.

**Expected result:** The `TextInput` is focused initially.

**Actual result:** The `TextInput` is not focused initially and after the first time clicking the Focus button. It is only focused after clicking Blur and then clicking Focus again.

### React Native Version

0.76.1

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.5
  CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
  Memory: 9.90 GB / 24.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.18.0
    path: ~/.nvm/versions/node/v20.18.0/bin/node
  Yarn:
    version: 1.22.22
    path: ~/.nvm/versions/node/v20.18.0/bin/yarn
  npm:
    version: 10.8.2
    path: ~/.nvm/versions/node/v20.18.0/bin/npm
  Watchman:
    version: 2024.07.29.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/penguin/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 3.1.2
    path: /Users/penguin/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.0.0
    wanted: 15.0.0
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.1
    wanted: 0.76.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Stacktrace or Logs

```text
N/A
```

### Reproducer

https://github.com/QichenZhu/reproducer-react-native-textinput-focus

### Screenshots and Videos

Bridgeless Enabled | Bridgeless Disabled
-- | --
<video src="https://github.com/user-attachments/assets/5c909c1d-9d1f-4e0a-b4ed-d08c577edb9d" /> | <video src="https://github.com/user-attachments/assets/51858799-4302-4a4c-a709-c327e5ae01b5" />

**Comment by shubhamguptadream11** [comment]
@QichenZhu 
This is specific to New arch only.
I initially tried to delay the calling of `.focus()` and it somehow worked this way.
```
setTimeout(() => {
      textInputRef.current?.focus();
    }, 0);
```

This is weird. I am still finding out what's the exact issue

**Comment by s77rt** [comment]
### Problem
The `useEffect` is called too early before the [mount instructions](https://github.com/facebook/react-native/blob/16eb53befa305df70e9aa1dae2ad6e9fe97f1ecb/packages/react-native/React/Fabric/Mounting/RCTMountingManager.mm#L43) are executed i.e. before the components are registered in the view registry, due to the [mount being async](https://github.com/facebook/react-native/blob/16eb53befa305df70e9aa1dae2ad6e9fe97f1ecb/packages/react-native/ReactCommon/react/renderer/uimanager/UIManagerBinding.cpp#L486). The focus fails as there is [no component view with the given reactTag](https://github.com/facebook/react-native/blob/16eb53befa305df70e9aa1dae2ad6e9fe97f1ecb/packages/react-native/React/Fabric/Mounting/RCTMountingManager.mm#L327).

Offending commits and PRs:
- https://github.com/facebook/react-native/commit/afec07aca273503b0647dbf1f73c518c6e52e8ba#diff-74d87b8778f3afdd8af5d227cb1aea00dd473ac220c2a89f4895570c37efeb67
- https://github.com/facebook/react-native/pull/41157
- https://github.com/facebook/react-native/pull/47084

cc @sammy-SC @rubennorte


### Temporarily solution
Patch `packages/react-native/ReactCommon/react/renderer/uimanager/UIManagerBinding.cpp`
```diff
@@ -483,7 +483,7 @@ jsi::Value UIManagerBinding::get(
           uiManager->completeSurface(
               surfaceId,
               shadowNodeList,
-              {.enableStateReconciliation = true, .mountSynchronously = false});
+              {.enableStateReconciliation = true, .mountSynchronously = true});
 
           return jsi::Value::undefined();
         });
```
Or set the RN flag `disableEventLoopOnBridgeless=true` but as far as I can the flag system is meant for internal use only.

**Comment by rubennorte** [comment]
Thanks for reporting this. This is a known issue we're investigating in #47576.

**Comment by QichenZhu** [comment]
Close this as the related issue https://github.com/facebook/react-native/issues/47576 has been resolved.
