### ISSUE TITLE
[Android] setTimoute inside componentDidMount never fires.

### ISSUE THREAD

**Issue by gs-akhan** [facebook/react-native#4746]
I am registering a setTimeout inside componentDidMount for several Components . What I observe is , componentDidMount does gets executed. but the setTimeout callbacks never. 
```
componentDidMount() {
    console.log("Option list Mounted")
    setTimeout(() => {
      this.refs.OPTIONLIST.measure(this.getMeasureAndUpdateState);
    },0);
  }
```
Node Version 4.1.1
ReactNative : 0.16

Thanks.

**Comment by theoriginalgri** [comment]
I cannot reproduce this with RN master.

```
componentDidMount() {
    setTimeout(
      () => console.log("componentDidMount with timeout!"),
      0
    )
  },
```

```
12-14 08:56:24.460 2256-3064/com.scrollviewtest I/ReactNativeJS: componentDidMount with timeout!
```

**Comment by gs-akhan** [comment]
@theoriginalgri Register multiple and I am facing this on Android only.. However I will try to setup a example.

**Comment by dabit3** [comment]
@gs-akhan have you looked at https://facebook.github.io/react-native/docs/timers.html#timermixin 
>We strongly discourage using the global setTimeout(...) and recommend instead that you use this.setTimeout(...) provided by react-timer-mixin. This will eliminate a lot of hard work tracking down bugs, such as crashes caused by timeouts firing after a component has been unmounted.

**Comment by christopherdro** [comment]
@gs-akhan Feel free to open this up again if you still have problems when switching to `this.setTimeout`.

**Comment by rulatir** [comment]
This bug was closed without justification.

The original problem was about the callback not firing at all, rather than firing when it shouldn't.

In addition, React components are not the only parties that might use setTimeout() - third party RN-agnostic libraries might do so too, and there is no way to make them use the mixin without rewriting them.

`setTimeout()` must do what specs say it should do, that is, actually cause the callback to be fired after the given amount of time with 100% certainty, unless `clearTimeout()` was used. This bug should be reopened and remain open until this issue is resolved, rather than some vaguely similar issue.
