### ISSUE TITLE
Different NavigatorBar for landscape mode?

### ISSUE THREAD

**Issue by aksonov** [facebook/react-native#4767]
Native iOS Navigator for landscape mode has smaller height and hidden status bar, is it possible to achieve the same with RN NavigatorBar?

**Comment by theoriginalgri** [comment]
I cannot find a NavigationBar component, what are you referring to?

**Comment by aksonov** [comment]
Sorry, NavigationBar 

Pavel.

**Comment by aksonov** [comment]
Standard navbar, it is within Libraries/CustomComponents/Navigator/NavigatorNavigationBar.js

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/different-navigatorbar-for-landscape-mode

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by mkonicek** [comment]
@facebook-github-bot stack-overflow
