### ISSUE TITLE
WebView inside ScrollView not working

### ISSUE THREAD

**Issue by leovanhaaren** [facebook/react-native#4773]
I noticed that, on version 0.16.0, putting a WebView inside a ScrollView results in a blank page, no error is thrown. Replacing the ScrollView with a normal View fixes this problem, but gives no way of scrolling through a list with for example a header component and a WebView body. Anyone?

**Comment by skevy** [comment]
@leovanhaaren Thanks for the report! Would you be able to put together a simple test case and post the link here?

**Comment by leovanhaaren** [comment]
https://github.com/leovanhaaren/ScrollViewWebView

It shows 2 WebViews, the top half in a normal View and the bottom one in a ScrollView. I can imagine this being related to the page being not loaded yet. But can't get it to work.

**Comment by leovanhaaren** [comment]
Added url now

**Comment by KameshInfinite** [comment]
I am facing the same issue. Any updates here?

**Comment by zhaoyu87** [comment]
+1

**Comment by BilalBudhani** [comment]
Hey did anyone happened to get through this issue? I'm facing the same problem currently. WebView doesn't appear inside ScrollView. I'm on `0.21.0`.

**Comment by avishayil** [comment]
Issue still persist.

**Comment by jaygarcia** [comment]
OK, this isn't a problem per-say.  It's a behavioral expectation issue.  (i'm on .22rc4)

First thing to realize is that webview seems to automatically resize itself.  In the below example (copied & modified from @leovanhaaren's post above), we can see that the top web view, self-sizes, based on it's parent's dimensions.

```
  render() {
    var source =  {uri: 'http://google.com'};
    return (
      <View style={styles.container}>
        <View style={{borderWidth:3, borderColor : '#FF0000', flex:1}}>
          <WebView source={source} style={{}} />
        </View>
        <ScrollView style={{borderWidth:3, borderColor : '#0000FF', flex:1}}>
            <WebView source={source} style={{height: 250}}/>
        </ScrollView>
      </View>
    );
  }
}
```
Demo:
![webviews](https://cloud.githubusercontent.com/assets/180031/13899550/819e2f78-edc7-11e5-952c-f36b825666e8.gif)

The web view shows up fine in a scroll view, *but you must give it a size*.

Now, what happens when you have a regular `<View/>` in place of a `<WebView/>` that self-sizes based on it's parent `flex:1`?  

```
    var source =  {uri: 'http://google.com'};
    return (
      <View style={styles.container}>
        <View style={{borderWidth:3, borderColor : '#FF0000', flex:1}}>
          <View source={source} style={{flex:1, backgroundColor: '#AAAAFF'}} />
        </View>
        <ScrollView style={{borderWidth:3, borderColor : '#0000FF', flex:1}}>
          <View source={source} style={{flex:1, backgroundColor: '#AAAAFF'}} />
        </ScrollView>
      </View>
    );
```

No View appears.  Why? Because it seems that ScrollView doesn't allow children to flex themselves.
Demo:
![views](https://cloud.githubusercontent.com/assets/180031/13899624/4cc2dfa4-edc9-11e5-84b2-0539bb502dfd.gif)

In the case where the web view is not given a height:
```
    var source =  {uri: 'http://google.com'};
    return (
      <View style={styles.container}>
        <View style={{borderWidth:3, borderColor : '#FF0000', flex:1}}>
          <WebView source={source} style={{}} />
        </View>
        <ScrollView style={{borderWidth:3, borderColor : '#0000FF', flex:1}}>
            <WebView source={source} style={{}}/>
        </ScrollView>
      </View>
    );
```
The WebView itself is not even in the tree:

![webview in scrollview](https://cloud.githubusercontent.com/assets/180031/13899657/22dcca14-edca-11e5-85a2-dad1d689e867.png)

**But...**
Same thing happens when you have the View in scrollview with `flex:1` example above.
![views in scrollview](https://cloud.githubusercontent.com/assets/180031/13899681/a88bbec2-edca-11e5-9ea1-0c5a845e77cd.gif)

Call me cray, but I think this issue can be closed. ;)

**Comment by satya164** [comment]
Closing based on the answer by @jaygarcia

**Comment by aferust** [comment]
the issue still exists for android :(

**Comment by carlovenus** [comment]
You need to set the height for the Webview.

**Comment by Athaphian** [comment]
This issue still persists in react native 0.53:

```
<ScrollView style={{
			borderColor: 'blue',
			borderWidth: 1,
			overflow: 'hidden'
		}}>
			<WebView
				source={{uri: 'https://en.wikipedia.org/wiki/Financial_crisis'}}
				style={{
					height: 8000,
					width: '100%'
				}}
			/>
			<Text>ABCD</Text>
		</ScrollView>
```

The webview gets a height of 0 and there seems to be no way to get it to show.

**Comment by alainib** [comment]
Any fix or hack ?

**Comment by mjugger** [comment]
I was having the same problem with my `ScrollView` setup. I found this package that helped me: 
`https://www.npmjs.com/package/react-native-webview-autoheight`
I think I could implement this from scratch, but I just don't have the time at this point in my project

**Comment by 0LING0** [comment]
give webview a fixed height, it can works, i use android emulator.
