### ISSUE TITLE
[Android] [TextInput] The `event` argument passed in `onBlur` function doesn't contains correct `nativeEvent` property

### ISSUE THREAD

**Issue by leftstick** [facebook/react-native#4785]
I am expecting to get the text from `TextInput` component while `onBlur` as well as `onSubmitEditing`.

But it seems not working. 

The `event` contains a `nativeEvent` property while listening `onSubmitEditing`, but left as empty while `onBlur`.

Is this by design?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-textinput-the-event-argument-passed-in-onblur-function-doesnt-contains-correct-nativeevent-property

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
