### ISSUE TITLE
Facing issues with codegen

### ISSUE THREAD

**Issue by riteshshukla04** [facebook/react-native#47936]
### Description

I am facing weird issue with codegen when trying to use direct cpp bindings for ios.

Getting below error when building.
`Undefined symbol: facebook::react::NativeCodegenExampleCxxSpecJSI::NativeCodegenExampleCxxSpecJSI(std::__1::shared_ptr<facebook::react::CallInvoker>)`

- When I remove outputDir from codegen config android build starts breaking. (which I think is optional)
- If I turn the includesGeneratedCode to false cmake is no longer able to link the specs generated 'react_codegen_RNCodegenExampleSpec' 

Reproducer Repo  Added  below

### Steps to reproduce

1. Create a c++ module using create react native library
2. Use pure c++ module turbo module for both android and ios
3. Write native cpp code .
4. Write onLoad.mm
5. Run yarn example ios

### React Native Version

0.76.3

### Affected Platforms

Runtime - iOS, Build - MacOS

### Areas

Codegen

### Output of `npx react-native info`

```text
System:
  OS: macOS 15.1
  CPU: (8) arm64 Apple M2
  Memory: 194.16 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 22.7.0
    path: ~/.nvm/versions/node/v22.7.0/bin/node
  Yarn:
    version: 3.6.1
    path: ~/.nvm/versions/node/v22.7.0/bin/yarn
  npm:
    version: 10.8.2
    path: ~/.nvm/versions/node/v22.7.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/riteshshukla2/.rvm/gems/ruby-2.7.5/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.1
      - iOS 18.1
      - macOS 15.1
      - tvOS 18.1
      - visionOS 2.1
      - watchOS 11.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2412.12266719
  Xcode:
    version: 16.1/16B40
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.12
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/riteshshukla2/.rvm/rubies/ruby-2.7.5/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Stacktrace or Logs

```text
#If outputDir is removed

info A dev server is already running for this project on port 8081.
info Installing the app...

> Task :app:invokeLibraryCodegen
ℹ Building target codegen
✖ Cannot read properties of undefined (reading 'android')

> Task :app:invokeLibraryCodegen FAILED
17 actionable tasks: 5 executed, 12 up-to-date
```

### Reproducer

https://github.com/riteshshukla04/rn-codegen-repro

### Screenshots and Videos

<img width="681" alt="Screenshot 2024-11-26 at 1 44 50 AM" src="https://github.com/user-attachments/assets/cbaeb21a-f5fd-42aa-8d22-ba79cf086416">

**Comment by cipolleschi** [comment]
@riteshshukla04 if you are using the `create-react-native-library`, I suggest you first to open an issue in [their repository](https://github.com/callstack/react-native-builder-bob).

If they end up finding that the problem is in react native core, we will investigate further. This looks more a configuration issue on the template created by the tool.

**Comment by riteshshukla04** [comment]
Hey @cipolleschi  , Thanks for the reply. 
Yes the repro example uses create-react-native-library but I am not using any of the cpp code they provided as they are not using direct cpp bindings to JS. So opening it there wont help either.
It would be really helpful if someone from RN core can look into this

**Comment by cipolleschi** [comment]
I think you are doing something that you should not do:
> When I remove outputDir from codegen config android build starts breaking. (which I think is optional)
This is not optional. If you are using codegen, you can't remove the folder

> If I turn the includesGeneratedCode to false cmake is no longer able to link the specs generated 'react_codegen_RNCodegenExampleSpec'

If you turn `includesGeneratedCode` to false, the Codegen will run in the app. You can't build your library in isolation because there are some missing pieces.

---

In the beginning of your message you mention:

> I am facing weird issue with codegen when trying to use direct cpp bindings for **ios**.

But then you talk about Android and Cmake. 
Which platform is having issues?

---

I strongly suggest to start by looking into the [website guides](https://reactnative.dev/docs/next/the-new-architecture/pure-cxx-modules) and to stick with the recommendations provided by `create-react-native-library`. Moving away from those binaries is a pretty advanced setup and a not recommended one.

**Comment by riteshshukla04** [comment]
You are right, The issue is with react native builder bob. I will raise a issue there. Thanks @cipolleschi
