### ISSUE TITLE
[View] Container borderRadius covered by sub view

### ISSUE THREAD

**Issue by Bronts** [facebook/react-native#4820]
![image](https://cloud.githubusercontent.com/assets/3986255/11841282/305ccd38-a437-11e5-895c-8a287169e7e2.png)
In the root view, I set borderRadius is 17, it display well on right, but on the left, the border radius covered by green sub view and yellow sub view, is this a bug?

**Comment by thomasvm** [comment]
Could you try setting `overflow: 'hidden',` on the root view's style?

**Comment by Bronts** [comment]
@thomasvm Hi, I add overflow: 'hidden' on the root view's style and then it works well. Thank you very much. In iOS native code the root view's borderRadius would't affected by subview default, so I once considered this is a bug in RN.  
Thanks for your suggestion again^_^

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/view-container-borderradius-covered-by-sub-view

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
