### ISSUE TITLE
React Native Layout Issue while using multiline in TextField

### ISSUE THREAD

**Issue by MuhammadAuonOfficial** [facebook/react-native#48203]
### Description

I am encountering a crash in native code when typing into a TextField with the multiline property set to true. This issue occurs in a new screen I created while working on an Expo SDK 51 project using React Native 0.74. The TextField works flawlessly across other screens in the app, including those with multiline enabled. However, on this specific screen, the app crashes immediately when I start typing.

Below, I have provided the relevant code for the TextField component and the debugger log where the issue is triggered in Xcode.

**Environment**

Expo SDK: 51
React Native: 0.74
Platforms: iOS
Development Environment: macOS with Xcode

**Error Code**
```
void YogaLayoutableShadowNode::layout(LayoutContext layoutContext) { 
      ...
      // We must copy layout metrics from Yoga node only once (when the parent
      // node exclusively ownes the child node).
      react_native_assert(childYogaNode->getOwner() == &yogaNode_); <-- com.facebook.react.runtime.JavaScript (10): signal SIGABRT
      ...
}
```

**My Code**
```
<Input
      placeholder="Action Detail"
      multiline
      style={{
            height: 100,
      }}
      value={fields.actionDetail}
      onChangeText={(value) => handleChange('actionDetail', value)}
/>
```

### Steps to reproduce

1. Use the TextField component with multiline={true} on the new screen.
2. Run the app on an iOS device or simulator.
3. Start typing into the TextField.
4. The app crashes immediately.

### React Native Version

0.74.5

### Affected Platforms

Runtime - iOS

### Areas

Other (please specify)

### Output of `npx react-native info`

```text
System:
  OS: macOS 15.1.1
  CPU: (8) arm64 Apple M1
  Memory: 104.31 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.18.0
    path: /opt/homebrew/opt/node@20/bin/node
  Yarn: Not Found
  npm:
    version: 10.8.2
    path: /opt/homebrew/opt/node@20/bin/npm
  Watchman:
    version: 2024.10.21.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/muhammadauon/.rubies/ruby-3.3.5/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.0
      - iOS 18.0
      - macOS 15.0
      - tvOS 18.0
      - visionOS 2.0
      - watchOS 11.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.21829.142.2421.12409432
  Xcode:
    version: 16.0/16A242d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.12
    path: /usr/bin/javac
  Ruby:
    version: 3.3.5
    path: /Users/muhammadauon/.rubies/ruby-3.3.5/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.5
    wanted: 0.74.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Stacktrace or Logs

```text
E1210 23:01:48.913069 1867591680 conversions.h:316] react_native_expect failure: value.hasType<std::string>()
E1210 23:01:50.273198 1867591680 YogaLayoutableShadowNode.cpp:688] react_native_assert failure: childYogaNode->getOwner() == &yogaNode_
Assertion failed: (childYogaNode->getOwner() == &yogaNode_), function layout, file YogaLayoutableShadowNode.cpp, line 688.
```

### Reproducer

https://snack.expo.dev/NRyACbtulAltLwe0W0-Ul

**Comment by shubhamguptadream11** [comment]
@MuhammadAuonOfficial Can you please check your reproducer once. It's not working correctly. Some files are missing.

**Comment by MuhammadAuonOfficial** [comment]
I can't provide a reproducer as the TextField if working on some screens and I can't share the rest of the code.

@shubhamguptadream11

**Comment by shubhamguptadream11** [comment]
Okay but without this we wouldn't be able to help.
I tried with your sample code provided, crash is not happening by just typing.

**Comment by MuhammadAuonOfficial** [comment]
I couldn't reproduce the error, I was a faulty View. I removed the View and It worked fined. Although, I was using gap in that View But Managed to acheive the same functionality using Margin.

**Comment by LCMJ21** [comment]
Still reproduces on **react-native 0.86.0** (new architecture, iOS 26 simulator, Debug).

Same assertion, now at line 709 with the renamed accessor:

```
E YogaLayoutableShadowNode.cpp:709] react_native_assert failure: YGNodeGetOwner(childYogaNode) == &yogaNode_
Assertion failed: (YGNodeGetOwner(childYogaNode) == &yogaNode_), function layout, file YogaLayoutableShadowNode.cpp, line 709.
```

`EXC_CRASH (SIGABRT)` on `com.facebook.react.runtime.JavaScript`, reached from a keystroke's content-size state update:

```
__assert_rtn
YogaLayoutableShadowNode::layout(LayoutContext)   ×7 nested
YogaLayoutableShadowNode::layoutTree(...)
RootShadowNode::layoutIfNeeded(...)
ShadowTree::tryCommit(...) / commit(...)
UIManager::updateState(StateUpdate const&)
```

In my case both conditions from this issue and from #52349 are present at once:

- a **multiline** `TextInput` (with `minHeight`/`maxHeight` via a style array), and
- the whole subtree containing it is **rendered conditionally** and gets unmounted/remounted

The extra ingredient that makes it fire reliably for me is a mount/unmount cycle: typing alone never crashes, but if the subtree is unmounted while the keyboard is open, then remounted, the next keystroke aborts ~2 times in 3.

Caveat for the *Needs: Repro* label: my reproduction currently goes through a third-party chat component, so it is **not yet minimal** — I didn't want to claim otherwise. What I can confirm is that the crash is unrelated to keyboard handling or theming (I ruled out `KeyboardProvider` placement, keyboard-driven re-renders, and `multiline={false}` by direct test), and that it is not Fast Refresh debris — one crash occurred 41 seconds into a freshly launched process.
