### ISSUE TITLE
How can I load from a JS Stream(integrating with existing app)? not JS Bundle file path.

### ISSUE THREAD

**Issue by Harbon** [facebook/react-native#4821]
I found that reactNative load react Js from android's default file directory,I want a api to load react Js from   
a stream, not file path. so I can load Js from a network server instead of putting a Js bundle file in local directory.

**Comment by arbesfeld** [comment]
Hey @Harbon, you can do this by downloading the entire JS file to local storage, and then using `setJSBundleFile` to point to this file in local storage. There's no technique for loading from a JS stream on Android at the moment.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/how-can-i-load-from-a-js-streamintegrating-with-existing-app-not-js-bundle-file-path

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
