### ISSUE TITLE
react-native upgrade overwrites .flowconfig

### ISSUE THREAD

**Issue by frantic** [facebook/react-native#4852]
For all other files but `.flowconfig` it asks if I want to override/skip.
Noticed when upgrading from 0.15 to 0.16

@foghina can you take a look?

**Comment by foghina** [comment]
This is caused by 2566ed (cc @AaaChiuuu); we're using raw copy commands instead of going through `mem-fs`. We should probably read the file in memory and do the replacements before writing it using `this.fs.write`.

**Comment by AaaChiuuu** [comment]
I filed t9748598 on myself. I'll hopefully get to it next week!

**Comment by grabbou** [comment]
@AaaChiuuu have you had a chance to look at it? I was going to work on it but looks like it would basically revert this https://github.com/facebook/react-native/commit/2566ed80899a4a071ed0e9c80fca0f28c2125a76#diff-0693784fbf2e944793d2c1f187991860 which makes me confused

**Comment by AaaChiuuu** [comment]
I haven't. @vjeux would know what's the best path to take with flowconfig.

**Comment by frantic** [comment]
I believe the motivation was to avoid maintaining 2 flowconfigs. From the
commit Mike linked seems it would be pretty easy to apply the fix Felix
suggested

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/react-native-upgrade-overwrites-flowconfig

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
