### ISSUE TITLE
No Images are loaded when i build release apk -> RN Android

### ISSUE THREAD

**Issue by BigPun86** [facebook/react-native#4863]
Recently when i buld my signed APK my Android App loads without any Images. I had this before too, but forgot how i fixed it :( . No idea anymore what the reason was...Maybe someone has an idea? 
When i build the debug apk (react-native run-android) Images are loaded.....

**Comment by PCharpentier** [comment]
I had the same problem.

You can see #4084 

To create bundle and assets :

    react-native bundle --assets-dest ./android/app/src/main/res/ --entry-file ./index.android.js --bundle-output ./android/app/src/main/assets/index.android.bundle --platform android -dev false

After, in android project on Android Studio, you can go to Build, Generated APK.

Finally, install your apk with :

    adb install app-release.apk

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/no-images-are-loaded-when-i-build-release-apk-rn-android

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by mkonicek** [comment]
`cd android && ./gradlew assembleRelease` should bundle the assets for you in recent releases of RN.

@facebook-github-bot stack-overflow

**Comment by nearchan** [comment]
@PCharpentier "... -dev false" must change to "... -- dev false" or may get an err message. Test on rn 0.35
