### ISSUE TITLE
how check react-native version?

### ISSUE THREAD

**Issue by PWDream** [facebook/react-native#4899]
hello, can you tell me how check react-native version? thank you

**Comment by gre** [comment]
`npm ls --depth 0`

**Comment by satya164** [comment]
Hey @PWDream 

There's an awesome place to ask question like this one: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see your question, you can vote on answers and mark question as answered etc. This lets us keep a list of bug reports and feature requests on github and especially [Product Pains](https://productpains.com/product/react-native/?tab=top) (again, with voting which is really nice).

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)
