### ISSUE TITLE
[ListView] removeClippedSubviews={true} and overflow:"hidden"

### ISSUE THREAD

**Issue by skatou** [facebook/react-native#4904]
Hi,

The document of ListView says the removeClippedSubviews={true} property only works when the list items have overflow:"hidden" style set.

I'm wordering whether this is just an interface design or an impmentation must.

In my case I want to display a badge on the upper-left corner of each of the list item, in order to avoid clipping the badge by the item margin, I set overflow to "visible" but after that the list is just to lag to be used.

Is it possible to make removeClippedSubviews work with overflow:"visible"?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/listview-removeclippedsubviewstrue-and-overflowhidden

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
