### ISSUE TITLE
native is 0.13-rc 

### ISSUE THREAD

**Issue by PWDream** [facebook/react-native#4918]
hello, I have 0.13-rc in pod manager, the dependencies is 0.16, I every time run the app crash?
how can you tell me why?

**Comment by satya164** [comment]
@PWDream You need to have the same version in both native and JS. RN is no longer distributed through the pods repository. The new instructions to set up the RN cocoapod are here - https://facebook.github.io/react-native/docs/embedded-app-ios.html#content

There's an awesome place to ask question like this one: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see your question, you can vote on answers and mark question as answered etc. This lets us keep a list of bug reports and feature requests on github and especially [Product Pains](https://productpains.com/product/react-native/?tab=top) (again, with voting which is really nice).

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)
