### ISSUE TITLE
0.16.0 Not Updating Generated APK after Running ./gradlew assembleRelease or./gradlew installRelease

### ISSUE THREAD

**Issue by ACCTFORGH** [facebook/react-native#4927]
I followed the guide on the docs to generate the APK. However, after the first version, it stops updating the generated APK. I have tried re-generating the keystone, clean build in Android Studio and re-run both assembleRelease and installRelease.

Is there some kind of cache that I should clear?

I am using RN0.16.0 Android on Mac OS.

**Comment by satya164** [comment]
You can try deleting the build directory under your project.

**Comment by ACCTFORGH** [comment]
@satya164  Thanks. I deleted both the build directory under android/ and android/app. The generated pkg is still not updated while the debug apk is un to date.Shall I try something like the imi files?

**Comment by ACCTFORGH** [comment]
@satya164 Or shall I do something related to the signing key such as generating a complete new set of key files?

**Comment by satya164** [comment]
That's strange. It should work. Are you sure that you don't have a bundle file somewhere in app/src/? Regenerating signing key is unnecessary. Deleting build folder should take care of everything.

**Comment by liuyaodong** [comment]
Is this the same issue with [#4357](https://github.com/facebook/react-native/issues/4357) ?

**Comment by satya164** [comment]
@liuyaodong Might be.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/0160-not-updating-generated-apk-after-running-gradlew-assemblerelease-orgradlew-installrelease

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
