### ISSUE TITLE
Callback on LayoutAnimation never been called.

### ISSUE THREAD

**Issue by alinz** [facebook/react-native#4936]
Version: 0.17
Platform: Android

After tracing the code, I have found that success and failure callbacks never been passed [from here](https://github.com/facebook/react-native/blob/v0.17.0/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIImplementation.java#L499-L504) to [here](https://github.com/facebook/react-native/blob/v0.17.0/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIViewOperationQueue.java#L623-L628).

Is there any reason for this? Or Just because of experimental feature, it never been implemented?

**Comment by browniefed** [comment]
@facebook-github-bot bugfix

**Comment by a9udn9u** [comment]
I can confirm this on Android: https://rnplay.org/apps/7tV7Tg

Callbacks work on iOS.

**Comment by nihgwu** [comment]
any news?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/callback-on-layoutanimation-never-been-called

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by joint-song** [comment]
Has resolved?

Version: 0.38.1
Platform: iOS
`onAnimationDidEnd` never be called.

**Comment by L-Yeiser** [comment]
This still seems to be an issue. Would be awesome to get a resolution to it.

**Comment by isaachinman** [comment]
Still an issue, but the docs now state that `onAnimationDidEnd` is only supported on iOS. Why? This is an essential hook if you want to avoid calling a layout animation while another is currently running.
