### ISSUE TITLE
[Image] Set correct image height

### ISSUE THREAD

**Issue by sorncc** [facebook/react-native#494]
I want to display images from the internet and want to make them as wide as the parent view, which is possible by setting the flex value. But I also want to make the image as high as width * aspectRatio.
Neither StyleSheet.create nor the direct style tag gives access to the image width and aspectRatio.
Any ideas?

**Comment by vjeux** [comment]
Unfortunately CSS doesn't have a good way to do aspect ratio like this. The best hack you can come up with is padding-bottom: 150% but it's super ugly. I prototyped an implementation of aspectRatio and it worked but wasn't spec compliant so I backed off.

In the meantime, you can do height: require('Dimensions').get('window').width / 1.5

**Comment by sorncc** [comment]
If possible, could you show your aspectRatio prototype implantation?

**Comment by paramaggarwal** [comment]
Same concern here. Is there a way to get the width of the parent view? Then I can do the math and set absolute height and width on the Image.

The parent view itself might be configured with alignSelf: 'stretch', so it would get its width during layout. Is there any way to access this computed width?

**Comment by brentvatne** [comment]
@paramaggarwal - check out [these bridge methods on RCTUIManager](https://github.com/facebook/react-native/blob/master/React/Modules/RCTUIManager.m#L971-L1119) for performing measurements

**Comment by paramaggarwal** [comment]
Please feel free to close this. Continuing discussion and sharing code snippets on #858.

**Comment by dubert** [comment]
> @paramaggarwal - would it help if you were given a callback with the width and height of the network image when it finishes loading?
This is what I need. I don't know the width and height before I receive the image. Is there a way to do this @brentvatne ?

**Comment by brentvatne** [comment]
@dubert - there is no way to do this right now, at least as far as I know, but you could potentially submit a patch to provide this information in a load callback at some point. For example, you can add the following code to [RCTImageDownloader](https://github.com/facebook/react-native/blob/a803e3217e5aa88da4c05e96d54209444c96ebee/Libraries/Image/RCTImageDownloader.m#L165-L168) to see the dimensions logged to your Xcode console:


      NSLog(@"*********************************************");
      NSLog(@"%@", url);
      NSLog(@"%f", image.size.height);
      NSLog(@"%f", image.size.width);
      NSLog(@"*********************************************");

I'm curious - what are your use cases for this?

**Comment by dubert** [comment]
I have a listview with rows of flexible height. Some rows have network images, and I want to make them full width, and then have their height proportionally take up as much space as they need.

So I was thinking.. if I could get the height and width, then I could calculate how height it should be and set it. Because right now, if a static height is not set on the image, then it doesn’t show. But each one will be different, and I don't have it before hand.

**Comment by paramaggarwal** [comment]
@dubert You'll see the items stutter around if you implement something like that, because let's say the third image loads first and takes up its space. Then the second one loads and pushes the third one down. Now imagine this constant re-layout for tens of items. Ideally you would want to let your server tell the app of the image `uri` as well as the width and height of the image beforehand.

**Comment by dubert** [comment]
I can handle the stuttering, that's what I want: the image size in the onLoad as a callback. Because then at least I could have a progress bar, and then animated it to it's full height once it's loaded.

I've been digging around the RCT Image library but I don't know any Objective-C. :(

**Comment by paramaggarwal** [comment]
Progress indicator is available: https://github.com/oblador/react-native-image-progress, but image size data is not exposed. Maybe you could start a separate issue to generate interest in implementing the feature?

**Comment by dubert** [comment]
@paramaggarwal Thank you very much for your assistance. One last issue if you're willing to help out. I'm using 0.8.0, and the source looks pretty different for it. Would I add that event here? https://github.com/facebook/react-native/blob/0.8-stable/Libraries/Image/RCTNetworkImageView.m#L123-L124 Doesn't the image need to be passed as a parameter?

I tried using master, but there were many errors in Xcode, I don't know if I'm supposed to build it or something :(

**Comment by paramaggarwal** [comment]
@dubert Ah you are right. Here is what that entire section will look like:

Add this right under `loadEndHandler` declaration on [#L122-L125](https://github.com/facebook/react-native/blob/0.8-stable/Libraries/Image/RCTNetworkImageView.m#L122-L125):

```
void (^loadImageEndHandler)(UIImage *image) = ^(UIImage *image) {
  NSDictionary *event = @{
    @"target": self.reactTag,
    @"size": @{
      @"height": @(image.size.height),
      @"width": @(image.size.width)
    }
  };
  [_eventDispatcher sendInputEventWithName:@"loaded" body:event];
};
```

and then call `loadImageEndHandler(image);` instead in the `else` block on line [#L159](https://github.com/facebook/react-native/blob/0.8-stable/Libraries/Image/RCTNetworkImageView.m#L159).

Then you can listen to `e.size` in `onLoad`. If it works, please do raise a PR! This is useful.

**Comment by dubert** [comment]
Woohoo! I got it working, thanks so much @paramaggarwal. I'll try to get master working on my machine, so I can submit a PR for it.

**Comment by MossP** [comment]
I look forward to this PR! :) :+1:

**Comment by MossP** [comment]
I'm having trouble implementing this. The size that gets returned across the bridge is the size that I had specified in the styles all of the time? Skipping the size declaration results in no image being loaded though. Could either of you shed any further light on this? @dubert, @paramaggarwal ?

**Comment by MossP** [comment]
Further testing shows that it's not always the defined sizes that get returned. The sizes vary depending on the `resizeMode` used and whether the image would fill the space or not. I Can see different sizes coming through but, none of them relate to the actual size of the image that I'm seeing?

**Comment by paramaggarwal** [comment]
@MossP I haven't tried this out, but the `image.size` should be the height/width of the image itself. The behaviour you describe seems to be the case if it was `imageView.size`. @dubert has actually tried this out - so will let him respond.

**Comment by MossP** [comment]
Thanks, @paramaggarwal. I think I may have just found it. The image must have resizeMode 'contain' applied and also the sizes returned are scaled in proportion to the device dpi, e.g. iPhone6 returns 50/100 for a 100/200 image. Thanks for the code above. I think the only place it fails is for gif's but that's due to the alternate loading method.

**Comment by MossP** [comment]
Extra info for anyone else.. the style attributed to the `<Image />` element needs to be larger than the image it's loading in order to return the correct size. At the point that the image begins to get shrunk to fit the frame the sizes start to change their scaling value making meaningful readings difficult.

e.g. loading a 300/200 image yields the following results. (Container Size vs reported image size)
```
container / reported
500*500   / 160*100
400*400   / 160*100
300*300   / 160*100
200*200   / 160*100
100*100   / 100*62.5
50*50     / 50*31.5
10*10     / 10*6.5
```

**Comment by originerd** [comment]
I've published to npm [react-native-fit-image](https://www.npmjs.com/package/react-native-fit-image). It enables you to draw responsive image component.
