### ISSUE TITLE
[iOS] RCTImageLoader doesn't call completion block.

### ISSUE THREAD

**Issue by skatou** [facebook/react-native#4942]
Hi there,

The method RCTImageLoader#loadImageWithTag:size:scale:resizeMode:progressBlock:completionBlock: doesn't call completionBlock when the passed in image tag is empty.

I don't think an implementation fails to call completion block is a strictly speaking correct implemention, it can be improved.

Thanks.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/ios-rctimageloader-doesnt-call-completion-block

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
