### ISSUE TITLE
libsystem_kernel.dylib`mach_msg_trap + 10, queue = 'com.apple.main-thread', stop reason = signal SIGKILL

### ISSUE THREAD

**Issue by cancan101** [facebook/react-native#4947]
Sometimes but not always when I exit the application from the multi task display (hitting home twice), I get:
```
(lldb) bt
* thread #1: tid = 0xc10373, 0x00000001100fd4de libsystem_kernel.dylib`mach_msg_trap + 10, queue = 'com.apple.main-thread', stop reason = signal SIGKILL
    frame #0: 0x00000001100fd4de libsystem_kernel.dylib`mach_msg_trap + 10
    frame #1: 0x00000001100fc64f libsystem_kernel.dylib`mach_msg + 55
    frame #2: 0x000000010ce1d144 CoreFoundation`__CFRunLoopServiceMachPort + 212
    frame #3: 0x000000010ce1c59f CoreFoundation`__CFRunLoopRun + 1295
    frame #4: 0x000000010ce1be08 CoreFoundation`CFRunLoopRunSpecific + 488
    frame #5: 0x00000001114f5ad2 GraphicsServices`GSEventRunModal + 161
    frame #6: 0x000000010e63630d UIKit`UIApplicationMain + 171
  * frame #7: 0x000000010a45b38f app`main(argc=1, argv=0x00007fff557a86a8) + 111 at main.m:16
    frame #8: 0x000000010fdcc92d libdyld.dylib`start + 1
    frame #9: 0x000000010fdcc92d libdyld.dylib`start + 1
```

**Comment by brentvatne** [comment]
cc @nicklockwood @tadeuzagallo @javache

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/libsystemkerneldylibmachmsgtrap-10-queue-comapplemain-thread-stop-reason-signal-sigkill

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
