### ISSUE TITLE
How to call another components function in a component? I'm trying to incorporate signIn() of GoogleSignIn componentin my component. 

### ISSUE THREAD

**Issue by aditya1994** [facebook/react-native#4959]
var AwesomeProject = React.createClass({
componentDidMount: function() {
   
  GoogleSignin.init();
  DeviceEventEmitter.addListener('googleSignInError', (error) => {
  console.log('ERROR signin in', error);
});

// callback on sign-in success
DeviceEventEmitter.addListener('googleSignIn', (user) => {
  console.log(user);
  this.setState({user: user});
 }); 
  this.refs['child'].signin(); 

},
  render: function(){
 return(   

  <View style= { styles.messagestyle }>
  <Text style= {styles.nice}>
     hi <GoogleSignin ref="child"/>
   </Text>
  </View>

           
      );
      } 
});

**Comment by satya164** [comment]
Hey @aditya1994 

There's an awesome place to ask question like this one: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see your question, you can vote on answers and mark question as answered etc. This lets us keep a list of bug reports and feature requests on github and especially [Product Pains](https://productpains.com/product/react-native/?tab=top) (again, with voting which is really nice).

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)
