### ISSUE TITLE
iPhone 5 issues with loading images

### ISSUE THREAD

**Issue by bpeters** [facebook/react-native#4969]
I am inline requiring image sources like `source={require('../assets/logo.png')}` which work perfectly for iPhone 6 and up. However, for iPhone 5 I get this error.

`Image has no propType for native prop RCTImageView.src of native type NSString`

on react-native v. 0.17

**Comment by brentvatne** [comment]
Hi @bpeters - can you try posting this to StackOverflow first with a reproducible example project? I think there is a problem with a mismatch between the JS bundle being used and the binary version (compiled IPA) on your iPhone 5. Maybe you had the app installed on it already and are fetching from a packager that you have since updated?

Tested this on UIExplorer and it works on iPhone 5 and 5s on iOS 9 :)
