### ISSUE TITLE
backButtonTitle not working on current version

### ISSUE THREAD

**Issue by CoericK** [facebook/react-native#4979]
As documentation says on https://facebook.github.io/react-native/docs/navigatorios.html, if i want to customize the text of the back button i should pass backButtonTitle into the props, im doing it but it is not working keep showing the title of the previous screen, i used leftButtonTitle but it hides the back arrow.

Any idea if this is a bug ? or im doing it wrong?

**Comment by satya164** [comment]
`NavigatorIOS` is not maintained by Facebook. It's maintained by the community. If you have a fix then PRs are welcome. But it'll be probably better to use `Navigator` instead.

**Comment by CoericK** [comment]
Hey @satya164 thank you for give me an answer, sorry im new to react-native and didnt know that. How can i know if a component its made by facebook or the community? Gonna look into Navigator.

**Comment by satya164** [comment]
@CoericK The `NavigatorIOS` docs say that it's not maintained by Facebook - http://facebook.github.io/react-native/docs/navigatorios.html#content

**Comment by satya164** [comment]
Also though I'm not familiar with `NavigatorIOS`, I think `backButtonTitle` is specified by the previous route, but not the current route. We should make this clear in the docs, if it's the case.

**Comment by vikeri** [comment]
It is correct that the backButtonTitle is set in the previous route.

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/backbuttontitle-not-working-on-current-version

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix.**
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by facebook-github-bot-5** [comment]
@charpeni tells me to close this issue. If you think it should still be opened let us know why.
