### ISSUE TITLE
Auto-refresh simulator

### ISSUE THREAD

**Issue by nick** [facebook/react-native#5]
Is it possible to have the simulator automatically refresh when a file is changed instead of Cmd-R?

**Comment by vjeux** [comment]
Done

**Comment by sokra** [comment]
@amasad I used the easter holydays to implement new SourceMaps for webpack. `devtool: "cheap-inline-source-map"` should be much faster (or `devtool: "cheap-module-inline-source-map"` if you want source mappings to jsx). Still experimental, but you can try it.

**Comment by pilwon** [comment]
Thanks @sokra! :+1::+1::+1:

We are not able to process `react-native` app with `webpack` entirely because [MessageQueue module uses dynamic require](https://github.com/facebook/react-native/issues/395#issuecomment-87723931) in a way that is supported by `webpack` at the moment. The fact that all `react-native` modules internally use flattened module names (ex: `require('ModuleName')`) make it even trickier (or impossible) to hack with `ContextReplacementPlugin`. A hybrid approach (using `react-native's packager` for `node_modules/react-native/**/*` and `webpack` for the rest) is one way to use `webpack` but we cannot test the new `cheap-inline-source-map` devtool option with that approach because `packager` only cares about the code, not the source map.

I believe we need more powerful way to handle dynamic requires that work with aliased module names in order to process all files with `webpack` unless `react-native` changes its code to support `webpack`.

**Comment by amasad** [comment]
Thanks @sokra. What @pilwon said about how we're not ready to completely switch to a standard webpack. But I have some ideas on how we can integrate webpack as a frontend and have our packager be plugged in as loader and resolver. Anyways, what you did should come in handy

**Comment by vjeux** [comment]
The way we currently communicate for Obj-C to JavaScript is by doing `eval('require("ModuleName").methodName(arguments)');`. Fortunately, most of it is abstracted away in only 7 methods. What we need to do is to change the call to `eval('ReactNativeJSExposedMethods.call('ModuleName', 'MethodName', arguments)')` and have all those methods register themselves before being called.

```
RCTEventEmitter.receiveTouches
RCTNativeAppEventEmitter.emit
RCTEventEmitter.receiveEvent
ReactIOS.unmountComponentAtNodeAndRemoveContainer
AppRegistry.runApplication
RCTJSTimers.callTimers
RCTDeviceEventEmitter.emit
```

This is on my todo list but I'm unlikely going to be able to get to it this week if someone wants to pick it up
