### ISSUE TITLE
Android WebView and  android:windowSoftInputMode="adjustResize" not work. 

### ISSUE THREAD

**Issue by barbarosh** [facebook/react-native#5000]
Keyboard cover html inputs. How to fix ?

**Comment by ncnlinh** [comment]
Hi, @barbarosh did you find out a way to solve this?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-webview-and-androidwindowsoftinputmodeadjustresize-not-work-

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
