### ISSUE TITLE
Add a flag to discriminate between debug and release builds in JS code

### ISSUE THREAD

**Issue by scouten** [facebook/react-native#5006]
I'd like to add additional UI to my app's debug build to monitor HTTP traffic and other performance characteristics. (Think of this as akin to the frame rate monitor.)

I can't find a suitable hook that I can use in my JS code to enable this for debug builds only. Is there one? If not, please consider adding one.

I'm a RN newbie; please forgive if this already exists. (A link to documentation would be much appreciated if so.)

**Comment by scouten** [comment]
Cross-posted to:

http://stackoverflow.com/questions/34498970/how-can-i-determine-if-my-react-native-app-is-a-debug-or-release-build-from-java

https://productpains.com/post/react-native/add-a-flag-in-js-environment-to-discriminate-debug-and-release-build/

**Comment by philikon** [comment]
```js
if (__DEV__) {
  ...
}
```
is what you want. Note: since RN 0.16, the `__DEV__` variable and all its uses are transformed out of the bundle (either by directly transforming it out or by replacing `__DEV__` with `false` and letting dead-code elimination in the minification phase deal with the debug code). So there's no penalty to using it, the debug code won't even be there in a release build.

**Comment by ide** [comment]
@philikon's answer is right

**Comment by scouten** [comment]
OK, confirmed that this works as expected in my app. Is this documented somewhere?
