### ISSUE TITLE
Sending Events to JavaScript

### ISSUE THREAD

**Issue by lvming6816077** [facebook/react-native#5013]
I follow the doc to send events to javaScript, but it not work, I also find the [stackoverflow](http://stackoverflow.com/questions/29424913/is-react-native-modules-sending-events-to-javascript-doc-correct) but it still not work, someone can help me to solve this problem?

**Comment by christopherdro** [comment]
According to your stack overflow questions you are using `sendAppWithEventName` which requires you to use `NativeAppEventEmitter` instead of `DeviceEventEmitter`.

Your listener should look something like this....
```javascript
var subscription = NativeAppEventEmitter.addListener(
  'EventReminder',
  (reminder) => console.log(reminder.name)
);
```

You can also just change change your native Obj-c to use `sendDeviceEventWithName` instead, as suggested.
