### ISSUE TITLE
[NavigatorIOS] Implement hidesBottomBarWhenPushed to hide TabBar while doing push in native module

### ISSUE THREAD

**Issue by nicholasding** [facebook/react-native#5031]
I followed the discussion on https://github.com/facebook/react-native/issues/720 and https://github.com/facebook/react-native/issues/1489, it seems the problem is not solved yet.

While it's really easy to implement in Objective-C while setting viewController.hidesBottomBarWhenPushed = YES, I'm wondering if it's possible to have it in native module.

```
// Objective-C
UIViewController *vc = [[UIViewController alloc] init];
vc.hidesBottomBarWhenPushed = YES;
[self.navigationController pushViewController:vc animated:YES];
```

```
// JavaScript
this.props.navigator.push({
    title: 'Detailed View',
    component: DetailedView,
    hidesBottomBarWhenPushed: true, // if possible
});
```

In the meanwhile, I was trying to modify RCTNavItem.m to pass additional attribute (hidesBottomBarWhenPushed) and RCTNavigator.m to inject code before the [_navigationController pushViewController:vc animated:(currentReactCount > 1)];

But it doesn't work even though the attribute is correctly set before the pushViewController method, could anyone give me some insight about how to make it work?

**Comment by kkgelu** [comment]
+100000

It should be supported as native code only need one line(hidesBottomBarWhenPushed). It's common to hide Tabbar when going to deeper level scenes. Having a top level navigator (as suggested by christopherdro in #1489) means all tabs share the same navigator and nav bar instead of maintaining its own backstack. I spent days trying suggested workarounds, none is good.

**Comment by atlas1119** [comment]
this problem is not solved yet??

**Comment by williambout** [comment]
:+1:

**Comment by follyxing** [comment]
not solved yet?? +1111

**Comment by lprhodes** [comment]
Unfortunately not - it's really odd that going into RCTNavigator and forcing tabBarController doesn't work.

As we need to get a release out I've opted to use a transform to move it out of the way inside the `- (void)navigationController:(UINavigationController *)navigationController
      willShowViewController:(__unused UIViewController *)viewController
                    animated:(__unused BOOL)animated` method of RCTNavigator

```    
if (indexOfTo == 0) {
    [UIView animateWithDuration:0.3f animations:^{
        _navigationController.tabBarController.tabBar.transform = CGAffineTransformIdentity;
    } completion:nil];
} else {
    [UIView animateWithDuration:0.3f animations:^{
        _navigationController.tabBarController.tabBar.transform = CGAffineTransformMakeTranslation(0, 60);
    } completion:nil];
}
```

**Comment by nicholasding** [comment]
I dived into the code, I believe the problem is much deeper than I originally thought.

The problem I found is due to the wrong view hierarchy. To make it work, the TabBarViewController needs to hold a UINavigationController as its direct child, but now it's a wrapper view controller due to the nature of RN.

To solve the problem, I'm thinking to modify the tab bar to let it aware the children if it's a nav.

**Comment by jainmitesh09** [comment]
Hi all,
any working solution for this issue?

**Comment by mcampsall** [comment]
I got it to work! See [this SO answer](http://stackoverflow.com/a/38532872/1102948) for the code. I also posted it [here if you want to see it in context](https://github.com/facebook/react-native/issues/1489)

**Comment by jainmitesh09** [comment]
@mcampsall  Thank you! I'll look at it over the week and get back to you.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/navigatorios-implement-hidesbottombarwhenpushed-to-hide-tabbar-while-doing-push-in-native-module

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
