### ISSUE TITLE
App gets stuck when connecting to debugger

### ISSUE THREAD

**Issue by onzag** [facebook/react-native#5035]
I have a huge problem with react native 0.17 I'm using it to create an android application, however if I try to debug it gets stuck forever in the "Connecting to remote debugger" part, when it fact it connects at first time, but once I try to reload it will just get stuck. I checked the connections, everything is fine.

So I stopped trying and tried using console.warn, however that is also not working, and they have some unexpected behaviour, eg.

```javascript
console.warn('1');
let finalquery = query || {};
console.warn('2');
finalquery.authtoken = this.state.authtoken;
console.warn('3');
```

I'll get 1 but not 2 or 3, query is just undefined, what happened, why did it stop?

```jsx
<Tag onSomething={()=>{
    console.warn('stuff');
    doSomething();
}}>
```

doSomething "will be" called but console warn will not; how does that work?

I also have places in which I make awful errors like:

```javascript
var promise = getPromise(); //I forgot to give a return, so I got undefined
stuff.then(() => {
   //do stuff
})
```
And I get no error at all, the code keeps running like nothing, even worse...

```
undefined();
```

Will actually make the code to stop without warning or error at all.

And if the debugger doesn't work how would I go and find these sort of mistakes?

**Comment by satya164** [comment]
I've also face this issue where it just gets stuck.

**Comment by iZaL** [comment]
:+1:

**Comment by onzag** [comment]
I found that the issue about the lack of error message happens when you have something undefined (but not set as undefined), that means undeclared, in which case the code will stop without throwing any exception.

I actually find great that the code fails if you forget to set a variable...

```function(x){
    let n = xx || this.state.defaultx; //xx not declared
    //code will not execute
}
```

```function(x){
    xx();//not declared will stop
   //code will not execute
}
```

```
//Forgot to import Easing
//Code will not execute, no errors thrown
Animated.timing(
   this.state.angle,
   {
     toValue: 360,
     duration: 2000,
     easing: Easing.linear
   },
).start();
```

**Comment by martinbigio** [comment]
If you add 'use strict'; on the top of your module, don't you get an actual error?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/app-gets-stuck-when-connecting-to-debugger

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
