### ISSUE TITLE
[Navigator.NavigationBar] fails to display the right bar button when not rendered full width.

### ISSUE THREAD

**Issue by dapetcu21** [facebook/react-native#5045]
We're trying to implement split pane navigation in our iPad app.
We have two Navigator instances side by side. The problem is that NavigationBar is styled using `Dimensions.get('window').width` and some white overlay starts covering my right bar button.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/navigatornavigationbar-fails-to-display-the-right-bar-button-when-not-rendered-full-width

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
