### ISSUE TITLE
Custom resolve extensions [Packager]

### ISSUE THREAD

**Issue by caske33** [facebook/react-native#5075]
It would be nice if we could configure the packager with custom resolve extensions like in webpack:

```
resolve: {
    extensions: ['', '.web.js', '.js', '.jsx']
  },
```

This way we can have a shared .native.js (o .mobile.js) file extension for common android and iOS code (but that is not shared with web) and a .web.js code for web specific code, a .android.js and .ios.js for those platforms while still having the .js extension for all platforms. 

maybe something like:

```
resolve: {
  android: ["", ".android.js", ".native.js", ".js"],
  ios: ["", ".ios.js", ".native.js", ".js"]
}
```

**Comment by brentvatne** [comment]
cc @spicyj @martinbigio

**Comment by martinbigio** [comment]
This is an interesting idea. At the moment the extension resolution algorithm is hardcoded on the resolver code. @spicyj recently had to tweak it include ".native". What if for each platform the user could indicate a list ordered by priority of the extensions the packager should look at when resolving modules?

**Comment by martinbigio** [comment]
cc @davidaurelio

**Comment by caske33** [comment]
@martinbigio From which version of React Native is the .native extension supposed to work?

**Comment by martinbigio** [comment]
it was added by @spicyj on 6a838a4201f99ae5e88b3684bb798d363815dd53. @spicyj, @davidaurelio  what do you guys think?

**Comment by spicyj** [comment]
I think this is probably reasonable. I didn't implement this myself because getting the logic in HasteMap right seemed like more of a hassle than I wanted to go through at the time but it should be possible to make work. Perhaps we can just write `["", ".[platform].js", ".native.js", ".js"]` or something like that instead of having fully-separate options per platform?

**Comment by martinbigio** [comment]
Yeah, that sounds good to me.

@caske33 do you want to send a PR for this? I could give you context and help reviewing :)

**Comment by caske33** [comment]
@martinbigio Unfortunately I don't really have the time myself either :cry:, I just wanted to point out a possible problem. If the .native extension is there, I think most use-cases are solved, but I think it still might be a good option to have.

**Comment by negativetwelve** [comment]
Does it make sense to add this to `rn-cli.config.js`? I can see us defining a function something like 

```
extensions(platform) {
  // Returns an array of extensions
}
```

I'm going to work on adding this, let me know if this is the approach we want to take!

**Comment by martinbigio** [comment]
Yes, adding it to the cli would be useful!

**Comment by negativetwelve** [comment]
Spent a little bit of time with this and ran into some of the issues that @spicyj mentioned above. Namely, the platform can't be an argument to the function because this is passed to both the server and the resolver. Initially, we need to search for all extensions to build our HasteMap, but then later, we only want to filter by the platform that's consuming the packager.

I'm currently toying around with changing the HasteMap to look up files via extension rather than the platform...does that seem like a step in the wrong direction? I'm not sure how else to make the ios platform aware of something like `native.js` or even `mobile.js`, etc.

**Comment by martinbigio** [comment]
When the dependency graph is built we shouldn't exclude any extension (don't invoke the function yet). The function should be invoked when processing a request as the `platform` is a request parameter. For instance for the HasteMap the function should be called here: https://github.com/facebook/react-native/search?utf8=%E2%9C%93&q=getModule%28name%2C+platform+%3D+null%29+%7B

**Comment by jsierles** [comment]
@negativetwelve any progress on a PR for this? We're trying to clean up issues to keep them focused on bugs, and looking to see which can be closed in favor of PRs or Product Pains entries. Thanks!

**Comment by davidaurelio** [comment]
Progress on this:

`Platform.OS` / `React.Platform.OS` get inlined, so platform-specific stuff can be included like this without size overhead in production:

```js
const Platform = require('react-native').Platform;
module.exports = Platform.OS === 'ios' ? require('./the-ios-thing') : require('./the-android-thing');
```

iirc we also support a `"react-native"` field in package.json, which works like the `"browser"` field.

**Comment by jsierles** [comment]
Thanks @davidaurelio! Sounds like enough use cases are covered now to achieve the goal of the original issue, so I'll close this out for now.

Feel free to continue discussion here or on Product Pains about custom extensions.
