### ISSUE TITLE
[iOS][TextInput] Add contentSize to onChange/onChangeText event

### ISSUE THREAD

**Issue by skoob13** [facebook/react-native#5095]
It would be great if width and height will be accessible when onChange event fires. It's already available on Android as contentSize, so I think it should be available on iOS as well.

**Comment by mangogogos** [comment]
just an FYI that this was added in 481f560

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/iostextinput-add-contentsize-to-onchangeonchangetext-event

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
