### ISSUE TITLE
ImageEditingManager.cropImage does not work correctly after upgrading from 0.15 to 0.17

### ISSUE THREAD

**Issue by ms88privat** [facebook/react-native#5113]
My App takes pictures with https://github.com/lwansbrough/react-native-camera (and the option `Camera.constants.CaptureTarget.disk`). 

In 0.17 when I'm trying to crop the image via `ImageEditingManager.cropImage(url, cropData)`, it doesn't work correctly anymore. It will result in a black or sometimes some different color image. For me, it looks like, it shows only one pixel of it. I tried all different resizeModes and imageSizes to display it, but it looks always the same. Images from the assets library still work fine.

`url = 
'/var/mobile/Containers/Data/Application/AA2AEEF1-85A1-4268-9129-D65C671330D2/Documents/F8749E02-6818-4CDB-8C15-83C96132C945.jpg'`

Anybody know what changed here?

Thanks.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/imageeditingmanagercropimage-does-not-work-correctly-after-upgrading-from-015-to-017

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
