### ISSUE TITLE
UnableToResolveError for spaces in path?

### ISSUE THREAD

**Issue by malkomalko** [facebook/react-native#5115]
https://gist.github.com/malkomalko/dfdbf6c92cab21731f70#file-gistfile1-txt-L34

It appears that the packager gets confused when there is a space in the path.  This only happens in this case.  I'm on 0.15.0 btw.  Let me know if this has been fixed in later versions.

**Comment by jsierles** [comment]
@amasad any ideas on this one? It's still happening on 0.21.0.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/unabletoresolveerror-for-spaces-in-path

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
