### ISSUE TITLE
Camera Roll, User denied access, -3311

### ISSUE THREAD

**Issue by steveleec** [facebook/react-native#5134]
This is how my code looks like

```javascript
 componentDidMount() {
    var fetchParams = {
      first: 25
    };

    CameraRoll.getPhotos(fetchParams, this.storeImages.bind(this), this.logError);
  }

  storeImages (data) {
    var assets = data.edges;
    var images = assets.map((asset) => asset.node.image);
    this.setState({
      images: images
    });
  }

  logError (error) {
    console.warn(error);
  }
```

Once I reached this point in the app, I got the following error:
```javascript
Object {code: -3311, message: "User denied access", nativeStackIOS: Array[9], domain: "ALAssetsLibraryErrorDomain"}
```

Any clue about how to fix it?

**Comment by adriansprod** [comment]
+1, was fine before

**Comment by grabbou** [comment]
@facebook-github-bot stackoverflow

**Comment by grabbou** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

PS. iOS-wise, once you have dismissed permission box, you can go to settings -> choose your app and enable access back again. Given the error, you can prompt your users to do so.
