### ISSUE TITLE
ViewManager is different between iOS and Android, why?

### ISSUE THREAD

**Issue by GitMaYi** [facebook/react-native#5139]
When I use EditText, I need a function to tell js how many numbers before cursor:  
- In iOS, i can use @ReactMethod to give JS a callback in ReactTextInputManager cause ViewManager is a Module
- In Android, js invoke ViewManager's method by override getCommandsMap() and receiveCommand() in custom ViewManager. The problem is this way can't pass a callback. So the solution is I use a JavaScriptModule, like RCTEventEmitter, to invoke js.  

Is there a better solution to figure it out? Why android and iOS designed differently?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/viewmanager-is-different-between-ios-and-android-why

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
