### ISSUE TITLE
can't load static image,when i put the jsbundle and images in server

### ISSUE THREAD

**Issue by huangqiaobo** [facebook/react-native#5142]
"react-native": "^0.17.0"

I run the commond:
react-native bundle \
  --entry-file index.ios.js \
  --platform ios \
  --dev false \
  --bundle-output ./main.jsbundle \
  --assets-dest ./ \

then I get
main.jsbundle and  assets/
 I found that all of my image is in assets folder.

Then I push the main.jsbundle and assets into service.

Then I use the url to load the bundle :
jsCodeLocation = [NSURL URLWithString:[NSString stringWithFormat:@"http://10.10.30.96/ota/main.jsbundle"];

then i find that ,I cant load the image.

what's the right way to load static images from server?

**Comment by huangqiaobo** [comment]
I find that the RCTImageLoader load image from 'http://10.10.30.96/assets/.../image.png'.
But my assets is in  'http://10.10.30.96/ota/assets/.../image.png'
The RCTImageLoader get a wrong url.
then I find the code in resolveAssetSource.js

var match = scriptURL && scriptURL.match(/^https?:\/\/.*?\//);

when I change the code like this

var match = scriptURL && scriptURL.match(/^https?:\/\/.*\//);

Then I can get true image URL.

It's a bug?

**Comment by huangqiaobo** [comment]
The image source is not need server URL only.The pathname is also necessary

**Comment by huangqiaobo** [comment]
@frantic

**Comment by frantic** [comment]
Hey @huangqiaobo, this behaviour is intentional. When you build an offline bundle with `react-native bundle` command it is supposed to be used only from somewhere on local disk, not network. If you point React Native to your server location it will think it's using development server and will load JS and images every single time. Additionally, it won't work if your user doesn't have internet connection.

The better way to do this is by packaging everything into an archive, downloading and unzipping it somewhere into `~/Documents` folder and pointing React Native there. There is a bunch of community projects that offer this functionality as a service.

I'm closing this as not-an-issue, but feel free to comment if you have any questions.


P.S. I do agree that that regex looks strange. Feel free to send a PR

**Comment by sdyxch** [comment]
+1

**Comment by huangqiaobo** [comment]
@sdyxch rn不推荐在release包里面直接用server的bundle，事实上如果你的项目有在build的时候运行RN的脚本的话，那么在release包里面，jsbundle和assets已经有一份在mainbundle里面，release包直接加载mainbundle里面的jsbundle就可以了。如果你想做热更新，可以把mainbundle里面的jsbundle和assets复制到你可以控制的目录下。

**Comment by sdyxch** [comment]
@huangqiaobo 
我是打算直接把bundle，发布到cdn。。
