### ISSUE TITLE
Implement defaultSource for Image on Android

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#5158]
Background: https://github.com/facebook/react-native/pull/5074#issuecomment-169399675

**Comment by kristjanmik** [comment]
@nicklockwood Do we want the defaultSource property to be implemented on Android as well? We need some mechanism to handle fallback images on Android. I could give it a shot if wanted.

**Comment by nicklockwood** [comment]
@kristjanmik we're still discussing it. I'm not sure if it's needed on iOS since you can implement the same functionality with the onLoad event, but apparently that doesn't work correctly on Android?

If you do decided to implement it, I believe the intended (but currently broken) behavior on iOS is that it should appear when the image first starts loading, and disappear when it's replaced by the correct image. If the image never loads, or loads with an error, it will stay indefinitely.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/implement-defaultsource-for-image-on-android

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
