### ISSUE TITLE
Change babel-plugin-external-helpers-2 to babel-plugin-external-helpers

### ISSUE THREAD

**Issue by ide** [facebook/react-native#5166]
See https://github.com/babel/babel/blob/master/CHANGELOG.md#640

> Breaking Change
>
> babel-plugin-external-helpers: 3205 Renamed from babel-plugin-external-helpers-2 due to someone taking the npm name beforehand.

@martinbigio could you take a look at this since it involves updating npm packages?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/change-babel-plugin-external-helpers-2-to-babel-plugin-external-helpers

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
