### ISSUE TITLE
[iOS] 0.17 tintColor set to default blue if first set and then remove

### ISSUE THREAD

**Issue by seph14** [facebook/react-native#5172]
On upgrading from 0.16 to 0.17, the tintColor prop doesn't work the same on images.
I have a image with style 
```
{
  borderRadius: 1
  height: 24
  tintColor: "#1b1b1b"
  width: 24
}
```

it was rendering in black(#1b1b1b) in 0.16, but it now renders in blue (as shown in below)
![bookmark_blue](https://cloud.githubusercontent.com/assets/6417336/12161947/a68ac888-b536-11e5-9239-bbf8b573e6a2.png)

Was this an intended change or it a bug?

**Comment by seph14** [comment]
on further investigation, it looks like when i have an image with tintColor style set, and then remove it on a state change, tintColor will be rendering wrong.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/ios-017-tintcolor-set-to-default-blue-if-first-set-and-then-remove

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
