### ISSUE TITLE
[iOS][Text] Can't measure Text's layout inside Text

### ISSUE THREAD

**Issue by kmsheng** [facebook/react-native#5173]
Demo:
https://rnplay.org/apps/yAMXUg

1. onLayout is never fired
2. measureLayout throws "Attempted to measure layout but offset or dimensions were NaN"

![screen shot 2016-01-07 at 11 47 53 am](https://cloud.githubusercontent.com/assets/880569/12162008/8d07930e-b537-11e5-8a6d-6c481b053fe9.png)

**Comment by Fanghao** [comment]
maybe take a look at https://github.com/facebook/react-native/commit/fe7edf08603a892435eb3c30f28055ba5bc02dc0?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/iostext-cant-measure-texts-layout-inside-text

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
