### ISSUE TITLE
The RCTURLRequestHandlers RCTFileRequestHandler: 0x7b2392d0 and RCTDataRequestHandler: 0x7b233910 both reported that they can handle the request NSMutableURLRequest: 0x7da29ed0 { URL: (null) }, and have equal priority (0). This could result in non-deterministic behavior.

### ISSUE THREAD

**Issue by liukepeng** [facebook/react-native#5175]
The log error :The RCTURLRequestHandlers RCTFileRequestHandler: 0x7b2392d0 and RCTDataRequestHandler: 0x7b233910 both reported that they can handle the request NSMutableURLRequest: 0x7da29ed0 { URL: (null) }, and have equal priority (0). This could result in non-deterministic behavior.
can anyone tell me how to solve it?

**Comment by epeli** [comment]
I also saw this error and it was because I accidentally passed `undefined` as `path` to `fetch(path)`. User error but error message could be better.

**Comment by sallyahmed** [comment]
any update i have the same issue

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/the-rcturlrequesthandlers-rctfilerequesthandler-0x7b2392d0-and-rctdatarequesthandler-0x7b233910-both-reported-that-they-can-handle-the-request-nsmutableurlrequest-0x7da29ed0-url-null-and-have-equal-priority-0-this-could-result-in-non-deterministic-behavior

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
