### ISSUE TITLE
does Image props capInset has no any effect?

### ISSUE THREAD

**Issue by tantou** [facebook/react-native#5176]
I have use image with `capInset` like this:
#### style
```
var style = StyleSheet.create({
 bubble:{
  width:200
}
});
```
#### bubble component
```
<Image capInsets={{top:30,left:15,bottom:20,right:20}} style={styles.bubble} source={imgUrl}>
    <Text>{message}</Text>
</Image>
```
and the image size is :
`height`:108,
`width`:130

`the source image`:
![receivertextnodebkg 2x](https://cloud.githubusercontent.com/assets/1531645/12166199/1c98ea32-b55f-11e5-9bec-d25212285d5b.png)

but I can not get the expected result .

Could anyone tell how to resolve this ? 
Or is the capInset has no any effect when using react native?
Or is that a bug with capInset in react-native

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/does-image-props-capinset-has-no-any-effect

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by mkonicek** [comment]
@facebook-github-bot stack-overflow

**Comment by MattFoley** [comment]
This may actually be a bug as of 0.33 of RN. Digging deeper now, but it looks like setCapInsets calls `reloadImage` and in certain cases may never call `updateImage` (which looks like what actually calls resizableImageWithCapInsets).

I'll follow up with more info as I dig in.
