### ISSUE TITLE
Installation issues in react native 

### ISSUE THREAD

**Issue by Hari70a** [facebook/react-native#5181]
I am getting error after the installation of npm
 Here I have attached the screenshot of my error

![issues](https://cloud.githubusercontent.com/assets/14177973/12169882/2da95f0c-b562-11e5-843c-6865495dc26c.jpg)

I need  your help obviously
Thanks in advance

**Comment by rmevans9** [comment]
More then likely your npm install location is not defined in your PATH variable on windows. You can see the location that needs added in your screenshot right after you do "npm install -g react-native-cli". Once you add that location to your PATH variable restart your command prompt and try the react-native init command again.

**Comment by Hari70a** [comment]
how to add npm install location in the path variable

**Comment by rmevans9** [comment]
http://windowsitpro.com/systems-management/how-can-i-add-new-folder-my-system-path

That should get you on the right direction. Once you get to the PATH variable you will just need to add the path "C:\Users\ADMIN\AppData\Roaming\npm to it.

**Comment by Hari70a** [comment]
I have all the steps given above 
again the same error continues

please guide me

**Comment by bbk1985** [comment]
Can you paste your PATH value?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/installation-issues-in-react-native-

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
