### ISSUE TITLE
ScrollView  on NavigationBar not working,not scroll

### ISSUE THREAD

**Issue by liubobo** [facebook/react-native#5193]
ScrollView  on NavigationBar not working,not scroll

**Comment by Ehesp** [comment]
Can you should a code example.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/scrollview-on-navigationbar-not-workingnot-scroll

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
