### ISSUE TITLE
anyway to dismiss keyboard without losing focus on TextInput?

### ISSUE THREAD

**Issue by narychen** [facebook/react-native#5194]
textInput.blur() or dismisskeyboard() call will lose focus on textInput.
I want to keep the focus and cursor staying there. Is there anyway to do it ?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/anyway-to-dismiss-keyboard-without-losing-focus-on-textinput

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
