### ISSUE TITLE
com.squareup.SocketRocket.NetworkThrea(17): EXC_BAD_ACCESS (code=EXC_I386_GPFLT)

### ISSUE THREAD

**Issue by montogeek** [facebook/react-native#5208]
Hi!

After a few minutes this errors happens:
```
com.squareup.SocketRocket.NetworkThrea(17): EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
```

RN: 0.17.0

**Comment by jnak** [comment]
same here. did you end up finding the root cause?

**Comment by montogeek** [comment]
Not, try updating to the latest version :)

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/comsquareupsocketrocketnetworkthrea17-excbadaccess-codeexci386gpflt

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
