### ISSUE TITLE
Custom UITextView can't get reference

### ISSUE THREAD

**Issue by ibraheemabukhdair** [facebook/react-native#5228]
I have a custom UITexViewComponents which are loaded dynamically into a listview. I wan't to load data into it, which is HTML, that is the only way I know how to display HTML in react native. Loading the html into it is done before a user interacts with it so I can't use a delegate to return the reference to the Native Code.  How can I return a reference to the UITextView that is being rendered in a listview?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/custom-uitextview-cant-get-reference

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by mkonicek** [comment]
@facebook-github-bot stack-overflow
