### ISSUE TITLE
[AppState] App state never becomes "inactive"

### ISSUE THREAD

**Issue by ide** [facebook/react-native#524]
The issue is that UIApplication doesn't fire a notification when an app has become inactive, but it tells you when it will become inactive (did vs. will). As a result (it's clear once you read through the code), the native portion of the AppStateIOS module never tells JS when the app has become inactive.

This should be reasonably easy to build as long as the state tracking is kept simple. It's not super urgent but would be good to get in before a lot of people start assuming "active" and "background" are the only two app states.

**Comment by jhabdas** [comment]
I noticed when an device is locked while the app state is `active` the `background` event is not emitted. I'm guessing the behavior is somehow inherited from the [app life cycle](https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/TheAppLifeCycle/TheAppLifeCycle.html) execution states. But I believe it's the root cause of https://github.com/brentvatne/react-native-video/issues/44

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by bodhi** [comment]
Adding this to the app delegate:

```
#import "RCTEventDispatcher.h"

@implementation AppDelegate

...

- (void)applicationWillResignActive:(UIApplication *)application {
    RCTRootView *rootView = (RCTRootView *)self.window.rootViewController.view;
    [rootView.bridge.eventDispatcher sendDeviceEventWithName:@"appStateDidChange"
                                                        body:@{@"app_state": @"inactive"}];
}

- (void)applicationDidBecomeActive:(UIApplication *)application {
    RCTRootView *rootView = (RCTRootView *)self.window.rootViewController.view;
    [rootView.bridge.eventDispatcher sendDeviceEventWithName:@"appStateDidChange"
                                                        body:@{@"app_state": @"active"}];
}
```

seems to be ok as a workaround, but I don't know if this is a reasonable thing to do (maybe it runs on the wrong thread, or some other thing that I'm not aware of).

You need to add `applicationDidBecomeActive:` because `_lastKnownState` in `RTCAppState.m` will not be updated (it will remain `@"active"`) when the app becomes inactive. Then when `UIApplicationDidBecomeActiveNotification` is posted, `RTCAppState` will do nothing because of the `if` in `handleAppStateDidChange`: As far as `RTCAppState` is aware, the app is transitioning from `active` to `active`, so it doesn't bother to send an event.

**Comment by jhabdas** [comment]
Is this fixed?

**Comment by jhabdas** [comment]
nm

**Comment by christopherdro** [comment]
Fixed via https://github.com/facebook/react-native/commit/ec9efb8a01ce59c7a594df5ca4c314a208ba1902

**Comment by rclai** [comment]
Guys, is it normal for `AppState` to emit both `inactive` and `background` when you go directly to the home screen on iOS. I'm using an iPhone 5s.

**Comment by jhabdas** [comment]
@rclai I saw all sorts of interesting behavior here. My suggestion is not to make your UX hinge on this behavior in any big way. In Lumpen Radio (OSS) I use it to animate a background video but it's okay if it's not always animated.

**Comment by bodhi** [comment]
@rclai 

>  is it normal for AppState to emit both inactive and background in immediate sequence when you go directly to the home screen on iOS.

Yes, the flow is `active -> inactive -> background`. You can see this in Figure 2-3 in [the iOS documentation](https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/TheAppLifeCycle/TheAppLifeCycle.html#//apple_ref/doc/uid/TP40007072-CH2-SW3).

**Comment by rclai** [comment]
@bodhi Thanks.
