### ISSUE TITLE
[iOS] Image Views are not displaying resized image properly with specific resolution range on iPhone 5C

### ISSUE THREAD

**Issue by EmingK** [facebook/react-native#5250]
Images loaded from network URIs or using `RCTPhotoLibraryImageLoader` are not always fit the size of the image view, thus some of them are not displaying right on iPhone 5C.
![5c-display](https://cloud.githubusercontent.com/assets/3735897/12234353/630195be-b8a7-11e5-8312-8e52d06668f8.png)

I found that the reason is `RCTImageView`s are applying `kCAFilterTrilinear` filter for upscaling and downscaling the image to display, which produces weird effect when the source image is of the size 32x32.

here's a simple native code to reproduce it (need to run on iPhone 5C to see the effect):
https://gist.github.com/EmingK/967f8d3f241187a022ed

**Comment by muxianwu** [comment]
@EmingK  +1

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/ios-image-views-are-not-displaying-resized-image-properly-with-specific-resolution-range-on-iphone-5c

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
