### ISSUE TITLE
[Navigator] Settable to have 'No' transition?

### ISSUE THREAD

**Issue by bfarrgaynor** [facebook/react-native#5257]
Being able to use animated transitions is awesome. But I want to be able to flip between routes without animation and just have it quickly pop there like you would with a Tab Bar. Like 1 frame it's route A and in the next frame it's route B.

Navigator.SceneConfigs.FadeAndroid comes close, but if I just simply accelerate the animation it has this undesirable flicker effect.

Any ideas? Thanks!

**Comment by jaygarcia** [comment]
I question the use of `Navigator` at all then. Why not just create a simple Component that flips through "Cards" via state change? Should be really easy to implement.

**Comment by VansonLeung** [comment]
+1, suggest to implement / PR for Navigator to toggle animation while push / pop / replace,

something like in iOS:

```[[self navigationController] popViewControllerAnimated:NO];```

suggested solution:

e.g. ```this.refs.navigator.pop(true)```   , while 'true' is for disabling animations

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/navigator-settable-to-have-no-transition

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
