### ISSUE TITLE
Throw exception if key is not defined in styles

### ISSUE THREAD

**Issue by montogeek** [facebook/react-native#5258]
Hi!

At this moment when you use undefined styles from a `StyleSheet` not errors show up, neither exceptions.

Example:
```
<View style={styles.container}>
....
const styles = StyleSheet.create({
  photo: {
    width: 55,
    height: 55
  }
})
```

It renders the component without styles.

It would be great to throw an exception.

**Comment by tomauty** [comment]
This might be better handled by `eslint-plugin-react-native`. Not sure if it handles your specific case, but a PR there might be easier to merge.

https://github.com/intellicode/eslint-plugin-react-native

**Comment by ide** [comment]
I don't know how we'd implement this tastefully without proxies, which we don't have.

**Comment by montogeek** [comment]
Hi!

Why is not as simple as check if the key exists?

**Comment by ide** [comment]
It's part of the API to allow null/false/undefined styles so we can't throw an error if we get any of those values. So we need to test if the key exists on the StyleSheet object as you say, and I don't know how to do that without proxies.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/throw-exception-if-key-is-not-defined-in-styles

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
