### ISSUE TITLE
Android TextInput: undefined is not an object (evaluating 'UIManager.AndroidTextInput.Constants.AutoCapitalizationType[this.props.autoCapitalize]')

### ISSUE THREAD

**Issue by jabm111** [facebook/react-native#5262]
I get this error anytime I try to render a text input on Android. I'm depending on "facebook/react-native".

Seems to be related to these changes: https://github.com/facebook/react-native/commit/cc449b394e9cd3300343016a5d6a3c924823cd2b

![screenshot_20160111-182857](https://cloud.githubusercontent.com/assets/10445424/12250961/f5e2f120-b898-11e5-9023-09bc80d880bc.png)

**Comment by chirag04** [comment]
@jabm111 Are you sure you are depending on "facebook/react-native" on java side also? npm install from 'facebook/react-native' will only give you js related changes from master.

**Comment by jabm111** [comment]
@chirag04 Good point, I'm not sure. I'm able to reproduce with:

* react-native init testproject
* replace "react-native": "0.17.0" with "react-native": "facebook/react-native" in package.json
* rm -rf node_modules
* npm install
* react-native upgrade, Y to all replacements
* change the last line of the dependencies in android/app/build.gradle to `compile "com.facebook.react:react-native:0.18.+"`
* add a TextInput to index.android.js 
* react-native run-android

Is there anything else I would need to do and is the line I changed in build.gradle correct?

**Comment by dmitryame** [comment]
I've tried it from from 'facebook/react-native'  and it's still happening

**Comment by andreicoman11** [comment]
This should be working off of master, but it needs to depend on the latest binary
cc @foghina

**Comment by foghina** [comment]
@jabm11 @dmitryame depending on `0.18.+` in `build.gradle` does not equate to master. To truly depend on master you need to build from source. See [Installing the React Native .aar in your local Maven repo](https://github.com/facebook/react-native/tree/master/ReactAndroid#installing-the-react-native-aar-in-your-local-maven-repo) and depend on whatever version was just built and installed in your `build.gradle`.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-textinput-undefined-is-not-an-object-evaluating-uimanagerandroidtextinputconstantsautocapitalizationtypethispropsautocapitalize

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by yash2code** [comment]
same issue
