### ISSUE TITLE
Error:Requiring unknown module.react-pure-render/mixin . If you are sure module is there ,try restarting the module 

### ISSUE THREAD

**Issue by Hari70a** [facebook/react-native#5279]
I have tried developing the code for weather Api . I shows the following error while reloading the JS in entering the command

$ react-native start

Please check the screenshot below:
![image](https://cloud.githubusercontent.com/assets/14177973/12287811/707953ea-b9f5-11e5-8f79-863ed4eebe1c.png)

Thanks in advance

**Comment by satya164** [comment]
Seems like you don't have `react-pure-render` package installed? Try running `npm install -S react-pure-render` in your project.

BTW, there's an awesome place to ask question like this one: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see your question, you can vote on answers and mark question as answered etc. This lets us keep a list of bug reports and feature requests on github and especially [Product Pains](https://productpains.com/product/react-native/?tab=top) (again, with voting which is really nice).

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)
