### ISSUE TITLE
Can I change color of action icon on the DrawerLayoutAndroid?

### ISSUE THREAD

**Issue by aleki** [facebook/react-native#5280]
I want to change color of action icon to white. 
![screenshot from 2016-01-12 19-03-37](https://cloud.githubusercontent.com/assets/4836709/12288521/14942546-b9e6-11e5-915c-b45b73592135.png)
Is it possible?

**Comment by mkonicek** [comment]
Hey and thanks for posting this!

There's an awesome place to post code / ask question first before filing an issue: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see and answer your question. This lets us use the github bug tracker for bugs.

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)
