### ISSUE TITLE
integration react-native layout abnormal

### ISSUE THREAD

**Issue by L-Jovi** [facebook/react-native#5295]
sorry to trouble, may be here someone will save me, if you don't mind, please notice [this issue on stackoverflow](http://stackoverflow.com/questions/34761948/integration-react-native-layout-abnormal).

**Comment by skevy** [comment]
Hey and thanks for reporting this!

There's an awesome place to ask question like this one: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see your question, you can vote on answers and mark question as answered etc. This lets us keep a list of bug reports and feature requests on github and especially [Product Pains](https://productpains.com/product/react-native/?tab=top) (again, with voting which is really nice).

If you think StackOverflow works for you please consider posting there instead and closing this issue.

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)
