### ISSUE TITLE
[Android] fetch with Accept-encoding Gzip leads to app crash

### ISSUE THREAD

**Issue by iinterest** [facebook/react-native#5297]
my code like this :
```javascript
let headers = new Headers({
    'Accept-Encoding': 'gzip, deflate',
    'Content-Type': 'application/json',
});
fetch(url, {
    method: 'GET',
    compress: true,
    headers: headers,
}).then(data => {
    ......
})
```

and app crash error log:
```
Assert (/Users/mkonicek/code/react-native/ReactAndroid/src/main/jni/first-party/jni/LocalString.cpp:36): 4 byte utf-8 encodings only valid for up to 21 bits
```

**Comment by mkonicek** [comment]
Hey @iinterest, can you try with 0.18 which comes out tomorrow? A pull request to fix this is welcome (please see the message from the bot above).

**Comment by mkonicek** [comment]
I'll close this because it's a bug report for an older version, need to confirm first it still happens in 0.18. We don't have bandwidth to maintain older versions unfortunately :(

**Comment by ide** [comment]
@mkonicek we saw this error in 0.18 so I'm going to reopen it. Something in the JNI layer doesn't handle arbitrary byte strings correctly.

**Comment by trabianmatt** [comment]
For what it's worth, I saw the same thing when trying to fetch an octet-stream where I expected base64 but received binary. I wasn't able to find a solid workaround other than correcting the backend, but C++ is a bit out of my depth. #3439 seems related.

**Comment by mkonicek** [comment]
OK thank you @ide! Anyone up for sending a PR to fix this?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-fetch-with-accept-encoding-gzip-leads-to-app-crash

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by dantebarba** [comment]
Is it fixed yet?.
