### ISSUE TITLE
Android resizeMode

### ISSUE THREAD

**Issue by InnerPeace080** [facebook/react-native#5298]
when i use resizeMode is 'contain' or 'stretch' , image not work as it must be. , image is smaller size that i set.

here is original image

![menu_bt1](https://cloud.githubusercontent.com/assets/3762408/12315852/546f7518-bab2-11e5-90db-45beadeb357a.png)

here is code:

```
<View style={[{width:widthScreen*2.2/4,height:40,justifyContent:'center',backgroundColor:'transparent'},self.props.style]}>
  <View style={[{position:'absolute',top:0,bottom:0,left:0,right:0},Debug.styles.border]}>
    <Image
      resizeMode='contain'
      width={widthScreen*2.2/4}
      height={40}
      style={
        [{
          flex:1,
          top:0,right:0,
          },
          Debug.styles.border
        ]
      }
      source={self.props.backgroundImage}/>
  </View>
 </View>
  
```

and it display 

![captureissue image](https://cloud.githubusercontent.com/assets/3762408/12315951/8d143218-bab3-11e5-8a03-0c16f5ea8edd.PNG)

image display not fit to white border (i use white border for debug , the tail will disappear when i not use border, ).

'stretch' work well when i not use border for style of Image. But i wish 'contain' will fit at least one dimension to size i set for it.

do anyone know how to slove this, i think this may be a issue

**Comment by thstarshine** [comment]
maybe related #4031

**Comment by GaverChou** [comment]
Have You solved this problem? I encountered the same problem.

**Comment by GaverChou** [comment]
This is a Fresco's problem. When use setBorder, Fresco world be use RoundingParams, and default use Bitmap_only to create RoundBitmap which use BitmapShader. Due to a limitation of Android's BitmapShader, if the image doesn't fully cover the view, instead of drawing nothing, edges are repeated. details on http://frescolib.org/docs/rounded-corners-and-circles.html#_

**Comment by InnerPeace080** [comment]
i don't know how to solve this, i don't use border and 'contain' anymore

**Comment by marcshilling** [comment]
Not specifying `resizeMode` seems to produce the correct sized image on both platforms. This confused me though because I thought `contain` was the default.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-resizemode

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by nicotroia** [comment]
resizeMode 'contain' still isn't possible on react-native `0.46.4` for android
