### ISSUE TITLE
AndroidToolbar

### ISSUE THREAD

**Issue by paulbrie** [facebook/react-native#5306]
Hi, it would be great to be able to center the title and the subtitle of the Component. According to the documentation this option is not available. Did I miss something?
Thanks for your help.
Paul

**Comment by corbt** [comment]
Hey and thanks for reporting this!

There's an awesome place to ask question like this one: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see your question, you can vote on answers and mark question as answered etc. This lets us keep a list of bug reports and feature requests on github and especially [Product Pains](https://productpains.com/product/react-native/?tab=top) (again, with voting which is really nice).

If you think StackOverflow works for you please consider posting there instead and closing this issue.

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)

**Comment by christopherdro** [comment]
@facebook-github-bot feature

**Comment by facebook-github-bot-9** [comment]
Hey @paulbrie! Thanks for opening the issue, however it looks like a feature request. As noted in the [Issue template](https://github.com/facebook/react-native/blob/master/ISSUE_TEMPLATE.md) we'd like to use the GitHub issues to track bugs only. Can you implement the feature as a standalone npm module? If not consider sending a pull request or a create an entry on [Product Pains](https://productpains.com/product/react-native). It has a voting system and if the feature gets upvoted enough it might get implemented. Closing this now, thanks for understanding!
