### ISSUE TITLE
MapView onAnnotationPress only triggers if there is a title attached to an annotation

### ISSUE THREAD

**Issue by bpeters** [facebook/react-native#5319]
I have UI concerns that I don't want to show the native iOS popup, so I don't include a `title` and `subtitle` to my annotations. However, that causes the `onAnnotationPress` to never trigger. I think the behavior should allow a callback without having to use the default popup.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/mapview-onannotationpress-only-triggers-if-there-is-a-title-attached-to-an-annotation

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
