### ISSUE TITLE
SyntaxError:Attempted to redefine property 'borderRadius'.

### ISSUE THREAD

**Issue by ReasonYuan** [facebook/react-native#5327]
It does't display when launch in Debug mode.

**Comment by satya164** [comment]
You've duplicate properties somewhere in the object. Please use a linter such as [ESLint](http://eslint.org) to catch these kind of errors.

BTW, there's an awesome place to ask question like this one: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see your question, you can vote on answers and mark question as answered etc. This lets us keep a list of bug reports and feature requests on github and especially [Product Pains](https://productpains.com/product/react-native/?tab=top) (again, with voting which is really nice).

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)
