### ISSUE TITLE
[HMR] Add support for sourcemaps

### ISSUE THREAD

**Issue by martinbigio** [facebook/react-native#5340]
When a runtime error occurs the stacktrace we show on the simulator doesn't get symbolicated correctly.This is roughly what we need to do to get beauty stacktraces:
  - The packager needs to be able to serve individual transformed files with the `//@sourceMappingURL` pragma at the end. This pragma needs to point to another URL on the packager which we'll serve the sourcemaps for the the transformed file. 
  - We need to modify the HMR runtime so that it send an array of objects `{filaname: 'foo.js', transformedCode:'__accept('foo', ...);'}` instead of the code altogether.
  - For each file that was updated we need to invoke a native module that injects the code into JSC. Need to go to native to inject the code because that's the only way stacktraces will include the original filename. I'm not sure how this works on Android. @satya164 any clue?
  - As a nice to have, would be great closing the red box if any before injecting the code.

**Comment by martinbigio** [comment]
@davidaurelio, @vjeux, @satya164 what do you guys thing about the approach? Any suggestion to avoid the through the bridge call?

**Comment by satya164** [comment]
I've no idea about how JSC works on Android :(

**Comment by martinbigio** [comment]
I have this working but I had to add a call through the bridge to inject the HMR update because doing different variations of eval didn't work. This is unfortunate as as a consequence we'll have to implement this same behavior on Android. I'll ask around internally to see if someone figures a better solution but it looks like this is a bug/missing feature on the old version of JSC we're using

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/hmr-add-support-for-sourcemaps

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
