### ISSUE TITLE
[HMR] Further improve transform to support not only HMR updates on React components

### ISSUE THREAD

**Issue by martinbigio** [facebook/react-native#5342]
At the moment Hot Loading is enabled though Dan Abramov's (who I can't mention, not sure why) proxies. One problem the transform has is that it only supports React components. So for instance all the following use cases can't be hot loaded:

1. `module.exports = function() { ... }`
2. `var foo = 'bar'; module.exports = React.createClass({ ...});`: changes to `foo` don't propagate
3. Changes on lifecycle methods that have already been executed (i.e.: `getInitialState`, `componentWillMount`, etc
4. // constants.js: `module.exports = {foo: 'bar'};` // component1.js: `require('constants'); module.exports = React.createComponent({ render() { return <Text>constants.js</Text>; });`

Also, would be great to detect whether the change can be hot loaded or not. By doing so we could provide feedback to the user by showing a yellow box so that the user will know he'll have to reload.

Note some of the problems could be solved if we inlined all the requires but for that to work all the modules would have to be side-effects free, which is something I don't think we want to ensure.

**Comment by satya164** [comment]
cc @gaearon

**Comment by ide** [comment]
One thing that might be helpful is the JS `import` keyword, which makes all symbol access lazy. For example, here `x` is not accessed until `printXName` is called:

```js
import x from 'x';

function printXName() {
  console.log(x.getName());
}
```

The above code is actually semantically like this:

```js
const $x = require('x'); // $x is inaccessible from user space

function printXName() {
  // exports (in this case the default export) are always lazily accessed
  console.log($x.default.getName());
}
```

The lazy access should make HMR easier since there's always a level of indirection (via `$x` in the example above).

cc @nikki93 who's been thinking about HMR and live coding a lot too

**Comment by skevy** [comment]
James Long played around with hot loading non-React components in his prototype "Monkey Hot Loader" -- https://github.com/jlongster/monkey-hot-loader

This code doesn't handle things like updating "var foo" in the module scope...but it does handle updating all top-level functions.

Anyway...not sure if it's fully useful...but something to at least look at for some ideas maybe.

cc @jlongster

**Comment by martinbigio** [comment]
Thanks for sharing!. @gaearon and I already looked into it, it's a super interesting approach. We're still not sure if we'll got the transform way as on that post or if we'll enhance the HMR runtime to support accepting hierarchies of modules as webpack does. Probably the first one on the short term.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/hmr-further-improve-transform-to-support-not-only-hmr-updates-on-react-components

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
