### ISSUE TITLE
[HMR] Hot Loading KPs

### ISSUE THREAD

**Issue by martinbigio** [facebook/react-native#5343]
- `borderRadius` doesn't get updated.
 - `<Image source="image!foo.png" />` => `<Image source={require('bar.png')} />` doesn't work (changing images that use the new asset system do work).

**Comment by satya164** [comment]
Changing `borderRadius` works for me.

**Comment by martinbigio** [comment]
Yeah, I bet it's a problem on native

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/hmr-hot-loading-kps

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
