### ISSUE TITLE
[HMR] Move listener out of file change debounced function

### ISSUE THREAD

**Issue by martinbigio** [facebook/react-native#5344]
The HMR listener is currently on a file change listener that is debounced. We need to trigger it upon any file change as otherwise it could happen that the user changes 2 different files super quickly and we get only the updates of the last one. This is a low priority bug fix as it's quite hard to run into this issue by changing files manually.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/hmr-move-listener-out-of-file-change-debounced-function

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
