### ISSUE TITLE
XMLHttpRequest polyfill doesn't provide the withCredentials property

### ISSUE THREAD

**Issue by navels** [facebook/react-native#5347]
The real problem I'm having is that socket.io-client is unable to connect via the polling transport when running the chrome debugger.  This is because it's a cross-domain request (debugger port is 8081 whereas my local server is running on port 3000) and socket.io in that case will only use XMLHttpRequest if it supports CORS.

socket.io-client checks for CORS like this:

    module.exports = typeof XMLHttpRequest !== 'undefined' &&
      'withCredentials' in new XMLHttpRequest();

which fails and ultimately it has to fall back on WS.  That isn't so terrible but made for some very confusing debugging.  I'd prefer for the behavior while debugging to be as close as possible to running the real app.

Am happy to submit a PR if this makes sense.  (FYI this is on react-native 0.18.0-rc)

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/xmlhttprequest-polyfill-doesnt-provide-the-withcredentials-property

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
