### ISSUE TITLE
LayoutAnimation scoped to the component that calls it

### ISSUE THREAD

**Issue by imton** [facebook/react-native#5359]
I might be wrong, but it seems that if a child component calls
```js
LayoutAnimation.configureNext(LayoutAnimation.Presets.spring)
````
the whole app (parents) is layout animated as well. Shouldn't/ couldn't it be scoped only to that (and children) component layout changes?

Thanks

**Comment by brentvatne** [comment]
Hi @imton!

This is just how LayoutAnimation works, if you need to animate a specific subtree then only update that during the frame or use `Animated` :)

**Comment by imton** [comment]
@brentvatne I see. What do you mean by "during the frame"? is there any other way (or lib you know) to whitelist or specify which components (children) ? I accept ugly-hacks suggestions :)

**Comment by imton** [comment]
my biggest problem right now is the navbar (Navigator) is flashing (opacity) when using this

**Comment by rigdern** [comment]
I added this as a feature request on ProductPains: https://productpains.com/post/react-native/scoped-layoutanimations/

@brentvatne suggested a couple of workarounds:
  - "only update that during the frame": What techniques do you use for this? When a particular view is rerendering and wants to use a LayoutAnimation, I don't see how it can guarantee that no other view updates during that frame. It doesn't seem like an individual view has that much knowledge or control.
  - "use `Animated`": `Animated` doesn't seem like a suitable solution for layout animations. I want to animate a view from its old position to its new position. There's not a straightforward way to know in JavaScript where the layout engine is going to position a particular View so I can't give this information to `Animated`. To have this information at the required time, I'd have to have to jump through some hoops due to the asynchronous nature of the bridge.

Scoped `LayoutAnimations` seem like a more elegant solution to this problem.

**Comment by imton** [comment]
@rigdern thank you!
