### ISSUE TITLE
Crash at RCTNavigator.m in NavigatorIOS

### ISSUE THREAD

**Issue by xhacker5000** [facebook/react-native#5367]
When you use NavigatorIOS and create yourself UINavigationController ...

there is a big bug in RCTNavigator.m line 

NSUInteger indexOfFrom = [_currentViews indexOfObject:fromController.navItem];

If I created  an UINavigationController at the AppDelegate.m

and put the RCTRootView as a subview like this:

 RCTRootView *rctView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                     moduleName:@"fastui"
                                              initialProperties:nil
                                                  launchOptions:nil];
  [self.view addSubview:rctView];

then if I wanna push some Object-c viewcontroller with these code:

````
RCT_EXPORT_METHOD(gotoPrinterSetting:(RCTResponseSenderBlock)callback)
{
 RCTLogInfo(@"go some ViewController");

UINavigationController *controller = (UINavigationController*)[[[UIApplication sharedApplication] keyWindow] rootViewController];
 
    SomeViewController *loginVC = [[SomeViewController alloc] init];

    [controller pushViewController:loginVC animated:TRUE];
}
````

The 'SomeViewController' will show up and Objective-c UINavigationController bar will show too,
And if you press '< BACK' on the left top button .

App crash at RCTNavigator.m 
NSUInteger indexOfFrom = [_currentViews indexOfObject:fromController.navItem];

any ideas? Thanks

ps: So , I have to use Navigator replace the NavigatorIOS, that will work fine :(

But really like NavigatorIOS

**Comment by satya164** [comment]
`NavigatorIOS` is not maintained by Facebook. PRs are welcome.

**Comment by xhacker5000** [comment]
@satya164 so I should report this issue to ?

**Comment by satya164** [comment]
@xhacker5000 I'm leaving this open and I've tagged it as `Community resposnibility`. So someone from the community will need to step forward to fix the issue. PRs are welcome.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/crash-at-rctnavigatorm-in-navigatorios

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
