### ISSUE TITLE
0.18 packager error

### ISSUE THREAD

**Issue by py110** [facebook/react-native#5393]
today when i upgrade from 0.17 to 0.18 
run ios get following errors
![image](https://cloud.githubusercontent.com/assets/13548241/12407276/b9a71152-be90-11e5-8b34-bb5a90946e95.png)

**Comment by mylonelyplanet** [comment]
i have same issue too, even in a new project created by react-native init

**Comment by mylonelyplanet** [comment]
i have same issue too, even in a new project created by react-native init

**Comment by mylonelyplanet** [comment]
i have same issue too, even in a new project created by react-native init

**Comment by mylonelyplanet** [comment]
i have same issue too, even in a new project created by react-native init

**Comment by regeda** [comment]
I've got another problem!
```
[9:28:23 AM] <END>   Crawling File System (1940ms)
[9:28:23 AM] <START> Building in-memory fs for JavaScript
[9:28:26 AM] <END>   Building in-memory fs for JavaScript (3140ms)
[9:28:26 AM] <START> Building in-memory fs for Assets
[9:28:29 AM] <END>   Building in-memory fs for Assets (3314ms)
[9:28:29 AM] <START> Building Haste Map
[9:28:32 AM] <START> Building (deprecated) Asset Map
[9:28:33 AM] <END>   Building (deprecated) Asset Map (1192ms)
Error building DependencyGraph:
 Error: Naming collision detected: <RN_PROJECT_PATH>/node_modules/react-native/node_modules/fbjs/lib/warning.js collides with <RN_PROJECT_PATH>/node_modules/react/node_modules/fbjs/lib/warning.js
    at HasteMap._updateHasteMap (HasteMap.js:132:13)
    at HasteMap.js:103:28
    at tryCallOne (<RN_PROJECT_PATH>/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at <RN_PROJECT_PATH>/node_modules/react-native/node_modules/promise/lib/core.js:123:15
    at flush (<RN_PROJECT_PATH>/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:430:9)
    at process._tickCallback (node.js:359:13)
```

**Comment by carlos-wong** [comment]
+1

**Comment by carlos-wong** [comment]
rm ./node_modules/react-native/node_modules/react-transform-hmr/node_modules/react-proxy/node_modules/react-deep-force-update/.babelrc  I remove this file, then work

**Comment by carlos-wong** [comment]
@py110 maybe you can have a try

**Comment by masom** [comment]
@carlos-wong which NPM version are you using? I just had a bunch of similar issues after upgrading NodeJS. `npm install -g npm@2` installed NPM 2  ( node ships with npm 3)

**Comment by py110** [comment]
@carlos-wong  +1

**Comment by jiangqqlmj** [comment]
+1

**Comment by sheldonhan** [comment]
+1

**Comment by jevakallio** [comment]
This root cause of the issue is that React Native uses Babel 6, which deprecated the use of the `stage` option on `.babelrc` files, and `react-deep-force-update`, a sub-dependency of React Native, still declares a `.babelrc` file with that option.

This is an issue with any third party modules that still use an older Babel in their own build process and do not clear the configuration files for the npm publish.

I have worked around the issue by adding the following npm run scripts to my `package` json:

```
  "scripts": {
    "clean:babelrc": "find ./node_modules -name react-packager -prune -o -name '.babelrc' -print | xargs rm -f",
    "postinstall": "npm run clean:babelrc"
  }
```
The script nukes all `.babelrc` files under the `node_modules` directory after every `npm install`, except the one under the `react-packager` directory, which is React Native packager uses to configure its own babel rules.

Note that this issue has been raised on Stack Overflow by a couple of users, in addition to the reports here:
* http://stackoverflow.com/questions/34975286/reactnativecli-init-helloworld-project-build-error-with-babel-transformerror
* http://stackoverflow.com/questions/34967261/when-i-learn-the-first-react-native-demo-react-native-error

In

**Comment by jevakallio** [comment]
I have not experienced this error myself (not on `0.18` in any of my apps yet), but it appears the depency tree that causes this error is the following:

* `react-native` depends on [react-transform-hmr](https://github.com/gaearon/react-transform-hmr)
* `react-transform-hmr` depends on [react-proxy](https://github.com/gaearon/react-proxy)
* `react-proxy` depends on [react-deep-force-update](https://github.com/gaearon/react-deep-force-update)
* `react-deep-force-update` contains the offending `.babelrc` file

The downstream dependencies below `react-transform-hmr` have since been updated to use Babel 6, but the latest `react-transform-hmr` still depends on  `react-proxy@1.1.1`. We would need to upgrade the html library to the latest `react-proxy@2.0.1` to resolve this issue. 

I will open an issue at `react-transform-hmr` to see if we can get this upgraded.

**Comment by hi54yt** [comment]
+1

**Comment by citysheep** [comment]
+1

**Comment by Sanster** [comment]
+1

**Comment by LichFaker** [comment]
I got same problem in 0.19, and `clean:babelrc` solved my problem. Thank you~

**Comment by minggo** [comment]
@jevakallio +1

**Comment by flute** [comment]
@jevakallio It works,thanks a lot!

**Comment by Reddick-wang** [comment]
+1

**Comment by deju** [comment]
(This)[http://stackoverflow.com/a/35644019/863276] works for me.

**Comment by pucca601** [comment]
does it need restart server

**Comment by vladp** [comment]
Same problem is happing with 0.21 upgrade. 
But there are no .babelrc  in the ./node_modules.  So the suggestion to clean them out does not work.

My package.json fragment

> 
>     "engines": {
>     "node": ">=4",
>     "npm": ">=2 <4"
>   },
> 
>     "devDependencies": {
> 	"babel-core": "^6.6.5",
>         "babel-register":"^6.6.0",
> 	"babel-eslint": "^5.0.0",
> 	"babel-loader": "^6.2.0",
>         "babel-preset-react-native": "^1.5.1",
> 	"babel-preset-es2015": "^6.6.0",
> 	"babel-preset-react": "^6.5.0",
> 	"babel-preset-stage-1": "^6.5.0",
> 	"eslint": "^2.2.0",
> 	"eslint-loader": "^1.1.1",
> 	"eslint-plugin-react": "^4.0.0",
> 	"react-native-webpack-server": "^0.8.4",
> 	"webpack": "^1.12.14",
> 	"webpack-dev-server": "^1.14.1"
>     },
> 
> 
>     "dependencies": {
> 
> 	"react-native": "^0.21.0",
> 	
> 	"@remobile/react-native-splashscreen": "^1.0.3",
> 
> 	"react-native-blur": "^0.7.10",
> 	"react-native-htmlview": "^0.2.0",
> 
> 
> 	"react-native-material-kit": "^0.3.0", 
> 	"react-native-material-design": "^0.3.3"
>     }
> 

Including the react-proxy or react-deep-force-update directly into package.json did not help either.

At this point I am stuck and would appreciate any pointers
Linux mint 17.3
nodejs 5.7.1
![react-proxy-erorr](https://cloud.githubusercontent.com/assets/94890/13552902/93697f3a-e342-11e5-9b42-d7ee1c1af546.png)

**Comment by jsierles** [comment]
I haven't been able to reproduce this issue on React Native 0.21. Since it looks like most people solved this issue, I'm closing it for now. @vladp, please reopen or continue discussion here if you're still seeing this issue. Thanks!
