### ISSUE TITLE
Navigator.jumpTo without using a Route Stack

### ISSUE THREAD

**Issue by dmwallace** [facebook/react-native#5425]
Why does Navigator.jumpTo require require the use of a route stack when Navigator.push does not?

I want to be able to jumpTo and back from any route/scene in my application.

Navigator.push and Navigator.pop work fine EXCEPT that I need to have my main scene remain mounted.

If I use Navigator.jumpTo and Navigator.jumpBack, the main scene remains mounted, but I have to use a route stack, which sometimes forces me to go back through multiple scenes to get back to my main scene.

The only solution I can think of is to dynamically manipulate the route stack before I jumpTo a new route, but this seems inelegant and unnecessary.

Or perhaps I'm missing something?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/navigatorjumpto-without-using-a-route-stack

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
