### ISSUE TITLE
[MapView] new way of using UIButtonTypeDetailDisclosure in annotations? 

### ISSUE THREAD

**Issue by dvcrn** [facebook/react-native#5427]
Hi!

Since hasRightCallout / hasLeftCallout is now deprecated, is there a new way to simply embed the "I" icon button (UIButtonTypeDetailDisclosure) inside a annotation?

**Comment by sgonyea** [comment]
I'm in favor of this as well.  Mostly, I want this because it makes the entire annotation tap-able.  Whereas with custom views + touchable-highlight, only small areas can be triggered and makes for a weird experience.  So far!  Maybe I just need to spend more time staring at this, but the old behavior was (mostly) ideal.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/mapview-new-way-of-using-uibuttontypedetaildisclosure-in-annotations-

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
