### ISSUE TITLE
Confusing error message when requiring and importing react-native

### ISSUE THREAD

**Issue by vjeux** [facebook/react-native#5434]
http://stackoverflow.com/questions/34900399/i-just-added-var-react-requirereact-native-and-my-whole-build-failed?stw=2

**Comment by satya164** [comment]
Our templates seem to be fine, as well as the docs. No idea where he found that :(

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/confusing-error-message-when-requiring-and-importing-react-native

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
