### ISSUE TITLE
Detail Callout Clipped

### ISSUE THREAD

**Issue by GantMan** [facebook/react-native#5435]
Sometimes it works sometimes it doesn't.  I'm not really sure why/when/how.

Here's my callout code
```javascript
// annotation.detailCalloutView = object_context.detailCallout(annotation)
  detailCallout (rowData) {
    return (
      <TouchableOpacity style={{flex: 1}}>
        <Text>{`Case Number: ${rowData.caseNumber}`}</Text>
        <Text>{`Subject Name: ${rowData.subjectName}`}</Text>
        <Text>{`Date: ${rowData.dateTime}`}</Text>
        <Text>{`Address: ${rowData.address}`}</Text>
      </TouchableOpacity>
    )
  }
```

Here's my result in 0.18 - Sometimes this works, and sometimes it doesn't.  You can never tell which pin will work, which time.
![simulator screen shot jan 20 2016 10 18 32 am](https://cloud.githubusercontent.com/assets/997157/12455021/827dd312-bf5f-11e5-96db-7bf20434fee9.png)

**Comment by GantMan** [comment]
Here's a gif of the issue being random.
![detail_callouts](https://cloud.githubusercontent.com/assets/997157/12455576/d6a61e70-bf61-11e5-9df6-c68023b9ebcb.gif)

**Comment by GantMan** [comment]
For those having this issue/watching this ticket, I just verified it still exists in 0.19

**Comment by iricketson** [comment]
+1

**Comment by af7** [comment]
I had this problem too.

I ended up using `react-native-maps` which doesn't have this problem:
https://github.com/lelandrichardson/react-native-maps

Maybe you would like to see what they are doing there OR (even better) work together and merge it into `react-native`?

**Comment by GantMan** [comment]
@af7 -  It seems react-native-maps works with Android in ways MapView can't!  @nicklockwood and @lelandrichardson - thoughts on possible merge conversation?

**Comment by lelandrichardson** [comment]
@GantMan I originally created that library in an effort to get it merged into RN. I would certainly love to see that happen, and we have talked about it. There are a couple of things to consider though:

1. react-native-maps requires google play services and an API key. This can make it extra difficult to package it with react native core, where we don't want to add that extra bulk to every RN app.
2. The react-native-maps library has significant API Surface Area. If it is merged into RN core, this can end up creating even more Issues/PRs for RN as a whole, where we are already struggling to keep up.
3. FB doesn't use react-native-maps internally

One alternative path is to remove the MapView component that's currently in core into a 3rd-party repo. This would then signal to everyone that a 3rd party solution is needed (just as it is for many things). We could add links to the main maps libraries in the docs if needed.

I'd be interested to see some more discussion around either path.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/detail-callout-clipped

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
