### ISSUE TITLE
[NavigatorIOS] - Not resizing properly on an iPad when orientation changes from landscape to portrait

### ISSUE THREAD

**Issue by aflanagan** [facebook/react-native#5437]
When I change the orientation on an iPad from landscape to portrait the NavigatorIOS component is not resizing. 

This doesn't happen for an iPhone, or when testing an iPad on the simulator. I've tested across multiple devices and versions of iOS (8.4 and 9.1).

I can reproduce it with the following components using RN 0.17.0:

```js
import React, {
  View,
  Text,
  StyleSheet,
  NavigatorIOS
} from 'react-native'

var styles = React.StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
  },
  messageStyle: {
    width: 300,
    textAlign: 'center',
    fontSize: 16,
    color: '#666666',
  },
  appContainer: {
    flex: 1,
    backgroundColor: 'white',
  },

});


class EmptyFeed extends React.Component {

  render() {
    return(
      <View style={styles.container}>
            <Text style={styles.messageStyle}>
              LOADING
            </Text>
      </View>
    )
  }
}

class App extends React.Component {

  render() {
    return (
      <NavigatorIOS
        style={styles.appContainer}
        titleTextColor={'red'}
        tintColor={'#65bc97'}
        translucent={true}
        initialRoute={{
          title: 'Explore',
          component: EmptyFeed
        }}
      />
    )
  }
}

React.AppRegistry.registerComponent('App', () => App);
```

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/navigatorios-not-resizing-properly-on-an-ipad-when-orientation-changes-from-landscape-to-portrait

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
