### ISSUE TITLE
[ListView] Possibility of allowing overscroll?

### ISSUE THREAD

**Issue by tomauty** [facebook/react-native#5441]
Hello,

Was wondering if this was possible with the current ListView API. I'm using sticky section headers, and would like to be able to scroll until the last header is clamped to the top of the view (so there would be empty space below the final list items). Currently only let's me scroll until the last row is at the bottom of the viewport. Any suggestions?

Thanks.

**Comment by ide** [comment]
You're probably best off implementing this yourself in JS. Render a dummy spacer view that is sufficiently tall so that it fills in the bottom of the list view content container.

**Comment by tomauty** [comment]
That's what I figured, just wasn't sure if there was an undocumented prop somewhere that would let me do this :)

**Comment by ide** [comment]
A lot of times the answer is no, even when looking at Apple's UIKit APIs. Probably over half of the amazing designs you see implemented in native apps are the result of dozens of hours and hard work. People writing native apps work harder because everything else is hard to do and your sense of productivity and efficiency gets numbed.

**Comment by MattFoley** [comment]
@ide Am I understanding this correctly? Android has a setOverScrollMode on ScrollView, did you guys decide against implementing that on Android? I'm checking because I've got some functionality that explicitly uses overscroll by scrolling passed the normal bounds of a ScrollView, and I'd rather not rework the logic on iOS as well. 

From what I can tell, ReactScrollView.java just disallows that with it's onOverScrolled callback. Am I missing some way to make that possible?

**Comment by ide** [comment]
I'm not sure, I didn't write ReactScrollView. Samsung also has a customized ScrollView so you'd have to test on their phones too, it might be hard to get consistent behavior.
