### ISSUE TITLE
About Fetch API

### ISSUE THREAD

**Issue by Llong1** [facebook/react-native#5449]
Assert (/Users/mkonicek/code/react-native/ReactAndroid/src/main/jni/first-party/jni/LocalString.cpp:36): 4 byte utf-8 encodings only valid for up to 21 bits

**Comment by brentvatne** [comment]
@mkonicek - weird that your name is coming up here :ocean:

**Comment by satya164** [comment]
Yeah, I have faced this one when trying to download an image file with fetch.

**Comment by mkonicek** [comment]
Wow this is strange. What's the repro? Is that a JS error, a compiler error, a log message? :)

**Comment by mkonicek** [comment]
What version of React Native are you using?

**Comment by satya164** [comment]
@mkonicek If I try to fetch image file with `GET`, it crashes the app with the above message in the adb logs.

**Comment by mangogogos** [comment]
+1 fetching an image with GET is giving me this crash in RN 0.18-rc

**Comment by Llong1** [comment]
I got this crash in RN 0.17.0

**Comment by Llong1** [comment]
I think it was caused by the character-set.

**Comment by mkonicek** [comment]
Curious what the use case is. Once you `fetch('https://example.com/someImage.png')` what do you do with it? How do you display it?

It might be that `fetch` doesn't support binary data on Android. We should at least have a better error :) And the fact a path from my machine appears in logcat is super weird, I'll try to find out why it happens.

**Comment by foghina** [comment]
Turns out all React Native code actually runs proxied on @mkonicek's laptop. It's the only explanation.

**Comment by mkonicek** [comment]
:)

**Comment by mkonicek** [comment]
:smile:

**Comment by mangogogos** [comment]
For me the use case is that there's not really any way to handle image errors on Android and I want to verify that a source is a valid image before trying to display it and otherwise display some default image. Im getting raw html from textile (http://txstyle.org/) and want to be able to render an image from source but I could potentially get an image src attribute like '/asdsadas' or 'notarealsite.com' since the html is generated from end-user input, so I need to do some kind of validation of the image before passing it off to the Image component because unfortunately on Android there's no onError and the onLoadEnd callback never fires due to a crash if a garbage uri is passed in (since image components support rendering images from a uri that refers to somewhere on the device but do no validation before attempting to render it)

**Comment by satya164** [comment]
@mangogogos For that use case, you can just send a `HEAD` request to check if the image exists. Been working quite well for me.

**Comment by mangogogos** [comment]
I always forget that HEAD requests are a thing... thanks, that's working like a charm! @satya164

**Comment by mkonicek** [comment]
`Image.onError` would be an useful thing to have on Android - anyone up for sending a PR for this?

**Comment by mkonicek** [comment]
Cool idea with the HEAD request @satya164!

**Comment by christopherdro** [comment]
@Llong1 Did any of the above suggestions help?

**Comment by christopherdro** [comment]
This issue is being closed because it has been inactive for a while.
