### ISSUE TITLE
Separate APK Google Play Invalid

### ISSUE THREAD

**Issue by alvinwoon** [facebook/react-native#5452]
First of all, thanks for the new separate apks feature on 0.18. It cuts down their respective size by 4 mb!

arm and x86 apk uploads perfectly to play store but the universal apk seems to have problem. 

Here's my build.gradle
```
defaultConfig {
        applicationId "com.foo"
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 7
        versionName "1.6"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
```

It appears that the universal apk is using versionCode as oppose to versionName.

![image](https://cloud.githubusercontent.com/assets/1026383/12472104/94d73fae-c03f-11e5-82e9-3c6d3bd51ae0.png)

**Comment by mkonicek** [comment]
Thanks a lot for trying out the new feature @alvinwoon! It looks like Google Play doesn't like the universal APK because it's unnecessary. What happens if you simply don't upload the universal one?

Maybe we should disable generating the universal APK by default. I thought the universal APK might still be useful in some cases but doesn't look like it is.

**Comment by mkonicek** [comment]
Will commit a change that changes this to `false` soon.

**Comment by alvinwoon** [comment]
@mkonicek

> What happens if you simply don't upload the universal one?

Basically nothing. Play still serves the right apk to different testing devices of mine. So +1 on removing universal. Thanks!
