### ISSUE TITLE
[RFC] Support UIDatePickerModeCountDownTimer on DatePickerIOS

### ISSUE THREAD

**Issue by chirag04** [facebook/react-native#5470]
Right now UIDatePickerModeCountDownTimer is not supported on DatePickerIOS. I have very basic support for it here: https://github.com/facebook/react-native/compare/master...chirag04:countdown_mode

Before submitting a PR i want to discuss the API. Here's what i have right now: 

`onDateChange` in `countdown` mode gives `seconds` and `date` object in other modes.

`nativeEvent` return `countDownDuration` in `countdown` mode and `timestamp` in other modes.

in `countdown` mode `countDownDuration` sets the initial value and `date` prop sets the initial value otherwise.

![screen shot 2016-01-21 at 4 22 08 pm](https://cloud.githubusercontent.com/assets/954063/12494989/2a5ae4d4-c05b-11e5-91c5-643ebbe88511.png)

cc @nicklockwood

**Comment by chirag04** [comment]
as a temp fix i created this: https://github.com/4Catalyzer/react-native-countdown-picker

**Comment by nicklockwood** [comment]
Sorry for the radio silence. The proposal sounds reasonable.

I guess the other options would be:

* Create a different component called something like `<CountdownPicker>` so that you don't have props that are mode-specific.

* Rename `date` to something like `value` so you can use the same prop for both date and countdown duration.

**Comment by chirag04** [comment]
Android recently added `DatePickerAndroid` and `TimerPickerAndroid` and in that direction `CountdownPicker` sounds good.

If the goal is to unify Date and Timer Picker on Android then a unified `DatePicker` with `value` props looks good.

Not sure what the roadmap is here.

@mkonicek thoughts?

**Comment by mkonicek** [comment]
Android Date and Time picker are separate components: http://developer.android.com/guide/topics/ui/controls/pickers.html

It makes sense to build a date&time picker using these but since the date and time picker show a separate dialog the UI and API is not very clear (there are many ways to do it). Once 0.20 is released with the Android date & time pickers we'll see what APIs (3rd party modules) people come up with on top of these.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/rfc-support-uidatepickermodecountdowntimer-on-datepickerios

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
