### ISSUE TITLE
Name collision without Pod

### ISSUE THREAD

**Issue by tobatha** [facebook/react-native#5472]
Hey guys, i followed the instruction and successfully created a project called ReactNative, when i open it with Xcode 7.2 & run, it always shows below error, plz help !

Error building DependencyGraph:
 Error: Naming collision detected: /Users/johnny/Documents/drafts/ReactNative/package.json collides with /Users/johnny/Documents/drafts/ReactNative/node_modules/react-native/Libraries/ReactNative/ReactNative.js
    at HasteMap._updateHasteMap (HasteMap.js:132:13)
    at HasteMap.js:112:32
    at tryCallOne (/Users/johnny/Documents/drafts/ReactNative/node_modules/promise/lib/core.js:37:12)
    at /Users/johnny/Documents/drafts/ReactNative/node_modules/promise/lib/core.js:123:15
    at flush (/Users/johnny/Documents/drafts/ReactNative/node_modules/asap/raw.js:50:29)
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! ReactNative@0.0.1 start: `node node_modules/react-native/local-cli/cli.js start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ReactNative@0.0.1 start script 'node node_modules/react-native/local-cli/cli.js start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ReactNative package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/react-native/local-cli/cli.js start
npm ERR! You can get their info via:
npm ERR!     npm owner ls ReactNative
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/johnny/Documents/drafts/ReactNative/npm-debug.log
JohnnydeMacBook-Pro:ReactNative johnny$ node -v
v5.4.1

**Comment by tobatha** [comment]
react-native-cli: 0.1.10
react-native: 0.18.1

$ node -v
v5.4.1

**Comment by dreamzhu** [comment]
I am running into the same problem

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/name-collision-without-pod

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
