### ISSUE TITLE
[IOS] onLayout called twice after entering to background

### ISSUE THREAD

**Issue by Fanghao** [facebook/react-native#5490]
I've used the UIExplorer example and enabled all four orientations of the iPad app to enable slider over. 

The app is in portrait mode and a `onLayout` was added to the top view of UIExplorerListBase.js. Then the app enter to background and the following logged:
```
'received view layout event\n', { target: 7, layout: { y: 0, x: 0, width: 1024, height: 768 } }
'received view layout event\n', { target: 7, layout: { y: 0, x: 0, width: 768, height: 1024 } }
```
So looks like the app is trying to turn to landscape mode and then back to portrait mode. But it only happens when enable all four orientations so far.

any idea what's the problem?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/ios-onlayout-called-twice-after-entering-to-background

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
