### ISSUE TITLE
Navigator confusion on navigationBar prop

### ISSUE THREAD

**Issue by ffxsam** [facebook/react-native#5506]
The documentation simply states:

>navigationBar node 
>
>Optionally provide a navigation bar that persists across scene transitions

I looked at the source code but still can't make sense of it. Is there any other, more detailed documentation on how to get a basic breadcrumb and title the way `NavigatorIOS` does?

**Comment by Ehesp** [comment]
This simply means you can pass a component in which will act as the Navigation bar instead of the built in one.

```
navigationBar={<View><Text>My own nav bar</Text></View>}
```

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/navigator-confusion-on-navigationbar-prop

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
