### ISSUE TITLE
react-native(android) can't find resource file in 'file:///android_asset'

### ISSUE THREAD

**Issue by jqmobile** [facebook/react-native#5525]
For example, there are some code like 'Image source={{uri : this.GlobalRoot + 'web/logo.png'}}',
GlobalRoot is bundle start root.
It may be like “file:///android_asset/index.android.bundle‘.
.So,the picture path should be 'file:///android_asset/web/logo.png'.
But, react-native can't find logo.png in this path,however,that picture is absolute exist.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/react-nativeandroid-cant-find-resource-file-in-fileandroidasset

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by onlybenyang** [comment]
I also own this issue, could you help tell me your solution @jqmobile
