### ISSUE TITLE
SyntaxError: Unexpected token ... when run jest tests

### ISSUE THREAD

**Issue by maksimr** [facebook/react-native#5532]
I try run tests for react-native but seems jest does not play well with ES6
Jest configuration - https://github.com/maksimr/TestAndroid/blob/test-jest/package.json#L10-L27
Test - https://github.com/maksimr/TestAndroid/blob/test-jest/js/components/HelloWorld/__tests__/index-test.js

Module - https://github.com/maksimr/TestAndroid/blob/test-jest/js/components/HelloWorld/index.js

run `npm test` take
```
Using Jest CLI v0.8.2, jasmine2
 FAIL  js/components/HelloWorld/__tests__/index-test.js
● Runtime Error
SyntaxError: Unexpected token ...
npm ERR! Test failed.  See above for more details.
```
Error message is not so clear but problem in import and I assume problem with es6
How can I run tests for react-native's es6 code?

Thanks

node --version
v5.4.1

npm --version
3.5.3

**Comment by mpm** [comment]
I have the same issue. I don't understand much of the whole babel transformation pipeline, but if you open the [preprocessor.js](https://github.com/facebook/react-native/blob/master/jestSupport/preprocessor.js#L19) refrenced in your `package.json`, you will see that files from the node_modules subdirectory are excempted from beeing transformed to ES5 (see link, line 19):

That means the contents of the react-native npm package is not transformed, while it [uses the spread operator in the main file in line 114](https://github.com/facebook/react-native/blob/master/Libraries/react-native/react-native.js#L114).

(I found this by removing all calls to `require` so I know it happens when you require the react-native package).

I have no idea what this all means or what the intention for this code was (it was introduced a couple of releases ago already), but so far just **commenting out the whole conditional block in `preprocessor.js` line 19+ works for me**!

**Comment by maksimr** [comment]
@mpm thanks! You are right! Problem reproduce only if we import `react-native`

**Comment by vitalets** [comment]
Even after commenting lines in `preprocessor.js` I'm getting another error whet trying to require react-native:
```js
const React = require('react-native');
console.log(React); // TypeError: Cannot read property 'DEFINE_MANY' of undefined

**Comment by maksimr** [comment]
@vitalets maybe you should disable jest automock or add some react libraries to:

```json
    "unmockedModulePathPatterns": [
      "promise",
      "source-map",
      "<rootDir>/node_modules/react",
      "<rootDir>/node_modules/fbjs",
      "<rootDir>/node_modules/react-dom",
      "<rootDir>/node_modules/react-addons-test-utils"
    ]
```

**Comment by vitalets** [comment]
thanks @maksimr! I will try. 
But if I disable jest automock I loose the most powerfull feature of jest..  
And I will need to write manual mocks for all used rn api

**Comment by lovelydreamer** [comment]
I'm having this same issue and can't solve it. Suggestions appreciated. 
https://stackoverflow.com/questions/36993445/runtime-error-running-jest-in-react

**Comment by buamod** [comment]
I having the same issue

**Comment by miclovich** [comment]
same here. With react16+
