### ISSUE TITLE
TextInput onChangeText event won't trigger when text turns to blank

### ISSUE THREAD

**Issue by narychen** [facebook/react-native#5535]
When you delete text in TextInput, the onChangeText event will not trigger at the last character.
Both on ios and android.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/textinput-onchangetext-event-wont-trigger-when-text-turns-to-blank

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by costabatista** [comment]
i'm with this problem too

**Comment by yugalbagul** [comment]
having the same issue in 
```"react": "16.0.0-alpha.6",
    "react-native": "0.44.0"```
