### ISSUE TITLE
TextInput onEndEditting doesn't get invoked until selecting a different text input

### ISSUE THREAD

**Issue by kkjamie** [facebook/react-native#5536]
On iOS the behavior is as expected, when pressing return, the callback is invoked.
With Android however when i hit the done button on the keyboard nothing happens, then when I click another text input, The event comes through. 

Tested using react native 0.17.0, Android v4.4.2 and 5.1.0

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/textinput-onendeditting-doesnt-get-invoked-until-selecting-a-different-text-input

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
