### ISSUE TITLE
How to optimize reactnative framework startup time when we use reactnative partially in our application

### ISSUE THREAD

**Issue by nanpian** [facebook/react-native#5543]
We use reactnative partially in order to be compatible with present app development,and we set develop mode false,but we find that reactnative application start-up time is longer than we expect.We want to make  reactnative application start-up time in about 0.5 seconds.
PS：we have about 3 activities using reactnative,so it takes some time for every reactnative activity start up ,can we make activity single-instance and modify reactnative instance manager  single instance so that we do not need to initialize reactnative instance manager every time?
Do we have any idea?

**Comment by xueduany** [comment]
You can try react-mix bundle example, seprate bundle file into two part , one is common file, another is smaller, business code bundle
https://github.com/xueduany/react-mix

**Comment by satya164** [comment]
@nanpian Yeah, you can use a single instance of the InstanceManager.

**Comment by nanpian** [comment]
@satya164  we're trying it.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/how-to-optimize-reactnative-framework-startup-time-when-we-use-reactnative-partially-in-our-application

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
