### ISSUE TITLE
Start/Stop Profiling doesn't seem to work on iOS 9.2

### ISSUE THREAD

**Issue by gr4yscale** [facebook/react-native#5551]
I'm generally confused about how to go about how to profile for performance on React Native with iOS.

I noticed a "JSC profiler is not supported" error, so then looked through the code of RCTJSCProfiler.m and realized it's trying to load a dylib (which as far as I know, I didn't have installed).

This led me to discovering that there is a JSCLegacyProfiler directory in the repo, so I ran the make script "make ios9" and got the dylibs needed.

I also did the brew install trace2html

After this, when running my project I got some crashes and general unpredicable behavior...the packager crashing sometimes, and lots of intermittent bad access on my app.

Does this functionality work with the latest release? If so, can someone give a quick summary of the steps to get it working in a stable manner? Should I try running this against an older version of iOS perhaps?

**Comment by gr4yscale** [comment]
On simulator I'm not seeing crashes consistently, but after selecting "Stop Profiling" in the menu I see an error from the json2trace script "maximun recursion depth exceeded while decoding a JSON object from a byte string"

![simulator screen shot 26 jan 2016 12 32 13](https://cloud.githubusercontent.com/assets/1342396/12580632/070864da-c429-11e5-93f9-4383303af38f.png)

**Comment by jnak** [comment]
+1 I've run the makefile and I'm not sure what to do next

@tadeuzagallo Would be awesome to have a brief instructions what to do after we run the make file :)
Great talk at react conf btw!

**Comment by jsierles** [comment]
@tadeuzagallo could iOS > 9.0 be using newer versions of libraries like JSCore? Couldn't find much info, as this page stops at 9.0.

http://www.opensource.apple.com/

**Comment by tadeuzagallo** [comment]
@jsierles iOS 9.2 uses JSC version 601.1.46 (you can just run `otool -L <library>` and it'll give you the version)

You can see the source here: https://trac.webkit.org/browser/branches/safari-601.1.46-branch/Source/JavaScriptCore

It doesn't seem to have anything that'd break the profiler.

@gr4yscale For how long did you run the profiler? Please note that it's extremely verbose, it'll log *every* function call, including to builtins.

@jnak I'm working on it! ;)

**Comment by cmcewen** [comment]
Can anyone point me in the right direction to get the profiler running? I was able to get the Makefile to run by changing the curl command but not sure where to go from there

**Comment by robclouth** [comment]
@tadeuzagallo is this the recommended method of profiling? i'm hitting performance problems in JS and suddenly realised I have no easy way of profiling.

**Comment by tadeuzagallo** [comment]
@robclouth As far as I'm aware, yes, either that or systrace, depending on the kind of problem, but I haven't been working on that for a while... @ndfred might be able to confirm.

**Comment by robclouth** [comment]
Yeah systrace works on Android, but I didn't think it was for iOS too.

**Comment by tadeuzagallo** [comment]
Yeah, AFAIK it should be available from the dev menu on iOS, as long as you're connected to the packager. It should be straightforward from there.

**Comment by robclouth** [comment]
I have the perf monitor but it only shows fps and some other high level
timings for initialisation and stuff. I'm looking for some proper systrace
style sampling or timing tool to figure out if the performance drop is from
the bridge or my code or wherever.

**Comment by tadeuzagallo** [comment]
I didn't mean the perf monitor, I meant systrace. If you're connected to the packager there should be an item in the dev menu that says "Start Systrace": https://github.com/facebook/react-native/blob/master/React/Modules/RCTDevMenu.m#L485

**Comment by wafisher** [comment]
Just a clarification, systrace can be used with iOS, too? Everything that shows up on Google talks about using it with Android only.

**Comment by tadeuzagallo** [comment]
React Native has a custom implementation of Systrace that works on iOS. See: https://github.com/facebook/react-native/blob/master/React/Profiler/RCTProfile.m

It can't provide you with all the information you'd see in Android, like scheduling and IO, but it does hook into the bridge, into every bridge module (in the ObjC bridge) and in all the React Components (in DEV mode).

**Comment by robclouth** [comment]
I can't believe I missed that! Thanks.

**Comment by robclouth** [comment]
The resulting traces are always blank when I open them. Viewing source shows that there's a lot going on scriptwise...but alas, nothing on the screen. This is on the simulator.

**Comment by robclouth** [comment]
Ok, the files that this outputs aren't compatible with the latest version of chrome, because they use ```Object.observe``` which has been removed. 
Loading the files in chrome://tracing fails with this message:
```
Error: Couldn't create an importer for the provided eventData.
    at Import.createImporter_ (chrome://tracing/tracing.js:1348:3342)
    at Import.createImports (chrome://tracing/tracing.js:1343:21)
    at Task.run (chrome://tracing/tracing.js:2062:13)
    at runAnother (chrome://tracing/tracing.js:2074:136)
    at runTask (chrome://tracing/tracing.js:2037:57)
    at processIdleWork (chrome://tracing/tracing.js:2043:116)
    at window.requestIdleCallback.timeout (chrome://tracing/tracing.js:2031:81)
```

The solution is to edit the html file to include a polyfill. [Details here](http://stackoverflow.com/a/37475803/4120819)

**Comment by robclouth** [comment]
The resulting traces are always blank when I open them. Viewing source
shows that there's a lot going on scriptwise...but alas, nothing on the
screen. This is on the simulator.

**Comment by gr4yscale** [comment]
+1 @robclouth also seeing this now

**Comment by peacechen** [comment]
To view the systrace in Chrome, uninstall `trace2html` so that RN doesn't clobber the JSON after generating the html.  We want to load the raw JSON in Chrome.

1. Open a new tab in chrome and enter `chrome://tracing`
2. Select Load and point it to the JSON file

The finder window annoyingly refuses to navigate to /tmp, so I had to move `/tmp/dump*.json` to an accessible directory.  Chrome's tracing debug tool is able to parse the JSON from RN Systrace.

**Comment by mattfysh** [comment]
is the custom RN systrace okay to use for iOS apps, or should we use Instruments instead?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by kralcifer-ms** [comment]
@tadeuzagallo, is getting the JS Sampling Profiler something that we could use in iOS to get callstacks that include our app JS functions?

RCTDevSettings.mm mentions:
"The JSSamplingProfiler is disabled. See 'iOS specific setup' section here https://fburl.com/u4lw7xeq for some help"

That URL appears to be an internal Facebook one.  Can you get more info on how to turn it on?

I found it via commit [b50f550](https://github.com/facebook/react-native/commit/b50f55026a83dd0f933b2bf8da698764a4641688#diff-5958d22ffdc365e3b3b1fd79941c6300) on Jan 10, 2017

**Comment by tadeuzagallo** [comment]
Hey @kralcifer-ms, as far as I know, that doesn't work with the builtin JSC. Unfortunately, I no longer work on this, so I'm afraid I don't have much more info than that. You could try to use the tools built into Safari, but I don't know what's the latest state on that (last I checked only very few features worked with JSC running on mobile).
