### ISSUE TITLE
RefreshControl "Spinner" Animation Problem [iOS]

### ISSUE THREAD

**Issue by daesan** [facebook/react-native#5553]
When I pull down the ListView with RefreshControl the first time, "spinner appearing" animation works as expected. However, from the second time on, if I pull down the ListView, "spinner appearing" animation gets delayed for some reason. (You have to pull down much further for "spinner" to start to appear.)

See the images attached below.

![ptr_first](https://cloud.githubusercontent.com/assets/2495/12583713/724a920a-c487-11e5-8bf2-78b38c894f8a.png)
![ptr_second](https://cloud.githubusercontent.com/assets/2495/12583714/728d38f8-c487-11e5-9997-36850c121801.png)

By the way, thanks a lot for implementing this feature. I was pulling my hair all out to implement this in JS.

**Comment by davidskaarup** [comment]
+1

**Comment by davidskaarup** [comment]
I have done a bit of testing, and the problem seems to occur when all the items in the listview have not been loaded, i.e. by using initialListSize. If all elements are loaded by scrolling to the bottom of the list it works fine.

**Comment by daesan** [comment]
@davidskaarup Hi. I removed "initialListSize" from ListView and the problem went away. Thanks for sharing the tip!

**Comment by davidskaarup** [comment]
Well it's a workaround, but optimally you should be able to use initialListSize without the spinner acting up. Can you reopen the issue so hopefully someone looks into it?

**Comment by daesan** [comment]
Sure. From what I can tell, ListView performance has improved quite a bit in the past months that I don't think I really need to use initialListSize anymore on my app. But as you said, it is a workaround. I will keep this issue open.

**Comment by janicduplessis** [comment]
@daesan Should be fixed in 102a31c13eed82432b3e0d93230653394f7baa3d. Can you check if it works now with react-native@0.22.0-rc4?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/refreshcontrol-spinner-animation-problem-ios

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
