### ISSUE TITLE
First Responder Issue!

### ISSUE THREAD

**Issue by aiflow** [facebook/react-native#5554]
Hi,

I have a Popup View on top of a ListView. The popup has itself a ListView and the scroll works fine but the touchable rows pass the touch to the back. The other half of the popup which is on top of a normal View handles the touches correctly.
The only workaround is to wrap the behind ListView in a View with pointerEvents-none.

Thank You!

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/first-responder-issue

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
