### ISSUE TITLE
PullToRefreshViewAndroid when `refreshing` prop is initially true

### ISSUE THREAD

**Issue by mikemonteith** [facebook/react-native#5560]
The PullToRefreshViewAndroid component doesn't honour the `refreshing` prop if it is set to true on initial mount.

This seems to be because you must call `setRefresh()` _after_ the Android SwipeRefreshView has been measured with `onMeasure()` (http://stackoverflow.com/questions/26858692/swiperefreshlayout-setrefreshing-not-showing-indicator-initially).

I have a javascript solution to this which involves using `setNativeProps` inside `onLayout()` to force the correct refreshing state. Note the refreshing prop is completely handled outside of `render()`.
This seems a bit hacky due to the use of onLayout.

```js
  _onLayout: function(e){
    this.refs[NATIVE_REF].setNativeProps({refreshing: !!this.props.refreshing});
    this.props.onLayout && this.props.onLayout(e);
  },

  componentDidUpdate: function(nextProps){
    if(this.props.refreshing !== nextProps.refreshing){
      this.refs[NATIVE_REF].setNativeProps({refreshing: !!this.props.refreshing});
    }

    return true;
  },

  render: function() {
    return (
      <NativePullToRefresh
        colors={this.props.colors && this.props.colors.map(processColor)}
        enabled={this.props.enabled}
        onRefresh={this._onRefresh}
        progressBackgroundColor={this.props.progressBackgroundColor}
        ref={NATIVE_REF}
        onLayout={this._onLayout}
        size={this.props.size}
        style={this.props.style}>
        {onlyChild(this.props.children)}
      </NativePullToRefresh>
    );
  },
```

Is there a better way of doing this?
Should it be fixed on the Android side maybe?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/pulltorefreshviewandroid-when-refreshing-prop-is-initially-true

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
