### ISSUE TITLE
Use Babel constant elements and inline elements in production

### ISSUE THREAD

**Issue by DaleJefferson** [facebook/react-native#5565]
Is there any reason why we can't enable the following transforms in production?

*React constant elements transformer*
https://babeljs.io/docs/plugins/transform-react-constant-elements/

*React inline elements transform*
https://babeljs.io/docs/plugins/transform-react-inline-elements/

**Comment by satya164** [comment]
cc @davidaurelio

**Comment by janicduplessis** [comment]
Have you tried using a `.babelrc` file in your project that extends `react-native` using the `babel-preset-react-native` and add these transforms.

If it works well it might be interesting to add them to the preset when building with `dev=false`.

**Comment by davidaurelio** [comment]
@DaleJefferson: Is the question why we didn’t add these to our default preset?
As @janicduplessis pointed out, you can easily enable it for your own projects.

I will be happy to try to add it in general as soon as I have more bandwidth

**Comment by lacker** [comment]
It's been a while and this seems like a "nice to have but not critical" issue since you can add this as a workaround in your own project pretty straightforwardly. It isn't clear to me that this would add all that much value, FWIW - it doesn't seem like this is likely to be on a critical performance path. If you do want this then I think a good way to make progress would just be to try it out for a while on your own project and see if things break.
