### ISSUE TITLE
Bugs of Navigator method jumpBack jumpTo(route) 

### ISSUE THREAD

**Issue by narychen** [facebook/react-native#5567]
When you use  jumpBack() or jumpTo(prevRoute) to previous route, the navbar's right button of the previous scene  won't get the correct route from navigationBarRouteMapper.RightButton(route, navigator, index, navState). And the right button won't be responding after that. 
The behavior is weird. It seems the views in the navbar got messed up. But the pop() method work correctly.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/bugs-of-navigator-method-jumpback-jumptoroute-

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
