### ISSUE TITLE
image cannot be rendered in low memory android

### ISSUE THREAD

**Issue by notlose** [facebook/react-native#5568]
all images rendering fine after a fresh start of app,
but the image cannot load properly after some navigation through views
is anyone encountering this problem same as me?

**Comment by gvaish** [comment]
@notlose Do you have a sample app / code to reproduce the behavior?

**Comment by notlose** [comment]
@gvaish i can create a sample app later on, 
i have exactly the same situation described here: 
http://stackoverflow.com/questions/34655189/react-native-image-missing-after-reloading-js-several-times/34786001#34786001

**Comment by laeijebor** [comment]
Having the same issue. I've been doing some playing around and noticed that in the situation @notlose describes (having reloaded JS many times), the image's **onLoad** doesn't fire, but **onLoadStart** and **onLoadEnd** do. Not sure if this is cause or effect, though...

Restarting app does seem to temporarily cure, as pointed out.

Setup is rn 0.19.0 and: GenyMotion on Mac, or GalaxyTab S2. GenyMotion emulator is set to 2048mb base memory.

**Comment by Sh3rawi** [comment]
@laeijebor We are suffering from the same issue, we have a quite large number of images in a certain scene in the app and it happens many times that appear/disappear randomly, both static images and network images. Any progress on that from your side ?

**Comment by 9mm** [comment]
I think I'm seeing the same thing, my images just show up blank a lot of times when many are on the same page. I'm not really sure how to go about starting to fix this however.

**Comment by notlose** [comment]
@Sh3rawi @9mm you can try to add android:largeHeap="true" in your android manifest application tag as a workaround, my app works better with this

**Comment by laeijebor** [comment]
@notlose Yep - that has been working for me for the last few days, too...

**Comment by phones24** [comment]
Same error since v0.19, I think. Happened on emulator and on galaxy s2. Also onLoadEnd doesn't provide any information about the error.

**Comment by NorthFoxz** [comment]
+1

**Comment by InnerPeace080** [comment]
+1

**Comment by notlose** [comment]
still happening on 0.25

**Comment by Sh3rawi** [comment]
@notlose what i did to fix this issue permanently is to copy the image component to a custom component but turn off hardware acceleration for it (view.setLayerType(View.LAYER_TYPE_SOFTWARE, null) in the setSource function in the CustomImageManager.java

**Comment by InnerPeace080** [comment]
i write app for android (i used large heap setting in manifestfile).
but Image  disapear when i exit and start app serve time. 
Image will apear again if i exit app by recently app list.

seem like when exit app (by back button) , memories for app not released .

**Comment by ms88privat** [comment]
+1

**Comment by itinance** [comment]
same issue here

**Comment by LHIOUI** [comment]
+1

**Comment by edencakir** [comment]
+1

**Comment by mwiley** [comment]
I'm experiencing this issue on lower end Android devices with react-native@0.33.

**Comment by daltones** [comment]
I'm having this problem on Android too. I have a parallax background formed by a few overlapping layers. They are png images as static resources. Every time they are rendered some will fail to load randomly.

**Comment by dgurns** [comment]
Still having this issue on lower end Android devices with RN 0.41.

**Comment by Kottidev** [comment]
I'm having same probleme with RN 0.42 . 
![screenshot_20170321-004117_1024](https://cloud.githubusercontent.com/assets/12915009/24138617/32807e32-0e19-11e7-8a77-ad9cad597c6d.png)

**Comment by jzhangdev** [comment]
@Kottidev Hi, can you solve this problems on android ?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by odemolliens** [comment]
It's not fixed at all...
