### ISSUE TITLE
:app:installDebug FAILED, while trying to run the application on AVD.

### ISSUE THREAD

**Issue by Panda-Srujan** [facebook/react-native#5581]
Hi everyone,

I'm new to react native. I've installed all the prerequisites required to develop the applications in react native.

I'm facing an error that says ':app:installDebug FAILED' while testing the application in AVD.

I've started the AVD manager.

![avd running 1](https://cloud.githubusercontent.com/assets/16679478/12614389/a29333d8-c525-11e5-98a5-7e9b4168e933.png)

Steps I followed in running the application.

I've configured a virtual device.

![avd manager configuration 1](https://cloud.githubusercontent.com/assets/16679478/12614436/f4f99afe-c525-11e5-8de1-91af28010ae4.png)

I'm facing the following error on running the application.

![react native error](https://cloud.githubusercontent.com/assets/16679478/12614446/0b70929c-c526-11e5-9a70-1bf608270298.png)

Thanks in advance.

**Comment by lalop** [comment]
Hi @Panda-Srujan,
did you start the vm manually ?

**Comment by janicduplessis** [comment]
@facebook-github-bot label Needs Response from Author

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/appinstalldebug-failed-while-trying-to-run-the-application-on-avd

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
