### ISSUE TITLE
Latency with RCTBubblingEventBlock at startup

### ISSUE THREAD

**Issue by timfpark** [facebook/react-native#5606]
I'm seeing a lot of latency with RCTBubblingEventBlock at startup and 0.17 that I don't believe I saw as much of with previous versions.

In my native module I have:

`@property (nonatomic, copy) RCTBubblingEventBlock onTileFetch;
`
which I then call at startup like so from the native module:

```
self.onTileFetch(@{
    @"action": @"tile-fetch",
    @"path": tilePath
});
```

which is bound to an event handler in my code:

```
onTileFetch: function(event: Event) {
       //...
},
```

I see self.onTileFetch being called in the native layer immediately at startup, but onTileFetch in the JavaScript layer is called something like 5000ms later.

After initial startup, the latency is much more management (~100ms). Is there something at startup that makes this expected?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/latency-with-rctbubblingeventblock-at-startup

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
