### ISSUE TITLE
Sometimes got error of  RCTNetworking.sendRequest() not found 

### ISSUE THREAD

**Issue by fakefish** [facebook/react-native#5607]
error message is like:
```
Invariant Violation: Callback with id 1: RCTNetworking.sendRequest() not found
```
it repeated over 21 times...

![qq20160129-0](https://cloud.githubusercontent.com/assets/1334025/12666677/04dd9200-c67e-11e5-8320-8bd323442456.png)

**Comment by jordanranz** [comment]
I get the same error when I have multiple Chrome debugger tabs open.

Here is the console log in Chrome:
<img width="1278" alt="screen shot 2016-01-28 at 9 38 37 pm" src="https://cloud.githubusercontent.com/assets/3868826/12668039/8fa4a652-c607-11e5-9c0d-86b6ffdf825b.png">

**Comment by fakefish** [comment]
@jordanranz so am I, debugger tab will automatically open..

**Comment by perqa** [comment]
Same problem here, and I'm running the debugger on the unaltered Movies example from https://github.com/facebook/react-native/tree/master/Examples/Movies. Using OS X and Chrome.

**Comment by Dcl1** [comment]
Closed multiples of Chrome debugger like @jordanranz said. Worked for me.

**Comment by brendanscarano** [comment]
The multiple tabs of Chrome debugger was breaking it for me as well. Closed all but 1 of them and now it works fine.

**Comment by Mokto** [comment]
It is still annoying that Chrome windows pop sometimes...

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/sometimes-got-error-of-rctnetworkingsendrequest-not-found-

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
