### ISSUE TITLE
exc_bad_access when systrace enabled

### ISSUE THREAD

**Issue by genxstylez** [facebook/react-native#5609]
<img width="710" alt="screen shot 2016-01-29 at 12 23 43 pm" src="https://cloud.githubusercontent.com/assets/1086338/12667179/2ba1043a-c683-11e5-8f3b-7d107be6d208.png">

This happens when I turn on systrace and reload the app, at this point, I had to reset simulator (with systrace turned off) to get the app working again

**Comment by gre** [comment]
I can't make systrace working neither since React Native 0.18 and this seem to systematically breaks when using third party library like gl-react-native.

I don't know what part is broken there and the error is cryptical.
I have even tried to commented out all gl-react-native's RCT_PROFILE_* usage but it still breaks.

<img width="952" alt="screen shot 2016-01-29 at 10 46 03" src="https://cloud.githubusercontent.com/assets/211411/12672306/880d71d0-c675-11e5-8506-e68e1f1d146b.png">

It seems to break after the systrace start and the first time you do an action that create a new view.
For instance when running https://github.com/ProjectSeptemberInc/gl-react-native/tree/master/Examples/Simple , the first time you change a tab.

I couldn't repro on UIExplorer.

any idea @nicklockwood ?

**Comment by nicklockwood** [comment]
It looks like the method signature for `-[RCTComponentData createViewWithTag:]` was changed, which is why the version in RCTProfile is crashing. This is fixed in the latest version though, so maybe the fix just didn't make it into 0.18?

**Comment by gre** [comment]
oh ok ! mmh let me try with facebook/react-native#master

**Comment by gre** [comment]
ok. it's working fine in master. is there any chance a patch gets in 0.18.x ?

**Comment by nicklockwood** [comment]
You could just copy the files.

**Comment by nicklockwood** [comment]
@mkonicek do you think it's worth releasing an 0.18.1 update with this fix?

**Comment by gre** [comment]
what is the commit?

**Comment by nicklockwood** [comment]
@gre this one: https://github.com/facebook/react-native/commit/473f9bca192a15e21946316a87b29001deccd5bf

**Comment by gre** [comment]
It is now working fine on React Native 0.19.

( @genxstylez i've also released gl-react-native 2.19.0 )
