### ISSUE TITLE
task 'bundleReleaseJsAndAssets' is not run when run assembleRelease

### ISSUE THREAD

**Issue by soxunyi** [facebook/react-native#5615]
![e458c601405](https://cloud.githubusercontent.com/assets/3918423/12673420/97bc8c32-c6b7-11e5-9b31-54181498f452.jpg)

As the above images. I run assembleRelease on two pc.
And on a pc, I find that bundleReleaseJsAndAssets  is not run, and run the release apk file, occur running error as follows:
```
E/AndroidRuntime(11821): com.facebook.react.bridge.JSExecutionException: ReferenceError: Can't find variable: __fbBatchedBridge (line 1 in the generated bundle)
E/AndroidRuntime(11821): 	at com.facebook.react.bridge.ReactBridge.loadScriptFromAssets(Native Method)
E/AndroidRuntime(11821): 	at com.facebook.react.bridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:32)
E/AndroidRuntime(11821): 	at com.facebook.react.bridge.CatalystInstanceImpl$2.run(CatalystInstanceImpl.java:154)
E/AndroidRuntime(11821): 	at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime(11821): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(11821): 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
E/AndroidRuntime(11821): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(11821): 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$1.run(MessageQueueThreadImpl.java:137)
E/AndroidRuntime(11821): 	at java.lang.Thread.run(Thread.java:841)
```

**Comment by dantman** [comment]
I have the same issue on OSX.

I threw some `logger.warn` calls into `react.gradle` to see if there was any obvious issue.
* `config."bundleIn${targetName}" ?: targetName.toLowerCase().contains("release")` resolves to `true` when `${targetName} == "Release"` so the task is not disabled.
* I tried making sure `react-native` is installed globally on my system node (rather than just inside the nvm version I was using), no difference.
* `mergeReleaseResources` and `mergeReleaseAssets` both are run during the job and commenting them out as dependencies changes nothing.
* I checked if `dependentTask` inside `runBefore` was null or not-null; It was not-null for `processDebugResources` and `processReleaseResources` so it should be registered.

In the Gradle projects view in Android Studio the jobs are present:
![screen shot 2016-02-20 at 2 21 37 pm](https://cloud.githubusercontent.com/assets/53399/13199548/73f0cb42-d7dd-11e5-831a-7c1557d60480.png)

However trying to run bundleReleaseJsAndAssets directly from there results in this error:
```
Error:FAILURE: Build failed with an exception.

* What went wrong:
Task 'bundleReleaseJsAndAssets' not found in root project 'MindMonkey'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

**Comment by dantman** [comment]
bundleReleaseJsAndAssets is run for me when I use `./gradlew assembleRelease` instead of using the standard way of running gradle through Android Studio.

**Comment by soxunyi** [comment]
Before `cd android && ./gradlew iRelease,
Run the below bundle command, instead of bundleReleaseJsAndAssets
`react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/

**Comment by fab1an** [comment]
Same problem here. It works on the commandline, it doesn't work in Android Studio.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/task-bundlereleasejsandassets-is-not-run-when-run-assemblerelease

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by fab1an** [comment]
@mkonicek: Bugs like this will never gain enough traction on ProductPains.

I reported this with JetBrains / AndroidStudio: https://youtrack.jetbrains.com/issue/IDEA-162837

**Comment by helengray** [comment]
I meet the same problem.I even can't see the group of gradle 'react' and the 'bundleReleaseJsAndAssets' task.
I had Reopen and Refresh

**Comment by matto1990** [comment]
I'm having a similar issue on my machine. It refuses to bundle using the Gradle plugin from either the command line or Android Studio. Bundling using the `react-native` command works fine.

It seems to be machine dependent because another developer can build correctly with the same codebase.

**Comment by soxunyi** [comment]
please see https://github.com/facebook/react-native/issues/7258
