### ISSUE TITLE
Navigator: Change transition color

### ISSUE THREAD

**Issue by jlevine22** [facebook/react-native#563]
Is there no way to change the background color on transitions between scenes in a Navigator component? I've dug into the code and it seems like the color value is hard coded. 

I've played around with adding this feature as a property on a Navigator (transitionBackgroundColor={'#FFFFFF'}). But I want to make sure this doesn't already exist before issuing a pull request.

**Comment by evanwalsh** [comment]
This would be extremely helpful. I hope this gets added!

**Comment by ide** [comment]
Something to consider - should this be a property of the navigator's style?
`<Navigator style={{transitionBackgroundColor: '#000'}} />`

**Comment by jlevine22** [comment]
Good point @ide. On second thought it would seem to make more sense that way

**Comment by ericvicenti** [comment]
Actually, there will be challenges if you try to put it on styles. It is kind of a special prop because we can't rely on it being an object (Stylesheet converts them into numbers for safety and optimization)

If we add `transitionBackgroundColor` as a special case here, then people will get confused and think it is a real style prop. Also, style validations will get confused.

This is the API we want:

`<Navigator style={{backgroundColor: '#000'}} />`

I haven't tried, but what if the default transitioner style is 'transparent'? Does that make this work?

**Comment by jlevine22** [comment]
@ericvicenti just tried and that didn't work. The transition background always ends up white.

**Comment by ericvicenti** [comment]
Hmm, I wonder what is causing it to be white..

cc @vjeux , this is one of those rare cases where we actually want the 'cascade' of CSS. What should we  do in these cases?

Although it is a bit funky, this would probably be the most consistent with everything else we do:

```
<Navigator
  style={{flex: 1}} // style for the navigator container
  transitionerStyle={{backgroundColor: 'black'}} // style applied to the scenes container
 ...
```

**Comment by ericvicenti** [comment]
Oh, @jlevine22, I didn't see your edit. Great news!

**Comment by alvaromb** [comment]
Shouldn't this be documented?
