### ISSUE TITLE
[Bridge] Codegen Flow interfaces from RCTBridgeModules

### ISSUE THREAD

**Issue by ide** [facebook/react-native#566]
This should be mostly automatable via static analysis with the exception of constantsToExport but it'd be useful to have a partial type interface anyway.

**Comment by ide** [comment]
Another thought: this would be helpful as documentation e.g. to easily be able to see what methods UIManager supports without reading the .m file.

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/bridge-codegen-flow-interfaces-from-rctbridgemodules

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
