### ISSUE TITLE
Visual artifact with Flexbox due to non-integral view dimensions

### ISSUE THREAD

**Issue by jdmunro** [facebook/react-native#5711]
I'm working on an app that uses lots of views with simple background colours. I am arranging these in rows using Flexbox. The problem is, depending on the overall containing view width, this sometimes means that the dimensions of the views contained within are non-integral which I believe is causing issues due to sub-pixel alignment.

See the below image:

![img_0346](https://cloud.githubusercontent.com/assets/17656/12762429/0508afc8-c9e7-11e5-95d4-ddcfa6b47b89.PNG)

Each of these views is set to flex 1 within the containing view, so in theory they all have equal distribution. However as you can see from the screenshot there is a vertical white line near the middle of the image. Whether or not this white line is present depends on the width of the containing view.

A little closer investigation reveals that the dimensions and position of the view means they will be aligned over pixel boundaries which I suspect is the root cause of this issue:

![img_0347](https://cloud.githubusercontent.com/assets/17656/12762652/30f949b6-c9e8-11e5-8324-c28e2758e390.PNG)

The containing view size is not absolute, it just fills the available width and has some padding so I don't think setting a fixed width here is a viable solution.

I don't think this is necessarily a bug because I am not sure how else React could behave in this situation. Does anyone have a solution that will allow the use of non-absolute dimensions yet somehow keeping them clamped to integral values?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/visual-artifact-with-flexbox-due-to-non-integral-view-dimensions

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by gre** [comment]
experiencing the same problem. RN 0.28

**Comment by aleclarson** [comment]
@mkonicek Is there a relevant Facebook employee that can look at this? Seems like a serious issue with flexbox, no?

**Comment by gre** [comment]
my workaround is anyone interesting is to fine a magic width that don't have a rounding. you might +1 or +2 or +3 your initial width.. it sucks but it works.

**Comment by jdmunro** [comment]
@gre The problem with that approach (I tried it too!) is that if you also support a different orientation or other screen sizes, you inevitably get the problem there too.

**Comment by gre** [comment]
yeah definitely.

**Comment by satya164** [comment]
Please file this issue on the CSS layout repo - https://github.com/facebook/css-layout

**Comment by hernancorigliano** [comment]
This is still happening in react 0.47. I am building a calendar and have that line in the middle. Has anyone found a workaround the issue?

**Comment by hernancorigliano** [comment]
I leave here my workaround for anyone out there with same issue. This is a big blocker as we cannot ship an App with a visual artifact. It's really bad.

I have a row of 7 flex boxes, so the problem comes form the rounding pixels.

Basically i adapt the width of the screen to a new Width that is divisible by 7.

In my component:

```
updateDimensions(event: Object) {
        const badWidth = (event.nativeEvent.layout.width); // Container width
        const magicWidth = Math.floor(badWidth / 7) * 7; // Closest Divisible by 7

        this.setState({ magicWidth });
    }
```

My component render():
```
 // Fix artifacts-glitches
        let fixedWidth = { width: '100%' };
        if (this.state.magicWidth !== undefined) {
            fixedWidth = { width: this.state.magicWidth };
        }
<View onLayout={this.updateDimensions.bind(this)}>
                <View style={{ alignItems: 'center' }}>
                    <FlatList
                          {...}
                        style={fixedWidth}
                    />
                </View>
            </View>
