### ISSUE TITLE
Organizing javascript code for a large repository [help-wanted]

### ISSUE THREAD

**Issue by prashanth1509** [facebook/react-native#5724]
Our organisation has fairly large repositories for android and ios, so we were planning to have a separate repository for javascript components.

And during their development, js developers will,
1. Checkout native codebase, just make change to the Podfile to specify path where node_modules are installed and will probably not touch that codebase further (except for git pulls)
2. Continue working with independent javascript codebase.
3. I understand there is some work needs to be done incase of installing third party plugins (but this is one time effort). Still,

Anyone follow this approach of having separate repo for js components?
What are the cons that you can think of?

thanks for your suggestions/guidelines.

**Comment by satya164** [comment]
Hey and thanks for reporting this!

There's an awesome place to ask question like this one: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see your question, you can vote on answers and mark question as answered etc. This lets us keep a list of bug reports and feature requests on github and especially [Product Pains](https://productpains.com/product/react-native/?tab=top) (again, with voting which is really nice).

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)
