### ISSUE TITLE
[Navigator] componentWillUnmount not called immediately after pop inside callback

### ISSUE THREAD

**Issue by lrettig** [facebook/react-native#5778]
Hello,

Normally, when a component is popped off the navigator stack, its `componentWillUnmount` method is called right away. I noticed that this isn't happening when `pop` is called inside a callback that the component in question passes somewhere else. The component is still popped, i.e., it goes away, but `componentWillUnmount` isn't called until another `push` happens.

In my app, I have three screens. Screen 1 pushes Screen 2. Screen 2 pushes Screen 3, and passes it a callback where it pops itself. Screen 3 does something, then pops itself, then calls the callback it received from Screen 2. I put together a very simple example here: https://github.com/lrettig/callback-pop-bug-example.

Using RN 0.19.

Thanks.

**Comment by grabbou** [comment]
Hey,

My guess is that call to `pop` from Screen2 happens before Screen3 is really unmounted (or during that process) which results in noop because of that line https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/Navigator/Navigator.js#L944

You could try `popToRoute` which should work in your case.
