### ISSUE TITLE
[Android] [BackAndroid] New listeners registered while back event is handled also receive the current event

### ISSUE THREAD

**Issue by feichngr** [facebook/react-native#5781]
I just faced for me unexpected behavior when (indirectly) registering a listener to `BackAndroid` while an event is currently handled.

In my project I use a `Root` component type, which calls a function provided to it via the `onBackPress` prop. It looks something like this:
```
export default class Root extends React.Component {

  _handleBackButton = () => {
    if (this.props.onBackPress) {
      this.props.onBackPress();
      return true;
    }
    return false;
  };

  componentDidMount() {
    BackAndroid.addEventListener('hardwareBackPress', this._handleBackButton);
  }

  componentWillUnmount() {
    BackAndroid.removeEventListener('hardwareBackPress', this._handleBackButton);
  }

  render() {
    return (
      …
  }
}
```

Now if the back button is pressed and, as part of the `onBackPress` function, the current `Root` element is replaced by a new one, the new `Root` element's `componentDidMount` is executed before `onBackPress` returns, adding the new event listener to `BackAndroid`.
Problem is: `BackAndroid` will add the new listener to the `Set` of listeners it loops over and eventually call the newly added listener for the same event it was created by.

I think the better behavior would be not to modify the `Set` of listeners while looping over them to dispatch an event. In case the `Set` needs to be modified create a copy, apply the modification there and continue to use the original `Set` to complete handling of the current event.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-backandroid-new-listeners-registered-while-back-event-is-handled-also-receive-the-current-event

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
