### ISSUE TITLE
[TextInput] Not rendering multiline values

### ISSUE THREAD

**Issue by TheeSweeney** [facebook/react-native#5786]
I have a text input on a page that is meant to render with a small block of text. Initially it's state is set to "Loading..." and I do a fetch to my db to get the block of text from my db (it's a bio that I would like to be editable) and set it to the state, causing a rerender. The idea is that the text input's value would be set to this block of text, rendering it inside the TextInput. I then have onChangeText function that set's the state to whatever is in the TextInput, and then a "save" button that does a PUT to my db with the current state of that TextInput. The basic functionality is fine, everything is hooked up correctly as far as I can tell.

The bug is this, though my fetch returns the block of text, anything on the second line of the block and below is not rendered. So if in my db, the bio is:

    I'm an Amateur Sailor from NZ.
    My Name is Germain.

only "I'm an Amateur Sailor from NZ." will render in the TextInput. The second line will appear only if the user focuses on the textinput AND types something. 

I've done console.logs to confirm the state is being set to a multiline value. I even have a function that calculates the difference between the current states length and the max length to show "characters remaining". Even though the app does not show the second line of the text initially, this "characters remaining" number will be calculated as though the second line is in there as well. 

I have thoroughly outlined the problem and various workaround I have tested in this post:
http://stackoverflow.com/questions/35170520/value-in-a-multiline-textinput-field-not-fully-rendering-react-native

react-native-cli: 0.1.10
react-native: 0.18.1

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/textinput-not-rendering-multiline-values

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
