### ISSUE TITLE
Can't build project for iOS 9.0 (but iOS 9.2 is fine)

### ISSUE THREAD

**Issue by ffxsam** [facebook/react-native#5809]
See attached errors below. Xcode project has 9.0 set as deployment target.

```
Feb  7 18:20:30  SydTechEco[13189] <Error>: CGContextSaveGState: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Feb  7 18:20:30  SydTechEco[13189] <Error>: CGContextTranslateCTM: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Feb  7 18:20:30  SydTechEco[13189] <Error>: CGContextRestoreGState: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
2016-02-07 18:20:30.752 [trace][tid:com.facebook.React.JavaScript][RCTJSCProfiler.m:63] JSC profiler is not supported.
2016-02-07 18:20:30.818 [error][tid:main] The operation couldn’t be completed. No such file or directory
```

![screenshot_2_7_16__6_21_pm](https://cloud.githubusercontent.com/assets/12532733/12877400/9c2522b8-cdc7-11e5-9942-3582aa9095ed.png)

**Comment by ffxsam** [comment]
A fresh project works fine, so the issue is specific to my project. I can't think of anything terribly unique about my project except that I integrated Facebook OAuth SDK into Xcode. That might have something to do with it?

**Comment by basketofsoftkittens** [comment]
does it work on 8.1 simulator?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/cant-build-project-for-ios-90-but-ios-92-is-fine

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by npomfret** [comment]
I'm getting this with 9.0 also - anyone know what the problem is?
