### ISSUE TITLE
User-Agent header not getting set with 'source' prop in Android Webviews

### ISSUE THREAD

**Issue by mtostenson** [facebook/react-native#5821]
With the recent addition of the 'source' prop to Android webviews, developers can provide a custom set of headers to the webview when making a request. However, in Android, the User-Agent header gets set through the webview settings and cannot be applied the same way as the rest of the headers.

**Comment by mkonicek** [comment]
Good catch, thanks!

**Comment by christopherdro** [comment]
@facebook-githb-bot bugfix

**Comment by Gentlee** [comment]
WebView has undocumented 'userAgent' property, you can try use it like this:

    <WebView
        userAgent='MyApp'
        style={{flex:1}}
        source={{uri:this.state.url}}/>

works only for android.

**Comment by greena13** [comment]
@Gentlee, appears to work for IOS as well on v0.29.0. Thanks!

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/user-agent-header-not-getting-set-with-source-prop-in-android-webviews

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
