### ISSUE TITLE
Syntax Error occurred when try to build the react-native android application in genymotion

### ISSUE THREAD

**Issue by SamTharani** [facebook/react-native#5833]
I create an android application using react-native when I try to load that application into Genymotion it shows an error as
 399/400Error while persisting cache: SyntaxError /home/samantha/AwesomeProject/index.android.js: "React" is read-only

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/syntax-error-occurred-when-try-to-build-the-react-native-android-application-in-genymotion

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
