### ISSUE TITLE
Warnings are useless without stacktraces

### ISSUE THREAD

**Issue by Noiwex** [facebook/react-native#5834]
So I'm getting warnings during application start and I can't even trace out the source of problem. The warning text is just that:
```
Warning: setState(...): Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.
```

Isn't there a way to give proper warnings with informative details instead of bogus spam?

**Comment by vjeux** [comment]
cc @spicyj

**Comment by spicyj** [comment]
I thought this message gave the component name but maybe it doesn't. I guess the yellow box doesn't show a stack trace? It would be nice if we could add that but for now you could try using the Chrome debugger to see the full stack trace.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/warnings-are-useless-without-stacktraces

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by Noiwex** [comment]
Seems like it was fixed in last version, but I'll check that out later.
