### ISSUE TITLE
[TextInput] Clarification: TextInput - password vs secureTextEntry

### ISSUE THREAD

**Issue by mudetroit** [facebook/react-native#584]
The documentation does not make the difference in intent for these two props immediately obvious. Would probably be helpful information to include,.

**Comment by brentvatne** [comment]
@mudetroit - you're right - I believe we should eliminate one of the two. It seems like the reason for it is that on Android the `password` prop is used and on iOS `secureTextEntry` is used, but both props are accepted regardless. 

@vjeux - if there's any interest, I can submit a PR for this

**Comment by vjeux** [comment]
If both props are doing the same thing, we should probably only have one and use the web naming convention.

**Comment by robtg4** [comment]
But what if you want to show a defaultvalue for a password textinput - like an indicator of what text should go there? password={true} makes that text hashed - prohibiting the developer to put a placeholder that isn't hashed

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/textinput-clarification-textinput-password-vs-securetextentry

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
