### ISSUE TITLE
Alert should be implemented as a component, rather than an imperative API.

### ISSUE THREAD

**Issue by nicklockwood** [facebook/react-native#5840]
To display an alert, you should be able to render something like:

    <Alert title="Error" message="Something happened">
        <Alert.Button title="OK" onPress={() => { ... }}/>
        <Alert.Button title="Cancel" type="cancel"/>
    </Alert>

A login field could be implemented using:

     <Alert title="Error" message="Something happened">
        <TextInput ref="username" placeholder="Username">
        <TextInput ref="password" placeholder="Password" secureTextEntry={true}>
        <Alert.Button title="Login" onPress={() => {
            this.submitForm(this.refs.username, this.refs.password);
        }}/>
        <Alert.Button title="Cancel" type="cancel"/>
    </Alert>

We could also merge this with the ActionSheet API on iOS, so an action sheet could be displayed with:

    <Alert title="Are you sure?" type ="action-sheet">
        <Alert.Button title="Send" onPress={() => { ... }}/>
        <Alert.Button title="Cancel" type="cancel"/>
        <Alert.Button title="Delete" type="destructive" onPress={() => { ... }}/>
    </Alert>

Alerts would stack so if there were two rendered, the frontmost one would be shown, and when it was dismissed, the next one would appear.

Existing Alert APIs could be kept as static functions on the new component (so `Alert.alert(title, message, etc)` would still work), both for backwards compatibility, convenience, and to support the global `alert(...)` polyfill.

I'm putting this here mostly to document the thinking. I may have a stab at implementing this myself at some point if nobody else wants to, but I don't have time right now. I'm hoping this might pique @janicduplessis's interest :-)

**Comment by janicduplessis** [comment]
Good write-up! I guess this component would wrap the native imperative Alert and ActionSheet API. What do you think about using a prop vs mounting/unmounting the component to show/hide it?

Something like:
``` js
<Alert opened={this.state.alert1Opened}>
  ...
</Alert>
```
opened? shown? displayed?

We'd also have to add some validation to make sure what is inside the Alert is valid considering the limitations of the underlying native API.

I'd definitely like to work on this when I get some time. I'll start a WIP PR when I get something working :)

**Comment by nicklockwood** [comment]
> I guess this component would wrap the native imperative Alert and ActionSheet API. 

Yes, at least in the first iteration. I can imagine that we might be able to build a better native API once we eventually drop support for some of the imperative features though.

> What do you think about using a prop vs mounting/unmounting the component to show/hide it?

Having hidden/visible state on the StatusBar makes sense when the StatusBar is visible by default, so absence of StatusBar can't easily hide be the cue to hide it.

But with an alert, it's not visible by default, so rendering it every time and then showing/hiding it seems like it's making extra work for the resolver without much benefit.

The only strong reason I can think of for doing it is that if it suddenly disappeared from the hierarchy, the resolver would re-render all the subsequent components because it wouldn't realise that they hadn't changed. That would be a concern, but perhaps we can solve it another way? Otherwise maybe we can just document that alerts should appear last in your view hierarchy.

Did you have another reason for wanting to implement it this way?

**Comment by satya164** [comment]
Would be perfect. One doubt, on Android, Alert can be dismissed with back button/clicking outside, not sure how to handle it. Maybe provide a callback like `onDismissAttempt` or something, and then do a `setState` to dismiss it when it gets called? Not sure.

**Comment by nicklockwood** [comment]
@satya164 hmm, that's an interesting point. On iOS you can't actually stop it from being closed either - only react to the button press. I guess we could work around that by simply re-showing it if we want it to be a controlled component. It's worth thinking about though.

**Comment by janicduplessis** [comment]
@nicklockwood I don't really mind one or the other, I just prefer not having to write a bunch of conditionals in a page that has multiple different alerts that can be shown but if there is any perf concert I would go with what is the best there.
``` js
<View>
  <Alert opened={this.state.alert1Opened}>
    ...
  </Alert>
  <Alert opened={this.state.alert2Opened}>
    ...
  </Alert>
</View>
```
vs
``` js
<View>
  {
    this.state.alert1Opened &&
    <Alert>
      ...
    </Alert>
  }
  {
    this.state.alert2Opened &&
    <Alert>
      ...
    </Alert>
  }
</View>
```

**Comment by geof90** [comment]
It would be cool to be able to toggle the behaviour of being able to dismiss the alert with the back button or clicking outside. In android, there is the native API `AlertDialog.Builder.setCancelable(true/false)`. On iOS, from my understanding, the alert is not dismissible by touching outside by default.

**Comment by Bhullnatik** [comment]
Isn't that weird to treat Alerts as 'view'/component when none of the native platforms do so?

To me they represent more a response from the app to an event, rather than a view being present at all time. I understand that an alert may never be shown so it's not really visible, but even the fact that it would be in the `render` function with other components feel strange.

**Comment by satya164** [comment]
@geof90 Making it a controlled component will make that possible. For example, it might notify you of clicking on outside, and you can emit a `setState` to dismiss it, or don't do anything to prevent it from being dismissed.

@Bhullnatik 

> Isn't that weird to treat Alerts as 'view'/component when none of the native platforms do so?

Well, I'd say it shouldn't matter how they are natively represented if we could build a nice reactive API on top of it. For example the DOM API sucks, and if React were to use the same APIs, it'll be a nightmare.

Making it a controlled component instead of a stateful API will have many benefits, for example you can store the state in a global store/component state, and hence looking at the state and props, you can predict how the final result will look like, which is what makes react so much better.

**Comment by satya164** [comment]
> On iOS you can't actually stop it from being closed either - only react to the button press. I guess we could work around that by simply re-showing it if we want it to be a controlled component.

Ah, it sucks. The solution sounds like a reasonable compromise.

**Comment by Bhullnatik** [comment]
@satya164 Fair enough. I can see your point where it's more predictable, but I'm not sure if I agree with it since it seems like a tradeoff in readability/comprehensiveness (in my opinion). I started working with React-native not so long ago and never tried React, so I'm not really familiar with the React-way of doing things.

If possible, keeping the old API would be great so that people can choose to use the API the way they are more comfortable with.

**Comment by janicduplessis** [comment]
As @nicklockwood stated in the initial post the old API will stay as static functions of the component. I think it is useful for simple use cases of just showing a message to the user but for more complex alerts like ActionSheet or alerts with inputs the component will be a better solution.

**Comment by julianocomg** [comment]
How about show/dismiss the alert using a component method like `this.refs.alert.show()`

It seems to be more performatic...

**Comment by satya164** [comment]
@julianocomg Still not a declarative API.

**Comment by grabbou** [comment]
> Making it a controlled component instead of a stateful API will have many benefits, for example you can store the state in a global store/component state, and hence looking at the state and props, you can predict how the final result will look like, which is what makes react so much better.

Although I get the benefits, it seems to me that in case of failed API calls, I still prefer just Alert.show() instead of calling setState & putting that in render() body.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/alert-should-be-implemented-as-a-component-rather-than-an-imperative-api

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by leecade** [comment]
This makes sense, only a `<Alert />` component is used in Redux way

**Comment by AbhijithRobosoft** [comment]
Should i import Alert from react native?
"<Alert></Alert>"
