### ISSUE TITLE
When I try to run "react-native init AwesomeProject" I am getting ETIMEDOUT.

### ISSUE THREAD

**Issue by rushabh1191** [facebook/react-native#5872]
macbook:~ rushabh$ react-native init AwesomeProject
This will walk you through creating a new React Native project in /Users/rushabh/AwesomeProject
Installing react-native package from npm...

npm ERR! Darwin 15.2.0
npm ERR! argv "/Users/rushabh/.nvm/versions/node/v5.6.0/bin/node" "/Users/rushabh/.nvm/versions/node/v5.6.0/bin/npm" "install" "--save" "react-native"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT 103.245.222.162:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rushabh/AwesomeProject/npm-debug.log

`npm install --save react-native` failed

Node and nvm both are latest,I am on stable internet connection.I dont know what is the issue. I checked everywhere but no solution. Please help.

**Comment by mkonicek** [comment]
Looks like an npm config issue, try running `npm config list`.

**Comment by mkonicek** [comment]
There's an awesome place to post code / ask question first before filing an issue: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see and answer your question. This lets us use the github bug tracker for bugs.

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)
