### ISSUE TITLE
[AlertIOS] collision with other animated native components

### ISSUE THREAD

**Issue by yelled3** [facebook/react-native#5892]
`AlertIOS` is using `presentViewController` with animation:

```obj-c
[presentingController presentViewController:alertController animated:YES completion:nil]; 
```
```obj-c
[alertController.presentingViewController dismissViewControllerAnimated:YES completion:nil];
``` 
see: https://github.com/facebook/react-native/blob/master/React/Modules/RCTAlertManager.m#L236

as you can see, there's a `completion` callback which isn't used at all.
I've encountered several instances where I needed to wait for the alert to close before calling another component which also used `presentViewController` with animation.

this is an issue with all components who are using default viewcontroller animatons;
when you dismiss component `A` and the present component `B` - 
`B` needs to wait for `A`'s animation to end. if not, `B` may not be presented at all.

IMO, there are 2 directions we can take here:
* expose the `completion` callback to the client
* rewrite `Alert` in JS and manage this issue using `Animated`

Thoughts?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/alertios-collision-with-other-animated-native-components

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
