### ISSUE TITLE
StatusBar API instead of component or both

### ISSUE THREAD

**Issue by CentaurWarchief** [facebook/react-native#5909]
I think that would be much more useful to manage the system status bar using an API instead of a component. I know that I can consume `NativeModules.StatusBarManager` directly in the same way that `StatusBar` component does, but will be unpredictable to API changes.

Plus, I think that with an API will be more easy for certain types of task such as changing the color while scrolling &mdash; currently you need to call setState and manage it from there.

What do you guys think? I can submit a PR implementing such API without introducing a BC in the current component.

/cc @julianocomg

**Comment by julianocomg** [comment]
:+1:

**Comment by gre** [comment]
:-1: for the idea to remove this new Component. I like the fact the new StatusBar is contextualized to a scene/screen instead of being an imperative API.
Also it forces you to express this as a state (e.g to put on the root component or in a store) and it's not a bad thing (instead of imperatively calling this from somewhere).

Why not directly using StatusBarManager.setColor if you really need to use it?

**Comment by CentaurWarchief** [comment]
@gre because I have to do it through `NativeModules`. What if the internal Java API changes? It's much more safer relying in a native JS API which will be always aligned to its underlying implementation.

And yes, it's a bad thing &mdash; take the scroll example... you'll have to call setState for each movement which IS a bad thing and there are also many others use cases which you'd prefer to handle it via the so-called imperative API.

**Comment by janicduplessis** [comment]
@CentaurWarchief I'm fine with adding static methods to the component to use it imperatively I can see the use cases there. You could add all the functions from `StatusBarIOS` + the new ones for Android.

cc @nicklockwood

**Comment by nicklockwood** [comment]
Yep, exposing as static methods on StatusBar component makes sense.

I'm not sure exactly how calling those static methods should affect the stack, but I guess the state should just be overridden on the next re-render?

**Comment by janicduplessis** [comment]
The static API could affect the default values of the stack so that changes done using it don't get overriden by default values on the next render. This would allow using the component for controlling certain properties and the static API for others. Using the component and the static API for the same prop will cause the component to override whatever value the static API set in the next render.

**Comment by janicduplessis** [comment]
This would require refactoring https://github.com/facebook/react-native/blob/master/Libraries/Components/StatusBar/StatusBar.js#L29 a bit to accept the default values as an argument and saving the current default values somewhere.

**Comment by CentaurWarchief** [comment]
@janicduplessis 

Yeah you're right. That's why I think that we should have it. We can't have the luxury of setting state just to change the bar color. There are many people that keep a complex view hierarchy and you can't simply `setState` every time because it could lead to a performance bottleneck.

**Comment by janicduplessis** [comment]
You can submit a PR if you'd like or I can look at this next week.

**Comment by satya164** [comment]
This is fixed.
