### ISSUE TITLE
support resolve.alias ala webpack

### ISSUE THREAD

**Issue by jacobrosenthal** [facebook/react-native#5917]
The big feature still missing from react packager is the ability to shim one module for another. You might know this in browserify as transforms. I was previously using react-native-webpack-server but that appears to be dying out so Im hoping to track support for this here.

**Comment by satya164** [comment]
cc @martinbigio

**Comment by grabbou** [comment]
Does this solve your issue by any chance? https://medium.com/@grabbou/a-cure-for-relative-requires-in-react-native-2b263cecf0f6

**Comment by jacobrosenthal** [comment]
Sadly not. What resolve.alias does is find all packages that, say, require('noble') and swap out that dependency for another, say react-native-ble. In this way we can shim existing api surfaces which already have an ecosystem built on top of them, and bring all that with us to react native.

**Comment by martinbigio** [comment]
I can see how this could be useful for the community but I think we want to be very cautious with the API call we add. @jacobrosenthal would be great if you could give a couple of examples and post on product pains to get a sense of how many people would love to have this.

cc @cpojer

**Comment by vespakoen** [comment]
This is fixed now that react-native supports the "browser" and "react-native" field (that works as the "browser" field but gets precedence)

https://github.com/defunctzombie/package-browser-field-spec

**Comment by jacobrosenthal** [comment]
Amazing, Ill check soon. What version was that support added?

**Comment by cpojer** [comment]
I'd be happy to support this inside of node-haste, see https://github.com/facebook/node-haste – once we have that, we can integrate it both into Jest and packager. Does anyone want to work on sending a PR for node-haste? :)

**Comment by vespakoen** [comment]
It is already in node-haste! (I think this got added in version 0.20, was still in react-native back then)

https://github.com/facebook/node-haste/blob/master/src/Package.js#L94

Btw, if you like even more browserify compatibility, support / improve my PR:

https://github.com/facebook/node-haste/pull/46

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/support-resolvealias-ala-webpack

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by sanketsahusoft** [comment]
It works well with this .babelrc plugin:
https://reactnatve.wordpress.com/2016/06/16/alias-in-react-native/
