### ISSUE TITLE
Animated.spring & PanResponder stopAnimation calls with 0 and doesn't stop animation

### ISSUE THREAD

**Issue by johannesspohr** [facebook/react-native#5926]
I'm implementing a swipe pager with a combination of PanResponder and Animated.spring.

```javascript
            onPanResponderGrant: () => {
                this.state.panOffset.stopAnimation((latestValue)=> {
                    console.log("picked up with ", latestValue)
                    pickupOffset = latestValue;
                    this.state.panOffset.setOffset(latestValue); // offset the whole movement by the current location
                    this.state.panOffset.setValue(0)
                });
            },
            onPanResponderMove: Animated.event([
                null,
                {dx: this.state.panOffset}, // map the pan x to the panOffset
            ]),
            onPanResponderRelease: onPanResponderRelease,
```

Release:

```javascript
                Animated.spring(
                    this.state.panOffset,
                    {
                        toValue: Math.sign(pageChangeIndicator) * this.state.containerWidth, ...this.springSettings,
                        velocity: gestureState.vx
                    }
                ).start((finished) => {
                    console.log("finished ", finished);
                    if (finished) {
                        // update current page, set the pageOffset and reset the panOffset
                        this.setState({currentPage: this.state.currentPage - Math.sign(pageChangeIndicator)});
                        this.state.pageOffset.setValue(-this.state.currentPage * this.state.containerWidth)
                        this.state.panOffset.setValue(0);
                    }
                });
```

The moved View is translated by Animated.sum(state.pageOffset, state.panOffset).
It's basically working, but when panning, releasing and panning again during the animation, the callback of stopAnimation is often called with a value of 0 (which it obviously isn't) and the animation seems to continue after the second panning is done (with weird offset). Am I doing anything wrong or should the code work?

BTW: Happening on Android 5 in Genymotion and on actual device. React Native 0.19 and 0.20 rc1 tested.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/animatedspring-panresponder-stopanimation-calls-with-0-and-doesnt-stop-animation

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
