### ISSUE TITLE
I recently(12 days ago) made a pull request to add Caratlane to showcase and it was successfully merged. 2-3 days ago our company name 'Caratlane' was visible in showcase but now its not visible. Can anyone plz check out this issue??

### ISSUE THREAD

**Issue by anishakd4** [facebook/react-native#5927]
Merge pull request #5709 from anishakd4/feature/CaratLaneAppShowcase

https://github.com/facebook/react-native/commit/656e992fa60eb9ca0cf429cca8346fed99af9f16

**Comment by grabbou** [comment]
Hey,

Docs are synced up with React Native versions, by default it loads the ones for the most recent stable version (0.19 in this case). 

Since your commit has been merged for the 0.20, it's for now here http://facebook.github.io/react-native/releases/0.20/showcase.html and will become visible in stable section pretty soon.
