### ISSUE TITLE
ViewPagerAndroid lock scroll

### ISSUE THREAD

**Issue by kevinejohn** [facebook/react-native#5949]
ViewPagerAndroid should have a prop that allows us to disable or lock the scrolling ability.

**Comment by AbilashK** [comment]
@kevinejohn @christopherdro I have the same requirement, would love to submit a PR if it's alright

**Comment by kevinejohn** [comment]
@AbilashK I started a pull request for this already. Would love improvements and feedback

https://github.com/facebook/react-native/pull/5968

**Comment by AbilashK** [comment]
@kevinejohn I had a look at your PR, can we discuss on discord when you are available?

**Comment by kevinejohn** [comment]
@AbilashK yeah if you want. How does that work? I use the same username

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/viewpagerandroid-lock-scroll

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
