### ISSUE TITLE
TouchableWithoutFeedback and Image don't get along well on Android

### ISSUE THREAD

**Issue by javierM84** [facebook/react-native#5979]
In the project I am working I have a TouchableWithoutFeedback component wrapping an Image like you can see in the code below:

```
    < TouchableWithoutFeedback onPress={() => alert('hello')}>
        <Image source={{uri: image, scale: 1}}>
            ...
        </Image>
    </TouchableWithoutFeedback >
```

On Android the onPress function event doesn't get called for some strange reason. This has been found in React Native 0.19, maybe in 0.20 there is already a fix.

Image the background of a row and it works fine on iOS.

**Comment by mkonicek** [comment]
Is this specific to `Image`?

**Comment by javierM84** [comment]
Not sure if it is just for Image or there might be other components having this issue I will test it later.

**Comment by mkonicek** [comment]
Just tried it and it works fine:

<img width="457" alt="screen shot 2016-02-21 at 10 01 18 am" src="https://cloud.githubusercontent.com/assets/346214/13204326/18110544-d882-11e5-872b-cb2d9617c7cb.png">

Note that you have to give an image dimensions, otherwise it won't render anything. Also, what are the `...` inside `Image`? Don't think you can put other components inside an `Image`:

    <TouchableWithoutFeedback onPress={() => alert('hello')}>
          <Image style={{width: 300, height: 300}} source={{uri: 'http://www.mtv.com/news/wp-content/uploads/movies/2012/11/21AndOver_Baner.jpg', scale: 1}}>
          </Image>
        </TouchableWithoutFeedback >

**Comment by mkonicek** [comment]
Can you please ask on StackOverflow, e.g. "How to use onPress with an Image on Android" rather than filing a bug?
