### ISSUE TITLE
packager assume that every method named require is module loader function

### ISSUE THREAD

**Issue by gorangajic** [facebook/react-native#5988]
I have tried to use `primus.io` with `react-native` and they are using Primus.require method wrapper so same lib can work in browser and in node.js. Packager throw error that was not able to find stream module but they have try/catch there with a fallback when stream module is not found. So packager should not preload that script and throw error

```
Unable to resolve module stream
```

There is a workaround and I have already created pull request there so it's not that urgent https://github.com/primus/primus/pull/432 

sorry if there is same issue already but was not able to find any.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/packager-assume-that-every-method-named-require-is-module-loader-function

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
