### ISSUE TITLE
[Android] Hidden <StatusBar> reappears after screen lock

### ISSUE THREAD

**Issue by marcshilling** [facebook/react-native#5991]
I'm trying out the new cross-platform StatusBar component. One thing I noticed is that if I lock my Android phone screen on a view with `<StatusBar hidden={true} />`, the status bar is visible again upon unlocking the phone.

**Comment by janicduplessis** [comment]
Thanks for reporting this I'll look into it :)

**Comment by charpeni** [comment]
@janicduplessis I just tried this cf3bd9f on branch `0.22-stable` and `master`, it doesn't seem to work.

```javascript
class AwesomeProject extends Component {
  render() {
    return (
      <View style={styles.container}>
        <StatusBar
          hidden
        />
        <TextInput/>
      </View>
    );
  }
}
```

Tested on Android 5.

1. Open the app. (StatusBar is hidden)
2. Minimize the app.
3. Reopen the app. (StatusBar is visible)

There seems to have an issue with focus on native components, maybe your fix should fixed it ? #6503 & http://stackoverflow.com/questions/36061617/reactnative-status-bar-disable-android

**Comment by marcshilling** [comment]
@charpeni is that code valid? You aren't passing anything to `hidden`

**Comment by charpeni** [comment]
@marcshilling It's a valid code, we can omit the value of the prop when it is explicitly `true`.

**Comment by TeodorKolev** [comment]
Why this issue is closed when problem still exist?

**Comment by janicduplessis** [comment]
@charpeni Have you rebuilt the native code? I just tested the steps you described using 0.22.0-rc4 from npm in one of my apps and it worked.

**Comment by TeodorKolev** [comment]
I have same issue, on every event soft keyboard open back button pressed etc. status bar showed up

**Comment by janicduplessis** [comment]
Are you on 0.22?

**Comment by TeodorKolev** [comment]
0.21

**Comment by janicduplessis** [comment]
Ok, this is normal the issue was fixed only in 0.22. Can you try with 0.22.0-rc4?

**Comment by TeodorKolev** [comment]
how to get that?

**Comment by janicduplessis** [comment]
npm install --save react-native@0.22.0-rc4

**Comment by TeodorKolev** [comment]
is there any chance that can break my app? Thanks btw

**Comment by janicduplessis** [comment]
0.22.0 will be released this monday so the rc build is pretty stable at this point.

**Comment by TeodorKolev** [comment]
Thanks a lot man. Respect!

**Comment by charpeni** [comment]
> @charpeni Have you rebuilt the native code? I just tested the steps you described using 0.22.0-rc4 from npm in one of my apps and it worked.

@janicduplessis Yes, I made a new application with `react-native init`, clone repo on branch `0.22-stable`, `react-native upgrade` and `react-native run-android`.

From `node_modules/ReactAndroid/src/main/java/com/facebook/react/modules/statusbar/StatusBarModule.java` I can see your fix.

Did it work for you @TeodorKolev ?

**Comment by janicduplessis** [comment]
Can you try 0.22.0-rc4 from npm? I think cloning the branch won't work properly unless you change your build.gradle to compile react-native from node_modules instead of using the version from maven (which is still 0.21 since 0.22.0 is using a prebuilt version distributed by npm instead of maven)

You can check http://facebook.github.io/react-native/docs/android-building-from-source.html#content to build it from source properly.

**Comment by charpeni** [comment]
I can't retry with 0.22.0-rc4 from npm right now because I have this strange error #6446.

I think you're totally right about the prebuilt version distributed by npm, I was blinded by `compile "com.facebook.react:react-native:+" // From node_modules`.

Actually, if you say it works I totally believe in your work. Nice job by the way! :
