### ISSUE TITLE
Clicking AlertIOS's button would trigger the button underneath

### ISSUE THREAD

**Issue by leijing7** [facebook/react-native#6047]
Please see the below screenshot.
![simulator screen shot 20 feb 2016 7 56 18 pm](https://cloud.githubusercontent.com/assets/2281763/13196575/ac9e1d6c-d80c-11e5-8114-7f8992843ba2.png)

The green button is a TouchableWithoutFeedback element. If I click the OK button to make the alert disappear, the green button would be pressed sometimes. Not always, but most of time. I think it depends where you pressed it, especially the overlay part of the two buttons.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/clicking-alertioss-button-would-trigger-the-button-underneath

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
