### ISSUE TITLE
The gesture responder system seems cannot detect certain touch area of view it apply to.

### ISSUE THREAD

**Issue by alrightlook** [facebook/react-native#6049]
Hi, There.
When I was trying to make a circle shaped button component with React Native. I set the borderRadius of an Image half the value of its height and width to make it looks like the circle button and apply gesture responder to it.As a result when i tapped outside the circle but inside some rectangular area around the Image view, the responder event dispatched which is unexpected.

I just cannot figure it out:
- Is there any possibility to determine the touch area of Touchable* and how?
- Does the gesture responder system support certain area gesture detection?
Any help would be appreciated!

**Comment by mkonicek** [comment]
Hey @alrightlook, we need a code sample to be able to better understand the issue.

I have a question for you. Did you see the [New Issue Guidelines](https://github.com/facebook/react-native/blob/master/ISSUE_TEMPLATE.md) when creating this issue? Is there anything we could improve there? Is the text too long or unclear for example?

**Comment by mkonicek** [comment]
I don't know the answer to this one but there's an awesome place to ask questions: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see and answer your question. This lets us use the GitHub bug tracker for bugs.

I'm posting this here because GitHub issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)

Closing as this really is a question that should be asked on StackOverflow.

**Comment by mkonicek** [comment]
Making a circular image button is a very good question actually. I'm interested in the answer myself. Can you add the Stack Overflow link here once you post there please?

**Comment by alrightlook** [comment]
Hi, @mkonicek Thanks for your reply. I`ve already know how to get information on this question now.

**Comment by alrightlook** [comment]
Hi, @mkonicek  as request below is the link I post on stackoverflow 

[StackOverflow link about this question](http://stackoverflow.com/questions/35572084/how-to-realize-a-circle-image-button-with-react-native)
