### ISSUE TITLE
async / await debug in chrome

### ISSUE THREAD

**Issue by jaynsw** [facebook/react-native#6056]
after changing the promise to async await, I found debugging in chrome is impossible.  Is there any plan to fix this in the near future or should I switch back to promise ?

**Comment by mkonicek** [comment]
Hey @jaynsw, in order to be able to help you with this issue you need to provide some code samples. What doesn't work exactly? Where did you put the breakpoint?

I have a question for you. Did you see the [New Issue Guidelines](https://github.com/facebook/react-native/blob/master/ISSUE_TEMPLATE.md) when creating this issue? Is there anything we could improve there? Is the text too long or unclear for example?

**Comment by mkonicek** [comment]
I'll close this until there's more information with clear repro steps. We can reopen then.

**Comment by Somojojojo** [comment]
I'll post my experience here, since the OP hasn't responded yet.

Debugging async/await in chrome is extremely difficult. Maybe because of my inexperience with the inner workings of how it works, I'm not sure. But when you have code like so:
```javascript
1. let response = await getSomethingFromTheNetwork();
2. let bar = response.foo;
3. doSomethingWithFoobar(bar);
```

In Chrome if I place a breakpoint at line 2, the debugger will pause the application on that line and `response` will be undefined. Obviously this is not desirable behaviour, and you'd expect response to have been resolved by the time the debugger breaks at line 2.

Does this make sense?

**Comment by jaynsw** [comment]
I have changed back all of my code to promise then and catch.

**Comment by mkonicek** [comment]
Thanks for the example @Somojojojo! Any idea how to make Chrome show you the value of `response`?

**Comment by Somojojojo** [comment]
Besides using the console JS API I haven't found a solid way of getting those values.
I haven't read into how React is managing the Chrome debug session at all, and I haven't had any experience managing it myself. At a high level, I would say you could defer breakpoints inside an async function the same way you defer code execution. As code execution progresses in an async function, you would execute breakpoints belonging to that call. In theory that would keep the debugger and the async function state synchronized. This is assuming you have power over if/when breakpoints are executed.

Again, as I have no idea how React is managing the debug session, my explanation likely sounds silly or obvious – but maybe it will give someone a good idea on how to solve this.

**Comment by mkonicek** [comment]
This looks like a feature request and I'm not sure anyone on the team has bandwidth to look into it. Let's vote on it on Product Pains (voting is not possible on GitHub) so we see how high-priority this is.

**Comment by mkonicek** [comment]
@facebook-github-bot feature

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/async-await-debug-in-chrome

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by mikecg** [comment]
@mkonicek Hello... has this feature been implemented? If not, is there a workaround?

**Comment by mikecg** [comment]
@Somojojojo I know this thread is old but I am having a similar experience. Are you still using react native and seeing the same difficult async/await debugging experience in Chrome? If so, did you come up with a better workaround for debugging?

**Comment by lhrolim** [comment]
I'm still experiencing that using RN 0.55.4

Are there any workarounds available?

**Comment by kelset** [comment]
Ok it looks like the chromium bug is still there, so there isn't much we can do about it for now AFAIK.

Still, let's reopen this.

**Comment by cpojer** [comment]
Since this is not actionable in the RN repo and an issue with Chromium, let's close this issue here since we can't do anything about it.
