### ISSUE TITLE
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found

### ISSUE THREAD

**Issue by cengYe** [facebook/react-native#6058]
When I'm using the fetch function in my react native apps send https request, gives an error in android. The error is 'TypeError: Network request failed'. Doing a bit of debugging, I found that the cause of the error seems to be the following: 'java.security.cert.CertPathValidatorException: Trust anchor for certification path not found'.
please help me,I was blocked for many days, the development can't proceed!

**Comment by Kureev** [comment]
Sounds like a problem with certificate: http://stackoverflow.com/questions/25122287/java-security-cert-certpathvalidatorexception-trust-anchor-for-certification-pa

**Comment by srikanthkh** [comment]
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found'.
Having the same issue when using https:// fetch / xmlhttprequests. Please look in to this.

**Comment by impuulse** [comment]
+

**Comment by ianakiara** [comment]
+1

**Comment by leledumbo549** [comment]
+1

**Comment by johnwei-git** [comment]
+1

**Comment by ide** [comment]
Are your certs valid? Can you post links to the HTTPS endpoints here so that we can see the cert chain?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/javasecuritycertcertpathvalidatorexception-trust-anchor-for-certification-path-not-found

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by onrige** [comment]
I am also have this problem. Maybe someone have a workaround or any updates on this?

**Comment by manit77** [comment]
you have a circular reference :)it's closed here but your link says go to here. https://react-native.canny.io/feature-requests/p/javasecuritycertcertpathvalidatorexception-trust-anchor-for-certification-path-not-found
