### ISSUE TITLE
WebView load  file 

### ISSUE THREAD

**Issue by jiangqqlmj** [facebook/react-native#6059]
Now this  i have a file  eg:'hello.html'  ,i want to load this file from webview.so there is a good case?

**Comment by dsibiski** [comment]
You can use the `source` prop on WebView: http://facebook.github.io/react-native/docs/webview.html#source

**Comment by mkonicek** [comment]
Hey and thanks for posting this!

There's an awesome place to post code / ask question first before filing an issue: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see and answer your question. This lets us use the github bug tracker for bugs.

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)

**Comment by mkonicek** [comment]
Closing this as it's a question rather than a bug and questions should be asked on StackOverflow.

@jiangqqlmj I have meta question. Did you see the [New Issue Guidelines](https://github.com/facebook/react-native/blob/master/ISSUE_TEMPLATE.md) when creating this issue? Is there anything we could improve there? Is the text too long or unclear for example?
