### ISSUE TITLE
how to module know app in backgroud or not. (Java android)

### ISSUE THREAD

**Issue by InnerPeace080** [facebook/react-native#6062]
i write a module for react-native.
i want my module do something when app go into background.

anybody know how to register a listener (onPause, on Resume event) in class extend from  SimpleViewManager and implements  from ReactContextBaseJavaModule

**Comment by Kureev** [comment]
Are you looking for something [like this](https://facebook.github.io/react-native/docs/appstateios.html)?

**Comment by mkonicek** [comment]
Hey and thanks for posting this!

There's an awesome place to post code / ask questions: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see and answer your question. This lets us use the github bug tracker for bugs.

I'm posting this here because GitHub issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)

**Comment by mkonicek** [comment]
Closing this as it's a question and questions should be asked on StackOverflow.

@InnerPeace080 I have a question for you. Did you see the [New Issue Guidelines](https://github.com/facebook/react-native/blob/master/ISSUE_TEMPLATE.md) when creating this issue? Is there anything we could improve there? Is the text too long or unclear for example?

**Comment by InnerPeace080** [comment]
thanks for your answer. my apologize.  But some time i post my question on StackOverflow and i didn't get useful answer. so sad. 

@Kureev :thank for your answer but i want do this in native side (java on android), not javascript size, because i want stop a service in native side.

**Comment by Kureev** [comment]
@InnerPeace080 I'm not that familiar with the native part, sorry. I hope you'll get an answer on StackOverflow soon. You can also try to ask this question on react-native Discord channel for a better real-time experience :wink:
