### ISSUE TITLE
Annotation View styles are an array- Map view

### ISSUE THREAD

**Issue by melbourne2991** [facebook/react-native#6066]
Please see:
https://github.com/facebook/react-native/blob/master/Libraries/Components/MapView/MapView.js#L341

The annotation view is being passed an array as its style prop, with the first item being a digit as opposed to an object because it is referencing the stylesheet.
```
children.push(React.cloneElement(view, {
  style: [styles.annotationView, view.props.style || {}]
}));
```

Given I have:
```
<MapView 
  annotations={[
    view: (<MyCustomView style={{ backgroundColor: 'green' }}/>)
  ]}
}
```
this.props.style for` <MyCustomView/>` is actually an array (`[64, {backgroundColor: 'green'}]`), the first item actually being a number (because we're referencing a stylesheet object here as opposed to regular js object), the second item being the actual styles I supplied.

**Comment by mkonicek** [comment]
@melbourne2991 What reply do you expect on this issue? If it's a bug would you be up for sending a pull requests with a fix?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/annotation-view-styles-are-an-array-map-view

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
