### ISSUE TITLE
[StatusBarManager] Detect 'onPress' 

### ISSUE THREAD

**Issue by aleclarson** [facebook/react-native#6069]
I'm looking to modify `RCTStatusBarManager` so that I can detect `onPress`, `onPressIn`, and `onPressOut` events.

I *could* override `- (void) touchesBegan:(NSSet *)touches withEvent:(UIEvent *)event` in my `AppDelegate.m`, but I would rather do the detection in `RCTStatusBarManager` (perhaps taking advantage of `RCTTouchHandler` to do so).

Using React Native's iOS API, how can I observe touches in the status bar's area?

**Comment by mkonicek** [comment]
Hey and thanks for posting this!

This looks like an usage question. There's an awesome place to post code / ask question first before filing an issue: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see and answer your question. This lets us use the github bug tracker for bugs.

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)
