### ISSUE TITLE
[ReactNative Android] Can I loadScript from URL?

### ISSUE THREAD

**Issue by jqmobile** [facebook/react-native#6071]
I saw something about loadsrcipt in JSBundleLoader.java. There are two methods to load script, "bridge.loadScriptFromAssets" and "bridge.loadScriptFromFile".Can I load script from url which start with "http://"? For example, "bridge.loadScriptFromUrl".

**Comment by satya164** [comment]
@jqmobile You should load the script with `OkHttp` or `java.net.URL` and save it to the file system, which you can provide to `loadScriptFromFile`.

There's an awesome place to ask question like this one: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see your question, you can vote on answers and mark question as answered etc. This lets us keep a list of bug reports and feature requests on github and especially [Product Pains](https://productpains.com/product/react-native/?tab=top) (again, with voting which is really nice).

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)
