### ISSUE TITLE
'ToolBarAndroid' Component question: modify action styles

### ISSUE THREAD

**Issue by jiangqqlmj** [facebook/react-native#6073]
'ToolBarAndroid' Component question: modify actions  styles
now  i use 'ToolBarAndroid', then  how to modify actions title styles ?
eg:actions={[{title: 'Settings', icon: require('./icon_settings.png'), show: 'always'}]}
i want to set title's color 'red' ?

**Comment by Kureev** [comment]
According to the [official documentation](https://facebook.github.io/react-native/docs/toolbarandroid.html), you can use a `titleColor` property.

**Comment by Kureev** [comment]
For the future:

There's an awesome place to post code / ask question first before filing an issue: StackOverflow. It's the best system for Q&A. Many people from the community hang out there and will be able to see and answer your question. This lets us use the github bug tracker for bugs.

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)
