### ISSUE TITLE
Missed translateZ support?

### ISSUE THREAD

**Issue by aksonov** [facebook/react-native#6086]
I want to make 3D animations like shown here:
https://desandro.github.io/3dtransforms/examples/cube-02-show-sides.html

I've tried translate(0,0,100) but it doesn't work.

**Comment by satya164** [comment]
Hey and thanks for reporting this!

There's an awesome place to ask question like this one: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see your question, you can vote on answers and mark question as answered etc. This lets us keep a list of bug reports and feature requests on github and especially [Product Pains](https://productpains.com/product/react-native/?tab=top) (again, with voting which is really nice).

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)

**Comment by aksonov** [comment]
Nobody answered my question there. 

Pavel.

**Comment by satya164** [comment]
@aksonov Try asking in #reactiflux or discord channel may be?

**Comment by mdias** [comment]
This likely doesn't work because the translationZ property is ignored on Android. See [here](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/uimanager/BaseViewManager.java#L149).

The "perspective" property also isn't yet implemented even though there is a [pull request](https://github.com/facebook/react-native/pull/6926/files) to implement it for quiet some time now.
