### ISSUE TITLE
[Android][TextInput] Cannot stop Android from dismissing the keyboard

### ISSUE THREAD

**Issue by mpretty-homepass** [facebook/react-native#6098]
This is pretty much the same as https://github.com/facebook/react-native/issues/2129 which was resolved by implementing 'blurOnSubmit' for iOS. We should be able to do the same on Android by doing this http://stackoverflow.com/a/19617831 here https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactTextInputManager.java#L481.

I would have done the PR myself but I can't seem to get the UIExplorer project running for Android so wouldn't be able to add the example and test it...

**Comment by AbilashK** [comment]
@mpretty-homepass I managed to test the logic you specified and it works. I can do a PR if needed. Did you manage to get the UIExplorer example running? It was recently fixed

**Comment by mpretty-homepass** [comment]
@AbilashK Oh good to hear that it works; unfortunately I still can't run the UIExplorer project on the latest master - The Android project now builds but when I run 'npm start' it fails with this error:

```
Error: ENOENT: no such file or directory, open '{SNIP}/react-native/Examples/UIExplorer/UIExplorerListBase.js'
    at Error (native)
```

Feel free to do the PR, hopefully when I have more time in the future I can sort out why I can't run the UIExplorer example and be able to submit PRs again.

**Comment by christopherdro** [comment]
@AbilashK A PR would be great!
Could you also reference this issue? Thanks

**Comment by AbilashK** [comment]
@christopherdro Sure, will try to do the PR today

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/androidtextinput-cannot-stop-android-from-dismissing-the-keyboard

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
