### ISSUE TITLE
[iOS 8.1 + NetInfo] change event only triggered when offline -> online

### ISSUE THREAD

**Issue by skizzo** [facebook/react-native#6106]
Hi,
I just realized that the code snippet provided in the [React Native NetInfo docs](https://facebook.github.io/react-native/docs/netinfo.html) only works properly when i use the iOS 9 simulator, if I run it on the 8.1 simulator, the event for changing connectivity status only fires when isConnected turns from true to false. 
Using react-native 0.19.0 on a OSX Yosemite.

**Comment by mangogogos** [comment]
Hmm I would definitely categorize that as a bug but I would also argue that you should really only be listening for changes from offline to online anyways ideally. I can't speak to iOS, but for Android Google specifically recommends checking if the application is connected when you got to make a network request then adding a change listener if it is not so that you can handle the case where the user regains connection. Listening arbitrarily for changes (at least on Android) is kind of a battery waste. http://developer.android.com/training/monitoring-device-state/connectivity-monitoring.html

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/ios-81-netinfo-change-event-only-triggered-when-offline-online

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
