### ISSUE TITLE
How to add spaces in the app name?

### ISSUE THREAD

**Issue by ffxsam** [facebook/react-native#6115]
If I create a new app via `react-native init MyTestApp`, I wouldn't want the actual app name to be "MyTestApp," but rather "My Test App." When I go into Build Settings in Xcode and go to Packaging > Product Name, I can change it to "My Test App," but when I try to build the app, I get an error:

```
ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk/Developer/Library/Frameworks'
ld: file not found: /Users/samh/Library/Developer/Xcode/DerivedData/MyTestApp-aomfrqfmwrvikjdpidmyuvhkqdrg/Build/Products/Debug-iphonesimulator/MyTestApp.app/MyTestApp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This fails because the actual file being built is `Debug-iphonesimulator/My Test App.app/My Test App`. Am I doing something wrong here? Xcode is like a labyrinth of settings.

**Comment by anarchicknight** [comment]
To update the name shown on the home screen under the app icon you need to change the Bundle display name property in the info.plist file for the project in xcode.If it is not present then add a new key for it

**Comment by Kureev** [comment]
There's an awesome place to post code / ask question first before filing an issue: StackOverflow. It's the best system for Q&A. Many people from the community hang out there and will be able to see and answer your question. This lets us use the github bug tracker for bugs.

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)
