### ISSUE TITLE
[Android] Layout of a React Native component embedded in native

### ISSUE THREAD

**Issue by MartinLiG** [facebook/react-native#6121]
In this [doc](https://facebook.github.io/react-native/docs/communication-ios.html#content), there are detail instructions on how to layout a react native component embedded in native UIView. But it's only for iOS.
Is there similar method or property for an Android ReactRootView to adjust its size according to its content?

Thanks

**Comment by mkonicek** [comment]
Hey and thanks for posting this!

This looks like an usage question. There's an awesome place to post code / ask question first before filing an issue: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see and answer your question. This lets us use the github bug tracker for bugs.

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)

**Comment by hslls** [comment]
@MartinLiG did you find a solution?
