### ISSUE TITLE
RCTTest vendors FBSnapshotTestCase without namespacing it.

### ISSUE THREAD

**Issue by alloy** [facebook/react-native#6126]
This leads to issues when a user is also including FBSnapshotTestCase themselves. (Duplicate symbols in static libraries / undefined behaviour in dynamic libraries.)

You should probably re-namespace it or specify it as a dependency in e.g. the podspec and not use the vendored sources in that case.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/rcttest-vendors-fbsnapshottestcase-without-namespacing-it

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
