### ISSUE TITLE
Get reactTag on iOS

### ISSUE THREAD

**Issue by lucasfeliciano** [facebook/react-native#6142]
I'm trying to emit a event from the iOS code to javascript but it asks about the "target" in the NSDictionary.

I see that my class have `self.reactTag` when `UIView+React.h` is imported however when I try to set it into the dictionary  the value is `( no summary )`.
What am I doing wrong?

RCTScanditManager.m

```objectivec
#import "RCTScanditManager.h"
#import "UIView+React.h"
#import "RCTUIManager.h"

@implementation RCTScanditManager
RCT_EXPORT_MODULE();

@synthesize bridge = _bridge;

- (dispatch_queue_t)methodQueue
{
  return _bridge.uiManager.methodQueue;
}

- (UIView *)view
{
  RCTScandit *scandit = [[RCTScandit alloc] initWithEventDispatcher:self.bridge.eventDispatcher];
   
  return scandit;
}

@end
```

Here is how I'm trying to get the target on file RCTScandit.m
```objectivec
  NSArray *recognized = session.newlyRecognizedCodes;
  SBSCode *code = [recognized firstObject];
  
  NSDictionary *data = @{@"target": self.reactTag,
                         @"code": code.data
                         };
  
  [_eventDispatcher sendInputEventWithName:@"scan" body:data];
```

Thank you in advance :)

**Comment by Kureev** [comment]
There's an awesome place to post code / ask question first before filing an issue: [StackOverflow](http://stackoverflow.com/tags/react-native/). It's the best system for Q&A. Many people from the community hang out there and will be able to see and answer your question. This lets us use the github bug tracker for bugs.

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)
