### ISSUE TITLE
JSC profiler is not supported

### ISSUE THREAD

**Issue by L-Jovi** [facebook/react-native#6146]
hey, I have some trouble to run my project on iphone device.

it works fine in simulator, but when I test on device which version is `iOS9.2`, some info output in Xcode console

    JSC profiler is not supported

then wait a litter longer, red screen appearing that prompt me `Could not connect to development server`.

what should I do?

thanks for your time.

**Comment by Kureev** [comment]
Hey, you can check a similar issue https://github.com/facebook/react-native/issues/5199, but in short: it's something you can ignore. That's not a reason why you device run fails. Please, double-check that you're using an offline bundle or your IP address points to the correct location (not to the localhost).

**Comment by Kureev** [comment]
There's an awesome place to post code / ask question first before filing an issue: [StackOverflow](http://stackoverflow.com/tags/react-native/). It's the best system for Q&A. Many people from the community hang out there and will be able to see and answer your question. This lets us use the github bug tracker for bugs.

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)

**Comment by L-Jovi** [comment]
thanks for your answer, I'll try it on stackoverflow

**Comment by L-Jovi** [comment]
sorry to trouble, would you mind have a look [here](http://stackoverflow.com/questions/35626362/jsc-profiler-is-not-supported) on stackoverflow, I still have no idea now :(

**Comment by L-Jovi** [comment]
I find the reason, it's my carelessness caused.

my iphone change network Gateway so it could't access my js bundle ...

thanks for your help!
