### ISSUE TITLE
falcor not working with react-native and console does not receive any network messages

### ISSUE THREAD

**Issue by almasakchabayev** [facebook/react-native#6187]
falcor works in react-native as expected with a local cache, however when I add
```
source: new FalcorHttpDatasource('http://localhost:9090/model.json', {
    withCredentials: false,
    crossDomain: true
  }),
```
react-native shows `[object Object]` error. However exact same setup works in browser. Not sure what might be causing such behaviour. Also cannot debug it as react-native does not show response/request header errors.

More details can be found here
https://github.com/Netflix/falcor/issues/740

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/falcor-not-working-with-react-native-and-console-does-not-receive-any-network-messages

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
