### ISSUE TITLE
TextInput Position Inconsistency! 

### ISSUE THREAD

**Issue by aiflow** [facebook/react-native#6199]
Hi,

The TextInput seems to have different y-axis positions on API 19 and API 20+. 
It is fixed with adding some top/bottom margins (7.5) and some if statements,
but not the best solution. 

Thank You!

**Comment by jaredly** [comment]
I assume this is android? please include as much info as possible. what react native version are you using?

**Comment by DHidee66** [comment]
@jaredly Yes it is on Android and RN 0.20

**Comment by brentvatne** [comment]
@terribleben - I think this is where our css-reset type changes we did to the Exponent Android styles would be helpful.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/textinput-position-inconsistency-

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
