### ISSUE TITLE
Documentation site anchor links broken

### ISSUE THREAD

**Issue by danawoodman** [facebook/react-native#6216]
All the anchor links on the doc site link to the homepage and not the current page. 

Eg, on https://facebook.github.io/react-native/docs/network.html the link to WebSockets goes to https://facebook.github.io/react-native/#websocket instead of https://facebook.github.io/react-native/docs/network.html#websocket as you'd expect.

It seems the `<base>` tag is causing the links to go to the homepage instead of the current page. Here is a SO article on the issue: http://stackoverflow.com/questions/8108836/make-anchor-links-refer-to-the-current-page-when-using-base

**Comment by grabbou** [comment]
I think the issue is missing `docs/` prefix - we had few PR's adding them recently, so that might be the way to go. Not all pages have it though, so I think for better clarity it's just better to just leave the base.

However, I cannot see a broken link to WebSockets on the page you've linked (in fact - I can't see any link on that page), so would appreciate if you can share some examples (and ideally - send over a PR).

See this for reference:  #6173

**Comment by danawoodman** [comment]
It appears it was fixed in the last day or so. I verified the issue on multiple pages of the docs site, so it wasn't an isolated incident but glad it's fixed!
