### ISSUE TITLE
[Android] Support POST redirect for 307 and 308 responses

### ISSUE THREAD

**Issue by nowaits** [facebook/react-native#6222]
i notice react use okhttp, and okhttp not support auto POST redirect for 307, (https://github.com/square/okhttp/pull/1101). I want to know is there any other solution for this problem ?

**Comment by nowaits** [comment]
i just temporarily fixed with this solution:

insert follow code into com.facebook.react.modules.network.NetWorkingModule.java line 209

            // @Bugfix { support POST redirect
            if (response.code() == HTTP_TEMP_REDIRECT && follow_redirects && method.equalsIgnoreCase("POST")) {
              sendRequest(method, response.header("Location"), requestId, headers, data, useIncrementalUpdates, timeout);
              return;
            }
            // }
any guys have better solution ?

**Comment by grabbou** [comment]
I think all feature requests regarding that should be directly filled in square/okhttp repo, especially given the fact they already discussed that issue and agreed it's not spec compliant. 

CC: @mkonicek

**Comment by brentvatne** [comment]
@nowaits - If we add this behaviour, we need to support the same thing on iOS.

- If you want to submit a pull request to solve this on iOS and Android that would be appreciated, and we can discuss there.
- Otherwise I have created a ProductPains issue for this, so people can indicate whether or not this is a large pain for them: https://productpains.com/post/react-native/support-post-redirect-for-307-and-308-responses/
