### ISSUE TITLE
RCTWebSocketModule.connect was called with 2 arguments, but expects 4

### ISSUE THREAD

**Issue by wheatma** [facebook/react-native#6225]
Hi, I have built my project  and run it on my ios device, the app loads  js from the pre-bundled file on disk

   `jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];`

i don't change any original code of react native but i got the error blow 

![image](https://cloud.githubusercontent.com/assets/5194746/13423942/e21fe320-dfd8-11e5-831a-95257249f2b1.png)

package version:
react-native: 0.20.0
babel: 6.5.2

however, it runs successfully on the simulators with js loads from development server
`jsCodeLocation = [NSURL URLWithString:@"http://myIP:8081/index.ios.bundle?platform=ios&dev=true"];`

OR

`jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle?platform=ios&dev=true"];`

**Comment by wheatma** [comment]
in addition, it runs successfully on the simulators

**Comment by wheatma** [comment]
reinstall the packages and the preblem solved

**Comment by plrthink** [comment]
@wheatma How do you reinstall the packages? Remove node_modules and re-run `npm install`? This doesn't work for me.

**Comment by kushal** [comment]
I'm also seeing this on a fresh install and am unclear on what packages I could reinstall to fix this.

**Comment by bradhanebury** [comment]
Also seeing this after deleting entire node_modules directory and running npm install

**Comment by kushal** [comment]
It turned out I was seeing this error because I had a running packager for a different app already running. Closing that terminal session and running again fixed this. The clues were not seeing the packager start and an error that the application couldn't be found in the Xcode console. That said, it'd be great to get a better error message, especially since it purports to tell me why I'm seeing this error but is wrong. :)

**Comment by plrthink** [comment]
any updates? still have this issue.

**Comment by plrthink** [comment]
finally I solve this problem. my issue is not have ref to main.jsbundle in xcode project.;)

**Comment by joshuapinter** [comment]
I'm getting this issue and removing `node_modules` directory and running `npm install` doesn't do the trick.

**Comment by DarkTemple** [comment]
I was seeing this error when integrate  RN with existing apps. Because my native code depend RN version 0.19, but npm start server depend on RN 0.22 .

0.19: 2 arguments
RCT_EXPORT_METHOD(connect:(NSURL *)URL socketID:(nonnull NSNumber *)socketID)

0.22: 4 arguments
RCT_EXPORT_METHOD(connect:(NSURL *)URL protocols:(NSArray *)protocols headers:(NSDictionary *)headers socketID:(nonnull NSNumber *)socketID)

**Comment by agmcleod** [comment]
Updating an older project of 0.14 to 0.25, running into a similar error: `rctwebsocketmodule.connect was called with 4 arguments, but expects 2`. Tried removing node modules, watch-del-all, clearing packager cache. Xcode clean & rebuild. This is when i have an ios url load the app. Launching the app without that works fine.

**Comment by Everhusk** [comment]
Still getting this error with RN0.26.. Tried removing node modules, watch-del-all, clearing packager cache. Xcode clean & rebuild as well multiple times. Android works fine, just iOS has the issue.
