### ISSUE TITLE
Calling a NativeModules method from the safari debugger crashes at `RCTAssertJSThread`

### ISSUE THREAD

**Issue by jaredly** [facebook/react-native#6226]
This is w/ the iOS 9.2 simulator on OSX. React Native 0.21.0-rc. 

Repro steps:
- start up a react native app
- open the safari debugger
<img width="513" alt="sim-safari" src="https://cloud.githubusercontent.com/assets/112170/13432032/2344bc7c-df89-11e5-88b4-71256d770a4e.png">
- enter `require('NativeModules').Clipboard.setString("something")` in the safari inspector js console
![image](https://cloud.githubusercontent.com/assets/112170/13432059/4900ea80-df89-11e5-8eea-9bcc456b5946.png)

The error:
RCTBatchedBridge.m @ 805
![image](https://cloud.githubusercontent.com/assets/112170/13432118/7d3abccc-df89-11e5-8ced-54163353c4bd.png)
![image](https://cloud.githubusercontent.com/assets/112170/13432138/a6cc3b38-df89-11e5-97ec-536b7a9fbeab.png)

However, calling native modules functions from the RN app (e.g. in response to a touch event) works just fine.

**Comment by brentvatne** [comment]
@tadeuzagallo - this seems like something you could answer in your sleep, any ideas?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/calling-a-nativemodules-method-from-the-safari-debugger-crashes-at-rctassertjsthread

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
