### ISSUE TITLE
[Website] Search is on current React native version, not selected version

### ISSUE THREAD

**Issue by Bhullnatik** [facebook/react-native#6245]
Right now when doing a search on the website, clicking on a result will go to the current React native version, ignoring the selected version.
This seems like an issue to me, as it's unexpected and not easy to notice.

I'd submit a fix for it myself but I'm not sure how Algolia works and how to handle different docs versions.

**Comment by grabbou** [comment]
If that's using Algolia, it might be tricky if full URLs are stored in their database. I would say the most reasonable thing would be to store only `docs/...` part of a link instead so it probably could work straight away given the correct base_url.

**Comment by brentvatne** [comment]
Assigned @skevy as it looks like he implemented this

**Comment by bestander** [comment]
Yeah, this one is a bummer, I looked at it briefly when was versioning the website.
Probably this requires some smarter integration with Algolia to differentiate between versions/paths.
If someone has a quick fix, it would be great.

**Comment by brentvatne** [comment]
@bobylito - maybe this is something you could look at? :)

**Comment by brentvatne** [comment]
Discussed this with @vjeux - let's remove the search bar from old versions if possible, and only enable search on the most recent version.

**Comment by bobylito** [comment]
That could be nice to have ;) I'm seeing what we can do on our side.

**Comment by bobylito** [comment]
We definitely support multiple versions. Do you want to forward? It's just a matter of choosing the right facet value. I can give you a hand for the algolia parameters @skevy @Bhullnatik

**Comment by bestander** [comment]
If it is a matter of params that we can define during build time then sure, let's do it.
Just to recap, we build a new version of website every 2 weeks and upload it to github CDN:
http://facebook.github.io/react-native/releases/0.20
http://facebook.github.io/react-native/releases/0.21
http://facebook.github.io/react-native/releases/next (for master branch build)
http://facebook.github.io/react-native (for latest stable build)

Ideally we don't want to touch "archived" versions every time we release a new one.

**Comment by brentvatne** [comment]
Awesome @bobylito & @bestander :) Algolia is even more powerful than I had thought

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/website-search-is-on-current-react-native-version-not-selected-version

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
