### ISSUE TITLE
How to pass data to navigator component after screen mounted

### ISSUE THREAD

**Issue by anwarhussain93** [facebook/react-native#6250]
i have login screen component in navigator i want to show loader after pressed sign in button so i want to pass props to show loader in login screen component **how can i pass props in navigator after screen mounted?** need help from this community

**Comment by satya164** [comment]
Hey and thanks for reporting this!

There's an awesome place to ask question like this one: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see your question, you can vote on answers and mark question as answered etc. This lets us keep a list of bug reports and feature requests on github and especially [Product Pains](https://productpains.com/product/react-native/?tab=top) (again, with voting which is really nice).

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)
