### ISSUE TITLE
couldn't find "libxxx.so"

### ISSUE THREAD

**Issue by shexiaoheng** [facebook/react-native#6261]
my library has .so file , has error: 
```text
AndroidRuntime: FATAL EXCEPTION: main
                            Process: com.bankcardidentify, PID: 31946
                            java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/mnt/asec/com.xxx-1/pkg.apk"],nativeLibraryDirectories=[/mnt/asec/com.xxx-1/lib, /vendor/lib, /system/lib]]] couldn't find "libxxx.so"
                            at java.lang.Runtime.loadLibrary(Runtime.java:373)
                            at java.lang.System.loadLibrary(System.java:540)
```

**Comment by shexiaoheng** [comment]
now , i remove library and move the .so file under android/app/src/main/jniLibs , still this error .

**Comment by grabbou** [comment]
Hey and thanks for reporting this!

There's an awesome place to ask question like this one: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see your question, you can vote on answers and mark question as answered etc. This lets us keep a list of bug reports and feature requests on github and especially [Product Pains](https://productpains.com/product/react-native/?tab=top) (again, with voting which is really nice).

If you think StackOverflow works for you please consider posting there instead and closing this issue.

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)

**Comment by brentvatne** [comment]
This isn't actionable enough for us, we would need exact repro steps or a project with the issue :( Please repost with this information if it is still an issue.

**Comment by dekemega** [comment]
+1 i have the same problem
