### ISSUE TITLE
[TabBar combination with NavigationBar error]

### ISSUE THREAD

**Issue by eric-sung** [facebook/react-native#6262]
code:
```
var Empty = React.createClass({
  render:function(){
    return (
      <NavigatorIOS
        style={styles.nav}
        initialRoute={{
          component: MainPage,
          title: '首页',
          navigationBarHidden:false,
          passProps: { myProp: 'foo' },
          tintColor:"#fff",
          barTintColor:"#333333",
          titleTextColor:"#fff",
          translucent:false,
      }}
      configureScene={this.configureScene}
    />
    );
  },
  configureScene:function(){
    return Navigator.SceneConfigs.FadeAndroid;
  },
});
```
when i set navigationBarHidden to true,Tabbar can show at bottom,but set false can
what's this problem?
-------------------------------------------------------------------------------------------------------------------
1.show navigator bar 
![image](https://cloud.githubusercontent.com/assets/4538766/13488438/25f7827c-e15c-11e5-9212-13f4ce001db5.png)
2.hide navigator bar
![image](https://cloud.githubusercontent.com/assets/4538766/13488446/3a3d75a2-e15c-11e5-801f-c86c13122b6c.png)

**Comment by grabbou** [comment]
Hey and thanks for reporting this!

There's an awesome place to ask question like this one: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see your question, you can vote on answers and mark question as answered etc. This lets us keep a list of bug reports and feature requests on github and especially [Product Pains](https://productpains.com/product/react-native/?tab=top) (again, with voting which is really nice).

If you think StackOverflow works for you please consider posting there instead and closing this issue.

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)

**Comment by grabbou** [comment]
Hint: Make sure you don't have height of your scene hardcoded. I have the feeling that when tabBar is presented, the height of container becomes smaller and hides your tabBar. Either consider using flexbox or position: absolute, bottom: 0

**Comment by mkonicek** [comment]
@facebook-github-bot stack-overflow
