### ISSUE TITLE
No notification pop up in top of the ios device while app is running foreground 

### ISSUE THREAD

**Issue by prabakarviji** [facebook/react-native#6276]
Notification is not appearing in top of the device while app is running .But notification reaches the notification bar in the device.How to handle this situation?

**Comment by grabbou** [comment]
Notifications are not showing due to iOS impl. details.

In order to e.g. present an Alert when app is running in the foreground, simply:
```js
PushNotificationIOS.addEventListener('notification', notification => {
      if (AppStateIOS.currentState !== 'background') {
          Alert.alert('Notification', 'I have just received notification in the foreground');
      }
}
```

Don't forget to follow all necessary steps for PushNotificationIOS module to work properly as described here -> https://facebook.github.io/react-native/docs/pushnotificationios.html#content

For the future issues regarding that, please consider filling in a StackOverflow question as Github issues are mainly for tracking bugs and making React Native even more stable :)

**Comment by prabakarviji** [comment]
Is it possible with newer version of RN?

**Comment by grabbou** [comment]
As I said - it's not possible due to system impl. details and React Native has nothing to do here. If you want to handle such case, you can use the snippet I provided (with probably some modifications) to display the bar manually (open up Messanger, keep chatting with your friends, you will see the notification bar that appears is different from the one that system would display)

**Comment by prabakarviji** [comment]
@grabbou Thanks . But i need clarification that is it possible with, if i schedule a coming notification (while app in foreground) and firing after a particular span of time?

**Comment by grabbou** [comment]
That is possible - all you have to do is to listen for it from within the app and display it manually. As long as the app is running in the foreground - it will receive notifications, but the system itself won't display it - since your app is running the display of it will be delegated to your app.

**Comment by charpeni** [comment]
@facebook-github-bot expected

**Comment by witalobenicio** [comment]
@grabbou when you say "system impl" you are talking about react native right? Because in iOS, when app is in foreground, it shows a banner notification inside the app (eg Whatsapp).

**Comment by grabbou** [comment]
The notification you see when app is in the foreground is a custom UI made by WhatsApp developers. It's not the same UI you see when you are in the background.
