### ISSUE TITLE
Hot Loading not working for *new react components*

### ISSUE THREAD

**Issue by martinbigio** [facebook/react-native#6280]
We have infra in place to send new dependencies to the HMR runtime if they didn't happen to be initially included on the bundle. This is working fine for module that export functions. For instance, given that `foo` is already on the bundle:

````
// Foo.js
class Foo extends React.Component {
  render() {
    return <Text>Hello</Text>;
  }
}
module.exports = Foo;
````

If you add the new module `bar`:

```
module.exports = function() {
  return " World";
}
```

and then change `foo`:

````
// Foo.js
var bar = require('./bar');
class Foo extends React.Component {
  render() {
    return <Text>{"Hello" + bar()}</Text>;
  }
}
module.exports = Foo;
````

You'll get "Hello World" as expected.

However, if bar is a component this just doesn't work:

````
// bar.js
class Bar extends React.Component {
  render() {
    return <Text>World</Text>;
  }
}
module.exports = Bar;
````

If you try to require `Bar` from `Foo` you'll get an error saying that the module `Bar` does not exist.

**Comment by martinbigio** [comment]
cc @skevy @satya164

**Comment by ide** [comment]
What if you use JS's `export default` instead of `module.exports`? Curious if that solves the problem.

**Comment by martinbigio** [comment]
@ide the problem is that the packager server doesn't send the HMR updates on the order it should. For the example described on this issue, we should always accept new modules before existing ones. I'll fix this now :)

**Comment by martinbigio** [comment]
The problem is not that simple because by requiring a new module we could potentially have to send a whole new dependency tree. We need to make sure that dependency tree is evaluated from the leaves to the root :/

**Comment by martinbigio** [comment]
have an idea: the resolution response returns the dependencies on BFS order. In here we build the list of modules we need to send to the client. The way we iterate on the list keeps the relative order of the modules, so we could just reverse that list and use that order :)

**Comment by martinbigio** [comment]
BTW, thanks @davidaurelio for flagging this!

**Comment by satya164** [comment]
I noticed this yesterday with the last RC. Didn't get the time to test on master though. Yeah, sending the whole new dependency tree will suck.

**Comment by martinbigio** [comment]
We only need to reverse the list of modules we need to patch. I'm landing a fix internally now :)

**Comment by satya164** [comment]
@martinbigio That's great. Waiting for it :)

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/hot-loading-not-working-for-new-react-components

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
