### ISSUE TITLE
The user limit on the total number of inotify watches was reached

### ISSUE THREAD

**Issue by svenjung** [facebook/react-native#6287]
After I installed react-native-image-picker, error via run npm start :
 ERROR  A non-recoverable condition has triggered.  Watchman needs your help!
The triggering condition was at timestamp=1457078390: inotify-add-watch(/sven/study/nodebb/node_modules/y18n/test) -> The user limit on the total number of inotify watches was reached; increase the fs.inotify.max_user_watches sysctl
All requests will continue to fail with this message until you resolve
the underlying problem.  You will find more information on fixing this at
https://facebook.github.io/watchman/docs/troubleshooting.html#poison-inotify-add-watch

{"watchmanResponse":{"version":"4.5.0","error":"A non-recoverable condition has triggered.  Watchman needs your help!\nThe triggering condition was at timestamp=1457078390: inotify-add-watch(/sven/study/nodebb/node_modules/y18n/test) -> The user limit on the total number of inotify watches was reached; increase the fs.inotify.max_user_watches sysctl\nAll requests will continue to fail with this message until you resolve\nthe underlying problem.  You will find more information on fixing this at\nhttps://facebook.github.io/watchman/docs/troubleshooting.html#poison-inotify-add-watch\n"}}
Error: A non-recoverable condition has triggered.  Watchman needs your help!
The triggering condition was at timestamp=1457078390: inotify-add-watch(/sven/study/nodebb/node_modules/y18n/test) -> The user limit on the total number of inotify watches was reached; increase the fs.inotify.max_user_watches sysctl
All requests will continue to fail with this message until you resolve
the underlying problem.  You will find more information on fixing this at
https://facebook.github.io/watchman/docs/troubleshooting.html#poison-inotify-add-watch

    at BunserBuf.<anonymous> (/sven/study/ReactNativeDemo/node_modules/fb-watchman/index.js:95:23)
    at emitOne (events.js:90:13)
    at BunserBuf.emit (events.js:182:7)
    at BunserBuf.process (/sven/study/ReactNativeDemo/node_modules/bser/index.js:289:10)
    at /sven/study/ReactNativeDemo/node_modules/bser/index.js:244:12
    at nextTickCallbackWith0Args (node.js:453:9)
    at process._tickCallback (node.js:382:13)

See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.

**Comment by satya164** [comment]
Hey and thanks for reporting this!

There's an awesome place to ask question like this one: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see your question, you can vote on answers and mark question as answered etc. This lets us keep a list of bug reports and feature requests on github and especially [Product Pains](https://productpains.com/product/react-native/?tab=top) (again, with voting which is really nice).

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)

http://unix.stackexchange.com/questions/13751/kernel-inotify-watch-limit-reached

**Comment by svenjung** [comment]
ok, got it. that was system issues.
