### ISSUE TITLE
keyboard hide TextInput when using placeholder and textAlign combination.

### ISSUE THREAD

**Issue by tal952** [facebook/react-native#6308]
```javascript
'use strict';
import React, {
    TextInput,
    AppRegistry,
    View,
    StyleSheet,
    Component
} from 'react-native';

class SampleApp extends Component {
    render() {
        return (
            <View style={style.main}>
                <TextInput placeholder='0'
                           style={style.numberInput}/>
            </View>
        );
    }
}

const style = StyleSheet.create({
    main: {
        flex: 1,
        justifyContent: 'flex-end',
        padding: 24,
        backgroundColor: 'white',
    },
    numberInput: {
        textAlign: 'center',
    }
});

AppRegistry.registerComponent('SampleApp', () => SampleApp);
```

I running the above code on my android lg g3.
when i touch the TextInput, the keyboard opens, and hide the TextInput.
If i remove `textAlign:'center'` or `placeholder='0'`, the View being scrolled and the textInput is visible.

I generated a new react-native@.21 project.
The problem **not** happend in https://rnplay.org/apps/fIoWrw.

**Comment by brentvatne** [comment]
@tal952 - is your device stock or is it rooted? can't think of what could cause this, cc @mkonicek

**Comment by tal952** [comment]
stock, not rooted.

**Comment by brentvatne** [comment]
@tal952 - do you have another Android device you can test this on? I don't have mine handy at the moment otherwise I would try it.

**Comment by tal952** [comment]
@brentvatne - tried it on samsung galaxy s4, same result.

**Comment by brentvatne** [comment]
thanks @tal952 

This ticket is available for interested contributors!

There is no clear answer for what needs to be changed -- you will want to be familiar with Android as this will require some understanding of the native side. If anyone wants to dig into this it would be much appreciated, Facebook folks might not get around to it until it becomes an issue for them.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/keyboard-hide-textinput-when-using-placeholder-and-textalign-combination

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by jpgarcia** [comment]
Hey @tal952 I'm running into the same issue did you found a workaround for this?
