### ISSUE TITLE
On windows, when adding new images/modules, you need to restart the packager

### ISSUE THREAD

**Issue by satya164** [facebook/react-native#6318]
Context - #6144

**Comment by AleCaste** [comment]
I don't know if the issue I am experiencing is related to this (I'd think so).
On Windows 7 64bit, whenever I modify any of the javascript files, if I reload the JS bundle on the mobile phone (I am not using an emulator, but a real Android device) I cannot see any of the changes I just made.
The bundle that gets loaded is exactly the same as the original one.
I'd guess the problem has to do with the filewatcher (I understand watchman is NOT being used on windows by the 'sane' module but something else; whatever it is, it seems it's not working).

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/on-windows-when-adding-new-imagesmodules-you-need-to-restart-the-packager

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
