### ISSUE TITLE
Better control over when the packager launches (iOS)

### ISSUE THREAD

**Issue by nevir** [facebook/react-native#6348]
Currently, the React xcode project has a run script step that checks for the packager and launches it if it is not running.

I've got a few cases where I'd like to be able to build my RN projects without spawning the packager.  Building for native tests, or to pass the binary off to another machine/device.

Ideally, I think, this script should be a phase of userland xcode projects rather than part of the React xcproj

**Comment by ide** [comment]
> this script should be a phase of userland xcode projects rather than part of the React xcproj

I think this is right. @frantic what do you think about moving the script that launches the packager, so that the script is in the project created by `react-native init` instead of React.xcproj?

**Comment by frantic** [comment]
This sounds good to me. We already have an "integration" script inside generated Xcode project called `packager/react-native-xcode.sh`, I guess we could use that to start the packager.


![image](https://cloud.githubusercontent.com/assets/192222/13680023/8c20f584-e6ab-11e5-8e49-9ba6cab1afa9.png)

**Comment by rogchap** [comment]
Best to add a new run script to the template generator.
This would help solve #7198
How about Android? Is this issue iOS only?
Happy to submit a PR if this is still needed.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/better-control-over-when-the-packager-launches-ios

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
