### ISSUE TITLE
Error: Unable to download JS Bundle from dev server - Android devices RN 0.20

### ISSUE THREAD

**Issue by poonamst** [facebook/react-native#6354]
**React version** - RN 0.20
**Environment** - Android devices
**Issue** - Unable to download JS Bundle from dev server when trying to use localhost on Android devices.

The issue is not reproducible on Android simulators. Applicable only for Android devices. Attached is a screenshot of the error. Verified that was not an issue in RN 0.18.

**Description and steps to reproduce**:-

1. Set the JSBundle location to localhost
2. Reload JS (since it grabs it from the bundle for the very first time)
3. Complains saying Unable to download JS Bundle from dev server

![error_android](https://cloud.githubusercontent.com/assets/5892908/13588398/4a4c72ec-e484-11e5-823c-dc517a98cc88.png)

**Comment by christopherdro** [comment]
@poonamst I can't image this being a problem between RN versions. Did you double check that your device is connected to the same network as your localhost?

If your devices are running Android 5+, you can try running `adb reverse tcp:8081 tcp:8081` instead of entering it manually through dev settings.

Also make sure you restart your packager when changing between versions.

**Comment by satya164** [comment]
You need to set the address to your computer's IP address, not `localhost`. Or run `adb reverse tcp:8081 tcp:8081` as @christopherdro suggested. Let's re-open if we're missing something.
