### ISSUE TITLE
ART on android can't recognize gesture

### ISSUE THREAD

**Issue by yiyangest** [facebook/react-native#6356]
I'm using react-native v0.20, and have a view containing ART surface and shape, like this:

     <View onStartShouldSetResponder={this.onStartShouldSetResponder.bind(this)}
                    onMoveShouldSetResponder={this.onMoveShouldSetResponder.bind(this)}
                    onResponderGrant={this.onResponderGrant.bind(this)}
                    onResponderMove={this.onResponderMove.bind(this)}
                    onResponderRelease={this.onResponderRelease.bind(this)}
                    onResponderTerminationRequest={this.onResponderTerminationRequest.bind(this)}>
               <Surface>
                     <Group>
                          <Shape ../>
                     </Group>
               </Surface>
    </View>

But only onStartShouldSetResponder (this returns true)  get called, the others never get called.

And the same code works fine on iOS.

So, dose the ART on android break the gesture responder system? If so, how should I do to get things fixed?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/art-on-android-cant-recognize-gesture

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
