### ISSUE TITLE
Multiple newline's not working correctly in TextInput

### ISSUE THREAD

**Issue by cornedor** [facebook/react-native#6361]
Multiple newlines in a defaultValue as visible in this snippet do not work correctly:
```js
<TextInput
  multiline={true}
  style={{ height: 200, width: 200, borderWidth: 2 }}
  defaultValue={`
Hello World!
Newline test

More newlines
 Even more newlines
  `} />
```

The result is a TextInput with only a newline after "Hello World!". If there are multiple newlines or if there is a whitespace after a newline the newline's are ignored.

This does occur in iOS and Android in React 0.21.0

![screen shot 2016-03-08 at 14 11 01](https://cloud.githubusercontent.com/assets/570297/13602730/a580db26-e538-11e5-8cbe-af71109b5e2c.png)

**Comment by cornedor** [comment]
After a bit more research I found that the problem is not with the input, but it is probably something with the JSX transformer.
![screen shot 2016-03-08 at 15 02 46](https://cloud.githubusercontent.com/assets/570297/13603978/ed5019a0-e540-11e5-916d-ed16bb4c6cc4.png)

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/multiple-newlines-not-working-correctly-in-textinput

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
