### ISSUE TITLE
Is it possible to use icons inside Navigator?

### ISSUE THREAD

**Issue by adampietrasiak** [facebook/react-native#6378]
![image](https://cloud.githubusercontent.com/assets/7311462/13639359/aee45688-e610-11e5-9dfe-4df0d9697e76.png)

Is there any way to use icons inside Navigator component instead of plain text? If so - is it documented anywhere or do you know how to do it?

Also - as on attached image - some of the icons are navigating to different views and some are in kind of "toggles" that are highlighted when toggled.

**Comment by mkonicek** [comment]
@facebook-github-bot stack-overflow

**Comment by charpeni** [comment]
You can refer to https://github.com/react-native-simple-router-community/react-native-simple-router, it's documented with example.

**Comment by mkonicek** [comment]
Thanks @charpeni! I'll close this issue as the question has been answered.

**Comment by mkonicek** [comment]
@facebook-github-bot stack-overflow

**Comment by adampietrasiak** [comment]
Actualy you didn't response to the question - the answer is no? Component you've linked is not really popular and I'm not sure if it might be production ready.

**Comment by charpeni** [comment]
[react-native-simple-router](https://github.com/react-native-simple-router-community/react-native-simple-router) is a simple implementation of `Navigator` component.

>but it's not really popular

Do not judge by the number of stars, the repository has been created about 1 month ago. 649 downloads in the last month. It's based on https://github.com/t4t5/react-native-router, since t4t5 doesn't maintain it.

>I'm not sure if it might be production ready.

I would say it's production ready, but if you're not sure just check how we implement icons/buttons on navigation bar. In a few words, `navigationBar` is a custom component that contains others component that act as buttons / icons.

**Comment by mkonicek** [comment]
@facebook-github-bot stack-overflow

**Comment by mkonicek** [comment]
> this issue looks like a question that would be best asked on StackOverflow

>  This also helps us use the GitHub bug tracker for bugs only

We use the GitHub issue for bugs only.
