### ISSUE TITLE
ScrollView.scrollsToTop should be deprecated

### ISSUE THREAD

**Issue by matthewga0** [facebook/react-native#639]
>**scrollsToTop** bool
>When true, the scroll view scrolls to top when the status bar is tapped. The default value is true.

**ScrollView** without suffix *IOS* makes me think that this component was designed for both iOS and Android, but the property `scrollsToTop` is a special api of UIScrollView which only on iOS, it's may not working on Android devices.

**Comment by karpotkin** [comment]
https://www.dropbox.com/s/jmss0ovvvp3cov1/Screenshot%202015-04-03%2013.17.26.png?dl=0 and scroll top depricated

**Comment by brentvatne** [comment]
@matthewga0 - it's possible to implement that same behaviour on another platform even if there is no built-in native function for it. We'll have to see where this goes with Android.

@karpotkin - thanks for the image, unfortunately it's not very clear from it exactly what the issue is? If you can explain further I will reopen the issue
