### ISSUE TITLE
[Android] Entering a dev server IP containing a space crashes the app

### ISSUE THREAD

**Issue by AntonNiklasson** [facebook/react-native#6402]
I accidentally entered an IP including a space in the dev settings of my react native application.

The app crashehs on a reload, and when I try to restart it instantly crashes. The only thing I've found that helps is a reinstallation.

I haven't tried this on iOS yet.

**Comment by KalebPortillo** [comment]
+1 
Same here...
If you don't want to reinstall, you can clear all the app data and cache, and then put the IP address again without any spaces

**Comment by AntonNiklasson** [comment]
I would say the best solution is to run some validation before even saving the IP adress.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-entering-a-dev-server-ip-containing-a-space-crashes-the-app

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
