### ISSUE TITLE
Embedded Android Docs Outdated

### ISSUE THREAD

**Issue by IanVS** [facebook/react-native#6422]
It seems like there were some major changes to lifecycle methods, as evidenced in https://github.com/facebook/react-native/commit/ad17a2f2908f430b05fd2836d3f08873988bce10 (I can't find the actual changes yet).

Judging by this commit, the [Integrating with Existing Apps](https://github.com/facebook/react-native/blob/v0.22.0-rc/docs/EmbeddedAppAndroid.md) docs seem out of date.

**Comment by satya164** [comment]
That code in the docs should still work. We've just added a base activity for React Native apps. Now, instead of doing all the things under the 'Add native code' section, your activity can just extend 'ReactActivity' like follows,

```java
public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "MyAwesomeApp";
    }

    /**
     * Returns whether dev mode should be enabled.
     * This enables e.g. the dev menu.
     */
    @Override
    protected boolean getUseDeveloperSupport() {
        return BuildConfig.DEBUG;
    }

    /**
     * A list of packages used by the app. If the app uses additional views
     * or modules besides the default ones, add more packages here.
     */
    @Override
    protected List<ReactPackage> getPackages() {
        return Arrays.<ReactPackage>asList(
            new MainReactPackage()
        );
    }
}
```

**Comment by janicduplessis** [comment]
I noticed that a while ago and fixed it today. I didn't even noticed this issue haha. #6435

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/embedded-android-docs-outdated

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
