### ISSUE TITLE
ReferenceError:Can't find variable: _fbBatchedBridge

### ISSUE THREAD

**Issue by ltyhome** [facebook/react-native#6425]
Hi ~
 When I build this project used my phone(HTC820us-AndroidOS4.4.4) in my macbook,Although though the project it works but produce a runtime exception.
 java.util.concurrent.ExecutionException:java.lang.RuntimeException:ReferenceError:
       Can't find variable:_fbBatcheBridge(<unknown file>:1)
screenshots
https://s-media-cache-ak0.pinimg.com/originals/9b/f1/63/9bf163a170b41ca5550acd1319b588ac.png
or
https://www.pinterest.com/ltyhome/bugreport/

**Comment by ahanriat** [comment]
Hi @ltyhome 
As @ide says in https://github.com/facebook/react-native/issues/6425, it is probably due to your `node_modules`. Try this `rm -rf node_modules && npm i`, and then `npm start --reset-cache`
Hope this will help :wink:

**Comment by christopherdro** [comment]
@ltyhome 
Your going to have to follow steps on how to connect your device. 
Since your running on a versions below 5, your have to input your dev server address manually. 

See:
https://facebook.github.io/react-native/docs/running-on-device-android.html#configure-your-app-to-connect-to-the-local-dev-server-via-wi-fi

Feel free to re-open this if the problem persists.
