### ISSUE TITLE
Network request failed after unlocking the phone

### ISSUE THREAD

**Issue by mcaoun** [facebook/react-native#6457]
I am seeing an interesting behavior on iOS using the following simple snippet and performing these steps:

 - Open the App the first time
 - Press Home
 - Re-open the app, as a result of the app becoming active a first fetch request is issued (and it succeeds)
 - Press Home again
 - Lock your phone
 - Unlock your phone
 - Open the App, as a result of the app becoming active a second fetch request is issued, it fails with the error "Network request failed"!

I can reproduce it every time on my iphone 6 running ios 9.2.1 and I am using react native 0.21.0

I think it is an issue with react native, because I tried to reproduce with a native app but I could not, although I could be mistaken.

Here is the snippet:

    import React, {
      AppRegistry,
      AppStateIOS,
      Component,
      View
    } from 'react-native';

    class TestConnectionFailureRN extends Component {
      componentDidMount() {
        AppStateIOS.addEventListener(
          'change', this._didBecomeActive);
      }
      _didBecomeActive(appState) {
          if (appState != 'active') {
            return;
         }
         return fetch('https://www.google.de', {}).then(
          (response) => console.log(response));
      }
      render() {
        return (
          <View></View>
        );
      }
    }

    AppRegistry.registerComponent('TestConnectionFailureRN', () => TestConnectionFailureRN);

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/network-request-failed-after-unlocking-the-phone

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by eomine** [comment]
@mcaoun How did you solve this issue? I'm getting the same behavior on a project I'm currently working on.

For now, I'm implementing a "request retry" whenever a network request error occurs.

**Comment by mcaoun** [comment]
I did the same. I retry immediately but only once when catching an error "Network request failed'"

**Comment by eomine** [comment]
Ok, thanks!
