### ISSUE TITLE
React-Native Maven is no longer actively updated with releases

### ISSUE THREAD

**Issue by lental** [facebook/react-native#6459]
Hey all,

I understand that 0.21.0 and higher are now being distributed through npm, however I'd like to suggest that react-native continues to distribute the package through maven,

I work on a library that places a complex UI Widget into the developer's application.  By using react-native as a maven dependency, I can ask the developer to add the maven dependency, and not have to bother with all of the react-native npm and other configuration process just to use our library.

From all verisons < 21, My company can create a library that is built using the entire react-native framework, and allow for integration with our library with nothing but the maven dependency, and I have had a great time building it to that point.

I'm treating this as a bug because it's a regression from our original usage of the framework. Is there any chance the Maven repository can continue to be updated?

Thanks

**Comment by ide** [comment]
For maintenance reasons it's unlikely that we'll publish to Maven (or CocoaPods on iOS). Maven significantly slows down the release process since we have to wait a few hours for the artifacts to get distributed, poses permissions problems, and increases the surface area of code to test. If you rely on Maven in your workflow, though, my suggestion is to take the JAR/AAR assets distributed via npm and upload them to Maven yourself.

**Comment by mkonicek** [comment]
@facebook-github-bot answered
