### ISSUE TITLE
[Android] "Unable to dispatch keyboard events in JS as the react instance has not been attached" when add Debug.startMethodTracing in MainActivity

### ISSUE THREAD

**Issue by atom992** [facebook/react-native#6463]
I am using React Native 0.17.0 on Android 5.0.1.
When I add Traceview Code ``` Debug.startMethodTracing("calc"); ``` in MainActivity's ```onCreate() ``` method ,and When I launch my app, I got the following logs:

```
          EGL_emulation  W  eglSurfaceAttrib not implemented
         OpenGLRenderer  W  Failed to set EGL_SWAP_BEHAVIOR on surface 0xa6c87a20, error=EGL_SUCCESS
          unknown:React  W  Unable to dispatch keyboard events in JS as the react instance has not been attached
```
And My app got stuck without any Rendering(When I pause my app,The UI rendered).
And When I remove the Traceview Code,all works fine.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-unable-to-dispatch-keyboard-events-in-js-as-the-react-instance-has-not-been-attached-when-add-debugstartmethodtracing-in-mainactivity

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
