### ISSUE TITLE
iOS XCode fatal hanging error while Unlock

### ISSUE THREAD

**Issue by TrueMax** [facebook/react-native#6484]
1. Created an XCode project, launched it via terminal "react-native run-ios", while launching got a bunch of permission (EACCES) errors, overriden by "sudo ..." commands 
2. opened .xcodeproj file in XCode (7.2.1) 
3. got an Unlock issue as in attached screenshots 
![2016-03-16 16 00 17](https://cloud.githubusercontent.com/assets/16180560/13813673/db2c79ae-eb93-11e5-9b20-cac16e7f7e87.png)
![2016-03-16 16 07 11](https://cloud.githubusercontent.com/assets/16180560/13813674/db777d78-eb93-11e5-86f5-fcce80540cbf.png)

4. made sure I did change the owner of all parent folders of the project by 
"sudo chown -R $MYSELF ~/PROJECTPATH" 

5. XCode did not allow to exit normally after the error, I forced the exit manually  

- [x] What's the **version** of React Native you're using?

the latest available today (installed today, 16/03/2016)

- [x] Does this occur on iOS, Android or both?
iOS 

- [x] Are you using Mac, Linux or Windows?
Mac OS X 10.11.3

**Comment by grabbou** [comment]
Hey, we use Github for issues only and all questions should be asked on StackOverflow. Please consider posting your question up there providing more details on what specifically you'd like to achieve! 

This is for us to keep the number of issues smaller so that we can iterate on React Native versions faster and provide you with the better developer experience. 

If you have any ideas on how we could improve the entire process, please share your thoughts on [React Native Community](https://www.facebook.com/groups/react.native.community/?ref=nf_target&fref=nf) group.
