### ISSUE TITLE
Framework inconsistency: removeEventListener() vs remove()

### ISSUE THREAD

**Issue by lprhodes** [facebook/react-native#6493]
It'd be great for the removal of listeners/observers to work in a consistent

At the moment there's two ways that work differently depending on which class is being used

**DeviceEventEmitter**
```
this.tabWillBlurObserver = DeviceEventEmitter.addListener('tabwillblur', this.tabWillBlur)
this.tabwillBlurObserver.remove()
```

**AppStateIOS**
```
AppStateIOS.addEventListener('change', this.handleAppStateChange)
AppStateIOS.removeEventListener('change', this.handleAppStateChange)
```
It feels more natural (from a learning point of view) to be able to remove something in the same way you added it. It also means there's less class vars which can make the code and IDE autocomplete feel cleaner.

i.e. `DeviceEventEmitter.removeListener('tabwillblur', this.tabWillBlur)`

Though I can also see the benefits of going the other way:

`this.appStateObserver.remove()`

Thoughts?

**Comment by janicduplessis** [comment]
I agree the API should be consistent. `DeviceEventEmitter` aka `RCTDeviceEventEmitter` is pretty much just an instance of the `EventEmitter` class (EventEmitter.js) and is a polyfill of the node EventEmitter (https://nodejs.org/api/events.html).

AppStateIOS implements an API that is more similar to `EventTarget` (https://developer.mozilla.org/en-US/docs/Web/API/EventTarget) which is probably more familiar to web developers.

I don't really have a preference of one API over the other but It would be a lot easier to change `AppStateIOS` since `EventEmitter` is used a lot through the code base.

As long as we use the same API everywhere for events :)

**Comment by ide** [comment]
I'm a lot more in favor of the subscription-like `remove()` API because you don't have to retain a reference to the listener. For example, this listener can never be removed with the web-like addEventListener API: `API.addEventListener('event', (evt) => {  })`.

cc @vjeux

**Comment by vjeux** [comment]
For context, we had like 5 different implementations of subscriptions internally and couldn't decide which one to pick so we went to the web like which, while probably the worse from a design standpoint had the merit of working for all use cases. I'd love to do another pass at it at some point as the api is really bad.

The big thing we tried to do was to tie it to the component lifecycle, such that we couldn't accidentally leak it when forgetting to remove the subscription.

**Comment by ide** [comment]
Explicit subscription objects seem like the easiest to integrate with the component lifecycle since we can define a clear interface (ex: all subscriptions must implement `remove()`... but later could implement things like `pause()` or `resume()` or `setPriority(p)`).

Tangent: one of the hardest parts about integrating them with component lifecycles is the lack of mixins IMO. We want a way to mix behavior into a component class and be able to implement `componentWillUnmount`. This was possible with React's first-class mixins when using `React.createClass`, but that went away with JS classes and we're left with higher-order components, which have their own slew of problems from the perspective of someone using React (vs. implementing React).

The reason I bring that up is because I don't think it will be easy to arrive at a complete solution for subscriptions till React mixins, or something similar, are figured out. But I do think that an API centered around explicit subscription objects is more future-proof because we can kind of break the problem into two pieces: what should the Subscription API look like, and how do we tell React about Subscription objects?

**Comment by satya164** [comment]
Yeah, love the idea of subscriptions objects.

**Comment by janicduplessis** [comment]
Most events are already implemented using EventEmitter which is the API everyone seems to prefer. Maybe we could just deprecate the APIs that use `addEventListener` like AppStateIOS and change it to EventEmitter. It should not be that much work and would make the exposed event APIs consistent.

**Comment by vjeux** [comment]
Is there a way to make both versions work and warn on the old one?

**Comment by ide** [comment]
@vjeux it's easy here because the functions are named differently: `addListener` and `addEventListener` :)

**Comment by rahuljiresal** [comment]
Added the API `DeviceEventEmitter.removeListener(eventType, listener)` in PR https://github.com/facebook/react-native/pull/6884

**Comment by lacker** [comment]
Since Rahul responded to this in his PR, I think the useful life of this issue is ended, and I am going to close this issue. Feel free to reopen or open a new one if there is something additional that we should figure out here.
