### ISSUE TITLE
Android: Native component bridging

### ISSUE THREAD

**Issue by monkichi99** [facebook/react-native#6494]
I have create a Custom UI component and not quite understand whether I need Event Handling to get the text of AutoCompleteTextView into JS side.

https://facebook.github.io/react-native/docs/native-components-android.html#content

I just want to use a onPress event to get the inputted text in the AutoCompleteTextView

```
            <View>
                <TouchableHighlight style={Styles.buttonInvite} onPress={this.getText.bind(this)}>
                    <Text style={[Styles.inviteText]}>Get input</Text>
                </TouchableHighlight>
            </View>
```

```
import { requireNativeComponent, PropTypes } from 'react-native';

var React = require('react-native');
var TextInput = React.TextInput;

var iface = {
  name: 'AutoCompleteTextInput',
  propTypes: {
  		...TextInput.propTypes
	},
};

module.exports = requireNativeComponent('RCTAutoCompleteTextView', iface);
```
```
class Sample extends Component {

  constructor(props) {
      super(props);
      //var label = await AutoComplete.getText;
     // Console.log(label);
  }
  


  
	render() {
        return (
            <View>
                <AutoComplete style={Styles.emailInput}/>      
            </View>
        );
    }
}

AppRegistry.registerComponent('AutoComplete', () => Sample);
```
```
public class ReactAutoCompleteTextView extends AutoCompleteTextView{

    private CustomPermissionChangeListener listener;
    private String[] language ={"C","C++","Java",".NET","iPhone","Android","ASP.NET","PHP"};
    private Context context;


    public ReactAutoCompleteTextView(ThemedReactContext context) {
        super(context);
        this.context = context;
        ArrayAdapter<String> adapter = new ArrayAdapter<String>
                (context,android.R.layout.select_dialog_item,language);
        this.setAdapter(adapter);
        listener = new CustomPermissionChangeListener(context, this);
    }

}
```
```
public class AutoCompleteTextViewManager extends SimpleViewManager<ReactAutoCompleteTextView> {

    public static final String REACT_CLASS = "RCTAutoCompleteTextView";

    @Override
    public String getName() {
        return REACT_CLASS;
    }

    @Override
    public ReactAutoCompleteTextView createViewInstance(ThemedReactContext context) {
        return new ReactAutoCompleteTextView(context);
    }
}
```

**Comment by mkonicek** [comment]
The AutocompleteTextView should be a _controlled component_. This is because it can be mutated by user interactions. For a quick explanation see the part about `onChange` here: https://facebook.github.io/react/docs/forms.html

To implement a controlled component you could look at the Android `ReactEditText`, it's closer to what you want to do but quite very complex.

You'll need to emit a text changed event every time the state of your component changes in a meaningful way (for example the user types a character, or selects an option), and maintain that same state in JS (this is needed for all controlled components). As an example of raising events from native to JS see the eventDispatcher in the `Switch` component, which is a controlled component too: https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/switchview/ReactSwitchManager.java

I'd like to start using StackOverflow more. We should really be discussing questions like this there rather than in the GitHub bug tracker.

**Comment by mkonicek** [comment]
@facebook-github-bot stack-overflow

**Comment by Noitidart** [comment]
We are working on androids `AutoCompleteTextView` (and `MultiAutoCompleteTextView`) here - https://github.com/rajsuvariya/autocompletetextview/pull/18


We bridged the component, however focus was getting stuck. And we also wanted multiline support and all the other goodies that come with `ReactEditText` so we tried to extend `ReactEditText`. i'm totally new to this bridging so what I did was copy `ReactEditText` and replace it with `AutoCompleteTextView`. In the PR linked above, I have the issue of this:

https://github.com/rajsuvariya/autocompletetextview/pull/18#discussion-diff-175345808R55

> The wrapper stops the EditText from triggering *TextChanged events

I think this is stopping the auto-suggestions from showing.

Would be awesome if any of the experienced folks can take a peek.
