### ISSUE TITLE
goBack did not work on Android API 19

### ISSUE THREAD

**Issue by TeodorKolev** [facebook/react-native#6521]
My code works on API 23 but it did not working on API 19
```
  goBack: function() {
     this.refs[WEBVIEW_REF].goBack();
  },
  onNavigationStateChange: function(navState) {
   this.setState({
     url: navState.url,
     canGoBack: navState.canGoBack,
   });
  },
  getInitialState: function() {
    return {
      url: DEFAULT_URL,
      status: 'No Page Loaded',
    };
  },
  render() {
    return (
      BackAndroid.addEventListener('hardwareBackPress',() => {
          var self=this;
          var url = this.state.url;
          var back = this.state.canGoBack;
          if (back && url != DEFAULT_URL + "login") {
            this.goBack();
            return true;
          } else {
            return false;
          }
       }),
      <View style={{flex: 1}}>
      <StatusBar hidden={true} />
        <WebView

**Comment by gre** [comment]
you are not using it correctly. also I did answered you on the chat concerning this.

@facebook-github-bot close

**Comment by gre** [comment]
@facebook-github-bot label android

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/goback-did-not-work-on-android-api-19

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
