### ISSUE TITLE
Fully-featured inline image

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#6529]
Original discussion: https://www.facebook.com/groups/reactnativeoss/permalink/1532669803696315/

### Parity on vertical alignment of inline images
- [x] Default to `verticalAlign: baseline` on iOS and Android (already on iOS, Android PR: https://github.com/facebook/react-native/pull/6528)
- [ ] [Support `top` property](https://github.com/facebook/react-native/pull/6528#issuecomment-198487699)
- [ ] Support some useful subset of `verticalAlign` values (others can be added as needed by contributors)

### Other details
- [ ] propType validation on the "virtual image" (eg: margin/padding do nothing, but we don't actually raise any warnings)
- [ ] Support for resizeMode on Android
- [ ] Support for fadeDuration on Android
- [ ] Determine what other `Image` properties can be shared, refactor to share logic between inline image and regular image.

**Comment by rickysahu** [comment]
Here's a workaround that'll preserve styles
```
        <View style={{flexDirection:'row', flexWrap:'wrap'}}>
          <Image
            style={styles.img}
            source={{uri: imageLink}} />
          <Text>
            {"sweet, this works"}
          </Text>
        </View>
```

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/fully-featured-inline-image

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
