### ISSUE TITLE
[ios][API 0.20.0]Assertion failure in -[RCTTouchEvent coalesceWithEvent:]

### ISSUE THREAD

**Issue by Chenjm08** [facebook/react-native#6554]
It has a crash when I used 2 CRTRootView and move them at the same time.

**Comment by grabbou** [comment]
Hey, could you include a stack trace? That'd help a lot!

**Comment by Chenjm08** [comment]
trunk/node_modules/react-native/React/Base/RCTTouchEvent.m:48
(lldb) bt
* thread #1: tid = 0x1eb121, 0x0000000182a33f48 libobjc.A.dylib`objc_exception_throw, queue = 'com.apple.main-thread', stop reason = breakpoint 1.2
    frame #0: 0x0000000182a33f48 libobjc.A.dylib`objc_exception_throw
    frame #1: 0x00000001833c57d0 CoreFoundation`+[NSException raise:format:arguments:] + 108
    frame #2: 0x0000000183d38a08 Foundation`-[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 88
  * frame #3: 0x000000010132c85c Circle`-[RCTTouchEvent coalesceWithEvent:](self=0x000000012cfac250, _cmd="coalesceWithEvent:", newEvent=0x000000012e144b60) + 824 at RCTTouchEvent.m:48
    frame #4: 0x0000000101319b74 Circle`-[RCTEventDispatcher sendEvent:](self=0x000000012cebc8a0, _cmd="sendEvent:", event=0x000000012e144b60) + 300 at RCTEventDispatcher.m:152
    frame #5: 0x00000001012e8eec Circle`-[RCTTouchHandler _updateAndDispatchTouches:eventName:originatingTime:](self=0x000000012ceecfb0, _cmd="_updateAndDispatchTouches:eventName:originatingTime:", touches=1 object, eventName=@"touchMove", originatingTime=335132.74809829169) + 1344 at RCTTouchHandler.m:203
    frame #6: 0x00000001012e92e4 Circle`-[RCTTouchHandler touchesMoved:withEvent:](self=0x000000012ceecfb0, _cmd="touchesMoved:withEvent:", touches=1 object, event=0x000000012ce54d90) + 244 at RCTTouchHandler.m:269
    frame #7: 0x00000001886353c8 UIKit`-[UIGestureRecognizer _touchesMoved:withEvent:] + 96
    frame #8: 0x00000001880e8600 UIKit`-[UIWindow _sendGesturesForEvent:] + 588
    frame #9: 0x00000001880e7e1c UIKit`-[UIWindow sendEvent:] + 764
    frame #10: 0x00000001880b84cc UIKit`-[UIApplication sendEvent:] + 248
    frame #11: 0x00000001880b6794 UIKit`_UIApplicationHandleEventQueue + 5528
    frame #12: 0x000000018337cefc CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
    frame #13: 0x000000018337c990 CoreFoundation`__CFRunLoopDoSources0 + 540
    frame #14: 0x000000018337a690 CoreFoundation`__CFRunLoopRun + 724
    frame #15: 0x00000001832a9680 CoreFoundation`CFRunLoopRunSpecific + 384
    frame #16: 0x00000001847b8088 GraphicsServices`GSEventRunModal + 180
    frame #17: 0x0000000188120d90 UIKit`UIApplicationMain + 204
    frame #18: 0x0000000100084c44 Circle`main(argc=1, argv=0x000000016fdafa80) + 124 at main.m:16
    frame #19: 0x0000000182e4a8b8 libdyld.dylib`start + 4

**Comment by Chenjm08** [comment]
https://github.com/mannyvergel/ReactNativeMVTableView

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/iosapi-0200assertion-failure-in-rcttouchevent-coalescewithevent

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
