### ISSUE TITLE
ToolbarAndroid - Font size on landscape view

### ISSUE THREAD

**Issue by ufon** [facebook/react-native#6567]
Portrait
![image](https://cloud.githubusercontent.com/assets/4355972/13928639/9b133160-efa7-11e5-863d-914c879fa97a.png)
Landscape
![image](https://cloud.githubusercontent.com/assets/4355972/13928685/c7d2f0e6-efa7-11e5-9e17-622e32b60be5.png)

```
 <Icon.ToolbarAndroid style={styles.toolbar}
        title={'news'}
        titleColor="white"
        navIconName="android-menu"
        onIconClicked={() => this.drawer.openDrawer()}/>
```

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/toolbarandroid-font-size-on-landscape-view

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
