### ISSUE TITLE
Docs missing for "Navigation card stack"

### ISSUE THREAD

**Issue by fungilation** [facebook/react-native#6573]
I see 0.22 release notes mentioning Navigation card stack. NavigationExperimental was added in 0.21. I'm trying to learn what these are about, but no reference to these in the [RN docs site](http://facebook.github.io/react-native/docs). These new features should be documented, for something as important as the Navigator? If it already is, I appreciate if someone can point me in the right direction.

**Comment by charpeni** [comment]
It seems your're right, at least you can check [the example inside UIExplorer ](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/NavigationExperimental/NavigationCardStackExample.js).

**Comment by charpeni** [comment]
@facebook-github-bot label documentation

**Comment by joshblour** [comment]
@fungilation check here for a hint: https://github.com/ericvicenti/navigation-rfc/blob/master/Docs/Navigation.md#navigationcardstack

**Comment by fungilation** [comment]
Thanks. Looking forward to NavigationExperimental taking over the standard Navigator.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/docs-missing-for-navigation-card-stack

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by timpler** [comment]
It makes me sick...
