### ISSUE TITLE
util 0.22.2 and master branch, box model still not support stretch height with flex layout

### ISSUE THREAD

**Issue by xueduany** [facebook/react-native#6582]
But if use css-layout new code, we met a new issue with padding, like https://github.com/facebook/css-layout/issues/173

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/util-0222-and-master-branch-box-model-still-not-support-stretch-height-with-flex-layout

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
