### ISSUE TITLE
AlertIOS cancel button is always left-aligned even if a destructive btn exists

### ISSUE THREAD

**Issue by samuelkraft** [facebook/react-native#6587]
If you add the style "cancel" to an alert button it will always be left-aligned regardless of the array order. This is great most of the time as per apple guidelines:
> When the most likely button performs a nondestructive action, it should be on the right in a two-button alert. The button that cancels this action should be on the left.

But when paired with a destructive action the order should be reversed:
> When the most likely button performs a destructive action, it should be on the left in a two-button alert. The button that cancels this action should be on the right.

From [this page](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/Alerts.html).

The android version respects the order of the buttons in code. Not sure if that is the best solution or if it's better to right-align the cancel button automatically if a destructive button exists.

See code below and a screenshot of the generated alert.
```jsx
Alert.alert(
  'Destructive confirmation',
  '',
  [
    {text: 'Delete', style: 'destructive'},
    {text: 'Cancel', style: 'cancel'}
  ]
) 
```

<img width="285" alt="screen shot 2016-03-22 at 14 31 51" src="https://cloud.githubusercontent.com/assets/2223418/13953550/bb13b878-f03c-11e5-9d29-2147227d02bf.png">

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/alertios-cancel-button-is-always-left-aligned-even-if-a-destructive-btn-exists

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
