### ISSUE TITLE
FormData object not detected by XHR wrapper libraries

### ISSUE THREAD

**Issue by mcorb** [facebook/react-native#6600]
The axios XHR wrapper library fails to detect RN FormData objects:

Expected output as seen in browsers: formData.toString() === "[object FormData]"

Actual output from RN:  formData.toString() === "[object Object]"

This appears to be a completeness-of-implementation in RN breaking compatibility.

Detection code in axios, currently broken with RN causing uploads to fail, is as follows:

https://github.com/mzabriskie/axios/blob/master/lib/utils.js

/**
 * Determine if a value is a FormData
 *
 * @param {Object} val The value to test
 * @returns {boolean} True if value is an FormData, otherwise false
 */
function isFormData(val) {
  return toString.call(val) === '[object FormData]';
}

**Comment by ide** [comment]
We should be able to fix this by overriding `toString` -- someone want to send a PR?

**Comment by mcorb** [comment]
So, the same problem seems to exist with other object instances:

Browser: new XMLHttpRequest().toString() "[object XMLHttpRequest]"
RN: new XMLHttpRequest().toString() "[object Object]"

So we're looking at a convention that DOM implementations follow. Instead of dealing with conformance issues as they arise individually, I'd suggest implementing this as a mixin and applying it to all DOM-like classes in react-native's browser-like API layer.

**Comment by prometheansacrifice** [comment]
@mcorb  @ide [Language specs]() say that the behaviour is consistent. I couldn't find much in [XMLHttpRequest specs](https://xhr.spec.whatwg.org/#interface-xmlhttprequest) either. Is it still justified then?

**Comment by satya164** [comment]
@prometheansacrifice Doesn't hurt to be consistent with the web implementation even if it's not in the specs. Who knows how many more libraries are using the same approach!

@mcorb Would be awesome if you could send a PR to fix this.

**Comment by grabbou** [comment]
I have realised two things after playing around with this - hence I am not sure if we can really do anything about it.

First thing is - overwriting `toString` is not going to work with axios since it calls `Object.prototype.toString` that has slightly different behaviour (more on that below). That means any custom things we do with that method on a class level won't do anything.

Second thing is - in most cases toString when called on an object, returns e.g. length of an array. The reason it prints `[object Array]` when called on Object's prototype is because the behaviour is slightly different. `Object.prototype.toString` returns the value of the internal `[[Class]]` property. It's value is a specification defined classification of an object and the values are: "Object", "Array", "Function", "Date", "RegExp", "String", "Number", "Boolean", "Error", "Math", "JSON", "null", "undefined" and "Arguments" for the `arguments` object. However - it's value for host objects like DOM elements or things like FormData and XMLHttpRequest can vary and is completely implementation-dependent (however it's good to notice that major browsers implemented same behaviour for these two).

More on that here: http://www.ecma-international.org/ecma-262/5.1/#sec-15.2.4.2

Having said the above, I am not sure if there's any way to overwrite that. One of the solutions (which is quite brittle btw) would be to overwrite `Object.prototype.toString` in React Native to properly classify host-provided objects (which in our case are FormData, XMLHttpRequest and possibly others).

**Comment by grabbou** [comment]
PS. We could still implement `toString` as @ide suggested and I proposed in PR #6778, but that would require @mzabriskie to add `|| val.toString && val.toString() === [...]` as a fallback to these checks.

**Comment by lacker** [comment]
It seems like there's no clear fix or bug here, and the outcome here would just be to support libraries like axios which is a "nice to have" rather than a "key requirement". I'm going to close this issue for now but if someone has a specific suggestion for fixing this I encourage them to open it as a new RFC issue.
