### ISSUE TITLE
PixelRatio.roundToNearestPixel returns non-integer on android

### ISSUE THREAD

**Issue by ColCh** [facebook/react-native#6606]
# Problem
[According to official documentation](https://facebook.github.io/react-native/docs/pixelratio.html#content), `PixelRatio.getPixelSizeForLayoutSize` should return integer value:

> Guaranteed to return an integer number

But it returns `18.666666666666668` for my android app...

Checked on android emulators 5.1.1 and 6.0

# Code snippet

```js
console.log(PixelRatio.roundToNearestPixel(scale * 60));
```

# Hotfix

```js
cast it explicitly to number: `Math.floor(PixelRatio.roundToNearestPixel(scale * 60))`
```

# Screenshot

*lineHeight* prop throws error on android. You really need a screenshot there?

# RN Version

*0.21.0* as well as *0.22.0*

# Where occurs

Nexus android emulator

# My platform

OS X El Capitan 10.11.1

**Comment by charpeni** [comment]
@facebook-github-bot label android

**Comment by charpeni** [comment]
@facebook-github-bot bugfix

**Comment by ColCh** [comment]
```
  /**
   * Rounds a layout size (dp) to the nearest layout size that corresponds to
   * an integer number of pixels. For example, on a device with a PixelRatio
   * of 3, `PixelRatio.roundToNearestPixel(8.4) = 8.33`, which corresponds to
   * exactly (8.33 * 3) = 25 pixels.
   */
  static roundToNearestPixel(layoutSize: number): number {
    var ratio = PixelRatio.get();
    return Math.round(layoutSize * ratio) / ratio;
  }
```
`Math.round` should return a number without fractional part ( aka integer)
I'm confused why it's returning `18.66666` on android, never see anything like this
I'm not sure if I can fix that.

**Comment by charpeni** [comment]
@ColCh Thank you!

**Comment by Kuzmin** [comment]
@ColCh I don't think that this is erroneous behaviour, if you read the documentation (https://facebook.github.io/react-native/docs/pixelratio.html), you see that they have this example for this method:

```For example, on a device with a PixelRatio of 3, PixelRatio.roundToNearestPixel(8.4) = 8.33, which corresponds to exactly (8.33 * 3) = 25 pixels.```

What's probably happening here is that you have a pixel ratio of 3 on your devices, and `18.666666666...` is equivalent to 56 pixels on those devices. I also noticed that you mention both `getPixelSizeForLayoutSize` and `roundToNearestPixel` in your message, maybe you could give a larget code snippet so that we could understand your use case better?

**Comment by ColCh** [comment]
OH my... I'm missed a method in documentation. Sorry for that, that's my sleep deprivation. :zzz: 
Thank you @Kuzmin for pointing out.

Entire issue becomes incorrect. It seems that all is working nicely. Closing it now. 

Sorry for noise :sleepy:
