### ISSUE TITLE
[MapView] Parent's panResponderCapture does't work

### ISSUE THREAD

**Issue by sulinixl** [facebook/react-native#6617]
----------------------------------------------------------

Device: iPhone Simulator(iOS 9.2)
Version: 0.22

----------------------------------------------------------
Just like the title, when component's children have `MapView`, then panResponderCaptures will not effect. 
It seems like MapView's gesture system is independent of ReactNative.
Below is an example:
```js
const React = require('react-native');
const {View, Text, MapView, ScrollView} = React;
const styles = React.StyleSheet.create({
    container: {
        flex: 1,
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: "stretch"
    },
    button: {
        height: 35,
        backgroundColor: '#DEDEDE'
    }
});
class MapTest extends React.Component {
    componentWillMount() {
        this.handler = React.PanResponder.create({
            onStartShouldSetPanResponderCapture: ()=>{
                console.log('onStartShouldSetPanResponderCapture', arguments);
                return true;
            }
        }).panHandlers;
    }
    render() {
        return (
            <View style={styles.container} {...this.handler}>
                <MapView style={{flex: 1}}/>
                <ScrollView horizontal={true} style={styles.button}>
                    <Text>BUTTON</Text>
                </ScrollView>
            </View>
        );
    }
}
module.exports = MapTest;
```
ScrollView will not response any gesture, but MapView will.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/mapview-parents-panrespondercapture-doest-work

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
