### ISSUE TITLE
default layout, padding is working wrong way with auto height

### ISSUE THREAD

**Issue by xueduany** [facebook/react-native#6619]
![image](https://cloud.githubusercontent.com/assets/1139866/14014367/05e1fd04-f1ed-11e5-9208-e82d44e4911d.png)

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/default-layout-padding-is-working-wrong-way-with-auto-height

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
