### ISSUE TITLE
[Android] Too many images caused Fresco's TooManyBitmapsException  

### ISSUE THREAD

**Issue by phones24** [facebook/react-native#6649]
My application is showing many images on many scenes (prerendered with Navigator).
From time to time, after couple of reloading almost all images got disappeared. 

I've added some logging to Fresco module and discovered 
`onFailure: failure: com.facebook.imagepipeline.common.TooManyBitmapsException`
for every image I'm trying to show.

Also I'm noticed that Fresco caches is basically not configured. It uses default configuration for ImagePipelineConfig.

I there a way to configure Fresco image pipeline for my app?

Also onLoadEnd for Image component provides no info on what's happened. Would be nice to have nativeEvent telling the cause of failure.

**Comment by ms88privat** [comment]
@phones24 did you find a solution?

**Comment by itinance** [comment]
Same issue here

**Comment by phones24** [comment]
@ms88privat, I optimized my app so it's not cached too many images. I also added some more JPEG compression and scale the images down a bit. I also wrote a path that adds error information to the event.

Still would be nice to have some control over fresco caching and logging from android app

**Comment by itinance** [comment]
@phones24 you wrote "I optimized my app so it's not cached too many images". How did you do that? Is it possible to control the <image> tag in how it will use any caches?

**Comment by phones24** [comment]
@itinance, I just cut the amount of prerendered scenes with big images. No magic here, unfortunately.

**Comment by narychen** [comment]
Same issue. 
And I found this would happen before react-native used Fresco to cache images. Just a few times of reloading JS will lead to this problem.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-too-many-images-caused-frescos-toomanybitmapsexception-

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
