### ISSUE TITLE
Issue with dragging while in Navigation scene using VerticalDownSwipeJump

### ISSUE THREAD

**Issue by aforty** [facebook/react-native#6663]
I have a navigation stack and one of my scenes comes in from the top via `Navigator.SceneConfigs.VerticalDownSwipeJump`. However in this scene, if I drag anything to the right, by accident or intentionally in a ScrollView then the scene begins to move down and, if dragged far enough, will pop the scene and return to the previous.

Playground: https://rnplay.org/apps/aC_jhw

If you drag to the right in scene 1 (via `FloatFromRight`) it behaves as expected.
If you drag to the right in scene 2 (via `VerticalDownSwipeJump`) it behaves in an unexpected way.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/issue-with-dragging-while-in-navigation-scene-using-verticaldownswipejump

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
