### ISSUE TITLE
[iOS] ListView + Lots of Images + overflow: hidden = App Freeze

### ISSUE THREAD

**Issue by sgonyea** [facebook/react-native#6664]
I've created a github repo that reproduces this problem. The has happened afaik since 0.20 (maybe even 0.19, I forget!)

https://github.com/sgonyea/react-native-listview-images-freezing

Setting `overflow: hidden` on the ListView's rows is a guaranteed way to trigger this problem, though I'm trying to recall if I've been able to trigger it without that.  More commonly, the app will simply exhaust available memory and crash without it :)

It's a partial lockup, not a full freeze / crash.  You can interact with some elements, but images won't load, you can't make network requests, and a navigator transition will trigger an actual lockup.

Here are some simple steps to reproduce the issue:

1. Run this app on your iPhone (not the simulator, you need a lot of images)

2. Scroll down several hundred photos.  If you do this really fast and get really far ahead of the image loading, you'll trigger the bug.

3. Hit your phone's Status Bar (scroll to the top) and then scroll down really fast.

4. Images will no longer load.  If you check XCode's memory profiler, you'll see memory use flatline.

5. Try shaking the phone + reloading.  The app will crash.  If this were embedded inside a real app, images would no longer load anywhere else.  And triggering a Navigator transition would also cause the app to lock up.

**Comment by sgonyea** [comment]
I've kicked this just about every possible way.  It seems to me that the only solution (for now) is to simply go without `overflow: 'hidden'` and risk an app crash from exhausting available memory.

There's a few hackey solutions that I could go with, but they still have some risk of a lockup.  IE, setting the render ahead distance to 0 will largely prevent the crash... and then prevent hitting the status bar to scroll to the top.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/ios-listview-lots-of-images-overflow-hidden-app-freeze

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
