### ISSUE TITLE
[Pods] Why pod spec is not exporting all library by default? 

### ISSUE THREAD

**Issue by zetachang** [facebook/react-native#667]
Currently if you install React Native by only depends on `React` in pod file, only `React/Core` will be pulled. 

Is there any reason the main pod spec specify `React/Core` as default subspec rather than exporting all library?

Some related issue might be #636 (where LinkingIOS is not included in any subspec)

p.s. [Suggestion from Cocoacpods](http://guides.cocoapods.org/syntax/podspec.html#default_subspecs)

**Comment by sahrens** [comment]
cc @tadeuzagallo

**Comment by brentvatne** [comment]
This [looks much more complete now](https://github.com/facebook/react-native/blob/master/React.podspec) but still doesn't include LinkingIOS. @ide any thoughts?

**Comment by ide** [comment]
There should probably be an entry under the podspec for LinkingIOS.

I think react diverges from the convention of shipping everything in the default spec because most apps won't use anything, and there are modules like adsupport that should be opt in.

**Comment by medington** [comment]
I'll be more than happy to submit a pull request which just adds the LinkingIOS to the React.podspec file if it will help get this resolved. Currently we have to fork just to add it ourselves.

**Comment by ide** [comment]
Closing this since the answer is: most apps don't want to pay the cost of pulling in all the subspecs, so pick and choose the subspecs that you need.

**Comment by strefethen** [comment]
@ide it sounds a little arbitrary considering deeplinking is a pretty core functionality on mobile. We use it in our app for push and geo notifications and to allow the RN portion of our app to navigate to other features within the app for those of us working to leverage RN despite not having a fully RN built app. The implication here isn't "all" subspecs be pulled in but that one which seems  quite core to mobile be included for simplicity. We are maintaining a full copy of the repo for our purposes because of this one issue.

I do think consideration of specific modules should be weighed independently from an "all" or nothing approach.

**Comment by strefethen** [comment]
@ide btw, I'm specifically referring to LinkingiOS and not the original subject of the thread asking for "all" subspecs since I agree not all of them should be included.

**Comment by ide** [comment]
Please send a PR that adds a LinkingIOS subspec -- you shouldn't have to fork in this case.

My general view was that what is core and what isn't will differ between apps and there may be superior linking solutions that emerge. It is very early to say what is "core" and what isn't. At the moment "core" mostly means "something that someone at Facebook wrote" and happens to be in this repo because it's simple to sync code that way. A very reasonable outcome would be for the ecosystem to grow like npm's where node tries to ship with a small stdlib and encourages development with npm.

Anyway that doesn't mean you should have to fork just to use LinkingIOS so I'm pretty sure a PR to add a subspec will be accepted.

**Comment by medington** [comment]
> Please send a PR that adds a LinkingIOS subspec

@ide @strefethen I already submitted a [PR](https://github.com/facebook/react-native/pull/1586) and it was merged several weeks ago.

**Comment by ide** [comment]
Cool -- thanks so much!
