### ISSUE TITLE
Update image-size library

### ISSUE THREAD

**Issue by tuckerconnelly** [facebook/react-native#6676]
svg <Images> cause the packager to fail with `invalid svg`. This is caused by an old version of the [image-size](https://github.com/image-size/image-size) library. This issue is outlined [here](https://github.com/image-size/image-size/issues/38) and was fixed in a more recent version. Just gotta do an `npm i -S image-size` :)

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/update-image-size-library

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
