### ISSUE TITLE
New version of NDK breaking builds?

### ISSUE THREAD

**Issue by ringzhz** [facebook/react-native#6697]
Hey, trying to follow the instructions for running the example apps is failing for me on Mac OS X "El Capitan". 

I was able to get it to work by downloading/setting up the last version of NDK (10e). It seems the recently released version (11b) isn't compatible.

Unfortunately, I don't see anyway to link people to the older version, I had to manipulate NDK's ZIP DL URL ( s/11b/10e/ ).

Not sure what you ought to do about it, just thought I'd give you a heads up.

**Comment by ide** [comment]
I believe Facebook is still on the legacy 10e NDK and will update RN after internally upgrading to 11b. For now, 10e is required.

**Comment by ringzhz** [comment]
Yeah. That makes sense. It's just that if you follow their instructions as they stand, they don't work, so maybe they should clarify in the mean time?

**Comment by satya164** [comment]
We've added download links to the correct NDK version in the docs, but this doesn't appear in the website cause it's only in master.

@bestander can we cherry-pick this to 0.23-rc and 0.22 - ce5dce9cd5b7cceac7c1442fc9b11a2808329693 ? We've already received about 4 issue reports due to this.

**Comment by bestander** [comment]
Makes sense but we try to do less cherry-picking.
0.23 is going to be stable within a week, let's only do it there.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/new-version-of-ndk-breaking-builds

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
