### ISSUE TITLE
Reformat Info.plist to use the same formatting as XCode

### ISSUE THREAD

**Issue by dantman** [facebook/react-native#6714]
Every time I `react-native upgrade` my project(s) I get an absolutely terrible diff like this for the Info.plist file:
![screen shot 2016-03-29 at 4 57 27 pm](https://cloud.githubusercontent.com/assets/53399/14127772/86fd7da6-f5cf-11e5-9c1a-488d8b4c5986.png)

This is because I changed a few settings and the format that react-native's boilerplate uses is different than the formatting XCode's plist tools output in.

It wouldn't be perfect, but these diffs could be made a lot better on upgrade simply by reformatting to use the same formatting that XCode uses. (Poke XCode to do a null edit to it, restore the comment, then make it the boilerplate the next version of react-native uses).

**Comment by satya164** [comment]
Up for a PR?

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/reformat-infoplist-to-use-the-same-formatting-as-xcode

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix.**
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot label label Icebox

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by facebook-github-bot-5** [comment]
@charpeni tells me to close this issue. If you think it should still be opened let us know why.
