### ISSUE TITLE
native addons: extending React with JXcore node.JS

### ISSUE THREAD

**Issue by jsbee** [facebook/react-native#676]
[Jxcore](https://github.com/jxcore/jxcore) runs node.js apps on iOS and almost everywhere else. There is a sample Cordova plugin project [here](https://github.com/jxcore/jxcore-cordova) . This sample project is much like a proof of concept. I would like to work on a possible React addon. 

I've checked most of the source codes. It's not that tricky to bring node.js support into React apps using jxcore's native interface. But instead of making this effort on a fork, I would like to do it as an addon. Is it possible to develop native addons for React? Otherwise please consider this as a feature request.

**Comment by vjeux** [comment]
it seems like jxcore is handling packaging js files and the js vm. Those are very integrated in React Native and seem pretty hard to plug and play at first glance. Can you tell us more about why you want to use jxcore? Do you have some use cases in mind?

**Comment by notduncansmith** [comment]
If JXCore allows us to run Node.js code that wouldn't otherwise be possible to run in React Native (e.g. PouchDB), that would unlock thousands of libraries for use in RN projects and would obviously be a huge gain for the project.  Determining whether that would in fact be the case, and whether it's worth the implementation effort, is another question of course, and one that would have to be answered at least in part by the React Native core team.

**Comment by jsbee** [comment]
`it seems like jxcore is handling packaging js files and the js vm. Those are very integrated in React Native and seem pretty hard to plug and play at first glance.`
@vjeux Why use JS engine from JXcore? We just need a bridge between JXcore and React-Native. JXcore instance only take a part for an application using node.js related stuff. I don't think it would require much change on react-native.

`If JXCore allows us to run Node.js code that wouldn't otherwise be possible to run in React Native (e.g. PouchDB), that would unlock thousands of libraries for use in RN projects and would obviously be a huge gain for the project.`

@notduncansmith That's what I'm after.  I couldn't find the link yet but a guy from Microsoft recently made a benchmark (PouchDB, JXcore) on iPhone 6 using PouchDB benchmark. I can say that the result was remarkable. He simply run the benchmark on iPhone that was originally designed for Desktop.

**Comment by vjeux** [comment]
This is the first time I've ever heard of JXCore and I still am not quite sure what it exactly does but if the interface is asynchronous and you can run it from obj-c, then it is possible to make a plugin for it: http://facebook.github.io/react-native/docs/nativemodulesios.html#content

**Comment by ktrzeciaknubisa** [comment]
Hi guys,

>  couldn't find the link yet but a guy from Microsoft recently made a benchmark 

@jsbee did you mean this one?: [Looking at JXCore’s perf](http://www.goland.org/jxcoreperf/)


> This is the first time I've ever heard of JXCore and I still am not quite sure what it exactly does 

@vjeux JXcore is a fork of node.js, but brings much more to the table. For example it can be compiled not only against V8 engine, but also SpiderMonkey, which opens the way to run node.js app on iOS devices (as @jsbee mentioned). Also runs on Android, if we speak about mobiles. Besides, no matter where it runs, it gives to the user wide range of new features, like multitasking (tasks running on different threads/instances within single process), packaging (which you have already noticed) - a single jx package, which can hold entire node solution can be executed as it would be a .js file.

**Comment by urbien** [comment]
Integration of jxcore into React Native is a fantastic way to launch jxcore project into the stratosphere. There is an unbounded interest in React Native. Our own initial React Native app on iOS shows that this all we have been dreaming of since iPhone came out and never managed to achieve with the phonegap and 1000 tricks to make HTML5 work like native. I personally spent many years on my life on that. React Native is great compromise and works amazingly well.
Yet we develop most of our modules in node now, and node-webkit is just not working on mobiles. Hense jxcore. JXcore + React native is heaven to us.
Specifically we need net and dgram modules working in React Native + JXcore. Why? Because we are developing P2P apps, specifically, bitcoin + bittorrent and ethereum + bittorrent apps.

**Comment by frantic** [comment]
Do you want to (a) use JXcore as runtime for React Native or (b) just communicate with JXcore from React Native running on JSC? 

For (a), it should be pretty easy to do. See [RCTJavaScriptExecutor](https://github.com/facebook/react-native/blob/master/React/Base/RCTJavaScriptExecutor.h) protocol, basically it's 3 async functions you need to implement, that boil down to something like:

```javascript
eval(code: string, callback: (result_json: string) => void)
```

See [list of runtimes we currently support](https://github.com/facebook/react-native/tree/master/React/Executors).

For (b) - it's even easier, you can just expose a native module.

**Comment by urbien** [comment]
@frantic after giving it some thought, I think for our project needs we will just use browserify and implement nodejs modules like dgram and net ourselves using Native Module iOS facility React Native provides and will create a levelDB (levelup/leveldown) polyfill on top of AsyncStorage. We used the same approach successfully with Chrome Apps. If you know of anyone working on these 3 modules, please connect us! If you know of a group that cares for Node development under React Native, please share a link.

**Comment by brentvatne** [comment]
Did anyone manage to get this working? Can we sit it on Github anywhere?

**Comment by urbien** [comment]
@brentvatne As stated in my prior comment, we proceeded to implement a subset of node.js modules in React Native iOS environment. 

- [AsyncStorage](https://github.com/tradle/asyncstorage-down) as a leveldown module and a [small wrapper for level apps](https://github.com/tradle/react-native-level). 
- a UDP module compatible with [Node.js Dgram](https://github.com/tradle/react-native-udp) 
- [forked and adjusted FS module on top of level](https://github.com/tradle/react-native-level-fs)
- [adapted DNS module to Node compliant API](https://github.com/indutny/dns.js)
- adapted [uTP module that works on top of UDP module](https://github.com/mafintosh/utp) to provide Node.js's NET module semantics for reliable transport, as an equivalent to TCP. 
- had to add socket multiplexing for NAT traversal support (ask me more about it)
- [adapted rUDP module](https://github.com/shovon/node-rudp), but it does not provide NET module API.

We had to overcome an [issue](https://github.com/facebook/react-native/issues/1055) with React Native packager. Another problem with it was that it does not support replacing core node.js modules with browserified versions of it. We used we used react-native-webpack-server to overcome this problem and we still had to hack our way through.

I would love to be able to relay our pain to React Native devs so that npm can be made to work well in React Native. Despite the difficulties we love React Native and are committing all our resources to make this a premier development environment for distributed apps (Dapps). This includes Bitcoin, Ethereum, Bittorrent, DHT access on mobile from React Native environment.

**Comment by urbien** [comment]
unresolved issue is with a [good source of randomness, see the issue we opened for it](https://github.com/facebook/react-native/issues/1189) 
Can anyone help?

**Comment by jacobbubu** [comment]
@urbien , can you share something more about how to combine browserify and react-native-webpack-server together?

**Comment by urbien** [comment]
@mvayngrib was doing actual work on that, I will ask him to describe it. Main problems were with replacing node core modules with their specific browserified versions. I do not think we achieved a 100% kosher result since as far as I recall, there is not way to specify anything but a 'browser' target, so you can't provide a 'react-native' version of a core module and a 'chrome-app' version of it, which is what we needed.

**Comment by mvayngrib** [comment]
@jacobbubu, @urbien [react-native-webpack-server](https://github.com/mjohnston/react-native-webpack-server) will let you use all the node core lib shims mapped in [node-libs-browser](https://github.com/webpack/node-libs-browser/blob/master/index.js) out of the box.

If you want to use others, like [fs](https://github.com/tradle/react-native-level-fs), [dgram](https://github.com/tradle/react-native-udp), [dns](https://github.com/indutny/dns.js), [net](https://github.com/mafintosh/utp), and maybe some others, you can use my [fork] (https://github.com/mvayngrib/react-native-node-libs) of node-libs-browser, or create your own fork. My devDeps in package.json look something like:

```json
  ...
  "node-libs-browser": "git://github.com/mvayngrib/react-native-node-libs",
  "react-native-webpack-server": "^0.2.0",
  ...
```

I've opened an [issue](https://github.com/webpack/node-libs-browser/issues/27) with the node-libs-browser guys on how to make this switcheroo more elegant, but they haven't responded yet.

**Comment by siuying** [comment]
If you want to see what JXcore is capable of, check out [this post](https://medium.com/@siuying/making-of-peerflix-for-ios-or-how-to-embed-any-nodejs-app-in-ios-app-36074f18ee3d). tl;dr, it run peerflix natively on iOS.

The benefit is that we run many native package (udp, http, openssl, leveldb, sqlite ...etc) out of the box, no need to stub them with fake library will bring many great nodejs stuff to mobile.
