### ISSUE TITLE
Touch events don't bubble up when nesting TouchableHighlight components

### ISSUE THREAD

**Issue by sevachon** [facebook/react-native#6796]
I would expect unhandled touch events to bubble up to the parent when a given TouchableHighlight component doesn't handle them. All the events currently stop at the direct container.

```
<TouchableHighlight onLongPress={this._onLongPress}>
     <TouchableHighlight onPress={this._onPress}>
           <Text>
               Press or LongPress me
           </Text>
     </TouchableHighlight>
</TouchableHighlight>
```
Is there a particular reason why we don't allow the events to bubble up and enable the above scenario?

**Comment by brentvatne** [comment]
Why not combine `onLongPress` and `onPress` on one `TouchableHighlight`? What's the use case?

I'm not sure of the reason why, but if you were to write your own `TouchableHighlight` you could override `onStartShouldSetResponderCapture` on the container View and make it return false.

**Comment by sevachon** [comment]
Thanks Brent. Here's the use case:
 
1. You have a common container component that is a `TouchableHighlight` and that needs to handle onLongPress. Imagine this is a container used to show a tooltip/context menu with some actions on long press.
1. This common container component is used in a number of places in a generic way and in some cases one of its children can be a `TouchableHighlight` that needs to handle onPress. Say an image preview that will open the full image on click.
 
At this point, the two `TouchableHighlight`'s are independent and we need the unhandled events to bubble up. I wasn't sure whether there was a good reason not to default to this, which seemed like the natural behavior to me.
 
True. If one were to write their own `TouchableHighlight`, he could override `onStartShouldSetResponderCapture` or `onStartShouldSetResponder` and set it to false based on whether the event at hand (e.g. long press) can be handled.

**Comment by brentvatne** [comment]
Somewhat related, check out [this great talk by Andy Matuschak](https://www.youtube.com/watch?v=uBYPqb83C7k) about the challenges of implementing a gesture system.

So this is what I think is going on: the touchable state is local to the touchable component, and touchable components are completely unaware of others and eager to become responder for any touch event that is given to it. Currently, there can only be one responder for any touch event. So when you touch the inner `TouchableHighlight`, it captures the touch which prevents the outer component from even having a chance to transition from the ["not responder" state of its state machine](https://github.com/facebook/react-native/blob/master/Libraries/Components/Touchable/Touchable.js#L273-L293). When you release the touch, it simply ends the gesture.

> I wasn't sure whether there was a good reason not to default to this, which seemed like the natural behavior to me.

My guess would be that it is a simple model that works most of the time. Maybe @vjeux can speak more to this.

> If one were to write his own TouchableHighlight, he could override onStartShouldSetResponderCapture or onStartShouldSetResponder but would he be able to tell which events is coming (e.g. long press) in order to make the determination of whether there's a handler for it and therefore whether to return true or false? I couldn't find a way to do this.

I'm actually not sure that this approach would work and don't have time at the moment to look into it :( Let me know if you find a solution to it.

**Comment by MayeuldP** [comment]
Hey all, I can't yet create new issues for my problem... I enjoy this post, to ask my question which is kind same....

I have too a `TouchableOpacity onPress={() => this._chargeMovie}
                                underlayColor='#dddddd'>
                      <View>....<Image/><View><Text>...</Text></View></View><TouchableOpacity` in a method which is in a class... And there is my chargeMovie method : ` _chargeMovie()
    {
        this.props.navigator.push({id:'MovieSelected'});
    }` , which is too in the same class. And so when I click the item (row) detect the click, but don't push my new activity... :/ Any ideas... I can put more code, if it's necessary... @brentvatne Thank's :)

**Comment by brentvatne** [comment]
@MayeuldP - full code for that would help :) can you create a StackOverflow with that?

**Comment by MayeuldP** [comment]
@brentvatne I'm not enough activ on stack overflow to could... :/ But I resolved it :) Instead of using
`class MyClass extends Component` , i did 'var MyClass= React.createClass({' and so re-think all my code, changing  `_myFunction()` by `_myFunction: function()`, and the transition/Navigator(push()..)  work well now ! So I'm trying to send props with getInitialiseState now. If you have any tips ^^ Thank's !

**Comment by brentvatne** [comment]
@MayeuldP haha :) glad you solved it. It's not necessarily a bad thing to do :) if that works for you, then go for it! It can just potentially be problematic because if the state is only updated by the initial value of the prop then it may be confusing unless you call it something like `initialValue`

**Comment by MayeuldP** [comment]
@brentvatne Hey, yep, but one error dissapears, another come... I tried to install this module : https://github.com/corymsmith/react-native-icons and it was almost working, then I had this error : 

`Requiring unknown module : "./node_modules\react-native\node_module\react-transform-hmr\lib\index.js" `... I tried `"npm install" "npm cache clean"`... I deleted all the files concerne related to react-native-icon, but I still have this error...; Any idea ? I found nothing on the web for resolved it...

Otherwise, thank's for the explain of `getInitialState: function(props)` :)

**Comment by MayeuldP** [comment]
OMG, found it ! I just disabled Hot reloading ! But don't understood why it was doing this erros :/ !

**Comment by DominicTobias** [comment]
Here's another use case - I need to close a tooltip like you would on the web by listening to document clicks. I need the next touch to still register on whatever was touched, but I also need the root to know about the touch so that the tooltip can be closed.

Due to this limitation I'd no idea how to implement a solution other than:

- Extend every touchable and perform some tooltip closing logic in case one is open
- Have an opaque background touchable which picks up the next touch and somehow passes it on the underlying component

**Comment by lacker** [comment]
This issue seems like it has been sufficiently answered, so I am going to close it.
