### ISSUE TITLE
[Android] overflow visible doesn't work

### ISSUE THREAD

**Issue by skv-headless** [facebook/react-native#6802]
second view ```{overflow: 'visible'}```

![bug](https://cloud.githubusercontent.com/assets/1488195/14264851/11dccf2a-fab8-11e5-9984-fdad544c2507.jpg)

**Comment by ide** [comment]
Overflow is not supported on Android: https://facebook.github.io/react-native/docs/known-issues.html#the-overflow-style-property-defaults-to-hidden-and-cannot-be-changed-on-android

**Comment by cherniv** [comment]
@ide the link is broken, is it still relevant?

**Comment by jreziga** [comment]
Still not working. Drawing outside a view on Android is nearly impossible...

**Comment by aymericbouzy** [comment]
Are there any practical recommendations ?

**Comment by tioback** [comment]
@aymericbouzy - I managed to get something similar to this behavior using elevation. Checkout the [gist](https://gist.github.com/tioback/6af21db0685cd3b1de28b84981f31cca).

**Comment by joncursi** [comment]
Would it be possible to update the documentation to call this out? [From what I see here in the docs](https://facebook.github.io/react-native/docs/view.html#style), `overflow: 'visible' | 'hidden'` would be available on both platforms.

**Comment by DeDuckProject** [comment]
How is this issue closed? any solutions?

**Comment by bd-arc** [comment]
This is a real deal breaker since advanced user interfaces like this one are just impossible to create on Android, while being pretty easy on iOS.
![image](https://cloud.githubusercontent.com/assets/7899844/19911034/3b4df760-a091-11e6-9f37-0e3dc1763f4d.png)

Are there really no plans to find a solution to this matter? I find it hard to believe that Facebook is able to cope with it...

**Comment by aymericbouzy** [comment]
I believe the interface you are showing can be obtained with absolute positioning.

**Comment by jreziga** [comment]
No he can't there is always a problem with zindex and ontouch methods it's very messy...

**Comment by aymericbouzy** [comment]
can't you abstain from using zIndex and simply put objects in the order in which they should be displayed ?

**Comment by bd-arc** [comment]
@aymericbouzy Unfortunately not, since you can't overlap views on Android. This really proves problematic for this kind of layout, particularly when soft shadows are involved. There are many issues at stake: no visible overflow (the real bummer), buggy z-indexes, absolute positioning randomness...

Let me show you another example of a UI I am trying to implement, but for which I am currently clueless.
![image](https://cloud.githubusercontent.com/assets/7899844/19923629/accc6622-a0e8-11e6-82b3-e7ac55c45002.png)
![image](https://cloud.githubusercontent.com/assets/7899844/19923171/7ab68200-a0e6-11e6-8e3e-07f03521133c.png)
![image](https://cloud.githubusercontent.com/assets/7899844/19923650/bfd909be-a0e8-11e6-96e6-fd67d42fff73.png)

On iOS, I would simply use negative margins or even absolute positioning with a global container; this would be pretty easy. But because of the overflow issue, neither of this classic methods will work on Android. Do you have any idea that would allow me to circumvent these limitations?

**Comment by aymericbouzy** [comment]
@bd-arc I have absolutely no experience building such complex UI, and I'm not saying it's simple.

The way I would go though would be the following : putting each view in a different layer, each layer being an absolute positioned view taking the full width and height of the display, and positioning the visible views inside each layer. Since each layer takes the full dimensions of the display, overflow is not a problem.

I fully agree this solution is a pain, but I believe it works. Please tell me if I'm wrong :)

**Comment by jreziga** [comment]
@aymericbouzy "each layer being an absolute positioned view taking the full width and height of the display" If you do that you won't be able to touch any button, or at least only the one with higher zIndex, even if you see the underlaying touchable element.

**Comment by aymericbouzy** [comment]
@bd-arc you're right. Then you can add touchable views on the uppermost layer upon the visible parts, but the interface is not going to be very responsive ... this is definitely not a long-term solution.

**Comment by bd-arc** [comment]
@aymericbouzy Unless I'm mistaken, you're solution is built on something that's pretty complicated: I don't see any reliable way of retrieving complex content's height, particularly before it is rendered (doing it after, assuming this would be both possible and reliable, would lead to jerkiness issues - believe me, I've been there :)

I would rather go with clever margins and paddings, since this seems easier to maintain, but it would be an incredibly tedious task, with lots of limitations. Furthermore, that still leaves no room for soft shadows. And we haven't even talked about orientation change or responsiveness...

**Comment by aymericbouzy** [comment]
@bd-arc indeed it is very complicated, and unmaintainable, and I wouldn't go this way on a general basis. I'm just saying this is the solution I've found for a much simpler use case than yours.

**Comment by talarari** [comment]
im having a similar issue, im using position absolute to draw outside a view.
everything works fine, untill i try to set onLayout property on the view, then it just clips whatever is outside the view.

any suggestions?

**Comment by br4nnigan** [comment]
A property that's only supported in one OS is not very useful ... don't claim react-native supports it then.

**Comment by jcsmesquita** [comment]
Been bitten by this multiple times, there should be a warning in RN if overflow: 'visible' is set on Android.

**Comment by RevanScript** [comment]
I hate Android. It doesn't support normal shadows, blur and even overlapping now

**Comment by codesinghanoop** [comment]
Any updates ..?

**Comment by ide** [comment]
There is a rewrite of Android's View library called Nodes. It is still not ready yet but maybe will be later this year if it is a success. Check back later this year.

**Comment by gonglong** [comment]
I think some updates needs to be done on the document https://facebook.github.io/react-native/docs/layout-props.html that **overflow** dose not work on Android currently 

> overflow?: enum('visible', 'hidden', 'scroll') 
> 
> overflow controls how a children are measured and displayed. overflow: hidden causes views to be clipped while overflow: scroll causes views to be measured independently of their parents main axis. It works like overflow in CSS (default: visible). See https://developer.mozilla.org/en/docs/Web/CSS/overflow for more details.

**Comment by codesinghanoop** [comment]
Hey checkout this https://www.npmjs.com/package/react-native-zindex-views it would help you.

**Comment by Dygerati** [comment]
Just looking for a little clarity, wouldn't Android's `setClipChildren` provide something similar?
https://developer.android.com/reference/android/view/ViewGroup.html#setClipChildren(boolean)

**Comment by redpandatronicsuk** [comment]
@Dygerati have you found out more about this? It looks like either `clipChildren` or `clipToPadding`  control overflow on Android: https://stackoverflow.com/questions/18048997/android-view-disappearing-when-go-outside-of-parent
The Android overflow bug has been bothering me for a while now, a fix would be nice.

**Comment by apexskier** [comment]
Can this be reopened?

**Comment by Noitidart** [comment]
Is this `overflow:visible` issue on Android closed by this commit - https://github.com/facebook/react-native/commit/30044fd531c22c4c5e8f1ede206fa7c2c3fd3aa8 ?

**Comment by JCMais** [comment]
The commit referenced above (https://github.com/facebook/react-native/commit/30044fd531c22c4c5e8f1ede206fa7c2c3fd3aa8) doesn't fixes this issue when using `overflow: visible` with images.

**Comment by ColCh** [comment]
AFAIK it will fix overflow:hidden in case there is border radius defined.

And about overflow:visible on android, it may be impossible to resolve because of android native views specific, but I can be wrong in this point

**Comment by SimplGy** [comment]
Found a working link to Ide's known issues article. It's a wontfix: https://web.archive.org/web/20160702114556/http://facebook.github.io:80/react-native/docs/known-issues.html#the-overflow-style-property-defaults-to-hidden-and-cannot-be-changed-on-android

**Comment by slorber** [comment]
RN50 overflow visible seems broken for me, even with something else than images. See https://github.com/facebook/react-native/issues/17074

**Comment by realappie** [comment]
Why does it always feel like android is just not a first class citizen in `react-native`

The way react-native is advertised in the readme 

> The focus of React Native is on developer efficiency across all the platforms you care about 

Doesn't come over with the way it actually functions at all, every time I am trying to build something for both platforms. Its super easy to do in iOS but for some reasons I require a ton of hacks to make things as trivial as this work on android. Now don't get me wrong, I think `react-native` is a fantastic tool. But I think the community would appreciate it more if it worked more consistently across different platforms.

**Comment by wmonecke** [comment]
Still no updates on this? I literally have to redo a dumb-component from scratch because of this... just cuz Android.

**Comment by nikasvan** [comment]
Any updates on this?

**Comment by adidoes** [comment]
Still no change?

**Comment by lugrugzo** [comment]
"Overflow" feature for Android won't be supported for next a few years. So find a tricky way to implement your design.

**Comment by dev4xy** [comment]
+1 !!!

**Comment by arielLeverate** [comment]
I found this workaround - https://github.com/entria/react-native-view-overflow
But note that it probably will require a bit of of restructuring of your code.
