### ISSUE TITLE
[Android] Invalid index 2, size is 1

### ISSUE THREAD

**Issue by tomazahlin** [facebook/react-native#6842]
I would like to ask, what this error means, because I get it all the time and everytime when I find out, something else is wrong. It takes me hours to debug application.........

**Comment by tomazahlin** [comment]
I would write more information, but not really sure how to start.

I am using react-native 0.24.0-rc and I am developing in an emulator for Android.

The error happens, when:
- Invalid import of a component
- I do not or provide multiple children to <TouchableWithoutFeedback>, because it expects only 1.
- I try to render a value which is not defined.

To me it looks like the behavior is changing almost every time we update react native to a newer version.

**Comment by BigPun86** [comment]
+1

**Comment by BigPun86** [comment]
Does this occur when u are in Debug mode?

**Comment by tomazahlin** [comment]
Yes, it occurs in Debug mode.

**Comment by exoer** [comment]
I have this problem too

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-invalid-index-2-size-is-1

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by zhaolei1177** [comment]
hi,@BigPun86, i have this problem, too. did u resolve this issue?

**Comment by BigPun86** [comment]
Sorry my friend, i never found out how to fix this. I simply cleared watchman, removed the the node module and made an update to the latest react native. after that installing it with yarn it worked ;)
