### ISSUE TITLE
XMLHttpRequest PUT Error (Android)

### ISSUE THREAD

**Issue by pangers** [facebook/react-native#6855]
Hi,

I am trying to use XMLHttpRequest for a PUT API. When running the PUT API with a method body on ANDROID simulator, I am getting the error "method put must not have a request body."
![screen shot 2016-04-07 at 5 23 33 pm](https://cloud.githubusercontent.com/assets/7816958/14343613/8c39d8e2-fce5-11e5-9efc-98f64f25a1f7.png)
The exact same code works fine for iOS.

I am running React Native 0.23.

Am I missing something?

Thanks

**Comment by dsibiski** [comment]
@facebook-github-bot stack-overflow

**Comment by pangers** [comment]
@dsibiski Isn't there a fundamental problem with the implmentation of XMLHttpRequest? Why is the error telling me the PUT method shouldn't have a body? Doesn't PUT typically have a body attached to the request?

**Comment by dsibiski** [comment]
@pangers Thanks for your reply, you're right, however it seems like this issue was addressed here: https://github.com/facebook/react-native/pull/4518

It looks like it made it into 0.23 stable, are you absolutely sure you are on this version? Can you check the code in your node_modules and see if the fix from that PR is there?

**Comment by pangers** [comment]
@dsibiski Yes I can confirm I am using 0.23 and that PR looks like it is in my node_modules folder.

However the problem I am facing seems to be slightly different to the one in the issue. I AM providing a body to the PUT request, but the error message is telling me that "method put must not have a request body." Whereas in the issue, the an error was occurring when a body WAS NOT attached to a POST/PUT request.

**Comment by dsibiski** [comment]
@pangers Can you paste here the code where you are making this call, that might help.

**Comment by pangers** [comment]
@dsibiski Yep sorry, I should have done that earlier. Here it is.

`updateDatabase: function(body) {
		const url = 'http://myurl.com';
		return Rx.Observable.create(observer => {
                        const request = new XMLHttpRequest();
		        request.open('put', url);
		        request.setRequestHeader("Content-type","application/json");
	
			request.onload = function() {
				if (this.XMLresponseOk(request)) {
					observer.onNext(this.XMLParse(request));
					observer.onCompleted();
				} else {
					observer.onError('error');
				}
			}.bind(this);
			request.onerror = function() {
				observer.onError('error);
			};
			request.send(JSON.stringify(actualBody));

			return function() {
				request.abort();
			}
		});
	}`

**Comment by dsibiski** [comment]
Thanks, what happens if you use `PUT` in uppercase in the line `request.open`?

**Comment by pangers** [comment]
@dsibiski It works!! Thanks for pointing that out. Perhaps in should noted in the documentation that the method should be specified in capitals? Or perhaps the implementation should be able to handle any combination of capital vs non-capita letters?

**Comment by dsibiski** [comment]
You're welcome :+1: 

I strongly think it should handle any case, here is an example in iOS where we're actually upcasing the method value before checking it in an `if` statement:

https://github.com/facebook/react-native/blob/master/Libraries/Network/RCTNetworking.m#L200

So that indicates to me that the same should be going on for Android. I'll work on a PR for this and have it submitted later this afternoon, unless you want to take a stab at it! :smile:

**Comment by pangers** [comment]
@dsibiski I'd love to try and contribute, but I'm not quite confident I'd get it right. My guess from looking at:

https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/modules/network/NetworkingModule.java#L151

is to create a temporary variable

`String uppercaseMethod = method.toUpperCase();`

and replace every use of 'method' to 'uppercaseMethod' in that method (pun intended)?

**Comment by dsibiski** [comment]
Actually, I think it's simpler than that. I think the problem comes In the commit I linked to earlier. We really only need to uppercase the value before we use it in a conditional. So I think this line is really the only one that needs it to be changed: https://github.com/qbig/react-native/blob/bcbd9cf9bf9725c71c700f0ca57e6f2a4e0a5451/ReactAndroid/src/main/java/com/facebook/react/modules/network/RequestBodyUtil.java#L121

**Comment by dsibiski** [comment]
@pangers Do you think you'll be able to knock this out with the help of my last comment? If not, let me know and I can do it.

**Comment by pangers** [comment]
@dsibiski Ah yeah, you can go ahead and make the change. Thank you!

**Comment by satya164** [comment]
We could just always uppercase it in JS before sending it to Native.

**Comment by dsibiski** [comment]
@satya164 Good point! I'll do that instead, gonna cut a PR shortly.
