### ISSUE TITLE
Standard react-native init command produces app that is rejected by Apple Store

### ISSUE THREAD

**Issue by obromios** [facebook/react-native#6892]
I asked [this question](http://stackoverflow.com/questions/36191348/set-or-remove-uiviewcontrollerbasedstatusbarappearance-key-introduced-by-react-n) on stack overflow, but received no answer, so perhaps it is an issue:

According to [this site]( https://github.com/jhabdas/react-native-webpack-starter-kit), the command ```react-native init``` does not set the correct value of the ```UIViewControllerBasedStatusBarAppearance``` IOS key. Furthermore the site states that failure to do so leads to Apple Store rejection. If this is correct, then how should it be fixed?  If it is false, then I will raise an issue at  [the site](https://github.com/jhabdas/react-native-webpack-starter-kit) and ask them to correct their README file.

**Comment by ide** [comment]
Has this actually led to rejection? I don't see why it would. It's not a private API.

**Comment by dsibiski** [comment]
I don't see how this could lead to a rejection as Apple explicitly states that it is an option that you can turn on or off based on your preference:

> NOTE
If you prefer to opt out of having view controllers adjust the status bar style—and instead set the status bar style by using the UIApplicationstatusBarStyle method—add the UIViewControllerBasedStatusBarAppearance key to an app’s Info.plist file and give it the value NO.

https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/TransitionGuide/AppearanceCustomization.html

**Comment by dsibiski** [comment]
@facebook-github-bot answered

**Comment by obromios** [comment]
Thank you. I have now asked for the [README file](https://github.com/jhabdas/react-native-webpack-starter-kit/issues/85) to be corrected.

I note that the facebook-github-bot needs some fine tuning as you will see from the first post, I did ask a question on stackoverflow and waited for several weeks before raising the issue here. However, I will not raise an issue about this :).

**Comment by jhabdas** [comment]
@ide yes, Lumpen Radio from the RN showcase was rejected until I removed the key or flipped the value over. It took me hours to discover while walking down the magical yellow brick road that is App Store approval because of something so simple as a console error inside Xcode. Would it happen again today? Personally, I'd rather not find out.

**Comment by jhabdas** [comment]
To add further clarification, emphasis here on **console error inside Xcode**. If the Xcode console error on build no longer occurs when the aforementioned setting is set by RN init I don't see it causing an issue. Nevertheless, prudence is advised.

**Comment by ide** [comment]
Could you paste the rejection message from Apple here? I don't understand why a [documented public API](https://developer.apple.com/library/mac/documentation/General/Reference/InfoPlistKeyReference/Articles/iPhoneOSKeys.html#//apple_ref/doc/uid/TP40009252-SW29) would lead to rejection.

Since dozens of other RN apps aren't getting rejected and UIViewControllerBasedStatusBarAppearance is a public API, I'm guessing that either you got a bad reviewer (which sucks and honestly some simple dynamic/static analysis can do most of the job) or there was some other non-deterministic bug in your app that led to rejection the first time.

**Comment by jhabdas** [comment]
I don't have any screenshots as that happened approximately a year ago  around the release of 0.11, IIRC). But, as mentioned, when I was rejected the key and it's preset value  were causing an error to log in the Xcode console.  If that's no longer happening I'd say you're in the clear.
