### ISSUE TITLE
Some props for RCTView subclasses not updating after initially being set

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#690]
Example project: https://github.com/brentvatne/PropsBugs

Callbacks: https://github.com/brentvatne/PropsBugs/blob/master/BVLinearGradient.m#L19 
`setACallback` is is never called.

~~Arrays: https://github.com/brentvatne/PropsBugs/blob/master/BVLinearGradient.m#L31
`setColors` is only ever called once.~~ - @tadeuzagallo resolved this in irc: [I had to add a diff function](https://github.com/brentvatne/PropsBugs/blob/master/LinearGradient.ios.js#L39-L46)

`setAString` works as expected.

**Comment by brentvatne** [comment]
![props](https://cloud.githubusercontent.com/assets/90494/6999311/21949a2e-dbba-11e4-88f7-d6060a3ba11c.gif)

**Comment by tadeuzagallo** [comment]
Hey, for the differ you can just use [`deepDiffer`](https://github.com/facebook/react-native/blob/master/Libraries/Utilities/differ/deepDiffer.js), because in your function `color1` and `color2` are actually arrays, so `color1 !== color2` will always be true in that case.

For the callback, you can't simply convert js functions to `RCTResponseSenderBlock`s... since you already explained that this was just test a test, and the actual goal is to notify that a video has finished playing, you should use events. you can define new events with `- customDirectEventTypes` and `- customBubblingEventTypes`, for your case, the first should be more suitable, any way, you can check the descriptions on [`RCTViewManager.h`](https://github.com/facebook/react-native/blob/master/React/Views/RCTViewManager.h#L59-L92). Then you just use the `RCTEventDispatcher` to emit the event with the name you have registered (as the key on the dictionary) and add a property to your native component, with the value you have registered.

You can look at `RCTSwitch` as a basic example, the `change` event is defined on [`RCTUIManager.m`](https://github.com/facebook/react-native/blob/master/React/Modules/RCTUIManager.m#L1149-L1154), the event is emitted in the [`RCTSwitchManager.m`](https://github.com/facebook/react-native/blob/master/React/Views/RCTSwitchManager.m#L31-L34) and the callback is registered on [`SwitchIOS.ios.js`](https://github.com/facebook/react-native/blob/master/Libraries/Components/SwitchIOS/SwitchIOS.ios.js#L101). Note the use of `topChange` and `onChange` according to the event definition.

**Comment by brentvatne** [comment]
Thanks @tadeuzagallo - giving this a try now.

Also...

![preview](https://cloud.githubusercontent.com/assets/90494/7009177/3e429548-dc4d-11e4-9811-48531cd892db.jpg)

**Comment by brentvatne** [comment]
@tadeuzagallo - thank you very much for the detailed response! I have this working now on [react-native-video](https://github.com/brentvatne/react-native-video/blob/master/RCTVideo.m#L54-L79) - both for progress events (to get currentTime updates on the video) and onLoad (to get any initial data about the video - duration, whether it supports fast forward etc).
