### ISSUE TITLE
[Android]PanResponder NativeEvent doesn't have any data.

### ISSUE THREAD

**Issue by aboutqx** [facebook/react-native#6933]
It seems that the `NativeEvent` parameter doesn't have any data like `LocationX`,`LocationY` when using the `panResponder` example of doc.The `gestureState` works however.

**Comment by satya164** [comment]
Can you post in more detail?

**Comment by aboutqx** [comment]
![image](https://cloud.githubusercontent.com/assets/4919094/14601804/e5a16e40-0596-11e6-87fb-1512c1032c2b.png

**Comment by aboutqx** [comment]
![image_20160418185358](https://cloud.githubusercontent.com/assets/4919094/14601881/3d12252a-0597-11e6-9933-04fcc0b7a9e0.png)
the `onPanResponderMove`'s evt parameter has no data

**Comment by lacker** [comment]
This works for me. If you can provide a small sample app that reproduces the problem - a rnplay.org link would be great - then I think I could make some progress here. Since it's been a while since anyone commented (sorry!) I am going to close this issue, but if you do have a way to repro this feel free to reopen it.
