### ISSUE TITLE
[NavigationExperimental] StackReducer should be able to handle initial action

### ISSUE THREAD

**Issue by arbesfeld** [facebook/react-native#6985]
Right now the NavigationStackReducer can take an `initialState` as a parameter: https://github.com/facebook/react-native/blob/master/Libraries/NavigationExperimental/Reducer/NavigationStackReducer.js#L69

I'd like the StackReducer to return a different state depending on the initial action.

@ericvicenti @hedgerwang is that something you'd want to support in this component? Perhaps instead of `initialState` we just let people return the initial state from `getReducerForState`, and then they could also use the action to influence the state?

**Comment by domchristie** [comment]
> I'd like the StackReducer to return a different state depending on the initial action.

This’d be nice, particularly when dealing with nested stacks. For example, a child stack may not have a `lastState` but may need to activate one or more child states depending on the action. (Hope that makes sense!)

**Comment by domchristie** [comment]
> I'd like the StackReducer to return a different state depending on the initial action.

Just to add to this: I’m currently wrapping the StackReducer in another reducer:

```js
const stackReducer = NavigationExperimental.Reducer.StackReducer({ … })

export default function (state, action) {
  if (SOME_CONDITION) {
    /* return a custom state */ 
  }
  return stackReducer(state, action)
}
```

**Comment by vshy108** [comment]
@domchristie I am using your way to implement my log out feature. thank you so much.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/navigationexperimental-stackreducer-should-be-able-to-handle-initial-action

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
