### ISSUE TITLE
I confuse about some code in MessageQueue._genMethod

### ISSUE THREAD

**Issue by MegatronKing** [facebook/react-native#7028]
Hi, I am studying the source code. When called NativeModules with callback params,  the first is success and the second is fail, but  the function  _genMethod handle with those params reversedly, and __nativeCall did it too. There is none problem when we called because reversed twice, but it is so strange!

_genMethod
```
let lastArg = args.length > 0 ? args[args.length - 1] : null;
let secondLastArg = args.length > 1 ? args[args.length - 2] : null;
let hasSuccCB = typeof lastArg === 'function';
 let hasErrorCB = typeof secondLastArg === 'function';
```

lastArg  we set logError, and secondLastArg is the callback function, such as:

```
RCTAppState.getCurrentAppState(
  (appStateData) => {
    AppState.currentState = appStateData.app_state;
  },
  logError
);
```

**Comment by damusnet** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-6** [comment]
Hey @MegatronKing and thanks for posting this! @damusnet tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
