### ISSUE TITLE
BorderBottom (and Top, Left, Right) not working in TextInput but Border is 

### ISSUE THREAD

**Issue by anttitakalahti** [facebook/react-native#7029]
I have a TextInput and I'm trying to add bottom border to it by adding style borderBottomWidth: 1, borderBottomColor: 'black' and they do nothing. However BorderWidth: 1, BorderColor: 'black' work just fine.

**Comment by anttitakalahti** [comment]
the same happens with borderRadius and borderBottomRightRadius. I can add borderRadius just fine but borderBottomRightRadius does nothing (and gives no warnings). This happens with a real iphone 6s+ and with iphone 4s simulator.

**Comment by iralution** [comment]
I have the same Issue. A quick workaround for me was, to wrap my TextInput in a view and pass the borderBottomX style attributes to the view component

**Comment by bolismauro** [comment]
+1

**Comment by LeoLeBras** [comment]
+1

**Comment by kevinvangelder** [comment]
I'm also having this issue with a `<Text>` component.

**Comment by viix** [comment]
+1

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/borderbottom-and-top-left-right-not-working-in-textinput-but-border-is-

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
