### ISSUE TITLE
Why isn't POPAnimation available in the OSS fork?

### ISSUE THREAD

**Issue by mcz** [facebook/react-native#708]
Hey Guys.

Just curious, why isn't POPAnimation available in the OSS fork as it is referred on:

https://github.com/facebook/react-native/blob/master/Libraries/Animation/POPAnimationMixin.js#L17

Thanks so much for this great tool!

**Comment by vjeux** [comment]
Multiple reasons:

1) We haven't figured out how to deal with obj-c dependencies so it was hard to embed POP
2) Pop runs in the main process, however there's a way on iOS to run code in a completely different process via CoreAnimation.
3) It doesn't work on Android

But ultimately, we haven't figured out a good general api for doing animations. Instead of exposing some half backed version (that are working) and trashing people in open source, we prefer to wait and iterate on it internally until we find something that we want people to use and we want to maintain.

**Comment by mcz** [comment]
Perfectly clear. Thanks so much and keep up with this awesome work!

**Comment by brentvatne** [comment]
https://github.com/facebook/react-native/issues/1365#issuecomment-104792251

**Comment by mcz** [comment]
Thanks Brent!

**Comment by brentvatne** [comment]
No problem @mcz :smile:
