### ISSUE TITLE
<Image> src / source Warning when it's not needed.

### ISSUE THREAD

**Issue by markbrown4** [facebook/react-native#7106]
I get the following warning for the component below:

> The &lt;Image&gt; component requires a `source` property rather than `src`

```js
function HttpImage(props) {
  let url = props.src;
  if (props.src[0] == '/') {
    url = API.getWebRoot() + props.src
  }
  return (
    <Image {...props} source={{ uri: url }}>
      { props.children || null }
    </Image>
  )
}
```

A custom component `<HttpImage src="blah" />` shouldn't display a warning.

**Comment by mkonicek** [comment]
IMHO you shouldn't be passing `{...props}` to `Image`, just remove the `src` property.

**Comment by DannyiCracked** [comment]
Seems like an arbitrary rule to enforce, no?

Most other components would simply ignore a prop if it isn't required in its lifecycle. I understand the `console.warn` is there to help a user that may suffer from logical confusions between `<img src=...` and `<Image source...`, but if both are provided the `<Image>` component should simply ignore the `src` attribute since it isn't used anywhere anyway.

Putting the onus on a user using a library component to make sure its "valid" really shouldn't be the case, imo.

**Comment by markbrown4** [comment]
I'm not too fussed, I was actually confused about the *source* of the error haha.

> IMHO you shouldn't be passing {...props} to Image

A proxy component like this is designed to simply pass things through to the child.

> just remove the src property from the props object

Immutability makes that a little cumbersome:

```js
let props2 = {...props};
delete props2.src;
```

**Comment by ide** [comment]
`let {src, ...props} = this.props` works too.

**Comment by markbrown4** [comment]
Neat, I didn't know you could pull a property off an object like that.
I needed to rename props to something else in this case but that works.
