### ISSUE TITLE
testID information not visible on UIAutomator in Appium.

### ISSUE THREAD

**Issue by kahn004** [facebook/react-native#7135]
Hi there,

We are doing an automation test for Android (API version 21) on Appium.

And we are using UI Automator Viewer to see the node details information and we need `resource-id` information visible in order to test for unique nodes so we know which elements are being interacted.

But currently, `resource-id` column is empty even though we have applied `testId` property on each `<View>`.

Please close this issue if there is a duplicate, otherwise please advise on what we can do to have each nodes to have unique id's specified from `testId` value provided.

Thanks,

Sam

**Comment by ashleydw** [comment]
I too struggled with this and actually gave up on android testing with appium.

> Appium is in the process of upgrading to uiautomator v2 which can find by tags because we have the full instrumentation API available. It'll probably take a very long time to be ready though. In uiautomator v1 (what appium currently uses), this isn't possible.

> The only work around I know of is exactly what you mentioned, strip the automaton only content descriptions out of production builds.

See https://discuss.appium.io/t/react-native-ui-element-access-via-testid

**Comment by atom992** [comment]
we need resource-id information visible in order to test too.

**Comment by kahn004** [comment]
Workaround:
Use both `accessible` and `accessibleLabel` on your views (so far, seems to work on View, Text, TextInput) and UiAutomator will generate `content-desc` field from `accessibleLabel`.

DOC on accessiblity label:
https://facebook.github.io/react-native/docs/accessibility.html#accessibilitylabel-ios-android

**Comment by JuliusMalisauskasDB** [comment]
We need resource-id information visible for testing too. Is there any date when it will be implemented?

**Comment by talarari** [comment]
Any update on this?

**Comment by sijicl** [comment]
Ping..Bothered by this issue as well. How does React Native community do end to end UI test on Android App without resource id supported here? Thanks.

**Comment by sondremare** [comment]
upvote

**Comment by tuckerconnelly** [comment]
Here's where the testID is set on android views:

https://github.com/facebook/react-native/blob/3d3b067f6fc831b6b23726087fe39cf39ef86f00/ReactAndroid/src/main/java/com/facebook/react/uimanager/BaseViewManager.java#L88

Not the best with Android, but seems like you'd want to use `setId()` there instead of `setTag()`. That way, if you were using webdriverio, you could do something like:

```js
var selector = '(new UiSelector().resourceId("whatever"))';
browser.click('android=' + selector);
```

...I think?

I can get around to submitting a PR for this when I get to android automation.

**Comment by tuckerconnelly** [comment]
@lexs Is there anything depending on the testID being in the tag? Would you accept a PR for this?

**Comment by mkonicek** [comment]
Commented on https://github.com/facebook/react-native/pull/8843

**Comment by jasonfma** [comment]
Is it actually bad to set the `resource-id` as well as the `tag`? I would rather use `resource-id` than override the content description since it is used for accessibility. But of course tag does seem like the better option all around.

@mkonicek do you have an example of how to get the view by the tag in appium? I think we're all here because we're not sure how to do it. Thanks :)

**Comment by talarari** [comment]
@jasonfma its not currently supported in appium
https://github.com/appium/appium/issues/6025#issuecomment-233680976

Im using content description, how are you using resource id?

**Comment by talarari** [comment]
any chance of setting resource-id in addition to content-desc? 

would allow us to select the element in appium today, until they add support for selecting an element by view tag.

the current solution is kind of bad for accessibility because it forces us to set accessibility labels for controls that are not important for accessibility.

**Comment by jdeff** [comment]
@talarari if you want to set the resource-id on a view for automation, you probably want to do it on it's corresponding AccessibilityNodeInfo object. You can use [setViewIdResourceName](https://developer.android.com/reference/android/view/accessibility/AccessibilityNodeInfo.html#setViewIdResourceName(java.lang.String)) to set the appium-visible resource id for a view.

**Comment by jdeff** [comment]
Actually, looking at this a little more, this would be a very simple thing to add to [AccessibilityHelper.java](https://github.com/facebook/react-native/blob/235b16d93287061a09c4624e612b5dc4f960ce47/ReactAndroid/src/main/java/com/facebook/react/uimanager/AccessibilityHelper.java).

**Comment by jsdevel** [comment]
Hey all, I have a PR to add proper support for `resource-id`.   Check it out and up-vote please: https://github.com/facebook/react-native/pull/9942

Once that's merged in `testID` will add `resource-id` so long as the Id is defined in `res/values/ids.xml`.

**Comment by forki** [comment]
> Once that's merged in testID will add resource-id

What's the status of this? 
I'm using react native 0.40 and setting testID on an image doesn't seem to set the resource-id!?

**Comment by JanPeter** [comment]
No update on this?

**Comment by gmaggess** [comment]
I wonder if this has been forgotten by the react native team...

**Comment by tayunus** [comment]
we are suffering and they don't care...

the problem is that some people say that testID will add a tag to the element, but Appium doesn't support it. 

some people say Appium cut the support for tag in version 1.5: i tried it and it didn't work in version 1.4.

some people are saying that tag will be activated in Appium version 2 because of uiautomator 2 (i think), but nothing new on that.

there is a tool called cavy, but it doesn't have support at all, it's a couple of months old....

i think the best thing we can do is to use accessibility label and add a special key in front of everything so that we can find and comment it thru out the whole application, i guess something like:

accessibilityLabel="ID button1"
accessibilityLabel="ID button2"
.
.
.
and then find (accessibilityLabel="ID) and replace it with (//accessibilityLabel="ID)

**Comment by WilliamNurmi** [comment]
upvote

**Comment by bhgames** [comment]
I got Android to work using accessibilityLabel, but on Sauce, where I have to use a release APK and not a debug APK which expects a package server to exist, it for some reason strips out accessibility labels in Android. So you can test Android, but God help you if you want to parallelize it on a third party. Only your laptop will do!

**Comment by Sartory** [comment]
@bhgames How did you manage to do this? I'm struggling to get it to run for two days now, but the appium test always fails with

>  [elementByAccessibilityId("testId-mainView-button1")] Error response status: 7, , NoSuchElement - An element could not be located on the page using the given search parameters. Selenium error: An element could not be located on the page using the given search parameters.

**react-native code:**
`  <View accessible={true} accessibleLabel="testId-index-view">
        <Button accessibilityLabel="testId-mainView-button1" title="1" style={styles.button} onPress={() => this.handleButtonClick('1')} />
      </View>`
**appium test:**
` await driver.elementByAccessibilityId('testId-mainView-button1').click();`

In the Appium inspector  I'm able to see the button's `accessibilityLabel="testId-mainView-button1" `and with "search for element" with "Locator Strategy:Accessibility ID - Selector:
testId-mainView-button1" in Appium I get the correct button.

**iOS** works if deleting the  `accessible={true}` in the `<View>`

**Comment by bhgames** [comment]
So the issue was that CodePush was overwriting my newer labeled JS code with older nonlabeled code on SauceLabs since it was considered a release APK, and my labels worked locally because in debug mode, CodePush doesn't do that. That was my issue, but yours sounds different.
