### ISSUE TITLE
[Touchable] Preventing a touch area from overflowing?

### ISSUE THREAD

**Issue by ide** [facebook/react-native#715]
I am using a navigation bar with a button inside of it. The navigation bar has a fixed height, and the button is a TouchableOpacity that wraps a View. When I give the View some large bottom padding (like 200pt) it is visually clipped by the navigation bar (overflow: hidden) but still responds to touches below the bar, where the overflowing content would be.

```
+----------------------------------------+                                 
|                           +------------|                                 
|  Navigation Bar           |   Button  ||                                 
|                           |           ||                                 
+----------------------------------------+                                 
                            |           |                                  
Region is clipped but       |           |                                  
still responds to     +---> |           |                                  
touches                     |           |                                  
                            |           |                                  
                            +-----------+                             
```

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by MossP** [comment]
Did you ever find a way around this @Ide?

**Comment by ide** [comment]
I don't think so.

**Comment by MossP** [comment]
No worries, thanks for getting back to me :) :+1:  I'll reply here if I find a workable solution or workaround.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/touchable-preventing-a-touch-area-from-overflowing

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.

**Comment by 6thfdwp** [comment]
I have a similar issue, where I tried to create touchable area with icon + text, acting like borderless button. The workaround I use is to instead of having `TouchableOpacity` that wraps a view, we wrap it inside a view, in that way, the touchable area will get confined to the parent view.

This is how it looks in the screenshot, only blue area responds to touch event. If we put `TouchableOpacity` as root element wrapping the view, the entire row is touchable.
![image](https://cloud.githubusercontent.com/assets/2919741/14106673/94f832f0-f5fe-11e5-95ad-5ca0c7f09c55.png)

Not sure it's a proper way to do it, but works for me now.
