### ISSUE TITLE
Keeping Keyboard open going from one text input to the next text input

### ISSUE THREAD

**Issue by kichingxx** [facebook/react-native#7158]
I've put a form with 2 text input fields in a scroll view. That way, when the user taps out of a text input, the keyboard gets dismissed. If I tap inside the first text input, the keyboard appears as expected. When I tap directly into the second text input, the keyboard dismisses. In order to get the keyboard back, I have to tap into the second text input again. 

How can I keep the keyboard open when I tap directly into the second text input from the first text input without dismissing it?

**Comment by DannyiCracked** [comment]
If you don't need to be in a `<ScrollView>` element you can achieve the same functionality like this:

```
var dismissKeyboard = require('dismissKeyboard');
<TouchableWithoutFeedback onPress={() => { dismissKeyboard(); }}>
    <View style={s.box}>
        <TextInput style={s.textInput} />
        <TextInput style={s.textInput}  />
    </View>
</TouchableWithoutFeedback>
```

**Comment by grabbou** [comment]
Very wall said @DannyiCracked!

**Comment by grabbou** [comment]
@facebook-github-bot stackoverflow

**Comment by dsibiski** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-8** [comment]
Hey @kichingxx and thanks for posting this! @dsibiski tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by grabbou** [comment]
@dsibiski why bot does not like me? :(

**Comment by dsibiski** [comment]
Haha, I think we should also add "stackoverflow" (without the dash) to the list of bot commands. I found quite a few of these in the issues.
