### ISSUE TITLE
enable the hot reloading , there is an exception

### ISSUE THREAD

**Issue by xsgkaka** [facebook/react-native#7174]
i  am coding in webstorm. when i set `enable hot reloading`  in my android devices.
my command window get this exception:
 'EPERM: operation not permitted, lstat 'E:\workspace\ReactWorkspace\eshop\.idea\workspace.xml___jb_old___'
{"errno":-4048,"code":"EPERM","syscall":"lstat","path":"E:\\workspace\\ReactWorkspace\\eshop\\.idea\\workspace.xml___jb_old___"}
Error: EPERM: operation not permitted, lstat 'E:\workspace\ReactWorkspace\eshop\.idea\workspace.xml___jb_old___'
    at Error (native)'
and then the `react-native start` process was be killed.
i think there are some configuration items to ignore the folders or files .
but i do not konw where and how to config. thanks in advance.

**Comment by AndrewTHuang** [comment]
It could be an npm permissions issue. What happens if you run `npm cache clean` before trying `react-native start` again?

**Comment by satya164** [comment]
@facebook-github-bot stackoverflow

**Comment by dsibiski** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-1** [comment]
Hey @xsgkaka and thanks for posting this! @dsibiski tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
