### ISSUE TITLE
where should I place code when I extend native modules?

### ISSUE THREAD

**Issue by tigerohuang** [facebook/react-native#7196]
I want to write some native modules for myself, but I found that node_modules can't be submitted by git, it was passed, If I write my own modules there, it will be hard to share.

**Comment by satya164** [comment]
@facebook-github-bot stackoverflow

**Comment by grabbou** [comment]
Hey @tigerohuang and thanks for posting this! @satya164 tells this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by satya164** [comment]
@grabbou is the new bot ;p
