### ISSUE TITLE
Incorrect ListView scrollbar height

### ISSUE THREAD

**Issue by devongovett** [facebook/react-native#7203]
Perhaps I'm missing something, but it seems that the `ListView` component computes its scroll view's content size (and from that the scrollbar height) using the rows that are (or have been) visible, rather than the actual full height of the rows. This makes sense from a technical perspective since it does not render the rows until they come into view so it doesn't know their height, but it doesn't make for a very good user experience. As far as I could tell from the docs and a brief look at the code, there isn't a way to manually set the content size of the scroll view right now (besides `contentContainerStyle.height` which breaks `ListView`).

Here's an example showing a simple list view with 1000 rows, each with a static height: https://rnplay.org/apps/ib6LQA. As you scroll down, the scrollbar gets shorter and shorter as new rows are rendered and their heights are taken into account.

I'd like to suggest adding an API to better calculate the size of the scrollbar. For lists with static row heights, this could be as simple as a `rowHeight` prop on the `ListView` component. All it needs to do is multiply the row height by the number of rows to get the correct content size for the scroll view.

For lists of variable row heights, some form of row height estimation (like iOS UITableView has) would be nice. An `estimateRowHeight` prop that takes a function to compute the row height for a given row object would work. If the row hadn't been displayed yet, use the estimated height, otherwise use the real height.

**Comment by christopherdro** [comment]
@facebook-github-bot feature

**Comment by christopherdro** [comment]
@facebook-github-bot feature

**Comment by lacker** [comment]
This seems reasonable, but we're focusing for now on creating an overall-superior ListView API rather than improving the existing one. If you are interested in sending a PR to improve this, that would be cool! Otherwise, we are using Product Pains to help prioritize feature requests, and there's a big one for ListView at https://productpains.com/post/react-native/fix-various-listview-issues that folks can add their votes/feedback to. To keep things single-sourcey I feel like I should close this issue. Thanks for bringing this up!

**Comment by j-priestley** [comment]
This looks like it's still an issue using FlatList with a large number of rows. The scrollbar gets smaller and jumps up as new rows are added to the bottom of the list.
