### ISSUE TITLE
[android]when ListView scrolled and datasource is changed after,ListView's scrollY state is not top

### ISSUE THREAD

**Issue by linjson** [facebook/react-native#7223]
不知道英文有没表述正确,就是当listview滚动到一半时,这时数据发生变化,listview的滚动状态没变为0(就是在顶部的状态)

**Comment by ZackZheng2014** [comment]
@linjson 请问你是怎么获取contentOffset的？

**Comment by ZackZheng2014** [comment]
How can I get the contentOffset when using onMomentumScrollEnd ?

**Comment by linjson** [comment]
没获取,是看DEMO,UIExample的首页,不是有个搜索框吗,listview滚动到一半时,这时数据发生变化,listview没滚动到顶部

**Comment by grabbou** [comment]
@facebook-github-bot stackoverflow

**Comment by dsibiski** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-5** [comment]
Hey @linjson and thanks for posting this! @dsibiski tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
