### ISSUE TITLE
NavigationExperimental and Android styling (FadeAndroid)

### ISSUE THREAD

**Issue by andreialecu** [facebook/react-native#7239]
NavigationExperimental seems to be set up exclusively with iOS transitions (`horizontal/vertical`), however these are not appropriate for android.

The old Navigator had FadeAndroid, which looked a bit more native. Are there plans to improve this for Android?

I'd give it a shot myself at a PR, but I'd like a bit of guidance on how/where this should be implemented.

**Comment by lacker** [comment]
We're working on publishing a public roadmap with our plans, and part of that is our plans for navigation. @skevy and @ericvicenti are working on a new navigation library to replace NavigationExperimental so in terms of guidance I think it's best to wait for that to hit. I'm gonna close this because it's also an old issue.
