### ISSUE TITLE
Native Video component for Android and iOS

### ISSUE THREAD

**Issue by abbasfreestyle** [facebook/react-native#7246]
Will there be a Native Video component for Android and iOS in the pipeline?

I've searched through all of the available components and none seem to deliver a native video player, iOS seems to have more support than Android. Just wondering if this will be considered?

Embedding WebViews just complicates things further with functionality, performance, styling etc...

Would be really awesome to have something  like `<VideoAndroid>` and `<VideoIOS>`

**Comment by jgibbons** [comment]
Check out https://github.com/brentvatne/react-native-video. It is quite good.

**Comment by jsierles** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-8** [comment]
Closing this issue as @jsierles says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.
