### ISSUE TITLE
[0.25][android]Press TextInput will not reopen the keyboard after closed

### ISSUE THREAD

**Issue by kiliwalk** [facebook/react-native#7251]
Press the TextInput element will cause the keyboard to open, then close the keyboard, and press the TextInput element again, the keyboard will not reopen.
I have already tested v0.24.1, it don't have this issue. 

Other environment info:
* react native v0.25.0-rc
* android

**Comment by radko93** [comment]
Seems to be fixed on `master`. Tested on Android 5.1.1 (real device) and 6.0.0 (emulator).
![](https://i.imgur.com/dEm3ijb.gif)

**Comment by dsibiski** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-7** [comment]
Closing this issue as @dsibiski says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

**Comment by wayne-mu** [comment]
Issue is there. 

I use react 0.14.8 and react-native 0.25.1, this issue is still there. Is there any quick solution without changing react-native version?


  "react": "^0.14.8",
  "react-native": "^0.25.1"
