### ISSUE TITLE
RCTException Index Out Of Bound from RCTUIManager

### ISSUE THREAD

**Issue by davodesign84** [facebook/react-native#7253]
Hi all,

I'm having some trouble chasing down a crash in production which I can't manage to reproduce.
The stack trace from Crashlytics is as follow:

Android:
Fatal Exception: java.lang.IndexOutOfBoundsException
Invalid index 2, size is 1
com.facebook.csslayout.CSSNode.addChildAt (CSSNode.java:95)

iOS:
Fatal Exception: RCTFatalException: Exception '*** -[__NSArrayM insertObject:atIndex:]: index 3 beyond bounds [0 .. 1]' was thrown while invoking manageChildren on target RCTUIManager with params ( 8, ( 0 ), ( 3 ), "<null>", "<null>", "<null>" ).

Any idea what it could be? or how to go about debugging it?

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-3** [comment]
Hey @davodesign84 and thanks for posting this! @DanielMSchmidt tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by facebook-github-bot-7** [comment]
Hey @davodesign84 and thanks for posting this! @DanielMSchmidt tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
