### ISSUE TITLE
React devtools in chrome

### ISSUE THREAD

**Issue by EasonWang01** [facebook/react-native#7259]
hi,is it possible to using react tap in chrome to debug Android app?

Because react says the devtools support for react native,but I can't see react tap in http://localhost:8081/debugger-ui 

thanks for reply.

**Comment by skv-headless** [comment]
It works inside Atom(Nuclide). And there is https://productpains.com/post/react-native/devtools-react-tab-does-not-work for that.

**Comment by grabbou** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-2** [comment]
Closing this issue as @grabbou says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.
