### ISSUE TITLE
Ios set transformMatrix error,the json convert error

### ISSUE THREAD

**Issue by charlesluo2014** [facebook/react-native#7270]
[RCTConvert.m:57] Error setting property 'transformMatrix' of RCTView with tag #147: JSON value '<null>' of type NSNull cannot be converted to NSNumber

```
(
    1,
    0,
    0,
    0,
    0,
    1,
    0,
    0,
    0,
    0,
    1,
    0,
    "<null>",
    "<null>",
    "<null>",
    "<null>"
)
```

can react-native provide the context of which tag name occur the exception.

**Comment by damusnet** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-6** [comment]
Hey @charlesluo2014 and thanks for posting this! @damusnet tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
