### ISSUE TITLE
rendering strangely using both setstate and setvalue to modify an animate.value 

### ISSUE THREAD

**Issue by henry42** [facebook/react-native#7302]
react native 0.24.1
both ios and android

1. render a animate view with translateX = 0 binding in state
2. translateX setValue directly to make the view move left
3. try to setState translateX = 0, but the view still not return the 0 position

I made a mistake or it's a bug?
here is the code
thx

	class Test extends Component {
	  constructor(props) {
	    super(props);
	    this.state = {
	      translateX : new Animated.Value(0),
	      text : 80,
	    };
	  }

	  componentDidMount(){

	    setTimeout(()=>{
	      //set animate value directly to move the view to left
	      this.state.translateX.setValue(-20);
	    },5000);

	    setTimeout(()=>{
	      //set animate value by setState
	      //but the view is still at left
	      this.setState({
	        translateX : new Animated.Value(0),
	        text:79
	      });
	    },10000)
	  }

	  render(){
	    return (
	      <View style={{marginTop:48,flex:1}}>
	        <Animated.View style={{transform:[{
	          translateX : this.state.translateX
	        }]}}>
	              <View style={{backgroundColor:"red",alignItems:"center"}}><Text>{this.state.text}</Text></View>
	        </Animated.View>
	      </View>
	      )
	    }
	}

**Comment by DannyiCracked** [comment]
Looks like you are trying to take a shortcut to get `Animated.Event` functionality. 

Have you looked at `Animated.Timing` and used the `.start()` method instead?

Perhaps better suited for stackoverflow.

**Comment by dsibiski** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-1** [comment]
Hey @henry42 and thanks for posting this! @dsibiski tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by henry42** [comment]
Thx.
I asked it on [stackoverflow](http://stackoverflow.com/questions/36951350/rendering-strangely-using-both-setstate-and-setvalue-to-modify-an-animate-value), but nobody answers it right now.
I did lots of test these days, I do think it should be a bug, can you help me review it?
@DannyiCracked I tried `Animated.timing`, but the result is the same.
@dsibiski
