### ISSUE TITLE
iOS app is not starting due to simulator problem.

### ISSUE THREAD

**Issue by surendharreddy** [facebook/react-native#7307]
Running my first iOS app using react native says 

> Directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/Developer/Library/Frameworks'

How to solve this issue?

**Comment by anttimo** [comment]
Found this similar issue with answer from stackoverflow http://stackoverflow.com/questions/30827022/xcode-7-library-search-path-warning/32620919#32620919 please try if it helps.

**Comment by dsibiski** [comment]
Thanks @anttimo. @surendharreddy Please remember that Github issues are only meant for bug reports. If the answer and @anttimo linked to doesn't solve your problem, please create your own question on StackOverflow or perhaps join the #react-native chat on Reactiflux.

**Comment by dsibiski** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-6** [comment]
Hey @surendharreddy and thanks for posting this! @dsibiski tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
