### ISSUE TITLE
renderRow with button

### ISSUE THREAD

**Issue by albo1337** [facebook/react-native#7328]
- [ 24.1 ] What's the **version** of React Native you're using?
- [ both ] Does this occur on iOS, Android or both?
- [ Mac ] Are you using Mac, Linux or Windows?

I'm doing this: 

```
...
    _onPress(data) {
        Actions.shopProducts(data);
    }
...
            <Button onPress={this._onPress.bind(this)}>
                <View style={styles.row}>
                    <View style={styles.listViewContainer}>
                        <Image
                            source={{uri: rowData.image}}
                         />

                        <View style={styles.rightContainer}>
                            <Text style={styles.smallText}>Name: {rowData.name}</Text>
                            <Text style={styles.smallText}>Straße: {rowData.address}</Text>
                            <Text style={styles.smallText}>Ort: {rowData.location}</Text>
                        </View>
                    </View>
                </View>
            </Button>
...
```

I'm getting following error: 

```
Possible Unhandled Promise Rejection (id: 0): undefined is not an object (evaluating 'this._onPress.bind') renderRow @...
```

I'm actually using react-native-router-flux and react-native-button.

What causes this error? I can't understand this...

Best regards
albo1337

**Comment by damusnet** [comment]
@facebook-github-bot stack-overflow

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-3** [comment]
Hey @albo1337 and thanks for posting this! @charpeni tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
