### ISSUE TITLE
Unable to resolve regenerator/runtime - constant error

### ISSUE THREAD

**Issue by davidfloegel** [facebook/react-native#7333]
Hey there,

I used to be able to run react-native apps just fine but since I restarted my computer today I'm getting this error constantly:

<img width="386" alt="screen shot 2016-05-02 at 16 54 16" src="https://cloud.githubusercontent.com/assets/13220692/14959902/be28d1d4-1089-11e6-96f9-d4ab6486c6d5.png">

It's pretty annoying since I have no idea what could be going on or what has changed. I even tried setting up a brand new react-native project but still get the same issue...
I'm on a mac and using these versions:
react-native: 0.24.1
node: v6.0.0

Any ideas??

Thanks a lot

**Comment by spencercarli** [comment]
I ran into this issue as well and found a hack to make it work for now... the issue seems to stem from react native's dependency on [`regenerator`](https://github.com/facebook/regenerator) which is deprecating `regenerator/runtime` in favor of `regenerator-runtime/runtime`.

So all I did was `npm install --save regenerator` and my app is running again, though it's warning me that above is being deprecated. 

It seems the issue is coming from here https://github.com/facebook/react-native/blob/master/Libraries/JavaScriptAppEngine/Initialization/InitializeJavaScriptAppEngine.js#L25

**Comment by davidfloegel** [comment]
Ah wicked @spencercarli thank you so much. I still wonder **how** this happened though as I literally restarted my macbook and it stopped working..

I'll close the issue for now!

**Comment by spencercarli** [comment]
Yeah it's very odd. I ran `rm -rf node_modules/ && npm i` just prior to everything going downhill for me.
