### ISSUE TITLE
how to import project root directory? 

### ISSUE THREAD

**Issue by phproot** [facebook/react-native#7346]
```
+ App
+ -- android
+ -- ios
+ -- application
+ ---- config
- ------ themes.js
+ ---- views
+ ------login
- --------login.js
- ---- index.js
```

index.js

```
....
import themes from './config/themes';
...
```

login.js
```
....
import themes from '../../config/themes';
...
```

I hope it like this:
```
....
import themes from '@root/config/themes';
...
```

my english is not good.

**Comment by dsibiski** [comment]
@phproot This question should really be asked on Stack Overflow. If you post it there, I can answer it for you 😄

**Comment by dsibiski** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-9** [comment]
Hey @phproot and thanks for posting this! @dsibiski tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by phproot** [comment]
thank you very much！Stack Overflow link is:
[http://stackoverflow.com/questions/37003898](http://stackoverflow.com/questions/37003898)

**Comment by dsibiski** [comment]
Answer posted here: http://stackoverflow.com/a/37005323/4932710
