### ISSUE TITLE
Navigator Experimental: Overriding Header styles difficult

### ISSUE THREAD

**Issue by mschipperheyn** [facebook/react-native#7350]
I'm having difficulties overriding header styles in NavigationHeader. The reason is that you pass the style to the Header component such as Title, but NavigationHeader applies its own internal style to the internal Animated.View that wraps that component. So, you end up compensating for the internal style with negative margins etc in stead of just applying the style you want.

**Comment by satya164** [comment]
@mschipperheyn Just create your own `NavigationHeader` component. It's quite small.

**Comment by mschipperheyn** [comment]
Nothing special. I'm basically creating a Material Design look on both iOs and Android. I could of course create my own Header component, but I always try to avoid reinventing the wheel

**Comment by madvas** [comment]
+1. If you want to use `NavigationHeader`, but just want to add [BlurView](https://github.com/react-native-fellowship/react-native-blur), there's no simple way to do it. If you wrap it, you lose all the styles. If you want to wrap children to it, u can't because this is `render` method: 

```
<View style={[ styles.appbar, style ]}>
        {scenesProps.map(this._renderLeft, this)}
        {scenesProps.map(this._renderTitle, this)}
        {scenesProps.map(this._renderRight, this)}
</View>
```

Correct me if I'm wrong
