### ISSUE TITLE
tabbariOS more tab is broken ? 

### ISSUE THREAD

**Issue by ArEnSc** [facebook/react-native#7356]
The tabbarIOS more functionality appears to crash the application. There doesn't seem to be any documentation about the more tab. RN-24.01

```javascript
import React, {
  Component,
  StyleSheet,
  Text,
  View,
  Props,
  TabBarIOS
} from 'react-native';


export default class TabsView extends Component {

  constructor(props) {
    super(props)
  }

  onTabSelect(tab) {

  }

  render() {

    return (
      <TabBarIOS translucent={false}>
        <TabBarIOS.Item title="Invoices"> </TabBarIOS.Item>
        <TabBarIOS.Item title="Customers"> </TabBarIOS.Item>
        <TabBarIOS.Item title="Products"> </TabBarIOS.Item>
        <TabBarIOS.Item title="Options"> </TabBarIOS.Item>
        <TabBarIOS.Item title="Settings"> </TabBarIOS.Item>
        <TabBarIOS.Item title="FAQ"></TabBarIOS.Item>
        <TabBarIOS.Item title="Contact Support"></TabBarIOS.Item>
        <TabBarIOS.Item title="Sign Out"></TabBarIOS.Item>
      </TabBarIOS>
    );
  }
}

/**

**/

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#00000000',
  }
});
```

**Comment by rogchap** [comment]
I had the same issue a long time ago...
Best thing to do is render your own `More` tab which then you have complete control over that view to render a `ListView` or whatever.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/tabbarios-more-tab-is-broken-

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
