### ISSUE TITLE
[Android] keyboardDidHide keyboardDidShow does not trigger for landscape keyboard

### ISSUE THREAD

**Issue by holyxiaoxin** [facebook/react-native#7359]
`DeviceEventEmitter.addListener('keyboardDidHide',  () => console.log('hide'))` does not fire for landscape keyboard.

I have checked that `DeviceEventEmitter.addListener('keyboardDidHide',  () => console.log('hide'))` does fire for portrait keyboard.

For IOS, `DeviceEventEmitter.addListener('keyboardDidHide',  () => console.log('hide'))` fires for both portrait and landscape keyboard.

React-native version: `0.25.0-rc`

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-keyboarddidhide-keyboarddidshow-does-not-trigger-for-landscape-keyboard

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
