### ISSUE TITLE
TextInput does not honor iOS text size

### ISSUE THREAD

**Issue by rgoldiez** [facebook/react-native#7363]
`TextInput` component always renders at the font size specified in the style for the component and does not honor font scaling from the OS (iOS, not sure about Android).  This becomes especially problematic when you have a populate the `TextInput` with some text and you want to size the `TextInput` properly from the start (and adjust it as more/less lines are added).  

Scenario: You have a user that has set their default font size to be the smallest or largest (_Important_) in their iPhone's settings.  In your RN app, you have a `Text` field that `onLongPress` is going to allow editing.  You want to size the `TextInput` component to be the same height at the `Text` component, but now with a cursor to allow for editing.

**Comment by rogchap** [comment]
Just checking that you've tried setting `allowFontScaling = true` for your `TextInput`??

**Comment by rgoldiez** [comment]
@rogchap - Thanks for the feedback.  I just tried `allowFontScaling={true}` and see the same result.  Below is one of the `TextInput` components I'm working with.  I'm open to any other suggestions on things to try.

```
<TextInput style={[styles.textInput, {height: Math.max(30, this.state.height), color: inputTextColor}]}
   onChangeText={this.onChangeText}
   onChange={(event) => {
      this.setState({height: event.nativeEvent.contentSize.height})
   }}
   value={this.state.message}
   autoFocus={this.props.autoFocus}
   blurOnSubmit={false}
   editable={!this.state.pressedSubmit}
   initialHeight={30}
   multiline={true}
   allowFontScaling={true}
   placeholder={this.props.placeholder || 'Message'}/>
```

**Comment by mangogogos** [comment]
+1 notable that I believe this only occurs with multiline={ true }

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/textinput-does-not-honor-ios-text-size

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
