### ISSUE TITLE
Android LayoutAnimation for 'create' ignores target opacity

### ISSUE THREAD

**Issue by martysaxton** [facebook/react-native#7367]
The 'create' animation is hard coded to fade in from opacity 0 to opacity 1.  It needs to fade in to whatever the view's target opacity is set to.  It's hard coded in BaseLayoutAnimation:

 @Override
  Animation createAnimationImpl(View view, int x, int y, int width, int height) {
    float fromValue = isReverse() ? 1.0f : 0.0f;
    float toValue = isReverse() ? 0.0f : 1.0f;
    if (mAnimatedProperty != null) {
      switch (mAnimatedProperty) {
        case OPACITY:
          return new OpacityAnimation(view, fromValue, toValue);
...

I think target opacity needs to be added as a param to this method and passed along from wherever it comes from:

  Animation createAnimationImpl(View view, int x, int y, int width, int height, float opacity) {

**Comment by machard** [comment]
Yes ! that's a big problem !

**Comment by machard** [comment]
And actually, for me the problem is that it overrides the opacity of all the nested children components as well !

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-layoutanimation-for-create-ignores-target-opacity

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
