### ISSUE TITLE
[packager]from 0.23.0 the packger use canonical ID instead of module path

### ISSUE THREAD

**Issue by swain** [facebook/react-native#7370]
Before version v0.23.0, I patched the packager for my project. I can package bundle file into two parts(one is core framework code bundle and the other is business code bundle).

From version v0.23.0 the packger use `canonical ID` instead of module path, so I can't do this now. Because when I package separately, the canonical ID duplicated, the canonical id is unique only in one package lifetime. 

This situation never happened when use module path for `require` method, because any module in project have unique module name or path.

so why use `canonical ID` instead of module path? How can I package code separately  like before?

**Comment by lacker** [comment]
I asked around and nobody seems to know. I think in general we can't necessarily support hacking the packager - I mean, good luck getting it to work, but I don't think we can support it per se, so I am going to close this issue. You might want to try asking on Stack Overflow since this is more of a "how to do X" than "bug" type issue.
