### ISSUE TITLE
set navigationBarHidden:true and leftButtonTitle:"ok"  leftButtonTitle not work

### ISSUE THREAD

**Issue by stoneWeb** [facebook/react-native#7379]
set navigationBarHidden:true and leftButtonTitle:"ok"  leftButtonTitle not work. why?

**Comment by damusnet** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-5** [comment]
Hey @stoneWeb and thanks for posting this! @damusnet tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by mkonicek** [comment]
Thanks @damusnet!
