### ISSUE TITLE
Cannot run program "node"

### ISSUE THREAD

**Issue by ghalong** [facebook/react-native#7382]
Hi,my react-native version is 0.2.0,I am using macOs,when I using
         `classpath 'com.android.tools.build:gradle:2.1.0'`
 in my project_root build.gradle file and run the ./gradlew assembleRelease command in the cli,I will got the error info as bellow:
`Caused by: java.io.IOException: Cannot run program "node" (in directory "/Users/wanghaiyu/RNTest/app"): error=2, No such file or directory
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
	… 4 more
Caused by: java.io.IOException: error=2, No such file or directory
	… 5 more`
I have tried so many times,then I found when I using the 
`classpath 'com.android.tools.build:gradle:1.3.1'`
it will work well,who can tell me how to make the  
`classpath 'com.android.tools.build:gradle:2.1.0'`
also work well?because the gradle:2.1.0 is the newest.

**Comment by damusnet** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-3** [comment]
Hey @ghalong and thanks for posting this! @damusnet tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
