### ISSUE TITLE
[Question] A question about JS call Java

### ISSUE THREAD

**Issue by zjutkz** [facebook/react-native#7398]
Hi,sorry to bother you,I've bean reading the source code about react native and I got a question:
```
    var now = new Date().getTime();
    if (global.nativeFlushQueueImmediate &&
        now - this._lastFlush >= MIN_TIME_BETWEEN_FLUSHES_MS) {
      global.nativeFlushQueueImmediate(this._queue);
      this._queue = [[], [], [], this._callID];
      this._lastFlush = now;
    }
```
This is a part of the code of function __nativeCall in MessageQueue.js.I found you guys added this code in October 2015 with the message "Batch native method calls in 5ms increments".But I have no idea about why you guys did this.In my opinion,data in MessageQueue(ModuleId,MethodId and params) will be pushed to native when Java event  driving Js,so could you please tell me the reason you guys added this code?

**Comment by mkonicek** [comment]
Hi @zjutkz, check out this presentation, there's a part about batching: https://speakerdeck.com/mkonicek/under-the-hood-of-react-native?slide=25

We don't want to execute every JS call in native immediately (that would have a lot of overhead communicating over the bridge often), so we want to batch the calls. However, we wait at most 5ms before executing the calls to help keep the UI feel responsive (e.g. you tap a button, the UI needs to reflect that asap).

**Comment by mkonicek** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-8** [comment]
Hey @zjutkz and thanks for posting this! @mkonicek tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
