### ISSUE TITLE
change CameraRoll quality or size

### ISSUE THREAD

**Issue by stoneWeb** [facebook/react-native#7399]
How to change CameraRoll quality or size

**Comment by radko93** [comment]
Can you provide more details? I suppose you are asking `Camera` and not `CameraRoll`, as there's probably no way to set the quality of an image from Camera roll.

**Comment by stoneWeb** [comment]
I want to upload image before compressed images, How do I do?

**Comment by damusnet** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-0** [comment]
Hey @stoneWeb and thanks for posting this! @damusnet tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
