### ISSUE TITLE
Query Device attributes, etc?

### ISSUE THREAD

**Issue by jaygarcia** [facebook/react-native#74]
Hi, 

How does one query Device attributes like screen dimensions via the JS bridge?

**Comment by stefalda** [comment]
I think some sort of access to the device screen size and capabilities is badly needed.

**Comment by chirag04** [comment]
+1

**Comment by brentvatne** [comment]
@chirag04 @stefalda - What capabilities did you have in mind? In terms of screen size, what information do you want to have access to beyond the width/height and pixel ratio?

width/height are currently available with `require('Dimensions').get('window')` which returns `{width: x, height: y}` and pixel ratio which you can access directly with the `PixelRatio` module or `require('Dimensions').get('window').scale`. 

So I think this issue is more about being able to watch the device for events that might change the dimensions eg rotation: #426. We can watch for changes in status bar size using [react-native-status-bar-size](https://github.com/brentvatne/react-native-status-bar-size). What else am I missing?

**Comment by ide** [comment]
There is also https://github.com/pjjanak/react-native-viewport for viewport sizes.

**Comment by stefalda** [comment]
@brentvatne I didn't know about those methods, but I think they'd be enough for now.
, and I agree about the need to get the device events...

**Comment by chirag04** [comment]
@brentvatne We only need width/height and pixel ratio and for now we are using ``Dimensions``. 

But as i read in github issues, dimensions is going to go and is a bad practice. Documented component/module for this would be helpful.

**Comment by brentvatne** [comment]
@chirag04 - check out the Viewport module that @ide mentioned above, it seems like a good alternative :smile:

I'm going to close this issue, let's create a new one when we have some specific attributes that we want to be able to query for so we can handle those on a case-by-case basis.
