### ISSUE TITLE
Update Version 0.25.1   React.findNodeHandle undefined is not a function 

### ISSUE THREAD

**Issue by dacaiji** [facebook/react-native#7401]
my code and   dependencies
"dependencies": {
    "react": "^0.14.8",
    "react-native": "^0.25.1",
    "react-native-scrollable-tab-view": "^0.4.0",
    "react-native-share": "lifuzu/react-native-share",
    "react-native-vector-icons": "^1.2.0",
    "react-native-viewpager": "^0.2.1"
  },

import React, {Component,} from 'react';

import{
  StyleSheet,
  Text,
  TextInput,
  ScrollView,
  Dimensions,
} from 'react-native';

  <View onStartShouldSetResponderCapture={(e) => {
            const target = e.nativeEvent.target;
 if (target !== React.findNodeHandle(this.refs.emailInput) &&
           target !== React.findNodeHandle(this.refs.passInput)) {}

**Comment by damusnet** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-4** [comment]
Hey @dacaiji and thanks for posting this! @damusnet tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by dacaiji** [comment]
I don't understand   
<View onStartShouldSetResponderCapture={(e) => {
            const target = e.nativeEvent.target;
            if (target !== React.findNodeHandle(this.refs.emailInput) &&
                target !== React.findNodeHandle(this.refs.passInput)) {
                this.refs.emailInput.blur();
                this.refs.passInput.blur();
            }}}>
In the old version can be used

**Comment by aljs** [comment]
@dacaiji , you should use it as ReactNative method. Add this line to beginning:
`import ReactNative from 'react-native';`
After change React.findNodeHandle() to **ReactNative**.findNodeHandle()

**Comment by dacaiji** [comment]
@aljs  thank you very much . i have already solved the problem!
