### ISSUE TITLE
No way to replaceState inside react-native

### ISSUE THREAD

**Issue by fab1an** [facebook/react-native#7404]
I'm setting my props / state from Java by calling a function on `RTCEventEmitter`.
In my component I set the state like this:

```javascript
    componentWillMount() {
        DeviceEventEmitter.addListener('setState', state => {
            requestAnimationFrame(() => {
                this.setState(state);
            });
        })
    }
```

1. I would rather set the properties instead of state, but I don't know how to access the root since there's no `ReactDOM.render` like on the web.
2. I would like to _replace_ my state, but `this.replaceState` gives me a deprecation warning. How can I get around this?

**Comment by damusnet** [comment]
@facebook-github-bot stack-overflow

**Comment by radko93** [comment]
`this.replaceState` is [depreciated](https://facebook.github.io/react/docs/component-api.html#replacestate). You can make a default `initialState` constant and use it like this `this.setState(...initialState, ...state)`.

**Comment by facebook-github-bot-8** [comment]
Hey @fab1an and thanks for posting this! @damusnet tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by fab1an** [comment]
I posted my question on SO could you look at it, maybe? https://stackoverflow.com/questions/37049292/no-way-to-replacestate-inside-react-native

I don't want to `setState()` twice…
