### ISSUE TITLE
Update documentation of React Native integration with existing app

### ISSUE THREAD

**Issue by MikeOrtiz** [facebook/react-native#7412]
For the past couple days, I've struggled integrating React Native with an existing app. I've posted a question to StackOverflow [here](http://stackoverflow.com/questions/37046933/requiring-unknown-module-reactperf-while-integrating-react-native-with-existin). At the root of my frustrations with this experience is the conflicting documentation:

- The **Integrating with Existing Apps** section of the [docs](http://facebook.github.io/react-native/docs/embedded-app-android.html#content) describes importing React Native from Maven Central.
- The Movies example app builds from source.
- Buried in a comment in a Github issue I can no longer find, I discovered that builds are now distributed through npm. This requires pointing to the React Native jar in node_modules.

Obviously, something is still wrong with my setup, but the cryptic error messages and conflicting documentation have made it very difficult for me to debug. The docs should be updated and the Movies example app should be updated as well to align with the methods stated in the docs.

**Comment by tryggvigy** [comment]
We had to compile `react-native-<version>-sources.jar` found under `node_modules` ourselves

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/update-documentation-of-react-native-integration-with-existing-app

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
