### ISSUE TITLE
TextInput

### ISSUE THREAD

**Issue by CaoLiang1991** [facebook/react-native#7423]
When TextInput is  in column container, it's not aligned with other view.

![screenshot_2016-05-06-15-13-38](https://cloud.githubusercontent.com/assets/16915325/15066739/1ebb2724-139e-11e6-97c2-40f57ee58b2f.png)

I think it should not keep distance

**Comment by damusnet** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-5** [comment]
Hey @CaoLiang1991 and thanks for posting this! @damusnet tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
