### ISSUE TITLE
[Android] Cannot hide inner contents when parent <View> has height or width of 0

### ISSUE THREAD

**Issue by ericmasiello** [facebook/react-native#7431]
I'm trying to use LayoutAnimation as a a means of hiding and showing different View elements. If I set  `height: 0` and `overflow: 'hidden'`, the View's contents are completely hidden in iOS. The ideas being that using LayoutAnimation, I'll toggle the height property to make the View elements slide up and down.

On Android though, that's the not the case. From what I've observed, the View will only shrink as small as the inner contents. It won't clip the inner elements.

I've removed the LayoutAnimation piece from my sample code. You can see what I'm talking about here https://rnplay.org/apps/yO0W4Q. The "ViewTwo" text is still visible even though the parent View has a `height: 0, flex: 0, overflow: 'hidden'`. If you run the demo in iOS, it works as designed. Is there a way around this or is this a bug or limitation on Android? Any suggestions on how to work around it? Thanks!

**Comment by jondbm** [comment]
A temporary workaround that sometimes works, but not always, is setting the  height/width of the view you want to hide to 0.1 instead of 0.  For some reason this will hide the contained view when 0 won't.

**Comment by ericmasiello** [comment]
Thanks for the recommendation @jondbm

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-cannot-hide-inner-contents-when-parent-view-has-height-or-width-of-0

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (60/60 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter01.reliabledns.org ([199.96.156.50]:50679)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bzseD-004LPG-56
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 21:55:42 +0000
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197] helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by filter01.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1bzseB-0000tV-Oy
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 14:55:40 -0700
Date: Thu, 27 Oct 2016 14:55:38 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1477605338;
	bh=gn5Kx3w8psUG47lHVGa25V3+amXrx254wN5eRwnGTuE=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=hE7MwyZibu/zUDIO8+I59RZu2cka0yc8bwA/BexzZBSkt/5cWrRxRImCJqXqOxQBH
	 F2ixLL6LliNG04bnO18WKJBM0hnFDZQrvxAKXWl4O11VJcrDvdAxHfloYMjneiNgoS
	 66rKUyiYSqDcvABmB0FSYdNWVg+cCFFN7Z+ryMZI=

**Comment by mkon** [comment]
Can you stop your bot from tagging me in your github projects all the time? Thank you.

**Comment by mkonicek** [comment]
@mkon I don't see the bot tagging you?

**Comment by mkon** [comment]
The problem is the bot is pasting the mail body where mkonicek is split in two lines like this
```
... @mkon=
icek
```

![bildschirmfoto 2016-10-28 um 14 12 41](https://cloud.githubusercontent.com/assets/637499/19806077/a11ee922-9d18-11e6-8f46-fa056472140e.png)


Which then tags me in a lot of PRs suddenly. Anyway I put your bot on ignore now maybe that helps
