### ISSUE TITLE
Packager is extremely slow

### ISSUE THREAD

**Issue by ngreenwood6** [facebook/react-native#7438]
I am running React Native version `^0.24.1` and am running this on OSX El Capitan version `10.11.4` (macbook pro 16GB). The command I am running to start the packager is `npm start`. The packager is taking anywhere from 45 seconds to 90 seconds to build my project. I tested on a new project and it was still taking around 20 seconds to build. I have tried to reset cache and it didn't help. Here is the output from the packager:

```
[3:26:00 PM] <START> Building Dependency Graph
[3:26:00 PM] <START> Crawling File System
[Hot Module Replacement] Server listening on /hot

React packager ready.

[3:26:48 PM] <END>   Crawling File System (47872ms)
[3:26:48 PM] <START> Building in-memory fs for JavaScript
[3:26:48 PM] <END>   Building in-memory fs for JavaScript (428ms)
[3:26:48 PM] <START> Building in-memory fs for Assets
[3:26:49 PM] <END>   Building in-memory fs for Assets (227ms)
[3:26:49 PM] <START> Building Haste Map
[3:26:49 PM] <START> Building (deprecated) Asset Map
[3:26:49 PM] <END>   Building (deprecated) Asset Map (79ms)
[3:26:49 PM] <END>   Building Haste Map (196ms)
[3:26:49 PM] <END>   Building Dependency Graph (48733ms)
```

This used to be running pretty quickly for me but now it's taking forever for the initial load. Once that initial load is done it recompiles much faster and building the bundle is really fast too. It seems like something is hung up on my system and im not sure what to check for. Another computer running this project does not take long to build the project. Looking for any suggestions on things to try.

**Comment by damusnet** [comment]
Hi @ngreenwood6, if the same project works fine on another computer, it is likely not a bug with react-native, and probably more something to do with your setup. I suggest you seek help on StackOverflow.

@facebook-github-bot stack-overflow

**Comment by ngreenwood6** [comment]
Are those unusual load times?

**Comment by ide** [comment]
2-3x slower than what we see. Maybe you need watchman installed?

**Comment by ngreenwood6** [comment]
Thanks @ide I installed watchman and it reduced the time to around 1000ms. I thought I had that installed but maybe at some point I uninstalled it.

**Comment by kevinold** [comment]
I'm seeing an issue similar to this when requiring a Scala.js lib that has already been optimized during the Scala.js build.

The lib is larger at around 238K and is taking right at 1 min to load initially.  Subsequent loads are immediate.

I have watchman installed (double verified) and I'm running React Native 0.30.0.

Any ideas @ide?

**Comment by ismdcf** [comment]
Upgraded react from 23.1 -> 25.1 and now react packager takes around 6 minutes to start. and doing a release build takes around 12mins. Upgraded watchman to 4.6.0 which fixed the issue and after a pc restart same issue persists for the first run . @ide any guesses on what might be reason for this.

**Comment by ide** [comment]
Not really sure what's going on with your computer, sorry.

**Comment by MattyK14** [comment]
@ismdcf any luck after? Initializing the packager all of a sudden brings my Mac to an absolute crawl. Was fine for the last few months, I'm not sure what changed.

**Comment by hugomosh** [comment]
@ismdcf did you manage to solve that issue?
Same here

**Comment by ismdcf** [comment]
I had recently upgraded react native to 0.37 after which it was a bit stable. Then after a couple of runs figured out watchman was eating my memory (around 2 GIGs) then figured out [ watchman watch-list
](https://facebook.github.io/watchman/docs/cmd/watch-list.html) command gave me reference to a huge list of directories. So did a [watchman watch-del-all](https://facebook.github.io/watchman/docs/cmd/watch-del-all.html) to clean the watch list which brought watchman memory consumption to less than 10MB. After which the builds were fast and live reloads were working really fast. But still I have to upgrade my hard drive to an ssd. Maybe that's a reason for this thing to build slow. 

**Reason for the watch man watch history to grow was because I had multiple copies of my project which I use as a template. So each time I run a template it adds the directory location to watchman watch list** @MattyK14 this could be your issue.

**Comment by MattyK14** [comment]
@ismdcf unfortunately not, I check the `watch-list` every time. It's consistently only when running Android though, but not every time.
