### ISSUE TITLE
[iOS] left-edge swipe gesture can be received by navigator even when a modal is presented

### ISSUE THREAD

**Issue by ultragtx** [facebook/react-native#7450]
![untitled3](https://cloud.githubusercontent.com/assets/431919/15102253/caf65e5e-15cf-11e6-8e28-bf2ea4d486c8.gif)

As the screenshot shows, the top most view can be popped by the swipe gesture even when the modal is presented. (Tested on version 0.22 0.23 and latest code on master branch 05.08.2016)

Furthermore, I added a picker on the modal in my app, add the swipe gesture can be received by both the picker and the navigator (Navigator.SceneConfigs.VerticalUpSwipeJump). That's pretty annoying.

**Comment by willmcneilly** [comment]
I'm also seeing this behaviour in 0.26

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/ios-left-edge-swipe-gesture-can-be-received-by-navigator-even-when-a-modal-is-presented

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
