### ISSUE TITLE
[Docs] Add documentation for initialProps

### ISSUE THREAD

**Issue by StevenLangbroek** [facebook/react-native#746]
When I run the debugger, I see `Running application "ReactNativeApp" with appParams: {"rootTag":1,"initialProps":{}}.`. Is there any documentation regarding how to set these initialProps? I've been scouring the docs, but couldn't find any...

**Comment by colinramsay** [comment]
In AppDelegate.m, after the `RCTRootView alloc`, you can set initialProperties:

    rootView.initialProperties = myNSDictionary;

**Comment by ssssssssssss** [comment]
Any chance to access the initalPropties in JS?

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by lastquestion** [comment]
@brentvatne , how do we contribute documentation changes?

@ssssssssssss to get the properties from JS, something like this:

```
app = React.createClass({
  componentWillMount: function() {
    console.log(this.props);
  }
});
AppRegistry.registerComponent('yourapp', () => app);
```

**Comment by brentvatne** [comment]
@lastquestion - you'll need to clone this repository and modify the `/website` directory :)

**Comment by stereodenis** [comment]
@brentvatne, @StevenLangbroek, @colinramsay, @ssssssssssss, @lastquestion 
did you find a way to pass props to InitialProps?

**Comment by grabbou** [comment]
@brentvatne happy to document it. Anyone have an idea where to add it? (Maybe we should add a special chapter as I'd like to also document `Settings` module)

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/docs-add-documentation-for-initialprops

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
