### ISSUE TITLE
[XMLHttpRequest] `HEAD` request doesn't work

### ISSUE THREAD

**Issue by grabbou** [facebook/react-native#7463]
The same request works fine on iOS, on Android it fails with `TypeError: Network request failed`. It used to work few version ago and no changes were done on the API or app side. Replacing the method from HEAD to GET and also making an extra endpoint on the API side temporarily resolves the issue (worth noting that the API handler itself stays unchanged, to the logic is the same)

AFAIK it has something to do with OkHTTP since:
a) it works flawlessly on iOS
b) it never reaches the API

I am not sure if that was fixed recently in OkHttp, but I guess it's kind of a blocker until we upgrade to 3.x ?

**Comment by 9mm** [comment]
Yes... spent quite a while figuring out what broke. +1

**Comment by DJAndries** [comment]
Any update on this issue?

**Comment by satya164** [comment]
@grabbou Since we've now updated to OkHttp3, is this still an issue?

**Comment by satya164** [comment]
I tried and it seems to be broken.
cc @AndrewJack

**Comment by satya164** [comment]
So I did some tests, and seems the issue is on JS side,

```js
const url = 'https://hey-neighbor.s3.amazonaws.com/uploaded/content/satya164/1e03a291-acda-47d9-ba09-6898837bc48b/1/boy2.png';

fetch(url, { method: 'HEAD' }).then(() => console.warn('fetch: success')).catch(() => console.warn('fetch: error'));

const req1 = new XMLHttpRequest();
req1.open('HEAD', 'https://hey-neighbor.s3.amazonaws.com/uploaded/content/satya164/1e03a291-acda-47d9-ba09-6898837bc48b/1/boy2.png', true);
req1.onreadystatechange = () => {
  if (req1.readyState === req1.DONE) {
    if (req1.status === 200) {
      console.warn('onreadystatechange: success');
    } else {
      console.warn('onreadystatechange: error');
    }
  }
};
req1.send();

const req2 = new XMLHttpRequest();
req2.open('HEAD', url, true);
req2.onload = () => {
  if (req2.status === 300) {
    console.warn('onload: success');
  } else {
    console.warn('onload: error');
  }
};
req2.onerror = () => {
  console.warn('onload: error');
};
req2.send();
```

output:

```
fetch: error
onreadystatechange: success
onload: error
```

So it actually works when using `onreadystatechange`. Haven't investigated why, but these are my findings.

**Comment by jkimbo** [comment]
So, out of curiosity I investigated this bug and think I've found the issue.

Firstly the reason the problem doesn't happen in example 2 in @satya164 code is because of setting an `onreadystatechange` handler on the request sets the [`useIncrementalUpdates` param on `sendRequest` to true](https://github.com/facebook/react-native/blob/031fe4d7975e05e2cc4c750ce415f5f453f63467/Libraries/Network/XMLHttpRequest.js#L392-L394) which means the code path the response logic takes is [slightly different](https://github.com/facebook/react-native/blob/08c375f828fd7755b75660c701c70207f3629c6c/ReactAndroid/src/main/java/com/facebook/react/modules/network/NetworkingModule.java#L337-L341).

As for the actual error, my theory is that since `HEAD` requests don't actually contain any body content, when [`.string()`](https://github.com/facebook/react-native/blob/08c375f828fd7755b75660c701c70207f3629c6c/ReactAndroid/src/main/java/com/facebook/react/modules/network/NetworkingModule.java#L346) is called on the response body an `IOException` is thrown by okhttp (related issue: https://github.com/square/okhttp/issues/1968). This issue will presumably affect any response that doesn't contain any body content so I would guess the best course of action would be to check the `.contentLength()` of the response body before trying to call `.string()`. 

Unfortunately at the moment I can't get react-native to compile from source on my machine, so if anyone else wants to try and fix this issue before me go ahead!

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/xmlhttprequest-head-request-doesnt-work

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by gijoehosaphat** [comment]
We are seeing this same error: `[TypeError: Network request failed]` in our HEAD requests in React Native 0.41.2

**Comment by SandroMachado** [comment]
@charpeni please reopen the issue. It is not fixed.

**Comment by SandroMachado** [comment]
I made a [PR](https://github.com/facebook/react-native/pull/14289) to fix the issue.

The problem is that the HEAD request do not have body and at [this](https://github.com/facebook/react-native/pull/14289/files#diff-f8703d50cf5af4c06824e2928dddb500R373) part of the code React Native will try to convert it to a string. `OkHttp` is not able to convert it and produces an exception.
