### ISSUE TITLE
Issue in DatePickerIOS to select only Date

### ISSUE THREAD

**Issue by alokverma65977** [facebook/react-native#7469]
When I uses the mode then UI is working properly but I get this format "Mon May 09 2016 09:12:58 GMT+0530 (IST)" .Problem is that I only want date format instead of full Date with Time with IST.Fix this issue ASAP.

**Comment by damusnet** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-9** [comment]
Hey @alokverma65977 and thanks for posting this! @damusnet tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
