### ISSUE TITLE
[NavigationExperimental TabBar] How to preserve tab states when switching between tabs?

### ISSUE THREAD

**Issue by joonhocho** [facebook/react-native#7491]
I am using a tabbar with NavigationExperimental based on the [example](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/NavigationExperimental/NavigationTabsExample.js).

I found that the UI states (any data, scroll position, etc.) are lost when navigating away from the current tab.
It causes data to be refetched and UIs to be rerendered when switched back to the old tab making tab switching a very expensive operation.
Native apps preserve the current state and makes the switching back to previously rendered tabs almost instant operation.
How can this be done in react native?
I believe something like `display: none` can be used instead of replacing tab content child, but there is no `display: none` in react native.

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-9** [comment]
Hey @joonhocho and thanks for posting this! @charpeni tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by joonhocho** [comment]
Sorry, created a question on StackOverflow. http://stackoverflow.com/questions/37146339/how-to-preserve-tab-state-when-using-navigationexperimental-on-react-native
