### ISSUE TITLE
Running a JSBundle in node

### ISSUE THREAD

**Issue by arbesfeld** [facebook/react-native#7492]
I am trying to execute a JSBundle in node so that I can simulate a full integration test without starting a simulator / web browser. However, it seems that the user of `require` to load modules makes it impossible to load bundles in node.

Steps to reproduce:

`react-native init MyProject && cd MyProject`
`react-native bundle --entry-file index.ios.js --bundle-output bundle.js`
`node bundle.js`

Error: `AssertionError: path must be a string`

This can be fixed by adding a line `require = global.require` to override the global node `require`. However, it would be nice if the packager did not use the keyword `require` for this so that the bundle does not to be post-processed.

**Comment by brentvatne** [comment]
> so that I can simulate a full integration test without starting a simulator / web browser

Not to derail, but this sounds very interesting, could you provide any more details? Might further motivate people to work on this too :)

**Comment by dsibiski** [comment]
Yes, I would like to hear more about this 😄

**Comment by arbesfeld** [comment]
I was trying something where I would record actions with an [Appium](http://appium.io/) script and then play them back with the bundle running in a node environment. We managed to get this working with a web worker, but would be nice to not have to spin up a browser!

Will share more after I clean up the code :D

**Comment by K-Leon** [comment]
@arbesfeld this sounds really great!!! Could you Share a hint how to get started?

**Comment by wzpan** [comment]
👍 Keep following this thread.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/running-a-jsbundle-in-node

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
