### ISSUE TITLE
How to get the native instance from ReactNative

### ISSUE THREAD

**Issue by X-Liang** [facebook/react-native#7508]
Hey there and thank you for using React Native!

React Native, as you've probably heard, is getting really popular and truth is we're getting a bit overwhelmed by the activity surrounding it. There are just too many issues for us to manage properly.

Do the checklist before filing an issue:

- [ ] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [x] Have a usage question? Ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). We use StackOverflow for usage question and GitHub for bugs.
- [ ] Have an idea for a feature? Post the feature request on [Product Pains](https://productpains.com/product/react-native/). It has a voting system to surface the important issues. GitHub issues should only be used for bugs.

None of the above, create a bug report
------------------------------------------------------------------

Make sure to add **all the information needed to understand the bug** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- [ ] Provide a **minimal code snippet** / [rnplay](https://rnplay.org/) example that reproduces the bug.
- [ ] Provide **screenshots** where appropriate
- [ ] What's the **version** of React Native you're using?
- [ ] Does this occur on iOS, Android or both?
- [ ] Are you using Mac, Linux or Windows?

**Comment by X-Liang** [comment]
I have an native viewController, and the viewController have an react native view, like this 
`- (void)loadView {

    RCTRootView *rcroot=[[RCTRootView alloc] initWithBridge:SharedAppDelegate.bridge moduleName:@"SelectPayment" initialProperties:nil];

    rcroot.frame=CGRectMake(0, 0, SCREEN_WIDTH, SCREEN_HEIGHT);

    self.view = rcroot;
}
`
I want call the viewController method in SelectPayment.js, so I Export the method like this 

`RCT_EXPORT_METHOD(payWithUserId:(NSString *)userId
                  orders:(NSArray *)orders
                  payMethod:(NSUInteger)payMethod
                  totalPrice:(nonnull NSNumber *)totalPrice){
}
`
 This is question: When I push this viewController use [navigation push..], I have a viewController instance , and when I call the export method in .js , I find the viewController don't same. How I get the instance which is pushed;

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow

**Comment by damusnet** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-8** [comment]
Hey @X-Liang and thanks for posting this! @charpeni tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by facebook-github-bot-8** [comment]
Hey @X-Liang and thanks for posting this! @damusnet tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
