### ISSUE TITLE
[Android][ScrollView] Strange thick scrollbar appearance 

### ISSUE THREAD

**Issue by Pranjal5** [facebook/react-native#7510]
I was trying to use a ScrollView which scrolls horizontally, but the scrollbar turns up to thicker than expected.
The react native version that I am using is 0.25.1
The problem is observed on marshmallow(6.0.1) on nexus 5

![2016-05-11](https://cloud.githubusercontent.com/assets/8691791/15179715/2c182e3e-179b-11e6-8408-2b82c8eb9b05.jpg)

```
render() {
    return (
      <View style={styles.container}>
        <Text style={styles.title}>Demo ScrollView</Text>
        <ScrollView
          style={styles.scrollView}
          contentContainerStyle={styles.scrollViewContentStyle}
          horizontal={true}
          decelerationRate={0}
        >
          {this.renderRedCards()}
        </ScrollView>
      </View>
    );
  }
```

**Comment by jayshah123** [comment]
+1

**Comment by calebmer** [comment]
+1

**Comment by jayshah123** [comment]
<item name="android:scrollbarSize">2dp</item> does the trick for now.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/androidscrollview-strange-thick-scrollbar-appearance-

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
