### ISSUE TITLE
How can I use multiple ReactActivity with seperate js bundle?

### ISSUE THREAD

**Issue by kkmoving** [facebook/react-native#7531]
How can I jump from one ReactActivity to another, each with a seperate js bundle?
MainActivty -> index.android.js
SettingActivity -> setting.android.js

I have read many Android examples using React-Native. Unfortunately, all of them are single activity.

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-3** [comment]
Hey @kkmoving and thanks for posting this! @charpeni tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by tianzhijiexian** [comment]
@kkmoving +1
