### ISSUE TITLE
RCTNetworkTask (RCTURLRequestDelegate) is nil when fetching data

### ISSUE THREAD

**Issue by clarle** [facebook/react-native#7545]
Hi, I'm trying to integrate React Native into an existing iOS app right now, and we're seeing issues where all XMLHttpRequest calls aren't returning any responses (whether success, error, or timeout).

I've traced down the issue to the following area:

https://github.com/facebook/react-native/blob/060664fd3d9331f062696e68179bac9cd4544a06/Libraries/Network/RCTHTTPRequestHandler.m#L96

Modifying the code a little bit, here's what I'm seeing in my debugger:

<img width="880" alt="screen shot 2016-05-12 at 6 47 58 pm" src="https://cloud.githubusercontent.com/assets/686352/15235766/0c8c1750-1873-11e6-9e66-6697b8687d73.png">

It looks like the `RCTURLRequestDelegate` is always nil at that point, so `URLRequest:didReceiveResponse:` is never being called, so nothing is ever returned back through the JavaScript bridge.  

The other NSURLSession delegates are being called though, however.

This is occurring in version 0.25.1 on iOS, built on OS X - I've tested this with both manually linking the React Native libraries and installing through CocoaPods as well.  I've also seen this in 0.21 as well.

I'm trying to find a minimal repro case for this bug, but I'm having difficulty root causing what's causing this issue.  It seems as if the `_delegates` NSMapTable is releasing the delegate values early, though I'm not sure how that's happening.

Let me know if there's any additional information I might be able to help provide.

**Comment by AndrewJack** [comment]
@facebook-github-bot label iOS

**Comment by lacker** [comment]
I think you point to the problem here - without a minimal repro case I don't think anyone else will be able to make much progress here. Practically in order to achieve a minimal repro I think you have to do something like, start with your project, get rid of half your code, repeat if needed and see at what point the bug goes away. Anyway, I am going to close this issue but if you do find a minimal repro then please feel free to open a new issue.
