### ISSUE TITLE
Run base starter app from bundle (/bin/sh failed with exit code 1)

### ISSUE THREAD

**Issue by anthonywebb** [facebook/react-native#7548]
Walking through the tutorial (install prerequisites, then 'react-native init AwesomeProject', and 'react-native run-ios', runs fin in the simulator) when I open the xcode project and try to run from a local bundle (option 2 in AppDelegate.m) I get the following error:
```
/Users/webb/projects/nativeapp/fuel/node_modules/node-haste/lib/index.js:331
Object.assign(DependencyGraph, {
       ^
TypeError: Object.assign is not a function
    at Object.<anonymous> (/Users/webb/projects/nativeapp/fuel/node_modules/node-haste/lib/index.js:331:8)
    at Module._compile (module.js:430:26)
    at Module._extensions..js (module.js:448:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/webb/projects/nativeapp/fuel/node_modules/babel-register/lib/node.js:166:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (index.js:16:30)
    at Module._compile (module.js:430:26)
Command /bin/sh failed with exit code 1
```
The error persists if I run in release or debug build configuration.  And happens both on the simulator and device.  Pretty much I am only able to run the sample app with AppDelegate.m configured for option 1 (load from dev server) which wont fly when I want to publish my app.

I tried both node 5.8 and 6.1.  Can anyone else think of next steps in debugging?  This is just the base sample app, it should run from a local bundle right?

```
"dependencies": {
    "react": "^0.14.8",
    "react-native": "^0.25.1"
  }
```
I am on a mac, have not tried android, but iOS is for sure non functional.

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-2** [comment]
Hey @anthonywebb and thanks for posting this! @DanielMSchmidt tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by anthonywebb** [comment]
Same error on 0.26 and no feedback on stack overflow :(

**Comment by jhampton** [comment]
+1 for this error on 0.26
