### ISSUE TITLE
How to skip ssl verify in android?

### ISSUE THREAD

**Issue by yanpeipan** [facebook/react-native#7551]
When I fetch https://api.chelook.com, I got warning: Network request failed. In iOS, add  the following code to Liabraries->RCTNetwork, and it works well. but I don't know how to do in Android.

```
- (void)URLSession:(NSURLSession *)session didReceiveChallenge:(NSURLAuthenticationChallenge *)challenge
 completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition disposition, NSURLCredential * __nullable credential))completionHandler{
  if (RCT_DEBUG) {
    completionHandler(NSURLSessionAuthChallengeUseCredential, [NSURLCredential credentialForTrust:challenge.protectionSpace.serverTrust]);
  }
}
```

**Comment by AndrewJack** [comment]
@facebook-github-bot stackoverflow

**Comment by AndrewJack** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-0** [comment]
Hey @yanpeipan and thanks for posting this! @AndrewJack tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by saatchibhalla** [comment]
Were you ever able to resolve this? Same issue.
