### ISSUE TITLE
ListView change one row of dataSouce,  but the ListView not re-render 

### ISSUE THREAD

**Issue by 2young2simple** [facebook/react-native#7563]
on ListView 368
`var shouldUpdateRow = rowCount >= this._prevRenderedRowsCount &&
          dataSource.rowShouldUpdate(sectionIdx, rowIdx);`
 rowShouldUpdate = true  but  rowCount >= this._prevRenderedRowsCount  is false ,not changed？
 && or  || ?

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-3** [comment]
Hey @2young2simple and thanks for posting this! @DanielMSchmidt tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by myaskevich** [comment]
@2young2simple I just came across the same issue myself. After some research I managed to solve the problem by the following thing:

In your `renderRow()` method make sure to specify a unique `key=` prop of root row view, ex.:
```
  _renderEvent(event, sectionId, rowId) {
    return (
      <View key={`ROW_${sectionId}_${rowId}`}>
        <EventCell
          onSelectEvent={() => this._onSelectEvent(event._id)}
          onHighlight={() => highlightRowFunc(sectionId, rowId)}
          onDehighlight={() => highlightRowFunc(null, null)}
          eventId={event._id} />
      </View>
    );
  }
```

**Comment by 2young2simple** [comment]
@myaskevich thank !
