### ISSUE TITLE
Cannot alter size of Switch

### ISSUE THREAD

**Issue by hasen6** [facebook/react-native#7573]
Styles like height and width don't seem to affect the switch at all. It kind of looks ridiculous having a set up with several switches on different devices. The only possible workaround I found is to manually add the style tag `style={{transform: [{scaleX: 2}, {scaleY: 2}]}}` but that is really not very practical since you'd have to write a detect each screen size and write an appropriate transform value. 

Also when transformed the switch's new size does automatically adjust other elements  position accordingly like it would with `height:` or `width:` size changes so you have to also manually add margins to push other elements away from it.

iPhone 5s
![5s](https://cloud.githubusercontent.com/assets/15882674/15274685/42413fea-1aeb-11e6-93d0-02d9fb80562b.png)

iPhone 6s+
![6s](https://cloud.githubusercontent.com/assets/15882674/15274684/42104674-1aeb-11e6-853e-8634c5ef183f.png)

iPad Air 2
![ipadair2](https://cloud.githubusercontent.com/assets/15882674/15274686/436aca94-1aeb-11e6-99bf-5d58eb312068.png)

**Comment by dsibiski** [comment]
I'm pretty sure this is how native elements are supposed to work on the platform. On an iPhone 6 Plus and an iPad, a switch is supposed to be "small" because it has not really changed it's size. The idea is that there should be more screen real estate, not larger elements.

If you still want to scale it, I think it makes perfect sense to detect the actual size of the device and go from there. You can use the `Dimensions` object provided by React Native to look at what the current size of the device is, and adjust accordingly.

Perhaps I didn't fully understand what you are talking about here. If my answer doesn't correspond, please clarify you issue a little more. 😄 Thanks!

**Comment by hasen6** [comment]
The elements are not small on iPhone 4s, only on larger devices. The issue isn't small or large, its that the size changes with every device which means the whole display layout will change and everything will move about accordingly. Trust me it doesn't work well at all. I used to just set sizes for all elements with fixed numbers or leave them as default but while it looks fine on one device, it looks ridiculous on another and all elements even end up in the wrong places.

Now I resize elements based on device size using dimensions but the switch is one thing that doesn't resize since it can't accept normal height and width styling. Also, as I said, the transform doesn't work well at all since it effectively retains its original size and will just grow and block out other elements. I've attached a screen shot to show how it messes up things even with just ONE switch. You can imagine with many it would be even more ridiculous.

Can I ask why you think only the switch should have appear small on larger devices? How is it different to other elements?

Here are the examples. The text automatically resizes depending on screen size, if it didn't it would look silly. Its still gonna look smaller on iPad pro even with resize. If you don't resize things then all elements end up in one corner of the screen on larger devices while they fill the screen of smaller devices.

iPhone 5s - normal size
![5sa](https://cloud.githubusercontent.com/assets/15882674/15309753/1c9a430e-1c1c-11e6-858d-a1ebd710fdc4.png)

iPad pro normal size
![ipadpro](https://cloud.githubusercontent.com/assets/15882674/15309754/1e777840-1c1c-11e6-840f-c7ad62d6a0d1.png)

iPad pro with transform
![ipadprotransform](https://cloud.githubusercontent.com/assets/15882674/15309755/21b9b2f2-1c1c-11e6-90b3-fa820110e5c8.png)

**Comment by dsibiski** [comment]
Sorry, I still don't follow. How is this supposed to work on the native platform? What are you actually trying to do here? Why do you need to resize the switch at all?

**Comment by hasen6** [comment]
Check the screenshots?

**Comment by hasen6** [comment]
"If you don't resize things then all elements end up in one corner of the screen on larger devices while they fill the screen of smaller devices."

**Comment by dsibiski** [comment]
Again, how is this supposed to work on the native platform and how is it different here?

**Comment by hasen6** [comment]
"If you still want to scale it, I think it makes perfect sense to detect the actual size of the device and go from there. You can use the Dimensions object provided by React Native to look at what the current size of the device is, and adjust accordingly."

This is incorrect, unless you can show me otherwise. Switch can only be 'transformed' accordingly which is impractical and leads to issues as shown in my screenshots. I think you're under the assumption that switch size can be altered in the normal way with height and width but as far as I can tell it cannot.

I think that's why your'e not understanding the issue.

**Comment by hasen6** [comment]
Yes exactly, it doesn't work well on the native platform. This is what I'm trying to show you. Its not different here, this is exactly how it is on the native platform.

**Comment by dsibiski** [comment]
> Yes exactly, it doesn't work well on the native platform. This is what I'm trying to show you. Its not different here, this is exactly how it is on the native platform.

Ok, that's what I wanted to know...so why do you think this is a bug for React Native? Perhaps this should be posted to Stack Overflow where you will get more feedback on how this could be accomplished.

**Comment by hasen6** [comment]
Its a bug because for some reason switch cannot be resized whereas every other element can. I just don't see why it can't be resized whilst all other elements can.

**Comment by dsibiski** [comment]
The reason why you can't set width/height on iOS Switch is because React Native is using the native component from UIKit, which also doesn't allow setting the width/height...only scaling. So it is a limitation of the platform (as we established above).

You can even see here in Apple's documentation:

> UISwitch overrides initWithFrame: and enforces a size appropriate for the control.
https://developer.apple.com/library/ios/documentation/UIKit/Reference/UISwitch_Class/#//apple_ref/occ/instm/UISwitch/initWithFrame:

Elements sizes for Switch and SegmentedControl (most likely other too) simply cannot be set via width/height props as is dictated by the underlying platform.

**Comment by hasen6** [comment]
Ok I see. I'm finding I have to move further and further away from native elements since they just don't work well with anything else. Ok thanks for your help. I guess its an issue with the UIKit itself then.

**Comment by dsibiski** [comment]
Yeah, I guess that's one downside of using UIKit native elements. You might be able to reproduce it in Javascript, but then you have other problems.

Glad to help 👍 Sorry that it took so long for me to understand what you were asking. 😄

**Comment by dsibiski** [comment]
@facebook-github-bot expected

**Comment by facebook-github-bot-5** [comment]
The comment above tells me this is expected behavior. Closing this as we'd like to use the GitHub issue tracker for bugs. If you'd like to change how this feature works please post a feature request on [Product Pains](https://productpains.com/product/react-native/) so that other people can vote on it.
