### ISSUE TITLE
[WebView] [Android] Geolocation does not work inside a WebView, the permission request popup never opens

### ISSUE THREAD

**Issue by anna-gladushko** [facebook/react-native#7609]
Further improvement for https://github.com/facebook/react-native/commit/f94abd3c012bd89b35b6a8165ffce1037c36cef2 is suggested:

`webView.setWebChromeClient(new WebChromeClient() {
 public void onGeolocationPermissionsShowPrompt(String origin, GeolocationPermissions.Callback callback) {
    callback.invoke(origin, true, false);
 }
});`

More details: http://stackoverflow.com/a/5423026

**Comment by danielbraun** [comment]
Can you submit a pull request?

**Comment by bbay** [comment]
I also ran across this problem :/

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/webview-android-geolocation-does-not-work-inside-a-webview-the-permission-request-popup-never-opens

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by spearmootz** [comment]
this issue still occurs
