### ISSUE TITLE
[Android][Windows][0.25.1] FileWatcher timeout error message not show in terminal

### ISSUE THREAD

**Issue by HaydnChen** [facebook/react-native#7610]
After my project includes more and more js files and node modules, I suddenly found that the packager  not detect my changes when Reload JS, I have to stop and run start again. After researching I finally found the root cause is FileWatcher failed to launch caused by MAX_WAIT_TIME reaches. But why error/waring messages not show in terminal? It will puzzle new developers.

**Comment by AleCaste** [comment]
I sent a pull request long ago to fix this issue and some others that are related to it:
https://github.com/facebook/node-haste/pull/63
... but it seems the author expects us to do all the work instead of just fixing the module with those ideas suggested on the pull request.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/androidwindows0251-filewatcher-timeout-error-message-not-show-in-terminal

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
