### ISSUE TITLE
[Bug] Linking example is broken

### ISSUE THREAD

**Issue by cablegunmaster** [facebook/react-native#7615]
Actions:
1. Open page: http://facebook.github.io/react-native/releases/0.25/docs/linking.html#handling-deep-links
2. Open the phone icon.
3. Experience bug:
"Touchable native feedback is not supported on this platform!"
4. ?????
5. Profit.

Still I am wondering how to use this feature.
Goal: retrieve the url from the webview on android, when it is set on a certain url. (oauth2 redirect_url)

**Comment by dsibiski** [comment]
I think the problem here is that the example on this page is for Android but the demo simulator is iOS (hence the reason for that error message).

Perhaps @caabernathy could chime in as I think she implemented most of these examples. Perhaps we can simply remove this example Demo for this one until either we have a Linking example for iOS and/or until we have Android simulators for the Demo.

**Comment by lacker** [comment]
Looks like this is fixed

**Comment by honeyjie** [comment]
I  have the same problem
