### ISSUE TITLE
iOS simulator input always mapping to standard QUERTY keyboard layout, not other layouts

### ISSUE THREAD

**Issue by ferologics** [facebook/react-native#7621]
- [x] What's the **version** of React Native you're using?
0.25.1
- [x] Does this occur on iOS, Android or both?
iOS
- [x] Are you using Mac, Linux or Windows?
mac, el cap

the iOS simulator is always taking input from a standard QUERTY keyboard layout, not sure if this is RN issue or iOS Simulator. I'm using the Colemak layout and it maps in the simulator to QUERTY keyboard

**Comment by lacker** [comment]
I'm not sure if trolling because QUERTY is not a thing. Also we left this stale for a while. Sorry. If you're still interested in this issue, I suggest debugging whether it's an RN issue or an iOS simulator issue by seeing if it repro's on rnplay. Otherwise well then I guess it doesn't matter. Anyway I am closing this issue until further notice.

**Comment by ferologics** [comment]
I found out that this is just the way the iOS simulator works, unrelated to React Native
