### ISSUE TITLE
[General] Eliminate use of Haste Modules

### ISSUE THREAD

**Issue by scriptjs** [facebook/react-native#7636]
There was talk that the direction for the project would to be normalize modules in React and React Native so they would no longer rely on Haste. Haste is proprietary to facebook and non standard. To this end, modules in these projects would then work more transparently in the JavaScript ecosystem and allow for other building and packaging options. ie browserify, webpack, rollup, etc.

Can a team member please provide an update in this regard. The direction appears to be the opposite. More projects are being perpetuated (Windows, OSX) with Haste and with release after release of react and react-native I see no effort to change this which is concerning

**Comment by satya164** [comment]
cc @davidaurelio

**Comment by davidaurelio** [comment]
The plan is to use a pre-publish step similar to React so that the files will be in e.g. `lib/*` when published to npm. The first step is taken; React will import modules from React native via node-style imports (facebook/react@151e1d7014ed63452218be496a6edf2355eb6a11).

The problem with additional platforms is that we need a way to override modules per platform, and *not* including the original (from this repo) source is a desirable. See the discussion after the merge in #7639 for a first idea. Unfortunately I have no silver bullet. Ideas are welcome.

It’s definitely my goal to kill `providesModuleNodeModules`, and that merge has made it a lot harder.

**Comment by davidaurelio** [comment]
cc @bestander @mkonicek

**Comment by scriptjs** [comment]
@davidaurelio I will think on this as well. #7639 is a regression that concerns me since. Yes, Windows support is important but we need to get away from current state without exceptions.

**Comment by mkonicek** [comment]
Thanks for replying @davidaurelio! I'll close this issue as it's more of a discussion than an issue that can be acted on (albeit still very useful of course!).
