### ISSUE TITLE
How to add tabs dynamically from the json obtained

### ISSUE THREAD

**Issue by agumack** [facebook/react-native#7653]
Hi, How to add tabs dynamically from the json obtained. My API returns the json with tab title, icon and component,...

Thank so much.

**Comment by chirag04** [comment]
@facebook-github-bot stackoverflow

**Comment by chirag04** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-0** [comment]
Hey @agumack and thanks for posting this! @chirag04 tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
