### ISSUE TITLE
Asyncstorage Getvalue from key.

### ISSUE THREAD

**Issue by cablegunmaster** [facebook/react-native#7654]
Trying to practise my redux skills, but im stuck, and in need of a few pointers.

- Where to implement the database calls?
I have a redux workflow with redux-thunk but not sure where to put it in.

Component loads a  componentDidMount() -> With databaseActions.fetchInfo()
My database action launches a reduce command ->  getInfo now im wondering, where to put the next step in. I have a problem resolving a promise object :

```
const INFO_KEY = '@_KEY';

let token = "";
const databaseReducer = ( state = initialState, action ) => {
    switch (action.type) {
             case types.GET_INFO:
             AsyncStorage.getItem(INFO_KEY, (err, result) => {
                 token = result;
             });
     }
```
Checked the content of the databaseState, but it gives me a promise back , withinside a key. but don't know how to resolve it. got the feeling i'm very close.

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-7** [comment]
Hey @cablegunmaster and thanks for posting this! @charpeni tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
