### ISSUE TITLE
[General] Remove packager from react native

### ISSUE THREAD

**Issue by scriptjs** [facebook/react-native#7668]
It is important that the packager be separated out of this project. It is currently opinionated for react-native – but this is also a curse. Simultaneous with exposing modules properly as node modules (as opposed to Haste  [https://github.com/facebook/react-native/issues/7636](https://github.com/facebook/react-native/issues/7636)), the packager needs to leave behind what is necessary for building up node modules from Haste into  libs for react-native and focus on providing a better experience as a packager on its own.

When extracted, it will be competing with the likes of browserify, webpack, and rollup and we will have choice for the experience that best works with our projects.

I realize that a package.json exists for this within the react-native sources but what I am suggesting is to remove it from the react-native sources completely and begin publishing and committing to it as a separate package.

**Comment by aleclarson** [comment]
Has this been addressed before? Interested to hear why it's the way it is.

**Comment by lacker** [comment]
Yeah I think @cpojer wants to do this. I'm going to close this issue since we are focusing issues on bug reports rather than feature requests but overall yes this is a good idea, the reason it is like it is is just because it takes work to refactor, but I think this is gonna happen at some point probably.
