### ISSUE TITLE
react-native init <ProjectName> hangs on windows

### ISSUE THREAD

**Issue by gitlovenotwar** [facebook/react-native#7681]
Followed all installation instructions from docs https://facebook.github.io/react-native/docs/getting-started.html#content

platform: windows
version: 7
node: v6.2.0
npm: 3.9.2
react-native-cli: 0.2.0

Error:
<pre>
This will walk you through creating a new Rea
ct Native project in D:\xampp\htdocs\staging\
tutorials\AwesomeProject
Installing react-native package from npm...
events.js:160
      throw er; // Unhandled 'error' event ^

Error: spawn npm ENOENT at exports._errnoException (util.js:953:11)
    at Process.ChildProcess._handle.onexit (i
nternal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:3
48:16)
    at _combinedTickCallback (internal/proces
s/next_tick.js:74:11)
    at process._tickCallback (internal/proces
s/next_tick.js:98:9)
    at Function.Module.runMain (module.js:577
:11)
    at startup (node.js:160:18)
    at node.js:449:3</pre>

**Comment by perkola** [comment]
+1
Having the same problem. Same setup and versions.

**Comment by gitlovenotwar** [comment]
Any help, please?

**Comment by gitlovenotwar** [comment]
@perkola Have you manage to fix the problem?

**Comment by joewood** [comment]
@gitlovenotwar have you tried using the most recent react-native-cli? It's current on v.1. 
```
npm outdated -g
npm update -g react-native-cli --save
```

**Comment by gitlovenotwar** [comment]
@joewood oh, wow, I don't. Though what's the --save for on global?

**Comment by joewood** [comment]
Yeah, ignore the --save - not required.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/react-native-init-projectname-hangs-on-windows

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
