### ISSUE TITLE
android fecth TypeError: Network request failed(…)

### ISSUE THREAD

**Issue by wasabia** [facebook/react-native#7688]
when use fetch in android.

when have symbol '|'  in url

use fetch get a url like 
fetch("/api?dates=2016-05-23|2016-05-24")

will catch a error TypeError: Network request failed(…)

in IOS it is ok..

**Comment by jiangqqlmj** [comment]
you can try  encode url parms~

**Comment by wasabia** [comment]
@jiangqqlmj ok thanks

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-fecth-typeerror-network-request-failed

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
