### ISSUE TITLE
react-native upgrade advice

### ISSUE THREAD

**Issue by npomfret** [facebook/react-native#7696]
I'm trying to upgrade from 0.24 to 0.26.  In the past I've not always run `react-native upgrade` because it destroys my Xcode project and I lose all the changes I've made to it (like setting the build number).  And in the past it seems that it's not always necessary to run it.  However this time, after just changing my package.json to bring in the new version or react and react-native my IOS project wouldn't start.  So I thought maybe this time I need to run `react-native upgrade`...

I guess my question is, when do you **need** to run `react-native upgrade`?  If I run it it creates a lot of work for me.

**Comment by formatlos** [comment]
You basically should run `react-native upgrade` after updating RN. 

My steps for upgrading:
1. git branch 
2. update RN to new version
3. run `react-native upgrade`
4. let the process overwrite all files 
5. diff replaced files 
6. merge in my changes
7. test 
8. commit
9. merge branch back into master

**Comment by dsibiski** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-3** [comment]
Closing this issue as @dsibiski says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.
