### ISSUE TITLE
react-packager has encountered an internal error

### ISSUE THREAD

**Issue by shaikhussian** [facebook/react-native#7710]
hai, some times when i run my project i am facing this problem, i don't know exactly what the error is, here i am attaching the screenshots of the error in simulator and terminal, please give any suggestions to how to solve this

![simulator screen shot 24-may-2016 10 07 18 am](https://cloud.githubusercontent.com/assets/11956308/15492298/6703c052-2197-11e6-8f3c-0bfe75e3eeee.png)

in terminal
![screen shot 2016-05-23 at 11 44 39 am](https://cloud.githubusercontent.com/assets/11956308/15492304/75b5d8f6-2197-11e6-83f6-ead609fb924d.png)

**Comment by shaikhussian** [comment]
Please respond

**Comment by damusnet** [comment]
According to the stack trace, you are probably trying to require a file that is not a valid image.

@facebook-github-bot stack-overflow

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/react-packager-has-encountered-an-internal-error

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by jpca999** [comment]
Restart the computer will fix it

**Comment by herman-rogers** [comment]
@damusnet has nothing to do with that. Like @jpca999 said, restarting your computer will fix this. Looks like it's an internal issue on the react-native side and has nothing to do with those using react-native. Should be fixed and not ignored.
