### ISSUE TITLE
NavigationCard will only re-render when the route changes

### ISSUE THREAD

**Issue by pbrito** [facebook/react-native#7720]
I'm trying NavigationExperimental and the NavigationCardStack.

But the renderScene isn't being call when the state is update.
You can test in the Examples/NavigationCardStackExample,when you press the direction doesn't happen anything only after you push new route a new direction is shown.

![simulator screen shot 24 05 2016 13 37 58](https://cloud.githubusercontent.com/assets/1783930/15504352/72fe78d8-21b6-11e6-87eb-5df111cb18a3.png)

**Comment by pbrito** [comment]
The Tabs and Composition Examples of  NavigationExperimental don't work either

**Comment by Kakahn** [comment]
same problem here :(
since 0.26 then 0.26.2 renderScene() isn't call after state changes.

**Comment by pbrito** [comment]
This bug was introduced with the commit [bb39a2e]  

Reduce extra rendering in NavigationCard

`  shouldComponentUpdate(nextProps: SceneViewProps, nextState: any): boolean {
    return (
      nextProps.sceneRendererProps.scene.navigationState !==
        this.props.sceneRendererProps.scene.navigationState
    );
  }
`

> Summary: This adds a new SceneView with a shouldComponentUpdate policy of only re-rendering when the scene's state changes.

But what this code is doing is checking the navigationState.And it doesn't re-render if the scene state changes and the navigationState is the same.
This kind of check shouldn't be done by react-native, for the same reason that react has shouldComponentUpdate and doesn't do it automatically . It's very difficult to guess the intensions of the programmer.

**Comment by vikeri** [comment]
I still have this issue with 0.27.0, I had to go into the source code of React and comment out those shouldComponentUpdate clauses 😞

**Comment by oHaiyang** [comment]
recently updated from 0.25 to 0.29 and got the same problem. And I use Redux with my APP.

I also think it's caused by [bb39a2e], all the scenes are rendered by calling of render method of `class SceneView` in `NavigationCard.js`. So if you only changed other states but `navigationState`, scenes won't re-render.

Could anyone confirm this is a bug or my misunderstanding?

**Comment by ericvicenti** [comment]
I agree the shouldComponentUpdate policy here is a bit strict. But this is intentional to prevent extra rendering: we will only re-render a card when the route changes in the navState. 

How would people like to see this change? We can't afford to re-render the insides of every scene whenever the navState changes, because that would result in several re-renders of every scene on every transition.

cc @ide @hedgerwang @jmurzy

**Comment by snf** [comment]
I used redux and created "container" components that where connected to the state instead of depending on NavigationCard passing the state and updating the children components. Probably not the most elegant solution. Tried removing shouldComponentUpdate but made the app perform really bad on debug mode.

**Comment by hedgerwang** [comment]
I'd say it's that the scene itself has to manage that itself. We'd recommend something like *Your Scene component should implement `shouldComponentUpdate` to avoid excessive re-render*.

**Comment by prabhaav** [comment]
How about allowing the user to send a boolean flag to force re-render of the scenes? I am also having issues using redux middleware store to re-render scenes.

**Comment by max-mykhailenko** [comment]
@prabhaav but why we need this? We should shallow check route and index. If you want to re-render — send a new values.

**Comment by prabhaav** [comment]
@max-mykhailenko I am using redux for states and redux-saga for async functions. When the scenes receive new props, they should be re-rendered. With the current flow, the component NavigationCardStack is re-rendered, but the scenes are not re-rendered.

**Comment by max-mykhailenko** [comment]
@prabhaav I work in the same way. In redux you don't change routes array, you create new. Shallow comparison can check it.

**Comment by prabhaav** [comment]
@max-mykhailenko not necessarily. In my case, the scene's are getting new props after the component is rendered. So if there's no change in the route stack, the scene's aren't re-rendered.

**Comment by prabhaav** [comment]
FYI: Disabling shouldComponentUpdate for class SceneView in NavigationCard.js fixed my issue.

**Comment by max-mykhailenko** [comment]
@prabhaav `connect` scene directly to redux and it will receive props not from NavigationCard.

**Comment by prabhaav** [comment]
@max-mykhailenko Thanks Max that was a much cleaner solution!

**Comment by RichardLindhout** [comment]
I have the same problem, fixed it with a a redux container.

**Comment by ide** [comment]
NavigationCard no longer implements shouldComponentUpdate (RN 0.33).

**Comment by mmazzarolo** [comment]
I'm probably missing something but since `react-native@0.33.0` whenever I push/reset a route `renderScene` is called twice... Is this behavior correct? 
Should I implement myself the shouldComponentUpdate? 
Any suggestions on the right place to do do this?
Also, does a place to discuss about Navigation Experimental exists?  

Thanks guys.

@ericvicenti @ide 

Snippet for reference, nothing fancy though
```javascript
// CardStack
<CardStack
  navigationState={navigationState}
  onNavigate={dispatch}
  renderOverlay={this._renderToolbar}
  renderScene={this._renderScene}
  style={styles.container}
/>

// RenderScene
_renderScene = (props) => {
  const { currentRoute } = this.props
  switch (currentRoute.key) {
    case 'splashScreen': return <SplashScreen />
    case 'authScreen': return <AuthScreen />
    case 'mainScreen': return <MainScreen />
    default: return null
  }
}

// Reducer
export const initialState = {
  key: 'root',
  index: 0,
  routes: [routes.splashScreen]
}

export default (state = initialState, action) => {
  switch (action.type) {
    case actionTypes.PUSH: {
      const { route } = action
      if (state.routes[state.index].key === (route && route.key)) return state
      return navigationStateUtils.push(state, route)
    }
    case actionTypes.POP: {
      if (state.index === 0 || state.routes.length === 1) return state
      return navigationStateUtils.pop(state)
    }
    case actionTypes.RESET: {
      const { route } = action
      return { ...state, index: 0, routes: [route] }
    }
    default:
      return state
  }
}
```

**Comment by ryankask** [comment]
Yes it makes sense that it is rendering twice. Once when you update your navigation state and then again when the transition ends.

Your solution is basically reverting the commit that addressed this issue. I'll probably add something similar.

**Comment by mmazzarolo** [comment]
@ryankask 
I noticed it not only re-render, it also mount, unmount and re-mount the component.

**Comment by ryankask** [comment]
Interesting. I just upgraded and I'm not having that issue.

**Comment by joaovpmamede** [comment]
I'm having the same exact issue as @mmazzarolo.
Tested on 0.32 and 0.31 and works fine.

What happens with me is that I have some Container Component that fetches data.
That Component is pushed at some point and when I want to pop the route that's using that Component it first renders the previous scene, then the scene that is about to be "popped" and then the previous scene again (between I get an error because of that Container Component).

Also when I start the app the `renderScene` function renders twice.

**Comment by mmazzarolo** [comment]
@joaovpmamede Did you try wrapping the renderScene in like in my example?  
I know, it's ugly, but it works

**Comment by joaovpmamede** [comment]
@mmazzarolo nop but I'll try that now.
Thanks.

**Comment by littlesome** [comment]
#9948  same 'render-twice' issue

**Comment by joaovpmamede** [comment]
I probably shouldn't ask this here but no one in Discord helped me yet.

**Comment by joaovpmamede** [comment]
I probably shouldn't ask this here but no one in Discord helped me yet.

The issue that I'm having with scenes being re-rendered is that when I push a scene I also add a key (id) with a specific value so that the next scene Container Component (with `connect`) can use it to grab some data from a store.
After a `pop` that same view is re-rendered before it "goes way" but the state no longer has the id the `mapStateToProps` needs.
Right now I'm doing some conditionals on `mapStateToProps` but I don't like this and honestly I don't think I should.

What would be the correct approach?

**Comment by ericvicenti** [comment]
> state no longer has the id the mapStateToProps needs.

How are you accessing this id? Is that data coming from the renderScene props?

**Comment by joaovpmamede** [comment]
@ericvicenti the id is being added to the route object when I trigger the action that will be pushed to the routes array.

On the Container Component I have a mapStateToProps selector that will get data using state from navigation (where I get this id) and state from other reducer.

renderScene renders this Container Component with a conditional once I push a new route but as soon as I pop that route I get this issue of re-rendering the Container Component.

**Comment by ericvicenti** [comment]
Yep, in NavigationCardStack, the scene gets re-rendered as it animates out. This is consistent with reality because the component still needs to exist for a moment during the transition.

The `shouldComponentUpdate` policy of the children can be set to prevent undesirable re-rendering. For a hint on how to do that, see the container that we removed in v0.33: https://github.com/facebook/react-native/commit/6c4d3c39c670e087930fcdae566e82db4b081113

**Comment by joaovpmamede** [comment]
@ericvicenti but because the selector function (from mapStateToProps) that grabs the data from the reducer runs before the child Component(where I could use the shouldComponetUodate) I still get this error. 

Still not sure how to deal with this without having to check if the id is present. And if not there I have to create empty objects or arrays for the child Componet.

**Comment by MossP** [comment]
@mmazzarolo Did you find a work around for the Unmount, Remount issue. It causes havoc with the stack when popping back through. Handling a re-render shouldn't be an issue but an unmount trashes everything.

**Comment by mmazzarolo** [comment]
Hey @MossP, I'm still using the wrapper i posted above even if it's not the prettiest solution...

**Comment by MossP** [comment]
@mmazzarolo
That.
Is.
Awesome.

It didn't work for me the first time so I assumed it was a WIP or not for current RN version. A few typos later et voila. Thank you.

**Comment by mmazzarolo** [comment]
No worries man , glad it worked!

**Comment by DominicTobias** [comment]
Thanks @mmazzarolo, I simply extended my `SceneView ` from [https://facebook.github.io/react/docs/react-api.html#react.purecomponent](PureComponent) and that did the trick
