### ISSUE TITLE
Examples won't compile with latest NDK (GCC=4.9)

### ISSUE THREAD

**Issue by GeoffreyPlitt** [facebook/react-native#7728]
The latest Android NDK includes GCC 4.9, not 4.8. It doesn't even seem easy to find the old NDK's.

The code here requires GCC 4.8, but even when I change it to 4.9 in ReactAndroid/src/main/jni/Application.mk, the code now has warnings/errors, seems to require 4.9.

Any suggestions on how to actually get Examples working?

**Comment by charpeni** [comment]
I already answered that on Stack Overflow : http://stackoverflow.com/a/36213150/4483873

Or even in the [React Native documentation](https://facebook.github.io/react-native/docs/android-building-from-source.html).

Good luck!

**Comment by charpeni** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-7** [comment]
Closing this issue as @charpeni says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.
