### ISSUE TITLE
[Feather request] Automatic re-dispatch when subview refuse to handle event.

### ISSUE THREAD

**Issue by Nick-The-Uncharted** [facebook/react-native#7738]
If I understand the source code correctly. ParentView will handle touch event if subView refuse to handle event. But in iOS (not familiar with Android) parentView will handle event after make sure there is no other subview which can handle this event (Which is how `tap through overlay view` work).   
Of course we can always do this (re-dispatch event) by ourselves , but I think it can be very handy to having this feather or providing a method like `hitTest` to see whether there is a subview can handle this event.

**Comment by ide** [comment]
It's not quite as generic, but you might want to take a look at the pointerEvents prop to see if it works for your use case. Specifically, that's how I'd do an overlay that doesn't capture touches.

**Comment by Nick-The-Uncharted** [comment]
@ide I already solved my problem, justing looking for a more elegant way so I can easily handle this next time I run into problem like this.   
And my use case is a little tricky that only a part of the view can capture touches while the other part can't.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/feather-request-automatic-re-dispatch-when-subview-refuse-to-handle-event

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
