### ISSUE TITLE
Transform 'skewY' isn't working properly

### ISSUE THREAD

**Issue by Pandzinho** [facebook/react-native#7752]
`skewY`  isn't working as expected, it seems that instead of skew transform - 2D rotation is applied. 

Render:

```
<View style={styles.container}>
    <View style={styles.background}>
        <Image style={styles.bgImage}
               source={require('../assets/live_betting.png')} />
    </View>
    <View style={styles.placeholder} />
    <View style={styles.overlay}
          onClick={this.navigateToGame()}>
    </View>
</View>
```

Styles:

```
const styles = StyleSheet.create({
    container: {
        flex: 1,
        flexDirection:'column',
        backgroundColor: '#F5FCFF'
    },
    background : {
        position: 'absolute',
        top:0,
        left:0,
        right:0,
        bottom:0
    },
    bgImage: {
        alignSelf : 'center'
    },
    placeholder : {
        flex: .75
    },
    overlay : {
        flex: .25,
        backgroundColor: 'rgba(249,168,37,0.7)',
        transform: [{skewY: '10deg'}]
    }
});
```

Result : 

![skewbug](https://cloud.githubusercontent.com/assets/13085426/15540544/476a4eea-2288-11e6-8a87-44a365a2a10c.png)

Result should be:

![propperskew](https://cloud.githubusercontent.com/assets/13085426/15540551/56587b84-2288-11e6-9390-5bbe47e34787.png)

I'm developing on Ubuntu 15.10, using react-native v : 0.25.1. Error occures on android. It isn't checked on iOS.

**EDIT**

It seems that SkewY transforms is 3D transformations, but there isn't SkewZ transform which in this case would be proper.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/transform-skewy-isnt-working-properly

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
