### ISSUE TITLE
Cannot read property 'injectMeasure' of undefined

### ISSUE THREAD

**Issue by zhongjie-chen** [facebook/react-native#7753]
react-native: 0.26.2
android

**Comment by casoetan** [comment]
I think the error has to do with react <code>15.1.0</code>. I'll advice you update your package.json to <code>15.0.2</code> (not <code>^15.0.2</code>) so you are locked in at <code>15.0.2</code> till this is fixed.

**Comment by Max93** [comment]
Work for me, thank's @casoetan

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/cannot-read-property-injectmeasure-of-undefined

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
