### ISSUE TITLE
How to invoke native Module on Main Thread

### ISSUE THREAD

**Issue by gilnuy** [facebook/react-native#7771]
i create a native modeul named RNBroardcast
``` 
#import "RCTBridgeModule.h"

@interface RNBroardcast : NSObject <RCTBridgeModule>

@end

RCT_EXPORT_METHOD(startBroardcast:(RCTResponseSenderBlock)callback)
{
}
```

this is js code:
```
var RNBroardcast = require('react-native').NativeModules.RNBroardcast;
  RNBroardcast.startBroardcast((error,events)=>{
        if (error) {
          console.log(error);
        } else {
          console.log(events);
        }
      });
```

now is the problem:
it worked on  'com.facebook.react.RNBroardcastQueue',how can let it work on main thread. 
because my native method must be work on main thread.

![image](https://cloud.githubusercontent.com/assets/4455464/15564750/d16e40be-2347-11e6-9b2d-06098bc09fbc.png)

**Comment by ide** [comment]
@facebook-github-bot stack-overflow

**Comment by gilnuy** [comment]
got you~
insert this code on my native method:
```
    dispatch_async(dispatch_get_main_queue()) {
    }
```

but i have many method, is there any other way to invoke on main thread instead of that.

**Comment by facebook-github-bot-1** [comment]
Hey @gilnuy and thanks for posting this! @ide tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by gilnuy** [comment]
[stackoverflow quesstion](http://stackoverflow.com/q/37453619/6384710)
