### ISSUE TITLE
Generate iOS project from my react-native project

### ISSUE THREAD

**Issue by luisfuertes** [facebook/react-native#7772]
I deleted my iOS project and now i want generate like Android (react-native android) but i dont found how can i do it.

Somebody knows how can i do it?

**Comment by ide** [comment]
Easiest way is to make a new project and copy your code over.

**Comment by luisfuertes** [comment]
I did that, but is a extrain solution..

**Comment by charpeni** [comment]
You can also achieve this with `react-native upgrade`.

**Comment by charpeni** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-8** [comment]
Closing this issue as @charpeni says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.
