### ISSUE TITLE
View rendering before the app goes in background

### ISSUE THREAD

**Issue by maxs15** [facebook/react-native#7782]
Hey guys,

I'm developing an IOS app using RN 0.25.1.
I currently have an issue with one of the feature, let me explain:

I would like to hide the app content when the app goes in the background.
So I'm detecting this using AppState and I'm updating my state accordingly.
The problem is the view is not updated before the app goes in background, only when it comes back, resulting in a small delay where you can see the app content.

Is there any way to be able to render a view before the app goes in background ? Maybe another event that I could use that is fired earlier ?

Thanks for the help

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-7** [comment]
Hey @maxs15 and thanks for posting this! @charpeni tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by maxs15** [comment]
This looks more like a bug/feature for me @charpeni
