### ISSUE TITLE
Why ScrollView.scrollRectToVisible implementation defaults to noop

### ISSUE THREAD

**Issue by Andreyco** [facebook/react-native#7789]
Wanting to find the cleanest solution to bring focused (or any other view) text input into viewport I search Apple Dev portal. Apple indeed advices to use `(void)scrollRectToVisible:(CGRect)rect animated:(BOOL)animated`, see this [reference](https://developer.apple.com/library/ios/documentation/StringsTextFonts/Conceptual/TextAndWebiPhoneOS/KeyboardManagement/KeyboardManagement.html).

Digging in codebase in order to find out any details on this, I discovered `RCTCustomScrollView` does implement such method - unfortunately [code does nothing](https://github.com/facebook/react-native/blob/a71a9efe9683f9d7cb1293a3f9e2fc10d788abc9/React/Views/RCTScrollView.m#L197-L200).
Also you state following:

> /**
>  \* Include a custom scroll view subclass because we want to limit certain
>  \* default UIKit behaviors such as textFields automatically scrolling
>  \* scroll views that contain them and support sticky headers.
>  */

What's the reasoning behind this decision?
cc @sahrens  (as `git blame` says you are the author)

Thanks for info

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/why-scrollviewscrollrecttovisible-implementation-defaults-to-noop

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
