### ISSUE TITLE
[android][AsyncStorage]crashed on HUAWEI MT7-CL00 , android 4.4.2

### ISSUE THREAD

**Issue by flare216** [facebook/react-native#7792]
log:
E/logserver( 2518): handle_notify_event, send msg [submit:trigger=0,bugtype=2,modulename=com.constructionquality,level=1,testtype=NORMAL,path=/data/log/unzip/MT7-CL00_V100R001C92B135_G2W0215904000624_20160527095114_crash;]
E/SubmitMessage( 3373): Submit string: submit:trigger=0,bugtype=2,modulename=com.constructionquality,level=1,testtype=NORMAL,path=/data/log/unzip/MT7-CL00_V100R001C92B135_G2W0215904000624_20160527095114_crash
W/ContextImpl(  949): Failed to ensure directory: /storage/sdcard1/Android/data/com.constructionquality/cache

i'm using react-native:0.26.1,
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/> ` has been added.

My app crashed when i click login, it maybe caused by AsyncStorage.setItem() in my login logic to remember user's account.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/androidasyncstoragecrashed-on-huawei-mt7-cl00-android-442

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
