### ISSUE TITLE
CSS System Fonts

### ISSUE THREAD

**Issue by kevinSuttle** [facebook/react-native#7796]
This is more for academic purposes than anything, but I recently discovered that CSS has font keywords based on operating system definitions. 

http://codepen.io/kevinSuttle/full/pbzxZZ/

I tried this in Electron, and it works, but not in RN.
Notice `fontFamily: -apple-system;`

![react-native-css-system-fonts-warning](https://cloud.githubusercontent.com/assets/95672/15598398/e66162ac-23a7-11e6-92e6-0181a24d1407.png)

===

Mac 10.11.5 / iOS 9.3 (SimulatorApp-645.9)
react-native-cli: 0.2.0
react-native: 0.26.2

**Comment by ide** [comment]
RN iOS defines a special font called "System" that refers to the default font: https://github.com/facebook/react-native/blob/235b16d93287061a09c4624e612b5dc4f960ce47/React/Base/RCTConvert.m#L612

**Comment by jacobp100** [comment]
It’s actually a keyword for `font`, not `font-family`. Setting it also adjusts things like the weight, font size, letter spacing etc. Not sure how this would work, since it would introduce style shorthands, not currently supported.

[Documentation](https://webkit.org/blog/3709/using-the-system-font-in-web-content/)
