### ISSUE TITLE
[TextInput] Dynamic change color style

### ISSUE THREAD

**Issue by ciklop** [facebook/react-native#7797]
When Textnput style *color* is defined in one place, and is being changed due state  with another style, on Android device entered text disapears.

https://rnplay.org/apps/pTwjLA
https://rnplay.org/apps/RqRcFg

RN 0.26.1
Android only bug
Tested on Windows with Genymotion and rnplay

**Comment by charpeni** [comment]
@facebook-github-bot label Android

**Comment by sreejithr** [comment]
Was able to reproduce. Fooled around in the codebase and these are my findings:

On entering the 6th keyboard input, there's a `ViewOperation`s of type `UpdateViewExtraData` dispatched. **It is a `ReactTextUpdate` which updates the value to text field to empty.** These are dispatched from `onBatchComplete()` in `UIManagerModule`. 

An empty `ReactTextUpdate` happens here because of this code:

*com/facebook/react/views/textinput/ReactTextInputShadowNode.java*
<pre>
@Override
  public void onCollectExtraUpdates(UIViewOperationQueue uiViewOperationQueue) {
    super.onCollectExtraUpdates(uiViewOperationQueue);
    if (mComputedPadding != null) {
      uiViewOperationQueue.enqueueUpdateExtraData(getReactTag(), mComputedPadding);
      mComputedPadding = null;
    }

    if (mJsEventCount != UNSET) {
      <b>Spannable preparedSpannableText = fromTextCSSNode(this);</b>
      ReactTextUpdate reactTextUpdate =
          new ReactTextUpdate(preparedSpannableText, mJsEventCount, mContainsImages);
      uiViewOperationQueue.enqueueUpdateExtraData(getReactTag(), reactTextUpdate);
    }
  }
</pre>

As I've emphasized in the snippet above, `preparedSpannableText` is `""`. For some reason, the `ReactTextInputShadowNode` hasn't received the text updates.

Can someone familiar with Shadow Nodes please tell me if this is expected behavior?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/textinput-dynamic-change-color-style

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
