### ISSUE TITLE
[Android] Multiple Activities Lifecycle Callback Issue when Sharing ReactInstanceManager

### ISSUE THREAD

**Issue by realaboo** [facebook/react-native#7807]
I've read #2916 and followed the section below in [doc](https://facebook.github.io/react-native/docs/embedded-app-android.html) to share a ReactInstanceManager across multiple activities:

> You can have multiple Activities or Fragments that use the same ReactInstanceManager. You'll want to make your own "ReactFragment" or "ReactActivity" and have a singleton "holder" that holds a ReactInstanceManager. When you need the ReactInstanceManager / hook up the ReactInstanceManager to the lifecycle of those Activities or Fragments, use the one provided by the singleton.

Say I have ActivityA and ActivityB start their ReactRootViews respectively with the same ReactInstanceManager. ActivityA includes a NativeViewA which is interested in ActivityA's lifecycle events so I have:

``` java
@Override
protected NativeViewA createViewInstance(ThemedReactContext themedReactContext) {
    NativeViewA viewA = new NativeViewA(themedReactContext);
    themedReactContext.addLifecycleEventListener(viewA);
    return viewA;
}
```

ActivityB also has a NativeViewB which want's to hook to ActivityB's lifecycle callbacks.

To make the event listeners work, the following code is added for both activities:

``` java
@Override
protected void onResume() {
    super.onResume();
    if (mReactInstanceManager != null) {
        mReactInstanceManager.onHostResume(this, this);
    }
}

// also onPause()
```

mReactInstanceManager is the shared ReactInstanceManager.

The issue is, listeners added by themedReactContext.addLifecycleEventListener() are organized together in the same ReactApplicationContext of ReactInstanceManager. So when ActivityB pauses or resumes, callbacks are called not only on NativeViewB but also on NativeViewA which is not expected.

Any suggestions on how to hook activity lifecycle event callbacks to views only included in this activity? Thanks!
@AaaChiuuu

**Comment by charpeni** [comment]
@facebook-github-bot label Android

**Comment by hey99xx** [comment]
A suggestion for you, `ThemedReactContext` actually has a reference to your base context. You can access it via `themedReactContext.getBaseContext()` which is going to be your activity containing your root view.

How do I know this? I read the source code because I had the exact same problem you have. However this also means this behavior is undocumented and could change in the future.

Anyways, here are relevant parts. When you create a `ReactRootView`, you pass in your activity
`mReactRootView = new ReactRootView(this);` where `this` refers to the activity.

When `ThemedReactContext` is created internally, it's base context is set to this root view's context on this line https://github.com/facebook/react-native/blob/82c8c97898c2ba7fbe7e371249354d353b1d4161/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIManagerModule.java#L183

Afterwards, all view creations refer to a copy of this context, you can see where the saved root view is taken from the view registry https://github.com/facebook/react-native/blob/d0d1712851d05595b13cf8cc558cec7894ec24f5/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIImplementation.java#L170

I might have skipped some classes, but if you follow this code path, practically from `UIManager` methods from JavaScript until `createViewInstance` methods, you will see that this solution works. I am personally using this in production.

`ThemedReactContext` extends from `ReactContext` which extends from Android's `ContextWrapper`. Luckily `ContextWrapper` kept a reference to its base context it received in its constructor.

Hopefully there is a more straight forward way in the future to get the correct activity in the future. This makes sharing react instance managers and having custom logic per activity insanely difficult.
