### ISSUE TITLE
Optimize RCTImageView resizes/reloads to avoid re-freshing/re-decoding when the source is a remote image

### ISSUE THREAD

**Issue by mikelambert** [facebook/react-native#7808]
So it appears that RCTImageView, when resized, has a comment that says:
```
        // If the existing image or an image being loaded are not the right
        // size, reload the asset in case there is a better size available.
```

I can see this making sense in the case of assets from disk, where we may need a higher or lower resolution. But in the case of remote assets pulled over the network, it (hopefully!) pulls the data from the cache and then calls decodeImageDataWithoutClipping() on it, which still feels like a waste of resources.

I assume it's worth an resize optimization to avoid reloading images when they are remote? I'm not clear on the best way to check this (or verify how helpful it'll be in the big pauses I'm seeing). I'm also not able to edit/debug any ReactNative code for some reason ([investigating here](http://stackoverflow.com/questions/37490032/debugging-react-native-source-code-in-my-project)), so not able to go in and debug the performance impacts of changing this at the moment.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/optimize-rctimageview-resizesreloads-to-avoid-re-freshingre-decoding-when-the-source-is-a-remote-image

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
