### ISSUE TITLE
[Android] Unable to get cookie from the https://myapp.com/websocket

### ISSUE THREAD

**Issue by Mokto** [facebook/react-native#7816]
#Hi,

Since 0.26 I cannot connect to my DDP Websocket server anymore. Cf [this](https://github.com/inProgress-team/react-native-meteor/issues/77).

* 0.26.1
* IOS is ok, android fails
* Using Mac

This is what I do with [ddp.js plugin](https://github.com/mondora/ddp.js/) :

```javascript
Data.ddp = new DDP({
      endpoint: endpoint,
      SocketConstructor: WebSocket,
      ...options
    });
```

My error is this `Unable to get cookie from the https://myapp.com/websocket`

Thanks !

**Comment by charpeni** [comment]
@facebook-github-bot label Android

**Comment by Mokto** [comment]
May be related to #7871.

**Comment by spencercarli** [comment]
Possible cause: https://github.com/facebook/react-native/pull/6851

**Comment by grsabreu** [comment]
Getting that here also using react-native-meteor

**Comment by Mokto** [comment]
As @spencercarli mentioned it [here](https://github.com/inProgress-team/react-native-meteor/issues/77), just use ws or wss protocol ;)

Not http or https

**Comment by grsabreu** [comment]
Yes, just saw. Awesome. Thanks @Mokto

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-unable-to-get-cookie-from-the-httpsmyappcomwebsocket

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
