### ISSUE TITLE
[Android] Linking.getInitialURL() appending extra characters to URL

### ISSUE THREAD

**Issue by sirnacnud** [facebook/react-native#7830]
I am trying to use `Linking.getInitialURL()` to get OAuth working and am running in to a problem with extra characters being appended to the URL returned on Android.  I am using version 0.26.1 of react-native.

React-Native Code:

    componentDidMount() {
      var url = Linking.getInitialURL().then((url) => {
        if (url) {
          console.log('Initial url is: ' + url);
        }
      }).catch(err => console.error('An error occurred', err));
    }

Console Output:

    Initial url is: myapp://callback?state=%3Cstate%3E&code=Mp0IgEMBdSdb2vlpPmhByfjYxV6puV#_

Logcat Output:

    ActivityManager: START u0 {act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=myapp://callback?state=<state>&code=Mp0IgEMBdSdb2vlpPmhByfjYxV6puV cmp=com.surge/.MainActivity (has extras)} from uid 10018 on display 0

You can see that `#_` is being appended and it not part of the URL supplied to the activity.

**Comment by charpeni** [comment]
@facebook-github-bot label Android

**Comment by lacker** [comment]
I don't think we have enough information here - it isn't clear from what you have provided whether the #_ could be coming from your own code. I think we need a small sample app and a rnplay.org link ideally if that's possible. I'm going to close this issue because it's also kind of old but if you do have this additional information then please feel free to reopen it.
