### ISSUE TITLE
directionalLockEnabled doesn't work if inner content size is bigger than the ListView's

### ISSUE THREAD

**Issue by gre** [facebook/react-native#7831]
**Example**

- one list view: `<ListView directionalLockEnabled pagingEnabled horizontal style={{ height:100 }}>` 
- with higher cells (aka rows): `<View style={{ height: 200 }}>`
- **bug:** I can still scroll vertically.

To my mind, the combination of props **`directionalLockEnabled`**` pagingEnabled horizontal` should have prevented this.

**My use case**
inner content that is higher that the carousel constraint should be allowed.
I want to make a carousel that expand/unexpand. To do that I simply use "overflow:hidden" with the carousel height to crop a carousel of images and where I want to expand it, I just perform an animation on the carousel height. I think it's the correct way to go for performance: I just have to re-render the ListView height and I don't have to re-render all cells heights everytime the main height changes.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/directionallockenabled-doesnt-work-if-inner-content-size-is-bigger-than-the-listviews

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
