### ISSUE TITLE
0.26.2 TextInput with Chinese chars in children will cause App infinite-loop and memory-blast

### ISSUE THREAD

**Issue by kiliwalk** [facebook/react-native#7851]
Test with react-native 0.26.2 IOS version, put a code like this below:
```js
<TextInput multiline><Text>中文</Text></TextInput>
```
The app will run into no response, cpu 100%, memory increasing 20M per second.

Some other comparisons:
1. No Chinese chars will not cause this problem!
2. Use `value` props with Chinese chars is ok, like `<TextInput multiline value='中文'/>`
3. RN 0.25 doesn't have this problem.
4. In RN 0.25, if not surrounding the chars with `Text` component, there will be a warning. But 0.26 not.

**Comment by kiliwalk** [comment]
Found which cause this problem:
In RN 0.26, `RCTTextManager.m`:
```oc
NSTextStorage *textStorage = [shadowText buildTextStorageForWidth:width widthMode:CSS_MEASURE_MODE_EXACTLY];
```

But in RN 0.25:
```oc
NSTextStorage *textStorage = [shadowText buildTextStorageForWidth:width widthMode:isnan(width) ? CSS_MEASURE_MODE_UNDEFINED : CSS_MEASURE_MODE_EXACTLY];
```

**Comment by sunnylqm** [comment]
ping @mkonicek @nicklockwood @rigdern

**Comment by mkonicek** [comment]
Thanks @kiliwalk for finding that line of code. Looks like @nicklockwood changed that line in https://github.com/facebook/react-native/commit/362738a776074b4d327d98650a1b85b5b534a0f1

Can you try sending a PR that reverts this line to the original and cc @javache who was the reviewer on the commit?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/0262-textinput-with-chinese-chars-in-children-will-cause-app-infinite-loop-and-memory-blast

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
