### ISSUE TITLE
unmount not be invoked when I pop via gesture

### ISSUE THREAD

**Issue by L-Jovi** [facebook/react-native#7865]
react native version `0.21`,

I find that `componentWillUnmount` not be invoked when I pop via gesture, what should I do?

thanks for your time.

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot stack-overflow

**Comment by huangbong** [comment]
I'm getting the same issue... componentWillUnmount not fired on Navigator pop(). RN 0.27.0

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/unmount-not-be-invoked-when-i-pop-via-gesture

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
