### ISSUE TITLE
how to animated multi transform attributes ？

### ISSUE THREAD

**Issue by 12343954** [facebook/react-native#7866]
http://stackoverflow.com/questions/37558292/how-to-make-this-animate-with-react-native

i want this static position

```
constructor(props) {
        super(props);
        this.state={
            loaded:false,
            transform:[{ perspective: 0 },
                      { translateX: width },
                      { rotateY: '0deg'}],
            isMenuOpen:false,
        }
    }
```
animate to this position

```
Animated.timing(
                this.state.transform,
                {toValue:[{ perspective: 850 },
                          { translateX: -width * 0.24 },
                          { rotateY: '60deg'}]},
            ).start();
```
how to write the animation code ？

**Comment by jeanregisser** [comment]
Stackoverflow is the right place to ask this question.
Could you please close this issue? Thanks.

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-7** [comment]
Hey @12343954 and thanks for posting this! @DanielMSchmidt tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
