### ISSUE TITLE
Websocket compatiblity v0.25 vs v0.26

### ISSUE THREAD

**Issue by Roconda** [facebook/react-native#7871]
Hi,

For a project I'm using websockets. I created a class which extends from the websocket polyfill like:

```js
class Socket extends WebSocket {
  constructor(param1 ) {
    super(uri)
  }

  onopen(event) { 
    this.send('foo')
  }

  onmessage(event) {
    // ...
  }
}
```

This used to work for react-native v0.25. After upgrading to v0.26 it doesn't seem to work anymore like this. It actually does connect but it doesn't seem to call the custom onopen, onmessage, onclose and onerror methods.

Any idea  how to use a websocket by extending the websocket polyfill class?

Thanks

**Comment by Mokto** [comment]
Are you seeing this on Android and/or iOS ?

I seem to have issues with Android on this matter.

**Comment by spencercarli** [comment]
It looks like this may be related to this PR https://github.com/facebook/react-native/commit/bf8b5499bba92e607be40c0ae0f12feffbfcc706

**Comment by Roconda** [comment]
@spencercarli You think so? I'm having this issue on iOS though(not tested Android due to incompatiblity in a dependency).. cc @Mokto

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/websocket-compatiblity-v025-vs-v026

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
