### ISSUE TITLE
pointerEvents prop doesn't work with WebView (Android)

### ISSUE THREAD

**Issue by Bema** [facebook/react-native#7897]
Tested on Android with RN versions 0.24, 0.25.1 and 0.26.3.

Trying to apply `pointerEvents={'none'}` to a WebView without success, WebView continues being target of touch events. 

```
<WebView
  pointerEvents={'none'}
  style={{
    height: 200,
  }}
  source={{uri: 'https://facebook.github.io/react/'}}
  scalesPageToFit={true}
/>
```
`pointerEvents` does work fine with View component, apparently issue is just with WebView.

**Comment by ms88privat** [comment]
👍 run into this yesterday

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/pointerevents-prop-doesnt-work-with-webview-android

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
