### ISSUE TITLE
Version upgrade encountered in the project to TextInput 0.26.3 can not enter chinese.

### ISSUE THREAD

**Issue by kmend** [facebook/react-native#7902]
Version upgrade encountered in the project to TextInput 0.26.3 can not enter chinese.

Test code:

`import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  TextInput,
  View
} from 'react-native';

class Test extends Component {
  state = { isRefreshing: false , text : ""};

    static defaultProps = {
        scale: 10
    };

    constructor(props) {
        super(props);
        this.state = {text: '', height: 0};
    }

    render() {

        return (

            <TextInput
                multiline={true}
                onChange={(event) => {
                  this.setState({
                    text: event.nativeEvent.text,
                    height: event.nativeEvent.contentSize.height,
                  });
                }}
                style={[Style.default, {height: Math.max(35, this.state.height)}]}
                value={this.state.text}
            />

        );
    }  
}

const Style = StyleSheet.create({
    default: {
        height: 26,
        borderWidth: 0.5,
        borderColor: '#0f0f0f',
        flex: 1,
        fontSize: 13,
        padding: 4,
    }
});

AppRegistry.registerComponent('Test', () => Test);`

**Comment by someok** [comment]
Replace the value to defaultValue
kmend <notifications@github.com>于2016年6月3日 周五09:23写道：

**Comment by kmend** [comment]
No relationship with setting defaultValue,
The same as the new initial project test,IOS input method in the Chinese language each letter in response to a Change event.

**Comment by kmend** [comment]
Replace the value to defaultValue    haha~    

thank you @someok

**Comment by charpeni** [comment]
Could be related to #7851.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/version-upgrade-encountered-in-the-project-to-textinput-0263-can-not-enter-chinese

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
