### ISSUE TITLE
RCTCameraRollManager.getPhotos will return no photo when native photos real count small than first in first params

### ISSUE THREAD

**Issue by nowaits** [facebook/react-native#7910]
in RCTCameraRollManager.getPhotos method, if i set the groupName in first param, in 
`[_bridge.assetsLibrary enumerateGroupsWithTypes:groupTypes usingBlock:^(ALAssetsGroup *group, BOOL *stopGroups) {`
on first loop if group name is not the groupName, it will return with 
`if (!resolvedPromise) {
         RCTResolvePromise(resolve, assets, hasNextPage);
        resolvedPromise = YES;
      }
` and return with wrong result, but actually in the following loops i will get the right group.
And if the real native photos count small than first in params, it will also can't return right result.

It's a bug, please fix it :)

**Comment by charpeni** [comment]
Are you up to send a pull request? :)

We're a small team and rely on the community to fix issues that don't affect fb apps.

**Comment by jfelker06** [comment]
I would like to take a crack at this, if possible.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/rctcamerarollmanagergetphotos-will-return-no-photo-when-native-photos-real-count-small-than-first-in-first-params

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
