### ISSUE TITLE
Portal removed from RN26. It's removal is not documented anywhere?

### ISSUE THREAD

**Issue by erickreutz** [facebook/react-native#7922]
It's seems as though `Portal` is not gone in 0.26 breaking `require('react-native/Libraries/Portal/Portal')`. Is the removal of this and the reasoning for it documented anywhere in the release notes?

https://github.com/facebook/react-native/commit/551c154261a29bd0a209bd00f7c086f80664c3ff

**Comment by javache** [comment]
`Portal` was not part of the public API. @dmmiller has been improving the `Modal` component and this should now be preferred over `Portal`.

**Comment by satya164** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-9** [comment]
Closing this issue as @satya164 says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.
