### ISSUE TITLE
undefined is not a function(evaluating react2.default,findNodehandle

### ISSUE THREAD

**Issue by AndrewJikun** [facebook/react-native#7923]
I just update reactnative to 0.26.3.After that i ran the project in both ios and android. ios works fine,but for andorid i get the error stated in the title . here is my code.

import {
  View,
  Text,
  TextInput,
  StyleSheet,
  TouchableOpacity,
  Image,
  ScrollView,
  ListView,
  InteractionManager,
  Dimensions,
  PixelRatio,
  Platform,
  Linking,
  findNodeHandle
} from 'react-native';

UIManager.measure(React.findNodeHandle(this['btn' + i]), (left, top, width, height, px, py)=> {
      if (__DEV__) {
        const data = [left, top, width, height, px, py];
        console.log('_handle1Press ....', data)
      }

      const screenSize = parseInt(this._scrollViewHeight / height); 
      const offset = height - this._scrollViewHeight % height; 
      const maxScrollCnt = (itemLength - screenSize);

**Comment by AndrewJikun** [comment]
and tried this, it didnot work neitehr.
import ReactNative, {
// your other imports
} from 'react-native';

...

ReactNative.findNodeHandle(component) it did not work

**Comment by charpeni** [comment]
```javascript
import {
  ...
  findNodeHandle,
  ...
} from 'react-native';

UIManager.measure(findNodeHandle(this['btn' + i]), (left, top, width, height, px, py)=> {
```

**Comment by charpeni** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-0** [comment]
Closing this issue as @charpeni says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.
