### ISSUE TITLE
fetch is not work on android

### ISSUE THREAD

**Issue by JarkimZhu** [facebook/react-native#7925]
below this code:

```
import React, {Component, PropTypes} from 'react';
import {View, Text, TouchableWithoutFeedback} from 'react-native';

export default class TestFetch extends Component {

    _onClick() {
        fetch("http://www.baidu.com")
            .then((response) => {
                return response.text();
            }).then(text => console.log(text))
    }

    render() {
        return <View>
            <TouchableWithoutFeedback onPress={this._onClick.bind(this)}>
                <View>
                    <Text>aaa</Text>
                </View>
            </TouchableWithoutFeedback>
        </View>
    }
}
```

it cann't log the response of the text.
did any one know this?

- [ ]React Native version  0.27.0-rc2
- [ ]It's only occured on Android
- [ ]I am using Mac.

**Comment by satya164** [comment]
Can you also add a catch block and see what the error is?

**Comment by damusnet** [comment]
You cannot use `fetch` to get `http://www.baidu.com` as it is not a proper API endpoint and lacks the `Access-Control-Allow-Origin` header.

![image](https://cloud.githubusercontent.com/assets/433409/15800257/967c55b6-2a74-11e6-9f40-2ff06ffa9e18.png)

You can do an opaque request like this, but it won't get you the content.

```js
fetch("http://www.baidu.com", {
  mode: 'no-cors'
})
```

Closing for now at it is not a react-native related issue, nor a bug.

@facebook-github-bot stack-overflow

**Comment by damusnet** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-7** [comment]
Hey @JarkimZhu and thanks for posting this! @damusnet tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by jonathanpalma** [comment]
Like @damusnet said you can't use `fetch` to get `http://www.baidu.com`.

That's due to `fetch` function is a way to make web requests and handle responses using an XMLHttpRequest. From this point you should know that this kind of requests are limited by the same origin policy.

For more information you could visit <a href="https://developer.chrome.com/extensions/xhr">Google developers | Cross-Origin XMLHttpRequest</a>

Attached screenshot of the response headers of the origin you're trying to get
![screenshot - 040616 - 10 44 26](https://cloud.githubusercontent.com/assets/12414771/15800825/d43b989a-2a41-11e6-841f-161f14d7307b.png)

Closing for now because it seems like is not react-native related issue

**Comment by jonathanpalma** [comment]
@facebook-github-bot answered
