### ISSUE TITLE
Bug with jpg <Image> pointing at XCAssets/drawable-resources

### ISSUE THREAD

**Issue by mikelambert** [facebook/react-native#7931]
https://facebook.github.io/react-native/docs/images.html says:

> you can still use images that are already bundled into the app (via Xcode asset catalogs or Android drawable folder):
> 
> `<Image source={{uri: 'app_icon'}} style={{width: 40, height: 40}} />`
> 

However, this is apparently only true of `png` images. If I have a jpg image, then I must do the following incantation to get it to work:
`<Image source={{uri: Platform.OS === 'ios' ? 'app_icon.jpg' : 'app_icon'}} ...`

Android needs an extension-less filename, as it uses `context.getResources().getIdentifier()`, which does not need/want the extensions.

It looks like iOS's `RCTIsXCAssetURL` will only return True on `png` or extension-less image names. So passing an extensionless image does work here, but then fails in `RCTXCAssetImageLoader.loadImageForURL`'s `[UIImage imageNamed:]` without the extension for some reason (I suspect, but haven't verified, that it needs to check extension-less, with an extension-ed fallback lookup).

However, if I pass the `jpg` extension , `RCTIsXCAssetURL` skips it, which then causes it to get (successfully!) loaded as a `file://` URL. But it makes for a really ugly difference between platforms, that took me a couple hours of sleuthing around to figure out the right incantation per platform, and that I was even doing wrong (since the documentation was inaccurate and mislead me into thinking I was doing the Right Thing).

**Comment by itinance** [comment]
I stumbled upon the same issue. RCTImageLoader is doing some crazy things regarding the extension. If there is no extension, it will automatically add ".png", otherwise the imageName won't be passed thru as is.
Thats why png-files will work out of the box, while JPEG needs the explicit extension when requeted with {{"uri: xxx.jpg" }}. 

However, if one use require("image!name"), it won't work neither with or without the explicit extension and will only handle png properly.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/bug-with-jpg-image-pointing-at-xcassetsdrawable-resources

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
