### ISSUE TITLE
Controlled TextInput with secureTextEntry={true} font size flicker.

### ISSUE THREAD

**Issue by sesm** [facebook/react-native#7936]
If a controlled TextInput (i.e. TextInput that has a 'value' prop) has secureTextEntry={true}, and there is any delay between input and updating 'value', font size for 'secure dots' start to flicker between provided fontSize and some default value.

![textinput_bug](https://cloud.githubusercontent.com/assets/1313744/15806034/2003a07e-2b4b-11e6-82aa-8ee39438be32.gif)

In this example, the delay is simulated with setTimeout: https://rnplay.org/apps/fMm0Ug
In my actual codebase the delay comes from using redux action and store to save the value.
React Native version: 0.26.
Occurs only on iOS.

**Comment by tomwalters** [comment]
I've been having this issue too, even just in setting the state of the current component and reading it back into the input.

**Comment by GuilhermeMedeiros** [comment]
Same here. It started happening after I updated react-native to `0.26.2`

**Comment by wtfil** [comment]
Hi! Having the same problem. Did you found any workaround for that?

**Comment by sesm** [comment]
@wtfil the workaround for me was to make TextInput uncontrolled, i.e. don't set the 'value' property, only set 'onChange'. 

However, in many cases this warkaround is not acceptable.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/controlled-textinput-with-securetextentrytrue-font-size-flicker

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by NeETsu** [comment]
Hello
is there already a acceptable solution for these issue. We have the same code in iOS and it does not cause the issue (only Android)
but we need to have the Value property cause we need to clear the fields after a button push
