### ISSUE TITLE
0.26 regression: touch events are lost when the component under the finger goes away

### ISSUE THREAD

**Issue by alangpierce** [facebook/react-native#7941]
I have an app I'm working on that involves dragging UI components around, and when I upgraded to React Native 0.26.3 and React 15.0.2, dragging stopped working. More specifically, any time you "pick up" a draggable component, it seems to immediately lose focus, and you have to release your finger and tap your finger down again to actually drag the component.

The interesting thing about my app is that the component directly under the finger is removed from the view hierarchy while dragging. (In its place, I draw a similar-looking component elsewhere in the view hierarchy that follows the finger.) But I'm handling all touch events through a top-level component that is mounted for the duration of the gesture, so I would expect to receive all touch events.

I think I tracked the problem down to this commit (although I'm not sure about the implications of just reverting it): https://github.com/facebook/react/commit/69b6869a3e6861b325ca2e9bb2d938cb81c7a090

Here's a small sample app demonstrating the problem on both Android and iOS:
https://github.com/alangpierce/DragBugDemo/blob/master/app.js

Here's the correct behavior on React Native 0.25.1 and React 0.14.5 (at least, I think it's correct):
<img src="https://cloud.githubusercontent.com/assets/211605/15810011/b07e6776-2b4e-11e6-9568-bff46c0fc88c.gif" width=300>

And here's the incorrect behavior on React Native 0.26.3 and React 15.0.2:
<img src="https://cloud.githubusercontent.com/assets/211605/15810022/c617b056-2b4e-11e6-8bd2-7613920a8b7d.gif" width=300>

I intentionally give the `dragging` and `notdragging` components different keys so that the `notdragging` component is removed from the view hierarchy while dragging. In the 0.26.3 version, all touch events after the first are lost for gestures that start with the finger over the `notdragging` component (even though that component doesn't handle any touch events itself).

**Comment by PyYoshi** [comment]
same issue :cry:

I downgraded RN version to 0.25.1 too.

**Comment by ide** [comment]
@sebmarkbage sounds like that commit introduced a regression and we want to continue to send touch events to JS even if the original target component was unmounted.

**Comment by sebmarkbage** [comment]
Ah yes. Known issue. It's not actually that commit. That commit just fixed an error firing when this happens. The original commit causing this regression is much more significant and is important memory usage and architectural wins. We can't revert that one.

We probably should've published this more visible in open source. Sorry about that. :( 

I believe that the semantics that we discussed is that we don't actually want to keep firing `touchmove` events in that case. That's also consistent with iOS. However, we do want to keep firing responder events which seems to be the issue here. If the current responder is removed from the tree, it should release to the nearest parent responder that accepts it. I forget what the proposed implementation details were.

@spicyj Do we have a GitHub issue tracking the bigger issue or just internally? We should at least document proposed solution or just fix it.

**Comment by sebmarkbage** [comment]
At the very least we should let the ResponderEventPlugin handle events in the bail out case somehow:

https://github.com/facebook/react/blob/master/src/renderers/native/ReactNativeEventEmitter.js#L127

We won't know what the target is though. So that will have to be `null`.

The second issue is doing something when the target of a touch gets removed to hand over the current responder before it is too late. We had a clever idea but I don't seem to find the notes right now.

**Comment by spicyj** [comment]
I don't think we have any GitHub issue tracking it. The notes I have internally are:

> Currently if you touch down on a node, then remove that node, the touch is lost and there's no way to receive touchmove events for it. Instead, the responder should transfer upwards (when there's a willing recipient ancestor) when the inner view is removed.
> 
> On web with mouse events, the mousemove event is always sent to the element under the cursor's current position so this isn't an issue.
> On web with touch events, the touchmove event gets sent to the detached node but does not bubble through the document (and currently, React DOM doesn't see the event at all). Andy M says this seems like a bad idea.
> On iOS, touch events disappear when a view is removed (even if your touchesBegan:/touchesMoved: handlers are on an outer view) – but when using a gesture recognizer on the outer view, the movements continue to be delivered.

I think this should be possible if we always store the parent path of the current responder.

**Comment by mquandalle** [comment]
I’m encountering a similar issue as @alangpierce. I have a view (a “card”) that is openable `onPress`, and draggable `onLongPress`. To drag the card component I create a clone of it that I render in an absolutely positioned view that follows the finger. This clone dragging is working as expected, the problem being that the user has to stop his original touch (the long press) and touch again to move the cloned card. My actual use case is described in more details in http://stackoverflow.com/questions/38198690/react-native-change-responder-dynamically.

So basically I’m looking for a way to transfer the responder from the original card to the newly created clone in the absolute positioned view. Since `onResponderMove` events aren’t called anymore on the clone, I have no point of entry to initiate the responder transfer.

The idea to transfer the responder when the original view is destroyed could fix the problem, but its assuming that we only want to transfer the responder when the original view is destroyed. In my case I could keep the original card in the view while still wanting to transfer responder to some other dragging view after a long press.

I’m not sure what additional API is needed to solve this use case, one possibility would be to have an imperative method `terminateResponder`, that I would in my example call after a long press. The new responder would then be delegated to a view accepting it with `onStartShouldSetResponder` basically creating a new touch event even if the user finger hasn’t move away from the screen. This `terminateResponder` method could also be called when the view is destroyed.

Another possibility would be to have an API to request responder responsibility outside of the existing `on{Start,Move}ShouldSetResponder` callbacks. In my example it would be used when the cloned card is rendered to indicates that it now wants to be the one handling touch events. Either way I think there need to be an imperative API to initiate the transfer on some event.

**Comment by alangpierce** [comment]
To be clear, in the example I linked, and in the app I'm working on, the responder (the node that returned `true` to `onStartShouldSetResponder`) is mounted for the duration of the gesture, but the touch events are still lost. The problem happens when the node under the finger at the start of the gesture (which doesn't interact with the responder system at all, at least not in application code) is removed. (I'm not sure if the term "responder" used in a few places above is the application-level responder or something implementation-specific that could be different.)

In my case, I don't need an API to transfer the responder to another node. I've already structured my code so there is a top-level responder controlling everything, and I just want it to keep getting events.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/026-regression-touch-events-are-lost-when-the-component-under-the-finger-goes-away

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by nikromiks** [comment]
I faced with this problem and tried on RN 0.43.0 and above.
And after overall trying - Good news, It works on RN 0.44.0
