### ISSUE TITLE
Fetch fails intermittently on first request with 'POST' method when using nginx 1.10.x

### ISSUE THREAD

**Issue by xiaoneng** [facebook/react-native#7943]
Fetch fails intermittently on first request with 'POST' method when using nginx 1.10.x with following server-side error:

client sent stream with data before settings were acknowledged while processing

Similar to:
 #7642

**Comment by xiaoneng** [comment]
Just a follow-up to hopefully keep others from banging head against wall on 'POST' requests.

Above seems to be due to http2 changes in nginx 1.10.x.
Nginx 1.10.x do not use http2 ( ssl only will work ) or you will have above problem.
Nginx 1.9.5 seems to work with http2 so seems to be change between versions.  I didn't try other 1.9 versions.

**Comment by ryankask** [comment]
It is indeed an nginx bug. You can track https://trac.nginx.org/nginx/ticket/959. I'm hoping there is a 1.10.2 release.

**Comment by ide** [comment]
We believe this might be fixed in RN 0.31-rc.0 which uses OkHttp 3.4.1.

**Comment by ryankask** [comment]
I'm actually seeing this in iOS.

**Comment by ide** [comment]
I believe the issue's been fixed in nginx 1.11.x -- just did some research on our own servers since we haven't been seeing HTTP/2 issues on iOS nor Android since we upgraded recently.

My reading of http://stackoverflow.com/questions/36907767/nsurlerrordomain-code-1004-for-few-seconds-after-app-start-up/37195635#37195635 is that iOS 9's NSURLSession library and nginx 1.10.1 don't get along.

I'm closing this since it doesn't look like it's related to React Native nor reasonable for RN to fix. Solutions at hand: use nginx 1.9.x, 1.11.x, or disable HTTP/2 until Apple patches iOS if they ever do.
