### ISSUE TITLE
[iOS][0.27]no such file or directory: RCTKeyboardObserver.m

### ISSUE THREAD

**Issue by someok** [facebook/react-native#7949]
clang: error: no such file or directory: '/Users/wjx/MyFolder/Develop/AnyTechMobile/node_modules/react-native/React/Base/RCTKeyboardObserver.m'
clang: error: no input files

**Comment by someok** [comment]
It's pod config problem

**Comment by someok** [comment]
It pod problem

**Comment by DanielMSchmidt** [comment]
Could you provide more information? 
- Steps to reproduce
- React Native version

**Comment by someok** [comment]
@DanielMSchmidt 

I use COCOAPODS manage some iOS components:
```
target 'ios' do
    pod 'React', :path => '../node_modules/react-native'
    pod 'react-native-image-crop-picker', :path => '../node_modules/react-native-image-crop-picker'
end
```

It's work fine at v0.26.2, but cannot compile libReact.a success at 0.27.0

**Comment by charpeni** [comment]
@facebook-github-bot label iOS

**Comment by stantoncbradley** [comment]
I just experienced this issue.  Cleaning my build, deleting *all* derived data, and clearing & reinstalling pods seems to reconcile it.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/ios027no-such-file-or-directory-rctkeyboardobserverm

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
