### ISSUE TITLE
ThemedReactContext is unable to .startActivityForResult()

### ISSUE THREAD

**Issue by wilsonpage** [facebook/react-native#7950]
- The `ThemedReactContext` instance is passed to all `ViewManagers`. It is an entirely different `ReactContext` instance to the `ReactApplicationContext`.
- The `ReactApplicationContext` always receives the [`onHostResumed()` callback](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/bridge/ReactContext.java#L159) which references `mCurrentActivity`.
- The `ThemedReactContext` instance never receives this callback and thus `mCurrentActivity` remains `null`.
- When `mCurrentActivity` is `null`, `themedReactContext.startActivityForResult()` throws an exception, crashing the app.
- Calls made to `themedReactContext.startActivityForResult()` should either be forwarded to `ReactApplicationContext` or `mCurrentActivity` should be defined when `ThemedReactContext` is created. Former solution sounds more sane to me.

---
- [x] Provide a **minimal code snippet** / [rnplay](https://rnplay.org/) example that reproduces the bug.

https://github.com/wilsonpage/react-native-themed-react-context-issue
- [x] What's the **version** of React Native you're using?

v0.27.0
- [x] Does this occur on iOS, Android or both?

Android
- [x] Are you using Mac, Linux or Windows?

Mac

**Comment by ncnlinh** [comment]
Do you have any workaround at the moment?

**Comment by wilsonpage** [comment]
I passed a reference to `ReactApplicationContext` into the View Manager and used that instead.

**Comment by ncnlinh** [comment]
@wilsonpage thank you very much, I figured it out after a while and did the same thing!

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/themedreactcontext-is-unable-to-startactivityforresult

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
