### ISSUE TITLE
ART is slow when a new piece is appended to a drawing that has a lot of pieces

### ISSUE THREAD

**Issue by rigdern** [facebook/react-native#7963]
ART redraws the entire drawing each time the drawing changes. This makes ART slow when a drawing has a lot of pieces.

Consequently, ART is unsuitable for use in a drawing app. Drawings will typically have a lot of pieces and they'll need to be updated very quickly as the user adds more to the drawing. Note that in a drawing app, the user will typically be appending pieces to a drawing. ART could be enhanced to handle this scenario efficiently by only drawing the newly appended pieces rather than redrawing all of the existing pieces.

### Proposal

ART should expose an API which enables it to efficiently update a drawing when the only change was that a piece was appended to it (common scenario in a drawing app).

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/art-is-slow-when-a-new-piece-is-appended-to-a-drawing-that-has-a-lot-of-pieces

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
