### ISSUE TITLE
Issue in connecting with Development Server

### ISSUE THREAD

**Issue by susylPearl** [facebook/react-native#7967]
In my previous react-native version 0.24 everything is fine, i can build and run application on device. But when i upgrade react-native to version 0.27, i cannot build and run application on device when downloading js bundle it always shows error as in screenshot below: why i got this error? please suggest me .

![screenshot_20160607-115329](https://cloud.githubusercontent.com/assets/17492075/15847640/5ce017cc-2ca7-11e6-9777-11aa75a87c90.png)

**Comment by adrienthiery** [comment]
Did you check the updated docs : https://facebook.github.io/react-native/docs/running-on-device-android.html ?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/issue-in-connecting-with-development-server

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
