### ISSUE TITLE
Android assembleRelease not working

### ISSUE THREAD

**Issue by yedidyak** [facebook/react-native#7970]
I have a react-native project that includes a number of external custom modules. Everything runs fine in both iOS and Android, when running from the react-native package server. It also works when released on iOS. However, when I build an apk with assembleRelease one of the imports fails with the error

`Requiring unknown module "xxx"`

Again, this is ONLY when running a released apk. Other external modules I use do import correctly.

The specific module that fails has native iOS code but no native android code. I've tried setting it up as a natve Android module matching the iOS native side, with a build.gradle specifying it as a library module. That also works when running from the packager but still fails when running as a bundled apk.

From the index.android.bundle files from the node packager and from inside the apk I can see that the module is not packaged at all in the apk.

What could be causing the difference?

(React-Native version 0.25.1)

**Comment by adrienthiery** [comment]
Did you use rnpm to link the package or did you do it by hand ?

I'm not sure of what you mean with `The specific module that fails has native iOS code but no native android code. I've tried setting it up as a native Android module matching the iOS native side, with a build.gradle specifying it as a library module.` 

If it has no Android code, why are you trying to include it as a native Android module?

Can you give more details on this module?
Maybe you should open an issue there instead of here?

**Comment by yedidyak** [comment]
I worked it out in the end. The external module had it's `main` set to `index.ios.js` in `package.json`.

For some reason, the node package server was allowing this to run, and used the code in `index.android.js` anyway. The bundle for release omitted both though, which caused the unknown module error.

Is this the expected behaviour or is this a bug in either the node server or bundler?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-assemblerelease-not-working

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
