### ISSUE TITLE
iOS: resizeMode='contain' for Image will not allow changing the source

### ISSUE THREAD

**Issue by jwyld** [facebook/react-native#7990]
Attempting to dynamically change the source of an image with state changes will not update the actual image:

<Image style={{marginLeft: 30, marginRight: 12, width: 80}} resizeMode='contain' source={source} >

This is likely an iOS only issue.  I don't see changes since v0.25.1 to fix this.

The problem is in -[RCTImageView reactSetFrame:].  If the sizes aren't changing, the method will call [self cancelImageLoad] which cancels the new load.

The easy fix is to not cancel.  That would not be good for the cases when the load is actually the same.  The problem is that RCTImageView doesn't know what's it's currently displaying versus what it's loading.  It only uses a single source property (RCTImageSource), but it really needs the two to compare to fix this properly.  Another option would be to use a boolean to track whether it's currently displaying what it was told to load.  If it's not displaying the load, it would not cancel.  If it is displaying the load already, it would cancel.

**Comment by charpeni** [comment]
@facebook-github-bot label iOS

**Comment by charpeni** [comment]
Thank you for your pull request, I was facing the exact same issue.

**Comment by npomfret** [comment]
I've noticed a similar issue in iOS. I have a list view containing images that get re-ordered frequently.  Often I see duplicated images in the list, and sometimes blank images (that have previously displayed).  I'm using `resizeMode='cover'` though so I'm not sure if this is the same issue.  I'm trying to reproduce the problem in a stand alone repo but so far I've failed.  I can't see what my app is doing differently.

I'm using rn 0.28, but have had the problem for several versions.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/ios-resizemodecontain-for-image-will-not-allow-changing-the-source

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
