### ISSUE TITLE
android,  part of layout be blank until tap the screen.

### ISSUE THREAD

**Issue by RaphaelYu** [facebook/react-native#7992]
I am using react native to write a communicator of Webrtc. After the stream is established, the video stream from remote doesn't play well in the native UIComponent. We need tap screen then it works.

The process of the communicator is as below.
1. prepare a view groupfor the video stream.
2. do establish video stream.
3. put  the video stream into the view.

I expected the stream will be play on the corresponding place but it didn't. 

Is there any solution for this case?

**Comment by RaphaelYu** [comment]
After inspect log. It is a surface was not created until tap the window.

**Comment by RaphaelYu** [comment]
two causes, 1 the stream be established after render, it would not be done again.
2. View not opacity.

**Comment by charpeni** [comment]
@facebook-github-bot label Android

**Comment by pthrasher** [comment]
I am curious about this as well. I am building a native ui component, and layout isn't triggered until a scroll event. So I'm wondering if there's some layout invalidation that needs to happen first. Additionally, I'm curious if this is due to some undocumented caveat in the way react-native renders native modules. I have a similar issue on iOS.

**Comment by RaphaelYu** [comment]
My case is a communication application by webrtc. webrtc will establish video stream and render a pre-defined native UIComponent(view group). 
We design the Interface with a "TouchableWithoutFeedback". the menu will be popped after the view is touched. It is very unstable both android and IOS.
 We remove the  "TouchableWithoutFeedback" component and use simple layout. Switch the view in layout by "weight" and "height" it is stable now.
I guess the view render collide with my UIComponent.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-part-of-layout-be-blank-until-tap-the-screen

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
