### ISSUE TITLE
Android react native the CatalystInstance is destroyed by unknown reason

### ISSUE THREAD

**Issue by RaphaelYu** [facebook/react-native#7993]
I am writing a communicator. I found the event lost sometimes while the interface is running well. It happens on both debug version and release version.

 "Calling JS function after bridge has been destroyed."  is in log. 
ReactAndroid/src/main/java/com/facebook/react/bridge/CatalystInstanceImpl.java

synchronized (mJavaToJSCallsTeardownLock) {
      if (mDestroyed) {
        FLog.w(ReactConstants.TAG, "Calling JS function after bridge has been destroyed.");
        return;
      }

      incrementPendingJSCalls();

      Assertions.assertNotNull(mBridge).callFunction(executorToken,
        module,
        method, arguments, tracingName);
    }
  }

**Comment by charpeni** [comment]
@facebook-github-bot label Android

**Comment by RaphaelYu** [comment]
The issu is move on. After set listener, the destroy part is found. That is in these part code in com.facebook.ReactInstanceManagerImpl. java
private void moveToBeforeCreateLifecycleState() {
    if (mCurrentReactContext != null) {
      if (mLifecycleState == LifecycleState.RESUMED) {
        mCurrentReactContext.onHostPause();
        mLifecycleState = LifecycleState.BEFORE_RESUME;
      }
      if (mLifecycleState == LifecycleState.BEFORE_RESUME) {
        mCurrentReactContext.onHostDestroy();  //<==== the instance is destroy at this line.
      }
    }
    mLifecycleState = LifecycleState.BEFORE_CREATE;
  }

 and this function is called by 
@Override
  public void onHostPause() {
    UiThreadUtil.assertOnUiThread();

    mDefaultBackButtonImpl = null;
    if (mUseDeveloperSupport) {
      mDevSupportManager.setDevSupportEnabled(false);
    }

    moveToBeforeResumeLifecycleState();// <==== this line is  trigger

    mCurrentActivity = null;
  }

Now question is why it consider there is a 'Pause', even it is a telephony app and the call is dialing.

**Comment by RaphaelYu** [comment]
The listener detected the resume missed sometimes while application restart. Why the program is running but not resume?

**Comment by RaphaelYu** [comment]
The application real happened pause and the resume lost.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-react-native-the-catalystinstance-is-destroyed-by-unknown-reason

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
