### ISSUE TITLE
Improve separator rendering, add renderSectionFooter

### ISSUE THREAD

**Issue by patrys** [facebook/react-native#7994]
Hey,

I'm trying to make my app feel more native in IOS 9. Native tables (listviews) have each section start and end with a full width line and lines between elements are indented to the same column as text of the items.

It's very hard to replicate with the current API. There is no way to add a footer to each section or to wrap each section in a container I could add borders to. Getting rid of the separator under the last item is super awkward:

```
renderSeparator = (sectionID, rowID) => {
  const { dataSource } = this.props
  const section = dataSource._dataBlob[sectionID]
  const isLast = rowID === `${section.length - 1}`
  if (isLast) {
    return null
  }
  return <ListSeparator key={`${sectionID}-${rowID}`}/>
};
```

It would be much easier if the separators were rendered only between list items and each section had a separate section footer.

**Comment by Bhullnatik** [comment]
👍 

It doesn't make much sense to render the separator on the last item imho, since that is applying the same style to every one of your rows, which can easily be done with some style.

**Comment by MichaelHancock** [comment]
@patrys I would suggest that rather than accessing ```dataSource._dataBlob[sectionID]``` like this. You solve the problem using dataSource's public methods rather than accessing the data directly:

```
const sectionLength = this.state.dataSource.getSectionLengths()[sectionID];
const isLast = (rowID + 1 === sectionLength);
```

Does the same thing as your's but it is a bit cleaner since we aren't accessing the data directly. But I agree, lets have a renderSectionFooter!

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/improve-separator-rendering-add-rendersectionfooter

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
