### ISSUE TITLE
default renderLoading for WebView

### ISSUE THREAD

**Issue by nihgwu** [facebook/react-native#7997]
since the `ActivityIndicatorIOS` has been depreciated in RN0.28, so the default indicator for renderLoading of WebView should be updated too, now it shows the YellowBox

**Comment by charpeni** [comment]
Good catch, thank you.

I'll be able to fix this in the next few days if someone else doesn't do that.

**Comment by nihgwu** [comment]
@charpeni that's great, i planed to create a pr but i thought that's a minor change and i haven't use the new indicator yet.

**Comment by janicduplessis** [comment]
I have a WIP PR to replace all ActivityIndicatorIOS with ActivityIndicator, I just need to test it a bit more and I'll land it.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/default-renderloading-for-webview

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
