### ISSUE TITLE
How to get an unique id of every component?

### ISSUE THREAD

**Issue by dragonwong** [facebook/react-native#7999]
Is there any way to get an unique id of every element? By the id i can locate the element.

I find that every element has an attribution called `ele._owner._rootNodeID`，the value looks like `.r[1]{TOP_LEVEL}[0].0.0.0.0.$scene_0.0.0.0.2.0.0`, but this is the id of the element's owner not the element itself. :disappointed:

**Comment by cablegunmaster** [comment]
Simple question: What are you trying to achieve?

**Comment by dragonwong** [comment]
@cablegunmaster 

I want to count how many times do users click each button on the view. My plan is when a button is pressed, I send its unique id to the server. Then, I can see the statistics of different buttons. I can even draw a thermodynamic chart above the view because I can located these buttons easily by the unique ids.

**Comment by cablegunmaster** [comment]
best bet is to give all the buttons a own unique ID like a prop , and on every onclick give the button position to the server. This is more react-native related as it is with the charts this github is about.

Best bet is to give it a manual label every time and return it with a onclick event.

@more a react-native question as a chart question

**Comment by satya164** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-3** [comment]
Closing this issue as @satya164 says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

**Comment by dragonwong** [comment]
@cablegunmaster thanks!
