### ISSUE TITLE
[Debugging] "Unknown" components in react dev tools

### ISSUE THREAD

**Issue by johanneslumpe** [facebook/react-native#800]
As seen here:

![Unknown components]
(https://s3.amazonaws.com/f.cl.ly/items/2h3y3V0d1d1U0E3q1t1M/Image%202015-04-10%20at%2010.25.32%20pm.png)

I didn't yet dive into the codebase but maybe I can figure something out.

**Comment by colinramsay** [comment]
This question was asked on SO too: 

http://stackoverflow.com/questions/29426537/what-is-unknown-in-react-native/29439395#29439395

I speculated (and I'm not 100% certain) that it might be due to text nodes in your code, specifically white space like tabs and newlines. Please see this issue from the react dev tools:

https://github.com/facebook/react-devtools/issues/44

There are several such issues on the devtools tracker, sometimes related to a lack of displayName on components but I don't see how that applies here.

In my SO answer I said that it might be worth opening an issue on this as I don't think it's desirable behaviour. The person from SO never did (or at least I can't find it) so if this is a bug then it might get picked up here.

**Comment by kyle-ssg** [comment]
Have you tried adding something like displayName: 'MyComponent' inside your component,

**Comment by brentvatne** [comment]
@johanneslumpe - is this fixed if you add `displayName: 'someName'` do your components?

**Comment by johanneslumpe** [comment]
@brentvatne No that didn't help at all. Actually in my screenshot above my own components are already named correctly. I just tried it in another project - the "Unknown" components are not the components I created. Those must be something else.

**Comment by brentvatne** [comment]
Strange, thanks for checking it out @johanneslumpe - let's move this issue over to the devtools repo
