### ISSUE TITLE
Missing docs for SwipeableListView

### ISSUE THREAD

**Issue by npomfret** [facebook/react-native#8005]
Could someone provide docs and/or and example of how to use SwipeableListView?

**Comment by charpeni** [comment]
This component is pretty new, documentation will landed soon. 

Until then, you can check that : https://github.com/facebook/react-native/commit/381a0051c7ec5bde4c35967e336050c8dca6a677

cc @fred2028

**Comment by charpeni** [comment]
@facebook-github-bot label Documentation

**Comment by charpeni** [comment]
@facebook-github-bot label Documentation

**Comment by charpeni** [comment]
@facebook-github-bot label Documentation

**Comment by charpeni** [comment]
@facebook-github-bot label Documentation

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/missing-docs-for-swipeablelistview

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
