### ISSUE TITLE
[Android] Elevation + TouchableOpacity visual bug

### ISSUE THREAD

**Issue by cmcewen** [facebook/react-native#8013]
Wrapping a view with elevation in a TouchableOpacity doesn't render properly

```
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  TouchableOpacity,
  View
} from 'react-native';

class elevation extends Component {
  render() {
    return (
      <View style={styles.container}>
        <TouchableOpacity>
          <View style={styles.button} elevation={10} />
        </TouchableOpacity>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
  },
  button: {
    height: 200,
    width: 200,
    borderRadius: 100,
    backgroundColor: 'green',
  }
});

AppRegistry.registerComponent('elevation', () => elevation);
```

<img width="641" alt="screen shot 2016-06-08 at 2 44 33 pm" src="https://cloud.githubusercontent.com/assets/1307633/15912270/1c16adbe-2d88-11e6-870e-c5e57eab67c1.png">
<img width="641" alt="screen shot 2016-06-08 at 2 44 39 pm" src="https://cloud.githubusercontent.com/assets/1307633/15912272/1e47f1f6-2d88-11e6-86dc-d0868bfde27e.png">

**Comment by charpeni** [comment]
@facebook-github-bot label Android

**Comment by phones24** [comment]
Having the same issue. TouchableOpacity (some other components too) have clipped the elevation. Try adding the elevation to outer container. 

This is especially annoying with elevated elements inside scrollview.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-elevation-touchableopacity-visual-bug

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
