### ISSUE TITLE
TextInput style issue when no placeholder is set

### ISSUE THREAD

**Issue by nihgwu** [facebook/react-native#8020]
I'm using RN0.27.0, and there is a visual issue if we don't set the placeholder prop of TextInput, here is the demo:
placeholder is not set and unfocused
![image](https://cloud.githubusercontent.com/assets/2595058/15918459/896da51e-2e39-11e6-999d-57e2d21e9e81.png)
placeholder is not set and focused
![image](https://cloud.githubusercontent.com/assets/2595058/15918467/936cecb4-2e39-11e6-8d1d-0f8ac69c04ee.png)
placeholder is set
![image](https://cloud.githubusercontent.com/assets/2595058/15918484/b55cd99c-2e39-11e6-90bc-3840b8fd44ff.png)

**Comment by charpeni** [comment]
I'm not sure what is the style issue, the bottom input border seems weird?

**Comment by nihgwu** [comment]
@charpeni yes, i'm describing the visual issue, seems there is an overlay on the bottom

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/textinput-style-issue-when-no-placeholder-is-set

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
