### ISSUE TITLE
[Android][0.26] Dynamic Picker Label Causes Picker to Change Selected Value

### ISSUE THREAD

**Issue by praveenperera** [facebook/react-native#8021]
I am trying to dynamically change the picker's label on android depending on what is currently selected. Example if French is selected show Anglais and Français if English is selected show English and French. When I try to do this the text changes briefly to the correct one but then switches back immediately. Code and gif provided below.

Is this a known issue? 

**Note: this works on iOS on 0.26 and works on both iOS and Android on 0.22.** 

For anyone else having this issue, a decent temporary work around is to manually require the PickerAndroid from 0.22.

``` jsx
<Picker
  selectedValue={ this.state.locale }
  onValueChange={(value) => this.setState({locale: value})}
  itemStyle={styles.picker}
  mode="dropdown">

  <Picker.Item label={this.state.locale === 'en' ? "English" : "Anglais"} value="en" />
  <Picker.Item label={this.state.locale === 'en' ? "French" : "Français"} value="fr" />
</Picker>

```

GIF:
![gif of problem](http://imgur.com/Hbgejoc.gif)

**Comment by charpeni** [comment]
@facebook-github-bot label Android

**Comment by xvalentino** [comment]
I'm also running into this. react ^15.1.0 react-native .28.0

Any work arounds?

**Comment by praveenperera** [comment]
@xvalentino Here is the edited version thats working for us: https://gist.github.com/praveenperera/62deb55d22003b5db3ffd30a8cd13a15

And calling it like this:
`+const Picker = (Platform.OS !== 'ios') ? require('../common/pickerAndroid') : require('react-native').Picker;`

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android026-dynamic-picker-label-causes-picker-to-change-selected-value

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
