### ISSUE TITLE
Linking libraries on Android

### ISSUE THREAD

**Issue by cablegunmaster** [facebook/react-native#8023]
Question how to "link a library"  in android?  What are the steps involved?  
I know about rnpm and this does the 'magic' for you. 
But how to do this manual , to check if its working? 
I like to have a explainatory page like IOS has, 
so it can be explained how to fix library links.

Example: https://facebook.github.io/react-native/docs/linking-libraries-ios.html

Label: Documentation request.

**Comment by Kureev** [comment]
Hi @cablegunmaster!

Yeah, indeed, this page is missing. Usually, on Android you don't have a "standard" path - every library may require some specific installation steps, so it's hard to write a one-fits-all doc about it. If you have a vision how it can be done, we would be glad to review your PR.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/linking-libraries-on-android

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
