### ISSUE TITLE
FormData cannot append null value

### ISSUE THREAD

**Issue by Frezc** [facebook/react-native#8035]
![formdata_value_null](https://cloud.githubusercontent.com/assets/6942296/15943215/8a4e78ce-2eba-11e6-9ee4-ad49af9ce796.png)

At line 30239, 'value.name' will throw this TypeError.
And I think null value should be serialized as "null". Is this a bug ? 

react native - version 0.27.0-rc2

**Comment by sodik82** [comment]
same issue here. the problem is with https://github.com/facebook/react-native/blob/master/Libraries/Network/FormData.js#L74
```
if (typeof value === 'object') {
```
condition is true for `null` values.

The question is what is best solution. As per specification `append` officially accept only string and blob arguments. Current implementation handles also other values like numbers or `undefined` by converting them to string (even though it converts `undefined` to string `'undefined'` which is imho contra-intuitive).

Maybe the best option would be to handle `null` to provide consistent handling with `undefined` and simply extend condition to `(typeof value === 'object' && value !== null)`

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/formdata-cannot-append-null-value

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
