### ISSUE TITLE
Deploy to appstore/google play

### ISSUE THREAD

**Issue by nschurmann** [facebook/react-native#8050]
Hey guys!, already finished the app, so i was looking on how to enable the performance boost and disable the developer mode that is active according to documentation but i cannot find it anywhere.

¿Is there some docs for that? ¿for android and iOS?

**Comment by charpeni** [comment]
Hi @nschurmann,

Congratulations !

The documentation can be found here : [Android](https://facebook.github.io/react-native/docs/signed-apk-android.html) & [iOS](https://facebook.github.io/react-native/docs/running-on-device-ios.html).

Happy deployment :)

**Comment by charpeni** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-5** [comment]
Closing this issue as @charpeni says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.
