### ISSUE TITLE
React Native Apps don't allow to be refreshed if run from xcode, also custom fonts are not added if using the command line

### ISSUE THREAD

**Issue by AdamKyle** [facebook/react-native#8051]
So two big issues I came across.

1. If you open the application in xcode after doing:

    ```
    react-native init AwesomeProject
    cd AwesomeProject
   ```

  Then click run, everything launches fine, but when I make a change in my editor, save it and hit `command+R`, nothing changes. Only by using `react-native run-ios` do I get to use the `command+r` feature to see my changes. Which leads me to issue number two:

2. When using [React Native Vector Fonts](https://github.com/oblador/react-native-vector-icons) They stipulate to make sure the fonts are in the copy bundle resources of the build phase and to rebuild the project. So I Made sure they are where they are suppose to be:

  ![Image](http://i.imgur.com/K4wBhXc.png)

  ![imageTwo](http://i.imgur.com/Nr8smZM.png)

  Then it states to rebuild the project, so I did `Command+B` It states the build succeeded, so I then run `react-native run-ios` and see:

  ![Image Three](http://i.imgur.com/NT3M5xl.png)

 How ever if I go into xcode and click run:

  ![Image four](http://i.imgur.com/53nvkGE.png)

 You can now see that the icon physically renders on the app, how ever, as stated before If I change the text of "Create your tweet below." to something else in my editor, hit save, and go to the simulator and hit `command+r`, the running app doesn't refresh, it only refreshes with your command `react-native run-ios` Which I do not think is building the app properly, because its not including my custom fonts.

More Info:

**Package JSON**:

```
{
  "name": "twitterQue",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "lodash": "^4.13.1",
    "react": "^15.1.0",
    "react-native": "0.27.2",
    "react-native-vector-icons": "^2.0.3"
  }
}
```

**Comment by charpeni** [comment]
@facebook-github-bot label iOS

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/react-native-apps-dont-allow-to-be-refreshed-if-run-from-xcode-also-custom-fonts-are-not-added-if-using-the-command-line

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
