### ISSUE TITLE
Bundler Performance Help

### ISSUE THREAD

**Issue by staufman** [facebook/react-native#8054]
Hi all,

First, apologies for the slew of questions. You guys have been doing awesome work over there so seriously, pat yourself on the back!

I am running the react-native CLI tools (React v15.1) on an AWS Micro instance (Ubuntu) for a side project. Essentially, I want to be able to run the CLI bundler on this Linux box and have it bundle my react-native app. However, I am noticing some disturbing artifacts running on a Micro.

For one, the bundler maxes out the CPU. Now I understand that a Micro box is not a dedicated instance so I should only expect some bursting but why is the bundler killing the CPU? Is bundling really that CPU bound? Bundling a very basic react-native app for the first time can take on the order of 5 mins. Now subsequent bundles are instantaneous but I'm wondering if there is a way to speed up the initial bundle?

I'm also noticing that memory consumption is quite high for the bundler. A basic AWS instance will not typically have swap space and with only 1GB of physical RAM, the bundler would just outright fail. By adding some swap space, the bundler will run but is this really how much RAM the bundler will require?

It also looks like live updates to an index.js file will get picked up by the bundler but any new files added to the bundler's tree while it is running will not get picked up. Is this correct?

Are there any alternatives? I hear Webpack is a thing (I'm coming from app development so a lot of these Web technologies are new to me). Is Webpack something I should be looking for? Are there other alternatives? Roll my own bundler in C? 💃 

Thanks for any help you can provide.

**Comment by charpeni** [comment]
@facebook-github-bot label Tooling

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/bundler-performance-help

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
