### ISSUE TITLE
Empty string passed as `after` param in CameraRoll.getPhotos returns zero results

### ISSUE THREAD

**Issue by niftylettuce** [facebook/react-native#8059]
If you pass `after` as a param, e.g. `const params = { after: '', ... }` with `CameraRoll.getPhotos` per the documentation here <https://facebook.github.io/react-native/docs/cameraroll.html>, you will get a result of zero photos, EVEN when there are actual photos stored.  However, if you remove this param, it works OK.  I would suggest to check if this string is null or blank, then to have it not take it into account with the core module itself.  That way it's a bit more dummy-proof.

**Comment by niftylettuce** [comment]
In your example you include this code <https://github.com/facebook/react-native/blob/0.27-stable/Examples/UIExplorer/CameraRollView.js#L148-L150>, but this is not apparent in the docs.

**Comment by niftylettuce** [comment]
Screenshots for support...

> With `after: ''`:

<img width="423" alt="screen shot 2016-06-11 at 1 47 59 am" src="https://cloud.githubusercontent.com/assets/523141/15983508/c3b7e484-2f77-11e6-8066-4a4bfdb12d4d.png">

> Without `after: ''` (e.g. simply don't include this prop)

<img width="423" alt="screen shot 2016-06-11 at 1 56 12 am" src="https://cloud.githubusercontent.com/assets/523141/15983510/cc0b752e-2f77-11e6-9bd9-833eaec85fc5.png">

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/empty-string-passed-as-after-param-in-camerarollgetphotos-returns-zero-results

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
