### ISSUE TITLE
[iOS][0.27.2] Unable to resolve module emptyFunction from SwipeableRow

### ISSUE THREAD

**Issue by someok** [facebook/react-native#8060]
I'm use import like this:

> import SwipeableListView from 'react-native/Libraries/Experimental/SwipeableRow/SwipeableListView';

or

> import SwipeableListView from 'SwipeableListView';

Throw error:
> Unable to resolve module emptyFunction from /Users/xxx/node_modules/react-native/Libraries/Experimental/SwipeableRow/SwipeableRow.js: Unable to find this module in its module map or any of the node_modules directories under /Users/node_modules/emptyFunction and its parent directories

**Comment by dozoisch** [comment]
See http://stackoverflow.com/questions/37489145/react-native-how-to-import-use-rc-experimental-components-i-e-swipeablerow/37709143#37709143

**Comment by janicduplessis** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-4** [comment]
Closing this issue as @janicduplessis says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.
