### ISSUE TITLE
The Navigator component can not work well in Android 

### ISSUE THREAD

**Issue by SmallComfort** [facebook/react-native#8061]
**Version of React Native:  0.27**
**occured on Android, I'm using Mac**
**Description**：
When I'm using Navigator Component, And if I want to touch left-to-right to back to previous，It does not work well in Android, No matter what I quickly swipes, It always can not back to previous until I get the "stillCompletionRatio"
The related source code is in this file:  react-native/Libraries/CustomComponents/Navigator/Navigator.js
In the line of 660, the code `Math.abs(velocity) < releaseGesture.notMoving` is always "true" in Android
In the line of 650, the code: `var isTravelInverted = releaseGesture.direction === 'right-to-left' || releaseGesture.direction === 'bottom-to-top';`, does it should be `var isTravelInverted = releaseGesture.direction === 'right-to-left' || releaseGesture.direction === 'left-to-right';` ？

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/the-navigator-component-can-not-work-well-in-android-

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
