### ISSUE TITLE
Something happend with performance Android.

### ISSUE THREAD

**Issue by antoxi4** [facebook/react-native#8063]
I update react native to 27.2 and animation in some places begin work with freezing.

**Comment by satya164** [comment]
@antoxi4 Are you connected to a debugger?

**Comment by antoxi4** [comment]
No. without connect to debugger. It happen when i update from 0.25.2 to latest release(((

**Comment by undef1ned** [comment]
#7995

**Comment by undef1ned** [comment]
Probably the same issue #7995

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/something-happend-with-performance-android

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
