### ISSUE TITLE
How is the "android" directory built?

### ISSUE THREAD

**Issue by nevir** [facebook/react-native#8067]
I'm attempting to depend on a specific git commit of react native.  Unfortunately, because the package has no `prepublish` script (and npm doesn't honor them on git installs anyway), the `android` directory is not generated.  

Confusingly, this leads to gradle silently pulling the latest version of `react-native` from jcenter (`0.20.1`), which leads to all sorts of subtle and difficult to understand errors.

How is the `android` directory generated, so I can at least sneak in a `prepublish` script of my own that runs it?

**Comment by satya164** [comment]
@nevir the `android` directory is generated when you run `react-native init`. Not sure if putting it in `prepublish` is a good idea, as it'll overwrite all your changes.

**Comment by satya164** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-5** [comment]
Closing this issue as @satya164 says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

**Comment by nevir** [comment]
@satya164 Sorry, my question wasn't very clear :(

I mean, how does the `node_modules/react-native/android` directory get built when you guys generate the npm package?  That's what's missing from my copy when installing from git

**Comment by satya164** [comment]
@nevir You might wanna look into this - http://facebook.github.io/react-native/docs/android-building-from-source.html

**Comment by nevir** [comment]
Oh perfect, thanks!
