### ISSUE TITLE
[Question] Event same close form in react native?

### ISSUE THREAD

**Issue by Shinichi52** [facebook/react-native#8070]
Hi All,
I'm newbie. I have a function and I want to callback it before router to new form.
How to callback it?

**Comment by satya164** [comment]
@facebook-github-bot stackoverflow

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-9** [comment]
Hey @Shinichi52 and thanks for posting this! @charpeni tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
