### ISSUE TITLE
Failed run android simulator : com.android.builder.testing.api.DeviceException: Timeout getting device list.

### ISSUE THREAD

**Issue by kumartarun** [facebook/react-native#8073]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:installDebug'.
> com.android.builder.testing.api.DeviceException: Timeout getting device list.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 1 mins 42.749 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

spent lot of time in setting up environment but now i am stuck here  , My emulator working fine appropriate build tools installed 
Help !!

**Comment by stanhe** [comment]
i think it's maybe the gradle script problem,i have't check this code .but you can follow this:
1.start your genymotion launch page,where you can creat your virtual devices.
Settings --> ADB --> Use custom Android SDK tools ,set the location you used before
2.restart genymotion and run adb devices,you will get the right devices,run react-native run-android
intresting! nothing changed yet,yes. you are right.then?
3.go to the project you just creat "AwesomeProject",goto app/build/outputs/apk,drag the app-debug.apk to the genymotion.now it works ,you can edit the index.android.js file,and double R on the genymotion,but now the react-native run-android still get Error.

hope someone can get the really problem

by the way my colleagues did'nt get this Error.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/failed-run-android-simulator-comandroidbuildertestingapideviceexception-timeout-getting-device-list

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
