### ISSUE TITLE
Load image from .htaccess protected directory 

### ISSUE THREAD

**Issue by georgi-kovachev** [facebook/react-native#8077]
I have image files under .htaccess protected directory. Whenever I tried to access the image on the browser, it asks me the username/pwd.

Password is protected like basic auth system which requires username/pwd

I am using simple source to display that image file but obviously it doesn't. How can I show the image file from protected directory?

Or what should i do in react native. React native code:

<Image style={styles.logo} source={{uri: 'https://xxx.xxx.com/abc.jpg'}}/>

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-3** [comment]
Hey @georgi-kovachev and thanks for posting this! @DanielMSchmidt tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by ide** [comment]
You could try putting the username and password in the URL (https://developer.mozilla.org/en-US/docs/Web/HTTP/Basic_access_authentication#Features) if you don't actually care about security. Or write a proxy server or host the images somewhere else. But this issue doesn't seem closely related to React Native.
