### ISSUE TITLE
TouchableHighlight and TextInput are invisible and have no style by default

### ISSUE THREAD

**Issue by phpscrpt** [facebook/react-native#8080]
I have added a TextInput and a button (touchablehighlight) to a sample app however both are invisible by default. You do not realize that it  is a TextInput unless you touch inside it. The TextInput and the TouchableHighlight behave as if they are invisible Views.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/touchablehighlight-and-textinput-are-invisible-and-have-no-style-by-default

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
