### ISSUE TITLE
[ViewPagerAndroid][ScrollView] removeClippedSubviews breaks ViewPagerAndroid

### ISSUE THREAD

**Issue by ramilushev** [facebook/react-native#8088]
Having a `ViewPagerAndroid` inside a `ScollView` with `removeClippedSubviews` enabled, renders an empty view, instead of the `ViewPagerAndroid`'s contents.

Strangely, after changing the orientation from portrait to landscape, `ViewPagerAndroid` renders and swipes as expected.

Tested with react-native `0.27.2`, only on Android. Cannot confirm for iOS ...

[RNPlay example](https://rnplay.org/apps/o2GmqA)

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/viewpagerandroidscrollview-removeclippedsubviews-breaks-viewpagerandroid

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by mikelambert** [comment]
Sigh, I have exactly this issue. From what I can tell this appears to be a bug in RN. The link to the product-pain no longer exists/works, either.

Should I create a new issue, or do you want to re-open this one @mkonicek ?

**Comment by pencilcheck** [comment]
Seems like it still exist in the latest RN
