### ISSUE TITLE
Bug: WebView won't load javascript locally.

### ISSUE THREAD

**Issue by cablegunmaster** [facebook/react-native#8089]
Question and bug report at the same time, there is a difference in including HTML from the source prop and getting it from a external source. (webpage)

Situation A: If I include JS from a Html page on a different source its running fine. like trying to include a Webpage.

Situation B: If I run the JS Inline on the webpage it won't run the javascript or just be ignored eventhough  javaScriptEnabled={true}  I made a var with all the  HTML

    var html = <html>
    <head>
       <script type="text/javascript">
            //big blob of javascript library. which works online and offline in the browser but not on the webview     internally, but if loaded externally it does. kinda want to know how to debug.
       </script>
    </head>
    <body>
    We are here! some text to test if its visible or not. Works though.
    </body>
    </html>
    `

    render() {
                <WebView
                    style={{ height: 200, width: 200}}
                    source={{html: HTML}}
                    scalesPageToFit={true}
                    javaScriptEnabled={true}
                />
}
`
Output: 
We are here! some text to test if its visible or not. Works though.  , (but no JS mutation etc).

_How did I find this out?_
I tried running console.log(HTML); and used Diff checker (online checking source) both sources seemed to run the same code. and the graph i'm trying to show does not display on only one of them. It does display on the FF or chrome Webbrowser , and if I include it as a external webpage. But not if asked to run as a source immedialy on the WebView.

Just wondering what I can do to make a JS library work offline.
Probably I'm not understanding how to use WebView Locally with a JS library.  but I can't find anyone who knows more about this.

OS: Android.
React-native 0.27.2

Addendum:

- JavascriptInjected used and simple things like alert('hello world') works but there is information lacking about when to use javascriptInjected, how to use it. and what I can input it and can't.
Because I have no idea in which lifecycle the Webview Works I can't be able to work with it, can this be clearified? I am trying to make a graph. but it ain't loading.

Step 1 Load JS script.
Step 2 find a Canvas ID from webview's HTML.
Step 3 display graph on that Canvas ID using javascript.

**Comment by dozoisch** [comment]
I've found a couple of quirks for webviews. Have you tried loading the screen at the end of body instead of head? I found that for android it seems to work better when you locate them in the body. In iOS it is the opposite... they need to be put in the head.

Here are a few quirks:

1. Script tags for the web views need to be placed in the head for iOS and in the body for Android.
2. In Android, JavaScript is disabled by default in the web views, we need to enable it with `javaScriptEnabled={true}`
3. In prod, files needs to be included in the bundle, and need to be loaded from the filesystem. To do that we add them in Xcode and make sure we load them using a filesystem URI.
4. Bridge injection doesn't support single-quotes well. We need to escape them or replace them.

If you want more info, [I wrote an article about it](https://medium.com/rendez-voo/migrating-incrementally-from-a-react-app-to-react-native-part-1-of-2-4566626e4ac5#.11szsxu78)

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/bug-webview-wont-load-javascript-locally

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by zhangqiangoffice** [comment]
I have the same issue now!

**Comment by tobowers** [comment]
I'm running into this too.

**Comment by sujitpk-perennial** [comment]
+1 me too facing same issue

**Comment by sankarganeshsiva** [comment]
any fixes?

**Comment by sujitpk-perennial** [comment]
Finally I am able to solve this issue. I used 'let' in script file to declare a variable. After spending some time I found that Safari won't support 'let' keyword.

**Comment by asam139** [comment]
I am running into this too :(

**Comment by antonioaltamura** [comment]
@sujitpk-perennial could you kindly explain how did you manage to solve?

**Comment by cablegunmaster** [comment]
On Android this issue is still open, on IOS it seems to be fixed.

**Comment by antonioaltamura** [comment]
Are you serious? A bug coming from 2016? I really need to reconsiderate RN as choice.

**Comment by sujitpk-perennial** [comment]
@antonioaltamura  @cablegunmaster  I am able to load the local html js file on webview for both iOS and Android. 

```
<WebView
        source={Platform.OS == 'ios' ? require('../Resources/HTML_Files/index.html') : { uri: 'file:///android_asset/HTML_Files/index.html' }}
        style={[styles.WebViewStyle, { height: height - TOP_BAR_HEIGHT_IOS }]}
        onLoadEnd={this.webViewLoadEnd}
        javaScriptEnabled={true}
        ref={(webview) => {
          this.templateDetailsWebView = webview
        }} />
```

**Comment by cablegunmaster** [comment]
Which react-native version ? Issue reported was on: 0.27.2 version, could be they changed it.

**Comment by antonioaltamura** [comment]
I bootstrapped my app using create-react-native-app CLI, which uses Expo. I do not have an android directory, any advices?

**Comment by antonioaltamura** [comment]
Ok I got it works (so long tested only on android device):
https://github.com/crubier/react-graph-vis/issues/35#issuecomment-380218471

**Comment by Arshiamidos** [comment]
hey guys  
found the trick base on [Image doesn't show after bundling into the apk](https://github.com/facebook/react-native/issues/4084).   
as you know **require('index.html')** work on _simulator_ and _emulator_ for both &driod and IOS  
but problem will faced when you bundle and you want release your app   
for android just follow this  **enablejavascript**  and copy you files in **assets** folder in `YOUR_APP/app/src/main/assets` and use just picture below.  

and for ios just bundle package with 
`react-native bundle --entry-file index.ios.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios`
when bundle created you have **main.bundle.js** and **asset** folder   
just copy you files in  **.xcworkspace** like this image  
![ios](https://user-images.githubusercontent.com/6451804/39201543-963c2e00-4804-11e8-9031-fb87a9f2c46e.jpg)
and set free all **refrence** in will be and unchanged just like mine. 
![screen shot - - at](https://user-images.githubusercontent.com/6451804/39201713-1260aeac-4805-11e8-92dd-efd9209cb44f.png)
i hope this tutorial help you from confusing release app in RN

**Comment by sujitpk-perennial** [comment]
@cablegunmaster Sorry for late reply. I am working on RN version 0.48.3
