### ISSUE TITLE
RefreshControl should not 'steal' move gesture from ViewPagerAndroid

### ISSUE THREAD

**Issue by ramilushev** [facebook/react-native#8090]
If I have a `ViewPagerAndroid` inside of a `ScollView` with `RefreshControl` enabled, the `RefreshControl` will steal the pan movement from the `ViewPagerAndroid`.

What I mean is, by dragging the `ViewPager` to the left midway and then, without releasing the touch, start to drag down, the `RefreshContorl` will activate, appearing and resetting the state of the `ViewPager`.

![viewpager](https://cloud.githubusercontent.com/assets/6991764/16008302/0ae06660-3180-11e6-81ee-157e75b69a52.gif)

I tried to disable the `RefreshControl` as soon as the `ViewPager` returns something other than `idle`, but if the swipe is quick enough (which usually is), the update does not happen on time to stop the `RefreshControl` from appearing.

I'm using a Mac, react-native version 0.27.2

**Comment by DanielMSchmidt** [comment]
Just to be clear about this issue, isn't it specific to your layout? If so, StackOverflow may be a better place for this question, if not it seems like you are requesting a feature for React Native, which is generally done in ProductPains.

**Comment by ramilushev** [comment]
@DanielMSchmidt My layout is as simple as possible, but I've posted this on [SO too](http://stackoverflow.com/questions/37797554/refreshcontrol-stealing-move-gesture-from-viewpagerandroid).

**Comment by vonovak** [comment]
@ramilushev I believe your layout is not correct, see SO

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-1** [comment]
Hey @ramilushev and thanks for posting this! @DanielMSchmidt tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by sinjimmyi** [comment]
+1

**Comment by WeweTom** [comment]
same problem

**Comment by ramilushev** [comment]
This was fixed a while ago. What RN version are you using?

**Comment by WeweTom** [comment]
@ramilushev 0.36

**Comment by ramilushev** [comment]
I think 0.36 should be fine. Did you try the latest version?

**Comment by WeweTom** [comment]
it works now , thanks
