### ISSUE TITLE
How to change the namespace of my application?

### ISSUE THREAD

**Issue by fmmsilva** [facebook/react-native#8092]
I would like to use "a.custom.namespace.projectname" instead of "com.projectname". Is it possible?

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-1** [comment]
Hey @fmmsilva and thanks for posting this! @charpeni tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
