### ISSUE TITLE
ios webview url blank,but use the url on safari is ok

### ISSUE THREAD

**Issue by py110** [facebook/react-native#8097]
when i use webview ,i have a question
1、use the url in webview， it display blank
2、copy the url open in safari it is ok
`
'use strict';

var React = require('react');
var ReactNative = require('react-native');
var {
    StyleSheet,
    View,
    Text,
    PixelRatio,
    WebView,
    Platform,
  } = ReactNative;

var WebPage = React.createClass({
        statics:{
            title:'详情',
            description:'WebPage',
            id:'WebPage',
        },
        getInitialState(){
          return{
            url:this.props.url,
          }
        },

        componentDidMount() {
        },
        loadEnd() {
          console.log('finish');
        },
        navChange(navstate){
          console.log(navstate.url);
          console.log(navstate);
        },
        render:function () {

           return (
             
                     <WebView style={{
                           flex:1,
                       }}
                       source={{
                         uri: 'http://61.136.95.136:8888/JLGLApp/GWTFormPlay.html?forms=IPHONE_FORM_TJCX_BZTZ&contentView=IPHONE_FORM_TJCX_BZTZ.form1&sid=d08dfe2a0913a07d93927f7ab8d8&UserCaption=%E7%AE%A1%E7%90%86%E5%91%98&UserName=9999&DWZD_BH=S&DWZD_MC=%E4%B8%AD%E5%9B%BD%E7%9F%B3%E5%8C%96&DWZD_QC=%E4%B8%AD%E5%9B%BD%E7%9F%B3%E5%8C%96&DWZD_JS=&DWZD_MX=%20',
                       }}
                       javaScriptEnabled={true}
                       startInLoadingState={true}
                       automaticallyAdjustContentInsets={true}
                       scalesPageToFit={true}
                       onLoadEnd={()=>this.loadEnd()}
                       renderError={(error)=>console.log('error:'+error)}
                       scrollEnabled={true}
                        onNavigationStateChange={(navstate)=>this.navChange(navstate)}
                        onShouldStartLoadWithRequest={(event)=> {return true} }
                       />
              )
            }
});

var styles = StyleSheet.create({

 });

module.exports = WebPage;

`

**Comment by yesman317** [comment]
please paste your code~

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/ios-webview-url-blankbut-use-the-url-on-safari-is-ok

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by terrathe2** [comment]
is there any answer for this?
