### ISSUE TITLE
[Android] borderBottomWidth on TouchableOpacity don't work

### ISSUE THREAD

**Issue by sarovin** [facebook/react-native#8105]
Hi,
i have a TouchableOpacity component with this style:

```
buttonStyle={{
   backgroundColor: 'white',
   borderBottomWidth: 4,
   borderColor: '#c6d0d5',
}}
```

The result is this:
![fbutton](https://cloud.githubusercontent.com/assets/5980398/16041000/71cf0ddc-3233-11e6-932d-0f92e86be057.png)

Can't i set borderBottomWidht for android Platform?

**Comment by flexzero** [comment]
I think it's not possible directly for android. You have to override shape attribute for button style.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-borderbottomwidth-on-touchableopacity-dont-work

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by Pranit-Harekar** [comment]
You can achieve this by setting borderStyle = "Solid" and then specify your desired borderBottomWidth. It works!!! 🎉

```
{
    borderStyle: "solid",
    borderBottomWidth: 1
}
```
