### ISSUE TITLE
编译源码遇到的问题：Error:Execution failed for task ':ReactAndroid:cleanReactNdkLib'.

### ISSUE THREAD

**Issue by hpdx** [facebook/react-native#8113]
编译源码遇到的非必现问题：
1、Error:Execution failed for task ':ReactAndroid:cleanReactNdkLib'.
> Process 'command '/Applications/Tool/android-ndk-r10e/ndk-build'' finished with non-zero exit value 2
2、我执行Clear Project后错误有时会消失，这个问题后面又会出现。
3、我在配置中屏蔽了clean.dependsOn cleanReactNdkLib，这个问题就没有了。
4、我想知道导致这个问题的具体原因，还有屏蔽clean.dependsOn cleanReactNdkLib会引发其他问题吗？

**Comment by belemaire** [comment]
Related to #7935 which propose a fix

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/errorexecution-failed-for-task-reactandroidcleanreactndklib

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by tensorflowfans** [comment]
please speak english
