### ISSUE TITLE
Cannot change background color of NavigationCards in a NavigationCardStack

### ISSUE THREAD

**Issue by edmofro** [facebook/react-native#8116]
It's all in the title, the result is an ugly looking transition with our app that has a different background colour.

See https://github.com/facebook/react-native/pull/8115 for a potential fix

**Comment by javache** [comment]
Can you provide an example of where this is an issue? `NavigationCardStackStyleInterpolator` doesn't provide a default backgroundColor, so it should just inherit the one from its container.

**Comment by edmofro** [comment]
That's right, but when used in the context of a NavigationCardStack, its container is a NavigationCard, which does have a default backgroundColor (see line 149 of NavigationCardStack.js, https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/NavigationExperimental/NavigationCard.js) 

JasperStam's fix solves the issue by exposing a cardStyle prop on NavigationCardStack, which is passed through to the NavigationCard; any styles in cardStyle will take precedence over the NavigationCard's default styles.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/cannot-change-background-color-of-navigationcards-in-a-navigationcardstack

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
