### ISSUE TITLE
[Android] i get a error when i fetch a image

### ISSUE THREAD

**Issue by fulang0208** [facebook/react-native#8119]
I use fetch to download a image,
 `fetch(imageURL).then((response)=>{ ... }).catch((err)=>{...})`
it work good in ios, but Android will get a error `Exception creating JSON string: null`
and if i open the js debug, no error. why?

**Comment by charpeni** [comment]
Can you provide a code sample ? A bit more than your last message.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-i-get-a-error-when-i-fetch-a-image

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
