### ISSUE TITLE
webview  x-www-form-urlencoded

### ISSUE THREAD

**Issue by China1Ai** [facebook/react-native#8124]
hi,everyone.
i'm using webview to loading the page.

when i use postman to test the apipoint,i post the uri with the body params in x-www-form-urlencoded,it will successed and respone the html.

when i use fetch,like this:
 fetch(this.props.uri, {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/x-www-form-urlencoded'
      },
      body: JSON.stringify(this.props.info)
    }).then(data => {
      console.log(data);
    })
in the console,it log like this:

ok:true
status:200
statusText:undefined
type:"default"
url:"https://www.xxxx.com/mobilegateway/xxxxxxx.htm"

now i use source={uri:this.props.uri,method:'POST',body:'a=1&b=2'} to request the uri. but it dosen't work,it will loading the page with errors like does't post the body.

what should i do?thanks.

e,my english is poor.

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-1** [comment]
Hey @China1Ai and thanks for posting this! @DanielMSchmidt tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by China1Ai** [comment]
it's my fault.when i use 'encodeURIComponent' to translate the params,the problem had solved.
