### ISSUE TITLE
Rotating list view causes text to disappear and sometimes causes app to STB

### ISSUE THREAD

**Issue by jaygarcia** [facebook/react-native#813]
Rotating the list view causes the text to disappear.  In some cases, the UIExplorer sample STBs. 

Perhaps the Flex layout has something to do with it?
```
 row : {
        flexDirection   : 'row',
        justifyContent  : 'center',
        padding         : 10,
        backgroundColor : '#F6F6F6',
    },
```

My App:
![stb2](https://cloud.githubusercontent.com/assets/180031/7101649/516eed6e-e031-11e4-8930-fcf9cb12992f.gif)

UIExplorer:
![stb](https://cloud.githubusercontent.com/assets/180031/7101639/e89d0f3c-e030-11e4-8672-50e04dffb68b.gif)

**Comment by ustun** [comment]
I can confirm, the example UIExplorer project has the same bug.

**Comment by siuying** [comment]
Yep this happens.

**Comment by drkibitz** [comment]
Seeing this in my own layout:
contentContainer: `position: 'absolute', left: 50, right: 50, top: 0, bottom: 0`
contentColumns: `flexDirection: 'row'`
contentColumn: `flexDirection: 'column', flex: 1`
contentColumnText: ...text styles...

If I give `contentContainer` an explicit `width` disallowing anything to reflow, text remains visible.

Also if I give `contentColumn` the style of `alignItems: 'flex-start'` it allows the containers to reflow, but also prevents the text from wrapping, therefore the text remains visible here as well. This points to something specific in the text view...

Maybe is has to do specifically with `alignItems: 'stretch'` and the text view, because with this style the text continues to disappear? Just not sure though, these are all just assumptions at this point.

**Comment by drkibitz** [comment]
Also an important note:
This issue is not related to ListView, or ScrollView, it can be reproduced easily in any View.

**Comment by drkibitz** [comment]
Tracing things back to this commit https://github.com/facebook/react-native/commit/3f6943c9abc90592c7f2e36abda0a98cb435aaf0, related to changes in `Libraries/Text `

**Comment by drkibitz** [comment]
Did some more digging, it looks like it is related to the NSLayoutManager losing it's reference to the NSTextStorage which results in NSLayoutManager returning an empty glyphRange in RCTText's `drawRect` method.

What's weird is when I compare `_textStorage.layoutManagers[0] == _layoutManager` I get `true`. But, `_layerManager.textStorage` is indeed `nil`. So the `_layoutManager` is added to _textStorage, but it does not have a reference back to the receiver, but I'm not sure how this happened.

NSLayoutManager.h says not to set `layerManager.textStorage` directly, but the funny thing is, when I do   this exactly, e.g. `_layoutManagers.textStorage = _textStorage;` inside `drawRect`, everything seems to work.

This seems like unexpected UIKit behavior to me, what does everyone else think?

**Comment by drkibitz** [comment]
Finally, I think I've got a fix, turns out we were causing this error in RCTShadowText RCTMeasure function here https://github.com/facebook/react-native/blob/master/Libraries/Text/RCTShadowText.m#L28

Turns out, an NSLayoutManager does allows, but does not work when adding to more than one NSTextStorage receiver.

I think I've got a PR brewing I should make shortly.

**Comment by chirag04** [comment]
+1. Having the same issue. @vjeux
