### ISSUE TITLE
New apps and app updates must be built with the public (GM) versions of Xcode 6 or later

### ISSUE THREAD

**Issue by DenisIzmaylov** [facebook/react-native#8136]
Dear,

Thank you for this great project.
I've just created a simple project with using Redux and CodePush.

Today I tried to publish the project to iTunes Connect but got an error message:

***
New apps and app updates must be built with the public (GM) versions of Xcode 6 or later, OS X, and iOS SDK. Don't submit apps built with beta software including beta OS X builds.
![image](https://cloud.githubusercontent.com/assets/1690596/16099784/ddb4efa0-3362-11e6-8e53-3bbaa1e5fd6f.png)
***

I did not update any options in Info.plist except of bundle ID, app ID, etc.

Is it something wrong in default ios folder?

Mac with OS X El Capitan, Universal Build for iOS, Xcode 7.3.1

**Comment by happierall** [comment]
I have this issue too...

**Comment by 7kfpun** [comment]
Assume that you have updated OS X to beta version like me...Change from 15G19a to 15F34.

http://stackoverflow.com/questions/32174954/submitting-app-from-building-in-xcode-6-4/32233429#32233429

Do at your own risk.

**Comment by DenisIzmaylov** [comment]
I've not updated OS X and use latest stable version as I mentioned in the message. :\

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/new-apps-and-app-updates-must-be-built-with-the-public-gm-versions-of-xcode-6-or-later

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
