### ISSUE TITLE
Auto binding doesn't work with ES6-style components

### ISSUE THREAD

**Issue by grgur** [facebook/react-native#814]
When creating a component 'ES6-style' (e.g. `class Card extends React.Component`), event callbacks will not automatically bind scope. 

In the following example, I had to replace 
`onPress={this.onPress}` 
with 
`onPress={this.onPress.bind(this)}`.

Using React Native 0.3.11

```
class Card extends React.Component {
    constructor(properties) {
        super(properties);
        this.state = {
            paired: false,
            visible: false
        };
    }
    
   onPress() {
        var state = this.state;
        console.log("I am no longer null", state);
    }
    render() {
        return (
          <TouchableHighlight
            onPress={this.onPress.bind(this)}
            underlayColor="blue"
            activeOpacity={0.5}>
            <Text>Dummy Text</Text>
          </TouchableHighlight>
        );
    }
};
```

**Comment by spicyj** [comment]
This is expected behavior. In ES7 you'll likely be able to use a [property initializer](https://gist.github.com/jeffmo/054df782c05639da2adb) to write

```
onPress = () => {
  // ...
}
```

which will autobind. This syntax is supported by Babel already in an experimental transform and hopefully will be supported in react-native sometime. You can continue to use React.createClass if you prefer its semantics.
