### ISSUE TITLE
Android's NFC support for React Native

### ISSUE THREAD

**Issue by fadils** [facebook/react-native#8144]
Hi Guys,

I've been wandering around the web about implementing react native NFC modules. Got some posts where they say we can encapsulate the NFC with native modules. Also got some posts where they say react native cannot do NFC stuff.

So, I'd better get the answer first hand.

Is this something feasible?

**Comment by ide** [comment]
It should be feasible if you write your own native modules. My guess is that the discrepancy comes from the fact that RN doesn't include NFC support, but you could implement it yourself.

**Comment by fadils** [comment]
Thanks!

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-1** [comment]
Hey @fadils and thanks for posting this! @DanielMSchmidt tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by giordy** [comment]
@fadils if you're still interested we recently released on GitHub [react-native-nfc](https://github.com/Novadart/react-native-nfc).
