### ISSUE TITLE
Dead lock

### ISSUE THREAD

**Issue by Nice2Me** [facebook/react-native#8145]
- When open debug in chrome, dead lock appears in our project?

- Identify problem and find dead lock appears in the following pic:
![image](https://cloud.githubusercontent.com/assets/17569377/16107709/b748d908-33d0-11e6-9b3a-278f0c2596ac.png)

- Add log and print and find out the dead lock appears in the class RCTModuleData[_moduleClass:RCTUIManager]

![image](https://cloud.githubusercontent.com/assets/17569377/16107804/4638833e-33d1-11e6-9244-5e6040d1798d.png)

Logs as follows:

 
-  `Method: [- (void)setUpInstanceAndBridge]` exists the case of dead lock` .

So, i do judge if _instance had been created in `Method: setUpInstanceAndBridge` before adding the lock and resolve it.

- I hope, you can resolve it as soon as possible or give me good advise

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/dead-lock

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
