### ISSUE TITLE
[Android][0.27.2] Fetch send cookie but sever can not receive

### ISSUE THREAD

**Issue by iinterest** [facebook/react-native#8149]
code:
```
let headers = new Headers({
    'Cookie': options.cookie,
    ...
});
fetch(url, {
    method: 'POST',
    headers: headers,
}).then(data => {
    ...
})
```
rn 0.25 is OK，but in 0.27.2 sever can not receive cookie

**Comment by 281330** [comment]
Are you debugging in chrome?  Just curious

**Comment by iinterest** [comment]
no...

**Comment by lznt** [comment]
We are experiencing the same problem.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android0272-fetch-send-cookie-but-sever-can-not-receive

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
