### ISSUE TITLE
Improve adding React Native to an existing Android app

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/react-native#8161]
We landed a big update to how to integrate RN to existing applications..

http://facebook.github.io/react-native/releases/next/docs/tutorial-integration-with-existing-apps.html

However, this focused on iOS and Swift mostly and the Android wording is basically the same as before with minor modifications. Do the same sort of thing for Android as we did for iOS.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/improve-adding-react-native-to-an-existing-android-app

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
