### ISSUE TITLE
How to distinguish phone and tablet in both android and ios in react-native?

### ISSUE THREAD

**Issue by susylPearl** [facebook/react-native#8176]
i want to make gridview customized in both tablet and phone. How can i distinguish both of them?

**Comment by Ehesp** [comment]
Well android and ios you use the Platform api. As for tablet, you could always use the Dimensions api to grab the width and determine whether it's a tablet from that.

**Comment by samuelkraft** [comment]
Use [onLayout](https://facebook.github.io/react-native/docs/view.html#onlayout) in your root view to get width and height. The Dimensions api isn't always updating on rotation/all devices. onLayout will always give you the correct size of the app.

**Comment by charpeni** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-1** [comment]
Closing this issue as @charpeni says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.
