### ISSUE TITLE
how to set default view property's order?

### ISSUE THREAD

**Issue by fov42550564** [facebook/react-native#8181]
when I create a custom view, it has several properties, how can I make sure these properties' order.
```ojbc
RCT_CUSTOM_VIEW_PROPERTY(props1, NSInteger, MyView) {
   doSomeThing1();
}
RCT_CUSTOM_VIEW_PROPERTY(props2, NSInteger, MyView) {
   doSomeThing2();
}
```
 ```doSomeThing2``` depend on  ```doSomeThing1```, so when I set default property I want doSomeThing1 exec before doSomeThing2,  as follows:
```js
<MyView props1={1} props2={2} />
```
Is there has some ways to solve it?

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-1** [comment]
Hey @fov42550564 and thanks for posting this! @charpeni tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by aleclarson** [comment]
I'm also facing this issue. Since the `props` on iOS side are stored in an `NSDictionary`, the keys are unordered. This means props have no guaranteed order in which they're updated.

**Comment by aleclarson** [comment]
I'm also facing this issue. Since the `props` on iOS side are stored in an `NSDictionary`, the keys are unordered. This means props have no guaranteed order in which they're updated.

@ide Is there a way around this?

**Comment by aleclarson** [comment]
Looks like the best solution is to implement `didSetProps` in your view implementation.

```objc
- (void)didSetProps:(NSArray<NSString *> *)changedProps
{
  // Do something that depends on all props having a value.
}
```
