### ISSUE TITLE
[Docs] Ambiguity in Getting Started (Android) SDK Platform Configuration

### ISSUE THREAD

**Issue by mendelk** [facebook/react-native#8195]
In the [Getting Started docs](https://facebook.github.io/react-native/docs/getting-started.html), it [says](https://github.com/facebook/react-native/blob/dc49edb9bbb1938114ff79a971bdd2d1b0c6a6b6/docs/getting-started.html#L62):

> In the `SDK Platforms` window, choose `Show Package Details` and under `Android 6.0 (Marshmallow)`, make sure that `Google APIs`, `Intel x86 Atom System Image`, `Intel x86 Atom_64 System Image`, and `Google APIs Intel x86 Atom_64 System Image` are checked.

However, this is the illustrative image:

![](https://facebook.github.io/react-native/img/react-native-android-studio-android-sdk-platforms.png)

Notice that `Android SDK Platform 23` and `Sources for Android SDK` are checked. Are these required? If yes, it should be noted. If not, perhaps they should be unchecked in the image? They weren't checked in my installation by default.

Another thing: `Intel x86 Atom_64 System Image` is noted as required to be checked, however the image shows it as unchecked. And while `Google APIs Intel x86 Atom_64 System Image` is supposed to be checked per the docs, the illustration has it unchecked, and instead has `Google APIs Intel x86 Atom System Image` checked (note the lack of `_64`).

I apologize if these are considered nit-picks, but ambiguities are confusing for newbies, such as myself 😄 

I'd be glad to make a PR once given clarification as to the correct verbiage.

Thank you!

**Comment by charpeni** [comment]
@facebook-github-bot label Documentation

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/docs-ambiguity-in-getting-started-android-sdk-platform-configuration

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
