### ISSUE TITLE
[JS] Remove the Yeoman dependency from the codebase

### ISSUE THREAD

**Issue by mkonicek** [facebook/react-native#8197]
The React Native CLI uses Yeoman generators for 'react-native init'. Yeoman has tons of dependencies and significantly adds to the time it takes to install React Native and to the size of `node_modules`.

We want to rewrite the code so it doesn't make use of Yeoman, so that we can remove the Yeoman dependency from package.json.

Here are the templates we currently process with Yeoman:
https://github.com/facebook/react-native/tree/master/local-cli/generator-android
https://github.com/facebook/react-native/tree/master/local-cli/generator-ios

We can probably use something much simpler, such as [lodash templates](https://lodash.com/docs#template) or simple string replace :) Our templates are super simple, we just replace a few placeholders.

One thing to think about is also `react-native upgrade` which uses Yeoman's fancy features for conflict resolution (shows which files would be overwritten by the upgrade). It shouldn't be hard to build something similar (simpler is fine).

**Comment by mkonicek** [comment]
@satya164 Started hacking on this. A really good start: https://github.com/satya164/generator

**Comment by mkonicek** [comment]
Adding a dependency on ncp is fine, it has no dependencies and it's <300 lines of code: https://github.com/AvianFlu/ncp/blob/master/lib/ncp.js

**Comment by gavriguy** [comment]
We started working on this issue on yesterday's fb hackathon on TLV
I'll as @mkonicek mentioned we plan use the ncp dependency for copying files from the template to the destination. I'll organize my code this weekend and post an update

**Comment by gavriguy** [comment]
The task seams to be a bit big. so before I create a huge PR I would like to summarise what we have and the my plan to fix this.

### Step 1 -  apply simple search and replace instead of using yeoman templates
@yuliroth and myself tweaked a bit  @satya164 worked and created a mechanism that can compile templates for iOS & Android using a simple search and replace

https://github.com/gavriguy/rn-init-generators

### step 2 - integrate the simple generators and remove any trace of yeoman in the code.
I still need to do more research and understand any bit of code in the `local-cli` folder to make sure we aren't removing functionality we want to keep 

Any comments or thoughts are more than welcome

**Comment by mkonicek** [comment]
@gavriguy Sounds great! Those two steps are a good way to go. For step 2, you'll need to look into `react-native upgrade` (try it on an older app).

**Comment by christopherdro** [comment]
Related #8610
