### ISSUE TITLE
Race condition in NavigatorNavigationBar.js on Android

### ISSUE THREAD

**Issue by MichaelDanielTom** [facebook/react-native#8205]
Hey guys,
I've been using Navigator completely fine for the last month until today. While mounting the navigator, it worked fine in dev, but when I assembled a release build, it kept throwing:

`TypeError: undefined is not a function (evaluating 'this._descriptors[componentName].indexOf(route)')`
At line 191 of [NavigatorNavigationBar.js](https://github.com/facebook/react-native/blob/b9396cd74419dd4165fb051605076d19b1c18905/Libraries/CustomComponents/Navigator/NavigatorNavigationBar.js)

After rebuilding a few times this started happening in dev mode too. After hours, I finally put a console.warn right before the offending call... and it all worked from then on out... I have no idea why this is, but I suspect a race condition, does anyone have any insight into this?

**Comment by MichaelDanielTom** [comment]
Update: It looks like it's trying to use "includes" on a Map, when it should be using "has". I'll submit a PR shortly.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/race-condition-in-navigatornavigationbarjs-on-android

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
