### ISSUE TITLE
[Android] fetch https then app crash

### ISSUE THREAD

**Issue by EasonWang01** [facebook/react-native#8210]
When I fetch an https domain it will crash then exit the app,But for http domain it works fine.
What might cause this problem?Thanks

something like this

```
    fetch(REQUEST_URL)
      .then((responseData) => {
     
        console.log(responseData)
      })
      .done();
```

**Comment by satya164** [comment]
Can you provide a reproducible sample, and the crash log?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-fetch-https-then-app-crash

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
