### ISSUE TITLE
NavigationExperimental: Unhandled JS Exception: Can't add property 0, object is not extensible

### ISSUE THREAD

**Issue by mschipperheyn** [facebook/react-native#8218]
After trying to upgrade from 0.24.1 to 0.26.2 I ran into this exception using NavigationAnimatedView.

As I understand the exception, React Native's Animated doesn't like it anymore if you use an animation value that is not an Animated.Value, which is what NavigationExperimental seems to be doing. 

But I could be wrong. I generally find these kinds of issues hard to debug.

**Comment by jmurzy** [comment]
I strongly recommend you to upgrade to v0.28-rc. A lot has changed in NavigationExperimental since v0.26.

If it still spits out an exception after the upgrade, please post the block of code that's causing it so we can help you debug.

🍺

**Comment by mschipperheyn** [comment]
Yeah, I'll upgrade a bit later. Got a bit scared when I saw all the changes. Also,  the. 25 and. 26 upgrade didn't go smooth. Can't really afford to spend much time fixing working stuff right now.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/navigationexperimental-unhandled-js-exception-cant-add-property-0-object-is-not-extensible

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
