### ISSUE TITLE
[Docs] React Native Katas

### ISSUE THREAD

**Issue by jondot** [facebook/react-native#8227]
Hello all,

I've spent considerable efforts to make React Native more digestible for designers and complete beginners. [React Native Katas](https://github.com/jondot/ReactNativeKatas) is a fully immersive hands-on experience that such an audience can go through, with a basic development setup and an iOS simulator. It currently focuses solely on views and styles.

I've heard there's a documentation revamp, so this might fit in there somewhere as it proved a really efficient learning tool in a very short while. Please let me know if you'd like me to push this forward.

/cc @caabernathy

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/docs-react-native-katas

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
