### ISSUE TITLE
Android Switch does not animate when within ViewPagerAndroid

### ISSUE THREAD

**Issue by vonovak** [facebook/react-native#8228]
Demo of the bug: [rnplay](https://rnplay.org/apps/kKX9ZA)

Bug occurs on android: when a `Switch` is nested within `ViewPagerAndroid`, it does not animate when changing its state. The demo is using RN 24, but the bug occurs on RN 27.2 too.

edit: interestingly, it starts working after screen orientation changes.

**Comment by christopherdro** [comment]
@facebook-github-bot bugfix

**Comment by facebook-github-bot-4** [comment]
Hey @vonovak, we're a small team and rely on the community to fix issues that don't affect fb apps. If you're sure this is a bug can you send a pull request with a fix?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-switch-does-not-animate-when-within-viewpagerandroid

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
