### ISSUE TITLE
show the adjacent cards in ViewPagerAndroid

### ISSUE THREAD

**Issue by karthickvkumar** [facebook/react-native#8240]
I'm trying to implement a swiper in android, where cards are arranged horizontally and users can swipe left/right to see the next card coming from adjacent edge.
How can we achieve this in android?

**Comment by ryankask** [comment]
It's probably best to ask these sort of questions on StackOverflow or on Discord. Discord is chat app with a room dedicated to react-native. The users there are really knowledgable and they've helped me answer a ton of questions like this one. You can sign up here: http://join.reactiflux.com/ and then ask the question in the "#react-native" channel.

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-1** [comment]
Hey @karthickvkumar and thanks for posting this! @DanielMSchmidt tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
