### ISSUE TITLE
<TextInput/> placeholderTextColor should be ColorPropType not string

### ISSUE THREAD

**Issue by erickreutz** [facebook/react-native#8253]
Can we change `placeholderTextColor` prop on `<TextInput/>` to be `ColorPropType` instead of `PropTypes.string`?

https://github.com/facebook/react-native/blob/master/Libraries/Components/TextInput/TextInput.js#L272

**Comment by javache** [comment]
That sounds reasonable. Could you send a pull-request for this?

**Comment by erickreutz** [comment]
@javache done.

https://github.com/facebook/react-native/pull/8325

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/textinput-placeholdertextcolor-should-be-colorproptype-not-string

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
