### ISSUE TITLE
[TextInput]How to get content height when TextInput has a defaultValue

### ISSUE THREAD

**Issue by musicode** [facebook/react-native#8271]
I want to write a auto grow text input, i know onChange will pass contentSize in event.nativeEvent

```jsx
<TextInput
  onChange={event => {
      event.nativeEvent.contentSize.height
  }}
/>
```

but if input has a defaultValue, how to get the content height?

sorry for my english...

**Comment by nihgwu** [comment]
you don't need to apologize for your english, it's understandable and that's ok
please try to ask questions on StackOverflow, issue is designed for bug tracking not for QA
and for your question, please refer to 
http://facebook.github.io/react-native/releases/0.27/docs/textinput.html#onlayout
http://facebook.github.io/react-native/releases/0.27/docs/view.html#onlayout

**Comment by nihgwu** [comment]
@Andreyco sorry for my quick answer, you are right

**Comment by damusnet** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-9** [comment]
Hey @musicode and thanks for posting this! @damusnet tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
