### ISSUE TITLE
about tarbarIOS icon selected

### ISSUE THREAD

**Issue by slowsay** [facebook/react-native#8273]
this tarbarios selected have square color ,
so i did it ;
node_modules/react-native/react/views/RctTabbaritem.h
--------------------------------------------------------
@property (nonatomic, strong) UIImage *selectedIcon;

node_modules/react-native/react/views/RctTabbaritem.m
--------------------------------------------------------
- (void)setIcon:(UIImage *)icon
{
  _icon = icon;
  if (_icon && _systemIcon != NSNotFound) {
    _systemIcon = NSNotFound;
    UITabBarItem *oldItem = _barItem;
    _barItem = [UITabBarItem new];
    _barItem.title = oldItem.title;
    _barItem.imageInsets = oldItem.imageInsets;
    _barItem.selectedImage = oldItem.selectedImage;
    _barItem.badgeValue = oldItem.badgeValue;
  }
    self.barItem.image = [_icon imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal];

}

- (void)setSelectedIcon:(UIImage *)selectedIcon
{
  _selectedIcon = selectedIcon;
  _systemIcon = NSNotFound;
    self.barItem.selectedImage = [_selectedIcon imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal];
}

node_modules/react-native/react/views/RCTTabBarItemManager
------------------------------------
//RCT_REMAP_VIEW_PROPERTY(selectedIcon, barItem.selectedImage, UIImage)
RCT_EXPORT_VIEW_PROPERTY(selectedIcon,UIImage)

**Comment by slowsay** [comment]
version:
 "react": "^15.0.2",
 "react-native": "^0.26.2"

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/about-tarbarios-icon-selected

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
