### ISSUE TITLE
ListView initialListSize property N interpreted as N+1

### ISSUE THREAD

**Issue by josvos** [facebook/react-native#8280]
The ListView property initialListSize suffers from the +/-1 problem.  Any size N (including the default property value of 10) is actually interpreted as N+1.

Just render a ListView with 12+ elements and see that there are 11 elements shown, or (e.g.) set initialListSize={5} and see 6 elements shown.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/listview-initiallistsize-property-n-interpreted-as-n1

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
