### ISSUE TITLE
[Android] Dimensions.get('window').height doesn't subtract the status bar size

### ISSUE THREAD

**Issue by kamek-pf** [facebook/react-native#8282]
The `Dimensions` API allows you to get either window or screen size : 

```
'window ', { width: 360, height: 592, scale: 3, fontScale: 3 }
'screen ', { width: 360, height: 640, scale: 3, fontScale: 3 }
```

However, it looks like 'window' doesn't subtract the size of the status bar (the one on top of the screen on Android). I feel like it should, otherwise, while setting a layout that's supposed to use all of the space, part of your view is gonna get cut off (most likely by 24 pixels, which seems to be the standard size for the status bar).

This is mostly problematic when setting background images, flex does the job well for regular views.

I don't know what behavior should be set as default, if what we currently have is the intended behavior, it would be nice to have a way to get the status bar height through the `Dimensions` API.

**Comment by simonvaucher** [comment]
Looks like the intended behavior. There are packages out there that get you the status bar height, though you can safely use 24 points in 99% of the Android devices.

**Comment by m3vaz** [comment]
@kamek-pf, This might be what you're looking for if you want a more granular breakdown of the heights.
https://www.npmjs.com/package/react-native-extra-dimensions-android

**Comment by phones24** [comment]
Unfortunately, the plugin is not compatible with react since 0.29

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-dimensionsgetwindowheight-doesnt-subtract-the-status-bar-size

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
