### ISSUE TITLE
Failed to build DependencyGraph - v0.28.0

### ISSUE THREAD

**Issue by danseethaler** [facebook/react-native#8294]
I'm getting this error when trying to build a new package from scratch with the newest version (0.28.0). I'm guessing it relates to 26e84262484767dd9abdfd78ff16fa37fcb8e334 where the folder `ActivityIndicatorIOS` was renamed to `ActivityIndicator`.

`Failed to build DependencyGraph: ENOENT: no such file or directory, open '/Users/username/Developer/Template/node_modules/react-native/Libraries/Components/ActivityIndicatorIOS/ActivityIndicatorIOS.android.js'`

I'm using the new reference of `ActivityIndicator`.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/failed-to-build-dependencygraph-v0280

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
