### ISSUE TITLE
WebSocket connection failed error after inactivity  

### ISSUE THREAD

**Issue by ywwgolife** [facebook/react-native#8302]
WebSocket connection failed with Error Domain = NSPOSIXErrorDomain Code = 57 "Socket is not connected "

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/websocket-connection-failed-error-after-inactivity-

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by ywwgolife** [comment]
thanks for your advise
