### ISSUE TITLE
Android: Support varying application id's for different build variants/flavors.

### ISSUE THREAD

**Issue by mvantellingen** [facebook/react-native#8308]
The ``react-native run-android`` supports setting a build variant via arguments but always uses the default application id when starting the app via adb.

So when you have a debug release and set applicationIdSuffix ".debug" then the adb command is executed with the wrong package name.

See https://github.com/facebook/react-native/blob/d4cc5b53c7770f8206e8dbe99593131a3ad0c2d0/local-cli/runAndroid/runAndroid.js#L123

React native version = 0.27.2

**Comment by tadas-subonis** [comment]
This is really annoying. I would like to keep my .debug suffix :(

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-support-varying-application-ids-for-different-build-variantsflavors

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
