### ISSUE TITLE
App crashes on reload. 

### ISSUE THREAD

**Issue by chanpod** [facebook/react-native#8317]
Whenever I try to debug or reload the app, it just "Unfortunately, XXX has stopped"

Windows - Android Emulator
react-native: 0.27

Firstly, debugging this is a nightmare b/c I can't see any logs. I can't run the app in debug mode b/c of the crashing. Logging things in the terminal using 

    adb logcat *:S ReactNative:V ReactNativeJS:V

Upon typing this out, I figured it out lol. Figures. Still think it's an issue though.

If you're using a singleton type service for rest calls and you have a timeout inside of a promise that doesn't get cancelled once the fetch completes, this is, for some reason, causing the app to fail completely.

Example

     var promise = new Promise(function (resolve, reject) {

			setTimeout(() => {
				reject("No response from server");
			}, fetchTimeout)
			
			resolve(fetch(url, { method: methodIn, headers: header, body: JSON.stringify(bodyIn) }));
		})

Not sure if this is necessarily a react-native problem, but I wanted to document it in case anyone else has the problem. Mostly b/c wasn't immediately obvious and it didn't do it all the time.

**Comment by tje3d** [comment]
Same problem here.
app will crash if there is an incomplete Fetch/XHR request.

in Fetch case user have to wait for request to be complete before exiting app ( ! )
but with XHR you can abort request in componentWillUnmount ...

Anyway i see another problem in XHR, the timeout property not works when you request to an unreachable address (or when you are in a bad network connection).

**Comment by 281330** [comment]
Not sure if this is related, just a wild guess.  Are your dependencies up to date?  I was receiving an error about minimatch out of date, and once I updated it, I was able to load my app (which makes a request as soon as it loads).

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/app-crashes-on-reload-

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
