### ISSUE TITLE
KeyUp and KeyDown listener 

### ISSUE THREAD

**Issue by AtixD** [facebook/react-native#8330]
Hey, tell me how to put the global event keyUp keyDown on Android device. Thx.

**Comment by skv-headless** [comment]
If I understand you correct you can create wrapper around one of ```Touchable``` with ```onPressIn```, ```onPressOut``` and use it everywhere.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/keyup-and-keydown-listener-

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
