### ISSUE TITLE
[Android] react native run-android to pass arguments to gradlew

### ISSUE THREAD

**Issue by beast** [facebook/react-native#8343]
Hi, all. I've been working an Android project and can't really figure out a way to pass arguments to the react native run-android cli. The specific one I am looking for is --offline before the gradlew (graddle wrapper is taking forever to resolve dependency due to some packages I use.) Using this option actually help reduce my build time from 4 mins to 40 seconds. It would be nice if we could pass additional gradle wrapper parameters with react native run-android. Please advise. Thanks.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-react-native-run-android-to-pass-arguments-to-gradlew

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
