### ISSUE TITLE
Trouble updating a ListView row when the state changes.

### ISSUE THREAD

**Issue by SudoPlz** [facebook/react-native#8353]
Hello,
I'm trying to update the rows on a ListView when the state changes but I don't want to use the `Datasource.rowHasChanged` method because its NOT the `rowData` that is changing.

How can I actually force a change in the listview?

Thank you.

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-3** [comment]
Hey @SudoPlz and thanks for posting this! @charpeni tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
