### ISSUE TITLE
Android: Set/Update root properties

### ISSUE THREAD

**Issue by fab1an** [facebook/react-native#8356]
The iOS guide mentions `appProperties` to update the `props` of the root-view. There doesn't seem to be such a method for Android.

**Comment by fab1an** [comment]
Any ideas on this?

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-setupdate-root-properties

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by fab1an** [comment]
This is missing in the documentation.
