### ISSUE TITLE
[Idea: Touchable] let Touchable support a "press radius" instead of a "press rect"

### ISSUE THREAD

**Issue by spicyj** [facebook/react-native#836]
Migrating from facebook/react#3602 (cc @ide):

> The press rect defines a rectangle around a touchable component in which the touch stays active. I was thinking a radius (or a pair of radii to form an oval) around the touchable component makes more sense than a rectangle in some ways.

**Comment by ide** [comment]
I originally posted in the React repo since Touchable.js is vendored from there. It applies to both projects so would be good to discuss it here too.

**Comment by spicyj** [comment]
I see, it's in vendor/react_contrib/interactions. That's not actually part of the React repo though and I'm pretty sure the source of truth for that file is here.

**Comment by ide** [comment]
Oh ok. For some reason I thought those files were from React proper.

**Comment by spicyj** [comment]
No worries.

**Comment by brentvatne** [comment]
:+1:

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/idea-touchable-let-touchable-support-a-press-radius-instead-of-a-press-rect

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
