### ISSUE TITLE
Issue @ getting started, attached npm-debug.log

### ISSUE THREAD

**Issue by CarreraPHP** [facebook/react-native#8376]
React Native Version: react-native-cli: 1.0.0
react-native: n/a - not inside a React Native project directory

OS: Mac OS X El Captain
[npm-debug.txt](https://github.com/facebook/react-native/files/330663/npm-debug.txt)

**Comment by charpeni** [comment]
What are you trying to do ? Can you provide more information ?

**Comment by CarreraPHP** [comment]
After longtime, wanted to try creating an React Native application. So went to "Getting started" and followed the instruction. Installed Homebrew, flow, watchman & ReactNative-cli.

executed "react-native init PlaybookPreMobile" in command line and i got below error in log. 

log: 

-------------------------

This will walk you through creating a new React Native project in /Users/yogeshofit/Desktop/React/NativeWorkspace/PlaybookPreMobile
Installing react-native package from npm...

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "--save-exact" "react-native"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5

npm ERR! Invalid Version: 0.0.1alpha1
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/yogeshofit/Desktop/React/NativeWorkspace/PlaybookPreMobile/npm-debug.log

`npm install --save --save-exact react-native` failed

-------------------------

Regards,
Yogesh Surendran alias CarreraPHP

**Comment by CarreraPHP** [comment]
Any update for the issue?

**Comment by charpeni** [comment]
Everything works fine on my side on OS X and node v6.2.2.

Can you try again?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/issue-getting-started-attached-npm-debuglog

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
