### ISSUE TITLE
react-native-android-studio-android-sdk-platforms-windows.png and react-native-android-studio-android-sdk-build-tools-windows.png are wrong

### ISSUE THREAD

**Issue by yajiex** [facebook/react-native#8393]
See https://facebook.github.io/react-native/docs/getting-started.html, the following two images are mismatched with their descriptions:
- react-native-android-studio-android-sdk-platforms-windows.png
- react-native-android-studio-android-sdk-build-tools-windows.png

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/react-native-android-studio-android-sdk-platforms-windowspng-and-react-native-android-studio-android-sdk-build-tools-windowspng-are-wrong

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (64/60 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter01.reliabledns.org ([199.96.156.50]:56237)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bzsvd-0004EB-Ap
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 22:13:43 +0000
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193] helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by filter01.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1bzsvb-0000dw-JM
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 15:13:40 -0700
Date: Thu, 27 Oct 2016 15:13:29 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1477606418;
	bh=yD3t+airFfwhPGEfGRZ7a/DzGajpPABnPxZxtdJ+R+U=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=wdwt818/IEUWJ46/dW5vAMXOzZpI9Cq0CPXSYFF7hDqRtFBMB7Voufjt0tvibfbo8
	 Wz3WNqFZsSlDQhwdwA0XdKQLn09VIp6RaBVZbS0k9ZSRuUkKwPHTHp9dseze8EKUPz
	 p2TSl2B+j1UxnGNwiV8X4A8Pr/Ncg1PG71O+8mLA=
