### ISSUE TITLE
ImagePipelineFactory was not initialized!

### ISSUE THREAD

**Issue by leeight** [facebook/react-native#8397]
1. Checkout the source code
2. Build and Install UIExplorer to Android Devices
3. The first time to launch UIExplorer app

![image](https://cloud.githubusercontent.com/assets/104052/16330338/0e9adf58-3a1b-11e6-9bd4-ac8cb30fab8a.png)

But after `RELOAD`, everything works fine.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/imagepipelinefactory-was-not-initialized

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
