### ISSUE TITLE
Getting Error ENOSPC while starting react native application

### ISSUE THREAD

**Issue by prafulc** [facebook/react-native#8403]
I have just created my new react native application and I am getting error while starting it. I am using Ubuntu 12.04. I have attached screen-shot of my terminal
![screenshot from 2016-06-24 18 20 03](https://cloud.githubusercontent.com/assets/14888733/16338314/70ea6da4-3a39-11e6-839b-bf365e7e1d07.png)
I have checked whether my temp is full, but found my temp has more space and has only 1% of usage. So I don't think it will be problem of that. Any suggestions

**Comment by fabianfiorotto** [comment]
Take a look at this answer in stackoverflow. It worked for me
http://stackoverflow.com/a/32600959

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/getting-error-enospc-while-starting-react-native-application

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
