### ISSUE TITLE
[IOS] Since 0.28.0 no network connection in Xcode Simulator

### ISSUE THREAD

**Issue by alexanderniebuhr** [facebook/react-native#8419]
Hey folks,

I am running an App on React Native 0.28.0 and IOS 9.3.3 Simulator from XCode 7.3 on MacOS Sierra 10.12

If I start to Start the App and Try to use a NetInfo.isConnected Statement to check if internet connection is available. I get always false. Even if I pass this security check manually I will get an Network error in the normal API Http fetch function.

So Simulator has Internet (Tried with Safari) and my App not

Any Idea?

Kind Regards
Alex

**Comment by khiemnm** [comment]
you're true.
I'm getting same issue.
fetch works in version 0.27 but not 0.28.
Please fix it soon

**Comment by levinqdl** [comment]
+1

**Comment by khiemnm** [comment]
i think its resolved. Please go here
https://github.com/facebook/react-native/issues/8118

**Comment by dot3bumpmap** [comment]
0.29.0-rc.0    (upgraded from 0.26)
'Allow Arbitrary Loads' is on for me but I'm still getting this issue.

**Comment by jeroenbourgois** [comment]
I am getting it too, but only on a physical device (or at least it has something to do with this since all fetch'es fail... In the simulator it works fine.

**Comment by ryankask** [comment]
I'm having a different issue related to connectivity checking.`NetInfo.isConnected.fetch()` initially returns `false` but if the device is connected, it then updates and returns `true`.

I saw a post in the FB dev group reporting this but is anyone else experiencing something similar?

**Comment by jeroenbourgois** [comment]
@ryankask Update on my issue, after some digging I realized it was exactly what you were experiencing!

**Comment by ryankask** [comment]
Interesting. The poster on Facebook mentioned this commit: https://github.com/facebook/react-native/commit/b71db1155440ec433dcf51b54c015166ecca8732

I don't know much about iOS dev but after reading it, it seems like the behaviour of NetInfo has changed. RCTNetInfo now implements RCTEventEmitter and it appears as though the SCNetworkReachability registration is now done lazily when a callback is first registered with NetInfo. (https://github.com/facebook/react-native/blob/b71db1155440ec433dcf51b54c015166ecca8732/React/Modules/RCTEventEmitter.m#L79)

The SCNetworkReachability code was previously in an init method so I wonder if it just "accidentally" worked because the reachability callback was registered and the checks started a lot earlier.

I'm using NetInfo.isConnected but I'm starting to wonder how useful that is for an initial check.

**Comment by khiemnm** [comment]
I hope team dev will update fix fetch in version 0.29

**Comment by ryankask** [comment]
I've created https://github.com/facebook/react-native/issues/8469 which reflects what I wrote above. It may be something totally different to this issue.

**Comment by afhaque** [comment]
+1 Same issue as above. Running 0.29

**Comment by khiemnm** [comment]
in mean time, i think you should use version 0.27.

**Comment by alexanderniebuhr** [comment]
Still in 0.29

**Comment by roman01la** [comment]
In both RN 0.29 and 0.30 a callback passed into `NetInfo.addEventListener` is being called immediately.

**Comment by mrkhan2** [comment]
Still running into the issue....any solutions besides changing Allow arbitrary loads to YES?

I'm on React-native 0.28
React 15.3

I've tried combos of react-native 0.28-0.34 and react 15.1-15.3,  get the same no connection error every time.

**Comment by lucianomlima** [comment]
+1 same issue.

I'm on:

"apisauce": "^0.6.0",
"native-base": "^0.5.13",
"react": "15.3.2",

Testing with iOS 9.3 and 10.1 simulator with iPhone 4s, 5s, 6 and 7.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/ios-since-0280-no-network-connection-in-xcode-simulator
