### ISSUE TITLE
ListView with absolutely positioned items doesn't show full content

### ISSUE THREAD

**Issue by mt00** [facebook/react-native#8427]
Perhaps I'm missing something, but it seems something wrong when the ListView component with the absolutely positioned items.

Here's an example showing a simple listview with 4 rows, the last one I set `{position: 'absolute', left: 0, top: 1000, width: 100, height: 100}`

https://rnplay.org/apps/i08SuA

the scrollbar can't reach the right end of the listview, and I can't see the last row.

**Comment by cpruijsen** [comment]
I tried your sample code and notice a few things: 
- you're using the old syntax (`React.createClass` instead of `class ... extends Component`, `getInitialState` instead of `this.state = {}` etc.).
- it's a bit hard to notice if anything is missing as both images are fully displaying and the rest of the 'rows' are empty. Due to the size of the viewport you just have to swipe in order to see the bottom image fully.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/listview-with-absolutely-positioned-items-doesnt-show-full-content

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
