### ISSUE TITLE
Keyboard Issue

### ISSUE THREAD

**Issue by michaeljgilmore** [facebook/react-native#8432]
I'm a bit new but hope this will help others.  

In previous versions of React Native I could utilize the keyboard aware scrollview component.  When upgraded to versions beyond 25 that is now causing an error that creates this alert in the debugger.  
view <RCTShadowView , RCTTextField is not a descendant of RCTShadowView.  (Obviously there is a longer amount of output).  From researching, it appears there may be a pull request to fix it.
One request I'd like to make is if we could get better documentation and examples of how to implemented the Keyboard.addListener('keyboardWillShow",func) usage.  It would be great to get any assistance as I really do want to use the newer version of React Native for my project.

Thank you.

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-9** [comment]
Hey @michaeljgilmore and thanks for posting this! @DanielMSchmidt tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
