### ISSUE TITLE
Document Android APK composition with more details

### ISSUE THREAD

**Issue by clarle** [facebook/react-native#8435]
From the [React Native Community](https://www.facebook.com/groups/react.native.community/permalink/788883451247235):

It's commonly asked why including the React Native for Android library increases APK size by 6-7 MB.  

It'd be good to have more details on:
- Why this is the case
- How to make it smaller by separating out x86 and ARM builds

Thanks so much @hramos!

**Comment by hramos** [comment]
Thank you for opening the issue!

**Comment by oargaruna** [comment]
We have seen that even after separating the x86 and ARM builds, the APK size increases by ~3.5MB. Most of this is due to the `.so` files added as libs (with `libjsc.so` being the largest contributor). What steps can be taken by developers to reduce this bump in APK size? ProGuard works only on the Java files, so what can we do about the `.so` files?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/document-android-apk-composition-with-more-details
