### ISSUE TITLE
Native view animations stopped working in RN 0.25 / iOS

### ISSUE THREAD

**Issue by jnak** [facebook/react-native#8459]
Hello,

I've just noticed that native views that had native animations (i.e. the native view animate native subviews) stopped working. I ran a git bisect and the regression seems to have started with 0.25.

Here are the repro (just run npm install && react-native run-ios):

1. 24.1 works:
https://github.com/jnak/rn-native-animation-repro/commit/d930151e7aa7e1376ad81b74e3ac782272676942

25.1 does NOT work:
https://github.com/jnak/rn-native-animation-repro/commit/2d94d048967d4bab6387dcd1d04c14fec55f6e2d

The only thing that differs is the react-native version. It seems that it is a major regression that screenshot based integration tests would have not caught. 

Can anyone confirm the repro on their machine?

Thx

**Comment by Flux159** [comment]
+1 I saw something similar when upgrading from 0.22 to 0.26

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/native-view-animations-stopped-working-in-rn-025-ios

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
