### ISSUE TITLE
console.error doesn't work on Android in v0.28

### ISSUE THREAD

**Issue by maikokuppe** [facebook/react-native#8473]
The red screen itself works, since I see it all the time when something doesn't work. But a manual call of `console.error` doesn't work. `console.warn` does work.

[working rnplay example](https://rnplay.org/apps/2nMs5Q)

**Comment by narychen** [comment]
I met this bug too.
console.warn doesn't have stack trace, so it is not as useful as console.error

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/consoleerror-doesnt-work-on-android-in-v028

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
