### ISSUE TITLE
EventEmitter #once is broken since upgrading to 0.27.2

### ISSUE THREAD

**Issue by erickreutz** [facebook/react-native#8477]
EventEmitter `#once` is not passing the correct arguments to the callback since updating to `0.27.2`

```javascript
events = new EventEmitter();

events.once('MY_EVENT', (...args) => {
  console.log("Args:", ...args);
  // Logs: 'Args:', 'MY_EVENT', [Function]
});

events.emit('MY_EVENT', 'one', 'two', 'three');
```
```javascript
events = new EventEmitter();

events.addListener('MY_EVENT', (...args) => {
  console.log("Args:", ...args);
  // Logs: 'Args:', 'one', 'two', 'three'
});

events.emit('MY_EVENT', 'one', 'two', 'three');
```

**Comment by satya164** [comment]
Can you send a PR to fix this?

**Comment by erickreutz** [comment]
Yes.

**Comment by erickreutz** [comment]
The problem is an arrow function does not bind its own arguments.

So this does not work: https://github.com/facebook/react-native/blob/0e8c3ff463420cc24f3bcc225cb9b0b76dd8eb3b/Libraries/EventEmitter/EventEmitter.js#L83

**Comment by erickreutz** [comment]
@satya164 done.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/eventemitter-once-is-broken-since-upgrading-to-0272

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
