### ISSUE TITLE
LinearGradient in ART for Android cant work, display black

### ISSUE THREAD

**Issue by safetydoor** [facebook/react-native#8506]
LinearGradient in ART for Android cant work, display black

**Comment by antoxi4** [comment]
This features are not implemented on Android yet)

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/lineargradient-in-art-for-android-cant-work-display-black

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (62/60 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter01.reliabledns.org ([199.96.156.50]:56043)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bzsux-0003w6-7H
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 22:13:00 +0000
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192] helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by filter01.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1bzsuv-0000MT-QN
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 15:12:58 -0700
Date: Thu, 27 Oct 2016 15:12:56 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1477606376;
	bh=oTzDSk0DJ/cDcDaw1bekQsRQtCtSB914EZiuYu6+WO8=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=jVXclKB90A6/+jqmehRUQdDnocobmcqFQSfEwgDXrxAzPEl1D5ABEwq04a9waofj2
	 7fk5Ip1LPhf9duLUdpZO9qMoWcRCSj5lckctaiP0hz+RO737Ad+eeh0Vy7MKjOFMNW
	 Wk0RbUcqlzc6kTvs0CwSRoI+t5FJSZGFBkv8XloY=
