### ISSUE TITLE
Android app Development real device error : Could not connect to development server

### ISSUE THREAD

**Issue by mustafakucuk** [facebook/react-native#8507]
Hi,
I'm react native with android app but real device is testing a problem

**Could not connect to development server**

# **[Image Show](http://prnt.sc/bn1lr7)**

**Comment by Ehesp** [comment]
Did you run the adb command like the error says?

**Comment by 281330** [comment]
Probably have to do adb reverse tcp:8080 tcp:8080

**Comment by douglasjunior** [comment]
I have the same problem. I'm using MacOSX El Capitan and Android Devices. 

Using `adb reverse` worked with my android 5.0+, but I can not run on devices 4.0, what can I do?

**Comment by cornedor** [comment]
On older devices you should set the IP to the packager in the dev settings menu. See https://facebook.github.io/react-native/docs/running-on-device-android.html

**Comment by gmagic10** [comment]
Before I run `adb reverse tcp:8081 tcp:8081`. I get the red screen telling me `http://localhostL8081/index.android.bundle?platform=android` could not connect to server.

But after I run the adb command. The red screen still tell me could not connect to server.
But disappear the `http://localhost` section.
And my packager actuall get the request and print the log in the console.
But the red screen still.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-app-development-real-device-error-could-not-connect-to-development-server

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
