### ISSUE TITLE
Accessing video files from CameraRoll on Android

### ISSUE THREAD

**Issue by cubbuk** [facebook/react-native#8511]
Is it possible to retrieve video files from `cameraRoll` on Android?. I see there is a groupTypes prop but it is not working for Android. I already asked a question on stackoverflow; but I couldn't get any answer. http://stackoverflow.com/questions/38104131/react-native-using-cameraroll

I tried setting the mimeTypes in fetch params as follows: mimeTypes: `["image/jpeg", "video/mp4", "video/mpeg"]` but it didn't work out either.

Am I missing something, I would appreciate any help.

Thanks

**Comment by cubbuk** [comment]
Seems like android version only checks images table from sqlite. I extended the current `cameraRoll` to also retrieve videos, its a bit dirty solution but it solves the problem for now. Here is the gist for that: https://gist.github.com/cubbuk/70e0841ec5e0ebfe80c6f747eb973216

**Comment by AndrewJack** [comment]
Looks like support for videos in the camera roll on Android was added in 0.29.0 https://github.com/facebook/react-native/commit/7357ccc37067133859c663f0b907c58801ac25c9

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/accessing-video-files-from-cameraroll-on-android

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
