### ISSUE TITLE
[iOS] Chinese and English can not be centered?

### ISSUE THREAD

**Issue by eggswift** [facebook/react-native#8522]
Why chinese and english can not be centered. Here is an example:
elements:
```
          <View style={styles.header_info_sub}>
                  <Text style={styles.header_info_sub_time}>刚刚</Text>
                  <Text style={styles.header_info_sub_from}>来自 aaa.com</Text>
          </View>
```
styles:
```
  header_info_sub: {
    flex: 0,
    flexDirection: 'row',
    alignItems: 'center',
  },
  header_info_sub_time: {
    fontSize: 12.0,
    color: 'orange',
  },
  header_info_sub_from: {
    fontSize: 12.0,
    marginLeft: 4.0,
    color: 'gray',
  },
```

effect:
![109da5ac-aafe-4603-81e7-b0bdfaf4dc36](https://cloud.githubusercontent.com/assets/15206466/16518784/5dbdbc9e-3fb7-11e6-9821-304488c43107.png)

I must add **paddingBottom: 1,**  to **header_info_sub_from** style to fix it. Why it can not be centered automatically?

**Comment by yueshuaijie** [comment]
If you want "来自" and "aaa.com" vertical aligned center, you should separate it into two `<Text>` component and use `alignItems:center` on parent component.

**Comment by eggswift** [comment]
@yueshuaijie What? I have done like this.  
```swift
header_info_sub: {
    flex: 0,
    flexDirection: 'row',
    alignItems: 'center',
  },
```

**Comment by yueshuaijie** [comment]
@eggswift 
Sorry, it seems I misunderstand. I thought you want make "来自" and "aaa.com" vertical center aligned. In fact you mean making "刚刚" and "来自 aaa.com" vertical center aligned :)

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/ios-chinese-and-english-can-not-be-centered

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by pannz** [comment]
that is the because of the font
use the default system font, Chinese character and English character even the Number are not in same alignment 
so when they in same line and same <Text /> components, the render result will not be centered!

You should found the FONT that the two kind of character render the same alignment
