### ISSUE TITLE
es6 transforms bug(Rest Params)

### ISSUE THREAD

**Issue by magicismight** [facebook/react-native#853]
```javascript
function push(array, ...items) {
    array.push(...items);
}
```
The code above will throw an SyntaxError
Unexpected keyword 'var'.Expected an opening '{' at the start of a function body.

But if I write rest params separately,they are just fine.

```javascript
function push(array, ...items) {
    array.push.apply(array, items);
}
```

OR

```javascript
function push(array) {
    var args = [].slice.call(arguments);
    array.push.call(...args );
}
```

**Comment by brentvatne** [comment]
So I ran this through the compiler and it gave me this:

```javascript
function push(array )var $__2; {for (var items=[],$__0=1,$__1=arguments.length;$__0<$__1;$__0++) items.push(arguments[$__0]);
  ($__2 = array).push.apply($__2, items);
}
```

You're right, this is an error and running in your browser shows that too. It looks like the var $__2; should be inside of the curly braces rather than before. That said, I believe this is actually an issue with `jstransform` and is very similar to this one: https://github.com/facebook/jstransform/issues/91 so I'm going to close this issue and move the discussion there and you can track the progress on that!

Thanks for the report :smile:
