### ISSUE TITLE
[iOS] TextInput will negate fontWeight with certain props

### ISSUE THREAD

**Issue by blakeandrewwood** [facebook/react-native#8533]
I'm encountering something weird with the styling of a TextInput component. Seems like it discards the fontWeight styling when certain props are set. Not sure if android has this problem.

Here fontWeight works:
```
<TextInput
  style={{
    flex: 1,
    alignSelf: 'stretch',
    fontFamily: 'Avenir',
    fontWeight: '800',
    fontSize: 14,
    color: 'black'
  }}
 maxLength={60}
 autoFocus={true}
 blurOnSubmit={true}
/>
```

Here it doesn't:
```
<TextInput
  style={{
    flex: 1,
    alignSelf: 'stretch',
    fontFamily: 'Avenir',
    fontWeight: '800',
    fontSize: 14,
    color: 'black'
  }}
 maxLength={60}
 autoFocus={true}
 blurOnSubmit={true}
 placeholder="Comment"
 placeholderTextColor="rgba(0, 0, 0, 0.7)"
 returnKeyType="done"
/>
```

**Comment by yueshuaijie** [comment]
Tested on latest master 2b1b8418f0f05a09c8a3bab3615d2d9aa23a8217, no problem, fontWeight still works.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/ios-textinput-will-negate-fontweight-with-certain-props

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
