### ISSUE TITLE
Missing `dispose` in module.hot

### ISSUE THREAD

**Issue by yonatanmn** [facebook/react-native#8558]
Hey, 
I'm not sure how you handle the hot-module-replacement, 
in normal [HMR with webpack](https://webpack.github.io/docs/hot-module-replacement.html) you get an object called `module`: 
`module: {exports: {...}, hot: {...}}`
and `hot` contains:
`hot: {accept, decline, dispose / addDisposeHandler, removeDisposeHandler, /*many more methods*/ }`

In React native you only get: 
`hot: {accept, acceptCallback}`

Specifically, what I need is `dispose` to correct HMR in [my framework](https://github.com/yonatanmn/Cartiv)

**Comment by satya164** [comment]
cc @martinbigio

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/missing-dispose-in-modulehot

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
