### ISSUE TITLE
Add possibility to subscribe a sequence enty animation complete

### ISSUE THREAD

**Issue by vaukalak** [facebook/react-native#8565]
Hello, it would be very handy if there been a possibility to subscribe an animation entry sequence. For example, we would like to to a fade-out => fade-in animation, and switch state when the view is invisible.
Here an example with scale animation:
```
Animated.sequence([
   Animated.timing(
      this.state.scale,
      {
         toValue: 0,
         duration: 300,
         onComplete: () => this.setState({someProp: 'new value'})
      }
   ),
   Animated.timing(
      this.state.scale,
      {
         toValue: 1,
         duration: 300
      }
   ),
]).start();
```

The feature is implemented with: https://github.com/facebook/react-native/pull/8494

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/add-possibility-to-subscribe-a-sequence-enty-animation-complete

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
