### ISSUE TITLE
Action sheet is not hiding if we are navigating from one page to another dynamically

### ISSUE THREAD

**Issue by tazmattaz** [facebook/react-native#8573]
I am working on app where we need push notifications. Let me explain the whole scenario:
1. I am on first page of app
2. There action sheet (or share sheet) is open (and app is in background)
3. I got push notification, when I clicked on that notification
4. My app will open and will redirect to second page dynamically without tap on screen
5. In this case action menu sheet should be close, but in this case it is remain open.

There should be some way if we can close it dynamically or if page is navigating it should be close automatically.

I am stuck into this and this is breaking my app. We need to fix this issue as soon as possible...
Thanks

**Comment by satya164** [comment]
You can emit an event when you navigate. The component with the action sheet can listen to these events and close the action sheet.

**Comment by satya164** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-4** [comment]
Closing this issue as @satya164 says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

**Comment by tazmattaz** [comment]
@satya164 please can you gimme an example of your answer? how can I implement this?

**Comment by tsemerad** [comment]
@satya164 I'm curious about this too - how can you programmatically close an ActionSheetIOS?

**Comment by AndrejGajdos** [comment]
+1
