### ISSUE TITLE
borderBottomLeftRadius et. al. produce blurry corners on iOS

### ISSUE THREAD

**Issue by joefocusrite** [facebook/react-native#8577]
It seems that when specifying some, but not all of borderBottomLeftRadius, borderBottomRightRadius, borderTopLeftRadius and borderTopRightRadius, you can end up with some strange effects in the other corners.

![screen shot 2016-07-05 at 17 06 32](https://cloud.githubusercontent.com/assets/3284312/16591321/4d7e0180-42d3-11e6-9c00-694dc3859deb.png)

See this [rnplay](https://rnplay.org/apps/TD8FzQ) or code snippet:

```
'use strict';

var React = require('react-native');
var {
  AppRegistry,
  StyleSheet,
  Text,
  View,
} = React;

var SampleApp = React.createClass({
  render: function() {
    return (
      <View style={styles.container}>
        <View style={styles.box} />
      </View>
    );
  }
});

var styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
  },
  box: {    
    borderWidth: 1,
    borderColor: 'black',

    width: 150,
    height: 150,

    borderBottomLeftRadius: 10,
  },
});

AppRegistry.registerComponent('SampleApp', () => SampleApp);
```

react-native 0.28.0

Seems to occur on iOS, but not on Android

Am I doing something wrong, or is this a bug?

**Comment by janicduplessis** [comment]
Looks like a bug, I actually hit this problem too.

**Comment by rclai** [comment]
For me this happens on a real device but doesn't happen on the simulator.

**Comment by manicakes** [comment]
I can't reproduce this (tried Simulator and a couple real devices).

**Comment by janicduplessis** [comment]
Seems to only happen on non retina devices, I can reproduce it using the original code sample on an iPod Touch. I can also reproduce the bug by setting the scale of the simulator to 50%.

**Comment by mrpp01** [comment]
I tested this, and it only appears when the screen's resolution is too low. Is this significant? I think most device from now on will have high resolution, so this wouldn't be an issue.

**Comment by fiattt** [comment]
for me happen on real device: iphone 6 plus

**Comment by frontendloader** [comment]
Merge #10823 and #11897 into this one?

Minimal reproduction on RNPlay: https://rnplay.org/apps/Cl4tGg

**Comment by xeonwell** [comment]
happen on react-native 0.42.3 & iphone6 plus

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
