### ISSUE TITLE
[ScrollView] Scrolling in both directions (horizontally and vertically) stops working on 0.28.0

### ISSUE THREAD

**Issue by neiker** [facebook/react-native#8579]
Hi!

My app needs to scroll both, horizontally and vertically, basically its a big canvas where you can draw, put objects, move them, etc. I was using `horizontal={true}` but now I upgrade to `0.28.0` and it doesn't work anymore. It just scrolls horizontally (makes sense, I think) but it doesn't scroll vertically anymore.

**Comment by neiker** [comment]
This still broken on 0.29.0 :(

**Comment by johnnyhalife** [comment]
:+1:

**Comment by carmon** [comment]
+1

**Comment by danielaconsti** [comment]
+1

**Comment by barbatus** [comment]
this probably related to https://github.com/facebook/react-native/issues/8369

**Comment by neiker** [comment]
Yes! Thanks!
Setting the `contentContainerStyle` with a fixed size works in my case. But I don't think it'll work if you don't know the size of the content.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/scrollview-scrolling-in-both-directions-horizontally-and-vertically-stops-working-on-0280

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by sumanlamsal** [comment]
solved
here is currently not a direct way to achieve this. If setting contentContainerStyle prop is not a problem for you, you can go that way. If it is, you can always use 2 nested ScrollViews.<ScrollView>    <ScrollView horizontal={true}>        {this.buildContent()}    </ScrollView> </ScrollView>
-- | --
