### ISSUE TITLE
Linking.addEventListener passes the url and not an Object e.g. {'url':'example://whatever'}  for Android

### ISSUE THREAD

**Issue by willchu** [facebook/react-native#8583]
On Android, the url is passed to the callback for Linking.addEventListener

On iOS the behavior is as expected, an object containing the url is passed to the callback for Linking.addEventListener. 

This is seen on version 0.28

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/linkingaddeventlistener-passes-the-url-and-not-an-object-eg-urlexamplewhatever-for-android

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
