### ISSUE TITLE
AsyncStorage cannot work on synchronous way.

### ISSUE THREAD

**Issue by xinggg22** [facebook/react-native#8589]
```javascript
async function _localStorage() {
	await AsyncStorage.getItem("g-value").then(v => {
		if (v) {
			global.gValue = v;
		} else {
			global.gValue = 'hello world!';
			AsyncStorage.setItem("g-value", global.gValue);
		}
	});
}
_localStorage().done();

alert(global.gValue); //get a undefined value.

```

**Comment by satya164** [comment]
It's called `AsyncStorage` because it's asynchronous. You cannot use it synchronously.

@facebook-github-bot answered

**Comment by janicduplessis** [comment]
You can only get the value from inside the async function, make sure all the code that depend on that global is executed inside the async function.
``` js
async function _localStorage() {
    const v = await AsyncStorage.getItem("g-value");
    if (v) {
        global.gValue = v;
    } else {
        global.gValue = 'hello world!';
        AsyncStorage.setItem("g-value", global.gValue);
    }

    // Continue here...
    alert(global.gValue);
}
_localStorage();
```

**Comment by max-mykhailenko** [comment]
How I can use AsyncStorage as redux InitialState of my application?

**Comment by janicduplessis** [comment]
You can dispatch an action that restores the application state after you get it from AsyncStorage and have your app render nothing until it is loaded. You can also use something like https://github.com/rt2zz/redux-persist that will take care of saving / restoring state for you.

**Comment by satya164** [comment]
@max-mykhailenko

I do it this way,
1. dispatch an action `LOAD_SAVED_DATA_REQUEST`.
2. load the data from `AsyncStorage` when I receive this action
3. dispatch an action `LOAD_SAVED_DATA` with the payload as the new state when loading succeeds, or `LOAD_SAVED_DATA_FAILED` when loading fails
4. when I get `LOAD_SAVED_DATA` action with new state, I replace the current state with the new state in my reducer

You can also have a state `isRestoringData` or something to indicate if you're loading the data, so that you can show a splash screen or spinner, and then set it to `false` when you get `LOAD_SAVED_DATA`. Usually it is fast enough that I just return null in my component instead of showing a spinner.
