### ISSUE TITLE
ScrollViewClass must be not undefined

### ISSUE THREAD

**Issue by gosherry** [facebook/react-native#8594]
Sometimes, when i run my app on iOS-Simulator, It will throw 'SrollViewClass must be not undefined'。
**My code**:
`			<ScrollView style={ styles.container }>
				<View style={ styles.menuContainer }>
					{ topMenu }
				</View>
				<View style={ styles.menuContainer }>
					{ resMenu }
				</View>
				<View style={ styles.menuContainer }>
					{ walletMenu }
				</View>
				<View style={ styles.menuContainer }>
					{ moreMenu }
				</View>
			</ScrollView>`

***Exception appears in the 536 line of then ScrollView.js file.(ReactNative -- ScrollView source code)***
`    invariant(
      ScrollViewClass !== undefined,
      'ScrollViewClass must not be undefined'
    );`

Looks very simple code，but can not be a good run. My project framework is builds with redux.
But when i write the code in then index.ios.js with ScrollView, it will works very well. I don't know where the problem is. Looking forward to your answer. Thanks.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/scrollviewclass-must-be-not-undefined

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
