### ISSUE TITLE
Real device width and height

### ISSUE THREAD

**Issue by gotikesD** [facebook/react-native#8597]
I have the next problem - when I build my react-native app into apk file, and then install app into the device, I get wrong data display(something like under a magnifying glass). After a few hours of working, I decide to do alert from demension(of course I did rebuild of apk ) my device height and width. And here is the question! - On my Galaxy S6 with resolution 2000+ x 1500+ I have got 640 x 480! 
Also I tried to find dependence on PixelRatio and i got it!

I have run Htc Evo from Genymotion, and get next results : 720x1280 dpi 160 (PixelRatio - 1.0) works great! Dimension return 720 and 1280 , 720x1280 dpi 240 (PixelRatio - 1.5) works wrong! Dimension return 480 and ~850 , 720x1280 dpi 320 (PixelRatio - 2.0) works wrong! Dimension return 480 x 640

I have an idea, that the dimensions is not a pixel-dimension(maybe some diff values), but I was wrong, cause when I insert Image(own height and size 30x30 px), toogle inspector shows me that my Image component is 30x30!

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/real-device-width-and-height

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
