### ISSUE TITLE
Property request not found on object of type 'RCTImageSource *'

### ISSUE THREAD

**Issue by xujianfei** [facebook/react-native#8598]
_loading = [_bridge.imageLoader loadImageWithURLRequest:source.request

Property request not found on object of type 'RCTImageSource *'?

**Comment by gre** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-7** [comment]
Closing this issue as @gre says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.
