### ISSUE TITLE
[NavigationExperimental] NavigationExperimental.Header title fades incorrectly in pop transition animation

### ISSUE THREAD

**Issue by nwlieb** [facebook/react-native#8618]
Navigation Experimental header animations are rough around the edges. An easy example to reproduce in UIExplorer under ios:
1. Go to the Navigation (Experimental) API example
2. Go to CardStack + Header + Tabs Example
3. Push Route
4. By dragging from the left to pop the card, notice that the title is being duplicated and fading from the left in both opacity and position.
5. Once the transition is completed, the correct title pops into the place of the old title.

Alternatively:
4. Press the back arrow and notice that the current title is suddenly replaced by the title belonging to the card below. Afterwards the animation completes as expected.

Push animations also have similar quirks.

Another issue that is maybe unrelated: when using the 'dragging from left' way to pop, if you change the color of the header between transitions, say from red header then popping to a blue header underneath, the red header does not slide and is present until the very last frame of animation. Then the red header abruptly switches to the blue header below.

**Comment by mmmulani** [comment]
this seems like a regression, it doesn't repro here: http://www.reactnative.com/uiexplorer/

**Comment by mmmulani** [comment]
I was able to solve this by making sure my renderTitleComponent, etc is called with new props, not the props passed into my renderHeader method, e.g.

```
<NavigationHeader
        {...props}
        renderTitleComponent={(p) => this.renderHeaderTitle(p)}
        onNavigateBack={() => this.navigate({ type: 'pop' })}
        renderRightComponent={(p) => this.renderHeaderRightButton(p)}
      />
```

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/navigationexperimental-navigationexperimentalheader-title-fades-incorrectly-in-pop-transition-animation

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
