### ISSUE TITLE
[iOS] DatePickerIOS has no 24 hour prop

### ISSUE THREAD

**Issue by mangogogos** [facebook/react-native#8620]
As best I can tell there's no way to use the iOS DatePicker component with 24-hour time. This is an option for the Android TimePickerAndroid API so does anyone know if support for this is planned or possible?

**Comment by mlumbroso** [comment]
Interested in this too!

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/ios-datepickerios-has-no-24-hour-prop

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by hegelstad** [comment]
This should be reopened. It's a pressing issue thinking of how far React Native has come since this issue was closed.
