### ISSUE TITLE
App Name change doesn't reflect when running by "react-native run-ios"

### ISSUE THREAD

**Issue by chiraggshah** [facebook/react-native#8633]
I wanted to rename my app name which gets displayed in the AppDrawer/HomeScreen from "Myapp" to "MyApp". For which I made the following changes:

For Android: 

- Changed the value in `android/app/src/main/res/values/strings.xml`
- Changed the value in `android/settings.gradle`

For iOS:
I added a new key in `info.plist` called `Bundle display name` with the value "MyApp"

The changes work for android when I run `react-native run-android`
But not when I run `react-native run-ios`. It only works when I build and run from xcode, but not from the terminal.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/app-name-change-doesnt-reflect-when-running-by-react-native-run-ios

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
