### ISSUE TITLE
Make the Getting Started solution less "hacky"

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/react-native#8658]
We have a great start on the updated Getting Started for React Native, but it is possible to clean things up a bit infra-wise as well. Not hi-pri right now, but keeping on our radar.

Some internal comments in D3265822 too.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/make-the-getting-started-solution-less-hacky

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
