### ISSUE TITLE
Network Request Failure Android on SSL only

### ISSUE THREAD

**Issue by martinalderson** [facebook/react-native#8659]
Having a very odd problem with TypeError: Network request failed from fetch on android.

1) Using http with no tls works 
2) Using https with fiddler or charles proxy works fine (it resigns the request).
3) Using https with cloudflare does not work for one rest call only. The rest of the rest calls on the same hostname and server work.

This also works fine on the iOS version of the same app and the Android browser can navigate to the site.

The fact that it starts working as soon as you inspect SSL traffic with Charles or Fiddler is making this difficult for us to debug.

**Comment by ide** [comment]
It's probably an issue with HTTP/2. Until we can pull in OkHttp 3.3.1, you should either turn off HTTP/2 on your servers or if you can't (in the case of CloudFlare) there might be some way to disable HTTP/2 support with a bit of Java code - that's the direction I'd look in.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/network-request-failure-android-on-ssl-only

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
