### ISSUE TITLE
Module RCTLog is not a registered callable module when set dev mode to false on 0.29.0

### ISSUE THREAD

**Issue by Fanghao** [facebook/react-native#8663]
encounter this red box error on iOS if set dev to false in `AppDelegate.m` of UIExplorer sample project.

env: React Native 0.29.0 + iphone 6 (9.3) simulator and device.

![simulator screen shot jul 8 2016 12 59 10 pm](https://cloud.githubusercontent.com/assets/1245211/16699929/f2ec62d0-450b-11e6-9b6c-3f9692c265d0.png)

**Comment by ios122** [comment]
I solve this tmp. in index.ios.js, add

`
var RCTLog = require('RCTLog');
`

**Comment by pavlelekic** [comment]
+1

**Comment by getnashty** [comment]
+1

**Comment by abdallahm** [comment]
+1

**Comment by echocsg** [comment]
+1

**Comment by glassysky** [comment]
+1

**Comment by ytqiu** [comment]
same error to me. finally i found i had build my app in Debug mode working with --dev false react native bundle. 
the following code tells us all the things:
`- (void)logMessage:(NSString *)message level:(NSString *)level
{
  if (RCT_DEBUG && [_javaScriptExecutor isValid]) {
    [self enqueueJSCall:@"RCTLog.logIfNoNativeHook"
                   args:@[level, message]];
  }
}`

**Comment by Amurmurmur** [comment]
I added: var RCTLog = require('RCTLog');

And with --dev false, I get the following, been struggling for couple of days now I hope you can help guys :/
![simulator screen shot 20 aug 2016 23 59 00](https://cloud.githubusercontent.com/assets/8608333/17834317/3f6adc34-6732-11e6-88dd-200998895785.png)

**Comment by zccan** [comment]
+1

**Comment by alloy** [comment]
This happens when:

* passing the `--dev false` option to the packager, which seems to exclude the `RCTLog` module
* and building/running an app with the Xcode `Debug` configuration, which (by default) defines the `DEBUG` macro
* this in turn [enables the `RCT_DEBUG` macro](https://github.com/facebook/react-native/blob/46e47aaecd79df529b27a68f45f3db2ba9fcf9f8/React/Base/RCTDefines.h#L28-L29)
* which finally leads to [RN expecting the `RCTLog` module to be available](https://github.com/facebook/react-native/blob/46e47aaecd79df529b27a68f45f3db2ba9fcf9f8/React/Base/RCTBatchedBridge.m#L753)

Seeing as all of this happens at compile time _and_ it’s a bit of an edge-case I’m not sure if there’s a simple/good way to detect this in the codebase.

I suggest that, if you do in fact want to test code that is packaged with `--dev false`, you build your app with the `Release` configuration instead. From Xcode, hold down the alt key while clicking the run button and select the `Release` configuration (remember to set it back afterwards).

@ide @javache Any other thoughts?

**Comment by ide** [comment]
I think we should make it so that you can test dev JS with Debug native code. It's a pretty reasonable thing to want to do, especially if you encounter bugs that are only in dev JS and want to debug from the native side.

**Comment by alloy** [comment]
@ide by `dev JS`, did you mean `production JS` ? Otherwise I’m confused.

**Comment by ide** [comment]
Sorry, yes, I meant production / `dev=false` JS.

**Comment by javache** [comment]
If this is really a common issue, we should revert https://github.com/facebook/react-native/commit/5db4aad347ad8aec754e227e9afd3f5b4922c120 and always provide RCTLog.

cc @lexs

**Comment by alloy** [comment]
Yeah I think it's common enough to warrant that and the RCTLog source seems small enough.

**Comment by javache** [comment]
Reverted: https://github.com/facebook/react-native/commit/4b8688926b93a5b41f191cdba78f0f4335a62111

**Comment by luyuan11233** [comment]
Yeah~I have the same question,and i add "let RCTLog = require('RCTLog')" in the code,hope to solve this issue.

**Comment by JakeNolan** [comment]
Hello All, 

I still seem to be seeing this issue "Module RCTLog is not a registered callable module" message.

I attempted to reach out with expo here: https://github.com/expo/expo/issues/3 but I haven't gotten any feedback yet so I am echoing myself here in search of assistance because it seems very closely related.

I have tried to add this "var RCTLog = require('RCTLog');" into the index.ios.js file.

My problem/confusion with that is is that I initially started with expo and then detached to expokit and no longer have the index.ios.js file to my knowledge. And when I try to throw it into App.js , which is what I believe to be the equivalent,  I get an error telling me that it should be listed in the project's dependencies. However, I don't think thats what needs done bc it's not something I can get from npm, I don't think.

Other related details: I just detached to expokit to try and implement some firebase dynamic link functionality. I have tried the suggestion of building from debug mode in Xcode with development turned on and off (for the packager) with no success and I have tried building from release mode in Xcode with development turned on and off (for the packager) with no success.  I am attempting to use the following versions of things:

Xcode Version 9.2 (9C40b)

"expo": "22.0.0",
"react": "16.0.0-alpha.12",
"react-native": "https://github.com/expo/react-native/archive/sdk-22.0.0.tar.gz",
(though I have tried 16.0.0-beta.5 per the expo version matching docs also, with the same results)

I have been following the developing with expokit documentation to a T, in my mind, but as I mentioned above when I try to run the xworkspace file in xcode I see a screen saying "There was a problem running the app with the RCTLog is not a registered callable module" message at the bottom and filling up the output window in Xcode.

I would much appreciate anyone to point out the errors in my thinking or assumptions that I have made. Any possible alternative things to try doing to get me past this point would also be appreciated. I really would just like to be able to build and deploy successfully from Xcode.

Don't hesitate to ask me to shed light on any areas that I have been unclear about or ask for additional information about my scenario. Any time of day or night would be fine I am very anxious to get beyond this, I will respond back as soon as possible.
