### ISSUE TITLE
module 0 is not a regeisterd callback module

### ISSUE THREAD

**Issue by AndrewJikun** [facebook/react-native#8667]
i just upgraded my RN from 0.20 to 0.27.2 and implemented the react and react native import isssues and then i ran IOS it worked fine. but when runnning android it said module 0 is not a regeisterd callback module。

**Comment by stoffern** [comment]
@AndrewJikun I have had the same issue, but it is not a error in react-native as i got it resolved.

Remember to always use:
`import React, {Component, PropTypes} from 'react'` NOT `react-native` this is removed in `0.26`

**Comment by AndrewJikun** [comment]
@stoffern , I have changed to :import React, {Component, PropTypes} from 'react' , or else it could not be run in IOS. the issue is it worked in IOS but not worked in android

**Comment by stoffern** [comment]
@AndrewJikun ok. Then try the following:
```
- remove node_modules
- npm clean cache
- npm i
- start up Android Studio and klick: Build -> Rebuild
```

**Comment by fab1an** [comment]
Also try: `./node_modules/react-native/packager/packager.sh start --reset-cache`

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/module-0-is-not-a-regeisterd-callback-module

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
