### ISSUE TITLE
Adding Support For RTL direction (flexDirection : 'row-reverse')

### ISSUE THREAD

**Issue by cadr-sa** [facebook/react-native#8682]
Hello , 

I've made app and it must support English and Arabic language. In Arabic language every thing should be from Right To Left directions. I was able to do many tricks to make this request except not able to find solution for Flex Box

I think it must to add support for flexDirection : 'row-reverse' to fix issue .

**Comment by phil-allcock** [comment]
Looks like this was added in 0.29
https://github.com/facebook/react-native/commit/d43e0db81e86d4d03638cd17034086717fe715a3

**Comment by cadr-sa** [comment]
I just upgraded the react and it's working great .. thank you

**Comment by cadr-sa** [comment]
When I use flexDirection : 'row-reverse' in main view.  any sub view with style alignItems:'flex-end' .. should go to the left of main view

currently will go to the right of main view

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/adding-support-for-rtl-direction-flexdirection-row-reverse

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by DanGDroid** [comment]
any solutions for horizontal flatlist in rtl?
