### ISSUE TITLE
Firebase File Storage Doesn't Work w/React Native

### ISSUE THREAD

**Issue by aaronksaunders** [facebook/react-native#8684]
I have also posted the issue with Firebase, but I believe this is related to how POST is being done in the react-native code

- Provide a **minimal code snippet** / [rnplay](https://rnplay.org/) example that reproduces the bug.
See Issues Here - https://github.com/davideast/firebase-react-native-sample/issues/5
See working version here with plain react.. - https://jsfiddle.net/Aaronksaunders/69z2wepo/48546/
- Provide **screenshots** where appropriate
- What's the **version** of React Native you're using?
```
react-native-cli: 1.0.0
react-native: 0.29.0
```
- [ YES ] Does this occur on iOS, Android or both?
- [ MAC ] Are you using Mac, Linux or Windows?

**Comment by JarmoKukkola** [comment]
Firebase blog post states that uploads to storage are not working.

https://goo.gl/7GLV5h

I wonder if there is some way to fix this? Maybe native code could be used.

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-0** [comment]
Hey @aaronksaunders and thanks for posting this! @DanielMSchmidt tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by aaronksaunders** [comment]
this is not a stack overflow issue... it is an issue because react-native doesn't support Blob and File @DanielMSchmidt

**Comment by ide** [comment]
Reopening since supporting Blob and File eventually might make sense. We should take a closer look at the APIs and decided if we want to implement them.

Just to set expectations though, the reality is that React Native is not a browser and you should use a web view if using browser APIs is one of your top priorities. And similarly, if supporting React Native is important to Google then it's best if they dedicate some time to supporting RN with Firebase.

**Comment by shirleycharlin** [comment]
I really hope that this would work before my scholarship interview.

**Comment by lacker** [comment]
Hey, this issue is stale, and the goal of issues is to use them for bugs rather than feature requests anyway. I think this would be better off either on product pains - phrased as "Add Support for X" as a feature request - or go to stack overflow if you're curious to find a workaround. I am going to close this issue but if folks have one of the above two ways of interpreting I encourage people to follow up elsewhere.
