### ISSUE TITLE
html break tag breaks

### ISSUE THREAD

**Issue by sourcesoft** [facebook/react-native#8685]
Not sure about older versions of react-native but now if I add 
`
<br />
`
 red screen:
Expected a component class, got [object Object].

tested on ubuntu and mac. I can do this in react already. However I can use {"\n"} in <Text/>.

**Comment by fab1an** [comment]
I don't think `<br/>` was ever support in RN.

**Comment by satya164** [comment]
@facebook-github-bot stackoverflow

**Comment by satya164** [comment]
React Native doesn't have 
In future, please post questions on stackoverflow.

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-0** [comment]
Hey @sourcesoft and thanks for posting this! @DanielMSchmidt tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
