### ISSUE TITLE
[iOS] RCTUIManager error: Adding a root view controller as a child view controller

### ISSUE THREAD

**Issue by aksonov** [facebook/react-native#8688]
I'm using custom iOS native module, similar to iOS Tab Bar (RCTTabBar) but custom transitions. With 0.29 i've started getting exception above (screenshot attached). My code works well with RN 0.28 and earlier versions, what was changed within 0.29?

![simulator screen shot 11 jul 2016 12 03 24](https://cloud.githubusercontent.com/assets/1321329/16727636/57f93c4a-4762-11e6-9c99-0d6e3f15dc3c.png)

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/ios-rctuimanager-error-adding-a-root-view-controller-as-a-child-view-controller

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
