### ISSUE TITLE
HMR not working on Linux Ubuntu 14.14

### ISSUE THREAD

**Issue by lancemao** [facebook/react-native#8690]
it works fine on Mac, however, with the same code both client and server, HMR seems not working on my Linux server. here is how I set it up:
1. on Linux, create package.json which contains the standard sample code:
{
  "name": "AwesomeProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "react": "15.2.1",
    "react-native": "0.29.0"
  }
}
2. after npm install, start the server by: node node_modules/react-native/local-cli/cli.js start or npm start
3. Enable Hot Reloading
4. on iOS client, modify the url host and point to my linux server. and I found

a. Reload works (although 1/50 I see red error dialog)
b. in RCTSRWebSocket.m I place a break point at:- (void)didConnect and it was hit at the moment app starts, which looks really promising
c. use vim to modify index.ios.js on my linux server and hit :wq

and there you go, nothing happened. 

Note on Mac OS, same setup, I can receive didReceiveMessage from websocket. I doubt it might be watchman issue, but not really sure. 

Final note, same behavior for both simulator and device

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/hmr-not-working-on-linux-ubuntu-1414

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
