### ISSUE TITLE
Reload often leads to red screen

### ISSUE THREAD

**Issue by lancemao** [facebook/react-native#8692]
I know this sounds a little picky but whether server is at localhost or on a remote machine, 1 out of 50 times reload will leads me to a red screen as below. note I didn't do any changes on js, I simply keep reloading. I'm trying hard to persuade my organization to start using RN, so I really want these little issues be resolved since it leads to worries if one is in serious business
![simulator screen shot jul 11 2016 8 31 58 pm](https://cloud.githubusercontent.com/assets/5020396/16730530/14c3efd0-47a6-11e6-86c2-0e6d9f834c4f.png)

**Comment by Isakdl** [comment]
To me it sounds like you have a bad network connection, personally I never see these screens unless I have entered the wrong IP-address.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/reload-often-leads-to-red-screen

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
