### ISSUE TITLE
[Inspector] Inspector not updated with HMR

### ISSUE THREAD

**Issue by stoffern** [facebook/react-native#8707]
When using Inspector with HMR, the Inspector is not updated.
After a HMR update the Inspector will crash if used.

RN: 0.29

cc @frantic

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/inspector-inspector-not-updated-with-hmr

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
