### ISSUE TITLE
Error while updating property 'lineHeight' in shadow node of type:RCTText

### ISSUE THREAD

**Issue by yanru** [facebook/react-native#8729]
This react native bug will show in some Android devices:
Error while updating property 'lineHeight' in shadow node of type:RCTText.
If the Text style like this: {lineHeight:30.5} ,the value is float,then android devices will be red screen.
The lineHeight must be int in android? But the same value in ios devices  is normal.

**Comment by SudoPlz** [comment]
Closely related to my issue here https://github.com/facebook/react-native/issues/7877, I just convert the float to an integer and the error is gone for me.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/error-while-updating-property-lineheight-in-shadow-node-of-typercttext

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
