### ISSUE TITLE
Android: Iterators generated while doing nothing

### ISSUE THREAD

**Issue by fab1an** [facebook/react-native#8742]
I noticed that, while doing nothing at all with my app, there are still objects being allocated, namely `HashMap$EntryIterators` in [`Timing.java`](https://github.com/facebook/react-native/blob/ed4db631faf0091a92179e9fd629ce06e4704d1e/ReactAndroid/src/main/java/com/facebook/react/modules/core/Timing.java#L99).

These are two seconds or so of running the app. I know that small objects don't cost much, but given that we're on mobile here and Dalvik/ART is still not the JVM, I ask myself if those allocations could be avoided.

![screen shot 2016-07-13 at 12 25 02](https://cloud.githubusercontent.com/assets/55547/16803891/39544944-4909-11e6-8bfe-7029f2553485.png)

Android 5.1 / RN 0.29 / Mac

**Comment by fab1an** [comment]
I read more about this, there's no more memory-efficient way of traversing a `HashMap` and the impact of these iterators is very small. A remaining question though: Is it necessary to loop at all if "nothing" happens?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-iterators-generated-while-doing-nothing

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
