### ISSUE TITLE
[android] ToolbarAndroid touchable children style not working properly

### ISSUE THREAD

**Issue by erickreutz** [facebook/react-native#8760]
As we can't customize the action color in `ToolbarAndroid` dynamically I'm trying to add my own but I can't seem to style the children properly. Is this incorrect behavior? Doesn't seem to honor the flex properties and the touchable is all out of whack

https://rnplay.org/apps/CpWXBw

![image](https://cloud.githubusercontent.com/assets/59875/16822796/f5a4b3fe-4913-11e6-8e1f-f85040c2ef65.png)

```javascript
'use strict';

var React = require('react-native');
var {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  ToolbarAndroid,
  Navigator,
  TouchableOpacity
} = React;

var SampleApp = React.createClass({
  render: function() {
    return (
      <View style={styles.container}>
        <ToolbarAndroid title={"Lugg"} style={styles.toolbar}/>
      
      	<ToolbarAndroid
      		title={"Lugg"}
      		style={[styles.toolbar]}>
      		<View style={styles.toolbarInner}>
      		  <Text style={{ backgroundColor: 'yellow' }}>A Button</Text>
      		</View>
      	</ToolbarAndroid>
      
         <ToolbarAndroid
      		title={"Lugg"}
      		style={[styles.toolbar]}>
      		<View style={styles.toolbarInner}>
      		  <TouchableOpacity style={{ backgroundColor: 'green' }}>
	            <Text style={{ backgroundColor: 'yellow' }}>A Button</Text>
     	          </TouchableOpacity>
      		</View>
      	</ToolbarAndroid>
      </View>
    );
  }
});

var styles = StyleSheet.create({
	toolbar: {
    backgroundColor: 'grey',
    height: Navigator.NavigationBar.Styles.General.NavBarHeight,
    marginBottom: 16
  },
  toolbarInner: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end'
  }
});

AppRegistry.registerComponent('SampleApp', () => SampleApp);
```

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-toolbarandroid-touchable-children-style-not-working-properly

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
