### ISSUE TITLE
The purpose of the Picker component [Android]

### ISSUE THREAD

**Issue by sampurcell93** [facebook/react-native#8763]
Hi there - the dropdown Picker component seems very confusing to me, especially in the Android context. It doesn't at all behave the way I need it to, which means that either I should seek out another component, or figure out how to use it correctly. There are two cases I see for it, but right now it only satisfies one.

In the first case, the picker toggles something - at any given time, a value must be selected. Opening the picker and tapping the currently selected value should do nothing. This is the case that the current Picker satisfies.

In the second case, the picker is simple a menu of options, and any one can be selected, repeatedly if need be. Basically, the behavior of the overflow action menu in Android. Right now, I have been totally unable to get the picker to work like this.

So my question is, if I want overflow-menu-like behavior, what should I do (do I need to write my own native component for this)? I need custom toolbar layouts, so using the built in ToolbarAndroid isn't an option. 

I have only found one issue that discussed this briefly but I'm interested to hear what others think of this.

Thanks!

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/the-purpose-of-the-picker-component-android

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
