### ISSUE TITLE
The development server returned response error code:404

### ISSUE THREAD

**Issue by sundeepkvkl** [facebook/react-native#8769]
![react error](https://cloud.githubusercontent.com/assets/2428297/16830125/970ff91e-49ba-11e6-9d4d-957ab8fe6631.png)

An error occured while running the RCTWebRTCDemo_master for android. Can anybody suggest how to rectify this error? 

I am setting the host URL and port in the following screen.

![react-error2](https://cloud.githubusercontent.com/assets/2428297/16830222/3cbb474c-49bb-11e6-9d86-aad5d413320e.png)

Please suggest an answer as soon as possible

Thanks

**Comment by charpeni** [comment]
It seems a misunderstanding rather than a issue with React Native itself.

Can you report yourself to concerned repositories ? https://github.com/oney/react-native-webrtc & https://github.com/oney/RCTWebRTCDemo.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/the-development-server-returned-response-error-code404

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
