### ISSUE TITLE
Solve flow issues on v0.29.1

### ISSUE THREAD

**Issue by mhollweck** [facebook/react-native#8773]
When I run flow on v0.29.1 I get many errors. This happened to me with a few other RN versions now as well. Can you make sure to check flow before pushing to master? It's pain 

That may happen to me because I'm using the newest flow version (0.28.0) and not the recommended version(0.25.0 as seen in .flowconfig). Can you please check that as well?

Thanks!

**Comment by satya164** [comment]
@mhollweck It would be great if you can send a PR to fix flow issues.

**Comment by dozoisch** [comment]
@mhollweck If you do a fresh react-native init with rn@0.29 you should see flow@0.28.0 as recommended version in flowconfig.

**Comment by jawang35** [comment]
I'm getting a lot of flow errors on RN@v0.29.1 with flow@0.28.0 as well and I changed the version in the flowconfig to 0.28.0. The errors disappear if I use 0.27.0 and change the flowconfig to match that version.

**Comment by frostney** [comment]
I ran into the same problem and @jawang35's workaround with using Flow 0.27 worked for me as well.
As far as I can tell some of the flow errors are happening because of the updates to unions and intersections that have been implemented with Flow 0.28 (https://flowtype.org/blog/2016/07/01/New-Unions-Intersections.html). The definitions in `NavigationExperimental` in RN 0.29.x don't cater to that. That being said, I've noticed that the flow errors related to unions are solved in `master`.

**Comment by ide** [comment]
The unit tests do run Flow, so if the Flow checks fail on master we'll see red X's right away.

**Comment by fantattitude** [comment]
React-Native `0.30.0` have `^0.27.0` in its `.flowconfig` so I guess somebody realized there was a problem ?

**Comment by hramos** [comment]
Seems like this can be closed now, ping me if you believe otherwise.
