### ISSUE TITLE
React Native doc doesn't load the correct codes

### ISSUE THREAD

**Issue by nicnocquee** [facebook/react-native#8779]
Browser: Safari (9.1.1)
OS: OSX El Capitan 10.11.5

The editable sample code in some pages in the doc doesn't load the correct code after the first try. 

Steps to reproduce:

1. Click on [docs](http://facebook.github.io/react-native/docs/getting-started.html) page.
2. Click [TextInput](http://facebook.github.io/react-native/docs/textinput.html) on the left side bar under Components.
3. Click [Image](http://facebook.github.io/react-native/docs/image.html) on the left side bar under Components.

Expected:

The code should show how to use Image component.

Reality:

It shows TextInput component's sample code.

Video preview: [https://www.dropbox.com/s/pi152rgz6reion5/ReactNative-doc.mp4?dl=0](https://www.dropbox.com/s/pi152rgz6reion5/ReactNative-doc.mp4?dl=0)

Screenshot:

<img width="1181" alt="7-14-16 2 36 pm - safari - www facebook com - - screen shot" src="https://cloud.githubusercontent.com/assets/311343/16839648/7e0d2d86-49d0-11e6-9390-a3ab2cb4ec07.png">

**Comment by charpeni** [comment]
@facebook-github-bot label Documentation

**Comment by hramos** [comment]
I wasn't able to reproduce this on a clean Safari 9.1.1 install running on El Capitan. Is it possible that a Safari extension may be at fault here?

**Comment by nicnocquee** [comment]
@hramos I tried disabling the only extensions I have, Ghostery and Adblock, still no luck. The only way I can see the correct code is by closing the tab and re-open it. 

Without the extensions, I only got this error

<img width="1667" alt="7-14-16 7 14 pm - safari - facebook github io - - screen shot" src="https://cloud.githubusercontent.com/assets/311343/16848767/a508fc40-49f7-11e6-90e7-cde12d920f6c.png">

**Comment by yueshuaijie** [comment]
Can't reproduce +1

**Comment by fdnhkj** [comment]
OS: MacOS Sierra beta 10.12 (16A238m)
Browser: Safari 10.0 (12602.1.38.2)
Safari extensions: Ghostery (5.4.10) & uBlock (0.9.5.2)

I had the same issue and managed to make it work by specifying https protocol instead of http in the URL ([**https**://facebook.github.io/react-native/releases/next/docs/props.html](https://facebook.github.io/react-native/releases/next/docs/props.html)).

I took two screenshots w/ console logs, the first with **http** specified:
<img width="1280" alt="capture d ecran 2016-07-16 a 02 49 17" src="https://cloud.githubusercontent.com/assets/5569608/16891809/5eb24274-4b00-11e6-8865-d234940acf01.png">
And the second with **https**:
<img width="1280" alt="capture d ecran 2016-07-16 a 02 52 16" src="https://cloud.githubusercontent.com/assets/5569608/16891813/a0e9a0c4-4b00-11e6-95e7-f93ab3751f2f.png">

Hope it helps :)

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/react-native-doc-doesnt-load-the-correct-codes

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
