### ISSUE TITLE
[rnpm] Pass params to postlink

### ISSUE THREAD

**Issue by geof90** [facebook/react-native#8797]
This is a dupe of https://github.com/rnpm/rnpm-plugin-link/issues/96, I'm not sure if I should continue to file issues in the RNPM repo or here now that RNPM has been merged in.

`rnpm link`/`react-native link` is great, however there are some patches specific to our plugin that developers need to make when instrumenting their app with our plugin. We intend to automate these extra steps for them in a `postlink` script.

Some of these patches require information that the user needs to provide to us (in our case, a deployment key). We tried to do something like this to prompt the user for the key:
```json
{
  "rnpm": {
    "params": [
      {
        "message": "What is your CodePush deployment key for iOS (hit <ENTER> to ignore)",
        "name": "iosDeploymentKey",
        "type": "input"
      }
    ],
    "commands": {
      "postlink": "rnpm codepushify-ios ${iosDeploymentKey}"
    }
  }
}
```
However, the `${iosDeploymentKey}` syntax doesn't actually get replaced with the key when our script is called. The alternative is for us to poll for that additional param ourselves, but it would be great if we can add support for parameterized strings in the `postlink` declaration.

@Kureev @grabbou

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/rnpm-pass-params-to-postlink

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
