### ISSUE TITLE
Customize NavigationExperimental Transitioning Box Shadow?

### ISSUE THREAD

**Issue by joncursi** [facebook/react-native#8799]
I'm trying to customize the styles of the scene as it transitions in, similar to using the `sceneStyles` prop on the standard Navigator. Is there a way to do this? The scene has a heavy box shadow by default for iOS that I would like to customize (notice the slight render glitch as a scene pops off the screen):

https://cdn-images-1.medium.com/max/800/1*xuqhfIZCKL6xTaf2-zaO3A.gif

Thanks!

**Comment by ryankask** [comment]
This is a known problem but I'm not sure there is an issue yet for it with regard to NavigationExperimental. There is one for the older Navigator: https://github.com/facebook/react-native/issues/2301

Looking at the iOS Settings app and playing around with its navigation, it appears like `NavigationCard`'s `shadowOpacity` and/or `shadowRadius` should be animated in `NavigationCardStackStyleInterpolator`.

I haven't had a chance to play around with doing that but you could try it out by using an animated value for those style properties.

If you're using `NavigationCardStack`, you can use the `cardStyle` prop that was added in 0.30 (available today). If you're not using it, you can just use the style prop directly.

If it works out, it would be a great PR. I'll probably have a look at it when I next get a chance if you'r not able to.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/customize-navigationexperimental-transitioning-box-shadow

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
