### ISSUE TITLE
[Packager] Haste dependency regex is over-eager

### ISSUE THREAD

**Issue by ide** [facebook/react-native#88]
If you have method named `require` on an object and call it with something that looks like a path, Haste parses it and puts it in the module map. Instead it should look for object-less require calls and maybe explicitly allow `global.require` and `window.require`.

Repro: `X.require('./hello')`

**Comment by christopherdro** [comment]
@ide Any updates on this issue?

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/packager-haste-dependency-regex-is-over-eager

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is super simple to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is heavily focused working on performance.
