### ISSUE TITLE
[Suggestion]Can we make property `value` manageable in Component <Slider />

### ISSUE THREAD

**Issue by ncysatnaf** [facebook/react-native#8803]
I was trying to update current location of a <Slider /> by changing the value property,but I got an Error like below:
```javascript
Error while updating property 'value' of a view managed by: RCTSlider
```
Env: 
>android 6.0.1
>react-native 0.26.2

*My suggestion*
May be we can replace the `value` property to a `defaultValue`,and make the `value` property changeable to reflect progress of a Slider?

**Comment by yueshuaijie** [comment]
Tested in 0.29.1 on iOS, updating the value property works.

Here is my code:

`<Slider value={this.state.value} />`

Update it:
`this.setState({value:0.2})`

Maybe only Android has the problem?

**Comment by ncysatnaf** [comment]
@yueshuaijie  thx 
 I create a text project in 0.29.1 on android, but the same error exist. 
Below is my text code:
```js
class test extends Component {
  constructor(props){
    super(props)
    this.state = {
      value: 0
    }
  }
  render() {
    return (
      <View style={styles.container}>
        <Slider value={this.state.value}/>
        <TextInput onChangeText={text => this.setState({
            value: text
          })}/>
      </View>
    );
  }
}
```

**Comment by janicduplessis** [comment]
This is maybe because value need to be a number? Does it work if you do `value: parseInt(text, 10)` ?

**Comment by ncysatnaf** [comment]
@janicduplessis 
It's working!! thank you~😀

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/suggestioncan-we-make-property-value-manageable-in-component-slider-

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
