### ISSUE TITLE
performance issue - StyleSheet border style on view with huge text

### ISSUE THREAD

**Issue by mateoKaradza** [facebook/react-native#8804]
I recently started playing with React Native and so far I'm really happy with it, it's much easier than writing Java code.

I'd like to report a performance issue I had when using styling border on a view that had a lot of text within it, first the rendering of the tab would take several seconds, and then scrolling was a disaster, huge lag, frame drop, check the screenshot
![screenshot_2016-07-13-19-11-44-808_com crystallexicon](https://cloud.githubusercontent.com/assets/4072018/16868304/187cd9e2-4a77-11e6-8b4f-80d7b0ec821a.jpg)
Here is the faulty styling: https://github.com/mateoKaradza/Crystal-Lexicon-App/commit/a178451bbddc46699783e2b4514e17dd7670fbb9

Here is the test screen that reproduces the error
https://github.com/mateoKaradza/Crystal-Lexicon-App/blob/master/app/screens/Test.js

In order to test it just change onItemPress id from 'ProductPage' to 'Testing':
https://github.com/mateoKaradza/Crystal-Lexicon-App/blob/master/app/screens/ProductList.js#L42

I'm using RN 0.29. and this has been tested on Android.

**Comment by charpeni** [comment]
@facebook-github-bot label Perf

**Comment by satya164** [comment]
cc @astreet

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/performance-issue-stylesheet-border-style-on-view-with-huge-text

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
