### ISSUE TITLE
React Native how using multiple page?

### ISSUE THREAD

**Issue by mustafakucuk** [facebook/react-native#8805]
Hi,
how to redirect to react native ?

Ex : index.android.js - login.js . profile.js 

` <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.android.js
        </Text>
        <Text style={styles.instructions}>
          Shake or press menu button for dev menu
        </Text>
      </View>`

Thanks :)

**Comment by Mayzie** [comment]
Please submit questions to [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

**Comment by mustafakucuk** [comment]
My StackOverflow account is banned :/

**Comment by mateoKaradza** [comment]
What you need is a Navigator, it's already part of the react-native.
Check this article: https://medium.com/@dabit3/react-native-navigator-navigating-like-a-pro-in-react-native-3cb1b6dc1e30#.ydeknoql5

**Comment by charpeni** [comment]
https://medium.com/@spencer_carli/exploring-navigators-in-react-native-869b6ab47e0f#.ahlqutd6i

**Comment by charpeni** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-2** [comment]
Closing this issue as @charpeni says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.
