### ISSUE TITLE
'NavigationExperimental in UIExplorer' hyperlink leads to 404 error.

### ISSUE THREAD

**Issue by comradealain** [facebook/react-native#8808]
The 'NavigationExperimental in UIExplorer' hyper-link from Navigation doc leads to 404. Apparently https://github.com/facebook/react-native/tree/master/Examples/UIExplorer/NavigationExperimental is deleted but https://github.com/facebook/react-native/blob/gh-pages/docs/navigator-comparison.html is not updated.

**Comment by satya164** [comment]
Would be awesome if you could send a pull request to fix it.

**Comment by nak1b** [comment]
@satya164 i can send a PR but what it should link to.

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-4** [comment]
Closing this issue as @DanielMSchmidt says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.
