### ISSUE TITLE
Document threading contract for ViewManagers

### ISSUE THREAD

**Issue by rigdern** [facebook/react-native#8819]
When you implement a ViewManager, what thread does React Native invoke its methods on that are annotated with `@ReactProp`? Based on reading the React Native source code, I suspect it's the UI thread but this information should be stated in the documentation for implementing ViewManagers:
  - iOS: http://facebook.github.io/react-native/docs/native-components-ios.html
  - Android: http://facebook.github.io/react-native/docs/native-components-android.html

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/document-threading-contract-for-viewmanagers

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
