### ISSUE TITLE
"Installing react-native package from npm..." never be closed

### ISSUE THREAD

**Issue by minhhuy150894** [facebook/react-native#8825]
I use command "react-native init MyProject".
Then it show "install react-native package from npm..."
I've waited for the finish message to be show for over an hour. But the message above seem display forever -_- 
Why this happened?
Any help?
Thanks very much!!

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-4** [comment]
Hey @minhhuy150894 and thanks for posting this! @DanielMSchmidt tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
