### ISSUE TITLE
TextInput don't support auto Expand

### ISSUE THREAD

**Issue by wenpkpk** [facebook/react-native#8832]
use textinput and write some text more than one line, the textinput don't auto expand.

**Comment by berkayk** [comment]
Search for **AutoExpandingTextInput**  in the text input docs here https://facebook.github.io/react-native/docs/textinput.html 

Instead of using default TextInput, you can use AutoExpandingTextInput.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/textinput-dont-support-auto-expand

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
