### ISSUE TITLE
[Android]ScrollView don't support two-dimensional scrolling

### ISSUE THREAD

**Issue by wenpkpk** [facebook/react-native#8833]
ScrollView on android can support only horizontal or vertical scrolling

**Comment by mquandalle** [comment]
This looks like a duplicate of #8579.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/androidscrollview-dont-support-two-dimensional-scrolling

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
