### ISSUE TITLE
[iOS]RCTImageLoader don't support disk cache

### ISSUE THREAD

**Issue by wenpkpk** [facebook/react-native#8834]
open a page shows some images downloaded from network,  they would redownload again when i relaunch app on iOS.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/iosrctimageloader-dont-support-disk-cache

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
