### ISSUE TITLE
[iOS]RCTHTTPRequestHandler thread issue

### ISSUE THREAD

**Issue by wenpkpk** [facebook/react-native#8835]
- (void)cancelRequest:(NSURLSessionDataTask *)task
{
  [task cancel];
  [_delegates removeObjectForKey:task];
}

_delegates is not thread-safe, it crashed in my app.

**Comment by RD1991** [comment]
Can you just confirm the method , if it exists or not on the delegate ? like, 

- (void)cancelRequest:(NSURLSessionDataTask *)task
{
  [task cancel];
  if([delegate respondsToSelector:@selector(removeObjectForKey:)])
    [_delegates removeObjectForKey:task];
}

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/iosrcthttprequesthandler-thread-issue

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
