### ISSUE TITLE
PanResponder.onPanResponderMove not responding for pinch

### ISSUE THREAD

**Issue by weixingsun** [facebook/react-native#8852]
Hello, 

I cannot get event that more than 2 touches in my Android 6.0.1/iOS 9.3 device with RN.29, which is very annoying
Help needed, any suggestion will be highly appreciated.

PanResponder.create({
onPanResponderMove: (evt, gestureState){
    if(evt.nativeEvent.touches.length<2)  //move
    //if(evt.nativeEvent.changedTouches.length<2)  //also move?
    else  //pinch, this condition is never called.
}
...
})
//Is PanResponder changing the API ?
thanks very much!

**Comment by weixingsun** [comment]
looks like the PanResponder is not so popular,

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/panresponderonpanrespondermove-not-responding-for-pinch

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by Ellegarden1219** [comment]
having same issue, tried to create 4 drag and drop circle for iOS device, but it only worked 2 touches

**Comment by slorber** [comment]
I am having same issue: move event does not fire anymore when there are 2 fingers in the screen

**Comment by slorber** [comment]
Please vote for https://react-native.canny.io/feature-requests/p/panresponderonpanrespondermove-not-responding-for-pinch

**Comment by antonKalinin** [comment]
Hi @slorber, I've just faced with same problem and it looks like PanResponder.onPanResponderMove don't work only when it place in **Modal**. I was trying to implement image view component with zoom in Modal and fail, but when I replaced Modal with simple View the handler started to response.
