### ISSUE TITLE
Android geolocation error

### ISSUE THREAD

**Issue by my-love** [facebook/react-native#8858]
Hi , When I use 'navigator.geolocation.getCurrentPosition' to get user's location, the error callback was executed when i closed the GPS in Android.

**Comment by KGALLET** [comment]
I don't understand what's your issue here. 
If you disabled GPS on your device, the `navigator.geolocation.getCurrentPosition` method can't locate you, that's why the error callback is triggered

**Comment by my-love** [comment]
yes, and I found out that there was two ways to locate users. Is 'android.permission.ACCESS_COARSE_LOCATION' useful in RN? And when the GPS is closed, could I prompt the user to open GPS(I mean open the GPS by code).

**Comment by KGALLET** [comment]
@my-love Personnaly i use : `   <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/> ` in my android app.

I don't know, probably, in my case I use https://github.com/yonahforst/react-native-permissions for iOS to know if the geolocation is disabled or not. 
Android is in the roadmap.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-geolocation-error

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
