### ISSUE TITLE
Parameter must be a decedent of the view error

### ISSUE THREAD

**Issue by RonakKhandelwal** [facebook/react-native#8864]
App works Nicely on other devices when I try to run it on moto x play and click on a row(In a list view) it shows me this error

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/parameter-must-be-a-decedent-of-the-view-error

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
