### ISSUE TITLE
[Tests] Reinstate AnimatedNative JS tests

### ISSUE THREAD

**Issue by ide** [facebook/react-native#8872]
See https://github.com/facebook/react-native/commit/d905af47362e2a95677678ec5a4256e35f8782ea#commitcomment-18279365

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/tests-reinstate-animatednative-js-tests

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by mkonicek** [comment]
Whoops this seems important. Pinged Elliot.

**Comment by mkonicek** [comment]
@kmagiera, @janicduplessis The test looked useful but was broken so was deleted. Would teh test still be valid and useful? https://github.com/facebook/react-native/commit/d905af47362e2a95677678ec5a4256e35f8782ea

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
