### ISSUE TITLE
cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by pavlelekic** [facebook/react-native#8888]
Often I'm getting these `cannot read property 'bind' of undefined` messages with absolutely no additional information. I don't know where to look for to fix this. This error message is completely useless. Please improve error messaging. 

I'm using RN 0.29.2, but I've seen this in earlier versions too. I'm on Mac, making an iOS app. Here is a screenshot.
![simulator screen shot jul 19 2016 11 11 07](https://cloud.githubusercontent.com/assets/7754193/16944759/5a26ec38-4da2-11e6-8943-aeb214a2f45e.png)

**Comment by KGALLET** [comment]
I think this error appears when you bind an undefined function, for example in the `constructor `.
This isn't normal that you don't have any more informations about this error, anyway.

Try to get a clean install of react-native, maybe it should solve the problem that you don't have more information :
`rm -rf node_modules && npm i`

**Comment by grabbou** [comment]
Hey, we use Github for issues only and all questions should be asked on StackOverflow. 

This is for us to keep the number of issues smaller so that we can iterate on React Native versions faster and provide you with the better developer experience. 

If you have any ideas on how we could improve the entire process, please share your thoughts on [React Native Community](https://www.facebook.com/groups/react.native.community/?ref=nf_target&fref=nf) group.

**PS**: Turn on Chrome Debugger and select `Stop on uncaught exceptions` to see which exact line is causing this exception to happen.
