### ISSUE TITLE
How to send event from iOS to javascript

### ISSUE THREAD

**Issue by Arthraim** [facebook/react-native#8891]
I'm doing something Async in iOS app, it's triggered by javascript. When it's done (somewhere separated in app), I want to let javascript know.
My current solution is a native module inherited from `RCTEventEmitter`, has a method like 

```
@interface MyEventEmitter : RCTEventEmitter
// ...
end
@implementation
- (void)giveSomethingToJS:(NSString *)something {
  [self sendEventWithName:@"SOME_NAME" body:something];
}
@end
```

Then when my Async job's done, I call this method like

```
MyEventEmitter *emitter = [[MyEventEmitter alloc] init];
[emitter giveSomethingToJS:@{}];
```

And obviously, `emitter.bridge` is nil and app crashed because of assert `bridge != nil`. So how am I get the bridge and let `*emitter`(the instance) know. Or how can I get the right instance with bridge initialized?

Thanks in advance!

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-0** [comment]
Hey @Arthraim and thanks for posting this! @charpeni tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by purplepeng** [comment]
I have the same problem.

**Comment by purplepeng** [comment]
Thank you. I have resolve the problem. https://github.com/facebook/react-native/issues/8714
