### ISSUE TITLE
Can't understand why the variable isolateModuleIDs assign to true by default in output/bundler.js!!

### ISSUE THREAD

**Issue by Leone90** [facebook/react-native#8897]
The variable isolateModuleIDs is assigned to true by default in output/bundler.js! The method createModuleIdFactory would execute  twice in Bundler/index.js! But the code "this._getModuleId = createModuleIdFactory()" already initial in Bundler/index.js constructor method! Want to ask why do it! @davidaurelio

**Comment by grabbou** [comment]
Hey, we use Github for issues only and all questions should be asked on StackOverflow. This is for us to keep the number of issues smaller so that we can iterate on React Native versions faster and provide you with the better developer experience. 

If you have any ideas on how we could improve the entire process, please share your thoughts on [React Native Community](https://www.facebook.com/groups/react.native.community/?ref=nf_target&fref=nf) group.
