### ISSUE TITLE
Unable to 'shrink' network image

### ISSUE THREAD

**Issue by TLenahan** [facebook/react-native#8901]
If I fetch an image from my server, and the image size is larger than the height and width defined, the image is not being displayed when I use resizeMode= contain or stretch. The Image will only be displayed if I use resizeMode = cover. 

resizeModes stretch and contain work, as long as the image is smaller that the width and height defined.

Any help with this?

Code example:

```
<View style={{flex: 1, padding: 10}}>
        <Image
          style={{height: 500, width: 300}}
          source={{uri: 'https://my-server/path/to/image.gif'}}
          resizeMode={Image.resizeMode.contain}
        />
</View>
```

**Comment by huyphan** [comment]
@TLenahan: How many frames are there in your GIF files ? 

I bumped into a similar issue recently and realized that React Native seems to have problem with displaying GIF images that have only one frame with resizeMode set to `contain` or `stretch`. This happens with both local images and network images.

**Comment by TLenahan** [comment]
I actually am using png files, sorry for the mix up in my example.

**Comment by lacker** [comment]
It seems like we are lacking a bug repro here so it has been hard for anyone to help. I am going to close this issue as stale. Maybe Stack Overflow would be more useful in this situation? - it seems like there is likely some bug but rooting around to figure out where the bug is will require some back and forth.
