### ISSUE TITLE
Is it a must to upgrade to 0.29?  

### ISSUE THREAD

**Issue by dunhuang** [facebook/react-native#8915]
From yesterday, when I start a new project and run react-native init xxx , if react native version is 0.27 or under in packadge.json, there is always a "RCTBundleURLProvider.h not found" error. 
Seems RCTBundleURLProvider.h is a new file came with 0.29, am I right?
Now I am forced to use 0.29 but I still don't know if it can work with my older version's code or plugins.

**Comment by shirleycharlin** [comment]
I have encounter some RCT bundle issue too. I was not able to find the bug in the source file. so I have downgraded to 0.28. Everything seems smooth.

**Comment by zhileichen** [comment]
I think it should be encouraged to upgrade to the newest version, 'cause each version contains lots of improvements. :)

**Comment by charpeni** [comment]
As @zhileichen said, each version brings new features and bug fixes although some breaking changes. If your environment allow it, you should definitely update your React Native version.

I'm not sure I understand the part that you run `react-native init` and if react native version is 0.27 or under?

Don't forget to run the upgrade tool `react-native upgrade` as described here : [Upgrading Documentation](https://facebook.github.io/react-native/docs/upgrading.html).

**Comment by ide** [comment]
We support only the latest version of React Native so it's generally a good idea to upgrade. These are some of the tradeoffs to help you make a decision that's right for your use case:

**Benefits of upgrading:**
- Bug fixes usually are committed to the next version of React Native. Sometimes they are cherry picked into the current version and we do a patch release.
- Only the latest version and master are supported. So if you're using the latest version and find a bug, we can look into it. Otherwise, we have so many issues that we can't support old versions.
- New components and modules may only work on the latest version.

**Downsides of upgrading:**
- React Native updates often. You might want to update only every month instead of every two weeks.
- Sometimes there are breaking changes
- Community native modules might stop working unless the authors update the modules

I would say that upgrading is usually the right decision unless your app is complete and you don't plan to work on it very much in the future. It does require work to stay up-to-date and sometimes write some native code to keep your native modules working, so keep that cost in mind when choosing to pull in native modules.
