### ISSUE TITLE
prebundle js can not be loaded in device when using a proxy server

### ISSUE THREAD

**Issue by dunhuang** [facebook/react-native#8919]
Now  I am using 0.28. It works as before in Emulator. But when I change to real iphone,  with a proxy server setting in my iphone in order to access some test host,  "Loading from pre-bundled fill..." sign is always visible, and bundle js can never be loaded. 
With very limited knowledge with Object C, I don't know what has been changed exactly. Anyway I found the way to solve this :
Change the ip address manually in RCTBundleURLProvider.m. It is a little bit more annoying than before when we had to change 'localhost' in AppDelegate.m to run app in device.
I just wonder if it could be a little bit easier to run in device while using a proxy server.

**Comment by grabbou** [comment]
Hey, we use Github for issues only and all questions should be asked on StackOverflow. This is for us to keep the number of issues smaller so that we can iterate on React Native versions faster and provide you with the better developer experience. 

If you have any ideas on how we could improve the entire process, please share your thoughts on [React Native Community](https://www.facebook.com/groups/react.native.community/?ref=nf_target&fref=nf) group.
