### ISSUE TITLE
Bridge between android sdk and android react native

### ISSUE THREAD

**Issue by chetnadaffodil** [facebook/react-native#8926]
Hi,
I need to interact with an android SDK and not a built in component of android. 
Is that possible with the current version of react native? If so.. please provide the details.

**Comment by charpeni** [comment]
Hi @chetnadaffodil, i'm not sure I understand your question. Can you provide more information ? 

Are you trying to use an SDK provided by external source in a React Native Application ? If it's the case, you can interact with it and you can even bridge it to the javascript. [Native Modules Documentation](https://facebook.github.io/react-native/docs/native-modules-android.html).

Although I'll try to help you as I can, but know that GitHub issues are for bugs only and you should ask your question on Stack Overflow.

**Comment by rmevans9** [comment]
Since this has been inactive for about a month and based upon my understanding the link provided answers the question... I am going to go ahead and close this. If there is anything further needed in this issue I would be happy to reopen.

**Comment by rmevans9** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-2** [comment]
Closing this issue as @rmevans9 says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.
