### ISSUE TITLE
React Native call components in imports js

### ISSUE THREAD

**Issue by ensarakin** [facebook/react-native#8927]
I have an import.js and I am writting all modules' path in there. For example. color.js and button.js is recognized in import.js. And then I want to call my imports from there in the other components. And I can call all modules' imports in the main.js. But in button.js , I can't call color.js When one of js file is imported in import.js, It can't call any js file in import.js. Also It is giving this error:

1.undefined is not an object (evaluating 'COLOR.BUTTONDARK')
2.[fatal][tid:com.facebook.react.RCTExceptionsManagerQueue] Unhandled JS Exception: undefined is not an object (evaluating 'COLOR.BUTTONDARK')
3.[error][tid:com.facebook.react.JavaScript] Module AppRegistry is not a registered callable module.

I have  asked question on stackoverflow:
[http://stackoverflow.com/questions/38482212/react-native-call-components-in-imports-js](link)

**Comment by satya164** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-0** [comment]
Hey @ensarakin and thanks for posting this! @satya164 tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
