### ISSUE TITLE
is cameraRoll create another activity for take photos?

### ISSUE THREAD

**Issue by Hanruis** [facebook/react-native#8940]
I had develop a cordova app which uesd camera plugin. 

It came across this issue : see here [PhoneGap camera restarts the application](http://stackoverflow.com/questions/8368091/phonegap-camera-restarts-the-application)

> It occurs because when the camera is triggered, the android activity goes background (onStop state), waiting for the camera to take the picture. Then the GC comes and kills the activity to free memory before the conclusion of camera action, and when the camera is done your activity has already died. That is why the app is restarted.

I am curious about whether RN's cameraRoll api consider this situiation.

**Comment by Dean177** [comment]
The [CameraRoll](https://facebook.github.io/react-native/docs/cameraroll.html#cameraroll) api isn't for taking photos using the Camera, its for accessing photos which are already on the device.

**Comment by grabbou** [comment]
Hey, we use Github for issues only and all questions should be asked on StackOverflow. Please consider posting your question up there providing more details on what specifically you'd like to achieve! 

This is for us to keep the number of issues smaller so that we can iterate on React Native versions faster and provide you with the better developer experience. 

If you have any ideas on how we could improve the entire process, please share your thoughts on [React Native Community](https://www.facebook.com/groups/react.native.community/?ref=nf_target&fref=nf) group.
