### ISSUE TITLE
something goes wrong after fatching data -0.25+

### ISSUE THREAD

**Issue by iniestano8** [facebook/react-native#8941]
i fetch some data(json) from my api, and it costs about 1.5 seconds on the step xx.json(), i checked the fetch source and found that the responseType of xhr( = New XMLHttpRequest()) exists and values a empty string, so it returns me a blob responseType, then i call xx.json(), it does take too long ...
![image](https://cloud.githubusercontent.com/assets/5787530/17023896/3e271f8e-4f88-11e6-9fa0-6d87d7be8c11.png)
maybe the method below works well..sorry for bad english
if ('responseType' in xhr **&& xhr.responseType** && support.blob) { xhr.responseType = 'blob' }

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/something-goes-wrong-after-fatching-data-025

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
