### ISSUE TITLE
Any way to adjust the height of TabBar iOS?

### ISSUE THREAD

**Issue by lazywei** [facebook/react-native#895]
Hi,

I'm using TabBarIOS, and I'm wondering is there any way I can change the height of the bottom bar?

![image](https://cloud.githubusercontent.com/assets/2840571/7196988/c63e988e-e50d-11e4-8aed-462ccc7e6242.png)

I've looked into the source code of TabBarIOS and TabBarIOS.Item, but it seems there is no any public API I can change that. Probably the only way is through overwrite the styles?

Thanks.

**Comment by brentvatne** [comment]
It seems that UIKit doesn't allow you to change the height of UITabBar [very easily](http://stackoverflow.com/questions/24397189/changing-the-height-of-uitabbar-in-ios7-8), probably because the designers did not intend for it to be changed. If you want to do you could subclass `React/Views/RCTTabBar.m` and add one of the fixes from the above link :smile:

**Comment by lazywei** [comment]
Got it. Thanks for the information :+1:
