### ISSUE TITLE
Vibration.vibrate() is not working after I setState

### ISSUE THREAD

**Issue by martco** [facebook/react-native#8955]
This doesn't work for me:

```
this.setState({foo: 'bar'}, ()=> Vibration.vibrate());
```

However this does: 

```
componentDidUpdate() {
  Vibration.vibrate();
}
```

**Comment by amccloud** [comment]
I'm running into a similar issue after reading state.

```js
  handleTalkStart() {
    if (!this.state.ready) { return; }
    Vibration.vibrate(); // I reach this call but nothing happens
  }
```

```js
  handleTalkStart() {
    Vibration.vibrate(); // I reach this call and it works
  }
```

**Comment by attilaaronnagy** [comment]
Same for me. Any workarounds?

**Comment by hubertperron** [comment]
This is still an issue in the latest version.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, it does not seem like there has been any traction on this issue for some time.

      The issue is being copied over to our feature request tracker at Canny: https://react-native.canny.io/admin/board/feature-requests/p/vibrationvibrate-is-not-working-after-i-setstate

      There you can upvote issues that are important to you. This will help contributors identify the issues that the community cares about.

      If you think this issue should definitely remain open here in the issue tracker and not on Canny, let us know.

**Comment by xeroxoid** [comment]
Hi there! The issue does still seem to exists.

### Environment

Environment:
  OS: macOS High Sierra 10.13.2
  Node: 8.9.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.3764568

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.3 => 0.50.3

Target Platform: iOS (10.2)

**Testing platform: Expo app ion iOS**

### Steps to Reproduce

Call ``Vibration.vibrate()`` after setting state like this:

```
this.setState({foo: 'bar'}, ()=> Vibration.vibrate());
```

Whereas the following seems to work fine:

```
componentDidUpdate() {
  Vibration.vibrate();
}
```


### Expected Behavior

The iPhone should vibrate when ``Vibration.vibrate()`` is called.

### Actual Behavior

The phone does not vibrate at all and any further calls to ``Vibration.vibrate()``, even not after setting state, also fail.

Please note that we are testing this on the expo app.

Thanks.

**Comment by pravinarr** [comment]
It might help to check the setting in Iphone whether Vibrate on ring and vibrate on silent is switch on.

I was also facing this issue, got to work by switching on vibration in Iphone setting

thanks

**Comment by danmatthews** [comment]
Also reporting this as seemingly not fixed.

**Comment by cky-BryanChan** [comment]
vibration not working
