### ISSUE TITLE
can setTag to react native view?

### ISSUE THREAD

**Issue by iceskyblue** [facebook/react-native#8959]
can setTag to react native view?

**Comment by grabbou** [comment]
Hey, we use Github for issues only and all questions should be asked on StackOverflow. Please consider posting your question up there providing more details on what specifically you'd like to achieve! 

This is for us to keep the number of issues smaller so that we can iterate on React Native versions faster and provide you with the better developer experience. 

If you have any ideas on how we could improve the entire process, please share your thoughts on [React Native Community](https://www.facebook.com/groups/react.native.community/?ref=nf_target&fref=nf) group.
