### ISSUE TITLE
Flex wrap has bugs

### ISSUE THREAD

**Issue by musicode** [facebook/react-native#8960]
flex style has some bug, just like the chat scene:

![image](https://cloud.githubusercontent.com/assets/2732303/17046205/3d697c74-5003-11e6-9fcb-3fb9b3a5e879.png)

```
  textContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  textContent: {
    color: '#333',
    fontSize: 16,
  },
  url: {
    color: '#007aff',
  },
```

wrap is not ok.

**Comment by kulmajaba** [comment]
Elements inside a `View` with `flexDirection: 'wrap'` and `flexWrap: 'wrap'` will behave as they should, `Text` elements will overflow to the right because of the `flexDirection`.

A common solution to this is to wrap the `Text` element in a separate `View` that has `flexDirection: 'column'` in the styles.

Hope this helps.

**Comment by musicode** [comment]
@kulmajaba 

thanks.

if I want to input emoji which is an image, the result is one image one row, it's so ugly.

**Comment by jaynsw** [comment]
flexDirection:'row' flexWrap:'wrap' has issue. The following is the screenshot when I upgrade to 0.30

![screen shot 2016-07-23 at 8 25 04 pm](https://cloud.githubusercontent.com/assets/5652798/17077433/e7325c92-5113-11e6-90ef-7c8fef47447c.png)

**Comment by kulmajaba** [comment]
@jaynsw Have you tried using `alignItems: 'flex-start'`?

**Comment by jaynsw** [comment]
I am interesting in removing the gap between lines when wrapping. Now when
it wraps,  there is a  gap between lines. the height is the image height,
this gap shouldn't exist

**Comment by ryankask** [comment]
I'm not sure if this is the same issue @jaynsw is talking about but I see this with `flexDirection: 'row'` and `flexWrap: 'wrap'`:

<img width="320" alt="2016-07-25 at 11 47" src="https://cloud.githubusercontent.com/assets/81891/17099056/cfa96e44-525d-11e6-90f5-3e3c25cc6d18.png">

Adding `alignItems: 'flex-start'` fixed it. I'll need to study the reason why later..

<img width="325" alt="2016-07-25 at 11 50" src="https://cloud.githubusercontent.com/assets/81891/17099082/f20b92f0-525d-11e6-9cfa-a2d1f0e6c28b.png">

Thanks, @kulmajaba!

**Comment by chrbradley** [comment]
Using version 0.34.1, it looks like `flexWrap: 'wrap'`  prevents `alignItems: any` from working:

```javascript
class AwesomeProject extends Component {
  render() {
    return (
      <View style={styles.container}>
        <View style={styles.box} />
        <View style={styles.box} />
        <View style={styles.box} />
        <View style={styles.box} />
        <View style={styles.box} />
        <View style={styles.box} />
      </View>
    )
  }
}

const styles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    height: 300,
    alignItems: 'center',
    borderWidth: 4,
    borderColor: 'red'
  },
  box: {
    height: 75,
    width: 75,
    backgroundColor: 'lime',
    borderWidth: 2,
    borderColor: 'black'
  }
})
```

results in: 
![screen shot 2016-10-07 at 9 41 26 am](https://cloud.githubusercontent.com/assets/5009163/19191898/46a7b43a-8c72-11e6-81a4-caf118918c60.png)

`flexWrap: 'nowrap'` (or just commenting it out) results in:
![image](https://cloud.githubusercontent.com/assets/5009163/19191942/6eedd758-8c72-11e6-8451-b8adeeb8a8db.png)


I've tried all the combinations of `flexDirection`, `flexWrap` and `alignItems`. When `flexWrap: 'wrap`, `alignItems` has no effect.

**Comment by danleveille** [comment]
`alignItems: 'flex-start'` Fixed the issue for me.

**Comment by plrthink** [comment]
`alignItems: 'flex-start'` also works on my project

**Comment by lokesh-coder** [comment]
Hi @chrbradley ,  I foo faced the same issue. I fixed it by wrapping the container `View `by another `View `and applied this style` {flex:1,justifyContent:'center'}`

In your case it should be something like this,
```
<View style={{flex:1,justifyContent:'center'}}>
  <View style={styles.container}>
    <View style={styles.box} />
    <View style={styles.box} />
    <View style={styles.box} />
    <View style={styles.box} />
    <View style={styles.box} />
    <View style={styles.box} />
  </View>
</View>
```

**Comment by hongyu315** [comment]
After RN 0.28, you have to use { flexWrap:'wrap'}，before that,{ flexWrap:'wrap' } work with {alignItems: 'stretch'}together default.

**Comment by vardanmobiloitte** [comment]
Can someone suggest what to use for RN 0.28 to solve above problem

**Comment by HyperSimon** [comment]
> @jaynsw Have you tried using alignItems: 'flex-start'?

@kulmajaba It work for me, Can you tell me what is the reason?

**Comment by idibidiart** [comment]
I've also noticed an issue in v0.42, but given this thread's staleness I might start another issue. But first, I'd like to know if the issues reported here have been resolved?

**Comment by kulmajaba** [comment]
> I've also noticed an issue in v0.42, but given this thread's staleness I might start another issue. But first, I'd like to know if the issues reported here have been resolved?

@idibidiart What kind of an issue?

To recap the issues on this thread:
### The original issue with text wrap inside a flex container
In a fresh React Native 0.44 project I could not reproduce this issue. Text will wrap in the following cases, all components inside a `View` container:
* `Text` is inside a `View`, `View` styles `flexDirection` and `flexWrap` can be any combination
* `Text` is standalone in the container `View`, `Text` styles `flexDirection` and `flexWrap` can be any combination

Originally the workaround would have been to wrap the `Text` component in a `View` with style `flexDirection: 'column'`. Now it seems this is not needed.

### Empty space in the bottom of `View` components inside a flex container
Again, could not reproduce the issue in React Native 0.44, seems like this is fixed as well. Tested by placing a bunch of `View` components with styles `minHeight: 100, minWidth: 100` inside a container `View` with styles `flexDirection: 'row', flexWrap: 'wrap'`. The boxes will take up minimum space.

Taking out `flexWrap` from the container `View`, the boxes will fill vertical space as expected, because the default behavior for `alignItems` is `'stretch'` and the primary flex direction has been set to `'row'`. 

### Using `flexWrap: 'wrap'` prevents `alignItems` from working
This is true, but it's not an issue, it's a feature and complies with the CSS3 reference.

`alignItems` aligns the children components in the cross direction. However you are already defining how the children should be aligned in the cross direction by using `flexWrap.` You need to use `alignContent` style instead as this will align the rows in the cross direction, not the children.

**Comment by EyalSi** [comment]
check out the output of this example. not sure what is happening here... so frustrating.
```
render(){
    return (
        <ScrollView>
          <View style={{flexDirection: 'row',flexWrap:'wrap'}}>
            <TouchableOpacity style={{margin:2, backgroundColor:'white'}} >
              <Text style={{fontSize:20}}> test </Text>
            </TouchableOpacity>
            <TouchableOpacity style={{margin:2, backgroundColor:'white'}} >
              <Text style={{fontSize:20}}> test </Text>
            </TouchableOpacity>
            <TouchableOpacity style={{margin:2, backgroundColor:'white'}} >
              <Text style={{fontSize:20}}> test </Text>
            </TouchableOpacity>
            <TouchableOpacity style={{margin:2, backgroundColor:'white'}} >
              <Text style={{fontSize:20}}> test </Text>
            </TouchableOpacity>
            <TouchableOpacity style={{margin:2, backgroundColor:'white'}} >
              <Text style={{fontSize:20}}> test </Text>
            </TouchableOpacity>
            <TouchableOpacity style={{margin:2, backgroundColor:'white'}} >
              <Text style={{fontSize:20}}> test </Text>
            </TouchableOpacity>
            <TouchableOpacity style={{margin:2, backgroundColor:'white'}} >
              <Text style={{fontSize:20}}> test </Text>
            </TouchableOpacity>
            <TouchableOpacity style={{margin:2, backgroundColor:'red'}} >
              <Text style={{fontSize:20}}> tes1 </Text>
            </TouchableOpacity>
          </View>
          <Text>
          This is a test
          This is a test
          This is a test
          </Text>
        </ScrollView>
    )
  }
};
```
![overlap](https://user-images.githubusercontent.com/7838363/26926622-18a7509a-4c57-11e7-9fac-f2d33d131172.PNG)

**Comment by idibidiart** [comment]
on iOS it is also buggy 

I've made a simpler version of the code posted by @EyalSi that shows an interesting definitely buggy behavior:

The only difference in the two screens below is a single extra "." after the last "test"

![image1](https://s30.postimg.org/pzskmed0x/Screen_Shot_2017-06-08_at_8.17.00_AM.png)

![image2](https://s10.postimg.org/ai4qxxj89/Screen_Shot_2017-06-08_at_8.10.23_AM.png)

@kulmajaba there is more buggy behavior that I've encountered that may or may not be related to this

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
