### ISSUE TITLE
[Android] No static field preferences of type I in class Lcom/facebook/react/R$xml

### ISSUE THREAD

**Issue by justingosan** [facebook/react-native#8967]
App runs fine but crashes whenever I try to open `Dev Settings`. Same case when run on emulator and on device

from `adb logcat`
`java.lang.NoSuchFieldError: No static field preferences of type I in class Lcom/facebook/react/R$xml; or its superclasses (declaration of 'com.facebook.react.R$xml' appears in /data/app/****/base.apk)`

react-native-cli: 1.0.0
react-native: 0.28.0
watchman: 4.6.0
Developing on latest OSX

If there's any more info you guys need, just let me know. I'll continue to debug this in the meantime. Thanks!

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-no-static-field-preferences-of-type-i-in-class-lcomfacebookreactrxml

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
