### ISSUE TITLE
Delay caused by onmessage in debuggerWorker.js

### ISSUE THREAD

**Issue by joonhocho** [facebook/react-native#8969]
Enabling 'Debug JS remotely' seem to cause some delays in operations like network calls and responses.
It seems that `onmessage` method in `debuggerWorker.js` is called every once in a while as it gets flushed in bulk maybe?
And, the flushing seems to be happening in not too often thus causing sometimes up to 2~300ms delay to all network calls.
I thought it was a bug in my app, and after digging for a while, I found that the `onmessage` was not being called instantly after the network calls finished.
Could someone briefly explain the mechanism behind this? 
Is there any way to make the flushing of the messages to happen more often so it feels more instant?

I also noticed that constantly scrolling view makes the `onmessage` to be called instantly.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/delay-caused-by-onmessage-in-debuggerworkerjs

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
