### ISSUE TITLE
Ghost character after setting value to null with TextInput (iOS only)

### ISSUE THREAD

**Issue by freakinruben** [facebook/react-native#8973]
Hi,

When I use the TextInput component on iOS I get the first character I typed in the TextInput after I deleted my previous entry:
![jul-11-2016 19-10-34](https://cloud.githubusercontent.com/assets/326344/17063206/7aaa2286-5036-11e6-80c8-a78d19a8b469.gif)

Here I'm doing:
- typing: 'Vit'
- delete 'Vit'
- somehow the 'V' returns
- delete 'V'
- type 'Sup'
- delete 'Sup'
- the 'V' returns again

I'm using a mac, and this only happens on iOS, Android works fine. I'm using RN 0.30.0 but I've seen the issue also with RN 0.24.0.

Code:

``` js
export default class Inputfield extends Component {
  constructor (props) {
    super(props);
    this.state = {
      value: props.value || props.defaultValue,
    };
    this._handleTextChange = this._handleTextChange.bind(this);
  }

  componentWillReceiveProps (nextProps) {
    if (nextProps.value != this.props.value && this.state.value != nextProps.value) {
      this.setState({value: nextProps.value || nextProps.defaultValue});
    }
  }

  _handleTextChange (text) {
    if (text.trim() == '') {
      text = null;
    }
    this.setState({value: text});
  }

  render () {
    return (
      <TextInput
          onChangeText={this._handleTextChange}
          value={this.state.value}
      />
    );
  }
}
```

I also found a fix. If I change `value={this.state.value}` into `value={this.state.value || ''}` the ghost-character doesn't appear so it only happens when you change the value to `null`.

**Comment by kristianm** [comment]
I also encountered the same problem when ``defaultValue`` of the ``TextInput`` was set to ``null``. Also fixed with setting an empty string instead.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/ghost-character-after-setting-value-to-null-with-textinput-ios-only

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
