### ISSUE TITLE
Possible to "hide" the <Picker> caret on Android?

### ISSUE THREAD

**Issue by breadadams** [facebook/react-native#8977]
Is there anyway to hide the _native_ caret shown when using a `<Picker>` component on android?

I thought maybe changing the `mode` prop it'd stop displaying - thinking this was only for the **dropdown** display mode - but it seems the default is **dialog**, and I'm still seeing a caret.

![screen shot 2016-07-22 at 18 47 32](https://cloud.githubusercontent.com/assets/5795227/17064654/e186926c-503d-11e6-8037-151a6d20da6d.png)

Cheers

**Comment by mangogogos** [comment]
I agree with this! I understand it's just wrapping a plain native Spinner component but the main thing keeping me from using the React Native Picker component is the ability to style the display on Android

**Comment by rmevans9** [comment]
A workaround for this is to set the background of the spinner via the Android style which should take away the caret for now. 

Do something like this (Specifically the spinnerStyle one that the answer tells them to remove):
http://stackoverflow.com/questions/13703233/style-android-spinner

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/possible-to-hide-the-picker-caret-on-android

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by brunocascio** [comment]
Same issue...

**Comment by QuangPB** [comment]
I found a "stupid solution" :v
just make a small view (set width, height, backgroundColor, marginLeft) and this view will overlap the carret

ref: https://snack.expo.io/rJR0Funa-

**Comment by 349989153** [comment]
Just give the `Picker` a `backgroundColor` and the caret will disappear.I tested it on 0.48.2.

Inspired by another issue: https://github.com/facebook/react-native/issues/9434
