### ISSUE TITLE
ActivityIndicator w/ TouchableHighlight `validAttributes` Bug

### ISSUE THREAD

**Issue by nickzuber** [facebook/react-native#8981]
**Using React Native v0.29.2**
**iOS & Android**
**Mac**

There is a bug when there is an `ActivityIndicator` component within a `TouchableHighlight` that has an `onPress` property.

## Example Code

```jsx
import React from 'react';
import {
  ActivityIndicator,
  TouchableHighlight
} from 'react-native';

class ExampleComponent extends React.Component {

  render() {
    return (
      <TouchableHighlight
        onPress={() => {}}
      >
        <ActivityIndicator />
      </TouchableHighlight>
    )
  }
}
```

### iOS
![screen shot 2016-07-22 at 3 57 52 pm](https://cloud.githubusercontent.com/assets/10540865/17069542/17c40580-5025-11e6-8919-e35dfcae182d.png)

### Android

![screen shot 2016-07-22 at 4 09 00 pm](https://cloud.githubusercontent.com/assets/10540865/17069844/dd3de5d2-5026-11e6-8299-98fd460c1ad6.png)

I can't reproduce this on `rnplay` because they're currently running v0.24.1 and `ActivityIndicator` components were released very recently.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/activityindicator-w-touchablehighlight-validattributes-bug

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
