### ISSUE TITLE
The tutorial is broken on my Chromium

### ISSUE THREAD

**Issue by oren** [facebook/react-native#8992]
The tutorial is broken on my browser (see picture). I am on Chromium Version 51.0.2704.79 Ubuntu 15.10 (64-bit). It's fine on Firefox.

![tutorial](https://cloud.githubusercontent.com/assets/6517/17082182/614bb108-5129-11e6-97a5-9c0edcfb43e8.png)

**Comment by charpeni** [comment]
@facebook-github-bot label Documentation

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/the-tutorial-is-broken-on-my-chromium

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
