### ISSUE TITLE
RefreshControl onRefresh func not work in ios 

### ISSUE THREAD

**Issue by sunquanzhi** [facebook/react-native#9001]
Run RefreshControlExample from http://facebook.github.io/react-native/docs/refreshcontrol.html
IOS _onRefresh()  function not run.(My simulator IOS 9.3)
Android work fun.

**Comment by grabbou** [comment]
Hey, we use Github for issues only and all questions should be asked on StackOverflow. Please consider posting your question up there providing more details on what specifically you'd like to achieve! 

This is for us to keep the number of issues smaller so that we can iterate on React Native versions faster and provide you with the better developer experience. 

If you have any ideas on how we could improve the entire process, please share your thoughts on [React Native Community](https://www.facebook.com/groups/react.native.community/?ref=nf_target&fref=nf) group.
