### ISSUE TITLE
Offline package does not load the HTML file

### ISSUE THREAD

**Issue by ChinaGoodProgrammer** [facebook/react-native#9002]
In WebView .
eg: source={require('./myHTML.html')}
why?

**Comment by Kureev** [comment]
`source={{uri: '...'}}`. See https://facebook.github.io/react-native/docs/webview.html#source

**Comment by Kureev** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-7** [comment]
Hey @ChinaGoodProgrammer and thanks for posting this! @Kureev tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
