### ISSUE TITLE
uk.co.senab.*.* cannot be cast to android.view.ViewGroup.

### ISSUE THREAD

**Issue by tigerraj32** [facebook/react-native#9004]
I was implementing  activity indicator for loading image from. It worked fine in iOS but for android I got this weird error with following code. 
**uk.co.senab.*.* cannot be cast to android.view.ViewGroup.**
```
render(){
    var loadingView = null;
    if(this.state.imageLoad){
      loadingView = <View style={{alignItems:'center', justifyContent:'center'}}>
      <Spinner isVisible={true} size={50}
      type={'9CubeGrid'} color={'#6ea18e'}/>
      </View>
    }
    return(
      <View style={{flex:1, backgroundColor:'black', justifyContent:'center', alignItems:'center'}} key={0}>

      <ZoomImage
      style={{width:width,height:height/2, margin:10}}
      source={{uri:this.props.imagePath}}
      onLoadStart={(e) =>this.setState({imageLoad: true})}
      onLoadEnd={(e) => this.setState({imageLoad: false})}>
      {loadingView}
      </ZoomImage>


      </View>
    );
  }
```

**Comment by grabbou** [comment]
It's hard to tell just by looking at the Javascript what's going wrong since the exception is coming from the Android native part of your app. It seems to me that the `uk.co.senab..` is not a subclass of a `ViewGroup` but something different (likely a `View`). You should check official guide on writing native components, create a `ViewGroup` and render that view inside.

When in doubt, please refer to StackOverflow.
