### ISSUE TITLE
[Layout] Text overflow in ListView with flexDirection: 'row'

### ISSUE THREAD

**Issue by michalraska** [facebook/react-native#901]
Hi,
I have problem with text overflow in ListView, when ancestor has set style flexDirection: 'row':

![image](https://cloud.githubusercontent.com/assets/827753/7202066/e1ec56d8-e50e-11e4-9aa9-35cbc776b664.png)

part of code:
```javascript
  render: function() {
    return (
      <View style={styles.container}>
        <ListView
          dataSource={this.state.dataSource}
          renderRow={this.renderRow}
        />
      </View>
    );
  },

  renderRow: function (message, sectionID: number, rowID: number) {
    return (
      <View style={{flexDirection: 'row'}}>
        <Image
          source={{
            uri: 'http://icons.iconarchive.com/icons/designbolts/free-male-avatars/128/Male-Avatar-icon.png',
          }}
          style={{flexWrap: 'wrap', width: 32, height:32}}
        />
        <View style={{flexWrap: 'wrap'}}>
          <Text>
            {message}
          </Text>
        </View>
      </View>
    );
  },
```
How to wrap text?
Thanks.

**Comment by michalraska** [comment]
I solved problem by set `flex: 1` to wrapper view of text.
```javascript
      <View style={{flexDirection: 'row'}}>
        <Image
          source={{
            uri: 'http://icons.iconarchive.com/icons/designbolts/free-male-avatars/128/Male-Avatar-icon.png',
          }}
          style={{width: 32, height:32}}
        />
        <View style={{flex: 1}}>
          <Text>
            {message}
          </Text>
        </View>
      </View>
```

**Comment by brentvatne** [comment]
@michalraska - that's the right way to go! Thanks for updating with your solution, should be helpful to others who have the same issue.

**Comment by sjmueller** [comment]
Setting `flex: 1` will trigger the underlying text to wrap, but what if you want your view to grow with the text, and then wrap when it reaches the boundary?  
![wrap-example](https://cloud.githubusercontent.com/assets/29085/7334113/6dfa0d30-eb3d-11e4-9546-e9a83ab02795.png)

**Comment by sjmueller** [comment]
The temporary hack I'm using right now is conditionally adding `flex: 1`, based on the content length.  Of course this is pretty imprecise, and doesn't take into consideration orientation or variations in device resolution.

**Comment by despairblue** [comment]
@brentvatne I just found the this solution only works if `flex: 1` is apllied to the view immediately beneath the one where `flexDirection: 'row'` is being applied to.
Example: https://rnplay.org/apps/B8mUMw

If one removes the second view or applies `flex: 1` to it it works, otherwise it won't.

Is this intended behaviour?

**Comment by brentvatne** [comment]
@despairblue - initially I was a bit confused but realize that it does indeed make sense - by setting `flexDirection: 'row'` we are telling it to flex on the horizontal axis. If you change that to `column` on the `container` it works as you would expect.

**Comment by despairblue** [comment]
@brentvatne right, it's a contrived example, by not using row in the first place this does not happen, but let's assume I need to use row because I want to do something like @michalraska. I've updated the example above and made a drawing to elaborate on it: 

![2015-06-16 13 04 41](https://cloud.githubusercontent.com/assets/927609/8181713/bf67272a-1428-11e5-8acb-85680e2b0250.jpg)

It seems in row 1 the view with the question mark simply keeps growing to the right, thus the containing view never wraps. That's what I meant by *the view immediately beneath the one where `flexDirection: 'row'` is applied needs to have `flexDirection: 'column'` applied*. Knowing this it's perfectly fine to avoid it, though finding this out took me some time, I just wonder if this is intended behaviour?

**Comment by jawadrehman** [comment]
@brentvatne is there a way to do this without using flex : 1, in my case i have multiple components stacked across a view with flexDirection : 'row'

what i want is each component to render to its full width, and if it overflows then go to the next line. 

Using flex : 1, means that each component has the same width , which is not what i want, which means there's a lot of unwanted blank space. 


in the screenshot you can see that the first row has less space between the emoticon and the space character,  whereas the third row has far more spacing since other components aren't there


![ios simulator screen shot 16-jun-2015 4 48 48 pm](https://cloud.githubusercontent.com/assets/1839153/8187456/b1360c1a-1447-11e5-911a-4e6c9001df20.png)

thanks for any help that you provide :)

**Comment by brentvatne** [comment]
cc @vjeux - not quite sure about the above, maybe you have some insight

**Comment by jawadrehman** [comment]
ping @vjeux ? any ideas on this... i have to use webviews atm to get around this, and the performance isnt really great.

**Comment by abhoopathy** [comment]
I believe what you're trying to do isn't achievable with this layout system right now. I ran into the same problem. I solved this by creating a native bridge to a function which does something like this:
```
let label = UILabel()
label.font = UIFont(name: "Avenir", size: 16.0)
label.text = THETEXT
return label.intrinsicContentSize().width
```
![ios simulator screen shot jun 24 2015 10 49 01 pm](https://cloud.githubusercontent.com/assets/939823/8345925/9edf182c-1ac3-11e5-94d0-53a5cd267bd2.png)

**Comment by jawadrehman** [comment]
@abhoopathy Why didnt you try hooking that up directly in the RCTTextView.m or something like that ... wouldn't that make it much easier ? Plus also save computation on creating the unnecessary UILabel  ?

**Comment by abhoopathy** [comment]
That's probably a good idea. By not using the UILabel, are you suggesting using NSString's `sizeWithFont`? (discussed here http://stackoverflow.com/questions/1324379/how-to-calculate-the-width-of-a-text-string-of-a-specific-font-and-font-size)

**Comment by jawadrehman** [comment]
@abhoopathy maybe sizeWithAttributes would be better since sizeWithFont is deprecated . 
However, I think I should have said RCTText.m instead of RCTTextView.

**Comment by abhoopathy** [comment]
Good idea

**Comment by brentvatne** [comment]
@abhoopathy - any success with that?

**Comment by PhilippKrone** [comment]
Is there any update here? :)

**Comment by brentvatne** [comment]
Haven't heard back for *like, forever* (sorry I'm on a plane to LA, just embracing it), so I'm closing

**Comment by SudoPlz** [comment]
If you feel the same pain, please let the team know [HERE](https://productpains.com/post/react-native/row-contents-getting-off-screen-ie-cant-get-text-to-wrap-it-goes-off-screen)

**Comment by mschipperheyn** [comment]
This issue should not be closed. Basically, if you use flexDirection : 'row',  text wrapping doesn't work. There doesn't seem to be a clear workaround. Using flex : 1 now collapsed your content to nothing/invisible, so that workaround is gone. A very basic layout aspect is now a total time wasting nightmare. Please fix this!

**Comment by pqkluan** [comment]
If I have a layout like this
`
<View style={{flexDirection: 'row'}}>
    <Text>This text will be wrap into the second line, but it's not!</Text>
    <Text>This one will be pushed over into nothingness</Text>
</View>
`
The second child will be cut out instead of the first child wrap into the second line. Please fix this issue.

**Comment by mschipperheyn** [comment]
Since the previous product pain item seems to have disappeared (perhaps the FB team considered it solved), I have create a new one.

https://productpains.com/post/react-native/flexdirection-row-breaks-wrap-and-forces-content-off-screen

**Comment by valetarton** [comment]
try this on your view container @mschipperheyn I also had this issue, the the following property worked for me `flexWrap: 'wrap'`

**Comment by JeffreyLeeSpokeo** [comment]
I have the same issue as pqkluan.

**Comment by windhost** [comment]
Use alignItems: 'flex-start'
[https://github.com/facebook/react-native/issues/8960](url)

**Comment by serco-chen** [comment]
@sjmueller 
I know it's long ago but incase you are still interested in how to solve the problem about view growing with text.

Here's a solution. 
```jsx
<View style={{ flexDirection: row }}>
  <Avatar/>
  <View style={{ flex: 1, flexDirection: row }}> // message view
    <View style={{ borderWidth: 1 }}> // bubble view
      <Text>Message</Text>
    </View>
  </View>
</View>
```
1. Add `flex:1` to message view avoid text overflow. 
2. Put a bubble view inside the original message view and add `flexDirection: row` to message view to make bubble view grow with the text.

**Comment by frankmeza** [comment]
I also found my text disappeared when I styled its container with `flexDirection: "center".

``` javascript
// where's my text?!
text: {
    // styles
},
textContainer: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
},
```

What I did to get around was to put `textAlign: "center"` on the text itself.

``` javascript
text: {
        textAlign: "center",
},
textContainer: {
    flex: 1,
    justifyContent: "center",
},
```

Yes! Now I feel grounded, and *centered*.

**Comment by sjmueller** [comment]
Thanks for the pointer @serco-chen. To get pixel perfection, we had to start measuring our text in native-land. It's the only way to have the best of all worlds.

**Comment by ovy9086** [comment]
well FML @sjmueller . that sounds like a big problem in RNText than...
