### ISSUE TITLE
a suggestion for react native api docs' layout and classification

### ISSUE THREAD

**Issue by Jerry-goodboy** [facebook/react-native#9019]
As is known to all, IOS's and Android's components and interaction is so different, so I think docs of api should group it according to the ios and android platform, I think it will be read more clear, Do you guys agree with me?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/a-suggestion-for-react-native-api-docs-layout-and-classification

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
