### ISSUE TITLE
Inconsistent handling of overridden cookies between iOS and Android

### ISSUE THREAD

**Issue by mikekreeki** [facebook/react-native#9028]
Using `fetch` we are setting cookies manually in our requests to backend API using code similar to the following...

```js
function httpPost(path, body) {
  return fetch(path, {
    credentials: 'include',
    headers: {
      cookie: `api-csrf=${getApiCsrfToken()}`
    }
    method: 'post',
    body: JSON.stringify(body)
  });
}
```

The issue is that backend is returning us new `api-csrf` cookie in every response. We want to ignore it and override it with the value from `getApiCsrfToken()` function. On iOS this works, but on Android it does seem to ignore the custom cookie header and it sends the value from the cookie jar (returned in previous response from backend), not overriding with custom value.

Tested on RN 0.30.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/inconsistent-handling-of-overridden-cookies-between-ios-and-android

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
