### ISSUE TITLE
onLayout did not trigger on Android devices, react-native is v0.30.0

### ISSUE THREAD

**Issue by 12d** [facebook/react-native#9034]
'onLayout' of TextInput did not trigger on Android devices, react-native is v0.30.0

**Comment by mkonicek** [comment]
Can you please provide an example? See:
https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by StevenKing9** [comment]
I found this bug on a little android‘s device ，example ： 
Nexus and MEIZU

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/onlayout-did-not-trigger-on-android-devices-react-native-is-v0300

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by jjhesk** [comment]
this is still an issue version 0.38.0
