### ISSUE TITLE
【iOS】   fetch  https ，   NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9843)

### ISSUE THREAD

**Issue by roselind** [facebook/react-native#9061]
It  is run correctly， but  open  charles  it  wrong 。 I already  imported charles certificate and  all service's certificate to my project ,  But it's still wrong.    
Usually we are 3 servers, a is the publisher, a is the test server, a is the development server, usually need through the IP domain point to select a different server, but I found react native recommended by the fetch function can only be used to access the network server, does not have access to the internal server （ NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9843)  error） ， This is a great inconvenience for debugging new features, hope to improve。

Can encapsulate a network library to solve this problem？ you can refer to the solution of afnetworking  ：
- (BOOL)evaluateServerTrust:(SecTrustRef)serverTrust
                  forDomain:(NSString *)domain

**Comment by grabbou** [comment]
Please try asking your question on StackOverflow or looking for a similar /already asked/ issue, like this one: http://stackoverflow.com/questions/30778579/kcfstreamerrordomainssl-9802-when-connecting-to-a-server-by-ip-address-through

It seems to me that the issue is not specifically a React Native issue but more an iOS thing. You can always ask on Discord or in any other place where more people will be able to help.

We use Github issue tracker for bugs only to keep working effectively on React Native.

**Comment by roselind** [comment]
Thank you so much for seeing the problem.
 I know how to solve this problem by oc , But I can't find a way to solve this problem in  react native. 
I  Could not describe my problem. My problem is that  I used to code react-native app, by Charles connection service error.  The error message is as follows: NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9843).
(Charles is a proxy tool that is used to point to different servers)
 
 I am considering mixed development, using OC to write network modules. But the workload is far greater than just OC development.  A good tangle ah, hoping to find the answer to the problem in  react-native ，Any help will be appreciated.
