### ISSUE TITLE
TabBarIOS: TabBar overlays content

### ISSUE THREAD

**Issue by rkostrab** [facebook/react-native#9066]
Hello,

I am using RN 0.30.0 and I've noticed that bottom part content view is hidden under the tabbar.
Is it bug? If I could code iOS I'd do the PR.

**Comment by samkleeman1** [comment]
I have the same problem - part of my ListView is hidden under TabBarIOS

**Comment by samkleeman1** [comment]
By the way, the solution is to add `contentInset={{bottom:59}}` to your ListView code

**Comment by satya164** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-9** [comment]
Closing this issue as @satya164 says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.
