### ISSUE TITLE
Transform Order Backwards

### ISSUE THREAD

**Issue by jacobp100** [facebook/react-native#9073]
To make a diamond shape, I would expect the following to work.

``` js
transform: [
  { rotate: '45deg' },
  { scaleY: 0.5 },
],
```

However, this does not work. It seems to be doing the transforms in the reverse order, as reversing it achieves the desired result.

**Comment by DanielMSchmidt** [comment]
Hey,

I just did a bit of research, the problem seems to be that the [renderer loops over the transforms in the wrong direction](https://github.com/facebook/react-native/blob/bd60d828c5fc9cb066e5f647c87ecd6f70cb63a5/Libraries/StyleSheet/processTransform.js#L31). If `.forEach` doesn't loop in the wrong direction in Safari I would guess they are in the wrong order before this. My question would be if this problem occurs in production builds. If not I would go for the [`Object.freeze`](https://github.com/facebook/react/blob/222f5087fe1267921aaa5e2f600ea94455ee6d2a/src/renderers/native/ReactNativePropRegistry.js#L22) to change the order somehow.

**Comment by jacobp100** [comment]
I think the issue looks to be [here](https://github.com/facebook/react-native/blob/bd60d828c5fc9cb066e5f647c87ecd6f70cb63a5/Libraries/StyleSheet/processTransform.js#L98). I believe `MatrixMath.multiplyInto(out, a, b)` is performing `B*A` rather than `A*B` (important here). In the case where we’re going forward in the loop (we are), we want to do `A*B`.

I can’t quite tell whether this is the intended behaviour in MatrixMath, or is a bug. It either wants fixing in MatrixMath, or the call-site I pasted. Or maybe it doesn’t matter, as it’s only used once: in that call site!

Happy to submit a PR if we’re clear on direction.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/transform-order-backwards

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
