### ISSUE TITLE
Do we need to concern overdraw in Andriod with React native?

### ISSUE THREAD

**Issue by simidaxu** [facebook/react-native#9081]
I have a question, that is do we need to concern overdraw in Android with react native?
But I found that, it will be red if set view's background no matter how simple of this view. 
So, if need to concern this issue, how to? In many views, need to set background indeed.

**Comment by grabbou** [comment]
Hey, we use Github for issues only and all questions should be asked on StackOverflow. Please consider posting your question up there providing more details on what specifically you'd like to achieve! 

This is for us to keep the number of issues smaller so that we can iterate on React Native versions faster and provide you with the better developer experience. 

If you have any ideas on how we could improve the entire process, please share your thoughts on [React Native Community](https://www.facebook.com/groups/react.native.community/?ref=nf_target&fref=nf) group.
