### ISSUE TITLE
How to modify the state in the onLeftButtonPress?

### ISSUE THREAD

**Issue by a289459798** [facebook/react-native#9083]
How to modify the state in the onLeftButtonPress?Because I need to click to do animation, show or hide me is stored in the state

`
_getRoute(component) {

        var com = new component();
        return {
            component: component,
            title: com.getNavTitle(),
            passProps: { myProp: 'foo' },
            leftButtonIcon: com.getNavLeft().icon,
            onLeftButtonPress: com.getNavLeft().onPress,
            interactivePopGestureEnabled: true
        };
    }`

`getNavLeft() {

        return {
            icon: require('../Images/wo_de.png'),
            onPress: () => {
                console.log(this);

                this.setState({leftShow: true});

                Animated.timing(          // Uses easing functions
                    this.state.leftWidthAnim,    // The value to drive
                    {toValue: 0}          // Configuration
                ).start();
            }

        };
    }`

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-5** [comment]
Hey @a289459798 and thanks for posting this! @charpeni tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
