### ISSUE TITLE
unable to resolve modules 

### ISSUE THREAD

**Issue by alirezavalizade** [facebook/react-native#9085]
When Im install any package in my project And When I Want import in my module throw this error...
`import Swiper from 'react-native-swiper'`
Error :
<img width="370" alt="screen shot 2016-07-29 at 2 00 17 pm" src="https://cloud.githubusercontent.com/assets/14992757/17245124/598e1508-559a-11e6-909e-26c95fc3cd14.png">
im try this : 
```
watchman watch-del-all
rm -rf node_modules && npm install
npm start -- --reset-cache
```
but not working and again throw this error...

**Comment by charpeni** [comment]
It looks like an integration issue rather than an issue with React Native.

Are you sure you did the installation as mentioned in the [README](https://github.com/leecade/react-native-swiper#installation) of `react-native-swiper` ?

```
npm i react-native-swiper --save
```

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-5** [comment]
Hey @alirezavalizade and thanks for posting this! @charpeni tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by alirezavalizade** [comment]
@charpeni yes Im try deferent packages and again Im have this issue
