### ISSUE TITLE
react native upgrading issues

### ISSUE THREAD

**Issue by mvnpgh** [facebook/react-native#9087]
As of today we are using react-native 0.24.For the app purpose we are using 10 3rd party modules all those modules are based on recat-native 0.24.So my app is working smoothly.Today we are upgrade the react-native to 30.Now the trouble starts.Android structre is diffeent,and all other 3rd party modules gives an error messages.How can we resolve it.Can any one suggest me what i need to do.
Advance Thanks.

**Comment by ryankask** [comment]
There's some information in the release notes: https://github.com/facebook/react-native/releases/tag/v0.29.0

I'd also look at the dependencies' repos because they may have updated instructions or example projects.

**Comment by charpeni** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-5** [comment]
Closing this issue as @charpeni says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.
