### ISSUE TITLE
Changes is not updating

### ISSUE THREAD

**Issue by thiagoterleski** [facebook/react-native#9088]
Hi, I've been trouble with react-native, I start a new project with react-native init, install dependencies, all right without errors, but when i run my app with `react-native run-android` the app opens in my device but if I change any file, it's not refresh, not update, nothing changes, if i force to 'reload', the app is refreshed but my changes not appear, so i have to run `run-android` again for see my changes.

My node version is v4.4.7
react-native-cli: 1.0.0
react-native: 0.24.1

Thanks!

**Comment by Deain** [comment]
I've changed this "index.js"  and it worked....
"app_name\node_modules\react-native\node_modules\node-haste\lib\FileWatcher\index.js "
            var MAX_WAIT_TIME = 120000;==>>var MAX_WAIT_TIME = 360000;
Hope to help you

**Comment by charpeni** [comment]
Hi @thiagoterleski,

Did you installed watchman as described in the [Getting Started documentation](http://facebook.github.io/react-native/docs/getting-started.html#dependencies-for-mac-android) ? 

Watchman is uses to watch files and record when they change. It can also trigger actions (such as rebuilding assets) when matching files change.

Since you're trying to do a fresh react native project, the version of react native should be `0.30.0` instead of `0.24.1` ?

**Comment by thiagoterleski** [comment]
Hi @charpeni,

So, i'm using windows and i can't install watchman, my react native version is 0.30.

**Comment by OnMyWayHome** [comment]
found "react-native/packager/react-packager/src/DependencyResolver/FileWatcher/index.js"
then change "const MAX_WAIT_TIME = 120000" to "const MAX_WAIT_TIME = 360000"

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/changes-is-not-updating

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by anhnam00** [comment]
Please help me. 
My stack:
node:9.2.0
npm:5.5.1
react-native-cli: 2.0.1
react-native: 0.51.0

**Comment by BipinAle** [comment]
This worked for me. I had same issue but solved exporting path

echo 'export ANDROID_HOME=/Users/$USER/Library/Android/sdk' >> ~/.bash_profile
echo 'export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools' >>~/.bash_profile
then
source ~/.bash_profile

**Comment by anwarhamr** [comment]
I was having a similar issue.  Updates to index.js in RN 0.52 didn't update on actual phone.  Finally found that `rm -rf node_modules && npm install`
