### ISSUE TITLE
listview--why not refresh?

### ISSUE THREAD

**Issue by a289459798** [facebook/react-native#9098]
To modify the listview dataSource is one of the data, the listview why not refresh?

`//fetch server data
ProModel.fetchFactorys(function (resData) {

            that.state.factorys = resData.data;
            that.setState({
                factoryDS: that.state.factoryDS.cloneWithRows(that.state.factorys),
            });
}`

`_pressFactory(sectionID, rowID) {

        this.state.factorys[rowID].name = "ddd";
        this.setState({
            factoryDS: this.state.factoryDS.cloneWithRows(this.state.factorys),
        });
    }`

**Comment by grabbou** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-5** [comment]
Hey @a289459798 and thanks for posting this! @grabbou tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
