### ISSUE TITLE
demo run error

### ISSUE THREAD

**Issue by yanbober** [facebook/react-native#9109]
TTT@Thinkpad:~/learn/reactnative/AwesomeProject$ react-native run-android
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  You are currently running io.js v4.0.0-pre.                               │ 
 │                                                                            │ 
 │  React Native runs on Node 4.0 or newer. There are several ways to         │ 
 │  upgrade Node.js depending on your preference.                             │ 
 │                                                                            │ 
 │  nvm:       nvm install node && nvm alias default node                     │ 
 │  Homebrew:  brew unlink iojs; brew install node                            │ 
 │  Installer: download the Mac .pkg from https://nodejs.org/                 │ 
 │                                                                            │ 
 │  About Node.js:   https://nodejs.org                                       │ 
 │  Follow along at: https://github.com/facebook/react-native/issues/2545     │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
why？

**Comment by ryankask** [comment]
The error message indicates that you are using "io.js v4.0.0-pre". You need to upgrade to a newer version of Node.

Please look at the message as it tells you several ways you can go about upgrading.

**Comment by grabbou** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-4** [comment]
Closing this issue as @grabbou says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.
