### ISSUE TITLE
Get Error about Gradle Version

### ISSUE THREAD

**Issue by skatpgusskat** [facebook/react-native#9125]
I got message when I try build android version from source with command `react-native run-android` following this [docs](http://facebook.github.io/react-native/releases/0.30/docs/android-building-from-source.html), and the error message was

```
* What went wrong:
A problem occurred evaluating project ':ReactAndroid'.
> Failed to apply plugin [id 'com.android.library']
   > Gradle version 2.10 is required. Current version is 2.4. If using the gradle wrapper, try editing the distributionUrl in /Users/echo/Documents/test-react-native/AwesomeProject/android/gradle/wrapper/gradle-wrapper.properties to gradle-2.10-all.zip
```

Do we have to edit [cli](https://github.com/facebook/react-native/blob/235b16d93287061a09c4624e612b5dc4f960ce47/local-cli/generator-android/templates/bin/gradle/wrapper/gradle-wrapper.properties) to donwload Gradle's version for 2.10?

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/get-error-about-gradle-version

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
