### ISSUE TITLE
Building for production docs need updating

### ISSUE THREAD

**Issue by pvinis** [facebook/react-native#9138]
https://github.com/facebook/react-native/blob/0.30-stable/docs/RunningOnDeviceIOS.md

in this one, the part about uncommenting the `jsCodeLocation` line is outdated. now there is a line that checks for an env variable.

how should the production build happen now?

**Comment by hramos** [comment]
You no longer need to muck with `AppDelegate.m` to run on device, as `RCTBundleURLProvider` takes care of using the right URL. IIRC, you don't need to do anything to make sure it uses the offline bundle in production. 

Tagging the author of `RCTBundleURLProvider` for confirmation, @adamjernst.

**Comment by ferologics** [comment]
add the remote server ip in the info plist and that's it then?

**Comment by npomfret** [comment]
I wasn't able to get it to run on a device since RN0.29 without making changes to `AppDelegate.m`.   So it looks like this:

```
  #ifdef DEBUG
    jsCodeLocation = [NSURL URLWithString:@"http://192.168.1.64:8081/index.ios.bundle?platform=ios&dev=true"];
  #else
    jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];
  #endif
```

I found that adding an ip address to `Info.plist` doesn't work.  I read that it's because it only accepts domain names, and not ip addresses. My Info.plist has this:

```
	<key>NSAppTransportSecurity</key>
	<!--See http://ste.vn/2015/06/10/configuring-app-transport-security-ios-9-osx-10-11/ -->
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
```

Yes I know its a security hole, but I couldn't get anything else to work.

**Comment by pvinis** [comment]
[this](https://facebook.github.io/react-native/docs/running-on-device-ios.html) doesnt help too much either

**Comment by lacker** [comment]
Hector totally refactored this part so that the initially linked file doesn't exist any more. IMO the new version looks pretty good and improves this part. But, I could be wrong, so if there are still problems then I encourage people to open issues against the new docs for this part. This specific issue has been dealt with though so I am going to close this issue.
