### ISSUE TITLE
if you create a symlink pointing to .. it silently freezes the packager up to out of memory

### ISSUE THREAD

**Issue by gre** [facebook/react-native#9147]
``` bash
ln -s .. foo

react-native bundle --entry-file index.ios.js --bundle-output out
# aka a Release build
```

will infinitely freeze the packager without any error or any log. After like 40minutes, it ends with a out of memory. not very helpful DX :(

```
[10:27:33 PM] <START> Building Dependency Graph
[10:27:33 PM] <START> Crawling File System
[10:27:34 PM] <START> find dependencies
```

^ Stopped here

We had hard time figuring out the problem (and obviously we accidentally created that symlink) so YEAH it's not very critical. but it's a terrible experience when you fall into it and packager don't want to build JUST in Release mode..
so it would be great to fix it in some way, here is thoughts:
- packager to ignore symlinks (if it doesn't support it, drop it)
- prevent file exploration loop (going back again back in one of the explored folder should be forbidden)
- log a more useful warning when you traverse symlink.. (at least in DEBUG mode? even enabling the export DEBUG= thing didn't even helped!)

**Comment by grabbou** [comment]
cc: @Kureev (not sure if related to your change at all as it AFAIK hasn't landed yet, but still, might be useful to chime in)

**Comment by Kureev** [comment]
Hi @gre,

Thanks for your issue! Can you tell me which version of RN you are running? 

Myabe my assumption is wrong, but it seems that `ln -s .. foo` creates a circular dependency in your project. So it's not about symlinks, it's about the place they're pointing to. We can try to detect circular dependencies, but I'm not sure if it worth it.

**Comment by gre** [comment]
RN 0.29.1

sure it's totally wrong to do so, but maybe at least packager should be more helpful if it would log some warning (at least anything that prevent the current behavior of freezing without saying anything, it was hard to figure it out :D )

**Comment by Kureev** [comment]
@bestander should I pick this one up or it's gonna be changed anyway according to [your plan](https://www.facebook.com/notes/konstantin-raev/react-native-build-infrastructure-plans-for-the-second-half-of-2016/1201871896524548)?

**Comment by bestander** [comment]
Symlinks in the Packager paths are not supported now.
The reason is, as I was explained, in Mac filesystem not being consistent and correct when sending file change events on symlinked folders.

So we are in a status quo and just don't deal with symlinks and don't plan to do it in the next 6 months, unless Apple releases a fix on OSX.
@Kureev if you want to pick this one up, go ahead.

**Comment by gre** [comment]
symlink is not supported, but the packager still traverses my `root` symlink? sounds like somewhere, packager is trying to traverse the symlink where it shouldn't (if it's not supported)

**Comment by Kureev** [comment]
I'll try to take a deeper look into it when I have a time

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/if-you-create-a-symlink-pointing-to-it-silently-freezes-the-packager-up-to-out-of-memory

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
