### ISSUE TITLE
debuggerWorker.js:18Uncaught NetworkError: Failed to execute 'importScripts' on 'WorkerGlobalScope' Error

### ISSUE THREAD

**Issue by dazziola** [facebook/react-native#9150]
After much frustration and testing potential edge cases, I finally have some form of a debug connection between my computer and my physical device when running a basic (the init code) React Native app on an iPhone through XCode. I am unable to get a debug bridge or a hot reload workflow up and running. I can get these scenarios working on my work computer but not at home.

The connection is picked up by my **http://localhost:8081/debugger-ui** window, however React Packager does not establish a connection with a client. I am left with an uncaught network exception for _main.jsbundle_

![screen shot 2016-08-01 at 22 37 48](https://cloud.githubusercontent.com/assets/1335585/17309832/bf4b3b64-5838-11e6-8b1d-77c79afc9b28.png)

These problems are as a result of running `react-native init testApp` so no code modification have yet been made.

I can get around this error by disabling remote debugging, but that negates the usefulness of the tooling supplied by React Native in my opinion.

In the interest of brevity, the hot reloading and JS debug bridge **does** work in the virtual Simulator on the computer. I have also tried to change the IP address in **RCTWebSocketExecutor.m** to my computers local address. This alleviated prior issues (namely: **Runtime is not ready for debugging** and **WebSocket Connection failed Code=61** errors).

Hopefully someone has come across these problems.

My environment is:
Mac OSX 10.11.6
Node: 5.11.1
React-native: 0.30.0

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/debuggerworkerjs18uncaught-networkerror-failed-to-execute-importscripts-on-workerglobalscope-error

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by farooqmajeed** [comment]
![image](https://user-images.githubusercontent.com/17095804/27762098-ff504d60-5e83-11e7-81b8-8b5a841704ef.png)
kindly any one tell how to solve this issue

**Comment by wolverineks** [comment]
try disabling debugger, sometimes it masks the real error

**Comment by lionbur** [comment]
@ wolverineks  Yes, it worked for me (stopping debugging revealed the real error)

**Comment by futurechallenger** [comment]
@wolverineks It worked for me too. Just close the debugger page!
