### ISSUE TITLE
PureComponent doesn't work with hot reloading

### ISSUE THREAD

**Issue by steida** [facebook/react-native#9152]
No iOS nor Android.

**Comment by hijamoya** [comment]
Can you provide code

**Comment by steida** [comment]
https://github.com/este/este/blob/master/src/native/main.js

**Comment by steida** [comment]
Just create RN 30 or 31 app with React 15.3, and use PureComponent instead of Component. Hot reloading will not work.

**Comment by max-mykhailenko** [comment]
Hot reloading also doesn't work with function components.

**Comment by steida** [comment]
Hmm, maybe we can fix it just with rerendering whole app. But how?

**Comment by patrickgordon** [comment]
👍 

Same issue here with:
RN @ 0.32.0
React @ 15.3.2

**Comment by steida** [comment]
This is enough for hot reloading in React Native https://github.com/este/este/blob/master/src/native/app/Root.js#L13

**Comment by steida** [comment]
@dylanpyle I don't use PureComponent anymore. It's a workaround to issue which is better to avoid. shouldUpdate belongs to data, not to a component because it slow downs PureComponent first render. redux-connect does it on data change, which is better. So, don't use PureComponent. Check Este https://github.com/este/este

**Comment by johnculviner** [comment]
@orta This still appears to be an issue (for me at least).

HMR doesn't work unless I switch stuff to Component instead of PureComponent for

```"react-native": "^0.47.1",```

I understand @steida says don't do it but that appears to be in the specific context of you using redux/connect which understandably isn't everyone's scenario (especially not for every component in an entire application)

Should this issue remain open or what am I missing about how it was fixed to be closed? 

Thank you for any insight you can provide 🍻

**Comment by rafeca** [comment]
Sorry for the delay with this issue, this had been fixed in https://github.com/gaearon/babel-plugin-react-transform/pull/106 and the fix will go to RN v0.50 😄

**Comment by tafelito** [comment]
I know this is an old issue but I'm having this issue using FlatList. I have a class component that renders a List with a ListHeaderComponent. If I change anything on the component, the list is not being updated.
Should I open a new issue for this?
