### ISSUE TITLE
Packager translation issue for escaped unicode characters

### ISSUE THREAD

**Issue by igrayson** [facebook/react-native#9153]
Specific code using escaped unicode characters behaves very differently after translated through packager.

Here's the input source:

```
exports.NON_BREAKING_HYPHEN = String.fromCharCode(8209);
function noBreak(str) {
    return str.replace(/[\-\–]/g, exports.NON_BREAKING_HYPHEN);
}
```

Translation when using the dev server:

```
exports.NON_BREAKING_HYPHEN=String.fromCharCode(8209);
function noBreak(str){
     return str.replace(/[\-\–]/g,exports.NON_BREAKING_HYPHEN);
}
```

Example execution:

```
noBreak('8:00a-10:30a')
> "8:00a‑10:30a"
```

Translation when packing an offline bundle:

```
__d(629,function(e,r,N,E){"use strict";function o(e){return e.replace(/[\-\\u2013]/g,E.NON_BREAKING_HYPHEN)}
```

Example execution:

```
noBreak('8:00a-10:30a')
> "8:‑‑a‑‑‑:‑‑a"
```

The original code is being somewhat malicious -- it provides escape `\`s for characters that do not need to be escaped -- but it executes just fine when run directly in `node` REPL, a chrome dev console, and in react-native compiled via the dev server.

The offline-translated code was compiled using this command:

```
node ./node_modules/react-native/local-cli/cli.js bundle \
  --reset-cache \
  --entry-file index.ios.js \
  --dev false \
  --platform ios \
  --bundle-output main.jsbundle \
  --sourcemap-output main.jsbundle.map \
  --assets-dest assets
```
- RN version: 0.27.2
- iOS and Android
- Tested on OSX.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/packager-translation-issue-for-escaped-unicode-characters

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
