### ISSUE TITLE
Custom actions in ToolbarAndroid display none when TextInput focus

### ISSUE THREAD

**Issue by sunkuiwei** [facebook/react-native#9199]
## initial page

![](http://i.stack.imgur.com/Rs8j3.png)

## Custom actions in ToolbarAndroid looks like this when longPress item

![](http://i.stack.imgur.com/8P0On.png)

## They will be marked and back when press custom actions in ToolbarAndroid

![](http://i.stack.imgur.com/2ZkmM.png)

## enter search page when press the search icon in the custom actions

![](http://i.stack.imgur.com/3RX7P.png)

## press the back icon to return and noting to do

![](http://i.stack.imgur.com/e6Cq9.png)

## enter search page again and focus TextInput to display keyboard and return
![](http://i.stack.imgur.com/SC044.png)

## !!! Custom actions in ToolbarAndroid display none when I longPress Item again

![](http://i.stack.imgur.com/k7lYN.png)

  [1]: http://i.stack.imgur.com/Rs8j3.png
  [2]: http://i.stack.imgur.com/8P0On.png
  [3]: http://i.stack.imgur.com/2ZkmM.png
  [4]: http://i.stack.imgur.com/3RX7P.png
  [5]: http://i.stack.imgur.com/e6Cq9.png
  [6]: http://i.stack.imgur.com/SC044.png
  [7]: http://i.stack.imgur.com/k7lYN.png

**Comment by sunkuiwei** [comment]
@DanielMSchmidt

**Comment by DanielMSchmidt** [comment]
Sorry, but this needs more information about the code, to be specific the parts that may cause the problem. Please provide an example with [RNPlay](https://rnplay.org/) and post it on StackOverflow instead of here as an issue, this place is more appropriate. It would be just a real issue if you could provide a small example showing this bug. If you have the RNPlay example and StackOverflow Question, please leave me a note here and I will have a look at it.

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-4** [comment]
Hey @sunkuiwei and thanks for posting this! @DanielMSchmidt tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by stephanemaillard** [comment]
Hello @Gmonking I currently have the same issue, did you find a way to manage it?

**Comment by jaystramel** [comment]
I wrote up a similar (maybe the same) issue here:  https://github.com/facebook/react-native/issues/11209

**Comment by vonovak** [comment]
@Gmonking did you solve this?

**Comment by chenvan** [comment]
I have the same problem, hope to get a solution
