### ISSUE TITLE
windows Generating Signed APK Failed

### ISSUE THREAD

**Issue by SeananXiang** [facebook/react-native#9204]
### The error is as follows

![image](https://cloud.githubusercontent.com/assets/5298972/17395215/dea55606-5a5f-11e6-8ee4-fa258f040177.png)

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/windows-generating-signed-apk-failed

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by ohtangza** [comment]
@facebook-github-bot Close
