### ISSUE TITLE
Error in onvaluechange function in Picker Cannot read property 'props' of undefined 

### ISSUE THREAD

**Issue by waqas19921** [facebook/react-native#9209]
whenever i change value of picker following error occurs 
![error](https://cloud.githubusercontent.com/assets/17469425/17402656/c6b06c44-5a6d-11e6-9d59-e662467e1ace.png)

**Comment by ryankask** [comment]
Please post a code so we can better understand if this is a bug or another issue. Thanks!

@facebook-github-bot label Needs more information

**Comment by ryankask** [comment]
@facebook-github-bot label Needs more information

**Comment by waqas19921** [comment]
Here is the code i have used 

```
constructor(props) {
    super(props);
    this.state = {
      city: ''
    };
  }

```
```
<View style={styles.field}>
            <Text>Select city</Text>
            <Picker style={styles.picker} selectedValue={this.state.city}
                    onValueChange={city=> this.setState({city: city})}>
              <Item label='None' value="-1"/>
              {this.props.cities.map((city, key)=> {
                return (
                  <Item label={city.name} key={key} value={city._id}/>
                )
              })}
            </Picker>
          </View>
```

**Comment by waqas19921** [comment]
Here is the picker shown 
![device-2016-08-05-105507](https://cloud.githubusercontent.com/assets/17469425/17427577/2b6dd0b2-5afb-11e6-8814-5d6bb0740c5b.png)

After i select the city above read screen appears saying `cannot read property Props of undefined`

**Comment by waqas19921** [comment]
@facebook-github-bot check now

**Comment by ryankask** [comment]
This issue is that Picker doesn't like the shape of the child Item objects. The problematic Item is the one with the label 'None'. 

If you want to fix this now you should flatten the children in `Picker`. Check out this related PR: https://github.com/facebook/react-native/pull/8153 as it involves the same issue.

**Comment by ryankask** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-4** [comment]
Closing this issue as @ryankask says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.
