### ISSUE TITLE
Portal is undefined in android

### ISSUE THREAD

**Issue by nilaybrahmbhatt** [facebook/react-native#9210]
Hi,
I am using new version of android.

and i am trying to use Portal

but it gives error " Portal is undefined"

what i use instead of "Portal"

**Comment by mlabrum** [comment]
Hi @nilaybrahmbhatt 

Portal is no longer used, use `<Modal/>` instead
https://facebook.github.io/react-native/docs/modal.html

Cheers,

**Comment by satya164** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-4** [comment]
Closing this issue as @satya164 says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.
