### ISSUE TITLE
Android: Picker triggers odd onValueChange when initialized with selectedValue which is first item in options

### ISSUE THREAD

**Issue by antonKalinin** [facebook/react-native#9220]
As in title: when initializing Picker component in Android with prop 'value' equals to value of first option, the odd onValueChange triggers. If prop 'value' equals to any other options value, everything is ok. iOS is ok.

RNPlay: https://rnplay.org/apps/DqxK9g

**Comment by KGALLET** [comment]
+1 having the same issue

**Comment by nezaidu** [comment]
+1 having the same issue. react-native: 0.26.2

**Comment by nezaidu** [comment]
my workaround:
`<View style={{width: 300}}>`
`  <Picker`
`    onValueChange={this.selectServiceCategory}`
`    selectedValue={"disabled"}`
`    mode="dropdown"`
`   >`
`   {Platform.OS == "android" ?`
`      (pickers.push(<Picker.Item label={""} value={"disabled"} key={""} />) && pickers)`
`    :`
`      (pickers)`
`   }`
`  </Picker>`
`</View>`

**Comment by wolframkriesing** [comment]
I made a workaround, that looks like this
```
  const weHaveAVersionWithThisBug = !!'https://github.com/facebook/react-native/issues/9220';
  const workAround = value => { if (value!==selectedValue) onChange(value); };
  const onValueChange = weHaveAVersionWithThisBug ? workAround : onChange;
  return (
    <Picker
      selectedValue={ selectedValue }
      onValueChange={ onValueChange }
    >
```
works for me now, and I know why this crap is in there :)

**Comment by antonKalinin** [comment]
Looks like this commit could fix the problem (as it described in release notes) but I haven't checked yet. 

https://github.com/facebook/react-native/commit/a2a8d7f5da93ee10cf5eccfb944f581f43cfe0c0

**Comment by jurcovicova** [comment]
+1 I would be thankful if this one got fixed. I had to use rather ugly workaround due to the way this interacted with other systems we use on frontend.

**Comment by gyzerok** [comment]
I guess [this](https://github.com/facebook/react-native/issues/6472) is related.

Looks like issue is still relevant.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, it does not seem like there has been any traction on this issue for some time.

The issue is being copied over to our feature request tracker at Canny: https://react-native.canny.io/admin/board/feature-requests/p/android-picker-triggers-odd-onvaluechange-when-initialized-with-selectedvalue-wh

There you can upvote issues that are important to you. This will help contributors identify the issues that the community cares about.

If you think this issue should definitely remain open here in the issue tracker and not on Canny, let us know.
