### ISSUE TITLE
NavigationBar Doesn't offset the content scene's height

### ISSUE THREAD

**Issue by tonyrzhang** [facebook/react-native#9221]
Hello!

I'm currently using a Navigator with a NavigationBar as well. The issue I'm running into, is that when the scene is being rendered, it doesn't seem to take into account the space that the nav bar takes up, so part of it is blocked by the nav bar.

I can use paddingTop inside the scene to move it down, but I figure that it would be better if the content's canvas started below the navbar.

Here's an example:
![screen shot 2016-08-04 at 1 49 52 pm](https://cloud.githubusercontent.com/assets/8292111/17417858/5d385b32-5a4a-11e6-9e2c-f5acedb77445.png)

**Comment by satya164** [comment]
It's intentional. `NavigationBar` is absolutely positioned. Which allows you to emulate iOS behaviour of scrolling content under translucent navigation bar.

@facebook-github-bot answered

**Comment by tonyrzhang** [comment]
@satya164 I see. Can you recommend a best practice for rendering the page's content beneath the nav bar?

**Comment by ryankask** [comment]
You can use `paddingTop` for the scene. You can get the height from NavigationBarStyles (https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/Navigator/NavigatorNavigationBar.js#L42 and https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/Navigator/NavigatorNavigationBar.js#L155).

Interesting related commit for NavigationExperimental: https://github.com/facebook/react-native/commit/38979f9c68bd054aca3c6102635b2005914506b1

**Comment by ryankask** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-4** [comment]
Closing this issue as @ryankask says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

**Comment by tonyrzhang** [comment]
@ryankask Awesome. Thx!
