### ISSUE TITLE
Unable to dismiss Modal in iOS when used with NavigationExperimental

### ISSUE THREAD

**Issue by ng-marcus** [facebook/react-native#9228]
I use Modal to display a progress screen whilst I fetch data from the server.

In normal interactions this works fine - the user taps the button, I show the modal, make the call and render again with the modal set to not visible, and it goes away.

Using 0.31, using NavigationExperimental and NavigationCardStack if I make the server call as part of componentDidMount, where that call is wrapped in a runAfterInteractions block, the modal won't clear.   Even using the Apple-R key to reload the app re-renders the app but leaves the modal in place.

My initial thought was to  use onTransitionStart and onTransitionEnd to make sure the transition was finished before showing the modal but these aren't available in NavigationCardStack.

I'm guessing the issue is because the Modal component is rendering a native Window and this isn't getting cleared somewhere.  I'll dig into the code to see if I can see the problem, but if anyone can point me in the right direction that would be great.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/unable-to-dismiss-modal-in-ios-when-used-with-navigationexperimental

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
