### ISSUE TITLE
max-height: "parent"

### ISSUE THREAD

**Issue by fab1an** [facebook/react-native#9229]
There seem to be layouts that can't be done in FlexBox without the notion of a containing parent-elements. Example:
- Have a list with items and a fixed footer
- If the list is small it will shrink and show it's contents
- If the container including the list and the button get's too large, the list will be scrollable.

![screen shot 2016-08-05 at 09 44 09](https://cloud.githubusercontent.com/assets/55547/17429830/2e901480-5af1-11e6-95f5-7f034a942791.png)

For this to work I have to set `max-height` to some value (relative to ScreenSize or so). What I want to do it do set `max-height` to never exceed some parent-view, which then is defined using normal paddings and margins. Otherwise I lose some responsiveness of my design.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/max-height-parent

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
