### ISSUE TITLE
Android TV/Apple TV supports

### ISSUE THREAD

**Issue by tadjik1** [facebook/react-native#9230]
Hey there!

Just want to ask any plans to support Android TV/Apple TV?

**Comment by charpeni** [comment]
Fork of React Native that adds Apple TV support : https://github.com/douglowder/react-native-appletv/blob/master/README-appletv.md

**Comment by rmevans9** [comment]
Since the fork basically answers the original question I am closing this out.

@facebook-github-bot answered

**Comment by rmevans9** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-5** [comment]
Closing this issue as @rmevans9 says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.
