### ISSUE TITLE
Animated.ValueXY not working for contentOffset for <ScrollView>

### ISSUE THREAD

**Issue by cameronbourke** [facebook/react-native#9231]
I'm not sure whether this in the incorrect use the API, or a bug per say. However, I have already posted an issue on StackOverflow addressing this very question, but yet to get a reply so I thought it would be appropriate to now create an issue.

http://stackoverflow.com/questions/38671101/react-native-cannot-animate-contentoffset-scrollview-using-animated-valuexy

Hopefully it is just me being thick, and this issue can be closed asap!

This is occurring for react-native v30 on iOS, on a Mac.
Thank you.

**Comment by ryankask** [comment]
This previous issue suggests what you're trying to do isn't possible: https://github.com/facebook/react-native/issues/3911. I have no idea if this would work but you could play around with adding a listener to the animated value and then using setNativeProps.

You're probably trying to do something more complex but there is a `scrollTo` method: https://facebook.github.io/react-native/docs/scrollview.html#scrollto

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/animatedvaluexy-not-working-for-contentoffset-for-scrollview

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
