### ISSUE TITLE
Issue Referencing component created with 'createAnimatedComponent'

### ISSUE THREAD

**Issue by KishPatel1996** [facebook/react-native#9239]
I have wrapped a scrollview in the animated component, and whenever I try to reference scrollview to, let's say, scroll to the top, it is not defined.  This works when the component is not wrapped.

For reference, here's my code

```
<AnimatedScrollView

          onLayout={() => this.scrollView.scrollTo({y: 20, animated: false})}
          ref={(ref) => this.scrollView = ref}
          style={{flex: 1,}} 
          keyboardDismissMode='on-drag'
          directionalLockEnabled={true}
```

**Comment by ide** [comment]
`scrollTo` is a method of ScrollView, not the Animated wrapper component. You can probably get at the wrapped component via `wrapperComponent.refs.node` but I'll warn you that the `node` ref is an implementation detail and could change in a future release so if you go this route be extra sure to keep an eye on changes to createAnimatedComponent.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/issue-referencing-component-created-with-createanimatedcomponent

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by a9udn9u** [comment]
For people searching for solution: #9944
