### ISSUE TITLE
running android with different version

### ISSUE THREAD

**Issue by georgi-kovachev** [facebook/react-native#9246]
Whenever I try to run on android emulator
'react-native run-android'
it says "ailed to find target with hash string 'android-23'"
I have configured AVD device for android-21 to test the app for old device.
How can I change the app running from android-23 to android-21?

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-4** [comment]
Hey @georgi-kovachev and thanks for posting this! @charpeni tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
