### ISSUE TITLE
Failed to parse SourceMap because of "freeProcess.binding is not a function"

### ISSUE THREAD

**Issue by jaggerwang** [facebook/react-native#9256]
I'm not sure it's a problem of RN or third party modules. App can run if disable "Pause on Caught Exceptions".
### ENV

Mac OS 10.11.6
RN 0.29
### Screenshot

![image](https://cloud.githubusercontent.com/assets/1255011/17455144/91cbf258-5be1-11e6-8e11-64961d380600.png)
![image](https://cloud.githubusercontent.com/assets/1255011/17455150/ae895cf0-5be1-11e6-8ec4-1bb41fc1d735.png)

If disable "Pause on Caught Exceptions", app can run, but without SourceMap.
![image](https://cloud.githubusercontent.com/assets/1255011/17455193/c9d78026-5be2-11e6-801b-80741ee0fe5e.png)

**Comment by TheIndianRaj** [comment]
I am having the same issue.

**Comment by Pro-YY** [comment]
having the same issue, too.

**Comment by IlyaRepo** [comment]
Having same issue

**Comment by TiuSh** [comment]
Having the same issue with RN 0.33

**Comment by whkailee** [comment]
Having the same issue with RN 0.37

**Comment by hramos** [comment]
Can you reproduce this on [rnplay.org](https://rnplay.org/)? Please provide a link.

**Comment by onpaws** [comment]
I tried debugging on a real device (i.e. not using the Simulator) and the issue happened there too, albeit without the SourceMap error. Just the `freeProcess.binding` one

@hramos I suspect you'll find this easy to repro.

RN 0.33

**Comment by yanni4night** [comment]
Same with RN 0.35

**Comment by janreyho** [comment]
Same with RN 0.41

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
