### ISSUE TITLE
RCTView displayLayer optimization? [iOS]

### ISSUE THREAD

**Issue by ATS-RyanPowell** [facebook/react-native#9261]
Within method `[RCTView displayLayer:]` rendering occurs even if the view is hidden or opacity = 0

There may be benefit to exiting prematurely in this method if either condition is met.

This could occur if hidden=YES & then you proceed to set any border property as these call

```
  [self.layer setNeedsDisplay];
```

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/rctview-displaylayer-optimization-ios

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
