### ISSUE TITLE
[android] borderRadius + borderBottom

### ISSUE THREAD

**Issue by n7olkachev** [facebook/react-native#9262]
RN 0.31
Example:

```
<View style={{ padding: 14, backgroundColor: '#ffa42f', borderRadius: 4, borderBottomWidth: 2, borderColor: '#dc5400' }}>
    <Text style={{color: '#f5f6fa', textAlign: 'center'}}>Text</Text>
</View>
```

Works fine on iOS, but not on Android (the bottom border isn't showing).

**Comment by RichardLindhout** [comment]
Maybe the border overlaps the view, in Android all views are overflow hidden. Maybe do elevation. Or do a wrapper around it with a paddingBottom: 1.

**Comment by n7olkachev** [comment]
Nope.
Also, found that the problem occurs only when I use `borderBottomWidth`, `borderTopWidth` etc, while using `borderWidth` border is showing (on each side of View).
Any other ideas?

**Comment by RichardLindhout** [comment]
I`ll look at it Monday. I have no experience but it would definitily work
with soms very dirty hacks

Op 6 aug. 2016 20:18 schreef "Nick Tolkachev" <notifications@github.com>:

**Comment by RichardLindhout** [comment]
You could do a wrapper view with 2px bottom padding and #dc5400 as background do the rest of the view te same inside but without the bottom border.

**Comment by kamek-pf** [comment]
This is somewhat similar to #7838

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-borderradius-borderbottom

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by RyanMitchellWilson** [comment]
Still happening can this be reopened?
