### ISSUE TITLE
fetch giving possible unhandled promise rejection

### ISSUE THREAD

**Issue by sachinvelaga** [facebook/react-native#9268]
This is the code . I cannot understand where i am going wrong. The same url works directly on browser but if i build it and use it in fetch , it gives possible unhandled promise rejection. Help please. 

fetch(api.predictupdate+JSON.stringify(object))
                                 .then((response) => response.json())
                                 .then((responseData) => {
                                         fetch(api.searchservice+responseData)
                                                 .then((response) => response.json())
                                                 .then((responseData) => {
                                                          console.log(responseData);
                                                       })
                                                 .catch(function(err) {
                                                            return err;
                                                          });
                                       });

**Comment by npomfret** [comment]
There's a bit of error handling missing.  Try this:

```
    const url = api.predictupdate + JSON.stringify(object);
    console.log("url", url);
    fetch(url)
      .then((response) => response.json())
      .then((responseData) => {
        return fetch(api.searchservice + responseData)
          .then((response) => response.json())
          .then((responseData) => {
            console.log(responseData);
          })
      })
      .catch(function (err) {
        return err;
      });

```

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/fetch-giving-possible-unhandled-promise-rejection

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
