### ISSUE TITLE
[Documentation] Using Navigators

### ISSUE THREAD

**Issue by kurapikats** [facebook/react-native#9270]
The instructions on **Using Navigators** at https://facebook.github.io/react-native/docs/using-navigators.html doesn't work and needs updating.
1. **AppRegistry** wasn't imported.
2. **getDefaultProps** was used on an ES6 class component.

**Comment by charpeni** [comment]
@facebook-github-bot label Documentation

**Comment by charpeni** [comment]
Thank you for reporting.

Are you up to send a pull request?

**Comment by kurapikats** [comment]
Sure np. Currently downloading my forked copy.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/documentation-using-navigators

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by jt3k** [comment]
I found this broken link on page http://facebook.github.io/react-native/docs/network.html below (link to `/docs/using-navigators.html`)

But could not find a place where it can be fixed it to send a PR
