### ISSUE TITLE
bridge variable null after getting callback from authentication

### ISSUE THREAD

**Issue by Brockify** [facebook/react-native#9277]
Hey guys i'm trying to setup some authentication and my 

`@synchronize bridge = _bridge;`

all works perfectly and I can use this + the event dispatcher to send events to JS, but when I call an authetnication and get a return in my function
'// Handle auth callback
-(BOOL)application:(UIApplication *)application
           openURL:(NSURL *)url
 sourceApplication:(NSString *)sourceApplication
        annotation:(id)annotation {
  // Ask SPTAuth if the URL given is a Spotify authentication callback
  if ([[SPTAuth defaultInstance] canHandleURL:url]) {
    [[SPTAuth defaultInstance] handleAuthCallbackWithTriggeredAuthURL:url callback:^(NSError *error, SPTSession *session) {

```
  if (error != nil) {
    NSLog(@"*** Auth error: %@", error);
    return;
  }

  if(self.bridge == nil)
  {
    NSLog(@"Nil");
  } else {
    NSLog(@"Not nil");
  }

  // Call the -loginUsingSession: method to login SDK
  [self loginUsingSession:session];
}];

return YES;
```

  }
  return NO;
}'

it is null. How can I make this an instance variable / grab that specific instance variable?

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/bridge-variable-null-after-getting-callback-from-authentication

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
