### ISSUE TITLE
Reload problem

### ISSUE THREAD

**Issue by uc-asa** [facebook/react-native#9278]
Hi,

React native team developer I am using react native 0.30 version when reload app using ctrl+then generate error and after more 2 times reload it work how to resolve this problem and work with first reload

**Comment by OnMyWayHome** [comment]
If you hit a ERROR Watcher took too long to load on Windows, try increasing the timeout in [this file](https://github.com/facebook/react-native/blob/5fa33f3d07f8595a188f6fe04d6168a6ede1e721/packager/react-packager/src/DependencyResolver/FileWatcher/index.js#L16) (under your node_modules/react-native/).

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/reload-problem

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
