### ISSUE TITLE
how to import WebSocket from "react-native"?

### ISSUE THREAD

**Issue by anguskwan** [facebook/react-native#9286]
my env:
```
  "dependencies": {
    "lodash": "^3.10.1",
    "react": "~15.2.1",
    "react-native": "^0.31.0",
    "react-native-config": "0.0.7",
    "react-native-device-info": "^0.9.3",
    "react-native-orientation": "^1.17.0",
    "react-native-pomelo": "0.0.1",
    "react-native-wechat": "^1.5.3",
    "react-redux": "^4.4.5",
    "redux": "^3.5.2",
    "redux-logger": "^2.0.4",
    "redux-thunk": "^2.1.0"
  },
```

https://github.com/facebook/react-native/blob/0.31-stable/Libraries/react-native/react-native.js#L72
seems from this code ,WebSocket is not require default. cannot do such import 
```
import {WebSocket} from 'react-native';
```
when click on WebSocket function in WebStorm Editor, it refers to HTML5.js!

after adding   ```get WebSocket() { return require('WebSocket'); },``` to react-native.js,  import works.

but i still cannot fire a correct connection to remote ws server.
```
    socket = new WebSocket(url);
    socket.binaryType = 'arraybuffer';
    socket.onopen = onopen;
    socket.onmessage = onmessage;
    socket.onerror = onerror;
    socket.onclose = onclose;
```

socket close event is trigger. but onerror, onopen never triggered. seems it never connect.
server works perfect on react web. 

can anyone tell me what i am missing , and share a working code, thanks .........

**Comment by satya164** [comment]
`WebSocket` is a global object, so you don't need to import it.

Checkout the example for usage - https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/WebSocketExample.js

@facebook-github-bot answered

**Comment by satya164** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-4** [comment]
Closing this issue as @satya164 says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.
