### ISSUE TITLE
"Missing form parameter: grant_type" issue

### ISSUE THREAD

**Issue by alokverma65977** [facebook/react-native#9290]
Getting **Object {error_description: "Missing form parameter: grant_type", error: "invalid_request"}** error while I request with fetch service .Issue in the react-native while request with **'Content-Type': 'application/x-www-form-urlencoded'** this content type.

fetch(`${URL, {
          method: 'POST',
          headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/x-www-form-urlencoded',
          },
          body: JSON.stringify({
                  username: value.username,
                  password: value.password,
                  grant_type: "password",
                  client_id: Global.private.keycloak.clientId,
                  client_secret: Global.private.keycloak.secret

```
      })
```

Request you to solve the issue with the application/x-www-form-urlencoded' type of data.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/missing-form-parameter-granttype-issue

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
