### ISSUE TITLE
debuggerWorker doesn't relay postMessage'd events

### ISSUE THREAD

**Issue by blackxored** [facebook/react-native#9300]
Debugger worker doesn't seem to relay postMessage events, other than those required for the communication. It works on JSC but not on Chrome debugger obviously.

How to reproduce:
1. Sub to `message` events: 

``` javascript
addEventListener('message', (message) => ...)
```
1. Emit an event via `postMessage`:

``` javascript
window.postMessage({foo: 'bar'});
```

Messages other than RN's internals are never received in that event listener.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/debuggerworker-doesnt-relay-postmessaged-events

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
