### ISSUE TITLE
[0.31] onlyChild must be passed a children with exactly one child

### ISSUE THREAD

**Issue by kLkA** [facebook/react-native#9305]
Hi, I'm developing app with LG Nexus 5 and version 0.31.
i have a code
```php
<TouchableNativeFeedback onPress={this.loginVK}>**SPACE**<View style={{
          width: 150,
          height: 100,
          backgroundColor: 'bisque'
        }}><Text style={{margin: 10}}>BUTTON</Text></View>

        </TouchableNativeFeedback>
```
When i place space symbol between Touchable Native open tag and View open tag
with enabled Hot Reloading module it shows me error: Only Child must be passed a children with exactly one child. Enter symbol is processed well.
web console log:
```
handleException	@	ExceptionsManager.js:61
handleError	@	InitializeJavaScriptAppEngine.js:115
reportFatalError	@	error-guard.js:30
guard	@	MessageQueue.js:43
callFunctionReturnFlushedQueue	@	MessageQueue.js:94
onmessage	@	debuggerWorker.js:39
```
error on mobile:
![image](https://cloud.githubusercontent.com/assets/5596845/17510746/dde79fea-5e28-11e6-8a12-5eb509cb494d.png)

after reloading the app error become different
![image](https://cloud.githubusercontent.com/assets/5596845/17510814/21780e2a-5e29-11e6-8e47-ef0b7de29602.png)

**Comment by satya164** [comment]
space is counted as a string. just place it in a new line and you should be fine.

@facebook-github-bot answered

**Comment by satya164** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-5** [comment]
Closing this issue as @satya164 says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

**Comment by kLkA** [comment]
Don't you think that this error is totally unclear ?

**Comment by satya164** [comment]
@kLkA You're right. This error is coming from `React.Children` though, so it'll be better to file a bug report against https://github.com/facebook/react to improve the error message.
