### ISSUE TITLE
[Android] onSubmitEditing is called twice when keyboard is dismissed in android

### ISSUE THREAD

**Issue by CocoaHoo** [facebook/react-native#9306]
I want to get current text from TextInput when keyboard is dismissed by pressing search button. In order to get the text, I use onSubmitEditing but it is called twice only if I set returnKeyType to 'search'. Here is a code snippet.

```
render() {
return (
<View style={{flex:1, justifyContent:'center'}}>
        <TextInput
          style={{alignSelf:'stretch'}}
          onChangeText={(searchInput) => this.setState({ searchInput }) }
          placeholder='Search'
          returnKeyType='search'
          onFocus={() => console.log('onFocus')}
          onBlur={() => console.log('onBlur')}
          onChange={(event) => console.log('onChange text: ' + event.nativeEvent.text)}
          onEndEditing={(event) => console.log('onEndEditing text: ' + event.nativeEvent.text)}
          onSubmitEditing={(event) => console.log('onSubmitEditing text: ' + event.nativeEvent.text)}
        />
      </View>
    );
  }

```

and no one answer the question in stackoverflow [http://stackoverflow.com/questions/38710253/onsubmitediting-is-called-twice-when-keyboard-is-dismissed](http://stackoverflow.com/questions/38710253/onsubmitediting-is-called-twice-when-keyboard-is-dismissed)

**Comment by CocoaHoo** [comment]
solve this issue by use textinput.blur
```
<TextInput
  ref={component => this._textInput = component}
  onSubmitEditing={this._onSubmitEditing.bind(this)}
  onEndEditing={this._onPressSearch.bind(this)}
  returnKeyType='search'
  style={styles.inputText}/>

  _onSubmitEditing(){
    this._textInput.blur();
  }
  _onPressSearch(event){
    console.log(event.nativeEvent.text);
  }
```

**Comment by viix** [comment]
meet the same problem, should be RN's bug?

**Comment by CocoaHoo** [comment]
@viix maybe it's a bug, but u can solve this above

**Comment by viix** [comment]
@CocoaHoo so I think it better to open the issue to let facebook guys be aware of the bug.

**Comment by holyxiaoxin** [comment]
I'm facing this as well, experienced it in RN 0.30.0.
Currently using debounce to overcome this. 

`onEndEditing` fires once but you don't want to call your method on end editing because this might mean that blurring it when pressing somewhere else on the screen might cause the method to trigger too.

**Comment by CocoaHoo** [comment]
@holyxiaoxin thx,I get it, using debounce is a good idea.

**Comment by holyxiaoxin** [comment]
Just want to highlight that this problem only exist for android. In iOS, it's firing once.

**Comment by iggyfisk** [comment]
Confirming that this occurs on Android 6.0.1, both simulator and device. However it **only** happens when using certain `returnKeyType` values. If `returnKeyType` is omitted, the event only fires once as expected. When it's set to `go`, `search` and a few others, it fires twice. Maybe the core problem lies somewhere deeper down in Android, but if React-Native wants to keep the promises the documentation makes it'll have to be dealt with.

**Comment by TheGermanGuy** [comment]
Another victim here. +1

**Comment by RayCai** [comment]
+1

**Comment by Sidhanthsur** [comment]
+1

**Comment by reneweb** [comment]
Same issue as: #10443
Pr to fix the problem: #11006

**Comment by rangav** [comment]
setting blurOnSubmit={false} worked for me on android

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, it does not seem like there has been any traction on this issue for some time.

The issue is being copied over to our feature request tracker at Canny: https://react-native.canny.io/admin/board/feature-requests/p/android-onsubmitediting-is-called-twice-when-keyboard-is-dismissed-in-android

There you can upvote issues that are important to you. This will help contributors identify the issues that the community cares about.

If you think this issue should definitely remain open here in the issue tracker and not on Canny, let us know.

**Comment by ahjsrhj** [comment]
is this solve in new rn version?
meet the same problem in __RN version 0.43.4__

**Comment by davidhellsing** [comment]
Setting `blurOnSubmit={false}` also disabled the `onSubmitEditing` trigger for me in Android Nougat.
