### ISSUE TITLE
ReactNativeJNI:Check failed :*m_isDestroyed JSCExecutor::destroy() must be called before its destructor

### ISSUE THREAD

**Issue by SabinHong** [facebook/react-native#9308]
ReactNativeJNI:Check failed :*m_isDestroyed JSCExecutor::destroy() must be called before its destructor

Open confusion after the formal package, in the mobile phone testing, there is this problem, the Internet search a circle did not result, a friend met this problem? Hope to get your help!

this android and windows!

**Comment by pvllnspk** [comment]
Any news?
I faced it after enabling PROGUARD

**Comment by pvllnspk** [comment]
-keep class com.facebook.react.** { *; }
It helped me

**Comment by SeananXiang** [comment]
I  encountered it also !

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/reactnativejnicheck-failed-misdestroyed-jscexecutordestroy-must-be-called-before-its-destructor

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by hovox** [comment]
I have the same error on iOS

**Comment by YogeshBharate** [comment]
I am facing same error on iOS, but after rebuilding app in xcode resolved the issue for while. Can anybody tell us how to resolve this issue permanently ?

**Comment by jbcullis** [comment]
Experiencing this on iOS but not Android
