### ISSUE TITLE
react-native upgrade --package is not possible with RN 0.31 anymore

### ISSUE THREAD

**Issue by formatlos** [facebook/react-native#9314]
As of RN 0.31 I get "error: unknown option `--package'" when specifying a custom package name. 
I see that the option still exists in generator-android but apparently I doesn't get passed to it...

**Comment by satya164** [comment]
cc @Kureev @grabbou

**Comment by Richard-Cao** [comment]
see #9234

**Comment by formatlos** [comment]
I've tried the solutions mentioned in #9234 before, but didn't solve the issue here.

**Comment by grabbou** [comment]
Indeed, might be an issue with flags. I'll take a closer look later today, thanks for reporting!

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/react-native-upgrade-package-is-not-possible-with-rn-031-anymore

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
