### ISSUE TITLE
CLI does no longer show stack traces

### ISSUE THREAD

**Issue by davidaurelio** [facebook/react-native#9315]
It seems that a recent change led to only error messages being shown for cli failures, rather than the full stack trace. It would be nice if we could at least have a `--verbose` option to switch traces on for debugging

cc @bestander  @Kureev

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/cli-does-no-longer-show-stack-traces

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
