### ISSUE TITLE
scrollsToTop not working in prod build

### ISSUE THREAD

**Issue by philipheinser** [facebook/react-native#9318]
For us scrollsToTop works fine in development build for iOS but if you do an production build tapping on the status bar doesn't trigger scrollsToTop.

RN version: 0.31.0

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/scrollstotop-not-working-in-prod-build

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
