### ISSUE TITLE
Any support for transition group ?

### ISSUE THREAD

**Issue by jcampbell05** [facebook/react-native#9321]
Any support for transition group ?

**Comment by TimBuckley** [comment]
From/to what?

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/any-support-for-transition-group-

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by yachaka** [comment]
Some update on this issue : TransitionGroup does work on react-native, using prop `component={View}`, but it seems super slow.

I'm currently running it on the iOS simulator and removing/adding an item in a list of 10 takes roughly 500ms. The lowest the list the faster, at a list of 1 it takes probably around 50ms.

Here's some sample code if you want to try:
```js
import TransitionGroup from 'react-addons-transition-group';

export default class TestProject extends Component {
  state = {
    data: ['One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten'],
  }

  reset = () => {
    this.setState({
      data: initialData,
    });
  }

  buttonPress = () => {
    this.setState({
      data: this.state.data.slice(1),
    });
  }

  render() {
    return (
      <View style={s.view}>
        <Button
          title="Reset"
          onPress={this.reset}
        />
        <Button
          title="Delete row"
          onPress={this.buttonPress}
        />
        <TransitionGroup component={View}>
          { this.state.data.map(data => (
            <View key={data}>
              <Text>{data}</Text>
            </View>
          ))}
        </TransitionGroup>
      </View>
    );
  }
}
```
Also, you will need to install `react-dom` for `TransitionGroup` to work.
