### ISSUE TITLE
[Android] TextInput On Tablet not centrilized Text

### ISSUE THREAD

**Issue by antoxi4** [facebook/react-native#9324]
![screenshot_2016-08-09-20-53-37](https://cloud.githubusercontent.com/assets/11519065/17527367/cb7fdaf2-5e73-11e6-8aa7-dcf8f405c9d1.png)
This is My code

```
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  TextInput,
  Image,
  View
} from 'react-native';

class TestSizes extends Component {
  render() {
    return (
      <View style={styles.container}>
        <TextInput style={{backgroundColor: '#aaa'}}>
          TEST TEXT ON TEXTINPUT
        </TextInput>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column'
  }
});

AppRegistry.registerComponent('TestSizes', () => TestSizes);
```

and what i see in screen.

[https://s9.postimg.org/bw6wdn5lr/Screenshot_2016_08_09_20_53_37.png](https://s9.postimg.org/bw6wdn5lr/Screenshot_2016_08_09_20_53_37.png)

 It bug i see only on Tablet. In small device it ok! Text  is centrilized.

**Comment by rmevans9** [comment]
I don't think I follow what you mean by "centrilized"? Do you mean centered vertically in the text input? or something else?

**Comment by antoxi4** [comment]
@rmevans9  Yep) This is bug with auto padding in TextInput. this can be solved by using padding: 0 in textInput, but it not normal)Because this fine work on small device but not work pretty in bug device size like Tablet)

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-textinput-on-tablet-not-centrilized-text

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
