### ISSUE TITLE
SwipeableListView not autoclosing

### ISSUE THREAD

**Issue by KishPatel1996** [facebook/react-native#9327]
Implemented a simple SwipeableListView sith a swipedistance of 100 and the following renderquickaction function.

```javascript

_renderQuickActionButtons: function(rowData, sectionID, rowID) {

    return (<View style={{flex: 1, flexDirection: 'row',  }}>
    <View style={{flex:1}} />
    <View style={{width: 100, backgroundColor: 'blue'}}/>
    </View>);
  },
```
None of the rows are closing :(  Any idea what is causing this/how to fix it?

**Comment by rmevans9** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-5** [comment]
Hey @KishPatel1996 and thanks for posting this! @rmevans9 tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by rmevans9** [comment]
Hey @KishPatel1996! It looks like this is a general question on the usage of React Native. Tagging this as a question for Stack Overflow and closing. If you find that your issue is not actually a code issue with your usage but rather a bug in React Native post back here and we can get this reopened.
