### ISSUE TITLE
Fetch's blob processing is slow on iOS

### ISSUE THREAD

**Issue by slycoder** [facebook/react-native#9328]
Blob processing functions (including dependents like .text() and .json()) in the fetch library check for the existence of a supported FileReader and Blob implementation.  For whatever reason, on iOS these are sometimes crushingly slow.  My hypothesis is that this is happening in FileReader.onload somewhere but haven't been able to dig deeper than that.

I can work around this by forking whatwg-fetch and setting support.blob to false.  This gets a typical API call from around 1700ms to 300ms by reducing response processing time from 1400ms to a negligible amount of time.

Using react-native v0.31 on iOS (haven't checked on Android).

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/fetchs-blob-processing-is-slow-on-ios

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
