### ISSUE TITLE
Rename TextInput to TextInputIOS

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#933]
Brought up by @vjeux in irc, my understanding is that it exposes a substantially different API than Android and so should be tied to the platform. PR very welcome!

**Comment by jabbrass** [comment]
Just had a brief irc conversation with @vjeux. Here are a few notes: 

We could split into 3 files: TextInput, TextInputIOS and TextInputAndroidTextInput would only have the subset of attributes that are available in both. This way, if you want to do a quick prototype you can use TextInput and then switch to the iOS or Android variant when doing something special. We'll probably want to do the same with View and all, but it's still unclear what the right strategy is.

**Comment by nicklockwood** [comment]
Which are the main differences between the controls that are prompting this discussion?

Looking at the TextInput.js it seems like there are no features on AndroidTextInput that aren't present on RCTTextField (with the exception of multiline) and most of the differences are simply features on RCTTextField that haven't been implemented yet on Android.

There are a few iOS-specific features such as returnKeyType and clear button that may have no analog on Android (I don't know Android, so correct me if I'm wrong), but that's always going to be the case with any control. I'm wondering whether it would be better to suffix just these property names with IOS/Android rather than forking the whole control.

That said, having a common component and then exposing the platform-specific properties on platform-specific subclasses does have its merits - in particular, it means that if platform-specific properties ever get promoted to x-platform, there's no need to change property names and disrupt existing code.

**Comment by brentvatne** [comment]
@nicklockwood - another big difference that jumps to mind for me is support for `multiline` which [is baked into the Android field](http://stackoverflow.com/questions/4233626/allow-multi-line-in-edittext-view-in-android) but not for iOS

**Comment by nicklockwood** [comment]
@brentvatne we have multiline support internally on iOS in the form of RCTTextView (you can see it referenced in the TextInput.js file) - we just haven't got around to building an open-sourceable version yet. iOS has a UITextView that supports multiline input, so we just need to wrap it (I was hoping someone would have filed a PR for it by now, but if not I'll probably end up building it myself!)

**Comment by nicklockwood** [comment]
@brentvatne but in any case, if we are going to fork a component, I think it should be because of irreconcilable differences between platforms, not because the Android/iOS feature lists haven't quite synced up yet :-)

**Comment by brentvatne** [comment]
@nicklockwood - fair! I just created this in response to a comment in IRC, I'll close this issue for now since it looks like there isn't as much consensus around the idea as I had thought, at least not enough to move forward with it yet. :smile:

**Comment by nicklockwood** [comment]
@brendanv I didn't mean to shut you down, I wasn't in the IRC chat so I don't have a lot of the context. I don't actually dislike the idea at all - just wanted to make sure that you weren't operating on incomplete information about why the missing features are missing.

**Comment by brentvatne** [comment]
@nicklockwood - no problem, I didn't read it as you shutting me down - it just seemed like we could wait until this becomes more of a *need* than a *want* and in the meantime focus on higher priority issues :rocket:

**Comment by nicklockwood** [comment]
👍🏽
