### ISSUE TITLE
is any possible to get react native images in Native UI Component?

### ISSUE THREAD

**Issue by WitzHsiao** [facebook/react-native#9331]
As title. I'm working on Native UI Component, and it's not quite much documentation. :(

**Comment by rmevans9** [comment]
What do you mean by react native images? Just images or are you talking about the React Native Image Component?

**Comment by WitzHsiao** [comment]
I'm doing a app, and it's almost being coding in js. but some of view are using native code to implement. I would like to get the assets which I am using in js system from native code.

**Comment by rmevans9** [comment]
You would actually have to make them go the other way - bring them in as assets on the native side like normal for the OS and then use them in React-Native. See https://facebook.github.io/react-native/docs/images.html#images-from-hybrid-app-s-resources for info on using images in the Native Assets in JS.

**Comment by rmevans9** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-2** [comment]
Closing this issue as @rmevans9 says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.
