### ISSUE TITLE
iOS context menu not displaying for TextInput contained in ListView

### ISSUE THREAD

**Issue by lprhodes** [facebook/react-native#9337]
Hi,

I'm trying to figure to get to the bottom of an issue when using non-editable TextInput components in a ListView on iOS; when you make a text selection, the context menu for "Copy", "Lookup" etc. isn't appearing.

Screenshot of not working in ListView: http://imgur.com/a/9o39e
Screenshot of working outside of ListView: http://imgur.com/a/UkGQo

I will be creating simplified code tomorrow to figure this out but if anyone has any ideas that could help it'd be much appreciated.

Thanks!
Luke

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/ios-context-menu-not-displaying-for-textinput-contained-in-listview

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
