### ISSUE TITLE
Requiring unknown module "ReactPropTypesSecret"

### ISSUE THREAD

**Issue by mvschynd** [facebook/react-native#9338]
While trying to upgrade from 0.28.0 to newer version I got this error:
Requiring unknow module "react/lib/ReactPropTypesSecret". If you are sure the module is there, try restarting the packager or running "npm install"
I am not sure if I made a mistake while trying to upgrade or this is a bug, as I have never seen this error before. Now I can't even make a new project, new or older version without getting this error.

**Comment by janicduplessis** [comment]
Try updating the "react" dependency to 15.3.0

**Comment by krtr** [comment]
@up it should be noted in release notes.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/requiring-unknown-module-reactproptypessecret

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
