### ISSUE TITLE
TouchableHighlight breaks ref property on his children

### ISSUE THREAD

**Issue by papasnippy** [facebook/react-native#9363]
TouchableHighlight breaks his children ref property:

```
<TouchableHighlight>
    <View ref={()=>{ console.log(`This will not be called.`); }}
</TouchableHighlight>
```

However, TouchableWithoutFeedback works fine:

```
<TouchableWithoutFeedback>
    <View ref={()=>{ console.log(`But this will!`); }}
</TouchableWithoutFeedback>
```

**Comment by hey99xx** [comment]
Looking at the `TouchableHighlight`'s source code, it looks like it does indeed steal the refs since it uses 
```javascript
{React.cloneElement(
   onlyChild(this.props.children),
   {ref: CHILD_REF}
)}
``` 

Can you give it a try with a secondary View layer
```javascript
<TouchableHighlight>
   <View>
       <View ref={()=>{ console.log(`This will not be called.`); }}
   </View>
</TouchableHighlight>` 
```

This should let you keep your own ref. In any case, this question is more appropriate for stack overflow. It would still be nice if this was in TouchableHighlight's documentation though.

**Comment by adbl** [comment]
I think this is a bug.

**Comment by hey99xx** [comment]
Actually agreeing with you that this should be considered a bug. The fact that only TouchableHighlight component behaving this way does sound wrong. I cannot add any bug label to the issue though.

**Comment by pvinis** [comment]
this should be fixed. i spent a whole day trying to `ref` a `TextInput` inside a `TouchableHighlight` and i couldnt. i thought i couldnt understand `ref`s. then later i made a new project, tried with a `View` and it worked, so in the end i found out it was because of the `TouchableHighlight`. is there a reason its like that? this looks like something that was forgotten to be fixed to behave like everything else.

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Comment by hey99xx** [comment]
@hramos I don't understand what's the point of closing a valid bug report. It's still an unfixed and fairly annoying bug, and closing it will make sure people don't see it if anyone decide to contribute to react-native

**Comment by pvinis** [comment]
i also agree. if a bug report is still valid, even if its old, should stay there. its still a bug that should be fixed. it might take long to fix, which sucks for the people needing that, but eventually a fix is needed. workarounds are not bug fixes, and should not stay there forever.

**Comment by hramos** [comment]
I'd argue that a bug report with no comments on it for over four months must not be blocking that many people. We're trying to cut down on the number of issues so we can better focus on what's currently affecting users.

I'm not saying that the bug is not worth fixing, but rather at this point if you're still blocked by this, it may well be worth looking into submitting a PR with a fix.

**Comment by hey99xx** [comment]
I thought you had an ice-box label for this. That would be more appropriate.

The fact that people have found workarounds and not actively blocked by it does not mean much if this costs a newcomer waste an additional hour when they come to react-native.

> it may well be worth looking into submitting a PR with a fix.

Once it's closed, no one will see this in the open issues, so you will not get a PR.

**Comment by hramos** [comment]
The issue has been open for nine months and no PRs have come from this thread, where presumably there would be more interest in getting this fixed. I am not sure that leaving the issue open for another 60 days would help here. Closing the issue, in my opinion, provides a honest reflection of the actual practical outcome (the issue will remain unfixed due to lack of interest).
