### ISSUE TITLE
transform-react-jsx-source not working on new react-native project

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#9364]
In order to get it to work, I need to create a `babelrc` with:

```
{
  "presets": ["react-native"],
  "env": {
    "development": {
      "plugins": ["transform-react-jsx-source"]
    }
  }
}
```

**Comment by brentvatne** [comment]
Any idea it works with the above `babelrc` but not inside of the preset? https://github.com/facebook/react-native/blob/8edb9524035b0c034135a81551ba955ee514dbd4/babel-preset/configs/main.js

cc @kittens @thejameskyle

**Comment by thejameskyle** [comment]
What is happening?

**Comment by gdowens** [comment]
Also seeing this issue. Works again if I turn off hot reloading. 

See this line https://github.com/facebook/react-native/blob/master/packager/transformer.js#L94
Changing the line to below seems to resolve it...
```
config = Object.assign({}, hmrConfig, {
  plugins: config.plugins.concat(hmrConfig.plugins)
})
```

Not super familiar with all the ways plugins might be loaded into RN, but my suspicion is that HMR is overriding config.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/transform-react-jsx-source-not-working-on-new-react-native-project

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by thejameskyle** [comment]
@brentvatne you never said what was going on

**Comment by brentvatne** [comment]
sorry @thejameskyle :< I wasn't sure how to respond to that when I saw it and then forgot about it because I just used the fix from the OP. still not really sure how to answer that -- `transform-react-jsx-source` is included in the react-native preset, but it doesn't work unless you add it manually to your babelrc after the preset. not super helpful but it's all of the context I have a few months after the post

**Comment by DaleJefferson** [comment]
I can recreate this issue in React-Native 0.42, this is still a bug
