### ISSUE TITLE
Creating an application named after a reserved word in Java prevents building

### ISSUE THREAD

**Issue by f0rk** [facebook/react-native#9365]
Run the following:

```
$ react-native init try
$ cd try
$ react-native run-android
```

Note the build errors:

```
/Users/ryan/Projects/try/android/app/src/main/java/com/try/MainActivity.java:1: error: <identifier> expected
package com.try;
```

I'm not sure what the best approach would be here. A warning? Throwing an error? Mangling the name? Willing to work on a patch if there's some consensus about the approach.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/creating-an-application-named-after-a-reserved-word-in-java-prevents-building

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
