### ISSUE TITLE
React native fetch issue

### ISSUE THREAD

**Issue by krishbhattacharyya** [facebook/react-native#9369]
Hi,
I am new in react native and facing problem in fetch data- 
Below in the shared screen shot  in the console section I got the array within "_65" after fetch data. How can I show this in list view? And can I pass the array with the navigator passProps for another screen?

![screenshot from 2016-08-12 12 39 05](https://cloud.githubusercontent.com/assets/10433734/17615220/5632a48c-608a-11e6-9859-70e1183fd272.png)

**Comment by ryankask** [comment]
Hi there.

`fetch`, like almost all APIs in React Native, is asynchronous. You can learn more about how to use it here: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch.

Also, you need to change the `underlayColor` prop value to `#ededed`.

GitHub issues are where bugs are reported rather than questions. In the future, try asking on StackOverflow or in the [Reactiflux chat room](http://www.reactiflux.com/).

Good luck!

**Comment by ryankask** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-2** [comment]
Closing this issue as @ryankask says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

**Comment by krishbhattacharyya** [comment]
Okay,
Thanks.
