### ISSUE TITLE
the right way of matrix 2d?

### ISSUE THREAD

**Issue by oubushixb** [facebook/react-native#9386]
i have a css3 tansform like
transform: matrix(1, 0, 0, 1, 5, 5);
so what's the react native "matrix array" is?
1.[
  1, 0, 0,
  0, 1, 0,
  5, 5, 1
]

2.[
  1, 0, 0,
  1, 5, 5,
  0, 0, 1
]

3.[
  1, 0, 5,
  0, 1, 5,
  0, 0, 1
]

all not right in the view....

**Comment by rmevans9** [comment]
Hey @oubushixb! Reading through your question I don't personally know the answer but posting this question over on Stack Overflow might get you faster results. The issue tracker here is used for tracking bugs in React Native where what you are looking for is guidance on how to use a feature of React Native. Closing this issue since it is not a bug in React Native.

**Comment by rmevans9** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-2** [comment]
Hey @oubushixb and thanks for posting this! @rmevans9 tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
