### ISSUE TITLE
live reload stops when there is an error

### ISSUE THREAD

**Issue by mvolkmann** [facebook/react-native#9403]
Live reload of the iOS simulator works great! However, if I introduce an error in my code and get the red screen, after fixing the error I have to manually reload the simulator. After that, live reload works again up until I introduce another error. I think it should live reload regardless of whether the last reload resulted in an error.

**Comment by baskan** [comment]
yeah, I feel the same live reload should trigger after the first file change after the error.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/live-reload-stops-when-there-is-an-error

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
