### ISSUE TITLE
View's style incorrectly overrides TextInput's style

### ISSUE THREAD

**Issue by csujedihy** [facebook/react-native#9417]
The container view adds its style to the child component, TextInput. It's not actually overriding. For example, if the container view's shadow color is set to BLACK and child component TextInput's shadow color is set to RED, the child component will have both BLACK and RED shadow. I cannot remove child component's shadow if I set shadow on the parent component.

JSX:

```
<View style={styles.codeContainer}>
  <View style={styles.codeInputWrapper}>                        
    <TextInput style={styles.codeInput} ref={"d1"} maxLength={1} onChangeText={(text)=>{
      this.d1 = text;
      this.refs.d2.focus()}
    }></TextInput>
  </View>
  <View style={styles.codeInputWrapper}>                        
    <TextInput style={styles.codeInput} ref={"d2"} maxLength={1} onChangeText={(text)=>{
      this.d2 = text;
      this.refs.d3.focus()}
    }></TextInput>
  </View>
  <View style={styles.codeInputWrapper}>                        
    <TextInput style={styles.codeInput} ref={"d3"} maxLength={1} onChangeText={(text)=>{
      this.d3 = text;
      this.refs.d4.focus()}
    }></TextInput>
  </View>
  <View style={styles.codeInputWrapper}>                        
    <TextInput style={styles.codeInput} ref={"d4"} maxLength={1} onChangeText={(text)=>{
      this.d4 = text;
      this.rightButtonHandler();
      }
    }></TextInput>                  
  </View>
```

Style:

```
const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
  },
  textContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-end',
    padding: 5
  },
  codeContainer: {
    flex: 1, 
    alignItems: 'flex-start', 
    flexDirection: 'row',
    justifyContent: 'center'
  },
  codeInputWrapper: {
    shadowColor: "#000000",
    shadowOpacity: 0.8,
    shadowRadius: 2,
    shadowOffset: {
      height: 1,
      width: 0
    },
    height: 50,
    width: 50,
    borderWidth: 1,
    borderColor: '#525357',
    borderRadius: 2,
    margin: 10,
  },
  codeInput: {
    shadowColor: "#FFFFFF",
    shadowOpacity: 1,
    shadowRadius: 0,
    shadowOffset: {
      height: 0,
      width: 0
  }
);
```

**Comment by shivani890** [comment]
needs work!

**Comment by christopherdro** [comment]
@facebook-github-bot icebox

**Comment by shergin** [comment]
iOS, Android, both?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, it does not seem like there has been any traction on this issue for some time.

The issue is being copied over to our feature request tracker at Canny: https://react-native.canny.io/admin/board/feature-requests/p/views-style-incorrectly-overrides-textinputs-style

There you can upvote issues that are important to you. This will help contributors identify the issues that the community cares about.

If you think this issue should definitely remain open here in the issue tracker and not on Canny, let us know.
