### ISSUE TITLE
react-native@0.27.2 requires a peer of react@15.1.0 but none was installed

### ISSUE THREAD

**Issue by waleedarshad-vf** [facebook/react-native#9423]
How to resolve this issue?

**Comment by zpp-gp** [comment]
npm install react@15.1.0 --save

**Comment by ide** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-2** [comment]
Closing this issue as @ide says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

**Comment by waleedarshad-vf** [comment]
@ide please provide link to answer. Question has been asked on StackOverflow but none answer is satisfactory. so i thought react-native team will provide authentic reason.

**Comment by waleedarshad-vf** [comment]
@facebook-github-bot-2  will you provide link and before closing you should
