### ISSUE TITLE
LayoutAnimation doesn't work with componentDidMount

### ISSUE THREAD

**Issue by 7ynk3r** [facebook/react-native#9424]
Can somebody explain to me why this doesn't animate correctly? It animates as a fade-in  with the final position instead of moving it from left to right. 

As far as I know this should work because the first frame is rendered with the initial state, then `componentDidMount` is called which will generate a new state, calling render again with a new state, which should be animated.

```
class LayoutAnimationExample extends React.Component {
  constructor(props) {
    super(props);
    this.state = {left:0};
  }
  componentDidMount() {
    LayoutAnimation.spring();
    this.setState({left:100});
  }
  render() {
    return (
      <View style={{flex:1}}>
        <View style={{
          left:this.state.left,
          height:100,
          width:100,
          backgroundColor:'blue'}}
        />
      </View>
    );
  }
}
```

If we wrap the `componentDidMount` body with `setTimeout` it'll work correctly, which is weird because it generates the exact same flow, calling render twice.

```
  componentDidMount() {
    setTimeout(() => {
      LayoutAnimation.spring();
      this.setState({left:100});
    });
  }
```

**Comment by ZhenjieRuan** [comment]
I think you should set ```LayoutAnimtaion``` in ```componentWillUpdate```

**Comment by 7ynk3r** [comment]
It's the same.

**Comment by ZhenjieRuan** [comment]
No it's not, componentDidMount will be triggered only once, but componentWillUpdate wiil be triggered everytime the component updates, either a state changed or received new props. Check https://facebook.github.io/react/docs/component-specs.html

**Comment by 7ynk3r** [comment]
@ZhenjieRuan i know about event and life cycle in react. what i'm saying is that it doesn't work anyway.

i've created a playground with the case https://rnplay.org/apps/Gu2Gyg

you can see all the approaches there.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/layoutanimation-doesnt-work-with-componentdidmount

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
