### ISSUE TITLE
Trigger an arbitrary TouchEvent with a given position [x,y]

### ISSUE THREAD

**Issue by jreziga** [facebook/react-native#9437]
Hello,

I'm wondering if it is possible to trigger a touch event somewhere on the screen. Something like : 

let touchEvent = new TouchEvent({x:10,y:10});
touchEvent.emit();

Thanks !

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of React Native.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #react-native](http://stackoverflow.com/questions/tagged/react-native)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

**Comment by jreziga** [comment]
http://stackoverflow.com/questions/38981866/trigger-an-arbitrary-touchevent-with-a-given-position-x-y
