### ISSUE TITLE
Android ScrollView onTouchEnd is not firing

### ISSUE THREAD

**Issue by stefvhuynh** [facebook/react-native#9439]
The touch `onTouchEnd` prop in `ScrollView` is not working on android. It works fine on iOS.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-scrollview-ontouchend-is-not-firing

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by Silcence** [comment]
Has this issue been fixed?

**Comment by mjylfz** [comment]
i have the same problem,how to solve this problem

**Comment by oriharel** [comment]
This needs to be solved.
