### ISSUE TITLE
Update error message suggesting user run: react-native android

### ISSUE THREAD

**Issue by ericnakagawa** [facebook/react-native#9440]
In some cases, the user is told to run "react-native android" but that command no longer exists.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/update-error-message-suggesting-user-run-react-native-android

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
