### ISSUE TITLE
[Android]WebView Hide balloon of Remember password API < 18

### ISSUE THREAD

**Issue by naivehhr** [facebook/react-native#9443]
In my program, I make a loginview with webview. When the android api version <18,it will be show a balloon of remember,but I do not want a show out. [I made reference to some of the information.](http://stackoverflow.com/questions/11531778/how-to-disable-the-save-password-dialog-on-an-android-webview), But I do not know how to set save password false on webview (webview.getSettings().setSavePassword(false);).How can I do? or other ideas?! Thanks to everyone!
[stackoverflow](http://stackoverflow.com/questions/38989291/react-native-anroid-webview-how-to-set-savepassword-false-when-build-version)

------------------------------------------------------------------
"react-native": "^0.29.0"

**Comment by rmevans9** [comment]
It appears that particular setting is not exposed via React Native. I am not sure if this is something they would want to support since it only matters on API versions prior to 18. Since this is not technically a bug and more a request for a new feature for the React Native web view I am going to close it as such. Feature Requests can be made on product pains.

**Comment by rmevans9** [comment]
@facebook-github-bot feature
