### ISSUE TITLE
NetInfo can't detect the wifi without Internet connect

### ISSUE THREAD

**Issue by windhost** [facebook/react-native#9444]
I use my device to connect to a wifi that does't connect to Internet. ButNetInfo.isConnected return true,  I really can not visit Internet.

**Comment by JohnyDays** [comment]
That is impossible to check just from the device, you have to periodically ping some service and check if a response is received

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot expected

**Comment by facebook-github-bot-0** [comment]
The comment above tells me this is expected behavior. Closing this as we'd like to use the GitHub issue tracker for bugs. If you'd like to change how this feature works please post a feature request on [Product Pains](https://productpains.com/product/react-native/) so that other people can vote on it.

**Comment by windhost** [comment]
thanks a lot
