### ISSUE TITLE
ReactMethod Callback  parameter is null

### ISSUE THREAD

**Issue by droidwolf** [facebook/react-native#9445]
Why the ReactMethod function is defined as follows

```
@ReactMethod
public void method(Callback cb1,Callback cb2,String str1)
```

cb1and cb2  parameter is null？

moves behind cb1&cb2 to str1.as follows

```
@ReactMethod
public void method(Callback cb1,Callback cb2,String str1)
```

can get  the CB1&CB2

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/reactmethod-callback-parameter-is-null

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by douglasjunior** [comment]
Any solution?
