### ISSUE TITLE
sync style from native ui component

### ISSUE THREAD

**Issue by WitzHsiao** [facebook/react-native#9446]
Hi, 
Since the animation is very slow on js thread, I would like to implement a view in native ui component. 
I made the view rotate 90 degree in the objective-c. How can I make the flexbox goes smooth? It keeps the same space on js side. :(

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-0** [comment]
Hey @WitzHsiao and thanks for posting this! @DanielMSchmidt tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
