### ISSUE TITLE
Create WebSocket with null paramter make the app crash immediately RN 0.28-0.31 IOS

### ISSUE THREAD

**Issue by tslearn** [facebook/react-native#9460]
Pass null to create WebSocket is wrong, but the app crash immediately, without any error log. 

let sockAddress = null;
new WebSocket(sockAddress);

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/create-websocket-with-null-paramter-make-the-app-crash-immediately-rn-028-031-ios

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
