### ISSUE TITLE
startInLoadingState={true} reloads webview indefinitely in Android

### ISSUE THREAD

**Issue by jqn** [facebook/react-native#9461]
# startInLoadingState breaks in Android. The webview shows the spinner and seems to never resolve.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/startinloadingstatetrue-reloads-webview-indefinitely-in-android

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (72/60 (120%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter03.reliabledns.org ([69.175.33.179]:38554)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1c671K-000jW3-7r
	for bunny@thumbmunkeys.com; Mon, 14 Nov 2016 02:29:19 +0000
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197] helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by filter03.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1c671J-00062s-S3
	for bunny@thumbmunkeys.com; Sun, 13 Nov 2016 19:29:18 -0700
Date: Sun, 13 Nov 2016 18:29:08 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1479090557;
	bh=eFiQoldrwkEAbHZrab0jJWw0swfXPFyGtKgZsHyon0s=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=o3F3MKcNmn8S5ESOWTdinj7MaKkPtD9w6M/4cVb0xRtM6/79TFKqUMbaqfzgAQ4l/
	 zRRB4sL5KHW2p/Jlovnx9SOPK8PjCYy/DJO2fRoB27cZgJXdkx8YsOhh4khyndJCtW
	 pS1khtMwTI9qSNC9Ue82Vbz82XtFdseC+sOkh+tA=
