### ISSUE TITLE
NavigatoriOS can't push same component twice

### ISSUE THREAD

**Issue by AllenHK** [facebook/react-native#9464]
In my project, I have to push same component to the navigation stack twice. For example, first push A component, then push B component and then push A Component. Things go wrong when I try to push A from B component. Here is the displayed error:

<img width="377" alt="screen shot 2016-08-18 at 5 43 02 pm" src="https://cloud.githubusercontent.com/assets/3193216/17769463/494fcaa2-656b-11e6-949b-a72da4d5882d.png">

Why can't NavigatoriOS push same component twice? Does anybody know how to fix this out.

**Comment by hey99xx** [comment]
Maybe if you post a sample of your code, someone will be able to help you, there's no way to understand  the error you're getting from looking at a red screen here. You can also try stackoverflow.

**Comment by hey99xx** [comment]
@facebook-github-bot label Needs more information

**Comment by AllenHK** [comment]
@hey99xx thanks for your reply, I have found the reason on stackoverflow. It is the problem of cyclic-dependency. here is the link:
http://stackoverflow.com/questions/29807664/cyclic-dependency-returns-empty-object-in-react-native

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/navigatorios-cant-push-same-component-twice

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
