### ISSUE TITLE
LayoutAnimation doesn't play well with justifyContent: 'space-between'

### ISSUE THREAD

**Issue by cdes** [facebook/react-native#9466]
I have an animated view with a disabled sibling button.
The animated view has 2 text views aligned on far left and far right using justifyContent: 'space-between'.

When I enable the sibling button, the far right text view "jumps".

Here's a video showing the problem: https://vid.me/npLI
Here's a repro on RNPlay: https://rnplay.org/apps/atSZAA

Asked in StackOverflow 3 days ago but no one answered yet.

http://stackoverflow.com/questions/38949393/layoutanimation-doesnt-play-well-with-justifycontent-space-between

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/layoutanimation-doesnt-play-well-with-justifycontent-space-between

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (61/60 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter01.reliabledns.org ([199.96.156.50]:34267)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1c6708-000j6N-IV
	for bunny@thumbmunkeys.com; Mon, 14 Nov 2016 02:28:05 +0000
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194] helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by filter01.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1c6707-0007oc-EY
	for bunny@thumbmunkeys.com; Sun, 13 Nov 2016 19:28:04 -0700
Date: Sun, 13 Nov 2016 18:28:02 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1479090482;
	bh=DlbaxCIqACUJVE7Hqir3AQYwj2/xJ/USitngp9QREHY=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=ucuUIDtHuhwmgVORADWboJLLxDAwCiTUSbpgVW79tnaR1YgQnlvJ0+W9EzblWrjmB
	 EEKRWKTNNgXZQEYAL+1cp2tW98mBe9ObTxcUH5JtTroCYhNqQuzNHK2eD3v4IdPA/Y
	 0K+00jxeZgmmm0xM+YtUhNvRsfuBVvSy5B9zQ8G0=

**Comment by Ashoat** [comment]
Hey there - reopening this issue in part because I am experiencing the same thing, and in part because the Canny.io (née ProductPains) link is now broken. Worst case it gets closed again and I get a Canny.io issue I can upvote :)

By the way, please let me know if this concern ought to be addressed to the Yoga team instead of React Native.
