### ISSUE TITLE
0.31 app does not start after 48+ hours

### ISSUE THREAD

**Issue by spietrek** [facebook/react-native#9473]
On Tuesday I successfully deployed my 0.31 app to my physical iPhone 6+. Everything worked fine Tuesday and Wednesday. Tonight (Thursday) I tried to open the application (it was not previously open) and it freezes on the start screen. It is causing major performance issues since I am unable to navigate to another app or close the offending app. I had to reboot my phone. The application is running successfully after deploying the app through Xcode. 

Could it be that it was deployed as "Debug"? I deployed as "Release" and will retest in a few days.

For iOS open your project in Xcode and select Product → Scheme → Edit Scheme... (or press ⌘ + <). Next, select Run from the menu on the left and change the Build Configuration to Release.

Recommendations on what to check if this happens again?

Thanks

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/031-app-does-not-start-after-48-hours

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
