### ISSUE TITLE
Error fetch in Android

### ISSUE THREAD

**Issue by toiyeugiadinh92** [facebook/react-native#9476]
I have 2 function

func2(){
    fetch('https://hacker-news.firebaseio.com/v0/jobstories.json', {
      method: 'GET',
      headers: {
        'Accept': 'application/json'
      }
    })
    .then((response) => response.json())
    .then( (responseData) => {
      console.log('fetch 2: ', "data 2");
    })
    .catch( (error) => {
      console.warn('Error 2: ', error)
    })
  }

  func1(){
    fetch('https://hacker-news.firebaseio.com/v0/jobstories.json', {
      method: 'GET',
      headers: {
        'Accept': 'application/json'
      }
    })
    .then((response) => response.json())
    .then( (responseData) => {
      console.log('fetch 1: ', "data 1");
      this.func2();
    })
    .catch( (error) => {
      console.warn('Error 1: ', error)
    });
  }

T1: When I touch on TouchableHight with onPress={() => this.func1()} action then Result:
**fetch 1: data 1**

T2: If func1() in componentWillMount() as 
componentWillMount(){
 this.func1();
}

then Result:
fetch 1: data 1
fetch 2: data 2

I want Result of T2 is Result of T1, but not. 

Only Error on Android

**Comment by damusnet** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-0** [comment]
Hey @toiyeugiadinh92 and thanks for posting this! @damusnet tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
