### ISSUE TITLE
NavigationExperimental how keep previous scene state when pop

### ISSUE THREAD

**Issue by Sean-Snow** [facebook/react-native#9479]
I return from a scene, the state to initialize.

i want keep the state. What should I do？

**Comment by nak1b** [comment]
I am having same issue. I wan to preserve state when changing tabs. Here is my implemntaion of Navigation Experimental with tabs. It re renders every time i change tab. https://github.com/nak1b/react-native-composite-navigation

**Comment by ryankask** [comment]
@nak1b I've had a brief look at your code and the issue seems to be that you're using the same `NavigationCardStack` for each tab. When you switch tabs, the current tab's scene components will be unmounted and then the new scenes mounted.

If you want each tab's state to persist, you need to render something for each tab's navigation state. For example, you can render a `NavigationCardStack` for each tab. It's common to only do this after the user has visited the tab for the first time.

@Sean-Snow Can you give an example? What kind of state do you mean? When you pop a scene from the stack you are unmounting it so any component state will be lost.

**Comment by nak1b** [comment]
@ryankask thanks buddy that sounds the right way to do it. I thought we can use single NavigationCardStack for entire application.

**Comment by Sean-Snow** [comment]
@ryankask   my code.in home scene, change the name to world. go user then back, the name is hello
Application.js

    import React, {Component} from 'react';
    import {
      AppRegistry,
      View,
      Text,
      NavigationExperimental
    } from 'react-native';
    import Home from './Home';
    import User from './User';


    const routes = {
        Home,
        User
    };

    const {
      StateUtils: NavigationStateUtils,
      Transitioner: NavigationTransitioner,
      Card: NavigationCard,
      CardStack: NavigationCardStack,
      Header: NavigationHeader
    } = NavigationExperimental;

    const excludeFunc = [
      'constructor',
      'render',
      'componentWillMount',
      'componentDidMount',
      'componentWillReceiveProps',
      'shouldComponentUpdate',
      'componentWillUpdate',
      'componentDidUpdate',
      'componentWillUnmount'
    ];

    class Application extends Component {

      props: Object;
      state: Object = {
        navigationState: {
          index: 0,
          routes: [{
            key: 'Home'
          }]
        }
      };

      navigator: Object = {
        getRoutes: () => this.state.navigationState.routes,
        push: route => this.handleNavigatorChange('push', route),
        pop: () => this.handleNavigatorChange('pop'),
        jumpTo: key => this.handleNavigatorChange('jumpTo', key),
        replace: route => this.handleNavigatorChange('replaceAtIndex', this.state.navigationState.index, route),
        reset: routes => this.handleNavigatorChange('reset', routes)
      };

      constructor(props) {
        super(props);
        // noinspection Eslint
        let propertyNames = Object.getOwnPropertyNames(Object.getPrototypeOf(this));
        propertyNames.forEach(func => {
          if (excludeFunc.indexOf(func) === -1 && typeof this[func] === 'function') {
            this[func] = this[func].bind(this);
          }
        });
      }

      handleNavigatorChange(type, ...args) {
        let state = NavigationStateUtils[type](this.state.navigationState, ...args);
        if (state !== this.state.navigationState) {
          this.setState({navigationState: state});
        }
      }

      renderScene(sceneProps): ReactElement {
        const {
          scene:{
            route:{
              params,
              key
            }
          }
        } = sceneProps;
        const Component = routes[key];
        return (
          <Component {...params}
            navigator={this.navigator}
          />
        );
      }

      renderComponent(props) {
        const {route} = props.scene;
        return (
          <NavigationCard {...props}
            key={`scene_${route.key}`}
            onNavigateBack={this.navigator.pop}
            renderScene={this.renderScene}
          />
        );
      }

      render() {
        return (
          <NavigationTransitioner
            navigationState={this.state.navigationState}
            render={this.renderComponent}
          />

        );
      }
    }

    AppRegistry.registerComponent('myapp', () => Application);



Home.js

    import React, {Component} from 'react';
    import {View,Text,TouchableOpacity} from 'react-native';
    
    
    class Home extends Component{
    
        state = {
            name: 'Hello'
        };
    
        handleChange(){
            this.setState({name: 'World'});
        }
    
        goUser(){
            this.props.navigator.push({
                key: 'User'
            })
        }
    
        render(){
            return (
                <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
                    <Text>{this.state.name}</Text>
    
                    <TouchableOpacity onPress={this.handleChange.bind(this)}>
                        <Text>Change Name</Text>
                    </TouchableOpacity>
    
                    <TouchableOpacity onPress={this.goUser.bind(this)}>
                        <Text>Go User Profile</Text>
                    </TouchableOpacity>
                </View>
            );
        }
    
    }
    
    export default Home;


User.js

    import React, {Component} from 'react';
    import {View,Text,TouchableOpacity} from 'react-native';
    
    
    class Home extends Component{
    
        render(){
            return (
                <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
                    <TouchableOpacity onPress={this.props.navigator.pop}>
                        <Text>Back Home</Text>
                    </TouchableOpacity>
                </View>
            );
        }
    
    }
    
    export default Home;

**Comment by ryankask** [comment]
This is very to the answer provided above. You need to render a `NavigationCard` for each scene, otherwise the scene component's replace each other and their states are reset.

Have a look at the `NavigationCardStack` component's `render()` method for some guidance: https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/NavigationExperimental/NavigationCardStack.js#L214. Notice how it calls `_renderScene()` for each scene on the stack. That method returns a `NavigationCard`.

Next time, join us on Reactiflux. It's a chat room where you can ask questions. Everyone there is really friendly and there is a room devoted to RN navigation called "rn-navigation".

**Comment by ryankask** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-0** [comment]
Closing this issue as @ryankask says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

**Comment by Sean-Snow** [comment]
@ryankask  thank you.
