### ISSUE TITLE
How to change Android package name?

### ISSUE THREAD

**Issue by dyguests** [facebook/react-native#9480]
[
    Mac.
    "react": "^15.2.1",
    "react-native": "^0.28.0",
]

I changed applicationId in build.gradle and AndroidManifest.
and changed package of MainActivity

and I found code `package = 'com.erp_rn',` in `./BUCK`.

should I changed package name in `./Buck` ??

**Comment by damusnet** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-1** [comment]
Hey @dyguests and thanks for posting this! @damusnet tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
