### ISSUE TITLE
How much marginTop I need in Android use NavigatorBar?

### ISSUE THREAD

**Issue by dyguests** [facebook/react-native#9482]
[
    mac
    "react": "^15.2.1",
    "react-native": "^0.28.0",
]

Use NavigatorBar.because of statusBar,NavigatorBar,,I need (marginTop: 64) in iOS,
but how much marginTop in android??

Or could you tell me how to get the height of statusBar and navigatorBar?

**Comment by satya164** [comment]
On Android, height of statusbar is 25, height of navbar is 56, on iOS height of statusbar is 20, height of navbar is 44

@facebook-github-bot answered

**Comment by satya164** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-0** [comment]
Closing this issue as @satya164 says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.
