### ISSUE TITLE
Don't let backgroundColor overflow past borderRadius

### ISSUE THREAD

**Issue by lorensr** [facebook/react-native#9494]
Re-opening #904, note the orange corners that shouldn't be there:

![image](https://cloud.githubusercontent.com/assets/251288/17833750/73153d9c-66f4-11e6-8370-afa5337dcbc4.png)

Should be:

![image](https://cloud.githubusercontent.com/assets/251288/17833762/aa84782e-66f4-11e6-845a-0e5088d9ef14.png)

`overflow: 'hidden'` fixes it, but it should not be needed – not showing the backgroundColor should be the default behavior. 

`v0.31.0`, mac, iOS

**Comment by geirman** [comment]
@lorensr you're probably right, this should be fixed without relying on the `overflow: 'hidden'` work around. At the very least, we should mention this in the docs. React native is a community project and so we rely on the community to help improve things. Would you be willing to submit a PR that either fixes this properly or at least updates the docs to help others understand the work around?

**Comment by lorensr** [comment]
Don't have time right now, but whereabouts in the code would the fix be?

**Comment by geirman** [comment]
¯\_(ツ)_/¯

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/dont-let-backgroundcolor-overflow-past-borderradius

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
