### ISSUE TITLE
ScrollView won't scroll on device

### ISSUE THREAD

**Issue by yeegr** [facebook/react-native#9501]
I'm using RN 0.31 on OSX, with the latest XCode. I'm having the weirdest bug, ScrollView and other views based on ScrollView like ListView and ParallaxView (react-native-parallax-view) works fine in the simulator, but once deployed on my iPhone, it only displays the first screen. Even though elastic scroll works as I can see there's content after the first screen, once my finger leaves the screen, the ScrollView bounces back to the top. I've tried adding and removing style={{flex:1}} at every level, but the results are the same. Anyone has seen this behavior - works in the simulator but not on the device?

Thanks

**Comment by AgtLucas** [comment]
@yeegr Do you have a repo? I'm willing to try out on my iPhone.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/scrollview-wont-scroll-on-device

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
