### ISSUE TITLE
React-active : Port related error 

### ISSUE THREAD

**Issue by nandusiyer** [facebook/react-native#9512]
Hi , 

I'm trying to run an app on emulator and I see this error - 

![image](https://cloud.githubusercontent.com/assets/7775862/17840973/3c92044c-67e1-11e6-8570-5675d323b4bd.png)

I did run the command react-native start in the other terminal and the packager is up and running on 8081 . 

Any idea what the issue could be of ? 

Thanks

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/react-active-port-related-error-

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
