### ISSUE TITLE
not execute Promise in Promise on Android

### ISSUE THREAD

**Issue by toiyeugiadinh92** [facebook/react-native#9514]
I have 2 Promise

Promise1 contain Promise2.

It execute content in Promise1 but not execute content in Promise2.

It only error on Android, but on IOS is OK.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/not-execute-promise-in-promise-on-android

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
