### ISSUE TITLE
React Native "Requiring unknown module "Crypto"

### ISSUE THREAD

**Issue by mjniuz** [facebook/react-native#9535]
Hello

I got this error message when i use any encryption library such as JWT

Requiring unknown module "crypto". If you are sure the module is there, try restarting the packager or running "npm install"

I already install crypto
https://www.npmjs.com/package/react-native-crypto

Can you help me for this?

ref http://stackoverflow.com/questions/29836434/requiring-unknown-module-crypto-in-react-native-environment

thanks

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of React Native.

Questions like yours deserve a purpose-built Q&A forum such as Stack Overflow. Since you have already posted your question there, I'll go ahead and close out this issue.
