### ISSUE TITLE
Navigator broken on Android

### ISSUE THREAD

**Issue by Maxim-Chugaev** [facebook/react-native#9542]
This my first app on react-native https://github.com/Maxim-Chugaev/react-native__sample-app
On IOS is good work, but on android navigator view broken!

I test my app on LG-D802 and ZTE Blade S6 - 5.0.2

How can i fix this annoying bug?

Update: when i disable remote debug, then app work is ok

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of React Native.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #react-native](http://stackoverflow.com/questions/tagged/react-native)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.
