### ISSUE TITLE
Scrollview PanResponder

### ISSUE THREAD

**Issue by tanabs18** [facebook/react-native#9545]
Looking at the ScrollView.js component, it looks like it uses responder instead of PanResponder. Is there a reason for this, as using gestureState inside of a scrollview would be really helpful.

`
     onResponderGrant: this.scrollResponderHandleResponderGrant,
     onResponderTerminationRequest: this.scrollResponderHandleTerminationRequest,
     onResponderTerminate: this.scrollResponderHandleTerminate,
      onResponderRelease: this.scrollResponderHandleResponderRelease,
      onResponderReject: this.scrollResponderHandleResponderReject,`

**Comment by Smallpath** [comment]
Do you solve the problem? 

I meet the same situation using `ViewPagerAndroid`: Every method in PanResponder works well except the `onResponderTerminationRequest`. It's crazy that even `onResponderTermination` works but `onResponderTerminationRequest` not !  

I feel confused about it. If you solve it by some ways, please let me know

**Comment by tanabs18** [comment]
Sort of. I originally tried to use the scrollview events to control other things, but instead decided to put a pan-responder on top. I'm pretty sure the onterminationrequest works on scrollview, but only one or two drag events are fired on the scrollview at the very beginning, meaning other responders don't actively try to take control. I figured out that if you capture the touch and the drag on the responder at the beginning, scrollview won't take it. So I put all my logic in there and moved the scrollview with scrollTo().

**Comment by Smallpath** [comment]
@tanabs18  You mean that you disables the ScrollEnable and use scrollTo() in PanResponder? Thanks very much!!!

**Comment by tanabs18** [comment]
I didn't do anything to scrollEnable actually, I'll see if that changes anything. Did you make any headway on any of this?

**Comment by Smallpath** [comment]
Hi

It seems that we are going far away from the issue, but finally I get a wild solution after 3 days debuging. I found that onterminationrequest not being triggerred is caused by Native Layer. 

Modify `react-native\ReactAndroid\src\main\java\com\facebook\react\views\scroll\ReactScrollView.java`    , comment Line 161 and then [build from the source](http://facebook.github.io/react-native/releases/0.32/docs/android-building-from-source.html), you will see  your PanResponder outside ScrollView takes the control as expected now.


```
  @Override
  public boolean onInterceptTouchEvent(MotionEvent ev) {
    if (!mScrollEnabled) {
      return false;
    }

    if (super.onInterceptTouchEvent(ev)) {
      NativeGestureUtil.notifyNativeGestureStarted(this, ev);  // comment this line!!
      ReactScrollViewHelper.emitScrollBeginDragEvent(this);
      mDragging = true;
      enableFpsListener();
      return true;
    }

    return false;
  }
```

It seems that `NativeGestureUtil.notifyNativeGestureStarted(this, ev)` notified a native gesture, which brokes the JS Layer gesture system. This is mentioned in the document but not explained detailed as follows:

>Might be taken by other views after a call to onResponderTerminationRequest, or might be taken by the OS without asking

I didn't see any thing goes wrong after taking away this notification, but use it as your own risk.

In addition,  `NativeGestureUtil.notifyNativeGestureStarted(this, ev)`  appeares not only in ScrollView, but also ListView (in my case), ViewPager, etc. So I believe this solution maybe the answer to all  Responder Outside Scrollable View issues

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/scrollview-panresponder

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
