### ISSUE TITLE
Blur on Multiline text is missing the text property on nativeEvent.

### ISSUE THREAD

**Issue by vijayst** [facebook/react-native#9548]
On RCTTextField (TextInput, multiline, iOS), the onBlur event is not passing the text property in the nativeEvent. The source code below may be causing the problem.

```
- (void)textViewDidEndEditing:(UITextView *)textView
{
  [_eventDispatcher sendTextEventWithType:RCTTextEventTypeEnd
                                 reactTag:self.reactTag
                                     text:textView.text
                                      key:nil
                               eventCount:_nativeEventCount];

  [_eventDispatcher sendTextEventWithType:RCTTextEventTypeBlur
                                 reactTag:self.reactTag
                                     **text:nil**
                                      key:nil
                               eventCount:_nativeEventCount];
}
```

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/blur-on-multiline-text-is-missing-the-text-property-on-nativeevent

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
