### ISSUE TITLE
[Android] Fresco initialized multiple times 

### ISSUE THREAD

**Issue by markzhai** [facebook/react-native#9558]
W/unknown:Fresco: Fresco has already been initialized! `Fresco.initialize(...)` should only be called 1 single time to avoid memory leaks!

If Android has already used Fresco in its native codes, which means we have already done 

``` java
Fresco.initialize(this, config);
```

in our application.

The `FrescoModule` will still initialize Fresco, which causes fresco initialized twice.

``` java
  @Override
  public void initialize() {
    super.initialize();
    // Make sure the SoLoaderShim is configured to use our loader for native libraries.
    // This code can be removed if using Fresco from Maven rather than from source
    SoLoaderShim.setHandler(new FrescoHandler());

    Context context = getReactApplicationContext().getApplicationContext();
    Fresco.initialize(context, mConfig);
    mConfig = null;
  }
```

We should be able to disable the second initialize.

react-native 0.31, Mac, Android.

**Comment by oprisnik** [comment]
Yeah, we are investigating this. I have added this warning for Fresco and we're currently figuring out how this can be fixed in RN.

**Comment by rigdern** [comment]
My team also hit this and created a fix. See PR #9606 for details.

**Comment by oprisnik** [comment]
This should now be fixed.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-fresco-initialized-multiple-times-

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by tasneembohra** [comment]
I am getting this issue in 0.53 
` Fresco has already been initialized! `Fresco.initialize(...)` should only be called 1 single time to avoid memory leaks!`

**Comment by midhun-murali** [comment]
I am too getting this issue in android.
This is occuring again recently after I have updated my fresco to 1.8.1
