### ISSUE TITLE
I got this error message  "Requiring unknown module "ws""

### ISSUE THREAD

**Issue by ChenCheng0914** [facebook/react-native#9559]
Hello

I got this error message when i run Android of windows10.

Requiring unknown module "ws". If you are sure the module is there, try restarting the packager or running "npm install"

I has installed ws in node_modules,Like this 
![_20160824115937](https://cloud.githubusercontent.com/assets/20809498/17917805/456c172a-69f2-11e6-99d7-781ea9c5ee36.png)

but I got this error message--"Requiring unknown module "ws". If you are sure the module is there, try restarting the packager or running "npm install""

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/i-got-this-error-message-requiring-unknown-module-ws

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
