### ISSUE TITLE
Improve AsyncStorage Documentation

### ISSUE THREAD

**Issue by pgom** [facebook/react-native#9565]
In the `AsyncStorage` section of the documentation,  there's the following statement:

`It is recommended that you use an abstraction on top of AsyncStorage instead of AsyncStorage directly for anything more than light usage since it operates globally.`

This statements led to some confusions on the `AsyncStorage` scope. 

Initially, it made me believe that `AsyncStorage` could be available globally for the entire system.  This behaviour made no sense to me but that it was validated by this article on [Auth0 blog](https://auth0.com/blog/adding-authentication-to-react-native-using-jwt/).

Having discovered that `AsyncStorage` is available only in the application scope, I think the documentation should be more explicit on this matter.

**Comment by ryankask** [comment]
Do you have any suggestions for how it could be clearer?

The paragraph before indicates that it's "global to the app":

> AsyncStorage is a simple, unencrypted, asynchronous, persistent, key-value storage system that is global to the app. It should be used instead of LocalStorage.

**Comment by SandroMachado** [comment]
@ryankask please see my stack overflow answer http://stackoverflow.com/a/39112472/3482000

**Comment by pgom** [comment]
@ryankask Actually I believe it makes more sense in the sentence below. Something like this:

```It is recommended that you use an abstraction on top of AsyncStorage instead of AsyncStorage directly for anything more than light usage since it operates globally within the app scope.```

For me, saying that is `global to the app` just means that the method can be invoked globally instead of clearly stating that `AsyncStorage` is only global to the app (and not the entire system).

**Comment by ryankask** [comment]
@SandroMachado nice explanation. I use react-native-keychain instead of storing tokens using `AsyncStorage` but it's not clear to if that makes any difference if the user was determined enough to read the data.

@pgom I agree that paragraph is confusing or maybe it's just the use of the word global in that document given that apps are sandboxed. I'm also a bit confused about the recommendation for using an abstraction because it's global. Perhaps it's meant to encourage the use of prefixes to avoid keys clashing when using it in multiple parts of the app.

**Comment by pgom** [comment]
I shared your confusion and conclusions about "abstracting". It's an evidence that the documentation could be more explicit and reliable.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/improve-asyncstorage-documentation

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by scottmas** [comment]
Doc still needs to be updated to be more explicit.... E.g. `it operates globally within the app scope.`
