### ISSUE TITLE
unable to execute js call __fbbatchedbridge is undefined under debug mode

### ISSUE THREAD

**Issue by welllin** [facebook/react-native#9575]
Hi,

I just deployed my app into App store.

Now I want to go back to my app in Debug mode and make some changes. 

What I did was change the build process in product schema from release to debug.

Then I got the following error message:

unable to execute js call __fbbatchedbridge is undefined

Anyone know what is going on? It is working beautifully under release mode.

Cheers

**Comment by welllin** [comment]
I have got a file called main.jsbundle in my project directory. does it matter. should I delete it and run again?

**Comment by welllin** [comment]
And also. I can get into debug mode by just issusing the following command.

react-native run-ios

But can't get into the debug mode from Xcode

**Comment by nihgwu** [comment]
Cmd+R

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/unable-to-execute-js-call-fbbatchedbridge-is-undefined-under-debug-mode

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by adamski** [comment]
I'm getting this issue too. Running on device, debug more, with js bundle.

**Comment by MaxwellGover** [comment]
@adamski Did you solve the issue? I'm getting the same issue on RN 0.43 and also running on device.

**Comment by LAITONEN** [comment]
I am also getting this issue from time to time. RN 0.45.1
