### ISSUE TITLE
Memory leak NavigatorExperimental

### ISSUE THREAD

**Issue by jreziga** [facebook/react-native#9578]
Hello,

I'm using NavigatorExperimental and when I'm switching between views on React 0.30.0 iOS 9.3, memory keep rising up when I push a route / pop a route again and again. Is there a tool or something to track memory leaks ? Is this a known issue or is my app abnormally memory consuming ?

Thanks.

**Comment by Andrewpk** [comment]
I'm seeing the same thing. I'm an iOS developer by day and when profiling this you can see that popped routes are never being dealloc'd. I wasn't sure if this was because I was using redux with NavigatorExperimental, but I was about to start profiling the UIExplorer example before I did a quick search to find this issue. I found another issue where someone mentioned that they were using a method to reset the navigation state in order to allow that retained memory to be released, but that seems to go against the flow of a navigator so I was avoiding that option.

**Comment by Andrewpk** [comment]
Pretty sure I'm just doing something wrong now (and you might be as well).

All the leaks I'm seeing in popular examples are in `CSSNodeListNew` and not causing entire VCs to be retained.

Offending area of tiny leaks:
```c
CSSNodeListRef CSSNodeListNew(unsigned int initialCapacity) {
  CSSNodeListRef list = malloc(sizeof(struct CSSNodeList));
  assert(list != NULL);

  list->capacity = initialCapacity;
  list->count = 0;
  list->items = malloc(sizeof(void*) * list->capacity);
  assert(list->items != NULL);

  return list;
}
```

**Comment by Andrewpk** [comment]
I retract my previous statement.

When using mapviews (even when using react-native-maps) on iOS, you can create endless mallocs simply by navigating to and from views that have mapview components in them. Memory will just climb and climb without ever being released.

**Comment by jreziga** [comment]
Can I have a look in your App & Navigation Component please ?

I tried reset but it doesn't solve anything. I'm also using the redux module but even without it I've this issue.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/memory-leak-navigatorexperimental

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
