### ISSUE TITLE
requestIdleCallback crashing on Android app launch (mReactChoreographer)

### ISSUE THREAD

**Issue by awendland** [facebook/react-native#9579]
### Problem

When `requestIdleCallback` is called outside of a Component at start, such as prior to AppRegistry getting called, results in an assertion failure within Timing.java (line 287). This is due to `mReactChoreographer` being null inside `Timing#setChoreographerIdleCallback`, because it is being executed prior to `Timing#initialize` is getting called (which sets `mReactChoreographer` by retrieving the singleton).

This error can be replicated with this `index.android.js`:

``` javascript
import React, {Component} from 'react'
import {AppRegistry, Text} from 'react-native'

requestIdleCallback(() => console.log('If this works, it\'s not broken :)')) // This will trigger the force close

AppRegistry.registerComponent('Broken App', () => () => <Text>Hello</Text>)
```
### Related

`requestIdleCallback` was implemented on Android in this PR https://github.com/facebook/react-native/pull/8569. I don't believe that it has been updated since (as far as I could tell from a quick diff b/w v0.31 and master).
### Environment
- **React Native**: 0.31
- **Dev OS**: macOS
- **App Environment**: Android Emulator, Intel x64, 6.0

**Comment by awendland** [comment]
For Google-ability, here's the stack trace when the error occurs:

```
java.lang.AssertionError
  at com.facebook.infer.annotation.Assertions.assertNotNull(Assertions.java:21)
  at com.facebook.react.modules.core.Timing.setChoreographerIdleCallback(Timing.java:287)
  at com.facebook.react.modules.core.Timing.access$2000(Timing.java:45)
  at com.facebook.react.modules.core.Timing$2.run(Timing.java:409)
```

**Comment by brentvatne** [comment]
cc @janicduplessis, seems like an easy fix

**Comment by janicduplessis** [comment]
@awendland Thanks for the detailed report, I'll take a look at it soon.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/requestidlecallback-crashing-on-android-app-launch-mreactchoreographer

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by idibidiart** [comment]
Was this ever fixed on Android @janicduplessis ?

**Comment by brentvatne** [comment]
https://snack.expo.io/SJNxdKDAb
