### ISSUE TITLE
custom spash screen

### ISSUE THREAD

**Issue by wowzaaa** [facebook/react-native#9586]
Hi

I need to add a custom splash screen of my app ... containing an animated svg ... any suggestions on how to approach this?

thanks,
Rares

**Comment by rmevans9** [comment]
Hey @wowzaaa! This sounds like a question about how to use React Native and not actually a bug within React Native. This GitHub tracker is used to track bugs. Questions like the one you have here is better suited over at Stack Overflow. I would recommend asking over there as you might get an answer quicker. Closing this.

**Comment by rmevans9** [comment]
@facebook-github-bot  stack-overflow

**Comment by rmevans9** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-0** [comment]
Hey @wowzaaa and thanks for posting this! @rmevans9 tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
