### ISSUE TITLE
'node start' CLI arguments didn't accept same options on React Native 0.32

### ISSUE THREAD

**Issue by sakim** [facebook/react-native#9603]
React Native 0.32 on Mac.

Previously, CLI options allow multiple `--root` and `--projectRoots` arguments. But, React Native 0.32 don't accept multiple same options anymore.

Previously the command below works fine:

`node node_modules/react-native/local-cli/cli.js start --projectRoots pwd/ReactComponent --projectRoots pwd/node_modules`

as a workaround on React Native 0.32, I have to change one of `--projectRoots` to `--root`

`node node_modules/react-native/local-cli/cli.js start --projectRoots pwd/ReactComponent --root pwd/node_modules`

Help shows me it allows list of values. Looks like a CLI bug.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/node-start-cli-arguments-didnt-accept-same-options-on-react-native-032

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
