### ISSUE TITLE
react.gradle file not bundling Js code

### ISSUE THREAD

**Issue by waqas19921** [facebook/react-native#9612]
i uncommented app.gradle code to following

```
/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 */
  project.ext.react = [
    // the name of the generated asset file containing your JS bundle
    bundleAssetName: "index.android.bundle",

    // the entry file for bundle generation
    entryFile: "index.android.js",

    // whether to bundle JS and assets in debug mode
    bundleInDebug: true,

    // whether to bundle JS and assets in release mode
    bundleInRelease: true,

    // whether to bundle JS and assets in another build variant (if configured).
    // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
    // The configuration property can be in the following formats
    //         'bundleIn${productFlavor}${buildType}'
    //         'bundleIn${buildType}'
    // bundleInFreeDebug: true,
    // bundleInPaidRelease: true,
    // bundleInBeta: true,

    // the root of your project, i.e. where "package.json" lives
    root: "../../",

    // where to put the JS bundle asset in debug mode
    jsBundleDirDebug: "$buildDir/intermediates/assets/debug",

    // where to put the JS bundle asset in release mode
    jsBundleDirRelease: "$buildDir/intermediates/assets/release",

    // where to put drawable resources / React Native assets, e.g. the ones you use via
    // require('./image.png')), in debug mode
    resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",

    // where to put drawable resources / React Native assets, e.g. the ones you use via
    // require('./image.png')), in release mode
    resourcesDirRelease: "$buildDir/intermediates/res/merged/release",

    // by default the gradle tasks are skipped if none of the JS files or assets change; this means
    // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
    // date; if you have any other folders that you want to ignore for performance reasons (gradle
    // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
    // for example, you might want to remove it from here.
    inputExcludes: ["android/**", "ios/**"],

    // override which node gets called and with what additional arguments
    nodeExecutableAndArgs: ["node"],

    // supply additional arguments to the packager
    extraPackagerArgs: []
  ]


apply from: "../../node_modules/react-native/react.gradle"
```

but no js is bundled in apk file upon building in both debug and release mode and no js files are placed in assets folder.

and following exception is thrown

```
08-27 03:52:08.736 9630-9630/com.simpfuel E/unknown:React: Exception in native call from JS
                                                           java.lang.RuntimeException: Could not get BatchedBridge, make sure your bundle is packaged correctly
                                                               at com.facebook.react.cxxbridge.CatalystInstanceImpl.loadScriptFromAssets(Native Method)
                                                               at com.facebook.react.cxxbridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:37)
                                                               at com.facebook.react.cxxbridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:177)
                                                               at com.facebook.react.XReactInstanceManagerImpl$4.call(XReactInstanceManagerImpl.java:889)
                                                               at com.facebook.react.XReactInstanceManagerImpl$4.call(XReactInstanceManagerImpl.java:882)
                                                               at com.facebook.react.bridge.queue.MessageQueueThreadImpl$1.run(MessageQueueThreadImpl.java:74)
                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                               at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                               at android.os.Looper.loop(Looper.java:148)
                                                               at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                               at java.lang.Thread.run(Thread.java:818)
```

![device-2016-08-27-125224](https://cloud.githubusercontent.com/assets/17469425/18026075/68479bec-6c55-11e6-943f-a0ef0639df05.png)

i am using react-native version `0.32.0`
on windows 10 and for android

**Comment by jiangqqlmj** [comment]
my question is the same with you~
But I performed manually for the following commands：
```
react-native bundle --platform android --dev false --entry-file index.android.js \
  --bundle-output android/app/src/main/assets/index.android.bundle \
  --assets-dest android/app/src/main/res/
```

you can see the following article:
![http://www.lcode.org/?p=307](http://www.lcode.org/?p=307)

**Comment by corbt** [comment]
I'm hitting this in React Native 0.34 on Android as well, but only from within Android Studio. If I run `./gradlew assembleRelease` manually, the bundle is generated correctly and the installed app works.

On the other hand, building/installing from within Android Studio skips the `:app:bundleLocalReleaseJsAndAssets` step entirely, and the bundle is not generated. Still trying to figure out what causes the difference.

**Comment by andpor** [comment]
I have the same issue. NO matter what I do, I cannot find the generated bundle file in either debug or release apk despite having uncommented project.ext.react in the app module.

**Comment by corbt** [comment]
I was able to get this working in Android Studio by going to Preferences > Build, Execution, Deployment > Build Tools > Compiler and unchecking "Configure on demand".

It was always working for me when running `./gradlew assembleRelease` from the command line, which is why I suspected an Android Studio config issue. Anyway, those are two things to try.

**Comment by andpor** [comment]
Weird. I am running on Mac OS X Captain.

1. When Studio was installed, gradlew was installed under Library/Android/sdk/tools/templates/gradle/wrapper/gradlew which was never added to PATH - had to add in manually to bash_profile
2. Even after adding this to path I cannot run ./gradlew assembleRelease - gives the following error which is not surprising since gradlew is NOT in the current directory
-bash: ./gradlew: No such file or directory
3. Running gradlew assembleRelease - caused gradle 1.14 to be installed on the mac somewhere which is obviously not what I want. Why is this happening ?

To me this whole thing is a royal nightmare. And total lack of documentation on this topic is completely ridiculous.

**Comment by jamesporter** [comment]
I had similar issues (and again running the gradlew assembleRelease thing seems to work fine but then ended up signing and zip align-ing manually which was extremely tedious).

@waqas19921 One thing worth trying is running the `bundleReleaseJsAndAssets` task in Android Studio (via Gradle view); then go to Generate Signed APK. This seemed to work reliably.

I highly recommend setting up new RN projects following closely the guide around certificates etc... unfortunately I set this one up 6 months ago and it appears that unwinding the more 'standard' Android approach (using AS + keyfile) will now be a lot of hassle.

**Comment by helengray** [comment]
I met the issues on win10 too.

I had findout the reason and solve the problem by setup the gradle.properties 
`org.gradle.configureondemand=false`

Open the Android project and edit the gradle.properties,append the above sentence.

If it still doesn't work,you can add the config for the global

![qq 20170110145256](https://cloud.githubusercontent.com/assets/6320872/21796559/95c0fb72-d744-11e6-885d-5d59babe247a.png)
![qq 20170110145314](https://cloud.githubusercontent.com/assets/6320872/21796590/b6b389e4-d744-11e6-90fc-777b5c7940e0.png)

**Comment by guilharj** [comment]
@corbt  your suggestion worked for me too.  Thanks for the help.

**Comment by norman-kapschefsky** [comment]
Hi, I would like to summarize the solution to bundle everything within a debug build. Especially the hint in point two did the trick for me. Found that in an underrated [comment](http://stackoverflow.com/a/40512480/5238186) on stackoverflow.

**1. Android Studio**
- go to Preferences -> Build, Execution, Deployment -> Compiler
- uncheck "Configure on Demand"

**2. build.gradle**
- within your `app/build.gradle` file do the following:
```
project.ext.react = [
    // whether to bundle JS and assets in debug mode
    bundleInDebug: true,

    // whether to bundle JS and assets in release mode
    bundleInRelease: true,
]

apply from: "../../node_modules/react-native/react.gradle"
```
- **NOTE** that it is important to define the react settings above the `apply from ...` statement, otherwise it will not work

**3. Create APK**
- create your dev apk as usual with `./gradlew assembleDebug` within your `android` folder

**Comment by Oblongmana** [comment]
So I think I figured it all out, I definitely and now have builds reliably running properly when hitting the "Run" button.

There are two issues (on OSX):
1) Android Studio skipping the `bundle[buildType]JsAndAssets` step for release-type builds
2) Android Studio not finding node

# To Solve:
## 1) Bundling being skipped
Uncheck "Configure on demand"
  ```
  Android Studio > 
  Preferences > 
  Build, Execution, Deployment > 
  Compiler > 
  [Untick] Configure on demand
  ```
## 2) Android Studio not finding node
Even after fixing bundling being skipped, the build still fails with `A problem occurred starting process 'command 'node''`. As noted by @andpor:
    >The apps [on OSX] do not execute any of the user shell profiles when they are started so if there is some nvm or node setup being done in files such as .bash_profile, they will not get picked app by Studio which will barf at executive react-native shell commands which are node based.

There are workarounds for trying to get apps to use your PATH, but basically - they're all terrible, relatively difficult, require restarts, and generally break between OSX versions, and for other reasons.

So the solution - when `gradle` runs, it checks `gradle.properties` as follows (documented at https://docs.gradle.org/current/userguide/build_environment.html):
>- from gradle.properties in project build dir.
>- from gradle.properties in gradle user home.

What we want to do is tell `gradle` directly what the node path is. We don't want to do this in the project's `gradle.properties` - you'll commit that to version control, and the node path may vary between developers.

Instead, you set it in the `gradle` user home. Users can override this, but generally it's `USER_HOME/.gradle`, so on OSX, generally `~/.gradle`. So (and this is the bit you want to add to your project README so your developers know how to configure it), we can configure our node path like this:
```
$ mkdir -p ~/.gradle    # make the gradle home dir, if it doesn't exist already
$ touch ~/.gradle/gradle.properties     # create a gradle.properties, if it doesn't exist already
```
Now open `/.gradle/gradle.properties` in your preferred editor, and add the line:
`NODE_PATH=/usr/local/bin/node`
Or wherever your node install is located of course - check this with `$ which node`

Open `android/app/build.gradle`
There should be a line that says 
`apply from: "../../node_modules/react-native/react.gradle"`
Just before that line, add the following (or add to your existing `project.ext.react` if you have one):
```
project.ext.react = [
    nodeExecutableAndArgs: hasProperty('NODE_PATH')?[NODE_PATH]:null
]
```
The `nodeExecutableAndArgs` is something you can configure for the `react` `gradle` file, which makes it use the path and args you supply, instead of looking in the environment (as discussed above, the environment won't work). This line checks whether the `NODE_PATH` has been configured, and uses it if supplied, and if not, sets the property to null (which causes the `react` gradle file to fall back to using the environment)

**Comment by robertsimoes** [comment]
@Oblongmana @norman-kapschefsky I love you both.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by diegoperini** [comment]
It continues and broke builds on `Android Studio 3 Preview Canary 9` with `gradle 3.0.0 alpha9`.

**Comment by diegoperini** [comment]
It continues and broke builds on `Android Studio 3 Preview Canary 9` with `gradle 3.0.0 alpha9`.

**Comment by gtzh110** [comment]
I also meet this problem:  A problem occurred starting process 'command 'node''.
on Android Studio 3.0 Preview  with gradle plugin 3.0.0 beta7 and gradle-4.1-all.

**Comment by TGPSKI** [comment]
Hi, I ran into this problem getting our Android app published, and ended up writing a medium article that addresses this and related issues.

https://medium.com/@paterw00t_17915/android-react-native-fastlane-working-with-multiple-build-types-a9a6641c5704

**Comment by diegoperini** [comment]
We ended up using a custom bash script that should be run only the first time someone clones our app repository. It creates a node wrapper specific to our developer's workstation to be used by React Native as well as CodePush build scripts by simply residing in the app's root folder. Below is the script. Copy it in a file named `prebuild.bash`, placed at the root of your app. Run it like 

`bash prebuild.bash` 

from the terminal only once. 

Script:
```
#!/bin/bash
rm $PWD/node > /dev/null
install -b -m 755 /dev/null $PWD/node
echo \#!/bin/bash >> $PWD/node
which node >> $PWD/node
printf %s "$(< node)" > node
echo -n $' \"$@\"' >> $PWD/node
```
