### ISSUE TITLE
Can't find variable URL

### ISSUE THREAD

**Issue by jaggerwang** [facebook/react-native#9615]
### Environment

iOS
react@15.3.1
react-native@0.32.0

### Error
Can't find variable: URL
![image](https://cloud.githubusercontent.com/assets/1255011/18028684/e862d186-6cb7-11e6-9c50-262d10d6363b.png)

### Related code
![image](https://cloud.githubusercontent.com/assets/1255011/18028728/66b0ddd0-6cb8-11e6-8618-cc029f632863.png)

### Analyze
It did working before, and suddenly it came out. It seems like babel not transforming correctly, I've also tried "react-native start --reset-cache".

**Comment by gmuraleekrishna** [comment]
@jaggerwang in line no. 13 you seem to be using `URL` module which is not imported yet.

**Comment by satya164** [comment]
It seems to be bug in your code.

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by satya164** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-6** [comment]
Hey @jaggerwang and thanks for posting this! @satya164 tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by lentan1029** [comment]
@jaggerwang, I had the same problem. 

URL was working because I had the Remote JS Debugger running in Chrome.

**Comment by jaggerwang** [comment]
Install npm package url to fix this.

**Comment by Naoto-Ida** [comment]
The correct answer to this should be installing [url-parser](https://www.npmjs.com/package/url-parse).
