### ISSUE TITLE
Fetch Streaming Body

### ISSUE THREAD

**Issue by ambarc** [facebook/react-native#9629]
Question about RN's fetch API spec vs the Web Spec.

For reading a JSON stream through a browser - something like this works:

```
fetch(url).then(response => {
  const reader = response.body.getReader();
  const decoder = new TextDecoder();

  reader.read().then(function process(result) {
    if (result.done) return;
    const text = decoder.decode(result.value, {stream: true});
    console.log(text);
    return reader.read().then(process);
  }).then(() => {
    console.log('All done!');
  });
});
```

However, in RN - `response.body` returns as undefined. Is this missing in RN's fetch spec? Is there an alternative to consume the partial stream?

**Comment by ambarc** [comment]
@vjeux sorry to page. Does React Native's fetch implementation support streaming?

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/fetch-streaming-body

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by yuyao110120** [comment]
This question resolved or have a plan now? Steam feature is good for download file process.

**Comment by ambarc** [comment]
ended up using websockets.
