### ISSUE TITLE
Alert appears not to be attached to Activity, stays even when Activity is killed

### ISSUE THREAD

**Issue by fab1an** [facebook/react-native#9634]
When my `Activity` is killed, when I leave it by press the HomeButton and there is an open `Alert`, then this Alert stays when I restart the app, even though the underlying Screen changes.

RN: 0.32 / Mac

**Comment by ThaJay** [comment]
confirmed on android as well.
and it's an old one.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/alert-appears-not-to-be-attached-to-activity-stays-even-when-activity-is-killed

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
