### ISSUE TITLE
Keyboard.addListener = keyboardDidShow not work when windowSoftInputMode=adjustNothing

### ISSUE THREAD

**Issue by antoxi4** [facebook/react-native#9640]
I need disable windowSoftInputMode.
And when windowSoftInputMode = adjustNothing, keyboardDidShow doesn't work. Any Idea?

**Comment by ryankask** [comment]
Please see [this issue](https://github.com/facebook/react-native/issues/2852) where it says:

> ... keyboard events are actually not triggered with adjustNothing because of the way it's implemented, and unfortunately there's no way around that. We should probably document all of this somewhere.

I don't think anything has changed.

**Comment by satya164** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-6** [comment]
Closing this issue as @satya164 says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.
