### ISSUE TITLE
[Android, iOS ] - Unknown module XXX / unable to resolve module XXX

### ISSUE THREAD

**Issue by dili91** [facebook/react-native#9643]
Hi everybody, 

I'm experiencing a very boring problem that doesn't let me include **ANY** of the node module downloaded with npm. I'm facing this issue on both **Android** and **iOS** and I can't find a suitable solution on the web. 
Seems to me a similar problem to the one already reported for iOS in the never-ending issue [#4968](https://github.com/facebook/react-native/issues/4968). Well, I tried **every** suggest indicated there with no success. 

I'm attaching some screenshots of my case. as you can see, i'm trying to require _**xml2json**_ module in this case. 

These are also the details of my dev-tools:
node : 6.4.0
npm : 3.10.3
react-native : 0.32.0
watchman: 4.7.0

I'm hoping someone could definitely identify this kind of errors because it's becoming very frustrating for lot of developers, just like me. Or, at least, highlighting these errors in a more accurate way so users can "easily" understand what's going wrong

Thanks

<img width="332" alt="android-emulator" src="https://cloud.githubusercontent.com/assets/10221348/18060665/d618050a-6e1f-11e6-9b34-e87317d25cd7.png">
<img width="498" alt="index" src="https://cloud.githubusercontent.com/assets/10221348/18060668/d65aa2e8-6e1f-11e6-9d0b-85bf17255578.png">
<img width="377" alt="ios-emulator" src="https://cloud.githubusercontent.com/assets/10221348/18060669/d65dcb26-6e1f-11e6-8575-52554408777c.png">
<img width="602" alt="package_json" src="https://cloud.githubusercontent.com/assets/10221348/18060670/d66e8a06-6e1f-11e6-8a10-5159add51610.png">
<img width="711" alt="prj_structure" src="https://cloud.githubusercontent.com/assets/10221348/18060671/d67340a0-6e1f-11e6-9c1c-2340e9dc9529.png">

**Comment by nihgwu** [comment]
RN is in running JavascriptCore, not no, and you should have noticed that the `xml2json` is for Node, you have to use `browserify` to transform the node module to a browser one

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-ios-unknown-module-xxx-unable-to-resolve-module-xxx

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
