### ISSUE TITLE
Model is containing   with text and checkbox, checking on checkbox is not updating List view

### ISSUE THREAD

**Issue by devekoperiOS** [facebook/react-native#9647]
I am using list view inside my modal. That list view is indicating items and check box. When I am checking item from list, I want that user can see the check box to be checked. I want to show check/uncheck action on list view, which is inside my modal.  Problem is that, its not rendering the list view of which is inside modal, on changing the state. Please help. Thanks in advance.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/model-is-containing-with-text-and-checkbox-checking-on-checkbox-is-not-updating-list-view

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by fannedalk** [comment]
Im facing the same problem. Did you find any solution? 
The link to productpains seems to be dead.
