### ISSUE TITLE
[NavigationExperimental] Bug on navigation header title effect

### ISSUE THREAD

**Issue by brunolemos** [facebook/react-native#9656]
In the first route, the navigation bar is hidden. In the second one, it's visible and blue.
When I swipe from one to another, you can see a rectangle with the background:

[![ios-bug-react-native-navigation-experimental.gif](https://s18.postimg.org/3zo5zgb5l/ios_bug_react_native_navigation_experimental.gif)](https://postimg.org/image/geaxzs2np/)

Important code:
```js
_renderHeader(props) {
    const { scene: { route: { navigationBarHidden } } } = props;
    return navigationBarHidden ? null : <NavigationHeader style={{backgroundColor: '#3ec4e3'}}/>;
}
```

```js
_renderScene(props) {
  const { scene: { route: { Component: SceneComponent, navigationBarHidden, passProps } } } = props;

  return (
    <View>
      {navigationBarHidden ? null : this._renderHeader(props)}
      <SceneComponent navigator={this} navigatorProps={props} {...passProps} />
    </View>
  );
}
```

In the first route, `navigationBarHidden` is `true`.

* React Native version: 0.32.0
* Platform(s) (iOS, Android, or both?): iOS
* Operating System (macOS, Linux, or Windows?): macOS 10.12

**Comment by flavordaaave** [comment]
@brunolemos  besides the "bug" you have this already looks great. I wonder hwo you achieved this because I also don't have a NavigationHeader on my first screen but when I'm sliding to go back from the second screen (where I do have a Navigation Header), the header is also visible on the first screen until the transition is completed...

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/5305150/18790315/9d175cf4-81ae-11e6-838e-95106d935d4f.gif)


My Code looks something like this:

```
const _renderOverlay = (navigatorProps) => {
  if (navigatorProps.scene.index != 0) {
    return (
      <NavBar
        title={ navigatorProps.scene.route.title }
        onLeftPress={ popScreen }
        {...navigatorProps}
      />
    )
  }
  return false
}
```

I would really appreciate if you could share your code.

Thanks!

**Comment by flavordaaave** [comment]
I had a closer look at your code. It seems like you are adding a separate Header to every scene where as I'm using the `renderHeade`r Property of `NavigationCardStack`:

```
<NavigationCardStack
  onNavigateBack={ popScreen }
  direction={ 'horizontal' }
  navigationState={ model }
  renderScene={ _renderScene }
  renderHeader={ _renderHeader }
  style={ styles.container } />
```

This renders just ONE header on top of all the scenes. The core problem with both implementations is that the Header that is coming with NavigationExperimental is always showing a transition where the a header for the previous scene is animated from left to right when swiping back. In your case, the title is empty but the element is still animating in from left to right with the background set in your styles. So far I didn't find a solution to conditionally disable this animation.

Just a note on your implementation. If you have a third screen that also has a Header, the transitions is not that pretty anymore because the header is rendered inside the scene and is also scaled with the scene transition. So I recommend to use the `renderHeader` property of  `NavigationCardStack`.
![ezgif com-video-to-gif-2](https://cloud.githubusercontent.com/assets/5305150/18799100/346a26a0-81d6-11e6-98d4-82ab0ea1e8cb.gif)

**Comment by brunolemos** [comment]
@flavordaaave thanks for your tips. I stopped using NavigationExperimental, I'm using `react-native-router-flux` instead. It was easier to get to the desired behaviour. But I believe it uses NavigationExperimental itself.

**Comment by ptomasroos** [comment]
Yup. Having same problems here. @ericvicenti something we can get assistance on?

**Comment by ericvicenti** [comment]
The header was not designed to be used in this way. There is only supposed to be one header for each NavigationCardStack that is always visible, defined with by `<NavigationCardStack renderHeader={}`. If you don't want an animated header, you can construct a static one in your scene.

You may be able to use `<NavigationHeader>` in this way, but you probably want to override the `position` and `progress` props to null.

**Comment by flavordaaave** [comment]
@brunolemos I ended up hacking into the core components of NavigationExperimental to achieve the desired behavior.
This is most likely not the way to go but it works for me for now. I uploaded the files that I used/modified to this [Gist](https://gist.github.com/flavordaaave/ba44e14046389f4676e6978b80d68b8e)

Then I use the header like this:

```
  import NavigationCardStack from '..PATH_TO_MY_MODIFIED_FILES/NavigationCardStack'
  import NavBar from '..PATH_TO_MY_MODIFIED_FILES/NavBar'

  const _renderHeader = navigatorProps => (
    <NavBar
      onLeftPress={ popScreen }
      {...navigatorProps}
    />
  )

  <NavigationCardStack
    renderHeader={ _renderHeader }
    ... />
```

And then my initial route has a property `hideNavBar`

```
routes: [
  {
    key: 'home',
    title: 'Home',
    hideNavBar: true,
    ...
  },
]
...
```

NOTE: This is just something I came up quick and dirty. There are also some other modifications in the Gist that I used to further customize it to my needs.

@brunolemos I ended up hacking into the core components of NavigationExperimental to achieve the desired behavior.
This is most likely not the way to go but it works for me for now. I uploaded the files that I used/modified to this [Gist](https://gist.github.com/flavordaaave/ba44e14046389f4676e6978b80d68b8e)

Then I use the header like this:

```
  import NavigationCardStack from '..PATH_TO_MY_MODIFIED_FILES/NavigationCardStack'
  import NavBar from '..PATH_TO_MY_MODIFIED_FILES/NavBar'

  const _renderHeader = navigatorProps => (
    <NavBar
      onLeftPress={ popScreen }
      {...navigatorProps}
    />
  )

  <NavigationCardStack
    renderHeader={ _renderHeader }
    ... />
```

And then my initial route has a property `hideNavBar`

```
routes: [
  {
    key: 'home',
    title: 'Home',
    hideNavBar: true,
    ...
  },
]
...
```

NOTE: This is just something I came up quick and dirty. There are also some other modifications in the Gist that I used to further customize it to my needs. There are a lot of limitations with this (e.g. this only works if the first route has NO header, for routes coming up after you'd need to do some further tweaking). Take this as an inspiration do create your own ;-)

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/5305150/18963234/5bb5f3d6-8674-11e6-93fd-c21fcfa970e8.gif)
