### ISSUE TITLE
Can react native require a javascript module that downloaded from the internet dynamically?

### ISSUE THREAD

**Issue by YjyJeff** [facebook/react-native#9663]
I want to write an app that can dynamically require a javascript module that downloaded from the internet.For example,the app downloads a simple js module via react-native-fs's downloadFile function ,the js module as follows:
```
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
} from 'react-native';

module.exports = class Hello extends Component {
  render() {
    return (
      <Text>Hello World.</Text>
    );
  }
}
```
How could I use the Hello class as a component in index.android.js file? I just want to execute the code dynamically.

As far as I konw, to use the js module, I have to require or import the js module. However, I can not require the file or import the js module(I guess I can only require the js module that bundled into the js bundle).

Does react native support this feature? I know react native can dynamically downloads js bundle from the internet. Does it support a single js file and execute the js module?

**Comment by cosmith** [comment]
@facebook-github-bot stackoverflow

**Comment by cosmith** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-9** [comment]
Hey @YjyJeff and thanks for posting this! @cosmith tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
