### ISSUE TITLE
RN 0.32 doc errata?

### ISSUE THREAD

**Issue by leonardgithub** [facebook/react-native#9673]
I found that:
default value of alignItems: flex-start in RN, stretch in CSS.
default value of flex-direction: column in RN, row in CSS.

But in http://facebook.github.io/react-native/docs/layout-props.html, the RN 0.32 doc says:
It works like align-items in CSS, except the default value is stretch instead of flex-start.
It works like flex-direction in CSS, except the default is column.
So, I am comfused with the "except... instead of" clauses. Which are the truly default values for the two props in RN, respectively?
#### Expected Results

I hope it can be consistent:
except the default value is [RN default] instead of [css default]
OR
except the default value is [css default] instead of [RN default]

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/rn-032-doc-errata

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
