### ISSUE TITLE
Navigation.NavigationBar leftButton height limits the content height

### ISSUE THREAD

**Issue by wowzaaa** [facebook/react-native#9682]
hey everyone,

I was trying to build my first navigation and i hit a bump
If i use a Navigation.NavigationBar with a height of 200px ... my LeftButton content cannot drop below 50-55 because it is truncated
If u combine this with translucent: true ... u r left with 26 dp (50 - status bar) which are not enough to have usable content inside

am i getting this wrong somehow? i tried every possible combination (embedding every element in a view and so on) 

thanks,
Rares

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/navigationnavigationbar-leftbutton-height-limits-the-content-height

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
