### ISSUE TITLE
Unexpected end-of-input: expected close marker for OBJECT

### ISSUE THREAD

**Issue by ThaJay** [facebook/react-native#9683]
hey,
I don't know what to do with this one as it's about java code. This error regularly pops up directly after a reload in the android emulator and I haven't figured out why just yet.
![end-of-input java error](https://cloud.githubusercontent.com/assets/9341747/18129341/a7db6206-6f8a-11e6-891a-c1518b6a98cb.png)

```
com.fasterxml.jackson.core.JsonParseException: Unexpected end-of-input: expected close marker for OBJECT (from [Source: java.io.StringReader@348ff60; line:1, column: 0]) at [Source: java.io.StringReader@348ff60; line: 1, column: 61]
```

I'm on version 29.2

**Comment by madhums** [comment]
And I have observed that it mostly happens when remote debugging is "On".

**Comment by lacker** [comment]
Can you figure out if this is happening from within your code or from within the code-reloading framework? If it's the latter then it sounds like a broken socket and maybe the solution is just to reload/retry if there is something borked with your local sockets.

**Comment by ThaJay** [comment]
I don't remember how this occurred and it doesn't happen with new versions.
Nowadays I just get a never ending stream of `unhandled promise rejection` from time to time that is impossible to debug.

**Comment by lacker** [comment]
OK. Well I'm sorry this is happening, but since it sounds like it doesn't happen with new versions I suspect this is fixed by one of the miscellaneous performance & stability improvements that have gone into this component over the last few months. So I am going to close this issue, and suggest to future people looking at this issue that they upgrade to 0.40+ versions of RN. Thanks for reporting this!
