### ISSUE TITLE
Issue templating note about .babelrc / react-native "doctor"

### ISSUE THREAD

**Issue by fab1an** [facebook/react-native#9684]
I think it would be a good idea to either prevent the react-transformer from using `.babelrc` or add this information to the issue-template:

> Babel will look for a .babelrc in the current directory of the file being transpiled. If one does not exist, it will travel up the directory tree until it finds either a .babelrc, or a package.json with a "babel": {} hash within.

(source: https://babeljs.io/docs/usage/babelrc/)

This caused me and other developers hours. One unrelated `.babelrc` in your homedirectory or else can break your build in very confusing ways.

Another idea, since I believe many people don't read the template would be a `react-native doctor` command that scans for issues like this.

**Comment by fab1an** [comment]
Another idea, since I believe many people don't read the template would be a `react-native doctor` command that scans for issues like this.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/issue-templating-note-about-babelrc-react-native-doctor

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by fab1an** [comment]
I would reopen this issue, because it would help *developers* and *maintainers* of this project. It would reduce the number of bug-reports.

This is not a good bug for product pains, because users of react-native will never vote for it.

**Comment by charpeni** [comment]
@fab1an Closed issues can also be found, but I'll reopen this issue. Be aware that it will be closed again in a few months if it is no longer active.

PRs are welcome :)

**Comment by charpeni** [comment]
@facebook-github-bot reopen

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
