### ISSUE TITLE
How to disable "select - copy - past" in WebView?

### ISSUE THREAD

**Issue by siyuan** [facebook/react-native#9686]
Thanks.

**Comment by leeight** [comment]
Looks like there is no available property in `<WebView />` component to disable selection. You can reference <http://stackoverflow.com/questions/5107651/android-disable-text-selection-in-a-webview> to address this issue.

**Comment by siyuan** [comment]
@leeight Thank you for your replay. How to port Android code to react-native?

**Comment by Kureev** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-4** [comment]
Hey @siyuan and thanks for posting this! @Kureev tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
