### ISSUE TITLE
Upgrade from 0.28 to 0.32 - 'android:name=".MainApplication"' missing from AndroidManifest.xml

### ISSUE THREAD

**Issue by janaka** [facebook/react-native#9690]
### Issue Description
I upgraded the TodoMVC example from to 0.32 and `android:name=".MainApplication"` did not get added to `<application>` in AndroidManifest.xml didn't

### Steps to Reproduce / Code Snippets
From the TodoMVC example dir
package.json - update `react-native` dependency to 0.32
run `npm install`
run `react-native upgrade`

run `react-native run-android` fails

#### Expected Results

The application build and runs successfully

### Additional Information

* React Native version: 0.28
* Platform(s) (iOS, Android, or both?): Android, untested for iOS
* Operating System (macOS, Linux, or Windows?): Windows 8

**Comment by lavystord** [comment]
Add android:name=".MainApplication" in the <application /> section of AndroidManifest.xml. It should now look like,

<application
+   android:name=".MainApplication"
    android:allowBackup="true"
    android:label="@string/app_name"
    android:icon="@mipmap/ic_launcher"
    android:theme="@style/AppTheme">

**Comment by satya164** [comment]
@facebook-github-bot answered

**Comment by satya164** [comment]
In future, please check release notes while upgrading since we document breaking changes and migration steps there.

**Comment by facebook-github-bot-3** [comment]
Closing this issue as @satya164 says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.
