### ISSUE TITLE
Adding additional roots when creating the bundled APK

### ISSUE THREAD

**Issue by benedicthsieh** [facebook/react-native#9694]
### Issue Description

Adding additional roots when creating the bundled APK
### Steps to Reproduce / Code Snippets

Our project is currently organized like this:

```
/
./App/
./common/
./www/
```

We run our react native app by first starting up the packager with the additional ./common root
`./App/node_modules/react-native/packager/packager.sh --root ./common`
and then
`cd App
react-native run-android`

Now, my question is how to include the additional ./common directory when generating an APK, following the steps here: https://facebook.github.io/react-native/docs/signed-apk-android.html Otherwise, the program fails to find anything inside our ./common/ folder, as expected.

It seems neither `cd android && ./gradlew assembleRelease` nor `react-native bundle` talk to the packager. We also tried modifying the build.gradle file with `extraPackagerArgs: ["--root", "../../../common"]`, but that didn't seem to help.

We were able to implement a workaround by `cp -R ./common ./App/node_modules` before bundling, but we're not sure if that's the right approach.
- React Native version: 0.31.0
- Platform(s) (iOS, Android, or both?): Android, would appreciate instructions for iOS as well
- Operating System (macOS, Linux, or Windows?): macOS

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/adding-additional-roots-when-creating-the-bundled-apk

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
