### ISSUE TITLE
android RefreshControl respects progressViewOffset only during pull-to-refresh and not on initial mount

### ISSUE THREAD

**Issue by jrs-onforce** [facebook/react-native#9703]
"react-native": "^0.29.0"

progressViewOffset works when pulling to refresh, but when the 'refreshing' property is set to true when the component mounts, the offset does not seem to be recognized and it draws at the very top. From there, again, when pulling to refresh, progressViewOffset is respected.

Here, while NOT using pull, it is not respecting the offset:

![screen shot 2016-08-31 at 5 01 23 pm](https://cloud.githubusercontent.com/assets/20481442/18168298/fbef790c-7022-11e6-98f6-21395ebc2bef.png)

Here, after pull-to-refresh, it is respecting the offset:

![screen shot 2016-09-01 at 9 01 33 am](https://cloud.githubusercontent.com/assets/20481442/18168315/0d9e4944-7023-11e6-87c6-1790675d99eb.png)

Thanks in advance!

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-refreshcontrol-respects-progressviewoffset-only-during-pull-to-refresh-and-not-on-initial-mount

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by zhuyifan2013** [comment]
How about this bug ?
