### ISSUE TITLE
could official support nodejs common module like fs, path, crypto embed in react-native?

### ISSUE THREAD

**Issue by fov42550564** [facebook/react-native#9709]
do you have the plan? 
or only depend thirdparty?

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/could-official-support-nodejs-common-module-like-fs-path-crypto-embed-in-react-native

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
