### ISSUE TITLE
How to use Zlib in ReactNative

### ISSUE THREAD

**Issue by yikuyirong** [facebook/react-native#9712]
I want to use Zlib feature in ReactNative .

when I use ...

import zlib from 'zlib'

RN show index.android.bundle:24290Requiring unknown module "zlib".If you are sure the module is there, try restarting the packager or running "npm install".

How to do...    React native include ZLIB ?

### Additional Information

* React Native version: 0.32
* Platform(s) (iOS, Android, or both?): android
* Operating System (macOS, Linux, or Windows?): Windows 10

**Comment by lavystord** [comment]
@facebook-github-bot  stackoverflow

**Comment by satya164** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-9** [comment]
Hey @yikuyirong and thanks for posting this! @satya164 tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by diogoviannaaraujo** [comment]
Got nothing on stack overflow, im too strugling with zlib when trying to use pdfjs to render some pdf documents

**Comment by anuraghkp1** [comment]
You can use  package https://www.npmjs.com/package/react-zlib-js to get zlib in react-native
