### ISSUE TITLE
WebView some time can't load web page

### ISSUE THREAD

**Issue by fq050766** [facebook/react-native#9714]
### Issue Description

When I use webView in my app, some time it can't open web page；
### Steps to Reproduce / Code Snippets

1、open pageA
2、open pageB
3、go back to pageA by "this.refs[WEBVIEW_REF].goBack();"
4、open pageB, now pageB can't open.
#### Expected Results

fixed it
### Additional Information
- React Native version: 0.32.0
- Platform(s) (iOS, Android, or both?): iOS
- Operating System (macOS, Linux, or Windows?): macOS

**Comment by hramos** [comment]
Can you provide a code snippet?

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/webview-some-time-cant-load-web-page

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by AndreyPatseiko** [comment]
can't open page https://partner.vtbins.ru/b2c/ in real device Nexus, android 6.0 react-native 0.42
