### ISSUE TITLE
[Android] backfaceVisibility not working.

### ISSUE THREAD

**Issue by antoxi4** [facebook/react-native#9718]
View Style backfaceVisibility on android not working.

just set backfaceVisibility: 'hidden' and nothing happen.

**Comment by nihgwu** [comment]
that's also a knowing issue 😀 #6695 , has been pending for a long time

**Comment by antoxi4** [comment]
@nihgwu  Ahaha, thanks again)

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-backfacevisibility-not-working

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
