### ISSUE TITLE
Using <Text> within <TabBarIOS> and a <NavigatorIOS> component makes Text lay behind Navigator

### ISSUE THREAD

**Issue by bk10287** [facebook/react-native#9722]
### Issue Description

When using a TabBarIOS component on a screen that also has a NavigatorIOS component, Text components are not being given enough margin to begin the ending point of the NavigatorIOS component
### Steps to Reproduce / Code Snippets

Create an IOS app, and include a NavigatorIOS component that contains a TabBarIOS.Item component which also contains an view component with a child text component.  Notice that the text component will not show up on the page.  However, if you add sufficient margin (~60), the text will show up underneath the Navigator Bar.  And then if sibling components are added, they are pushed down by the added margin.
#### Expected Results

Expected: Text shows up properly underneath the Navigator
Actual: Text is being put at the top of the app
### Additional Information
- React Native version: 0.32
- Platform(s) (iOS, Android, or both?): iOS
- Operating System (macOS, Linux, or Windows?): macOS

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/using-text-within-tabbarios-and-a-navigatorios-component-makes-text-lay-behind-navigator

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
