### ISSUE TITLE
AsyncStorage.multiGet does not forward errors from native

### ISSUE THREAD

**Issue by sfrdmn** [facebook/react-native#9724]
### Issue Description

AsyncStorage.js#multiGet does not forward errors from native
### Steps to Reproduce / Code Snippets

Check it out:

https://github.com/facebook/react-native/blob/0.32-stable/Libraries/Storage/AsyncStorage.js#L259-L277
#### Expected Results

The multiGet operation should forward errors via `callback(errors)` and `reject([errors, result])`

(reject should be passed a tuple of the errors and the result. This is because the operation may be  partially successful)
### Additional Information
- React Native version: 0.32
- Platform(s) (iOS, Android, or both?): both
- Operating System (macOS, Linux, or Windows?): all

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/asyncstoragemultiget-does-not-forward-errors-from-native

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
