### ISSUE TITLE
Linking does not open mailto with body for Android

### ISSUE THREAD

**Issue by vu-dang** [facebook/react-native#9726]
Using Linking.openURL to open a mailto link with subject and body params works as expected in iOS but does not work in Android.  In Android, an email is open but the body is empty.

**Comment by ubatin** [comment]
@facebook-github-bot stackover-flow

**Comment by ryankask** [comment]
@facebook-github-bot stackover-flow

**Comment by ryankask** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-5** [comment]
Hey @vu-dang and thanks for posting this! @ryankask tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
