### ISSUE TITLE
[Fresh project install] Upgrade version of Yeoman Generator 

### ISSUE THREAD

**Issue by andresn** [facebook/react-native#9728]
Hi There,

I think the version of Yeoman needs to be upgraded to at least v0.24.1, otherwise we get this warning:

https://github.com/yeoman/generator/issues/934

```
(master)*$ npm ls yeoman-generator
MyApp@0.0.1 /Users/andresn/dev/MyApp
└─┬ react-native@0.32.0
  └── yeoman-generator@0.21.2 
```

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot label Tooling

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/fresh-project-install-upgrade-version-of-yeoman-generator-

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
