### ISSUE TITLE
React Native - Buck Integration, iOS

### ISSUE THREAD

**Issue by dili91** [facebook/react-native#9737]
Hi, 
here is the link of a question I posted on stackoverflow

http://stackoverflow.com/questions/39180614/react-native-build-with-buck-and-nuclide-features

Every answer would be really appreciated

thanks

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-5** [comment]
Hey @dili91 and thanks for posting this! @DanielMSchmidt tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
