### ISSUE TITLE
Customize Error Page

### ISSUE THREAD

**Issue by iceNuts** [facebook/react-native#974]
I am wondering if there is a way to use self error pages like network failure things.

Thanks.

**Comment by nicklockwood** [comment]
The red box error screen is only for development purposes, and won't show up in a real app.

There's nothing to stop you presenting an error alert using AlertIOS, or building a custom error screen to display in the event of catching a JS exception, but I'd advise against it, as it's not a great user experience.

Users don't expect to see 404-style error pages in a native app - the ideal scenario is that you should ship your app without any showstopping crashes, but in the event that a React Native app does throw an uncaught exception in a release build, it will quit to the home screen lust like a normal app.

Network failures, and other "expected" errors should always be sent back to your JS code in the form of error callbacks, so you can handle these gracefully and appropriately to the context in which they arise, rather than needing to resort to exception handlers and red/blue/pink screens of death :-)
