### ISSUE TITLE
Is there a similar android native ExpandableLayout  component?

### ISSUE THREAD

**Issue by guowang1102** [facebook/react-native#9756]
[ExpandableLayout](https://github.com/AAkira/ExpandableLayout )

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-5** [comment]
Hey @guowang1102 and thanks for posting this! @charpeni tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
