### ISSUE TITLE
Clarity of tutorial in accessing camera roll view

### ISSUE THREAD

**Issue by mdrmuhaimin** [facebook/react-native#9779]
### Issue Description

I am new to react-native I am trying to follow the camera roll tutorial. However, I get stuck on [the following line](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/CameraRollExample.js#L40).  

```
const CameraRollView = require('./CameraRollView');

const AssetScaledImageExampleView = require('./AssetScaledImageExample');
```

I am wondering from where are the code of the following 2 files? 
### Steps to Reproduce / Code Snippets

N/A

#### Expected Results

N/A

### Additional Information

* React Native version:N/A
* Platform(s) (iOS, Android, or both?): both
* Operating System (macOS, Linux, or Windows?): all

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of React Native.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #react-native](http://stackoverflow.com/questions/tagged/react-native)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

**Comment by mdrmuhaimin** [comment]
@hramos can you help me with this question? 
http://stackoverflow.com/questions/39416408/react-native-get-all-photos-from-camera-roll-and-camera-roll-api
