### ISSUE TITLE
[Improvement] TabBarIOS auto reRender when willChangeStatusBar

### ISSUE THREAD

**Issue by yutin1987** [facebook/react-native#9785]
![tabbar](https://cloud.githubusercontent.com/assets/2505934/18303845/aa115116-7511-11e6-849f-38ede185c36f.gif)

if I want to fix it, have any ideas?
or don't fix it ?

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/improvement-tabbarios-auto-rerender-when-willchangestatusbar

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
