### ISSUE TITLE
couldn't add a  View  or some other Component over the  MapView

### ISSUE THREAD

**Issue by xiongcaichang** [facebook/react-native#9806]
I couldn't add a  View  or some other Component over the  MapView ,
I have try it with all I can thought . the  component what I have add over the MapView  still can't display

I hope you can fix this issue .
                                                                                                                        thanks

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/couldnt-add-a-view-or-some-other-component-over-the-mapview

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
