### ISSUE TITLE
RCTEventEmitter `supportedEvents()` override in Swift

### ISSUE THREAD

**Issue by nicholaswyoung** [facebook/react-native#9811]
I have the following Swift code:

``` swift
@objc(AudioEngine)
class AudioEngine: RCTEventEmitter {
  @objc override func supportedEvents() -> [String]! {
    return ["player.currentItem.duration", "player.currentItem.status"]
  }

  @objc func enqueue(url: String) -> Void {
    let url = NSURL(string: url)
    let asset = AVURLAsset(URL: url!)
    let item = AVPlayerItem(asset: asset)

    player.insertItem(item, afterItem: nil)
  }

  @objc func play() {
    player.play()
  }

  func pause() {
    player.pause()
  }
  // ...
}
```

It is bridged with:

``` objc
#import "RCTBridge.h"
#import "RCTEventEmitter.h"

@interface RCT_EXTERN_MODULE(AudioEngine, NSObject)

RCT_EXTERN_METHOD(supportedEvents)
RCT_EXTERN_METHOD(enqueue:(NSString *) url)
RCT_EXTERN_METHOD(play)
RCT_EXTERN_METHOD(pause)

@end
```

Any time I attempt to add an observer, I receive:

```
2016-09-08 09:12:00.420 Tap[66656:6803266] *** Assertion failure in +[RCTEventEmitter initialize](), /.../React/Modules/RCTEventEmitter.m:29
2016-09-08 09:12:00.421 [fatal][tid:com.facebook.react.AudioEngineQueue] Exception 'You must override the `supportedEvents` method of NSKVONotifying_AudioEngine' was thrown while invoking play on target AudioEngine with params (
)
```

Reading over the documentation, it seems that I understand the API. But I'm still seeing the above error. 

XCode 7.3.1 (7D1014)
iOS 9.3 (Deployment Target)

**Comment by algesten** [comment]
Are you really supposed to bridge the `supportedEvents`? Isn't that just internal for the native side?

**Comment by nicholaswyoung** [comment]
Maybe, @algesten. If I'm handling this incorrectly (which I could be), it's because the docs are horribly out of date... There's next to no information on this subject.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/rcteventemitter-supportedevents-override-in-swift

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
