### ISSUE TITLE
WebView should reload if headers change

### ISSUE THREAD

**Issue by idris** [facebook/react-native#9814]
If the headers change on a WebView, it should reload.

Currently, this doesn't happen because [RCTWebView prevents reloading if the URL is the same as before](https://github.com/facebook/react-native/blob/29febb9b1e6c17c61000d80ef3703f697c5c1a03/React/Views/RCTWebView.m#L106-L108).

Here's a simple example:

```
<WebView source={{ uri: 'http://scooterlabs.com/echo', headers: { test: this.props.headerValue } }} />
```

Just change `props.headerValue` and the echo page will still show the previous header value.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/webview-should-reload-if-headers-change

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
