### ISSUE TITLE
Ambuiguous "Missing key prop" warning when using ListView

### ISSUE THREAD

**Issue by simonayzman** [facebook/react-native#9816]
### Issue Description

When using ListViews and providing components to render without section + row information, an ambiguous warning is thrown "Missing key prop..." Only two functions can cause this, renderRow and renderSeparator, but this warning does not provide enough information to indicate that that's where the problem lies.

**Comment by zetachang** [comment]
This is described in reactjs doc https://facebook.github.io/react/docs/multiple-components.html#dynamic-children .

The `renderRow` signature is `(rowData, sectionID, rowID, highlightRow) => renderable`, so the quick fix would be simply use the `rowID` as the key to the component, but the real solution require the better understanding about the rowData you provided.

**Comment by simonayzman** [comment]
Yeah, definitely. After a bunch of research, I realized that that was the problem. I just mean that the warning itself could probably be more descriptive.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/ambuiguous-missing-key-prop-warning-when-using-listview

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
