### ISSUE TITLE
[Xcode 8] Move TravisCI tests to run with Xcode 8 and iOS 10

### ISSUE THREAD

**Issue by ide** [facebook/react-native#9818]
TravisCI already supports Xcode 8 GM. Not sure if everything will work out of the box with TravisCI since some Xcode changes have been causing problems with xctool and xcodebuild but nothing we can't solve eventually.

cc @bestander

**Comment by bestander** [comment]
Yeah, it makes sense.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/xcode-8-move-travisci-tests-to-run-with-xcode-8-and-ios-10

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
