### ISSUE TITLE
Build stopped while try run "react-native run-ios"

### ISSUE THREAD

**Issue by younthu** [facebook/react-native#9821]
While i try to run command "react-native run-ios", it launchs simulator, then stopped at an uncertain step.

Below is the output, it hangs there forever.

Anyone know how to resolve it please?

`
➜  dgAndroid git:(master) react-native run-ios
Found Xcode project DealGlobe.xcodeproj
Launching iPhone 6 (9.3)...
Building using "xcodebuild -project DealGlobe.xcodeproj -scheme DealGlobe -destination id=CF4EDCED-3D60-4328-870A-C95051DB0064 -derivedDataPath build"
User defaults from command line:
    IDEDerivedDataPathOverride = /Users/andrewy/sourcecode/github/androiddg/ReactNative/dgAndroid/ios/build
`

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/build-stopped-while-try-run-react-native-run-ios

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by TSMMark** [comment]
For the record, a colleague of mine was experiencing the same issue (hanging after the `IDEDerivedDataPathOverride` line). He restarted his MacBook and the problem disappeared. :man_shrugging:

**Comment by Prateek479** [comment]
@younthu : Did you finally find any solution for this , I try reinstalling react-native-cli upgrading/downgrading version , reinstalling node  nothing helps .

+1 for the issue ,

**Comment by TahmidRahman** [comment]
@Prateek479 did you solve this issue?

**Comment by younthu** [comment]
@Prateek479 ,

I resolved it by launching it from Xcode, after that, you will be able to run it from terminal.

**Comment by EsdrasEtrenne** [comment]
+1 restarted computer and good to go
