### ISSUE TITLE
Error while updating 'nativeBackgroundAndroid' of a view managed by: RCTView

### ISSUE THREAD

**Issue by xristos3490** [facebook/react-native#9826]
### Issue Description

When i run-android on API 23 everything works fine, but when i try to test in API 19 i get this strange error message:

Error while updating 'nativeBackgroundAndroid' of a view managed by: RCTView

I cant figure out what is causing this type of error, specially on specific API level

Thank you
### Additional Information
- React Native version: 0.29.0
- Platform: Android
- Operating System: Windows

**Comment by orlando** [comment]
This is happening to me when using an Animated view as the first view of our application.

We have something like this

```jsx
      <Animated.View style={{flex: 1, opacity: this.state.fadeAnimation }}>
        <App />
      </Animated.View>
```

If I remove the `Animated.View` then it works correctly.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/error-while-updating-nativebackgroundandroid-of-a-view-managed-by-rctview

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by alainib** [comment]
i have this error. 
my code work on android 7 but i tryed to test the application on android 4.1 and i get this error.

my android/app/build.gradle

	android {
		compileSdkVersion 23
		buildToolsVersion "23.0.1"

		defaultConfig {
			applicationId "com.iosreacttestplantnet2"
			minSdkVersion 16
			targetSdkVersion 22
			versionCode 1
			versionName "1.0"
			ndk {
				abiFilters "armeabi-v7a", "x86"
			}
			vectorDrawables.useSupportLibrary = true
		}
                ... }

any advice please ?

**Comment by germanurrus** [comment]
hello @orlando when you say: "You can fix this using the Platform library from react native and checking for the Platform.Version" how would you use this to check the platform version? how would you avoid using the Ripple Effect by checking the platform...it seems obvious the response...but do to change something in the configuration to avoid using Ripple Effect...in my case I believe I'm getting this error since I'm using Animated.View...Thanks!

**Comment by orlando** [comment]
@germanurrus we are using this in a button, and in the component constructor we do this

```js
  constructor(props) {
    super(props);
    this.background = TouchableNativeFeedback.SelectableBackground();

    if (Platform.Version >= 21) {
      this.background = TouchableNativeFeedback.Ripple('#FFFFFF');
    }

    this.state = {
      activeStyles: {}
    };
  }
```

Then we will have the Ripple effect in the button only where's supported. I hope that helps
