### ISSUE TITLE
`Unable to resolve module` shows the wrong module

### ISSUE THREAD

**Issue by sigurdsvela** [facebook/react-native#9827]
### Issue Description

When importing some `Module A`, which in turn imports some unresolvable `Module B` the error message shown says `Unable to resolve Module A`.

In my case(the one in the screenshot below), I'm trying to import `webtorrent`, which in turn imports the npm package `events`, which is unresolvable. But the error message erroneously show that `webtorrent` is the module it can't resolve. 

![screen shot 2016-09-09 at 17 28 31](https://cloud.githubusercontent.com/assets/5571884/18392687/fe808d78-76b2-11e6-9f7f-4e773e8242d5.png)
### Steps to Reproduce / Code Snippets

Try to import a module which in turn imports a module that does not exist.
#### Expected Results

It should show that `Module B`(from the issue description) is the module that can't be found.
### Additional Information
- React Native version: 0.32.1
- Platform(s) (iOS, Android, or both?): iOS
- Operating System (macOS, Linux, or Windows?): macOS

**Comment by nihgwu** [comment]
be aware that RN is not Node, you can't use it directly, and seems the error message is right

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/unable-to-resolve-module-shows-the-wrong-module

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
