### ISSUE TITLE
about WebView, when set 'baseUrl', only show html source string.

### ISSUE THREAD

**Issue by cdmalcl** [facebook/react-native#9835]
Whether it is the issue of bug:
http://stackoverflow.com/questions/39396716/react-native-webviewwhen-add-baserrl-then-just-show-html-string

when set 'baseUrl', only show html source string.
but this control is works: 
https://github.com/lucasferreira/react-native-webview-android

**Comment by leeight** [comment]
Can not reproduce it on the master branch with following code:

```
  {
    title: 'Static HTML',
    render(): ReactElement<any> {
      return (
        <WebView
          style={{
            backgroundColor: BGWASH,
            height: 200,
          }}
          source={{html: HTML, baseUrl: 'file:///android_asset/'}}
          scalesPageToFit={true}
        />
      );
    }
  }
```

![image](https://cloud.githubusercontent.com/assets/104052/18438166/c767e6f6-7932-11e6-9678-43ade0a5c8a3.png)

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/about-webview-when-set-baseurl-only-show-html-source-string

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
