### ISSUE TITLE
Webview crashed 

### ISSUE THREAD

**Issue by falltodis** [facebook/react-native#9837]
I meet a problem where change webview very quickly ,the webview will crash and display none until restart app.
the same code 

```
this.state.buttonIndex = 1
render() {
    let content = this.state.buttonIndex ==1 ? <WebView> : <ListView>
   <View>
      <Button   onPress = {this.changeState}/>
      {content}
   <View>
}
```

This will happend when I press button quickly .
Just as I test, It only occur on android

Some logs may be helpful:

```
09-09 15:05:53.688: E/DataReductionProxySettingListener(25014): No DRP key due to exception:java.lang.ClassNotFoundException: com.android.webview.chromium.Drp
09-09 15:05:53.753: E/SELinux(338): avc:  denied  { find } for service=batteryproperties scontext=u:r:untrusted_app:s0:c512,c768 
```
### Additional Information
- React Native version: [0.31]
- Platform(s) (iOS, Android, or both?): [Android]
- Operating System (macOS, Linux, or Windows?): [Mac]

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/webview-crashed-

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
