### ISSUE TITLE
Navigator: presentedIndex on push is incorrect and results in re-render

### ISSUE THREAD

**Issue by arvindch** [facebook/react-native#9842]
### Issue Description

Refer: [Navigator.js](https://github.com/facebook/react-native/blob/v0.33.0/Libraries/CustomComponents/Navigator/Navigator.jsl)

When a `route` is [pushed](https://github.com/facebook/react-native/blob/v0.33.0/Libraries/CustomComponents/Navigator/Navigator.js#L1056) to `Navigator`, `setState` is [called](https://github.com/facebook/react-native/blob/v0.33.0/Libraries/CustomComponents/Navigator/Navigator.js#L1066) before `_transitionTo` takes place. This means when [rendering](https://github.com/facebook/react-native/blob/v0.33.0/Libraries/CustomComponents/Navigator/Navigator.js#L1282) the Routes, the `render` function sees the old value of `presentedIndex` and `index !== this.state.presentedIndex` fails for the previous route and results in an unecessary re-render.
### Steps to Reproduce / Code Snippets

Add a `console.log(route)` at [L1283](https://github.com/facebook/react-native/blob/v0.33.0/Libraries/CustomComponents/Navigator/Navigator.js#L1283) and [L1285](https://github.com/facebook/react-native/blob/v0.33.0/Libraries/CustomComponents/Navigator/Navigator.js#L1285), to track which routes are re-rendered. You will see that both previous and new route are re-rendered on `push`.
#### Expected Results

Previous route has already been rendered. Should result in a cache hit and not be re-rendered.
### Additional Information
- React Native version: [0.33]
- Platform(s): [both]
- Operating System [linux]

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/navigator-presentedindex-on-push-is-incorrect-and-results-in-re-render

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by arvindch** [comment]
@charpeni - Did anyone on the team follow my steps to reproduce?

I think forced, unnecessary re-renders on navigation is a pretty important bug.
Maybe no one else in the community has noticed it, since no one tracks individual renders.

**Comment by jeemuu** [comment]
虽然重新渲染多余，但是state并没有变化，状态还可以保存下来，重绘未导致重新创建。
