### ISSUE TITLE
Crashed: com.apple.NSURLSession-work

### ISSUE THREAD

**Issue by Azimus** [facebook/react-native#9847]
### Issue Description

Few days ago we've release our application to AppStore and stared to receive quite a significant amount of crashes on Crashlytic related to:

```
Crashed: com.apple.NSURLSession-work
0  libobjc.A.dylib                0x20c3fa86 objc_msgSend + 5
1  CFNetwork                      0x21ab52b7 -[__NSCFURLSessionTask dealloc] + 270
2  CFNetwork                      0x2198ea95 -[__NSCFLocalSessionTask dealloc] + 424
3  libobjc.A.dylib                0x20c4cf8b objc_object::sidetable_release(bool) + 150
4  CFNetwork                      0x219cfbfb -[__NSCFURLSessionConnection dealloc] + 38
5  CFNetwork                      0x219d03c5 -[__NSCFURLLocalSessionConnection dealloc] + 116
6  libobjc.A.dylib                0x20c4cf8b objc_object::sidetable_release(bool) + 150
7  libdispatch.dylib              0x21007cbf _dispatch_call_block_and_release + 10
8  libdispatch.dylib              0x21019c31 _dispatch_source_cancel_callout + 1752
9  libdispatch.dylib              0x21009bdb _dispatch_source_invoke + 702
10 libdispatch.dylib              0x210119ed _dispatch_queue_drain + 592
11 libdispatch.dylib              0x2100ae17 _dispatch_queue_invoke + 282
12 libdispatch.dylib              0x210136a1 _dispatch_root_queue_drain + 1572
13 libdispatch.dylib              0x2101307b _dispatch_worker_thread3 + 94
14 libsystem_pthread.dylib        0x211a6e0d _pthread_wqthread + 1024
15 libsystem_pthread.dylib        0x211a69fc start_wqthread + 8
```

We was not able to reproduce this issue on our side yet.
It would be great if we cat get at least a hint where is the source of the issue =)
### Additional Information
- React Native version: [0.32]
- Platform(s) (iOS, Android, or both?): [iOS]
- Operating System (macOS, Linux, or Windows?): [Mac]

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/crashed-comapplensurlsession-work

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
