### ISSUE TITLE
RCTHTTPRequestHandler Crash

### ISSUE THREAD

**Issue by barbarNik** [facebook/react-native#9848]
### Issue Description

Few days ago we've release our application to AppStore and stared to receive quite a significant amount of crashes on Crashlytic related to _RCTHTTPRequestHandler_, this is few of the crashes we getting, i can attach more if it is required:

```
Crashed: com.apple.NSURLSession-work
0  libobjc.A.dylib                0x20c3fa86 objc_msgSend + 5
1  CFNetwork                      0x21ab52b7 -[__NSCFURLSessionTask dealloc] + 270
2  CFNetwork                      0x2198ea95 -[__NSCFLocalSessionTask dealloc] + 424
3  libobjc.A.dylib                0x20c4cf8b objc_object::sidetable_release(bool) + 150
4  CFNetwork                      0x219cfbfb -[__NSCFURLSessionConnection dealloc] + 38
5  CFNetwork                      0x219d03c5 -[__NSCFURLLocalSessionConnection dealloc] + 116
6  libobjc.A.dylib                0x20c4cf8b objc_object::sidetable_release(bool) + 150
7  libdispatch.dylib              0x21007cbf _dispatch_call_block_and_release + 10
8  libdispatch.dylib              0x21019c31 _dispatch_source_cancel_callout + 1752
9  libdispatch.dylib              0x21009bdb _dispatch_source_invoke + 702
10 libdispatch.dylib              0x210119ed _dispatch_queue_drain + 592
11 libdispatch.dylib              0x2100ae17 _dispatch_queue_invoke + 282
12 libdispatch.dylib              0x210136a1 _dispatch_root_queue_drain + 1572
13 libdispatch.dylib              0x2101307b _dispatch_worker_thread3 + 94
14 libsystem_pthread.dylib        0x211a6e0d _pthread_wqthread + 1024
15 libsystem_pthread.dylib        0x211a69fc start_wqthread + 8
```

```
Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x182b12db0 __exceptionPreprocess
1  libobjc.A.dylib                0x182177f80 objc_exception_throw
2  CoreFoundation                 0x182b19c4c __methodDescriptionForSelector
3  CoreFoundation                 0x182b16bec ___forwarding___
4  CoreFoundation                 0x182a14c5c _CF_forwarding_prep_0
5  AppMobile                    0x1002bc3e8 -[RCTHTTPRequestHandler URLSession:task:didCompleteWithError:]
6  CFNetwork                      0x183220930 __51-[NSURLSession delegate_task:didCompleteWithError:]_block_invoke170
7  Foundation                     0x1834cc540 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
8  Foundation                     0x18341e870 -[NSBlockOperation main]
9  Foundation                     0x18340ee48 -[__NSOperationInternal _start:]
10 Foundation                     0x1834ce934 __NSOQSchedule_f
11 libdispatch.dylib              0x18255d47c _dispatch_client_callout
12 libdispatch.dylib              0x1825694c0 _dispatch_queue_drain
13 libdispatch.dylib              0x182560f80 _dispatch_queue_invoke
14 libdispatch.dylib              0x18256b390 _dispatch_root_queue_drain
15 libdispatch.dylib              0x18256b0b0 _dispatch_worker_thread3
16 libsystem_pthread.dylib        0x182775470 _pthread_wqthread
17 libsystem_pthread.dylib        0x182775020 start_wqthread
```

We was not able to reproduce this issue on our side yet.
It would be great if we cat get at least a hint where is the source of the issue =)
### Additional Information
- React Native version: [0.32]
- Platform(s) (iOS, Android, or both?): [iOS]
- Operating System (macOS, Linux, or Windows?): [Mac]

**Comment by jreziga** [comment]
Same issue 

```objective-c

- (void)URLSession:(NSURLSession *)session task:(NSURLSessionTask *)task didCompleteWithError:(NSError *)error
{
  [[_delegates objectForKey:task] URLRequest:task didCompleteWithError:error];
  [_delegates removeObjectForKey:task]; // Error here (EXC_BAD_ACCESS)
}

```

**Comment by shawnXiao** [comment]
Same issue on 0.36

**Comment by nmhuang** [comment]
Same issue on me

**Comment by IlyaRepo** [comment]
Same issue on 0.34

**Comment by wulyn** [comment]
Same issue on 0.33

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
