### ISSUE TITLE
iOS tests: allow to customize the root frame size

### ISSUE THREAD

**Issue by gre** [facebook/react-native#9853]
https://github.com/facebook/react-native/blob/master/Libraries/RCTTest/RCTTestRunner.m#L114

this value is hardcoded but I would prefer to have a different size, I would like to have iPhone size for instance.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/ios-tests-allow-to-customize-the-root-frame-size

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
