### ISSUE TITLE
[iOS] secureTextEntry ignores keyboard locale

### ISSUE THREAD

**Issue by Pholey** [facebook/react-native#9866]
### Issue Description

Due to what seems to be an iOS bug (As far as i can find people commenting on it), enabling `secureTextEntry` on `TextInput` causes the keyboard to ignore the user's locale, and instead shows english
### Steps to Reproduce / Code Snippets

https://rnplay.org/apps/21qZ0A

Be sure to go to the settings of the phone and set your main language/keyboard language to something like Japanese, After it is done loading, tap between the inputs to see the difference
#### Expected Results

For the keyboard to use the correct locale with `secureTextEntry`
### Additional Information
- React Native version: 0.31.0
- Platform(s) (iOS, Android, or both?): iOS
- Operating System (macOS, Linux, or Windows?): macOS

Best SO solution i've found for this problem:
http://stackoverflow.com/questions/6828834/selecting-language-of-the-keyboard-for-uitextfield-with-securetextentry

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/ios-securetextentry-ignores-keyboard-locale

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
