### ISSUE TITLE
[PushNotificationIOS] Support react-native link for default libraries

### ISSUE THREAD

**Issue by cmcewen** [facebook/react-native#9897]
@Kureev @grabbou wanted to see what you thought about supporting react-native link for the two default libraries that require linking native code, PushNotificationIOS and Linking. It seems a bit silly to require all the manual normal steps for linking the libraries when you've already built a really solid solution.

Alternatively, it might be worth moving push support out to `react-native-push-notification` - that already has a good cross-platform API

**Comment by lacker** [comment]
I agree, stuff that requires mucking with linking should be using `react-native link`. I think it would be a good idea to move out push notification support - @mkonicek brought this up recently I think. Linking hasn't come up. If you'd like to work on it go for it but let us know! Since we are trying to keep issues focused on bug reports rather than feature requests I am going to close this issue but I support this wholeheartedly
