### ISSUE TITLE
react-native android command disappeared

### ISSUE THREAD

**Issue by dritan-x** [facebook/react-native#9909]
### Issue Description

react-native android command has disappeared from react-native v.0.33 yet react-native run-android asks the dev: "Android project not found. Maybe run react-native android first?"
### Steps to Reproduce / Code Snippets
1. checkout source of RN app
2. react-native upgrade to generate the android & ios folders
3. react-native android to generate the class links (FAILS HERE)
4. react-native run-android to run on device/emulator
#### Expected Results

either have "react-native run-android" automagically perform "react-native android" or bring back the damn command.
### Additional Information
- React Native version: 0.33
- Platform(s) (iOS, Android, or both?): both
- Operating System (macOS, Linux, or Windows?): MacOS

Also I consider this a bug not a feature so I followed instructions on this page and angrily posted a bug on SO http://stackoverflow.com/questions/39499604/react-native-android-command-disappeared

**Comment by lacker** [comment]
Hey, I'm sorry you had such a bad experience here. Upgrading things has been pretty painful for a while - our solution is to encourage community solutions like http://facebook.github.io/react-native/blog/2016/12/05/easier-upgrades.html which is now what I recommend to people upgrading. I'm going to close this issue under the theory that that solves the problem here, and I appreciate your bringing this up and sticking with it and so on. Thanks!
