### ISSUE TITLE
TextInput driven date picker

### ISSUE THREAD

**Issue by ambarc** [facebook/react-native#9928]
We're seeing use cases where we have a date input field and would like a DatePicker to slide up from the bottom. Since React Native currently makes us manually place that date picker to be able to slide from the bottom our code becomes indirect. Here's a suggestion:

<Input type='date'> slides up a date picker on focus, at least on iOS. If the fallback is to present a modal on Android, so be it.

Thoughts appreciated.

**Comment by lacker** [comment]
That sounds like a useful feature for a new component. I think that might be a cleaner way to do things than to just add more features to DatePicker. So I encourage you to build a component like that! Since we are trying to keep these issues focused on bugs I am going to close this issue but thank you for sharing this.
