### ISSUE TITLE
Unable to connect with remote debugger

### ISSUE THREAD

**Issue by hantc** [facebook/react-native#9946]
### Issue Description
App deploys to my nexus 5 correctly, but when I try to reload app, this screen appears: 

![image](https://cloud.githubusercontent.com/assets/11539237/18589823/b5718c70-7c2c-11e6-8296-5a74db8b1a7f.png)

I found the similar issue here - https://github.com/facebook/react-native/issues/6390 - but it was on React Native 0.21

Had someone experienced similar problem?

### Additional Information

* React Native version: 0.33
* Platform(s): Android 6
* Operating System: Windows 10

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of React Native.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #react-native](http://stackoverflow.com/questions/tagged/react-native)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

**Comment by cinder92** [comment]
any update about this? i can not deploy in real device andriod tablet....

**Comment by hanhuizhu** [comment]
unable connet debugger in 0.41.2 with windows&android
