### ISSUE TITLE
Confused of 'rowHasChanged'

### ISSUE THREAD

**Issue by qianjunsteve** [facebook/react-native#9970]
Hi, there is a issue during my developing. 

I use 'AsyncStorage' to render the page firstly, then use the new data. But if the new data just modified a little( rowHasChanged has already return true), the row wasn't re-render. 
eg: `{
		"data": {
			"banner": "AppStore/083df49ad9f51643c4859484b54bf7ae76b426ca1",
			"subjectId": 2303
		}`
       only modi bannerUrl, won't work, but if I replace the whole data item.

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of React Native.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #react-native](http://stackoverflow.com/questions/tagged/react-native)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.
