### ISSUE TITLE
On Windows 10 android SDK- Changing in index.android.js but app not refreshing.

### ISSUE THREAD

**Issue by gauravverma029** [facebook/react-native#9972]
### First Issue when react-native start error is coming
(node:4380) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Watcher took too long to load (NodeWatcher)

###Second issue
When I am changing in index.android.js file and save it.App is not refreshing.

React Native version is - 0.33
Npm version - 3.10.3
node version - 6.6.0
OS - Windows 10 

On First Time app is working fine but when i doing changing in file and doing save app is not refreshing
Please help me out.......

**Comment by stoffern** [comment]
tried: `react-native start --reset-cache` ?
you also need to check "Enable Live Reload" if you are not doing it manually:
https://facebook.github.io/react-native/docs/debugging.html

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of React Native.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #react-native](http://stackoverflow.com/questions/tagged/react-native)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.
