### ISSUE TITLE
Google recaptcha v2 in react-native

### ISSUE THREAD

**Issue by satthu565** [facebook/react-native#9981]
Hi everyone,

How to add google recaptcha v2 in react-native on Android and IOS?

Please help me!

**Comment by satya164** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-4** [comment]
Hey @satthu565 and thanks for posting this! @satya164 tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
