### ISSUE TITLE
Use background session

### ISSUE THREAD

**Issue by jcampbell05** [facebook/react-native#9983]
Is is possible to use background session on iOS with requests ? If not is it easy to add in ?

**Comment by stoffern** [comment]
@jcampbell05 it is fully possible with a plugin. React Native does not support it out of the box.
https://github.com/ocetnik/react-native-background-timer

**Comment by jcampbell05** [comment]
What I mean is to use NSURLSession background requests.

**Comment by stoffern** [comment]
Then you have to code out yourself:)
Why not use fetch in js and save it?

**Comment by jcampbell05** [comment]
@stoffern in this case its for allowying the user to use the action buttons for a notification. We need background requests so iOS accepts it.

In future would be cool with this was transparently used when iOS is in background.

**Comment by Kureev** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-4** [comment]
Hey @jcampbell05 and thanks for posting this! @Kureev tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
