### ISSUE TITLE
Build error after upgrading

### ISSUE THREAD

**Issue by nikolal** [facebook/react-native#9988]
I upgraded Xcode, OSX, React and React Native and I have error:

```

** BUILD FAILED **


The following build commands failed:
	CompileC /Users/nikolalukic/Desktop/sportunity-clean-front/ios/build/Build/Intermediates/RCTWebSocket.build/Debug-iphonesimulator/RCTWebSocket.build/Objects-normal/x86_64/RCTWebSocketModule.o RCTWebSocketModule.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

```

I had several other CompileC error which I solved by upgrading dependencies. I can't find answer to this one.

I am using
```
"react": "^15.3.1-rc.2",    
 "react-native": "^0.34.0-rc.0",
```

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of React Native.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #react-native](http://stackoverflow.com/questions/tagged/react-native)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.
