### ISSUE TITLE
Argument 0 (NSNumber) of RCTNavigatorManager.requestSchedulingJavaScriptNavigation must not be null

### ISSUE THREAD

**Issue by msutyak** [facebook/react-native#9992]
I am using a simple navigator to change views (which was working previously), but after some changes, it is giving me this error:

Argument 0 (NSNumber) of RCTNavigatorManager.requestSchedulingJavaScriptNavigation must not be null

Argument 0 (<null>) of RCTNavigatorManager.requestSchedulingJavaScriptNavigation could not be processed. Aborting method call.

reactConsoleError @ ExceptionsManager.js:75

Clicking the exception takes me to:  
// Flow doesn't like it when you set arbitrary values on a global object
  (console: any)._errorOriginal = console.error.bind(console);

code:

```
          <TouchableHighlight
            style={styles.button}
            onPress={this.testSubmit.bind(this)}
            underlayColor="white">
              <Text style={styles.buttonText}> Test </Text>
          </TouchableHighlight>

  testSubmit(){
    this.props.navigator.push({
      title: "Login Page",
      component: Test,
      passProps: {
      }
    });
  }
```

**Comment by DesignMonkey** [comment]
Same here... updated from 0.24 and to 0.34, and now my navigator don't work no matter what I do.

**Comment by lacker** [comment]
I think we are missing enough information to reproduce this problem. My main suggestion would be to try using react-navigation instead of Navigator; we are probably going to focus our navigation-related energy on other libraries because we don't think Navigator is the ideal API. But more practical might just be to ask this on Stack Overflow because that's a better interface for complex "how to do X" type questions. I am going to close this issue because it seems like its utility is drawing to an end. Hope this helps or that at least you have figured out how to get around this!
