### ISSUE TITLE
Live/Hot reload not working after adding React Native Map plugin

### ISSUE THREAD

**Issue by madhanapk** [facebook/react-native#9995]
These are my dependencies

"version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
	"native-base": "^0.5.4",
    "react": "15.3.1",
    "react-native": "0.32.0",
	"react-native-drawer": "^2.2.6",
    "react-native-easy-grid": "^0.1.6",
    "react-native-maps": "^0.8.0",
    "react-timer-mixin": "^0.13.3",
    "rn-viewpager": "^1.1.3",
	"color":"0.11.3",
	"underscore":"1.8.3",
	"fbemitter":"2.0.2",
	"react-native-button":"1.6.0"
  }

It was working fine before the installation of "react-native-maps": "^0.8.0"

Any ideas...

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of React Native.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #react-native](http://stackoverflow.com/questions/tagged/react-native)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.
