### ISSUE TITLE
cannot find entry file index.ios.js in any of the roots 

### ISSUE THREAD

**Issue by 274793580** [facebook/react-native#9998]
### Issue Description

cannot find entry file index.ios.js in any of the roots

### Steps to Reproduce / Code Snippets
`
react-native init
`
`
rm -rf   node_modules
`
`
npm install
`
`
npm install --save redux
`
`
npm install --save react-redux
`
`
react-native run-ios 
`
then has the error cannot find entry file index.ios.js in any of the roots [...react-native/0.33.0/react-native ]
`
"dependencies": {
    "react": "15.3.2",
    "react-native": "0.33.0",
    "react-redux": "^4.4.5",
    "redux": "^3.6.0"
  }
`

### Additional Information

* React Native version: [0.33]
* Platform(s) (iOS, Android, or both?): [iOS version 10.0]
* Operating System (macOS, Linux, or Windows?): [macOS]

**Comment by 274793580** [comment]
if that not install redux and react-redux .it's ok.

**Comment by 274793580** [comment]
that command  can be ignored。

**Comment by 274793580** [comment]
Mainly the following commands

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of React Native.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #react-native](http://stackoverflow.com/questions/tagged/react-native)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.
