### ISSUE TITLE
Is there a hook to catch redbox error and exit the app elegantly?

### ISSUE THREAD

**Issue by narychen** [facebook/react-native#9999]
When an redbox error happens, app usually stop responding to touches or behave weirdly.
This is much worse than the app crash because a release version won't show a redbox and users don't know what happened and why the app stop responding. They will delete your app if they cannot do anything with it.
You cannot be sure there is no bug in your app. So when it happens, we should make sure our users could be forced to restart the app or they will fail to use it.

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of React Native.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #react-native](http://stackoverflow.com/questions/tagged/react-native)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

**Comment by narychen** [comment]
Ok. I posted it on stackoverflow http://stackoverflow.com/questions/39606035/is-there-a-way-to-catch-the-react-native-redbox-error
